### ISSUE TITLE
Vanish

### ISSUE THREAD

**Issue by zRiaz** [EssentialsX/Essentials#100]
Could you make VanishNoPacket were your hand is still visible for yourself even when being vanished?

**Comment by zRiaz** [comment]
Sry on my phone 'make IT like vanishnopacket'

**Comment by EvilOlaf** [comment]
Why don't just use VNP?

**Comment by zRiaz** [comment]
Because if they implement that here, using VanishNoPacket seems useless to me, the only other difference is the effects etc.

I just find being completely invisible annoying and would like to see this implemented in Essentials.

**Comment by EvilOlaf** [comment]
As for me I don't see a reason to implement this into essentialsX as VNP works well. 
there is no need to overload essentialX with features. 

The only valid argument I see is that VNP is actually not supported by mbaxter when using with spigot CB/SPIGOT 1.8 or higher. As written above it works well though.

**Comment by zRiaz** [comment]
I wouldnt call making yourself visible when vanished "overloading essentialsx with festures" more like a fix/very small feature.
And using VNP just for that small feature when Essentials can fix it easy is pretty useless.

**Comment by EvilOlaf** [comment]
That were just my two cents.
Lets see what @drtshock thinks about :)

**Comment by Elgorond** [comment]
I'd love to have a better/fixed Essentials vanish, instead of having to add VanishNoPacket with multiple negated effects permissions.

**Comment by drtshock** [comment]
@mbax

**Comment by mbax** [comment]
You don't have to negate any permissions. Default VNP perms are fuck-all unless you're an OP in which case you can see people who are invisible and get information about them.

All the effects stuff is 100% disabled by default.

While I don't support VNP on anything but Bukkit, people running DMCA-violating forks would have to try pretty damn hard to break my code :3

**Comment by drtshock** [comment]
Teaches you not to use \* permission incorrectly!
