### ISSUE TITLE
essentials.ban.notify will show IGN ban but not IP ban

### ISSUE THREAD

**Issue by dwilley83** [EssentialsX/Essentials#1004]
One of my moderators tried to IP ban a troll and the notification would not show in the chat. We had banned the same person when they used a different account and the IGN ban notified the staff but the IP ban did not. The Essentials perms list shows essentials.banip to ban IPs and essentials.ban to ban IGNs but essentials.ban.notify is listed as notifying those groups with that permission as notifying for both IGN and IP bans.

Running EssentialsX 2.0.1 on Spigot 1.11.

**Comment by mdcfe** [comment]
Have you updated to [the latest build](https://ci.drtshock.net/job/EssentialsX/lastSuccessfulBuild)?

**Comment by dwilley83** [comment]
Essentials 2.0.1-b450

Also running latest Spigot version.

**Comment by mdcfe** [comment]
You need `essentials.banip.notify` for IP ban notifications.

**Comment by dwilley83** [comment]
Ok. I thought maybe that was the case but on the Essentials list it lists essentials.ban.notify to be for IP bans and IGN bans. I will try this, thank you.

**Comment by mdcfe** [comment]
Closing due to lack of response; the issue also appears to be resolved. If this is still a problem, however, feel free to reopen the issue.
