### ISSUE TITLE
Unable to craft piston and redstone torches in latest build

### ISSUE THREAD

**Issue by melinstagibson** [EssentialsX/Essentials#1005]
Im unable to craft pistons and RS torches (maybe more things) in #453. i downgraded and it worked again

**Comment by mdcfe** [comment]
Which version did you downgrade to?

**Comment by melinstagibson** [comment]
using b446 now because thats the one i had on my system anyways

**Comment by SupaHam** [comment]
I'm unable to reproduce this issue. Please pastebin your server log using b453.

**Comment by melinstagibson** [comment]
sorry, this was caused by another plugin which actually broke it with the delay of one restart so i thought it was the updated essX files i restarted for

really sorry to cause you work by being stupid
