### ISSUE TITLE
Homes

### ISSUE THREAD

**Issue by HaNiTLG** [EssentialsX/Essentials#1007]
Hey!
I have a problem. Sometimes the homes will deteled from the players automatically... Why? :o

Information
Spigot: 1.8.8
EssentialsX: 2.0.1 - b370

**Comment by HaNiTLG** [comment]
There isn't any error in the console. :)

**Comment by mdcfe** [comment]
Could you try updating to build 439 on the [CI](https://ci.drtshock.net/job/EssentialsX/)?

**Comment by HaNiTLG** [comment]
And what is with the Build 453? :o

**Comment by mdcfe** [comment]
Build 453 has somewhat limited support for versions prior to 1.11 if I recall correctly.

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to reopen the issue.
