### ISSUE TITLE
/give issue with spawn_egg in latest version of Spigot

### ISSUE THREAD

**Issue by DramasticStar** [EssentialsX/Essentials#1009]
I'm using the command in a command block
`/give @p[lm=10] spawn_egg 1 0 {EntityTag:{id:minecraft:pig}}`
but it is failing to execute.

It has been duplicated by another person and verified that EssentialsX is the conflicting jar. 

Running Spigot on MC 1.11

**Comment by mdcfe** [comment]
Use the `minecraft:` prefix in the command block or the `command-block-overrides` option in the Spigot config. This is not an EssentialsX issue.

**Comment by DramasticStar** [comment]
But I did use the Minecraft: prefix. Is there another location that I should be using the prefix other than in the entity tag?

**Comment by mdcfe** [comment]
~~If you used the `minecraft:` prefix, then EssentialsX isn't even related. How do you know the command failed? What is the output in the command block's output box?~~

You need to prefix the give command, like this: `minecraft:give`.

**Comment by DramasticStar** [comment]
I was concerned it was an EssentialsX problem because the command works in vanilla MC but didn't work with only EssentialsX installed, which is how we came to the conclusion. It wasn't giving the egg and listed error in the previous output box. 

But I'll try adding minecraft:give once I'm back on my computer in the morning. Thanks. 

This worked. Thank you!
