### ISSUE TITLE
Tpa accept

### ISSUE THREAD

**Issue by AmazedMender16** [EssentialsX/Essentials#1010]
http://prntscr.com/dh22dz

after getting a request and then accepting it its givign the error you see in the screenshot

**Comment by Kakifrucht** [comment]
Which version are you using? (Type */ess ver*)

**Comment by AmazedMender16** [comment]
2.0.1-b453 


Having world teleport permissions on true
And working with the permisison node but keeps saying players dont have permissions to anything either teleport or /back

**Comment by mdcfe** [comment]
If this is still an issue, could you run `/ess debug` and paste the console output when this issue occurs?

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to respond and reopen the issue.
