### ISSUE TITLE
Economy MultiWorld Support

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1011]
Edit: drtshock told me I need to "make your case for why we should add it and how it can apply to other cases and not *just* yours" so here it is:

I'm looking to set up multiple worlds on a single server that each have a separate economy. PerWorldInventories has the ability to split up the balances per world, however there are a few loopholes that allow players to transfer money between worlds. Its not a perfect solution.

Currently, /pay allows players to transfer money between two different worlds. There is also no way to have different prices per world for /worth or /sell. Finally, when admins attempt to modify a players balance they must have the player stand in the world they want to modify it for, otherwise they could alter the wrong balance.

Basically, any economy command in Essentials has no support for mutli-world setups and the current solutions are very limited. Mutli-world support for economies have been an issue for years, now. A very large portion of the servers that are not running BungeeCord have a multi-world setup. This is clearly seen on MCStats. As of writing this, of the 76,392 servers running Spigot, 24,886 are running Multiverse-Core. Yet there is only one actively managed economy plugin that supports multiple worlds, and that plugin is still in alpha.

Essentials has long been the standard base plugin for economy servers. It has been around for many years and is clearly the standard for most servers, with 56,449 servers currently running Essentials or EssentialsX. Thats 73% of all Spigot servers. Also, through my year and a half of using EssentialsX I've seen many of Essential's features vastly improved by it. Its become clear to me that EssentialsX is not only a continuation of Essentials, but a polished version with new features and improvements on the current ones.

I think that multi-world support for economy is long over-due and something that should definitely be built into Essentials, and EssentialsX is the exact project that I would expect to take on something like this. Economy stands as the only thing that does not have mutli-world support. We've come up with solutions for inventories, exp, permissions, even entire plugins, but not economy.

**Comment by mdcfe** [comment]
As an additional note to your statistics: not every Bukkit server runs Spigot. Many use Thermos and some also use CraftBukkit.

**Comment by drtshock** [comment]
I'm not sure I agree with full multiworld support for economy. But I could get behind having essentials.pay.receive as a permission so that you could negate it in a world where you don't want players to receive money, which is what I thought your message was about :)

**Comment by smrkn** [comment]
Probably not probable

**Comment by ghost** [comment]
@drtshock Yes, I suppose that is an option as well. I thought I might as well try for the full multi-world support first, though!

I'm currently having an issue where players' balances are randomly going up by 2,000 to 300,000 $. Someone will have $1000 one day and come back the very next with $300,000. I haven't done any testing yet to figure out why, but I do know for certain that nobody is using the /eco command and nothing on the server could possibly cause that to happen.

I'm bringing this up because it could be related to PerWorldInventories, which would mean what I thought would be a solution would no longer work.

I'm really surprised, actually, that you haven't added multi-world support for economy yet. Is there any reason why? I would think that would be a very basic thing to add considering how popular multi-world setups are.

**Comment by mdcfe** [comment]
Bumping an old issue, but yes, there are many reasons for why there is no multiworld support in EssentialsEco:
* It would require changes to how balances are stored.
* We'd need to decide whether the player's balances in each world are attached to separate economy accounts or one account whose balance is swapped when the player swapped worlds.
* It may require breaking changes to the Essentials API.
* We'd need to decide how Vault and other plugins would integrate with the new economy system.

**Comment by pop4959** [comment]
This is probably best left for multi-world plugins to deal with.
