### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1012]
logs
https://gist.github.com/mat41997/6045148c8cf4f780f7023d49c35a11ce
timings
https://timings.aikar.co/v2/?id=d5de74a804d4407dada5fab8642a77b8

**Comment by mdcfe** [comment]
Could you try running the server without ProtocolSupport?

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to open a new issue.
