### ISSUE TITLE
Towny issue with Essentials API

### ISSUE THREAD

**Issue by BlueSoapTurtle** [EssentialsX/Essentials#1013]
Running essentials v 2.0.1-b450
getting this error whenever towny runs a new day
http://hastebin.com/caqejuyahe.yaml

line marked with "<---- 1000x" appears 1,000 times but I removed the duplicate ones.

was going to post this on towny's issue  tracker but it looked like it was related to Essentials.

**Comment by mdcfe** [comment]
Looks like sort of issue loading user data. What permissions do you have set on your usermap and EssentialsX user files?

**Comment by BlueSoapTurtle** [comment]
660 on the usermap
660 on some user files and 770 on some other user files
(don't know why they're different)

**Comment by BlueSoapTurtle** [comment]
i tried chmod'ing all essentials files to 770 and it still didn't work.

**Comment by mdcfe** [comment]
Does this still happen after a restart?

**Comment by BlueSoapTurtle** [comment]
Yup, just restarted and no change.

**Comment by BlueSoapTurtle** [comment]
Still an issue

**Comment by mdcfe** [comment]
If this is still an issue, could you paste a new log?

**Comment by BlueSoapTurtle** [comment]
Nope, can't remember how we solved it, think updating towny and essentials after a while worked.
