### ISSUE TITLE
/recipe shows almost nothing

### ISSUE THREAD

**Issue by aurel85** [EssentialsX/Essentials#1016]
Hey,

Since the passage in 1.11 the /recipe shows almost no craft for all the players.
There is no error in the console.
I use the version Essentials-2.x-SNAPSHOT (# 15) of the plugin and I currently use Paper Spigot 1.11 (# 960).

**Comment by mdcfe** [comment]
Are you sure you're using build 15 of EssentialsX? If you're not sure which build you're using, get the latest build from [here](https://ci.drtshock.net/job/EssentialsX/lastSuccessfulBuild).

**Comment by aurel85** [comment]
Oh sorry I'm tangled in versions of Essentials and EssentialsX. Everything works, thank you.
