### ISSUE TITLE
`notify-no-new-mail` does not appear in config after migrating to EssentialsX

### ISSUE THREAD

**Issue by RoyCurtis** [EssentialsX/Essentials#102]
After migrating from Spigot-Essentials [build 12](https://hub.spigotmc.org/jenkins/job/Spigot-Essentials/12/) to [EssentialsX build 176](https://ci.drtshock.net/job/EssentialsX/176/), I had wanted to disable the `No new mail` notification as [advertised on the wiki](https://github.com/drtshock/Essentials/wiki). However, I could not find such a setting in our _existing_ `config.yml` file, even after executing `/ess reload`.
## Workarounds

After searching the issue tracker, I [found](https://github.com/drtshock/Essentials/commit/f5b40dba347e856f5d9708e20437fb3f5b2609a5) the config option in question: `notify-no-new-mail`. Manually adding this to our config file and reloading disabled the mail notification on login, as expected.
## Suggestions

I propose having missing config options saved, with their defaults, to the config file after executing `/ess reload`, so that those migrating from Spigot-Essentials to EssentialsX  or upgrading may more easily find new settings.
## Notes

Unrelated, but thank you for working on EssentialsX. I very much appreciate the continued maintenance and development of a vital plugin to the server ecosystem. The ability to disable the mail notification easily tops one of my favorite features.

**Comment by Agazed** [comment]
Upgrading doesn't add the new options to the config, you have to add them or regenerate yourself.

But since this resource is constantly being updated I would really like this feature.

**Comment by Terrobility** [comment]
+1 on this idea.

**Comment by drtshock** [comment]
I can add a wiki page with new options but adding them to the config will delete comments which I will not do.

**Comment by RoyCurtis** [comment]
Understood; thank you for the response!
