### ISSUE TITLE
Building EssentialsX fails, trying to build GroupManager

### ISSUE THREAD

**Issue by SurtursRevenge** [EssentialsX/Essentials#1020]
HI everyone,

at the moment i am trying to biuld ExxentialsX from git source but it is failing.
I have done these exact steps 

git clone ...
java -jar BuildTools.jar --rev 1.8
java -jar BuildTools.jar --rev 1.8.3
java -jar BuildTools.jar --rev 1.9
java -jar BuildTools.jar --rev 1.9.4
mvn clean install

I changed the pom.xml back to bukkit 1.10-R0.1-SNAPSHOT and also copyed the spigot 1.10 jar file into the lib folder named bukkit.jar

It is failing with these errors :

`[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ EssentialsX ---
[INFO] Compiling 306 source files to ...GitHub/EssentialsX/Essentials/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/craftbukkit/FakeWorld.java:[597,58] error: cannot find symbol
[ERROR]  class FakeWorld
...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/craftbukkit/FakeWorld.java:[602,55] error: cannot find symbol
[ERROR]  class FakeWorld
...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[835,38] error: cannot find symbol
[ERROR]  class OfflinePlayer
...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1157,58] error: cannot find symbol
[ERROR]  class OfflinePlayer
...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1162,55] error: cannot find symbol
[ERROR]  class OfflinePlayer
...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1175,39] error: cannot find symbol
[ERROR]  class OfflinePlayer
...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1180,36] error: cannot find symbol
[ERROR]  class OfflinePlayer
...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/craftbukkit/FakeWorld.java:[597,58] error: cannot find symbol
[ERROR]  class FakeWorld
...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/craftbukkit/FakeWorld.java:[602,55] error: cannot find symbol
[ERROR]  class FakeWorld
...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[835,38] error: cannot find symbol
[ERROR]  class OfflinePlayer
...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1157,58] error: cannot find symbol
[ERROR]  class OfflinePlayer
...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1162,55] error: cannot find symbol
[ERROR]  class OfflinePlayer
...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1175,39] error: cannot find symbol
[ERROR]  class OfflinePlayer
...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1180,36] error: cannot find symbol
[ERROR]  class OfflinePlayer
...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/craftbukkit/FakeWorld.java:[341,4] error: method does not override or implement a method from a supertype
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/craftbukkit/FakeWorld.java:[596,4] error: method does not override or implement a method from a supertype
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/craftbukkit/FakeWorld.java:[601,4] error: method does not override or implement a method from a supertype
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[772,4] error: method does not override or implement a method from a supertype
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[897,4] error: method does not override or implement a method from a supertype
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1065,4] error: method does not override or implement a method from a supertype
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1070,4] error: method does not override or implement a method from a supertype
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1075,4] error: method does not override or implement a method from a supertype
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1080,4] error: method does not override or implement a method from a supertype
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1085,4] error: method does not override or implement a method from a supertype
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1156,4] error: method does not override or implement a method from a supertype
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1161,4] error: method does not override or implement a method from a supertype
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1174,4] error: method does not override or implement a method from a supertype
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1179,4] error: method does not override or implement a method from a supertype
[INFO] 28 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] EssentialsXParent ................................. SUCCESS [2.694s]
[INFO] NMSProvider ....................................... SUCCESS [2.252s]
[INFO] UpdatedMetaProvider ............................... SUCCESS [0.668s]
[INFO] 1_8_R1Provider .................................... SUCCESS [0.735s]
[INFO] 1_8_R2Provider .................................... SUCCESS [0.999s]
[INFO] LegacyProvider .................................... SUCCESS [0.813s]
[INFO] ReflectionProvider ................................ SUCCESS [1.213s]
[INFO] EssentialsX ....................................... FAILURE [15.680s]
[INFO] EssentialsXAntiBuild .............................. SKIPPED
[INFO] EssentialsXChat ................................... SKIPPED
[INFO] EssentialsXGeoIP .................................. SKIPPED
[INFO] EssentialsXProtect ................................ SKIPPED
[INFO] EssentialsXSpawn .................................. SKIPPED
[INFO] EssentialsXXMPP ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 25.492s
[INFO] Finished at: Mon Dec 12 01:48:31 CET 2016
[INFO] Final Memory: 31M/387M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project EssentialsX: Compilation failure: Compilation failure:
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/craftbukkit/FakeWorld.java:[597,58] error: cannot find symbol
[ERROR] class FakeWorld
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/craftbukkit/FakeWorld.java:[602,55] error: cannot find symbol
[ERROR] class FakeWorld
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[835,38] error: cannot find symbol
[ERROR] class OfflinePlayer
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1157,58] error: cannot find symbol
[ERROR] class OfflinePlayer
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1162,55] error: cannot find symbol
[ERROR] class OfflinePlayer
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1175,39] error: cannot find symbol
[ERROR] class OfflinePlayer
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1180,36] error: cannot find symbol
[ERROR] class OfflinePlayer
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/craftbukkit/FakeWorld.java:[597,58] error: cannot find symbol
[ERROR] class FakeWorld
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/craftbukkit/FakeWorld.java:[602,55] error: cannot find symbol
[ERROR] class FakeWorld
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[835,38] error: cannot find symbol
[ERROR] class OfflinePlayer
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1157,58] error: cannot find symbol
[ERROR] class OfflinePlayer
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1162,55] error: cannot find symbol
[ERROR] class OfflinePlayer
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1175,39] error: cannot find symbol
[ERROR] class OfflinePlayer
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1180,36] error: cannot find symbol
[ERROR] class OfflinePlayer
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/craftbukkit/FakeWorld.java:[341,4] error: method does not override or implement a method from a supertype
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/craftbukkit/FakeWorld.java:[596,4] error: method does not override or implement a method from a supertype
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/craftbukkit/FakeWorld.java:[601,4] error: method does not override or implement a method from a supertype
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[772,4] error: method does not override or implement a method from a supertype
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[897,4] error: method does not override or implement a method from a supertype
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1065,4] error: method does not override or implement a method from a supertype
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1070,4] error: method does not override or implement a method from a supertype
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1075,4] error: method does not override or implement a method from a supertype
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1080,4] error: method does not override or implement a method from a supertype
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1085,4] error: method does not override or implement a method from a supertype
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1156,4] error: method does not override or implement a method from a supertype
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1161,4] error: method does not override or implement a method from a supertype
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1174,4] error: method does not override or implement a method from a supertype
[ERROR] ...GitHub/EssentialsX/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[1179,4] error: method does not override or implement a method from a supertype
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :EssentialsX

`

I am fairly experienced with programming, but am new to building with maven an java ...
My question is what am i dooing wrong ???

My goal is to build Essentials GroupManager for spigot 1.10, as i really need it for some Servers i am running. 
But to build GroupManager i need to get EssentialsX first builded, as it is an dependency to build GroupManager

Thank you for any sugesstion

**Comment by mdcfe** [comment]
Don't use GroupManager. It is not supported.

**Comment by SurtursRevenge** [comment]
I know it is not supported, so i am trying to build in on my own, because i need it !
I already updated the GroupManager code. I just need to build it.

But here my question is how to compile EssentialsX from Source, as this is the base i need.
So can anyone help me building the EssentialsX from git source ?

**Comment by mdcfe** [comment]
Wait for #1015 to be merged, then try again.

**Comment by Fonzee9** [comment]
https://www.spigotmc.org/resources/groupmanager-revived.28389/

**Comment by mdcfe** [comment]
@Fonzee9 Not relevant here, GM itself has nothing to do with the problem.

@SurtursRevenge Essentials now builds properly, so you can try again now.

**Comment by boredhero** [comment]
Why did you guys stop supporting GM anyway. I still use it because Pex is atrocious

**Comment by vemacs** [comment]
@boredherobrine13 We never supported it in the first place, so how could we stop

**Comment by boredhero** [comment]
@vemacs Sorry, different team now. Allow me to rephrase properly.

Why wasn't it supported when Essentials X started? It's superior to literally every other permissions plugin. Is it just a lack of dev interest in maintaining it?

**Comment by vemacs** [comment]
@boredherobrine13 The codebase is even worse than that of PEX 1.x. None of us run it, and as you said, dev time is limited.

**Comment by boredhero** [comment]
@vemacs Okay, thanks. I don't do much coding but maybe sometime in the future I'll play with it. Is it actually a part of essentials or can it be seperated and built on its own?

**Comment by mdcfe** [comment]
@boredherobrine13 @SurtursRevenge is trying to build a usable version.
