### ISSUE TITLE
/balance & baltop are wrong

### ISSUE THREAD

**Issue by MrArcane** [EssentialsX/Essentials#1023]
Baltop shows alot more than the player has...

**Comment by MrArcane** [comment]
Player-save seems to be broken actually.. /seen on a player that plays does not work

**Comment by mdcfe** [comment]
What version of EssentialsX are you running and on what version of Spigot?

**Comment by MrArcane** [comment]
Essentials 2.0.1-b455
Spigot: git-Spigot-f950f8e-7e02867

**Comment by SupaHam** [comment]
`/baltop` caches the results for 2 minutes.

This means when you type `/baltop` Essentials will display the results after it calculates it, but to stop your server from lagging behind it will only do calculations again after 2 minutes. So if a player balance drops to 0, their balance will update in `/baltop` after 2 minutes.

`/balance` is displaying my balance as it changes without any issues.
