### ISSUE TITLE
Idea Request: Update Notifications

### ISSUE THREAD

**Issue by DalesMC** [EssentialsX/Essentials#1024]
Hi, could you have it so it notifys pepole with the permission that there is an update and click this link to update it
Thanks

**Comment by mdcfe** [comment]
I don't see the point of this; personally, I prefer to stay on the same build of Essentials for stability unless a feature has been added or a bug has been fixed. If you want to update, just check the build server for a new version.

**Comment by mdcfe** [comment]
This is unlikely to happen, at least not until #1873 has been merged.

**Comment by mdcfe** [comment]
Bumping again. This could be done, but we'd want to make sure that the update notifications only appear if the user is using an "official" build (one built directly from the `2.x` branch of this repo).

**Comment by pop4959** [comment]
I personally don't see much of a point to this -- seems like a redundant thing when you could just bookmark EssentialsX and check for updates yourself. For most people this is something annoying, so definitely permission and config based if at all. Automatic downloading would not be possible though, as I believe Spigot has a policy against it.

Closing, but leaving open to pr tag just in case.
