### ISSUE TITLE
Suggestion for /condense

### ISSUE THREAD

**Issue by SwiftSwamp** [EssentialsX/Essentials#1027]
* Add Quartz to the /condense command
* Add a new alias, /block

**Comment by mdcfe** [comment]
`/block` doesn't nake sense as an alias, and you can add aliases yourself using commands.yml.

**Comment by Taybosquee** [comment]
It's missing x9 bonemeal->bone block as well as 4x quartz->uartz block.

**Comment by mdcfe** [comment]
EssentialsX uses the server's recipe list to see if they can be condensed, not its own predefined list, so we can't add manual support for different items. If there isn't a vanilla recipe (or custom server recipe) for it, it shouldn't be condensed by EssentialsX.
