### ISSUE TITLE
SUGGESTION | Support of 3rd-party plugin's economy system

### ISSUE THREAD

**Issue by Lammendam** [EssentialsX/Essentials#1029]
Hello, can you claim economy system support of other economy plugins to essentials via Vault? I want to use Essentials command cost but not want to use Essentials Economy. For example, I want to use Gringotts economy system for Essentials commands.

**Comment by mdcfe** [comment]
I don't know how feasible this would be without making Vault a requirement. It's definitely possible, but is it worth doing?

**Comment by Lammendam** [comment]
Sure that would be nice optional feature. But... I do not force you to do that. It's just a suggestion. To do or not to do - its your opinion.
I think that Essentials always lacked this feature.

**Comment by Lammendam** [comment]
So what yo decided to do?
Can yo implement this support for EssentialsX?
I can donate you for this work  :)

**Comment by mdcfe** [comment]
I don't see why the commands from other plugins aren't sufficient, and why relying on one plugin to manage another plugin's economy is a good idea?

**Comment by Lammendam** [comment]
Emm.. As I said above: I want to give players ability to use ESSENTIALS commands not for free - using currency of other economy system plugin. When I specify command cost for /spawn - money won't widthrawed from player's account, even if he don't have any money.
Also it refers to Essentials signs.
Vault is already claimed to Essentials, only left to do - connect Ess to Vault in relation to economy.

**Comment by mdcfe** [comment]
This should already work, as all user economy operations first check with Register for valid alternate payment methods (including any Vault economy plugins) before charging the user in Essentials.

Could you confirm whether this happens or not?

**Comment by pop4959** [comment]
Closing since there is no response, but as far as I know Essentials does not take priority over other plugins' economies.
