### ISSUE TITLE
Spigot 1.11

### ISSUE THREAD

**Issue by ArchieIrving** [EssentialsX/Essentials#1030]
Hey, when are you guys going to release on Spigot a version that supports Minecraft 1.11?
There are a few things broke, such as /suicide and /kill.

**Comment by Lammendam** [comment]
Don't you look at Jenkins repository for updates?
Latest build works fine with 1.11.

**Comment by mdcfe** [comment]
[Build server](https://ci.drtshock.net/job/EssentialsX/)

**Comment by ArchieIrving** [comment]
Okay thanks.
You should think about releasing it on Spigot too.
