### ISSUE TITLE
Kit issue

### ISSUE THREAD

**Issue by BehnH** [EssentialsX/Essentials#1031]
Hi,

I'm having an issue with my kit config.
Upon reloading essentials (/ess reload) I get an issue (http://pastebin.com/6kFCgGZq) with my kit config
The affected section is `  Count:
    delay: 259200
    items:
      - 267 1 damage_all:1 name:&5Count Kit`

Help is appreciated

**Comment by mdcfe** [comment]
If this is still an issue, could you paste the log output when reloading Essentials?

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to respond and reopen the issue.
