### ISSUE TITLE
AFK players appear... odd.

### ISSUE THREAD

**Issue by MayorMike** [EssentialsX/Essentials#1033]
AFK players have an odd look for their player name. Nothing appears in the console, but here's my config in case it's a config issue and a screen shot of it in action.

Config: http://pastebin.com/4Kepz9ja

![2016-12-22_15 29 15](https://cloud.githubusercontent.com/assets/5709976/21437767/269cfc88-c85c-11e6-80bc-89afce0051cc.png)

**Comment by mdcfe** [comment]
What version are you running? Are there any symbols in the username?

**Comment by MayorMike** [comment]
2.0.1-b446 is what I get when I run /ess reload

The username is nothing special. It does it with all players who go AFK. But for reference, it's Teethdude.

**Comment by mdcfe** [comment]
Could you try updating your version of EssentialsX? Also, what server software are you using?

**Comment by MayorMike** [comment]
Redownloaded the EssentialsX jar, and it's still like above. Using Spigot. I'm two builds behind. 
I even tried adding EssentialsXChat, but it didn't fix it either. 

Spigot Version: This server is running CraftBukkit version git-Spigot-7d78b81-a867313 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**Comment by mdcfe** [comment]
Try surrounding the value of afk-list-name in quotes (`afk-list-name: "{USERNAME}"`).

**Comment by MayorMike** [comment]
Surrounding it in quotes worked. For whatever reason they either weren't there by default or I deleted them. Thanks for your help.
