### ISSUE TITLE
/payon payoff toggle and confirm on, off, toggle

### ISSUE THREAD

**Issue by saturnux** [EssentialsX/Essentials#1036]
operator has the acces on this new cool feature, but player cant access this.

> [12:29:11] [Server thread/INFO]: gultch issued server command: /payoff
> [12:29:11] [Server thread/INFO]: L'accès à la commande a été refusé pour gultch.

> [12:28:53] [Server thread/INFO]: Lopoju issued server command: /payconfirmtoggle
> [12:28:53] [Server thread/INFO]: L'accès à la commande a été refusé pour Lopoju.

thanks for all

**Comment by Sikatsu** [comment]
Same, can't seem to find the perm.

**Comment by Sikatsu** [comment]
essentials.paytoggle
essentials.payconfirmtoggle

**Comment by saturnux** [comment]
many thanks

**Comment by SupaHam** [comment]
Sorry.

As always, any command belonging to essentials will be `essentials.<command>` where <command> is the name of the command. This should not be confused with command aliases. In this case the command aliases are `payon`, `payconfirmon`, etc. So you need to find the actual command name (As listed in the wikis) and add the permission for it. So as Sikatsu said, `essentials.paytoggle` for `payon`/`/payoff` and `essentials.payconfirmtoggle` for `/payconfirmon`/`/payconfirmoff`
