### ISSUE TITLE
/recipe spawnegg

### ISSUE THREAD

**Issue by YellowZaki** [EssentialsX/Essentials#1037]
I have custom craftings in my server (like spawn eggs).
I used to use /recipe 383:120 for example to see the crafting but now essentials doesn't allow it. If I use /recipe 383:103 /recipe 383:102, etc, it shows all the time the same crafting, the metadata doesn't affect.

**Comment by mdcfe** [comment]
What version of EssentialsX and Spigot are you running?

**Comment by YellowZaki** [comment]
I'm using the latest build of essentialsX.
And paperspigot 1.11.2 (the latest build)

**Comment by YellowZaki** [comment]
Bump

**Comment by pop4959** [comment]
Closing this issue since numeric IDs are no longer accepted by the game, so each item is actually fully unique now. This should not be an issue anymore as a result.
