### ISSUE TITLE
Auto-afk kick question

### ISSUE THREAD

**Issue by Sikatsu** [EssentialsX/Essentials#1038]
How am I able to remove the long afk kick message?

As shown here: http://prntscr.com/dofn63

I don't think everyone needs to know the player has been kicked for that?

**Comment by SupaHam** [comment]
https://github.com/drtshock/Essentials/wiki#afk-message

**Comment by Sikatsu** [comment]
@SupaHam 

This explains about the afk message /afk -text- but doesn't tell me how to hide the global kick message when a player gets kicked for AFK?

**Comment by Sikatsu** [comment]
Just wondering, are the notifications gone after closing an issue or didn't you have time yet? :P

**Comment by mdcfe** [comment]
@Sikatsu Not automatically, but you can unsubscribe.

**Comment by Sikatsu** [comment]
Alright, yeah still hoping for a reply actually

Op za 31 dec. 2016 11:28 schreef md678685 <notifications@github.com>:

**Comment by mdcfe** [comment]
I think the only way to disable this is to remove the message for kick notifications. I don't think there is a specific message for AFK kicks.

**Comment by Sikatsu** [comment]
How do you mean exactly?

Op za 31 dec. 2016 13:10 schreef md678685 <notifications@github.com>:

**Comment by mdcfe** [comment]
Remove the permission `essentials.kick.notify` or set the message to blank in `messages_xx.properties`.
