### ISSUE TITLE
SUGGESTION: Tab List Order System

### ISSUE THREAD

**Issue by ygtdmn** [EssentialsX/Essentials#1039]
Can you make a order system for tab list? Here my current tab list:
http://prntscr.com/dojbjt

It seems so messy. If you can make a order system that orders players with their rank weights it will be great.

**Comment by ygtdmn** [comment]
Bump @drtshock

**Comment by mdcfe** [comment]
EssX still doesn't alter the tab list aside from afk, prefixes and suffixes to my knowledge. The provided screenshot doesn't appear to be related to EssentialsX.

**Comment by ygtdmn** [comment]
The tab list changed when i update from Classic Essentials to EssentialsX. It gets prefixes from zPermissions.

**Comment by mdcfe** [comment]
EssX doesn't have tab list headers or footers. Nor does it currently manipulate the order in the tab list - this has been suggested before and has not yet been implemented, and I think different people will have different opinions on the sorting if it were to be added.

**Comment by ygtdmn** [comment]
Yeah tab list and tab footers are from another plugin. But prefixes getting from permission plugin as i said before. Permission plugins usually have group weight option. Essentials can use it and different people can edit weight as they wish too.

**Comment by mdcfe** [comment]
I'm still not convinced that this belongs in EssentialsX over a dedicated tab list plugin.

**Comment by ygtdmn** [comment]
Then maybe you can add an option to disable showing prefixes in TAB list. Because currently it is so messy. Here a screenshot with more players:
http://prntscr.com/ipbupw

But i still think ordering TAB list will be best.

**Comment by mdcfe** [comment]
Uncomment [`change-playerlist`](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/config.yml#L44) and set it to false to disable EssentialsX's playerlist interaction.

**Comment by pop4959** [comment]
This is not possible to implement currently in vanilla without using a very hacky implementation -- this involves creating "teams" with lexicographical ordering such that players in the list are in the proper positions.

Definitely something you want to use another dedicated plugin for.
