### ISSUE TITLE
Lag with /TP and /TPO on latest build

### ISSUE THREAD

**Issue by CheatSupport** [EssentialsX/Essentials#1041]
Lag with /TP and /TPO on latest build

I do /tpo (player) and it causes server lag for a split moment.. then teleports me. why is this?

**Comment by Kakifrucht** [comment]
Do you have lots of homes?

**Comment by CheatSupport** [comment]
no, but there is 50+ players. It just lags when I teleport to a player

**Comment by Kakifrucht** [comment]
Turn on timings before teleport and paste immediately after.

**Comment by CheatSupport** [comment]
https://timings.aikar.co/v2/?id=83592e825b8e4bb9bc592004d136bfca

**Comment by Kakifrucht** [comment]
From these timings it doesn't seem to be Essentials related. Check SuperVanish, which causes pretty immense amount of lag, and modify your hopper settings in spigot.yml to improve performance.

**Comment by CheatSupport** [comment]
Thanks, any recommended hopper settings?

**Comment by Kakifrucht** [comment]
Use the same factor for hopper-transfer and hopper-amount. If you double hopper-transfer, double hopper-amount aswell. Keep in mind that this will break certain auto breweries.

**Comment by CheatSupport** [comment]
So
hopper-amount: 6
and
    ticks-per:
      hopper-transfer: 48

? Thanks so much, you are very helpful!

**Comment by Kakifrucht** [comment]
Yes, for example.
