### ISSUE TITLE
[Suggestion] /list Format

### ISSUE THREAD

**Issue by AntZaro** [EssentialsX/Essentials#1042]

**Comment by AntZaro** [comment]
Oops. I clicked enter too early on accident. Basically, I would like to suggest an option for the /list command to use only usernames, with no prefixes, nicknames, or colors. Just usernames with a color you choose. This would make a world of difference, because the /list is immensely crowded and difficult to read as is.

**Comment by TomLewis** [comment]
You can edit the messages_en.properties to change the display of any text, may want to look at that.
you can also create a custom playerlist based on groups in custom.txt I do this to have a /staff
{PLAYERLIST:Admin}
For instance.

**Comment by AntZaro** [comment]
I'm not sure you understand what I meant. I know about custom.txt and I do the same exact thing with my own /staff. The issue is not in that part. The issue is in the part where all users are listed with their rank prefix and display name. I was asking for an option to change this so that just their username is listed instead.

Example: [Admin]~Notchy versus Notch. The first is what /list lists (rank and nickname). I'm asking if it could be made to just list the second (username only).
