### ISSUE TITLE
Warp Messages

### ISSUE THREAD

**Issue by EverF0** [EssentialsX/Essentials#1044]
I realize this isn't a huge "issue", but still somewhat of a bug.

When you have a teleport-cooldown set in the config.yml and you try to warp somewhere, you will get the message that you are warping to said place, and then message that you can't warp for however long you set the cooldown to. I assume there is just a missing check to see if the player is on a cooldown before it sends the warping message.

![Screenshot of Issue](http://i.imgur.com/RItojut.png)

**Comment by TomLewis** [comment]
I customized all my messages, you can extract the messages_en.properties from the essentials.jar and put this in your main essentials directory to customize your messages.
Edit; or just use it from the git https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/messages_en.properties

**Comment by EverF0** [comment]
I know how to customize the messages; that wasn't what I was saying. I'm saying that if the player is on a teleport cooldown and they type /warp destination, it will deliver the "Warping to destination." message, and also deliver the "Time before next teleport" message. I'm saying that if the player is on a cooldown, the "Warping to" message should **not** appear.

**Comment by mdcfe** [comment]
I think this is because cooldowns for teleportation are handled by the Teleport class, but the message is sent by the `/warp` command. I'd suggest putting a cooldown on the warp command to avoid this for now.
