### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by zukmeku** [EssentialsX/Essentials#1048]
29.12 18:30:46 [Server] WARN Task #69 for Essentials v2.0.1-b461 generated an exception
29.12 18:30:46 [Server] INFO java.lang.NullPointerException
29.12 18:30:46 [Server] INFO at com.earth2me.essentials.xmpp.XMPPManager.updatePresence(XMPPManager.java:152) ~[?:?]
29.12 18:30:46 [Server] INFO at com.earth2me.essentials.xmpp.EssentialsXMPP.updatePresence(EssentialsXMPP.java:109) ~[?:?]
29.12 18:30:46 [Server] INFO at com.earth2me.essentials.xmpp.EssentialsXMPPPlayerListener$1.run(EssentialsXMPPPlayerListener.java:31) ~[?:?]
29.12 18:30:46 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot188.jar:git-Spigot-db6de12-18fbb24]
29.12 18:30:46 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot188.jar:git-Spigot-db6de12-18fbb24]
29.12 18:30:46 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot188.jar:git-Spigot-db6de12-18fbb24]
29.12 18:30:46 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot188.jar:git-Spigot-db6de12-18fbb24]
29.12 18:30:46 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot188.jar:git-Spigot-db6de12-18fbb24]
29.12 18:30:46 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot188.jar:git-Spigot-db6de12-18fbb24]
29.12 18:30:46 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]

Another 

29.12 18:28:45 [Server] WARN Task #61 for Essentials v2.0.1-b461 generated an exception
29.12 18:28:45 [Server] INFO java.lang.NullPointerException
29.12 18:28:45 [Server] INFO at com.earth2me.essentials.xmpp.XMPPManager.updatePresence(XMPPManager.java:148) ~[?:?]
29.12 18:28:45 [Server] INFO at com.earth2me.essentials.xmpp.EssentialsXMPP.updatePresence(EssentialsXMPP.java:109) ~[?:?]
29.12 18:28:45 [Server] INFO at com.earth2me.essentials.xmpp.EssentialsXMPPPlayerListener$1.run(EssentialsXMPPPlayerListener.java:31) ~[?:?]
29.12 18:28:45 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot188.jar:git-Spigot-db6de12-18fbb24]
29.12 18:28:45 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot188.jar:git-Spigot-db6de12-18fbb24]
29.12 18:28:45 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot188.jar:git-Spigot-db6de12-18fbb24]
29.12 18:28:45 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot188.jar:git-Spigot-db6de12-18fbb24]
29.12 18:28:45 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot188.jar:git-Spigot-db6de12-18fbb24]
29.12 18:28:45 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot188.jar:git-Spigot-db6de12-18fbb24]

**Comment by mdcfe** [comment]
If you aren't using EssentialsXMPP, you don't need to install the jar. Feel free to reopen it if you're encountering an issue while trying to use it.
