### ISSUE TITLE
BungeeCord silent join/quit issue

### ISSUE THREAD

**Issue by zRiaz** [EssentialsX/Essentials#105]
So basically, with the setting 
allow-silentjoin & silent-quit enabled, it will still send a message if you're running BungeeCord and join another server. (Then it will send "player has left.")

Not sure if its a bug or what, but yea. Would be nice to have that fixed as I had to install HideSteam to completely remove that message too.

**Comment by drtshock** [comment]
Can you turn on debug and paste your logs in a pastebin for us when that happens please.
