### ISSUE TITLE
auto-afk doesnt work using a fishing rod

### ISSUE THREAD

**Issue by TheoRetisch1** [EssentialsX/Essentials#1050]
How to reproduce the bug:
1. Enable auto-afk after some seconds in the config. 
2. Cast a fishing rod in the water or on the land and wait.
3. You wont go afk. 
4. If you set your afk status manually it will be cancelled as soon as a fish bits.

The Problem is 1.11 related. Testsystem: Essentials 2.0.1-b460, PaperSpigiot build 1008; no erros in the log.

**Comment by Sikatsu** [comment]
Same issue here.

**Comment by Sikatsu** [comment]
I'm using normal Spigot with the same issue. @SupaHam

**Comment by TNTUP** [comment]
Confirming this, on 1.10­.2. Quite "critical". A player has found this usebug without staff consent and I've warned him. (and he ragequitted lol)

**Comment by TheoRetisch1** [comment]
This is an bump. The Issue is still exist in 1.12.2 and is still urgent. I would be gratefull for any help or progress.

**Comment by itsgatto** [comment]
Another bump i think, i haven't found a way to solve this at the moment :/

**Comment by itsgatto** [comment]
I have created the pull request #1804 that will offer the ability to avoid fishing being detected as an activity by disabling the setting `cancel-afk-on-interact`.

**Comment by Remski01** [comment]
It is still broken, I just checked it with build **# 612** 

I checked it in 2 ways:

First: I did not use the fishing rod. I was put in afk in 10 minutes.

Second: I used the fishing rod. I was not put into afk. Even not after 15 minuts.

Config: (afk section) https://pastebin.com/XdyfsbsE

**Comment by pop4959** [comment]
Should be fixed by the PR mentioned above. The settings Remski linked to appear to not disable the setting `cancel-afk-on-interact`.
