### ISSUE TITLE
EssentialsX /worth command REMOVING ITEMS FROM PLAYERS!

### ISSUE THREAD

**Issue by Vestle** [EssentialsX/Essentials#1053]
Hey there drt! There is a MAJOR bug with the /worth command where it is taking the items from players inv and it doesn't give money for it either. It's a big glitch that needs to be fixed thank you!
I disabled it on my server until fixed.

**Comment by mdcfe** [comment]
What version of Spigot and EssentialsX are you running?

**Comment by Vestle** [comment]
latest build for essentialsx 461
and Spigot latest 1.11.2 release

**Comment by Momshroom** [comment]
We have the same issue.  No  console errors.  Items disappear when the player does /worth.  Their balance does not change.  EssentialsX build 460 and latest spigot 1.11.2.
CraftBukkit version git-Spigot-7d78b81-613be0d (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
Essentials2.0.1-b460.

**Comment by Vestle** [comment]
definitely and issue with the command.

**Comment by ghost** [comment]
Confirmed on Spigot 1.11.2 (newest release) and latest build (dev) of Essentials

**Comment by SupaHam** [comment]
I'm currently away from my computer. I will aim to have this resolved by the end of weekend. Sorry for the inconvenience.

**Comment by vemacs** [comment]
Does this happen on 451? Is the reported value correct? 

Can somebody test this JAR? https://transfer.sh/aTJWc/essentialsx-2.0.1.jar

**Comment by ClankyPoo** [comment]
Same issue on 462

**Comment by vemacs** [comment]
@ClankyPoo Not 462, the JAR I linked. No changes wrt this issue were committed.

**Comment by ClankyPoo** [comment]
oh i see

**Comment by vemacs** [comment]
Results?

**Comment by cliffness** [comment]
@vemacs 
Tested the JAR, and /worth was working correctly in that snapshot.
