### ISSUE TITLE
Error player online but says offline

### ISSUE THREAD

**Issue by AmazedMender16** [EssentialsX/Essentials#1054]
when people try to send message to players. when they are online but says the players are offline.
using latest essentialsx build from jenkins 
1.11.2 server and latest protocollib

**Comment by mdcfe** [comment]
If this is still an issue, could you update to the latest version of EssentialsX then run `/ess version` and paste the **full output**?

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to respond and reopen the issue.
