### ISSUE TITLE
[request] teleport offline players to a new lastlocation when they re-join

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#1055]
If I need to teleport an offline player to a new location when they next spawn, I have to manually edit "lastlocation" in the essentials data, this is a massive pain in the ass, can we just get a command to change it? could be /updatelastlocation <username> and it sets their lastlocation to where your standing. Easy.
Would save everyone so much headache.

**Comment by mdcfe** [comment]
Closing in favour of #1561.
