### ISSUE TITLE
bed respawn broken with essentialsx installed

### ISSUE THREAD

**Issue by chillerkraft** [EssentialsX/Essentials#1056]
i removed essentialsx and retested bed respawn and it worked fine.

**Comment by mdcfe** [comment]
Install EssentialsXSpawn and set `respawn-at-home: false` to `true`.

**Comment by chillerkraft** [comment]
i don't want people to respawn at there first set home i just want them to be able to respawn at there bed like vanilla (and with the multiverse bed-respawn option)

**Comment by chillerkraft** [comment]
i set respawn listener priority to lowest; expecting the respawn behavior to return back to before i installed essentials having bedrespawn true in multiverse respawn me at my bed when i die

**Comment by chillerkraft** [comment]
when i set respawn listener priority to lowest, does essentials just ask multiverse which world to take me to or does it LET multiverse do it's thing? i have a feeling its asking..

**Comment by chillerkraft** [comment]
OH i know! i can just remove essentialsxspawn and that should restone respawn back to how it was beforee!! YAY. will update on success

**Comment by chillerkraft** [comment]
SUCCESS

**Comment by chillerkraft** [comment]
i really think theres a bug though

**Comment by vemacs** [comment]
Not bug, intended behavior.

**Comment by chillerkraft** [comment]
well idk what i did wrong i set priority to lowest so multiverse would take control but it still made me respawn at spawn instead of my bed
i believe with multiverse, it allows vanilla behaviour of respawning at bed, but with essentialsxspawn it only checked for respawn world and not the bed respawn behaviour of vanilla/multiverse

**Comment by chillerkraft** [comment]
im gonna try to put respawn priority on high and see if i can do the vanilla bed respawn that way maybe.. doubt itll work tho

anyone know how i can have essentialsxspawn annd have the vanilla bed respawn feature?
