### ISSUE TITLE
"spawn-on-join: true" doesn't work

### ISSUE THREAD

**Issue by Twonox** [EssentialsX/Essentials#1057]
"spawn-on-join: true" doesn't work.
(I've tested with and without AuthMe, so AuthMe is not the cause)

I use EssentialsX b455

**Comment by Kakifrucht** [comment]
Do you have EssentialsXSpawn installed?

**Comment by Twonox** [comment]
Yes, I have.

**Comment by SupaHam** [comment]
I would think another plugin is interfering. Please try reproduce this with just Essentials installed.

**Comment by LazoYoung** [comment]
I thought the same as @Twonox. But then I realized I was having a superperm that involves
'essentials.spawn-on-join.exempt' permission which ignores this feature for the player.

P.S. I confirmed that this spawn-on-join is working for the latest build.
