### ISSUE TITLE
command "/Pay" give me ERROR:NULL in game

### ISSUE THREAD

**Issue by Ancard** [EssentialsX/Essentials#1058]
Using the pay command in the game, users get null error in response. The error came from the server in version 1.10 and I am currently using the plugin on the server with version 1.11.2. In the console I do not get errors.
![2017-01-05_23 57 29](https://cloud.githubusercontent.com/assets/24949481/21706209/00080858-d3a4-11e6-89d0-d65398925c1b.png)

**Comment by BlueSoapTurtle** [comment]
Sure there's nothing in the console? check the latest.log file

**Comment by SupaHam** [comment]
Type `/ess debug` then reproduce the issue, you must then get an error in the console.

**Comment by Ancard** [comment]
Was solved with the last update. I am thinking about the possibility that the problem was a mistake in the configuration files or in the storage of the data of the players. Was solved when I tried it on a new test server and I could not repeat the error.
