### ISSUE TITLE
Permission for /back only on death

### ISSUE THREAD

**Issue by cicatrice74** [EssentialsX/Essentials#1059]
Is it possible to have players do only /back if they die instead of having to give them the /back whenever they want ?

something like:

essentials.back --> they can use the /back command
essentials.back.ondeath --> they can only do /back when they die

i don't want they to forcefully have both of them to use the /back on death

**Comment by mdcfe** [comment]
Doesn't this already exist?

**Comment by cicatrice74** [comment]
If u wamt to let players do back when they die u must give them also the normal back permission...so i cannot have them only use the back on death but the normal back too. I want to choose wich one to give them.

**Comment by smmmadden** [comment]
use an alias and tell them which one to use.  if they type in /back do xyz if they type in /died you do back
not sure if you can override the default behavior by using an alias of the same name, but seems like it would work.  So in your commands.yml, it would look similar to the below.  You can change the name of "died" to anything you want of course. :-)  The dash before the say command and back command should be shown, this editor keeps removing the dashes (-)
command-block-overrides: []
aliases:
  icanhasbukkit:
  - version $1-
  back:
  - say You are not allowed to use back in this game
  died:
 - back

**Comment by cicatrice74** [comment]
it is sufficient to separate the two  permissions:
essentials.back u can do back always but not on die
essentials.back.ondeath u can only do back on death
if u use both u can do back always

**Comment by mdcfe** [comment]
@smmmadden Could you use a paste service (or at the very least, code block tags)? Also, this seems to just hide the problem from players who have absolutely no initiative; it doesn't solve the issue at all.

@cicatrice74 I see what you mean now; this is a valid suggestion and I can see the use of it.

**Comment by cicatrice74** [comment]
u should also add afk cooldown cause my users uses afk message to spam on
chat...can u add afk cooldown?

Il 09 Gen 2017 23:47, "md678685" <notifications@github.com> ha scritto:

**Comment by cicatrice74** [comment]
can u also add a
custom join message on title ?

Il 09 Gen 2017 23:57, "Francesco Fabbri" <cicatrice74@gmail.com> ha scritto:

**Comment by mdcfe** [comment]
@cicatrice74 Could you create separate issues for each separate suggestion? (Also, you can use existing `command-cooldowns` to prevent command spam including `/afk` spam.)

**Comment by cicatrice74** [comment]
I cannot see the afk command cooldown, have i to add it manually ?

**Comment by mdcfe** [comment]
Yes, you need to enable cooldowns and add the afk cooldown to the config.

**Comment by MattAKAFred** [comment]
Just wanted to jump in and say I was just looking for this exact feature. Specifically, since I'm trying to cut back on the amount of pure warping players are allowed to do, I'm looking to have a sign in the respawn room that issues the back command to players, which only sends them there on death. If that is too complicated, I would be totally OK with simply separating the permissions.

**Comment by cicatrice74** [comment]
can u please write here the options to add to the config to have both commands and afk cooldowns ?

**Comment by Ironic8b498** [comment]
I would love to have this feature for my vanilla server, back on death only would be great since back is too OP for vailla

**Comment by darbyjack** [comment]
Closing because this permission node exists now.

**Comment by mdcfe** [comment]
@darbyjack Does it?

**Comment by Ironic8b498** [comment]
the perm might be there but it don't work, for only allowing players to use back only on death, thats OK I made my own plugin to do this
