### ISSUE TITLE
/pay bug when you have a balance limit in place

### ISSUE THREAD

**Issue by denizaygundev** [EssentialsX/Essentials#106]
Essentials allows you to pay someone when they've reached the balance limit but they won't get the money and you still lose your money.

Perhaps to tackle this we can check how much the users balance will be with the amount the user wants to send and if it's over the limit then deny it?

**Comment by Kakifrucht** [comment]
I can confirm this issue, the payment will be send, however the recipient won't see a notification.

**Comment by denizaygundev** [comment]
It's been an issue for since I can remember...

**Comment by vemacs** [comment]
Do you get the message that they're over the balance limit, or is there no message?

I'm trying to figure out if `MaxMoneyException` is being thrown properly.

**Comment by Kakifrucht** [comment]
You get the message, money is still being taken though.

**Comment by vemacs** [comment]
What message? Screenshot?

```
maxMoney=\u00a74This transaction would exceed the balance limit for this account.
```

**Comment by Kakifrucht** [comment]
yes, maxMoney is the string being used.

**Comment by andrewkm** [comment]
This issue does not seem to be fixed with this commit @vemacs and @drtshock 
Did it fix it for you guys @NmExHunTeRz & @Kakifrucht
