### ISSUE TITLE
Error ( /r message wrong person )

### ISSUE THREAD

**Issue by AndreasTecH** [EssentialsX/Essentials#1060]
Hello im here to report something so it'll get fixed. Im using the latest version of essentialsX b463 but i think that this also happens in older beta and releases.
So my todays issue is that. If i contact someone with /m and after this someone else contact me, when ill try to replay to the latest person that contacted me, i will not replay to him, but to the first guys. ( to the one that i used /m to contact him )
I guess you have understood the issue, thanks for the great work.

**Comment by mdcfe** [comment]
This is a config setting - [`last-message-reply-recipient`](https://github.com/drtshock/Essentials/wiki#controlled-private-messaging). This is not a bug.
