### ISSUE TITLE
SUGGESTION: Item names

### ISSUE THREAD

**Issue by Lammendam** [EssentialsX/Essentials#1062]
Move item names to external yml or txt file to add an ability to translate them.
For example, i wrote a command /give Lammendam iron_ingot 2 or /i iron_ingot 2 and take notification that this items is in my inventory. I want to to customize it.
Same situation with enchantments and other items that have customized names.

**Comment by mdcfe** [comment]
One solution could be to send JSON components in chat, as I believe these allow you to use translation strings that the client fills in. However, this would require overhauling how we send messages to players to enable sending components.

**Comment by pop4959** [comment]
You can now create custom aliases using `/itemdb alias create` in the latest version.
