### ISSUE TITLE
Custom join message not working

### ISSUE THREAD

**Issue by PiggyPiglet** [EssentialsX/Essentials#1065]
The custom join message is not working for me or my friend.
Plugins: CleanroomGenerator, CoreProtect, LuckPerms, Ram_Monitor, TerrainControl, QuickBoard, PlaceholderAPI, PerWorldPlugins, BlingTrees, Obole, AdvancedBan, WorldBorder, RandomTP, GeneralLib, AntiWDL, FastAsyncWorldEdit, RAMManager, DeluxeMenus, BlocksHub, ViaVersion, ItemJoin, Tablist, Vault, WorldEdit, Essentials, PerWorldInventory, PlotSquared, Multiverse-Core, WorldGuard, Holograms, ProtocolLib, HideAndCustomPlugins, NoCheatPlus, AdvancedAchievements, Multiverse-NetherPortals, SuperVanish, ServerListPlus, GriefPrevention, Statz, VentureChat, Autorank, WarpPortals
config:
http://pastebin.com/s0kM6CP1

**Comment by mdcfe** [comment]
Could you paste what shows up in the console when a player joins? (Make sure to remove any IP addresses.)

**Comment by PiggyPiglet** [comment]
[01:12:53] [User Authenticator #3/INFO]: UUID of player PiggyPiglet is 29ce1721-7764-4c15-9f71-a19d81f33927
[01:12:54] [Server thread/INFO]: PiggyPiglet[removed] logged in with entity id 1401 at ([Hub]-142.8128843192056, 116.73642585306696, -194.29061358858723)
[01:12:54] [Server thread/INFO]: [0;37;22m[21m[[0;32;1m[21m+[0;37;22m[21m][0;37;1m[m PiggyPiglet[m

**Comment by PiggyPiglet** [comment]
bump

**Comment by mdcfe** [comment]
What shows up in game when you log in? The join message seems to be working.

**Comment by PiggyPiglet** [comment]
Nothing. The leave message is working but the join isn't.

**Comment by mdcfe** [comment]
If this is still an issue, could you run `/ess debug` then post what occurs in the console and in your log when a player logs out?

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to respond and reopen the issue.
