### ISSUE TITLE
Edit socialspy messages

### ISSUE THREAD

**Issue by kikelkik** [EssentialsX/Essentials#1066]
I would very appreciate if, as it has been before your last updates, I had the possibility to edit the formatting of socialspy msgs (not just the [SS]) in messages.properties.
It is much more comfortable to overview the chat if I could format SS-msgs seperated from personal msgs.
I think, this little feature does not require lots of work and time in implementing so I hope, you can and want to manage it :)

**Comment by kikelkik** [comment]
Still waiting for an answer

**Comment by mdcfe** [comment]
Added by #1460.
