### ISSUE TITLE
VanishEvent

### ISSUE THREAD

**Issue by Lammendam** [EssentialsX/Essentials#1067]
Could you add an event that checks player if he is vanished?
I just want to recompile TeleParticles plugin to allow players in vanish to autodisable effects.

**Comment by mdcfe** [comment]
Do you want to listen to an event which gets called when someone's vanish status changes, or do you want to be able to check whether someone is vanished at a particular time? Both are possible as far as I know.

**Comment by Lammendam** [comment]
In my situation will be best second variant. It would be nice.
For example, I want to add event to TeleParticles that checks if player wrote command /v or /vanish and check Essentials vanish status. If essentials returns true or false, teleport effects and sounds will be enabled or disabled.

**Comment by mdcfe** [comment]
You can listen to `VanishStatusChangedEvent` which will fire whenever the player is vanished or unvanished.
