### ISSUE TITLE
itemdb fix

### ISSUE THREAD

**Issue by cicatrice74** [EssentialsX/Essentials#1068]
Can u update the plugin to fully support latest 1.11.2 items ? when i do /itemdb with the polarbear egg it says me only 383:0 but it isn't, do i need to update something ?

**Comment by mdcfe** [comment]
Spawn eggs are known to have issues. Other 1.11 and 1.11.1 items have already been added and 1.11.2 didn't add any items.

**Comment by cicatrice74** [comment]
so what do we need to do to have updated monster eggs id ?

**Comment by pop4959** [comment]
The way items work was changed in 1.13, and item db has had substantial updates since then. Please download the latest version and create a new issue if you still have problems spawning items.
