### ISSUE TITLE
custom join/leave message command or title

### ISSUE THREAD

**Issue by cicatrice74** [EssentialsX/Essentials#1069]
Can u add the option to have a command sent when a player joins or Leaves the server with placeholders so when a player joins u can send the firework command or a title to other players... can this be added ?

**Comment by mdcfe** [comment]
I feel that this is outside the scope of EssentialsX. Other plugins can already do this.

**Comment by cicatrice74** [comment]
i don't think cause we have the custom join message... i only suggest a feature that could come in handy for everyone...with a command on join option u can have server's owners using your plugin instead of having two.. do you remember the option to spawn on join i suggested time ago ? it was outside the scope of the plugin ? no. i think someone used that option instead of using other's..

**Comment by pop4959** [comment]
Leaving this as open to pr, but closing since there seems to not be much interest in this.
