### ISSUE TITLE
Option for creating userfiles

### ISSUE THREAD

**Issue by baticag** [EssentialsX/Essentials#107]
I use Essentials on hubs, so every users that joins creates new file in userdata and it is really not needed for hub. Can there be an option for this, or some other way of storing information?

**Comment by Agazed** [comment]
I've always hated the millions of userfiles I had to transfer. Would be cool if there was a MySQL option to store them too
.

**Comment by vemacs** [comment]
Most wrappers allow you to run scripts on server shutdown or before startup. I think this has a very limited audience.

**Comment by drtshock** [comment]
You could either deny writing to the directory or just use a script to delete on shutdown / before the server starts again. That's what I did for Minetime. I also don't know why this would be needed unless a few mb of disk space is a premium.
