### ISSUE TITLE
Tab colors not changing

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1070]
Essentials(X) used to change the color of player names when looking at the player list. But as of recent, it no longer does this. Instead, only ops appear red, but no other group does.

Using EssentialsX, EssentialsXChat, PEx.

Config (concerning colors):

```
# A color code between 0-9 or a-f. Set to 'none' to disable.
ops-name-color: '4'

# The character(s) to prefix all nicknames, so that you know they are not true usernames.
nickname-prefix: '~'

# Disable this if you have any other plugin, that modifies the displayname of a user.
change-displayname: true

# When this option is enabled, the (tab) player list will be updated with the displayname.
# The value of change-displayname (above) has to be true.
change-playerlist: true
```
Using version 2.0.1-b463 and most recent Spigot release.

**Comment by TheDarkTurnip** [comment]
You should probably get Vault to use PeX.

**Comment by ghost** [comment]
I'd forgotten to mention Vault. I do have it installed.

**Comment by mfnalex** [comment]
I have the same problem, and prefixes don't work either in tab. it used to work with the version from december 2016
