### ISSUE TITLE
/msgon /msgoff

### ISSUE THREAD

**Issue by voodootje0** [EssentialsX/Essentials#1072]
Would be nice if that can be added. Same as /payon and /payoff

**Comment by mdcfe** [comment]
I don't see the point of being able to turn on constant message confirmations?

On a side note, I feel like the command confirmations should become independent of the pay command, and the commands which have confirmations can be configured either on a server-wide or per-user basis. @SupaHam thoughts?

**Comment by voodootje0** [comment]
@md678685  It's just the same as /paytoggle, when @SupaHam added that command he also added /payon and /payoff, and it would be nice if that can also be added for /msgtoggle.

**Comment by mdcfe** [comment]
Apologies, misunderstood the request. Although I still don't really see the point of this? You can `/msgtoggle [on|off]` already.
