### ISSUE TITLE
Prefix in /list

### ISSUE THREAD

**Issue by dukedase** [EssentialsX/Essentials#1073]
Hello, even after disabling this: https://i.gyazo.com/6637dc7ecd51cb1edb08cb7452c7a852.png

I am still seeing https://i.gyazo.com/04c2dcad90b07d6fe77f4af3ccf60d18.png

I have checked my permissions plugin (zPermissions) and it has nothing about this

My plugins are:  https://i.gyazo.com/57decd1ab1ef592c69ec07df6362ffd2.png

**Comment by rye761** [comment]
You need to remove the `#` from the line `add-prefix-suffix: false`. The `#` tells the interpreter to ignore the line.

**Comment by dukedase** [comment]
Ah, that fixed it, thanks!  However, I now have another problem... is there a way to keep the color of the names but not the words?  For example, a ranks prefix is "&4Title&f:&4" .. could I make it so the /list only shows &4Name?

**Comment by mdcfe** [comment]
Not with EssentialsX, no. There is only one prefix and suffix.

**Comment by dukedase** [comment]
Ah, thank you.
