### ISSUE TITLE
Buy and Sell signs limited to 41 items in some cases?

### ISSUE THREAD

**Issue by boredhero** [EssentialsX/Essentials#1074]
I have noticed that TNTMinecart and Totem are both limited to stack sizes of 41. This is new. Does anyone know what could be causing this issue. If I set them to 64 when typing the sign, it is auto-corrected to 41 as soon as I save the sign.

**Comment by boredhero** [comment]
I have noticed this applies to:
Totems
All Minecart Types
Filled Buckets (Milk, Water, Lava)

**Comment by boredhero** [comment]
I have noticed this also applies to:
Rabbit Stew
Mushroom Soup
Beetroot Soup

**Comment by SupaHam** [comment]
41 because that is the size of your inventory multiplied by the item's max stack size, which is 1 in all those cases.
