### ISSUE TITLE
/kick error?

### ISSUE THREAD

**Issue by Linebeck** [EssentialsX/Essentials#1076]
Everytime I /kick someone off my server. This is reported in console: 

16.01 01:14:02 [Server] WARN handleDisconnection() called twice

What exactly does this mean?

**Comment by mdcfe** [comment]
As far as I know, this is a Spigot (or possibly even vanilla) issue and isn't directly related to Essentials.

**Comment by MattAKAFred** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-854
