### ISSUE TITLE
[REQUEST] Portable Anvil Command

### ISSUE THREAD

**Issue by TheJadyha** [EssentialsX/Essentials#108]
This command would work exactly like the /craftingtable or /bench command. It's pretty sweet and simple. You type the command /anvil and a magical anvil appears when there is no anvil in sight!

You could do the same with an enchanting table!

**Comment by Joomzy** [comment]
I vouch, this would be a nice addition.

**Comment by Kakifrucht** [comment]
makes sense, +1, should be pretty straight forward.

**Comment by EvilOlaf** [comment]
+1

**Comment by Agazed** [comment]
+2

**Comment by vemacs** [comment]
Requires significant amounts of NMS. Use http://dev.bukkit.org/bukkit-plugins/virtualpack/ instead.

**Comment by Kakifrucht** [comment]
Thats unfortunate :(
