### ISSUE TITLE
Butcher skeleton horse

### ISSUE THREAD

**Issue by ChanceSD** [EssentialsX/Essentials#1083]
The butcher/killall command is missing skeleton horses somehow.
I tried: 
/killall monster - doesnt remove the horses
/killall skeletonhorse - 0 entities removed
/killall skeleton_horse - invalid mob

I didn't try killall animals or mobs just because i have animals i can't delete but even if that worked i think it should be working with just the name.

**Comment by Taybosquee** [comment]
Skeleton horses aren't hostile and thus aren't considered monsters but instead animals like normal horses, chickens, ect. Although yes, "/killall skeleton_horse" *should* work while it doesn't.

**Comment by pop4959** [comment]
Unable to replicate in the latest version. I used the below commands to test.

/spawnmob skeletonhorse 1 (spawn a skeleton horse next to you)
/killall skeletonhorse 10 (kill skeleton horses within 10 blocks of you)
