### ISSUE TITLE
Buy/sell create broken

### ISSUE THREAD

**Issue by MrArcane** [EssentialsX/Essentials#1086]
The permissions for buy & sell create signs are broken the first line gets replaced with "**"

    - essentials.signs.create.sell
    - essentials.signs.create.buy

**Comment by mdcfe** [comment]
What permissions plugin are you using?

**Comment by MrArcane** [comment]
Permissionsex

**Comment by mdcfe** [comment]
What other plugins do you have installed?

**Comment by MrArcane** [comment]
http://prntscr.com/dxh2j5

**Comment by mdcfe** [comment]
> MinecraftMarket, ... Auctions, SafeTrade, ... KitAdder, PROCrates, ... AlphaCore

I'm not familiar with any of these plugins, but are you sure that none of them are conflicting with Essentials' signs (especially `MinecraftMarket`)?

**Comment by MrArcane** [comment]
MinecraftMarket is for my Donation store, AlphaCore is my plugin and doesn't do anything with signs, SafeTrade is a /trade command, Auctions is basically a way to sell items through commands, KitAdder adds kits from your inventory, PROCrates is a very nice crate Plugins "Nothing with signs". So no i don't think so.

**Comment by mdcfe** [comment]
Could you also [paste your permissions.yml](http://hastebin.com)?

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to reopen the issue.
