### ISSUE TITLE
Do I need EssentialsChat to get color codes? & a /vanish question.

### ISSUE THREAD

**Issue by Linebeck** [EssentialsX/Essentials#1087]
Ok, So I use color codes when I am op. Im currently using this: [https://www.spigotmc.org/resources/%E2%99%A3-chatcontrol-pro.10258/](url) as my chat plugin. I gave users the essentials.chat.color. But nothing... Suggestions?

Also, one of my supervisors doesn't have to do /vanish when he logs in anymore. When we had the old TeamCity plugin he did. I still have to do that. Odd glitch? Or what?

**Comment by mdcfe** [comment]
With regards to the first issue, I can't help, but I'm fairly certain you need EssentialsXChat to use any of EssentialsX's chat features.

Regarding `/vanish` on join, they need `essentials.silentjoin.vanish` for this to work.
