### ISSUE TITLE
EssX Kills PEX prefixing ability

### ISSUE THREAD

**Issue by Tikkle** [EssentialsX/Essentials#1088]
When i installed Essentials X, all of the sudden my permissionsEX prefixs stopped working.
There is no stacktrace, nothing in debug mode, nada. I dont know what is causing this

**Comment by mdcfe** [comment]
What other plugins do you have installed?

**Comment by Tikkle** [comment]
I was literally just starting to configure a server so:

EssentialsX
PeX
Votifier
Worldedit
Worldguard

**Comment by vemacs** [comment]
Read the readme and install Vault.

**Comment by Tikkle** [comment]
I installed vault and im still having this problem
@vemacs 

Also running PaperSpigot Build #1040

**Comment by mdcfe** [comment]
You also need EssentialsXChat if you want EssX to format your chat.

**Comment by Tikkle** [comment]
I have All ESSX .jars

EssentialsX 2.0.1
EssentialsX AntiBuild 2.0.1
EssentialsX Chat 2.0.1
EssentialsX Protect 2.0.1
EssentialsX Spawn 2.0.1
PermissionsEx 1.23.4
Vault 1.5.3
Votifier 1.9
Worldedit 6.1.5
Worldguard 6.2

**Comment by mdcfe** [comment]
Can you [paste your config](http://hastebin.com)?

**Comment by Tikkle** [comment]
https://hastebin.com/eyosapuhol.coffeescript

**Comment by mdcfe** [comment]
Change `format` to include your prefixes.

**Comment by Tikkle** [comment]
Yea for some reason, i had to format each group's prefix through essentials, that's kind on annoying. Could you find a way to allow the permissions plugins to takeover prefixing, in the old essentials, pex would overtake the prefixs just fine

**Comment by Tikkle** [comment]
You also have to relog after a group change to change the color of your nametag

**Comment by vemacs** [comment]
We do through Vault, that's the whole point of the Vault system... There's just something wrong with your setup, many other users are using Vault prefixes through PEX perfectly fine.
