### ISSUE TITLE
/tell and socialspy

### ISSUE THREAD

**Issue by Platinteufel** [EssentialsX/Essentials#1090]
If a player uses /tell for private messages socialspy will show it twice
http://fs5.directupload.net/images/170122/4yep74u8.png

I think this is not intended as /msg, /w, .. only show it once.

**Comment by Kakifrucht** [comment]
Cannot reproduce. What do you have set under socialspy-commands in your config?

**Comment by Platinteufel** [comment]
```
# These commands will be shown to players with socialSpy enabled.
# You can add commands from other plugins you may want to track or
# remove commands that are used for something you dont want to spy on.
# Set - '*' in order to listen on all possible commands.
socialspy-commands:
  - msg
  - w
  - r
  - mail
  - m
  - t
  - whisper
  - emsg
  - tell
  - er
  - reply
  - ereply
  - email
  - action
  - describe
  - eme
  - eaction
  - edescribe
  - etell
  - ewhisper
  - pm
```

**Comment by Platinteufel** [comment]
I've just tested it on a sandbox server (latest build, no changes in config). Same issue here.

**Comment by Kakifrucht** [comment]
Try removing the duplicate commands of that list.
Mine looks like this:
````
socialspy-commands:
- mail
- email
````
/msg (includes /tell, /t, /m etc.) and /r are obsolete since the new socialspy, you do not need to add them, for the rest you will need to specify aliases aswell (like /mail and /email).

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to reopen the issue.
