### ISSUE TITLE
EssentialsTimer error - player list name only 16 characters long

### ISSUE THREAD

**Issue by airoons** [EssentialsX/Essentials#1092]
Hello!

I'm using newest paperspigot 1.7.10, even tried on normal spigot 1.7.10, but it was the same - when I type /list, it shows similar error in game chat too, but this error pretty frequently spams in console: http://pastebin.com/uPcNTVFD

Maybe the problem is that in 1.7.10 there might be a less maximum character limit in TAB, I've set a [AFK] tag in tablist when someone goes AFK. Maybe that's the problem? Tried to use /afk command, in chat it didn't showed that I'm AFK now, only when I'm not AFK.

Can you fix it? I'm using one of the newest development versions of Essentialsx,

**Comment by airoons** [comment]
Bump

**Comment by mdcfe** [comment]
If this is still an issue, you'll need to use a shorter AFK list name or limit nicknames to prevent this. However, 1.7.10 is no longer supported.
