### ISSUE TITLE
(Request or BUG?) Kits time dont stop if player dont have the kit perm

### ISSUE THREAD

**Issue by FabioZumbi12** [EssentialsX/Essentials#1094]
Hi,

I was wondering if this is a bug or can be added:

> On my server i have a plugin for vips where the player can have two vips at same time. The situation is, the player have Vip1 30 days and Vip4 10 days and the respective kits.
> 
> This player gets the kit Vip4 and chage to Vip1(deactivating the vip4) and wait the time needed to get another kit Vip4 and change to Vip4 only when the cooldown for kit vip4 end... and with this this player gets infinites kits Vip4 using the time of Vip1.
> When a player change the vip, this player have only the perm of active vip.

It is possible to pause the kit time when the player dont have the permissions that kit? Or theres a command to reset the kit time (to i fire when the deactivates one vip to other)?

EDIT: Maybe you add usage quantity for kits and a command to reset the quantity for specific players?

**Comment by lol768** [comment]
Discussed in IRC, can't see any command that would call `setKitTimestamp` to reset a kit's use timer in this manner. My guess is that there isn't any such command to reset the time.

**Comment by FabioZumbi12** [comment]
Hooking into Essentials i have this: 
`ess.getUser(Bukkit.getPlayer("FabioZumbi12")).setKitTimestamp(KitName, Time);`

I will try to store the reaim time on a variable and restore when change the active vip.

(But a comand to set the kit time still be welcome)
