### ISSUE TITLE
Socialspy displaying all private messages despite config

### ISSUE THREAD

**Issue by anzeumek** [EssentialsX/Essentials#1095]
Using build #467. Socialspy displays private messages despite that I removed pm commands from config. My config looks like this:
socialspy-commands:
  - jail
  - broadcast
  - weather
  - day
  - night
  - time
  - tpa
  - storm
  - dawn
  - tpaall
  - tpahere
  - rain
  - snow
  - pay

**Comment by mdcfe** [comment]
It's not ideal, but I think this is intended due to how the new SocialSpy works.

Can we have a config toggle for the new `/msg` SocialSpy yet? (A user-by-user basis is useless if you don't want staff to see messages at all.)

**Comment by anzeumek** [comment]
The problem here is, that players don't like it if some moderators read their private messages. Furthermore, in some countries, reading personal messages could actually be considered as an invasion of privacy and thus illegal.
This was a really useful feature for players with "helper" rank. They could monitor scams and private deals, becase they could socialspy on usage of /pay command. Also they could see if someone was annoying with /weather or /tpahere commands. However, now that they could also see pm, other players got really annoyed by that.

**Comment by pop4959** [comment]
So is this actually a bug? I'm a bit confused, although certainly the main use of social spy would be to see private messages. If that's a problem in your country you may want to disable use of the command.

**Comment by mdcfe** [comment]
@pop4959 As far as I can recall, about 2 years ago EssentialsX added a new formatting for private messages, and at the same time it meant PMs were always visible to members of staff who had socialspy turned on. Prior to this, it would only log the commands listed in the config to those members of staff, so `/msg` could be removed from the socialspy commands list and PMs wouldn't be visible.

**Comment by pop4959** [comment]
Yeah I was using the plugin around when the change happened, and I absolutely hated the new format at first. That aside, what I was mostly wondering is, under what circumstances is it that `socialspy-commands` is now partially ignored? Is that intentional, or was it simply a consequence of code changes? I see that this is labelled as an enhancement but it almost sounds like this could be a bug.

**Comment by mdcfe** [comment]
It isn't ignored per se, but I believe private messages are now always shown by default and can't be disabled. `socialspy-commands` still controls which *commands* get shown.

**Comment by pop4959** [comment]
OK so do you suppose we should support disabling private message in social spy in the future? Or is this a wontfix?

**Comment by mdcfe** [comment]
A config option or permission check could easily be added [here](https://github.com/EssentialsX/Essentials/blob/d3cee314c6ac8e7b8974b63ecefc9a257f13144a/Essentials/src/com/earth2me/essentials/messaging/SimpleMessageRecipient.java#L87) to control this.

Edit: silly Samsung keyboard disappeared while typing
