### ISSUE TITLE
Issues with /help? (Narrowing down the problem)

### ISSUE THREAD

**Issue by Linebeck** [EssentialsX/Essentials#1096]
So, I have set this customtext #help with a custom message. I added the alias in commands.yml, and made /help ---> customtext #help. So the problem is, recently it has been reverting to Essentials /help. I thought that commands.yml auto overrides everything by default. I am using paperspigot. So I don't know if paperspigot could cause this error? Or what exactly? If you could help me narrow this down or provide an explanation that would be great!

Thanks <3

Keep up the good work!

(I am using the latest builds, and paperspigot 1.11.2.)

**Comment by mdcfe** [comment]
Which build of Paper are you running (from `/version`)?

**Comment by Linebeck** [comment]
This server is running Paper version git-paper-1042 (MC: 1.11.2) (Implementing API Version 1.11.2-R0.1-SNAPSHOT)

**Comment by pop4959** [comment]
Probably fixed by now. Commands.yml should work just fine. If this is still a problem, feel free to open a new issue with more details.
