### ISSUE TITLE
Confirmation and toggle for clearinventory (/ci) command.

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#1097]
Would it be possible to add a confirmation and a toggle setting to the ```/clearinventory``` (/ci) command similar to how ```/pay``` has a confirmation by default and an ability to opt out of having to confirm? Clearing inventory can be a command people abuse when others aren't familiar with the alias ```/ci``` when others in chat tell people to use it.

**Comment by mdcfe** [comment]
I still think there should be a config option to make any command confirmable.

**Comment by mibby** [comment]
Still an issue my players are requesting. :( Someone spams "type /ci" in chat, then people complain when they lose their inventory. So having an option to add it as a toggleable confirmation would be nice.

**Comment by dordsor21** [comment]
This is a thing now, but it really would be nice to be able to disable all confirms. Creative servers with none-noob players have no need for a confirm on /ci

**Comment by LaxWasHere** [comment]
Update to the latest build, it should be disabled by default

**Comment by dordsor21** [comment]
Ah yes, thanks
