### ISSUE TITLE
Essentials Chat will not work.... VAULT INSTALLED

### ISSUE THREAD

**Issue by Dannysan626** [EssentialsX/Essentials#1098]
So I ran into an issue while editing the config for EssentialsX. I was doing some customizations and when I got to the part for EssentialsChat, I could not edit the group formats and get them to work. Whenever I did, and reloaded the plugin and or the server, the output would still be the default:

<[Owner] DannySan626> : Test

 not the

[Owner] Dannysan626 >>>>>> Test  (WHICH I WANT)

I have tried everything from uninstalling ALL plugins, moving and removing '#' around the config. I even uninstalled and reinstalled the whole plugin, and edited the config (only the group formats part without editing anything else) and still no dice.

I also have VAULT installed.

There will be 3 pastebins for you to look at 

                 1 is just the Chat Formatting part of the config
                 2 is the FULL config in case that is what you want
                 3 is the startup log for the server 

I hope you can help, and if this is an issue with the plugin, then hopefully a fix is in order,

link 1: http://pastebin.com/g6ZL1jP2
link 2: http://pastebin.com/ZNBnrfmK
link 3: http://pastebin.com/WnJvYrRM

**Comment by eUipKh** [comment]
Change this:
```
  // Should Factions set the chat format?
  // This should be kept at false if you use an external chat format plugin.
  // If you are planning on running a more lightweight server you can set this to true.
  "chatSetFormat": true,
```

to:
```
  // Should Factions set the chat format?
  // This should be kept at false if you use an external chat format plugin.
  // If you are planning on running a more lightweight server you can set this to true.
  "chatSetFormat": false,
```

In MassiveCore-Factions config also you could try updating EssentialsX (2.0.1-b467)

**Comment by Dannysan626** [comment]
I feel like an idiot.... I have used factions before and I forgot that it can change the chat layout. Sorry -.-
