### ISSUE TITLE
[REQUEST] Cool down for commands

### ISSUE THREAD

**Issue by TheJadyha** [EssentialsX/Essentials#110]
Just like the cost for commands in the default essentials config, You can put a cool down on any command you choose. It would sort of look like this:
# Cool Down In Seconds For Commands

commandCoolDowns:
- heal 60
- feed 40
- mycustomcommand 38

**Comment by vemacs** [comment]
Good idea, I hate having to put in every last alias for a command in boosCooldowns

**Comment by Botanistt** [comment]
Please add this and different cooldowns for different groups!
Thank you so much!

**Comment by Terrobility** [comment]
https://gyazo.com/1cd77be5438aac998533ef684c53aabf
I guess boosCooldowns not gonna be the "only good cooldown plugin" any more :smile:

**Comment by Joomzy** [comment]
Also, vouching for this idea, would help alot! Especially with teleportation requests

**Comment by Joomzy** [comment]
How is the progress on this? Could really use it soon.

**Comment by EvilOlaf** [comment]
+1. Teleport delays are always handy if used on a PVP server. As for now I realize this by using a 3rd party plugin.

**Comment by EncryptedPixel** [comment]
+1

**Comment by drtshock** [comment]
+1

**Comment by SupaHam** [comment]
Any discussions may be continued in #692.

**Comment by PsychoLynx** [comment]
So was a bypass permission ever added to the command cooldown in the end?

**Comment by SupaHam** [comment]
@PsychoLynx Nope. I'll add that now. Look out for a new build.
