### ISSUE TITLE
suggestion: Infinite Dispensers/Chests with Free-Sign

### ISSUE THREAD

**Issue by Andre601** [EssentialsX/Essentials#1100]
My Idea is, that if you place a Free-Sign at a Block with inventory (Dispenser, Dropper, Chest, ...) that this block will always be filled with the item.
This would be usefull, to maybe make a trainstation.

**Comment by mdcfe** [comment]
I don't think this is a particularly essential feature considering the point of the `[free]` sign is to let people right click it for free items. If other signs could already affect inventories then it would make more sense, but as far as I'm aware they currently can't do that.
