### ISSUE TITLE
Why message's commands are blocked in jail ? | & FactionChat messages not blocked during mute

### ISSUE THREAD

**Issue by dartasen** [EssentialsX/Essentials#1101]
When a player is jailed, he can't /m|/t|/w|/msg|/tell|/whisper or /r.
It's a bit annoying...

Also another problem is that Factions' message (FactionChat) aren't blocked when player is muted.

**Comment by eUipKh** [comment]
I use this:

```
# Mute Commands
# These commands will be disabled when a player is muted.
# Use '*' to disable every command.
# Essentials already disabled Essentials messaging commands by default.
# It only cares about the root command, not args after that (it sees /f chat the same as /f)
mute-commands:
  - f
  - factions
  - factions:f
  - factions:factions
```

**Comment by dartasen** [comment]
For the mute's problem, I have found a solution : this works when we load FactionChat after EssentialsX

But for the jail I need a fix :/
