### ISSUE TITLE
MultipleHomes does not work

### ISSUE THREAD

**Issue by pablochv** [EssentialsX/Essentials#1102]
The MultipleHomes does not work, because with the normal Essentials is nothing more than using the Command
/ Sethome (HomeName)
/ Home (HomeName)
But with this plugin is not the same, I do not know if it is because it has to be with another command which I can not find, because when I put those commands that I said previously in minecraft what I get is what
Correct Usage: <command>

And the sethome others does not help either
I like the same
Correct Usage

**Comment by smmmadden** [comment]
Not saying this is the answer to the issue, but it is an alternative if you want to support multiple homes, kits and warps.  https://www.spigotmc.org/resources/essentialsx-extras.23822/ 

I use it and works great for 1.11.2.

**Comment by Kakifrucht** [comment]
Multiple homes, kits and warps is all perfectly working. You have an issue with your setup. Ensure that you have given the proper permissions to set multiple homes, check console for exceptions/errors. Try to enable debug mode and check console output again.

**Comment by mdcfe** [comment]
@smmmadden All that plugin does is extend EssX.

@PabloGamer380YT What other plugins do you have installed? Are you sure your permissions are configured correctly?

**Comment by smmmadden** [comment]
@md678685 - yes, I know all it does is extend EssentialsX.  I stated it was an alternative, not as a solution.  If they used this plugin and it still didn't work, it would show beyond any doubt, there is a configuration issue.

**Comment by pablochv** [comment]
I already solved it, the results that I have the Plugin Skript, and apparently that Plugin installs me a Skript by default of Houses and conflicts with the one of Essentials that was what happened, I'm sorry xD
My delay :,v
