### ISSUE TITLE
silentquit permission does not work

### ISSUE THREAD

**Issue by VladStarr** [EssentialsX/Essentials#1108]
Hi

I've noticed that while I'm op and with setting allow-silent-join-quit, the silentquit works.
But if I try to give permission essentials.silentquit to non-op player, it won't work. On the other hand, SilentJoin work pretty well.

And also I suggest adding op-permissions setting, that will deny ops from using all of plugin commands.

Spigot 1.11.2-R0.1, EssentialsX latest build, GroupManager

**Comment by mdcfe** [comment]
This is likely caused by using GroupManager (see #1677). We no longer support GroupManager and recommend you switch to LuckPerms, which can cope with offline players properly through Vault unlike GroupManager.

**Comment by ElgarL** [comment]
Can you explain this issue in better detail? As far as I know GroupManager handles offline players just fine via vault.
