### ISSUE TITLE
Bug on /nick Using & Color code

### ISSUE THREAD

**Issue by DMFCraftBR** [EssentialsX/Essentials#1109]
https://hastebin.com/xuyuqoxece.vbs

Bug?

**Comment by mdcfe** [comment]
Try without the underscore (alfanumerico = alphanumeric/only contains letters and numbers).

**Comment by DMFCraftBR** [comment]
Can not use color?

**Comment by mdcfe** [comment]
Don't put the `_` at the end of the command. The colour should work fine.
