### ISSUE TITLE
[REQUEST] Mass Player Files Editing.

### ISSUE THREAD

**Issue by TheJadyha** [EssentialsX/Essentials#111]
Let's create a story together;

Dexter donates to my server. One of the features he gets as donator is the ability to send mail to the entire server with /mail sendall {message}

```
      (Never give any player this permission btw)
```

Dexter gets raided on my server and decides to quit forever. But before he leaves, He sends a mass message out to every single player that has connected to my server. His message reads the following.

"/mail sendall Hey peeps leave this server and play MinePlex!!!!!! BAII"

Now, Every single player is going to see this message. And if I (the admin) Don't want everyone to see it. I have to spent 3 years in the essentials player files manually removing the message data. This can be a pain for a server that has over 20k unique users.

Then comes along EssentialsX! The epic feature that let's admins wipe all mail from the universe!!

The command could look something like this;
- /mail clearall 10

The 10 stands for 10 minutes. EssentialsX won't remove any mail sent longer than 10 minutes ago. That may be a hard feature to implement but may be useful.

The bulk of this feature could be used for many more things.
- /eco resetall {balance}
- /mail resetall {time}
- /kitsresetall 

Let me know what you think guys :)

**Comment by vemacs** [comment]
This can be easily abused by operators and seems like a feature with incredibly limited appeal. I don't see us implementing this, it would be much safer for admins to use command-line automation (sed, awk) to resolve these
