### ISSUE TITLE
Error Message repeatedly spamming console

### ISSUE THREAD

**Issue by YouGamePlayHD** [EssentialsX/Essentials#1113]
Hey,
whenever a player joins the server, the console is telling me this:
http://pastebin.com/mTnfyN7y
Can you tell me what is wrong?

**Comment by mdcfe** [comment]
[Update to the latest build.](https://ci.drtshock.net/job/EssentialsX/lastSuccessfulBuild)

**Comment by YouGamePlayHD** [comment]
Thanks, it fixed the problem.
