### ISSUE TITLE
Store UUID on Trade signs

### ISSUE THREAD

**Issue by Volander** [EssentialsX/Essentials#1117]
Any possibility to have trade signs store store the players uuid so when they change name it won't be a problem.

**Comment by mdcfe** [comment]
EssentialsX doesn't track signs to avoid complexity, but rather determines what to do with the sign once it's placed and then each time it is right-clicked. This means that we don't actually save any hard data relating to the sign.

@drtshock @SupaHam Thoughts?

**Comment by drtshock** [comment]
This would require us to start persisting who owns each sign. I agree, it would be the right way to do things so I'm not going to disagree. Given that, I don't think it'd be very high on the todo list.

**Comment by mdcfe** [comment]
The alternative is to set `MetadataValue`s on the sign that track the UUID when the block is placed, which would avoid the overhead of storing a permanent list to track signs.

**Comment by drtshock** [comment]
That's true, but if we're going to start storing it, I think it'd be nice to be able to search for signs that you own / allow admins to search for signs by player.

**Comment by JRoy** [comment]
closing in favor of #81
