### ISSUE TITLE
EssentialsPlayerListener being high in timings

### ISSUE THREAD

**Issue by Sikatsu** [EssentialsX/Essentials#1118]
Everytime I use /timings, the EssentialsPlayerListener event from EssentialsX is really high. When I showed my timings with low TPS on Spigot, they claimed Essentials is one of the issue givers.

https://timings.spigotmc.org/?url=cucinerudi

Might be worth a shot to look at it?

**Comment by mdcfe** [comment]
If this is still a problem, feel free to reply (with a new timings report) and I'll reopen the issue.
