### ISSUE TITLE
Potions in kits aren't working properly

### ISSUE THREAD

**Issue by daniexxtra** [EssentialsX/Essentials#1119]
In config.yml file kits, splash_potion and lingering_potion are not recognised as a potion, so if I add effects to it, the game says kit is improperly defined, and console says that it's not a potion.
And another little issue is that /ci doesn't clear armour.
MC 1.11.2

**Comment by vemacs** [comment]
What exact items are you putting in the kits? /ci didn't clear armor in previous versions of Minecraft, so we decided to keep that behavior.

**Comment by OasisArtisan** [comment]
i have the same problem exactly with the splash potions.
i tried this:
 - SPLASH_POTION 1 name:&rPotion_of_Levitation effect:levitation power:1 duration:20
and this
 - 438:0 1 name:&rPotion_of_Levitation effect:levitation power:1 duration:20
and this
 - 373:16397 1 name:&rPotion_of_Levitation effect:levitation power:1 duration:20
and nothing worked

**Comment by daniexxtra** [comment]
I had the same issue as @omar31, I can't get custom splash or lingering potions work in kits

**Comment by triagonal** [comment]
Closing in favor of #2867.
