### ISSUE TITLE
[REQUEST] Custom Death Messages

### ISSUE THREAD

**Issue by TheJadyha** [EssentialsX/Essentials#112]
It would be cool if essentialsx let us edit Minecraft's default death messages. Not only could we be able to edit the messages, But we could make it so that different messages display randomly when a player dies, so we don't see the same old message each time a player dies from an event. It would look something along the lines of this;

drowned - drowned.txt
was slain by - slain.txt
was shot by - shot.txt
was killed by - killed.txt
fell out of the world - void.txt
tried to swim in lava - lava.txt
went up in flames - flames.txt
burned to death - burned.txt
blew up - blewup.txt
was fireballed by - fireballed.txt
was killed by magic - magic.txt
suffocated in a wall - suffocated.txt
was pricked to death - pricked.txt
hugged a cactus, but the cactus hugged back - pricked.txt
was shot by arrow - shotbyarrow.txt
died - died.txt

Thank you and let me know what you think :)

**Comment by drtshock** [comment]
There are plenty of other plugins that do this already.
http://dev.bukkit.org/bukkit-plugins/death-messages/
