### ISSUE TITLE
Permission to limit /nick

### ISSUE THREAD

**Issue by neokyle** [EssentialsX/Essentials#1121]
I would like to be able to allow my players the ability to change there nickname but with some restriction. Essentially the permission would allow a player to change their nickname but it would have to match the first X characters of their original name.

This would allow players to shorten there names, and keep nicknames reasonable.

Example permission: essentials.nick.limit.4

With the above example a players nickname would have to start with the same 4 characters that there actual name begins with.

**Comment by pop4959** [comment]
I am closing this because the feature is way too specific in scope to include in Essentials.
