### ISSUE TITLE
users are unable to use unstable enchant signs

### ISSUE THREAD

**Issue by Angel9001** [EssentialsX/Essentials#1124]
Not sure if this is an issue or not but going to add it her incase it is

So the problem I'm haveing is that users can't use the [Enchant] sign when there is an unstable enchantment the sign will provide. The sign works if u are opped so the sign

I did some testing with trying to give default users the premission

essentials.enchant
essentials.enchantments.*
essentials.enchantments.allowunsafe
essentials.sign.use.*

so now a default user was able to just flatt out use the enchant command to make unstable enchants wile holding a item in there hand, but they where still unable to add unstable enchant to items via the sign

the error that pop up for players:. (not op's)
Error: Enchantment level is either too low or too high (given 10,bounds are 1 to 3)

the essentialsx config has the allow unstable enchants set to true

so my question is there a premissions I don't know about that allow the op's to use this sign fine wile players can't or is it borked somehow?

**Comment by mdcfe** [comment]
Is this still an issue?

**Comment by pop4959** [comment]
Please open a new issue with detailed steps to set up and reproduce the issue if this is still an issue for you.
