### ISSUE TITLE
/clear ** don't remove item in left hand

### ISSUE THREAD

**Issue by VladStarr** [EssentialsX/Essentials#1125]
I tried both /clear and /clear **, both of them don't clear left hand slot.
Please fix that :)

**Comment by vemacs** [comment]
Planned, I'll do it this week

**Comment by CoolLord22** [comment]
Any word on this issue? the command still isn't clearing the off hand slot.

**Comment by leonardo-dgs** [comment]
In my server build (1.13), with the latest EssentialsX version, the command /clear works even for items in the off hand

**Comment by triagonal** [comment]
This was fixed in 983f3a7.
