### ISSUE TITLE
God

### ISSUE THREAD

**Issue by gaizkaeu** [EssentialsX/Essentials#1127]
If you activate the god mode, with the command /god don't work, you can be hit by other players and mobs.

Thanks.

**Comment by mdcfe** [comment]
What server version (`/version`) and EssentialsX version (`/essentials`) are you running?

**Comment by gaizkaeu** [comment]
If I put the command /essentials: 
09.02 22:39:28 [Server] INFO CONSOLE issued server command: /essentials 
09.02 22:39:28 [Server] INFO /<command> <reload/debug>
09.02 22:39:28 [Server] INFO Essentials ha cedido los siguientes comandos a otros plugins:
09.02 22:39:28 [Server] INFO kick => LiteBans:litebans:kick, t => Towny:town, mute => LiteBans:litebans:mute, tempban => LiteBans:litebans:tempban, ban => LiteBans:litebans:ban

If I put the command /version
09.02 22:40:01 [Server] INFO This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
09.02 22:40:01 [Server] INFO You are 583 version(s) behind

Some days ago I downloaded the last version of Essentials X

Thanks.

**Comment by mdcfe** [comment]
Use `/ess reload` from in game to show the version.

Also, use Spigot, not CraftBukkit, for 1.8.

**Comment by gaizkaeu** [comment]
11.02 23:56:26 [Server] INFO Using locale es_ES
11.02 23:56:26 [Server] INFO Essentials ha sido recargado. La versión es 2.0.1-b467.

**Comment by mdcfe** [comment]
Closing due to lack of response regarding CraftBukkit. If this is still a problem, feel free to reopen the issue.
