### ISSUE TITLE
Right clicking animals with milk doesn't convert to babies

### ISSUE THREAD

**Issue by Deliphin** [EssentialsX/Essentials#1129]
Lines 496-497:
```
# Toggles whether or not right clicking mobs with a milk bucket turns them into a baby.
milk-bucket-easter-egg: true
```

Right clicking them with a milk bucket does not convert them to babies.
Left clicking does.

This either needs to be fixed by editing the comment to say left click, or editing code to make it look for a right click.

**Comment by mdcfe** [comment]
This was fixed by 37acdc18f24ddc3fb70c65b1f71de04b9990f1a9 and is present in any recent version. (Thanks to @triagonal for the heads up.)
