### ISSUE TITLE
[REQUEST] Trading system.

### ISSUE THREAD

**Issue by TheJadyha** [EssentialsX/Essentials#113]
Running an RPG server? Running an Faction server? Are you tired of people complaining about scammers and would you prefer to have every trade safely done? This could be done with EssentialsX!

I know i'm going a bit overboard when it comes to suggestions. But my brain is filled with cool ideas. I need to learn how to code myself. (better anyway) Let's get started.

How does it work?
- Imagine you have player 'steve' and player 'notch'. Notch wants to trade with steve, so he sends him a request using a command (/trade (username))
  Steve wants to trade as well, so he accepts the request.
- Now an inventory pops up containing empty slots. Both notch and steve each have a different side.
- Now the 'start' of the trade can begin. Notch can simply click items in his inventory that he wants to trade, and Steve can do the same.
- After they both selected enough items that they want to trade, they simply click the trade button.
  (A Button within the trade GUI)
- They see that the 'button' becomes a orange button, and they can no longer add/remove items from the GUI, in order to prevent late changes/scamming.
- After they both 'confirm' the transaction, the items will be credited to both players, and they live happily ever after.

**Comment by vemacs** [comment]
This seems to have been covered by other trading plugins using Vault and doesn't seem to belong in Essentials. Sorry, but we're not willing to support something so complex and reinvent the wheel.
