### ISSUE TITLE
Improving Vanish & Seen

### ISSUE THREAD

**Issue by RI4Z** [EssentialsX/Essentials#1133]
Hello.

Just had a few features to spice up the good old vanish command.
As it is quite boring, and many people tend to get their own vanish plugin. So why not make the essential vanish command actually become more used & useful?

1. The "invisible hand" thing.
When vanishing with essentials, your hand dissapears. Which is to be fair, quite annoying. A fix to making it visible again is by healing yourself etc. But that is not something I want to do every single time I vanish.
2. Create a vanished subtitle, so it displays on your screen constantly, with a small text "You are invisible!"
or something like that. And unvanish "You are no longer vanished!" (for like 2-3 seconds).

3. This one is more about how /seen handles vanished players. As of right now, if you /seen riaz and player Riaz is currently vanished. It will display with dark red text that the player you're trying to seen have never joined the server before. (And also, even /seen on players that actually have never joined the server before gives a different message) /seen should tell the user that you are offline since xxx time ago.

I actually have abused this method on another server to know when the owner & admins are vanished, because /seen basically tells me that they are vanished.

Hope this could be implemented, thanks.

**Comment by pop4959** [comment]
Closing this issue for now, but if anyone feels like implementing it feel free.

As for /seen, since it is meant as more of a staff command, I don't think this is much of an issue. Although, I guess there may be some servers that do it anyway. I'd make a separate issue for this though (if it's not fixed already).
