### ISSUE TITLE
Disconnecting when pressing "e"

### ISSUE THREAD

**Issue by woodiertexas** [EssentialsX/Essentials#1134]
I used the latest build on my server and whenever I pressed "e" to open my inventory, it disconnected me and here is the error: [personal information removed] and my plugin list: [personal information removed]

**Comment by mdcfe** [comment]
The problem doesn't seem to be directly caused by Essentials. 
Could you try stopping the server, *backing up* and deleting/moving your user data file (the one in the screenshot) and restarting the server?
