### ISSUE TITLE
AFK message doesn't seem to be working

### ISSUE THREAD

**Issue by akashagarwal7** [EssentialsX/Essentials#1135]
I'm trying AFK message on a test server only with the Essentials plugin. When I try something like `/afk My message` or `/afk 'My message'`, it doesn't work. What am I doing wrong? Or is there a config line that needs to be there or set differently? TIA.

**Comment by mdcfe** [comment]
You need to set `userIsAwayWithMessage` in `messages.properties` to something which includes `{1}`. You might have to copy the messages.properties file from [here](https://github.com/drtshock/Essentials/raw/2.x/Essentials/src/messages.properties) to your `plugins/Essentials` folder first.

**Comment by akashagarwal7** [comment]
Just a note, you also need to enable the locale file comment in the configuration, I was missing that out too. Thanks!
