### ISSUE TITLE
PermissionsEx prefix appearing in MOTD and toggle commands.

### ISSUE THREAD

**Issue by attributeerror** [EssentialsX/Essentials#1137]
For some reason, whenever I do /fly it puts my PermissionsEx group prefix at the start of my name and it can get really annoying.
Is there any way to stop EssentialsX from hooking into PermissionsEx/Vault and letting DeluxeChat do the work?

**EDIT:** Screenshot: http://prntscr.com/e9c28s

**Comment by mdcfe** [comment]
Sounds like DeluxeChat or another plugin is changing your display name - I'm fairly certain Essentials doesn't normally do this.

**Comment by mdcfe** [comment]
In retrospect, you most likely have `add-prefix-suffix` enabled, causing this. Try disabling that option and restarting your server.
