### ISSUE TITLE
EssentialsX [NB NH] Error

### ISSUE THREAD

**Issue by BuilderDan** [EssentialsX/Essentials#1138]
For some reason my chat is doing this:

http://i.imgur.com/OMkY9ct.png

Here are the Configs for my permissionsEx and EssentialsX:

Essentials:
http://pastebin.com/zkxUGE3S

PermissionsEx:
http://pastebin.com/AAgyz3Ef

**Comment by mdcfe** [comment]
* What EssX version are you running? `/ess`
* What Spigot version are you running? `/version`
* What other plugins do you have installed? `/plugins`

**Comment by BuilderDan** [comment]
My EssX ver is: 2/0/1-b467
Spigot is: 1.11.2-R0.1-SNAPSHOT (8 Vers Behind)
Plugins List: http://i.imgur.com/6xy2RYE.png

**Comment by mdcfe** [comment]
Does this problem go away if you disable `change-displaynames` in your EssentialsX config? If not, this probably isn't an EssentialsX issue.

**Comment by BuilderDan** [comment]
I figured out what the problem was by disabling each plugin until it went away, turns out it was Jobs. Thanks for the help.
