### ISSUE TITLE
Suggestion: Real time

### ISSUE THREAD

**Issue by Borc55** [EssentialsX/Essentials#1139]
Greetings, dunno if this is contained within any of the EssentialsX versions, if it is, I didn't find it. But it would be cool if Essentials knew the timezone of the server, and was able to print out real time with (for example) command /clock or something like that.

**Comment by mdcfe** [comment]
I don't see the purpose of this being part of EssentialsX, as opposed to just being part of most operating systems and any reasonable search engine.
