### ISSUE TITLE
Add Crapples in the itemdb

### ISSUE THREAD

**Issue by Terrobility** [EssentialsX/Essentials#114]
For item id 322 in the itemdb, you should add crapple as a short name. 
People usually distinguish a regular gapple from an enchanted gapple by calling it a crapple.

**Comment by vemacs** [comment]
I sincerely hope you're joking

**Comment by Kakifrucht** [comment]
+1, very important

**Comment by mbax** [comment]
> I sincerely hope you're joking

![No this is patrick](http://38.media.tumblr.com/tumblr_m9f9jh0WNH1rqdq2ko2_500.gif)

**Comment by Terrobility** [comment]
@vemacs How is this a joke?

**Comment by LaxWasHere** [comment]
Here ya go, https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/items.csv do it yourself.

**Comment by HunterGPlays** [comment]
Bu-- but you could add it in the default releases!

**Comment by vemacs** [comment]
We don't care to introduce immaturities such at these in default releases, especially since literally nobody on my 100+ player factions server refers to normal apples as these

**Comment by Terrobility** [comment]
@vemacs In all seriousness, I have been on several factions servers where 300+ people refer to them as "crapples/craps" (god apples) and "gapples/gaps" (enchanted golden apples). It is not an immaturity, just a common term.
"Everybody calls them crapples, what is he on about" - This guy called Kevin who I was just Skyping while on this one factions server where loads of PvP goes down. It's like how everyone calls potions "pots" and how everyone says "gear up" but they don't refer to actual gears.

**Comment by vemacs** [comment]
Still a curse word, you can easily add it yourself.

**Comment by zRiaz** [comment]
+1 for Gapple as Enchanted Golden Apple & Crapple for Regular Golden Apple

**Comment by vemacs** [comment]
Add it to items.csv in your Essentials directory and `/ess reload`.
