### ISSUE TITLE
Suggestion: Add API method to set the "/back" location

### ISSUE THREAD

**Issue by soluciones-ya** [EssentialsX/Essentials#1142]
We need it for AACAdditionPro (the freecam check is teleporting players every X ticks and it changes the /back location).

**Comment by GriffinCodes** [comment]
Or just listen to the PlayerTeleportEvent

**Comment by Kakifrucht** [comment]
It's already there: https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/User.java#L227
