### ISSUE TITLE
Message file

### ISSUE THREAD

**Issue by ArchieIrving** [EssentialsX/Essentials#1146]
**On version 2.0.1-b460**
It doesn't seem to be loading the message file at all so I can't edit the messages? If I paste an old one it, it uses it, but it isn't generating a new one.

**Comment by mdcfe** [comment]
Copy it from the jar for an up-to-date one. Also, make sure the `locale` setting is set in the config.

**Comment by ArchieIrving** [comment]
Copy it from where?
That setting is enabled.

**Comment by Kakifrucht** [comment]
Open the EssentialsX.jar with an archiving tool like WinRAR/7zip and extract the applicable language file into your Essentials folder. This doesn't happen automatically.

[Or just download it](https://github.com/drtshock/Essentials/tree/2.x/Essentials/src)
