### ISSUE TITLE
EssentialsX Locale - Missing Messages

### ISSUE THREAD

**Issue by op-Hen** [EssentialsX/Essentials#1147]
Hey there,

I’m currently looking at editing the messages_en.properties file for the EssentialsX locale.

It’s come to my attention that command hints such as just typing /pay, /setwarp etc. just print a white message and that there is no ability to customise the messages in the locale file. I was wondering if this could be a future addition?

https://gyazo.com/74ed6e235eb7b2b92ecbc77c1154d101

Was told to cc @SupaHam here.

**Comment by Kakifrucht** [comment]
These messages are read from the plugin.yml afaik. So that would be a no, not worth it, for some they can be changed to the config file, globally will most likely not happen.

**Comment by mdcfe** [comment]
Closing in favour of #1795.
