### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by jacklollz2** [EssentialsX/Essentials#1148]
The contents of this have been erased.

**Comment by mdcfe** [comment]
* Could you post a screenshot of the message? I haven't seen this occur before.
* What EssentialsX version are you running? `/ess`
* What Spigot version are you running? `/version`

**Comment by jacklollz2** [comment]
Sigot: Latest version.
ESS: Latest version & snapshot versions.
http://puu.sh/ug3ya.png
[After typing in /spawnmob, and then /spawnmob snowman](http://puu.sh/ug3FX.jpg)
Directory: E:\Servers\Mc 1.11.2.
Storage type: HDD WD Black 5tb.
OS: Windows 10 post anniversary.
Server launch options (tried with just basic launch options):
java -server -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+UseGCOverheadLimit -XX:ParallelGCThreads=8 -DJINTEGRA_NATIVE_MODE -DJINTEGRA_COINIT_VALUE=0 -Dsun.io.useCanonCaches=false -XX:ThreadPriorityPolicy=42 -XX:CompileThreshold=10000 -XX:+TieredCompilation -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseLargePages -XX:+UseAdaptiveGCBoundary -XX:+UseBiasedLocking -Xverify:none -XX:UseSSE=4 -XX:+UseThreadPriorities -Djava.net.preferIPv4Stack=true -XX:+OptimizeStringConcat -XX:+UseFastAccessorMethods -Xrs -Xmx6G -Xms2G -Xmn2G -Xss2G -XX:+AggressiveOpts -XX:MaxPermSize=128m -XX:+DisableExplicitGC -d64 -Djline.terminal=jline.UnsupportedTerminal -Xnoclassgc -jar spigot-1.11.2.jar nogui

**Comment by jacklollz2** [comment]
Update: After turning on ESS debug, the error printed in the console.
http://puu.sh/ug3Lz.jpg

**Comment by jacklollz2** [comment]
Also, could you update spawnmob to use the latest mobs?

**Comment by mdcfe** [comment]
If this is still an issue, could you respond with whether this still occurs on the latest version?

**Comment by jacklollz2** [comment]
Is is no-longer an issue and has been fixed with updates.
