### ISSUE TITLE
/spawnpoint safe tp always enabled

### ISSUE THREAD

**Issue by maduranma** [EssentialsX/Essentials#1149]
Hello,
Even if I set to force disabled the tp safety (with all combinations), spawnpoint acts always safe.
If I remove essentialsx spawn from the server, it TP me on the center when I die and go to the spawnpoint.

**Comment by mdcfe** [comment]
If this is still an issue, could you elaborate on how it always "acts safe"?

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to reopen the issue.
