### ISSUE TITLE
[Request] Ability to tempban IPs?

### ISSUE THREAD

**Issue by denizaygundev** [EssentialsX/Essentials#115]
Not sure if this is possible already but a "/tempbanip [username/IP] [time] [reason]" would be great.

**Comment by EvilOlaf** [comment]
Never mind.

**Comment by denizaygundev** [comment]
The command doesn't exist...

I've tried /tempbanip and no luck.

**Comment by EvilOlaf** [comment]
Ah lol xD. Sorry, totally messed up the repositories. Never mind my comment, sorry.

**Comment by denizaygundev** [comment]
So could this be reopened?

**Comment by aeyu** [comment]
Bump !
Would be a GREAT idea imho.

**Comment by pop4959** [comment]
Looks like this should be possible through the Bukkit API, there just isn't a command for it yet.
