### ISSUE TITLE
1_8_R1Provider pom.xml Typo

### ISSUE THREAD

**Issue by geitir** [EssentialsX/Essentials#1151]
<url>file:${project.basedir}/lib</url>

should be 

<url>file:${project.basedir}\lib</url>

At least for me here on windows

**Comment by mdcfe** [comment]
Isn't this corrected automatically by Maven for Windows users?

**Comment by mdcfe** [comment]
Closing this, since as far as I know Maven should deal with forward slashes without any issue on Windows.
