### ISSUE TITLE
Command blocks

### ISSUE THREAD

**Issue by ardentcrest** [EssentialsX/Essentials#1153]
When using commandblocks the server info panel gets flooded with

[INFO]  CommandBlock at *,*,*,*,8 issued server command: /********
or
[INFO] ******* issued server command: /clear ********

This only happens when Essentials is loaded in to the server. Is there any way to stop this constant flow of [INFO] as it is really annoying. 

Also tested with no other plugins loaded and still happens.

also used /gamerule logAdminCommands false and still happens.

also silent-commandblock-console to true, still happens.

and /gamerule commandBlockOutput false

**Comment by ardentcrest** [comment]
Also tested with no other plugins loaded and still happens.

**Comment by ardentcrest** [comment]
So no help

**Comment by ardentcrest** [comment]
Still nothing

**Comment by mdcfe** [comment]
This is a [deliberate feature](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/Essentials.java#L464), but I agree that it's spammy - either this message should be made toggleable, or there should be a blacklist for command block log messages (to hide these messages for specific commands when run by a command block).
