### ISSUE TITLE
(Request) (enhancement) Staff mail inbox

### ISSUE THREAD

**Issue by RealmportalMC** [EssentialsX/Essentials#1156]
the idea is to send mail to a separate inbox that has some permissions like essentials.staffmail.read or something Staff could leave offline notices for others staff members. Still keeping regular /mail

**Comment by mdcfe** [comment]
This seems like the whole point of a ticket plugin. If you really don't want to add a ticket plugin, then just allowing players to mail staff seems like the best idea, but this seems out of scope as an EssentialsX feature.
