### ISSUE TITLE
/setspawn not working still

### ISSUE THREAD

**Issue by tccummings** [EssentialsX/Essentials#116]
When I type the old Essentials /setspawn command I just get feedback from the client saying unknown command.  I looked at /help essentials and noticed there isn't a /setspawn command anymore.....so how do I set a custom spawn point now?

**Comment by Agazed** [comment]
It's working for me... Maybe the plugin is conflicting with another one.

**Comment by vemacs** [comment]
Is setspawn in disabled-commands? Do you have any other plugins that register the same command?

**Comment by tccummings** [comment]
I have GroupManager, WorldEdit, WorldGuard, Vault, EssentialsX, ClearLag, and GriefPrevention....although I added GriefPrevention after I wrote this post.  Im running spigot 1.8.8.  Unless setspawn is disabled at install, I didn't disable it.  This is a new server.  Last time I ran a server was with the old Essentials and it worked fine and I had all of these plugins installed.

**Comment by drtshock** [comment]
You need to have essentialsspawn.

**Comment by tccummings** [comment]
Thanks Trent, I got it.  When I downloaded essentialsx from the Bukkit
plugins site, I only got the essentialsx.jar instead of the whole thing.  I
ended up finding all of the jars on another site.  Everything is working
now.

**Comment by drtshock** [comment]
https://ci.drtshock.net/job/EssentialsX has everything.

**Comment by tccummings** [comment]
oh good, thats where I ended up downloading everything.  I bookmarked the
page.  Thank you!
