### ISSUE TITLE
Splash / Lingering potions and /potion

### ISSUE THREAD

**Issue by GeeorgeUK** [EssentialsX/Essentials#1166]
Been trying to create potions with custom effects using the **/potion** command, and I've noticed that when I try to type /potion on a creative spawned splash potion, it returns the message:

> Error: You must be holding a potion to apply effects to it.

I am running EssentialsX version: 2.0.1-b468
I am running CraftBukkit version: git-Spigot-65a0347-a552117 (MC 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**Comment by Blamo27** [comment]
@md678685 Do you know, when will this issue be fixed ?

**Comment by Blamo27** [comment]
@md678685 Still not fixed ?

**Comment by aolko** [comment]
Any ETA for a fix? /potion apply seems not working as well

**Comment by SupaHam** [comment]
~Running this on git-Spigot-325fbc7-e40c9ef and b566 and /potion adds effects and `/potion apply` applies them to me without consuming the item just fine.~

**Comment by SupaHam** [comment]
This has been fixed in b6aea0a. You can grab the fix from [build 567](https://ci.ender.zone/job/EssentialsX/) on the CI server.

**Comment by aolko** [comment]
just did, `/potion [apply] effect:speed power:6 duration:600` doesn't work on empty potions/water bottles

**Comment by mdcfe** [comment]
Water bottles aren't potions, so it [shouldn't be possible to add effects to water bottles](https://github.com/EssentialsX/Essentials/commit/b6aea0a5f886a7d617a85b6c0bf073323ee1005a#diff-66294c78ccc726650f0c6c47204fd208R50). Try making a base potion without any effects first.

**Comment by aolko** [comment]
same on Mundane,Thick and Awkward potion

**Comment by SupaHam** [comment]
I'm pretty sure they're all water bottles. What does it say when you hover
over the item when you have item debug on? (F3 + H)

**Comment by aolko** [comment]
![image](https://user-images.githubusercontent.com/581458/34668581-1a5e52e6-f47f-11e7-92da-cf7ce6d90621.png)

**Comment by SupaHam** [comment]
Drink it and see what happens. :)

**Comment by aolko** [comment]
nothing, it should indicate the effects
therefore /potion is still broken
