### ISSUE TITLE
[EssentialsX] {Chat} Color Codes

### ISSUE THREAD

**Issue by VikingOmu** [EssentialsX/Essentials#1167]
Hello dear developers, thank you for you whole work, you did an amazing job here!
Since the last build I have some problems with the colors, "&5" and "&d" are the same color, could you please fix that? Thanks!

**Comment by mdcfe** [comment]
* What EssentialsX version are you running? `/essentials`
* What Spigot version are you running? `/version`
* Could you upload a screenshot and link it here?

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to reopen the issue.
