### ISSUE TITLE
/setspawn not working still

### ISSUE THREAD

**Issue by tccummings** [EssentialsX/Essentials#117]
When I type the old Essentials /setspawn command I just get feedback from the client saying unknown command. I looked at /help essentials and noticed there isn't a /setspawn command anymore.....so how do I set a custom spawn point now?  I have GroupManager, WorldEdit, WorldGuard, Vault, EssentialsX, ClearLag, and GriefPrevention....although I added GriefPrevention after I wrote this post. Im running spigot 1.8.8. Unless setspawn is disabled at install, I didn't disable it. Which config file would I check to see if its disabled. This is a new server. Last time I ran a server was with the old Essentials and it worked fine and I had all of these plugins installed.  I am set to Owner in GroupManager so I should have all commands available.  Not sure why Vemacs closed this before I could answer.

**Comment by vemacs** [comment]
You don't have EssentialsSpawn installed. /setspawn is a command in EssentialsSpawn, not Essentials. Install the EssentialsSpawn JAR from the CI.
