### ISSUE TITLE
Command cost not working (/spawnmob)

### ISSUE THREAD

**Issue by InterVi** [EssentialsX/Essentials#1172]
`spawnmob-wolf: 900`

Only spawnmob not working, money is not taking. I use latest version. Server version: git-Spigot-283de8b-aa522c9 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**Comment by InterVi** [comment]
forum discussion: https://www.spigotmc.org/threads/essentialsx-command-cost-spawnmob-not-working.226066/

**Comment by pop4959** [comment]
You need to describe your issue more clearly for us to understand what you want. Please make a new issue if this is still a problem.
