### ISSUE TITLE
Essentials Protect Need new versioN! 

### ISSUE THREAD

**Issue by minecraftraiding** [EssentialsX/Essentials#1173]
https://gyazo.com/4d8910b1d7259b9d959da12e8eb1ad6e 
I need version b467 to have it work! cant seem to find.

**Comment by smmmadden** [comment]
what you need is the same versions of Essentials for each plugin. Mixing of them aren't supported.  Click on the <> Code tab above, scroll down and click the download button.  On the left side of the page is all the version.  Select the versions you need e.g. 468 is the latest and stable version.
