### ISSUE TITLE
NPC accounts are shown in {unique}

### ISSUE THREAD

**Issue by aeonlamb** [EssentialsX/Essentials#1176]
Kind of a nitpicky thing, but I like to have the variable {UNIQUE} used in my server's motd, so people can see the number of unique players that have joined the server. The problem is that {UNIQUE} lists all of the accounts essentials has saved, which includes accounts it recognizes as npcs. If it wouldn't be too much trouble it would be great if npc accounts could be excluded from this count. Thanks for all the hard work, it is really appreciated! ^^

**Comment by Antivalent** [comment]
A simple (but annoying) workaround which has worked for me is the following:
1. Go to /plugins/Essentials/userdata/
2. Sort by file size (ascending)
3. Open the first few files and delete the ones only containing a 'lastlocation' value
4. The number shown by {UNIQUE} should correct itself the next time the server is restarted

**Comment by pop4959** [comment]
This likely will be fixed automatically once/if EssentialsX decides to handle NPCs separately. Till then it's likely that you will have to live with this problem. Sorry for any inconvenience.
