### ISSUE TITLE
Clear command dont remove banners

### ISSUE THREAD

**Issue by Kixot14** [EssentialsX/Essentials#1177]
when use /clear [player] [banner|425] command from console, it dont remove banners...
Without Essentials all good with default clear command. (/clear [player] minecraft:banner -1 -1)

Essentials build 468
Spigot build 986 (MC 1.10.2)

**Comment by AnttiMK** [comment]
Works for me on Essentials 2.0.1-b468. You are running quite an old version of spigot, so this might be the culprit. Have you tried deleting essentials configs and then rebooting the server?

**Comment by Kixot14** [comment]
does not work

**Comment by pop4959** [comment]
Unable to reproduce on the latest version of Essentials. Please create a new issue if this is still a problem for you.
