### ISSUE TITLE
EssentialsPlayerListener caues server to lag

### ISSUE THREAD

**Issue by wanted156** [EssentialsX/Essentials#1180]
Hello,

I've ran multiple timings reads and it always points to essentials being the main cause of the "on join delay".
This is the read:
https://timings.spigotmc.org/?url=doxajilewo

Running Essentials 2.0.1-b468

Regards,
Wanted

**Comment by Kakifrucht** [comment]
While it is taking up some time on your CPU it doesn't look like the culprit of TPS being too low.
It takes around 50 ms for the task to complete after a player joins. That's fine, considering it does quite some things [there](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java#L221). Are you running the server from a vServer?

**Comment by wanted156** [comment]
I'm running the servers (11 of them) on a Microsoft Azure VM. There are absolutely no problems on join on any other servers, just on hub. When players join they have to wait a couple of secs for them to "load".

**Comment by Kakifrucht** [comment]
Your timings suggest that it takes 57 ms on average.
If they experience lag, it must be longer for some players than it takes for others. There are no readings in your timings suggesting that it takes a couple of secs. Is the Essentials player file of players that do lag filled with lots of homes? How large are these files?

**Comment by wanted156** [comment]
It's just on hub, so no homes are set... on others servers, more intensive, that doesn't happen.

You can check it out yourself at play.mystichero.com.

**Comment by Kakifrucht** [comment]
I do believe you, I just can't reproduce. 57 ms seems fine. Might be an I/O issue with server.

**Comment by wanted156** [comment]
Yes, i understand. I know it's hard to reproduce, especially when even on my side it happens just once. What do you suggest i do?

**Comment by wanted156** [comment]
Latest timings:
https://timings.spigotmc.org/?url=ruyidurudu

**Comment by pop4959** [comment]
It doesn't cause lag for me on the latest version of Essentials. Join task is indeed a bit heavy compared to other things, but this only happens once when players join. A single 50ms task shouldn't be the end of the world for your server either.
