### ISSUE TITLE
NickName Colors 

### ISSUE THREAD

**Issue by jfernandz** [EssentialsX/Essentials#1181]
I'm getting `~` character when I try to change my nickname colors

```
[22:07:02 INFO]: [world]<_WyRe_> asd
[22:07:13 INFO]: _WyRe_ issued server command: /nick &5_WyRe_
[22:07:14 INFO]: [world]<~_WyRe_> asdasd
```

**Comment by AnttiMK** [comment]
Works as intended. If you set ANY nickname with the /nick command (even if you change the colors only), Essentials applies a prefix to the nickname. This settings is defined in Essentials's config.yml.
```yaml
nickname-prefix: '~'
```
If you want to disable the prefix, set `nickname-prefix: ''`
