### ISSUE TITLE
warp files & usermap.csv doesn't support UTF-8 name

### ISSUE THREAD

**Issue by jessefjxm** [EssentialsX/Essentials#1188]
Currently, in latest EssentialsX #468, utf8 characters (here i use Chinese characters) will be recorded as '_' in both warp files & usermap.csv, make it not possible to distinguish between names with same length.

Edit: for usermap.csv, I'm not sure what will be affected with this problem, for UUID used by userdatas is actually a nice way to figure out the right person. But this is really wired... or maybe this file has been abandoned?

**Comment by SupaHam** [comment]
`usermap.csv` does not store anything UTF-8 (or with spaces) anyways, so that's not a rpoblem them. However, where ever you use UTF-8, I expect Essentials to store it just fine. If not, are you sure you have UTF-8 support enabled on the JVM:

`java -Dfile.encoding=UTF-8 -jar server.jar`

**Comment by prozhong** [comment]
https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/utils/StringUtil.java#L20

[^a-z0-9-]

**Comment by pop4959** [comment]
Seems this is disabled on purpose, presumably because it causes problems when storing / etc.
