### ISSUE TITLE
Add an auto feed thing with the essentials /feed command

### ISSUE THREAD

**Issue by Terrobility** [EssentialsX/Essentials#119]
This was just suggested by someone on my server, and I think it would be a great idea!
Something like "/autofeed" and it would require the essentials.feed.automatic permission node. It would feed you automatically when your hunger gets low, and it would also work with the feed/heal cooldown.

**Comment by Kakifrucht** [comment]
What you are actually asking for is a /nohunger?
Would be simpler to implement instead of a running task that executes /feed on demand.

**Comment by Terrobility** [comment]
Not a /nohunger command, that would make sure that your hunger doesn't go down. I'm talking about a command that auto-feeds you every 60 seconds. I changed my mind about this idea, it wouldn't be ideal.

**Comment by Kakifrucht** [comment]
Well vemacs already tagged it a enhancement, so I guess he likes it wether you changed your mind or not ;)

**Comment by Terrobility** [comment]
I meant like how some people get macros to /feed them when their hunger gets low. Maybe there could be something like that but an /autofeed. And fair enough @Kakifrucht

**Comment by Kakifrucht** [comment]
What difference does it make? None. No hunger is basically the same and simpler to implement. It's a good idea though.

**Comment by drtshock** [comment]
I don't really see why this would be added in this project.

**Comment by TomLewis** [comment]
This should not be implemented.
