### ISSUE TITLE
Fireworks and Potions included in /createkit have corrupted meta.

### ISSUE THREAD

**Issue by obzidi4n** [EssentialsX/Essentials#1190]
Fireworks, Potions (and possibly Books) seem to be losing or having corrupt meta saved when using the /createkit command.   For example:

`firework 1 name:Angry_Creeper color:red fade:green type:creeper power:1`

results in:

`- 'FIREWORK 1 name:Angry_Creeper color:Color:[rgb0xB3312C] shape: CREEPER fade:Color:[rgb0x3B511A] power: 1'`

and 

`potion 1 effect:speed power:2 duration:60`

results in:

`- POTION 1`

**Comment by mdcfe** [comment]
Closing in favour of #155 for potions and #1283 for fireworks.
