### ISSUE TITLE
Bigtree command range limit

### ISSUE THREAD

**Issue by PunkFunk** [EssentialsX/Essentials#1192]
I think it would be smart to have a distance of maybe 4 or 5 blocks that you could spawn in a tree with /tree or /bigtree. I've given my players the commands but I've had to set a huge WorldGuard region of 150 blocks outside of my survival spawn area where the command is blocked. Players were snipering trees into spawn lol.

This would also help limit players from putting trees into players protected or "claimed" areas they don't have permission to build in and with things like skyblock so they are not putting trees on other players islands that they can see.

Just a suggestion, thanks for reading

**Comment by pop4959** [comment]
Could easily implement this with a config option and/or permission and simple check within the command (distance from player to targeted block).

**Comment by PunkFunk** [comment]
I dunno, It would still be more customizable just setting the region in the
same way with worldguard right?

**Comment by pop4959** [comment]
I think from Essentials' end, it will only be able to limit the range of the command. WorldGuard not actually preventing trees from growing is an issue in that plugin, if anything. Check if there's a flag for that, and if not, maybe suggest it to them.

**Comment by PunkFunk** [comment]
Agree, minecraft obviously knows what block your looking at. Wonder what
kinda resources it would take to say, have a blacklisted area of where the
player was looking. Say it only tracked players pov block within the 150
block region and only let them use a command while not looking at the
blacklisted area

**Comment by pop4959** [comment]
Yeah if I was following your feature request correctly you were asking for a range to be added to the command. So for example, if the range was 5 and the player was more than 5 blocks away from the block, it would not place a tree.
