### ISSUE TITLE
FIX /condence all

### ISSUE THREAD

**Issue by SuperJogosDBZ** [EssentialsX/Essentials#1194]
Some players are giving the command "/condence all" with the packed inventory of leather and thus causing the drop of thousands of boots on the ground, this can cause problems for other players. FIX PLS

Demo video:
https://www.youtube.com/watch?v=NekrulDG1nw

Players doing this is causing absurd lag to other players.

**Comment by SuperJogosDBZ** [comment]
fix?

**Comment by SuperJogosDBZ** [comment]
fix?

**Comment by smmmadden** [comment]
I have no idea what /condence all does let alone how to respond to a 2 minute video in another language that I don't speak or read.  Most commands have a permission node to them, so if it is something you don't want them to do, remove the permission.  I suspect that's what you'll get for a response as well.

**Comment by SuperJogosDBZ** [comment]
The command (/condence all) identifies the leather as a block, so when executed it transforms the material into leather boots, since the boots occupies one slot per item (doesn't group) and the leather does, it opens the possibility to create a massive amount of leather boots and cause LAG on the server due to the quantity of dropped items.
We use this command to compact minerals like diamond, gold, iron and its use its allowed to all the players.

**Comment by smmmadden** [comment]
okay, that makes sense but where does Essentials come into play here?  I'm not aware of a /condence or /condense command.  I did find this plugin which sounds similar to what you describe. https://dev.bukkit.org/projects/itemcondenser but even that project was abandoned.  If the potential of it causing lag and creating hundreds or thousands of boots, why take that chance?  There must be other ways to achieve the same without the users abusing it like removing the permission node that grants the feature and possibly creating a shop where users could buy them or even a command block to generate exactly what is allowed?  The owners of Essentials can choose to support this or not.  I'd recommend reaching out to the plugin owner where it is coming from if you don't have an alternative to work with. :-)

**Comment by SuperJogosDBZ** [comment]
I assure you that this command comes from the Essentials plugin, I'm reporting this so you can fix it.

**Comment by smmmadden** [comment]
I'm not the one that fixes it - just offering support.  I did find it finally and see the permission node is essentials.condense  For the heck of it, I tried filling up my slots with Leather (64 in each) and then doing the /condense all - I got "You have no items that can be converted into blocks".  So I tried with diamonds and it created the blocks it should have. I'm running with a Spigot 1.11.2 and BungeeCord Network.  Perhaps the developers will be able to shed some light on it.  FWIW, having a user convert their inventory to blocks is nice to have, but they can do the same on a crafting table without impacting server performance albeit it takes longer, but better for the community as a whole.  If there is a bug in it, I'm sure they'll investigate it further.  Good luck!

**Comment by SuperJogosDBZ** [comment]
Test with spigot 1.8.8.

**Comment by smmmadden** [comment]
sorry, too old of a release - 1.12 will be out soon, planning forward. :-)

**Comment by mdcfe** [comment]
@SuperJogosDBZ Update your server. There is no properly maintained server software for versions before 1.11.

**Comment by SupaHam** [comment]
This is an important issue even on 1.12. Sorry it's taken so long to look at. I'll try look for a solution soon.

EDIT: with that said 1.12 does not seem to keep the items on the floor. It just removes them from the world.

**Comment by Cewkaurai** [comment]
Got this issue on my 1.12 server too... Attempting to condense diamonds results in the creation and dropping (with a full inventory) of diamond boots when attempting /condense hand or /condense all. doing just /condense results in the "You have no items that can be converted into blocks" error that has been mentioned for a while.

Is there any chance that we could even just get some kind of hotfix patch kind of thing for it?

**Comment by Foryx** [comment]
This is still an issue. I currently cannot condense diamond or iron into blocks. Instead it made boots. The only major change I can think of is it being paperspigot instead of spigot.
I am on 1.12.2

**Comment by sadoj-kuro** [comment]
same here, spigot 1.12.2 condense broken

 diamond transform into boot, fer into trap, gold into boot etc

**Comment by mdcfe** [comment]
We should probably strictly define what recipes are used somewhere, rather than relying on the seemingly-inconsistent recipe database Bukkit provides, which as far as I can tell used to work properly.

**Comment by gmemstr** [comment]
Outdated, unable to replicate on

```
>version
[19:46:58 INFO]: This server is running CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[19:46:58 INFO]: This is a final build for 1.13.2. Please see https://www.spigotmc.org/go/1.13.2 for details about upgrading.
>
```

**Comment by mdcfe** [comment]
I can replicate this and am working on a fix:
```
[13:25:30 INFO]: CONSOLE issued server command: /ess version
[13:25:30 INFO]: Server version: 1.14.2-R0.1-SNAPSHOT git-Paper-87 (MC: 1.14.2)
[13:25:30 INFO]: EssentialsX version: 2.16.1.211
[13:25:30 INFO]: Vault is not installed. Chat and permissions may not work.
```

**Comment by mdcfe** [comment]
This has now been fixed - you can download the latest version from the [build server](https://ci.ender.zone/job/EssentialsX).
