### ISSUE TITLE
Newly joining players get random items.

### ISSUE THREAD

**Issue by MissPvP** [EssentialsX/Essentials#1195]
I'm getting a weird issue with newly spawned in players receiving 30 wood planks and 70 stone that are enchanted as power 3 thorns 5, It also shows the player's name in the lore as well as Kit Newbie.

**Comment by OasisArtisan** [comment]
i'm not an expert but did u check this config part?
newbies:
  announce-format: '&dWelcome {DISPLAYNAME}&d to the server!'
  spawnpoint: newbies
  kit: tools

there might be a kit that is defined here like "tools" in mine just remove the whole kit part and i think you'll be fine. 
unless you've already checked the config and its a programming issue then sorry for interfering :)

**Comment by mdcfe** [comment]
If this is still an issue, check the `newbies` section for whether a kit is defined. Otherwise, this is probably not caused by EssentialsX but by another plugin.
