### ISSUE TITLE
/tpdeny responds with 'null'

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1196]
I am getting the issue when I don't get any teleport requests and typing the command /tpdeny it responds in chat with 'null' without the quotes. 

I am not sure how to fix this as I have not found a option in the messages.yml to change it?

**Comment by ghost** [comment]
I have same problem.

**Comment by SupaHam** [comment]
This has been fixed in 4bfabaa. You can grab the fix from [build 470](https://ci.drtshock.net/job/EssentialsX/) on the CI server.

See #1229
