### ISSUE TITLE
EssentialsxSpawn not using correct cordinates

### ISSUE THREAD

**Issue by Johandrex** [EssentialsX/Essentials#1198]
When teleporting to the "/spawn" it's always teleporting the player to the middle of a block, it doesn't teleport to the correct location from the "spawn.yml" file.

**Comment by SupaHam** [comment]
This is the case with all teleports.

Please explicitly specify the following in your `config.yml`:
`teleport-to-center: false`

EDIT: I've documented this in the [wiki](https://github.com/drtshock/Essentials/wiki#teleport-to-exact-coordinates)
