### ISSUE TITLE
spawners not working with worth.yml

### ISSUE THREAD

**Issue by PhanaticD** [EssentialsX/Essentials#1199]
to test i have this entry:
```
  52:
    '5': 10 #wither skeleton
```

i do /i 52:5 in game then /sell hand and it says this item cannot be sold

**Comment by mdcfe** [comment]
Does this still occur if the `'5'` is *not* surrounded by quotes?

**Comment by PhanaticD** [comment]
probably since every other item works

**Comment by pop4959** [comment]
Please create a new issue if this still broken in the current version of Essentials, as item IDs are no longer supported, and worth.yml is no longer used. This would be something to support in the new Item DB if it doesn't already.
