### ISSUE TITLE
How can I use /give with SilkSpawners?

### ISSUE THREAD

**Issue by Terrobility** [EssentialsX/Essentials#120]
I have tried "/i spawner:52 1 name:&eSpider_&fSpawner" and "/i spawner:52 1 name:&eSpider_&fSpawner {BlockEntityTag:{EntityId:Spider}}". They don't seem to give me a spawner that stacks with the spawner from "/silkspawners spider". I have also tried looking for documentation on this but I can't seem to find anything. Has anyone got a way to spawn a spawner from SilkSpawners using the /give command?

**Comment by drtshock** [comment]
This is the essentials issue tracker.
