### ISSUE TITLE
MAX BALANCE ERROR

### ISSUE THREAD

**Issue by yasons-zz** [EssentialsX/Essentials#1200]
I got a problem, I set my maximum money in config for 10000000 ($10 million)
But the fact maximum balance of player is $999,999. I've did echo give/set 1000000, result still same, it max at $999,999.

Please, help.

My Software:
Spigot 1.11
EssentialX 2.0.1 last version.
Java 8.1.12

**Comment by SupaHam** [comment]
In order to maintain existing (expected) behaviour, this issue will not be "fixed". Please set your `max-money` to `10000000.0001`.
