### ISSUE TITLE
Jenkins/repo is down

### ISSUE THREAD

**Issue by Androkai** [EssentialsX/Essentials#1201]
Can somebody with access please have a look on the Jenkis/repo? Thx

**Comment by RikoDEV** [comment]
Project rip? No update since last month.

**Comment by SupaHam** [comment]
Currently waiting on server renewal.

**Comment by Pokechu22** [comment]
As mentioned in IRC, the temporary mirror is at https://ci.lucko.me/job/Essentials/.

**Comment by EvilOlaf** [comment]
https://ci.drtshock.net/ is up for me.

**Comment by Portanna** [comment]
Repo is up for me too
