### ISSUE TITLE
Permissions list?

### ISSUE THREAD

**Issue by ECMD** [EssentialsX/Essentials#1202]
Hi, so im kinda noob in minecraft mods, but im using EssentialsX and PermissionsEX, but the problem is that i want the default permissions goup to have the default essentials commands, like afk, help,info...
But i cant give permissions, probably i put the wrong permission in the default group, anyone can give me the permission name? i tried "essentials.general" and "essentials.general.x" (i took from web, but probably is wrong lol, or mainly because im noob xD) Any help? Thanks :)

**Comment by Kakifrucht** [comment]
[See here](http://wiki.mc-ess.net/wiki/Command_Reference/Perm)
