### ISSUE TITLE
Command Block Spam Problem

### ISSUE THREAD

**Issue by Flick3rF3r** [EssentialsX/Essentials#1204]
Can I turn off command block /tell logs? Its spamming so much :(
Screenshot: https://ibb.co/hYucO5

**Comment by Kakifrucht** [comment]
Use ```/gamerule logAdminCommands false```. This is not Essentials related.

**Comment by Flick3rF3r** [comment]
No progress :(
Screenshot: https://ibb.co/eHyAt5

**Comment by Kakifrucht** [comment]
That was the wrong one, try ```/gamerule commandBlockOutput false```.

**Comment by Flick3rF3r** [comment]
Still won't work: https://ibb.co/crT76Q
Also I have found something like this in EssentialsX files: https://ibb.co/mkxvt5
directory: Essentials.jar\com\earth2me\essentials\Essentials.class

**Comment by Kakifrucht** [comment]
Interesting, I was unaware.
Can you confirm that the message disappears without Essentials enabled?

**Comment by Flick3rF3r** [comment]
hm....I'll try. wait a min.

**Comment by Flick3rF3r** [comment]
MC client view: https://ibb.co/cfkLRQ
Servers console view: https://ibb.co/hyj3fk
The problem is gone... 😄 
But I need Essentials 😞

**Comment by Kakifrucht** [comment]
Seems like you are out of luck for now, as Essentials commands are always logged right now, no matter what. Only way to remove it is to use a different messaging plugin, Bukkit seems to no longer support the default /tell from what I can see unfortunately.

**Comment by Flick3rF3r** [comment]
What else can I use to send links/messages to players by commandblocks?

**Comment by Kakifrucht** [comment]
Try ```/tellraw @p ["",{"text":"www.google.com"}]```.

(Doesn't make the link clickable, use https://www.minecraftjson.com/).

Clickable link example: ```/tellraw @p ["",{"text":"Google!","color":"blue","clickEvent":{"action":"open_url","value":"http://google.com"}}]```

**Comment by Flick3rF3r** [comment]
Ok. I'll tell you if it works for me 😃

**Comment by Flick3rF3r** [comment]
Thanks...it works fine 👍

**Comment by Flick3rF3r** [comment]
But anyway: It should be added in the future updates. Do you agree with me? ;)

**Comment by Flick3rF3r** [comment]
Should I close this issue?

**Comment by Kakifrucht** [comment]
I agree that it should be toggleable, and you do too, so no I guess.

**Comment by Flick3rF3r** [comment]
okay

**Comment by Flick3rF3r** [comment]
Seriously: BIG THANKS for your help! 😄 
I was stuck with this problem for 2 days 😅

**Comment by Pokechu22** [comment]
> Bukkit seems to no longer support the default /tell from what I can see unfortunately.

Hm?  `/minecraft:tell` (which, without plugins, is just `/tell`) should still work, you just don't have `/bukkit:tell` anymore.  Though in commandblocks, `/tellraw` is probably better.

**Comment by Kakifrucht** [comment]
You are right, I recall it being ```/bukkit:tell```, since they also have (had?) their custom permissions renamed from ```minecraft.``` to ```bukkit.```.

**Comment by Pokechu22** [comment]
Yea, for a while there were both `bukkit:` and `minecraft:` versions of most commands (such as `/bukkit:say` which used purple text); a while ago (I think in 1.8) those were removed because the vanilla commands worked fine and it was better to be consistent.
