### ISSUE TITLE
[Feature request] Add owner: UUID to next created warps yml files :)

### ISSUE THREAD

**Issue by FlashLight34** [EssentialsX/Essentials#1207]
**_# ss.yml file_**:
world: worldust2
x: -974.3767364747757
y: 60.0
z: 1385.798465019171
yaw: 91.50531
pitch: 9.750012
name: ss
**OWNER: 102397ff-0552-406d-8493-93bfae0ae5a4**

**Comment by mdcfe** [comment]
This was added in #1961.
