### ISSUE TITLE
Ability to teleport to unsafe locations while having teleport safety disabled.

### ISSUE THREAD

**Issue by KillerAntMC** [EssentialsX/Essentials#121]
A recent problem that's been happening in my server is that people set their homes in water and when they try to teleport back to them, they are unable to teleport to them because it is an unsafe location. I disabled teleport safety in the config to stop a tpa glitching problem that people were using to raid bases. Now some players can't teleport to there homes because they set them in water. Maybe adding  a config option to enable unsafe teleports.

**Comment by vemacs** [comment]
We already have that. Turn `teleport-safety` to true and `force-disable-teleport-safety` to true. The reason `teleport-safety` needs to be true is to not break existing behavior.
