### ISSUE TITLE
Send time remaining to muted players who attempt to chat

### ISSUE THREAD

**Issue by RikoDEV** [EssentialsX/Essentials#1211]
When the player is silenced, he or she receives the time information for muting. I would like to receive the same information when I try to write something. For example: You were muted for X hours, X minutes, X seconds.

**Comment by virtualdxs** [comment]
I would suggest the remaining time rather than the total time

**Comment by triagonal** [comment]
This feature has been implemented in 9681933 and is present in versions `2.17.2.156` and above. Download the latest build [here](https://essentialsx.net/downloads.html).
