### ISSUE TITLE
Suggestion: Add Playtime to /whois

### ISSUE THREAD

**Issue by Fluxty** [EssentialsX/Essentials#1212]
Add the players total playtime on the server to the /whois command :+1:

**Comment by EvilOlaf** [comment]
Good idea but probably not easily solvable.
EssentialsX would have to track all the time when a player comes online and goes offline and store these values in a database or whatever. 
There are other plugins that can do that including top players of day/week/month and subtract afk time and stuff.

**Comment by molor** [comment]
> EssentialsX would have to track all the time when a player comes online and goes offline and store these values in a database or whatever.

Player#getStatistic(Statistic.PLAY_ONE_TICK)

**Comment by SupaHam** [comment]
This has been introduced in 7c0fa46. You can grab the feature from [build 479](https://ci.drtshock.net/job/EssentialsX/) on the CI server.

Thank you! :)
