### ISSUE TITLE
 EssentialsX-2.0.1.jar not adding folder/config 

### ISSUE THREAD

**Issue by kayak503** [EssentialsX/Essentials#1213]
I downloaded  EssentialsX from https://ci.drtshock.net/job/EssentialsX/ and when I put it into the plugins folder and restarted my server everything went fine no errors all sys. loaded but when I killed the server via "stop" and looked in the plugins folder there was no config folder 
bukkit version 1.11.2 
 EssentialsX version 2.0.1 
plz help

**Comment by SupaHam** [comment]
Is this still a problem?
