### ISSUE TITLE
Suggestion: Jail Disabled Commands

### ISSUE THREAD

**Issue by NicoNekoDev** [EssentialsX/Essentials#1215]
Add option to disable commands for players in jail. (like disabled commands for muted players)

**Comment by NicoNekoDev** [comment]
Should I close this suggestion? Cuz nobody replay to it.

**Comment by darbyjack** [comment]
This has been implemented.

**Comment by kokqi** [comment]
when there wlll be "/unmute" feature? ik /mute works the same but I want a toggle feature. Don't need if yall added jail disabled commands or the unmute feature i want...
