### ISSUE TITLE
Suggestion: Add automatic userdata purge

### ISSUE THREAD

**Issue by Portanna** [EssentialsX/Essentials#1217]
Add config option to enable automatic userdata purge older than X days, that deletes userdata on server shutdown if older than X days.

Example in config:

userdata_purge_toggle: true
userdata_purge_days: 30

**Comment by pop4959** [comment]
Essentials user data is very small. I don't see a reason for this feature. If you *absolutely* need this, you can still create a script (perhaps as part of your server startup) that deletes files with a last modification date before some time.
