### ISSUE TITLE
respawn at bed spawns player on roof etc

### ISSUE THREAD

**Issue by chillerkraft** [EssentialsX/Essentials#1218]
i can do "/home bed" fine but when i Respawn at bed it puts me on the roof or surface, whatever is above the bed. i have a 3 block space above the bed. this happens on my other server too.
i could make a video if needed?

**Comment by iBurkeMC** [comment]
Try 3 blocks above and 2 blocks each side

**Comment by chillerkraft** [comment]
yea. that fixes it.
unhappy with how strict it is though.
but i decided yesterday im not gonna use the essentials.sethome.bed perm
just gonna make people respawn at there first home

**Comment by mdcfe** [comment]
The config option `force-disable-teleport-safety` may help ensure players respawn at the set location.

**Comment by Jeronimo654** [comment]
Doesn't work
