### ISSUE TITLE
HELP, CONSOLE SPAMS /LIST

### ISSUE THREAD

**Issue by Techno3600** [EssentialsX/Essentials#1219]
Hello,

My console spams the /list command every minute. What's causing this?

**Comment by ParadauxDev** [comment]
Your Panel is dong this, not the plugin.

**Comment by Techno3600** [comment]
No it I don't not, I already had a live chat. When removing EssentialsX there was no spams, but when it was installed there was. Ask the live chat guys for a description of what happened.

**Comment by Techno3600** [comment]
[Here's my configuration](https://pastebin.com/bLsMaGH3)

[Here's my plugins installed](https://pastebin.com/dCJ5hh2A)

**Comment by SupaHam** [comment]
This is most commonly an issue with Control Panel services. Regardless, I can assure you this is not a problem on our end, your config looks absolutely fine.

If it is not your Control Panel, then it is probably another plugin you have installed.

For more information:

When you remove `EssentialsX` and you dont see spam anymore, that doesn't mean it's EssentialsX's fault. It means that another plugin is providing the `/list` command. Usually there is the built-in `/list` provided with Minecraft by default.

**Comment by Techno3600** [comment]
Okay, I figured out that EssentialsX just shows the command being run, apparently its always been run, just EssentialsX shows it. Can you PLEASE make it so EssentialsX does not show the spam of /list in the console. I am debating wheather to use this because I want to see what my players are doing. Not a bunch of /list commands.

Thanks
Anand

**Comment by SupaHam** [comment]
We cannot stop showing "spam of /list" because we don't know what counts as spam. The only solution is rate-limiting which means to limit how often the command can be run. But that's not going to happen because it's not a problem with EssentialsX. I would advise you fix this problem using your Control Panel software which I'm sure is the problem.
