### ISSUE TITLE
When using chat-radius, all messages are duplicated (stripped + colored) in console / logs

### ISSUE THREAD

**Issue by justwheel** [EssentialsX/Essentials#122]
When using the chat-radius feature of EssentialsChat, all messages by all players are duplicated twice in console and in logs. They are two different versions, one using the default chat formatting with what you would get without running EssentialsChat, one with any modifications made in the `config.yml` for EssentialsChat. I don't \* think \* this is intended behavior, and even if it is, it's annoying either way to have all messages duplicated.

On a side note, since this may be related, emotes don't seem to be logged either.

![Screenshot of Behavior](http://i.j-f.co/u/4fdc5a13240d6caa4a530aeb7d79a0a6.png)

**Comment by drtshock** [comment]
Emotes aren't broadcasted if local chat because it's send to each player and not logged. I'll need to add that as well.
