### ISSUE TITLE
Locale for the places in baltop?

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1220]
Hey! Where can I find the locale for # places in the /baltop? I cannot really find it..
So to change colors of "1. Sauce, $99,800"
http://i.imgur.com/VbUavOU.png

**Comment by mdcfe** [comment]
This isn't currently customisable - EssentialsX uses [static concatenated strings](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/commands/Commandbalancetop.java#L125) for `/baltop` at the moment.
