### ISSUE TITLE
[Fix] Essentials Kit Console Error

### ISSUE THREAD

**Issue by Beags** [EssentialsX/Essentials#1221]
When console runs the command to give a user a kit, it makes this error:

Error: https://hastebin.com/uwofumisej.rb

Version: his server is running Paper version git-Paper-1091 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

I am running protocolsupport too.

**Comment by SupaHam** [comment]
This is a problem with a plugin called tokenenchant. It is overriding EssentialsX's behaviour beyond our control, and breaking the game feature completely.
