### ISSUE TITLE
[bug] Book spawning stopped working with certain names.

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#1225]
This has always worked for me in kits:
`387 1 title:&a~_&dPirateCraft_Bible_&a~ author:GodsDead lore:Rules_Commands_Ranks book:Bible`

But recently after updating to 1.11.2 its stopped working, If I rename it to:
`387 1 title:&dPirateCraft author:GodsDead lore:Rules_Commands_Ranks book:Bible`
Then it works, but I have no idea why its stopped working, there are no errors in console.

**Comment by SupaHam** [comment]
Works fine for me.

Please make sure the chapter `Bible` exists in the `book.txt` file under the Essentials plugin folder.

**Comment by TomLewis** [comment]
Yeah it does, Ive used it for 4 years, only recently its stopped allowing the name its always used...
