### ISSUE TITLE
Clearing player inventories does not clear item held in hand.

### ISSUE THREAD

**Issue by iBurkeMC** [EssentialsX/Essentials#1227]
Pretty self-explanatory, but whenever a player's inventory gets cleared, the item held in hand does not get removed with the rest of the items.

**Comment by mdcfe** [comment]
I've never encountered this issue before.

If this is still an issue, could you [update to the latest build of EssentialsX](https://ci.ender.zone/job/EssentialsX) then post the output of `/version` and `/essentials`?

**Comment by mdcfe** [comment]
This was fixed by 983f3a7935712ff63da3bfd2c2233ffb9914db51 - update to the [latest version](https://md678685.github.io/EssXDocs).
