### ISSUE TITLE
<command>?

### ISSUE THREAD

**Issue by molor** [EssentialsX/Essentials#1230]
If I perform /ess, then in the chat it looks like a bug. Minor. \<command\> is not replaced to command name ("ess" in this case).
https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/commands/Commandessentials.java#L62

**Comment by SupaHam** [comment]
It's not a bug. :)

This is common behaviour that you will find with all commands.

**Comment by molor** [comment]
Maybe you did not understand me. @SupaHam 

If I type /ess, then I get this response:
![1](https://cloud.githubusercontent.com/assets/19989717/25706254/8e589d88-30e8-11e7-82e2-af3432458664.PNG)

But if I try any other command instead of /ess (/call for example), there will be correct name (/call instead of /\<command\>):
![2](https://cloud.githubusercontent.com/assets/19989717/25706257/902739d0-30e8-11e7-8e35-f55596b72a43.PNG)
