### ISSUE TITLE
Suggestion: add message, when player ignored

### ISSUE THREAD

**Issue by Kixot14** [EssentialsX/Essentials#1231]
When player1 ignore player2, and player2 try to pm, tpAsk, mail... he shuld get message about "No responde, cause u are in ignore-list".

**Comment by Kixot14** [comment]
And maybe it possible to add option/permission to disable ignore in general chat? May ignore only applies to private interacts (pm, mail and tpask)...

**Comment by Kixot14** [comment]
Add coma separator for player names, in ignore-list.

**Comment by mdcfe** [comment]
I think it slightly undermines the ignore list if the player is being told they're being ignored.

**Comment by drtshock** [comment]
This is purposefully not sent.
