### ISSUE TITLE
Remove serverTotal string

### ISSUE THREAD

**Issue by Kixot14** [EssentialsX/Essentials#1232]
Remove 'serverTotal' string from messages file! Meaningless and no needed option, which impossible to remove. When i delete this string, it leaves empty space between 'infoPages' and list of economy players, in /balanceTop command.

**Comment by Kixot14** [comment]
And add format for player list of this /balanceTop command.

**Comment by pop4959** [comment]
Please create an issue for each suggestion separately. Also, I don't think balancetop can completely be customized right now because the list is generated by the plugin.
