### ISSUE TITLE
A bug with boats

### ISSUE THREAD

**Issue by DanielTravi** [EssentialsX/Essentials#1233]
Boats do not get in the water by clicking

**Comment by dordsor21** [comment]
and this is a problem with essentials...how?

**Comment by SupaHam** [comment]
Sorry, this probably isn't an EssentialsX issue.

1. Please make sure you are not within the `spawn-protection` region as specified in `server.properties`.
2. Make sure you are not in a WorldGuard protected region which might prevent you from using items or placing blocks, etc.
