### ISSUE TITLE
Recomendation with /nick

### ISSUE THREAD

**Issue by Technerder** [EssentialsX/Essentials#1238]
Could you add options in the config where, on /nick the tablist name, chat name, and the name above a player will be modified aswell? I strongly believe this should be added.

**Comment by chillerkraft** [comment]
ALSO make nick max length not count formatting codes

**Comment by chillerkraft** [comment]
please

**Comment by mdcfe** [comment]
To change the tab list name: `change-playerlist: true` (you may need to remove the # before it).

Changing the name in chat depends on what chat plugin(s) you have installed. If you have EssentialsXChat, it should show the nickname by default.

To make the max length for nicks ignore colour codes: `ignore-colors-in-max-nick-length: true`.

You will need another plugin to change the name above players as far as I know.

**Comment by chillerkraft** [comment]
yea i discovered that new addition to the config right after i posted that request
thankyou essentialsx thankyou md!

**Comment by Technerder** [comment]
Why not implement the feature for over head names?

**Comment by mdcfe** [comment]
As far as I know, this would require packet manipulation, which means it is unlikely it will be added to EssentialsX.

**Comment by SupaHam** [comment]
It's not really essential. Sounds like a feature you should get from another plugin. Sorry.
