### ISSUE TITLE
Recource Page on SpigotMC problems.

### ISSUE THREAD

**Issue by PermissionError** [EssentialsX/Essentials#1239]
Hi team!
I searched EssentialsX on SpigotMC and the page on there does not match the most recent version and the download button does not work.
Will you guys fix that?
Regards,
Shadow.

**Comment by PermissionError** [comment]
Edit: The download from Jenkins button DOES work but the original spigot download button leads to an invalid bukkit page.

**Comment by mdcfe** [comment]
The version on Spigot and BukkitDev are known to be outdated. It would be useful if they linked to the Jenkins lastSuccessfulBuild page, though.

**Comment by PermissionError** [comment]
Thanks mate!
Closing issue
