### ISSUE TITLE
Cannot modify chat

### ISSUE THREAD

**Issue by PhanaticD** [EssentialsX/Essentials#124]
I am not sure if this is an essentialsx issue or a commandhelper, but after switching to essentialsx from regular essentials modifying the chat event using commandhelper no longer seems to be working

This little commandhelper script would put a heart before your username: http://pastebin.com/N4tvGFBr while still keeping all the essentials features such nickname, chat radius etc

This no longer works, perhaps its the event priority?

**Comment by drtshock** [comment]
Are you using essentialsxchat? We haven't modified that project at all other than reformatting it.

**Comment by PhanaticD** [comment]
yes, I talked to the people from commandhelper they said it was most likely the event was set at the same priority

**Comment by drtshock** [comment]
Ess chat runs at 3 different priorities for different things. I'd have them look at it.

**Comment by PhanaticD** [comment]
alright :/ but it only broke after switching from the old essentials to essentialsx
