### ISSUE TITLE
Combine

### ISSUE THREAD

**Issue by msburgess3200** [EssentialsX/Essentials#1241]
To whom it may concern:
Would you consider combining the Extra plugins with your repos at Spigot and Dev Bukkit?

Due to some "jar-heads" over at Aternos, we can't install EssentialsXSpawn or EssentialsXChat because it's considered as an "external" link.

(The irony being that it is an external download from Spigot and Dev Bukkit)

**Comment by mdcfe** [comment]
They're effectively modules or components of the same plugin. The SpigotMC and BukkitDev links are outdated anyway; you should always be downloading the latest version from the build page.

**Comment by msburgess3200** [comment]
Well, they won't. That's why I am asking to make the plug-in and is modules in a downloadable zip file.



Happy Connecting. Sent from my Sprint Samsung Galaxy S® 5


-------- Original message --------

**Comment by mdcfe** [comment]
Use a proper host, or at least a host that allows you to upload files through its panel.

**Comment by msburgess3200** [comment]
Again. People with a small budget kinda need the free hosting... Would you please consider my request.

Proof:
https://board.aternos.org/index.php?thread/11275-request-essentialsx-extras/&postID=62730#post62730

**Comment by mdcfe** [comment]
If the scale of your server is large enough to require EssentialsX, it is large enough to also require proper hosting. As said before, use a host which allows file uploading.

**Comment by msburgess3200** [comment]
Not exactly. You can have plenty of players but none of them donate to keep one alive. Is it too much to ask for some help with this?

**Comment by smmmadden** [comment]
I agree with md678685 that if you need to use other plugins to get the capability you desire, there are other hosts with more flexible server options you can use or host it yourself and have full control over which plugins you want to use or not.  That's what I do, it really isn't that hard to do and removes unrealistic restrictions imposed by hosting companies.  The link you provided does not even explain why they don't want to do and they don't explain clearly their reason and closed the request.

My take on the closure reason has to do with either security or technical reasons why they only apply plugins from the two locations as it would be how the server is built.  Much like Forge Servers do, they only support Forge created plugins.  Other servers have the same restrictions.  Find out what that is and that will help you find a hosting company you can work with.  Not ideal, but you know your players and situation better than anyone. :-)
