### ISSUE TITLE
/home leaving on void

### ISSUE THREAD

**Issue by NathanPB** [EssentialsX/Essentials#1242]
Hello,
sometimes an error happens and when a player execute /home <homename>, the command teleports him to void, in the correct X and Z axis, but wrong Y.
Some, I'm asking for a config to spawn the player in a safe place, into his home =)
Is it possible? Thanks

**Comment by Eufranio** [comment]
Agree.

**Comment by smmmadden** [comment]
I've never seen /home being an issue.  
What server/version are you using and which build of Essentials are you running with?  
Also are you using the [EssentialsX Extras](https://www.spigotmc.org/resources/essentialsx-extras.23822/) plugin or just this one?

I'm using the latest build for Spigot 1.11.2 and don't have issues with /home

**Comment by Eufranio** [comment]
Thermos, 1.7.10 build 58 and Essentials 2.0.1-b370. I tested with other plugins as well, a lot of teleports and none of them failed, only the homes.

**Comment by smmmadden** [comment]
While Thermos is a newer build, Essentials 370 is a very old build.  I'd recommend at least 468 (the one I'm using) or 472 (latest).

**Comment by mdcfe** [comment]
@smmmadden 370 is definitely compatible with 1.7.10, but builds after 438 are unlikely to be stable on versions before 1.11 due to compatibility changes.

**Comment by smmmadden** [comment]
good to know, thanks @md678685  :-)

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to reopen the issue.

**Comment by SrBedrock** [comment]
Setting /home in blocks as chests and carpet causes void death.

**Comment by SrBedrock** [comment]
The player does not teleport above the mentioned blocks, but "inside" the blocks, causing them to fall into caves and if there is no cave, die in the void.
