### ISSUE TITLE
TPA issue with placing teleported player

### ISSUE THREAD

**Issue by MithrandirCraft** [EssentialsX/Essentials#1245]
Hi, there's an issue when players get teleported with TPA, here's an example:
https://www.youtube.com/watch?v=H2d7NefPK0c&feature=youtu.be
(Yeah the video is poor in quality, the tpa is sent near the begining, and the player missplacement is after half way, as he took his time to answer the tpa call)

The issue occurs because the tpa location is in water, and EssentialsX tries to place the player in a safer block (On top of obsidian in the video example, and inside an inaccesible area) I presume.

EssentialsX version: 2.0.1 b460
Spigot version: MC: 1.11.2

**Comment by mdcfe** [comment]
You can disable teleport safety, but there's not much else that can be done to solve this.

**Comment by pop4959** [comment]
Disabling teleport safety is the solution to this issue. You can also alternatively use other plugins which further restrict players from entering the inaccessible region.
