### ISSUE TITLE
Add permission: values to all commands in plugin.yml

### ISSUE THREAD

**Issue by molor** [EssentialsX/Essentials#1247]
Please.

Many plugins (that works with a bukkit command list) think that all commands from Essentials is not available for player. Even /home is considered unavailable as it is not have specified permission node and it is considered that it is only available to operators..

**Comment by smmmadden** [comment]
I think you are mistaken about /home.  There "are" permission nodes available to enable/disable for players.
    - essentials.home
    - essentials.home.bed
    - essentials.home.use

**Comment by molor** [comment]
@smmmadden, it doesn't contain permission node which is required to other plugins. 
https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/plugin.yml#L178

**Comment by smmmadden** [comment]
not sure what you're expecting in the plugin.yml as the permissions are at the bottom of the file.  Even the latest build 472 shows the same detail.  You simply need to grant/deny which ever permission you want to each player in your permssions.yml or permissions plugin which is what I provided above showing the 3 permissions for /home

**Comment by mdcfe** [comment]
This is a valid issue - if these aren't present when the commands are defined, the server won't have a permission node attached and so plugins won't be able to know if a permission node is required for a command.

**Comment by pop4959** [comment]
I just checked -- looks like commands are in the plugin.yml, so this shouldn't be an issue anymore.
