### ISSUE TITLE
https://ci.drtshock.net/job/EssentialsX  DOWN

### ISSUE THREAD

**Issue by smmmadden** [EssentialsX/Essentials#1248]
getting an HTTP 502 error

**Comment by jaroslawjanas** [comment]
Are you using Spigot or something else?
Provide log files.
Provide config files.

**Comment by smmmadden** [comment]
got nothing to do with my server has everything to do with the server in the subject. :-)

**Comment by jaroslawjanas** [comment]
:D
I just realised what a retard I am. I'm sorry.
Yeah it's down.
![image](https://cloud.githubusercontent.com/assets/28691446/26262882/4ba9a15c-3cce-11e7-834f-5d6f856c279e.png)

**Comment by jaroslawjanas** [comment]
Try this one. It's a mirror: https://ci.lucko.me/job/Essentials/

**Comment by smmmadden** [comment]
Thanks, someone else mentioned the mirror but the build details are far off from the primary.  The mirror shows build #8 when it should be 472 (latest).  So its confusing if it is even valid.

**Comment by kingnicolas27** [comment]
Any idea when this will be fixed..? :(

**Comment by PermissionError** [comment]
It's back on.

**Comment by smmmadden** [comment]
confirmed - thanks!

**Comment by SupaHam** [comment]
The official CI server is back up thanks to @drtshock https://twitter.com/drtshock/status/865717250279526400
