### ISSUE TITLE
EssentialsX + PEX (GroupChat formating)

### ISSUE THREAD

**Issue by jaroslawjanas** [EssentialsX/Essentials#1249]
Essentials completely ignores group formats and uses the standard format even for OPs
Pex + EssentialsX config
https://pastebin.com/HSqsG2u3

**Comment by SupaHam** [comment]
Do you have vault installed?

**Comment by jaroslawjanas** [comment]
Yup
List of Plugins:
AuthMe-5.2-spigot.jar
AutoMessage.jar
Broadcaster%202.0.0.jar
Clearlag.jar
CustomServerMessages.jar
DynmapPlotMe.jar
EssentialsX-2.0.1.jar
FastLogin.jar
FirstJoinPlus.jar
HolographicDisplays.jar
HomeSpawnPlus.jar
LogBlock.jar
LWC.jar
MakeYourOwnCommands.jar
MaxBans.jar
Modifyworld.jar
Multiverse-Core-2.5-b717.jar
Multiverse-Portals-2.5.jar
PermissionsEx-1.23.4.jar
PlotMe-Core.jar
PlotMe-DefaultGenerator.jar
PowerMotD.jar
ProtocolLib.jar
Reporter.jar
ServerTutorial-2.2.3.jar
SimpleHelpTickets.jar
SpamGuard.jar
Vault.jar
Vote.jar
worldedit-bukkit-6.1.3.jar
worldguard-6.2.jar

**Comment by SupaHam** [comment]
You need EssentialsXChat from the CI server.

**Comment by ertagon2** [comment]
Should be mentioned or linked!
Thanks

**Comment by ertagon2** [comment]
![image](https://cloud.githubusercontent.com/assets/28691446/26262545/0b8912ca-3ccd-11e7-8848-2bdb3251c32d.png)
![image](https://cloud.githubusercontent.com/assets/28691446/26262563/16adce3e-3ccd-11e7-8ee6-0d01876456b6.png)

**Comment by ertagon2** [comment]
![image](https://cloud.githubusercontent.com/assets/28691446/26262580/29b8eb58-3ccd-11e7-9b87-b1df516cfe69.png)
![image](https://cloud.githubusercontent.com/assets/28691446/26262584/30034774-3ccd-11e7-816d-83b44a16aae1.png)

**Comment by jaroslawjanas** [comment]
![image](https://cloud.githubusercontent.com/assets/28691446/26262628/5c5fa0a6-3ccd-11e7-886e-8007f608a8d5.png)
![image](https://cloud.githubusercontent.com/assets/28691446/26262631/5fa7c9aa-3ccd-11e7-9bab-0bc89a8e1025.png)
