### ISSUE TITLE
/Nick suggestions

### ISSUE THREAD

**Issue by Terrobility** [EssentialsX/Essentials#125]
On my server, my donators can use /nick freely. I had these amazing ideas:
1. Either add a permission node to only allow people using /nick to colour their name, such as "/nick &cHunter&6G&ePlays" (even though that isn't my IGN you get the point)
2. Number 2 wasn't a good idea

**Comment by drtshock** [comment]
1. So make it so they can color their current name but not change it? Could work.
2. I don't see us doing that as it's a very narrow use. Another chat plugin could handle tooltips.

**Comment by FlippantCactus** [comment]
I think with adding hover text, it could lead to adding lots of things to the config file because people will request support for EZRanksLite, etc... Without making the plugin Deluxe Chat almost, this might be hard to do, especially as all of the good features get added.

**Comment by Terrobility** [comment]
I would like it if the first suggestion was added then. There wouldn't be much need for a blacklist using this and it would also make for a good donator perk, making players stand out in chat.

**Comment by Elgorond** [comment]
Number 1 is a great idea.

**Comment by TomLewis** [comment]
I dont like either idea, But I would like to suggest a /nick option, Add cooldowns and cost to it, and a limit, so they cant /nick whenever they feel like it, I dont ever use nick as its confusing to players to know whos who as it dousnt auto fill properly, maybe that would be better, having a proper implementation that auto fills properly with all other commands.

**Comment by Terrobility** [comment]
@FrozenBeard You could use boosCooldowns to do that. It handles costs, cooldowns, and limits.
I want number 1 to be implemented because it adds as a good donator perk. It makes you stand out in chat and really gives a person the feeling to donate for the sexy look in chat. At the same time, it adds a restriction to /nick and prevents people having retarded nicknames (not to mention players don't get confused too).

**Comment by Elgorond** [comment]
100% agree with HunterGPlays
