### ISSUE TITLE
joinfullserver kick player?

### ISSUE THREAD

**Issue by chillerkraft** [EssentialsX/Essentials#1253]
i haven't been able to try this setting to see how it works,
the essentials.joinfullserver perm, does that kick someone when someone with that perm joins a full server?
i dont want it to kick someone.

**Comment by Antivalent** [comment]
As far as I'm concerned, it won't kick any players who are already online on your server. Instead, players with 'essentials.joinfullserver' will be able to connect even if all of your slots are filled, allowing for player counts like 61/60.

**Comment by chillerkraft** [comment]
awesome:) blessed to hear that it doesnt kick anyone :) thankyou

**Comment by Antivalent** [comment]
You're welcome!

**Comment by virtualdxs** [comment]
@chillerkraft Please close this issue as it has been resolved.

**Comment by chillerkraft** [comment]
thankyou SupaGam
i finally tested this..
im op and it's saying Failed to connect to the server
ill go find the perm and give it to my player and test again

**Comment by chillerkraft** [comment]
i gave myself the perm and it still said the server is full
but im also seeing some odd activity with my perm plugin
i can test more later when i have some free time. tomorrow afternoon

**Comment by chillerkraft** [comment]
testing done
the perm doesn't work
when i have the perm and try to join a full server i get a Server is full! message
Please Fix! who do i gotta tag hmm @drtshock ?

**Comment by mdcfe** [comment]
Could you reopen the issue and post logs of what happens in the console when you try to join? Another plugin might be conflicting.

**Comment by chillerkraft** [comment]
i tested on a server with just luckperms and essentialsx but yea i'll get the logs

**Comment by chillerkraft** [comment]
https://pastebin.com/9wntie6Z

**Comment by chillerkraft** [comment]
thanks :)

**Comment by mdcfe** [comment]
```
[00:56:33] [Server thread/INFO]: [Essentials] Using config file enhanced permissions.
[00:56:33] [Server thread/INFO]: [Essentials] Permissions listed in as player-commands will be given to all users.
[00:56:33] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
```

For some reason, EssentialsX isn't detecting LuckPerms. Do you have Vault installed?

**Comment by chillerkraft** [comment]
woops
https://pastebin.com/8twi4vcu
there we go. still not workin

**Comment by mdcfe** [comment]
Hmm, I'm not sure what's causing that. Could you reopen the issue so someone else could take a look?

**Comment by chillerkraft** [comment]
yay POWERR 😃

**Comment by chillerkraft** [comment]
hmm i can't find out how to reopen this issue

**Comment by mdcfe** [comment]
~~On the desktop site, I believe there's a button at the bottom?~~ EDIT: Or not, it seems.

**Comment by chillerkraft** [comment]
im on github.com on web browser

**Comment by chillerkraft** [comment]
i don't think i have the ability to do it. maybe a github bug too here lol

**Comment by chillerkraft** [comment]
also sorta blaming SupaHam and wondering if he has the power to reopen

**Comment by mdcfe** [comment]
Not really SupaHam's fault, @virtualdxs was the person who told you to close it in the first place.

**Comment by chillerkraft** [comment]
well still shoutout to @SupaHam to re open this issue if possible :p anyways
