### ISSUE TITLE
How do I use the pay multiple command?

### ISSUE THREAD

**Issue by Carbonawk** [EssentialsX/Essentials#1255]
Within the permission wiki there is a permission called "essentials.pay.multiple" keep in mind, this is part of the old essentials wiki. Not essentialsx documentation. So it may no longer be present. However, if it is. How would I use it?

**Comment by SupaHam** [comment]
EssentialsX is a fork of the original Essentials. This fork aims to expand upon the original feature set, if something is removed (which i cant recall off the top of my head), there will be a good reason for it.

**Comment by Carbonawk** [comment]
Okay, but any idea how I would use it in a command?

**Comment by SupaHam** [comment]
You can use `*` for wildcard. And the rest is done by Bukkit's `Server#matchPlayer` method. If you're not technical and able to read Bukkit's code I could not tell you exactly what the criteria is. But the gist is that if, for example, you don't complete a name it will match multiple people that have the given search term in their name.
