### ISSUE TITLE
Request: /tpignore <username>

### ISSUE THREAD

**Issue by ygtdmn** [EssentialsX/Essentials#1257]
Can you add a command like that? Dont /ignore a player totally but only ignore player from teleportation.

**Comment by Blamo27** [comment]
This is a good idea !

**Comment by RikoDEV** [comment]
@SupaHam

**Comment by ghost** [comment]
@UnioDex maybe to add on to your request they could add like /payignore for the same reason

**Comment by voodootje0** [comment]
This would be really nice =)

**Comment by pop4959** [comment]
The command for this is `/tptoggle`. I don't think there will be support for ignoring teleportation from specific players. If you are getting spammed, have them ask you to send them a teleport instead.
