### ISSUE TITLE
[Suggestion] Option to toggle messaging/tping players nicknames

### ISSUE THREAD

**Issue by Wazez** [EssentialsX/Essentials#126]
Say Player1 has the nickname drtshoc (/nick drtshoc)
and there is a player online called drtshock

if Player3 does /tpa drt it will send a tpa to the drtshoc guy with a nickname.
The same with /msg and other commands associating players.

It's a good feature, but it gets abused on faction servers for example where players disguise/nick themselves as the other players friend/ally and tp to them.

The suggestion is to toggle commands to players nicknames and only apply to real player names.

Sorry if this doesn't make sense, I'm in a hurry, if you need me to explain it better let me know and I will.

**Comment by drtshock** [comment]
Then how would you message someone based on their nickname if you don't have access to /realname?

**Comment by Wazez** [comment]
All our players already have access to /realname XD. And you could make it toggle-able I guess.

**Comment by drtshock** [comment]
Couldn't this happen with colliding real names anyway? I just don't see the use case.

**Comment by pop4959** [comment]
Yeah I don't see the use case either. This seems fairly obscure, and it doesn't seem like there is much demand for it. You can probably get this to work the way you want by using a different tp plugin instead, as well.
