### ISSUE TITLE
Sweeping Edge Enchantment

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1263]
Server Version: 1.11.2
Essentials Version: Latest of 2.0.1
Issue: Trying to use /enchant sweepingedge/sweeping 1-3
Some reason this enchantment doesn't exist but I am certain there is a enchantment like this in vanilla minecraft but when I do /enchant it only lists the following for swords:
Sharpness
Smite
Bane of Arthropods
Mending
Unbreaking
Fire Aspect
Knockback
Looting
Vanishing Curse

Sweeping Edge should be in this list and I could have swore it was in previous Essentials versions.
Tried every sword type (Gold, Iron, Wood, Stone & Diamond) none of them had this enchantment..

Unless I'm dumb and they removed it prior to 1.11.2 then I think you should add this enchant to the list of enchantments.

**Comment by SupaHam** [comment]
I've quickly edited the class and haven't actually tested this. I would appreciate it if you could test out a build and let me know if it works. You can get it [here](https://ci.drtshock.net/job/EssentialsX/).

P.S. Using the new version should not cause any extraordinary harm.

**Comment by ghost** [comment]
Thank you very much for the quick fix (hopefully)
I'll get back to you in a second telling you if it worked!

**Comment by ghost** [comment]
Yeah it works when I do /enchant Sweeping 1-3
@SupaHam 

but it doesn't list it in the available enchants while just typing /enchant while holding a sword. Not sure if that's a easy fix.

**Comment by SupaHam** [comment]
`/enchant` lists all valid enchantments on the item (as decided by Minecraft itself), assuming the user has the enchant permission. In this case `essentials.enchantments.sweeping_edge`.

**Comment by ghost** [comment]
I was op when testing it and it still didn't show up I even tried adding that permission after and its still not there. @SupaHam

**Comment by SupaHam** [comment]
What item are you holding?

**Comment by ghost** [comment]
Diamond Sword

**Comment by SupaHam** [comment]
I'll have to look further into this at a later date, I'm currently busy with exams.

**Comment by ghost** [comment]
Okay that's fine! it's not a big issue.
