### ISSUE TITLE
[Suggestion] Add MySQL and SQLite Databases

### ISSUE THREAD

**Issue by Portanna** [EssentialsX/Essentials#1265]
A cool addition in order to get rid of all those annoying .yml userdata (with 300+ yml opening that folder gets harder and harder), would be adding the possibility to use MySQL or SQLite databases.
SQLite would be cool for those server owners that don't know / can't configure a MySQL server but they want a compact database.
MySQL would be cool for server owners that want all data organized in their sql databases (also for web-hooks).

Another addition that would be very useful is a userdata timer that deletes all user data older than x days, configurable in the config.yml, this way if you still want to keep .yml database at least you just have to deal with the active users' userdata.

**Comment by mdcfe** [comment]
Database support has been [suggested](https://github.com/drtshock/Essentials/issues/241) [many](https://github.com/drtshock/Essentials/issues/440) [times](https://github.com/drtshock/Essentials/issues/815), and [deemed unfeasible by the original Essentials author](https://github.com/drtshock/Essentials/issues/241#issuecomment-166185349) and [rejected by the current maintainer](https://github.com/drtshock/Essentials/issues/440#issuecomment-189747237).

See #167, #241 and #440.

**Comment by Portanna** [comment]
Ok sorry
