### ISSUE TITLE
Remove tp request when player teleported

### ISSUE THREAD

**Issue by ygtdmn** [EssentialsX/Essentials#1266]
Hi, im recently taking a lot of reports. A player(im gonna say "A") wants from another player (im gonna say "B") send teleport request to him. After B send the request A dont accept it and waits for B to take expensive items to his inventory. When B takes good items A accept it and kill B unexpectedly.

For this reason can you remove tp request when a player teleports to another place? Thanks.

**Comment by mdcfe** [comment]
This should probably be a config setting because I can see that some people might not like it, but it seems like a good idea.

**Comment by SupaHam** [comment]
`/tpatoggle` has been introduced in c28d7495. You can grab the feature from [build 474](https://ci.drtshock.net/job/EssentialsX/) on the CI server.

Do you think this is a sufficient fix?

**Comment by mdcfe** [comment]
I mean, this doesn't directly solve the problem, but I guess it helps.

**Comment by ygtdmn** [comment]
Yeah it is sufficient i guess. But still players need to get used to this and they should remember the new /tpacancel command. Still an automatic cancel would be good.
