### ISSUE TITLE
essentials.joinfullserver not working

### ISSUE THREAD

**Issue by chillerkraft** [EssentialsX/Essentials#1268]
https://github.com/drtshock/Essentials/issues/1253

**Comment by mdcfe** [comment]
### Logs from #1253
* [Without Vault](https://pastebin.com/9wntie6Z)
* [With Vault](https://pastebin.com/8twi4vcu)

**Comment by mdcfe** [comment]
Can you try setting `use-bukkit-permissions: true` in your Essentials config?

**Comment by chillerkraft** [comment]
i did that and only that not sure if i need to add the perm essentials.joinfullserver somewhere else with that option true? it still says server full when trying to join https://pastebin.com/ty2NF7cE

**Comment by chillerkraft** [comment]
i opped myself and it says failed to connect to the server https://pastebin.com/U2pSibzU and i think there's an off ERROR message in there too, player connection reallowed? hmm.. i had reported that to LuckPerms yesterday too since the ERROR was showing up with ]LuckPerms] in front of it

**Comment by chillerkraft** [comment]
i mean i opped the player to give him that permission and tried joining with oped player and got the Failed to connect to server message

**Comment by chillerkraft** [comment]
please fix

**Comment by voodootje0** [comment]
This is actually true, it just don't work when all player slots are filled and player with the permission try to join it still cannot join.

**Comment by chillerkraft** [comment]
https://pastebin.com/ge15zdcM

**Comment by chillerkraft** [comment]
@voodootje0 works fine for me, i must have been doing something wrong during the testing, or maybe it's a problem with multicraft hosting services etc?

**Comment by imaBASKET** [comment]
http://i.imgur.com/yhkh8f0.png

**Comment by mdcfe** [comment]
@imaBASKET Please create a new report for your issue.
