### ISSUE TITLE
How to delete account?

### ISSUE THREAD

**Issue by yasons-zz** [EssentialsX/Essentials#1269]
Hello, I'm using spigot 1.11

Since I'm not using white list because I not in full timer in managing my server, can we delete account using essentials command? or to check registered accounts using command?

I know that there is a folder called player data, but wew~~
It's all in UUID, it's so tiring to open one by one to check the ID
sometimes an account of wrong lettters in name are registered, so I want to delete it.

Any suggestion?

Thank you.

**Comment by mdcfe** [comment]
You can use `/seen` with either a username or UUID to search for users. The usernames and UUIDs are mapped in `plugins/Essentials/usermap.csv`.
