### ISSUE TITLE
Economy prefix removal.

### ISSUE THREAD

**Issue by FlippantCactus** [EssentialsX/Essentials#127]
![](http://i.imgur.com/4e1ua6i.png) 
This is what is shown upon using the /balance command.
Config.yml setting: currency-symbol: ''
Essentials message properties setting: balance=\u00a77You have \u00a7a{0} \u00a77in tears.
I'd like to be able to remove the economy prefix completely, that way you can make the command fully customisable and look a bit nicer too.

**Comment by drtshock** [comment]
`currency-symbol: '$'` in the config.yml

**Comment by drtshock** [comment]
oh nvm. i see your issue now. rip

**Comment by triagonal** [comment]
This is already possible (added in 6da705c) by editing the `currency` key in `messages.properties`.

As `{0}` is the currency symbol and `{1}` is the amount, changing the value from `currency={0}{1}` to `currency={1}` produces the desired effect:

![image](https://user-images.githubusercontent.com/10545540/79998156-b1097200-84fd-11ea-9474-1e9bfceb647b.png)
