### ISSUE TITLE
Request: Meta to spawn tipped arrows with /i

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#1272]
I cant seem to find a way to spawn tipped arrows into kits with /i I cant just add on effects like potions from the meta http://wiki.mc-ess.net/wiki/Item_Meta

Please can you add it so we can spawn tipped arrows from a command that can be used in kits. Look at the potion meta page, should be the same as that.

**Comment by pop4959** [comment]
They can be spawned now using the new Item DB implementation.

For example: 
/i tipped_arrow
/i poisonarrow
