### ISSUE TITLE
1.12 chat is overidden by mojangs chat format

### ISSUE THREAD

**Issue by Legoman99573** [EssentialsX/Essentials#1273]
There are no errors, it seems that mojang has updated how chat works now.

**Comment by SupaHam** [comment]
1.12 isn't released yet, so please do not expect immediate support.

Can you elaborate on this issue? What is happening? What are you expecting to happen and why?

**Comment by Legoman99573** [comment]
@SupaHam didnt expect immediate support. Just posting ahead of time since i ran it over a test server with only essentials. Plus pre6 of spigot is out.

**Comment by SupaHam** [comment]
I still don't know what the issue is.

**Comment by mdcfe** [comment]
I'm guessing EssentialsXChat's formatting isn't working?

**Comment by SupaHam** [comment]
If there's anything wrong, we have to wait until an official Spigot full version release and investigate from there. If there's nothing that you think is directly the cause of this issue, then we mustn't speculate.

**Comment by TNTUP** [comment]
I see nothing wrong with EssentialsChatX. Works as usual on my 1.12 test server :)

**Comment by Twonox** [comment]
@Legoman99573 
Any news ?
Do you have Vault and Faction plugins ?

**Comment by Legoman99573** [comment]
Bug occurs when you use LuckPerms. Works fine when I use PEX, so I used PEX again until there is support for LuckPerms.

**Comment by mdcfe** [comment]
If this is still an issue, please reply with more details on what the actual issue is (such as exactly where the issue occurs).
