### ISSUE TITLE
EssentialsX shadows minecraft:give and does not provide auto-completion

### ISSUE THREAD

**Issue by cjunekim** [EssentialsX/Essentials#1277]
EssentialsX shadows minecraft:give with its Commandgive class. However, the EssentialsX's give does not provide auto-completion on the item name.

It would be desirable either:

 * user can disable essentials:give(but leaving essentials:egive) and instead use minecraft:give as the default for /give
 * essentials:give provides auto-completion on item names

**Comment by mdcfe** [comment]
You can use the `commands.yml` file to alias /give to /minecraft:give.

**Comment by cjunekim** [comment]
Yes, I can but then the minecraft:give's auto-completion becomes unusable, since auto-completion isn't handled in aliased commands.

**Comment by SupaHam** [comment]
#1203 and #1282 are implementing tab support for Essentials command. Please be patient and follow #1282 instead. Thank you.
