### ISSUE TITLE
Permissons

### ISSUE THREAD

**Issue by CreeperBoyNick** [EssentialsX/Essentials#1278]
im trying to make permissons in my server but it doesnt work normaly i have to do like essentials.msg or something but what do i need to do with this plugin?

**Comment by mdcfe** [comment]
You can find all the permissions you need on the [old Essentials wiki](http://wiki.mc-ess.net/wiki/Command_Reference/Perm) and the [new EssentialsX wiki](https://github.com/drtshock/Essentials/wiki).
