### ISSUE TITLE
Teleportation triggering on its own

### ISSUE THREAD

**Issue by PetKCH** [EssentialsX/Essentials#1281]
As title say, after server is up for around 10 hours this happens. I tried using latest version, tried using older version, still happens;
https://gyazo.com/14e022545ae1b7e26f0c002b118515a1
https://gyazo.com/916ba22c77b45f8181454bdd03deb367

Only fix is restart, then it stops for few hours.
There are no errors in the log....

**Comment by mdcfe** [comment]
* What server version do you have installed? `/version`
* What EssentialsX version do you have installed? `/ess`
* What other plugins do you have installed? `/plugins`

I'm almost certain this isn't an EssentialsX error.

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to reopen the issue, adding the requested details.
