### ISSUE TITLE
Suggestion: Add command toggles

### ISSUE THREAD

**Issue by Portanna** [EssentialsX/Essentials#1284]
Adding the possibility to toggle all essentials functions in config.
For example, to completely disable the "afk" system: "toggle_afk: true", which when the plugin starts won't register the afk commands and listeners, this for every command.
Another example, you have a custom TPA, TPAHERE plugin and want to use the same commands, "toggle_tpa: false" would disable the entire tpa/tpaccept system and commands registration on restart.

Could be cool for those servers that only need certain aspects of Essentials, and not every feature, this way the plugin could be more efficient performance-wise.

:)

**Comment by mdcfe** [comment]
You can already disable EssentialsX commands by adding the command to the [`disabled-commands` in your `config.yml`](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/config.yml#L143), although to my knowledge this has a minimal effect on performance.

If you're experiencing a command conflict with another plugin, however, you'll want to use [Bukkit's `commands.yml`](https://github.com/drtshock/Essentials/wiki/Known-Issues#essentialsx-overrides-a-command-from-spigot-or-another-plugin) to alias the desired commands to the other plugin as needed.
