### ISSUE TITLE
Tab Complete Build #481 Doesn't work

### ISSUE THREAD

**Issue by LogGits** [EssentialsX/Essentials#1287]
Title says it all. I am testing out the tab complete on build 481 and none of the commands will work with tab. e.g. /tpa + [tab] results in nothing. However, tab complete works for other plugin commands. Is there like a new setting I am missing?

**Comment by SupaHam** [comment]
4c0857f only adds the tab completion framework. The actual individual command tab completion is not yet on the master branch, however I'm awaiting some feedback on #1282 before I can bring in those changes.

**Comment by SupaHam** [comment]
This has been fixed in bbe0ca9. You can grab the fix from [build 483](https://ci.drtshock.net/job/EssentialsX/) on the CI server.
