### ISSUE TITLE
Permissions??

### ISSUE THREAD

**Issue by craftingtables** [EssentialsX/Essentials#129]
I'm using bPermissions and I'm making a default group. Some of the original essentials permissions work but some of them don't. I added essentials.afk and it works but I added essentials.tpaccept or essentials.warp.shop it doesn't work. I test it out and it says I don't have access to that command. Please help! my server is almost finished.

**Comment by FlippantCactus** [comment]
https://github.com/drtshock/Essentials/wiki has all of the changes. 
https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/plugin.yml shows all the commands, just add essentials. to all of the commands and that should be the permission.
