### ISSUE TITLE
Tab completion #482

### ISSUE THREAD

**Issue by maginka** [EssentialsX/Essentials#1292]
Using latest dev build, on MC 1.12,  breaks Tab completion when using things like /tp, /tpa etc.

I rolled back to an earlier version and it works fine.

**Comment by smmmadden** [comment]
I think that's a known issue that the tab completion isn't working right for essentials.  There were a few others reporting the same so I know that the developer is working on it. :-)

**Comment by maginka** [comment]
Thanks for the heads up

**Comment by SupaHam** [comment]
Duplicate of #1287.

(There should be no tab completion as it was never actually built on the CI server.)

**Comment by SupaHam** [comment]
This has been fixed in bbe0ca9. You can grab the fix from [build 483](https://ci.drtshock.net/job/EssentialsX/) on the CI server.
