### ISSUE TITLE
/reply ignores mute?

### ISSUE THREAD

**Issue by molor** [EssentialsX/Essentials#1293]
Is it really so? If a player is muted, but it someone wrote in the PM, he still may answer? Why?

If it is so intended, could you make /r command as alias of /reply, not vice versa? Just because commands in this case in the plugin.yml will look better.

**Comment by delbertina** [comment]
I agree, this seems like it is not working as intended. Just looking at the commandmsg and commandr files looks like commandr is just missing : 

```
if (user.isMuted()) {
throw new Exception(tl("voiceSilenced"));
}
```

from the commandmsg file to check if a player is muted.

Disclaimer: Not a good plugin dev, just trying to help.

**Comment by delbertina** [comment]
In my testing, issue is fixed after one of the latest dev versions with that merged PR.
#1375

**Comment by mdcfe** [comment]
This was fixed in a recent build - you can get the latest version from the [build server](https://ci.drtshock.net).
