### ISSUE TITLE
Tab Completing Playernames in ESS Commands

### ISSUE THREAD

**Issue by Fluxty** [EssentialsX/Essentials#1294]
Tab complete no longer works since the tab complete framework was added. Previous to this version we could tab complete online player names in our commands, I.E. /tpa <player> or /invsee <player>. This is a very annoying change for our playerbase and really hope you guys patch that one up! Thank you :+1:

**Comment by mdcfe** [comment]
Revert to a version prior to the tab completion framework commit, or wait patiently for tab completion to be finished.

**Comment by d3ath2005** [comment]
@md678685 - Do you know when they'll add that feature?

**Comment by SupaHam** [comment]
See #1287.

**Comment by SupaHam** [comment]
This has been fixed in bbe0ca9. You can grab the fix from [build 483](https://ci.drtshock.net/job/EssentialsX/) on the CI server.
