### ISSUE TITLE
1.12 - Tab complete of player names is not working for essential commands

### ISSUE THREAD

**Issue by Drag0nz69** [EssentialsX/Essentials#1295]
Running 1.12 and dev build of EssentialsX #482 

When executing EssentialX commands like /tp, /tpa, /eco, /pay, etc the Tab-Complete action on player names is not working. Commands for other plugins are auto-completing names.

**Comment by PetKCH** [comment]
Not working on 1.8.8 either.

**Comment by SupaHam** [comment]
Duplicate of #1287

**Comment by SupaHam** [comment]
This has been fixed in bbe0ca9. You can grab the fix from [build 483](https://ci.drtshock.net/job/EssentialsX/) on the CI server.
