### ISSUE TITLE
com.earth2me.essentials.EssentialsTimer lag

### ISSUE THREAD

**Issue by Bedah95** [EssentialsX/Essentials#1297]
Hello,
we get some lags caused by com.earth2me.essentials.EssentialsTimer on our server.
Do you know about any reasons?

[Timings](https://timings.aikar.co/?id=16f026e980af45e384799a0df64b3641)

**Comment by mdcfe** [comment]
Closing as the timings report is no longer available. If this is still an issue, feel free to respond with a new timings report.
