### ISSUE TITLE
Tab completion broken for some commands

### ISSUE THREAD

**Issue by pop4959** [EssentialsX/Essentials#1301]
Several commands, such as /seen and /whois no longer correctly tab complete in the most recent versions of EssentialsX. For these particular commands, they would tab complete for a player currently online in prior versions.

List of broken commands (missing tab completion):
/exp give/set
/speed
/unlimited
/setworth
/realname
/seen
/spawner
/whois
/spawnmob
/sudo
/unban
/unbanip

List of broken commands (incorrect tab completion):
/tree
/remove
/setspawn

**Comment by LogGits** [comment]
Can confirm tab complete isn't working for some commands including /seen and /whois. Tab complete does work for other commands such as /tpa, /tp, and /mail.

**Comment by FrankHeijden** [comment]
Can also confirm, not working.

**Comment by NinjaSlatz** [comment]
I also have this problem.

**Comment by CheatSupport** [comment]
Confirmed

**Comment by pop4959** [comment]
Found more commands that do not adhere to the syntax description found at [http://wiki.ess3.net/wiki/Command_Reference](http://wiki.ess3.net/wiki/Command_Reference). I've put these in the OP, but keep in mind that these are only commands that I tested, and therefore by no means an exhaustive list. I'll update the list if you guys find anything else broken.

**Comment by SupaHam** [comment]
This has been fixed in 12930cf. You can grab the fix from [build 493](https://ci.drtshock.net/job/EssentialsX/) on the CI server.
