### ISSUE TITLE
[Suggestion] Multiple prefixes/suffixes in EssentialsChat

### ISSUE THREAD

**Issue by AfkF24** [EssentialsX/Essentials#1305]
I feel like this is our's permissions plugin's job, but I'm gonna suggest this here anyways. Basically, this feature would allow users to have multiple prefixes or suffixes displayed in chat based on Permission groups they're in. I know that a plugin called **ChatEx** has this. 

For example PermissionEx: A user can be in multiple groups, but only the prefix/suffix from the 'highest' group they're in (if using rank ladders) would show in chat.
Let's take another example - GroupManager: User can only have one main group, but can be a part of multiple subgroups, and only the main group's prefix/suffix would display in chat. What Multi-Prefix/Suffix does in ChatEx is that it basically displays prefixes/suffixes from subgroups as well, which is really neat. You can basically have your chat formatted somewhat like this using this feature: '[Rank1] [Rank2] Playername [Rank3]: Message'. (Where the user is a member of groups Rank1, Rank2, Rank3, and groups Rank1 and Rank2 have only got setup up prefixes, while the group Rank3 has only got set up a suffix), etc.

**Comment by mdcfe** [comment]
This is already supported in LuckPerms, which allows you to combine multiple prefixes before passing them to chat formatting plugins.

In addition, we don't support GroupManager or PermissionsEx any more, so the only plugin that would be supported by this would be LuckPerms anyway.

I would recommend switching to LuckPerms which already supports this.
