### ISSUE TITLE
/worth deletes items.

### ISSUE THREAD

**Issue by Spooklin** [EssentialsX/Essentials#1307]
Currently, /worth deletes your item.

Essentials version: 2.0.1-b370
Spigot: 1.12-R0.1-SNAPSHOT

I am aware that both are outdated. If this bug was squashed, I'll prioritize updating as I was holding that off until Thursday night.

**Comment by mdcfe** [comment]
705c1c60c85a74ae3e832dccc161ae5a1f0d4025 fixed this - update EssentialsX to the [latest version](http://ci.drtshock.net/job/EssentialsX/lastSuccessfulBuild).

**Comment by Spooklin** [comment]
But still, my build isn't 5 months outdated, so I shouldn't have it, right?

Op ma 19 jun. 2017 om 18:24 schreef md678685 <notifications@github.com>

**Comment by mdcfe** [comment]
The point was that you're on an ancient version of EssentialsX and this was patched a long time ago.

**Comment by Spooklin** [comment]
Hmm, I'll make sure my friend doesn't get to do the patching anymore. I'll
fix it ASAP, apologies for bothering you with something that was so
obviously our fault!

Op ma 19 jun. 2017 om 18:45 schreef md678685 <notifications@github.com>
