### ISSUE TITLE
SUGGESTION: Implement confirmation dialogue for `/ci`

### ISSUE THREAD

**Issue by CheatSupport** [EssentialsX/Essentials#1309]
Just like https://github.com/drtshock/Essentials/pull/1002

but instead for /ci (clear inventory)

@SupaHam @Kakifrucht @drtshock @vemacs

**Comment by mdcfe** [comment]
Please don't close and reopen issues to bump them.

This is a duplicate of #1040.

**Comment by Sikatsu** [comment]
Would love to see this too! Often had issues with players performing /ci or trolling eachother to use /ci.

**Comment by CheatSupport** [comment]
Agreed Sikatsu!

**Comment by mdcfe** [comment]
This was added ages ago, didn't realise this was still open.
