### ISSUE TITLE
Bungeecord Compatibility Issues

### ISSUE THREAD

**Issue by Samistine** [EssentialsX/Essentials#131]
Okay here is the issue. When I disable force_default_server and a specific player leaves and joins back on the same server, essentials works. However, if the player leaves another server, comes back and transfers to the server with essentials it stops working.

By stops working, I mean some features such as /msg don't work for specific people. I am able to reproduce this 100% of the time, but it requires an account that has such issue. The accounts having such issue are almost random, as far as I know it only happens to a select amount of people who have nicks and prefix/suffix's.

Plugins on Bungeecord 0
Plugins on Spigot server - Plugins (5): PermissionsEx, Essentials, EssentialsSpawn, EssentialsChat, EssentialsGeoIP

**Comment by drtshock** [comment]
I don't see how this is an essentials issue. They are still joining the server as far as essentials is concerned. Can you paste the logs of the players when they join with debug mode enabled? We'll see if the initplayer method ever gets called or not.

**Comment by Samistine** [comment]
I am quite busy at the moment, but I believe when I checked with debug mode all methods were being called. I can't seem to figure out what in Essentials/Pex is causing this.

**Comment by drtshock** [comment]
Nothing, it'd be something in bungee then.
