### ISSUE TITLE
Alert Issues

### ISSUE THREAD

**Issue by Astrareach** [EssentialsX/Essentials#1311]
Hi

The alert must not be fired normally :
https://prnt.sc/flz218

Regards

**Comment by Astrareach** [comment]
the alert is still here after removing the permission essentials.protect.alerts

**Comment by mdcfe** [comment]
What permission plugin are you using? Could you post your permissions config (through [Hastebin](https://hastebin.com) or [Gist](https://gist.github.com/) ideally)?

**Comment by mdcfe** [comment]
Did you solve your problem? If so, could you paste how you did to help others with the same problem?
