### ISSUE TITLE
Spamming "You have 1 messages! Type..." everytime I use essentials command and #1026

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1312]
First issue is same as: #1026 

**Second issue:**
When I have mail inbox and write random essentials command like /msg, I will receive message, that I have email inbox. It is very annoing because it works with every essentials command like /gamemode, /heal, /god, ...

Can you fix it or add option to the config? Thank you.

**Comment by SupaHam** [comment]
Real your mails?

**Comment by ghost** [comment]
I have to clear mails if I want to remove this message. Imagine you are administrator and players are sending mails very often.

**Comment by SupaHam** [comment]
This has been introduced in 11a03bb. You can grab the feature from [build 490](https://ci.drtshock.net/job/EssentialsX/) on the CI server.

Thanks for the feature request. :)

**Comment by ghost** [comment]
Great! Can you fix #1026 too?
