### ISSUE TITLE
/whois tab completion does not work, and playtime is completly wrong.

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#1314]
- /whois tab-completion isn't working.

- The new playtime is completly wrong. there is a statistics folder in the over-world with the players playtime in this, already waiting, checking on a player with 110 days playtime it says they have played 2 days.

**Comment by SupaHam** [comment]
Create issues separately please.

Tab completion fixed in 12930cf. You can grab the fix from [build 493](https://ci.drtshock.net/job/EssentialsX/) on the CI server.

`playtime` is based on statistics. Make sure you're not deleting the statistics files.

**Comment by TomLewis** [comment]
Awesome. Im not deleting Statistics files, I never have, at what point would I be deleting statistic files?

**Comment by SupaHam** [comment]
Statistics files exist in the main world directory. So any playtime that is displayed on there is what Minecraft thinks.

**Comment by mdcfe** [comment]
Do you have a multiworld inventory/player data plugin installed like PerWorldInventories, MultiInv or Multiverse-Inventories? They might be configured to overwrite player data when switching worlds.

**Comment by TomLewis** [comment]
@md678685 nope.
