### ISSUE TITLE
AFK Changing TAB names

### ISSUE THREAD

**Issue by misuda12** [EssentialsX/Essentials#1321]
Hello EssentialsX engineers,
I've noticed, when someone is AFk or use /afk command, than it change the name, that is displayed in TAB
Please, try to solve that.
- misuda12
![image](https://user-images.githubusercontent.com/19598684/27492233-c90cd758-5845-11e7-9ae4-8394e73093eb.png)
![image](https://user-images.githubusercontent.com/19598684/27492248-d664e8dc-5845-11e7-9d8b-f2e2b4faa0c3.png)

**Comment by SupaHam** [comment]
Please <http://pastebin.com> your config.yml and post URL here. Thanks

**Comment by mdcfe** [comment]
I think this is safe to close, as no information was ever provided.

@SupaHam or @misuda12, feel free to reopen this if you feel it is appropriate.
