### ISSUE TITLE
Suggestion: Remove fly on remove permission

### ISSUE THREAD

**Issue by FabioZumbi12** [EssentialsX/Essentials#1322]
Hi,

I want to suggest to remove fly from player when this player dont have the command permission to fly (and a option on config to choose if disable the fly without permission). 

The problem i having its because, as example, i have two vip plans, one with fly and other with not. If a player have both vip, he change to vip with fly, enable this vip and change back to vip without fly, but still flying.

**Comment by mdcfe** [comment]
I'm not sure that this is worth implementing - we would need to regularly check their permissions (as I don't think Vault has permission events) and also track whether they have used `/fly` to avoid disabling flight when the player didn't enable it for themselves in the first place (staff using `/fly <player>`, other plugins, creative mode, spectator mode).

**Comment by FabioZumbi12** [comment]
I think this too and is not an emergency or too important feature, but like my suggestion, add an option on config (with false by default) to we choose if will regularly check for permission.

**Comment by Kakifrucht** [comment]
Sounds very specialized and shouldn't be included in this project imo. Not an "essential".

**Comment by mdcfe** [comment]
I don't see that this can be done in a way that is efficient while supporting most permissions plugins. In addition, I'd say that `essentials.fly` should remain the permission for the `/fly` command and not have additional side effects like this.
