### ISSUE TITLE
Teleport issue

### ISSUE THREAD

**Issue by MithrandirCraft** [EssentialsX/Essentials#1328]
Players are safely placed wrongly in situations such as the following:
https://www.youtube.com/watch?v=-Ko-VHICEzQ&feature=youtu.be
This is a problem because it can be used in order to breach inaccesible areas if the right conditions are met.

I'm using EssentialsX (Which sent me here), version: 2.0.1-b460
Spigot: MC->1.11.2

**Comment by SupaHam** [comment]
There's a little bit of an issue with this one. It won't be as simple as checking if the foot block is a "safe" block such as water. It will also need to check that there is a solid block under, so the player may not teleport and proceed to drown.

**Comment by MithrandirCraft** [comment]
An easy solution in order to stop these breaches from occuring would be to give the config option for forcing no teleportation if the location is unsafe.

**Comment by ghost** [comment]
@MithrandirCraft Thats already a thing.

In the config.yml:

If the teleport destination is unsafe, should players be teleported to the nearest safe location?
If this is set to true, Essentials will attempt to teleport players close to the intended destination.
**If this is set to false, attempted teleports to unsafe locations will be cancelled with a warning.**
teleport-safety: true

**Comment by MithrandirCraft** [comment]
That piece of config doesn't show up on my EssentialsX config. So right now I'm attempting at adding it manually after: `teleport-invulnerability`

**Comment by MithrandirCraft** [comment]
Ok, so now with that feature, no one is teleported if the location is unsafe.
However, this also affects admins. Can it be disabled for such?
Else, could teleports be done even if the location is unsafe?
All the current options seem imperfect.

**Comment by pop4959** [comment]
You can turn off teleportation safely in the config. Otherwise, use another plugin that restricts players from entering areas that should not be accessible.
