### ISSUE TITLE
money NBSP

### ISSUE THREAD

**Issue by Andrey228322** [EssentialsX/Essentials#1329]
How fix it?
https://images-ext-2.discordapp.net/external/RbCcC-y6eXogqza4XUrUhToV9IpRRGAEOVNQ6Whepo0/https/images-ext-1.discordapp.net/external/hP31MFYytsUvLPhLoafvm8D9NHrYZ4TnN84Lndx9E88/https/images-ext-1.discordapp.net/external/T8jcXnmPKum9imiJFc1smUGHe115B0qpmwRFkBmScFM/https/images-ext-2.discordapp.net/external/N0U9FYJtlYpBohdh5YfW2GNckXTJ7z49Nn9aedaWFrc/https/images.discordapp.net/attachments/279224905906782210/327832936969666570/e55d2be0b9058c7c.PNG

**Comment by mdcfe** [comment]
Where does this happen? I can't read this so I don't know what is happening.

**Comment by SupaHam** [comment]
This is why we document things. https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/config.yml#L633
