### ISSUE TITLE
Teleport Velocity?

### ISSUE THREAD

**Issue by zRiaz** [EssentialsX/Essentials#133]
Hai
Basically my players have been complaining quite a lot about when teleporting they get teleported 1 block down and get sort of stuck in the floor for a little while. They say it happens roughly 50% of the time.

Not sure if its completely caused by Essentials but still thought I should make a ticket about it and maybe get some answers :octopus:

**Comment by EvilOlaf** [comment]
I noticed this quite a while ago with essentials. Happens when for me when the world is not loaded fast enough. 
Happened for warps took, solved this by setting the warp one block higher as the floor was. 
Maybe something similar could be used for teleports. Like target position = y+1

**Comment by zRiaz** [comment]
Yes, but it also happens when people go to their homes etc. So I would have to tell everyone to set their home 1 block high wouldnt be very good. (As many wouldnt do it and be annoyed by it) so idk if its something on essentials part then a fix/an option to teleport them maybe a block above the location they are going to would be nice?

**Comment by Cldfire** [comment]
I've had this issue as well.

**Comment by pop4959** [comment]
Closing since I don't think this is a very prevalent issue anymore. This used to happen years ago, and it's most likely due to how the server itself handled teleportation rather than Essentials itself. Lag may cause this as well as EvilOlaf mentioned.
