### ISSUE TITLE
tppos world argument

### ISSUE THREAD

**Issue by LyraGhost** [EssentialsX/Essentials#1335]
In the wiki it says the tppos command now has a world argument, however when I try to use it in game theres no way of putting the world name?

Was this intended?

**Comment by md678685** [comment]
What version of EssentialsX are you running?

**Comment by mdcfe** [comment]
It should be supplied as the fourth argument. It was added in 3283b8c0a3e29454156175b97108d6d83f56478f almost two years ago, so your version should support this.
