### ISSUE TITLE
place bed down - brreak bed - stays floating

### ISSUE THREAD

**Issue by smmmadden** [EssentialsX/Essentials#1336]
Okay, maybe it's me, but I was trying to figure out how to dye a bed and put a bed in my hand and some blue dye.  Placed the bed down and tried right clicking with the dye.  That didn't work, but I got a message that my bed spawn is set (lovely, not what I wanted).  So I broke the bed but then it just floats in the air as  tiny sized bed and no way to pick it up into my inventory.
![bed](https://user-images.githubusercontent.com/10309346/27522075-4121d8fe-59f1-11e7-8f33-6343497802a4.png)
![bed-floating](https://user-images.githubusercontent.com/10309346/27522078-45cf14fc-59f1-11e7-8352-399c0cfb4322.png)
Are we not allowed to break a bed or pick it up and move it anywhere?  This is on BungeeCord Server 1.12 / Spigot 1.12 (both builds from today) and EssentialsX2.0.1b491
Thanks guys! -Steve

**Comment by Antivalent** [comment]
This is possibly a bug in Bukkit, Spigot and Paper which occured today, it prevented players from picking up any items (I had this issue myself). If you update Spigot now and restart your server, the issue should be gone.

PS: If you want to dye beds, you need to use the right colored wool when crafting them. As far as I know, there is no way to re-dye a bed which has already been crafted.

**Comment by smmmadden** [comment]
Confirmed, just rebuilt my servers with today's build and can now pick up beds/other blocks after breaking.

Thanks!
