### ISSUE TITLE
[Suggestion] Allow tab-completion of home points also for players with 'essentials.home.others'

### ISSUE THREAD

**Issue by Antivalent** [EssentialsX/Essentials#1337]
I don't know if this is intended or not, but on my server (using EssentialsX 2.0.1-b491), a player can't tab-complete his home points as soon as he is granted the 'essentials.home.others' permission, and the server will suggest player names instead.

I get that this might be helpful when using the `/home <player>:<home>` syntax, but I would find it more useful to still tab-complete home points instead of player names (or maybe do both as a compromise), since players with 'essentials.home.others' will still most frequently use the /home command to target their own home points.

**Comment by TomLewis** [comment]
Congrats on getting issue ID 1337

**Comment by Antivalent** [comment]
Thanks!
But I'm more interested in the EssentialsX Devs' opinions about those suggestions I keep posting. I haven't gotten any responses so far :/
