### ISSUE TITLE
[Suggestion] Command to rebroadcast /motd to everyone & MOTD delay

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#1338]
2 simple suggestions, I use /motd to relay important information to players when they log on. 
I have noticed a few issues over the 4 years I have used it.

1. It displays so fast in chat that its lost as in-game chat happens fast, If we could have an option to delay the MOTD for a few seconds, we could let the user get in and settled and then send them the message. its like when you get in form a long day at work, open the front door and you are bombarded as soon as you get in. Allow them some room to settle and then send the MOTD.
2. Add /bmotd, To broadcast the MOTD again, this would be good to remind people to read the MOTD, its auto broadcast to everyone, This could also be used from any automated system to run commands (Cron/web ui to auto push commands) so then it can be auto sent every X amount of time. or any of the millions of scheduling plugins to auto run commands.

edit: Oh man I missed out on being issue 1337 by 1! :(

**Comment by Antivalent** [comment]
I like the delay idea a lot. If you have multiple plugins sending you messages on join, it appears to be quite random which one is displayed first and parts of different messages can even get stuck in between each other.

Even though I try to be minimalistic with plugin messaging especially on player join, as soon as you have a second plugin with a motd, things start to get very inconsistent.

**Comment by TomLewis** [comment]
I try to keep my chat tidy and very minimal, the issue is when its busy and I have over 50 people online, its just normal chat that pushes the MOTD down. both the delay and being able to rebroadcast it whenever I see fit would be a lifesaver. And nether would be big jobs to implement.

**Comment by pop4959** [comment]
Looks like this delay feature has been merged already, so closing this issue.

**Comment by TomLewis** [comment]
Aye, I did post this 3 years ago, have since switched to one that can actually use JSON and placeholderapi now, how on earth Essentials doesn't suppose these still is nuts.
