### ISSUE TITLE
/recipe shows pink cubes

### ISSUE THREAD

**Issue by Platinteufel** [EssentialsX/Essentials#134]
Hello,
typing /recipe workbench only shows me pink cubes instead of wooden planks.

**Comment by drtshock** [comment]
what are pink cubes

**Comment by ChanceSD** [comment]
I think he means this: http://hydra-media.cursecdn.com/minecraft.gamepedia.com/f/f4/Lockedchest13w18b.png?version=53b47933d81b7d9d9ba124d131c325a2
It has happened to me too with one of the recipes.

**Comment by Agazed** [comment]
http://i.imgur.com/hK5SF1d.png

I can confirm this

**Comment by Kakifrucht** [comment]
+1, should be easy fix though.
This happens, when the data value of the item is non existant and is a new behaviour in Minecraft 1.8.

**Comment by drtshock** [comment]
Which version of minecraft / spigot and essx?

**Comment by Agazed** [comment]
1.8.8 and b186 Seems to have the issue.

**Comment by Platinteufel** [comment]
Spigot 1.8.8, latest EssX dev build. Just test it in your environment. Should be broken since 1.8.
/recipe workbench

**Comment by npateras** [comment]
Guys, the /recipe command is broken cuz the item ids changed since they editted it, it shows corrupted texture, the Dev needs to update them.

**Comment by Kakifrucht** [comment]
I suspect this line to be the issue: https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/commands/Commandrecipe.java#L93

This only happens to shaped recipes, and all of the pink cubes are set to amount 0. Not sure though.

**Comment by Jikoo** [comment]
Recipes that support any data value of item have ingredients with data values of Short.MAX_VALUE. Since 1.8, any data value of a block the client doesn't have a texture for displays as the missing textures magenta and black check pattern, where before it would just show the default texture.

**Comment by Kakifrucht** [comment]
Jikoo so why does this only affect shaped recipes?

**Comment by Jikoo** [comment]
@Kakifrucht I do not believe that shapeless recipes would display properly either.

If you could, please provide an example of a shapeless recipe that uses blocks with nonspecific data values that displays correctly - I can't think of a single one in vanilla, which could be why you have not experienced it.

**Comment by Jikoo** [comment]
Those items do not require blocks of nonspecific data values.

**Comment by Kakifrucht** [comment]
Thanks, makes sense.
