### ISSUE TITLE
Buy, sell and ETC signs are broken.

### ISSUE THREAD

**Issue by F0xin1** [EssentialsX/Essentials#1344]
While setting up my server's shop, I tried to create a [Buy] Sign, but whenever I set it up correctly and exited the sign editor, it says
`Error: Unknown item name: .`

Image: https://i.ohcumin.me/06-27-17-T8L480.png

I was originally using the Spigot essentials thing, thinking that EssentialsX would fix it, but it's still broken :P.

**Comment by SupaHam** [comment]
If two separate plugins are not fixing your problem, I would start considering the problem is coming from your methodology.

http://wiki.mc-ess.net/wiki/Sign_Tutorial#Buy_Sign
