### ISSUE TITLE
tab auto complete not working (broke after recent changes) for /seen etc

### ISSUE THREAD

**Issue by CheatSupport** [EssentialsX/Essentials#1345]
I can't use /seen (name) now, using 1.8  server software (spigot)
This broken after the recent update to fix auto tabbing for commands such as /give

**Comment by CheatSupport** [comment]
https://github.com/drtshock/Essentials/issues/1301
my bad didn't see this

**Comment by SupaHam** [comment]
This has been fixed in 12930cf. You can grab the fix from [build 493](https://ci.drtshock.net/job/EssentialsX/) on the CI server.
