### ISSUE TITLE
Can't unban anyone

### ISSUE THREAD

**Issue by Metisuneatn** [EssentialsX/Essentials#1347]
1.12 - lastest dev build

Unable to /unban anyone even as OP. IT just says Error:null and there are 0 errors in the console.

**Comment by iSkeptical** [comment]
I don't have this issue.

**Comment by Metisuneatn** [comment]
I guess the person I was trying to unban maybe their data was old, not sure.

**Comment by SupaHam** [comment]
Type `/ess debug` and try to unban again. That will show an error for sure.

**Comment by Metisuneatn** [comment]
My admin removed their name in the actual file and I don't think I can recreate it :/

**Comment by SupaHam** [comment]
Well, I'll have to close this. Please comment back here if you are able to reproduce the issue.
