### ISSUE TITLE
Time set per world

### ISSUE THREAD

**Issue by Platinteufel** [EssentialsX/Essentials#135]
I have several worlds on my spigot 1.8.8 server and want to allow my users to change the time in only one world. So i gave them essentials.time & essentials.time.set permissions in this world. But now they are also able to change the time in my other worlds with /day day [world] or /day day all. How can I prevent that?

**Comment by drtshock** [comment]
Use per world permissions with your permissions plugin.

**Comment by Platinteufel** [comment]
Well .. that doesn't work. They'll get essentials.time & essentials.time.set only in 1 world, but can use there /day day all to change the time in all worlds. Test it.

**Comment by Platinteufel** [comment]
Please reopen this ticket. You can't prevent users from changing the time in all worlds typing
/day day all
with per-world-pemissions. Test it, please.
