### ISSUE TITLE
Essentials Blocking Other Prefix Plugins

### ISSUE THREAD

**Issue by ZardosCraft** [EssentialsX/Essentials#1351]
Hello,
So my essentials plugin is blocking any plugin where it gives me and my players prefixes, for example, I tried Power ranks and much more and made my prefix [Owner] and it won't show but as soon as I disable essentials its works I really need prefixes but also need essentials.....PLEASE HELP

**Comment by NJDaeger** [comment]
you need to use vault

**Comment by ZardosCraft** [comment]
I don't get what your saying

**Comment by mdcfe** [comment]
Install Vault - Essentials prefixes won't work without it.

**Comment by SupaHam** [comment]
You can download Vault from [here](https://dev.bukkit.org/projects/vault).
