### ISSUE TITLE
/seen and tab

### ISSUE THREAD

**Issue by Castiella** [EssentialsX/Essentials#1353]
you can no longer double tap tab to auto fill a name with /seen

**Comment by mdcfe** [comment]
What version of EssentialsX are you running? This was fixed in a recent update.

**Comment by Castiella** [comment]
I thought i was using the current version. My apologies. Its essentialsx.2.0.1. Could you possibly link me the correct version if i am outdated please? for some reason the link on bukkit says its insecure and it won't let me access it.

**Comment by Castiella** [comment]
Okay, I just checked jenkins and apparently I'm using the correct version.

Another bug added as well - when we use /manuadd to change a player group, it doesnt update until the server restarts.

**Comment by Castiella** [comment]
Closing, updated to the new one on jenkins and it resolved the issue.

Sorry!

**Comment by mdcfe** [comment]
`/manuadd` looks like a GroupManager command. GroupManager is not a part of EssentialsX, and EssX does not support it (if you're using a fork, contact them about the issue).

**Comment by smmmadden** [comment]
GroupManager is also no longer supported.  There is a new GroupManagerX plugin which could be used with minimal changes.  Or other permission based plugins like PermissionsEx (PEX).  You can find details for each [here](https://goo.gl/7UqETR) for whatever server version you are using.
