### ISSUE TITLE
Inheritance not working

### ISSUE THREAD

**Issue by JBaadargo** [EssentialsX/Essentials#1355]
I've just updated my server to 1.12, and I'm having problems with PermissionsEx inheritance for essentials. It only appears to be for essentials though, everything else seems fine. For example, one of my Trusted members can use /fly, but I (owner rank) can not, even though it appears I should be able to. I'm unsure exactly if it's pex or essentials that is the issue, so I'm posting this on both pages in hopes of an answer. Below is my permissions.

https://pastebin.com/7SWQXjqx

**Comment by JBaadargo** [comment]
Found the problem, closed.

**Comment by SupaHam** [comment]
Can you post your fix here so others can see it?

**Comment by JBaadargo** [comment]
I had "Mod" inheriting from a "TMod" rank that I removed when updating permissions, and forgot to fix it. Unfortunately you skip past things like that when you're updating things at 1AM.
