### ISSUE TITLE
Essentials should not override WorldEdit commands.

### ISSUE THREAD

**Issue by Pangamma** [EssentialsX/Essentials#1357]
I was trying to activate //sp recur 20 today, and I saw a message saying Essentials was locking up the /sp command. Well that's fine. I'm fine with Essentials locking up /sp. But //sp? That's a bit too far. Many users who are lazy, would benefit from Essentials being a bit less aggressive with the command alias claiming. 

Is there a config to turn off some aliases? There may already be a sln, I just haven't found a practical one yet. Editing the plugin.yml file every update is a bit annoying.

**Comment by SupaHam** [comment]
I can assure you EssentialsX is not interfering with `//sp`. We don't have any commands called that. This is done by another plugin, maybe WorldEdit?
