### ISSUE TITLE
Essentials Wont Allow any Prefix plugin

### ISSUE THREAD

**Issue by ZardosCraft** [EssentialsX/Essentials#1358]
hi, I have tried many different plugins that set prefixes but essentials is blocking them ALL and yes i tried installing Vault...please help

**Comment by mdcfe** [comment]
* What version of EssentialsX are you running? `/essentials`
* What server software are you running? `/version`
* Do you have EssentialsXChat installed? If so, are there any "version mismatch" errors in the log?
* What prefix plugins have you tried?
* Can you paste your EssentialsX config on [Hastebin](https://hastebin.com) or [Gist](https://gist.github.com), as well as a startup log from your server?

Apologies for the long list, but as much of this info as possible will help.

**Comment by ZardosCraft** [comment]
@md678685
*I'm Running 1.11 latest 
*Im Running CraftBukkit 
*No I dont
*I tried Owner,Admin,Builder,etc
*https://hastebin.com/oyupafuwaj.coffeescript
And Btw Im Not Using EssentialsX im using ServerEssentials And Just Regular Essentials

**Comment by mdcfe** [comment]
This is not the support for ServerEssentials nor regular Essentials. Regular Essentials is not supported any more, and ServerEssentials is a different plugin ([this one?](https://dev.bukkit.org/projects/server-essentials-plugin)).

**Comment by ZardosCraft** [comment]
@md678685 oh ok sorry
