### ISSUE TITLE
PERMISSIONS MANAGER IS NOT ACCESSIBLE. IS PERMISSIONSEX ENABLED

### ISSUE THREAD

**Issue by ZardosCraft** [EssentialsX/Essentials#1359]
I Just Installed PermissionEx and it says "PERMISSIONS MANAGER IS NOT ACCESSIBLE. IS PERMISSIONSEX ENABLED" And I cant type "/help" or Anything...PLEASE HELP

**Comment by mdcfe** [comment]
This is not PermissionsEx support.

**Comment by ZardosCraft** [comment]
@md678685 oops sorry
