### ISSUE TITLE
Essentials [Buy] Signs

### ISSUE THREAD

**Issue by EvModder** [EssentialsX/Essentials#1360]
Essentials [Buy] Signs don't work with data values for some items anymore, a fix or alternative should be provided.
![2017-07-01_19 46 14](https://user-images.githubusercontent.com/5511002/27766469-5dbe083a-5e96-11e7-992c-7e5eeec9e862.png)

**Comment by SupaHam** [comment]
Players cant hold spawners with mob data. You'll have to figure out another way of fixing this. Like sell a spawnegg with the spawner, then they right click the spawnegg on the spawner and it'll change type.
