### ISSUE TITLE
/warps list accessible by all players regardless of permissions

### ISSUE THREAD

**Issue by Castiella** [EssentialsX/Essentials#1361]
Players can double tap tab with /warp 
This will let them cycle through the warp list even though they do not have the permission node to view all warps.

**Comment by FlashLight34** [comment]
+1 and i think that need to add permission check (a new permission like essentials.tabcomp)

**Comment by mdcfe** [comment]
I think tab completion should check the normal list perms rather than having its own set of perms, as this could cause confusion and could create even longer permission lists.

**Comment by FlashLight34** [comment]
and its possible to add the uuid of the owner of all created warps (not the already created but the next :P)

**Comment by mdcfe** [comment]
A check for the `essentials.warp.list` permission was added in 301a3a72dfb18e0305b0c42afe6b90a4ed50e444. You can get the build 498 from the [build server](https://ci.drtshock.net/job/EssentialsX/498/).

For storing warps with the creator's UUID, please create a separate issue.

**Comment by FlashLight34** [comment]
thx sir :P
