### ISSUE TITLE
Essentials "addons"

### ISSUE THREAD

**Issue by Smokinlow** [EssentialsX/Essentials#1363]
EssentialsX version (`/essentials`): EssentialsX 2.0.1-b488

Server software (`/version`): 1.8

EssentialsX config (if applicable): default

**Comment by SupaHam** [comment]
And the issue is?

Do you want to download Essentials plugins? https://ci.drtshock.net/job/EssentialsX/

**Comment by Smokinlow** [comment]
Yes, thank you, didnt know there was a X version of them aswell 👍
