### ISSUE TITLE
Suggestion: Add a tag to make items of kits irreparable

### ISSUE THREAD

**Issue by jsuarezl** [EssentialsX/Essentials#1365]
Hi, I was working in a factions server with a friends and we want to make some items of kits irreparable so the players can't repair it, I don't know if is some tag yet to make this.

**Comment by YellowZaki** [comment]
Just add unbreakable:true.

**Comment by mdcfe** [comment]
Irreparable with `/repair`, an anvil or both?

**Comment by Shivelight** [comment]
I like this suggestion, I'll go with both

**Comment by jsuarezl** [comment]
Irreparable with both, or something like the nbt tag RepairCost that allows to set a custom repair cost for an item

**Comment by SupaHam** [comment]
Duplicate of #377

This has been fixed in 203d656. You can grab the fix from [build 516](https://ci.drtshock.net/job/EssentialsX/) on the CI server.
