### ISSUE TITLE
Wird info/error EssentialsX config.

### ISSUE THREAD

**Issue by 23Chromosomes** [EssentialsX/Essentials#1367]
So I installed LordPermissions, because there is no Groupmanager for essentialsX on the jenkins page...
After I start the server I get this message:

05.07 11:31:09 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot112.jar:git-Spigot-7d78b81-a867313]
05.07 11:31:09 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot112.jar:git-Spigot-7d78b81-a867313]
05.07 11:31:09 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot112.jar:git-Spigot-7d78b81-a867313]
05.07 11:31:09 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot112.jar:git-Spigot-7d78b81-a867313]
05.07 11:31:09 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot112.jar:git-Spigot-7d78b81-a867313]
05.07 11:31:09 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325) [spigot112.jar:git-Spigot-7d78b81-a867313]
05.07 11:31:09 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375) [spigot112.jar:git-Spigot-7d78b81-a867313]
05.07 11:31:09 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot112.jar:git-Spigot-7d78b81-a867313]
05.07 11:31:09 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot112.jar:git-Spigot-7d78b81-a867313]
05.07 11:31:09 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) [spigot112.jar:git-Spigot-7d78b81-a867313]
05.07 11:31:09 [Server] INFO at me.Gomze.LordPermissions.Main.LordPermissions.onEnable(LordPermissions.java:17) [LordPermissionsEN.jar:?]
05.07 11:31:09 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:142) [spigot112.jar:git-Spigot-7d78b81-a867313]
05.07 11:31:09 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:174) [spigot112.jar:git-Spigot-7d78b81-a867313]
05.07 11:31:09 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:239) [spigot112.jar:git-Spigot-7d78b81-a867313]
05.07 11:31:09 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184) ~[spigot112.jar:git-Spigot-7d78b81-a867313]
05.07 11:31:09 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:58) ~[spigot112.jar:git-Spigot-7d78b81-a867313]
05.07 11:31:09 [Server] INFO org.bukkit.configuration.InvalidConfigurationException: Top level is not a Map.
05.07 11:31:09 [Server] ERROR Cannot load configuration from stream

Is this normal/bad that I get this and how to fix this?
EssentialsX 2.0.1-b496
server is Spigot 1.11.2

Config:
https://pastebin.com/qBQRvL7u

**Comment by NJDaeger** [comment]
I'm fairly certain it's LordPermissions that's causing this issue. Can you please show the configurations of LordPermissions?

**Comment by 23Chromosomes** [comment]
Lordpermissions config is empty I think thats normal?

Globalgroups.yml
https://gist.github.com/Hendrik379/f7fa24a2b8babbce9e7d6c0b43f93ef6
Player.yml
https://gist.github.com/Hendrik379/3172a083c53118ebf1a8cd24a26a72e2

**Comment by mdcfe** [comment]
Could you use [Gist](https://gist.github.com) to paste your config a rather
than embedding them here? It makes it more difficult for us to follow when
long configs are pasted here.

**Comment by 23Chromosomes** [comment]
Sorry, is this good?
(See edited comment)

**Comment by mdcfe** [comment]
It looks like something is up with your permissions plugin's config, but this is not LordPermissions support.

**Comment by 23Chromosomes** [comment]
Alright thx for the help.
I installed PermissionsEx and everything is working fine now!
I have one last question.
How do I change or disable the arrow brackets like this < PlayerName > in my essentials config I cant find where to change it.
Edit: Nvm I found it!
Thx for helping me out!
