### ISSUE TITLE
Kit {player} placeholder inconsistent

### ISSUE THREAD

**Issue by Kakifrucht** [EssentialsX/Essentials#137]
While for normal items that are given, you have to use the placeholder {PLAYER} capitalized, using the same placeholder in commands within the kit will result your name with an appended r at the end of the name. You have to use {player} to make it work. This is an unnecessary inconsistency.

**Comment by drtshock** [comment]
When I wrote the code for the commands in kit, I didn't realize that ess normally uses all uppercase for that. I don't want to break what I have now, but I could add {PLAYER} as an option on top of {player} if you think that would be a wise choice, seems odd though.

**Comment by mdcfe** [comment]
This just requires adding another `.replace`:
https://github.com/EssentialsX/Essentials/blob/3b41bb47b6a3315af059168496a84f48099c5159/Essentials/src/com/earth2me/essentials/Kit.java#L166
