### ISSUE TITLE
Add XMPP (and other) documentation?

### ISSUE THREAD

**Issue by Omio** [EssentialsX/Essentials#1370]
I intend to add XMPP functionality to a server, but I don't know if I need to be running a separate server, and need to configure EssentialsXMPP as a client, or if EssentialsXMPP runs a XMPP server, and I need to configure accordingly. The documentation I've found has been rather lacking on the non-core Essentials modules. Can we make a documentation improvement here? If not (and I can be filled in on what's going on with commands/perms), I'm willing to help contribute.

EDIT: After looking at the config, it looks like the XMPP libraries are connecting as a client.

**Comment by mdcfe** [comment]
EssentialsXMPP is documented at the [old Essentials wiki](http://wiki.mc-ess.net/wiki/XMPP).

**Comment by mdcfe** [comment]
I'm adding `enhancement` here too, in case we decide to migrate old Essentials documentation over to our wiki at some point.

**Comment by mdcfe** [comment]
The docs progress is now tracked on the [Docs project board](https://github.com/orgs/EssentialsX/projects/2).

**Comment by pop4959** [comment]
Good to know, I just closed the issue since the question had been answered. Also I felt like this issue wasn't really being tracked properly anymore since you kind of re-purposed it. Probably warrants having its own issue rather than putting it in a comment here.
