### ISSUE TITLE
selling Spawn Egg

### ISSUE THREAD

**Issue by billy78987** [EssentialsX/Essentials#1371]
i got latest update on essentials and on spigot and i use boss shop pro but what is going on is that when i got to put spawn eggs up to sell some work but some like parrot llama newer mobs give white egg that says spawn and i dont know why if you have any idea that be great!

EssentialsX version (`/essentials`): 

Server software (`/version`): 

EssentialsX config (if applicable):

**Comment by mdcfe** [comment]
This seems to be a problem with your shop plugin rather than EssentialsX.
