### ISSUE TITLE
Add command support for kits

### ISSUE THREAD

**Issue by Twonox** [EssentialsX/Essentials#1372]
Hi,

I prupose a new feature for kit system of EssentialsX.
This is to add a **command support** which allow us to add an executable command by server when a player type `/kit newbies` for example.

**Comment by mdcfe** [comment]
I feel like this might be outside the scope of Essentials' kits system, which has always provuded item kits, but I'm curious as to what others think about this.

**Comment by SupaHam** [comment]
You can already do this, just start the line with / to let it be known as a command.

From the wiki: "Allow commands in kits and use {player} to replace with player's name."

**Comment by mdcfe** [comment]
@SupaHam Wasn't aware that this was already implemented, oops
