### ISSUE TITLE
Non-case sensitive kit names

### ISSUE THREAD

**Issue by baticag** [EssentialsX/Essentials#1374]
Can you please make kit names not case sensitive, because it's better looking on /kits and other places?

**Comment by mdcfe** [comment]
~~If this changed, it could potentially cause some servers problems if they rely on case-sensitive kit names.~~ See SupaHam's comment below.

**Comment by SupaHam** [comment]
Technically, this is doable without harm. EssentialsX doesn't rely on the kits in the config being lowercase, it just lowercases it in runtime.

The change would involve maintaining original casing in some form, e.g. new Map or modify existing Map container, and use it when displaying kit names.

**Comment by JRoy** [comment]
https://github.com/EssentialsX/Essentials/commit/cd43355d4c18e12f743092c31a765aaa8451cb1b added this a while back

**Comment by JRoy** [comment]
https://github.com/EssentialsX/Essentials/commit/cd43355d4c18e12f743092c31a765aaa8451cb1b did this
