### ISSUE TITLE
Option for data saving

### ISSUE THREAD

**Issue by Twonox** [EssentialsX/Essentials#1377]
Hi,

I use essentials in my lobby server, but in this server, me and probably other server owners, we don't need essentials players data.
So, I would like an option from config file to disable data saving.

Is it possible ?

Thanks.

**Comment by mdcfe** [comment]
This isn't currently possible. You can manually purge EssX's player data if needed though.

**Comment by Poslovitch** [comment]
@md678685 @SupaHam Can you assign this suggestion to me?
I'll push a PR during the week-end, 'cause I need this feature too :)

**Comment by pop4959** [comment]
@Poslovitch Feel free to make a PR if you haven't already (I'm not really sure since this issue has been here for a couple years).

Closing but leaving as open to PR in case someone feels like implementing it.

**Comment by Poslovitch** [comment]
Hi. I don't remember having submitted a PR for that. But I don't think I'll be able to work on it. I'm quite busy with school and BentoBox already... Sorry!

**Comment by pop4959** [comment]
Don't feel like you have to do it, I was just cleaning through old issues. To be fair, I don't really see how helpful this is considering how small the user data files are. It can effectively be ignored. That's basically why I closed the issue. I was just curious if you had ever followed up on it.

**Comment by Twonox** [comment]
@pop4959 Yes, the user data files are small, this is why it's not the reason of my request.
I requested that because the user files are useless in a lobby and when there is a lot of user file (especially in a lobby server) the saving/deleting of all them became very long with a FTP.

I'm no longer a server owner, so currently this implementation is not important for me. But I think that can be interesting for other owners.
