### ISSUE TITLE
Fly mode issues

### ISSUE THREAD

**Issue by PhanaticD** [EssentialsX/Essentials#138]
when you are flying then reconnect, you fall to the ground

steps to reproduce the issue
1. do /fly
2. fly in the air
3. logout
4. login

you will now fall to the ground instead of being suspended in the air like when you logged out. 

This was not an issue prior to switching to EssentialsX

**Comment by EvilOlaf** [comment]
I am still using essentials from spigot and recently had the problem that a player with fly got disconnected and fall to the ground at reconnect. 
So those problem might not be introduced in essentialsX. 

Would be better if that would be solved some way though.

**Comment by BiGUNMAN** [comment]
Do you have
Permissions:
essentials.fly
essentials.fly.safelogin (Is what you're looking for).

**Comment by PhanaticD** [comment]
yes those are set

**Comment by PhanaticD** [comment]
boomp

**Comment by SupaHam** [comment]
The underlying, untouched issue only sets the `essentials.fly.safelogin` user flying if they're mid air when joining the game.

**Comment by Terrobility** [comment]
I made this: https://github.com/HunterGPlays/Essentials/commit/902e1e84cda2386e304915660c44d62a2c53d7e9
This should add a permission node to make players fly upon login, regardless of whether they should be flying or not. The only difference to `essentials.fly.safelogin` is that it doesn't check LocationUtil.shouldFly. This isn't the best workaround but it would suffice.

**Comment by PhanaticD** [comment]
according to players on my server this actually doesnt happen anymore, so it must have been fixed somewhere along the line
