### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by mdcfe** [EssentialsX/Essentials#1380]
There are quite a few missing translations as found by [this script](https://gist.github.com/md678685/a5e435a79d3431040d91ea9d4b84026d), so I thought I would list them here to keep track of them - and eventually people might help to translate the missing lines. "Extra keys" refers to keys that are present in the translated file but not in messages.properties.

# Missing translations
<details>
<summary>Click to expand</summary>

### Missing keys
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

### Missing keys
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

### Missing keys
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

### Missing keys
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* timeSetWorldPermission
* msgIgnore
* minimumPayAmount
### Extra keys
* nickNamesOnlyColorChanges

### Missing keys
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

### Missing keys
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

### Missing keys
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

### Missing keys
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* timeSetWorldPermission
* msgIgnore
* minimumPayAmount

### Missing keys
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

### Missing keys
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

### Missing keys
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

### Missing keys
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

### Missing keys
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

### Missing keys
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

### Missing keys
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* timeSetWorldPermission
* userAFKWithMessage
* userIsAwayWithMessage
* kitItem
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount
### Extra keys
* kitItems

### Missing keys
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* pWeatherInvalidAlias
* requestAccepted
* requestAcceptedFrom
* sellBulkPermission
* sellHandPermission
* timeSetWorldPermission
* userAFKWithMessage
* userIsAwayWithMessage
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount
### Extra keys
* requestaccepted
* requestacceptedFrom

### Missing keys
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

### Missing keys
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

### Missing keys
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

### Missing keys
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

### Missing keys
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

### Missing keys
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

### Missing keys
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount
</details>

**Comment by Poslovitch** [comment]
I'll do it for the fr locale.

**Comment by mdcfe** [comment]
I've updated the script to output the total number of missing and extra keys (see the Gist above for changes). I've updated the sample output accordingly:

# Missing translations
<details>
<summary>Click to expand</summary>

## messages_cs.properties
### Missing keys (14)
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* socialSpyMutedPrefix
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

## messages_da.properties
### Missing keys (14)
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* socialSpyMutedPrefix
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

## messages_de.properties
### Missing keys (11)
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* socialSpyMutedPrefix
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

## messages_en.properties
### Missing keys (10)
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* socialSpyMutedPrefix
* timeSetWorldPermission
* msgIgnore
* minimumPayAmount
### Extra keys (1)
* nickNamesOnlyColorChanges

## messages_es.properties
### Missing keys (14)
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* socialSpyMutedPrefix
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

## messages_et.properties
### Missing keys (14)
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* socialSpyMutedPrefix
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

## messages_fi.properties
### Missing keys (14)
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* socialSpyMutedPrefix
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

## messages_fr.properties
### Missing keys (1)
* socialSpyMutedPrefix

## messages_hu.properties
### Missing keys (14)
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* socialSpyMutedPrefix
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

## messages_it.properties
### Missing keys (1)
* socialSpyMutedPrefix

## messages_ko.properties
### Missing keys (14)
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* socialSpyMutedPrefix
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

## messages_lt.properties
### Missing keys (14)
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* socialSpyMutedPrefix
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

## messages_nl.properties
### Missing keys (14)
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* socialSpyMutedPrefix
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

## messages_pl.properties
### Missing keys (14)
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* socialSpyMutedPrefix
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

## messages_pt.properties
### Missing keys (17)
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* socialSpyMutedPrefix
* timeSetWorldPermission
* userAFKWithMessage
* userIsAwayWithMessage
* kitItem
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount
### Extra keys (1)
* kitItems

## messages_pt_BR.properties
### Missing keys (19)
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* pWeatherInvalidAlias
* requestAccepted
* requestAcceptedFrom
* sellBulkPermission
* sellHandPermission
* socialSpyMutedPrefix
* timeSetWorldPermission
* userAFKWithMessage
* userIsAwayWithMessage
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount
### Extra keys (2)
* requestaccepted
* requestacceptedFrom

## messages_ro.properties
### Missing keys (14)
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* socialSpyMutedPrefix
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

## messages_ru.properties
### Missing keys (14)
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* socialSpyMutedPrefix
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

## messages_sv.properties
### Missing keys (14)
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* socialSpyMutedPrefix
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

## messages_tr.properties
### Missing keys (14)
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* socialSpyMutedPrefix
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

## messages_zh.properties
### Missing keys (1)
* socialSpyMutedPrefix

## messages_zh_HK.properties
### Missing keys (14)
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* socialSpyMutedPrefix
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

## messages_zh_TW.properties
### Missing keys (14)
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* socialSpyMutedPrefix
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount
</details>
