### ISSUE TITLE
Probleme with command /recipes

### ISSUE THREAD

**Issue by cercus** [EssentialsX/Essentials#1381]
When I use the command /recipe <item> or /method <item>, the crafting table doesn't show the recipe of item

EssentialsX version :  EssentialsX for spigot 1.11

Server software : CraftBukkit version git-Spigot-6f7aabf-c8ff651 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)

**Comment by mdcfe** [comment]
Can you give us the version from `/ess`?

**Comment by cercus** [comment]
When I do /ess  , it display " /<command> <reload/debug>"

**Comment by mdcfe** [comment]
Run the command in-game, not in the console (hence the `/`).

**Comment by cercus** [comment]
I ran this command in-game
I ran command /essversion and it display "This server is running Essentials TeamCity"
I download the version Essentials 2.0.1-b498 and the command /recipes run on
