### ISSUE TITLE
TAB complete restrictions conflicting with other plugins

### ISSUE THREAD

**Issue by NewBestX** [EssentialsX/Essentials#1384]
The tab-completion system implemented in the latest builds of EssentialsX restrict player's ability to complete a command if they do not have permission to use that command. However, I was testing a ban management plugin, and I ran into the issue that players can't tab-complete the name in the /ban command from that plugin because they do not have the Essentials /ban permission.
I was able to fix this by adding aliases in commands.yml:
```
  ban:
  - otherPlugin:ban $1-
```

Perhaps something you want to look into, or maybe others will find the info useful.
Have a nice day!

**Comment by Fonzee9** [comment]
Same problem

**Comment by mdcfe** [comment]
To ensure consistent behaviour with other plugins overriding commands, you should always alias them to the other plugin. [See here](https://github.com/EssentialsX/Essentials/wiki/Common-Issues#essentialsx-overrides-a-command-from-spigot-or-another-plugin) for more details.
