### ISSUE TITLE
Just updated to EssentialsX from SpigotEssentials and getting low tps.

### ISSUE THREAD

**Issue by pisaiah** [EssentialsX/Essentials#1386]
**EssentialsX version (`/essentials`)**:  buid 498.

**Server software (`/version`)**:  Paper version 1.12-1147

**EssentialsX config (if applicable)**: https://gist.github.com/IsaiahPatton/365646767e6182bfd563bf7ea495ef95

**Tps usage (from tps):**

- Spigot-Essentials: 19.98 tps (normal for server)
- EssentialsX: 3.5 tps (not normal)

**Plugins:**

![image](https://user-images.githubusercontent.com/16439221/28133927-6dd9122e-670f-11e7-8346-f2ae0acefc1b.png)

4 GB ram, 40 GB SSD Disk, 4 Core Processor.

I've switched back to Spigot-Essentials untill this is fixed.

**Comment by mdcfe** [comment]
You can use Spugot's timings report feature to try and determine the problem, but we don't have enough information to help solve this.
