### ISSUE TITLE
Ability to change Broadcast prefix [Request]

### ISSUE THREAD

**Issue by SiuanSong** [EssentialsX/Essentials#1388]
Hello, I would really like to be able to change the [Broadcast] prefix, but can't seem to find a setting for it anywhere.
Thank you!

**Comment by zRiaz** [comment]
You can change it with all other messages if you use the "messages.properties" file.

**Comment by mdcfe** [comment]
Copy `messages.properties` (or the relevant `messages_zz.properties` file for other languages) from the EssentialsX repo to the plugins/Essentials folder, and edit the strings as desired.

**Comment by SiuanSong** [comment]
Oh! Thank you! Is there a way to change how the social spy messages show?  I'd like them to be greyed out but I can only find an option to change the socialspy prefix

**Comment by mdcfe** [comment]
The "new" social spy system still doesn't allow this even though PR #1226 was proposed a while ago to allow this.
