### ISSUE TITLE
Teleport Safely Isn't Working

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1390]
EssentialsX version (`/essentials`): 2.0.1-b494

Server software (`/version`): Paper-1147 (MC 1.12)

EssentialsX config (if applicable): 

teleport-safety: true
force-disable-teleport-safety: false

I'm having some issues with teleportation on my server. When players teleport to a platform that is one block thick they often fall through it. Additionally, teleporting someone to me while floating in the air causes them to spawn where I am and fall to their death. In previous versions, they would spawn on the ground unless they also have fly mode or creative enabled.

**Comment by mdcfe** [comment]
Could you post your `paper.yml` on [Gist](https://gist.github.com)?

Edit: looks like this might be due to a change in vanilla/CB/Spigot, but I can't investigate at the minute so I'll have a look later.

**Comment by ghost** [comment]
@md678685 Good to hear I'm not going crazy and there is an actual issue. Is there anything I can do to help OR have you made any progress? I have people dying from falling beneath platforms they teleport to daily.

**Comment by mdcfe** [comment]
Since you're using Paper, could you post your `paper.yml` on [Gist](https://gist.github,com) just to see whether there is an issue with your server's configuration? I believe there are teleport-related options in Paper.

**Comment by SioWolf** [comment]
https://pastebin.com/n0Ve6c86

**Comment by ghost** [comment]
Closed, fairly certain this was caused by AAC's fly check.
