### ISSUE TITLE
Baltop

### ISSUE THREAD

**Issue by Weymouth87** [EssentialsX/Essentials#1391]
EssentialsX version (`/essentials`): 2.0.1-b473

Server software (`/version`): Minecraft 1.12

EssentialsX config (if applicable): https://hastebin.com/pihemobati.coffeescript

I am currently using your EssentialsX plugin within my server and have done for a long while now, however Ive recently noticed that /baltop doesn't seem to update regularly anymore, only upon reloading the plugin or restarting the server.

Any suggestions you have would be greatly appreciated.

Many Thanks
Weymouth87
Co-Owner of SnakeMC

**Comment by mdcfe** [comment]
Do individual players' balances change when you run `/balance`?

Are you ensuring you're waiting at least two minutes between running the command for the first time and a second time?

**Comment by Weymouth87** [comment]
Hello,

Yes, when running /balance they do update. We have left hours between
running the command and still see no change.

Regards,
Chelsea Weymouth
Co-Owner of SnakeMC

**Comment by mdcfe** [comment]
What effect does running `/baltop force` have? Do all the balances update? Does this change what is shown by the normal `/baltop` command?

**Comment by Weymouth87** [comment]
Hello,

Due to an unrelated issue, I had to generate new essentials files and
noticed that this issue corrected itself even after configuration. Thank
you for your time, I will be in contact if I run into the issue again.

Regards,
Chelsea Weymouth
Co-Owner of SnakeMC
