### ISSUE TITLE
custom-join/quit-message: "none" & custom-join-message: "" doesn't disable message

### ISSUE THREAD

**Issue by Twonox** [EssentialsX/Essentials#1393]
`custom-join-message: "none"` & `custom-quit-message: "none"` doesn't disable the join/leave message.
`custom-join-message: ""` display an empty message
`custom-quit-message: ""` disable the leave message.

_(during test, there was only essentials plugins)_

Server version: Spigot 1.8.8
Essentials version: latest build

**Comment by mdcfe** [comment]
Duplicate of #991. You can give players the `silentjoin` permission, or just leave the custom messages with a blank line.
