### ISSUE TITLE
Join/Quit messages randomly appear

### ISSUE THREAD

**Issue by BiGUNMAN** [EssentialsX/Essentials#140]
Config: http://pastebin.com/Gsk1XSBc
Console: No messages related to it.

All players have the silentjoin/quit messages, yet messages are randomly sent.

(Idea)
It seems it doesn't send join ones, but once anything within essentials is modified in the files (like a book.txt), or the plugin is reloaded. It starts sending them again, which is extremely annoying, and only a restart fixes the issue. 

Its always sends leave messages, but it doesn't send it on join, yet everything is setup properly. Its as if the essentials.silentquit permission doesn't work, yet I have it setup right beside silentjoin.

**Comment by xXBarchticXx** [comment]
^ "A simle restart fixes it"... What is the hassle with restarting your server? Not like your whole playerbase is gonna die if you turn your server off for 33.5 seconds.

**Comment by BiGUNMAN** [comment]
Not if you need to do it multiple times, and no. I figured it out, let me update the report.

**Comment by Agazed** [comment]
@xXBarchticXx That is not true, especially with large communities.

**Comment by xXBarchticXx** [comment]
Why not put it offline for maintenance. I mean yes it is a hassle but really not a BIG problem that drtshock needs to focus on right at this moment.

**Comment by BiGUNMAN** [comment]
I've already updated latest post with how it works, and a restart does not fix it.

**Comment by Cldfire** [comment]
Why don't you just disable join/leave messages...

**Comment by BiGUNMAN** [comment]
There is no actual "config" option for that. (Atleast that I know of..)

**Comment by Cldfire** [comment]
Just set the messages to ""

**Comment by BiGUNMAN** [comment]
That doesn't disable them. It instead sends an empty line of chat.

**Comment by vemacs** [comment]
Seems to be a problem with config reloading. In the meantime, use something like HideStream.

**Comment by BiGUNMAN** [comment]
@vemacs And the essentials.silentquit (it would seem, but okay).

**Comment by mdcfe** [comment]
Is this still an issue? I don't recall any subsequent reports of this.

**Comment by pop4959** [comment]
I agree with md, haven't seen anything pertaining to this lately. If anyone's having this problem, please open a new issue with more information so that we can test it more thoroughly.
