### ISSUE TITLE
Missing messages in messages_en.properies

### ISSUE THREAD

**Issue by HenrikEngen** [EssentialsX/Essentials#1400]
EssentialsX version (`/essentials`): 2.0.1-b483

Server software (`/version`): git-spigot-3fb9445-2b6c9f4 (MC: 1.11.2)

EssentialsX config (if applicable): 

I have a problem... There are some messages in EssentialsX that is not included in the messages_en.properties ... for example, the message for /tpacancel can't be found in that file so therefore, I cannot modify it...

Are there any solutions to this problem?

**Comment by LaxWasHere** [comment]
https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/messages_en.properties#L429-L430
Are these the ones you are looking for?

**Comment by SupaHam** [comment]
Or this https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/messages_en.properties#L459

**Comment by HenrikEngen** [comment]
I found out the problem.

**Problem:**
The messages_en.properties that was posted on the EssentialsX home page in spigot has not been updated with the latest messages and that was the file I downloaded.

**Solution:**
I just downloaded the latest messages file from https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/messages_en.properties

_Closed._
