### ISSUE TITLE
essentialsX chat

### ISSUE THREAD

**Issue by Someone-NEW** [EssentialsX/Essentials#1403]
Im noob with using github dont know using everything here so i write my suggestion here.
I dont know is this issue or is just need to be add some more feature into EssentiasChat
I have not bungee thats clear. I will use **Per World Chat** ok right i change **radius: 999999** but this is not the right solution ok this will work in some cases will not under that radius for example.
Tham other problem is when you have a survival and there are 3 worlds like Nether End and my survival world need to be connected with the same chat but its not EssentiasChat is not realy Helpfull about that.
So this is my suggestion to be add in that plugin more Usefull chat channels for all possible types?
But for some fast using that just launch a version that will be used this **option to connect this 3 worlds** you have custom selecte in config.yml in section chat
Thank you all for the best job you do in this plugin.

Server software spigot 1.12 

EssentialsX config chat section

Sorry for bad English xD

**Comment by mdcfe** [comment]
Could you separate suggestions into different issues?

Could you also clarify exactly what you're referring to with the "per-world chat" functionality that you want? As far as I can tell this is outside the scope of EssXChat.

**Comment by Someone-NEW** [comment]
Inside config for EssentiaslChat are nothing special, so in this case can be add some more feature like other chat plugins have but to avoid have to many plugins is a easy was to implement more feature in this plugin.
For example "Per World Chat" <-- i think this say all. So please make so that we have more configurable things in this section i can do separate CHAT but not at all, players can see /afk messages but i currently dont want disable some broadcasting messages only all personality messages.
Than make so we can make a group, for example my worlds:  world, SPAWN_nether, SPAWN_the_end have the same chat channel. Than my world: SPAWN have the their own chat channel in their own group section separate from all other worlds. Than world SkyWars can have for example the same separated channel etc. just like that. But i suggest to add posssible to use /global "message" to see all in all worlds with permissions. Than for admin, owners..  when have permissions for "spy chat channel- this mean cthey can see all messages from all worlds" they will automaticaly see all messages but they can do /spy on/off some spy thing i think is already there.
All above are just examples how can be look this cool plugin. All Configurable inside config.yml in section "CHAT" like now but now is there nothing so useful.
Thank you very much.

**Comment by smmmadden** [comment]
that may be out of scope for Essentials-Chat, but I can tell you what you're looking for exists in Factions and Residence plugins among others.  You can also private message someone with this plugin /msg name message and only that person sees it.  Not a chat channel as you describe, but does have some support for private messages.  Hope that helps.

**Comment by Someone-NEW** [comment]
WTF smmmadden Im here to suggest SOMETHING for essentials go away with factions etc. man i use residence too but WUT?
"Essentials-Chat" <<-- i think this say all.  Out of scope? Noo  whati s than "Essentials-OutOfScope" or whatever this is my suggestion and will be realy nice to implementes it i use all essentials plugins but when i dont find any good solution for all i muss thinking to replace a mmost of ESs plugins but idk..

**Comment by mdcfe** [comment]
Many servers either don't see the need for shared separated chats, or already have a separate plugin to handle this. Essentials is only intended to provide the "essential" features that many or most servers would use, and it seems unlikely that the majority of servers would use this feature.

By adding features that people won't use, this creates bloat in the plugin. In addition, adding these features requires a large amount of work and testing from people who work on EssentialsX for free in their spare time. If not many people are going to use a feature then it's not worth the amount of time spent working on the plugin to add it.

EssentialsX still provides a wealth of useful features for many servers, but if you have specific requirements then you shouldn't be relying on one plugin to satisfy all of them.

**Comment by smmmadden** [comment]
no need to be rude about it @Someone-NEW - was just suggesting what @md678685 just did in a nice way.  Many server owners rely on multiple plugins because each of them are small, performance driven and has exactly what players want.  Minecraft Plugins were designed to be layered on top of each other and extend the capability of MC at the same time offering tailoring to ones needs more easily.  

FWIW - all the servers I own/manage, each of them have 40-50 plugins to do exactly what we need without needing to bloat any one plugin or have any TPS drops b/c of it.  That's the advantage of mixing plugins. :-)

**Comment by Someone-NEW** [comment]
Im just suggest to implement something look up in config what is from Chat sooo small thing nothing realy usefull, Only solution is to replace with other plugins than. i have 61 plugins btw in that case i dont want have it more in one server. But i have only one lol.

**Comment by mdcfe** [comment]
Closing as this is out of scope, though others can reopen if desired.
