### ISSUE TITLE
spawn-on-join not working

### ISSUE THREAD

**Issue by partydragen** [EssentialsX/Essentials#1404]
Hey this is first time i use EssentialsX but "spawn-on-join: true" not work :/ spawn is set and work to use /spawn

But when i relog im not back to spawn :/

Using latest Build: 499 on a 1.8.8 server
There is no errors in console

**Comment by mdcfe** [comment]
Are you opped or do you have full permissions? There is a spawn-on-join bypass permission that you might have accidentally been granted.

**Comment by partydragen** [comment]
Ah yea i had bypass xD
