### ISSUE TITLE
First  Join

### ISSUE THREAD

**Issue by Someone-NEW** [EssentialsX/Essentials#1405]
Here i have another suggestion i hope you can add in section **"First join"** inside confi.yml for example they give a reward or Start kit that is selected 

    # Do we want to give users anything on first join? Set to '' to disable
    # This kit will be given regardless of cost, and permissions.
    #kit: ''
    kit: Start

but this is global and player have this on spawn world and this world for example have separate inventory from all other world and this world have some feature like HUB so in this case i hope you can add some more things there. Need to be possible in wich world can player give/take in their inventory "start kit" not in my SPAWN world currentlly but in Survival world for example called : world for first time join when they go in this world. This is very usual for server like mine i dont have Bunge all is based on per word system.
So realy thank you for all good job here ;)

**Comment by mdcfe** [comment]
This also seems to be outside the scope of EssentialsX - this could most likely be achieved with a plugin such as FirstJoinPlus.

**Comment by Someone-NEW** [comment]
but this option is already inside this plugin Why to have too many plugins? Why not to implement something usefull there? to avoid with too many plugins i suggest for something better here i thinking to replace all this plugins idk i hope will be this ess better ;)

**Comment by mdcfe** [comment]
Essentials already combines the features that would otherwise be provided by lots of separate plugins, and many server owners don't want hundreds more features that they'll never use on their servers. Adding more features, especially when other plugins already have these features, will only make this bloat worse for many people and can cause confusion as it can become harder to distinguish between similar but different features.

**Comment by Someone-NEW** [comment]
Sorry Essentials have not this what i say and what is needed only solution is to replace with other plugins than. What i say is just suggestion i know that is alot of work but but what will be plugin without any suggestion? hmm ok no one i think will do that, take your time.

**Comment by mdcfe** [comment]
I don't think we're going to be adding any multiworld-specific features any time soon.
