### ISSUE TITLE
[Idea] Redo /give Command

### ISSUE THREAD

**Issue by Techno3600** [EssentialsX/Essentials#1407]
Hello,

I've got a new idea with the current /give command:
With right now I cannot do something like `/give Techno3600 diamond_chestplate 1 prot:100`. You can only do `/give Techno3600 diamond_chestplate 1 prot:5`. Can there be an option where you are able to bypass the max amount a certain enchantment limit?

Thanks
Techno3600

**Comment by Kakifrucht** [comment]
In your config.yml, set ``unsafe-enchantments`` to ``true``.

**Comment by Techno3600** [comment]
Thanks
EssentialsX thinks of EVERYTHING!
