### ISSUE TITLE
Blocked items list not working.

### ISSUE THREAD

**Issue by Castiella** [EssentialsX/Essentials#1408]
I have always had enderpearls blocked for the default rank players on my server.
It gives them a notification that tells them they can not use the item.

However, since updating, (to the new dev build) it alerts them - saying they cant use it until the higher rank.... but they still can use the item.

haven't changed the config or anything

**Comment by mdcfe** [comment]
Do you know what build you were using before you updated?

**Comment by SupaHam** [comment]
Also blocked using what exactly? AntiBuild?

**Comment by Castiella** [comment]
Fixed issue, it was config related - sorry.
