### ISSUE TITLE
Changing social spy back to grey (&7)

### ISSUE THREAD

**Issue by Castiella** [EssentialsX/Essentials#1409]
On the official essentials build, social spy messages were grey, not white - like this

socialSpy=\u00a76SocialSpy for \u00a7c{0}\u00a76\: \u00a7c{1}
socialSpyFormat=\u00a76[\u00a7c{0}\u00a76 -> \u00a7c{1}\u00a76] \u00a77{2}
socialSpyPrefix=\u00a7f[\u00a76SS\u00a7f] \u00a7r

It's really annoying having to ask my dev to re-do the colours in the jar file every time theres a new build - is there anyway you can rectify this? the white is so bright and annoying. Not sure if others care about this too.

**Comment by mdcfe** [comment]
Copy the relevant `messages_zz.properties` to plugins/Essentials and edit that. Don't edit the messages in the jar.

If you want to change the default colour of socialspy for PMs, this isn't supported yet.

**Comment by mibby** [comment]
https://github.com/drtshock/Essentials/issues/788

> If you want to change the default colour of socialspy for PMs, this isn't supported yet.

Still waiting on that. ^^ Impossible to use and keep socialspy enabled with 100+ people online since it blends in with normal chat.

**Comment by triagonal** [comment]
The ability to edit socialspy's PM format was added in a8d9139 / #1460.
