### ISSUE TITLE
/msgtoggle resets on logout

### ISSUE THREAD

**Issue by Mikgreg** [EssentialsX/Essentials#141]
Not sure if intended or not, but when you log out /msgtoggle also resets.
Would it be too much of a hassle for Essentials to remember its status like /tptoggle does?

Using version: 2.0.1-b184

**Comment by denizaygundev** [comment]
I definitely do think /msgtoggle should act more like /tptoggle, it's extremely annoying that it acts as a /ignoreall rather than an actual message receive toggle, users have no clue whether you're receiving their mail or not, this is a huge flaw in my opinion.

**Comment by drtshock** [comment]
This is intended.

**Comment by pop4959** [comment]
The way I see it this command has a use for temporarily disabling all messages, but if you want to disable receiving all chat you can already do this in the client. Therefore there isn't really much of a need for this. `/ignore` also exists if someone is getting on your nerves.

**Comment by Mikgreg** [comment]
Thanks for the timely response :)

**Comment by pop4959** [comment]
Haha, no problem! We do try to respond in under 5 years. 😉

**Comment by denizaygundev** [comment]
Wow haha, half-a-decade is quite something and a lot of changes since then, not running a minecraft server anymore (miss it a lot) but great to see Essentials is still going!
