### ISSUE TITLE
Accessing the enderchest of offline players

### ISSUE THREAD

**Issue by zRiaz** [EssentialsX/Essentials#1410]
title explains it all pretty much, let admins access others enderchests even though they are not online.

**Comment by SupaHam** [comment]
I don't believe there's an easy way to make this happen currently, the ability to access a player's enderchest is made possible by the owner being online.

**Comment by Poslovitch** [comment]
This would require to save ender chests in files.

**Comment by zRiaz** [comment]
Wouldn't it be possible to save the enderchests in the playerdata files for Essentials though?

**Comment by Poslovitch** [comment]
Sure, this is possible. However, this is a huge amount of data there. ItemStacks, ItemMetas, nbts...

**Comment by Antivalent** [comment]
Shouldn't it be saved in your main world's "playerdata" folder already? But I don't know how accessible those files are. Anyway, if you're considering /ec <player> for offline players, I'd love to see /invsee for offline players as well.

**Comment by Poslovitch** [comment]
Minecraft's player data is saved as .dat file, which are a bit hard to read.

**Comment by pop4959** [comment]
This probably won't be implemented any time soon, as there isn't a way to get the inventory of offline players through bukkit.
