### ISSUE TITLE
Glitching balances and infinite money

### ISSUE THREAD

**Issue by gameplayerhd** [EssentialsX/Essentials#1412]
EssentialsX version (`/essentials`):  2.01-b488

Server software (`/version`): latest spigot 1.8.8

By paying money less than 1 cent you can glitch the balances out.

Example: /pay name 1.000001

You balance is now glitched and you have infinite money.

Is there a way to limit the decimals?

**Comment by SupaHam** [comment]
Sorry, I'm unable to reproduce this in build 499. Can you please elaborate on "glitch the balances out"? Decimal points are not a glitch, they're a true representation of your balance.

There's a config option [`minimum-pay-amount`](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/config.yml#L623) which lets you limit the minimum range required to transfer money.
