### ISSUE TITLE
/blocks not working in 1.12

### ISSUE THREAD

**Issue by YepImRobbie** [EssentialsX/Essentials#1414]
http://i.imgur.com/7f3yp1v.png

EssentialsX version (`/essentials`): 
http://i.imgur.com/zAs8SNm.png
Server software (`/version`): 
http://i.imgur.com/NqDJAfv.png

**Comment by smmmadden** [comment]
I suggest you get the latest version of Essentials to go with 1.12.  Build 370 is quite old. :-)

**Comment by mdcfe** [comment]
Build 370 does not support 1.12. You can update from the [build server](https://ci.drtshock.net/job/EssentialsX/lastSuccessfulBuild).

**Comment by SupaHam** [comment]
This was fixed a while ago, see #1298.
