### ISSUE TITLE
Mute broadcast can't be translated

### ISSUE THREAD

**Issue by dartasen** [EssentialsX/Essentials#1415]
Just a small issue : all messages can be translated in messages_en.properties except the mute broadcast.
When we mute a player, others players see a broadcast message (with the permission "essentials.mute.notify") that can't be translated into this file.
<ADMIN> has muted player <PLAYER> for <TIME>

That's a bit annoying

**Comment by LaxWasHere** [comment]
https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/messages.properties#L256-L257

**Comment by dartasen** [comment]
@SupaHam @LaxWasHere Nop : 
muteNotify=\u00a7c{0} \u00a76a r\u00e9duit \u00a7c{1}\u00a76 au silence.
mutedPlayer=\u00a76Le joueur\u00a7c {0} \u00a76est maintenant muet.
