### ISSUE TITLE
Listener Warning "Server performance will be affected"

### ISSUE THREAD

**Issue by AdamTragedy** [EssentialsX/Essentials#1416]
28.07 08:15:46 [Server] WARN "Essentials v2.0.1-b499" has registered a listener for org.bukkit.event.player.PlayerPickupItemEvent on method "public void com.earth2me.essentials.EssentialsPlayerListener.onPlayerPickupItem(org.bukkit.event.player.PlayerPickupItemEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally, drtshock, vemacs, SupaHam, md678685].

EssentialsX version (`/essentials`): Essentials reloaded 2.0.1-b499

Server software (`/version`): version git-Spigot-596221b-2c5c611 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT

EssentialsX config (if applicable): N/A

**Comment by SlimeDog** [comment]
This is due to the latest Spigot 1.12 built (today). Many plugins warned.

**Comment by AdamTragedy** [comment]
Yeah I'm aware. Is this going to be fixed within essentials? Or is it something I don't need to worry about?

**Comment by SupaHam** [comment]
It will be fixed. It's not something you need to worry about.

**Comment by MrsKliper** [comment]
I received same error after updating spigot a bit ago. Glad it's nothing to worry about

**Comment by SupaHam** [comment]
Forgot to mention this has been fixed in 210494d. You can grab the fix from [build 501](https://ci.drtshock.net/job/EssentialsX/) on the CI server.
