### ISSUE TITLE
[Feature request] Confirm for doing /clear

### ISSUE THREAD

**Issue by Sikatsu** [EssentialsX/Essentials#1417]
Often players make a mistake with /clear causing their inventory to be reset.
Theres a confirm feature for /pay, but why not for /clear?

WARNING: This will clear your inventory, to confirm type /clear again

**Comment by mdcfe** [comment]
I feel like if we keep adding confirmation prompts, we might as well make them generic and configurable - for example having a list in the config that contains all the EssentialsX commands that will require confirmation.

**Comment by Sikatsu** [comment]
That would be a nice idea too. I think however a confirmation for /ci is quite important to have.

**Comment by Sikatsu** [comment]
@SupaHam Are you able to implement this perhaps?

**Comment by SupaHam** [comment]
No promises. I'm quite busy.

**Comment by SupaHam** [comment]
Thoughts on #1623?

**Comment by Sikatsu** [comment]
@SupaHam Looks nice. Hope you will merge it soon.

**Comment by Sikatsu** [comment]
@SupaHam 

The new toggle command seems to give an error: https://pastebin.com/E8kvM0GX
But the confirm works fine.

**Comment by mdcfe** [comment]
The class `Commandclearconfirmtoggle` should be `Commandclearinventoryconfirmtoggle` instead.

**Comment by SupaHam** [comment]
Should be fixed now. Sorry about that.

**Comment by Sikatsu** [comment]
@SupaHam Builds are failing..

**Comment by mdcfe** [comment]
This has been fixed - grab the latest build from [the build server](http://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/).
