### ISSUE TITLE
Mute broadcast can't be translated

### ISSUE THREAD

**Issue by dartasen** [EssentialsX/Essentials#1418]
I reopen an issue for #1415 : 
@SupaHam @LaxWasHere

muteNotify=\u00a7c{0} \u00a76a r\u00e9duit \u00a7c{1}\u00a76 au silence.
mutedPlayer=\u00a76Le joueur\u00a7c {0} \u00a76est maintenant muet.

But broadcast mute message isn't either translated in game.

**Comment by Antivalent** [comment]
I think muteNotifyFor might be the message you're looking for (the one where the mute duration is also broadcasted). As far as I'm concerned, it's missing in almost every translation. I had to manually add it to my german translation as well. It goes right in between muteNotify and mutedPlayer, if you want to keep the alphabetical order.

You can add it manually just like I did:
{0} is the player executing the mute
{1} is the player getting muted
{2} is the duration (using the time format generated by EssentialsX)

Example:
muteNotifyFor=\u00a7c{0} \u00a76has muted player \u00a7c{1} \u00a76for \u00a7c{2}\u00a76.

**Comment by mdcfe** [comment]
@dartasen Is the issue fixed?

**Comment by dartasen** [comment]
Yes thanks to @Antivalent.
