### ISSUE TITLE
Mob Spawners Issue Just turns back to default spawner when placed

### ISSUE THREAD

**Issue by quadbamber** [EssentialsX/Essentials#142]
When a player on my server placed the mob spawner it turned back to the default pig spawner

https://cloud.githubusercontent.com/assets/12215202/9184680/a4b3e8bc-3fae-11e5-96ef-82ca9f0580c0.png
Players can buy this as normal.

https://cloud.githubusercontent.com/assets/12215202/9184725/ec8497ea-3fae-11e5-934b-d4fbe80d16d6.png
But when it comes around to then placing it it just turns back to default spawner ID:52.

**Comment by vemacs** [comment]
Can't reproduce, this is an issue we intentionally fixed. Please pastebin server startup log and list plugins.

**Comment by Kakifrucht** [comment]
You need to give them the permissions essentials.spawnerconvert.mobtype

**Comment by denizaygundev** [comment]
Thanks Kakifrucht, that worked for me!
