### ISSUE TITLE
[Suggestion] Add an option to log chat messages from muted players

### ISSUE THREAD

**Issue by Antivalent** [EssentialsX/Essentials#1420]
I'd find it quite useful to see what muted players are actually trying to write, instead of just printing the "tried to speak, but is muted" message in console. We can already see their private messages, since those are logged as server commands and it would be nice to see all chat activity.

It would be even more useful if private and public messages from muted players appeared in socialspy, maybe with an extra mute prefix similar to the socialspy prefix in the messages.properties files.

**Comment by twieteddy** [comment]
Great idea. I've been already wondering if it is possible!

**Comment by Poslovitch** [comment]
Interesting :)
I'll have a look if I can do that

**Comment by mdcfe** [comment]
Implemented by #1430.
