### ISSUE TITLE
How do I Give Everyone Something?

### ISSUE THREAD

**Issue by Techno3600** [EssentialsX/Essentials#1422]
Hello,

I was wondering how I could give everyone on my server an item. Like `/give @a wooden_cloud 1` or something like that?

Thanks
Techno3600

**Comment by Antivalent** [comment]
As far as I can see, /msg does support a `/msg ** <text>` syntax which messages everybody on the server. However, /give doesn't seem to have this implemented currently.

You can still try one of those two options:

1. Insert `give @a paper 1` into a command block, it worked fine for me and targeted every player on the server while still using Essentials-/give
2. Use `/minecraft:give @a paper 1` instead, but bear in mind that this command uses a different syntax for defining item meta and that it requires different permissions

**Comment by Techno3600** [comment]
Maybe /give all should be a new thing implement in the next version?

**Comment by Antivalent** [comment]
`/give **` would be a more consistent and useful implementation, since "all" is a valid player name (looking at you, `/msg console`), but there are already ways around it. If you're having trouble with `/minecraft:give`, I can offer you my help.

**Comment by Techno3600** [comment]
But is it possible the developers of this plugin could add this feature?

**Comment by smmmadden** [comment]
probably the quiest way is to use the kit options where all playeres or a group

**Comment by Techno3600** [comment]
Okay, but I'm asking how I could pitch this idea to the developers.

**Comment by mdcfe** [comment]
It's been labelled `enhancement`, so the feature request has been noted.

**Comment by Techno3600** [comment]
Awesome!

**Comment by Techno3600** [comment]
Is this feature still able to be implemented?

**Comment by mdcfe** [comment]
As a workaround currently, you can use [`/execute`](https://minecraft.gamepedia.com/Commands/execute) to make use of `@a`. I believe the following should work:

```
/execute as <player> run essentials:give @a ...
```

**Comment by pop4959** [comment]
This can easily be done with the vanilla give command on its own, and if you want a more essentials-like format, using what md mentioned above. Someone could feel free to PR this, but I feel like anyone who needs to give everyone an item is already using vanilla commands for this.
