### ISSUE TITLE
Error EntityPickupItemEvent

### ISSUE THREAD

**Issue by Fiks75** [EssentialsX/Essentials#1424]
EssentialsX version (`/essentials`): Essentials v2.0.1-b501

Server software (`/version`): Java 8

EssentialsX config (if applicable): 

My server console error:
31.07 01:54:00 [Server] ERROR [Essentials] Plugin Essentials v2.0.1-b501 has failed to register events for class com.earth2me.essentials.EssentialsPlayerListener$PlayerListener1_12 because org/bukkit/event/entity/EntityPickupItemEvent does not exist.

How to get rid? This is serious?

**Comment by mdcfe** [comment]
Can you run `/version` from in-game or the console and post the output?

**Comment by Fiks75** [comment]
31.07 02:34:04 [Server] INFO This server is running CraftBukkit version git-Spigot-99c2a37-f078eed (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
31.07 02:34:04 [Server] INFO You are 8 version(s) behind

**Comment by mdcfe** [comment]
@SupaHam How long has `EntityPickupItemEvent` been part of Spigot?

@Fiks75 As far as I know you'll have to update to the absolute latest version of Spigot.

**Comment by SupaHam** [comment]
@md678685 days. PlayerPickupItemEvent will be removed in the future. Update your 1.12 Spigot server to fix issue.

See #1416
