### ISSUE TITLE
Clear Inventory

### ISSUE THREAD

**Issue by CryptoMorin** [EssentialsX/Essentials#1426]
Add support for clearing armor slot + Off Hand slot using /clearinventory

**Comment by ghost** [comment]
You can already clear armor slots with /clear ** but the offhand slot should be included.

**Comment by Kosyne** [comment]
I'd like to see this one as well. Using this command for the prep phase of an arena, and I don't want people sneaking non-pvp-kit items into it.

**Comment by Kosyne** [comment]
Yeah, just did this in my own build, all you need to do is add a `player.getInventory().setItemInOffHand(null);` after `player.getInventory().setArmorContents(null);`

Too bad the new clear confirmation breaks my original purpose for this command  (clear inventory upon clicking a button to enter an arena), so guess I'll have to get rid of that as well :/
