### ISSUE TITLE
Command Usage Custom Messages

### ISSUE THREAD

**Issue by CryptoMorin** [EssentialsX/Essentials#1427]
It would be hard but can you add custom messages for your command usage in messages.properties? As it's not nice having a fully white message displayed.

**Comment by Antivalent** [comment]
You can actually edit the descriptions found in the plugin.yml, here's an example:
```
  tpa:
    description: §6Sends a teleport request to a target player.
    usage: §c/<command> <player>
```
This will make the help message appear colored ingame, with §6 representing gold and §c representing light red.

**Comment by CryptoMorin** [comment]
Thank you!
Working just fine.
