### ISSUE TITLE
KeepInventory for /suicide

### ISSUE THREAD

**Issue by FrankHeijden** [EssentialsX/Essentials#1429]
Im requesting this feature as most players hate it to lose their items when they do /suicide. I think this feature would really make the command better. Was thinking of a boolean config option, to toggle the usage.

EssentialsX version (`/essentials`): 
reloaded 2.0.1-b499

Server software (`/version`): 
CraftBukkit version git-Spigot-596221b-2c5c611 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT

**Comment by pop4959** [comment]
Closing this issue since there doesn't seem to be much interest in it. If someone wants to implement it, feel free though.
