### ISSUE TITLE
Message for when another player has msgtoggle enabled?

### ISSUE THREAD

**Issue by denizaygundev** [EssentialsX/Essentials#143]
Hi is it possible to add a message to /msgtoggle so that users can realise that the person they're messaging isn't receiving their messages bit like the one for /tptoggle

Not sure why something like this hasn't been added already :/

**Comment by EvilOlaf** [comment]
Should have been added, see https://github.com/drtshock/Essentials/commit/891605380ffcc52671f3e6874a28b32f16ffce58

It is untested though. Do you have proper permissions?

**Comment by denizaygundev** [comment]
Yep perms are all fine as I'm OP'd plus the messages don't go through, they just hide away.

**Comment by drtshock** [comment]
No as we went with the functionality of /ignore with /msgtoggle so people don't know you are ignoring them.

**Comment by denizaygundev** [comment]
But why? Surely it would be important for a player to know if their friend is receiving their message...

Or in my case a player knows whether the owner is receiving their message or not.. Please consider adding a message notifying the user, much appreciated.

**Comment by vemacs** [comment]
Considered, but at least on my servers, the use scenario is for YouTubers who most definitely do not want fans to know that they're being ignored.
