### ISSUE TITLE
Cannot negate essentials.build.pickup.anything after essentials.build.pickup.*

### ISSUE THREAD

**Issue by YepImRobbie** [EssentialsX/Essentials#1437]
Is it possible to do essentials.build.pickup.* and then add essentials.build.pickup.435 and it work? Because it isn't for me with any ID. I'm using PowerfulPerms.

**Comment by mdcfe** [comment]
Have you tried using the item name instead? I haven't checked but that might work.

**Comment by mdcfe** [comment]
Correction: I don't know about IDs/names, but you should make sure you put the `essentials.build.pickup.435` *before* the wildcard negation, as that's how permissions plugins tend to read perms.

**Comment by YepImRobbie** [comment]
appreciate the help; although it wasn't the answer.

To future viewers just do :0, -essentials.build.pickup.435:0
