### ISSUE TITLE
No perm to sell in bulk

### ISSUE THREAD

**Issue by denizaygundev** [EssentialsX/Essentials#144]
I tried add essentials.sell.bulk, essentials.sell.*, essentials.sell.hand, essentials.sell and still no luck. 

Using build #190

**Comment by drtshock** [comment]
You need essentials.sell and essentials.sell.bulk

**Comment by remibarna** [comment]
/sell hand and /sell all dosent work I tried all the perms that you said and it dosent work this is from build #190 please fix

**Comment by denizaygundev** [comment]
"You need essentials.sell and essentials.sell.bulk"

Please read what I said properly. And as remibarna has said this is an issue from build #190

**Comment by remibarna** [comment]
This build needs fixing, this was not a successful build.

**Comment by drtshock** [comment]
Just tested with build 192 (same as 190) and it works fine. You must've given the wrong permissions.

**Comment by denizaygundev** [comment]
I will confirm this when I get back, thanks.

**Comment by denizaygundev** [comment]
Even with "essentials.sell.bulk" I can't do /sell inventory but I can do /sell all
