### ISSUE TITLE
[Suggestion] Add Teleport-invulnerability permissions

### ISSUE THREAD

**Issue by Zoiter7** [EssentialsX/Essentials#1443]
Hello, I have suggestion, Add Teleport-invulnerability permissions, or do it per world, because I want to avoid the tpakills but if I use this option the user teleport to /warp pvp for example and have the invulnerability.
Or add tpa invulnerability.

Regards,

**Comment by mdcfe** [comment]
As in, make the player invulnerable for a short delay when they teleport to someone?

**Comment by Zoiter7** [comment]
@md678685 Yes, or add permission to use the teleport-invulnerability per world, so there would be no problems with the warps that are not in the same world. The idea is add some method to player invulnerability when a player using /tpa command, because now if you use /warp command o other command of teletransportation the invulnerability is active, and I don't want this because as I said before
when I use /warp pvp I have the invulnerability.

**Comment by pop4959** [comment]
The teleportation invulnerability is global, if you need something custom per world for mini games and such, you should probably get a custom plugin for that.
