### ISSUE TITLE
Minecraft issuse with EssentialsX essentials.gamemode

### ISSUE THREAD

**Issue by niki2416** [EssentialsX/Essentials#1447]
Hello...I have a problem with EssentialsX
I gave a permission essentials.gamemode,essentials.gamemode.others,essentials.gamemode.creative......
But they still don't have permissions....
If someone can help,please tell me!
                                                                                                                    Thank You!

**Comment by SupaHam** [comment]
Chances are, they don't have the permission. Check your permissions plugin. If it is GroupManager, we don't support it.

**Comment by niki2416** [comment]
Ok,i will check and reload plugin

**Comment by niki2416** [comment]
OMG....The problem was a Chat Control plugin -_- now all is OK.....Thanks for support :)
