### ISSUE TITLE
Vanish Bug

### ISSUE THREAD

**Issue by Topburns** [EssentialsX/Essentials#145]
I keep getting put into vanish randomly, I do not get notified. People can not see my name in TAB nor can they see me they are also unable to message me. Does anyone know how to fix this issue? Is it a glitch or a bug. It is really annoying and causing a lot of problems for me

Update: Some people can see me and some can't

**Comment by Agazed** [comment]
Getting this too. Not sure if it's related to essentials, or a different plugin.

**Comment by zRiaz** [comment]
I have noticed this too.

**Comment by drtshock** [comment]
what really? I've never seen this before.

**Comment by FlippantCactus** [comment]
@drtshock It's been a long issue. It's an essentials "bug". When you log in, people can't message you etc... It's a permission. essentials.silentjoin.vanish
It's really frustrating though, should probably be removed. If people want to be in vanish upon join, a separate plugin wouldn't be hard to make for that.

**Comment by denizaygundev** [comment]
Exactly ^ 

I remember having some issues myself a while back with this.

**Comment by Agazed** [comment]
@TWSSYesterday That's not the issue.

**Comment by Topburns** [comment]
~ Also I don't know if i was very clear in my first post, some people can not even see me when i stand in front of them but some can, We have ecopets on the server can everyone can see my pet but can't see me. along with the other issues ~ 

Thanks, just wanted to add that is a did not think i made that part very clear in my first post

**Comment by drtshock** [comment]
So don't give people essentials.\* or *

**Comment by Kakifrucht** [comment]
I'm all for a complete removal of any vanish capabilities! :D
However I'm not having this issue neither.

**Comment by Topburns** [comment]
~So don't give people essentials.\* or *

That has not fixed the problem

**Comment by afroman84** [comment]
i have this breaking bug in my server, latest 1.10.2 spigot. Still not solved? it is server-breaking, players can't see each others randomly and also moderators cannot see players. For vanish purpose i use VanishNoPacket, please help me also just with a temporary workaround :(

**Comment by mdcfe** [comment]
It doesn't matter whether or not you have essentials.silentjoin.vanish or not; after turning vanish on and back off, some players still can't see the previously vanished player. This is still happening in the latest version (as of today).

**Comment by afroman84** [comment]
apparently i solved removing vanish from plugin.yml. 
this bug is server-breaking, IDK why they work on other commits when this is not solved

**Comment by mdcfe** [comment]
@afroman84 As far as I'm aware the devs haven't ever managed to replicate the bug, and nobody has found criteria to trigger the bug, so it's not fair to say they're not bothering with this bug.

**Comment by afroman84** [comment]
I could give some hints to replicate the bug: i'm using these plugins that may afflict the visibility of players: EssentialsX (last), Party and Friends 1.0.86, VanishNoPacket (last). 
I solved as i said removing the vanish part of plugins.yml inside EssentialsX.
Using last spigot. I do not believe that no-one are using EssentialsX in combination with VanishNoPacket. 
Party and Friends is a plugin for parties and a friends list, and letting players choose to hide all players, or just see their friends. 
I removed this plugin, but only when editing plugins.yml inside Essentials i solved definitively. 
Playing with permissions were unuseful too, or disabling vanish from the essentials config.yml, also disabling essentials:vanish from commands.yml had no results.
I have 3 servers connected with bungeecord. In the hub i uploaded this modified version of essentialsX without vanish part. The other 2 servers had a default essentialsX. When joining on the hub, no problems. when entering one of the other's server, players can't see who joined after them. The moderators had to go back to the hub, then rejoin the server and so they see again everyone. they to do this every time when they encountered the issue.
Sorry for being unfair, i didn't meant to be, i just want to help and I hope that this informations will be useful for everyone.
I think there's some conflict with VnP and its joinvanished permission/function.

**Comment by mdcfe** [comment]
@afroman84 This issue is strictly about EssentialsX's vanish functionality (which is indeed broken) - it might be worth reporting your conflict with VnP in another issue.

**Comment by mdcfe** [comment]
This might be related to #1764.

**Comment by mdcfe** [comment]
Can anyone still replicate this as of 2.15.0 or any later version? #1796 appears to have fixed #1764 and I'm not aware of any recent reports of vanish bugs.

**Comment by pop4959** [comment]
I used to have this issue but it must have been fixed with the above changes. If anyone else is having this still, today, with the latest version of Essentials, I'd advice opening a new issue.

**Comment by lee3kfc** [comment]
i got same issue with EssentialsX2.19.7 on paper1.19.2.
i am the only one who can use /vanish command on my server, so i logged out from my server and then deleted my data from Essentials/userdata folder and servername/mainworld/playerdata folder. it worked.

**Comment by Soundouss-benabou** [comment]
Hi guys , The problem you are describing, whereby you randomly get thrown into "vanish" mode, is starting to sound like a plugin, mod, or setting from a Minecraft server, particularly if you use said or similar software. you can use this link: https://1921681001.id/

**Comment by Lapua1** [comment]
non of you guys have been useful, every entity is "vanished" still even after reinstalling the mod.

**Comment by mdcfe** [comment]
> non of you guys have been useful, every entity is "vanished" still even after reinstalling the mod.

@Lapua1 This issue has been closed for 5 years, and does not have anything to do with hiding other entities. If you believe you have found a bug with EssentialsX and have steps to reproduce it, please open a bug. If you need more general support, please join the Discord server and ask.
