### ISSUE TITLE
Question: Repair Signs

### ISSUE THREAD

**Issue by CryptoMorin** [EssentialsX/Essentials#1450]
Hello since i'm using a kitpvp plugin and i want to allow my users to repair their armor in the arena for free but not all of them as some items have special one-time-use ability.

Is there something like this possible:
    - essentials.signs.use.repair
    - -essentials.signs.use.repair.GOLD_SWORD

Or is not added? or it must be item ID?

**Comment by SupaHam** [comment]
This is not possible right now. We may add this in the future.

**Comment by pop4959** [comment]
You should probably consider getting a custom plugin for that if you haven't already. It's not likely that Essentials will have such specific repair commands.
