### ISSUE TITLE
Do nothing if "/home" is used when no home is set.

### ISSUE THREAD

**Issue by stapleshotz** [EssentialsX/Essentials#1452]
EssentialsX version (`/essentials`): 2.0.1-b488

Server software (`/version`): 1.12.1-R0.1-SNAPSHOT

Currently, if a player uses "/home" and they have no home set or their bed home was destroyed etc. they are teleported to the spawn. That's great, but if you have a setup where players use beds as their homes exclusively, if those beds are destroyed the player has no way of knowing and is teleported to the spawn when they expect to go somewhere else. This can be annoying for many.

**What I'd like to have happen:** When a player uses "/home" and their home is not set, they don't get teleported anywhere and a message appears saying something like "You have no home set."

This used to be a feature in Essentials. In the config it looked like this:
------------------
If no home is set send you to bed or spawn when /home is used
spawn-if-no-home: true/false

**Comment by mdcfe** [comment]
This was removed from the upstream Essentials a long time ago:
* Added in dd164d2e38a0e18051de0ce34075774c9347cd4e
  - Seems to have been refactored a lot in the 8 months it existed
* Functionality removed in 4c2b9b8d0fd35cd27ef4cbdd0a8e4200d02926b0
* Config option removed from ISettings in 256ce9e9e6b3b256b5750d1abeb274881f4ad58a
* Config option fully removed in edbac5560d52c1b6bd635f49a4ed7defc4d49281

It doesn't look too difficult to reimplement this now, looking at the [`/home` command class](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/commands/Commandhome.java#L57).

**Comment by Weasel-Beans** [comment]
On my server regular members cannot use /sethome, but can right click a bed and use '/home' or '/home bed' to teleport back to it. However like stapleshotz points out, when players move their bed and forget to reset their home, the command takes them back to the global spawn, which is unused on my server. If it was possible to instead set it so typing /home with no home set returns an error message (eg. "You do not have a home!") that would save some of my players a lot of confusion.

**Comment by mdcfe** [comment]
This has been implemented in [EssentialsX 2.17.1.19 and above](https://essentialsx.cf/downloads.html).
