### ISSUE TITLE
Malfunctioning UUID mechanism.

### ISSUE THREAD

**Issue by Sitmobedaf** [EssentialsX/Essentials#1453]
Hello, DRTShock.
I'm writing on an old Essentials problem.

When I use /seen <nick with Russian characters> or /unban <nickname with Russian characters> or any other command Essentials and <nickname with Russian characters>
We do not get the result that we would like. Esentials can not work correctly with Russian-speaking nicknames. It seems that it is not fully translated into the UUID. And it would be nice to add the ability to use Offline UUID. There is also a problem with the ban players. If the nickname of the player is licensed, but has a different case of letters, for example Not Sit, and SiT, then the player will not be banned. Offline Offline UUID players ban. And please correct the ban using not English letters in player nicknames.

WARNING: Translated by Google Translate

All versions of Essentials.
All version of Bukkit or Spigot.

**Comment by mdcfe** [comment]
Offline mode servers are not supported. (Also, nicknames have nothing to do with UUIDs.)

**Comment by Sitmobedaf** [comment]
I've known this problem since 1.6.4
When Essentials was not on UUID Russian words were replaced by "_"
Now Russian-language nicknames are normally displayed in playerradata-files. But there are problems when using commands. Do not rush to close my ticket, I waited 3 years.

**Comment by Sitmobedaf** [comment]
And yes, there are still problems with the economy when using Russian-language nicknames. Players lose their money, or on the contrary get someone else's balance. 
Are you not interested in this problem? Essentials is working for UUID and it seems that it should perfectly cope with Russian symbols in UTF-8?

**Comment by mdcfe** [comment]
If you can replicate this on an online mode server then I'll reopen the issue, otherwise I can't help.
