### ISSUE TITLE
 [closed]

### ISSUE THREAD

**Issue by soliddanii** [EssentialsX/Essentials#1454]
closed

**Comment by mdcfe** [comment]
Based on drtshock's response to #807, I still don't think we're going to manually hook into a third-party vanish plugin to add support for it, especially not a paid one. There's already hooks so that plugins can set whether or not the player is hidden through the API (`User#setHidden`).

**Comment by soliddanii** [comment]
PhantonAdmin has been open source for 8 months now.
https://github.com/BigScary/PhantomAdmin
Is there any docs for that API?

**Comment by mdcfe** [comment]
```
IEssentials essentials = (IEssentials) Bukkit.getPluginManager().getPlugin("Essentials");
IUser user = essentials.getUser(player);
user.setHidden(true);
```

**Comment by soliddanii** [comment]
I tryied using reflection so I dont have to add the dependency, but it doesn't work, the message still shows      😞 

public static void setHidden(Player player, boolean value) 
    {     
        try 
        {
            
            Plugin essentials = Bukkit.getPluginManager().getPlugin("Essentials");
            Method getUser = essentials.getClass().getMethod("getUser", String.class);
            Object essentialsPlayer = getUser.invoke(essentials, player.getName());
            
            if (essentialsPlayer != null) 
            {
                Method setHidden = essentialsPlayer.getClass().getMethod("setHidden", boolean.class);
                setHidden.invoke(essentialsPlayer, value);
            }
            
        } catch (Exception e) 
        {
            e.printStackTrace(System.err);
        }
    }

I don't understand why not, I don't get any errors. Any help will be much appreciated.

**Comment by mdcfe** [comment]
This isn't a Java support thread.

You can use [this Maven repo](https://ci.drtshock.net/plugin/repository/) for an always up-to-date version of EssentialsX to build against, and EssentialsX should be included in your build config as a `provided` dependency.
