### ISSUE TITLE
Fire arrows in god/vanish

### ISSUE THREAD

**Issue by NewBestX** [EssentialsX/Essentials#1456]
If a player with god or vanish enabled shoots a player with a bow enchanted with FLAME, the player shot will not take the damage from the arrow itself, but the fire effect will still apply and could kill him. The first player does not have the permission to pvp from god/vanish.
This issue is a duplicate of an issue submited by me almost 1 year ago: https://github.com/drtshock/Essentials/issues/871

I can't understand the delay as it should be a super-easy fix. 
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityCombustByEntityEvent.html

**Comment by Azewilous** [comment]
A Pull Request submitted earlier was merged that fixed this bug.

**Comment by SupaHam** [comment]
This has been fixed in 13fbd311. You can grab the fix from [build 519](https://ci.drtshock.net/job/EssentialsX/) on the CI server.
