### ISSUE TITLE
How to stop Essentials take over Important command function?

### ISSUE THREAD

**Issue by EnderDragonEP** [EssentialsX/Essentials#1458]
How can I use the Minecraft's original commands?
for example: ```/give```, ```/kill```, ```/tp``` commands.
Because Essentials take over it, but I want to use some command like  ```/kill @e[type=!Player] ``` and  ```/give @p mob_spawner 1 0 {BlockEntityTag:{SpawnData:{id:villager_golem},SpawnPotentials:[]}} ```
but those command did not work when Essentials it enabled......
Is there any way to stop Essentials take over those commands?

Server: Spigot 1.12
Essentials plugn version: EssentialsX-2.0.1

**Comment by jyhsu2000** [comment]
How about add `minecraft:` prefix when using?
`/minecraft:kill @e[type=!Player]`, `/minecraft:give @p ... `, ...

**Comment by smmmadden** [comment]
or don't use essentials, but you lose more by doing so. :-)

**Comment by EnderDragonEP** [comment]
@jyhsu2000  YES! It did work! thank you a lot!!!
But unfortunately... Essentials plugin lock the give spawner command as a Pig_spawner......
the only way to fix this It to remove Essentials plugin, I think......

**Comment by jyhsu2000** [comment]
After place the spawner,
use `/spawner` command from Essentials to modify the types of mobs of the spawner you're looking at.

**Comment by EnderDragonEP** [comment]
That's right...
But I need to put these things into chest, for players to use

**Comment by EnderDragonEP** [comment]
I try to create another world and put those Spawners into a chest and load to server, but It still all become Pig Spawner

**Comment by mdcfe** [comment]
Use Bukkit's `commands.yml` to override the commands with their `minecraft:` version.

If you are having an issue with spawners, please create a separate issue.

**Comment by EnderDragonEP** [comment]
@jyhsu2000 Yes! It did work!! thank you a lot!!!
but mob spawner still can not use.... Essentials locked it as a Pig spawner......

**Comment by Peak123455** [comment]
You can use /execute as @s run >minecraft commands<
 and /minecraft:

**Comment by Chew** [comment]
Please don't comment on years old issues, the discussion has run its course and your suggestion was already offered...
