### ISSUE TITLE
http://ci.drtshock.net/job/essentialsx/ Reporting "Bad Gateway"

### ISSUE THREAD

**Issue by CDAGaming** [EssentialsX/Essentials#1459]
Build Site isn't working, and reporting "Bad gateway"

**Comment by FunnyCraft** [comment]
+

**Comment by SupaHam** [comment]
It's back up. Sorry for the inconvenience.

**Comment by CDAGaming** [comment]
Thank You :)
Can confirm its up now

**Comment by krusic22** [comment]
Dead again.

**Comment by ghost** [comment]
Still dead

**Comment by smmmadden** [comment]
update your bookmarks to use the one behind the Download button on the main page.  The url has changed.
