### ISSUE TITLE
Remove the "Use the /back command to return to your death point." message

### ISSUE THREAD

**Issue by denizaygundev** [EssentialsX/Essentials#146]
Hi, so currently this message only appears when the user has essentials.back.ondeath however the user can't do /back without essentials.back and for me this is a problem as I have a CommandSign (external plugin that lets you run commands through signs) at my spawn which allows players to return to their previous location however they of course need essentials.back.ondeath for this to work and the command "/back" is a donator only perk so for non-donators to see the message it's misleading and I get a few complaints.

I hope that makes sense, thanks!

**Comment by zRiaz** [comment]
Remove it yourself in the language file..

**Comment by denizaygundev** [comment]
Ah, completely forgot about that, thanks
