### ISSUE TITLE
Error when players right click while holding *anything*.

### ISSUE THREAD

**Issue by stapleshotz** [EssentialsX/Essentials#1465]
EssentialsX version (/essentials): 2.0.1-b488

Server software (/version): Spigot 1.12.1-R0.1-SNAPSHOT

When players are holding a bow in their main hand and they right click, console gives this error:
https://pastebin.com/qNk9EU6N

The same error appears regardless of gamemode or whether or not they have arrows to shoot.
The error does **NOT** appear if the bow is in the off hand.
The error does **NOT** appear if the player is looking at a block/entity that is close enough to interact with.

Seems like it only shows up when they're looking at something too far away to interact with.

**Comment by stapleshotz** [comment]
Actually, it turns out it doesn't have to be just a bow. The error happens when they are holding **ANY** item. 
The error does **NOT** appear if the player is holding nothing in their hand.

**Comment by mdcfe** [comment]
This was fixed in 7fbc721db6a405c3fd4185190d9d86c0e3dfe1c4 - make sure you've updated EssentialsX from the [build server](https://ci.drtshock.net/job/EssentialsX).
