### ISSUE TITLE
Cant Break BLocks

### ISSUE THREAD

**Issue by FatmanC** [EssentialsX/Essentials#1467]
EssentialsX version (`/essentials`): 

Server software (`/version`): 

EssentialsX config (if applicable): 

EssentialsX 2.0.1-b488
running MC:1.12
newb question, i have looked through all the config files, and dont know what i am doing wrong. PLayers joining my server cannot break or place blocks without first creating a claim. Then, and only then they can, and they can only mine within their claimed areas.

OP's can use /ignoreclaims but it doesnt allow for free mining or anything. How can i correct this problem?

**Comment by mdcfe** [comment]
EssentialsX doesn't have a claiming system in place. Check your plugins list (you could post it here if you want) for a plugin that handles land claims.

**Comment by FatmanC** [comment]
it is fixed. It was grief prevention plug in. Sorry for confusion
