### ISSUE TITLE
/spawn command

### ISSUE THREAD

**Issue by FatmanC** [EssentialsX/Essentials#1468]
EssentialsX version (`/essentials`): 

Server software (`/version`): 

EssentialsX config (if applicable): 
how do i enable a /spawn command to work for all players? that when entered, send people back to the world spawn point i set?

**Comment by mdcfe** [comment]
Using the EssentialsXSpawn module, you can set a spawnpoint with `/setspawn`. Players can then use `/spawn` to teleport to it. In addition, you can use the `spawn-on-join` option in the config to set a spawn - see the [wiki](https://github.com/drtshock/Essentials/wiki#teleport-to-spawn-when-joining) for more info.

You can download EssentialsXSpawn from the [build server](https://ci.drtshock.net/job/EssentialsX) - make sure you're running the same build of EssentialsX and EssentialsXSpawn though.

**Comment by mdcfe** [comment]
Feel free to respond if the above response didn't answer your question, and I'll reopen the issue.
