### ISSUE TITLE
Repair player argument

### ISSUE THREAD

**Issue by LogGits** [EssentialsX/Essentials#1469]
Is there a way to repair a players inventory/hand without giving the player access to the /repair command? Something that could be used if an admin needed to repair a players inventory for example.

**Comment by SupaHam** [comment]
Maybe create a [repair] sign and break it after?

http://wiki.mc-ess.net/wiki/Sign_Tutorial#Repair_Sign

**Comment by LogGits** [comment]
How can i do that in console? I also want to use it for vote party rewards.

**Comment by SupaHam** [comment]
You can't. You have to create this sign in game.
