### ISSUE TITLE
Spawner Bug Build #190

### ISSUE THREAD

**Issue by remibarna** [EssentialsX/Essentials#147]
There is a bug with spawners, my player had a iron golem spawner, placed it into his EnderChest, PlayerVault and /hat and floauction every time it turns into a pig spawner, the UUID for spawners need to be fixed or somthing please fix ASAP this is causing a lot of problems

**Comment by Terrobility** [comment]
I can't replicate this without floAuction. It's probably an issue with floAuction.

**Comment by drtshock** [comment]
Which version of spigot?

**Comment by denizaygundev** [comment]
It says in the title "Spawner Bug Build #190 " ....

**Comment by vemacs** [comment]
Spigot, not EssX

**Comment by remibarna** [comment]
It's essentialsX because spigot has nothing to do with it but spigot 1.8 dryshock

**Comment by vemacs** [comment]
Spigot has a lot to do with it. What Spigot version exactly? We build against 3 versions of Spigot. I strongly suggest you upgrade to 1.8.3+.

Furthermore, do the players have spawnerconvert permissions? (essentials.spawnerconvert.mobtype or essentials.spawnerconvert.*)

**Comment by remibarna** [comment]
I just upgraded my spigot to spigot 1.8.8 on my test server, also I am OP on it. Used essentialsX build 190 and it still dosent work, it's the essentials UUID not working well when you transfer the spawners into a EnderChest, Player Vault and /hat and floauction. This is a big bug that must be fixed befor other servers realize it

**Comment by vemacs** [comment]
Spawners have nothing to do with UUIDs...

I can't reproduce it on my 1.8.8 server with BetterEnderChest, PlayerVaults, and floAuction, with typically 100+ peak players daily. Nobody else seems to be able to either. Seems incredibly isolated and probably a configuration issue on your part. Server startup log, please.

**Comment by Kakifrucht** [comment]
There are no issues I can replicate with the spawners currently. The issue is clearly on your side.

Give yourself a spawner with /i mobspawner:mobid 1
Give yourself the permission essentials.spawnerconvert.mobtype
Try without potentially interfering plugins.

**Comment by remibarna** [comment]
http://pastebin.com/BemMw7UR

The consol start up of essentialsX spawners not working please look at it

**Comment by remibarna** [comment]
Also, please note that I found bug and this is for sure essentialsX if I'm wrong, do this challenge. 

Install essentialsX build 190 
Install PlayerVaults
install FloAuctions 
Use any spigot 1.8 + jars and you tell me if it works, cause this happend on a server called Skylarkpvp.net all the time and they have 200 players on a day and they are also waiting for this bug fix, listen to this and fix the problem then ignoring it.

**Comment by drtshock** [comment]
The startup is fine. The blockplace event is having issues because of coreprotect it looks like.

**Comment by remibarna** [comment]
Nope, I took out core protect, restarted server and tried it again placing the spawner in player vault and taking it out again and it's still a pig spawner

**Comment by vemacs** [comment]
Update to 1.8.7 (recommended) or the last 1.8.3 build (not recommended). PlayerVaults does not store spawners correctly on 1.8 and earlier builds of 1.8.3 due to the BlockStateMeta API being introduced in later builds of 1.8.3.
