### ISSUE TITLE
Stacktrace

### ISSUE THREAD

**Issue by xtechgamer735** [EssentialsX/Essentials#1473]
EssentialsX version (`/essentials`): Essentials v2.0.1-b488

Server software (`/version`): 1.12.1

EssentialsX config (if applicable): 

Hello! This stack trace is randomly showing up on my server and spams console.

https://pastebin.com/YDvNqd6w

Thanks!

**Comment by LaxWasHere** [comment]
Please update to the latest version of EssentialsX https://ci.drtshock.net/job/EssentialsX/
