### ISSUE TITLE
Chat formatting not working?

### ISSUE THREAD

**Issue by Stephambish** [EssentialsX/Essentials#1476]
I cant add chat formatting such as colors with &a-f or &0-9

EssentialsX version : 2.0.1

for minecraft 1.12

**Comment by SupaHam** [comment]
You need to have:
- `essentials.msg.color` permission for colors
- `essentials.msg.magic` permission for magic/obfuscated text
- `essentials.msg.format` permission for formatting permissions

http://wiki.mc-ess.net/wiki/Command_Reference/Perm
