### ISSUE TITLE
Random error log spam on console

### ISSUE THREAD

**Issue by MithrandirCraft** [EssentialsX/Essentials#1479]
https://hastebin.com/zuyudepuya.vbs

EssentialsX version (`/essentials`): 2.0.1 b-496

Server software (`/version`): Spigot with Bungee for MC 1.12.1

**Comment by LaxWasHere** [comment]
Please download the latest version of essentials at https://ci.drtshock.net/job/EssentialsX/

**Comment by MithrandirCraft** [comment]
Done, will report if any further issues.

**Comment by MithrandirCraft** [comment]
Looks like that solved it. Thanks.
