### ISSUE TITLE
AFK Kick Modification?

### ISSUE THREAD

**Issue by zRiaz** [EssentialsX/Essentials#148]
So basically, I would want it to be able to extend someone's AFK timeout without giving them bypass.
Maybe like certain players/staff can be on for maybe 1 hour while regulars can only be on for 30 minutes before being kicked.
Maybe make it a bit like the sethomes work or just a command thats like /afkextend (player) (minutes)

**Comment by drtshock** [comment]
Any justification for this? Just seems silly imo.

**Comment by zRiaz** [comment]
Idk its a decent Donor perk perhaps, to give them a bit more time to afk before getting kicked.
And I would have my Staff being able to stay on a bit longer to catch up with messages if they have to afk for a little while.
Idk. But if you're not feeling it I understand that, might  just get a plugin made that does it in that case..

**Comment by drtshock** [comment]
Why are you kicking afk players? Don't you want more players on your server..?

**Comment by Kakifrucht** [comment]
For staff there already is a bypass permission AFAIK.
