### ISSUE TITLE
EssentialsX plugin problem 1.11.2/1.12

### ISSUE THREAD

**Issue by user1000012** [EssentialsX/Essentials#1483]
\Problem is :

when paying an offline player it says:
Error:player not found.
Please fix it. Please! For God's sake. or tell me how to pay an offline player. please
ASAP REPLY ASAP

**Comment by SupaHam** [comment]
http://wiki.mc-ess.net/wiki/Essentials_Economy

**Comment by smmmadden** [comment]
There doesn't appear to be anything on wiki/Essentials_Economy about paying offline players.  I did a quick search and found a solution that "may" work.  Scroll down to note 19 for the dropbox download of the jar file.  https://bukkit.org/threads/offline-paying.300132/

Good luck!
Steve
