### ISSUE TITLE
EASSENTIALSX 1.11.2/1.12

### ISSUE THREAD

**Issue by user1000012** [EssentialsX/Essentials#1485]
I HAVE A PROBLEM! 
firstly I TRIED TO POST THIS 3 TIMES RIGHT NOW BUT IT DOESNT GETTING SAVED!

SECONDLY I CANT PAY OFFLINE PLAYER IN MY SERVER!
BUT NORMALLY IT MUST WORK

**Comment by user1000012** [comment]
test

**Comment by SupaHam** [comment]
I won't say this again. Stop creating issues. Your issues are not disappearing. They are all under different ids e.g. #1483 

Stop creating new issues!
