### ISSUE TITLE
messages_en.yml Latin Chars

### ISSUE THREAD

**Issue by Ganeb** [EssentialsX/Essentials#1487]
EssentialsX version (`/essentials`): 2.0.1-b493

Server software (`/version`): Spigot 1.8.8-R0.1-SNAPSHOT

Hello, i have a question/concern about modifying messages_en.yml to my liking, i wan't to make my server as much as understandable to Lithuanian players as possible, but to do that, i need to use Latin characters for correct spelling, latin characters that i need to use are: ąčęėįšųū, and if i write them in that config, in messages it comes up like this:
http://imgur.com/a/xSJQP

So i need to know, if you can't write that kind of letters, maybe i'm doing something wrong, hoping to get 
a response ASAP, thanks!

**Comment by mdcfe** [comment]
Looking at [`messages_ro.properties`](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/messages_ro.properties), it looks like you'll need to use Unicode escape codes for special characters, for example `\u0109` would represent `ĉ`. The best reference I've found so far for this is [unicodelookup.com](http://unicodelookup.com) - you'll want to look under the `Dec` column for the code, then add `\u` to the beginning with as many zeros as needed to pad it to 4 digits (`94` -> `\u0094`, `163` -> `\u0163`) then enter that in place of the character you want to insert. If this still doesn't work, then it's likely a limitation of Minecraft's font.

**Comment by Ganeb** [comment]
Nope, it doesn't work, tried Oct, Hex, Dec, all results turned out wrong, i'm in the dead end here, i'll wait maybe someone will have other solution, thanks for effort.

**Comment by SupaHam** [comment]
Minecraft doesn't support certain characters which renders them weirdly. You need to find the right equivalent of what you're looking for. I'm not sure if it exists, but seeing as Minecraft is multi-national and aims to support all languages, I would assume that your characters are supported. Have a look at the official Minecraft client language files and what characters they use.

**Comment by mdcfe** [comment]
You could also ensure that you're saving the file as UTF-8, but that doesn't look like the problem here.

**Comment by Ganeb** [comment]
I tried using \u0279, other numbers, one time it came up as upside down r, next time it showed only e, not ė

**Comment by Ganeb** [comment]
Guys at discord helped me out, this was the [unicodes for chars](http://www.geocities.ws/click2speak/unicode/chars_lt.html), i will close this issue, thanks for everyone who commented.
