### ISSUE TITLE
Essentials Groupmanager Problem

### ISSUE THREAD

**Issue by chefgre** [EssentialsX/Essentials#1488]
Caused by: while parsing a block mapping
 in 'reader', line 12, column 3:
      player:
      ^
expected <block end>, but found BlockMappingStart
 in 'reader', line 24, column 4:
       SuperVIP:
       ^

seem to be getting this error constantly

 any ideas?

**Comment by mdcfe** [comment]
We don't provide support for GroupManager. I'd recommend switching to LuckPerms (or, if you'd prefer, PermissionsEx). If you're using a maintained version of GM, contact the maintainer.

**Comment by smmmadden** [comment]
A third option is to use the new [GroupManagerX plugin](https://www.spigotmc.org/resources/groupmanagerx.32280/)
