### ISSUE TITLE
[Idea] Modify Broadcast Prefix

### ISSUE THREAD

**Issue by Techno3600** [EssentialsX/Essentials#1490]
Hello,

I was wondering if in the configuration an option like:

broadcast-prefix:
`&6[&4Broadcast&6] &a<message>`

This would be nice for modifying the prefix and could be very helpful to users.

Thanks
Techno3600

**Comment by mdcfe** [comment]
You're looking for `broadcast` in `messages.properties`. Copy the file for your language from [here](https://github.com/drtshock/Essentials/tree/2.x/Essentials/src/) (use `messages.properties` if you haven't changed the language) into `plugins/Essentials`, then edit the `broadcast=...` line as desired.
