### ISSUE TITLE
1.9 or up Enchant is not available thru sign

### ISSUE THREAD

**Issue by lifehome** [EssentialsX/Essentials#1497]
EssentialsX version (`/essentials`): 2.0.1-b523

Server software (`/version`): git-Spitogt-65e8124-963b19c (MC: 1.12.1) (API 1.12.1-R0.1-SNAPSHOT)

EssentialsX config (if applicable): default config

Steps to replicate issue:
1) Put an enchant sign, on line 3 write `Mending`
2) Click Done.
3) It breaks.

**Comment by mdcfe** [comment]
By "it breaks", do you mean the placed sign breaks or it doesn't work? In addition, does Mending work in `/enchant`?

**Comment by lifehome** [comment]
It looks like this:

![image](https://user-images.githubusercontent.com/1886237/29485291-1064f4a8-8502-11e7-9948-e579d3ea9a17.png)

**Comment by mdcfe** [comment]
Does `/enchant` work when you use Mending? This would help us narrow down the cause of the issue.

**Comment by lifehome** [comment]
Yes the command works, only the sign breaks

**Comment by mdcfe** [comment]
I believe you also need to specify a level, for example `mending:1` for Mending I (even though there's only one level for Mending).

@SupaHam Should we set a default level for enchant signs, either hardcoded or configurable?

**Comment by lifehome** [comment]
Thanks @md678685, it works as you said. However it seems it cannot stack enchantments to enchanted items, to replicate the bug, simply hold an enchanted item and right click at the enchantment sign.

![image](https://user-images.githubusercontent.com/1886237/29485796-c3d406ca-850a-11e7-8722-d47e679eadfc.png)

**Comment by mdcfe** [comment]
Does the enchantment override the existing enchantment, or does it not get applied at all?

**Comment by lifehome** [comment]
It simply rejects all enchanted items to be enchanted.

**Comment by SupaHam** [comment]
@md678685 I think it'll be fine to default to 1. However, we mustn't help discourage reading wiki. After all users must know what the signs are doing to prevent issues.

**Comment by lifehome** [comment]
@SupaHam thanks for the consideration. I suggest letting the plugin to evaluate if the line either does not contain enchantment level, to prompt a related error, or to tell the enchantment does not exists.
