### ISSUE TITLE
Could not pass PlayerInteractEvent to Essentials [Spigot 1.12.1]

### ISSUE THREAD

**Issue by Morsmorse** [EssentialsX/Essentials#1499]
This Error is spamming the console after I updated to spigot 1.12.1
https://gist.github.com/Morsmorse/a4d7d988d4c7d17b8bb294da0e4f3680

EssentialsX version (`/essentials`): 2.0.1-b491

Server software (`/version`): git-Spigot-65e8124-357b573

**Comment by mdcfe** [comment]
[Update EssentialsX](https://ci.drtshock.net/job/EssentialsX). This has already been fixed.
