### ISSUE TITLE
/kill,/suicide and /spawnmob not working

### ISSUE THREAD

**Issue by MEMOTNTN** [EssentialsX/Essentials#1500]
As the title says I am the owner of the server and I am OP but I cannot do any of those commands for some reason! They used to work but not anymore. 
I don't even receive anything in chat telling me if I did something wrong. 
I have '*' Permission in PEX.
even when I try kill (playername) the player doesn't die.
Please help.

my plugins: Wild, WorldEdit, ArcaneEnchants, Essentials, OreNotify, ClearLag, FactionsChat, SurvivalGames, JustInvSee, Votifier, WorldGuard, Multiverse-Core, ProtocolLib, KitAdder, iDisguise, EssentialsChat, EssentialsGeoIP, PermissionsEx, EssentialsAntiBuild, AntiCheat, mcMMO, Multiverse-Portals, AntiSwear, GAListener, Vault, GriefPrevention, EssentialsSpawn, MassiveCore, EnjinMinecraftPlugin, ChestShop, HolographicDisplays, BedwarsRel, Factions, FactionsPlus, ServerSigns, SuperVanish, CratesPlus.

Server software: This server is running CraftBukkit version git-Bukkit-357b573 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**Comment by LaxWasHere** [comment]
We unfortunately cannot help you without log files. Please ask the server owner to provide it and we also recommend not using the wildcard node '*'.

**Comment by MEMOTNTN** [comment]
Where can I find the log files?. And I am the server owner

**Comment by LaxWasHere** [comment]
Copy what's in "logs/latest.log" to https://hasteb.in/ and post the link in the channel. 

Do the commands that is not working first before opening the file so any errors can be copied.

**Comment by MEMOTNTN** [comment]
https://hasteb.in/raw/tetonoyavi

the commands were /kill /suicide and /spawnmob creeper

**Comment by LaxWasHere** [comment]
You are not running EssentialsX, please download the latest version of Essx here: https://ci.drtshock.net/job/EssentialsX/

**Comment by MEMOTNTN** [comment]
Still didn't work
https://hasteb.in/raw/jumimufuki

/summon works fine but not /spawnmob, /kill or /suicide

**Comment by LaxWasHere** [comment]
Please provide us with the full log.

**Comment by MEMOTNTN** [comment]
Here you go: https://hasteb.in/amumijeyug.coffee

**Comment by SupaHam** [comment]
`[00:11:01] [Server thread/ERROR]: Ambiguous plugin name `Essentials' for files `plugins/Essentials-2.x-SNAPSHOT.jar' and `plugins/EssentialsX-2.0.1.jar' in `plugins'`
Delete the old spigot jars. You can't run EssentialsX and others at the same time.

**Comment by MEMOTNTN** [comment]
Problem solved by:
Delete the old spigot jars. and installing EssentialsX.
Thanks to LaxWasHere and SupaHam <3 <3 <3
