### ISSUE TITLE
Essentials throws exception with ProtocolSupport

### ISSUE THREAD

**Issue by MasterGabeMOD** [EssentialsX/Essentials#1502]
Upgrading my network from MC from 1.12 to 1.12.1, there appears to be an exception being thrown with Essentials and ProtocolSupport. This exception didn't appear prior to 1.12.1. I'm uncertain if this exception is aimed towards ProtocolSupport or Essentials.

Error: https://pastebin.com/sBeqfF2t

EssentialsX version:  Essentials reloaded 2.0.1-b525.

ProtocolSupport version: 4.27

Server software: Paper version git-Paper-1191 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**Comment by mdcfe** [comment]
Update both EssentialsX from [its build server](https://ci.drtshock.net/job/EssentialsX) and ProtocolSupport from [its build server](https://build.true-games.org/job/ProtocolSupport/). This is an issue on ProtocolSupport's side that has been fixed.
