### ISSUE TITLE
Version mismatch When all running 2.0.1

### ISSUE THREAD

**Issue by CodedMindsorg** [EssentialsX/Essentials#1503]
EssentialsX version 2.0.1

Server software 1.12

Error
```
[15:39:37] [Server thread/INFO]: [Essentials] Enabling Essentials v2.0.1-b488
[15:39:37] [Server thread/WARN]: [Essentials] §4Version mismatch! Please update EssentialsProtect to the same version.
[15:39:37] [Server thread/WARN]: [Essentials] §4Version mismatch! Please update EssentialsChat to the same version.
[15:39:37] [Server thread/WARN]: [Essentials] §4Version mismatch! Please update EssentialsAntiBuild to the same version.
[15:39:37] [Server thread/WARN]: [Essentials] §4Version mismatch! Please update EssentialsSpawn to the same version.
```
All files are the same version (2.0.1) EssentialsX itself is running but these addon's are not loading up or installing and they are all the latest. 
Can someone please help me resolve this issue? My goal is to have the basics on essentials along with per world (multiverse-core) permissions and usergroups so I can add permissions per world. I don't want to have to run an outdated server version tho to achieve this. I've seen other server running this all find on 1.12 but I get these errors in console and need some help please? I also noticed there is no group manager for this, can i please get some help with that so I can set permissions per world based off of the usergroups? aka Player, Builder, Contributor, Admin, Moderator, and so on.

**Comment by mdcfe** [comment]
You need to update all the EssentialsX jars to the same version - you can use `/version <name>` (`/version EssentialsX`, `/version EssentialsXChat` etc.) to check the version of each jar. The latest builds can be downloaded from the [build server](https://ci.drtshock.net/job/EssentialsX).

You should be able to comfortably use Multiverse-Core on 1.12.1 without any issues.

Regarding permissions, [GroupManager is not supported as it is an outdated plugin](https://github.com/drtshock/Essentials/wiki/Common-Issues#i-need-help-with-groupmanager--wheres-the-updated-groupmanager). We recommend you use LuckPerms instead as it's actively maintained and supported. You can find the EssentialsX permissions through the [Essentials wiki](http://wiki.mc-ess.net/wiki/Command_Reference/Perm) and [EssentialsX wiki](https://github.com/drtshock/Essentials/wiki).

**Comment by CodedMindsorg** [comment]
Hmm, Did a reupload of same thing and fixed. Maybe it was a corrupt upload. Thanks.
