### ISSUE TITLE
Keep Inventry

### ISSUE THREAD

**Issue by FatmanC** [EssentialsX/Essentials#1506]
EssentialsX version (`/essentials`): 
EssentialsX 2.0.1-b488

Server software (`/version`): 112

EssentialsX config (if applicable): 

Trying to find an option to allow keep inventry, when players die. I cannot find a command or anything that allows this, apart from /gamerule which i have tried and it does not work. 
Could a new command or feature be added to allow this? Or if it is something i am missing, please tell me how to enable this. 
I have enabled keepexp... just i dont know how to keep items in inventry.

Thankyou

**Comment by LaxWasHere** [comment]
This seems to be out of essentials' scope. 

If you want to enable the gamerule, use the command '/gamerule keepInventory true'

or use the countless other plugins that exist [at](https://www.spigotmc.org/resources/)

**Comment by FatmanC** [comment]
the gamerule command i have already tried... both in chat and from console... neither worked. I will install a plugin for now... but i had it set up before i did something stupid and reset the server, which deleted the config files. Now i cant find the place where i set it up before.
