### ISSUE TITLE
Pipes deleting items

### ISSUE THREAD

**Issue by asawula** [EssentialsX/Essentials#1507]
Essentials reloaded 2.0.1-b525 with Spigot 1.12.1 creates undesired functionality with pipes.
Items in the input chest disappear and do not appear in the output chest.

Working Configuration:
Essentials reloaded 2.0.1-b525
CraftBukkit version git-Spigot-cd6ba67-f7d14f1 (MC: 1.12) (Implementing API version 1.12.-R0.1-SNAPSHOT)

Not Working:
Essentials reloaded 2.0.1-b525
Spigot MC:1.12.1 (Sorry I don't have the /version command output for that server at the moment, I will try to add it later)

First time submitting, please advise if more/better information is required.

**Comment by SupaHam** [comment]
What are pipes?
Please Pastebin your server log.

Steps:

1. Open `logs` directory in server directory.
1. Find and open a file called `latest.log`.
1. Go to [www.pastebin.com](http://pastebin.com).
1. Copy all `latest.log` contents and paste into the big text area.
1. Copy & paste the URL in your browser into a reply here.

Please repeat the steps above for your `Essentials/config.yml`.

**Comment by asawula** [comment]
So sorry, the bug is with Craftbook, not Essentials. This is embarassing...
