### ISSUE TITLE
Wither, iron and snow golem build

### ISSUE THREAD

**Issue by JohOply** [EssentialsX/Essentials#1508]
Hello everyone,

I have a question. I want to know if EssentialsProtect allow to disable wither, iron and snow golem build (by player & dispenser), and able to add a permission for each type to allow autorized players to build them? (or any way to reach the same goal maybe?)

I searched a lot, but I didn't find any up to date plugin. I discuss with a dev who told me it could possible, maybe, with Essentials, but I didn't find any way in wikis

Cheers!

NB: English is not my native language, so if something is not clear please tell me!

**Comment by mdcfe** [comment]
I don't think EssentialsProtect ever supported blocking build events specifically, although you can disable *all* wither and iron/snow golem spawning using `protect.prevent.spawn.wither`, `protect.prevent.spawn.iron_golem` and `protect.prevent.spawn.snowman` in your [config.yml](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/config.yml#L704).

**Comment by JohOply** [comment]
Thank you for your quick answer! If it could be implemented, I think it could be a great feature :)
