### ISSUE TITLE
/back command not tracked properly

### ISSUE THREAD

**Issue by iArcanex** [EssentialsX/Essentials#1510]
I am experiencing an issue that isn't producing any error logs, but is evident within gameplay. The /back command isn't registering the previous locations properly, especially upon death. I have enabled the listener for the teleport event, and that hasn't changed the issue. Players who die in one area would only return to an area previously marked by teleportation. All in all, it doesn't seem death is registered to be tracked. Apologies I have no logs, but this is the best I can explain from an in-game standpoint.

EssentialsX version (`/essentials`): 
Build 526 Revision: a049a03faae482edbba31b88c379574ff623a84e

Server software (`/version`): 
Paper version git-Paper-1194 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

EssentialsX config (if applicable): 
https://gist.github.com/iArcanex/e7f2b622453a9c824f2659f6cb4e2ab2

**Comment by mdcfe** [comment]
Which `essentials.back` permissions have been granted?

**Comment by iArcanex** [comment]
Both essentials.back and essentials.back.ondeath were granted.

**Comment by mdcfe** [comment]
Can you run `/essentials debug` then [paste the console output](https://gist.github.com) when `/back` is run and *doesn't* update the last location?

In addition, could you paste the output when a player dies and their last location doesn't get updated?

**Comment by iArcanex** [comment]
Apologies, it seems like our permissions plugin reset due to an issue in parsing the configuration. After validating our perms, the command worked fine (including essentials.back.ondeath). Everything is now functioning as intended. Thank you for the swift responses @md678685.
