### ISSUE TITLE
NPCs showing up in balance rank

### ISSUE THREAD

**Issue by iSkitzu** [EssentialsX/Essentials#1513]
EssentialsX version (`/essentials`):  https://i.gyazo.com/7902e3243db97b15652a086846d7f5ae.png

Server software (`/version`): https://i.gyazo.com/7902e3243db97b15652a086846d7f5ae.png

EssentialsX config (if applicable):  https://pastebin.com/4xrRuU3H

I was wondering if there is a way to keep npcs from showing up in the balance rank (balancetop) besides switching it to false in the config. For some reason, they still show up in the ladder for a while after reloading, restarting, etc. I redid the entire file & reninstalled both citizens & essentials. 

Then, it suddenly updates after a while. Is this how it's meant to work or am I missing something?

**Comment by iSkitzu** [comment]
https://i.gyazo.com/bcb7f7bc66610a6170ad18b831cd3e39.png
Here's a screenshot of the npcs continuing to show up in the list.

(I also tried deleting the npc uuids in the essential payerdata folder, but they just recreate themselves when I restart the server or reload the plugin.

**Comment by mdcfe** [comment]
As far as I know, `/baltop` caches the results for 2 minutes before recalculating the list.

**Comment by mdcfe** [comment]
The config option seems to be the only way to hide NPCs from the balance ranking. There is no way to hide individual NPCs from the ranking, although you could set their balance to be 0 or negative to make them appear at the bottom if desired.
