### ISSUE TITLE
/firework is broken (Nothing in console nothing ingame)

### ISSUE THREAD

**Issue by AmazedMender16** [EssentialsX/Essentials#1515]
/firework is broken it doesnt give any output in console or either ingame! waiting for a fix!

EssentialsX version (`/essentials`):  Latest

Server software (`/version`):  Last 1.11.2 build (Spigot)

EssentialsX config (if applicable):  Default config

**Comment by mdcfe** [comment]
* Please run `/version` and `/essentials` and paste the output here.
* Could you give an example of the arguments are you passing to `/firework` that don't work?
* Are you using a custom `messages.properties` file? Does it contain `holdFirework`?

**Comment by AmazedMender16** [comment]
/firework shape:ball As example
Yes it has holdfirework!.
holdFirework=\u00a78» \u00a7c\u00a7lYou must be holding a firework to add effects.

http://prntscr.com/gfyvy7

**Comment by AmazedMender16** [comment]
@md678685 Please can u look into this

**Comment by smmmadden** [comment]
I can confirm that it works with Spigot 1.12.1 and Essentials build 529.  Note that the message is correct, you do need to be holding a rocket in order to "set the parameters of it".  Perhaps this page will [**help**](https://www.minetime.com/threads/firework-help-please.27518/).

**Comment by AmazedMender16** [comment]
And i can confirm it doesnt work on 1.11.2

**Comment by mdcfe** [comment]
If you set a colour with `color:<color>`, does the command work? If not, could you upload a screenshot after running the command?

**Comment by smmmadden** [comment]
"and" while holding a firework rocket :-)
/firework shape:ball color:red,blue,green

**Comment by mdcfe** [comment]
@smmmadden AmazedMender pasted the unformatted `holdFirework` line from their messages.properties just to check that that particular message wasn't missing from their install. It was not from a log or command output.

@AmazedMender16 Just to clarify, as far as I can tell from the `/firework` class, fireworks don't have a default colour but have a default shape, so you should always need to specify the colour but the shape should be optional.

**Comment by AmazedMender16** [comment]
@md678685 @smmmadden Whenever im doing /firework shape:ball color:red,blue,green it doesnt change the firework in holding but instantly send one from the location im standing..

**Comment by mdcfe** [comment]
Could you paste your plugins list so we can check if there is a conflict?

**Comment by AmazedMender16** [comment]
@md678685 its a clean install with only essentialsx and vault

**Comment by mdcfe** [comment]
@AmazedMender16 Is this still an issue?

**Comment by mdcfe** [comment]
Closing due to lack of response; if this is still a problem, please reopen the issue.
