### ISSUE TITLE
/tppos x y z <world> doesn't check for world-teleport-permission

### ISSUE THREAD

**Issue by Platinteufel** [EssentialsX/Essentials#1516]
Latest EssX, latest Paper 1.12
There are some worlds for that my players don't have the permission to teleport into with /tp, /tpa, .., for example my adventure world.
Now i figured out that a player was able to avoid this restriction by typing /tppos 100 100 100 adventure, so maybe it's possible that /tppos doesn't check for per-world-teleportation permissions?

**Comment by Platinteufel** [comment]
This world-teleporting feature was added in https://github.com/drtshock/Essentials/commit/3283b8c0a3e29454156175b97108d6d83f56478f
Seems like a check like this (from `/tp` command) is missing here.

```
if (user.getWorld() != player.getWorld() && ess.getSettings().isWorldTeleportPermissions() && !user.isAuthorized("essentials.worlds." + player.getWorld().getName())) {
throw new Exception(tl("noPerm", "essentials.worlds." + player.getWorld().getName()));
```

**Comment by Platinteufel** [comment]
Any news here? :/

**Comment by Platinteufel** [comment]
Would be awesome if this could be fixed one day. @md678685  :/

**Comment by DrewAMitchell** [comment]
@md678685 Yay! It's merged! Close please?
