### ISSUE TITLE
[Server] WARN handleDisconnection() called twice

### ISSUE THREAD

**Issue by FrankHeijden** [EssentialsX/Essentials#1519]
EssentialsX version (`/essentials`): 
2.0.1-b523
Server software (`/version`): 
CraftBukkit version git-Spigot-65e8124-79e55b6 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)
EssentialsX config (if applicable): 
-

`27.08 22:08:56 [Server] WARN handleDisconnection() called twice` error when somebody gets kicked after being X minutes AFK.

**Comment by mdcfe** [comment]
As far as I'm aware, this is a long-standing Spigot issue that's out of our control. You can ignore the message unless it has other side effects.
