### ISSUE TITLE
/baltop

### ISSUE THREAD

**Issue by FrankHeijden** [EssentialsX/Essentials#1523]
Heya,

Is there a possibility of not removing players in cache? `/baltop` for example, sometimes players are white and sometimes they have their displayname. I'd to see a feature which enables to show all players' displayname OR all white and not 50/50.

Also, i didnt see a part in the translations for the numbers in `/baltop`. 

Hope you can help me out!
Frank

**Comment by mdcfe** [comment]
Formatting for currency was added in a more recent version - you may need to update EssentialsX and add the new entries to your `config.yml`.

Regarding the first, I don't think we should be caching all the player data in memory. For servers with lots of players, this would be an unnecessary waste of memory and a large amount of the data is unlikely to be used elsewhere before the server would need to be restarted.

**Comment by FrankHeijden** [comment]
And saving it to flatfile? Just their displayname in their uuid.yml
