### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1524]
EssentialsX version (`/essentials`):  2.0.1-b488

Server software (`/version`): git-Spigot-edd0396-20ab5d3 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**Comment by mdcfe** [comment]
Please post the stack trace from your console log on [Gist](https://gist.github.com).

**Comment by ghost** [comment]
https://gist.github.com/xIPad3Zockerx/299526896d16f413bedbd303a4293080

**Comment by mdcfe** [comment]
This has been fixed in more recent builds. Download the latest build from the [CI server](https://ci.drtshock.net/job/EssentialsX/lastSuccessfulBuild).
