### ISSUE TITLE
Spawnerconvert in 1.12.1

### ISSUE THREAD

**Issue by Platinteufel** [EssentialsX/Essentials#1525]
EssX build 527
git-Paper-1196 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

Since I've **updated** my server to **Paper 1.12.1** yesterday spawnerconvert doesn't work for my players anymore, although they have the `essentials.spawnerconvert.*` permission.
If I test it with OP permissions it still works fine.
**Update: I have to be OP AND Gamemode 1 to use spawnerconvert in 1.12.1.**

I just double checked it on my testserver as a normal player with spawnerconvert permissions. After downgrading to Paper 1.12 it works fine again, so it's definitely related to the new Minecraft/Paper version.

I would be very pleased if you could test it on your end too.
Thank you in advance!

**Comment by Platinteufel** [comment]
Seems to be related to this patch: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/19507baf8b7903427bc3efab7118de6e7c1c931e

**Comment by Platinteufel** [comment]
Just to make it clear: The command `/spawner <mobtype>` still works as intended. 
But if I take a specific spawner e.g. with `/i mobspawner:52` (spider spawner) EssX doesn't convert it anymore and I'm only able to place pig spawners.

**Comment by Phoenix616** [comment]
As of the TileEntity rework blockstates need to be updated to apply their state to the block which the spawner convert mechanism does not do as seen [here](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/EssentialsBlockListener.java#L42).

**Comment by Kakifrucht** [comment]
Having the same issue. It works fine for operators in gamemode1 however.

**Comment by PhanaticD** [comment]
having same problem

**Comment by CDAGaming** [comment]
Just Tested #1536 but it did not solve the issue unfortunatly

**Comment by PhanaticD** [comment]
it did fix it for me, make sure you give them essentials.spawnerconvert and essentials.spawnerconvert.*

**Comment by CDAGaming** [comment]
Ah, forgot that part, will try again shortly

**Comment by CDAGaming** [comment]
Yup, works now

**Comment by Platinteufel** [comment]
Thanks! Could you merge it please? :)

**Comment by Platinteufel** [comment]
@md678685 ?

**Comment by mdcfe** [comment]
PR #1536 has been merged, which should fix the issue - you can get the latest version of EssentialsX from the [build server](https://ci.drtshock.net/job/EssentialsX/lastSuccessfulBuild).
