### ISSUE TITLE
Essentials Eco into a separated module

### ISSUE THREAD

**Issue by EverNife** [EssentialsX/Essentials#1526]
It would be really nice to have an Essentials Eco into a separated module for people who search for a good eco plugin.

To be honest, no other plugins out there are as good as essentials eco :/

**Comment by mdcfe** [comment]
I think the nature of how Essentials was built means that it would be awkward to make EssentialsEco an optional module, but it could in theory be separated into its own plugin (though it currently relies on EssentialsX's data storage as far as I know). It's unlikely that EssentialsX will ship EssentialsEco independently of the main jar, however.

**Comment by mdcfe** [comment]
Correction: Essentials' economy is entirely baked in to the Essentials userdata, so it wouldn't make sense to separate them - you'd end up with an entirely new plugin, at which point you might as well have just switched to an existing dedicated economy plugin.

Closing this issue as it's not planned nor would it make sense.

**Comment by EverNife** [comment]
👍
