### ISSUE TITLE
Date timestamp in mails.

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#1527]
Is it possible to implement a date timestamp for mails sent in-game? That way if you come back from an extended break, you know when exactly someone sent you that mail message?

**Comment by mdcfe** [comment]
This would facilitate #963, though we'd need to add an upgrade to change the mail format in the userdata, as well as implementing customisable date formatting (I don't think EssentialsX has anything related to date formatting at the moment, and different servers may prefer different date formats).

**Comment by jpeaceau** [comment]
@md678685 if different servers prefer different date formats, let them format it themselves with placeholders like %day% %month% %weekday% %minute% %hour% %second% %year%
