### ISSUE TITLE
Spawners Turning into Default Pig Ones

### ISSUE THREAD

**Issue by Tomographix** [EssentialsX/Essentials#1529]
EssentialsX version: 2.0.1-b528

Server software: Paper Spigot 1192

Problem: Placing a spawner turns them into a pig one even if they have the permission node spawner.place.all

I am spawning in the spawners with the following command: /give {name} mob_spawner:59 1
For example: /give Tomographix mob_spawner:59 1 name:&1&lCave_Spider_Spawner

This happens for all spawner types. As an OP I am still able to place the spawner and not have it turn into a pig.

**Comment by mdcfe** [comment]
Players need the `essentials.spawnerconvert.MOB` permission for each mob spawner you want them to be able to place. There is also a related bug, however - see #1525.

**Comment by grzegorzekkk** [comment]
My players have that permission but still they can't change type of spawner by /spawner command.

**Comment by mdcfe** [comment]
This should now be fixed - grab the latest build from the [CI server](https://ci.drtshock.net/job/EssentialsX/lastSuccessfulBuild).
