### ISSUE TITLE
Permission for modified spawner?

### ISSUE THREAD

**Issue by Platinteufel** [EssentialsX/Essentials#153]
If my players place modified spawner, they will change to pig spawner. After adding essentials.\* this didn't happen any longer. Could you tell me the exact permission node?

**Comment by Platinteufel** [comment]
Got it, essentials.spawnerconvert.mobtype.
Maybe you could make a list with essx perms.

**Comment by Kakifrucht** [comment]
This is a standard permission node that was already there when the original Essentials implemented it, so you could just check their command reference? http://wiki.ess3.net/wiki/Command_Reference

Just realize that they didn't put it in the list.
