### ISSUE TITLE
Event issue

### ISSUE THREAD

**Issue by QueenKisaki** [EssentialsX/Essentials#1532]
EssentialsX version EssentialsX 2.0.1

Server software (`/version`): 1.12.1

Paste Error: https://pastebin.com/gVnXj77k

Not sure what that is telling me but I recently updated server from 1.11.2 then that keeps happening. Thanks.

**Comment by mdcfe** [comment]
Update EssentialsX from [Jenkins](https://ci.drtshock.net/EssentialsX/lastSuccessfulBuild).
