### ISSUE TITLE
Command /potion not working

### ISSUE THREAD

**Issue by Blamo27** [EssentialsX/Essentials#1533]
EssentialsX version (`/essentials`):  2.0.1-b528

Server software (`/version`): 1.12-R0.1 (Paper-1196)

EssentialsX config (if applicable): x

Hello,

There is an issue with the /potion command. It doesn't seem to work with splash or lingering potions, it only works with normal potions (the command doesn't recognize that you are holding a potion if you are holding a splash or lingering one).

Thank you for looking into this.

**Comment by mdcfe** [comment]
Duplicate of #1166.
