### ISSUE TITLE
CratesPlus keys do not work in Kits

### ISSUE THREAD

**Issue by svnxd** [EssentialsX/Essentials#1535]
Title basically says it all. Put a CratesPlus key in a kit and it just makes it improperly defined.

**Comment by mdcfe** [comment]
EssentialsX does not (as far as I am aware) support data on items in kits that is specific to other plugins. You may want to use another kits plugin that explicitly supports the CratesPlus plugin.

**Comment by svnxd** [comment]
Hmm 🤔, I'll look elsewhere. Would a plugin something like item on first join work?
