### ISSUE TITLE
Kits does not work correctly

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1538]
**EssentialsX version (`/essentials`):** 528
**Server software (`/version`):** git-Paper-1104 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
**EssentialsX config (if applicable):**  default

I saved inventory with /kitcreate <name> <duration> and it does not work correctly. 
Video: https://youtu.be/WflkTHyp6tg

I'm using KitPreview plugin but it doesn't matter, It's Essentials problem.

Kit: https://gist.github.com/anonymous/7daff01e0b0201bea69fce7fffbabdd3

**Comment by mdcfe** [comment]
Please paste your config on [Gist](https://gist.github.com). Kits are stored in the config so we can't help you unless you paste it.

**Comment by ghost** [comment]
I pasted it, check last link in my post. I'm using default config, so you can generate yourself. There is not problem with bad cofiguration file, there is a problem with saving of items. It is outdated.

**Comment by mdcfe** [comment]
EssentialsX does not save kits automatically as this would delete the config comments.

Please edit your config to include the kit generated by `/createkit`, then restart the server.
