### ISSUE TITLE
Want to change the nickname command to support Chinese.

### ISSUE THREAD

**Issue by hou0122** [EssentialsX/Essentials#1539]
Want to change the nickname command to support Chinese(Asia Language).
 use this **" ^[\u2E80-\u9FFF_a-zA-Z0-9]+$ "**

**Comment by mdcfe** [comment]
Related: #1630

**Comment by DoNotSpamPls** [comment]
You can add the `essentials.nick.allowunsafe` permission to allow non-alphanumeric characters in nicknames (including Chinese characters). This version works with EssentialsX version 2.16.0 or newer

**Comment by mdcfe** [comment]
@hou0122 If you have any further questions, let us know and I'll reopen this.
