### ISSUE TITLE
Money bug

### ISSUE THREAD

**Issue by franxyk** [EssentialsX/Essentials#154]
Please this is very annoying Glitch's sake repair it
https://www.spigotmc.org/threads/essentials-1-8-baltop-players-duplicating-with-0.40920/
http://www.minecraftforum.net/forum...th-essentials-and-uuid-1-7-9-1-8?cookieTest=1

**Comment by vemacs** [comment]
Don't run a cracked server.

**Comment by franxyk** [comment]
I need to run it on crack

**Comment by vemacs** [comment]
Don't steal
