### ISSUE TITLE
Kits are outdated 

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1540]
I dont understand why someone closed my issue. So Im pasting it again.

EssentialsX version (/essentials): 528
Server software (/version): git-Paper-1104 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
EssentialsX config (if applicable): default

I saved inventory with /kitcreate and it does not work correctly.
Video: https://youtu.be/WflkTHyp6tg

I'm using KitPreview plugin but it doesn't matter, It's Essentials problem.

Kit: https://gist.github.com/anonymous/7daff01e0b0201bea69fce7fffbabdd3

**Comment by mdcfe** [comment]
As stated before, you *must* copy your kit from the given link to your config.yml under `kits:`. If you've done this, please post your full config file including the kit.

**Comment by ghost** [comment]
No. I'm not reporting any issue with config. Essentials has outdated kit saving. It does not support some items like spawning eggs when I'm trying to save it with command. I used /kitcreate with auto save and /kitcreate with pastebin. I pasted given link under kits: and I have still same problem. You can check last link in my post.
