### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1542]
https://gist.github.com/xIPad3Zockerx/299526896d16f413bedbd303a4293080

EssentialsX version (`/essentials`):  2.0.1-b488

Server software (`/version`): git-Spigot-edd0396-20ab5d3 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**Comment by ItzLevvie** [comment]
Please update to the latest [EssentialsX](https://ci.drtshock.net/job/EssentialsX) version.

According to your logs, you're running EssentialsX build 488 while the latest one is build 528.

**Comment by mdcfe** [comment]
This issue is fixed in newer builds - as noted above, please update EssentialsX.
