### ISSUE TITLE
EssentialsX v2.0.1 PlayerInteractEvent error

### ISSUE THREAD

**Issue by TheRealPear** [EssentialsX/Essentials#1543]
`[Error] Could not pass event PlayerInteractEvent to Essentials v2.0.1-b488java.lang.NoSuchMethodError: org.bukkit.entity.Player.getTargetBlock(Ljava/util/HashSet;I)Lorg/bukkit/block/Block; at com.earth2me.essentials.signs.SignPlayerListener.onSignPlayerInteract(SignPlayerListener.java:41) ~[?:?] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor472.execute(Unknown Source) ~[?:?] at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.12.1.jar:git-Paper-1199] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.1.jar:git-Paper-1199] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.1.jar:git-Paper-1199] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[patched_1.12.1.jar:git-Paper-1199] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[patched_1.12.1.jar:git-Paper-1199] at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) ~[patched_1.12.1.jar:git-Paper-1199] at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202) ~[patched_1.12.1.jar:git-Paper-1199] at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198) ~[patched_1.12.1.jar:git-Paper-1199] at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:987) ~[patched_1.12.1.jar:git-Paper-1199] at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) ~[patched_1.12.1.jar:git-Paper-1199] at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.12.1.jar:git-Paper-1199] at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.1.jar:git-Paper-1199] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102] at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.1.jar:git-Paper-1199] at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.1.jar:git-Paper-1199] at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) [patched_1.12.1.jar:git-Paper-1199] at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.1.jar:git-Paper-1199] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.1.jar:git-Paper-1199] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]`

EssentialsX version (`/essentials`): v2.0.1 (already tried reinstalling)

Server software (`/version`): PaperSpigot @ 1.12.1

EssentialsX config (if applicable):

**Comment by mdcfe** [comment]
This issue is fixed in newer builds - please [update EssentialsX to the latest version](https://ci.drtshock.net/job/EssentialsX/lastSuccessfulBuild).

**Comment by TheRealPear** [comment]
But it's already running the latest build.

**Comment by ItzLevvie** [comment]
You're running build 488, the latest one is build 528.
