### ISSUE TITLE
Turn On and Off PVP In-Game

### ISSUE THREAD

**Issue by Techno3600** [EssentialsX/Essentials#1544]
Hello,

I was wondering if we could add an option where if the command _/pvp [player]_ was ran, it could globally toggle:

- Global PvP damage cancelled
- Blocks Projectiles (arrows, snowballs, fireballs, rods)
- Poisonous potion damage
- Damage delt by lava buckets
- TNT placed by player
- Any other damage done by players

And if _/damage [player]_ was ran, it would stop **all** damage coming to players. This includes:

- Global PvP cancelled
- Blocks Projectiles (arrows, snowballs, fireballs, rods)
- Poisonous potion damage
- Any other damage done by players
- Fall Damage
- Lava/Water Damage
- Weather Damage
- Hunger Damage
- Damage by mobs
- Etc.
 
Also, if someone's player name was inserted into the _/pvp [player]_ argument, then it would disable pvp for a specific player.

Hope you guys like this idea!
Techno3600

**Comment by LaxWasHere** [comment]
My opinion on this suggestion is that it is out of the scope of 'Essentials'.  WorldGuard maybe but not Essentials..

**Comment by SupaHam** [comment]
Although it's potentially useful for some, it's not useful for most cases and that goes against the essentials for everyone.
