### ISSUE TITLE
Bad Gateway Error on Build CI Server (Again)

### ISSUE THREAD

**Issue by CDAGaming** [EssentialsX/Essentials#1545]
Unable to get builds from Build CI, cloudflare reporting bat gateway

**Comment by SaitDev** [comment]
@SupaHam save us plz. I havent downloaded other essentialsx like antibuild, chat...

**Comment by smmmadden** [comment]
I can confirm the same results from USA - South East
Error 502 Ray ID: 39dcde78781e386a • 2017-09-13 17:36:29 UTC
Bad gateway

**Comment by CDAGaming** [comment]
Changed Title to be more clearer
(Save us @SupaHam 👍 )

**Comment by CDAGaming** [comment]
@smmmadden @SaitDev Just checked, it seems to now be up again 👍 
Please confirm if its working, as if so, ill close this issue as solved

**Comment by smmmadden** [comment]
Confirmed - I also have access to it. 👍

**Comment by SaitDev** [comment]
Yes, its up now

**Comment by CDAGaming** [comment]
Marked as Solved...for now

**Comment by SupaHam** [comment]
Sorry for late reply. For future reference we have two mirrors, https://ci.akpmakes.tech/job/EssentialsX/ and http://ci.ender.zone/job/EssentialsX/

**Comment by CDAGaming** [comment]
Thanks, SupaHam.
