### ISSUE TITLE
Lag Notice Slow Economy Response ?

### ISSUE THREAD

**Issue by bertek41** [EssentialsX/Essentials#1546]
EssentialsX version: 2.0.1-b528 (And same version for Chat and Spawn)

Server software: This server is running CraftBukkit version git-PaperSpigot-"8b18730" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Error: [22:55:34 INFO]: [Essentials] Lag Notice - Slow Economy Response - Request took
over 299.994ms!

**Comment by mdcfe** [comment]
Could you paste your list of plugins from `/plugins`, as well as your Vault version from `/version Vault`?

**Comment by Darthmineboy** [comment]
Issue is in your Economy plugin. Unless that happens to be EssentialsEco, the issue should not be reported in this repo.

**Comment by bertek41** [comment]
Vault version: 1.5.6-b49 using essentials economy

**Comment by mdcfe** [comment]
Please post the output of `/plugins` and generare a Spigot timings report.

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to reopen the issue.
