### ISSUE TITLE
Potions and /createkit

### ISSUE THREAD

**Issue by Armannnnnn** [EssentialsX/Essentials#155]
Say I create a kit using the /createkit command with splash instant health II potions and splash regeneration II potions. When I now actually use the kit, the potions are just regular drinkable instant health I and regular drinkable regeneration I.

EssentialsX Version: 2.0.1-b177
Spigot Version: http://prntscr.com/85blv8

**Comment by mdcfe** [comment]
Old issue, but this was heavily improved on 1.13 in EssentialsX 2.16.0 - can anyone confirm if this is still an issue?

**Comment by pop4959** [comment]
Closing in favor of #2867 as it appears trying to reproduce this bug in current versions no longer works the same way (instead you receive the error message "item is not a potion").
