### ISSUE TITLE
Thor and other lightning commands error out when no player selected 

### ISSUE THREAD

**Issue by stevewall85** [EssentialsX/Essentials#1551]
While on the server and using the smite commands thor and lightning with no player selected it errors out in the below logs. I have discovered that if i add a players name they will be smiten and no error to be displayed. Back on the original essentials even using just thor would make the lightning effects which was pretty cool. So i am posting this as to give info to stop the error but if the command did give the effect with no player selected thats a bonus i love these commands.

Further example /thor   - error
                          /thor player   - works!

EssentialsX version (`/essentials`): 
2.0.1-b488

Server software (`/version`): 
This server is running CraftBukkit version git-Spigot-da42974-8f47214 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

EssentialsX config (if applicable): 
https://gist.github.com/stevewall85/2743aa48b0840b2b15cc893deb2b0f33

https://gist.github.com/anonymous/024c430a5b745d7d58468cde1ef81468   - Console Error Log using /thor

https://gist.github.com/stevewall85/6da4acae8a6d0f6c290187b8eeae78e2  - Console Error Log using /lightning

**Comment by LaxWasHere** [comment]
You are running an outdated version of EssentialsX, please download the latest version at https://ci.drtshock.net/job/EssentialsX/ and close the issue if the problem is fixed.

**Comment by stevewall85** [comment]
I updated to 529 from your link and it worked! i guess i was on an older fork. Thank you for your quick response your awesome keep up the good work!
