### ISSUE TITLE
FEATURE REQUEST: Change playtime message in message.properties

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1554]
EssentialsX version (`/essentials`): 
Essentials 2.0.1-b526

Server software (`/version`):
1.12.1-R0.1-SNAPSHOT

Add the ability to change the Playtime message (can be seen with /whois) in message.properties
You are able to change all the other /whois messages but not UUID or Playtime

**Comment by mdcfe** [comment]
Update your messages.properties by downloading a new copy or adding the missing strings. These messages were added a few months ago, so if you have custom language files from an earlier version of EssentialsX, these particular messages won't be present.

In future, please open one issue unless your issues are significantly different from each other. I've closed #1552 and #1553 as this also addresses both of them.
