### ISSUE TITLE
Error with the / me command

### ISSUE THREAD

**Issue by Mundo-Minecraft** [EssentialsX/Essentials#1556]
Hello, on my server when users write / me "message" can only be read by users who have the essentials.chat.spy permission. But I do not want to give that permission because they also read the local messages.
Is this a bug? or is there any way to separate this? I have not found a solution, I use the last compilation of spigot and essentialsx.

Thank you.

**Comment by mdcfe** [comment]
If you have a chat radius set, `/me` messages should only be broadcast within the set radius. Currently there isn't a way to change this behaviour in EssentialsX aside from disabling the local chat radius, though you could [alias the `me` command to `minecraft:me`](https://github.com/drtshock/Essentials/wiki/Common-Issues#essentialsx-overrides-a-command-from-spigot-or-another-plugin).

**Comment by Mundo-Minecraft** [comment]
ok, I did not know this, since I've been using essentialsx for two weeks now. In the classic essentials it is separated, the / me is read all over the world even if it puts a radius of action to the local chat.
Then I leave it as a suggestion.

Thank you.
