### ISSUE TITLE
economy command alias

### ISSUE THREAD

**Issue by madtomic** [EssentialsX/Essentials#1558]
Any way to set new alias?

balance
eco

I need it to be different for essentials. I know about the other alias: bal, money and economy. I still need something else for essentials because they are all used by another plugin.

Thanks

**Comment by LaxWasHere** [comment]
Essentials gives other plugins priority over registering commands, if the essentials /eco or /balance still works then the other plugin did not register it.

**Comment by madtomic** [comment]
I have no way to access economy in essentials. That is why I'm asking here. I need someone to help either create it with new command or add more alias.

**Comment by LaxWasHere** [comment]
You can append `e` or `essentials:` to any ess command and it will use the essentialsx command.
/etop
/ebal
/eeco
/essentials:top
/essentials:bal
/essentials:eco

**Comment by mdcfe** [comment]
If you want to permanently override the other plugin's commands, see [this wiki page](https://github.com/drtshock/Essentials/wiki/Common-Issues#tab-completion-doesnt-work-for-commands-that-override-an-essentialsx-command).

**Comment by madtomic** [comment]
Thank you both for help. I will give this a try later.

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to reopen the issue.
