### ISSUE TITLE
essentials.* does not grant gamemode changing permissions

### ISSUE THREAD

**Issue by Kakifrucht** [EssentialsX/Essentials#156]
What the title says, using /gm 0,1,2,3 does only work if the permission essentials.gamemode.type has been specifically assigned.

**Comment by klausenbusk** [comment]
Is there any update/explanation of why this happens?

**Comment by drtshock** [comment]
Because of the newish way to grant each gamemode permission individually.

**Comment by drtshock** [comment]
Fixed
