### ISSUE TITLE
[Idea/Enhancement] Mail Should Support Color Codes

### ISSUE THREAD

**Issue by Techno3600** [EssentialsX/Essentials#1560]
Hey Guys,

In the next update, it would be nice if we were able to use color codes (&4, &3, &b) in our mail messages.

Thanks
Techno

**Comment by Tsuser1** [comment]
Already implemented..?

**Comment by Techno3600** [comment]
Well then, how do you enable it?

**Comment by SupaHam** [comment]
This has been introduced in 665229b. You can grab the feature from [build 540](https://ci.drtshock.net/job/EssentialsX/) on the CI server.

Thanks for your suggestion.

**Comment by mdcfe** [comment]
The latest build can be found [here](https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild).

**Comment by Techno3600** [comment]
Awesome guys, thanks so much!!!
