### ISSUE TITLE
[Idea/Enhancement] Teleport to Offline Players

### ISSUE THREAD

**Issue by Techno3600** [EssentialsX/Essentials#1561]
Hey Guys,

In the next update could their be a feature which allows:

- Teleporting to Offline Players
- Teleporting Offline Players To Yourself (so when they log in next time, they log in where you set them)

Thanks
Techno3600

**Comment by kalebmmm** [comment]
I forgot to say something but if you don't mind me picking this up... https://github.com/kalebmmm/Essentials/tree/tpoffline

Happy Hacktoberfest!

**Comment by Techno3600** [comment]
Does the tpoffline file work?

**Comment by mdcfe** [comment]
@kalebmmm Feel free to PR your command to EssentialsX.

**Comment by TomLewis** [comment]
Please add this.

**Comment by mdcfe** [comment]
This was implemented in #2505 and is now available in the latest dev builds.

**Comment by Azim** [comment]
So it is still impossible to teleport offline players?

**Comment by pop4959** [comment]
no, read the issue that MD linked

**Comment by Azim** [comment]
> no, read the issue that MD linked

@pop4959 i might be blind, but i dont see a single word about teleporting offline players - only teleporting **to** offline players is mentioned
