### ISSUE TITLE
[Enhancement] Streamline TP Permissions

### ISSUE THREAD

**Issue by Techno3600** [EssentialsX/Essentials#1562]
Hello,

Currently, with TP Perms, it is very hard to just give one player every permission regarding tp, I find it very difficult.

It would be easier if **essentials.tp.*** gave someone every possible /tp(a)(o)(here)(all)(accept)(deny)(etc.) command.

Thanks
Techno

**Comment by mdcfe** [comment]
This is unlikely to be changed, considering that moving permissions would silently break lots of existing permissions setups, while aliases would make permissions setups harder to debug.

In addition, if you're hoping to make setting up permissions quicker and easier, you're not going to get far. Permissions are time consuming for a reason - you should be making sure players and groups are allowed to do exactly what you want them to be able to do, no less and no more.
