### ISSUE TITLE
Question - Admins are able to kill Owners

### ISSUE THREAD

**Issue by Sonic8608** [EssentialsX/Essentials#1563]
EssentialsX version (`/essentials`): 

Server software (`/version`): 

EssentialsX config (if applicable): 

[config.txt](https://github.com/drtshock/Essentials/files/1319626/config.txt)

**Comment by Kakifrucht** [comment]
That is an error how?
What does this have to do with Essentials exactly?
"Admin" and "Owner" are nothing defined anywhere at all.

**Comment by Sonic8608** [comment]
I don't know how to prevent admins to stop killing the owner and which node to put in
