### ISSUE TITLE
how to prevent admins from killing owners? [Question]

### ISSUE THREAD

**Issue by Sonic8608** [EssentialsX/Essentials#1564]
EssentialsX version (`/essentials`): 

Server software (`/version`): 

EssentialsX config (if applicable):

**Comment by LaxWasHere** [comment]
It's more of a statement.

**Comment by mdcfe** [comment]
Don't give them perms if you're not happy with how they use them? We can't tell you how to run your server.

**Comment by Sonic8608** [comment]
I added the permission node that prevents the owner from being killed but even still you can still kill the owner for some odd reason

**Comment by mdcfe** [comment]
If you want a group to not be able to bypass the exemptions, make sure they don't have `essentials.kill.force` and that the exempt group has `essentials.kill.exempt`. If this doesn't solve the issue, please post the groups from your permissions config on [Gist](https://gist.github.com).

**Comment by mdcfe** [comment]
Closing due to lack of a response.
