### ISSUE TITLE
Users can't set more than 3 homes when they have permission for 4

### ISSUE THREAD

**Issue by Electromaster232** [EssentialsX/Essentials#1568]
EssentialsX version (`/essentials`): 
2.0.1-b483.
Server software (`/version`): 
CraftBukkit version git-Spigot-7754231-9a1f5ee

I have a group who has permission to set 4 homes, however all users report only being able to set 3. There is no logs or errors.

**Comment by mdcfe** [comment]
Could you paste your config on [Gist](https://gist.github.com), as well as your permissions config for that group?

**Comment by Electromaster232** [comment]
https://gist.github.com/Electromaster232/a5d0026bcae48f78b2aec6d825d997d2     Config
https://gist.github.com/Electromaster232/230648a5d67d32a071d20f5c4c4868ed      Permissions
@md678685

**Comment by mdcfe** [comment]
To change the home limit, you need to:
* Define a home limit with a name under [`sethome-multiple`](https://gist.github.com/Electromaster232/a5d0026bcae48f78b2aec6d825d997d2#file-config-yml-L510).
* Give the permission `essentials.sethome.multiple.[name]` where `[name]` is the name of the limit in your config.

For example, if you were to add a limit called `hello`, you would give the permission `essentials.sethome.multiple.hello`.

**Comment by Electromaster232** [comment]
thnx, it works now!
