### ISSUE TITLE
Spawning custom shields is broken using /give

### ISSUE THREAD

**Issue by malonnnn** [EssentialsX/Essentials#1569]
`/give <player> minecraft:shield 1 durability:3 mending:1 basecolor:14188339 HALF_HORIZONTAL:10040115 HALF_HORIZONTAL_MIRROR:10040115 CROSS:3361970 STRIPE_CENTER:3361970 STRIPE_MIDDLE:3361970 FLOWER:16777215 name:&4C&9apt&fain_&4A&9mer&4ica's_&9Shield
`
That above code used to give a shield. Now it only reports "Error: null" in CHAT, not console. There is no console error.

EssentialsX version (`/essentials`): 
[23:57:33 INFO]: CONSOLE issued server command: /essentials ver
[23:57:33 INFO]: [Essentials] Using locale messages_EN_properties
[23:57:33 INFO]: [Essentials] Using Paper 1.12+ ServerListPingEvent methods
[23:57:33 INFO]: Essentials reloaded 2.0.1-b530.

Server software (`/version`): 
[23:57:55 INFO]: This server is running Paper version git-Paper-1220 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[23:57:55 INFO]: Checking version, please wait...
[23:57:55 INFO]: You are running the latest version

EssentialsX config (if applicable):

**Comment by malonnnn** [comment]
Anyone? This is important for me

**Comment by mdcfe** [comment]
Looks like a change in 1.12.2, but I haven't had time to take a look at this yet.

**Comment by malonnnn** [comment]
@md678685 

Thank you for acknowledging. Do you think you'll have time to check it sometime in Octoboer?

**Comment by malonnnn** [comment]
anyone have time to check this? this is quite important for my server

**Comment by malonnnn** [comment]
boop :)

**Comment by malonnnn** [comment]
Fixed it, the world of color changed color numbers, just needed to update the give command. Left column is the old numbers, right column is the new numbers.

    1644825 	1908001
    10040115 	11546150
    6717235 	6192150
    6704179 	8606770
    3361970 	3949738
    8339378 	8991416
    5013401 	1481884
    10066329 	10329495
    5000268 	4673362
    15892389 	15961002
    8375321 	8439583
    15066419 	16701501
    6724056 	3847130
    11685080 	13061821
    14188339 	16351261
    16777215 	16383998
