### ISSUE TITLE
[REQUEST] Tempmuting

### ISSUE THREAD

**Issue by Cldfire** [EssentialsX/Essentials#157]
I hate to add to the pile of requests, but it would be great to have access to a /tempmute command. I'd rather not have to install an entirely different plugin just to have that feature.

**Comment by drtshock** [comment]
Or just `/mute <player> <time> <reason>` like it's always been.

**Comment by Cldfire** [comment]
Well.... There's my dose of _feels like an idiot_ for the day...

Thank you very much for telling me that. Either I forgot, or I'm just that dumb.

**Comment by drtshock** [comment]
no problem :)
