### ISSUE TITLE
Villages regeneration is broken

### ISSUE THREAD

**Issue by DmitryRendov** [EssentialsX/Essentials#1571]
There's a wonderful tool **/regen**, it works fine for most cases. But in case of villages it looks funny:
https://www.dropbox.com/sh/n8w464g95pdpsv2/AACKvAjY8scyr5ZvVzE47Wbfa?dl=0
Is there a way to fix that?

EssentialsX version (`/essentials`): 
**2.0.1-B530**

Server software (`/version`): 
**git-Spigot-7754231-94b0980 (MC: 1.12.2)**

EssentialsX config (if applicable): 
**N/A**

**Comment by mdcfe** [comment]
As far as I can tell, this is not an EssentialsX command. To me it looks like WorldEdit, but there may be other plugins that provide that command.

**Comment by DmitryRendov** [comment]
you're right - it's WE tool, sorry for bothering. closed.
thank you
