### ISSUE TITLE
/tpo and /tpa 

### ISSUE THREAD

**Issue by FrankHeijden** [EssentialsX/Essentials#1572]
Heya,

im requesting a feature which teleports a player to the exact location of a flying player when switching through worlds. 

Currently, when you have a setup of `Player1` flying into `World1` and `Player2` in world `World2` and also has the essentials' flying permission -- Let `Player2` tpo/tpa to `Player1` and he will be set on the ground (under `Player2`)

What i want = `Player2` also flying when being teleported to `Player1`

**Comment by Techno3600** [comment]
Doesn’t sound like a bad idea, I actually think it would be cool to have!
Maybe in the Config
_on-teleport-with-permission-essentials-fly-tp-with-fly-on: true_

**Comment by khobbits** [comment]
This is actually already a feature.

https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/utils/LocationUtil.java#L278

I think the current logic checks to see if the player is in creative or god mode, and if so, skips the 'find safe place to put player at' checks.

If the player would need to fly, it checks to see if they could fly and sets flying enabled.

The reasons for this is that unless a player is in god mode or creative mode, the most important thing is that the user isn't teleported inside of a block, above a pool of lava, or a hole that goes to void.  To do this, it finds the closest location to the user that is considered 'safe' and drops the user there.

**Comment by mdcfe** [comment]
Closing due to lack of response to @khobbits's comment. If this is still a problem, feel free to reopen the issue.
