### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by Gnacik** [EssentialsX/Essentials#1573]
Essentials v2.0.1-b532
git-PaperSpigot-1f7d532 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

Hello. Im using last version of paperspigot 1.7-1.8

After changing old, default essentials to essentialsX got in logs spam about NoSuchMethodError

https://hastebin.com/oviqovezil.go

there is already try-catch block, but it catch only IllegalStateException, probably thats why it throws error. Its possible to add next catch for 1.7 ? afair getTargetBlock() was added later.

Thanks.

**Comment by LaxWasHere** [comment]
You are running an **unsupported** version, please follow the instructions on how to build the latest craftbukkit/spigot at http://www.spigotmc.org/wiki/buildtools/

**Comment by mdcfe** [comment]
1.7.10 is no longer supported by EssentialsX. If you need to use 1.7.10, please use [build 511](https://ci.drtshock.net/job/EssentialsX/511/).
