### ISSUE TITLE
Self bow shot

### ISSUE THREAD

**Issue by milani23234** [EssentialsX/Essentials#1574]
https://hastebin.com/motexuyawe.vbs
(1.7.10)

**Comment by NJDaeger** [comment]
1.7.10 isn't supported

**Comment by Gnacik** [comment]
Duplicated : #1573

**Comment by LaxWasHere** [comment]
You are running an unsupported version, please follow the instructions on how to build the latest craftbukkit/spigot at http://www.spigotmc.org/wiki/buildtools/

**Comment by DrewAMitchell** [comment]
@md678685 Close for unsupported version?
