### ISSUE TITLE
Bugged Enchants

### ISSUE THREAD

**Issue by alebertz** [EssentialsX/Essentials#1577]
EssentialsX version (`2.0.1-b488`): 

Server software (`This server is running CraftBukkit version git-Spigot-c3c767f-33d5de3 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT`): 

EssentialsX config ([Click here](https://pastebin.com/EF0sPFMa))

I made a kit with Diamond Pickaxe efficiency 5 and this doesn't work, the pickaxe mines slowly, how as if it were not enchanted.

**Comment by mdcfe** [comment]
Could you paste the output of `/plugins`?

**Comment by alebertz** [comment]
WorldEdit, EmptyWorldGenerator, JoinCommands, NoRain, ClearLag, WithdrawPlus, LuckyBlock, NoPluginViewer, MessageAnnouncer, BuycraftX, WorldGuard, ProtocolLib, NoCheatPlus, PlotSquaredSG, MVdWPlaceholderAPI, PermissionsEx, FeatherBoard, CS-CoreLib, AnvilColors, Vault, StaffPlus, MyCommand, EZRanksPro, QuickSell, Essentials, PrisonUtils, PlotSquared, SafeTrade, Multiverse-Core, ChestCommands, EssentialsChat, Multiverse-Portals, EssentialsSpawn, HolographicDisplays, DonationsHolograms, CratesPlus, PrisonMines, TokenEnchant 


@md678685

**Comment by mdcfe** [comment]
* Was the kit created by hand or with `/createkit`?
* Does Efficiency V show up on the tooltip?
* Do normal Efficiency V diamond picks work as expected?

**Comment by alebertz** [comment]
The kit was created in the config file by hand.
Yes the enchant shows up on the tooltip
No, i think no.

**Comment by mdcfe** [comment]
This doesn't sound like an EssentialsX issue. Could you test while gradually removing plugins (including EssentialsX and its modules) to see if any plugins (or combinations) are causing the issue?

**Comment by alebertz** [comment]
Ok i'll try

**Comment by DrewAMitchell** [comment]
@MegaITA Results?

**Comment by mdcfe** [comment]
Closing due to lack of response; if this is still a problem, please reopen the issue.
