### ISSUE TITLE
[Issue] & [Feature] Weird startup error & /ci confirmation

### ISSUE THREAD

**Issue by miekymc** [EssentialsX/Essentials#158]
I recently changed over to EssentialsX replacing Essentials with EssentialsX but keeping EssentialsChat, Protect, Spawn, and AntiBuild. Whenever I start up my server I get this error:

http://pastebin.com/D3YiiWqN

Also, feature request:
I'd like a way so you can confirm the clear your inventory.
So when you do /ci, it asks if your sure, and you just do /ci again.
This could be toggle-able in the configuration

**Comment by vemacs** [comment]
Error is entirely cosmetic and affects nothing. If you really care, swap out the module JARs with those from http://ci.drtshock.net/job/EssentialsX.

In the future, please file multiple tickets for different issues.
