### ISSUE TITLE
Changing Chat colours

### ISSUE THREAD

**Issue by luncherrs** [EssentialsX/Essentials#1581]
Well... I wanted to change the colours of the BROADCAST command as well as the ME command but I don't know how, I downloaded the messages_properties but It didn't worked ;-;

EssentialsX version (`/essentials`): Essentials 2.0.1

Server software (`/version`): MC: 1.12.2 (API version 1.12.2-R0.1-SNAPSHOT)

EssentialsX config (if applicable):

**Comment by MrLunch** [comment]
Ok, I tried everything I can and It still don't work ;-; Heelp
