### ISSUE TITLE
Jail buggs

### ISSUE THREAD

**Issue by FrankHeijden** [EssentialsX/Essentials#1582]
EssentialsX version (`/essentials`): 
b530
Server software (`/version`): 
CraftBukkit version git-Spigot-7754231-362ed32 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Jailed player issues non-essentials command, `jailMessage` of the locale is triggered twice;
Jailed player issues essentials command like /spawn --> results in  `player X jailed for X seconds`
Jailed player doesn't get teleported back to his previous location when he has been released; only the message `jailReleasedPlayerNotify` pops up.

**Comment by DrewAMitchell** [comment]
git-Spigot-f982156-22564a9 (MC: 1.12.2), EssentialsX 2.0.1-b547 - Was unable to replicate issues, they must be resolved. What about you now @FrankHeijden?

**Comment by mdcfe** [comment]
@FrankHeijden Could you post your config?

If EssentialsX is configured to listen to the teleport listener and change the `/back` last location, then this could mean that their last location is being reset when they try to teleport while in jail.

**Comment by FrankHeijden** [comment]
Jailed player issues non-essentials command, jailMessage of the locale is triggered twice; - this issue still persists for both permanent jails and temp jails

Jailed player issues essentials command like /spawn --> results in player X jailed for X seconds - this issue is only with temp jails

Jailed player doesn't get teleported back to his previous location when he has been released; only the message jailReleasedPlayerNotify pops up. - this issue is only with permanent jails.

**Comment by DrewAMitchell** [comment]
@FrankHeijden Just to make sure, update to the [latest build](http://ci.ender.zone/job/EssentialsX/lastStableBuild/)?
Also, please post the config.yml like was asked, if you would.

**Comment by mdcfe** [comment]
Closing due to lack of response; if this is still a problem, please reopen the issue, including your `config.yml` otherwise we can't help.
