### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by enlyow** [EssentialsX/Essentials#1584]
![112](https://user-images.githubusercontent.com/29000881/31317768-5da95dde-ac4f-11e7-9422-c1be60aec255.png)

Essentials 2.0.1-b481.
Paperspigot 1.12.2 b1234

Errors occur every 3 seconds.

**Comment by mdcfe** [comment]
You are running an outdated version of EssentialsX - download the latest version from the [build server](https://ci.drtshock.net/job/EssentialsX/lastSuccessfulBuild).
