### ISSUE TITLE
Prefix & suffix disappearing after dying (change-playerlist: true)

### ISSUE THREAD

**Issue by SoSeDiK** [EssentialsX/Essentials#1585]
EssentialsX: 2.0.1-b532
Server: Spigot 1.12.2 R0.1 b 1415
EssentialsX config: Default config, only removed '#' from '#change-playerlist: true'.

Problem: When player dies, then his prefix & suffix won't be showed in tab for other players (just white nick; also in commands from EssentialsX with display name like /fly <player<player>>) until he writes something in chat. Player who died will still see himself normally in tab.

Installed plugins: EssentialsX, EssentialsXSpawn, EssentialsXChat, Vault, ProtocolLib, LuckPerms.

**Comment by Techno3600** [comment]
Good point, I also have seen this problem.

**Comment by DrewAMitchell** [comment]
Duplicate @ https://github.com/drtshock/Essentials/issues/1642

**Comment by mdcfe** [comment]
Closing in favour of duplicate #1642, which has a response from Luck regarding the issue.
