### ISSUE TITLE
 lp temp prefix

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1588]
https://github.com/lucko/LuckPerms/issues/499#issuecomment-336570436

**Comment by BrainStone** [comment]
What's not working about the proposed solutions?

**Comment by ghost** [comment]
@BrainStone all be ok.

**Comment by DrewAMitchell** [comment]
@md678685 This can be closed:
Lucko said in the issue linked in the original post:
"Just to clarify, this is absolutely not an Essentials issue.
You've just configured the plugin (EssentialsChat in this case) incorrectly. I gave two solutions above."
