### ISSUE TITLE
Item durability in kits

### ISSUE THREAD

**Issue by Botanistt** [EssentialsX/Essentials#159]
Hello.
Could you please add item durability in kits section? I want to give half used bow to players.
Thanks

**Comment by Elgorond** [comment]
Would loveee this if implemented.

**Comment by Cldfire** [comment]
This can already be done, it's in one of the example kits. I'll paste the example here:

```
- 279:780 1
```

That's a diamond axe with 780 (or half) durability.

**Comment by Elgorond** [comment]
@Cldfire Jeez, I confused Essentials with a different plugin that was missing item durability functionality... lol
