### ISSUE TITLE
Building EssentialsX issues

### ISSUE THREAD

**Issue by ChimpGamer** [EssentialsX/Essentials#1593]
`[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building EssentialsX 2.0.1
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for net.milkbowl.vault:Vault:jar:1.5.6 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
Downloading: https://ci.drtshock.net/plugin/repository/everything/net/ess3/NMSProvider/2.0.1/NMSProvider-2.0.1.pom
Downloading: https://ci.drtshock.net/plugin/repository/everything/net/ess3/UpdatedMetaProvider/2.0.1/UpdatedMetaProvider-2.0.1.pom
Downloading: https://ci.drtshock.net/plugin/repository/everything/net/ess3/1_8_R1Provider/2.0.1/1_8_R1Provider-2.0.1.pom
Downloading: https://ci.drtshock.net/plugin/repository/everything/net/ess3/1_8_R2Provider/2.0.1/1_8_R2Provider-2.0.1.pom
Downloading: https://ci.drtshock.net/plugin/repository/everything/net/ess3/LegacyProvider/2.0.1/LegacyProvider-2.0.1.pom
Downloading: https://ci.drtshock.net/plugin/repository/everything/net/ess3/ReflectionProvider/2.0.1/ReflectionProvider-2.0.1.pom
Downloading: https://ci.drtshock.net/plugin/repository/everything/org/bukkit/bukkit/1.12-R0.1-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.bukkit:bukkit:1.12-R0.1-SNAPSHOT/maven-metadata.xml from/to ess-repo (https://ci.drtshock.net/plugin/repository/everything/): Failed to transfer file: https://ci.drtshock.net/plugin/repository/everything/org/bukkit/bukkit/1.12-R0.1-SNAPSHOT/maven-metadata.xml. Return code is: 522 , ReasonPhrase:Origin Connection Time-out.
[WARNING] Failure to transfer org.bukkit:bukkit:1.12-R0.1-SNAPSHOT/maven-metadata.xml from https://ci.drtshock.net/plugin/repository/everything/ was cached in the local repository, resolution will not be reattempted until the update interval of ess-repo has elapsed or updates are forced. Original error: Could not transfer metadata org.bukkit:bukkit:1.12-R0.1-SNAPSHOT/maven-metadata.xml from/to ess-repo (https://ci.drtshock.net/plugin/repository/everything/): Failed to transfer file: https://ci.drtshock.net/plugin/repository/everything/org/bukkit/bukkit/1.12-R0.1-SNAPSHOT/maven-metadata.xml. Return code is: 522 , ReasonPhrase:Origin Connection Time-out.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:35 min
[INFO] Finished at: 2017-10-17T17:58:05+02:00
[INFO] Final Memory: 6M/18M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project EssentialsX: Could not resolve dependencies for project net.ess3:EssentialsX:jar:2.0.1: Failed to collect dependencies at net.ess3:NMSProvider:jar:2.0.1: Failed to read artifact descriptor for net.ess3:NMSProvider:jar:2.0.1: Could not transfer artifact net.ess3:NMSProvider:pom:2.0.1 from/to ess-repo (https://ci.drtshock.net/plugin/repository/everything/): Failed to transfer file: https://ci.drtshock.net/plugin/repository/everything/net/ess3/NMSProvider/2.0.1/NMSProvider-2.0.1.pom. Return code is: 522 , ReasonPhrase:Origin Connection Time-out. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Process finished with exit code 1
`

I receive this error when I'm trying to build the EssentialsX module and I didn't even modified anything yet so why is this happening? Can someone help me with this?

**Comment by mdcfe** [comment]
Try replacing `https://ci.drtshock.net/plugin/repository/everything/` with `https://ci.ender.zone/plugin/repository/everything/` in the root `pom.xml`.

**Comment by ChimpGamer** [comment]
Thanks that did the trick! <3
