### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by JustDylan23** [EssentialsX/Essentials#1594]
https://gist.github.com/Dylan123111/94b8bbcfeab79406895fd6113f4ea71d

EssentialsX version (`/Essentials v2.0.1-b488`): 

Server software (`Spigot 1.12.2`): 

EssentialsX config (if applicable): 
-->https://gist.github.com/Dylan123111/51edc8999e0ae2d8df07f450d8683beb

**Comment by mdcfe** [comment]
This has been fixed in recent builds. Update EssentialsX to the latest version from [this mirror](https://ci.akpmakes.tech/job/EssentialsX/).
