### ISSUE TITLE
Towny new day + essentials error

### ISSUE THREAD

**Issue by Metisuneatn** [EssentialsX/Essentials#1595]
EssentialsX version (`/essentials`):  Currently on #532 version on jenkins, I believe we were on #528 before I updated today. This started happening Monday after no changes were made to the server. It is still happening on this latest version.

Server software (`/version`):  spigot-7754231-94b0980 1.12.2

This suddenly started happening after nothing was changed on the server. The towny creator instantly said its essentials. (https://github.com/LlmDl/Towny/issues/2704)

https://pastebin.com/j0NjaGkq

**Comment by FrankHeijden** [comment]
Could you please paste this on pastebin/hastebin?

**Comment by Metisuneatn** [comment]
Sure thing, first post updated with error in pastebin

**Comment by Metisuneatn** [comment]
I don't mean to be annoying but bumping this up again. This has almost fully broken towny for us.

**Comment by mdcfe** [comment]
Could you try replicating this on a test server with just Towny, EssentialsX and Vault, both with and without your server's user data on your test server?

**Comment by Metisuneatn** [comment]
I cannot recreate without server data, I will be trying with server data shortly. Right now trying a temp fix to get things moving again.

**Comment by Metisuneatn** [comment]
Done. I was able to recreate with the server data on the test server. I cannot recreate without the data

**Comment by mdcfe** [comment]
Closing as the Pastebin link has expired and this issue has been inactive for over two months. If you have any new information please reopen the issue.
