### ISSUE TITLE
how to disable the confirm payment for /pay?

### ISSUE THREAD

**Issue by Sonic8608** [EssentialsX/Essentials#1599]
I really want to know how you would disable confirm payment for /pay

EssentialsX version (`/essentials`): 
2.01
Server software (`/version`): 
Spigot - 1.12.1
EssentialsX config (if applicable):

**Comment by h8squid** [comment]
not 100% sure (I don't keep tabs on the project), but https://github.com/drtshock/Essentials/blob/5f83766dc169a48f7c2cb9c58cab77d2b0b583b0/Essentials/src/com/earth2me/essentials/commands/Commandpayconfirmtoggle.java should help.

**Comment by SupaHam** [comment]
https://github.com/drtshock/Essentials/wiki#pay-confirmation-toggle
