### ISSUE TITLE
Error on paperspigot 1.12 with 2.0.1 essentialsX

### ISSUE THREAD

**Issue by MineServidorCraft** [EssentialsX/Essentials#1604]
https://pastebin.com/g6Pwq9iA

EssentialsX version (`/essentials`):  2.0.1-b488

Server software (`/version`):  Paperspigot b1155 (1.12)

EssentialsX config (if applicable):  https://pastebin.com/TLZmgAL9

**Comment by LaxWasHere** [comment]
You are running an outdated version of EssentialsX, please update and close the issue if it has been fixed. https://ci.akpmakes.tech/job/EssentialsX/lastSuccessfulBuild/

**Comment by MineServidorCraft** [comment]
A new problem with this version that you give me:

https://pastebin.com/PEKQLxQd

**Comment by mdcfe** [comment]
Please open a separate issue for this issue.
