### ISSUE TITLE
Payment confirm disable

### ISSUE THREAD

**Issue by Arkobat** [EssentialsX/Essentials#1606]
EssentialsX version (/essentials):
Essentials 2.0.1-bSNAPSHOT

Server software (/version):
Paper Spigot 1.12.2

Can there be added in config something like
payment-confirm: false

If true, it will ask if you would pay as i does now.
If false, it won't ask

I know there is a command to disable it (something like /paytoggle), but i want it to be false by default.

**Comment by ScuroK** [comment]
would be nice.

and pls update:
https://www.spigotmc.org/resources/essentialsx.9089/

it leads to a inactive jenkins page!

**Comment by SupaHam** [comment]
This was avoided intentionally. We wanted to ensure a consistent behaviour
with regards to account balance across all servers. This exists to help
protect newbies.

**Comment by Arkobat** [comment]
@SupaHam 
So I would need to make a plugin to handle pay?
I won't have the accept payment, if that means I have to get a developer to make a plugin only to handle pay, because essentials won't make it configurable, that's what i will do, but I think that's stupid...

**Comment by SupaHam** [comment]
It is configurable, per player. If your players understand the consequences of disabling pay confirmation then there will be no problem. Educate your community.

**Comment by dordsor21** [comment]
per-player configurable is just a bad idea. It should be configurable in config too. I don't want to tell a player to use a long command just to toggle something that 90% want off by default...

**Comment by Remski01** [comment]
Nvm. I see what you mean. But still. Dont be lazy mate.

**Comment by drtshock** [comment]
It's now disabled by default and users have to toggle it on.
