### ISSUE TITLE
EssentialsX kit variable

### ISSUE THREAD

**Issue by WarnDa** [EssentialsX/Essentials#1607]
Hey ! Help me pleaz !
I use deluxemenus to add a menu for the /kit
and in this menu is use the variable %essentials_kit_is_available...%, but he doesn't work ( 50% of my player have the problem that is it written that they can't have the kit, but if they do /kit XXX it works, so the variable %essentials_kit_is_available...% sometimes bugs

EssentialsX version (`/essentials`):  lastet

Server software (`/version`): 1.8.8

EssentialsX config (if applicable):

**Comment by mdcfe** [comment]
We don't provide support for other plugins - contact the author of DeluxeMenus.
