### ISSUE TITLE
server implementation does not support hiding players from ping

### ISSUE THREAD

**Issue by smmmadden** [EssentialsX/Essentials#1609]
EssentialsX version (`/essentials`): 2.0.1 - build 538
Server software (`/version`): Waterfall build 152
Spigot 1.12.2 today's build
O/S: Windows Professional 2010 x64

Startup Warning:
[08:38:45] [Server thread/INFO]: Refresh time: 20
[08:38:45] [Server thread/INFO]: [BungeeServerSigns] [Info] Started Pinger and Refresher!
[08:38:45] [Server thread/WARN]: [Essentials] Current server implementation does not support hiding players from server list ping. Update or contact the maintainers.
[Full Startup log here](https://pastebin.com/mburwsb6)

Did something change that needs to be added/updated in the[ config.yml](https://pastebin.com/FyRM7NeL)?  The message isn't clear what needs to be fixed and I haven't changed anything with respect to players visibility.

Thanks - Steve

**Comment by SupaHam** [comment]
@md678685

**Comment by mdcfe** [comment]
In this case, the message is somewhat misleading. BungeeServerSigns is likely calling a custom ServerListPingEvent which does not fully implement the SLPE. If this issue can only be replicated with BungeeServerSigns, contact the author and tell them to add an `iterator` to their implementation of ServerListPingEvent.

**Comment by smmmadden** [comment]
thanks, I'll reach out to the developer again and advise accordingly.  I removed that plugin and the message did go away as you thought, so this is not an EssX bug.
