### ISSUE TITLE
JailStatusChangeEvent not firing.

### ISSUE THREAD

**Issue by TagCraftMC** [EssentialsX/Essentials#161]
I was trying to hook into the JailStatusChangeEvent but it does not seem to be firing. The event is registered (other events in the class are firing) and there are no errors.

Thanks.

``` java
    @EventHandler
    public void onJailStatusChange (JailStatusChangeEvent event)
    {   
        Bukkit.getLogger().info("DEBUG - Player: " + event.getAffected().getName() + " Status: " + event.getValue());
    }
```

**Comment by drtshock** [comment]
Yeah it looks like there aren't any usages lol.

**Comment by TagCraftMC** [comment]
An possibility of adding it in the future? At the moment we using PlayerCommandPreprocessEvent for the jail and unjail command + checking if the player is jailed, which kinda feels a little dirty.

Thanks drtshock.
