### ISSUE TITLE
I need help about building the code

### ISSUE THREAD

**Issue by Sonic8608** [EssentialsX/Essentials#1612]
So I recently downloaded the zip files for essentials and I wanted to edit the "Commandpayconfirmtoggle" but now I want to compile all the files in the essential folder from the zip file into a jar file, so that I could run the plugin on my server, if anybody know how can someone teach me? And yes I do have Eclipse.

**Comment by mdcfe** [comment]
See the [Building](https://github.com/drtshock/Essentials/blob/2.x/README.md#building) section - make sure you have Maven and a JDK installed. You'll also need BuildTools, so you'll also need to have Git installed.
