### ISSUE TITLE
/createkit isn't working at all

### ISSUE THREAD

**Issue by Eufranio** [EssentialsX/Essentials#1613]
EssentialsX version (`/essentials`): EssentialsX-2.0.1, build 540 (jenkins)
Server software (`/version`): Thermos B58, 1.7.10
EssentialsX config (if applicable): https://hastebin.com/ribunebimo.coffeescript

The /createkit command doesn't work at all. I do `/createkit name 0` and it doesn't create any kits not output anything in the console/reply. I do have permission to run the command but looks like it won't let me to...

**Comment by mdcfe** [comment]
Can you replicate this on a test Spigot 1.8 server on the same machine to confirm whether the issue is caused by Thermos?

**Comment by pop4959** [comment]
Closing due to lack of response + I'm unable to replicate the issue with the given procedure. It's giving the expected output in chat.
