### ISSUE TITLE
Stuck in Lilypads on tp

### ISSUE THREAD

**Issue by ridalarry** [EssentialsX/Essentials#1614]
If someone tpa and the teleport location is on a lilypad the player that executed "/tpa" will be stuck in the lilypad
EssentialsX version (`/essentials`): 
the latest on the jenkins today
Server software (`/version`): 
1.8.8 and I think this happens on other minecraft versions too
EssentialsX config (if applicable): 
Happens with the original config of the latest version

**Comment by ridalarry** [comment]
I have tried to tp with vanilla /tp and it doesn't happen

**Comment by DrewAMitchell** [comment]
In 1.12.2, EssentialsX 2.0.1-b547, replicatable:
Given that collision doesn't occur, the destination player standing on (or hovering above) a lilypad causes the teleporting player to sink into the Lilypad, teleporting into the bounding box and no-clipping through it.

**Comment by DrewAMitchell** [comment]
https://github.com/EssentialsX/Essentials/issues/133 Potential relationship?

**Comment by pop4959** [comment]
Not really a bug in Essentials, just has to do with how Bukkit handles teleportation. This has been an issue for years though, and unlikely to change any time soon. Best workaround is to break the lilypad or teleport onto a solid block instead.
