### ISSUE TITLE
BUG: Essentials World with MultiVerse not teleporting to World Spawn, but relative to location in last World.

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1615]
Hi all,
I am having a bug on my Server, running EssentialsX w/ MultiVerse, when running /world <world> - I teleport to that World, but I teleport to the location relative to where I were, on the last World.

Example: I run /world <world> @ **X: 21 Y: 70 Z: 12** - I will teleport to the World specified but then teleport to **X: 21 Y: 70 Z**: 12 in that World, and not the World Spawn **or where I last logged off.**

Regarding my issue, does anyone know a workaround to make it forcefully **TP you to the Spawn**, or, **TP you to the last location** of where you **logged off in that World**.

**EssentialsX version:** Essentials 2.0.1-bSNAPSHOT

**Server software:** This server is running CraftBukkit version git-Spigot-93e20b3-31d3159 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Any help is appricated!

**Comment by mdcfe** [comment]
* ~~Are you using EssentialsX Spawn?~~
* ~~What build of Multiverse are you using?~~

~~This doesn't sound like an EssentialsX issue to me.~~

[**This is intended behaviour.**](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/commands/Commandworld.java) If this is not desired behaviour, I would suggest using `/mvtp` from Multiverse instead (as that teleports players to the spawnpoint).
