### ISSUE TITLE
Command logging in console option in config

### ISSUE THREAD

**Issue by JunkiEDM** [EssentialsX/Essentials#162]
This is a feature request to add a config option to be able to enable/disable command block/player command logging in the console. This gets incredibly annoying when you have a command block clock especially since it is a default spigot.yml feature. Usually I would edit the source code, but I get this:

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:23 min
[INFO] Finished at: 2015-08-21T11:36:43-03:00
[INFO] Final Memory: 17M/316M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.
3.2:compile (default-compile) on project Essentials: Compilation failure: Compil
ation failure:
[ERROR] \Users_\Documents\GitHub\Essentials\Essentials\src\com\earth2me
\essentials\UserMap.java:[117,15] error: method get in interface Cache<K,V> cann
ot be applied to given types;
[ERROR] \Users_\Documents\GitHub\Essentials\Essentials\src\com\earth2me
\essentials\commands\Commandbreak.java:[22,36] error: reference to getTargetBloc
k is ambiguous
[ERROR] \Users_\Documents\GitHub\Essentials\Essentials\src\com\earth2me
\essentials\craftbukkit\FakeWorld.java:[20,7] error: FakeWorld is not abstract a
nd does not override abstract method getWorldBorder() in World
[ERROR] \Users_\Documents\GitHub\Essentials\Essentials\src\com\earth2me
\essentials\commands\Commandlightning.java:[28,50] error: reference to getTarget
Block is ambiguous
[ERROR] \Users_\Documents\GitHub\Essentials\Essentials\src\com\earth2me
\essentials\OfflinePlayer.java:[27,7] error: OfflinePlayer is not abstract and d
oes not override abstract method getLastTwoTargetBlocks(Set<Material>,int) in Li
vingEntity
[ERROR] \Users_\Documents\GitHub\Essentials\Essentials\src\com\earth2me
\essentials\signs\SignPlayerListener.java:[46,35] error: reference to getTargetB
lock is ambiguous

A config option or help on compiling the source code would really improve things (for me at least) And I know some other people were upset at how the official essentials or Teamcity essentials didnt have this as an option.

On a side note, is Spigot-essentials required / needed with essX or do the features come with it?

Thanks for the help!

**Comment by drtshock** [comment]
Spigot essentials isn't required. This is a drop in replacement for essentials.

I don't understand the rest of your ticket.

**Comment by JunkiEDM** [comment]
When any form of essenials is installed, including this one, it overwrites the spigot.yml function for whether or not to show command block outputs in the server console. What I am asking for is a way to disable command logging in console in a config (https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/Essentials.java#L369)

**Comment by Telkir** [comment]
See also #1153 

Bumping this issue to say that with EssentialsX loaded, the `silent-commandblock-console: true` setting present in the `spigot.yml` file of Spigot and PaperSpigot servers is ignored, allowing command blocks to potentially create heavy log spam.

This may not be a problem for all servers but as soon as you have any repeat CBs in your world, log spam could potentially lead to exceeding a hosting provider's storage allowance.

Without any way to disable this behaviour inside Essentials config, I'd consider this is a bug, not an enhancement request, and hope that it would be treated as such.
