### ISSUE TITLE
/jump command ignoring block protection

### ISSUE THREAD

**Issue by Eufranio** [EssentialsX/Essentials#1620]
This isn't really a issue nor a new feature, but an enhancement. Let's say a player builds an closed room, usually no one else would be able to enter it, but players can enter using the jump command. They just target a corner, the bottom, anyway, and can "jump" inside the room. This breaks the player protection.

It'd be nice if you could check if the player cannot break a block on a certain area when jumping: this would prevent situations like that for server that don't want/have a protection system.

**Comment by mdcfe** [comment]
I'm not convinced that this is a worthwhile change - to me, `/jump` doesn't seem to be designed for normal players, and so it makes sense for it to have caveats like this.

~~That said, I'm not closing this as a wontfix as some may have different opinions or may want to implement this themselves.~~

2 years later edit: closed as a wontfix
