### ISSUE TITLE
tab auto complete not working

### ISSUE THREAD

**Issue by Snoradbe** [EssentialsX/Essentials#1621]
Can't use /tpa (name), /home (name) and etc in 2.0.1-b488
But this working in 2.0.1-b370
Minecraft version 1.7.10 Thermos core

**Comment by mdcfe** [comment]
Could you try building ed0ad87632492ee0d2273424dec676d77adf4d08 (build 511)? 1.7.10 is not supported from build 512 and above, but you're running a very outdated version of EssentialsX.

**Comment by Snoradbe** [comment]
Old versions [here](https://ci.drtshock.net/job/EssentialsX), but site is down
I can't find build 511

**Comment by mdcfe** [comment]
I'm aware - you'll need to build EssentialsX from the commit linked above.

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to reopen the issue.
