### ISSUE TITLE
Powertool bugg

### ISSUE THREAD

**Issue by FrankHeijden** [EssentialsX/Essentials#1622]
/powertool only works if you damage a block, clicking in air doesn't execute the powertool command.

EssentialsX version (`/essentials`): 
b540
Server software (`/version`): 
CraftBukkit version git-Spigot-5695bca-53fccdf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
EssentialsX config (if applicable):

**Comment by FrankHeijden** [comment]
bump 👍

**Comment by stevmei** [comment]
Confirmed b542.

**Comment by Nibby49** [comment]
Also seeing this error.

**Comment by mdcfe** [comment]
Can this be replicated on [build 533](http://ci.ender.zone/job/EssentialsX/533/)?

**Comment by FrankHeijden** [comment]
Nope, 533 works just fine

**Comment by mdcfe** [comment]
It looks as though e6fc4590804a8687815faa2477ad1ee4b8a88edd (#1534) may have broken this when the `break` statements were added. This could be confirmed if this can be replicated on build 534.

**Comment by FrankHeijden** [comment]
Sorry for not replying - didn't get an email unfortunately 👎 
but yes, build 534 broke the feature. Clicking air doesn't execute the powertool command.

And yet another question: e.g. in a worldguard region; commands "/near,/powertool,/pt" are blocked; but when a user has already set a powertool of /near on e.g. a dirt block, essentials still lets him execute the powertool command. Is there a way to fix this? - so just instead of this in the console:
```[Essentials] [PT] FrankHeijden issued server command: /testcommand```
this (executing the command AS the player):
```FrankHeijden issued server command: /testcommand```

**Comment by mdcfe** [comment]
@FrankHeijden That's a separate issue and I don't know how WG blocks the command, but we're dispatching the command as normal through the Spigot API.

**Comment by mdcfe** [comment]
If someone could confirm whether #1657 fixes the issue, it would be much appreciated.

**Comment by stevmei** [comment]
Yes, it is fixed applying https://github.com/drtshock/Essentials/commit/ed2e0303d94823ac895f7dff44a8c47b97aeeafd

Thanks :)
