### ISSUE TITLE
Nukkit

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1625]
Is it possible that Nukkit support will be added in the future? Just curious.

**Comment by mbax** [comment]
Who would write such a total conversion? Do you have anyone in mind?

**Comment by mdcfe** [comment]
^

@PGaming6994 Nukkit support can't just be "added" - Nukkit is an entirely different platform to Spigot, and has many differences in terms of writing plugins. It's not literally impossible to support Nukkit in EssentialsX, but the required code changes to EssentialsX would be substantial.

**Comment by mdcfe** [comment]
Closing as a `wontfix`.
