### ISSUE TITLE
whoisUUID Is missing

### ISSUE THREAD

**Issue by AmazedMender16** [EssentialsX/Essentials#1627]
EssentialsX version (`/essentials`): Latest

Server software (`/version`): Latest 1.12.2

whoisUUID is missing from the mesages_en.properties

**Comment by mdcfe** [comment]
Related to #1380 - arguably a duplicate, but I'll keep this open for future reference.

**Comment by AmazedMender16** [comment]
@md678685 all i would need to know what the name of the message is i have tried

WhoisUUID= 
But that doesnt seem to work..

**Comment by mdcfe** [comment]
You can copy it from `messages.properties` - as far as I know, it's `whoisUuid` (note the specific casing).

**Comment by AmazedMender16** [comment]
I have checked messages.properties and couldnt find it in there..

whoisUuid it is!

**Comment by mdcfe** [comment]
[It's definitely there](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/messages.properties#L600) - in fact, [it's in `messages_en.properties`](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/messages_en.properties#L591) as well.

You might want to update your messages files to include the new messages if you've recently updated EssentialsX, or if you're looking inside the jar and can't find them, you should update EssentialsX.

If you haven't made any major changes to your messages file, you can just copy a newer `messages_xx.properties` [from the repo](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/) over your old one.

If you *have* made major changes however, you can use a three-way merge tool if you know which version of EssentialsX you originally copied your file from. Another way, if you have Python installed, is to download the [most recent `messages.properties`](https://raw.githubusercontent.com/drtshock/Essentials/2.x/Essentials/src/messages.properties) and [this comparison script](https://gist.github.com/md678685/a5e435a79d3431040d91ea9d4b84026d#file-compare-py), put them in an empty directory, copy your messages file to that directory then run the script to see which lines you need to add.
