### ISSUE TITLE
 suggestion: /god (option to loot)

### ISSUE THREAD

**Issue by comonier** [EssentialsX/Essentials#1628]
**wanted that while god mode is active the player with this permission can loot the mobs. When the god mode is active the player kills the mob but does not receive the loot, however he only deactivates the god and receive the loot again when he kills.**

**Comment by kennyrkun** [comment]
so you're meaning that when the player kills a mob with God active, the mob will not drop its loot?

**Comment by triagonal** [comment]
Closing for reasons mentioned in #2500.
