### ISSUE TITLE
Reset kit cooldown

### ISSUE THREAD

**Issue by baticag** [EssentialsX/Essentials#163]
This is a suggestion to add command for reseting players kit cooldown
/resetcooldown <player> <kit>
And also that <kit> can be for all kits!
Thanks!

**Comment by thu2468** [comment]
i think it better if it /kitreset {name} {kitname}
And having another command to reset all that player kit so /kitreset {name} all

**Comment by drtshock** [comment]
good idea.

**Comment by drtshock** [comment]
what if you have a kit named all? :(

**Comment by thu2468** [comment]
true, then /kitresetall {name}
or just tell people don't make a kit named all xD

**Comment by baticag** [comment]
Yes, the command can be whatever you want :D but idea is what I was going for!

**Comment by EncryptedPixel** [comment]
+1

**Comment by Sikatsu** [comment]
+1

**Comment by darbyjack** [comment]
Currently in the works via #2645 .

**Comment by AshwaysDev** [comment]
PLEASE ADD THE POSSIBILITY TO DO THE EXACT SAME THING BUT INVERTED. I NEED IT. (And i failed to do it with the api...)

**Comment by mdcfe** [comment]
@FlappyMC This issue was closed 4 years ago. If you would like to make a new feature request, please [open a new feature request](https://github.com/EssentialsX/Essentials/issues/new/choose).
