### ISSUE TITLE
Can I use non-alphanumeric nicknames?

### ISSUE THREAD

**Issue by Midnight9746** [EssentialsX/Essentials#1630]
Hello, I am wanting to use non-alphanumeric nicknames, but I can't seem to find that anywhere. I am a staff member on a mythology server and I wish to use Ｈａｄｅｓ, as my name. But doing /nick Ｈａｄｅｓ, just says "Must be alphnumric!". Any ideas?

Note:

I tried using essentials.nick's perms, bunch of plugins, and group manager, but I can't find a way to allow anything to be my nickname. I've seen many other servers that do have names using symbols and fancy font, but as far as I can Google. Nothing helps.

I heard of a permission for non-alphnumric but I don't know it, the person who suggested it didn't give the node

EssentialsX version (`/essentials`): 1.12.1

Server software (`/version`): Spigot 1.12.1

EssentialsX / Group Manager X, I don't think my config or groups have anything to do with it. I've already checked.

I am assuming it's possible, just wanna know how:
https://imgur.com/XdsTVae

Update:

It's possible to edit your essential user config (essentials > userdata > your UUID) and change your prefix to use non-alphanumeric nicknames. However, once you change your name again in-game, you can't go back without editing the config... Anyway to do this without the config, and in-game without other plugins?

**Comment by mdcfe** [comment]
Currently, this isn't possible without recompiling EssentialsX with changes. The alphanumeric characters check is done [here](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/commands/Commandnick.java#L79), so you could remove the first check and rebuild EssentialsX.

If someone's willing to submit a PR that makes this configurable, feel free.

**Comment by mdcfe** [comment]
In the `1.13` branch, you can now give users the permission `essentials.nick.allowunsafe` to let them use non-alphanumeric characters in nicknames.

Edit: this isn't in release builds from the normal download link yet. We don't recommend using 1.13 builds on 1.12 and below, but in their current state, they should be functional on both versions.

**Comment by Midnight9746** [comment]
Aw sweet, Thank you so much, I'll get to updating the plugin now!

**Comment by Midnight9746** [comment]
I've had gotten busy with other things and updated to version 1.13.2, and even from 1.13 this has been happening and I've used this link: https://github.com/EssentialsX/Essentials/tree/1.13 (Scroll down to the Jinkins link, which was like https://ci.ender.zone/job/EssentialsX/ but that link looked weird to me) and basically it works fine as normal and I have the perm but the nick part still won't work. 

Is there a config setting or anything I'm missing? The plugin is from the 1.13 branch.
![2018-11-01_01 38 09](https://user-images.githubusercontent.com/30037006/47836871-d63d7a00-dd77-11e8-97a7-69c6b85dc47e.png)

**Comment by Xeyame** [comment]
Try this one: https://ci.ender.zone/job/EssentialsX-Experimental/

**Comment by Midnight9746** [comment]
Thanks, that works, I'm so happy!

**Comment by soshimee** [comment]
Was this removed? I can't do this anymore for some reason.

**Comment by Chew** [comment]
Please make a new issue (filling out template completely)

**Comment by pop4959** [comment]
You need the `essentials.nick.allowunsafe` permission to use non-alphanumeric characters.

Keep in mind, this allows you to use ***any*** characters, which could cause potential problems such as incompatibilities with other plugins. Please test yourself before enabling the feature.
