### ISSUE TITLE
Server crashing from /spawn

### ISSUE THREAD

**Issue by CommandGuardian** [EssentialsX/Essentials#1635]
<!---
When my players or I use /spawn the server crashes. The plugin I use for /spawn is EssentialsX. This issue either started yesterday or today but the only thing I have done to the server between those 2 days was pay for my server. So I have no clue had it started. I loaded my backups but still no change plus I even loaded a personal backup made about a month ago. What do I do to fix this?

**Comment by Kakifrucht** [comment]
Duplicate of #1631
