### ISSUE TITLE
Signs not working correctly for other players in server

### ISSUE THREAD

**Issue by Trikery** [EssentialsX/Essentials#1636]
EssentialsX version (`/essentials`): 
Essentials 2.0.1-b488
Server software (`/version`): 
git-Spigot-da42974-8f4 7214 (MC: 1.12.1)
EssentialsX config (if applicable): 

~~[config.txt](https://github.com/drtshock/Essentials/files/1460050/config.txt)~~

*Edit by @md678685: please use [Gist](https://gist.github.com/) for future configs rather than attaching them. I've copied your attachment to a Gist [here](https://gist.github.com/md678685/c317a01e7420c2fbd1ca5b9c92455296).*

I've been having trouble running Signs in my server.  For Some reason the Signs don't work for other players besides myself in the correct Manner.  We've manage to make it work... sort of.  Only while holding an item in your left hand and crouching while clicking the sign will it work.
I've disabled most of my other plugins to see if it was being caused by one of them, but as far as I can tell thus far... it's not.

**Comment by mdcfe** [comment]
Update EssentialsX to the [latest version](http://ci.ender.zone/job/EssentialsX).

**Comment by Trikery** [comment]
K, I've Updated all the Essentials Plugins that I'm using to Essentials 2.0.1-bSNAPSHOT.   But the problem is still the same.
I am using Essentials, Spawn, and Chat

**Comment by Trikery** [comment]
Found the Problem.
Any Sign I Make, is locked this way when I'm OP.
