### ISSUE TITLE
error at server start

### ISSUE THREAD

**Issue by Ironic8b498** [EssentialsX/Essentials#1639]
EssentialsX version (`/essentials`): Build 532

Server software (`/version`): 1.12.2

EssentialsX config (if applicable): https://www.hastebin.com/unihexaqib.coffeescript

Error: https://www.hastebin.com/ziveritupi.vbs

I would download an updated but link don't work anymore

**Comment by Kakifrucht** [comment]
The link works perfectly fine. This update was fixed in [build 542](http://ci.ender.zone/job/EssentialsX/542/).

**Comment by Ironic8b498** [comment]
that link works but the one I have didn't [https://ci.drtshock.net/job/EssentialsX/](url)

**Comment by Kakifrucht** [comment]
That one isn't linked anymore.

**Comment by Ironic8b498** [comment]
I figured that out when it stopped working, no more errors at boot up either
