### ISSUE TITLE
Nether Portal Creation Prevention.

### ISSUE THREAD

**Issue by DahFrozen** [EssentialsX/Essentials#164]
Hi,

I've set "portal-creation: true" in the EssentialsProtect prevent section of the config. However, players can still create Nether Portals.
Thanks.

**Comment by drtshock** [comment]
How are they creating the nether portals and which version of mc are you on? Also, give us a full list of plugins please.

**Comment by DahFrozen** [comment]
They are creating the portals by lighting the obsidian frame on the inner walls with a flint and steel.
Server Version: Paper Spigot 1.8.8
Plugins (63): CleanroomGenerator, BarAPI, Buycraft, DunterraVapples, DonatorReclaim, DeluxeTags, DunterraPvP, FallingBlockFix, CrateKey, ClaimLevels, DunterraPortalDestination, HideStream, DunterraSorcery, WorldEdit, CustomList, DunterraExtras, AnimatedNames, ClearLag, ChatControl, AutoMessage, WorldBorder, Votifier, LightningDeathReloaded, Multiverse-Core, ProtocolLib, LibsDisguises, AutoSaveWorld, DunterraScythes, PermissionsEx, mcMMO, ServerListPlus, Vault, MassiveCore, HolographicDisplays, VoteParty, WorldGuard, ProxyPipe-Bukkit, boosCooldowns, Essentials, CompatNoCheatPlus, Auctions, LiteBans, KoTH, SilkSpawners, NoCheatPlus, PluginsBaker, GAListener, Factions, EssentialsProtect, EssentialsAntiBuild, EssentialsSpawn, TitleManager, FBasics, DunterraGems, iGates, DeluxeChat, ObsidianDestroyer, CombatTagPlus, FactionChat, JCTools, DunterraEnchants, DunterraCosmetics, DunterraFactionsExtra
