### ISSUE TITLE
[REQUESTS]  /mail and /pay feature requests

### ISSUE THREAD

**Issue by Formula350** [EssentialsX/Essentials#1641]
EssentialsX version (`/essentials`): 
2.0.1-b530
Server software (`/version`): 
Spigot 1.11.2

**[Request 1]:** Allow for the usage of `/mail send <UUID>` for ***offline*** players. Currently, you can only use their UUID for `/mail` while they are connected to the server.
Reasoning: I have an Enjin hosted website, which logs users UUIDs in the DonationCraft history. Often times I'll need to look up and message a player for one reason or another. In this case, I was messaging every player who had donated for disguise packages with a Free coupon code for them to go through the process again and obtain the new permissions (new plugin; at the time this seemed easier than resolving the UUID, removing 5-9 permissions, adding 5-9 new permissions, over and over). Unfortunately, for simplicity sake I used a command block with `/mail send <UUID> [Message] <coupon code>`, instead of `/sudo Formula350 mail send blah-blah-blah`, so I did not receive the `Error: Player not found.` message after clicking the button to execute the block. 

**[Request 2]:** Have the `/pay` confirmation display who the person the plugin has selected for the association, so players know for sure WHERE their command will be sending money to when using Nicknames.
Reasoning: Player today had used `/pay hermes 20000` and all it asked was to repeat the command again to confirm. Fair enough, except, Essentials looks at the entire display name when factoring in the "who" in commands like this *(/msg, /tp, etc are others)*. So instead of going to the player whose Nickname was Hermes (full display name of `[MAJOR]Hermes`), it went to the player whose Group Prefix was [HERMES] (full display name of `[HERMES]Paxton_Miner`); thus, the confirmation didn't really help any. :P

**Comment by mdcfe** [comment]
There isn't really any reason for `/mail` to *not* support sending mails by UUID, so this should be added.

Regarding the `/pay` issue, we currently determine who to send the payment to *after* the command has been confirmed - this would need to be done beforehand for the user to get an accurate response from EssX.

**Comment by pop4959** [comment]
Please make separate issues for each feature request, so that it can be more easily tracked (and people who want to PR such features can more easily find it).
