### ISSUE TITLE
custom-join-message for groups

### ISSUE THREAD

**Issue by seema84** [EssentialsX/Essentials#1643]
i need group support for custom join messages

**Comment by noahcoetsee** [comment]
That would come with almost any chat plugin. Since essentials isn't chat focused, it's better to rely on another plugin. Try ChatControl https://www.spigotmc.org/resources/chatcontrol.271/

**Comment by seema84** [comment]
I dont need a big chat solution and i cant find this option in chatcontrol.

**Comment by noahcoetsee** [comment]
Look in formatting. Trust me, it's there. Plus, all feature are originally disable in ChatControl, so honestly, I don't see why it wouldn't be a good solution.

**Comment by DrewAMitchell** [comment]
@md678685 Not a necessary enhancement? Close?

**Comment by mdcfe** [comment]
Unlikely to happen, as it's a fairly specific feature, but I personally don't see the need to close it.

**Comment by seema84** [comment]
every join plugin has a group support, thats not a specific feature

**Comment by mdcfe** [comment]
I don't think many people will have a use for this, even if some people do, and so I would say that this is best left to other plugins.

**Comment by noahcoetsee** [comment]
I know I'm late to this conversation, but I would agree with @md678685 . Plus, @seema84 if you really need something lightweight and specific, I would gladly cook up a quick plugin that does just that...

**Comment by TheIntelloBox** [comment]
Would be great.

**Comment by mdcfe** [comment]
Closing as this is outside the scope of EssentialsX.
