### ISSUE TITLE
Severe Server Crash Error.

### ISSUE THREAD

**Issue by bigbluu722** [EssentialsX/Essentials#1646]
EssentialsX version (`/essentials`): 
`[Tue, 14. Nov 2017 22:33:24 EST INFO] Using locale en_US
[Tue, 14. Nov 2017 22:33:24 EST INFO] [Essentials] Using Spigot 1.7.10+ ServerListPingEvent iterator
[Tue, 14. Nov 2017 22:33:24 EST INFO] Essentials reloaded 2.0.1-bSNAPSHOT.`

Server software (`/version`): 
`[Tue, 14. Nov 2017 22:33:42 EST INFO] This server is running CraftBukkit version git-Spigot-d21162c-adbfc1f (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[Tue, 14. Nov 2017 22:33:42 EST INFO] You are 1 version(s) behind` 

EssentialsX config (if applicable): 
https://pastebin.com/i96TuKM8

Description:
For about a week now, our servers have been randomly crashing throwing these thread dumps in and killing our console wrapper which is supposed to restart them even if they crash (I don't expect help for the wrapper), but we really have no idea what else is causing the issue and decided to post a report to here and the Spigot issue reporter seeing as we've updated essentialsx to the latest dev version available and it still throws these stacks. Not sure what to do at this point so any help we can get would be appreciated, thank you.

https://pastebin.com/3dMzFTg5

**Comment by smmmadden** [comment]
first - you should really post long mixed text/styled config files into pastebin or some other site and leave a url reference to review so it doesn't look like the above and easier to read with formatting maintained.
Second, which build of essentials are you using?  Are you using build 542 or 543 (latest)?  If not, I'd recommend updating first so it matches the spigot version as well and it fixes a KI with a recent Spigot change related to Spawn.

**Comment by bigbluu722** [comment]
I've went ahead and fixed the post regarding the config, that was a my bad due to me being in a rush. Seeing as we're actually a few versions behind I'll go ahead and update to see if that solves our issue.

**Comment by mdcfe** [comment]
This error appears to be caused by EssentialsX Spawn - I'm not able to look into this properly at the moment, but you could monitor your server's CPU load, RAM usage and disk usage (`top` and `df` may be useful) to see if there are any anomalies when the server locks up.

In addition, you may want to see if this can be replicated using Paper, which seems to have a more helpful lockup report (from what I remember, at least).

**Comment by bigbluu722** [comment]
Latest updates seem stable currently. Will leave it be for a few more days before closing incase the stack/thread happens again

**Comment by Llopeando** [comment]
Im having the same problem too :(

**Comment by enterih** [comment]
Same here @drtshock

**Comment by bigbluu722** [comment]
@Sprungente @AllPlayed Try the solution sent here above as it seems to be working for our servers.

**Comment by StoneLegion** [comment]
I know 1.7.10 not welcome here but also having this crash in that version... The second someone types /spawn in game the server hangs then does the thread crashing stuff.

**Comment by mdcfe** [comment]
@KaneHart Build 511 was the last version of EssentialsX to support 1.7.10, but build 511 can't be downloaded any more as the old CI server was the only build server to go back that far. You'll need to build ed0ad87632492ee0d2273424dec676d77adf4d08 manually for 1.7.10.

**Comment by StoneLegion** [comment]
Thanks @md678685 I will do that.

**Comment by bigbluu722** [comment]
Closed seeing as my issue is resolved.
