### ISSUE TITLE
Java 9 support

### ISSUE THREAD

**Issue by lifehome** [EssentialsX/Essentials#1647]
Would there be any Java 9 support? It seems the repository cannot build against Java 9...

**Comment by NJDaeger** [comment]
I'm pretty sure this is a maven issue. I tried to compile with java 9 and it complained. Java 8 will suffice for now.

**Comment by lifehome** [comment]
I am afraid artifacts built by Java 8 cannot be ran on Java 9 platforms, as EssentialsX utilize Java EE as dependencies, it would simply fail to run since Java 9 removed Java EE classpath from it's modular mechanism newly introduced.

I suggest eliminating the dependency relation, as it would affect deeply once transiting from Java 8 to 9 or even 18.3.

**Comment by mdcfe** [comment]
There should be no issues using the [latest build](https://ci.ender.zone/job/EssentialsX) on Java 9. If you encounter any issues, please open a new issue.
