### ISSUE TITLE
Problem with essentialsX economy

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1648]
EssentialsX 2.0.1. #545
Spigot 1.12.2 
Vault 1.5.6

Money is not counted or deducted from offline players. Problem with the ChestShop, ShopChest... maybe other plugins using the vault plugin.

Same problem with command `/eco give|take`. When the player is offline, money is not added.

**Comment by mdcfe** [comment]
Did you resolve this issue?

**Comment by ghost** [comment]
The problem was with the plugin [MySQL Economy Bridge](https://www.spigotmc.org/resources/mysql-economy-bridge.6174/). When the player joined, the plugin rewrote the money in the account with the old value in the mysql.
