### ISSUE TITLE
Two players same nickname

### ISSUE THREAD

**Issue by baticag** [EssentialsX/Essentials#1649]
Two players can change nickname to the same one.

For example:
Player Marco: /nick Luca
Player Leon: /nick Luca
You get two players named ~Luca on server

Can you please fix this?

**Comment by DrewAMitchell** [comment]
Not necessarily a bad thing - it'd be horribly inefficient to look through other players' stored nicknames on a larger scale. Nicknames are purely cosmetic, so other than /realname being affected, there's no real point to making them be unique.

**Comment by baticag** [comment]
How can you find out their real name then if they insult other players?

**Comment by drtshock** [comment]
It'll just send you the real name of both players if you type `/realname <nickname>`

Important note is not breaking after finding one result https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/commands/Commandrealname.java#L34

**Comment by baticag** [comment]
But still how do you know which player wrote the message, this is the situation:

Player Marco: /nick Luca
Player Leon: /nick Luca
Player Batica: /nick Luca
Marco (as ~Luca) wrote: I f*c* you
Leon (as ~Luca) wrote: Wait what?
Batica (as ~Luca) wrote: Okay bla bla

Player Alex wants to report ~Luca for insulting, types /realname Luca, gets output Batica, Leon,  Marco.
How does he know who to report i.e. who wrote the insulting message?

**Comment by drtshock** [comment]
That's a good point. Sounds like it's time to add chat components to show who the real player is when you hover over their name!

**Comment by pop4959** [comment]
Chat components are still not widely supported IIRC, however this is not really a bug. Several players can have the same nickname, and that is valid. As mentioned, `/nickname` shows all such users. If it's a problem you should probably have moderators remove the person's nickname who is abusing it.
