### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Banana-Man** [EssentialsX/Essentials#165]
Boolean in the config to change how receiving money works. 
If the boolean is true, instead of sending a message to the player that they received money, it should be sent via action bar. If set to false, nothing should be different.

**Comment by Kakifrucht** [comment]
There is currently no Title API.

**Comment by Agazed** [comment]
They would need to use NMS for Titles, which won't ever happen because it breaks on new versions.

**Comment by drtshock** [comment]
not going to use nms
