### ISSUE TITLE
Silent join vanish shown on tablist

### ISSUE THREAD

**Issue by baticag** [EssentialsX/Essentials#1650]
When a player who has a permission essentials.silentjoin.vanish joins the servers, he is vanished, but appears on tablist until he doesn't disable and enable vanish again.

Can you please fix this?

**Comment by caojohnny** [comment]
Unable to reproduce, I suggest closing this.

**Comment by mdcfe** [comment]
If anyone can reproduce this, feel free to reply to this issue and we'll reopen it.
