### ISSUE TITLE
Any way to null the Symbol?

### ISSUE THREAD

**Issue by madtomic** [EssentialsX/Essentials#1652]
Set this to a currency symbol you want to use.
Remember, if you want to use special characters in this document, 
such as accented letters, you MUST save the file as UTF-8, not ANSI.
currency-symbol: ''

I could use a space but it's ugly.

**Comment by DrewAMitchell** [comment]
@madtomic There's not, with the current implementation. I've tried putting special escape codes or whatnot, but if you set it to empty quotes, it defaults to $.
