### ISSUE TITLE
Can Essentials be moved up to java 8? 

### ISSUE THREAD

**Issue by NJDaeger** [EssentialsX/Essentials#1653]
I understand that Essentials aims for backward compatibility, but Java 7 is no longer supported and shouldn't be used in the first place. I personally would really love to be able to use some of Java 8's features with essentials. It would make my life easier and code look nicer. Thanks.

**Comment by mdcfe** [comment]
EssentialsX supports Java 8 servers without any problems. If absolutely necessary, you can recompile EssentialsX targeting Java 8.

**Comment by NJDaeger** [comment]
I know I can compile with it, but I want to be able to actually use Java 8 in development. Out of the thousands of servers, essentials is on, there are only like 70 that are on Java 7 (they really should expect support drops from everything at this point). Can I use Java 8 features in development?

**Comment by mdcfe** [comment]
If you change the build target to Java 8 (and use JDK 8 or above), you can use features introduced by Java 8.

**Comment by NJDaeger** [comment]
Sounds good. I'll change the target version in the travis yml and maven. Thanks! (Btw there will probably be a PR coming implementing Java 8 features where possible if you don't mind)
