### ISSUE TITLE
Is there a way to embolden text in messages_en.properties?

### ISSUE THREAD

**Issue by Kyle-Mar** [EssentialsX/Essentials#1654]
Hello, I just have a simple question. Is there any possible way to embolden the text in the messages_en.properties file? If not that is fine, I would just like to know.

I don't know if i can mark my post as a question or not so if an administrator could to that for me that would be great.

**Comment by mdcfe** [comment]
You can use `\u00a7` followed by the relevant [formatting code](http://wiki.ess3.net/mc/).

For example, `\u00a7lHello` would produce **Hello**.
