### ISSUE TITLE
Problems with grouping on /list

### ISSUE THREAD

**Issue by timbirtles** [EssentialsX/Essentials#1661]
Hi,
For some reason, I cannot get users groups to show up upon typing /list. I want all users to be in their own group, meaning staff and donators and normals can be identified easlier. 
For some reason when you type /list it is still putting them all in the same group.

If anyone can see why this is, and can edit the config for me, that would be great!

EssentialsX version (`/essentials`):  2.0.1-b488

Server software (`/version`): 1.12

EssentialsX config (if applicable): 
[https://pastebin.com/xLGPm27D](https://pastebin.com/xLGPm27D)
`

**Comment by mdcfe** [comment]
Under the `list` section, you can specify grouping for the `/list` command. For example, if you had the groups `staff` and `donators` and wanted them to appear in `/list` as `Staff` and `Donators`, you could do this:
```yaml
list:
    Staff: staff
    Donators: donators
```

You could also add a line like `Players: "*"` to change the `default` group's name in `/list`.

For more information, see [this Essentials wiki page](http://wiki.ess3.net/wiki/List).

**Comment by Drkmaster83** [comment]
@Inspectiver Have you had any luck fixing your issue? In your config, you have:
`Admins: owner staff`
@md678685 I just tested with PEX and build 547 on 1.12.2
https://i.imgur.com/pAUcDjq.jpg
Configuration
`list:
    # To merge groups, list the groups you wish to merge
    #Staff: owner admin moderator
    Admins: owner admin
    Members: default
    # To limit groups, set a max user limit
    #builder: 20
    # To hide groups, set the group as hidden
    #default: hidden
    # Uncomment the line below to simply list all players with no grouping
    #Players: '*'`

**Comment by timbirtles** [comment]
Ah, yes, I forgot to say, it works now, thankyou!
