### ISSUE TITLE
Essentials X XP Bug 

### ISSUE THREAD

**Issue by Mr4Skinz** [EssentialsX/Essentials#1666]
I thought you must get tired of reading peoples threads so I decided to submit a video response instead.
https://youtu.be/YfQk-BeY98g

EssentialsX version (`/essentials`): 
2.0.1-b488
Server software (`/version`): 
Latest 1.7.10/1.8 paperspigot
EssentialsX config (if applicable):

**Comment by mdcfe** [comment]
Please write out the issue in addition to the video, as it's much less convenient to follow a link and watch a video (even if it helps in some cases).

Edit: didn't intend to close this.

**Comment by Mr4Skinz** [comment]
When I add xp using the following command /xp set 1000 (I had 0 xp prior to adding the xp) It displays that I have 1700 instead of 1000.
https://i.imgur.com/g4CoNEt.png

**Comment by Mr4Skinz** [comment]
@md678685 What do you think is causing this issue?

**Comment by mdcfe** [comment]
I'm not sure at the moment, but I suspect this is intentional and is related to the 1.8+ experience calculations.

**Comment by Mr4Skinz** [comment]
@md678685 Are you able to fix it?

**Comment by Mr4Skinz** [comment]
@md678685

**Comment by SaltfuricAcid** [comment]
A server I am currently working for is also experiencing this issue. It seems like a calculations issue, and should be fixable with some math adjustments based on version number, assuming it isn't neccesary to maintain the odd calculation shifting. Can you update on your efforts to fix it, or explain why it's needed, @md678685?

**Comment by mdcfe** [comment]
I haven't had a chance to look at the experience code, so I don't have an update on this yet. If someone else is interested in this, feel free to look into it.

**Comment by caojohnny** [comment]
You are running PaperSpigot 1.7.10; it is not compatible with the EssentialsX and hasn't been for the past 2 years. The way that experience was calculated changed between 1.7.10 and 1.8, see: https://github.com/EssentialsX/Essentials/commit/3634cab1a5209bb621322be8a9e18aa4d531508c.

If you want EssentialsX to work correctly on 1.7.10, you will need to use 2.0.1-b304 or before, or update your PaperSpigot.
