### ISSUE TITLE
Cooldown between last message in chat and /nick

### ISSUE THREAD

**Issue by baticag** [EssentialsX/Essentials#1670]
Greetings,

On my server we are trying to solve this situation:
Player A: hey guys
Player B: hey mate
Player A: /nick Fucker
Player A (shown as ~Fucker): YOU ASS NOOBS BLA BLA BLA
Player A: /nick off
Player B: /realname Fucker (output: There is no player with that name)

Our solution is that between the last message sent to the chat and the command /nick should be the delay/cooldown configurable in config which will stop them from changing the name quickly and let the other players use the /realname command to find their realname and report them to the staff.

It would be cool if you could add this!
Thank you in advance!

**Comment by mdcfe** [comment]
For now, you can configure a [command cooldown](https://github.com/drtshock/Essentials/wiki/Command-Cooldowns) for the `/nick` command, which would prevent people from changing their nicknames too regularly, though it doesn't solve this problem entirely.

**Comment by baticag** [comment]
That won't fix the problem :/

**Comment by drtshock** [comment]
Enable social spy and watch the player switch names?

**Comment by baticag** [comment]
Situation without moderators online...

**Comment by drtshock** [comment]
Not hard to grep logs for this :\

**Comment by triagonal** [comment]
As drtshock mentioned above, it wouldn't be difficult to go through logs and find the user doing this given the message and/or approximate time. This seems unnecessary for the majority of Essentials users.
