### ISSUE TITLE
Help command only displays commands that are registered in the plugin yml

### ISSUE THREAD

**Issue by NJDaeger** [EssentialsX/Essentials#1672]
The current way essentials runs the help command is it looks for commands through plugin yml's. This is an issue for some developers and users. I know quite a few developers use things such as ACF and other various tools which register commands directly into the server CommandMap. To solve this issue, I have made a PR which, rather than looking through the plugin yml's, it looks through the CommandMap and displays all commands and plugins no matter how they were registered. 

Please review the PR: #1659

**Comment by mdcfe** [comment]
Please don't create issues to bump your PR - we'll review your PR when we get a chance.
