### ISSUE TITLE
Clear command confirmation.

### ISSUE THREAD

**Issue by MineServidorCraft** [EssentialsX/Essentials#1676]
I have some problem but i don't know what plugin give me this command. A month ago users could change bedrocks (which cost 20k in the sv) per permissions, the elevator etc ... we used several blocks of commands, to detect the bedrocks and delete them, then we gave permission. To erase we used the clear @p 7 N (N = number of bedrocks). 
Now he does not let us use the clear and the users get the permissions for free. And this is because the clear now needs to be confirmed or deactivated. It can be deactivated by individual but not in general. Does anyone know how to remove it or in some config put by default that no confirmation is needed? https://imgur.com/a/DSomA

EssentialsX version (`/essentials`): EssentialsX2.0.1-b #545 (15-nov-2017 18:20:05)

Server software (`/version`):  PaperSpigot-B1155

I think you can add in the config something like this:

Confirmate clear:

Confirmation on in the begining: true / false.

Because i can't use the command blocks with clear right now, i can't put some command for don't need the confirmation.

**Comment by MineServidorCraft** [comment]
What I can do? Wait for new version where this confirmation works better or go another version where clear and item replace good well (?) If i go another version, which version recommend me?

**Comment by mdcfe** [comment]
This may be implemented in the future. In the mean time, you can use the [vanilla `minecraft:clear` command](https://minecraft.gamepedia.com/Commands/clear).

**Comment by MineServidorCraft** [comment]
I can use it, because when I use the command, it recognizes and picks up the essentials.

**Comment by Techno3600** [comment]
Please implement this in the Config, I find the confirmation very annoying.

**Comment by DrFallen** [comment]
It didn't used to be thing I don't why it was changed.

**Comment by DrewAMitchell** [comment]
For all those wondering what the status of this is, check #1667. There's an extensive amount of discussions as to our options there... @md678685 any closer to a decision? We want to our overlords to decide, we're just the mere peasants haha!

**Comment by drtshock** [comment]
Adding a configuration option is the last thing on our todo list before pushing out a release.

**Comment by DrewAMitchell** [comment]
@drtshock I was more or less asking if any of the options in 1667 had been discussed/decided on. I'd be more than happy to submit a PR attempting to implement it to save you guys time, I just need to know what to work on.

**Comment by FlippantCactus** [comment]
Would love to see a config option added. I'm amazed a "feature" quite as obtuse as this didn't have a config option when implemented. It's clearly causing some people distress, it is also quite annoying when in use.

**Comment by DrewAMitchell** [comment]
@TWSSYesterday Discussion will continue on #1667, I think.

**Comment by drtshock** [comment]
Yes please keep it over there.
