### ISSUE TITLE
Display/playername displaying prefix and suffix

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1679]
Issue I am having with essentials is that when people do /msg or /give or anything that involves a playername it will sometimes display the playername "PLAYER" and other times it will display everything "PREFIX PLAYER SUFFIX" It seems random as to when it will display which one but I figured out if you I dont talk in chat it will simply display my nickname, if I talk in chat then it displays all the PREFIX PLAYER SUFFIX, same goes with other players. I am using ChatControlPro if this matters. I removed every plugin from the server except essentials, vault, protocol lib, and PEX and it still shows the displayname and not the PlayerName. Maybe add an option for this somewhere so people can choose? 

EssentialsX version (`/essentials`): 
EssentialsX-2.0.1 (build #545)

Server software (`/version`): 
Spigot 1.12.2 

Server (logs/latest.log):
Irrelevant 

EssentialsX config (if applicable): 
If needed I will add. Dont think its neeeded.

**Comment by mdcfe** [comment]
Please paste your config on [Gist](https://gist.github.com).

**Comment by ghost** [comment]
https://gist.github.com/MsArtix/c7db9d7083b4b1f622fdf2b3bab8ac64

I have ChangeDisplaName set to true because nicks dont work properly and even with it set to false it still shows the PREFIX PLAYER SUFFIX in commands like /tpa and /give

**Comment by mdcfe** [comment]
Could you post a plugin list? `/plugins`

This doesn't appear to be caused by EssentialsX, as to my knowledge EssentialsX doesn't add prefixes or suffixes to the display name.

**Comment by ghost** [comment]
Plugins: 
https://gyazo.com/62d6e2f0ac6051d3571b63bef1b6764c
I dont know what could be cause it other than essentials itself, reason being is I deleted all but the plugins listed in my original post above and still had the issue.

**Comment by ghost** [comment]
@md678685 The prefix/suffix part might be another plugin but I know for a fact that if I change my nick in essentials when doing /give or /tpa or /msg or anything it changes the name used in those commands.

https://gyazo.com/86357472b6dfcd195a00c524e151194e

**Comment by mdcfe** [comment]
Could you post a screenshot of where the changed display name appears, both when all of your plugins are installed and when only EssentialsX is installed?

**Comment by ghost** [comment]
Here is what happens when all plugins are installed and I do commands like /afk /gm 1 /tpa /give
https://gyazo.com/3d308eaee1f8da2fd34b51e1b3d9524c
I think what is happening is that essentials is asking PEX what the users "displayname" is so it shows the prefix nickname suffix and that is why you see the RANGER before and PRINCESS after the players name as well as mine. When doing /gm 1 and /give it somestimes shows the PREFIX/SUFFIX as well as the nickname and sometimes it does not. (no clue why) 

Here it is without any plugins (essentials only)
https://gyazo.com/fd680bfd242204e63ad99dddfa77a38c 
The nick still appears as change but without the prefix/suffix cause pex is gone. As soon as I turn the nick names off it will all go back to how it should be. 

This is after I did /nick off for both accounts. (essentials only)
https://gyazo.com/4fe083a5546f0b88601d27a68b1bc791

**Comment by mdcfe** [comment]
The issue is probably not caused by PEX - to confirm this, try with only EssentialsX, Vault and PEX installed. Checking the startup log may also be helpful to see which plugin EssentialsX is relying on to handle permissions.

**Comment by ghost** [comment]
EssentialsX says on startup it is using vault based permissions (permissionsex)
Here is what it looks like when only those three plugins are installed.
https://gyazo.com/fb05cf009fa5a59fc6e0c185cb204b16
The prefix/suffix are not there, but it still should not be using the nickname for the playername it should be using the actual playername.

**Comment by mdcfe** [comment]
EssentialsX uses the display name for command messages, and the display name is automatically set to the player's nickname if `change-displayname` is true - this is intended behaviour and is not a bug.

Regarding the prefix and suffix, another plugin is adding these to the display name somewhere. I suggest incrementally removing and adding back plugins until you find the culprit, then see if it can be disabled within that plugin.

**Comment by ghost** [comment]
Understandable but when Change-displayname is set to false it does not allow players or myself to change their nickname. So I would have to install another plugin to display nicknames to turn this feature off.

**Comment by mdcfe** [comment]
EssentialsX's display name feature is doing exactly what it's supposed to do. Using any other plugin for nicknames will achieve exactly the same effect.

As far as I can see, the prefix and suffix issue is not related to EssentialsX.
