### ISSUE TITLE
/spawn <player>, /warp <player> should not have a cooldown. /kit should apply armour where slots are free

### ISSUE THREAD

**Issue by TobyMellor** [EssentialsX/Essentials#168]
Hi,
These are just small things that just need to be in. /warp <player> should be instant because, it's by an OP.

When typing /kit, if the kit has armour in it, essentials should try to apply that armour where slots are free. "Armour has been applied where slots are free.".

**Comment by Terrobility** [comment]
Why was this closed?

**Comment by drtshock** [comment]
No idea, he closed it himself. But it's not an issue anyway. Just a case of not reading the instructions.

**Comment by TobyMellor** [comment]
I closed it because the first issue has already been fixed since Spigots version of Essentials.

The /kit thing would be nice, where is the proper place to suggest features?

Thanks,
Toby.

**Comment by Terrobility** [comment]
You can make suggestions here on the issue tracker. It's up to you whether you want to reopen this and modify the title + post, or if you want to make a new issue.
