### ISSUE TITLE
Tempban sentence isn't shown when attempting logn

### ISSUE THREAD

**Issue by Joe7670** [EssentialsX/Essentials#1680]
When a player is tempbanned, the ban message shown is the same as a permanent ban instead of showing tempban details like duration, ban reason, or expiry

**Comment by mdcfe** [comment]
* What versions of EssentialsX and Spigot are you running? `/version` and `/essentials`
* Are you using the default locale or a different language?
* Could you give an example of a tempban command that causes this to happen, with a screenshot of the ban reason screen?

**Comment by Joe7670** [comment]
This server is running CraftBukkit version git-Spigot-00128b5-558c5a3 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
that's the latest version as of now

When pressing /essentials version doesn't come up, but when i type /essentials debug it says i have version 2.0.1-b546

I tempbanned myself for 7 days for reason testing. Which is the command: /ban (me) 7d testing
If I am online and kicked when the ban occurs, the reason and time comes up. When trying to log in again, instead of giving me the banreason and time banned, and all that, it gives this:
![2017-12-06_20 11 27](https://user-images.githubusercontent.com/19633675/33656545-19e23c96-dac2-11e7-91a2-d72ae75e868d.png)

**Comment by Joe7670** [comment]
Sorry, it does give me the reason as shown, but not the other stuff

**Comment by DrewAMitchell** [comment]
@Joe7670 I couldn't replicate this on 1.12.2, EssentialsX build 547. You're sure it's essentials is handling it?

**Comment by mdcfe** [comment]
This appears to be an actual issue, as EssentialsX [does not distinguish between permanent and temporary bans when setting the disconnect message](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java#L361)

**Comment by mdcfe** [comment]
I've submitted PR #1709, which adds a tempban message that should be shown on the disconnect screen instead of the regular ban message when the player is tempbanned. A test build can be found [here](https://keybase.pub/md678685/EssentialsX-2.0.1-pr1709.jar).
