### ISSUE TITLE
TPA Event

### ISSUE THREAD

**Issue by kangarko** [EssentialsX/Essentials#1682]
Hello,

I would love to see a way to catch /tpa event as my users suggested that since I also have /ignore feature in my plugin, they would appreciate if it could also catch the tpa.

Thanks!

**Comment by wyatt-herkamp** [comment]
Should it be called on request or once the request as been accepted?

**Comment by drtshock** [comment]
Catch how?

**Comment by wyatt-herkamp** [comment]
I am thinking event? on /tpa plugin and they have the permission. They will call the event?

**Comment by kangarko** [comment]
It should be handled similarly to https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/net/ess3/api/events/IgnoreStatusChangeEvent.java but with different variables due to the nature of the tpa event. 

It should so be handled before the request so if we cancel it, the other party won't receive a notification message at all.

But anyways, I have already had it workarouned, so feel free to close it.

**Comment by DrewAMitchell** [comment]
@kangarko Can't you close it? It'd be simple to create/call a TPAEvent, but there's a lot of TP types, like TPO and TP, so they probably won't implement an event like this.

**Comment by mdcfe** [comment]
@Drkmaster83 To my knowledge, this is a request for an event for teleport **requests** (`/tpa`). Teleportation itself can be caught with the Bukkit `PlayerTeleportEvent`, but this isn't a good way to do this.

**Comment by DrewAMitchell** [comment]
@md678685 What should we do about the user who requested the /tpa if the event is cancelled?

**Comment by kangarko** [comment]
If the event is cancelled no notification nor teleport should take place imo.

Yes, PlayerTeleportEvent is useful but hacking in and getting to know that it's Essentials' cause is rather obtrusive and I haven't succeeded with it.

Yes you can close is at your will, I already found an alternative solution.

**Comment by triagonal** [comment]
Closed by #1727
