### ISSUE TITLE
Problem with changing "/tpacancel" message

### ISSUE THREAD

**Issue by ACrispyCookie** [EssentialsX/Essentials#1683]
I'm having a small problem on changing the message of the "/tpacancel" command. It
doesn't appear at the messages file. What can I do? Thanks!

EssentialsX version (`/essentials`):  2.0.1

Server software (`/version`): Spigot 1.8.8 

Server (logs/latest.log): https://pastebin.com/HmV0iY8A

EssentialsX config (if applicable): https://pastebin.com/icTvsr6m

**Comment by mdcfe** [comment]
You may need to [copy the new keys over](https://github.com/drtshock/Essentials/issues/1627#issuecomment-342004623) from a newer language file:
> If you haven't made any major changes to your messages file, you can just copy a newer `messages_xx.properties` [from the repo](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/) over your old one.
> 
> If you *have* made major changes however, you can use a three-way merge tool if you know which version of EssentialsX you originally copied your file from. Another way, if you have Python installed, is to download the [most recent `messages.properties`](https://raw.githubusercontent.com/drtshock/Essentials/2.x/Essentials/src/messages.properties) and [this comparison script](https://gist.github.com/md678685/a5e435a79d3431040d91ea9d4b84026d#file-compare-py), put them in an empty directory, copy your messages file to that directory then run the script to see which lines you need to add.

**Comment by mdcfe** [comment]
Choosing due to a lack of response. If this is still a problem, feel free to reopen the issue.
