### ISSUE TITLE
Remove use of all numeric ids

### ISSUE THREAD

**Issue by MiniDigger** [EssentialsX/Essentials#1684]
Since numeric ids will break in 1.13 (and bukkit will not provide 100% backwards combat), all use of them should be removed and replaced with non numeric apis.
see  
https://www.spigotmc.org/threads/minecraft-1-13-what-to-expect.288714/   
and   
https://hub.spigotmc.org/stash/projects/PLUGIN/repos/essentials/compare/diff?sourceBranch=refs%2Fheads%2Fterrible-1.13&targetRepoId=15

**Comment by DoNotSpamPls** [comment]
This issue should've been resolved with the release of the 2.16.0 version
