### ISSUE TITLE
Vanish on join for all staff, without permission 

### ISSUE THREAD

**Issue by FatmanC** [EssentialsX/Essentials#1685]
EssentialsX version (`/essentials`): 

Server software (`/version`): 

Server (logs/latest.log):

EssentialsX config (if applicable): 

Only owner group has all the relevant vanish/silent join/quit permissions
Yet admin and mod groups join silently/part silently and also when they login they are also in vanish
So i added both to the individual users and groups: -essentials.vanish, -essentials.silentjoin, -essentials.silentquit, -essentials.silentjoin.vanish - still having same problem
so i removed the g:vanish_mod from global groups - still happening
in between each step ive tried, user log in vanished, so i get them to un vanish, (getting a message saying vanish is disabled making us visible to users) get them to log out and in to check the permissions went through, but they log back in, in vanish again. Ive gone into their individual user files removed anything even remotely associated with vanish (while they were visible) and same thing still occurs

**Comment by mdcfe** [comment]
Could you run `/ess debug` then paste what appears in the log when an admin joins?

**Comment by mdcfe** [comment]
Closing for to lack of response. Feel free to reopen and/or respond if you still need help.
