### ISSUE TITLE
Warp Signs Saying "That Warp Does Not Exist"

### ISSUE THREAD

**Issue by wonderwally** [EssentialsX/Essentials#1686]
Hey! I'm trying to make warp signs through essentials, and all of the signs in the config have been enabled (I removed the #).
When I do /ewarps, it shows the warps I'm trying to put on the sign. I can manually type /warp wild in the chat, and it takes me there.
The warps are also in the essentials warps folder, just for some reason the sign gives that error. This is what I type on the sign when I try to make it work:
[warp]
wild
My warp is called wild. When I exit the sign, the "wild" part goes away and it is only a blue "warp" with an error message when I right click it.

**Comment by mdcfe** [comment]
* Is this the same for all warps?
* What EssentialsX version are you using? `/essentials`
* What server version are you using? `/version`

**Comment by wonderwally** [comment]
-This is the same for all warps, including ones in both multiverse worlds and newly made ones just for testing purposes.
-Essentials v2.0.1-bSNAPSHOT
-CraftBukkit Version git-bukkit-558c5a3 (MC 1.12.2)
Not exactly sure what those version things mean. Maybe this is a super obvious just-gotta-update solution, haha! Hopefully :)

**Comment by DrewAMitchell** [comment]
Just to be sure, update all the Essentials plugins you use to the [latest Essentials versions here](https://ci.ender.zone/job/EssentialsX/lastStableBuild/). This will eliminate the possibility of version mismatch being the cause.

**Comment by mdcfe** [comment]
@Drkmaster83 Signs are part of the main EssentialsX jar, and no sign-related code has changed for almost half a year.

@wonderwally Could you ensure you are using a Spigot jar rather than CraftBukkit? Your version number indicates you are using CB, which is not supported by EssentialsX.

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to reopen the issue.
