### ISSUE TITLE
NoSuchMethodError on PlayerInteract

### ISSUE THREAD

**Issue by KillerOfPie** [EssentialsX/Essentials#1689]
EssentialsX version (`/essentials`): 2.0.1-b488

Server software (`/version`): 1.12.2

Server (logs/latest.log): https://gist.github.com/KillerOfPie/3fdc662dda648319e233b6b1664c31a4

EssentialsX config (if applicable): n/a

Seems to appear when players use a rocket while flying, don't know if there are any other times. Also do believe that they removed the hashset method which would cause the nosuchmethoderror.

**Comment by mdcfe** [comment]
This has already been fixed. Update EssentialsX to the [latest version](https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild).
