### ISSUE TITLE
Recipe command not functioning properly

### ISSUE THREAD

**Issue by HiddenCloud** [EssentialsX/Essentials#169]
Hello, the recipe command doesn't show the items in the workbench properly:
![wdeipb6](https://cloud.githubusercontent.com/assets/1923024/9541200/39c3d9ca-4d66-11e5-965a-71263feaf32a.png)

**Comment by Agazed** [comment]
Update to latest build. Was fixed in https://github.com/drtshock/Essentials/commit/046752f8c29be2e18898ec4326ca13164d5e7d95
