### ISSUE TITLE
give spawn_egg show null in minecraft chat

### ISSUE THREAD

**Issue by l12436** [EssentialsX/Essentials#1691]
This BUG is trigger by the EntityType that pass to SpawnEggRefl is possible null.
cause set type crash.
I fix it by add a if at SpawnEggRefl.java:98 and variable relative it.

EssentialsX version (`/essentials`): 
2.0.1-bSNAPSHOT
Server software (`/version`): 
This server is running CraftBukkit version git-Spigot-00128b5-d063cd0 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Server (logs/latest.log):
https://gist.github.com/l12436/c3cad99ec2b08043e565710fd8ff939f
EssentialsX config (if applicable):

**Comment by DrewAMitchell** [comment]
@l12436 What's the command you use to get the error?

**Comment by l12436** [comment]
/give <ID> minecraft:spawn_egg 1 0 {EntityTag:{id:"minecraft:villager"}}

**Comment by DrewAMitchell** [comment]
@l12436 Try to update to the recent builds of EssentialsX.
While this command doesn't execute successfully for me (it says "Error: null"), the data values work for getting the spawn egg. It's possible that there needs to be a re-evaluation of this for spawn eggs. I'm not entirely sure that the command will provide support for JSON, though.

If you need to, you can utilize /minecraft:give to successfully execute your command.

**Comment by l12436** [comment]
I already know why and where the BUG is, and have patched by myself, Did I need to offer that patch that I fixed?
As I remembered, this BUG also occur when I did not add data, (aka. /give minecraft:spawn_egg 1 0)

**Comment by mdcfe** [comment]
@l12436 Feel free to submit a pull request if you feel that you've fixed the issue.

**Comment by mdcfe** [comment]
@l12436 Do you still have your patch for this issue?

**Comment by l12436** [comment]
Sorry for the late response.

You can try this patch，I extract from my commit. This should be the fix of spawnegg null issue.

```
diff --git b/nms/ReflectionProvider/src/net/ess3/nms/refl/SpawnEggRefl.java a/nms/ReflectionProvider/src/net/ess3/nms/refl/SpawnEggRefl.java
index 186b031f..acbaf338 100644
--- b/nms/ReflectionProvider/src/net/ess3/nms/refl/SpawnEggRefl.java
+++ a/nms/ReflectionProvider/src/net/ess3/nms/refl/SpawnEggRefl.java
@@ -94,12 +94,14 @@ public class SpawnEggRefl {
         Object id = NBTTagCompoundConstructor.newInstance();
         Method tagSetString = ReflUtil.getMethodCached(NBTTagCompoundClass, "setString", String.class, String.class);
         
-        String idString = type.getName();
-        if (ReflUtil.getNmsVersionObject().isHigherThanOrEqualTo(ReflUtil.V1_11_R1)) {
-            // 1.11 requires domain prefix of minecraft.
-            idString = "minecraft:" + idString;
+        if (type != null) {
+	        String idString = type.getName();
+	        if (ReflUtil.getNmsVersionObject().isHigherThanOrEqualTo(ReflUtil.V1_11_R1)) {
+	            // 1.11 requires domain prefix of minecraft.
+	            idString = "minecraft:" + idString;
+	        }
+	        tagSetString.invoke(id, "id", idString);
         }
-        tagSetString.invoke(id, "id", idString);
 
         Method tagSetTag = ReflUtil.getMethodCached(NBTTagCompoundClass, "set", String.class, NBTTagCompoundClass.getSuperclass());
         tagSetTag.invoke(tagCompound, "EntityTag", id);
```

**Comment by mdcfe** [comment]
I can't replicate this on current builds of EssentialsX with 1.8.8.

**Comment by l12436** [comment]
I almost forget I have submit this issue before.

the new command that is tested. 
`/give player minecraft:spawn_egg 1 0 {EntityTag:{id:"minecraft:rabbit"}}`

EssentialsX version (/essentials):
[21:46:13 INFO]: EssentialsX 2.17.1.16
Server software (/version):
This server is running CraftBukkit version git-Spigot-e8ded36-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT

now the error become no item name as spawn_egg. I need to use monster_egg to spawn it.
![image](https://user-images.githubusercontent.com/2596649/64025528-736f6780-cb6f-11e9-9604-f75ba5e0f9b2.png)
and if I change to monster_egg, the error appear
![image](https://user-images.githubusercontent.com/2596649/64025651-bfbaa780-cb6f-11e9-8721-e5b01927ccc3.png)
![image](https://user-images.githubusercontent.com/2596649/64025682-d234e100-cb6f-11e9-8529-cb8ba27b79aa.png)

Hope this will help you

**Comment by mdcfe** [comment]
As far as I know, if you use NBT then the SpawnEggProvider shouldn't even be involved. The providers aren't necessary when you use NBT, so it looks like the provider is being called when it shouldn't be. If anyone could look into this, I'd appreciate it - I'm a bit busy at the moment.

**Comment by pop4959** [comment]
Unable to reproduce this issue. If it's still present, please feel free to make a PR for it (or explain how it can be replicated on a newer version of  Essentials).
