### ISSUE TITLE
How to restrict /fix to certain items

### ISSUE THREAD

**Issue by nblockbuster** [EssentialsX/Essentials#1692]
EssentialsX version (`/essentials`):  Unable to get

Server software (`/version`):  Spigot 1.12.2-R0.1-SNAPSHOT (27 versions behind)

Server (logs/latest.log): Unable to get, i am admin without FTP access

EssentialsX config (if applicable): nope

I am wondering how to restrict /fix of certain items and each time for a certain price, and if it can be done, i wil tell the head of staff or owner how to do it (he is currently on vacation)

**Comment by mdcfe** [comment]
While you can't prevent people from repairing items, you can set a cost using the [`command-costs` section](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/config.yml#L607) of your config (eg `repair-278: 200` for a diamond pickaxe).

**Comment by DrewAMitchell** [comment]
@nblockbuster2500 Is the solution md678685 proposed suitable?

**Comment by mdcfe** [comment]
Closing for to lack of response. Feel free to reopen and/or respond if you still need help.
