### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1693]
All messages are not changing. No errors in console/logs.

**Comment by mdcfe** [comment]
* Where is your messages file located, and what is it called?
* Have you set `locale` in your `config.yml`?
    This will force EssentialsX to load a specific language file.
* Have you **restarted your server** (not just reloaded EssentialsX) since updating your language files?

**Comment by ghost** [comment]
1. Where is your messages file located, and what is it called? - 
 1.1. server files/plugins/EssentialsX
 1.2. messages_en.properties
---------------------------------------------------------------
2. Have you set locale in your config.yml?
 2.1. 
```yaml
# Set the locale for all messages.
# If you don't set this, the default locale of the server will be used.
# For example, to set language to English, set locale to en, to use the file "messages_en.properties".
# Don't forget to remove the # in front of the line.
# For more information, visit http://wiki.ess3.net/wiki/Locale
#locale: en
```
---------------------------------------------------------------
3. Have you restarted your server (not just reloaded EssentialsX) since updating your language files?
  3.1 Yes.


First my messages worked i changed some colors,words now its not changing.

**Comment by mdcfe** [comment]
Can you try copying a fresh locale file to your EssentialsX config folder?

In addition, please post a startup log from your server on [Gist](https://gist.github.com).

**Comment by ghost** [comment]
Sorry, didin't undarstand this part - Can you try copying a fresh locale file to your EssentialsX config folder?

**Comment by mdcfe** [comment]
Download a clean copy of the [relevant messages file](https://github.com/drtshock/Essentials/tree/2.x/Essentials/src) and replace the existing messages file in your EssentialsX folder with the new one.

**Comment by ghost** [comment]
Still nothing .... 
Maybe i need to remove # in #locale: en ?

**Comment by mdcfe** [comment]
If you're using English, I would suggest using `messages.properties` instead of `messages_en.properties`.

**Comment by ghost** [comment]
Ok i will try 2 more things if not  fixes i will write here

**Comment by ghost** [comment]
Ok so i replaced my old messages_en.properties with original messages_en.properties. 

At line antiBuildBreak=\u00a74You are not permitted to break\u00a7c {0} \u00a74blocks here. i added word TAIP at the end to test if its working. I started my server, joined the server i tried braking some block and it shows me antiBuildBreak=\u00a74You are not permitted to break\u00a7c {0} \u00a74blocks here but not with the word TAIP at the end.... I dont know what to do more...

**Comment by mdcfe** [comment]
Please post a startup log from your server on [Gist](https://gist.github.com).

**Comment by ghost** [comment]
Here you go - https://gist.github.com/Wrohi/1bf8d737a37289673aad7a7101f69fdb .

**Comment by ghost** [comment]
I made very stupid mistakes not even in a code or something. Im really sorry for wasting your time. Good luck in life and thanks for trying to help me !
