### ISSUE TITLE
kits do not support any type of repair cost modifier

### ISSUE THREAD

**Issue by DalBrar** [EssentialsX/Essentials#1694]
EssentialsX version (`/essentials`): 2.0.1-b547

Server software (`/version`): Spigot 1.12.2-R0.1-SNAPSHOT

Server (logs/latest.log):

EssentialsX config (if applicable): 
Kits:
  godsword:
    delay: 0
    items:
      - DIAMOND_SWORD 1 name:&bGod_Sword lore:The_sword_that_killed|all_of_human_kind damage_all:1985 vanishing_curse:1

Is there a way to add a "repair cost" so that kits can give items that cannot be repaired? Also a damage modifier to be able to give "used" items?

**Comment by jbarradas** [comment]
+1 Need RepairCost in a Kit

**Comment by pop4959** [comment]
Not sure if this is possible ATM without NMS but will keep it open since this kind of sounds like a thing that could be added as item meta.
