### ISSUE TITLE
messages_pt_BR.properties don't work

### ISSUE THREAD

**Issue by br-Rigonatti** [EssentialsX/Essentials#1695]
I already found the error in a few lines of the file

please, check that and fix, or tell me how can I post a fixed file. Thanks. I want to help here with pt_Brazilian support!

**Comment by mdcfe** [comment]
Have you set `locale: pt_BR` in the config?

You can edit the [relevant messages file](https://github.com/drtshock/Essentials/tree/2.x/Essentials/src/messages_pt_BR.properties) on GitHub then submit a pull request with your changes

**Comment by br-Rigonatti** [comment]
yes but there are some errors in the file ex: 

essentialsHelp1=O arquivo est\u00E1 corrompido e o Essentials n\u00E3o consegue abri-lo. Essentials desativado. Se `voc\u00AA` n\u00E3o consegue arrumar o arquivo sozinho, acesse http\://tiny.cc/EssentialsChat
essentialsHelp2=O arquivo est\u00E1 corrompido e o Essentials n\u00E3o consegue abri-lo. Essentials desativado. Se `voc\uuea` n\u00E3o consegue arrumar o arquivo sozinho, digite /essentialshelp no jogo ou acesse http\://tiny.cc/EssentialsChat

And others more, so the file is not loading.

Thanks, I'm sorry for any inconvenient.

**Comment by br-Rigonatti** [comment]
Here is the original file from EssentialsX 2.0.1-b488


[messages_pt_BR.zip](https://github.com/drtshock/Essentials/files/1551000/messages_pt_BR.zip)

**Comment by mdcfe** [comment]
I don't see what the issue is. If you're referring to the content of those messages in particular, they are intended to be there as they are shown by EssentialsX.

**Comment by br-Rigonatti** [comment]
The word você is tu e issue11

**Comment by br-Rigonatti** [comment]
The word 'você' is using diferents formats, that isso causing error And do not load, loading the en file, I shown above only 1 error, but there More.

**Comment by mdcfe** [comment]
You need to replace special characters like `ê` with their corresponding escape code. You can find a reference of escape codes [here](https://www.rapidtables.com/code/text/unicode-characters.html).

**Comment by br-Rigonatti** [comment]
But don't you see, the file having 2 differents format character in a same word? tha't happening in many word, I want to fix it and would like you insert in a original file essentialsx.jar, this problem don't let messages_pt_BR.properties work.

**Comment by mdcfe** [comment]
Apologies; didn't realise what the issue was.

As I'm not sure exactly what these characters are supposed to be, I can't correct them in the original language file, but feel free to [submit a PR](https://github.com/drtshock/Essentials/edit/2.x/Essentials/src/messages_pt_BR.properties) if you can help.

**Comment by br-Rigonatti** [comment]
no problem my friend, I already send a PR thanks!

**Comment by br-Rigonatti** [comment]
however I think I'll need send another cause realize the translation is not complete, but I'll check it out!

**Comment by Logics4** [comment]
From my experience, wouldn't save messages.properties as UTF-8 solve the problem? Or is it already in UTF-8?
