### ISSUE TITLE
Separate heal & feed cooldowns

### ISSUE THREAD

**Issue by ArtelGG** [EssentialsX/Essentials#1697]
I would like to suggest that you separate /heal and /feed cooldowns.

So instead of this: `heal-cooldown: 60`
It could be:
```
cooldowns:
  feed: 60
  heal: 60
```

And any other commands similar to these. (It would be nice to have a cooldown on /msg and /mail send

**EssentialsX version**: 2.0.1-b547
**Server software**: TacoSpigot 1.8.8

**Comment by drtshock** [comment]
You can already do this https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/config.yml#L518
