### ISSUE TITLE
Could not pass event PlayerInteractEvent to Essentials v2.0.1-b488

### ISSUE THREAD

**Issue by connorhsm** [EssentialsX/Essentials#1698]
Not quite sure whats going on here? But its repeating whenever a player is interacting with the world.

EssentialsX version (`/essentials`): v2.0.1-b488 

Server software (`/version`): Spigot 1.12.2

Server (logs/latest.log): 14.12 05:58:13 [Server] ERROR Could not pass event PlayerInteractEvent to Essentials v2.0.1-b488
14.12 05:58:13 [Server] INFO org.bukkit.event.EventException: null
14.12 05:58:13 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot131.jar:git-Spigot-3d850ec-809c399]
14.12 05:58:13 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot131.jar:git-Spigot-3d850ec-809c399]
14.12 05:58:13 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot131.jar:git-Spigot-3d850ec-809c399]
14.12 05:58:13 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot131.jar:git-Spigot-3d850ec-809c399]
14.12 05:58:13 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [spigot131.jar:git-Spigot-3d850ec-809c399]
14.12 05:58:13 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202) [spigot131.jar:git-Spigot-3d850ec-809c399]
14.12 05:58:13 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198) [spigot131.jar:git-Spigot-3d850ec-809c399]
14.12 05:58:13 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:989) [spigot131.jar:git-Spigot-3d850ec-809c399]
14.12 05:58:13 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) [spigot131.jar:git-Spigot-3d850ec-809c399]
14.12 05:58:13 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot131.jar:git-Spigot-3d850ec-809c399]
14.12 05:58:13 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot131.jar:git-Spigot-3d850ec-809c399]
14.12 05:58:13 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
14.12 05:58:13 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
14.12 05:58:13 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot131.jar:git-Spigot-3d850ec-809c399]
14.12 05:58:13 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot131.jar:git-Spigot-3d850ec-809c399]
14.12 05:58:13 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot131.jar:git-Spigot-3d850ec-809c399]
14.12 05:58:13 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot131.jar:git-Spigot-3d850ec-809c399]
14.12 05:58:13 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot131.jar:git-Spigot-3d850ec-809c399]
14.12 05:58:13 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
14.12 05:58:13 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getTargetBlock(Ljava/util/HashSet;I)Lorg/bukkit/block/Block;
14.12 05:58:13 [Server] INFO at com.earth2me.essentials.signs.SignPlayerListener.onSignPlayerInteract(SignPlayerListener.java:41) ~[?:?]
14.12 05:58:13 [Server] INFO at sun.reflect.GeneratedMethodAccessor236.invoke(Unknown Source) ~[?:?]
14.12 05:58:13 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
14.12 05:58:13 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
14.12 05:58:13 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot131.jar:git-Spigot-3d850ec-809c399]
14.12 05:58:13 [Server] INFO ... 18 more

EssentialsX config (if applicable): *Let me know if needed

**Comment by Mishyy** [comment]
Are you by chance using a custom server jar?

**Comment by mishyy** [comment]
This error does not appear to make sense, from what I saw in the code.

**Comment by connorhsm** [comment]
Nothing changed to what I downloaded from Spigtmc.com.

**Comment by connorhsm** [comment]
I'm going to re-produce this & then re-install Spigot and then attempt to re-produce.

**Comment by mishyy** [comment]
Have you tried using one of the builds from the build server?

**Comment by connorhsm** [comment]
I have not, what is the difference?

**Comment by mishyy** [comment]
The version currently hosted on Spigot is much older whereas the build server has the latest.
Which I believe is what this issue is.

**Comment by connorhsm** [comment]
Oh okay. Do you have a link on hand?

**Comment by mishyy** [comment]
It should be in the description of the project, https://github.com/drtshock/Essentials

**Comment by mdcfe** [comment]
Update to the [latest version](https://ci.akpmakes.tech/job/EssentialsX/lastSuccessfulBuild).
