### ISSUE TITLE
Essentials /jump

### ISSUE THREAD

**Issue by Johandrex** [EssentialsX/Essentials#170]
The "essentials.jump" permission stopped working after that I updated from #189 to #194. When they have the permission it says "You are not permitted to do that. Are you in the right mode?"

**Comment by Johandrex** [comment]
Fix this! I've waited for 20 days!!!

**Comment by Kakifrucht** [comment]
Fix it yourself. You are in no position to demand service.

**Comment by Johandrex** [comment]
How shall I fix it.. I'm not a coder. This is the place to report bugs in isn't it?

**Comment by Kakifrucht** [comment]
Yes it is, you are simply not in a position to write "Fix this!", nobody will follow your order. This is not how this works.
You can either a) pay somebody to fix it for you, b) fix it yourself, or c) wait until somebody takes care of it

**Comment by Johandrex** [comment]
Alright thanks. I'll wait some weeks for this fix then.

**Comment by vemacs** [comment]
We haven't changed anything regarding /jump compared to upstream, so it's not our issue. Your entitled attitude isn't helping.
