### ISSUE TITLE
Spawn commands not working

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1706]
EssentialsX version (`/essentials`): 2.0.1-b488

Server software (`/version`): git-Spigot-3d850ec-809c399 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Server (logs/latest.log): https://pastebin.com/X8PqWyg0

EssentialsX config (if applicable): https://pastebin.com/e2ivfiEz

the ./spawn and ./setspawn commands are not working, multiverse's ./mv spawn and ./mv setspawn are working

**Comment by LaxWasHere** [comment]
You are running an outdated version, please download the latest version at https://ci.akpmakes.tech/job/EssentialsX/lastSuccessfulBuild/

**Comment by ghost** [comment]
@LaxWasHere  thanks that fixed it! The other EssentialsX plugins besides the spawn and main one in that link you gave are not working though :( GEOIP and stuff. Also what is the XXMPP one for, it is the only one I did not install.

**Comment by QuantumScience** [comment]
what is the XXMPP one for, it is the only one I did not install

**Comment by LaxWasHere** [comment]
You just need EssentialsX and EssentialsxSpawn, no need to install all of them.

Please close the issue if the problem is fixed.

**Comment by DrewAMitchell** [comment]
@QuantumScience http://wiki.mc-ess.net/wiki/XMPP
Not likely you need it. It's for something really complicated.
GeoIP isn't that relevant, either, but if you need it to work, well... I doubt you need it, but...
If you do, I guess that's for another issue.

**Comment by ghost** [comment]
Okay, thanks for the help guys!
