### ISSUE TITLE
Reserve Support

### ISSUE THREAD

**Issue by creatorfromhell** [EssentialsX/Essentials#1707]
Hello, I'm the developer of Reserve, which aims at bringing a modern Economy API to the Bukkit API. I'd appreciate it if you looked over the API, and possibly implemented it into EssentialsX. If you need help implementing it, just let me know. https://www.spigotmc.org/resources/reserve.50739/

Thanks,
creatorfromhell

**Comment by mdcfe** [comment]
We're always open to PRs that add support for new features.

The payment method system that EssentialsX uses can be found in the `com.earth2me.essentials.register.payment` package - you'll want to implement the [`Method` interface](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/register/payment/Method.java) in a class within `com.earth2me.essentials.register.payment.methods` then initialise it in the [`Methods` class](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/register/payment/Methods.java). This will allow your plugin to provide an economy system for EssentialsX **to use**.

The Essentials Economy API can be found at `net.ess3.api.Economy`, if you want to allow EssentialsX to provide its economy system to other plugins.

**Comment by SupaHam** [comment]
@creatorfromhell Please add an FAQ answering why Reserve is better than Vault for your own sake. I'm not sure I see much of a difference for us compared to Vault.

**Comment by creatorfromhell** [comment]
@SupaHam I suppose you're right, and I'll add better explanation in the documentation of the differences, but that was more of the design decision for Reserve; from a non-economy provider perspective that was the goal. The magic happens when you get into economy providers, and the nitty gritty of the API.

**Comment by pop4959** [comment]
Closing this issue since your PR is self-declared dead.
