### ISSUE TITLE
Messages issue

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#171]
Hey

For some reason when people do /back , /home or such it will show up with "You have x messages! Type /mail read to view your mail."

Any chance this could be changed?

**Comment by Kakifrucht** [comment]
Well, if they have messages, this is the expected behaviour? Or are you saying that they don't actually have any messages?

**Comment by ghost** [comment]
They have messages, but I only want it to come up when they join the server and at least not each time you do a command, as it can be a bit hard to keep track on the chat.

**Comment by drtshock** [comment]
If you read your mail then it wouldn't happen.
