### ISSUE TITLE
Playerlist nick problem

### ISSUE THREAD

**Issue by Lunatik934** [EssentialsX/Essentials#1710]
Hey I have a problem when I set "change-playerlist: false" for disable the nick in the tab(playerlist) it not work :x 

EssentialsX version (`/essentials`): 2.0.1 b550

Server software (`/version`): This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Server (logs/latest.log):

EssentialsX config (if applicable): change-playerlist: false

**Edit by @md678685: Moved details from the comment block into the issue**

**Comment by mdcfe** [comment]
~~Please add more detail. What exactly is happening?~~

Edit: nevermind - it appears the details were in the comment block, so I've edited the OP.

Could you paste your full config on [Gist](https://gist.github.com/)?

**Comment by Lunatik934** [comment]
https://gist.github.com/Lunatik934/664d2fff55da0101b4489dc0461b5202

**Comment by DrewAMitchell** [comment]
Perhaps you have another plugin that handles it?
Either that or... maybe (and this is unlikely, but considering all options) the playerlist name is stored to be that somehow?

**Comment by Lunatik934** [comment]
idk :x

**Comment by mdcfe** [comment]
Could you paste a plugin list?

**Comment by Lunatik934** [comment]
I use animated names it's a problem with this ?

**Comment by mdcfe** [comment]
Potentially; could you try removing plugins you think may be causing this?

**Comment by Lunatik934** [comment]
fixed ty
