### ISSUE TITLE
/enchant response

### ISSUE THREAD

**Issue by ArtelGG** [EssentialsX/Essentials#1711]
The response for /enchant (no arguments) is always null regardless of the item you're holding. The only exception to this is if you're holding air.

EssentialsX version (`/essentials`): 2.0.1-b547
Server software (`/version`): TacoSpigot 1.8.8

**Comment by DrewAMitchell** [comment]
In 1.12, Build 547, the no item in hand message sends when air is in the hand.
With anything but air, it sends the usage message followed by a list of applicable Enchantments to the item you're holding.

Must be a 1.8 issue.

**Comment by drtshock** [comment]
https://github.com/TacoSpigot/TacoSpigot/blob/version/1.8.8/pom.xml#L14 they set the version incorrectly which breaks our check. Issue on their end.

**Comment by ArtelGG** [comment]
Very strange, I've never had issues with the /enchant responses before... I'll look into updating.
