### ISSUE TITLE
Sign Shop Error: Invalid charge

### ISSUE THREAD

**Issue by Remliwer** [EssentialsX/Essentials#1714]
When i try to Buy or sell in in my sign shop it just says: Invalid charge

**Comment by drtshock** [comment]
Please fill out the questions in the issue template
EssentialsX version (/essentials):

Server software (/version):

Server (logs/latest.log):

EssentialsX config (if applicable):

**Comment by Remliwer** [comment]
Essentials 2x Snapshot

Minecraft 1.12.2

logs: https://pastebin.com/kCyQpjTA


Config: https://pastebin.com/HzEZXfJz

**Comment by DrewAMitchell** [comment]
@Remliwer Have you tried updating to the [latest stable build?](https://ci.ender.zone/job/EssentialsX/lastStableBuild/) Also, what type of sign are you using? Perhaps post a screenshot of the sign to ensure formatting is okay?

**Comment by LaxWasHere** [comment]
You are not running EssentialsX, Please download the latest EssentialsX version at https://ci.akpmakes.tech/job/EssentialsX/lastSuccessfulBuild/

**Comment by Remliwer** [comment]
Thanks, updating did it!
