### ISSUE TITLE
question about versions/builds

### ISSUE THREAD

**Issue by smmmadden** [EssentialsX/Essentials#1716]
At what point will EssentialsX actually increment the version?  We have gone thru hundreds of builds, yet the version remains at 2.0.1.  Seems counter-intuitive if the version that is part of the name never changes doesn't it?  Perhaps with the 1.13 release we move to 2.0.2 or 2.1.0  and then start to increment the versions?

**Comment by mdcfe** [comment]
This isn't an issue. EssentialsX's changes aren't enough to warrant moving to 3.x, but moving to 2.1.x would conflict with Essentials's version numbers. The only suggestion I can make is to jump to 2.15.x, which would skip past all Essentials 2 release numbers, but wouldn't make sense in the context of EssentialsX alone. At the end of the day, EssentialsX's approach of using build numbers works for us.

**Comment by smmmadden** [comment]
Thanks @md678685 - it was only a question, not an issue.  We should have builds and wasn''t implying anything should change on that front.  I was asking about when does version 2.0.1 ever get incremented as an official new release?  Reading many issues, the perception to users is that the version they are using is 2.0.1 which is correct - but there are literally hundreds of builds in that version.  

At what point in time (when is the question) does the version of the plugin should be incremented? Or does it make sense to remove the 2.0.1 from the filename and simply use build numbers instead (which it appears that is more favorable given what you said)?

**Comment by mishyy** [comment]
Essentials does use build numbers to identify different versions.

**Comment by smmmadden** [comment]
@Mishyy - yes, I know what Essentials is using. I'm asking a valid question.  Perhaps an example is in order?
I'm using the build 554 in my servers, and each jar is named similarly (e.g. EssentialsX-2.0.1b554.jar).
Though if I type in /essentials version I see:
[Essentials] Using Spigot 1.7.10+ ServerListPingEvent iterator
Essentials reloaded 2.0.1-bSNAPSHOT.

However, I'm using Spigot 1.12.2+ builds - so a noob could get confused with the first line.
The second line adds zero value since the build number isn't pulled in.
I think the version @md678685 mentioned may be due to what the wiki page shows for current versions, but that appears to be higher than the actual versions shown in the plugins.
![image](https://user-images.githubusercontent.com/10309346/34256304-ab84ad4e-e622-11e7-8255-28a898247e0c.png)

So unless the user puts the build number in the filename, or the version is incremented its hard to tell which one it is on.  The plugin.yml's have the 2.0.1-bSNAPSHOT in it for the version field.  I'm just looking for continuity/consistency in how we increment the versions/builds.

**Comment by LaxWasHere** [comment]
It only says 2.0.1-bSNAPSHOT because the build server failed to replace the build number, something @SupaHam could fix. If you download from https://ci.akpmakes.tech/job/EssentialsX/lastSuccessfulBuild/ it should say the correct build number and your problem should be fixed.

There really is no problem here, the build versions are mainly for us developers.

**Comment by smmmadden** [comment]
not sure what that site is for since I've always used the button for the Jenkins server https://ci.ender.zone/job/EssentialsX/ to download the latest builds as I'm sure other server owners would do.  You're response only acknowledges that it is an issue. lol

Build #'s are not just for developers of that project.  If this was an internal project maybe, but its a public project and used on thousands of servers so it is equally important to a server owner to know what build/version they are on when they have problems - since that's one of the first questions we ask them for. :-)

**Comment by SupaHam** [comment]
I've fixed https://ci.ender.zone build number. :)
