### ISSUE TITLE
Just random errors...

### ISSUE THREAD

**Issue by RainOfPain125** [EssentialsX/Essentials#1718]
EssentialsX version (`/essentials`): Latest Ver

Server software (`/version`): Paper Spigot Latest Build ver #1283

Server (logs/latest.log): [savlatest.txt](https://github.com/EssentialsX/Essentials/files/1579391/savlatest.txt)

EssentialsX config (if applicable): https://pastebin.com/xScBdYJ1

**Comment by LaxWasHere** [comment]
Please update to the latest version of EssentialsX at https://ci.akpmakes.tech/job/EssentialsX/lastSuccessfulBuild/

**Comment by mdcfe** [comment]
You are not running the latest version of EssentialsX - update to the [latest build](https://ci.akpmakes.tech/job/EssentialsX).
