### ISSUE TITLE
/setspawn seems to break the spawn.yml.

### ISSUE THREAD

**Issue by badbones69** [EssentialsX/Essentials#1719]
I seem to be having a problem with EssX atm. I set a spawn but then whenever I reload/start I keep getting an error and it seems to like to crash my server sometimes. I haven't looked into the code atm so I am not sure why its happening.

Error Log: https://hastebin.com/dihazagepa.vbs
Spawn.yml: https://hastebin.com/ilavimulix.http

EssentialsX: 2.0.1-b488

Spigot: git-Spigot-549c1fa-45c8386 (MC: 1.12.2)

**Comment by mdcfe** [comment]
Update EssentialsX and any other modules (Spawn, Chat etc) to the [latest version](https://ci.akpmakes.tech/job/EssentialsX/lastSuccessfulBuild).
