### ISSUE TITLE
Disposal thru commands

### ISSUE THREAD

**Issue by BluPenDragon** [EssentialsX/Essentials#1721]
I'd like to see a command added that would allow the disposal feature to be access via command, its rather annoying to have to get out a sign to throw away junk all the time (being Co-Owner on a server) I'm always building and expanding what we already have whether through command blocks or structure blocks or good old fashion building i am always throwing stuff in and out of my inventory and the sign thing (while being a GREAT idea) could be expanded upon

Spigot 1.10

**Comment by DrewAMitchell** [comment]
So, you want a command that does the same thing as the Disposal sign?

**Comment by TNTUP** [comment]
You can already cleanup your inventory by shiftclicking the red X button in your creative inventory?

**Comment by BluPenDragon** [comment]
@Drkmaster83 yes that would be amazing
@TNTUP shift click the red X clears then ENTIRE Inventory but thats not what i want

**Comment by drtshock** [comment]
Anyone willing to make a PR for this? <3

**Comment by mishyy** [comment]
I could if I managed to work out this command registration system.

**Comment by drtshock** [comment]
Example of how a command can be added https://github.com/EssentialsX/Essentials/commit/c28d749548ed54fb83287c9e7fe9c5a4c78af87f#diff-38157a5986ffd1cbf12316300880d88a
