### ISSUE TITLE
crateplus key in kit

### ISSUE THREAD

**Issue by AkYamin** [EssentialsX/Essentials#1726]
EssentialsX version (`/essentials`): 2.0.1 b556

Server software (`/version`): 1.12.2

Server (logs/latest.log):https://pastebin.com/fMg9jkQH

EssentialsX config (if applicable): https://pastebin.com/BdY2JDtf

the issue is how do i put this item on kit
      '17':
        Type: ITEM
        Item Type: TRIPWIRE_HOOK
        Item Data: 0
        Name: '&bCommon Crate Key'
        Amount: 3
        Enchantments:
        - DURABILITY-1
        Lore:
        - §7Right-Click on a "§bCommon§7" crate
        - §7to win an item!
        - ''
        Metadata:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: §bCommon Crate Key
          lore:
          - §7Right-Click on a "§bCommon§7" crate
          - §7to win an item!
          - ''
          enchants:
            DURABILITY: 1

**Comment by drtshock** [comment]
Read the wiki :) http://wiki.mc-ess.net/wiki/Item_Meta
