### ISSUE TITLE
Issue with EssentialsChat

### ISSUE THREAD

**Issue by RainOfPain125** [EssentialsX/Essentials#1728]
EssentialsX version (`/essentials`): Latest ver 2.0.1-b553

Server software (`/version`): git-Paper-1284

Server (logs/latest.log): No log needed

EssentialsX config (if applicable): Un-needed

When I open my server with EssentialsChat ( https://hub.spigotmc.org/jenkins/job/spigot-essentials/25/ ) console says 

[21:01:09 WARN]: [Essentials] Version mismatch! Please update EssentialsChat to the same version.
[21:01:09 WARN]: Version mismatch! Please update all Essentials jars to the same version.

**Comment by drtshock** [comment]
This isn't spigot essentials. Get essentials chat from us https://ci.ender.zone/job/EssentialsX/
