### ISSUE TITLE
Time set per world

### ISSUE THREAD

**Issue by Platinteufel** [EssentialsX/Essentials#173]
Sorry for repost, but my ticket #135 has been closed.

I have several worlds on my spigot 1.8.8 server and want to allow my users to change the time in only one world. So i gave them essentials.time & essentials.time.set permissions in this world. But now they are also able to change the time in my other worlds with /day day [world] or /day day all. How can I prevent that? 

I'm using PEX for per-world-permissions, but whenever I give them the permissions for changing time in only one world they can use /day day all there to change the time in all worlds. Any ideas please?

**Comment by Joomzy** [comment]
I believe you can give seperate permissions per world with pex. Try that.

**Comment by EvilOlaf** [comment]
@BloodyHarvest is right. PEX supports per world permission setup. Read the documentation for further instructions.
Either you have a problem with your permission setup or there is something wrong with the `time` command.

**Comment by Platinteufel** [comment]
You just can't solve it with per-world-permissions. If you give your players 
essentials.time & essentials.time.set
they can change the time in all worlds with
/day day all
even they have this permissions only in one specific world.

**Comment by drtshock** [comment]
I see your issue now, I'll take a look at it.

**Comment by Platinteufel** [comment]
Thank you! There should be a new permission for
/day day [world] and /night night [world] and essentials.time.set shouldn't allow this commands.

**Comment by Platinteufel** [comment]
Öhm, is a fix still planned? :D

**Comment by SupaHam** [comment]
This feature has been implemented in [build 248](https://ci.drtshock.net/job/EssentialsX/248).

**Comment by Platinteufel** [comment]
Wow, that was fast, thank you!

**Comment by SupaHam** [comment]
I've updated the permissions.

Permissions are as follow:

| permission | description |
| --- | --- |
| essentials.time.world.<world> | Permits the user to set the time in <world>. <world> is the world name with spaces replaced with _. e.g. My World becomes, my_world. |
| essentials.time.world.all | Permits the user to set time of all worlds. |

EDIT: Please consider using [build 250](https://ci.drtshock.net/job/EssentialsX/250).

**Comment by Platinteufel** [comment]
That means I should give my players essentials.time.world.My_World, if they only should be able to change the time in "My World"?

**Comment by SupaHam** [comment]
`essentials.time.world.my_world` correct.

**Comment by Platinteufel** [comment]
Thank you! :+1:

**Comment by Platinteufel** [comment]
Do I still need one of these permissions?
essentials.time
essentials.time.set

**Comment by SupaHam** [comment]
Yes, both `essentials.time` and `essentials.time.set` are required for the command to function.

**Comment by Platinteufel** [comment]
Okay, thanks :)
