### ISSUE TITLE
Bug when /Essentials reload

### ISSUE THREAD

**Issue by iskandarluqman** [EssentialsX/Essentials#1730]
EssentialsX version : 2.0.1-b557 

Server software : Spigot 1.12.2

Server (logs/latest.log): [latest.log](https://github.com/EssentialsX/Essentials/files/1589570/latest.log)

EssentialsX config (if applicable): 

So the problem is when you reload Essentials with /essentials reload. The custom join message doesnt work/break. When a player join it show the default join message. It will work after a server restart but once you do /essentials reload, it show back the default join message. This only affect the custom join message, the custom leave does work fine although after /essentials reload. When they leave the server, it does show the custom leave message. Only the custom join message. Can you fix this bug? Thanks

**Comment by mdcfe** [comment]
Could you [paste your `config.yml`](https://gist.github.com/)?

**Comment by iskandarluqman** [comment]
https://pastebin.com/AwswcAUL

**Comment by mdcfe** [comment]
Cannot replicate on the latest build.

We don't support offline mode servers. Feel free to reopen the issue if you can replicate the issue in online mode and without AuthMe installed.
