### ISSUE TITLE
Error Spamming Console

### ISSUE THREAD

**Issue by VeeKai** [EssentialsX/Essentials#1731]
EssentialsX version (`/essentials`): 
**_EssentialsX 2.0.1-b488_**

Server software (`/version`): 
**_git-Spigot-7754231-94b0980 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)_**

Server (logs/latest.log):
https://paste.codeco.tk/ololekitih.vbs

EssentialsX config (if applicable): 
https://paste.codeco.tk/sexarekari.coffeescript

**Comment by ItzLevvie** [comment]
1) You need to update your EssentialsX to the latest build available @ http://ci.ender.zone/job/EssentialsX
