### ISSUE TITLE
/pay confirmation (suggestion)

### ISSUE THREAD

**Issue by matejokemp** [EssentialsX/Essentials#1735]
Hey,

I have started using your plugin EssentialsX, but there's 1 feature I would like to be added/changed.
You added a /pay confirmation, which can be nice for some people, but we use our own /pay GUI, and so we looked for an option in the config to disable this. But I didn't find any.

So my suggestion/request is that you add an option to disable /pay confirmation in the config, or just a permission to bypass this.

PS; Yes, I'm aware that there's a toggle command, but we need it to be disabled by default.

Thanks!

**Comment by partydragen** [comment]
Yea same as my https://github.com/EssentialsX/Essentials/issues/1667

**Comment by SupaHam** [comment]
If the player is running the command, they will get the confirmation request. They can individually toggle this behaviour by using the `/payconfirmtoggle` or any of its aliases. This behaviour is similar to `/clearinventory`'s confirmation security, making it standard across all servers for safety against malicious intent.

EDIT: Consider making your GUI open another page which asks them to confirm and just have it execute `/pay` again. Although I'm not happy with the following solution, you should be able to give new players a kit when they join the server and have it run the confirm toggle command. For existing players you may edit their files (preferably via a script) to set `confirm-pay`. But that completely defeats the purpose of the introduction of this feature and I highly recommend you go with the former.

**Comment by matejokemp** [comment]
I honestly don't see why it can be an issue to just let it be togglable or just add a permission for it. The point was that there's a confirmation GUI. Not 2.

(almost) everything in essentials is toggleable. I don't see why you're forcing people to have this as a feature. If you really do not want to add a permission or option to disable this (for everyone, I don't need all my players to do /paytoggle), can you just give me the source code so my developers can do this themselves?

EDIT: I found the source code. I guess we'll do it ourselves then, but I really don't see why this can't be added. It's not hard.

**Comment by LaxWasHere** [comment]
@MrMaty @partydragen I've built essentials with confirmations disabled by default. You can find it [here.](https://github.com/AwesomePowered/Essentials/releases)

Please be advised that by using this modified software, you will get no official support from EssentialsX and that you are on your own.
