### ISSUE TITLE
/setspawn not a valid command?

### ISSUE THREAD

**Issue by ImH8** [EssentialsX/Essentials#1737]
EssentialsX version (`/essentials`): newest

Server software (`/version`): bukkit

Server (logs/latest.log): 

EssentialsX config (if applicable):

**Comment by ImH8** [comment]
All permissions are set, and yet everytime I enter /setspawn or /spawn minecraft says "Unknown command"

**Comment by smmmadden** [comment]
Please provide the exact build numbers and what server type/version you are using.  I'm running on Spigot 1.12.2 git-Spigot-b66ad9e-b5a10a9 (which is two builds behind) and EssentialsX plugins 2.0.1-b558 and I don't see this issue.

**Comment by LaxWasHere** [comment]
It means you don't have EssentialsSpawn installed. Download it [here](https://ci.akpmakes.tech/job/EssentialsX/lastSuccessfulBuild/).

And please, provide more info next time instead of just "newest" and "bukkit", actually do the commands provided in the template.
