### ISSUE TITLE
Stacked items

### ISSUE THREAD

**Issue by dvargas135** [EssentialsX/Essentials#174]
1. I have the stacked items
   https://gyazo.com/a392c0b70236f59ecb1e34141c5da5ae
2. I drop the stacked items:
   https://gyazo.com/48d2123b45c7482b36d23d96087d768e
3. I pick up the stacked items:
   https://gyazo.com/fce25af6ee67640fed9f033f21504dda

It doesn't pick them up back to 64 ):

**Comment by Kakifrucht** [comment]
This is the expected behaviour.

**Comment by Agazed** [comment]
Armor is not meant to be stacked.

This is vanilla Minecraft behavior, not Essentials.

**Comment by Cldfire** [comment]
dvargas, this is meant to happen. Nothing's wrong here.

**Comment by dvargas135** [comment]
then could you please make it compatible or make it work? Or either a fix? I really like your plugin

**Comment by Cldfire** [comment]
...why?

**Comment by dvargas135** [comment]
so players can pick up the complete stack of the item

**Comment by Johandrex** [comment]
This is a great suggestion!

**Comment by mdcfe** [comment]
I'm pretty sure this isn't going to be changed as it's vanilla behaviour.
