### ISSUE TITLE
Switching to GeoLite2

### ISSUE THREAD

**Issue by k-jiang** [EssentialsX/Essentials#1745]
EssentialsX version (run `/essentials`): 2.0.1 build 562

Details:
The Legacy GeoLite dat will be discontinued by April 1, 2018. So it is the time to upgrade EssentialsGeoIP to work with GeoLite2 and MaxMind DB.

```
The free versions of the GeoLite Legacy databases available at 
http://dev.maxmind.com/geoip/legacy/geolite/ will no longer be updated 
and free downloads of GeoLite Legacy using the geoipupdate program 
will no longer be available starting April 1, 2018.
```
[https://support.maxmind.com/geolite-legacy-discontinuation-notice/](
https://support.maxmind.com/geolite-legacy-discontinuation-notice/)

**Comment by drtshock** [comment]
Care to make a PR? <3

**Comment by k-jiang** [comment]
#1748 Here you go. @drtshock 
If you have any thought or suggestion of this PR, please let me know. I will try to help more.

**Comment by drtshock** [comment]
<3
