### ISSUE TITLE
EssentialsX Protection Problem

### ISSUE THREAD

**Issue by H1DD3NxN1NJA** [EssentialsX/Essentials#1749]
EssentialsX version (2.0.1-b556): 

Server software (1.8.8): 

Server (l05.01 01:03:40 [Server] ERROR Essentials not installed or failed to load. Essenials Protect is in emergency mode now. 05.01 01:03:40 [Server] INFO Enabling EssentialsProtect v2.0.1-b563`):

EssentialsX config ([](https://pastebin.com/NLNVyBEs)): 

Details: so today out of no where for some reason EssentialsX Protection wont load and players cant Mine, but then can place blocks on the server and i have no idea why, this is the only error i get in console from it

**Comment by drtshock** [comment]
Please post your full server startup log in a https://gist.github.com/

**Comment by H1DD3NxN1NJA** [comment]
https://gist.github.com/H1DD3NxN1NJA/a3b796cc8b3a268466b0c929f9c0cfc9

**Comment by drtshock** [comment]
Why is it all on one line? What server management tool are you using?

**Comment by H1DD3NxN1NJA** [comment]
i have no idea why its in one line, i just copied and pasted it from my console on Mcprohosting

**Comment by drtshock** [comment]
Can you please grab the actual latest.log file https://forums.mcprohosting.com/threads/guide-how-to-access-your-servers-logs-multiple-ways.208/

It's impossible to read what you sent us :\

**Comment by DrewAMitchell** [comment]
@drtshock Wrote a small regex to parse it out/split the lines. :]
https://gist.github.com/Drkmaster83/b40eae70318ea1ccb6415cd346557182

**Comment by drtshock** [comment]
```05.01 01:42:02 [Server] ERROR Essentials not installed or failed to load. Essenials Protect is in emergency mode now. 
05.01 01:42:02 [Server] INFO Enabling EssentialsProtect v2.0.1-b563 
05.01 01:42:03 [Server] INFO Enabling Essentials v2.0.1-b556 
```
Update essentials protect to the same version.
