### ISSUE TITLE
[Suggestion] Repair -> Fix & Cooldowns

### ISSUE THREAD

**Issue by L4BORG** [EssentialsX/Essentials#175]
It would be nice if /repair would be moved to /fix (default command that's shown in /help) since /repair is also Skill used by McMMO

And I guess cooldowns would be nice too (like for /feed).

**Comment by FlippantCactus** [comment]
The main command is /repair, if it changes in the config, https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/commands/Commandrepair.java might as well be changed, along with permissions as Essentials has an "easy to understand" permissions system too. (essentials.repair.enchanted)
