### ISSUE TITLE
Latest essentials, weird issue config,

### ISSUE THREAD

**Issue by Cobwebster** [EssentialsX/Essentials#1750]
notch:
    delay: 6000
    items:
      - 272 1
      - 2 35
      - 1 1
      - 293 1
      - 293 1
      - 278 1
      - 278 1
      - 276 1
      - 276 1
      - 279 1
      - 2 1

Why does this give me  https://gyazo.com/33bc0b1ded2bf2c8241ceef1149f844b ?

gives me 2 of everything for some reason.

**Comment by drtshock** [comment]
Why did you delete the issue template and not fill it out? Please give us your essentials and spigot version info.

**Comment by Cobwebster** [comment]
Sorry,

PaperSpigot 1.12.2, Build #563 (03-Jan-2018 20:40:10)

**Comment by LaxWasHere** [comment]
Because you are literally giving yourself two of everything? Re-read what you've just posted and you'll see.

**Comment by Cobwebster** [comment]
- 279 1 = 1? 
- ItemID : amount

Not sure where I say give 2? I guess i'm overlooking something. it only seems to be the diamond tools giving double, the stone tool which has the same format gives 1.

**Comment by drtshock** [comment]
You list each item twice.
