### ISSUE TITLE
essentials.joinfullserver doesn't work anymore

### ISSUE THREAD

**Issue by xwolfyxNL** [EssentialsX/Essentials#176]
Dear,

Since i switched to to drtshock fork of essentials it seems that essentials.joinfullserver doesn't work anymore.
Could you fix this? :)

Sincerely xwolfyxNL

**Comment by Mikgreg** [comment]
I'm unable to replicate this. Have you made sure that your user groups or any groups in the inheritance chain dont have essentials.joinfullserver negated for whatever reason?

**Comment by drtshock** [comment]
It definitely still works.

**Comment by TomLewis** [comment]
It does not work.
100% have the permission.
