### ISSUE TITLE
EssentialsChat

### ISSUE THREAD

**Issue by marzman1** [EssentialsX/Essentials#1761]
When I download the plugin and upload it to filezilla, there is no EssentialsChat.jar, which I would need to use the EssentialsChat. Why is this happening? 

I need this to use PermissionX right?

**Comment by LaxWasHere** [comment]
EssentialsChat.jar can be obtained here https://ci.akpmakes.tech/job/EssentialsX/lastSuccessfulBuild/

**Comment by mdcfe** [comment]
I'm not aware of a plugin called `PermissionX`, but EssentialsXChat shouldn't be a dependency for any permissions plugin. As @LaxWasHere mentioned, you need to download EssentialsXChat along with the **same version of EssentialsX** from the [build server](https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild) or [mirror](https://ci.akpmakes.tech/job/EssentialsX/lastSuccessfulBuild).
