### ISSUE TITLE
Error on server startup

### ISSUE THREAD

**Issue by dwilley83** [EssentialsX/Essentials#1762]
EssentialsX version (run `/essentials`):  2.0.1-b568

Server software (run `/version`): CraftBukkit version git-Spigot-109b080-bd30843 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Server (`logs/latest.log`) https://gist.github.com/dwilley83/42a5058e7352f5d3288fe7909087210e

EssentialsX config (`plugins/Essentials/config.yml`): https://gist.github.com/dwilley83/c7cc4e6194f211a068dcb9712f3798a8

Details: EssentialsX, EssentialsX-GeoIP, and EssentialsX-Spawn have an error when server is starting up and those plugins won't start. EssentialsX-Protect tries to start but notices that EssentialsX isn't started or installed and disables that plugin. When logging in there is a warning stating that Essentials is in emergency mode and players can't do anything at all, not even exit the game or tab out of it. Downgraded to Build #568 and all EssentialsX plugins load fine with no errors. I think there may be an issue with build #569.

**Comment by DrewAMitchell** [comment]
@dwilley83 I'm running build 569 just fine. Judging from your error, it seems like the Essentials.jar file is either corrupted or unable to be read... double check the file size, if that doesn't work, redownload Essentials, and if that doesn't work, redownload it and try running it without other plugins interfering.

**Comment by mdcfe** [comment]
```java
[17:27:42] [Server thread/ERROR]: Could not load 'plugins/EssentialsX-2.0.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
    ...
Caused by: java.util.zip.ZipException: zip file is empty
```

Your Essentials jar is corrupted or empty - redownload the [latest build](https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild).
