### ISSUE TITLE
Missing Check (Kits)

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1763]
EssentialsX version (2.0.1-b569)

Server software (Spigot 1.8.8)

EssentialsX config (`plugins/Essentials/config.yml`):
https://pastebin.com/zjrgc02H

Details:
Missing check to which of the kits are malformed(unsafe) when the unsafe enchants is deactive and blacklisting all the kits if one of them is unsafe!
It gives this error for  Every kit: That kit is improperly defined. Contact an administrator.

**Comment by mdcfe** [comment]
Did you resolve this issue?

**Comment by ghost** [comment]
Yes i believe it was a type of lag bug. Thanks

2018-01-11 20:22 GMT+02:00 md678685 <notifications@github.com>:
