### ISSUE TITLE
Essentials Not Logging Buy / Sell Commands

### ISSUE THREAD

**Issue by RainOfPain125** [EssentialsX/Essentials#1769]
EssentialsX version (run `/essentials`): version 2.0.1-b557

Server software (run `/version`): git-Paper-1298

Server (`logs/latest.log`): N/A

EssentialsX config (`plugins/Essentials/config.yml`): 
Enable this to log all interactions with trade/buy/sell signs and sell command.
economy-log-enabled: true

https://pastebin.com/PAWznf4f\
Details: Does not do what it appears it's supposed to do. Nothing shows up in console or logs

**Comment by mdcfe** [comment]
You should have a `trade.log` file in your `plugins/Essentials` directory - this file is where all trade interactions should be logged.
