### ISSUE TITLE
lag

### ISSUE THREAD

**Issue by Castiella** [EssentialsX/Essentials#1771]
EssentialsX version (run `/essentials`):  /essentials didnt work, its the recent stable build.

Server software (run `/version`):  paper1129 1.12.2

Server (`logs/latest.log`):
[latest.log](https://github.com/EssentialsX/Essentials/files/1636931/latest.log)

EssentialsX config (`plugins/Essentials/config.yml`): not needed

Details: Essentials commands causing lag on my server, see here: https://timings.aikar.co/?id=c7a8893c4fb54232aa6972d279ad3f42

**Comment by LaxWasHere** [comment]
Looks more to me like Disk IO problems, perhaps put your server on an SSD?

**Comment by Castiella** [comment]
I'm really sorry, but what do you mean?

**Comment by LaxWasHere** [comment]
Your hard drive is slow, get a better hard drive.

**Comment by DrewAMitchell** [comment]
As LaxWasHere said, @Castiella, doesn't appear to be an Essentials problem. The lag of your server is due to its inability to keep up with the map loading/unloading, and entity data being saved/written. It's data input/output that is your problem.

You're running build 570, by the way.

**Comment by Castiella** [comment]
Thank you, I found the issue source and was just making sure it wasn't the plugin. you are literally everywhere, drkmaster haha.
