### ISSUE TITLE
cannot /pay offline players

### ISSUE THREAD

**Issue by aeonlamb** [EssentialsX/Essentials#1772]
This is a pretty minor issue, but I hear there's going to be a full release soon so I thought I should report it because it's something that is a bit of an annoyance on my server. Sometimes, we have a serversign make players /pay an admin account on the server, or just have people directly run /pay <admin account> as a way of giving money back to the server admin account. Problem is, essentials just says it can't find that player even though they do exist.

[see here](https://i.imgur.com/emp1J6U.png)

EssentialsX version: build 559

Server software: Paper 1.12.2

**Comment by mdcfe** [comment]
Could you try running `/baltop` first, then `/pay` again?

**Comment by drtshock** [comment]
Does it work for any offline users ever? Or just sometimes?

If it works sometimes:
Can you show me your spigot.yml? Also how many players join your server? If a player is offline, spigot will cache them according to settings in the spigot.yml. I'm guessing that your cache is set to be really small.

**Comment by aeonlamb** [comment]
Running /baltop first and then trying /pay on an offline player still doesn't work. 

I haven't found any situations where it ever works with offline players at all, no. My server's pretty small, it has a little over 600 total unique players... ever. 

the values from my spigot.yml:

  user-cache-size: 4000
  int-cache-limit: 1024

I'm pretty sure this is actually larger than the default (I had some issues with factions that people told me were due to the cache, but upping it never helped)

**Comment by drtshock** [comment]
Does it ever work to pay an offline user?

**Comment by drtshock** [comment]
Yeah, it looks like pay is not intended to work with offline users. Not sure if that's something we want to even support considering dealing with player caches like that would be annoying and potentially laggy. Perhaps we could /allow/ it as a fall back, but not encourage it? @SupaHam @md678685 any thoughts?

**Comment by mdcfe** [comment]
I personally don't mind either way, though this use case does beg the question: why use a real player's account rather than an NPC?

**Comment by aeonlamb** [comment]
good question... I think there was a reason, but I can't remember it now lol. if it's intended behavior I guess that's fine, just something we gotta work around on the server
