### ISSUE TITLE
Join messages not showing for regular players

### ISSUE THREAD

**Issue by WizzleBear** [EssentialsX/Essentials#1773]
EssentialsX version (run `/essentials`): 2.0.1-b570

Server software (run `/version`): CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Server (`logs/latest.log`):

EssentialsX config (`plugins/Essentials/config.yml`): https://pastebin.com/6xRjBm96

Details: I am trying to add the join message so that every player can see it. However, only I can see them and I am wondering what is wrong. If you want to see my plugins, ask as I don't want random people knowing what I use.

**Comment by LaxWasHere** [comment]
Remove EssentialsXMPP, update your server to the latest minecraft version.

If you didn't want people seeing your plugins, why post your startup log? https://pastebin.com/XX8fNN4w

**Comment by WizzleBear** [comment]
Good point. Mind if you delete the pastebin?

**Comment by mdcfe** [comment]
@GrizzsChannel Please remove EssentialsXMPP as instructed if you're not using it. If that doesn't resolve the issue, update to the latest version of Minecraft.

**Comment by DrewAMitchell** [comment]
@LaxWasHere If you would, lad, delete that pastebin link when you can out of respect.

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to reopen the issue.

**Comment by 0fEfF2Dto4KoNAVZu8cb5** [comment]
Having this same issue and XXMP is not installed. When I change anything from "none", regular players are not able to see it. Players with * permission are able to see the join message. Leave message works fine.

EssentialsX version: 2.17.1.0
Paper Spigot: git-Paper-186 (1.14.4-R0.1-SNAPSHOT)
EssX Conf: https://pastebin.com/6MtZY0SR

**Comment by mdcfe** [comment]
@mcgrenoa Is there any chance you could post a startup log?

**Comment by 0fEfF2Dto4KoNAVZu8cb5** [comment]
Startup Config: https://pastebin.com/iNR3gERq

**Comment by 0fEfF2Dto4KoNAVZu8cb5** [comment]
@md678685 I just did some troubleshooting, No luck. Some players with * permission can see it, but other groups can't. Soooooo bizarre.

Clarification: other groups with * permission as well.

**Comment by mdcfe** [comment]
@mcgrenoa Apologies for the slow response. Could you open a separate issue for this?
