### ISSUE TITLE
Back command not to last position

### ISSUE THREAD

**Issue by LoXR** [EssentialsX/Essentials#1776]
EssentialsX version (run `/essentials`):  Essentials version 2.0.1-b569

Server software (run `/version`): version git-Paper-1305 (MC: 1.12.2)

Server (`logs/latest.log`):

EssentialsX config (`plugins/Essentials/config.yml`): https://pastebin.com/0NcmQevW

Details: Players have reported that /back doesn't take you back to the last position it takes you back to the position before your last. If other owners are having this problem, they would know about this situation.

**Comment by mdcfe** [comment]
`register-back-in-listener` is false, so to my knowledge only death location (and possibly EssX teleports) will be stored by the plugin and not most other teleportation.

**Comment by LoXR** [comment]
Okay, so enabling that should fix my problem?

**Comment by mdcfe** [comment]
It *might* fix what you think the problem is, but at this stage it is impossible to tell whether that is the issue or something else.

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to reopen the issue.
