### ISSUE TITLE
AFK Tab list 

### ISSUE THREAD

**Issue by sidboy55555** [EssentialsX/Essentials#1777]
I use the latest Essentialsx and the latest spigot. and when I was afk my friend notite that my name in the tablist was strange (see picture). my config: https://pastebin.com/3m3aAiuY
![unknown](https://user-images.githubusercontent.com/9865110/35152069-244eab3e-fd21-11e7-9ed3-1036bc3ec642.png)

**Comment by drtshock** [comment]
Can you please give us your essentials version string. Type `/essentials version` and tell us the out put :)

**Comment by LaxWasHere** [comment]
Lol

**Comment by mdcfe** [comment]
You need to surround the value of `afk-list-name` with quotes:
```yaml
afk-list-name: "{USERNAME}"
```
