### ISSUE TITLE
&nbsp problem

### ISSUE THREAD

**Issue by Erthinarius** [EssentialsX/Essentials#1778]
EssentialsX version (run /essentials): 2.0.1-b577

Server software (run /version): CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Server (logs/latest.log): gist https://gist.github.com/Erthinarius/ebd7641f18c25fc95db3e030a3a8bf24

EssentialsX config (plugins/Essentials/config.yml): gist https://gist.github.com/Erthinarius/ebd7641f18c25fc95db3e030a3a8bf24

https://imgur.com/rNDWoy4
https://imgur.com/YkTj08h
(Sorry, I don't know how to upload screens on git)

**Comment by LaxWasHere** [comment]
**PLEASE follow the issue template**

EssentialsX version (run `/essentials`): 

Server software (run `/version`): 

Server (`logs/latest.log`):

EssentialsX config (`plugins/Essentials/config.yml`)

**Comment by Erthinarius** [comment]
Edited

**Comment by drtshock** [comment]
Try using a different text editor. I suggest notepad++ or Atom. It's an issue with your text editor adding extra spaces / characters.
