### ISSUE TITLE
latest build error (/kit)

### ISSUE THREAD

**Issue by SayNada** [EssentialsX/Essentials#1779]
EssentialsX version (run /essentials): Essentials version 2.0.1-b578

Server software (run /version): version git-Paper-1305 (MC: 1.12.2)

Server (logs/latest.log):

EssentialsX config (plugins/Essentials/config.yml): https://pastebin.com/0NcmQevW

Details:

When typing /kit, it doesn't strike through kits you have already redeemed anymore which are still on cooldown after the new feature which brings kits to their own .yml

I think 
kitDelay=\u00a7m{0}\u00a7r

has something to do with it in the messages.properties

please fix this (its after kits were migrated to their own file).
Also /ess reload needs to reload the kits.yml file!

**Comment by drtshock** [comment]
Can you please fill out the template as well.

**Comment by SayNada** [comment]
also doing /ess reload
doesnt reload kits.yml

**Comment by SayNada** [comment]
@drtshock done!

**Comment by drtshock** [comment]
You sure? I'm not seeing any issues on my end. Can you show me a gif of this happening?

**Comment by SayNada** [comment]
here

https://i.gyazo.com/f0bb780e2fa755e07afa70699d179da7.gif

it doesnt show i used the kit

**Comment by drtshock** [comment]
Are you sure that you don't have permission to bypass cooldowns?

**Comment by SayNada** [comment]
no i dont @drtshock that was a random minecraft account new to the server i was using

**Comment by mdcfe** [comment]
From a quick glance, I can't see what in cd43355d4c18e12f743092c31a765aaa8451cb1b changed and broke this, but there are quite a few reports of this happening. If someone could look into this, it would be much appreciated.

**Comment by mdcfe** [comment]
Closing in favour of #2301, which appears to be the same bug.
