### ISSUE TITLE
[Request] /ping

### ISSUE THREAD

**Issue by Joomzy** [EssentialsX/Essentials#178]
Could /ping be replaced with an actual command that checks your ping to the server? Currently it's useless and I haven't seen a single server use it.

**Comment by vemacs** [comment]
Minecraft's ping provided in EntityPlayer isn't exactly super reliable (it's easily 50ms+ off). Furthermore, it does require reflection to use: https://gist.github.com/vemacs/1550cac797314a2c841f

**Comment by Joomzy** [comment]
So I presume this wont be added then? Even if it's a bit off. I'd like to have a ping command more then what it does now. Might as well intirely be removed.

**Comment by drtshock** [comment]
It won't be added.
