### ISSUE TITLE
cannot pour lava when deopped

### ISSUE THREAD

**Issue by Blighthorn** [EssentialsX/Essentials#1780]
EssentialsX version (run `/essentials`): Build 578

Server software (run `/version`): This server is running CraftBukkit version git-Spigot-7754231-9a1f5ee (MCL1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT

Server (`logs/latest.log`):

EssentialsX config (`plugins/Essentials/config.yml`): 

Details:

Not - Opped players cannot pour lava from bucket. They CAN place TNT and do everything else properly.
Although blocks 10,11,327 was removed from configuration from Antibuild section.

**Comment by drtshock** [comment]
Please put your log file in a pastebin as well as your config.yml

**Comment by Blighthorn** [comment]
[server log](https://pastebin.com/RdpjfY0V)
[config.yml](https://pastebin.com/cdd3ys4S)
(log has enabled some additionals debug logs from several plugins for additional data)

**Comment by mdcfe** [comment]
What's the issue here? Lava is in the `placement` blacklist, so players aren't supposed to be able to place it.

**Comment by Blighthorn** [comment]
lines 802 to 822 - there is no lava there in config.yml
It was removed by me (block id 10,11,327)

**Comment by mdcfe** [comment]
My mistake - misread the config. Could you enable alerts for placement of lava and see whether alerts are output when players try to place lava and TNT?

**Comment by Blighthorn** [comment]
even for OP I have message in game and nothing in console for TNT.
`Warning: TNT will not destroy blocks above the sea level. `
This appears to be true, and I do not know why.
I added 327 in line 803 so it is now ` on-placement: 46,327`
After save + essentials reload  - nothing still can place as OP, without warning, and no warning for not-op, and no placing too.
added 10 ` on-placement: 10,46,327`  results the same
added 11 ` on-placement: 10,11,46,327` results the same

no warning for lava at all
op can pour lava bucket
not-op cannot pour lava bucket
TNT works with warning for OP, but above sea level it does nothing... which puzzles me more.
edit: of course TNT cannot be placed by not-op because blacklist.
edit2: well interesting that not-op have additional message about not having permission to put TNT here - but that's because of that blacklist. Lava is not on blacklist, and get no message about permission, and still placing by not-op not work.

**Comment by Blighthorn** [comment]
UPDATE:
It is possible to place lava on blocks to Y asis = 91
92 and higher is not possible.  (by not-op).
Is it possible to change it anywhere? I am on aplified, thus lot of people living higher.
I think that "not enough info" tag could be removed.

**Comment by mdcfe** [comment]
Could you run `/ess debug`, then paste the console output when the issues occur?

**Comment by Blighthorn** [comment]
Nothing is catched by /ess debug when I am trying to pour lava bucket.

**Comment by Blighthorn** [comment]
Eveything pointed to Essentials, but this was not the cause. I must apologize you guys. It was another plugin, that I use to prevent loot and exp farms (Antifarm component). It has also World component that I never used, and is disabled, however it seems it still somehow work, even disabled. 
For anyone who will have similiar problem in the future, maybe you have:
[MonsterFix](https://dev.bukkit.org/projects/monsterfix) and its component World, even if disabled have parameter lheight (limit-height) Height value to deny placing forbidden blocks (10 and 11 - as default). 
this value can be raised lets say to 250.
Thank you guys for quick response.

**Comment by mdcfe** [comment]
No worries - thanks for reporting back about Monsterfix.
