### ISSUE TITLE
Warp Error

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1781]
EssentialsX version: 2.0.1.577beta

Server software: CraftBukkit 1.8.8 / Spigot 1.8.8 (On both versions)

Server (`logs/latest.log`):

EssentialsX config (`plugins/Essentials/config.yml`): 
world: world_wild
x: 111.28273470812704
y: 65.0
z: 392.8329642118338
yaw: 84.3341
pitch: 32.936497
name: wild
https://pastebin.com/ArX4UdLS

Details: Hello, i have uploaded an 3rd party world and set it as the default, after this i created a warp. Then i set as default my normal world. I tried to use /warp wild to go there (to the 3rd world) but i got an error (Error: Invalid World). Then i get warps from folder to see if everything was correct. It was okay. But i can't warp there tho.

**Comment by mdcfe** [comment]
Is the world `world_wild` loaded? You need a multiworld plugin to load multiple worlds at once.

**Comment by ghost** [comment]
Hm i think that this is maybe the error thanks ill check it and reply

**Comment by ghost** [comment]
yeap i still have a lot issues after the multi world.
I cant even use /back after i create a new world and teleported the to create a warp.

**Comment by mdcfe** [comment]
Did you set up your multiworld plugin properly? You'll probably need to import your non-default worlds for it to load them.

**Comment by ghost** [comment]
i loaded manual the world and teleported there. no restarts so the world is up and running.

**Comment by DCWizard** [comment]
it propably caused when i changed the default world name

**Comment by DCWizard** [comment]
my mistake for this the perms is not setted well ill set it and reply

**Comment by ghost** [comment]
I get 'the teleport destination is unsafe and teleport-safety is disabled' now
**but that mean that they can teleport right ?
I fixed the location and retried. Its working thanks!

**Comment by ghost** [comment]
Now the back is working to. For a reason
