### ISSUE TITLE
EssentialsGeoIP Exception at startup - build 580

### ISSUE THREAD

**Issue by smmmadden** [EssentialsX/Essentials#1783]
[09:45:40] [Server thread/INFO]: [EssentialsGeoIP] Enabling EssentialsGeoIP v2.0.1-b580
[09:45:40] [Server thread/INFO]: Downloading GeoIP database... this might take a while (country: 1.7 MB, city: 30MB)
[09:45:44] [Server thread/ERROR]: Failed to read GeoIP database!
com.maxmind.db.InvalidDatabaseException: Could not find a MaxMind DB metadata marker in this file (Geo2-City.mmdb). Is this a valid MaxMind DB file?

Full Startup Log: https://pastebin.com/igQEUkP8  (Note that I used a Paid Version of Pastebin so they don't expire).
Minecraft Version: 1.12.2
Spigot Version 1.12.2 git-Spigot-9b8bba4-bdcc7c7 - 1.12.2-R0.1-SNAPSHOT
EssentialsX build 580
Plugins:
![image](https://user-images.githubusercontent.com/10309346/35195411-ed87759c-fe90-11e7-8c51-a79c4e0779b9.png)
![image](https://user-images.githubusercontent.com/10309346/35195413-f9005bb4-fe90-11e7-9ed3-bb72589bf3e5.png)

**Comment by LaxWasHere** [comment]
Are you using the module? Just remove it?

**Comment by mdcfe** [comment]
Could you check the size of the downloaded GeoLite2 database files in `plugins/EssentialsGeoIP`?

**Comment by drtshock** [comment]
@k-jiang ? :)

**Comment by smmmadden** [comment]
sorry for delay, stepped out for a bit.  Here's what I see in my server.
![image](https://user-images.githubusercontent.com/10309346/35199225-5b47cd24-fec9-11e7-9365-328d5bc83641.png)

**Comment by k-jiang** [comment]
The size of unpacked Geo2-City.mmdb should be 60mb. Check your config if download URLs are right. Once modified try delete the mmdb or download it manually from http://dev.maxmind.com/geoip/geoip2/geolite2/ (and don't forget to rename the file).

Check here for the correct URLs:
github.com/EssentialsX/Essentials/blob/2.x/EssentialsGeoIP/src/config.yml

I'm going to create a PR for config migration later on. And I will try to add checksum if I have time.

@smmmadden

**Comment by smmmadden** [comment]
Thanks - that's not the url in the config.yml and i've never touched it to be honest.  I've left the default as it was.
![image](https://user-images.githubusercontent.com/10309346/35200472-fc686e4e-fedc-11e7-86fe-1f09ac85991f.png)
Downloading using the config.yml option directly, show the following sizes:
![image](https://user-images.githubusercontent.com/10309346/35200483-3568f290-fedd-11e7-9fe2-244056d386eb.png)
The link you provided, the file size is just over 60mb.  However, adding it to the folder and restarted still tried to download the file even if I set it to false for download-if-missing probably due to the name being different.  I renamed it to GeoI-City.mmdb and the server started up fine with no warnings.

**Comment by k-jiang** [comment]
Yes the new GeoIP2 got different filename as default. Will make it clear in a new PR.

BTW the new download urls are:
Country: http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz
City: http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz

Make sure you change your config.yml accordingly. Yet I stongly suggest you [replace the config with this one](https://github.com/EssentialsX/Essentials/blob/2.x/EssentialsGeoIP/src/config.yml) since I have add some new features (like auto update the db file).

**Comment by smmmadden** [comment]
Thanks - I've replaced the config.yml with the recommended changes and also enabled show-cities.  Can verify everything looks much better with the downloading and no more exceptions on startup.
Geo2-City.mmdb=61,525 KB
