### ISSUE TITLE
Prefix and Suffix not working properly

### ISSUE THREAD

**Issue by X00LA** [EssentialsX/Essentials#1786]
EssentialsX version (run `/essentials`): 
Essentials 2.0.1-b579
Server software (run `/version`): 
CraftBukkit version git-Spigot-9b8bba4-bdcc7c7 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Server (`logs/latest.log`):
[Pastebin](https://pastebin.com/vkHdC58C)
EssentialsX config (`plugins/Essentials/config.yml`): 
[Pastebin](https://pastebin.com/XyXLXe0Q)
Details:
Pictures say more than a thousand words: [Imgur](https://i.imgur.com/1QByf96.png)

**Comment by LaxWasHere** [comment]
I'm gonna assume that {WORLDNAMESHORT} is not working?

It's supposed to be {SHORTWORLDNAME} as per http://wiki.ess3.net/wiki/Chat_Formatting

**Comment by mdcfe** [comment]
As @LaxWasHere said, the token for shortened world name is [`{SHORTWORLDNAME}`](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/Settings.java#L426).
