### ISSUE TITLE
motd.yml Error

### ISSUE THREAD

**Issue by ArtelGG** [EssentialsX/Essentials#1788]
EssentialsX version (run `/essentials`): 2.0.1-b582
P.S: Running the command `/essentials` just shows `/<command> <reload/debug>`
Server software (run `/version`): TacoSpigot 1.8.8-b29
Server (`logs/latest.log`): N/A
EssentialsX config (`plugins/Essentials/config.yml`): N/A
Details: Having an empty `motd.yml` results in players being messaged "Unknown chapter." every time they connect.

**Comment by mdcfe** [comment]
Either add `motd` to [`disabled-commands` in your `config.yml`](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/config.yml#L147), or revoke the permission `essentials.motd` from users.

[Relevant source](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java#L323)
