### ISSUE TITLE
Admin account becomes invisible when a player relogs

### ISSUE THREAD

**Issue by Agazed** [EssentialsX/Essentials#179]
Didn't feel like writing a paragraph on how to reproduce so heres a video:

https://www.youtube.com/watch?v=Dq3IR4HDcTA

**Comment by drtshock** [comment]
please write a paragraph.

**Comment by Agazed** [comment]
When an admin joins, he is visible to all players that joined before him.

When a player re-logs, the admin becomes invisible and can only be fixed if the admin re-logs or vanishes and unvanishes.

**Comment by Elgorond** [comment]
I remember this bug from Essentials/Spigot-Essentials; a big reason why we stopped using Essentials vanish.

**Comment by mdcfe** [comment]
Closing in favour of #1764, which is the actual bug that causes this.
