### ISSUE TITLE
Prefix and Suffix - second try

### ISSUE THREAD

**Issue by X00LA** [EssentialsX/Essentials#1792]
EssentialsX version (run `/essentials`): 
Essentials 2.0.1-b579

Server software (run `/version`): 
CraftBukkit version git-Spigot-9b8bba4-bdcc7c7 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Server (`logs/latest.log`):
[Pastebin](https://pastebin.com/vkHdC58C)

EssentialsX config (`plugins/Essentials/config.yml`): 
[Pastebin](https://pastebin.com/XyXLXe0Q)

Details:
Changed the wrong variable but the same issue as before: [Imgur](https://i.imgur.com/4Jy5q64.png)

Regards

**Comment by mdcfe** [comment]
Could you run `/ess debug`, then post the console output when someone tries to chat?

**Comment by X00LA** [comment]
Hi, thanks for the fast reply!
Here's the console output: [Pastebin](https://pastebin.com/SgcLqP6t)

**Comment by mdcfe** [comment]
Big oversight on my part when I wrote #1663 - prefixes and suffixes never get parsed. I'm working on fixing this at the moment.

Edit: could you replace your build of EssentialsXChat with [this build](https://keybase.pub/md678685/essx/EssentialsXChat-2.0.1-issue1792.jar)?

**Comment by X00LA** [comment]
I've tested your build, but this wont fix it. Here's a screenshot of it: [Imgur](https://i.imgur.com/55CZYIw.png)
I'm going to sleep, it's 10 pm here. So I cant answer the next few hours.
Good Night.

**Comment by mdcfe** [comment]
Could you elaborate on ehich part isn't working now?

**Comment by X00LA** [comment]
Hi, sorry for my late reply.
In the picture [HERE](https://i.imgur.com/I1KrqOM.png) you can see what differences in the messages shown up.

Regards

**Comment by mdcfe** [comment]
Just to clarify - is it the short world name that isn't working properly?

**Comment by X00LA** [comment]
It's interesting.
When I replace the {SHORTWORLDNAME} variable the output looks like [L] X00LA.

Here's the ess debug log from the console:
[16:51:42 INFO]: X00LA[/127.0.0.1:51356] logged in with entity id 127 at ([CGN-Spawn]20.0, 70.0, 156.0)
[16:51:42 INFO]: [Essentials] checking if X00LA has essentials.sleepingignored - false
[16:51:42 INFO]: [Essentials] looking up groupname of X00LA - default
[16:51:42 INFO]: [Essentials] checking if X00LA has essentials.motd - false
[16:51:42 INFO]: [Essentials] checking if X00LA has essentials.mail - false
[16:51:42 INFO]: [Essentials] checking if X00LA has essentials.fly.safelogin - false
[16:51:42 INFO]: [Essentials] checking if X00LA has essentials.speed - false
[16:51:51 INFO]: [Essentials] checking if X00LA has essentials.chat.color - false
[16:51:51 INFO]: [Essentials] checking if X00LA has essentials.chat.magic - false
[16:51:51 INFO]: [Essentials] checking if X00LA has essentials.chat.format - false
[16:51:51 INFO]: [Essentials] checking if X00LA has essentials.chat.url - false
[16:51:51 INFO]: [Essentials] looking up groupname of X00LA - default
[16:51:51 INFO]: [Essentials] attempting to charge user X00LA
[16:51:51 INFO]: [Essentials] calculated command (chat) cost for X00LA as 0
[16:51:51 INFO]: [Essentials] charge user X00LA completed
[16:51:51 INFO]: [L]<X00LA> Hello there!
[16:51:51 INFO]: [Essentials] attempting to charge user X00LA
[16:51:51 INFO]: [Essentials] calculated command (chat) cost for X00LA as 0
[16:51:51 INFO]: [Essentials] charge user X00LA completed
[16:51:51 INFO]: [L] X00LA : Hello there!

I'm using your build. Schould i use the regular build instead?

**Comment by mdcfe** [comment]
What did you replace `{SHORTWORLDNAME}` with? It looks like another plugin is adding the `[L]`.

**Comment by X00LA** [comment]
Your'e right. I was reorganizing my permission database and have forgotten to change the prefix of the tables.
Now I have created two scenarios:

1.  Scenario with all plugins disabled exept LuckPerms, Essentials (Core, Chat, AntiBuild, Spawn and Protect) and Vault.

2. Scenario with all Plugins disabled  exept Essentials /Core, Chat, AntiBuild, Spawn and Protect) and Vault.

[HERE'S](https://pastebin.com/KrvsihTm) the Ess-Debug from the console.
[HERE'S](https://i.imgur.com/OlZPAYg.png) the image from this attemps.
[HERE'S](https://pastebin.com/1YtDLzkj) my Essentials config.yml.

P.S.: I also got this `multiplayer.player.joined` issue with the used essentials build.

**Comment by mdcfe** [comment]
I've pushed the fix to the repo, so you can safely update to the [latest official builds](https://ci.ender.zone/job/EssentialsX).

I'm not sure what is causing this. Does it still occur when all of your plugins except EssXChat are enabled?

**Comment by X00LA** [comment]
I'm sorry. but the last build does'nt solve the issue. :(
[HERE'S](https://pastebin.com/gG7jtTqJ) my console output with /ess debug.
[HERE'S](https://i.imgur.com/7V0O3td.png) a screenshot how it looks like with the newest version. All activated plugins, Spigot version and Essentials version in the chat output.

**Comment by mdcfe** [comment]
As I said, could you try disabling EssentialsXChat? This will show whether it is related to EssentialsXChat or not.

**Comment by X00LA** [comment]
Oh sorry, I overseen it. I'm very tired, sitting about 13 hours on my pc. Time for bed! :/
I tested it without Essentials Chat. All issues are gone. [HERE'S](https://i.imgur.com/567GeCI.png) the screenshot from it. It looks like the issue comes definetively from Essentials Chat.

Regards

**Comment by mdcfe** [comment]
Any chance you could rename your config temporarily and restart the server? This will help eliminate the chance of a config being the issue.

**Comment by X00LA** [comment]
That's interesting, I renamed my config and let the plugin create a new one. See [HERE](https://i.imgur.com/ANfPcZX.png). The only things I changed in Chat section you can see [HERE](https://pastebin.com/vG09GDSF) my full config (old one) [HERE](https://pastebin.com/1YtDLzkj). I looked into the two files and compared it, but I can't see anything that could be the trigger for this.

UPDATE!
I found out what happens! The problem is, that {DISPLAYNAME} shows the whole information! Prefix, Displayname and Suffix! So if  anyone defines the suffix and prefix separately it creates that error!

**Comment by mdcfe** [comment]
You can remove the prefix showing up in your display name by setting `add-prefix-suffix` to false.

If the issue is resolved, feel free to close the issue.

**Comment by X00LA** [comment]
Works perfect now!
Thank you for your great and fast help!

Regards
