### ISSUE TITLE
Empty motd.txt - Unkown chapter

### ISSUE THREAD

**Issue by baticag** [EssentialsX/Essentials#1794]
If motd.txt file is empty Unknown chapter message is send to player on login.

I think it's because of this commit, because it didn't happen before it.
https://github.com/EssentialsX/Essentials/commit/ef1e57f4456093291f3f0ff5852201f40bcddda3

**Comment by drtshock** [comment]
@AgentTroll want to take a look at this?

**Comment by caojohnny** [comment]
I will get to it ASAP

**Comment by mdcfe** [comment]
@baticag If you're not using the motd, I'd suggest adding `motd` to `disabled-commands` to prevent EssentialsX trying to send a MOTD.

**Comment by Flavourized** [comment]
This is still an issue on b591. 

Deleting motd.txt & reloading essentials regenerates the motd.txt file.
Deleting all contents of motd.txt & reloading essentials returns Unknown Chapter

Adding motd to disabled commands fixes it.

**Comment by caojohnny** [comment]
The changes have not been pulled yet, so yes, it is still an issue.
