### ISSUE TITLE
[Request] Can usage command message's be added into properties.

### ISSUE THREAD

**Issue by Remski01** [EssentialsX/Essentials#1795]
EssentialsX version (run `/essentials`): 
2.0.1-585
Server software (run `/version`): 
Spigot 1.12.2
Server (`logs/latest.log`):

EssentialsX config (`plugins/Essentials/config.yml`): 

Details:
I mean message when you ONLY type as example /pay /tpa /gm etc,

**EDIT: 
Short version.** 

Can be usage message commands be added? The message's what you get after you only typed the command. (With no urgemment)

**Comment by LaxWasHere** [comment]
Could you elaborate more? Do you mean more commands contexts?

**Comment by Remski01** [comment]
Yes. The blank message's. 
As example:"
https://ibb.co/b5Rr4G

**Comment by DrewAMitchell** [comment]
So... you're wanting to add the usages of the commands... to the messages.properties.

**Comment by mdcfe** [comment]
There isn't any point adding the usage messages to `messages.properties` unless we're planning to overhaul how usage messages work, which I doubt is going to happen.

**Comment by Remski01** [comment]
Yes. The usage message's. 

And the "There isn't any point adding the usage messages to messages.properties". If an server is english and it follow the same style as EssentialsX. Then yes. Its a bit useless. But if an server is not english. And the chat style is so much difr then the blank white one. its a bit annoying. So if it can added its really helpfull for non-english servers.

**Comment by mdcfe** [comment]
Related: #1865
