### ISSUE TITLE
Config auto updater

### ISSUE THREAD

**Issue by Sikatsu** [EssentialsX/Essentials#1797]
Would it be possible to implement an auto config updater? Turns out my config was quite outdated.

**Comment by drtshock** [comment]
Not without erasing comments in the config :\

**Comment by Sikatsu** [comment]
Good point. Maybe if an update gets released from now on, link the config from github with all the config changes? So that we can manually see what has been removed, added or moved?

**Comment by drtshock** [comment]
Yes, that's why I'm working on more detailed release notes for when we push out updates :)You can see initial notes for the next release here https://github.com/EssentialsX/Essentials/wiki/2.0.2

**Comment by mdcfe** [comment]
The point of including build numbers in condos was to allow people to do a three-way merge between the original config, a user's edited config and the most recent config. If you have a versioned config, you can look at the diffs between your config and the new one.
