### ISSUE TITLE
Essentials Directory Cleanup

### ISSUE THREAD

**Issue by Sikatsu** [EssentialsX/Essentials#1798]
Maybe it would be a nice idea to put certain things into a folder. Like all of the .txt files, usermap files and such. Looks more clear.

**Comment by drtshock** [comment]
Can you give some specific examples

**Comment by Sikatsu** [comment]
Userdata
Warps
Txt (containing all .txt files)
Csv (containing usermap.csv and items.csv)
config.yml
kits.yml
jail.yml
spawn.yml
worth.yml

**Comment by LaxWasHere** [comment]
Too much work when barely anyone looks at the Essentials folder. imo.

**Comment by mdcfe** [comment]
I don't see what this achieves, other then making it slightly harder to find files?

**Comment by Sikatsu** [comment]
I don't see why it would become slightly harder to find files? Currently there are a lot of files in the directory making it look messy. Ofcourse, I don't know how much work it would be.

**Comment by mdcfe** [comment]
Because it's an extra folder to navigate from either a command line or file manager.

This would also result in inconsistencies between EssentialsX and the original Essentials documentation, which while it might not seem like an issue, it creates unnecessary confusion for new users.

**Comment by drtshock** [comment]
I don't think this is necessary.
