### ISSUE TITLE
Add configurable auto-reply when using /msgtoggle

### ISSUE THREAD

**Issue by justwheel** [EssentialsX/Essentials#180]
Referring commit 891605380ffcc52671f3e6874a28b32f16ffce58, suggestion #89:

I think `/msgtoggle` is a useful command; however, I think before I'd actually use it, I'd like to have a message sent to people who message players with that mode enabled. So if someone is actually trying to message something important, they can at least be given relevant information about where to go to get a response, e.g. "Make a ticket using /ticket, go to our website server.com and make a thread, etc." sort of thing.

A generic message applicable to anyone could be added, but of course it should be able to be modified in the `messages.properties` file. I think this would make this command very useful for medium and small-sized servers especially.

This could be implemented as a permission, so in addition to granting `essentials.msgtoggle`, there could be a permission node for `essentials.msgtoggle.noreply` to prevent that message from being sent. At least, I feel like this is the best way to implement it.

Thanks for your time!

**Comment by Agazed** [comment]
+1 this

Don't know what devs will think as this has been discussed before

**Comment by EvilOlaf** [comment]
+1. I always wanted something that tell people who sends wisps "blame someone else" :grinning:

**Comment by Mikgreg** [comment]
+1. Although I think I have seen @drtshock say this feature isn't planned to be added it's very useful.

**Comment by drtshock** [comment]
My thoughts were to add a message for it and like other messages, if you remove it from the messages file it just won't be sent.

**Comment by Kakifrucht** [comment]
Sounds good

**Comment by justwheel** [comment]
That sounds like a good way to implement it.

**Comment by drtshock** [comment]
There ya go :) You'll have to add that to your messages file if you're already using a custom one.

**Comment by justwheel** [comment]
Thanks, confirmed to work!
