### ISSUE TITLE
nickNamesOnlyColorChanges missing from default language file.

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#1800]
Noticed 'nickNamesOnlyColorChanges' is missing from the default messages.yml language file. It is present in my old messages_en.yml file.

```
nickNamesOnlyColorChanges=\u00a74Nicknames can only have their colors changed.
```

**Comment by mdcfe** [comment]
This was fixed in 752565b8f1412c645a1b91a682576330186af52c - all future builds should now include this key.
