### ISSUE TITLE
Global config option to enable/disable confirm pay / clearinventory by default.

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#1801]
https://github.com/EssentialsX/Essentials/commit/fcc7c3af78d664b259685044531bec1d323a3088#commitcomment-27061223

**Comment by Kakifrucht** [comment]
So right now it is not possible to globally require the confirmation?

**Comment by mdcfe** [comment]
Not yet - it's being worked on.

**Comment by mibby** [comment]
@md678685 Do you know how long it would take to re-implement as a default state config toggle? People got used to the confirming of /ci since it was present for months, now it is dangerous being open again. :(

**Comment by mdcfe** [comment]
@mibby The solution in #1816 or another solution will be merged when we've decided on how best to approach this.

**Comment by mdcfe** [comment]
Closing as this was implemented in #1816 a while ago.
