### ISSUE TITLE
Bug with giving money to an offline player/UUID

### ISSUE THREAD

**Issue by denizaygundev** [EssentialsX/Essentials#181]
Giving money to an offline player or UUID doesn't work, it goes into some separate account and not the actual user's account. Almost as if there's 2 users, an offline and an online one. Using Essentials-X build 194.

Also as for evidence: http://puu.sh/jVdoC.jpg

I gave the same UUID $1000, once when online and once when offline. 

Thanks.

**Comment by drtshock** [comment]
What 2 users did you try this with? Are you typing out the exact name? Has the player been online since the last restart? What's your spigot user cache?

**Comment by denizaygundev** [comment]
I tested with the username "QubeCraft", and his UUID: 14229e79-10ce-4898-ac93-74ebe2d6f366
Another test: http://puu.sh/jWvPr.png

This occurred after another user didn't receive their money from a rank they purchased through a webstore as they were offline and the money went into an offline account of some sort. 

Anyway I just tested on another alt "QubeCraftMC" and can now 100% confirm that giving money to an offline UUID does not work:
Test 3: http://puu.sh/jWvKB.png

And what do you mean by my spigot user cache?

**Comment by denizaygundev** [comment]
My Spigot config for "cache" is:
  user-cache-size: 1000
  int-cache-limit: 1024

**Comment by drtshock** [comment]
Wait, when did we say that you can type the UUID to send it to the player offline? Just type their name...

**Comment by denizaygundev** [comment]
I just assumed that was a thing especially as Enjin encourages you to use UUIDs instead of usernames.

I'll just use the username anyway but thought adding UUID support for sending money offline should be a thing.

**Comment by drtshock** [comment]
It's not.
