### ISSUE TITLE
GeoIP: Could not find a MaxMind DB metadata marker in this file 

### ISSUE THREAD

**Issue by Astrareach** [EssentialsX/Essentials#1812]
Version : DEV 5​88 24 janv. 2018 19:25 (2.0.1-b588)
Error : https://pastebin.com/z5Nqhz9A
Description : An error appear everytime a player connect to the server 
Server software : CraftBukkit version git-Spigot-4bd94dc-c765646 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
EssentialsX config (`plugins/Essentials/config.yml`): https://pastebin.com/6SXF0B8d

**Comment by Astrareach** [comment]
Error on server start : https://pastebin.com/2LTip3eM

**Comment by LaxWasHere** [comment]
Try the fixes here https://github.com/EssentialsX/Essentials/issues/1783

@k-jiang

**Comment by mdcfe** [comment]
Could you [update to the latest build](https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild) and report back whether this issue still occurs?

**Comment by k-jiang** [comment]
#1784 should have this fixed already. Please try the [build here](https://ci.ender.zone/job/EssentialsX/590/).
Sorry for the bug. @Noiknez 

If you still experiencing the problem, please let me know with your GeoIP's config.yml.

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to reopen the issue.

**Comment by Astrareach** [comment]
Hello, I managed to fix the problem by deleting the folder
