### ISSUE TITLE
Bug with [Sell] Shift Click Selling

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [EssentialsX/Essentials#1814]
**Note:** I tried using https://gist.github.com/ but it kept asking for filename with extension and denied everything I tried to put into it. 

EssentialsX version (run `/essentials`): 
Doesn't work.
https://gyazo.com/b8f023767a7f0a29791386e20bb62cbb

Server software (run `/version`): 
https://gyazo.com/b4310c23e9f1f9162c04aa8caf0310b1

Server (`logs/latest.log`):
https://pastebin.com/jE69KMTR

EssentialsX config (`plugins/Essentials/config.yml`): 
https://pastebin.com/06SStkhs

Details:
When players try selling an item using a [sell] sign they will shift click and it sells a stack at a time. That part is working fine. BUT it **only** works fine if the player is holding the item. If not, it goes back to selling at the lower stated amount on the sign (such as 16). Please make it so it doesn't matter what item the player is holding when they try to shift click the sell sign to sell items.

**A GIF of what's happening:**
https://gyazo.com/cda05ee840b273fefc60cd6c96c725dd

**Comment by mdcfe** [comment]
This is [deliberate](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/signs/SignSell.java#L35); this decision was made ([presumably](https://github.com/EssentialsX/Essentials/issues/65#issuecomment-234661169)) to prevent players accidentally bulk selling the wrong item.

cc @SupaHam
