### ISSUE TITLE
Annoying [L] in front of Name (EssChat)

### ISSUE THREAD

**Issue by X00LA** [EssentialsX/Essentials#1815]
EssentialsX version (run `/essentials`): 
Server software (run `/version`): 
[Screenshot](https://i.imgur.com/w3paTHA.png) with all informations you need.

Server (`logs/latest.log`):
[Latest Log](https://pastebin.com/c4YgVXh4)

EssentialsX config (`plugins/Essentials/config.yml`): 
[Ess-Config](https://pastebin.com/vJYtvhw7) I'm using.

Details:
You can see that I'm using the latest build of EssentialsX and I got this annoying [L] in front of my name. First I was thinking it is from another plugin, but it wasn't. It's definetly from EssentialsChat.
I use no mods in my client and, as you can see in the screenshot, there are no other plugins installed.

Regards

**Comment by xBMAN88** [comment]
![image](https://user-images.githubusercontent.com/8965862/35483218-9c8f7eb4-040d-11e8-91b4-9903749c92d8.png)

You have LocalChat enabled; change the number to zero to disable it.

**Comment by X00LA** [comment]
Oh my! This is that! Man! Could'nt find any description of that! Now its clear!
Thank you!
