### ISSUE TITLE
[Essentials] Task #39239 for Essentials v2.0.1-b590 generated an exception

### ISSUE THREAD

**Issue by straZX** [EssentialsX/Essentials#1819]
EssentialsX version (run `/essentials`): 2.0.1

Server software (run `/version`): 1.7.10

Server (`logs/latest.log`):

EssentialsX config (`plugins/Essentials/config.yml`): 

Details:

**Comment by LaxWasHere** [comment]
You are running an **unsupported** (1.7) version, please follow the instructions on how to build the latest craftbukkit/spigot at http://www.spigotmc.org/wiki/buildtools/

**Comment by mdcfe** [comment]
EssentialsX no longer supports Minecraft 1.7.10. Update to a more recent Minecraft server for support. (Not to mention we have literally no idea what the error is without a log.)
