### ISSUE TITLE
Data loss bug

### ISSUE THREAD

**Issue by ACrispyCookie** [EssentialsX/Essentials#1820]
EssentialsX version (run `/essentials`): 2.0.1-b589

Server software (run `/version`): PaperSpigot 1.8.8-R0.1-SNAPSHOT

Server (`logs/latest.log`): https://hastebin.com/eluxacinay.md

EssentialsX config (`plugins/Essentials/config.yml`): https://hastebin.com/kirutimope.vbs

Details: I have a problem. My players have reported that they lose their balance and their inventory after being offline for some hours. Can someone help me?

**Comment by LaxWasHere** [comment]
We do not condone the use of pirated plugins. You've been banned from the discord server and will receive no support whatsoever.

**Comment by mdcfe** [comment]
In addition, this is caused by an inventory management plugin not EssentialsX.

**Comment by ACrispyCookie** [comment]
What about the balances problem?
