### ISSUE TITLE
Loop Protection (/kit)

### ISSUE THREAD

**Issue by ACrispyCookie** [EssentialsX/Essentials#1821]
EssentialsX version (run `/essentials`): 2.0.1-b589

Server software (run `/version`): PaperSpigot 1.8.8-R0.1-SNAPSHOT

Server (`logs/latest.log`): https://hastebin.com/ukosezezip.md

EssentialsX config (`plugins/Essentials/config.yml`): https://hastebin.com/kirutimope.vbs

Details: What does the "Loop Protection! Change the command name or the command output." mean? How can I fix it?

**Comment by mdcfe** [comment]
That doesn't look like an EssentialsX issue.

Could you provide a screenshot or log output where this message appears?

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to reopen the issue.
