### ISSUE TITLE
EssentialsX 2.0.1-b488

### ISSUE THREAD

**Issue by LudnicaKiller** [EssentialsX/Essentials#1825]
EssentialsX version (run `/essentials`):  EssentialsX 2.0.1-b488

Server software (run `/version`):  CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Server (`logs/latest.log`): "Unknown chapter." bug

EssentialsX config (`plugins/Essentials/config.yml`):  https://pastebin.com/fyVr58iC

Details:

I'm using this latest version of plugin and whenever I join the server it writes down in chat, white color "Unknown chapter.". So what is wrong whit this, something in config?

**Comment by drtshock** [comment]
Please stop posting issues to THREE spots. I see all three. I respond to all three. No need to duplicate.

Like i said in PM and on spigot thread 
>Updating to this build https://ci.ender.zone/job/EssentialsX/592/ or anything newer will fix that.
