### ISSUE TITLE
[Request] /exp take command

### ISSUE THREAD

**Issue by ryd4n** [EssentialsX/Essentials#1827]
Would allow the user to specify an amount of experience to be taken from the player similar to the way it currently works with the set command.

Example: `/exp take playerName amount`

**EDIT:** Realised that you can do it by making the given amount negative, but I still think this is a good feature and possibly something to look in to.

**Comment by drtshock** [comment]
(responding after your edit)

Not sure why we would add this with being able to give negative. It works the same way the money command works.
