### ISSUE TITLE
Faction uuid essentialsx chat bug

### ISSUE THREAD

**Issue by xXBarchticXx** [EssentialsX/Essentials#183]
Hello. I am using essentialsx and I realized the placeholder {FACTION} doesn't work in essentials chat.

**Comment by Kakifrucht** [comment]
The placeholder ist [FACTION]

**Comment by drtshock** [comment]
The placeholder is defined in your conf.json and you can see it there. You also need to have EssentialsXChat installed for chat to work.

**Comment by xXBarchticXx** [comment]
I have all those installed. It just seems {FACTION} doesn't work.

**Comment by Agazed** [comment]
[FACTION] not {FACTION}
