### ISSUE TITLE
Per group teleport delay

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1830]
Hello! I'm wondering if it would be possible to implement different teleport delays per permission groups, such as [Rank1] having a teleport delay of 10 seconds while [Rank2] having a teleport delay of 2 seconds.

**Comment by Agazed** [comment]
Literally just PRed this a few days ago https://github.com/EssentialsX/Essentials/pull/1826

**Comment by ghost** [comment]
Ah, thank you! I tried searching for open and closed issues about it but I could not find anything relating to the matter.
