### ISSUE TITLE
Where is the currency symbol property in the code?

### ISSUE THREAD

**Issue by TylerMattioli** [EssentialsX/Essentials#1832]
I want to change it from a character to allow multiple characters, or you know, just a string. If anyone can point me to it if they've come across it that would be great.

**Comment by LaxWasHere** [comment]
https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/config.yml#L580

**Comment by TylerMattioli** [comment]
Not talking about in the config. I want to modify how it's handled from what you specify in the config. It trims the string to choose the first letter for the currency.

**Comment by TylerMattioli** [comment]
Think I found it
https://github.com/EssentialsX/Essentials/blob/738efe8c50b817324c361ea2d178cfc2d2d67bca/Essentials/src/com/earth2me/essentials/Settings.java#L640
