### ISSUE TITLE
Suggestion: Translating with Crowdin

### ISSUE THREAD

**Issue by enterih** [EssentialsX/Essentials#1836]
Hello everyone 

I have the idea, that in the future this plugin will translate with crowdin: https://crowdin.com/ . Minecraft and some other plugins use it for translate because it's easier for people like me. It has specially functions for files from special places like github. It would be nice, if someone use little time to checkup the possibility.

**Comment by mdcfe** [comment]
I believe Essentials used to use Crowdin. Fortunately, it's free for open source projects, but @drtshock would need to apply on behalf of EssentialsX if we decided to use it. Personally, I think that using GitHub PRs alone works fine (though I don't do any translation myself), but I don't mind if people feel it would be better to use Crowdin.

**Comment by enterih** [comment]
Sure
It´s opensource, has github integration and it´s worthy to try out.

But thanks that you are open for this suggestion

**Comment by DoNotSpamPls** [comment]
I'd love if this gets implemented, for example a bot merging new edits every week (if any), instead of relying on slow PRs, which can take weeks(!) to get merged.

**Comment by mdcfe** [comment]
The main reason for the delay is that generally someone needs to look over them to make sure they are actually useful PRs. If Crowdin were to automatically merge updated translations into EssentialsX, we can't control that process and would have to wait until someone notices malicious changes to revert them.

**Comment by enterih** [comment]
https://de.crowdin.com/translate/minecraft/9385/enus-de

example

**Comment by Madis0** [comment]
+1 for Crowdin, it is the easiest to use translation interface IMO. It would also help leading confused translators to the maintained plugin as the [old one is still not marked as deprecated](https://crowdin.com/project/essentials-2).

>The main reason for the delay is that generally someone needs to look over them to make sure they are actually useful PRs.

That's what proofreaders are for. For example, LineageOS [only uploads translations when they are accepted](https://wiki.lineageos.org/translate-howto.html):

>After the strings have been validated, a scripted job is run (by one of the Managers to import the strings to Gerrit. After a successful test build they get merged to source code and will be part of every new official build.

**Comment by mdcfe** [comment]
@Madis0 The translation project you linked is for the original Essentials. EssentialsX doesn't control that page so we can't add any warning messages there.

The other issue is that we tend to have very few contributors willing to proofread, especially compared to larger projects like LineageOS that have a much larger installed base. For us, translation PRs often stay open until several people have verified them, and this process varies wildly between hours and months. This wouldn't change even if we used Crowdin or a similar service.

Don't get me wrong - I agree that editing files and opening PRs on GitHub is not at all intuitive for new contributors, and Crowdin would help significantly in that regard. It's just that we need to evaluate whether the benefits outweigh the potential maintenance effort.

**Comment by DoNotSpamPls** [comment]
There is progress on the issue - EssentialsX now has a Crowdin project over [here](https://crowdin.com/project/essentialsx-official). However, please wait a bit before translating so we can fix all the little issues that may arise.

**Comment by mdcfe** [comment]
We now use Crowdin and regularly merge in changes as necessary.
