### ISSUE TITLE
Essentials timings

### ISSUE THREAD

**Issue by RainOfPain125** [EssentialsX/Essentials#1837]
EssentialsX version (run `/essentials`): 
You mean /version essentials. /essentials doesn't provide ver info
Essentials version 2.0.1-b557

Server software (run `/version`): 
git-Paper-1320

Server (`logs/latest.log`):
N/A

EssentialsX config (`plugins/Essentials/config.yml`): 
https://pastebin.com/4RDdHnp2

Details:
https://s18.postimg.org/q06hksedl/what_the.png

**Comment by LaxWasHere** [comment]
Please give us your server log and the full timings report (The timings link).

**Comment by RainOfPain125** [comment]
Heres the full timings report (not the same one, I just made this one which is much, much longer)
https://timings.aikar.co/?id=e2ab20826d6d436da9ccec48114fdf83

Full logs (even though nothing event full has happened)
https://pastebin.com/yL7irjvj

**Comment by mdcfe** [comment]
Is there a noticeable amount of lag on your server? Do you have any other metrics to indicate that EssentialsX is the root cause of the problem? It could be slow disk IO, though I don't know at exactly what point the userdata is saved when `/back` is run and the last location is updated.

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to reopen the issue.
