### ISSUE TITLE
/back only on death

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1839]
Would it be possible to implement the use of /back _only_ on death? I know the essentials.back.ondeath permission exists, but that requires the essentials.back permission in order to be used.

**Comment by mdcfe** [comment]
I've been meaning to implement a way to do this for forever - I've assigned it to 2.18 for now.

**Comment by pop4959** [comment]
How were you planning to implement this? Sounded like a whole lot of jank, which is why I closed it (in addition to the author of this issue not being active anymore). Config option to determine what the function of the permission does, or something?

**Comment by mdcfe** [comment]
This has been asked about over and over, so there's definitely a demand for it, even if not represented on GitHub.

I was thinking we could implement a permission to control whether or not teleports update the `/back` location - either we could add an `essentials.back.onteleport` permission that defaults to `true` in superperms, or we could add a `essentials.back.ondeath.only` permission. I prefer the former as the latter isn't as obvious to the end user. Controlling this through the config alone would limit the usefulness of this feature (eg certain areas/worlds you might want different ondeath/onteleport options).
