### ISSUE TITLE
Unsafe Enchanted books - Anvil

### ISSUE THREAD

**Issue by AmazedMender16** [EssentialsX/Essentials#1840]
With McMMO you can get unsafe enchanted books by doing the following:
- You have to have armor/tools with prot/unbr 20. I got mine from the christmas kit with leather prot & unbr 20 armor.
- Now just salvage the armor, and if you are lucky you will get an enchanted book with Protection enchantment.level.20 or Unbreaking enchantment.level.20 or both on one book if your very lucky.

Now my question is.. Could you add support for unsafe enchantments using an anvil? Cuzz if they try to add the prot 20 book to an armour piece it comes out as prot 4

**Comment by mdcfe** [comment]
I think this would require a lot of NMS-based code to achieve, and I'm not convinced this really belongs in EssentialsX.

**Comment by AmazedMender16** [comment]
Well yeah i wasnt quite sure if essentialsX has something to do with anvils.. are the anvils spigot based?

**Comment by mdcfe** [comment]
I don't think Spigot touches anvils at all - they're part of vanilla.

**Comment by mdcfe** [comment]
Having looked into this, it doesn't look like there are any obvious ways to do this from the Spigot API itself, and it seems like a feature that should belong in another plugin rather than in EssentialsX.
