### ISSUE TITLE
[Bug] /Back is Inconsistent

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [EssentialsX/Essentials#1841]
EssentialsX version (run `/essentials version`): 
https://gyazo.com/74b471e080c107c1b15d284b2b24b8e9

Server software (run `/version`): 
https://gyazo.com/49ac57407a2149dd1a7b0151d10d05a6

Server (`logs/latest.log`):
https://gist.github.com/pinkpig3777/817908f75e324f0cae8681741da76bc7

EssentialsX config (`plugins/Essentials/config.yml`): 
https://gist.github.com/pinkpig3777/9d13f0a727b0131c95e1dcfa47b282ad

Details:
/back is inconsistent. It sometimes teleports people to places where they were but not where the /back should've led.

There have been multiple reports of this issue and I had it happen to me but didn't think at the time to write down steps to reproduce it. So, I'll only provide steps to reproduce the issue from 1 player.
**Please note:** Not every time a mob is interacted with when this /back issue occurs. 

Steps to Reproduce:
1) Teleport to someone. In my example, Zapara teleported to me, pinkpig3777, in a different world.
2) Do /back. Worked fine. 
3) Fight a mob.
5) Kill the mob.
6) Do /back. Zapara went to the place where he fought the mob.
Like I said though, it's very inconsistent so this may not work. So far I haven't noticed any patterns for when it is working and when it doesn't.
If you need it, my plugins are: https://gyazo.com/e1f9911e581ca026a64d13583f5c6599

**Comment by PiggiesGoSqueal** [comment]
Not sure what the issue is, but possibly a plugin conflict with CMI (even though /back was disabled in CMI)..

Possible fix for users using CMI & EssentialsX: https://www.spigotmc.org/threads/back-is-unreliable-for-2-plugins-help-please.307603/

**Comment by mdcfe** [comment]
It seems like the player is being teleported when killing a mob, resetting the `/back` location, but I can't see why this is happening or if this actually is the case.

**Comment by pop4959** [comment]
This absolutely does sound like a plugin conflict. I don't see anyone else reporting this either. Try without any other plugins installed, and if it still is inconsistent please create a new bug report showing how to replicate it.
