### ISSUE TITLE
EssentialsXSpawn error on enable

### ISSUE THREAD

**Issue by enotakin** [EssentialsX/Essentials#1842]
Error:
![image](https://user-images.githubusercontent.com/35406568/36078620-e2639fea-0f81-11e8-8967-cea2c0885a29.png)

Version:
![image](https://user-images.githubusercontent.com/35406568/36078637-02d87f66-0f82-11e8-805c-a778703e5540.png)

**Comment by LaxWasHere** [comment]
Please update your EssentialsX.jar https://ci.ender.zone/job/EssentialsX/
