### ISSUE TITLE
[Sugestion] Adding Hover Per Player.

### ISSUE THREAD

**Issue by Methosss** [EssentialsX/Essentials#1843]
Add hover information per player to chat and support for FunnyGuilds Plugin
![image](https://user-images.githubusercontent.com/32804020/36107956-dd789ce8-101b-11e8-8345-0faa59be2bc4.png)

**Comment by mdcfe** [comment]
We won't be baking support for specific plugins into EssentialsX unless it brings some actual benefit to the plugin.

Adding chat components with tooltips has been proposed to solve the issue of similar nicknames, however it is not being worked on at the minute (as far as I know).

**Comment by drtshock** [comment]
Would be great to allow info when you hover over a player's name. Though not something that is WIP at all yet, and wouldn't be implemented as described in this ticket.

**Comment by pop4959** [comment]
Please visit the discussion in #2391 for hover events and other thing chat-overhaul-related. This kind of thing will probably be added plugin-wide if and when support gets implemented.
