### ISSUE TITLE
kit preview signs (feature request)

### ISSUE THREAD

**Issue by svnxd** [EssentialsX/Essentials#1845]
EssentialsX version (run `/essentials version`): 2.0.1

Server software (run `/version`): Not really required

Server (`logs/latest.log`): Not Required

EssentialsX config (`plugins/Essentials/config.yml`): Not Required

Details: Kit Preview signs built in? (Feature request)

**Comment by mdcfe** [comment]
EssentialsX doesn't natively support previewing kits anyway, and adding a sign for this seems unnecessary. You may want to look into combining [KitPreview](https://www.spigotmc.org/resources/kitpreview-display-and-buy-essentials-kits-in-a-gui.31251/) with [ServerSigns](https://dev.bukkit.org/projects/serversigns) to achieve this.

Closing as this is out of scope, but others are welcome to reopen it if they feel it should be added.
