### ISSUE TITLE
Suggestion - Option to add lore to items repaired with /fix.

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#1848]
Would it be possible to have an option to add lore to items repaired with /fix? This would allow differentiating between items repaired normally and repaired illegitimately via command for survival economy servers. You could possibly take it a step further and only allow items to be repaired once if it doesn't have any lore, but having _something_ such as ```Repaired by command.``` added to the bottom of the item lore would be nice.

**Comment by Sikatsu** [comment]
Fully agree.

**Comment by mibby** [comment]
Similarly, adding lore to items dragged out of the creative menu would be nice so you know what items were spawned in. ^^

**Comment by mibby** [comment]
Any update to this feature request? It would be nice to have creative items marked that they were spawned in with /i , /give, and dragged from creative inventory.

**Comment by pop4959** [comment]
On a survival server you should probably not be giving repair command to normal players. Having custom lore or other such changes to items sounds like something niche to your server that probably should be added via a custom plugin.
