### ISSUE TITLE
Request: Mask invisible people from /near

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#1849]
/near should mask/hide invisible people.
it may be cool to do &kusername to obscure their username, so they know someone is close but not know who. also the option to toggle on just hiding invis people from /near.

**Comment by TomLewis** [comment]
No. It works on everyone, even staff that are in /v, it really needs to be fixed.

**Comment by drtshock** [comment]
Which vanish plugin are you using? It hides them if they are vanished by essentials or bukkit https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/commands/Commandnear.java#L87

**Comment by TomLewis** [comment]
Using Vanish by Essentails, Hmm strange. I will re-test. 
As for the Invisibility potion, that would be handy to get implemented.

**Comment by LaxWasHere** [comment]
That doesn't sound like EssentialsX
In the future, please follow the given template and provide all of the information that the instructions ask for.

> If you have a question about using EssentialsX, it may be more helpful to ask
> in our Discord server: https://discord.gg/F7gexAQ
> 
> If you have a feature suggestion for EssentialsX, please delete the template.
> 
> Otherwise, if you are reporting a bug, read on:
> 1.  Fill out the template, running the commands either in the console or 
>     as a player. Don't simply put "latest" or we will ignore it.
> 
> 2.  When linking files, do not attach them to the post! Paste them on 
>     https://gist.github.com/, then paste a link to them in the relevant parts
>     of the template. Avoid using Hastebin or Pastebin, as files are deleted
>     after a period of time.
> 
> 3.  If you are reporting an issue with lag, please include a timings report.
> 
> 4.  If you are reporting an issue with messages or in-game behaviour, please
>     include screenshots detailing the problem.
> 
> 5.  Include a description and any other details that may be helpful under the
>     Details section.
> 
> 6.  Delete this line and all above lines before posting your issue!       -->

---


### Information

EssentialsX version (run `/essversion`): 

Server software (run `/version`): 

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 

### Details

Describe your issue here.

**Comment by TomLewis** [comment]
@LaxWasHere None of that is relevant. 
But because you asked: 
essversion: 2.0.1-b570
paperspigot 1.12.2 1322

No need for my log or config to be public.

Either way, invisible people _SHOULD NOT_ be displayed on /near.

**Comment by TomLewis** [comment]
How is this still marked invalid? People that use A potion to be invisible should not show up on ./near, hell make it a permission so people have the option, or in the config.

**Comment by mdcfe** [comment]
People who have invisibility potions are still visible to players, so I'm not sure if this makes much sense.

If you're using EssentialsX's vanish or any other well-written vanish plugin, EssentialsX will not show vanished players in `/near`.

**Comment by TomLewis** [comment]
Im sure Vanish is fine, I had it reported by one of my admins and haven't had time to check.

You may not think it makes sense, but as someone that's run a survival for 5 years with /near is valuable to players, but its a little too OP as it displays invisible players, invisible players only have very, very small particles visible, hardly call them "people who have invisibility potions are still visible to players", no, really not, they show off a very small particle effect.

Where as /near would just say XYZ is standing so far away, gives them away. its something very simple that could be checked, its an incredibly basic request that has only positive results, for those people that only have /near for staff, you can have a permission node that makes hidden people show in a different color in near.

**Comment by mdcfe** [comment]
Players with invisibility potions are still synced to the client when in range, and are still considered "visible" by most plugins.

I can open this to a PR, but it's just not a high enough priority change for me to implement at the momoent.

**Comment by TomLewis** [comment]
But I'm not talking about other plugins, I'm talking about just essentials, it's just how it should act. I don't have anything else that tells players if there's someone nearby

**Comment by ImNachoMans** [comment]
I think they shouldn't be hidden. Just my opinion.

**Comment by mdcfe** [comment]
It doesn't change much though - if they're within range of the player, then any player can mod their client to show where synced players are.

**Comment by TomLewis** [comment]
@NachoMans Depends how you setup your server.

@md678685 I have spoken to a large selection of players on how ./near should act, and nearly all of them as players want ./near to hide invisible players, This is from a survival aspect, Of course players could mod their clients, but that isnt anything to do with this request, I personally don't allow modded clients on my server, and set the rules myself.

**Comment by ImNachoMans** [comment]
@FrozenBeard For a survival server, I wouldn't give them /near.

**Comment by TomLewis** [comment]
It's a donator perk.

**Comment by FrozenBeard** [comment]
For anyone interested in this, I ended up creating my own /near in commandhelper that obscures invisible people, im happy to share the script if anyone wants a copy.

**Comment by drtshock** [comment]
I think it's established that we disagree with this functionality change.

**Comment by TomLewis** [comment]
Why did you delete my comment? When someone else finds this thread they will have an option that works.

**Comment by mdcfe** [comment]
Please don't advertise your plugins or scripts here. This is an issue tracker, not an advertisment spot. If you want to promote your own plugins and scripts, post them on Spigot or another forum.

**Comment by TomLewis** [comment]
@md678685 haha what? Neither of those things is happening, its a solution to this thread, Its something I had to create due to this "issue", it couldn't be more relevant. How far up your own ass can you possibly be to consider this "advertising". pathetic.

**Comment by drtshock** [comment]
This is the second time that you've had your comments deleted for advertising. Please stop or you will be banned from the org.

Another thing is just be nice :) We're all here in our spare time to help people out for free. Lets not make it any harder on us than it already is.

**Comment by mdcfe** [comment]
As I said, feel free to post your script to a forum or resource board. This isn't the place for it.
