### ISSUE TITLE
Ability to center MOTD

### ISSUE THREAD

**Issue by aoov** [EssentialsX/Essentials#1852]
It would be great to see the ability to center lines of the MOTD, perhaps [this](https://www.spigotmc.org/threads/free-code-sending-perfectly-centered-chat-message.95872/) could help with that. 

Maybe a placeholder like {center} would indicate the line be centered. Thanks for reading and hope you consider it and hope it's possible :)

**Comment by mdcfe** [comment]
I can't see that this is something that will ever get implemented (unless someone is willing to submit a PR for it), but I'll leave this open pending comments from other.

**Comment by drtshock** [comment]
I personally think this would be great.

**Comment by Ichbinjoe** [comment]
I agree this would be great (many administrators end up doing this instead by hand).

One corner-case to recognize is that centering of text will not be consistent across different fonts which can be provided by resource packs.

In addition, players can manually change the width of their chat. Granted, I know absolutely no one who would do this, but it may be something to consider if someone writes a PR, or at the very least something to document.

**Comment by JRoy** [comment]
Due to font and chat width being controlled by the client, this feature wouldn't be something we could add and maintain consistency across all clients. Space the messages out yourself if you'd like to achieve this yourself.
