### ISSUE TITLE
[Suggestion] Able to edit armorstands

### ISSUE THREAD

**Issue by ImNachoMans** [EssentialsX/Essentials#1857]
### Information

EssentialsX version (run `/essversion`): 

Server software (run `/version`): 

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 

### Details

Describe your issue here.

Could you add a feature to essentials to edit armor stands. Meaning change the way they are postioned (their arms,legs,head,etc). Also if you could add features like big/small, Invisible, show name, glowing, gravity,etc. Would be very nice to have.

**Comment by LaxWasHere** [comment]
https://www.spigotmc.org/resources/armor-stand-editor.7688/

**Comment by ImNachoMans** [comment]
I wanted it to be built into essentials.

**Comment by mdcfe** [comment]
I don't see this as a necessary feature that many people will use within EssX at all - it's also a very large amount of work that belongs in its own plugin rather than being dropped into EssentialsX.
