### ISSUE TITLE
Kit crossout

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1858]
### Information

EssentialsX version (run `/essversion`): 2.0.1-b601

Server software (run `/version`):  1.8.8 PaperSpigot

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)): 

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 

### Details

Kits arent being crossed out when used by a player. There is no errors or logs regarding it, and i believe Trent knows about the issue already.

**Comment by mdcfe** [comment]
Duplicate of #1779.
