### ISSUE TITLE
essentials.joinfullserver Not work for me

### ISSUE THREAD

**Issue by Espantonius** [EssentialsX/Essentials#186]
Hello

The permission does not work essentials.joinfullserver to me. I tried to put the group permission. Also in globalgroups. Even I have given with manuaddp and not working.
Any solution?

Ps: This happens when I connect to another server within a network (bungeecord)

**Comment by EvilOlaf** [comment]
https://github.com/drtshock/Essentials/issues/176
https://github.com/drtshock/Essentials/issues/128

Maybe there is a problem with offline mode (even with bungee)?

**Comment by Espantonius** [comment]
We use offline mode with bungee. I have tried many methods and no way of entering.

**Comment by Espantonius** [comment]
I tried it with essentials and work. I try to essentialsX and not working.

**Comment by TomLewis** [comment]
I reported this in #128 Im in online mode and im not using bungee, Also worked in normal essentials for me.

**Comment by Agazed** [comment]
Maybe you should put it in online mode and stop pirating the game?

**Comment by XxCoolGamesxX** [comment]
@Agazed At not fix the error of the plugin. -_-

**Comment by Agazed** [comment]
Offline mode is not supported. Put it in online mode and see if you are still having the problem.

**Comment by XxCoolGamesxX** [comment]
@Agazed Read what @FrozenBeard say.

Where do is say is not support offline mode. -_-

**Comment by Agazed** [comment]
Bukkit is not meant to run in offline mode, as it causes problems with UUIDs not being able to be authenticated.

**Comment by EvilOlaf** [comment]
Did I miss something or didn't he say he uses offline mode to be able to use bungeecord (which probably runs in online mode)? So I don't see a reason for piracy?

**Comment by Espantonius** [comment]
Nothing changes that are online or offline.

**Comment by XxCoolGamesxX** [comment]
@Espantonius Yes same for me.

![Image of True Story](https://dl.dropboxusercontent.com/u/16158672/GIF/true-story-thumb.jpg)

**Comment by vemacs** [comment]
I am unable to reproduce this under PaperSpigot 1.8.8 with BungeeCord.

Check to see that online-mode is false and bungeecord is true.

**Comment by XxCoolGamesxX** [comment]
We don't use PaperSpigot, can you please redo the test you did using Spigot?. Our server is 100% offline mode.

**Comment by vemacs** [comment]
If it's 100% offline mode, we can't support it. Permissions checks are done by UUID which aren't forwarded with offline mode, plus the entire piracy thing.

Spigot and PaperSpigot make no difference.

**Comment by XxCoolGamesxX** [comment]
Can you please explain to me why the old essentials work but essentialsx doesn't?

**Comment by vemacs** [comment]
No reason. Spigot-Essentials shouldn't work either. We have made no changes to the code that handles joinfullserver.

**Comment by vemacs** [comment]
https://github.com/essentials/Essentials/blob/ad13062117b0867073b76380503900245a4618ee/Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java#L376
https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java#L298

Absolutely no changes. It's an issue with your setup. Don't support piracy.

**Comment by TomLewis** [comment]
Again, This is broken for me and im in ONLINE mode as I wrote in 
https://github.com/drtshock/Essentials/issues/186#issuecomment-137558068
and in #128

**Comment by Espantonius** [comment]
I tried a 100% server online and not work either. It is not the problem of online or offline!!

**Comment by vemacs** [comment]
I have tried a 100% online server and it works. Used max-players 1 and me with my alt account. Are you sure your permissions are assigned correctly? Again, we have made absolutely no changes to the code that handles full joins.

**Comment by XxCoolGamesxX** [comment]
This is happening to other people as well who have 100% online server, this problem can't be because of my setup, we have even tried with a server that is 100% online and it still doesn't work like for some other people.

**Comment by vemacs** [comment]
Try Spigot-Essentials. We have made no changes whatsoever to that aspect.

Likewise, the problem can't be with EssentialsX, since we have made 0 changes to joinfullserver handling.

**Comment by XxCoolGamesxX** [comment]
We used that before and it worked, but when we changed to essentialsx it doesn't work anymore.

**Comment by vemacs** [comment]
I fail to see how that would happen.

**Comment by Agazed** [comment]
Probably your permissions manager being unable to work in offline mode.

**Comment by XxCoolGamesxX** [comment]
We use the Essentials GroupManager and is work on online and offline mode the plugin. -_-

**Comment by KyrneDev** [comment]
Don't use group manager it is deprecated and completely unsupported. Switch to PremissionsEX or Bpermissions, especially if you use bungeecord

**Comment by TomLewis** [comment]
This is still broken, The issue should not be closed if there's an open bug. 
To clarify, this has nothing to do with online/offline and has been broken since I moved to EssentialsX version. What makes no sence at all is players with essentials.joinfullserver can not join a full server but OP's can.
