### ISSUE TITLE
[Feauture] Timed mails

### ISSUE THREAD

**Issue by Arkobat** [EssentialsX/Essentials#1860]
A nice enchantment would be to be able to send timed mails
There format should be: `/mail send <player> [time] <mail>`
`/mail send Arkobat 3d This message will only be in your mailbox for 3 days`
If no time format is specified, the mail won't "expire"

Another method could be `/tempmail send <player> <time> <mail>`

This could be very useful for example events.
If I have an Easter event, where I would inform all players about it in a mail, the mail would only be relevant as long as the event lasts.

**Comment by mdcfe** [comment]
I believe we'd need to either alter how mails are stored or store them separately, but I can see a case for this. Unfortunately I don't think I'll have time to implement it, but feel free to implement it in a PR.
