### ISSUE TITLE
only last command is executed with Bukkit.dispatchCommand()

### ISSUE THREAD

**Issue by NurPech** [EssentialsX/Essentials#1861]
### Information

EssentialsX version (run `/essversion`): 2.0.1-b559

Server software (run `/version`): 1.12.2

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)): https://gist.github.com/NurPech/f2a87826d6718dbdcc056dc57dd7d864

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): https://gist.github.com/NurPech/146d7a502a3bacc30523ab4bb3ea70eb

### Details

I devlop a new plugin which should execute some commands via Bukkit.dispatchCommand()
As you can see in the logs, only the last essentials command is executed successfully.

**Comment by mdcfe** [comment]
We have absolutely no idea what the problem is unless you provide us with the code that isn't working - I'd suggest talking to people in `#codehelp` on the [EssentialsX Discord support server](https://discord.gg/casfFyh).

**Comment by NurPech** [comment]
Ok, you can close this issue. There was an error in the code
