### ISSUE TITLE
Problem with strange symbol in {UNIQUE}

### ISSUE THREAD

**Issue by Hekzory** [EssentialsX/Essentials#1863]
### Information

EssentialsX version 2.0.1-b601

Server software: This server is running CraftBukkit version git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

EssentialsX config: 
https://gist.github.com/AzDreamerr/ce8f26a185db692d50c7ed76dd55808c

### Details

When I use {UNIQUE} in announce-format (Welcome message for newbies) and when the count of players is more than 999 it write : 1(NBSP symbol in square)000 but not just 1 000
You can see example here: 
![default](https://user-images.githubusercontent.com/36638457/36387834-1479c1ba-15ab-11e8-890e-86e9b69730ca.png)
Translation: "Welcome, qwerty12345! You're the 1(strange symbol)255 player on our server SIlentWorld"

**Comment by mdcfe** [comment]
This looks like an issue with the text encoding of a config file, but I don't know for certain.

**Comment by Hekzory** [comment]
@md678685 Then how can I fix this if the problem is in text encoding?

**Comment by DrkMatr1984** [comment]
You can try downloading Bluefish from http://bluefish.openoffice.nl/ and editing your yml with it. You can set character encoding of the file by going to Documents then to character encoding, then just save at the end. 
https://prnt.sc/ii1c98

**Comment by mdcfe** [comment]
@AzDreamerr are you using an edited `messages.properties` file? If you are, could you paste it on [Gist](https://gist.github.com)?

**Comment by Hekzory** [comment]
@md678685 I didn't change anything in .jar
The only unusual thing is that I changed default language to Russian. I can find the same problem in /gc when any number is more than 999
