### ISSUE TITLE
Colors wont work on /mail sendall tag. (sendall)

### ISSUE THREAD

**Issue by Remski01** [EssentialsX/Essentials#1866]
**EssentialsX version:** 2.0.1-b601

**Server software:** Spigot 1.12.2

**Server log:** Not... There is no error. 

**EssentialsX config:** Not needed.

### Details

Colors wont work and i just showed as "&4&lBELANGRIJK:" instead the bold & red BELANGRIJK. I do have OP. And the colors work when you send it to an player. (It only not work with SendAll)

If you are not enable to reproduce this issue. Please say what you need to retry it.

**Comment by caojohnny** [comment]
Op yourself and retry. If it works, you are missing the `essentials.mail.color` permission.

**Comment by mdcfe** [comment]
@DutchUser Could you run `/ess debug` then paste the console output when `/mail sendall` is run?

**Comment by Remski01** [comment]
@AgentTroll " I do have OP. And the colors work when you send it to an player. **(It only not work with SendAll)**"

@md678685 https://pastebin.com/6VBVzaVe

**Comment by caojohnny** [comment]
Oops, I apologize for not catching that the first time. On closer inspection, it seems that the `/mail sendall` command doesn't translate color codes at all, according to this:

https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/commands/Commandmail.java#L84

I will be opening a PR soon.
