### ISSUE TITLE
[Suggestion] Control allowed colors in Nicknames and Private Messages/Chat 

### ISSUE THREAD

**Issue by penturt** [EssentialsX/Essentials#187]
Add a way to limit what colors are allowed for players to use in nicknames and private messages/chat. Either by permissions, or options set in the config. 

Main reason is sometimes, certain colors are hard to read in chat such as "black". This is only for nick names and private messages/chat.

Rather then listing the colors to allow for chat or nicknames, there can be a blacklist to just add the colors you'd want to prevent, or negate the permission for that color.

**Comment by mdcfe** [comment]
PR that implements this through permissions: #1441

**Comment by mdcfe** [comment]
Closing as #1441 is now open.
