### ISSUE TITLE
Gamemode Perm issues

### ISSUE THREAD

**Issue by BlueDefend** [EssentialsX/Essentials#1870]
### Information

EssentialsX version (run `/essversion`): 

Server software (run `/version`): 

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 

### Details

We are using essentials as it is the best to use. We want our builders to beable to only go from gm c and gm s but if we give them perms they can do all 4 gamemodes and we have tried limiting it everyway and they all fail. Help would be amazing. We tried /pex group Builder add -essentials.gamemode.all or /pex group Builder add -essentials.gamemode.spectator or /pex group Builder add essentials.gamemode.creative and nothing is working.

**Comment by mdcfe** [comment]
Please edit your issue and follow all the instructions.

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to respond and reopen the issue.
