### ISSUE TITLE
[Request] Mining spawners

### ISSUE THREAD

**Issue by Fix3dll** [EssentialsX/Essentials#1874]
EssentialsX have spawner support like 52:99 Maybe you can add simple silk spawner. It should be very good.

**Comment by mdcfe** [comment]
I don't see this as an essential feature. If you want silk touch for spawners, why not use SilkSpawners?

**Comment by Fix3dll** [comment]
Maybe its not "essentials feature" but it can help to server owners. I dont like SilkSpawner. It have lot of problem. Maybe we can create plugin like a EssentialsXSpawn if you'll let.

**Comment by mdcfe** [comment]
The point of Essentials modules isn't too duplicate other plugin developers' efforts, it's to provide particular features that are often essential to servers, but easily replaceable. There's no point adding random features to EssentialsX. If you're encountering issues with SilkSpawners, please report it to them or look for a fork or alternative that meets your needs.
