### ISSUE TITLE
Essentials Userdata issue with LeaderHeads/Citizens

### ISSUE THREAD

**Issue by ZeuosEtherus** [EssentialsX/Essentials#1876]
### Information

EssentialsX version (run `/essversion`): Essentials 2.0.1-bSNAPSHOT

Server software (run `/version`): CraftBukkit version git-Spigot-4bd94dc-e3b4cf5 (MC: 1.12.2)

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)): https://gist.github.com/ZeuosEtherus/9755bd2cbeb227e141599bc717047b56

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)):  https://gist.github.com/ZeuosEtherus/f167543dbd3c1e612c2b2e526ec957c3

### Details

@md678685 
I have the same issue as: https://github.com/EssentialsX/Essentials/issues/1605

This is my plugin list: https://pastebin.com/4ZxHf2aF
The server is running in offline mode due to BungeeCord.

**Comment by mdcfe** [comment]
* Have you tried running `/essclean` from @arkobat's plugin?
* After installing CTEH, does the number of userdata files continue to grow (ie significantly more after 24 hours)?
* Could you give an example of an excess userdata file?

**Comment by ZeuosEtherus** [comment]
**1) I have run /essclean, but it doesn't do anything:**
> [11:53:00 INFO]: /essclean purge
>essclean purge
> [11:53:05 INFO]: Are you sure you want to move/delete invalid userdata files.
> [11:53:05 INFO]: Be sure you know what to are doing.
> [11:53:05 INFO]: To contuine, type '/esscealn confirm' within 30 seconds
> [11:53:05 INFO]: To cancel please type '/essclean cancel'
>essclean confirm
> [11:53:08 INFO]: Starting to purge
> [11:53:08 INFO]: Checked files: 33
> [11:53:08 INFO]: Files sent to deletion: 0
> [11:53:08 INFO]: Files successfully deleted: 0

**2) It's strange. It keeps spamming my console, and on /baltop I have apparently balanced of 1.4k+ players files, but in the actual userdata file it's only 30 or so.**

**3) An example? As in what is written in the YAML file? If so below are a few examples:**
_A quick note: these files all have a size of around 115.00 B, which distinguishes itself from the real ones which are 300-400 B+._

lastlocation:
  world: survival2
  x: 26.5
  y: 181.0
  z: 8.5
  yaw: 0.35979998
  pitch: 0.0
info:
  citizens: 21

lastlocation:
  world: survival2
  x: 26.5
  y: 181.0
  z: 8.5
  yaw: 0.35979998
  pitch: 0.0
info:
  citizens: 21

lastlocation:
  world: survival2
  x: 36.5
  y: 185.0
  z: 3.5
  yaw: 5.6863027
  pitch: 0.0
info:
  citizens: 22

**Comment by Arkobat** [comment]
With /essclean - Have you changed the config to fit your need?
The default maxSize is 100 bytes for example
Alternative you can enable debug /essclean debug, and paste the info in a hastebin

**Comment by mdcfe** [comment]
You'll probably want to raise the limit in @arkobat's plugin to 120 bytes or so.

If the number of files in `plugins/Essentials/userdata/` isn't continuing to grow over the period of a day or so, then CTEH is purging files as intended.

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to respond and I'll reopen the issue.

**Comment by Redstoneguy129** [comment]
I am getting this problem
