### ISSUE TITLE
Don't Know how to call this issue... After this server just stopped...

### ISSUE THREAD

**Issue by misterboombasta** [EssentialsX/Essentials#1877]
Okay, i got this error, and after this server stopped:

https://gist.github.com/RagezLT/d6717339c56babb7f1eb4aee6b3c3dc7

### Information

EssentialsX version: 2.0.1

Server software: 1.12.2

Server log: 
https://gist.github.com/RagezLT/f82139ca95ff9ea3632f67b1e25b8627

EssentialsX config:
https://gist.github.com/RagezLT/48605e2f058ad9c4195adffa90e022d9 

### Details

Don't Know how to call this issue... After this server just stopped...

**Comment by drtshock** [comment]
Update to latest on https://ci.ender.zone/job/EssentialsX

**Comment by misterboombasta** [comment]
dude. Im using the latest...

**Comment by LaxWasHere** [comment]
No you are not, you are running 113 builds behind.
