### ISSUE TITLE
Not loosing XP on Die

### ISSUE THREAD

**Issue by o0Julia0o** [EssentialsX/Essentials#1878]
hi, please add a permission, so that the admin who has '*' -permission could negate the essentials.keepxp-permission. Or let it choosen from the config.yml.

EssentialsX: 2.0.1-b488
LuckPerms: 4.1.5

Thank you!

**Comment by dariasc** [comment]
It's up to the Permission plugin to do that, and wildcards are generally a bad idea (*)

**Comment by o0Julia0o** [comment]
So how can i set all EssentialsX-permissions withouth that one, who keeps the xp on die? I can´t find it on the permissions-site: http://wiki.mc-ess.net/wiki/Command_Reference/Perm

**Comment by mdcfe** [comment]
Give each group the permissions they need. Wildcards will automatically include exemptions, which you don't want in this case, so the best way is to go through each and every permission and give them individually to the right groups to set your server up exactly as you want.

You can find the Essentials permissions list at the [Essentials wiki](http://wiki.mc-ess.net/wiki/Command_Reference/Perm), and the added EssentialsX permissions can be found on the [EssentialsX wiki](https://github.com/EssentialsX/Essentials/wiki).
