### ISSUE TITLE
/jail is broke

### ISSUE THREAD

**Issue by Gamer43251** [EssentialsX/Essentials#1879]
### Information

EssentialsX version (run `/ess version`): 

Server software (run `/version`): 

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 

### Details

Describe your issue here. 

When i do /jail it works the first tiem but after that it doesnt work anymore it just lags my chat then crashes it please help me

**Comment by LaxWasHere** [comment]
Help us help you by filling those form you left empty above.

**Comment by mdcfe** [comment]
Please edit your issue, read the instructions carefully and follow them exactly as they say.

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to reopen the issue.
