### ISSUE TITLE
One time use kits removed from /kit?

### ISSUE THREAD

**Issue by zRiaz** [EssentialsX/Essentials#188]
Could you make it so kits that are one time use (-1) get removed from the /kit list when they have been used?

Instead of the "You cant use that kit again" make it just not show up on /kit - Thanks :]

**Comment by denizaygundev** [comment]
I thought this was already a thing? If not it would be great to have!

**Comment by drtshock** [comment]
Doesn't it just show them crossed out? I don't see why we'd change that functionality since that's how it does it for timed kits.

**Comment by FlippantCactus** [comment]
It shows them crossed out, however I see where @ISanderI is coming from, perhaps it should remove them from the /kit list when they've been used, or have a message under saying "You have 2 kits that you can redeem in x <time> or more".

**Comment by zRiaz** [comment]
Yes its crossed out. But like I feel like one time kits should just be removed from the kit list when used to keep the list clean without an unessecerry kit they wont ever be able to use again.

**Comment by Agazed** [comment]
Something like this?

Where uses is the total amount of times the kit can be given to the player and where delay is the cooldown like current behavior.

```
armor:
  delay: 10
  uses: 5
  items:
    - 310 1
    - 311 1
    - 312 1
    - 313 1
```

**Comment by zRiaz** [comment]
When delay is -1 it has only 1 use. Basically I want -1 delay kits to dissapear from the kit list after being used. The other amount of uses thing should be in another ticket.

**Comment by drtshock** [comment]
I don't agree with changing the current functionality.

**Comment by zRiaz** [comment]
I mean if you can never use the kit again, why would you want to keep it showing on the kit list?

Reasoning I really want this is because we have quite a few kits on our server and having 2 kits that are -1 kits. So cutting out quite a few of them from the list to make it just look cleaner would be a very nice solution for us.

**Comment by drtshock** [comment]
@vemacs have any input on this?

**Comment by vemacs** [comment]
Wouldn't kill anybody to add a config option.
