### ISSUE TITLE
Essentials Spams TP command, No errors found in logs or anything

### ISSUE THREAD

**Issue by evanmcclan** [EssentialsX/Essentials#1881]
`07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=4,score_AM_yMWcfG=4]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=2,score_AM_yMWcfG=2]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=3,score_AM_yMWcfG=3]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=4,score_AM_yMWcfG=4]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=2,score_AM_yMWcfG=2]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=3,score_AM_yMWcfG=3]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=4,score_AM_yMWcfG=4]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=2,score_AM_yMWcfG=2]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=3,score_AM_yMWcfG=3]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=4,score_AM_yMWcfG=4]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=2,score_AM_yMWcfG=2]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=3,score_AM_yMWcfG=3]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=4,score_AM_yMWcfG=4]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=2,score_AM_yMWcfG=2]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=3,score_AM_yMWcfG=3]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=4,score_AM_yMWcfG=4]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=2,score_AM_yMWcfG=2]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=3,score_AM_yMWcfG=3]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=4,score_AM_yMWcfG=4]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=2,score_AM_yMWcfG=2]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=3,score_AM_yMWcfG=3]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=4,score_AM_yMWcfG=4]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=2,score_AM_yMWcfG=2]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=3,score_AM_yMWcfG=3]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=4,score_AM_yMWcfG=4]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=2,score_AM_yMWcfG=2]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=3,score_AM_yMWcfG=3]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=4,score_AM_yMWcfG=4]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=2,score_AM_yMWcfG=2]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=3,score_AM_yMWcfG=3]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=4,score_AM_yMWcfG=4]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=2,score_AM_yMWcfG=2]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=3,score_AM_yMWcfG=3]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=4,score_AM_yMWcfG=4]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=2,score_AM_yMWcfG=2]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=3,score_AM_yMWcfG=3]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=4,score_AM_yMWcfG=4]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=2,score_AM_yMWcfG=2]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=3,score_AM_yMWcfG=3]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]
07.03 14:39:48 [Server] INFO CONSOLE issued server command: /etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=4,score_AM_yMWcfG=4]
07.03 14:39:48 [Server] INFO Teleport to a player.
07.03 14:39:48 [Server] INFO /etp <player> [otherplayer]`

**My console consistently spams this all the time. I've concluded that it has to be a plugin issue because I've unloaded all worlds on the server, Turned off command blocks & deleted any scoreboard objective and cleared all entities from the server. Essentials paste NO errors and the logs only display this.**

Server Version: 1.12.2 - Spigot-5695bca-53fccdf
Essentials Versions: ALL LATEST (2.0.1-b603)

**Comment by mdcfe** [comment]
Something, likely a plugin, is repeatedly running `/etp @e[type=armor_stand,tag=AM_yMWcfG,name=xYCWH,score_AM_yMWcfG_min=2,score_AM_yMWcfG=2]` as the console. This collides with EssentialsX's `tp` command, which has an alias at `/etp`.

If you're not sure what would be repeatedly trying to move armor stands with a specific random name, try removing any plugins that aren't EssentialsX, Vault or your perms plugin until the issue stops.

**Comment by Dolphin2Point1** [comment]
@evanmcclan There were blanks you needed to fill. Also can we know which plugins your using?

**Comment by mdcfe** [comment]
Closing due to lack of response from OP. If this is still a problem, feel free to reopen the issue.
