### ISSUE TITLE
Could not pass event PlayerInteractEvent to Essentials v2.0.1-b603

### ISSUE THREAD

**Issue by Zxpphire** [EssentialsX/Essentials#1883]
### Information

EssentialsX version (run `/ess version`): 
2.0.1 -b603

Server software (run `/version`): 
1.7.10-R0.1-SNAPSHOT GIT-paperspigot-a925999

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):
https://gist.github.com/Zxpphire/5ca9d2c82fc0382e4b4c25ac23dff80a

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 
https://gist.github.com/Zxpphire/0f9b75fa403776d4695e455335b14714
### Details

The issue is it spams console when i right click on anything. I even loaded JUST essentials to see if essentials is the problem

**Comment by LaxWasHere** [comment]
We do not support 1.7 servers, you can either update to the latest server version or find an older build of Essentials.
