### ISSUE TITLE
afk message not working

### ISSUE THREAD

**Issue by Castiella** [EssentialsX/Essentials#1884]
EssentialsX version (run `/ess version`):  2.0.1- B603

Server software (run `/version`):  1.12.2 (Paper) version 1321

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)): Not sure if necessary but will post if required

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): Not nec

### Details

When I try to use the custom afk message with /afk MESSAGE it says ERROR: Player not found.
When players do it it just sets them afk with the normal message.

**Comment by LaxWasHere** [comment]
Negate `essentials.afk.others` or add more than just `MESSAGE`

**Comment by Castiella** [comment]
Hi, thanks for the response. However, I just tried that and neither worked.

**Comment by mdcfe** [comment]
Could you run `/ess debug` then paste the console output when a player runs `/afk test test`?

**Comment by Castiella** [comment]
09.03 13:26:23 [Server] INFO _Castielle_ issued server command: /afk test test
09.03 13:26:23 [Server] INFO [Essentials] checking if _Castielle_ has essentials.mail - true
09.03 13:26:23 [Server] INFO [Essentials] checking if _Castielle_ has essentials.afk - true
09.03 13:26:23 [Server] INFO [Essentials] checking if _Castielle_ can afford charge.
09.03 13:26:23 [Server] INFO [Essentials] calculated command (afk) cost for _Castielle_ as 0
09.03 13:26:23 [Server] INFO [Essentials] checking if _Castielle_ has essentials.afk.others - false
09.03 13:26:23 [Server] INFO [Essentials] checking if _Castielle_ has essentials.afk.message - true
09.03 13:26:23 [Server] INFO [Essentials] checking if _Castielle_ has essentials.sleepingignored - true
09.03 13:26:23 [Server] INFO [Essentials] attempting to charge user _Castielle_
09.03 13:26:23 [Server] INFO [Essentials] calculated command (afk) cost for _Castielle_ as 0
09.03 13:26:23 [Server] INFO [Essentials] charge user _Castielle_ completed

**Comment by mdcfe** [comment]
Could you post the corresponding output in game? There's nothing in the debug log that indicates that this isn't working correctly.

**Comment by Castiella** [comment]
its just doing the standard Afk message "cas is now AFK

My server is play.wintercrestc.com if you want to see it for yourself

**Comment by mdcfe** [comment]
[Relevant wiki page](https://md678685.github.io/EssXDocs/#/Home?id=afk-message)

> However, this can be changed in the locale file (`messages_en.proeprties`, or whichever locale file you are using) by modifying `userIsAwayWithMessage` and using the `{1}` argument, the message.

**Comment by Castiella** [comment]
userIsAwayWithMessage=\u00a77* {1} \u00a77is now AFK.

Edited it with that but still not working

**Comment by Remski01** [comment]
Properties filles. Where all the message's are. (most part of it anyways)

You can get it from here > https://github.com/EssentialsX/Essentials/tree/2.x/Essentials/src

**Comment by Castiella** [comment]
Yeah i did that and edited both the en and normal one and it still isnt working

**Comment by Remski01** [comment]
Please show us you'r file.

And try to do /afk This is an test.

If you want to set an other player afk with message its the same but then an name before "This"

**Comment by Castiella** [comment]
https://pastebin.com/Ga5RAJgk

**Comment by Remski01** [comment]
userIsAwayWithMessage=\u00a77* {0} \u00a77is now AFK.

**Comment by Castiella** [comment]
It was at 0 previously, but i thought md said to put it as 1

**Comment by Remski01** [comment]
**Try**
userIsAwayWithMessage=\u00a77* {0} \u00a77is now AFK. Reason: {1}

**Comment by Castiella** [comment]
DId not work either.

**Comment by Remski01** [comment]
**Does the player have the permssion >** essentials.afk.message

**And did you try to use:** /afk This is an test.
**and do you have:** userIsAwayWithMessage=\u00a77* {0} \u00a77is now AFK. Reason: {1}

**Comment by Castiella** [comment]
Yes, I am also OP. 

Yes i am literally writing, /afk this is a test
and yes i have that in both the EN and normal msg properties

**Comment by Remski01** [comment]
"both the EN and normal msg properties"?

**Comment by Castiella** [comment]
I copy pasted the config into every language file just in case it was using a different one.

**Comment by Remski01** [comment]
You only need 1 language file...

Please say witch one you use  

## and send us you'r config,

**Comment by Castiella** [comment]
Okay, I deleted every language file except EN and this is it 
https://pastebin.com/RnDAb3us

**Comment by Remski01** [comment]
Does other changed message's works?

**Comment by Castiella** [comment]
Sorry, I don't understand what you're trying to say. What other changed messages?

**Comment by Remski01** [comment]
Does other message works that you have changed.

If you change an other message, Does that changed message appear?

**Comment by Castiella** [comment]
I haven't changed any other messages, what would you like me to change?

**Comment by Remski01** [comment]
Yes. Change an other one and check if the changed one appear.

**Comment by Castiella** [comment]
Can you give me an example of what to change please, i dont know what im doing

**Comment by Castiella** [comment]
Okay, i changed 
heal=\u00a76You have been healed.
to 
heal=\u00a76You This is a test heal

and it didnt change, it just said " you have been healed"

**Comment by Remski01** [comment]
kay, Give us you'r config.

**Comment by Castiella** [comment]
https://pastebin.com/bvTzcrRb

**Comment by Castiella** [comment]
(I edited "you have been healed" back, by the way)

**Comment by Remski01** [comment]
Give us you config.yml

**Comment by Castiella** [comment]
Well, you didnt specify what config, theres no need to be rude ^.^
https://pastebin.com/EDsBA15P

**Comment by Remski01** [comment]
anyway
Try to change "#locale: en "to "locale: en" and rename you'r properties file to "messages_en.properties"

**Comment by Castiella** [comment]
Okay, did that and it still isnt working.
Here is the updated config: https://pastebin.com/PZs9fNe6

Here is a screengrab of the file showing message properties 
![image](https://user-images.githubusercontent.com/29293070/37246929-5976a07c-24aa-11e8-8fb2-ddbd3a8e82ad.png)

**Comment by Remski01** [comment]
Please show us the current messages_en.properties

**Comment by Castiella** [comment]
https://pastebin.com/a4eGG9Kf

**Comment by Remski01** [comment]
Then its maybe because of "Paper"

It works fine for me, (spigot)

**Comment by mdcfe** [comment]
@DutchUser Please keep it civil. The issue is not related to Paper.

@Castiella I can't tell what stage you're at in terms of getting this sorted, but here's a rough concise guide to using locale files:
1. Download the appropriate `messages_ZZ.properties` file from [here](https://github.com/EssentialsX/Essentials/tree/2.x/Essentials/src) (where ZZ is the language you intend to use), and place it in `plugin/Essentials/`.
2. Remove the `#` before the `locale` option in `config.yml`, and if necessary change `en` to the language that matches your downloaded file.
3. With a text editor, find the line that starts with `userIsAwayWithMessage` and add something like ` - "{1}"` to the end of that line.
4. Restart your server and try `/afk test test` again.

**Comment by Castiella** [comment]
Thank you for responding, but it still doesnt work
here is the new messages properties as well:
https://pastebin.com/ZiRy6rWP

**Comment by Castiella** [comment]
That worked, thank you so much!

**Comment by mdcfe** [comment]
Good to hear - let us know if you need any more assistance.
