### ISSUE TITLE
group-format

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1886]
### Information

EssentialsX version (run `/ess version`): 2.0.1-b601

Server software (run `/version`): git-Spigot-21fe707-e1ebe52 (MC: 1.8.8)

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)): https://gist.github.com/pushekthecat/82ed45efe93526a9f59c662d8667c4f5

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): https://gist.github.com/pushekthecat/857a7d562bfd80e4b33572b6c313b49a

### Details
I formated my group-format, but essentials is still using normal format. Please help.
![screenshot_1](https://user-images.githubusercontent.com/37236512/37239519-c7aa687a-243d-11e8-817a-29ba5c15f596.png)

**Comment by drtshock** [comment]
Comment out https://gist.github.com/pushekthecat/857a7d562bfd80e4b33572b6c313b49a#file-gistfile1-txt-L651

**Comment by ghost** [comment]
Did that and:
![screenshot_2](https://user-images.githubusercontent.com/37236512/37242672-c027646a-246d-11e8-8a66-c456cdb6afb0.png)

**Comment by Remski01** [comment]
Witch permission plugin do you use?

**Comment by ghost** [comment]
PermissionsEx.

**Comment by Remski01** [comment]
Could you please show us what it say about you under users: (what for rank you have it say)

**Comment by ghost** [comment]
![screenshot_3](https://user-images.githubusercontent.com/37236512/37243240-7bf49476-2476-11e8-8904-bc0c0d368dfd.png)

**Comment by mdcfe** [comment]
Could you run `/ess debug`, then paste the console output when someone chats?

**Comment by ZerekZarson** [comment]
I'm having the same problem. 
EssentialsX version 2.15.0.52
PermissionsEx (also tried it with luckperms but got the same issues so i switched back to PEX)

When I switched from spigot-essentials 1.13.1 snapshot to EssentialsX 2.15.0.52, my group-formats no longer were affecting chat. instead showing &7[Default] &f<User>: <Message>. 

I believe essentialsX-chat is having a problem receiving the group info provided by permissions plugins.

pic from from /ess debug on console

![2018-10-13 14_11_25-cubedhost prisma](https://user-images.githubusercontent.com/7546219/46909559-f1903480-cef1-11e8-88f2-4d46fe029391.png)

pic from essentialsX config

![2018-10-13 14_12_41-c__users_derek_appdata_local_temp_scp35105_plugins_essentials_config yml - subli](https://user-images.githubusercontent.com/7546219/46909575-2603f080-cef2-11e8-80de-0ef2c9454244.png)

pic from permissionEx user area

![2018-10-13 14_13_04-c__users_derek_appdata_local_temp_scp55310_plugins_permissionsex_permissions yml](https://user-images.githubusercontent.com/7546219/46909582-3320df80-cef2-11e8-9fbb-adb92e2df97d.png)

**Comment by mdcfe** [comment]
> I believe essentialsX-chat is having a problem receiving the group info provided by permissions plugins.

@ZerekZarson Please post the full output of `/ess version`.

Spigot-Essentials still uses a direct hook into PermissionsEx, whereas EssentialsX uses Vault to support all plugins that properly support Vault.

PEX is [no longer maintained nor supported](https://github.com/PEXPlugins/PermissionsEx), and we don't make any guarantees that EssentialsX will work with PermissionsEx.

**Comment by ZerekZarson** [comment]
Okay thanks, I didn't realize Vault was required. Vault fixed this issue. You should know that PEX still functions without error as of now with essentialsX if anyone else asks.

**Comment by Remski01** [comment]
https://github.com/PEXPlugins/PermissionsEx/issues/2923

**Comment by mdcfe** [comment]
Closing as the original poster didn't respond to my request for more information.
