### ISSUE TITLE
[Translate-Add] Updated dutch localization.

### ISSUE THREAD

**Issue by Remski01** [EssentialsX/Essentials#1887]
Hello. 

I have updated a few engelish lines in the Dutch(official) localization file.

https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/messages_nl.properties

=====================
[ English / old version. ]

[ Dutch / translated version. ]

===========================
confirmClear=\u00a77To \u00a7lCONFIRM\u00a77 inventory clear, please repeat command: \u00a76{0}

confirmClear=\u00a77Om de inventory clear te  \u00a7lBEVESTIGEN\u00a77, Herhaal de command: \u00a76{0}

===

confirmPayment=\u00a77To \u00a7lCONFIRM\u00a77 payment of \u00a76{0}\u00a77, please repeat command: \u00a76{1}

confirmPayment=\u00a77Om de betaling van \u00a76{0}\u00a77 te \u00a7lBEVESTIGEN\u00a77, Herhaal de command: \u00a76{1}

===

createdKit=\u00a76Created kit \u00a7c{0} \u00a76with \u00a7c{1} \u00a76entries and delay \u00a7c{2}

createdKit=\u00a76Gemaakte kit \u00a7c{0} \u00a76met \u00a7c{1} \u00a76items en met \u00a7c{2} \u00a76vertraging.

===

createKitFailed=\u00a74Error occurred whilst creating kit {0}.

createKitFailed=\u00a74Fout opgetreden tijdens het maken van kit {0}.

===

commandCooldown=\u00a7cYou cannot type that command for {0}.

commandCooldown=\u00a7cJe kan deze command niet typen voor {0}.

===

banIpJoin=Your IP address is banned from this server. Reason: {0}

banIpJoin=Jou IP adress is verbannen van deze server. Reden: {0}

===

banJoin=You are banned from this server. Reason: {0}

banJoin=Je bent van de server verbannen. Reden: {0}

===

clearInventoryConfirmToggleOff=\u00a76You will no longer be prompted to confirm inventory clears.

clearInventoryConfirmToggleOff=\u00a76Je zal niet meer worden gevraagd om je inventory clear te bevestigen.

===

clearInventoryConfirmToggleOn=\u00a76You will now be prompted to confirm inventory clears.

clearInventoryConfirmToggleOn=\u00a76Je zal nu worden gevraagd om je inventory clear te bevestigen.

===

payConfirmToggleOff=\u00a76You will no longer be prompted to confirm payments.

payConfirmToggleOff=\u00a76Je zal niet meer worden gevraagd om betalingen te bevestigen.

===

payConfirmToggleOn=\u00a76You will now be prompted to confirm payments.

payConfirmToggleOn=\u00a76Je zal worden gevraagd om betalingen te bevestigen.

===

payMustBePositive=\u00a74Amount to pay must be positive.

payMustBePositive=\u00a74De aantal wat je wilt geven moet positief zijn.

===

payToggleOff=\u00a76You are no longer accepting payments.

payToggleOff=\u00a76Je accepteert niet langer betalingen.

===

payToggleOn=\u00a76You are now accepting payments.

payToggleOn=\u00a76Je accepteert betalen weer.

**Comment by mdcfe** [comment]
Feel free to PR these changes - you'll want to click edit in the corner of [this file](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/messages_nl.properties), change the file as needed, then fill in the bottom and click **Commit** to open a PR.

**Comment by Remski01** [comment]
Done https://github.com/EssentialsX/Essentials/pull/1888

**Comment by Remski01** [comment]
Closed in favour of https://github.com/EssentialsX/Essentials/pull/1888
