### ISSUE TITLE
 [Essentials] Task #103228 for Essentials v2.0.1-b488 generated an exception keeps occuring

### ISSUE THREAD

**Issue by davidstrains96** [EssentialsX/Essentials#1889]
### Information

EssentialsX version (run `/ess version`): 
2.0.1
Server software (run `/version`): 
CraftBukkit version git-Spigot-7754231-94b0980 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 

### Details

Describe your issue here.
whenever a player leaves i get  [Essentials] Task #103228 for Essentials v2.0.1-b488 generated an exception

**Comment by Remski01** [comment]
Please upgrade to the latest on https://ci.akpmakes.tech/job/EssentialsX/ and test if the sissue is still there,

If yes, 

Please fill up the "Server log (upload logs/latest.log to Gist):" and "EssentialsX config (upload plugins/Essentials/config.yml to Gist):"

And give us the full error. Not only 1 line.

**Comment by davidstrains96** [comment]
https://pastebin.com/kVg7Kduq this is console for the server

**Comment by davidstrains96** [comment]
and this is the config.yml 

https://pastebin.com/aFaDhETn

essentials keeps kicking out exception

**Comment by mdcfe** [comment]
Update EssentialsX to the [latest version](https://ci.ender.zone/job/EssentialsX).
