### ISSUE TITLE
[Request] max-nick-length to exclude color codes

### ISSUE THREAD

**Issue by denizaygundev** [EssentialsX/Essentials#189]
At the moment my max-nick-length is 30 so that players can apply color and formatting to their nicknames. Could you make it so this ignores color-codes? That way I can leave it at something like 14 and they can still apply color codes without hitting the limit.

Thanks!

**Comment by Johandrex** [comment]
I love this idea! My community has requested it so many times!

**Comment by denizaygundev** [comment]
Bump?
