### ISSUE TITLE
*snip*

### ISSUE THREAD

**Issue by ArtelGG** [EssentialsX/Essentials#1894]
*snip*

**Comment by mdcfe** [comment]
Can you add `locale: en` to the end of your config, restart your server and try again?

**Comment by Mxra** [comment]
Unfortunately, that made no difference.

**Comment by mdcfe** [comment]
Could you paste a screenshot of the **in-game output of `/gc`**?

**Comment by Mxra** [comment]
![screenshot_1](https://user-images.githubusercontent.com/21347579/37324473-f6ab1e34-265f-11e8-962a-1447060f486f.png)
![screenshot_2](https://user-images.githubusercontent.com/21347579/37324478-f9117772-265f-11e8-88e1-7301f44724fd.png)

**Comment by mdcfe** [comment]
You appear to be using LagMeterPlus, which overrides EssX's `/tps` command.

**Comment by Mxra** [comment]
I'm not using that.

**Comment by mdcfe** [comment]
That is not an EssentialsX command output.

Could you post a full `/plugins` list?

**Comment by Mxra** [comment]
![screenshot_1](https://user-images.githubusercontent.com/21347579/37345292-fb389150-26a2-11e8-8b87-c8af53f34e92.png)
Honestly, I just tried `/etps` and I realized it shows the same thing as `/gc`... I've thought that `/tps` response was from EssX for as long as I've been using it.

**Comment by LaxWasHere** [comment]
Best guess is it's from CMI '/cmi tps'

**Comment by Mxra** [comment]
I've already ruled out CMI.
![screenshot_2](https://user-images.githubusercontent.com/21347579/37346014-b3599526-26a4-11e8-9dae-0a063648f5fe.png)

**Comment by mdcfe** [comment]
`essentials:gc` is the EssentialsX command, which has the `/tps` alias unless another command overrides it.

Unless you can isolate EssentialsX on a test server, this isn't an EssentialsX command issue.

**Comment by ArtelGG** [comment]
Is this enough isolation to confirm it?
![screenshot_2](https://user-images.githubusercontent.com/21347579/37360767-8930e2e0-26c7-11e8-9a14-074ec82bf594.png)

**Comment by LaxWasHere** [comment]
No, not enough.

![here](https://i.imgur.com/6Cwtwyv.png)

vanilla command.

**Comment by ArtelGG** [comment]
Shouldn't it be getting replaced by the EssX's one though?

**Comment by mdcfe** [comment]
@LaxWasHere Is that vanilla or Spigot/Paper? I thought LMP had one that looked identical to that, and it doesn't match the style of any other vanilla Minecraft commands that I can remember.

@ArtelGG You could use one of the many other aliases of `/gc` including `/lag` and `/etps`, or you could [manually create an alias](https://md678685.github.io/EssXDocs/#/Common-Issues?id=essentialsx-overrides-a-command-from-spigot-or-another-plugin) for `/tps` to `/essentials:gc`.

**Comment by ArtelGG** [comment]
It's not really a problem of that, I was just confused as to why I couldn't change the formatting of it as it very closely resembled an EssentialsX message.
