### ISSUE TITLE
EssentialsAntiBuild error: Event is Deprecated.

### ISSUE THREAD

**Issue by ItsMennyo** [EssentialsX/Essentials#1897]
### Information

EssentialsX version (run `/ess version`): 
INFO: Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1349 (MC: 1.12.2)
INFO: EssentialsX version: 2.0.1-b603
INFO: Vault version: 1.5.6-b49
INFO: EssentialsXProtect version: 2.0.1-b603
INFO: EssentialsXSpawn version: 2.0.1-b603
INFO: EssentialsXChat version: 2.0.1-b603
INFO: EssentialsXAntiBuild version: 2.0.1-b603

Server software (run `/version`): 
INFO: This server is running Paper version git-Paper-1349 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
INFO: You are running the latest version

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)): https://hastebin.com/yobomuyibu.md

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): https://hastebin.com/fevunosaxu.coffeescript

### Details

Describe your issue here.
I get this error on startup: https://hastebin.com/juqumogaxi.css

**Comment by drtshock** [comment]
This won't actually break anything on your server. It's just a warning that we're listening to a deprecated event.

**Comment by ItsMennyo** [comment]
It is still kinda annoying but good to know now.

**Comment by ItsMennyo** [comment]
It was a Bukkit config bug. But it is fixed now. Tnxx for the support!
