### ISSUE TITLE
AFK acting strange.

### ISSUE THREAD

**Issue by Remski01** [EssentialsX/Essentials#1898]
EssentialsX version (run `/ess version`): 2.0.1-b601

Server software (run `/version`): Spigot 1.12.2

Server log: Not any error.

EssentialsX config: https://gist.github.com/DutchUser/a13c5b5356f8f81b5cbf7e61d0562813 (locale included]

I runned a /ess debug, Please note that **i wont check if i have any afk related permissions**. Not sure if that is important. But it kinda should check for the permission because i used /afk

13.03 12:57:34 [Server] INFO calculated command (essentials) cost for RemcoMC as 0
13.03 12:57:34 [Server] INFO checking if RemcoMC can afford charge.
13.03 12:57:34 [Server] INFO checking if RemcoMC has essentials.essentials - true
13.03 12:57:34 [Server] INFO checking if RemcoMC has essentials.mail - true
13.03 12:57:34 [Server] INFO checking if RemcoMC has essentials.sleepingignored - true
13.03 12:57:34 [Server] INFO RemcoMC issued server command: /ess debug

**Note 1:**  After x minuts/hours the /afk does not longer work for me, for other it still works, only after /ess reload it works again fine again for me. 

**Note 2:** is does not matter much if im offline or online, as example. I went offline for few hours. Joined few minuts ago, Used /afk to test it again an issue. And it did not work again, only after an /ess reload it work fine. 

**Note 3:** The only thing that i have changed are a few lines in the locale, (afk related message)

**Comment by mdcfe** [comment]
Could you run `/ess debug`, *then* run `/afk` and post that output? After that, run `/ess version` and paste its **full output**.

**Comment by Remski01** [comment]
https://pastebin.com/H94Gf0ud

**PS: I used first "/afk Even drank halen." and right after that also "/afk" whitout any text behind it.**

**And not sure when you mean with** 
/ess version and paste its full output.
**It will just say that the plugin as reloaded and have version** 2.0.1-b601

**Comment by mdcfe** [comment]
Update EssentialsX to the [latest version](https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild), then run `/ess version` again.

Could you then provide a screenshot of exactly how that appears in the console, after running both `/afk test test` and `/afk` with debug enabled?

**Comment by Remski01** [comment]
Debug log: https://pastebin.com/GjK81zNy

What you see ingame(nothing): https://s17.postimg.org/amjpilq4f/Knipsel.png

/ess version: https://s17.postimg.org/bc2hv30zj/Knipsel.png

The "***********" is to show when i did "/afk" and "afk Hoi, This an test thing." 1 line up then the ******* the afk message should appear. (What is not the case now)

**Comment by mdcfe** [comment]
In the player list (`tab`), do the AFK players' names change to be greyed out?

In addition, could you paste the output of `/plugins`?

**Comment by Remski01** [comment]
For the plugins, >> https://s17.postimg.org/598g2bru7/Knipsel.png

I cant do "In the player list (tab), do the AFK players' names change to be greyed out?" now, I reloaded the after i had it and forget that request, so i have to wait till it happen again.

As side note, i have now build -b612 It still is happening,

**Comment by mdcfe** [comment]
@DutchUser Does this issue still occur?

**Comment by pop4959** [comment]
Can re-open if further details emerge (particularly if the author replies and still has this issue). There is no clear indication that this isn't a plugin related conflict, or so on.
