### ISSUE TITLE
Expanding the /exp command

### ISSUE THREAD

**Issue by Flavourized** [EssentialsX/Essentials#1899]
So currently the EXP command is not the equivalent of the eco command. 

## **A+ arg example:**
The eco command has the following args. These args are extremely useful
- Give - Add [amount] to [player]'s balance
- Take - Takes [amount] from [player]'s balance
- Set - Sets [player]'s balance to [amount]
- Reset - Set [player]'s balance to 0

## **What we currently have**:
The exp command only has these args. 
- Show - Returns how much EXP [player] has
- Set - Sets [player]'s EXP to [amount]
- Give - Adds [amount] to [player]'s EXP

## **What we need:**
This suggestion will make the EXP command have the following args:
- Give - Adds [amount] to [player]'s EXP
- Take - Takes [amount] from [player]'s EXP
- Set - Sets [player]'s EXP to [amount]
- Reset - Set [player]'s EXP to 0
- Show - Returns how much EXP [player] has

**Comment by mdcfe** [comment]
This has now been added - you can download the latest version from the [build server](https://ci.ender.zone/job/EssentialsX).
