### ISSUE TITLE
Suggestion: Essentials Chat Hover over tooltips

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#190]
I've been a die hard Essentails chat user since day 1, before I make the switch to DeluxeChat just for hover over tool-tips, any chance this would ever make it to Essentials chat?
I want to have click events when clicking usernames, and shift-clicking to put something into the chat bar, and hover over messages that can include essentials variables.

**Comment by drtshock** [comment]
Possibly, but it'd be awhile before it's in here.

**Comment by TomLewis** [comment]
Ok, thanks, Ill move over to DeluxeChat until its implemented, then move back when it is! ;p

**Comment by pop4959** [comment]
Let's move discussion of hover events to #2391, as this would be part of larger scale improvements to the plugin as a whole.
