### ISSUE TITLE
After updating essentails confirm-pay is not default to off.

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#1902]
PaperSpigot: 1349
Ess: 2.0.1-b603
MC: 1.12.2

All of a sudden after updating the confirm to pay has been turned off without warning, so /pay user 1 will be instant again, this has thrown off nearly everyone who is used to using the command twice to trigger a payment.

How can I set a default value for all players to turn this on again? I scanned the config and cant see it at all.

**Comment by LaxWasHere** [comment]
Wait for #1816 to be merged.
