### ISSUE TITLE
EssentialsSpawn and EssentialsXMPP Crashing server

### ISSUE THREAD

**Issue by FlameHeroDev** [EssentialsX/Essentials#1905]
### Information

Full output of `/ess version`:

[02:06:13 WARN]: config broken for xmpp
[02:06:13 INFO]: [Essentials] Using locale en_US
[02:06:13 INFO]: [MW] Essentials has been reloaded. Version: 2.0.1-b488
Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):
https://gist.github.com/FlameHeroDev/9849dad2ebccc57668e2e7bd104183db
EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 
https://gist.github.com/FlameHeroDev/2cce8a82c34dd65de16e3851245f3f6a
### Details

Server starts, essspawn and xmpp start logging warns and errors to console, 1 minute later server crashes.

**Comment by LaxWasHere** [comment]
Cmon bud, buy the plugins

https://i.imgur.com/2Em2LiD.png
