### ISSUE TITLE
Essentials recognizing FactionsUUID bank accounts as players

### ISSUE THREAD

**Issue by xXBarchticXx** [EssentialsX/Essentials#191]
I am here to report not one but 2 bugs. When you specify a first time join balance from essentialsx and then create a "new" faction it adds that amount to the factions bank balance as essentials sees the faction as a player. Also in baltop it displays faction balances as it also does recognize factions as players.

**Comment by KyrneDev** [comment]
I can confirm the above

**Comment by xXBarchticXx** [comment]
Any updates?

**Comment by drtshock** [comment]
no ;c

**Comment by SupaHam** [comment]
Apologies for the late reply.

This has been fixed in e95fad0. You can grab the fix from [build 366](https://ci.drtshock.net/job/EssentialsX/366/) on the CI server.
