### ISSUE TITLE
/nick off for users who can only change their username's color

### ISSUE THREAD

**Issue by KAGamerAlex** [EssentialsX/Essentials#1910]
### Information

Full output of `/ess version`: 2.0.1-b525
(my build of EssentialsX doesn't have /ess version, but looking through the commits for this project, I don't see the issue I'm about to detail being addressed yet)

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):  https://gist.github.com/KAGamerAlex/b637f9bf989e7df86aef5afc4d29ecdf

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 
https://gist.github.com/KAGamerAlex/78547e8c2efe2fb109c2575c46d6e726

### Details

Hi all.  We have permissions configured such that our default group has access to the following:
• essentials.nick
• essentials.nick.color
• essentials.nick.changecolors

This allows them to simply change the color of their username, but not the actual characters of the username in their nick, as expected.  However, if these users try to use /nick off, it won't work.  Clientside, they get:
`[01:09:45] [Client thread/INFO]: [CHAT] Error: Nicknames can only have their colors changed.`
`[01:09:58] [Client thread/INFO]: [CHAT] [Islander]~KA_Gamer: eyyy, I fixed a bug` (included for reference to server's log)

You'll see in the latest.log file a corresponding attempt to do /nick off at line 1467 (there is a difference in system time between the server and client by an hour and a few minutes because of timezones and such) :
1467: `[02:10:06] [Server thread/INFO]: KA_Gamer issued server command: /nick off`
1471: `[02:10:19] [Async Chat Thread - #4/INFO]: [Islander]~KA_Gamer: eyyy, I fixed a bug` (included for reference)

I know there was an with "nickNamesOnlyColorChanges" not being present in the message.properties file, and I've made the necessary changes to correct that.  However, the lack of access to /nick off remains an issue.

**Comment by mdcfe** [comment]
This is a bug - the `changecolors` check happens [before](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/commands/Commandnick.java) checking for `/nick off`.

**Comment by mdcfe** [comment]
This has been fixed in the latest build of EssentialsX - grab it from the [build server](https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild).

**Comment by IITFA** [comment]
The update did not fix this for my server.

**Comment by mdcfe** [comment]
@IITFA Could you open a separate issue, filling out the relevant template?
