### ISSUE TITLE
[Enhancement] Adding /itemlore to EssentialsX

### ISSUE THREAD

**Issue by ImNachoMans** [EssentialsX/Essentials#1911]
### Information

Full output of `/ess version`:

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 

### Details

Describe your issue here.

I would like to suggest a new feature to EssentialsX which is renaming your Item and Itemlore. It's a good feature without adding separate plugins. Also an easier alternative for the vanilla rename.

**Comment by LaxWasHere** [comment]
Just get a new item with a new name and a new lore?

**Comment by ImNachoMans** [comment]
Yeah

**Comment by caojohnny** [comment]
He means that you can just obtain a new item using the `/item` command rather than changing the lore and name.

**Comment by ImNachoMans** [comment]
Oh well it would be good if there was a command like /itemname and itemlore because if there were a long enchantment on an item, you wouldn't have to enchant it again

**Comment by ImNachoMans** [comment]
helo

**Comment by Dolphin2Point1** [comment]
Right now, you can use [EpicRename](https://www.spigotmc.org/resources/epicrename.4341/).

**Comment by ImNachoMans** [comment]
Yes I know, I just wanted to add a suggestion to EssentialsX for having this feature.

**Comment by triagonal** [comment]
The `/itemname` command was implemented in #2573 and is present in versions `2.17.0` and above. An `/itemlore` command (or similar) has yet to be added to EssentialsX.

**Comment by triagonal** [comment]
The `/itemlore` command has now been implemented in 711bfed and is present in versions `2.17.2.155` and above. Download the latest build [here](https://essentialsx.net/downloads.html).
