### ISSUE TITLE
Command /back issues

### ISSUE THREAD

**Issue by AmazedMender16** [EssentialsX/Essentials#1912]
There seems to be a issue with the /back feature
here is a example of it happening https://youtu.be/iMpZ7axYZQ0

http://prntscr.com/itbt40

Essentials Version: b575

**Comment by mdcfe** [comment]
Please write up what the issue is.

**Comment by AmazedMender16** [comment]
As you can see in the video its not saving the correct last positions of the players.

it takes you back to a location you were a while ago
or some /backs ago
not the previous

**Comment by mdcfe** [comment]
Please post your EssentialsX config as requested in the template.

**Comment by AmazedMender16** [comment]
Anyway i can share this in private?

**Comment by SlimeDog** [comment]
I have a similar issue when I use non-Essentials teleportation. For example, if I _/mvtp_ somewhere, Essentials seems unaware of it (wrt /back). I have worked around it by aliasing _mvtp_ to
> essentials :tppos ~ ~ ~
> mvtp <wherever>

Then _/back_ works as desired.

**Comment by mdcfe** [comment]
@SlimeDog Please post your config so we can investigate the issue.

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to respond and reopen the issue.

**Comment by SlimeDog** [comment]
[config.yml.txt](https://github.com/EssentialsX/Essentials/files/1971915/config.yml.txt)

**Comment by mdcfe** [comment]
@SlimeDog Apologies for the delay, but in your config, `register-back-in-listener` is set to `false`. This prevents EssentialsX picking up teleports from other plugins. For EssentialsX to correctly pick up other plugins' teleports, set `register-back-in-listener: true` in your config.

**Comment by SlimeDog** [comment]
Thanks.
