### ISSUE TITLE
Essentials is missing? [SOLVED]

### ISSUE THREAD

**Issue by SkotKeller** [EssentialsX/Essentials#1914]
I am not even sure how to format this.
There no logs there is nothing. 
Any essentials thing I type in has no return; not even /ess reload or /ess version.
I have noticed it when players started PM me crazzy with say we don't have /home.
I looked into my Server plugins and still had EssentialsX-2.0.1.jar
So here I am having a panic attack not knowing what to do!

**Comment by mdcfe** [comment]
Could you post your server's full startup log on [Gist](https://gist.github.com)?

**Comment by SkotKeller** [comment]
https://pastebin.com/iFSxBKwi

**Comment by SkotKeller** [comment]
https://gist.github.com/SkotKeller

**Comment by mdcfe** [comment]
Delete your EssentialsX jar and redownload it from [the build server](https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild).
