### ISSUE TITLE
Compass no longer pointing to world spawn after going through any portal and back

### ISSUE THREAD

**Issue by axemwa** [EssentialsX/Essentials#1918]
Information

Full output of /ess version:

Server Version: 1.12.2-R0.1-SNAPSHOT git-paper-1355 (MC: 1.12.2)
EssentialsX version: 2.15.0.1
LuckPerms version: 4.1.25
Vault Version: 1.6.1
EssentialsXChat version: 2.15.0.1

Server log (upload logs/latest.log to Gist): https://gist.github.com/axemwa/9bb99fbce5a049ae3c2fd1ec86dbefd7

EssentialsX config (upload plugins/Essentials/config.yml to Gist): https://gist.github.com/axemwa/f358f7df2d8e20ecc3f4c80fd4c88790

Details:

Hi there the essientials plugin seems to be changing defualt players compasses after entering portals and returning eg: Before I leave the overworld my compass points to world spawn but for some reason if I enter a portal to any world and then come back to the overworld and check my compass it points to the bed spawn instead of the overworld spawn  please help me fix this if possible its really anoying. Cheerz!

(https://user-images.githubusercontent.com/37608633/37695059-38f2b9f6-2d1c-11e8-9c9d-9ab29979de71.png)

**Comment by drtshock** [comment]
Please fill out the entire issue template. Mainly, we need your config.yml and server log here please.

Also, see if you still have the issue on the latest version from https://ci.ender.zone/job/EssentialsX

**Comment by axemwa** [comment]
hi thanx for the reply, yes i still have the issue on the latest build heres the server log and config.yml
[latest.log](https://github.com/EssentialsX/Essentials/files/1832170/latest.log)
[configyml.zip](https://github.com/EssentialsX/Essentials/files/1832172/configyml.zip)

Only happens after going through a portal and stops happening when i remove essentials

**Comment by axemwa** [comment]
updated to latest version from jenkins didnt seem to fix it but now the Nickname won't display on the online players list (TAB) even tho the setting in config is set to true

**Comment by axemwa** [comment]
updating to latest version didnt help but after updating the nickname doesnt display in player list (TAB) only real username shows, after updating to latest essentials

**Comment by axemwa** [comment]
On latest build i had to manually put in permssions for my permissions manager cause permissions in config werent working anymore (even with bukkit perms turned off in config) for some reason.

Still having the issue with compass pointing to bed after using a portal to another world though

**Comment by axemwa** [comment]
Template updated

**Comment by Dolphin2Point1** [comment]
@axemwa Can you show us a video of it? Because I don't see how this happens.

**Comment by Infinityy1** [comment]
Failed to reproduce
CraftBukkit version git-Spigot-c3093ef-7e94e65 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Essentials Version: 2.1.5 (Also tested on b614)

**Comment by axemwa** [comment]
@loper12  Thanks for the response here's a video URL I've made of the reoccurring/reproducing issue: https://www.youtube.com/watch?v=lDu-0YTIwnY&feature=youtu.be

**Comment by axemwa** [comment]
updated /ess version in the template above due to newer plugins installed

**Comment by mdcfe** [comment]
I think the intended behaviour is to point compasses towards the bed spawnpoint rather than the world's spawnpoint.

~~I'll see if there's a way to disable this already.~~

**Edit:** this is [intended behaviour](https://github.com/EssentialsX/Essentials/blob/823f1c2ee3b117781b901214656bd32432b35d17/Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java#L353).

**Comment by Dolphin2Point1** [comment]
@axemwa Maybe you could try EssentialsX's spawn plugin, or Multiverse's world spawning system. You are using the vanilla command(which isn't the best option).

**Comment by mdcfe** [comment]
@loper12 This is a feature of Essentials that has been around for years. The spawn plugin is not an issue.

I think this should be made toggleable in the config.

**Comment by Dolphin2Point1** [comment]
ok.

**Comment by axemwa** [comment]
That would be a great idea @md678685, if it were toggleable that would be awesome I appreciate the effort u guys put into helping me with this plugin, thankyou.

**Comment by mdcfe** [comment]
This has been added in the latest build of EssentialsX - grab it from the [build server](https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild).

**Comment by axemwa** [comment]
Thanx! Does the old config need to be deleted? EDIT - Yep looks like it thanx guys works great!

**Comment by mdcfe** [comment]
You don't need to delete the config - you can just add the new configs options to the old config if you'd prefer.

**Comment by axemwa** [comment]
oh thanks I'll remember that for future reference
