### ISSUE TITLE
Essentials kit.yml dont give all items but with older versions it does!

### ISSUE THREAD

**Issue by ItsMennyo** [EssentialsX/Essentials#1919]
### Information

Full output of `/ess version`:
INFO: Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1353 (MC: 1.12.2)
INFO: EssentialsX version: 2.0.1-b603
INFO: PermissionsEx version: 1.23.4
INFO: Vault version: 1.5.6-b49
INFO: EssentialsXProtect version: 2.0.1-b603
INFO: EssentialsXChat version: 2.0.1-b603
INFO: EssentialsXAntiBuild version: 2.0.1-b603
INFO: EssentialsXSpawn version: 2.0.1-b603

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):
Full server log on request...
Essentials/Vault console log: https://hastebin.com/bozacawate.md

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 
Essentials config: https://hastebin.com/nomupiyomo.coffeescript
Kits config: https://hastebin.com/ezitewasuf.rb
### Details

I paste my old kits into the new kits.yml file but I dont get a book with custom title, author and lore and I also dont get armor or food. IDs are good ect. This always worked with older versions (version 2.0.1-b483).

**Comment by mdcfe** [comment]
EssentialsX should migrate your kits automatically.

Could you post `upgrades-done.yml` and `kits.yml`?

**Comment by ItsMennyo** [comment]
@md678685 
upgrades-done.yml: https://hastebin.com/ateyonovus.scala
kits.yml: https://hastebin.com/ezitewasuf.rb

**Comment by drtshock** [comment]
You didn't automatically allow your kits to be converted (I see that it's not noted in upgrades-done.yml.

Are you sure you didn't break something on pasting? Can you post your books.yml please and then also the log with /ess debug enabled when executing /kit <anyofthesekits>

**Comment by ItsMennyo** [comment]
I pasted it manually in kits.yml but after 7 hours it trying yo make it wotk I got it working again by myself because help is so slow here 😑

**Comment by mdcfe** [comment]
We're busy people that support this plugin in our limited free time.

Could you post how you solved the issue?

**Comment by ItsMennyo** [comment]
True but it still took me 7 hours to find out and it was that 1 min work to correct. While converting the "book:Claim" part was randomly removed so it could not load the book and the items after that. I did fully copy the kits and book.yml file form my old config including the book:Claim part but it was not there anymore.
