### ISSUE TITLE
When toggling afk status to off with /afk it changes the players name in the player list (tab) back to player name instead of displayname (nick) even though change-displayname and change-playerlist are set to true

### ISSUE THREAD

**Issue by axemwa** [EssentialsX/Essentials#1923]
Information

Full output of /ess version:

Server Version: 1.12.2-R0.1-SNAPSHOT git-paper-1355 (MC: 1.12.2)
EssentialsX version: 2.15.0.1
LuckPerms version: 4.1.25
Vault Version: 1.6.1
EssentialsXChat version: 2.15.0.1

Server log (upload logs/latest.log to Gist): https://gist.github.com/axemwa/9bb99fbce5a049ae3c2fd1ec86dbefd7

EssentialsX config (upload plugins/Essentials/config.yml to Gist): https://gist.github.com/axemwa/f358f7df2d8e20ecc3f4c80fd4c88790

Details:

Hi when a player toggles afk status to off manually with /afk command it changes the players name in the player list (tab) back to the (default)player name instead of displayname (nick) even though change-displayname and change-playerlist are set to true

(https://user-images.githubusercontent.com/37608633/37695059-38f2b9f6-2d1c-11e8-9c9d-9ab29979de71.png)

**Comment by mdcfe** [comment]
Please post the **full output** of `/ess version` as requested.

**Comment by axemwa** [comment]
Ok I have edited/updated the /ess version output details as above. Thanks.

**Comment by Infinityy1** [comment]
Can Reproduce 2.1.5(Also tested on b615)

**Comment by axemwa** [comment]
Just updated /ess version in template again since i had installed newer plugins, @Infinityy1 yes problem still reproduces/reoccuring in essentialsx 2.15.0.1

**Comment by mdcfe** [comment]
@Infinityy1 `2.1.5` is not an EssentialsX version; do you mean `2.15.0.1`?

@axemwa No changes in 2.15.0.1 to AFK, but this will be looked into.

**Comment by axemwa** [comment]
@md678685 yeah i think that's what they meant (2.15.0.1) and thanks I appreciate it, it's only when u untoggle afk manually that it changes the players name in the player list (the list you get when you press TAB) back to default, other than that it all works great! Thanks again :)

**Comment by axemwa** [comment]
Sorry I noticed in description/details I added 

"Hi there the essientials plugin seems to be changing defualt players compasses after entering portals and returning eg: Before I leave the overworld my compass points to world spawn but for some reason if I enter a portal to any world and then come back to the overworld and check my compass it points to the bed spawn instead of the overworld spawn please help me fix this if possible its really anoying. Cheerz!".

This was obviously for the compass update which is now working but somehow the description from that issue page ended up here so I've edited it since then to say what it should.

**Comment by ProblemsSender** [comment]
I did, read this and try to emulate it
1/Enter /nick name it first appears in player list as nickname
2/Waiting it to auto-afk or enter /afk command
3/It might looks like will keep using your nickname to mask the real name, but when you turn off afk
4/It become real name, I also tested it with other player, we can see the real name of player
Read my opened issue later of this #2291

**Comment by mdcfe** [comment]
@axemwa @ProblemsSender @Infinityy1 I've pushed 579f554edbd7ec3b2dd5bcde4fdd42b10606063f which should fix this. Could you try updating to the [latest version](https://ci.ender.zone/job/EssentialsX) to see if the problem persists?

**Comment by axemwa** [comment]
All systems a go! The problem is no longer persisting, when typing /afk(or waiting for auto afk) and then typing /afk again (to turn off afk) the players nickname is still there and no longer reverts to the players (actual/normal) name excellent work!

Also confirmed in latest experimental build - [EssentialsX-2.16-pre1.11](https://ci.ender.zone/job/EssentialsX-Experimental/52/)

**Comment by ProblemsSender** [comment]
*Confirmed! The bug no longer found just now, I will test it deeper. If it appears again, there will be another comment of me. If not, Congrats!

**Comment by iMxAndyy** [comment]
Hi, I see this was resolved years ago but I'm now having this same issue on my server. 
When players toggle AFK either manually or automatically their name reverts to their unformatted username. 
and when exiting AFK it remains as their unformatted name
However, a few minutes later it reverts back to their formatted nickname.
