### ISSUE TITLE
Could not pass event StandardPaperServerListPingEventImpl

### ISSUE THREAD

**Issue by DardBrinza** [EssentialsX/Essentials#1924]
Latest build paper spigot 1.12.2
https://pastebin.com/1zS62Heb

**Comment by mdcfe** [comment]
Paper changed their ServerListPingEvent again: PaperMC/Paper@e15167251bab0bc5dbcd136b40bdb66e9a16494d

**Comment by Dolphin2Point1** [comment]
@DardBrinza There was a template for a reason. Please edit your problem with the updated info.

**Comment by mdcfe** [comment]
@loper12 No need to demand for the template when we know exactly what the issue and cause are.

Closing as Minecrell has submitted #1925 to fix this.
