### ISSUE TITLE
Converter 

### ISSUE THREAD

**Issue by TheIntelloBox** [EssentialsX/Essentials#1929]
Hi,

I'm using Essentials from Spigot. Is there a converter when I switch to EssentialsX or have you got tips ?

**Comment by mdcfe** [comment]
You delete the Essentials jars, including AntiBuild, Chat, GeoIP, Protect, Spawn and XMPP, then replace them with the relevant EssentialsX jars from the [build server](https://ci.ender.zone/job/EssentialsX).

EssentialsX will update your configs and userdata files for you.

If you've got custom `messages.properties` files, you can add any missing messages from [this page](https://github.com/EssentialsX/Essentials/tree/2.x/Essentials/src) - you'll need to look for the right language then copy new messages into your existing files.

You may also want to update your `config.yml`, which can be done by renaming it to generate a new file **after you've run EssentialsX once** (to ensure kits and userdata are updated properly before the config is replaced).
