### ISSUE TITLE
Warp not working

### ISSUE THREAD

**Issue by supernunoski99** [EssentialsX/Essentials#193]
When some player try to make /warp minas or /warp membro or another warp it says that they don't have permission to do it.

In the ranks I have this permissions.
- essentials.warp
- essentials.warps.<warpname>

No errors in the console

Waiting for the fastest answer.

**Comment by EvilOlaf** [comment]
Add essentials.warps.membro for example. Or wildcard for all warps.

**Comment by supernunoski99** [comment]
~i've added

**Comment by supernunoski99** [comment]
still nt working.

**Comment by drtshock** [comment]
You need essentials.setwarp to make warps.

**Comment by EvilOlaf** [comment]
@drtshock True, but this won't fix the issue as well as he does not want his users to create warps  :grin:

**Comment by drtshock** [comment]
The OP says "make warp"

**Comment by EvilOlaf** [comment]
Sounds more like "they try to run the command /warp ...." ^^
