### ISSUE TITLE
Extinguish Others Permission

### ISSUE THREAD

**Issue by mcmbuddy** [EssentialsX/Essentials#1934]
Feature needed to give players permission to extinguish others. Right now the only permission given is to extinguish yourself.

I suggest setting the permission node as Essentials.Ext.Others.

Thanks

**Comment by Dolphin2Point1** [comment]
You could make a pr.

**Comment by Infinityy1** [comment]
The permission essentials.ext gives permission to extinguish others does it not?
https://gyazo.com/7a38cf250cc4fcc654092347086dd114

**Comment by mdcfe** [comment]
`/ext` can already extinguish other players, provided you have access to the command itself via `essentials.ext`.
