### ISSUE TITLE
/msg Not Working

### ISSUE THREAD

**Issue by tylerhyperHD** [EssentialsX/Essentials#194]
I tried doing /msg and it fails to work, it just says unknown command.

**Comment by drtshock** [comment]
paste your startup log in a pastebin as well as your config.yml

**Comment by tylerhyperHD** [comment]
The issue is, there are no errors when starting up, the config is the default config, and I am just using netbeans to compile it.

**Comment by drtshock** [comment]
Download it from https://ci.drtshock.net - it works fine.
