### ISSUE TITLE
Jail Respawn?

### ISSUE THREAD

**Issue by ImdralRaenwood** [EssentialsX/Essentials#1947]
Hey there. 
I have a question regarding the jails. 
Is there a way to remove the auto-tp'ing of players AFTER being jailed?

Say, I do /jail Imdral_Raenwood rochdailcell1 30

Then the player is jailed there, for 30 seconds. But, after, they are tp'd back to their previous location.
I'd like to be able to LEAVE them there. 

So, they're "jailed," for 30 seconds, then, after the time is up, they're unjailed (jail toggles off), but they are left in the cell. 

The key difference is that this allows them to be released/escape, and then they are inconvenienced with having to travel back to their old location. 

How can I turn off the auto-tp?

**Comment by ImdralRaenwood** [comment]
I see you added some commits, and a reference. 
What exactly does this mean, for me?
Next build?

**Comment by Ichbinjoe** [comment]
I have opened a PR. If the PR is merged, then it will be within the next build. This will occur when someone with write access to the repository reviews my code and decides to incorperate it.

**Comment by ImdralRaenwood** [comment]
How will I know when this happens?
Will it notify my github account somehow?

**Comment by mdcfe** [comment]
When #1949 is merged, we'll close this issue and you'll get a notification to say that it's closed.

**Comment by ImdralRaenwood** [comment]
So, what does the above mean? ^
I see a bunch of code.

**Comment by mdcfe** [comment]
@ImralRaenwood The feature is still being worked on, but isn't part of EssentialsX yet.

**Comment by mdcfe** [comment]
This has now been added - you can download the latest version from the [build server](https://ci.ender.zone/job/EssentialsX).
