### ISSUE TITLE
Daylight sensor triggering /fly command for certain users(admin) after logging out and then back in

### ISSUE THREAD

**Issue by axemwa** [EssentialsX/Essentials#1950]
### Information

Full output of `/ess version`:

Server Version: 1.12.2-R0.1-SNAPSHOT git-paper-1355 (MC: 1.12.2)
EssentialsX version: 2.15.0.1
LuckPerms version: 4.1.25
Vault Version: 1.6.1
EssentialsXChat version: 2.15.0.1

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)): https://gist.github.com/axemwa/9bb99fbce5a049ae3c2fd1ec86dbefd7

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)):  https://gist.github.com/axemwa/f358f7df2d8e20ecc3f4c80fd4c88790

### Details

When a user has essentials.* permission set to true, I noticed that if such a player was standing on a daylight sensor and logged out and logged back in it would enable fly mode automaticlly (even if it was off before loging out), it's not really an issue for me but thought I'd report it anyway incase ya's didn't know. I'm not sure what permission node specifically is doing this but it seems to be essentials related becuase removing the essentials* from permissions stops the daylight sensor problem.

**Comment by mdcfe** [comment]
If you don't fully understand the implications of using a wildcard, don't use a wildcard.

`essentials.fly.safelogin` will enable fly mode when a user logs in but is not on the ground, which is what EssentialsX seems to be the case when someone stands on a daylight sensor.

**Comment by axemwa** [comment]
ok yeah that makes sense thankyou, sorry ive taken over this mc server for a friend so im new to all this and enjoy learning new things and reporting any thing i find to help others. Kind Regards.
