### ISSUE TITLE
Essentials Protect Emergency Mode

### ISSUE THREAD

**Issue by TheIntelloBox** [EssentialsX/Essentials#1951]
Hi, 

[10:18:24] [Server thread/WARN]: Enabled plugin with unregistered PluginClassLoader EssentialsProtect v2.15.0.1
[10:18:24] [Server thread/ERROR]: Essentials not installed or failed to load. Essenials Protect is in emergency mode now. 

I'm using PaperSpigot 1.12.2 and have this problem with HolographicDisplays, GetDownPro and many other plugins such as Teleport+ !

**Comment by LaxWasHere** [comment]
Please fill these in for help.
EssentialsX version (run `/essentials version`): 

Server software (run `/version`): 

Server (`logs/latest.log`):

EssentialsX config (`plugins/Essentials/config.yml`): 

Paste logs and configuration here <https://hasteb.in/>

**Comment by TheIntelloBox** [comment]
/ess version:
[12:02:45] [Server thread/INFO]: Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1375 (MC: 1.12.2)
[12:02:45] [Server thread/INFO]: EssentialsX version: 2.15.0.1
[12:02:45] [Server thread/INFO]: LuckPerms version: 4.1.52
[12:02:45] [Server thread/INFO]: Vault version: 1.6.1
[12:02:45] [Server thread/INFO]: EssentialsXChat version: 2.15.0.1
[12:02:45] [Server thread/INFO]: EssentialsXProtect version: 2.15.0.1
[12:02:45] [Server thread/INFO]: EssentialsXSpawn version: 2.15.0.1

/ver:
[12:02:59] [Server thread/INFO]: This server is running Paper version git-Paper-1375 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Logs: https://pastebin.com/Jqz2Z8Cy

Essentials' Config: https://pastebin.com/CYA2a9nY

**Comment by mdcfe** [comment]
The log you posted does not show Essentials Protect loading in emergency mode.

Please systematically add plugins back (half at a time or one by one) until the issue reoccurs, and check their dependencies in their `plugin.yml`s to make sure there isn't a dependency loop somewhere.

**Comment by TheIntelloBox** [comment]
I already did that: when I put Teleport+ and HolographicDisplays, EssentialsProtect is in emergency mode.

Here are the logs where EssProtect is in emergency: https://pastebin.com/ThQtKTgk

**Comment by Infinityy1** [comment]
A few things
 1) Try Fixing The LOTS of errors you have
 2) Try getting rid of ezprotect it might be interfering
 3) Get rid of moneyprinters as you are not using HD(Or its not loading)

**Comment by mdcfe** [comment]
@TheIntelloBox Does it fail to load with just one of those plugins installed? What are their dependencies in their `plugin.yml`s?

**Comment by TheIntelloBox** [comment]
Teleport+ has no dependency but maybe it interacts with Essentials. The other plugins have HD as dependency.

**Comment by TheIntelloBox** [comment]
The problem is that ESS is loaded after ESSProtect. You can't solve that ?

**Comment by mdcfe** [comment]
No, because Spigot's plugin load order is out of our control aside from the `plugin.yml`, which is already configured to load Essentials before EssentialsProtect. We can't make Spigot follow that more strictly than it currently does, so if that's being ignored then we can't do anything about that.

#1954 adds a means for EssentialsProtect to automatically continue enabling itself once Spigot has actually enabled Essentials itself, resolving issues like this where EssentialsX *does* load, just later than expected.

**Comment by TheIntelloBox** [comment]
Teleport+ is a plugin which causes the problem, could you see why ?

**Comment by mdcfe** [comment]
Teleport+ causing load order issues isn't our fault (and likely isn't theirs either).

You can try changing the name in that plugin's `plugin.yml` to not include `+` (maybe `TeleportPlus`).

**Comment by TheIntelloBox** [comment]
That's not my plugin, so I cant. :x

**Comment by mdcfe** [comment]
You can manually edit the jar, assuming you're confident that you don't have any plugins installed that depend on it.

**Comment by TheIntelloBox** [comment]
The name is Teleport in the plugin.yml.

**Comment by TheIntelloBox** [comment]
Same problem with LuckyBlocksSuper : dependency: [WorldEdit, WorldGuard, Vault].

**Comment by TheIntelloBox** [comment]
So ?

**Comment by mdcfe** [comment]
We don't control the Spigot plugin load order. I don't know what causes this issue, so I can't help with this.

**Comment by TheIntelloBox** [comment]
Could you check maybe in the source code of these plugins ?

**Comment by mdcfe** [comment]
Late response, but as I said it's Spigot's fault if plugins are forced into loading in the wrong order, not the plugins.

**Comment by mdcfe** [comment]
Could you update to the [latest versions](https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild) of both EssentialsX and EssentialsXProtect, then see whether the issue still occurs?

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to respond and reopen the issue.

**Comment by matisse987** [comment]
for people googling for a fix in the future, I checked my plugins folder and the essentialsx.jar wasn't there, just all the things that come with it. try redownloading that same exact .jar file or completely get a new essentialsx version and delete all the old ones. let me know if you need help.
