### ISSUE TITLE
Checking if 

### ISSUE THREAD

**Issue by neqs20** [EssentialsX/Essentials#1956]
### Information

Full output of `/ess version`:

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 

### Details
/ess version
Server version: 1.12-R0.1-SNAPSHOT git-Spigot-ede465d-bb4ae3b (MC: 1.12)
EssentialsX version: 2.15.0.1
PermissionsEx version: 1.23.4
Vault version: 1.5.6-b49
EssentialsXProtect version: 2.15.0.1
EssentialsXChat version: 2.15.0.1
EssentialsXGeoIP version: 2.15.0.1
EssentialsXAntiBuild version: 2.15.0.1
EssentialsXSpawn version: 2.15.0.1

server log: https://gist.github.com/HazmatDemon/697510046e7b414ef65289d306bc8a77
config: https://gist.github.com/HazmatDemon/dcdaaec4d3e5c3911a1fbc51ae6f1ec6

I just want to prevent displaying this on my console:

[Essentials] checking if Gracz has essentials.afk.auto - false

I had old version if EssentialsX and I didnt have this thing. 
Is there any way to disable it or is that kind of issue with code?

**Comment by Remski01** [comment]
Set this

More output to the console.
debug: true 

to false

**Comment by neqs20** [comment]
Thank you so much :)
