### ISSUE TITLE
Ess Problem.

### ISSUE THREAD

**Issue by TheIntelloBox** [EssentialsX/Essentials#1957]
https://hastebin.com/gukararafu.vbs

**Comment by Xeyame** [comment]
It looks like you are trying to load Essentials with something like plugman, Reboot your server instead.

**Comment by mdcfe** [comment]
Don't use PerWorldPlugins. If you need different plugins for different worlds, set up parallel Spigot/Paper servers on a Bungeecord proxy.

In addition, redownloading EssentialsX will ensure that the jar is intact.
