### ISSUE TITLE
Request: Item Meta, Rename existing item.

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#1958]
http://wiki.mc-ess.net/wiki/Item_Meta

The custom item creation has always been my go-to for custom items, one thing that drives me utterly insane, is if you create a custom item and you have to re-name it, or you spelt it wrong and you have to edit it, or there is a player that wants an item renamed, I want to create multiple items with different names so I dupe then and be able to change their names and so on.

Can we have a rename command that respects all the Item Meta parameters? 

So If I'm holding a sword with custom enchants I could do /rename name:&eNew_name and it'll just update its name, or maybe a better idea would be call it an item update? so we use the existing /i system but we have a parameter to update an item in hand? /i update name:New_name, /i update unbreaking:2

**Comment by mdcfe** [comment]
This was the purpose of #672, however that PR has been inactive for quite a while.

**Comment by pop4959** [comment]
The latest versions of Essentials have the `/itemname` command which should do this.
