### ISSUE TITLE
Can not modify chat format

### ISSUE THREAD

**Issue by scriptinator** [EssentialsX/Essentials#196]
I have tried changing the config option to remove the <'s around the username. I have tried resetting the config and running through a yaml parser, essentials works, but I can never remove the brackets.

**Comment by vemacs** [comment]
Install EssentialsChat.

**Comment by scriptinator** [comment]
Regular or X. I already have the EssentialsXChat plugin

**Comment by drtshock** [comment]
Then the plugin didn't enable or something. Do you have vault?

**Comment by scriptinator** [comment]
Yes, I have Vault

**Comment by DataPools** [comment]
I have the same problem. I get this when loading it up: 

```
20.11 01:09:04 [Server] INFO [01:09:04 INFO]: [EssentialsChat] Enabling EssentialsChat v2.0.1-b174
```

So the plugin is enabled
However, when I reload EssentialsChat with Plugman, the chat format kicks in (Of course without hooking on to anything else)
And Yes I do have Vault
