### ISSUE TITLE
EssentialXMPP Not allowing 1.8 players to join

### ISSUE THREAD

**Issue by FlameHeroDev** [EssentialsX/Essentials#1960]
### Information

Full output of `/ess version`:

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 

### Details

EssentialsXMPP instantly kicking players running on 1.8. Please help me fix this, this is ruining the entire server.

```java
04.04 19:20:46 [Server] WARN [Essentials] Task #53615 for Essentials v2.15.0.1 generated an exception
04.04 19:20:46 [Server] INFO java.lang.NullPointerException: null
04.04 19:20:46 [Server] INFO at com.earth2me.essentials.xmpp.XMPPManager.updatePresence(XMPPManager.java:152) ~[?:?]
04.04 19:20:46 [Server] INFO at com.earth2me.essentials.xmpp.EssentialsXMPP.updatePresence(EssentialsXMPP.java:109) ~[?:?]
04.04 19:20:46 [Server] INFO at com.earth2me.essentials.xmpp.EssentialsXMPPPlayerListener$2.run(EssentialsXMPPPlayerListener.java:51) ~[?:?]
04.04 19:20:46 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[custom.jar:git-Spigot-c3093ef-7e94e65]
04.04 19:20:46 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [custom.jar:git-Spigot-c3093ef-7e94e65]
04.04 19:20:46 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [custom.jar:git-Spigot-c3093ef-7e94e65]
04.04 19:20:46 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [custom.jar:git-Spigot-c3093ef-7e94e65]
04.04 19:20:46 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [custom.jar:git-Spigot-c3093ef-7e94e65]
04.04 19:20:46 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [custom.jar:git-Spigot-c3093ef-7e94e65]
04.04 19:20:46 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```

**Comment by mdcfe** [comment]
Please follow the instructions in the template.

> Otherwise, if you are reporting a bug, read on:
> 1.  Fill out the template, running the commands either in the console or 
    as a player. Don't simply put "latest" or we will ignore it.
>
> 2.  When linking files, do not attach them to the post! Paste them on 
    https://gist.github.com/, then paste a link to them in the relevant parts
    of the template. Avoid using Hastebin or Pastebin, as files are deleted
    after a period of time.
> 
> ...
> 
> 6.  Delete this line and all above lines before posting your issue!       -->

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to respond and reopen the issue.
