### ISSUE TITLE
'No Effects' on Potion Tipped Arrows from kits

### ISSUE THREAD

**Issue by StormyIceLeopard** [EssentialsX/Essentials#1962]
### Information

Full output of `/ess version`:
20:22:02 [WARNING] Event net.ME1312.SubServers.Bungee.Event.SubSendCommandEvent@66e5448f took 327,431,776ns to process!
20:22:02 [INFO] Factions > CONSOLE issued server command: /ess version
20:22:02 [INFO] Factions > Server version: 1.12.2-R0.1-SNAPSHOT git-Spigot-b6ecf3b-68b4fb6 (MC: 1.12.2)
20:22:02 [INFO] Factions > EssentialsX version: 2.15.0.1
20:22:02 [INFO] Factions > PermissionsEx version: 1.23.4
20:22:02 [INFO] Factions > Vault version: 1.5.6-b49
20:22:02 [INFO] Factions > EssentialsXXMPP version: 2.15.0.1
20:22:02 [INFO] Factions > EssentialsXProtect version: 2.15.0.1
20:22:02 [INFO] Factions > EssentialsXChat version: 2.15.0.1
20:22:02 [INFO] Factions > EssentialsXGeoIP version: 2.15.0.1
20:22:02 [INFO] Factions > EssentialsXAntiBuild version: 2.15.0.1
20:22:02 [INFO] Factions > EssentialsXSpawn version: 2.15.0.1

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 
https://gist.github.com/DangerAngel97/d9ad7303c06a1ca22c1bf26c03545e47

### Details

Potion Tipped Arrows don't work in kits. They come back with 'No Effects' instead of there proper effect.

**Comment by AgentTroll** [comment]
You mentioned "proper" effect, so are you pointing out the lack of effect or are you pointing out that it is the wrong effect? I don't see any configuration for potions at all.

**Comment by caojohnny** [comment]
See #468 and #486

**Comment by pop4959** [comment]
Replication of this issue no longer works, as it produces the same message "item is not a potion", as described in #2867. Will close this in favor of that issue.
