### ISSUE TITLE
Kits are still dropping items even drop-items-if-full is false

### ISSUE THREAD

**Issue by ygtdmn** [EssentialsX/Essentials#1963]
### Information

Full output of `/ess version`:
2.0.1-b530

### Details
I set drop-items-if-full: false in config but when players has full inventory and write /kit <blabla> they drop items to the ground. Instead of that please disallow getting kits if inventory is full.

**Comment by mdcfe** [comment]
Could you update to the latest build of EssentialsX and report back whether the issue still occurs? Kits were heavily refactored recently, which may have changed the behaviour in newer versions.

**Comment by ygtdmn** [comment]
I can confirm it is still happening in latest build (2.15.0.1):
http://prntscr.com/j3iptz

**Comment by mdcfe** [comment]
Could you paste your full config and kits file on [Gist](https://gist.github.com) so we can replicate the issue?

**Comment by ygtdmn** [comment]
I replicate the issue with the default config. Here it is: https://gist.github.com/UnioDex/d041ac4879b2c74b5ea371b9106b55d1

**Comment by darbyjack** [comment]
I cannot reproduce this on the latest version. Feel free to re-open if you can still reproduce it.
