### ISSUE TITLE
Vanish Bypass with Commands

### ISSUE THREAD

**Issue by ygtdmn** [EssentialsX/Essentials#1968]
Players can see vanished users with commands like /balance <playerTag>. 

For example; lets say my tag (permission tag) is Owner and if players use the command "/bal owner" they can see my balance. If i'm offline and when they use "/bal owner" result will be nothing. But if they use the command while i'm online and vanished they can see result.

**Comment by pop4959** [comment]
Upon testing, all appears to be working on the current versions of Essentials. This is probably no longer an issue.
