### ISSUE TITLE
cannot compile EssentialsX

### ISSUE THREAD

**Issue by NurPech** [EssentialsX/Essentials#1970]
Hi

I cannot compile Essentials on my own server.
I just doing "git clone https://github.com/EssentialsX/Essentials.git", then "cd Essentials". After that I typed in "mvn clean install".
That gave me the following error:
[ERROR] The build could not read 6 projects -> [Help 1]
[ERROR]
[ERROR]   The project net.ess3:NMSProvider:[unknown-version] (/root/test/Essentials/nms/NMSProvider/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for net.ess3:NMSProvider:[unknown-version]: Failure to find net.ess3:EssentialsXParent:pom:2.0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project net.ess3:UpdatedMetaProvider:[unknown-version] (/root/test/Essentials/nms/UpdatedMetaProvider/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for net.ess3:UpdatedMetaProvider:[unknown-version]: Failure to find net.ess3:EssentialsXParent:pom:2.0.1 in https://hub.spigotmc.org/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of spigot-repo has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project net.ess3:1_8_R1Provider:[unknown-version] (/root/test/Essentials/nms/1_8_R1Provider/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for net.ess3:1_8_R1Provider:[unknown-version]: Failure to find net.ess3:EssentialsXParent:pom:2.0.1 in file:${project.basedir}/lib was cached in the local repository, resolution will not be reattempted until the update interval of project.local has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project net.ess3:1_8_R2Provider:[unknown-version] (/root/test/Essentials/nms/1_8_R2Provider/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for net.ess3:1_8_R2Provider:[unknown-version]: Failure to find net.ess3:EssentialsXParent:pom:2.0.1 in file:${project.basedir}/lib was cached in the local repository, resolution will not be reattempted until the update interval of project.local has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project net.ess3:LegacyProvider:[unknown-version] (/root/test/Essentials/nms/LegacyProvider/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for net.ess3:LegacyProvider:[unknown-version]: Failure to find net.ess3:EssentialsXParent:pom:2.0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project net.ess3:ReflectionProvider:[unknown-version] (/root/test/Essentials/nms/ReflectionProvider/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for net.ess3:ReflectionProvider:[unknown-version]: Failure to find net.ess3:EssentialsXParent:pom:2.0.1 in https://hub.spigotmc.org/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of spigot-repo has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 5, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

It seems that the nms packages are using the wrong version von EssentialsXParent.

**Comment by caojohnny** [comment]
Can confirm here. A quick/dirty fix would be to downgrade the version in the parent and sibling poms back to 2.0.1 and re-run, or upgrade the NMS projects that haven't been bumped yet.

**Comment by mdcfe** [comment]
Apparently I didn't think to check the NMS modules before pushing the versioning PR, and the build didn't fail on ci.ender.zone so I assumed there wasn't an issue. I've updated the NMS modules to use version 2.15.0 in PR #1971.
