### ISSUE TITLE
Essentials v2.15.0.1 generated an exception

### ISSUE THREAD

**Issue by CitrusFruit** [EssentialsX/Essentials#1974]
### Information

Full output of `/ess version`:
Server version: 1.12.2-R0.1-SNAPSHOT git-Spigot-a630691-bea5a84 (MC: 1.12.2)
EssentialsX version: 2.15.0.1
LuckPerms version: 4.1.25
Vault version: 1.5.6-b49
EssentialsXChat version: 2.15.0.1
EssentialsXSpawn version: 2.15.0.1

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):
https://gist.github.com/CitrusFruit/1867cab7cebde1b2a3cac6c723a06f42

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 
https://gist.github.com/CitrusFruit/1abec03351c13d86db5ed1bf76186332

### Details

Getting this error when loading up server - https://gist.github.com/CitrusFruit/9405b054e195a9d80bcfa12926ab8f8e

Also getting server lockups due to essentials - 
https://gist.github.com/CitrusFruit/7fa23bc77e0835c94b1811a333548663

**Comment by mirolm** [comment]
Latest spigot build (commit [17ee35ec62e](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/17ee35ec62eb9128f8c45599f4e4939f9821e443)) updated to SnakeYAML 1.21 and this causes the error.

**Comment by LaxWasHere** [comment]
Latest bukkit build (commit [33a62b95913](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/33a62b95913e6df50dc60f0fdad3144ba094bef7)) has fixed this issue. Please re-run buildtools.

**Comment by mdcfe** [comment]
~~Closing due to lack of response. If this is still a problem, feel free to respond and reopen the issue.~~
