### ISSUE TITLE
gson breaks < MC 1.8.3 compatibility 

### ISSUE THREAD

**Issue by LaxWasHere** [EssentialsX/Essentials#1980]
0d5da063fbc6ed67f15b2c6ef65bb290e33e4d69 breaks our compatibility with versions 1.8.2 and below as gson was [added](https://hub.spigotmc.org/jira/browse/SPIGOT-207) on versions 1.8.3 and up.

@lucko 

Log: https://hasteb.in/ufomahot.md

**Comment by mdcfe** [comment]
Why are we supporting anything below 1.8.8? I don't see the changes that necessitate using 1.8.3, let alone 1.8.0-1.8.2.

**Comment by LaxWasHere** [comment]
¯\\_(ツ)_/¯

**Comment by lucko** [comment]
Not sure why I was tagged - the existing implementation used gson too.

There's not really a good workaround aside from [shading the entire library](https://github.com/lucko/LuckPermsLegacy/). 😢 

I agree with md, I wouldn't waste your energy maintaining support for anything pre-1.8.8.

**Comment by LaxWasHere** [comment]
The solution is to drop support for < MC 1.8.8
