### ISSUE TITLE
EssentialsX not reliably cancelling join broadcasts

### ISSUE THREAD

**Issue by GriffinCodes** [EssentialsX/Essentials#1983]
### Information

**Versions**
![image](https://user-images.githubusercontent.com/12417961/39325986-afeabf70-4961-11e8-8db8-14fa086b3e45.png)

**Server log**
This is not applicable, there is no output related this issue from Essentials on startup, nor when this message occurs.

**EssentialsX config**
``` 
allow-silent-join-quit: true
custom-join-message: 'none'
custom-quit-message: 'none'
```

**PermissionsEx config**
```groups:
  Guest:
    options:
      default: true
    permissions:
    - essentials.silentjoin
    - essentials.silentquit
```

### Details

A while ago I disabled Essentials' handling for join/leave messages in favor of a different plugin. To accomplish this, I made the configuration changes stated above in EssentialsX and in PermissionsEx (soon to be LuckPerms)

For the most part it works, but on *occasion* Essentials will still broadcast a join message. 
![image](https://user-images.githubusercontent.com/12417961/39326187-3265ced6-4962-11e8-982f-b7b7068f203b.png)

I know it's essentials for multiple reasons:
1) All users always have `essentials.silentjoin`, they should absolutely *never* have a join message broadcasted
2) The join message that is broadcasted reflects essentials configuration. For example, when I changed the config messages to an empty string ( `''` ), blank lines were printed in chat, instead of the default yellow join message

3) This only started showing up when I made this change. I used to use Essentials as my join message handler for over 2 1/2 years, and I never got blank lines, or the default yellow join message. Only since I tried to turn off Essentials' join message broadcasts has this happened.

Again, this happens very occasionally. I've gone multiple weeks without seeing it myself or having it reported to me by players, but it still happens. As far as I can tell there's no pattern to it. I've seen it happen with staff members and I've seen it happen with normal players. I cannot reliably reproduce this issue (which sucks, I know, I'm sorry)

Anything that can be done to try to increase the reliability of Essentials' cancellation of the join messages would be greatly appreciated.

**Comment by mdcfe** [comment]
Please paste the full output of `/ess version` as requested.

Could you also run `/ess debug`, then paste the full console output when a player logs in **and** EssentialsX shows its join message? This could potentially be a permissions lookup issue.

**Comment by GriffinCodes** [comment]
![image](https://user-images.githubusercontent.com/12417961/39399359-47ed948a-4aea-11e8-9d20-a14c40827f64.png)

![image](https://user-images.githubusercontent.com/12417961/39398506-d3d319ec-4adc-11e8-9fa6-2dfb70f7baef.png)


Using my debug command, 
![image](https://user-images.githubusercontent.com/12417961/39398493-a33a2c26-4adc-11e8-8ebc-77796f963cf4.png)

**Comment by mdcfe** [comment]
Are you using offline mode? This might affect how PEX looks up permissions.

Could you enable PEX's debug mode for a user (`pex user <user> toggle debug`) alongside EssentialsX's debug mode (`ess debug`), then paste the console output when that user **logs out then back in**?

**Comment by GriffinCodes** [comment]
I am not using offline mode.

Unfortunately, as I said before, the bug only happens randomly. I am not able to reproduce it at the moment, I will get back to you when it happens.

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, let us know and we'll reopen the issue.
