### ISSUE TITLE
{UNIQUE} variable increases by 2 with each new players

### ISSUE THREAD

**Issue by Dakotaa** [EssentialsX/Essentials#1985]
### Information

Full output of `/ess version`:
27.04 19:26:06 [Server] INFO Server version: 1.12-R0.1-SNAPSHOT git-TacoSpigot-"99d21c3f" (MC: 1.12)
27.04 19:26:06 [Server] INFO EssentialsX version: 2.15.0.1
27.04 19:26:06 [Server] INFO Vault version: 1.5.6-b49
27.04 19:26:06 [Server] INFO EssentialsXChat version: 2.15.0.1
27.04 19:26:06 [Server] INFO EssentialsXProtect version: 2.15.0.1
27.04 19:26:06 [Server] INFO EssentialsXSpawn version: 2.15.0.1

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)): https://gist.github.com/Dakotaa/2e224b6f5d48c6164a071e2c70e6f78b

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): https://gist.github.com/Dakotaa/30739ffe8deeacd71f25f5dc3d8aca9c

### Details

Describe your issue here.

When a new player joins, the unique player count increases by two. I have been experiencing this since the last map of my server (which started last May), and the issue continues even on a whole new server.

This happened while stress testing my server with bots, but it also happens with actual players.
[Image](https://i.imgur.com/vAs6biy.png).

The {UNIQUE} variable seems to be increasing by two each time, but there is only one userdata file for each actual player (with 1396 actual unique players, there is currently 1396 userdata .yml files, but when a new player joins it will say 2792 unique players).

Server is running through a BungeeCord proxy, with the server in offline mode and the proxy in online mode.

**Comment by mdcfe** [comment]
How many entries are in your usermap? (From a bash shell, use `wc -l plugins/Essentials/usermap.csv`, else check the line count with your text editor.)

**Comment by Dakotaa** [comment]
It now seems like it doubled the amount of userdata files after server restart. There are 2535 userdata.yml files now, with only 1174 lines in the usermap.csv.

Could this be related to the server being in offline mode, but the proxy in online mode? Maybe there's a userdata file being created for both their online and offline UUID.

**Comment by mdcfe** [comment]
Ensure the bungeecord option in your Spigot config set to true if you're using BungeeCord. 

Is there any chance you could upgrade to the latest version of TacoSpigot?

In addition, could you check your logs to see if there are any logs relating to UUID migration? It might be that online UUIDs are being migrated to offline UUIDs or vice versa on server startup.

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to respond and reopen the issue.
