### ISSUE TITLE
Force spawn on join if in specified worlds.

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#1987]
With EssentialsSpawn, would it be possible to force players to spawn on join if they are logging on in specified worlds? For example, if someone is in an arena world, force them back to spawn on rejoin. If someone is in a normal survival world, don't force them back to spawn - they login back where they last logged off.

**Comment by LaxWasHere** [comment]
Simply use the group option for spawn-on-join and remove them from the group on the excluded worlds.

**Comment by mibby** [comment]
What if I don't want them to inherit that group's permissions? 

What I would like to do is have it so spawn-on-join forces my Guest group to spawn every time they login with ```spawn-on-join: Guest``` and if _anyone_ logs into the world ```void``` (which I use for arenas), force them back to spawn so they don't relog in a world they aren't suppose to be in unnaturally. Having a world exclusion list to force spawn regardless of grouping seems much more fluid.

**Comment by mdcfe** [comment]
You can use LuckPerms and create groups that don't have any permissions.

I agree that this is a useful request though - I don't think even LuckPerms lets you control parent groups by world.

**Comment by JRoy** [comment]
LuckPerms allows for this nowadays, closing.
