### ISSUE TITLE
Craft Scheduler Thread - when reload > Cauldron

### ISSUE THREAD

**Issue by Lorrainrm** [EssentialsX/Essentials#1994]
Ello!
Got recently the Essentials X after years using Essentials. Sometimes the server crashed cause of the Essentials and i got sick of it and tried to updated to X.

First i had this issue with the /setspawn and /spawn crashing, tried to solve using the guides provided by some users.

I believe its fixed for me now, ill confirm or start crying after the next server restart

Versions are those:
05.05 19:30:46 [Server] INFO Server version: 1.7.10-R0.1-SNAPSHOT 1.7.10-1448.133 (MC: 1.7.10)
05.05 19:30:46 [Server] INFO EssentialsX version: 2.15.0.2
05.05 19:30:46 [Server] INFO Vault version: 1.4.1-b436
05.05 19:30:46 [Server] INFO EssentialsXProtect version: 2.15.0.2
05.05 19:30:46 [Server] INFO EssentialsXAntiBuild version: 2.15.0.2
05.05 19:30:46 [Server] INFO EssentialsXSpawn version: 2.15.0.2

As you may notice, its 1.7.10 and im using cauldron.
So im kinda limited to update bukkit/spigot whenever it fixes something. I know cauldron is dead/frozen, etc.

When i /ess reload i got those errors: 
https://pastebin.com/S16Qiv8z

**Comment by Lorrainrm** [comment]
Algo getting those in my console:
https://pastebin.com/r4XjRCuE

Ye, crashed the server.
I'm kinda screwed now. Since i updated and didnt backup my old essentials files. So all my 20k+ players would loose all their money, homes and nicknames/suffix/prefixes if i got the old version back.

So i'm stuck with this version and no idea what todo. Unless theres a undo with the all user data... any idea?

**Comment by Lorrainrm** [comment]
Yeah, and also whenever i restart the server the /spawn and /setspawn and jail and /ess reload crashes the server :P

**Comment by Xeyame** [comment]
1.7.10 is not supported, upgrade to some minecraft version thats not 4 years old,

**Comment by Lorrainrm** [comment]
Yeah, as i said.. cauldron.. limited..
¯\_(ツ)_/¯


But, well, if you are a dev, are you interested in a simple plugins/thing to unconvert the userdata ? Basically to convert to what it was..

**Comment by Xeyame** [comment]
i guess you could do an vault import and export

**Comment by Lorrainrm** [comment]
Sorry to bother, but is it a technical feature or is there a command or similar for an end user ?

**Comment by Xeyame** [comment]
You should be able to do something like `/vault-convert Essentials EssentailsX` with both Essentials-non-x installed and with EssentialsX

**Comment by Lorrainrm** [comment]
I believe wont be that easy:
 Ambiguous plugin name `Essentials' for files
`plugins\EssentialsX-2.0.1.jar' and `plugins\Essentials.jar' in `plugins'

:(

2018-05-06 6:30 GMT-03:00 Xeyame <notifications@github.com>:

**Comment by mdcfe** [comment]
Don't do that - Vault has nothing to do with EssentialsX userdata and can't even differentiate between Essentials and EssentialsX.

@Lorrainrm As far as I know, EssentialsX doesn't backup userdata files. I believe any version before 7fbc721db6a405c3fd4185190d9d86c0e3dfe1c4 should work with your converted userdata, though you'll need to copy your kits back into the config.yml and you'll miss out on updates.

Make sure you only have one jar for each EssentialsX module installed at a time.

**Comment by Lorrainrm** [comment]
Will try. Thank you.


Em Seg, 7 de mai de 2018 03:33, md678685 <notifications@github.com>
escreveu:

**Comment by Lorrainrm** [comment]
Ok, I'm not so sure how do I would take this version you mentioned, @md678685  =/

Just keep in mind I cant compile plugins.
