### ISSUE TITLE
[Feature Request] Social Spy

### ISSUE THREAD

**Issue by AntZaro** [EssentialsX/Essentials#1995]
I know more customization was recently made available for the social spy, and I really appreciate it. But I'm looking for one additional setting.

Is it possible to add a setting for social spy to use usernames vs display names? Because I find the current format of display name to be awful in social spy. It's way too busy and too much information. I don't need to see people's rank and nickname within social spy, but rather just their username. 

I'd love to just make it look like "[SS] Player:" or something simple like that, but I'm unable to edit the use of display name right now. I hope you'll consider this. Thank you!

**Comment by mdcfe** [comment]
This isn't currently possible, but should be doable once PlaceholderAPI is supported (#1945).

**Comment by AntZaro** [comment]
Ah awesome, I look forward to it! Thanks
