### ISSUE TITLE
Add per-world setting to - prevent section 

### ISSUE THREAD

**Issue by khlfkk** [EssentialsX/Essentials#1997]
Hope there can let's us set the water-flow and lava-flow and so on that we can have different in world A world B .... sometime if we only want the world A to prevent water-flow. 
Or add a world list which we can put the world name in the list which we want to prevent lava-flow and so on...
Thanks

**Comment by mdcfe** [comment]
This isn't currently supported by EssentialsX Protect, but you can use a plugin such as WorldGuard to control environment behaviour per-world and per-region.

**Comment by pop4959** [comment]
Yeah Essentials isn't equipped to handle these settings per world. Might be useful to use a multi-world plugin to handle this, or BungeeCord with several servers. WorldGuard is also a good option (or other plugins that handle region rules specially).
