### ISSUE TITLE
[Bug] Report

### ISSUE THREAD

**Issue by DevJoey** [EssentialsX/Essentials#1998]
wen i restart or reload my server and join /afk and /me dont work please fix
wen i reload the sever whre iam on it the the plugin command /afk and /me works

**Comment by Xeyame** [comment]
Seems to be related to #1898

**Comment by DevJoey** [comment]
Jap is the same Problem i waiting for a fix

**Comment by drtshock** [comment]
Closing in favor of the more... well articulated ticket.
