### ISSUE TITLE
[Feature Request] /top but /down?

### ISSUE THREAD

**Issue by kristouffe** [EssentialsX/Essentials#1999]
What about a /down command? I saw this command on a server and i was pretty sure it was provided by essentialsx. Sadly it was a custom command.

/down would work like the /top command but in the opposite way. Instead of going straight top, down would allow the player to top on the first valid bloc (solid bloc with at least 3 blocs of air above) under him.

btw it would be nice to get a /top enhancement since top tps the player on the highest bloc above him. An idea would be to tp the player on the first valid bloc above him, like the /down command would tp on the first valid bloc under him.

Thanks :D

**Comment by mdcfe** [comment]
WorldEdit already includes `//asc` and `//desc` commands that do what you described, so I'm not sure if this is a necessary addition to EssentialsX. That said, I'll leave this open in case someone wants to PR it.

**Comment by kristouffe** [comment]
oh, i didnt know it was included with worldEdit, thanks. That said, EssentialsX provides the top command, although the bot/desc is not included ^^'
