### ISSUE TITLE
Suggestion: URL whitelist

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#200]
I want to keep the full URL blocking that removes the .'s in URLS posted, this is fantastic, but we have absolutely 0 control over what gets blocked, I would like to allow posting internal/server URLS only, this could be in a comer separated variable in the main config where I can put domains and sub-domains.
piratemc.com,wiki.piratemc.com,stats.piratemc.com,map.piratemc.com or use a wildcard *.piratemc.com would be nice, that would include having http:// and www. too!

Its infuriating when players try to link forum posts, or wiki pages and they cant, but its great stopping bots and people that come on to spam urls or send virus or whatever.

Suggestion, Add a URL whitelist for Essentials Chat.

**Comment by TomLewis** [comment]
Bump.

**Comment by kmecpp** [comment]
Need this as well

**Comment by TomLewis** [comment]
@kmecpp I moved to ChatControl Pro many years ago, its worth switching for full regex support.
