### ISSUE TITLE
Issue with gamemode 3

### ISSUE THREAD

**Issue by danielgarciagarcia** [EssentialsX/Essentials#2003]
### Information

Full output of `/ess version`:
Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1415 (MC: 1.12.2)
EssentialsX version: 2.15.0.2
PermissionsEx version: 1.23.4
Vault version: 1.5.6-b49
EssentialsXGeoIP version: 2.15.0.2
EssentialsXAntiBuild version: 2.15.0.2
EssentialsXSpawn version: 2.15.0.2

Here is the server log of a part of the day where we tested the issue as described beneath: https://gist.github.com/MetalGearDaner/7e538ed811c59cbc41b8f20b17dc970d.
 
EssentialsX config:  https://gist.github.com/MetalGearDaner/e416ec7d9f7bfa909940159196b987fb

"Moderador" rank permissions: https://gist.github.com/MetalGearDaner/e1934d90e41bf263ee75984b7d5ac4e8

### Details

This issue consist in the following: Any player with the _"Moderador"_ rank falls into the void and dies whenever they use the command: _/gm 3_, or _/gamemode 3_. They become the invisible entity expected for the spectator mode, but **immediately** fall.

The user "Utrerano" has tested this issue by using the command, while the Essentials **debug mode is enabled**. I have uploaded the log file, you can find it above. 

I'm not completely sure if it's an Essentials issue, or Spigot, or PermissionsEX... But as I have no clue about this, and it's related to an Essentials command, I hope you can help me to find a solution.

Thanks for your time :)

**Comment by mdcfe** [comment]
Could you run `/minecraft:gamemode spectator` and report back what happens?

**Comment by danielgarciagarcia** [comment]
Sure!

The command /minecraft:gamemode spectator has the same behaviour: The user falls into the void. It seems, there's no difference between the minecraft native command and the EssentialsX one, over this issue.

Furthermore, I have noticed that this bug seems to appear and disappear per player with no reason, the day I opened this ticket, Utrerano (_one of the users with "Moderador" rank that suffers this_) suffered this problem, and, for example, this morning he didn't experience it on the main world (worldcraft), but on the SkyBlock one. So I asked another player with "Moderador" rank, SancaVIP, to test it. He experienced it on the main world and on the Skyblock one as well. So I suspect it **may** be a permission-related / world-related conflict. I've uploaded the personal permissions of this players:

Utrerano's permissions: https://gist.github.com/MetalGearDaner/0778d4d4f70c05b5d6d5adf341deda2a
SancaVIP's permissions: https://gist.github.com/MetalGearDaner/d367c30258d6cb31eb507d85e51eee7d

This is the list of user-accessible worlds:
- worldcraft
- worldcraft_nether
- worldcraft_the_end
- recursos
- ASkyBlock
- ASkyBlock_nether

Thanks for the help! :)

**Comment by Xeyame** [comment]
This probably isn't an essX issue then, as I'm pretty sure all essentials does is check for permissions for the command, and then uses the native bukkit api to set gamemode (just like the `/minecraft:gamemode` command does).

Edit: all I can think of when it comes to essX, is that you are missing permission to fly in some world(s). But normally it doesn't check that on gamemode change.

**Comment by mdcfe** [comment]
Can you replicate this issue with just EssentialsX and that particular Paper build? If not, this is probably not an EssentialsX bug.

**Comment by drtshock** [comment]
Also replicate without essentialsx. Doesn't appear to be an essx issue, please re open if you have new info suggesting it is.
