### ISSUE TITLE
command-cooldown issue

### ISSUE THREAD

**Issue by kristouffe** [EssentialsX/Essentials#2004]
i last a fewhours now on trying to resolve my issue, but in any way, it doesnt' work.

**Information:**

[16:58:58] [Server thread/INFO]: Server version: 1.12.2-R0.1-SNAPSHOT git-Spigot-2086bb0-ca057a3 (MC: 1.12.2)
[16:58:58] [Server thread/INFO]: EssentialsX version: 2.15.0.2
[16:58:58] [Server thread/INFO]: PermissionsEx version: 1.23.4
[16:58:58] [Server thread/INFO]: Vault version: 1.5.6-b49
[16:58:58] [Server thread/INFO]: EssentialsXChat version: 2.15.0.2
[16:58:58] [Server thread/INFO]: EssentialsXSpawn version: 2.15.0.2

**Some explanation:**
i have a plugin "wilderness-tp" wich can random tp players. the command i want use is /rtp <world>. As you see it's a command with an argument. I noticed that essentialsX command cooldown feature doesn't handle/support complex commands with arguments.
That said, when i try to cooldown, let's say, the essentials /feed command, everything works fine. The cooldown is activated correctly.

Imagine i want to cooldown the "/rtp survival" command, this won't work even with regex ('^rtp.*survival$') nor quotes, nor any other way to write the command in the command-cooldown section. This just let's me think, essentials doesn't support commands with argument.

If anyone has suggestions or just confirm that essentials command-cooldown doesn't support commands with arguments, let me know.

PS: i tryed it with lot's of other multiple argument commands. Result is the same, doesn't work :(

**Comment by drtshock** [comment]
Can you show us your relevant config.yml section please.

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to respond and reopen the issue.
