### ISSUE TITLE
/back not work

### ISSUE THREAD

**Issue by muzyeh** [EssentialsX/Essentials#2005]
---------------------------------------------------
/back  Player does not work

not error
server ver  PaperSpigot-1.12.2-b1386
GroupManager  

    - essentials.back
    - essentials.back.ondeath
----------------------------------------------------

**Comment by mdcfe** [comment]
We don't support GroupManager. Please switch to [LuckPerms](https://luckperms.github.io/) - install the latest version of LP, [migrate your perms](https://github.com/lucko/LuckPerms/wiki/Migration) and then delete the GroupManager jar.

Once you're running LuckPerms, please post the **full output** of `ess version` exactly as it appears in the console, as requested in the template you didn't follow.
