### ISSUE TITLE
/info doesn't work yet /einfo does

### ISSUE THREAD

**Issue by Fordy436** [EssentialsX/Essentials#2006]
### Information

Full output of `/ess version`:
[14:37:14 INFO]: Server version: 1.12.2-R0.1-SNAPSHOT git-Spigot-7754231-94b0980 (MC: 1.12.2)
[14:37:14 INFO]: EssentialsX version: 2.15.0.1
[14:37:14 INFO]: LuckPerms version: 4.2.2
[14:37:14 INFO]: Vault version: 1.6.1
[14:37:14 INFO]: EssentialsXChat version: 2.15.0.1
[14:37:14 INFO]: EssentialsXProtect version: 2.15.0.1
[14:37:14 INFO]: EssentialsXGeoIP version: 2.15.0.1
[14:37:14 INFO]: EssentialsXSpawn version: 2.15.0.1

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):
https://gist.github.com/Fordy436/b0fdb2b1bea7b5b2e5861b7eba60a43d

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 
https://gist.github.com/Fordy436/41267e3dd413ef67007ec0aadecf73a4

### Details

Describe your issue here.
So I've recently removed WorldEdit to try and get /info to work so I don't have to keep explaining to Players that they have to use /einfo. Yet when I remove WorldEdit, /info doesn't work.

I repeated the same commands /einfo colors and /info colors; the /einfo command executed correctly and displayed the colors chapter, but the /info command sent back the "SelectChapter" message like I was spelling it wrong.

**Comment by mdcfe** [comment]
Have you tried aliasing `info` to `einfo` in your `commands.yml`?

**Comment by Fordy436** [comment]
Turns out that was the issue. In an attempt to make Essentials /info override WorldEdits /info, I tried aliasing info to einfo, but obviously commands.yml doesn't support arguments and I forgot I did this a long time ago.

Thanks @md678685 , would've driven me crazy otherwise
