### ISSUE TITLE
[Feature Request] Info Interactive Text

### ISSUE THREAD

**Issue by Fordy436** [EssentialsX/Essentials#2007]
It'd be a unique and potentially really useful tool if it was possible to make text in `info` interactive. 
Example Chapter:

#RankSystem
Rank1 --> Rank2 --> Rank3...

So you could click on Rank1 for example and it'd take them to another info page about that rank.

**Comment by mdcfe** [comment]
Related: #2391

**Comment by pop4959** [comment]
Currently isn't supported; see the linked issue from md to discuss these changes. Interactive or hover text will only be supported once it is added plugin-wide. Not easy to PR this as is.
