### ISSUE TITLE
[Feature Request] Change sign names

### ISSUE THREAD

**Issue by ConnorFranta** [EssentialsX/Essentials#2009]
Requesting the ability to change [Buy] and [Sell] sign names somewhere in Essentials to a custom name.
We currently use [sell] with another plugin for selling regions. Would like to use Essentials [Sell] but can't because of the conflict. 

http://wiki.mc-ess.net/wiki/Sign_Tutorial

**Comment by mdcfe** [comment]
I don't see that renaming signs will be supported, as it will create inconsistencies when signs are changed in the config but not in the world, and would also potentially bypass sign creation permissions checks by validating previously-created signs.

I would suggest changing the sign used by the other plugin if possible, as players will likely expect `[Sell]` signs to behave the same across different EssentialsX servers.
