### ISSUE TITLE
teleport-safety don't work correctly when  teleport from another world

### ISSUE THREAD

**Issue by netherstar** [EssentialsX/Essentials#2010]
```
# If the teleport destination is unsafe, should players be teleported to the nearest safe location?
# If this is set to true, Essentials will attempt to teleport players close to the intended destination.
# If this is set to false, attempted teleports to unsafe locations will be cancelled with a warning.
teleport-safety: true

# This forcefully disables teleport safety checks without a warning if attempting to teleport to unsafe locations.
# teleport-safety and this option need to be set to true to force teleportation to dangerous locations.
force-disable-teleport-safety: true
```
As this setting above, when both `teleport-safety: true` and `teleport-safety: true` player should allowed teleport to unsafe location. If player teleport to same world, this setting work correctly, but if player teleport to another world, example from `nether` to `world` it teleport player to SAFE location

Tested on Ess version 2.15.0.2 Build 616 download from _https://ci.ender.zone/job/EssentialsX/616/_

**Comment by mdcfe** [comment]
Please run `/ess version` as instructed and post the output.

**Comment by netherstar** [comment]
here are /ess version
`
[18:38:33 INFO]: CONSOLE issued server command: /ess version
[18:38:33 INFO]: Server version: 1.11.2-R0.1-SNAPSHOT git-Paper-1104 (MC: 1.11.2)
[18:38:33 INFO]: EssentialsX version: 2.15.0.2
[18:38:33 INFO]: Vault version: 1.5.6-b49
[18:38:33 INFO]: EssentialsXSpawn version: 2.15.0.2
`

**Comment by iMaarten** [comment]
This bug still happens on latest builds, here is a video demonstrating:
https://drive.google.com/file/d/1lLeAqB3f0S-5oYLZdEagTCqnIQIFFZqr/view

**Comment by pop4959** [comment]
@iMaarten that appears to be a safe location. Can you explain what you were expecting to have happen?

**Comment by iMaarten** [comment]
> @iMaarten that appears to be a safe location. Can you explain what you were expecting to have happen?
They shouldn't be put in a safe place... this bug only happens if the teleport is cross-world, if the user were to teleport from the same world it would teleport them to the dangerous location as intended. 

```
# This forcefully disables teleport safety checks without a warning if attempting to teleport to unsafe locations.
# teleport-safety and this option need to be set to true to force teleportation to dangerous locations.
force-disable-teleport-safety: true
```

**Comment by pop4959** [comment]
@iMaarten Ah never mind, I think I see what you intended. Did you want it to teleport you into the cobblestone? It looks like around 0:16 your friend fills that in.

Are you able to teleport to the home location using `/minecraft:tp <x> <y> <z>`?

**Comment by iMaarten** [comment]
> @iMaarten Ah never mind, I think I see what you intended. Did you want it to teleport you into the cobblestone? It looks like around 0:16 your friend fills that in.
> 
> Are you able to teleport to the home location using `/minecraft:tp <x> <y> <z>`?

Yes it should teleport inside the cobblestone otherwise you can teleport inside bases and such
Yes, I am able to use that command to teleport inside the block. Keep in mind this issue only occurs when cross-world teleporting, if you're in the same world the setting functions correctly.

**Comment by iMaarten** [comment]
Any updates on this?

**Comment by pop4959** [comment]
Thank you for the additional information. The bug will still need to be confirmed by an Essentials team member or contributor, which will happen when we have time. I may be able to do this for you soon. Keep in mind that the bug may then still not be fixed until a contributor investigates the issue and finds a potential solution for it. It may take some time, so please remain patient, and if we need further comment we'll mention you in this thread.

**Comment by JRoy** [comment]
The teleport system has been refactored since the opening of this issue, closing unless reconfirmed.

**Comment by netherstar** [comment]
I tried latest version but the issue still exist
Players used this bug to make glitches on Factions server

```
[23:08:13 INFO]: Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
[23:08:13 INFO]: EssentialsX version: 2.19.0-dev+51-e287600
[23:08:13 INFO]: PlaceholderAPI version: 2.10.2
[23:08:13 INFO]: LuckPerms version: 5.2.76
[23:08:13 INFO]: Vault version: 1.5.6-b49
[23:08:13 INFO]: Citizens version: 2.0.22-SNAPSHOT (build 1547)
[23:08:13 INFO]: EssentialsXSpawn version: 2.19.0-dev+51-e287600

```

**Comment by JRoy** [comment]
Thanks for confirming

**Comment by JRoy** [comment]
https://user-images.githubusercontent.com/10731363/110329133-37ca1f00-7fea-11eb-88f8-6c7e2983eb3c.mp4


Cannot reproduce with `teleport-safety: true` and `force-disable-teleport-safety: true`
