### ISSUE TITLE
ess 2.15.0.3 errors

### ISSUE THREAD

**Issue by jerzean** [EssentialsX/Essentials#2015]
### Information

Full output of `/ess version`:

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 

### Details

Describe your issue here.
getting a error on join
https://gist.github.com/jerzean/affaf47ca02a36f8adeb161fc339fa05  
EssentialsX version: 2.15.0.3
Vault version: 1.6.1
EssentialsXProtect version: 2.15.0.3
EssentialsXChat version: 2.15.0.3
EssentialsXAntiBuild version: 2.15.0.3
EssentialsXSpawn version: 2.15.0.3

**Comment by jerzean** [comment]
default config   i tried to turning use bukkit perms True    no change

**Comment by mdcfe** [comment]
You don't appear to have a permissions plugin enabled?

Please post a full server startup log so we can see the problem is.

**Comment by jerzean** [comment]
https://gist.github.com/jerzean/43da0901ddb94544866f5a7f058fdb60

**Comment by jerzean** [comment]
@md678685

**Comment by mdcfe** [comment]
GroupManager isn't supported. Please switch to LuckPerms.

In addition, could you post the output of `/plugins`?

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to respond and reopen the issue.
