### ISSUE TITLE
Clearinventory Confirm Improvement Request

### ISSUE THREAD

**Issue by CourtneySechrist** [EssentialsX/Essentials#2021]
Currently, with /clearinventoryconfirmtoggle on, the user will normally do /ci once, have the confirmation message, then type the command again to clear an inventory. Something our server has noticed is that if the user logs out before doing the confirmation, the 'confirm-clear' of the userdata will still be true when the user logs back on, so the next time they do /ci, it will clear without confirmation. Is this something that could be improved upon?

**Comment by mdcfe** [comment]
The `confirm-clear` probably shouldn't be persisted across relogs to avoid this.

**Comment by VirtualParticle** [comment]
I created a PR [here](https://github.com/EssentialsX/Essentials/pull/2023). I made the confirmation condition set to false on login.
