### ISSUE TITLE
Players' money is reset when they go over $3,000,000

### ISSUE THREAD

**Issue by Shawn11564** [EssentialsX/Essentials#2022]
### Information

Full output of `/ess version`:
Server version: 1.8.8-R0.2-SNAPSHOT git-CannonSpigot-b181nwil (MC: 1.8.8)
EssentialsX version: 2.15.0.1
Vault version: 1.5.5-b47
EssentialsXChat version: 2.15.0.1
EssentialsXSpawn version: 2.15.0.1

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):
https://gist.github.com/Shawn11564/b9ddbcf71f807df7c7834dd7783024cd

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 
https://gist.github.com/Shawn11564/3a33c98558ef0bcbb7177b18ffe96791

### Details

Describe your issue here.
I am using Vault and EssentialsX to handle my economy. When players get above about $3million their money gets reset for some reason. This used to not be an issue but now it is. I am using spigot 1.8.8
The issue occurs when the player goes over $3,000,000.
I tested this by setting my balance to $2,999,000 and then selling something to go over the $3mil mark. When I did this my balance was set back to 0. You can see by the screenshots provided when this happens. Oddly enough there is no error in console when this happens either. It looks like the player can go over $3mil if it is done in a single transaction, but the next transaction afterwards resets it. 
![2018-05-30_17 50 20](https://user-images.githubusercontent.com/28599869/40749780-22707436-6433-11e8-870e-273396553c7d.png)
![2018-05-30_17 50 26](https://user-images.githubusercontent.com/28599869/40749781-26748ce8-6433-11e8-82de-4a5eb4bbfe66.png)
![noerrors](https://user-images.githubusercontent.com/28599869/40749784-2eddfa68-6433-11e8-88c6-85b9e54b5c58.png)

**Comment by mdcfe** [comment]
Can you replicate this with `/ess debug` enabled?

**Comment by Shawn11564** [comment]
Replicated, here is the log: https://pastebin.com/fNu04LDr (log starts after I did /ess debug)

**Comment by Shawn11564** [comment]
bumppppppp

**Comment by pop4959** [comment]
Unable to replicate. Latest version of essentials gives me over 3M money when selling over the threshold mentioned in this issue.
