### ISSUE TITLE
[Request] Message in case of loneliness in the radius of local chat

### ISSUE THREAD

**Issue by AIphaDragon** [EssentialsX/Essentials#2024]
Hello. In Essentials, a message was output that no one hears the player, if he is alone in the range of the local chat. Could you add such a message in this EssentialsX? Thank you in advance for your response.

**Comment by mdcfe** [comment]
This hasn't been removed - you need to set `localNoOne` in your messages file.

Edit: Essentials' source code never seemed to contain this message, so I don't know which Essentials versions the message worked in, but I definitely remember this being a thing years ago and I also thought this was a default. 🤔
