### ISSUE TITLE
Commnad Cooldowns not working with Powertool 

### ISSUE THREAD

**Issue by Zenya4** [EssentialsX/Essentials#2027]
Ok so the desc basically says it all. For example, when I add a cooldown to /lightning in the "command-cooldowns:" section in the config, there is a cooldown for "/lightning", but no cooldown when the player uses "/powertool lightning" and binds it to an item. Hence clicking the item repeatedly basically just bypasses the cooldown set in config. Is it meant to be like this or is this a bug?
![screen shot 2018-06-02 at 1 21 29 pm](https://user-images.githubusercontent.com/15248687/40871130-3e25fe30-6668-11e8-9d78-9a61575a3837.jpg)

**Comment by mdcfe** [comment]
I don't see this being changed, as it's the main purpose of powertools. If you don't want people to bypass cooldowns using a powertool, don't give them access to powertools.
