### ISSUE TITLE
Essentials localization based on player client language

### ISSUE THREAD

**Issue by ChefMC** [EssentialsX/Essentials#2029]
My server will have two groups of players: Russian speaking and English speaking. I won't create new servers. Instead I want to show Essentials messages on language that select in player's client settings.

API which will help realise that:

1st. https://www.spigotmc.org/resources/api-languages.22305/
(also has ability to select certain language by command)

2nd. https://www.spigotmc.org/resources/1-7-x-1-12-language-utils.8859/

**Comment by Phoenix616** [comment]
Could also just use [Player#getLocale](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.html#getLocale--) for that to just use the client's language.

**Comment by darbyjack** [comment]
This is a great idea and we will be mapping out a solution for this soon.

**Comment by mdcfe** [comment]
I think this should come as part of #2391, so I'm pushing this back to 2.18.
