### ISSUE TITLE
spawners name not recognized

### ISSUE THREAD

**Issue by KristianHansen94** [EssentialsX/Essentials#203]
When I use floauction and whatisit plugins, to auction a  spawner on my factions server, the name of any spawner appears in chat as "monster spawner".

I am running spigot 1.8.8 and your latest essentialsX
flo-auction and whatisit are also up to date

**Comment by Terrobility** [comment]
Make sure it displays the name of the item in chat. That's to do with Floauction and its localisation

-----Original Message-----

**Comment by drtshock** [comment]
There is an option for "show item name" instead of item type in floauction.
