### ISSUE TITLE
Setworldspawn issue

### ISSUE THREAD

**Issue by CodeRunner47** [EssentialsX/Essentials#2032]
### Information

Full output of `/ess version`:
Server version: 1.12.2-R0.1-SNAPSHOT git-Spigot-7754231-94b0980 (MC: 1.12.2)
EssentialsX version: 2.15.0.1
LuckPerms version: 4.2.17
Vault version: 1.6.1
EssentialsXChat version: 2.15.0.1
EssentialsXSpawn version: 2.15.0.1

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):
https://gist.github.com/obiku19/df77646539a8a0fdc99356ff74d3560b

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 
https://gist.github.com/obiku19/15cb8a3351727fc5c5342577074ae3fc

### Details

Describe your issue here.
What ever I try, I can't change my spawnchunks location with vanilla setworldspawn command. After disconnecting the spawnchunks return to their previous location.
While this issue doesn't occure when essentialsX plugin is dissabled. Only if the core EssentialsX plugin is disabled the spawnchunks can be moved and stay at that location. As soon as EssentialsX is loaded again, spawnchunks are moved back to their pervious location.
Somehow EsstentialsX is overriding the vanilla setworldspawn command.

This is extremely annoying, cause due to this I have to make two locations on my server mob spawn free. first the server spawn area and second the spawnchunks which are in a total different location.

**Comment by LaxWasHere** [comment]
Disable `spawn-on-join` in the config.

**Comment by CodeRunner47** [comment]
That didn't help :(

BTW, its only in an askyblock world that this issue wit essentialsX happens.
Informed the creator of skyblock too (tastybento), but according to him there is nothing in the askyblock plugin that is doing something with the spawnchunks.

**Comment by mdcfe** [comment]
EssentialsXSpawn doesn't move the [spawn chunks](https://minecraft.gamepedia.com/Spawn_chunk), which are part of how Minecraft loads the world. Instead, it sets its own spawn location that controls where players are spawned, which can be set with `/setspawn`.

**Comment by CodeRunner47** [comment]
Correct, it isn't the essentialsX-spawn plugin that is buggin.

To make it all a bit more visible for me, I.... removed all Essentials plugins I used on my server (EssentialsX, EssentialsXSpawn, EssentialsXChat)
After a restart, I could use the setworld spawn to relocate the spawnchunks. Spawn chunks stayed at their new location even after I logged out and back in. The spawn chunks stayed at the position I moved them to.

Then, I placed back essentialsX (core) plugin, restarted the server, and after logging in, the spawn chunks returned to its first loaction, the location it was before I relocated them.

Odd thing is, everything is OK again as soon as I remove essentialsX core plugin.

As stated before, this issue only occurs on a askyblock server. Non of my survival servers has this issue. Perhaps a bit preliminary, but it looks like this is an issue between essentialsX and askyblock.

**Comment by mdcfe** [comment]
EssentialsX does not touch the **world spawn chunks**, and I would presume that aSkyBlock also doesn't if the author says so. EssentialsXSpawn also does not touch the world spawn chunks, only the **spawn location**.

Are you using a world loader plugin on your server (MultiWorld, Multiverse etc.)?

**Comment by CodeRunner47** [comment]
No, im am not using any worldloader.
I do use multiple plugins, for the main part that is askyblock, worldguard, coreprotect, viaversion, litebans and LuckPerms.

**Comment by mdcfe** [comment]
Could you try using aSkyBlock's admin set spawn command instead of the vanilla command?

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to respond and we'll reopen the issue.

**Comment by Gladiator0001** [comment]
I am having this exact issue and have not found a resolution. I verify worldspawn changes with a compass. Everything works as expected until essentials is installed

**Comment by dalandis** [comment]
Also can't move spawn chunks.

Here a little more detail https://www.reddit.com/r/admincraft/comments/gdl9dv/cant_move_spawn_chunks/

My version EssentialsX 2.17.2.0
