### ISSUE TITLE
EssentialsX 1.11.2 NEED

### ISSUE THREAD

**Issue by OnWolfOn** [EssentialsX/Essentials#2034]
I need a plugin EssentialsX 1.11.2, because in base version it make a crash. Please help!

**Comment by mdcfe** [comment]
EssentialsX 2.15.0 is fully compatible with 1.9 to 1.12.2, as well as mostly compatible with 1.8 and unsupported but functional on 1.7.10.

If you're encountering a crash issue on 1.11.2, please report the actual issue in a [new issue](https://github.com/EssentialsX/Essentials/issues/new) or on the [Discord server](https://github.com/MinecraftOSS/Discord/wiki/Discord-Info).
