### ISSUE TITLE
[Suggestion] Infinite Anvils

### ISSUE THREAD

**Issue by WizzleBear** [EssentialsX/Essentials#2035]
You can set an anvil as an infinite anvil so if it breaks, it's replaced. You can make it an automatic thing which you can toggle on/off when placing anvils. Just thought it would be neat for spawns who don't want to replace anvils every week. I found a plugin for reference: www.spigotmc.org/resources/infinite-anvil.42585/

Why don't I download this plugin, you ask? Well, I don't want to get a plugin specifically for that because I thought it would take up space on the /pl list and when searching for files in the FTP, so I wanted to see if you guys could implement it in so there are less plugins and what not.

**Comment by mdcfe** [comment]
This is beyond the scope of EssentialsX, and already covered by the plugin linked. Adding excess features creates bloat that many servers would rather not have, as well as increased code complexity that makes working on EssentialsX more difficult.

If you don't want to install the existing plugin for some reason, that's your choice.
