### ISSUE TITLE
SUGGESTION prompt before setting home with the same name.

### ISSUE THREAD

**Issue by Castiella** [EssentialsX/Essentials#2038]
Would be super cool if we had a prompt that asks you to confirm when you're setting a home name that you've already set. (confirmation before overwriting)

thank you

**Comment by triagonal** [comment]
This feature is now present in EssentialsX versions `2.17.2.140` and above and is controlled using the `confirm-home-overwrite` option in the config. Download the latest build [here](https://essentialsx.net/downloads.html).
