### ISSUE TITLE
[Suggestion ] Max mute time

### ISSUE THREAD

**Issue by Arkobat** [EssentialsX/Essentials#2039]
Pretty much self-explaining title.

What I'm suggesting is a max mute time for Essentials, that can be defined in the config.yml, like max tempban time

How it could look in the config. (Just a copy of the max tempban section)

[#] Set the maximum time /mute can be used for in seconds.
[#] Set to -1 to disable, and essentials.mute.unlimited can be used to override.
max-tempban-time: -1

Permission:
This feature should properly come with an override permission, like tempban also have. This could be essentials.mute.unlimited

**Comment by DardBrinza** [comment]
I would suggest for more flexibility different times for different permission groups.

moder: 1d
admin: 3d
stadmin: 7d
global: 31d

**Comment by Arkobat** [comment]
Yeah, that would be cool.
This could be accomplished the same way homes work.


[#] Set the maximum time /mute can be used for in seconds.
[#] Set to -1 to disable, and essentials.mute.time.unlimited can be used to override.
max-mute-time: -1

[#] Allow staff to have different max mute times.
[#] Players need essentials.mute.maxtime before they can mute more than max-mute-time.
[#] To remove the home limit entirely, give people 'essentials.mute.maxtime.unlimited'.
[#] To grant different mute times to different people, you need to define a 'mute-rank' below.
[#] Create the 'mute-rank' below, and give the matching permission: essentials.mute.maxtime.<time-rank>
maxmute-time:
  helper: 3600
  moderator: 86600
  admin: 604800

// The numbers above are just an example, all defined in seconds. Helper is 1 hour, Moderator is 1 day, and admin is one week.

**Comment by Freyhold** [comment]
why did u close it lol  i want this option

**Comment by pop4959** [comment]
@Haczyn [Download the latest version of Essentials](https://essentialsx.netlify.com/downloads.html). This was closed automatically because the feature request has been merged.
