### ISSUE TITLE
LuckPerms + EssentialsX = Permissions issues on world change (fly test)

### ISSUE THREAD

**Issue by andrewkm** [EssentialsX/Essentials#2042]
**Full debug:**
hashtags have actions
lp verbose - on
ess debug - on

https://gist.githubusercontent.com/andrewkm/33487d74d04c19bb9edb8e415ee45ffd/raw/ce758158205115538e3a7c9413bb7944c1926761/gistfile1.txt

TL;DR
A user with essentials.fly set to true crossing into a world with essentials.fly set to false will keep their essentials.fly true permission allowing them to fly. Perhaps doesn't change to false fast enough. If the user tries /fly again however, essentials.fly is correctly showing as false.

@lucko perhaps you can shed some light here for us :)

**Tested with other world change methods as well to confirm it's not a portal/stargate issue. (Such as force teleporting the user to the essentials.fly false world with multiverse).**

**Comment by mdcfe** [comment]
Already responded in the Discord, but `essentials.fly` doesn't control the user's fly toggle itself - it controls whether they can use `/fly` to toggle flying.

~~This is essentially a feature request for disabling fly mode when a user teleports to a different world where they don't have the `essentials.fly` permission, which could be a config option.~~

Edit: Essentials already does this, but there's some permissions issue with your setup that interferes with this.

**Comment by andrewkm** [comment]
Awesome :) would love it if you guys can implement this.

**Comment by mdcfe** [comment]
Do you have a server startup log for this? It seems like EssentialsX isn't properly detecting and using LuckPerms as it should.

**Comment by andrewkm** [comment]
This has fixed the issue @md678685 
https://github.com/lucko/LuckPerms/commit/6baa472567a13c9ce2d7ef99e7d5722e99b1cdb5

If there is still something specific you would like shared from our startup log let me know (I cannot share the full log unfortunately.)

**Comment by andrewkm** [comment]
@md678685 

Here are the startup logs from when it was broken as it pertains to Essentials and LuckPerms
https://pastebin.com/raw/hBaxqrAR
