### ISSUE TITLE
some userdata broken  when they join

### ISSUE THREAD

**Issue by Milkshake777** [EssentialsX/Essentials#2044]
### Information

Full output of `/ess version`:
[19:40:19] [Server thread/INFO]: CONSOLE issued server command: /ess version
[19:40:19] [Server thread/INFO]: Server version: 1.8.8-R0.1-SNAPSHOT git-Spigot-db6de12-18fbb24 (MC: 1.8.8)[m
[19:40:19] [Server thread/INFO]: EssentialsX version: 2.15.0.1[m
[19:40:19] [Server thread/INFO]: Vault version: 1.5.6-b49[m
[19:40:19] [Server thread/INFO]: EssentialsXChat version: 2.15.0.1[m
[19:40:19] [Server thread/INFO]: EssentialsXProtect version: 2.15.0.1[m
[19:40:19] [Server thread/INFO]: EssentialsXSpawn version: 2.15.0.1[m

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):
https://gist.github.com/Milkshake777/4cc4473db603b1118780d831632deb49
EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 
https://gist.github.com/Milkshake777/9108530e55a5aa641e14e1ac3caa0ab8
### Details
Describe your issue here.

some player  log in again will be Clear all items
Then the server broadcasts new players join
The program cannot access the file because the file is being used by another program

my english from google
Focus error:
https://gist.github.com/Milkshake777/da758ec0b9745031c421030725f372c7

**Comment by mdcfe** [comment]
The items being reset isn't related to EssentialsX.

It looks like another program has opened the userdata files, or is writing to them when the player logs in. This might be a text editor, an antivirus program or even a duplicate server.

Could you restart the computer that runs your server, and let us know if that fixes the issue?

(In addition, if you aren't using XMPP, delete `EssentialsXXMPP-2.15.0.1.jar`.)

**Comment by Milkshake777** [comment]
ok i know something 
when playerA
Use the same IP to log in playerB accounts
then login playerA will be clean
https://gist.github.com/Milkshake777/d5b5ced5c56580131f6fb5fb6700a72a
@md678685

**Comment by mdcfe** [comment]
Is there any chance you could replicate it with `/ess debug` enabled?

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to respond and reopen the issue.
