### ISSUE TITLE
/baltop customization

### ISSUE THREAD

**Issue by WizzleBear** [EssentialsX/Essentials#2047]
Maybe adding a section in the config.yml dedicated to customizing /baltop further would be nice. You could add an option to change the header, footer, and how the numbering goes.

**Comment by partydev** [comment]
Further customization of the messages in baltop would be amazing!

**Comment by TheExceed** [comment]
Can I add on to this? Allowing the ability to customize the font/color of the player strings output from /baltop would be nice too.
For example:
&61. &e{player} | &a{balance}
