### ISSUE TITLE
Title and/or Action Bar when changing gamemode. :D

### ISSUE THREAD

**Issue by TheIntelloBox** [EssentialsX/Essentials#2048]
Hi ! :D 

I have an easy idea for EssentialsX ! :D In fact, could you add a title or an action bar, when a player changes his gamemode ? :D 
I have an example for your, don't worry ! :D 
If the player does /gamemode 1, it says in the main title "Gamemode changed" and in the subtitle "to Creative". :D And for the action bar : "Gamemode changed to creative". :D 
I think that it would be very very very good for EssentialsX ! :D 

Thanks ! :D 
TheIntelloBox. :D

**Comment by mdcfe** [comment]
Action/boss bar messages aren't something we're planning at the minute, but this is open to PR.

**Comment by pop4959** [comment]
I don't know that this specifically makes much sense, although if action bars were added to the plugin, it should probably be made possible for any message. Please follow #2391 to discuss potential changes such as this for future chat improvements.
