### ISSUE TITLE
Glitch with beds and /tp player1 player2. :D

### ISSUE THREAD

**Issue by TheIntelloBox** [EssentialsX/Essentials#2051]
Hey ! :D 

A player of my Minecraft server just found a bug. :D 
In fact, if player2 sleeps in a bed, if we do the command /tp player2 player1, the player isn't sleeping on the bed, but he's "flying". :D Just look my screenshot below ! :D 

https://cdn.discordapp.com/attachments/430335199843319809/458683134238523392/2018-06-19_19.16.26.png ! :D 

Thanks for fixing it ! :D 
TheIntelloBox ! :D

**Comment by Xeyame** [comment]
iirc this is not an essentials bug, but a bug in minecraft in general

**Comment by TheIntelloBox** [comment]
Is the command /tp player1 player2, in a vanilla server ? :o

**Comment by Xeyame** [comment]
Yea it is

**Comment by TheIntelloBox** [comment]
Are you sure that is bug is by default in a vanilla server ? :D

**Comment by Xeyame** [comment]
If i recall correctly, yes. Also essentials doesn't mess with teleports a lot. If you can confirm this not happening in vanilla it's a valid bug.

**Comment by mdcfe** [comment]
This is not an EssentialsX bug, it's just a quirk with how Minecraft teleports players that are sleeping.

**Comment by TheIntelloBox** [comment]
Hello ! :D 

Okay thanks for your answer my friends ! :D 

Thanks again ! :D 
Best regards ! :D 
TheIntelloBox. :D
