### ISSUE TITLE
sign kit

### ISSUE THREAD

**Issue by Xtreaper101** [EssentialsX/Essentials#2052]
when I use the permission essentials.kit.use.buy you can buy stuff from the sign [buy] but when I do essentials.kit.use.kit all it says is permission essentials.kits.pvp needed to use this kit, how do i fix this

**Comment by Xeyame** [comment]
Add the permission ¯\_(ツ)_/¯

**Comment by Fordy436** [comment]
`essentials.kit.use.kit all` isn't a thing... Neither is `essentials.kit.use.buy`. 

The [BUY] signs use `essentials.signs.use.buy`
The [KIT] signs use `essentials.signs.use.kit`

To give someone access to all kits, it's `essentials.kits.*` or `essentials.kits.[kitname]` to give someone access to a particular kit only.

**Comment by mdcfe** [comment]
@Xtreaper101 If this is still an issue after following @Fordy436's [advice](https://github.com/EssentialsX/Essentials/issues/2052#issuecomment-399263103), could you explain the issue more clearly?

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to respond and we'll reopen the issue.
