### ISSUE TITLE
Check gm/fly/god/tptoggle permission when re-join to the server

### ISSUE THREAD

**Issue by DardBrinza** [EssentialsX/Essentials#2053]
I propose to add an important test for permission to be in different modes. For example, the administrator gave the player fly, but the player does not have permission to do so and the next time you log on to the server due to lack of permission from the player will be removed fly.
According to the standard in the config, you can turn off this functionality, but for administrators with online above 300 on the survival server, this will be quite important functionality.

Config:
https://pastebin.com/VkhweJg4

(The module is enabled, the survival of leaves survival, creative and adventure move to survival, disable fly and god)

Permissions:
essentials.checker.gamemode
essentials.checker.fly
essentials.checker.god
essentials.checker.tptoggle

**Comment by mdcfe** [comment]
This is already implemented for god mode by default.

EssentialsX does not persist fly mode across relogs, unless the user is both already in the air *and* has `essentials.fly.safelogin`.

This can already be done outside of EssentialsX using the Spigot and EssentialsX APIs. Including this automatic system inside EssentialsX will likely create confusion when users enable it without understanding it and it then conflicts with other plugins that do similar things (such as Multiverse Inventories, which can automatically set fly mode and gamemode iirc).

As this doesn't seem to be a highly-requested feature, I don't see this happening soon.

**Comment by TNTUP** [comment]
I'd love to see this added because I need to fork this repo ever again for updates to remove the god check. Adding that permission like ignore check, would leave that player with god mode enabled^^
