### ISSUE TITLE
add /mail clearall /mail clear <user>

### ISSUE THREAD

**Issue by jpeaceau** [EssentialsX/Essentials#2057]
Suggestion: Add /mail clearall & /mail clear <player> due to people potentially abusing /mail sendall I had to make a plugin to fix this for a case that happened to me, all it does is clear all mail when installed on the server onEnable() and 6 people on the first day already got it.

**Comment by mdcfe** [comment]
If people are abusing `sendall`, why are you giving them access to it?

I think this should take an optional timestamp (like #963), but this would then require mails to store timestamps (as requested in #1527).

**Comment by jpeaceau** [comment]
Because drama happened with an admin and I. You could just make it /mail list "all"/player then /mail clearall <index> or /mail clear <player> <index>
