### ISSUE TITLE
replying to vanshed players

### ISSUE THREAD

**Issue by Vaarikas** [EssentialsX/Essentials#2066]
When messaging someone while in vanish (or sending the message, then vanish. Doesn't matter), they can't message you with /msg but still can use /reply command  to message you (as long as you are the last person who messaged them, of course) therefore exposing you.

Version: 2.15.0.1

**Comment by mdcfe** [comment]
I think this should be added as a config option, to allow people to choose whether to keep the current behaviour (allowing people to reply to vanished players) or use the new behaviour (checking whether they are visible to the player first).

**Comment by Vaarikas** [comment]
That would be amazing.

**Comment by ConnorFranta** [comment]
There is another sneaky one players like to use, /baltop. If it has your [RankName] next to your balance, they know you are online in vanish.
