### ISSUE TITLE
The config of the messages pt_BR is not detected

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#2067]
EssentialsX does not detect the locate of the variation of portuguese "pt_BR" (brazilian portuguese). The configuration automatically picks up from the EssentialsX jar file, not the root folder. Only "pt" (Portuguese from Portugal) language is detected if put in the config.

Build #628 (2.15.0.16)

![screenshot_1](https://user-images.githubusercontent.com/13368991/42540001-3b216b9c-8473-11e8-9490-f599e49462d9.png)
![screenshot_3](https://user-images.githubusercontent.com/13368991/42540003-3b402c3a-8473-11e8-9f1f-550ff2b0e774.png)

**Comment by pop4959** [comment]
File should end with ".properties" and not ".properti" which seems to be the case for you.
