### ISSUE TITLE
Feature Suggestion: Socialspy Blacklist

### ISSUE THREAD

**Issue by SirBlobman** [EssentialsX/Essentials#2075]
- Socialspy blacklist instead of whitelist

Sometimes you want to be able to see all commands EXCEPT some
e.g: '*' but you don't need to see "/login" or "/sell all"

**Comment by pop4959** [comment]
Doesn't seem like there's much interest in this. Also, I'd argue if you want to see all commands logged, check the console. There you have them all. Social spy isn't really intended for logging/viewing commands, but rather messages, so a blacklist doesn't really fit in with the intended use of the feature.

**Comment by mdcfe** [comment]
If you want more in-depth command logging features, you can try [this CommandSpy plugin](https://www.spigotmc.org/resources/commandspy.61494/) which might better suit your needs.
