### ISSUE TITLE
Compatibility with /back

### ISSUE THREAD

**Issue by AlansS53** [EssentialsX/Essentials#2076]
Hello! It would be possible to add an option in config.yml to place compatible commands with /back?
I am currently using the Residence, PlotSquared and ASkyBlock plugins in which the teleport commands do not work with the back command.
I do not know if this is very difficult, but maybe I could place a list of commands that when executed, keep the last location of the command /back.

Example:
- Place the commands here
back-compatibility:
   plotme home
   island
   res tp

**Comment by mdcfe** [comment]
Set [`register-back-in-listener`](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/config.yml#L451) to `true` in your `config.yml`.
