### ISSUE TITLE
Command sign

### ISSUE THREAD

**Issue by elliot-huffman** [EssentialsX/Essentials#208]
Can you add a sign that runs a command when executed?

That would make my day!

**Comment by Terrobility** [comment]
Use MyCommand

**Comment by elliot-huffman** [comment]
It appears to be a stalled project. its last update is from February and when 1.9 comes out I would like to have as much compatibility as possible as fast as possible.

I did look into that plugin and its premise is good but support is not what I would call "supported".

Thanks for the thought!

**Comment by drtshock** [comment]
Unlikely.

**Comment by elliot-huffman** [comment]
@drtshock Thx for the info.
