### ISSUE TITLE
Is the Update for 1.13 coming soon?

### ISSUE THREAD

**Issue by Shiftrr** [EssentialsX/Essentials#2081]
### Information

Full output of `/ess version`:

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 

### Details

Describe your issue here.

**Comment by TAfirehawk** [comment]
Good question....haven't seen much around here about 1.13 as SpigotMC is in dev stage right now and looks pretty stable.

**Comment by kashike** [comment]
![soon](https://i.imgur.com/xbGMMks.png)

**Comment by DoNotSpamPls** [comment]
Please do not ask for updates or an ETA. It will be when it is out. not a moment sooner, not a moment later.

**Comment by mdcfe** [comment]
See the status update [here](https://github.com/EssentialsX/Essentials/issues/2086#issuecomment-408167473).
