### ISSUE TITLE
Add a config option to disable players in spectator gamemode from showing up on /near

### ISSUE THREAD

**Issue by AfkF24** [EssentialsX/Essentials#2082]
The title basically says it.

**Comment by pop4959** [comment]
I don't really see the purpose of this. Seems very specific, and you could probably just use a custom plugin or something to handle this for your server. Doesn't really seem like a thing that is necessary on most servers.

**Comment by AfkF24** [comment]
Legitimately forgot I've even opened this. Nonetheless, I don't think a config option or even a permission node to handle this would hurt anybody and people could find use of it in various ways.
