### ISSUE TITLE
Error when placing/using signs

### ISSUE THREAD

**Issue by KyaniteKingdom** [EssentialsX/Essentials#2084]
### Information

Full output of `/ess version`:

Server version: 1.12.2-R0.1-SNAPSHOT git-Spigot-642f6d2-57ab4cf (MC: 1.12.2)
EssentialsX version: 2.15.0.1
PermissionsEx version: 1.23.4
Vault version: 1.5.6-b49
EssentialsXProtect version: 2.15.0.1
EssentialsXChat version: 2.15.0.1
EssentialsXSpawn version: 2.15.0.1

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):
https://gist.github.com/KyaniteKingdom/b7df3e4a4e73098d592913e0743ae6db

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 
https://gist.github.com/KyaniteKingdom/179a497059b3a933f49312ae0fa51876

### Details

I get a big error in console any time anyone places or uses a sign. I removed all other plugins and it still happens with only Essentials installed. 

All I did to cause the above error was place a blank sign.

**Comment by montlikadani** [comment]
Invalid string key in messages_en.properties:
```
[17:52:06] [Server thread/WARN]: Missing translation key "signFormatSuccess" in translation file en
```
Please check the messages_en.properties file.

**Comment by KyaniteKingdom** [comment]
Thank you, that fixed it :)
