### ISSUE TITLE
Connot compile EssentialsX from "1.13" branch

### ISSUE THREAD

**Issue by arklanq** [EssentialsX/Essentials#2086]
As I have mentioned above, I can't compile EssentialsX via maven's "mvn clean install". I have followed compilation instruction on README page. I have also downloaded via BuildTools and (automatically installed in m2 repo) these versions of bukkit/craftbukkit/spigot:
1.8, 1.8.3, 1.9, 1.9.4 and.. 1.13pre-7 and 1.13 dev build.

Anyway still cannot compile the plugin, following error occurs:
[https://image.ibb.co/kixTJo/Szkic.png](https://image.ibb.co/kixTJo/Szkic.png)

**Comment by arklanq** [comment]
PS: I want to integrate EssentialsX with my own plugins, which are prepared for native 1.13.

**Comment by Aerodog** [comment]
yeah, I figured that essentials would be updated pretty quickly considering how important it is to many servers, but the code hasn't been touched in 9 days. devs are probably dead.

**Comment by mdcfe** [comment]
@IdkMan2 The `1.13` branch currently supports an early API preview, and doesn't directly support any released Spigot build. For now, use EssentialsX 2.15.0 as a dependency. This shouldn't cause any issues with 1.13 plugins.

@Aerodog At the moment Trent and SupaHam are busy with their own lives and I'm on my way home from a trip. We will be working on 1.13 support when we have time, which shouldn't be too long now.
