### ISSUE TITLE
Player in jail relogs and is not teleported back

### ISSUE THREAD

**Issue by stevmei** [EssentialsX/Essentials#2089]
### Information

Full output of `/ess version`:

Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1509 (MC: 1.12.2)
EssentialsX version: 2.15.0.9
PermissionsEx version: 1.23.4
Vault version: 1.5.6-b49
EssentialsXChat version: 2.15.0.9
EssentialsXProtect version: 2.15.0.9
EssentialsXAntiBuild version: 2.15.0.9
EssentialsXSpawn version: 2.15.0.9

### Details

When a player is jailed and relogs, he is not teleported back to his last position when the jail time ends. Can this bis verified here? It is no problem as we (team / staff) can teleport the player to the spawn but I just want to know if this is a expected behavior.

Thanks :)

**Comment by mdcfe** [comment]
We don't currently have time to look into this, but once we've updated to 1.13 I'll take a look.

**Comment by Aerodog** [comment]
The solution is to remove the jail feature because no one is going to sit in a box, and putting someone in “jail” just makes young server admins giddy with power. Ban/temp ban and move on.

**Comment by stevmei** [comment]
No, our staff members for example use jail to investigate griefers so they can't move on on the server but we can still investigate their inventory.

So there are reasons to jail a player into a safe place.

Thanks @md678685

**Comment by mdcfe** [comment]
@Aerodog It's not our place to dictate how server admins do their jobs. If I sell you a pie, it's not my fault if you throw it in someone's face.

In fact, @sigmaroot's use case for jails is a very good use for jails, and honestly something I've never even considered before.

**Comment by pop4959** [comment]
I'm pretty sure the reason is that it uses the back teleport point, and this is reset when the player is gone. If it's not an issue for you to teleport the players (or the players to teleport themselves) after they are jailed, this is probably not a major problem. Feel free to create a new issue if you feel that a feature request is in order, assuming you are still looking for something like this.
