### ISSUE TITLE
Arrows in chat

### ISSUE THREAD

**Issue by evilstriker** [EssentialsX/Essentials#2093]
### Information

Full output of `/ess version`:

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 

### Details

Describe your issue here.

I deleted the arrows in the chat in essentials config but they are still in the chat.

**Comment by Xeyame** [comment]
What do you mean with arrows? If you changed it in the essentials config, make sure you have EssentialsXchat installed, and make sure no other plugin is changing the chat format.

**Comment by evilstriker** [comment]
These ones: http://prntscr.com/kcw9s1

Op ma 30 jul. 2018 om 16:19 schreef Xeyame <notifications@github.com>:

**Comment by Xeyame** [comment]
Are you using EssentialsX chat? If not install it, or change the chat format in another plugin you have installed.

**Comment by evilstriker** [comment]
Im using x but how do i change format?

Op ma 30 jul. 2018 19:43 schreef Xeyame <notifications@github.com>:

**Comment by Xeyame** [comment]
I mean if you have the EssentialsXChat.jar file installed? Else the chat format setting in the config won’t work.

**Comment by evilstriker** [comment]
I dont even have x gimme a second

Op ma 30 jul. 2018 19:53 schreef Xeyame <notifications@github.com>:

**Comment by evilstriker** [comment]
Nvm i got it

Op ma 30 jul. 2018 19:53 schreef Xeyame <notifications@github.com>:

**Comment by evilstriker** [comment]
I got essentialsx 2.0.1

Op ma 30 jul. 2018 19:53 schreef Xeyame <notifications@github.com>:

**Comment by evilstriker** [comment]
It worked omg thanks!!

Op ma 30 jul. 2018 19:53 schreef Xeyame <notifications@github.com>:

**Comment by Xeyame** [comment]
No problem, Please now close the issue :)

**Comment by evilstriker** [comment]
Thanks for the help I got it to work!
