### ISSUE TITLE
Disable nick system

### ISSUE THREAD

**Issue by fede1132** [EssentialsX/Essentials#2096]
### Information

Full output of `/ess version`:

Server version: 1.12.2-R0.1-SNAPSHOT git-Spigot-642f6d2-57ab4cf (MC: 1.12.2)
EssentialsX version: 2.15.0.1
Vault version: 1.5.6-b49
EssentialsXSpawn version: 2.15.0.1

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 

### Details

Describe your issue here.

Hello, i'm using another /nick command plugi, but essentials ovveride it, please there a method to disable Essentials' nick system ?

**Comment by Xeyame** [comment]
Usually when you restart your server and another plugin registers a command, essentials will disable the command. However if this doesn't happen, you can try to use [Commands.yml](https://bukkit.gamepedia.com/Commands.yml) to bind the command to the other plugin.
