### ISSUE TITLE
Add events for private messages

### ISSUE THREAD

**Issue by funniray** [EssentialsX/Essentials#2097]
It would be nice to have an event for private messages that would let you see who the PM sender is, the recipient and then it would let you be able to cancel the event. This would be useful for other plugins that let you ignore and then it would also let you be able to make like a friends only thing. I feel like this along with events for things that interact with other players (like even TPA) would be nice.

**Comment by Aerodog** [comment]
If you use a plugin that takes over private message functionality and offers an ignore feature, you'll have exactly what you're looking for. Other chat plugins also have better API support. Alternatively, you can intercept the chat packet with protocollib.

**Comment by funniray** [comment]
I want to be able to whitelist PMs and TPA, instead of blacklisting users.

**Comment by mdcfe** [comment]
This is a feature that should definitely already be a part of EssentialsX. Unfortunately, I can't work on it at the moment, but this it definitely on list of things to do.
