### ISSUE TITLE
Events API [question]

### ISSUE THREAD

**Issue by BaxAndrei** [EssentialsX/Essentials#2100]
How can I make so my plugin can send an event to my data-base when an admin mutes/kicks or bans a player?Its it even possible to do something like that using essentials api?

**Comment by mdcfe** [comment]
For mutes, you can listen for the [`MuteStatusChangeEvent`](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/net/ess3/api/events/MuteStatusChangeEvent.java), which includes the IUser of the player who was muted/unmuted (`getAffected`) and the person who muted/unmuted them (`getController`).

For kicks, you can use Bukkit's [`PlayerKickEvent`](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/player/PlayerKickEvent.html).

There is no API for bans, so you'll need to do your own detection logic (observing commands etc).

**Comment by BaxAndrei** [comment]
Thanx.
