### ISSUE TITLE
Ability to open and modify shulker boxes without placing them

### ISSUE THREAD

**Issue by saturnux** [EssentialsX/Essentials#2111]
not an issue.

Can you make a permission to open a shulkerbox directly from the inventory ?

Google trad for more explain:
>You can create a permission to open the boxes from the inventory without placing them. A bit like the enderchest, but without command.

Thx

**Comment by mdcfe** [comment]
This would involve loading the inventory from the item's NBT data, since you can't easily access the inventory of a shulker box from its ItemStack. In contrast, ender chest inventories are readily available through Bukkit.

I'm not sure whether this is in the scope of EssentialsX due to the complexity involved.

**Comment by Jikoo** [comment]
Actually, you can access it from the ItemStack using the Bukkit API. It has a BlockStateMeta that can be used to get the block inventory.

Had the same style request on another plugin's tracker, ended up making [PortableShulkerBox](https://github.com/Jikoo/PortableShulkerBox). It's a pretty simple plugin, most of the nuisance lies in ensuring inventory contents changes are saved to the box's original ItemStack.

Permission is `portableshulkerbox.open`, default true.

**Comment by mdcfe** [comment]
@Jikoo Thanks for pointing that out - I wasn't aware of that.

It's unlikely I'll get around to implementing this any time soon. If anyone wants to PR this, feel free.

**Comment by JRoy** [comment]
Outside of the scope of essentials, we would prefer not to manage inventories.
