### ISSUE TITLE
[1.13] /spawner

### ISSUE THREAD

**Issue by TheClowner** [EssentialsX/Essentials#2112]
Server Version: 1.13-R0.1-SNAPSHOT git-paper-99 (MC: 1.13)
EssentialsX Version: 2.15.0.18

When using /spawner, the error "Error: Target block must be a mob spawner." always shows and the command doesn't work - when you are actually targeting a mob spawner.

**Comment by pop4959** [comment]
@md678685 [https://gyazo.com/aef134ddefcade0f5c0303ed0fec7f8c](https://gyazo.com/aef134ddefcade0f5c0303ed0fec7f8c)

**Comment by mdcfe** [comment]
I believe this is fixed in the 1.13 branch.

**Comment by seema84** [comment]
yes its fixed in the 1.13 branch

**Comment by mdcfe** [comment]
Closing as this has been fixed in the experimental builds.

@TheClowner If you still encounter this problem on the experimental builds (`dev-xx.yy`), let us know and I'll reopen this.
