### ISSUE TITLE
Spawners Converting to Pig on Placement

### ISSUE THREAD

**Issue by Tomographix** [EssentialsX/Essentials#2113]
Hi,
Version: PaperSpigot 1.13-R0.1-Snapshot
EssentialsX: 2.15.0.18
Permissions: LuckPerms v 4.2.58

Players on placing a spawner will have it turn into a pig.
All ranks inherit essentials.spawnerconvert.* and was not an issue on 1.12.
OP players can place without an issue.
thanks

### Information

Full output of `/ess version`:

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 

### Details

Describe your issue here.

**Comment by WaverlyCole** [comment]
Plugin isnt 1.13 compatible yet

**Comment by Tomographix** [comment]
I am aware but MD requested it to be reported anyway :)

**Comment by mdcfe** [comment]
@Tomographix Is there any chance you could test whether this is still an issue on the latest [experimental builds](https://ci.ender.zone/job/EssentialsX-Experimental/)?

**Comment by Tomographix** [comment]
Hi @md678685 sure. Pretty sure I did comment on this the other day saying it was fixed though in the latest builds I think?

**Comment by mdcfe** [comment]
I don't recall seeing a comment, but I might be mistaken. Either way, thanks for confirming that this is fixed!
