### ISSUE TITLE
[1.13] Whois Failure

### ISSUE THREAD

**Issue by AmazedMender16** [EssentialsX/Essentials#2115]
ERROR - https://pastebin.com/Jzi2dZ4u
ESSENTIALS - 2.15.0.18

The WHOIS command is throwing these errors on execute.

**Comment by mdcfe** [comment]
This error doesn't occur in the 1.13 branch as it was fixed by ace361af60a6dc373d9850cec8f93ed56a2f8773, however the statistic reported is inaccurate, which is fixed in 4e165d375c463d5f755e2abf03185c38b4c2f638. Thanks for the bug report!
