### ISSUE TITLE
Feature Request: Config option for AFK message broadcast

### ISSUE THREAD

**Issue by DeliciousJaffa** [EssentialsX/Essentials#2116]
I'm currently using EssentialsX and BetterSleep, BetterSleep hooks into essentials to check if a player is AFK to adjust it's logic. 
I'd like to set an automatic AFK in the essentials config but players and myself find it too spammy/clogging up chat, especially considering this status can already be seen in /list.

**Comment by mdcfe** [comment]
For now, you can set `userIsAway` in `messages.properties` to a blank message if you'd like to hide the message.

**Comment by triagonal** [comment]
This has been implemented in #2780 and is present in EssentialsX versions 2.17.2.56 and above.
