### ISSUE TITLE
Item Name Support 

### ISSUE THREAD

**Issue by Scorpionvssub** [EssentialsX/Essentials#2117]
Can you guys add the option:

Block-Name-Selling: true/false 

Can be something else but what this option would do is this:
When someone does /sell all or /sell hand it checks if that item has a custom name like collectibles have a custom name.

If the item has a custom name or is renamed and block-name-selling = true it will not sell that specific item.
Edit: Possibly with -o to override named objects to still be sold

(Small issue/suggestion): I've had players doing sell hand without realising that /sell hand sells that item in hand + any corresponding in the inventory, maybe make it /sell hand all if they wanna sell all items of that type?

**Comment by JRoy** [comment]
closing in favor of #3516
