### ISSUE TITLE
/gamemode doesn't work in 1.13

### ISSUE THREAD

**Issue by TheCactusMonkey** [EssentialsX/Essentials#2118]
### Information

Full output of `/ess version`: doesn't work either, just reloads the plugin.

-> Essentials-2.x-SNAPSHOT build #30 from Aug 14th

Server log [Error/Server Log](https://gist.github.com/TheCactusMonkey/3051e1d696f8159c59d183a81b5333cc)

EssentialsX config [config.yml](https://gist.github.com/TheCactusMonkey/6fcee45cc95842a88f41b2553625e940) 

### Details

Any /gamemode commands doesn't work in Essentials-2.x-SNAPSHOT build #30 from Aug 14th 5am CET.

Alias:
> /gmc
> /gamemode c
> /gamemode creative

All of them are broken and doesn't work at all.

**Comment by smmmadden** [comment]
are you sure you are using the latest Essentials plugin?  I'm using 2.15.0.17 and they all work fine with the latest Spigot build.  Make sure this is returned when you check the version.
![image](https://user-images.githubusercontent.com/10309346/44091638-1d9a5770-9f9c-11e8-88ec-65cdb0dc1385.png)
Or with ess version
![image](https://user-images.githubusercontent.com/10309346/44091721-68f72888-9f9c-11e8-9d87-e394c8857b94.png)

**Comment by Scorpionvssub** [comment]
latest actually is .18

**Comment by Xeyame** [comment]
@TheCactusMonkey Is your server in offline mode?

**Comment by mdcfe** [comment]
@TheCactusMonkey You're running Spigot-Essentials, not EssentialsX. EssentialsX does not currently support 1.13. Please report this error to Spigot-Essentials.
