### ISSUE TITLE
/tnt is acting wierd :S

### ISSUE THREAD

**Issue by chillerkraft** [EssentialsX/Essentials#212]
how come /tnt barely hurts mobs and doesn't throw them back?
let me know what information you need in order to help assist us figure out what's going on :)

**Comment by drtshock** [comment]
not sure? does it throw tnt at them?

**Comment by chillerkraft** [comment]
yea its puts the tnt where i want it.
i think whats going on is the tnt actually stays inside the block i set it at, and when it explodes it acts like a very mild damaged explosion.
if i /tnt a block above mobs in order to drop the tnt onto them, it blows up normally and hurts them nornally. so it was just that /tnt that is done at the ground will actually sortof shield the explosion. with tntblockdamage off at least.

**Comment by vemacs** [comment]
Intended behavior by original Essentials project.
