### ISSUE TITLE
Allow teleporting to a player when there is a hole in floor if you are flying.

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#2120]
Currently if you try to teleport to someone flying over the void or where there is a hole in the floor _in a different world_ it denies the teleport and outputs ```Error: Hole in floor!```. Would it be possible to allow teleporting to players over void / unsafe locations if you are flying when in a different world?

Or at least make it so ```/tpo``` can override?

Teleporting to someone over void while flying in the same world works fine. It's when teleporting from a different world where it errors.

**Comment by mdcfe** [comment]
Making `/tpo` override this behaviour doesn't make sense, because disabling safe teleportation isn't the purpose of that command.

There seems to be lots of issues raised about safe teleport behaviour when teleporting between worlds - this definitely needs looking into.

**Comment by ghost** [comment]
Yes this is kind of annoying for me as well, I don't need a safe spot when I am in creative mode.

**Comment by mdcfe** [comment]
#3102 includes a fix for this and has been merged into the latest dev builds. You can download them from the [EssentialsX website](https://essentialsx.net/downloads.html).
