### ISSUE TITLE
(1.13) error

### ISSUE THREAD

**Issue by FrankHeijden** [EssentialsX/Essentials#2125]
### Information

Full output of `/ess version`:
17.08 14:48:55 [Server] INFO Server version: 1.13-R0.1-SNAPSHOT git-Spigot-fe3ab0d-bfb9131 (MC: 1.13)
17.08 14:48:55 [Server] INFO EssentialsX version: 2.15.0.${git.closest.tag.commit.count}
17.08 14:48:55 [Server] INFO Vault version: 1.5.6-b49
17.08 14:48:55 [Server] INFO EssentialsXGeoIP version: 2.15.0.${git.closest.tag.commit.count}
17.08 14:48:55 [Server] INFO EssentialsXSpawn version: 2.15.0.${git.closest.tag.commit.count}
${git.closest.tag.commit.count} = compiled build as of commit `4dc1d2c50e6ef852c8a8ec67984f0abcb159669d`

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):
https://gist.github.com/FrankHeijden/1a31b566849303092ba84ee43391c883
EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 
default
### Details
the 8000 lines of debug lol

**Comment by mdcfe** [comment]
Items aren't currently supported on 1.13. In addition, official [experimental builds](https://ci.ender.zone/job/EssentialsX-Experimental/) are available - please use those where possible when reporting issues on 1.13.

**Comment by FrankHeijden** [comment]
So when is this going to be supported?
