### ISSUE TITLE
Unable to set bed spawn by clicking on a non-red bed during the day.

### ISSUE THREAD

**Issue by Herdsman45** [EssentialsX/Essentials#2127]
### Information

Server version: 1.13-R0.1-SNAPSHOT git-Spigot-2b0e71c-4a24108 (MC: 1.13)
EssentialsX version: 2.15.0.20
Vault version: 1.6.7-b81
EssentialsXSpawn version: 2.15.0.20
EssentialsXChat version: 2.15.0.20

Default Config other than:
When users die, should they respawn at their first home or bed, instead of the spawnpoint?
respawn-at-home: true

### Details
Right clicking a red colored bed during the day works as expected.
Right clicking any color bed other than red, does nothing and produces no errors.
Sleeping in any bed at night updates the location correctly.

Reproduced on a fresh server running only EssentialsX version: 2.15.0.20 as well as the above configuration.

**Comment by PhotoAlexC** [comment]
**Information:** 
Server version: 1.13-R0.1-SNAPSHOT git-Spigot-fe3ab0d-bfb9131 (MC: 1.13)
EssentialsX version: 2.15.0.1
permissionsEx version: 1.23.4
Vault version: 1.5.6-b49

**Details**
Same problem as described in original issue.

![minecraft screenshot 2018 08 19 - 20 45 48 58](https://user-images.githubusercontent.com/42524516/44315824-467d6600-a3ed-11e8-8ca7-0301a154332c.png)

**Comment by mdcfe** [comment]
This was fixed in the 1.13 branch by 6c9c9ad42a65091ff3dc28a7583e13e6660d8641.
