### ISSUE TITLE
Essentials chat/respawn "group" error

### ISSUE THREAD

**Issue by NickCloudAT** [EssentialsX/Essentials#2131]
Information
Server version: git-PaperSpigot-1f7d532 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
EssentialsX version: 2.15.0.18
LuckPerms version: 4.2.58
Vault version: 1.5.6-b49
EssentialsXChat version: 2.15.0.18

Config: https://pastebin.com/JUqu8fHR

Details
Sometimes if a player respawns, this error appears: https://pastebin.com/uLr2f82d

A simillar error also appears sometimes (less common) if a player writes something in chat. But it also is a nullpointer with "group" at the end

**Comment by Remski01** [comment]
1.7.10 is not supported, please update to atleast 1.8.8

`Actively maintained and updated for the latest Spigot and Minecraft versions at all times, retaining support going back to 1.8.`

**Comment by mdcfe** [comment]
You can ignore this error - it should have no detrimental effects on your server. EssentialsX doesn't seem to be able to retrieve a player's groups while they are respawning, meaning LuckPerms throws an error when EssentialsX doesn't give it a group to get the prefix from.

I can't recall this ever being reported on 1.8 or above, and 1.8 is the lowest server version we support. If you can replicate this on 1.8 or above, please let us know.
