### ISSUE TITLE
Teleport-to-center=true being overridden when teleport-safety and force-disable-teleport-safety are true

### ISSUE THREAD

**Issue by JGuerndt** [EssentialsX/Essentials#2138]
### Information

Full output of `/ess version`:

Server version: 1.12.2-R0.1-SNAPSHOT git-Spigot-2cf50f0-2b93d83 (MC: 1.12.2)
EssentialsX version: 2.15.0.1
PermissionsEx version: 1.23.4
Vault version: 1.5.6-b49
EssentialsXChat version: 2.15.0.1
EssentialsXGeoIP version: 2.15.0.1
EssentialsXSpawn version: 2.15.0.1

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)): 
https://gist.github.com/JGuerndt/5a7cb39bf84ef708e3953be0fdf90163

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 
https://gist.github.com/JGuerndt/0b5d0102346935c6e1887f508adf0022

### Details

With these settings:
teleport-safety: true
force-disable-teleport-safety: false
teleport-to-center: true

Outcome:
You can not teleport to an unsafe location as expected, unless in creative.
Teleport to center works as expected by giving whole number coordinates.

With these settings:
teleport-safety: true
force-disable-teleport-safety: true
teleport-to-center: true

Outcome:
You can teleport to an unsafe location as expected, even between worlds. (the above config may resolve issue #2120 - their config was not attached to show if these settings are used)
Teleport to center does not work as expected by giving whole number coordinates.
You have to specify the decimal ".5" as part of the coordinate to teleport to center of block.
It seems that "force-disable-teleport-safety: true" overrides teleport-to-center: true, losing the ability to teleport to center by giving a whole number only.

**Comment by JRoy** [comment]
Teleport system has been revamped since this issue has been submitted, please reopen if the issue persists

**Comment by Antal1609** [comment]
This is still an issue on 2.19.0-dev+135-347751a

**Comment by pop4959** [comment]
@Antal1609 Please open a new issue and fill out the issue template so that we can look into it.
