### ISSUE TITLE
/banip command doesn't kick players with the banned IP

### ISSUE THREAD

**Issue by leonardo-dgs** [EssentialsX/Essentials#2143]
When an IP is banned using `/banip <ip>` or `/banip <player>`, the online players with that IP doesn't get kicked

**Comment by mdcfe** [comment]
https://github.com/EssentialsX/Essentials/blob/849efa9756495a34260d57ff1d81df1283e5f5e7/Essentials/src/com/earth2me/essentials/commands/Commandbanip.java#L17

This has been a TODO for [over 4 years](https://github.com/EssentialsX/Essentials/commit/575a8142ff4ce34afffc1dee8eca8ba11a33bf6b)...
