### ISSUE TITLE
Silent commands

### ISSUE THREAD

**Issue by iGabyTM** [EssentialsX/Essentials#2149]
My suggestion is to add a way to execut silent commands (without the message in-chat to the target)
For example, the **/eco [give/take]** command have that annoying message (i know it can be removed from **messages_\##.properties** but maybe you don't want to remove it at all).

**/eco take GabyTM 1234 -s**

**Comment by mdcfe** [comment]
Do you want to prevent players being informed when you do `/eco` commands? The only way to do this currently is to remove the messages from the locale.

I'll mark this as an enhancement - perhaps we could add a `sendMessage` method to `EssentialsCommand` that doesn't do anything if the command is silenced. Though, I don't know what syntax could be used that isn't ambiguous.

**Comment by pop4959** [comment]
Closing this for now, but leaving as open to PR in case someone is actually interested in trying to implement this.
