### ISSUE TITLE
Home issue

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#215]
When someone is muted they can't do /home

**Comment by FlippantCactus** [comment]
Versions?

**Comment by ghost** [comment]
@TWSSYesterday  Sorry forgot to write those.

EssentialsX 2.0.1-b196

**Comment by ShadowRanger** [comment]
Do you happen to have the home command added to the 'mute-commands' section of the Essentials config.yml file?

**Comment by ghost** [comment]
Nope

**Comment by SupaHam** [comment]
Please http://pastebin.com your config.yml.

**Comment by ghost** [comment]
@SupaHam http://paste.yu8.me/?9c1388960c1530f2#lWKEI6yDr3V67IB+Akskmjnn16gQcsDRVIUkVVjd+HU=

**Comment by SupaHam** [comment]
Please confirm the issue is still happening, if it is, I'll need a list of plugins the server is using.

**Comment by ghost** [comment]
Problem is fixed, sorry forgot to post.
