### ISSUE TITLE
pumpkin <> carved_pumpkin

### ISSUE THREAD

**Issue by SlimeDog** [EssentialsX/Essentials#2155]
Spigot 1.13.1 latest (and 1.13)
EssentialsX 2.15.0.45 (and previous)

Prior to the 1.13.x flattening, pumpkins were carved (jack-o-lanterns). Naturally spawned pumpkin is now uncarved; carved_pumpkin is a different block/item entirely.
```
/give [player] pumpkin
/i [player] pumpkin
```
give a carved_pumpkin, as they did prior to 1.13.x.

**Comment by Xeyame** [comment]
This is probably going to get fixed by #2153.

**Comment by SlimeDog** [comment]
Yes, probably. :)

**Comment by mdcfe** [comment]
When the new item system lands, carved pumpkin will have the names `carved_pumpkin` and `carvedpumpkin` automatically. Is it worth adding alternative item names for this?

**Comment by SlimeDog** [comment]
Those should work fine. **`carved pumpkin`** would be a nice extra.

**Comment by mdcfe** [comment]
I don't think we're going to add aliases with spaces between, as our commands aren't currently designed to handle that.

**Comment by SlimeDog** [comment]
No worries. I guess that's more a Skript thing. :)

**Comment by Xeyame** [comment]
There are a few other names i can think of, `hollow_pumpkin`, `faced_pumpkin`, `sheared_pumpkin`, `legacy_pumpkin`, `cutted_pumpkin`.

**Comment by mdcfe** [comment]
I've updated the script to add a few more pumpkin aliases. They'll be added to this repo when I get a chance to push an updated `items.json`.

**Comment by mdcfe** [comment]
Closing as the actual aliases have been added (though the plugin hasn't yet been updated).
