### ISSUE TITLE
1.13.1 - /enchant doesn't work with Trident

### ISSUE THREAD

**Issue by tsiedsma** [EssentialsX/Essentials#2161]
### Information

Full output of `/ess version`:

Server version: 1.13.1-R0.1-SNAPSHOT git-Spigot-0ede7d0-c88ae6b (MC: 1.13.1)
EssentialsX version: 2.15.0.45
PermissionsEx version: 1.23.4
Vault version: 1.6.7-b${env.TRAVIS_BUILD_NUMBER}
EssentialsXChat version: 2.15.0.45
EssentialsXSpawn version: 2.15.0.45

### Details

While holding a trident, type /enchant channeling and it says "Error: You have nothing in your hand."

**Comment by pop4959** [comment]
I'm not getting this error on my server.

Server version: CraftBukkit version git-Spigot-0ede7d0-ee5efeb (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
EssentialsX version: 2.15.0.69
PermissionsEx version: 1.23.4
Vault version: 1.5.6-b49

Gif: [https://gyazo.com/5f9f147726b3d1794e6079d75a49bfea](https://gyazo.com/5f9f147726b3d1794e6079d75a49bfea)

**Comment by tsiedsma** [comment]
![2018-09-05_16 22 45](https://user-images.githubusercontent.com/2625597/45121856-f78f3a80-b127-11e8-952f-ba0da9d9c42d.png)

**Comment by Xeyame** [comment]
You are running `2.15.0.45`. Please update

**Comment by tsiedsma** [comment]
That's the latest version @ https://ci.ender.zone/job/EssentialsX/

**Comment by Xeyame** [comment]
Try from here, https://ci.ender.zone/job/EssentialsX-Experimental/
Notice its experimental and using it on public servers isn't recommended.

**Comment by tsiedsma** [comment]
Ok, confirmed it works.  Any idea when a release that fixes that issue will be safe to use in production?

Server version: 1.13.1-R0.1-SNAPSHOT git-Spigot-0ede7d0-c88ae6b (MC: 1.13.1)
EssentialsX version: dev-23.73
PermissionsEx version: 1.23.4
Vault version: 1.6.7
EssentialsXChat version: dev-23.73
EssentialsXSpawn version: dev-23.73

**Comment by mdcfe** [comment]
@lhdev Once 1.13 support for EssentialsX is released, which we'll announce closer to the time.

**Comment by mdcfe** [comment]
Closing as this issue has been fixed in 1.13 builds.
