### ISSUE TITLE
/home doesn't trigger "teleporting" message

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#2162]
### Information

Full output of `/ess version`:

[21:29:02 INFO]: Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1554 (MC: 1.12.2)
[21:29:02 INFO]: EssentialsX version: 2.15.0.34
[21:29:02 INFO]: LuckPerms version: 4.2.71
[21:29:02 INFO]: Vault version: 1.6.7-b${env.TRAVIS_BUILD_NUMBER}
[21:29:02 INFO]: EssentialsXSpawn version: 2.15.0.34

config.yml, messages_en.properties, and latest.log with /ess debug:

https://gist.github.com/eightbitx/aedf83ac203649158f1016e5ad5d5e7b

### Details

When players do /home they do not receive a message in chat notifying them that a teleportation request has been received. I expected output in chat that says "Teleporting to \<home name\>".

/home is the only command to have this issue so far.

**Comment by mdcfe** [comment]
The `/home` command doesn't have a "`Teleporting to {0}`" message as far as I know, so this would need to be added.

**Comment by mdcfe** [comment]
This was added by PR #2489 - you can download the latest version from the [build server](https://ci.ender.zone/job/EssentialsX).
