### ISSUE TITLE
Message not inside the en.properties file

### ISSUE THREAD

**Issue by FlailoftheLord** [EssentialsX/Essentials#2165]
Okay, so theres a message i found thats missing in the messages_en.properties lang file.

When you type /tpa [player] it sends this...
![tpa-request](https://user-images.githubusercontent.com/41513161/45173715-fd902480-b1d6-11e8-8c5e-c37217f26430.png)

**to cancel this request type /tpacancel**

I then went and searched through the messages_en.protperties file, using ctrl+f to search for any keywords, even the orange color code,
Nothing came up, the format for that second message is not inside the File, could you please add it in the next update? 
I also tried adding it myself
but i had no idea what to name the identifier. so that didnt work.
Thankss!

Heres the /ess version output:
![EssentialsX-Version-output](https://user-images.githubusercontent.com/41513161/45173830-4a73fb00-b1d7-11e8-8552-b32bbb3106c8.png)

**Comment by Xeyame** [comment]
https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/messages.properties#L542

**Comment by FlailoftheLord** [comment]
Oh, ok thanks!!

**Comment by mowmowkittycat** [comment]
im having this issue and that link above does not work

**Comment by Xeyame** [comment]
https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/resources/messages.properties#L1365
