### ISSUE TITLE
respawn-listener-priority does not work.

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#2167]
# Set this to lowest, if you want Multiverse to handle the respawning.

I set it to lowest, reloaded, restated, it still takes over Multiverse on death respawns.

**Comment by TomLewis** [comment]
I removed essentials all together and tried death respawns with Multiverse alone, and its no different it still brings the person to their bed instead of the world-respawn, so I don't think this is Essentials. How can I check what is deciding how a user respawns once they die?

**Comment by mdcfe** [comment]
Remove each plugin systematically until you find the offending plugin.

**Comment by TomLewis** [comment]
Whats so frustrating is it somehow just fixed itself, and I have no idea if I changed anything to fix it. :(

**Comment by triagonal** [comment]
Closing as this was not an issue with Essentials.
