### ISSUE TITLE
EssentialsAntiBuild Item Code Problems

### ISSUE THREAD

**Issue by Jay9519** [EssentialsX/Essentials#2168]
### Information

Full output of `/ess version`:
Server Version: 1.13.1-R0.1-SNAPSHOT git-Spigot-0ede7d0-c88ae6b (MC: 1.13.1
EssentialsX version: dev-23.73
PermissionsX version: 1.23.4
Vault version: 1.6.7
EssentialsXProtect version: dev-23.73
EssentialsXChat version: dev-23.73
EssentialsXChat version: dev-23.73
EssentialsXSpawn version: dev-23.73

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):
https://www.dropbox.com/s/npmex8ejgnj9i40/latest.log?dl=1

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 
https://www.dropbox.com/s/2lovn9pu052e0e1/config.yml?dl=1
### Details

Describe your issue here.
Item codes are not working anymore on the breaking/placing notifications

**Comment by mdcfe** [comment]
Numerical item IDs aren't supported in 1.13.

I haven't looked into updating AntiBuild to 1.13, so this will need investigating.

**Comment by mdcfe** [comment]
Can you reproduce this on the latest [experimental build](https://ci.ender.zone/job/EssentialsX-Experimental)? Protect and AntiBuild now accept Material enum names (like `LAVA_BUCKET`), though they don't accept item IDs any more.

**Comment by Jay9519** [comment]
Yes works great now thank you
