### ISSUE TITLE
[Enchantment] Commandblock support for /time, /weather

### ISSUE THREAD

**Issue by Bodyash** [EssentialsX/Essentials#217]
/weather storm|sun duration
so i can`t use this command from commandblock

I need /weather -w [world] storm|sun duration 
to change weather in world from any commandblock.
Same with /time.
Its all because i have command-block based mechanism which can change weather/time when 8+ players stays at pressure plates. with CommanBook this mechanism is working good, but im migrated to essentials, and this command not working in cmdblocks at all.

Sorry for my bad English

**Comment by Bodyash** [comment]
We can close that.

**Comment by mdcfe** [comment]
EssentialsX's `/time` and `/weather` both accept worlds, and you can use the `minecraft:` prefix to force command blocks to use the vanilla command instead.
