### ISSUE TITLE
1.13 Items don't work in blacklist or kits

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#2170]
### Information

Full output of `/ess version`:

Server version: 1.13.1-R0.1-SNAPSHOT git-Paper-222 (MC: 1.13.1)
EssentialsX version: dev-23.73
LuckPerms version: 4.2.88
Vault version: 1.6.7-b${env.TRAVIS_BUILD_NUMBER}

Console kit error with /ess debug, Console blacklist errors, kits.yml, item-spawn-blacklist:
https://gist.github.com/eightbitx/6e7af1a3afc204b1fe58ab9048acb8a8

### Details

Updated to latest dev build and 1.13 items are working with /give, but the blacklist is saying unknown items. Additionally, kits (even with just "dirt") are not working. Interestingly, the dirt kit did work randomly once, but only once among the 20+ times I've tried it.

**Comment by mdcfe** [comment]
I've reverted 1.13 item support until we're able to fix these issues.

**Comment by ghost** [comment]
@md678685 Using lowercase item names in kits seems to fix the problem. However, this same solution does NOT work for the item-spawn-blacklist.

**Comment by mdcfe** [comment]
The item lookups should be case-insensitive anyway. I'll take a look when I get a chance.

**Comment by mdcfe** [comment]
@eightbitx Could you confirm whether you're still having issues with kits and the item spawn blacklist on the [latest experimental build](https://ci.ender.zone/job/EssentialsX-Experimental)?

**Comment by ghost** [comment]
@md678685 Kits, buy/sell signs, etc are working. Haven't checked on blacklist in a while. I see these errors, and I think at least some of these names are correct for 1.13? https://pastebin.com/g2xyBycg

**Comment by mdcfe** [comment]
@eightbitx Any chance you could get a full startup log so I can see where/when this occurs?

Edit: I've *just* pushed a fix (literally a minute ago) that improves logging when loading the `item-spawn-blacklist`, so if possible could you update again?

**Comment by mdcfe** [comment]
The `item-spawn-blacklist` appears to work on the latest Paper and EssentialsX prerelease:
```java
[16:30:51 INFO]: Server version: 1.13.2-R0.1-SNAPSHOT git-Paper-487 (MC: 1.13.2)
[16:30:51 INFO]: EssentialsX version: 2.16-pre1.14
[16:30:51 INFO]: LuckPerms version: 4.3.58
[16:30:51 INFO]: Vault version: 1.7.1-b91
[16:30:51 INFO]: EssentialsXProtect version: 2.16-pre1.14
[16:30:51 INFO]: EssentialsXSpawn version: 2.16-pre1.14
[16:30:51 INFO]: EssentialsXChat version: 2.16-pre1.14
[16:30:51 INFO]: EssentialsXGeoIP version: 2.16-pre1.14
[16:30:51 INFO]: EssentialsXAntiBuild version: 2.16-pre1.14
[16:30:51 INFO]: EssentialsXXMPP version: 2.16-pre1.14
```
