### ISSUE TITLE
Remove underscore from new item names

### ISSUE THREAD

**Issue by pop4959** [EssentialsX/Essentials#2172]
The old Essentials(X) item DB did not require you to type an underscore when trying to request an item. In testing the new item DB, I have found it is really annoying to have to type the underscore. Especially while trying to tab-complete names. For example, typing "/i diamond_sword" instead of "/i diamondsword" (you aren't able to get the tab-complete suggestion for sword until you put the underscore). Any chance this can be changed? I think it's best to update something like this before EssentialsX is released officially for 1.13, because otherwise more people will have to re-update their kits, etc.

**Comment by mdcfe** [comment]
This is mostly due to the fact that the item listing isn't returning all the item names, which it should do.

**Comment by mdcfe** [comment]
@pop4959 The underscore should no longer be mandatory - is there any way you could test this?

**Comment by pop4959** [comment]
@md678685 It looks like it's working in build 39.182, as shown below. Thanks a lot for adding this extra convenience, as I'm sure many people will be happy not to have to type the underscore in order to get a suggestion. Closing this issue now.

![https://i.gyazo.com/1580f125e45442c2e297ef2ddd2fabec.png](https://i.gyazo.com/1580f125e45442c2e297ef2ddd2fabec.png)
