### ISSUE TITLE
Suggestion for auto-afk listeners

### ISSUE THREAD

**Issue by takatalvi** [EssentialsX/Essentials#2173]
**User scenario, rationale**
As part of an AFK rule revision, I recently set `cancel-afk-on-interact` to `false` to disable AFK fishing farms. I still have an auto-AFK timer set to 5 minutes, and `cancel-afk-on-move` on `true`. Now my players like to complain that when they just stand around and chat, they are set to afk, and after some time, kicked due to an auto AFK kick timer.

**The need**
To have a separate setting for cancelling AFK on chat entries, instead of counting it in `interact`. Either on any chat entry, or it could be possible to specify what entries would cancel AFK (plain chat message, /msg, /w, /r, etc.) But really, anything goes - if there was such a setting, managing player presence would be much easier.

**The suggestion**
Add a separate setting for cancelling AFK on a chat/command entry, either on any entry, or on a list of entries that could be customized by the admin.

**Comment by tadeas-drab** [comment]
Hi, I would like to work on this issue. Can it be assigned to me? Thanks

**Comment by mdcfe** [comment]
This has already been implemented in #3863.
