### ISSUE TITLE
Console Spam Checking

### ISSUE THREAD

**Issue by SevenX159** [EssentialsX/Essentials#2175]
### Information

Full output of `/ess version`:
Server version: 1.12.2-R0.1-SNAPSHOT git-Spigot-4bd94dc-fb414fe (MC: 1.12.2)
EssentialsX version: 2.15.0.34
PermissionsEx version: 1.23.4
Vault version: 1.5.6-b49
EssentialsXGUI version: 1.0.2

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):
[latest.log](https://github.com/EssentialsX/Essentials/files/2363962/latest.log)

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)
[config.txt](https://github.com/EssentialsX/Essentials/files/2363963/config.txt)

): 

### Details

Describe your issue here.
Hi,
Sometime, for a reason i ignore, i got console spam really hard ( https://gyazo.com/65b5b73f5f596391b7d3420f3b1332dd if you don't wanna check logs )
If someone could help me since there is no error message so i don't know from what that come, i would be gratefull =)
Thanks

**Comment by Xeyame** [comment]
Seems like you have enabled debug mode. Type `essentials debug` to toggle it back off.

**Comment by mdcfe** [comment]
You have `/ess debug` enabled, and a plugin is repeatedly checking kit expirations, causing these repeated messages. Run `/ess debug` to turn the messages off.
