### ISSUE TITLE
Console gives an error everytime than an user join.

### ISSUE THREAD

**Issue by facundogaidano** [EssentialsX/Essentials#2176]
### Information

Full output of `/ess version`: 2.15.0.34
LuckPerms version: 4.2.58
Vault version: 1.6.7

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)): (No more errors on console :/) 
[11:04:19 INFO]: UUID of player SrFakon is ********-****-****-****-************
[11:04:20 INFO]: SrFakon[/**.**.**.**:*****] logged in with entity id 4635 at ([world]-453.4362031564079, 156.0, 2185.5759344899047)

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): https://gist.github.com/SrFakon/1f59618132bba9e287db2d26c27e6f49

### Details

Only gives this error, no one more. I search by internet about this problem but all of them were with Permissionx and I don't use it :/

**Comment by Xeyame** [comment]
What is exactly the error? These UUID and Logged in messages are completely normal.

**Comment by facundogaidano** [comment]
Oh my bad, sorry. This is the error: [11:04:20 WARN]: [Essentials] Permissions lag notice with (GenericVaultHandler). Response took 30,445239ms. Summary: Getting prefix for SrFakon

**Comment by Xeyame** [comment]
This also isn't an error, just a notice that your permissions plugin is a little bit slow at getting prefixes. If your permissions plugin has a standalone database, you might want to look into that. Although i wouldn't 
worry too much about it, cause its only 30ms.
