### ISSUE TITLE
/give not giving 1.13.1

### ISSUE THREAD

**Issue by DeadIntermediate** [EssentialsX/Essentials#2177]
### Information

Full output of `/ess version`:
http://prntscr.com/ksk57l

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):
https://pastebin.com/DKd7tmFs

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 

### Details

Describe your issue here.

I have tried to  give myself Turtle Spawn Eggs, via command "/i " and "/give" as you can see in the server logs and nothing. But as for using Spigot commands, work just fine. What gives?

**Comment by mdcfe** [comment]
The main release builds of EssentialsX don't yet support 1.13 items yet.

**Comment by DeadIntermediate** [comment]
Any ETA or information that it is being currently being worked on, or some items being added in the next Dev Build Update?

**Comment by Serveix** [comment]
This is the 1.13 new blocks, items and mobs list, including spawn eggs:
- https://minecraft.gamepedia.com/1.13#Blocks
- https://minecraft.gamepedia.com/1.13#Items
- https://minecraft.gamepedia.com/1.13#Mobs

Is anyone working on this already? I will give it a go if no one is.

**Comment by mdcfe** [comment]
@Serveix 1.13 support is present and almost complete in the [`1.13`](https://github.com/EssentialsX/Essentials/tree/1.13) branch, with items support, the main missing functionality, added by PR #2204.

As I said, the [official release builds](https://ci.ender.zone/job/EssentialsX) don't have 1.13 support yet. You may use the 1.13 branch at your own risk.

**Comment by mdcfe** [comment]
Closing as item support is now part of the 1.13 branch and [experimental builds](https://ci.ender.zone/job/EssentialsX-Experimental).
