### ISSUE TITLE
Essentials.joinfullserver not working 

### ISSUE THREAD

**Issue by Zenya4** [EssentialsX/Essentials#2178]
Title says it all. Donators or admins with this permission still get the “server is full” message when they try joining a full server. If it makes any difference, I’m running on Bungeecord and when the backend servers are full this happens to players with the permission node as well.

**Comment by mdcfe** [comment]
Please fill out the issue template as requested.

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to respond and reopen the issue.
