### ISSUE TITLE
Leather armour improperly serialised

### ISSUE THREAD

**Issue by lol768** [EssentialsX/Essentials#218]
https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/ItemDb.java#L331

Should be comma-separated R,G,B values instead of just an int. Alternatively, the config reader/deserialisation should support this type of colour integer (in addition to the existing format).

https://korobi.io/network/esper/channel/drtshock/logs/2015/10/08/#L223

**Comment by SupaHam** [comment]
Fixed in bae6f89 and 9805f3f.

**Comment by lol768** [comment]
Any unit tests?

**Comment by SupaHam** [comment]
None, functionality has been tested by me successfully.
