### ISSUE TITLE
Suggestion for sell command

### ISSUE THREAD

**Issue by LaughNgamez** [EssentialsX/Essentials#2182]
Suggestion that would be useful for /sell & /sellall would be a feature to limit what can be sold depending on item status.

For example being able to have an option "disable-selling-named-items: true"

Personally this would be a nice change to prevent players selling rares or custom items they don't wish to sell. I've seen other threads of this request when looking into this.

**Comment by Xeyame** [comment]
You already have requested this before, that issue is still open. #1988

**Comment by mdcfe** [comment]
Closing in favour of #1988.
