### ISSUE TITLE
[Suggest] [Feature] make "/home" able to use in console and commandblock.

### ISSUE THREAD

**Issue by playbabe** [EssentialsX/Essentials#2183]
heyyyyyy
I try to do my own cumtomize feature in my server using datapack, commandblock and Essentials plugin work togather.
But I got a ploblem, /home and /homes can only be execure by player.

May you look into it? maybe make it work if have target (@a,name,@p,eles)

**Comment by Xeyame** [comment]
The @ selectors are currently broken iirc, but how would you let a command block do /home anyways? That should then teleport the command block or something xD. You might want to look into using /execute or /sudo for teleporting players.

**Comment by playbabe** [comment]
Well, If we use /home {playername}
That player will got teleport to his/her home.

But I can't apply this method to commandboock or console.

/sudo that player need permission to run command and I don't give it on purpose. 
/execute can only use vanilla command. (1.13)

**Comment by Xeyame** [comment]
Uhm, no? That will teleport you to a home you set (with name `{playername}`), If you didn't set a home with that name it will list your set homes. Are you sure you are using essentials for setting homes?

**Comment by playbabe** [comment]
Is I experiment. Yes it will tp to home with that name but

If we add third text, the second text will become player name instead of home name.

"/home {playername} bed" -> tp that player to his bed.

**Comment by Xeyame** [comment]
I still dont think you are using Essentials for homes. The only similar prefix i know of is `/home playername:homename`, but that teleports the player executing that command to someone else's home. `/home playername homename` is also invalid, thus showing your own home list.

**Comment by playbabe** [comment]
Hmm, maybe you right. It was a year ago when I test it with other plugin that save bed spawn point.

I will try test it tomorrow.

**Comment by playbabe** [comment]
you were right! but im gonna open new suggest issues :D

**Comment by mdcfe** [comment]
Closing as this doesn't appear to be valid.
