### ISSUE TITLE
[Suggest] Sudo Ideas

### ISSUE THREAD

**Issue by DevCold211** [EssentialsX/Essentials#2186]
Have 2 things for sudo /sudo {Username} c:Put your message here & /sudo {Username} {command}

**Comment by Xeyame** [comment]
This is already how sudo works?

**Comment by mdcfe** [comment]
As @Xeyame said, you have literally just described the `/sudo` command.

**Comment by kennyrkun** [comment]
I think they meant `/sudo {Username} c:Put your message here` would make them send a chat message.

**Comment by mdcfe** [comment]
This is already a feature.

**Comment by kennyrkun** [comment]
I used Essentials since 2011 and I didn't know this? I'm an idiot.

**Comment by mdcfe** [comment]
This has been part of `/sudo` since [October 2012](https://github.com/EssentialsX/Essentials/commit/e670d0af452dc91ea36adf82dcbd8d2530984ea4) 😛
