### ISSUE TITLE
Insane lag from Essentials

### ISSUE THREAD

**Issue by jordanwilliams1** [EssentialsX/Essentials#2193]
Here lag from essnetialsx on 1.13

https://i.gyazo.com/f877b556782e15d695db62ae4c91366f.png
https://timings.aikar.co/?id=c693f51ef361455898fd18c300d7c04c#timings

verison: https://i.gyazo.com/43ead94f57e50fb258d7e65af7ebc2bc.png

**Comment by Xeyame** [comment]
In this case, the lag is from people doing Essentials /home, causing this plugin to load chunks. Your server seems to be lagging quite a bit (maybe not enough I/o) and thus that takes up a lot of time, making Essentials look like it's lagging

**Comment by jordanwilliams1** [comment]
I Was reading in the spigot IRC and was wondering if this would be possible with pappers async chunk?
"A fork of Essentials to use async would be very easy, all their teleports use a custom method. "

Could make a config option for papers async chunks?

**Comment by mdcfe** [comment]
Closing in favour of #2326.

Edit:
> This should now be improved due to integrating PaperLib - grab the [latest build](https://ci.ender.zone/job/EssentialsX/) from the build server.
> 
> Special thanks goes to @DoNotSpamPls for contributing this.

**Comment by BurkenDev** [comment]
This still is not working though over a year later. Timings show that essentialsx is still causing these problems. Even when nobody is on the server.

**Comment by pop4959** [comment]
@BurkenDev Please don't necro post closed issues. If you are still having performance issues please open a new issue and include as much information as possible.
