### ISSUE TITLE
/kittycannon destroy turtle eggs

### ISSUE THREAD

**Issue by andris155** [EssentialsX/Essentials#2199]
### Information

Full output of `/ess version`:
```
04.10 18:52:35 [Server] INFO Server version: 1.13.1-R0.1-SNAPSHOT git-Paper-332 (MC: 1.13.1)
04.10 18:52:35 [Server] INFO EssentialsX version: 2.15.0.45
04.10 18:52:35 [Server] INFO LuckPerms version: 4.3.2
04.10 18:52:35 [Server] INFO Vault version: 1.7.1-b${env.TRAVIS_BUILD_NUMBER}
04.10 18:52:35 [Server] INFO EssentialsXChat version: 2.15.0.45
04.10 18:52:35 [Server] INFO EssentialsXGeoIP version: 2.15.0.45
04.10 18:52:35 [Server] INFO EssentialsXSpawn version: 2.15.0.45

```

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):
I send if need.

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 
https://pastebin.com/SEydSzr4

### Details

Describe your issue here.
https://www.youtube.com/watch?v=AvADyCvbL3A

**Comment by mdcfe** [comment]
The attached video doesn't appear to show this bug in action?

**Comment by mdcfe** [comment]
@andris155 Did you solve this?
