### ISSUE TITLE
Add silent commands

### ISSUE THREAD

**Issue by LagClear** [EssentialsX/Essentials#2201]
Can you guys add a silent teleport command like example /warp crates LagClear -s or /tphere LagClear -s

This would make it so it sends no messages to the player that got teleported.

**Comment by mdcfe** [comment]
This would require handling at the `onCommandEssentials` level, and would involve some amount of refactoring all commands to enable this. I don't see this as a high priority at this point, but it's possible in theory.

**Comment by pop4959** [comment]
Same as #2149
