### ISSUE TITLE
Error unbanning players

### ISSUE THREAD

**Issue by kaanakduman** [EssentialsX/Essentials#2203]
### Information
`/ess version`, server log, and config all at 
https://hastebin.com/vusuqazaqu.coffeescript

### Details
I use luckperms to give some people a ★ suffix. If a mod with this suffix bans someone, they get put into the banned-players list, but then they can not be unbanned and their ban message can not be changed.

**Comment by kakd** [comment]
It looks like hastebin cleared my paste. 

/ess version:
[15:55:52 INFO]: Server version: 1.13.1-R0.1-SNAPSHOT git-Paper-352 (MC: 1.13.1)
[15:55:52 INFO]: EssentialsX version: 2.15.0.45
[15:55:52 INFO]: LuckPerms version: 4.2.17
[15:55:52 INFO]: Vault version: 1.5.6-b49
[15:55:52 INFO]: EssentialsXGeoIP version: 2.15.0.45
[15:55:52 INFO]: EssentialsXChat version: 2.15.0.45
[15:55:52 INFO]: EssentialsXAntiBuild version: 2.15.0.45
[15:55:52 INFO]: EssentialsXSpawn version: 2.15.0.45

I can not reobtain the server log or the config very easily at the moment, but I think that you shouldn't need that considering I told you how to replicate the issue.

**Comment by Serveix** [comment]
Hello, I'd like to take a look at this issue. I believe it has to do with some reading problem using a non ASCII character such as the ★. I'll keep you updated.

**Comment by kaanakduman** [comment]
I was wrong. This isn't the cause of the issue. I have no clue what is.
I have a shortcut in commands.yml to where /banx will act like /ban. The only difference is that /banx adds an extra message to the end of the ban message. Sometimes /banx results in a `warning: player never joined the server` message so I suspected this to maybe be the issue, but my tests couldn't confirm it.

**Comment by mdcfe** [comment]
@kakd Should I close this issue?

**Comment by kaanakduman** [comment]
It's still an issue I'm experiencing with my server. I had thought it was caused by the star suffix but it must be caused by something else.

**Comment by mdcfe** [comment]
Could you provide an example of a broken `banned-players.json` entry (one where you *can* unban the player) and one that is *not* broken (one where you *can't* unban them)?

**Comment by kaanakduman** [comment]
It now seems to happen with all players. I switched to paper 1.13.2 and updated my essentials a while ago. I also tested it out without essentials installed and it seemed to still have an error, "Error: Player not found", instead of "Error: null". So this probably isn't an issue with essentials considering the issue persisted even without essentials.
