### ISSUE TITLE
/jump not function (disappear) in 1.13.1

### ISSUE THREAD

**Issue by mechcalvin** [EssentialsX/Essentials#2205]
### Information

Full output of `/ess version`:

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 

### Details

Describe your issue here.

/jump start not working in 1.13.1 

#649 2.15.0.45

it will auto go to /jumpto in worldedit, /jump in essentialsx disappear, /top, /back are working fine

**Comment by mdcfe** [comment]
Does `/ejump` work?

If so, [create an alias for `jump` to run `essentials:jump`](https://essentialsx.github.io/#/Common-Issues?id=essentialsx-overrides-a-command-from-spigot-or-another-plugin).

**Comment by mechcalvin** [comment]
what /ejump or essentials:jump does is just stick on the same block, it doesn't go where the center of the mouse pointed to

**Comment by seema84** [comment]
fixed in 1.13 branch

**Comment by mdcfe** [comment]
Closing as this appears to be fixed in the 1.13 branch.
