### ISSUE TITLE
Sign Commands Do Not Execute

### ISSUE THREAD

**Issue by WolfGameStudios** [EssentialsX/Essentials#2207]
Whenever I try to right click a sign with command executing data the sign does not execute the command. It does not produce an error but I have deduced that the cause is this plugin as all the plugins I've used before and have not encountered this issue, Please find and fix whatever is causing this...

**Comment by mdcfe** [comment]
What?

EssentialsX does not have command signs.

**Comment by BluePlastics** [comment]
Are you sure essentials is causing it and not oh the fact that 1.13 broke the heck out of selectors in every which way?

**Comment by mdcfe** [comment]
@BluePlastics EssentialsX does not have "command signs" as described by the OP, so that still doesn't make sense.

@WolfGameStudios Please clarify your issue. This does not seem to relate to EssentialsX whatsoever.

**Comment by BluePlastics** [comment]
@md678685 my guess was he's attributing selectors not working to essentialsx since his signs have essentialsx commands attached to them. But we won't know for certain unless he replies.

**Comment by mdcfe** [comment]
Closing due to lack of response from @WolfGameStudios. If this is still an issue, please open a new report.
