### ISSUE TITLE
/itemdb on birch logs registers as oak logs

### ISSUE THREAD

**Issue by smmmadden** [EssentialsX/Essentials#2209]
**EssentialsX:** 2.15.0.52 (AntiBuild, XChat, XGeoIP, XProtect & XSPawn)
**Paper Spigot:** 1.13.1 (Build 355)
**Waterfall:** b227

**/itemdb** OR **/essentials:itemdb** with _Birch log_ held in hand returns **oak log**
![image](https://user-images.githubusercontent.com/10309346/46879356-d18a4380-ce13-11e8-8267-ae050ddc0ef6.png)
**/itemdb birchlogs** returns the correct entry of **LOG - 17:2 and right short names.**
Item identifier above the block when holding is correct:
![image](https://user-images.githubusercontent.com/10309346/46880663-4d39bf80-ce17-11e8-9a79-58cdea83916d.png)

**These links are set to never expire.** 
The log attached shows without TreeAssist being loaded in case it conflicted.  Same results both ways.
items.csv: https://pastebin.com/nBRkR8FR
config.yml: https://pastebin.com/1myA2s7m
Plugins:  https://pastebin.com/hUDAfwFq
Startup Log: https://pastebin.com/t9BUkNqi

Thanks - Steve

**Comment by mdcfe** [comment]
You're running a non-1.13.x build on 1.13.1, and there are no officially supported builds that support items on 1.13.x yet.

Edit for clarification: this will be fixed as part of #2204.

**Comment by smmmadden** [comment]
Thanks for the quick reply MD - still doing testing, so wanted to make sure this was reported.

**Comment by smmmadden** [comment]
all stripped logs are registered as AIR - 0.
![image](https://user-images.githubusercontent.com/10309346/46918030-b8f86580-cf9a-11e8-84f6-b642b5e76431.png)
![image](https://user-images.githubusercontent.com/10309346/46918055-fbba3d80-cf9a-11e8-9425-757302f40133.png)

If you want a separate issue for each of the ones I'm finding, let me know or the # to post under.  Thanks!

**Comment by Xeyame** [comment]
This will probably be every item added in 1.13, and thus not supported by the spigot compatibility layer.

**Comment by smmmadden** [comment]
yes I know.  We do need to know which ones that need to be added though don't we and keeping track of what is or isn't?

**Comment by mdcfe** [comment]
Every item in 1.13.1 is at least recognised by the new system, as it uses a new database of items generated from Bukkit's list of every item in the game.

**Comment by mdcfe** [comment]
Closing as item support is now part of the 1.13 branch and [experimental builds](https://ci.ender.zone/job/EssentialsX-Experimental).
