### ISSUE TITLE
/back save location not stored properly? 

### ISSUE THREAD

**Issue by CorrupTftw89** [EssentialsX/Essentials#2214]
### Information

Full output of `/ess version`:

 14.10 12:32:23 [Server] INFO EssentialsXSpawn version: 2.15.0.52
14.10 12:32:23 [Server] INFO EssentialsXAntiBuild version: 2.15.0.52
14.10 12:32:23 [Server] INFO EssentialsXProtect version: 2.15.0.52
14.10 12:32:23 [Server] INFO Vault version: 1.7.1-b91
14.10 12:32:23 [Server] INFO LuckPerms version: 4.2.58
14.10 12:32:23 [Server] INFO EssentialsX version: 2.15.0.52
14.10 12:32:23 [Server] INFO Server version: 1.13.1-R0.1-SNAPSHOT git-Paper-355 (MC: 1.13.1)

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):
https://gist.github.com/CorrupTftw89/6b585cde671b151e03de943d93976d62
EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 
https://gist.github.com/CorrupTftw89/6b585cde671b151e03de943d93976d62
### Details

Describe your issue here.

I'm running EsseentialsX2.15.0.52 (Which is the latest I'm pretty sure)

And when players do /back twice it doesn't properly register their saved location this is one of my players describing the issue. 

"Sadly the /back still glitches on occasion. I was working on my tower last night and needed to go out for resources. Along the way I found an area I l wanted to explore and began harvesting resources. I clicked /back to go home and place the full inventory into my chests then tried to go back to the spot for a bit more. This time it just sent me a few spots away from where I was standing in my base, and I lost the spot I was in." 

Kind  Regards
Server Admin of ElderCrafters

**Comment by mdcfe** [comment]
Can you replicate this or provide steps to replicate it?

**Comment by CorrupTftw89** [comment]
This happens almost everytime you do/back it dosent give any errors which is the weird part. It just dosent work properly.

Skaffa Outlook för Android<https://aka.ms/ghei36>

________________________________

**Comment by Serveix** [comment]
Hello, in order to find out what is causing the error, we need to replicate it. I can't seem to be able to do it. Please give more details on how you found the issue other than a user quote.

**Comment by M1904** [comment]
we have the same problem only with the new blocks like stripped wood, wood, coral-blocks,...

**Comment by mdcfe** [comment]
Closing due to a lack of response. If this is still an issue, could you provide more detail?
