### ISSUE TITLE
Essentials Chat Prefix - Suffix

### ISSUE THREAD

**Issue by ACEx86** [EssentialsX/Essentials#2219]
Full output of `/ess version`: 2.15.0.52

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)): https://gist.github.com/0OMPHALOS/91cb7ee9407c31312f0a3f56169c68e4

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): https://gist.github.com/0OMPHALOS/085573702d3b2a59f2cb58b66e9e11a4

### Details

Essentials Chat Faills to apply groups prefix suffix and also fails to get the groups position. (From essentialsgroupmanager - I never had this issue back in the days..)
*I have not tried another permission plugin

**Comment by BluePlastics** [comment]
Read your server logs please:
[12:34:20] [Server thread/WARN]: [Essentials] Features such as chat prefixes/suffixes and group-related functionality will not work until you install Vault.

You need to install vault for prefix, suffix, etc. to work.

**Comment by mdcfe** [comment]
As @BluePlastics **and the logs that you provided** said, you need to install Vault to use chat prefixes and suffixes with EssentialsX. We also do not support GroupManager.
