### ISSUE TITLE
1.13 commands lag

### ISSUE THREAD

**Issue by Castiella** [EssentialsX/Essentials#2220]
SERVER VERSION: PAPER 1.13.2 Build 396

Ess : 2.15.0.52
Vault: 1.6.1
EsSPAWN: 2.15.0.52
Esschat: 2.15.0.52

TIMINGS: https://timings.aikar.co/?id=aab506b802554c3fa14f3caf13817196

A lot of essentials commands are giving us lag. When someone does /skull it will send the tps from 20 to 17. 

/back is causing issues on the current timings but /home has also been problematic. 

**Edit by @md678685: corrected `SERVER VERSION` as per Timings link**

**Comment by mdcfe** [comment]
[Please replicate the issue with a supported permissions plugin.](https://essentialsx.github.io/#/Common-Issues?id=i-need-help-with-groupmanager--wheres-the-updated-groupmanager)

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to respond and reopen the issue.
