### ISSUE TITLE
tab complete 1.13

### ISSUE THREAD

**Issue by seema84** [EssentialsX/Essentials#2222]
tab complete error in build #28 (https://ci.ender.zone/job/EssentialsX-Experimental/28/)

https://pastebin.com/RzH69mak

Spigot-eb21557-4a47be6 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
EssentialsX version: dev-28.154
EssentialsXChat version: dev-28.154

**Comment by mdcfe** [comment]
Does this happen with only `/gm`?

**Comment by seema84** [comment]
no, with all commands

**Comment by seema84** [comment]
ok thats the same problem https://github.com/EssentialsX/Essentials/issues/2224
if i remove the last line in items.json than it works

**Comment by mdcfe** [comment]
This should be fixed by a7fcafb245b96a6f496c15f5a4fe39c425d56c55 - grab the latest experimental build from the [build server](https://ci.ender.zone/job/EssentialsX-Experimental).
