### ISSUE TITLE
Use JsonReader.setLenient(true)

### ISSUE THREAD

**Issue by seema84** [EssentialsX/Essentials#2224]
error on server start -> https://pastebin.com/TTJx9Erx

Spigot-eb21557-4a47be6 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
EssentialsX version: dev-28.154
EssentialsXChat version: dev-28.154

**Comment by mdcfe** [comment]
I had already fixed this, and it seems the fix didn't get past the refactoring.

The previous fix was to remove the checksum line before passing the contents of the file to the JSON parsing method, but this apparently isn't present any more.

As a temporary fix, you can manually remove the last line from `items.json` and reboot the server (if you can open the file, that is).

**Comment by seema84** [comment]
"As a temporary fix, you can manually remove the last line from items.json and reboot the server (if you can open the file, that is)."

thats right and works

**Comment by mdcfe** [comment]
This should be fixed by a7fcafb245b96a6f496c15f5a4fe39c425d56c55 - grab the latest experimental build from the [build server](https://ci.ender.zone/job/EssentialsX-Experimental).
