### ISSUE TITLE
RPG Player Leveling API incompatibility with any Essentials/EssentialsX version 

### ISSUE THREAD

**Issue by kingdcreations** [EssentialsX/Essentials#2227]
The RPG Player Leveling API doesn't work if any version of Essentials is enabled:

Code: https://pastebin.com/px4CYj0q

Error: https://pastebin.com/yj6s5Lkw

I tried anything, I just need help!
It only happens when Essentials is enable and the RPG PlayerLeveling developper is kinda innactive...

**Comment by mdcfe** [comment]
This is not an EssentialsX issue.
