### ISSUE TITLE
My warps and teleport commands aren't working 

### ISSUE THREAD

**Issue by MadMuffinMan** [EssentialsX/Essentials#2229]
whenever I try and teleport or use warps it just displays the message "Teleporting..." and nothing happens.
This is my console log:
27.10 22:08:26 [Server] INFO IRONDALEK_123 issued server command: /spawn
27.10 22:08:26 [Server] ERROR Command spawn failed:
27.10 22:08:26 [Server] INFO java.lang.NoSuchFieldError: SPECTATOR
27.10 22:08:26 [Server] INFO 	at com.earth2me.essentials.utils.LocationUtil.isBlockUnsafeForUser(LocationUtil.java:227) ~[EssentialsX-2.15.0.52.jar:?]
27.10 22:08:26 [Server] INFO 	at com.earth2me.essentials.Teleport.now(Teleport.java:122) ~[EssentialsX-2.15.0.52.jar:?]
27.10 22:08:26 [Server] INFO 	at com.earth2me.essentials.Teleport.teleport(Teleport.java:198) ~[EssentialsX-2.15.0.52.jar:?]
27.10 22:08:26 [Server] INFO 	at com.earth2me.essentials.Teleport.teleportPlayer(Teleport.java:168) ~[EssentialsX-2.15.0.52.jar:?]
27.10 22:08:26 [Server] INFO 	at com.earth2me.essentials.spawn.Commandspawn.respawn(Commandspawn.java:56) ~[EssentialsXSpawn-2.15.0.52.jar:?]
27.10 22:08:26 [Server] INFO 	at com.earth2me.essentials.spawn.Commandspawn.run(Commandspawn.java:33) ~[EssentialsXSpawn-2.15.0.52.jar:?]
27.10 22:08:26 [Server] INFO 	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:157) ~[EssentialsX-2.15.0.52.jar:?]
27.10 22:08:26 [Server] INFO 	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:522) [EssentialsX-2.15.0.52.jar:?]
27.10 22:08:26 [Server] INFO 	at com.earth2me.essentials.spawn.EssentialsSpawn.onCommand(EssentialsSpawn.java:73) [EssentialsXSpawn-2.15.0.52.jar:?]
27.10 22:08:26 [Server] INFO 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [PluginCommand.class:1.7.10-1614.58]
27.10 22:08:26 [Server] INFO 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [SimpleCommandMap.class:1.7.10-1614.58]
27.10 22:08:26 [Server] INFO 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) [CraftServer.class:1.7.10-1614.58]
27.10 22:08:26 [Server] INFO 	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370) [nh.class:?]
27.10 22:08:26 [Server] INFO 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107) [nh.class:?]
27.10 22:08:26 [Server] INFO 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
27.10 22:08:26 [Server] INFO 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
27.10 22:08:26 [Server] INFO 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
27.10 22:08:26 [Server] INFO 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
27.10 22:08:26 [Server] INFO 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
27.10 22:08:26 [Server] INFO 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
27.10 22:08:26 [Server] INFO 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
27.10 22:08:26 [Server] INFO 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
27.10 22:08:26 [Server] INFO 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
27.10 22:08:59 [Server] INFO CONSOLE issued server command: /list 
27.10 22:08:59 [Server] INFO Admins: iOwneriIRONDALEK_123
27.10 22:08:59 [Server] INFO hadmin: iHead-AdminiCookieLulDogs

**Comment by mdcfe** [comment]
Please fill out a proper report using the appropriate template.
