### ISSUE TITLE
Players able to create Essentials signs

### ISSUE THREAD

**Issue by VoxaDub** [EssentialsX/Essentials#223]
Ok so this has been happening for a while.
I'm on 2.0.1-b196 and players do not have any perms to create signs, only use.
They have perms to use every type of sign.
Somehow some players are able to create the essentials signs, such as buy/sell/enchant etc.
I dont know how they're doing it, I'm assuming they're using a client of sorts or something but I have not been able to replicate the results myself.
But due to this I have had to disable said signs because its breaking my server because they make a buy sign for dirt for $1 and a sell sign for dirt for $100 tril.
Im not sure how I can get more info on this bug/glitch, if you need more info feel free to msg me on skype (voxadub).

**Comment by drtshock** [comment]
You must be using another plugin that modifies signs as we fixed that issue awhile ago.
