### ISSUE TITLE
Buy/Sell signs do not work with Colored blocks ( Like Red,Green,Etc Concrete).

### ISSUE THREAD

**Issue by Xeddius** [EssentialsX/Essentials#2230]
Full output of `/ess version`:
Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1574 (MC: 1.12.2)
EssentialsX version: 2.15.0.52
Vault version: 1.6.7-b${env.TRAVIS_BUILD_NUMBER}

**Problem**
I am unable to buy or sell blocks with multiple data values.

I've tried using Itemdb to get short names and using those but they do not work either, nor does
251:15
or anything of the sort.
I am able to sell and buy many other items without issue. However all signs created with data values or shortnames end up as invalid.

**Comment by mdcfe** [comment]
Do short names actually work for other items?

**Comment by Midnight9746** [comment]
It should use Red_Wool and stuff now, because of Mojang and it's need to ruin ID's.
(ID's in general)

**Comment by mdcfe** [comment]
@Midnight9746 This is irrelevant for non-1.13 builds of EssentialsX running on Paper 1.12.2, which is clearly stated in the original post.

**Comment by xSepticSidx** [comment]
red_wool is not working, no coloured wool is working apart from white.
all carpet colours cannot be sold (black looks for "bkfloor")
all terracotta blocks like white_terracotta, pink_terracotta etc. are not recognized for /buy or /sell either.
also:
Magenta Stained Glass pane
Light Grey Stained Glass pane
Light Blue Stained Glass pane

**Comment by Xeddius** [comment]
> Do short names actually work for other items?

Not that I am aware of, I've tried shortnames for many items, I am only able to sell or buy items of the original block data value unless using the /sell hand command. Signs do not work at all with extended block ID's like wool, Carpet, Terracotta, Etc, as @xSepticSidx has stated.

**Comment by xSepticSidx** [comment]
It seems no names actually work. correctly.
You can buy the block OK, you can sell the exact same block back OK.
But if you try and sell back the same block but one from creative inv or mined/obtained by survival it says you do not have the correct blocks.
If you want to be able to see this not working, or a more exhaustive list of blocks it fails on let me know.
Any suggestions, or even a list of what all the blocks should be called would be more than welcome :)

**Comment by 3HortB98** [comment]
By any chance are the items on the your 1.12.2 server producing the items with a nbt tag? currently on a 1.13.2 server we are having a similar problem and ive noticed that anything with additional data values like 5:5 or 5:2 it gives the correct item but it adds a "damage" nbt tag to that item with that damage value that is equal to the  item id. For example, buying block with id 5:2 will give you that block but will have a damage nbt value of 2 and a block with id 5:4 will produce that block but with a damage nbt tag value of 4.

**Comment by xSepticSidx** [comment]
Sorry, my mistake:
My server is 13.1.2

TBH I'd really like an extensive list of the names and data values for all 1.13 blocks to try?

**Comment by Xeddius** [comment]
This may be useful for devs.
https://github.com/ModCoderPack/MCPBot-Issues/blob/master/migrations/1.12-to-1.13.md

**Comment by mdcfe** [comment]
@Xeddius CraftBukkit and derivatives (Spigot, Paper) don't use MCP. That page is for mod developers wishing to start working on updating MCP/Forge mods to 1.13.

@xSepticSidx The latest `items.json` with 1.13 names can be found [here](https://gitlab.com/md678685/essx-scripts/-/jobs/artifacts/master/raw/out/items.json?job=run_items), and the latest `items.csv` for older versions can be found [here](https://raw.githubusercontent.com/EssentialsX/Essentials/2.x/Essentials/src/items.csv). Can you also use `F3+H` to check whether there are any NBT values, as @3HortB98 mentioned?

@3HortB98 Are you using `dev-xx.yy` (experimental) builds on your server or `2.15.0.xxx` (release) builds?

**Comment by 3HortB98** [comment]
@md678685 On our server we are using version `2.15.0.52`

**Comment by Xeddius** [comment]
Latest Essentials version on 1.13.2 buy/sell signs now work with item names properly for the most part.

Certain sell/buy signs do have issues with mined blocks vs bought blocks. Specifically polisheddiorite and polishedandesite blocks from what I've observed so far.

**Comment by pop4959** [comment]
Closing since it seems like this is fixed as per the author of this issue. If there is a new, different problem, please create a new issue.
