### ISSUE TITLE
no damage or death falling from high places

### ISSUE THREAD

**Issue by smmmadden** [EssentialsX/Essentials#2231]
I found in my servers that if I turn on **/fly** and go to any height I can double tap my spacebar and fall hundreds of blocks without dieing.  I can also jump off a bunch of blocks high and not take any damage.  This only occurs if I've turned **/fly** on.

I've tested EssentialsX with 1.13.1 and the 1.13.2 (Build 403) of PaperSpigot and they both have the same behavior.  I don't recall reading anything that if a player is given fly permissions that they won't take any damage if they fall.  So I went from 70 plugins down to just the ones I needed on a vanilla server (LuckPerms-Bukkit-4.3.2, EssentialsX-2.15.0.52 & Vault 1.7.1.  I was able to reproduce.
**Plugins**
![image](https://user-images.githubusercontent.com/10309346/47610506-ddd1eb80-da24-11e8-9eeb-56c03a3bba5f.png)

**Full startup log:** https://hastebin.com/aqisikayon.md

Has something changed or is this a bug?  I am an admin and OP level 4, but that has never been an issue in prior versions that I remember.

**Comment by mdcfe** [comment]
~~I get the feeling that this may be a change made to the server software somewhere along the chain.~~ EssentialsX does not actively block fall damage when flight is enabled, so this needs some further investigation.

Edit: I don't think you ever took fall damage when flight was enabled, so I'm not sure anything changed?

**Comment by pop4959** [comment]
I don't think it's a bug. This is how Essentials has worked for as long as I can remember.

**Comment by electronicboy** [comment]
I've been enabling fly mode since pre 1.8 days to avoid fall damage while jumping aimlessly around the world

**Comment by Tofuus** [comment]
I spun up both a 1.8 paper and spigot server and tested with the latest Essentials on Spigot. Fall damage is blocked when you're in fly mode.

**Comment by mdcfe** [comment]
Thanks to @pop4959, @electronicboy and @Tofuus for confirming my suspicion.

@smmmadden As there doesn't seem to be any indication that this changed, could you try and replicate this on a non-1.13.x server?

**Comment by smmmadden** [comment]
I just set up a 1.12.2 server and retested and you are all right.  No damage taken if /fly is enabled no matter whether you are flying of fall off the face of a cliff and not flying.  Very odd since I've been playing since 1.9 days and never noticed it.  I just made sure I didn't fall all these years. lol

I always thought that if I had fall damage enabled that it didn't matter how I fell.  Is there any way that if I did turn on /fly that it look at this setting to determine if fall damage should be maintained?
![image](https://user-images.githubusercontent.com/10309346/47614672-c83ae100-da79-11e8-9df7-078d056e2641.png)
Thanks!

**Comment by mdcfe** [comment]
This is vanilla behaviour and is not at all related to EssentialsX. `/fly` instructs the server to turn on fly mode for a specific player, and a side effect of that is that fall damage is disabled by the vanilla server.

`protect.disable.fall` is part of EssentialsX Protect and is not at all related to EssentialsX's `/fly`.
