### ISSUE TITLE
Issue dealing with items which contain metadata with signs

### ISSUE THREAD

**Issue by Stroodles** [EssentialsX/Essentials#2233]
### Information

**Full output of `/ess version`**:

```
16:32:11 [INFO] CONSOLE issued server command: /ess version
16:32:11 [INFO] Using locale en_GB
16:32:11 [INFO] Essentials reloaded TeamCity.
```

**Server log**: https://gist.github.com/Stroodles/14046212e98a36144cd36978e3a54cb4

**EssentialsX config**: https://gist.github.com/Stroodles/14046212e98a36144cd36978e3a54cb4
### Details

**Description**  
When I attempt to sell Granite which I have collected through mining via the signs it doesn't recognise I have any. When I try to sell it via the /sell hand it works, however, sells it as if it is stone. I can buy Granite from the signs but this wont stack with the 'natural' granite and this sign granite can be sold both through [Sell] signs and by /sell granite, unlike the 'natural' variant. When I used itemdb with the 'Natural' granite it labelled it as 1:0 and stone whereas the store bought is 1:1 and granite.
This also appeared to be the case for lapis as when using '/sell hand' it sold as ink sack as well as everything else I tried which contained metadata which wasn't = 0.

I have realised that in the supporting video that when I clicked on the sell sign (With the item being just the name 'Granite') while trying to sell the 'Natural' granite the mouse press wasn't registered... What happens when I do successfully use my mouse is an error would appear saying 'Error: You do not have 1x granite.'

**Steps to reproduce**  
To make it easier to reproduce I created a clean spigot1.13.2 server with only Essentials-2.x-SNAPSHOT as a plugin. I created buy and sell signs for granite as well as sell signs for '1.1' and '1:1' then tried to sell granite at all three signs which I had mined none of which worked. I then tried to sell it by the '/sell granite' command which again didn't work. The '/sell hand' did, however. I then tested with sign bought granite which worked with all the options

**Expected behavior**  
I expected the 'Natural' granite to be sold using the [Sell] /n 1 /n Granite /n $1 sign

**Screenshots**  
![image](https://user-images.githubusercontent.com/44538264/47611677-d1a26880-dace-11e8-90d2-6e0dca7f38b8.png)
Supporting Video - https://youtu.be/TgSC4BcuSkU

**Edit by @md678685 - removed unnecessary markup**

**Comment by mdcfe** [comment]
Thanks for filling out a detailed report! Unfortunately, you're running Spigot-Essentials, not EssentialsX.

Download the latest stable build from [here](https://ci.ender.zone/job/EssentialsX), or the latest experimental build with improved 1.13.x support from [here](https://ci.ender.zone/job/EssentialsX-Experimental).

**Comment by Stroodles** [comment]
> Thanks for filling out a detailed report! Unfortunately, you're running Spigot-Essentials, not EssentialsX.
> 
> Download the latest stable build from [here](https://ci.ender.zone/job/EssentialsX), or the latest experimental build with improved 1.13.x support from [here](https://ci.ender.zone/job/EssentialsX-Experimental).


Hi, that very true apologies for that haha. I just downloaded EssX and tested everything above on it too: 
06:44:57 [INFO] CONSOLE issued server command: /ess version
06:44:57 [INFO] Server version: 1.13.2-R0.1-SNAPSHOT git-Spigot-a1ba5fe-b4230a9 (MC: 1.13.2)
06:44:57 [INFO] EssentialsX version: 2.15.0.1
All the things I demonstrated in the video and wrote about in my report holds true for EssX as well with no difference in the way it handled it. I tried with granite again as well as lapis as it is a dye with meta data too.

**Comment by mdcfe** [comment]
You're running the outdated Spigot build. Only the 1.13 experimental builds linked in my previous comment support items - could you test on an experimental build?

**Comment by Stroodles** [comment]
Ahh my apologies I tried it again with a fresh download of spigot and the dev build of EssX and its working now thanks for the help apologies for miss-reporting the issue.

**Comment by mdcfe** [comment]
No worries.
