### ISSUE TITLE
Join/leave message issue

### ISSUE THREAD

**Issue by mlefeb01** [EssentialsX/Essentials#2234]
Full output of `/ess version`:

http://prntscr.com/lbfzns

**Server log:** https://gist.github.com/mlefeb01/bac3d976c7ce897a908ae8d5426c4b93

**EssentialsX config** https://gist.github.com/mlefeb01/3eabff304a20df96ba6413ee92a788d5

### Help request

**Problem**
when people join it either says "test true" or "test false" instead of the essentials join and leave messages

**What I have tried**
I have tried changing a bunch of stuff in the config but havent gotten anything to work

**Screenshots**
http://prntscr.com/lbfzbm
http://prntscr.com/lbfzff

**Comment by mdcfe** [comment]
Thanks for opening a support request.

This doesn't seem to be an EssentialsX message - could you post a plugin list?

In addition, the screenshot definitely does *not* show the output of `/ess version` on 2.15.0.1 - could you try that again, making sure you typed the command properly?

**Comment by mlefeb01** [comment]
full /ess version
http://prntscr.com/lbjxmc

plugins
http://prntscr.com/lbjxzm

**Comment by mdcfe** [comment]
Can you replicate this on a clean test server, copying over only EssentialsX, Vault and PEX (and their relevant configs)?

Nothing stands out as the issue in your plugin list, but isolating EssentialsX will help determine whether EssentialsX is the issue or another plugin.

**Comment by mlefeb01** [comment]
i guess its not essentialsx, i just went through my whole plugins folder and didnt find any debug enabled so idk

**Comment by mlefeb01** [comment]
I figured out which plugin was the issue. Its BeastCore, I contacted the dev hopefully I can resolve this 
http://prntscr.com/lbkf7b

**Comment by mdcfe** [comment]
Good to hear you figured out what plugin was causing the issue - can this be closed now?

**Comment by triagonal** [comment]
Closing - issue resolved, and not related to EssentialsX.
