### ISSUE TITLE
/Spawner isnt working correctly.

### ISSUE THREAD

**Issue by jhammerberg** [EssentialsX/Essentials#2237]
Full output of /ess version:
Server version: 1.13.2-R0.1-SNAPSHOT git-Spigot-a1ba5fe-b4230a9 (MC: 1.13.2) 
INFO EssentialsX version: 2.15.0.54 
Vault version: 1.5.6-b49 
EssentialsXProtect version: 2.15.0.54 
EssentialsXChat version: 2.15.0.54 
EssentialsXSpawn version: 2.15.0.54

28.10 21:40:15 [Server] INFO DirkDozer issued server command: /spawner Skeleton
(That is all it says.)

Server log: https://gist.github.com/Warp8/a929eea77d661cae07b72d6a1b7dfb8b

EssentialsX config: https://gist.github.com/Warp8/928bdb245854989427f1885751c15565
Details

Description
When I do /spawner (While looking at a spawner) it says that the target block must be a spawner.

Steps to reproduce
Simply look at a spawner and do /spawner (Any mob type)

Expected behavior
It should change the spawner type to what I put down. eg; /Spawner Skeleton

Screenshots
I can't seem to upload them to Gist. But all they say are things I've already said.

**Comment by mdcfe** [comment]
Did you read my [previous comment](https://github.com/EssentialsX/Essentials/issues/2236#issuecomment-433815001)?

> This is fixed in the 1.13 branch - you need to use [experimental builds](https://ci.ender.zone/job/EssentialsX-Experimental) for this to work on 1.13.2.
