### ISSUE TITLE
Pressure plate = anti afk

### ISSUE THREAD

**Issue by CryLegende** [EssentialsX/Essentials#2241]
**Full output of `/ess version`:**
``Server version: 1.12.2-R0.1-SNAPSHOT git-TacoSpigot-"f8ba67d6" (MC: 1.12.2)
EssentialsX version: 2.15.0.55
LuckPerms version: 4.3.11
Vault version: 1.6.7-b${env.TRAVIS_BUILD_NUMBER}
EssentialsXSpawn version: 2.15.0.55``

**EssentialsX config**: https://gist.githubusercontent.com/CryLegende/ab55937f1d47612ba3236feaf0dbd0a6/raw/5b0e1eb4a744ad1079606f4e1de8b8a905a4b9e8/Essentials_config

**Description**  
When a player afk on a pressure plate, he is not kick for afk by essentials.

**Steps to reproduce**  
afk

**Comment by mdcfe** [comment]
Thanks for filing a bug report!

Unfortunately due to time constraints, I can't look into this right now, but I'll mark this as "help wanted" so people can look into this as needed.

**Comment by CryLegende** [comment]
Ok, thanks you for the fast answer

**Comment by Midnight9746** [comment]
Essentially, it probally sees it as a non-activated plate, so when you afk, it then think that the activated plate somehow moved you down, thus unafks.

Edited:

Change the following to false:

This setting controls if a player is marked as active on interaction.
When this setting is false, the player would need to manually un-AFK using the /afk command.
cancel-afk-on-interact: true

If the player isn't frozen when afking, they should be able to unafk without retyping the command. Doing this, does let them interact with things and slightly move around, but like I don't think that would matter much. [Breaking blocks, looking, etc. won't be recognized and neither will plates, people who are talking but not moving would also go afk unfortunately this is mainly minechatters]

These should be left how they are:

 Set this to true, if you want to freeze the player, if the player is AFK.
Other players or monsters can't push the player out of AFK mode then.
This will also enable temporary god mode for the AFK player.
The player has to use the command /afk to leave the AFK mode.
freeze-afk-players: false

Should we automatically remove afk status when a player moves?
Player will be removed from AFK on chat/command regardless of this setting.
Disable this to reduce server lag.
cancel-afk-on-move: true

**Comment by pop4959** [comment]
As Midnight mentioned, this is configurable. It is intended to un-afk the player if they interact, when cancel-afk-on-interact is set to true.
