### ISSUE TITLE
Groupspawn doesnt work with LuckPerms

### ISSUE THREAD

**Issue by andinis** [EssentialsX/Essentials#2242]
### Information

**Full output of `/ess version`**:

Server version:  1.12.2-R0.1-Snapshot git-Spigot-2cf50f0-2b93d83 (MC: 1.12.2
EssentialsX version: 2.15.0.1
LuckPerms version: 4.3.27
Vault version: 1.7.1-b91
EssentialsXChat: Version 2.15.0.1
EssentialsXSpawn: Version 2.15.0.1

```

**Server log**: https://gist.github.com/andinis/74f11d5786187faf3dae8fed5d1c8681

**EssentialsX config**: https://gist.github.com/andinis/0a56797a57e8db80d29f5f74a1ac5c95

### Details

**Description**  
Since I changed from permissionsEx to LuckPerms the function for groupspawn isn't working, when The specified group enters /spawn they teleport to default spawn,

**Steps to reproduce**  
use LuckPerms as permission manager

**Expected behavior**  
When a certain group types /spawn it should teleport them to the certain location.

**Screenshots**  
<!-- Replace this with screenshots, if necessary. -->

**Comment by mdcfe** [comment]
Could you run `/ess debug`, then paste the console output when a player runs `/spawn`?

**Comment by andinis** [comment]
I get this, that player has multiple groups but it shows only the player group the group priority is the same the groups

https://gist.github.com/andinis/74f11d5786187faf3dae8fed5d1c8681

*edit: I made the group that has the different spawn on a higher priority still doesnt recognize that group only player group, when i remove the playergroup and only leave the other group it does teleport to the wanted location*

**Comment by krusic22** [comment]
Try updating Vault since you are using a very outdated version.

**Comment by andinis** [comment]
> Try updating Vault since you are using a very outdated version.

I updated it and still same issue

**Comment by mdcfe** [comment]
@andinis EssentialsX checks the player's primary group. Make sure your players have their [primary group](https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent#lp-user-user-parent-switchprimarygroup) set correctly and check your [primary group calculation settings](https://github.com/lucko/LuckPerms/wiki/Configuration#primary-group-calculation).

**Comment by andinis** [comment]
@md678685 I've done that, but I will try to recreate all the groups

**Comment by mdcfe** [comment]
@andinis Re-creating all the groups isn't necessary if you've set weights and/or primary groups on users correctly.

**Comment by pop4959** [comment]
Closing due to lack of response. If this is still an issue, please provide a way for us to replicate your exact setup, so that we can confirm it as a bug or not.
