### ISSUE TITLE
big tree spawns where standing, not where looking

### ISSUE THREAD

**Issue by SlimeDog** [EssentialsX/Essentials#2243]
Spigot 1.13.2 latest
EssentialsX 2.15.0.55-b656

>/bigtree ...

(of any type) spawns the tree there the player is standing. This causes damage. According to documentation, not to mention player safety, the tree should spawn where the player is looking.

**Comment by mdcfe** [comment]
This is likely due to material changes in 1.13.x. You can try the experimental builds, but I think `LocationUtil` needs updating for the new materials.

**Comment by SlimeDog** [comment]
I am using the dev builds. Are there other experimental builds?

**Comment by mdcfe** [comment]
You're running a 2.x branch build - the 1.13 branch builds can be found [here](https://ci.ender.zone/job/EssentialsX-Experimental).

**Comment by SlimeDog** [comment]
Thanks. Issue remains with Essentials experimental build dev-32.162

**Comment by pop4959** [comment]
Unable to replicate. Feel free to create a new issue if you have steps to do this on the latest version of Essentials.

**Comment by SlimeDog** [comment]
Confirmed, no longer an issue with EssentialsX 2.17.2.68, and probably a goodly portion of 18 months of dev builds. Thanks.
