### ISSUE TITLE
bigtree replaces non-dirt/grass

### ISSUE THREAD

**Issue by SlimeDog** [EssentialsX/Essentials#2244]
Spigot 1.13.2 latest
EssentialsX 2.15.0.55-b656

Generally, bigtree will not spawn a tree if the ground is not dirt/grass. However
> bigtree jungle

(for example) will spawn a 2x2 trunk even if only two of the four ground blocks are dirt/grass, replacing the other two ground blocks with dirt.

Prepare ground
![screen shot 2018-11-01 at 10 10 47 am](https://user-images.githubusercontent.com/17748923/47867494-e88ed680-ddbe-11e8-9aba-eaec872ed243.png)
Stand on closest dirt block and
> /bigtree jungle
![screen shot 2018-11-01 at 10 12 23 am](https://user-images.githubusercontent.com/17748923/47867511-f2b0d500-ddbe-11e8-923f-a1e6f39f9368.png)
Chop tree to view ground
![screen shot 2018-11-01 at 10 13 07 am](https://user-images.githubusercontent.com/17748923/47867523-f8a6b600-ddbe-11e8-9edb-daee0815e871.png)

**Comment by mdcfe** [comment]
Tree generation is performed by vanilla/CraftBukkit, not by EssentialsX, so the only solution on our side is to add a manual check.

Considering this is a building tool, adding a check seems unnecessary.

**Comment by SlimeDog** [comment]
A check seems reasonable, but I was using **bigtree** only to test a tree-chopping plugin, so it doesn't matter much to me. I don't allow **bigtree** in production.
