### ISSUE TITLE
Gamemode dosn't work in all Groups

### ISSUE THREAD

**Issue by SvenHornburg** [EssentialsX/Essentials#2245]
When i add the permission "Gamemode" at some self-defined groups they cant use them.

The Console says that they haven't the Permission for Gamemode...

**Comment by mdcfe** [comment]
In the future, use the [issue templates](https://github.com/EssentialsX/Essentials/issues/new) for support.

The permission is `essentials.gamemode`.

**Comment by SvenHornburg** [comment]
i have used this permission in the codes but it dosn't work ...

**Comment by kennyrkun** [comment]
make sure you also specify `essentials.gamemode.type`
