### ISSUE TITLE
Disable chat formatting

### ISSUE THREAD

**Issue by TobiasDeBruijn** [EssentialsX/Essentials#2250]
### Feature request

**Feature description**
Be able to disable chat formatting (&m, &l, &1 etc) for everyone. Currently able to "disable" by not giving essentials.format and essentials.color to players. Wont affect OPs. Words like M&M cannot be said, which can be annoying. I'd like to suggest a config option to completely disable it.

**How the feature is useful**
Usefull for people who dont want it or want to talk about M&M's

**Comment by mdcfe** [comment]
This is not a valid feature request - EssentialsX already allows you to do this, provided you have set up permissions properly. Don't use OP, and if necessary, negate permissions from users in your permissions plugin.

**Comment by kennyrkun** [comment]
@TheDutchMC04 you can escape formatting by using an additional `&`

ex: `M&&M` == `M&M`

**Comment by TobiasDeBruijn** [comment]
Alright. THanks!
