### ISSUE TITLE
Item 1.13.X not add to the /repair or /repair all

### ISSUE THREAD

**Issue by jere62smi** [EssentialsX/Essentials#2254]
Hello, Even if I know that EssentialsX is not yet completely in 1.13.X, can you tell me if this is a bug and/or not yet added but the turtle helmet and the trident are not fix with /repair or /repair all.
I'm using the latest version of EssentialsX available on Jenkins and I'm using one of the latest versions of Paper 1.13.2

**Comment by Remski01** [comment]
**We're missing the following lines. (Will remove it when you have added it.)**

### Information

**Full output of `/ess version`**:

```
<!-- Run the command in your console, and copy and paste the whole output here -->
```

**Server log**: 

**EssentialsX config**: 

### Details

**Description**  


**Steps to reproduce**  


**Expected behavior**  


**Screenshots**

**Comment by jere62smi** [comment]
[17:52:04] [Server thread/INFO]: Server version: 1.13.2-R0.1-SNAPSHOT git-Paper-387 (MC: 1.13.2)
[17:52:04] [Server thread/INFO]: EssentialsX version: 2.15.0.55
[17:52:04] [Server thread/INFO]: LuckPerms version: 4.3.2
[17:52:04] [Server thread/INFO]: Vault version: 1.7.1-b91

**Comment by Remski01** [comment]
Please use this builds: https://ci.ender.zone/job/EssentialsX-Experimental/

Those are builded against 1.13, the dev builds are builded against 1.12.2
ps: Please make sure you have the lastest version of PaperMC. For more 1.13.2 stable versions.

**Comment by mdcfe** [comment]
@jere62smi This should no longer be an issue in the latest dev builds - can you update to the latest [prerelease build](https://ci.ender.zone/job/EssentialsX-Experimental) and report back whether this is fixed?

**Comment by BBoyJD10** [comment]
its fixed

**Comment by mdcfe** [comment]
Closing as this has been fixed.
