### ISSUE TITLE
Essentials X /item & /enchant 

### ISSUE THREAD

**Issue by Ifriedmonkey** [EssentialsX/Essentials#2255]
have been searching for ages and I was seeing if you could help me out. Basically when a player uses /item I want it so that item says spawned in by (name) as a lore and so they can’t drop the item to the other players but can place the item and break it. Also the same with /enchant when a player enchants an item it has a lore and they can’t drop it. I’m not sure if this is a thing already and this is why I’m asking on assistance if you can help.

**Comment by kennyrkun** [comment]
this is not a feature in Essentials, and it probably shouldn't be. you should look into a separate plugin which overrides the Essentials /i(tem) and /enchant.

**Comment by mdcfe** [comment]
This is not within the scope of EssentialsX. As mentioned above, you should find an alternative plugin that overrides these commands.
