### ISSUE TITLE
Better /fix

### ISSUE THREAD

**Issue by WizzleBear** [EssentialsX/Essentials#2256]
### Feature request
Better /fix

**Feature description**

The command cost for /fix all should ignore the cost for /fix or have a permission to make /fix all cost nothing

**How the feature is useful**

Allows /fix to be more extensive, allowing ranks to have better features.

EDIT: Found out that repair-all doesn't work in the cooldown section, only repair. Can you also add a feature for that?

**Comment by Remski01** [comment]
Did you try to use regex? So far i know you then as example "/fix x" 40 and "/fix all" 50

**Note:** I cant confirm this works, but i pretty sure i saw something like this pass in the EssX support channel.

**Comment by WizzleBear** [comment]
I tried but it appears not. It may be because I am doing it wrong, but I have seen others have this issue before.

**Comment by mdcfe** [comment]
This is not something we intend to change. Use regular expressions as mentioned above to achieve this.
