### ISSUE TITLE
Wrong terracotta items.json alias

### ISSUE THREAD

**Issue by GiraffeCubed** [EssentialsX/Essentials#2258]
**Server log**: Not applicable

**EssentialsX config**: "terracotta": "white_terracotta"

### Details

**Description** 
In the 1.13 experimental builds:
"terracotta" gives "white_terracotta", it is a different item

**Steps to reproduce**  
Not applicable

**Expected behavior**  
"terracotta" should give the `terracotta` item, rather than `white_terracotta`

**Screenshots**  
Not applicable

**Comment by mdcfe** [comment]
Thanks for opening this issue. I've opened a corresponding issue over at md678685/essx-scripts#2.

**Comment by mdcfe** [comment]
I've fixed the `items.json` script - I'll update EssentialsX soon.
