### ISSUE TITLE
1.13+ command suggestion system

### ISSUE THREAD

**Issue by glorying16** [EssentialsX/Essentials#2259]
### Feature request

**Feature description**
So with the new 1.13+ command suggestions, it is only supposed to show a player commands that they have permission for. This, from what I have been able to understand, is done in the way the plugin.yml reads the commands with permissions. EssentialsX seems to be showing more than just what players have permission to. Im really hoping that we can get that changed so players dont have to sift through and figure out what they actually have permission to.

**Comment by ShaneBeee** [comment]
Okay so this was something I have seen many many people complaining about on Spigot. 
It was something I posted about on the Spigot resource page for EssentialsX
I decided to do a PR for it #2267 
There is some good news and bad news for this. See the PR for more info!

**Comment by mdcfe** [comment]
This was added in 8e4fc77244e198c6822cc97f3892a16e9a8b9a6b.
