### ISSUE TITLE
/heal * & /feed * works without perm

### ISSUE THREAD

**Issue by Pdani001** [EssentialsX/Essentials#2260]
### Information

**Full output of `/ess version`**:

```
Server version: 1.12.2-R0.1-SNAPSHOT git-Spigot-3d850ec-809c399 (MC: 1.12.2)
EssentialsX version: 2.15.0.52
EssentialsXChat version: 2.15.0.52
EssentialsXSpawn version: 2.15.0.52
```

### Details

**Description**  
When running /heal * or /feed *, players without the essentials.heal/feed.others permission can run the command too.

**Steps to reproduce**  
1. Run command /heal * or /feed * with only the essentials.heal/feed permission

**Expected behavior**  
Players can only heal themselves.

**Comment by mdcfe** [comment]
You are not running a supported permissions plugin (if any at all?).

Please include a full startup log.

**Comment by Pdani001** [comment]
Oops, forgot to include it, I'm using LuckPerms with Vault:
```
LuckPerms version: 4.3.17
Vault version: 1.5.6-b49
```

**Comment by mdcfe** [comment]
Could you run `/ess debug`, replicate the failing permissions checks then post the console output?

**Comment by lantren** [comment]
try to run luckperms verbose 

"/lp verbose on"       from the console  , then try commands and observe the verbose output in the console
This will show you exactly why the permission was granted.  This would at least verify that  essentials.heal is allowing the essentials.heal.others and it's not some forgotten wildcard.

**Comment by mdcfe** [comment]
Closing due to lack of response from @Pdani001. If this is still a problem, feel free to respond and I'll reopen the issue.
