### ISSUE TITLE
Server crash after running /setjail and /jail

### ISSUE THREAD

**Issue by EOT3000** [EssentialsX/Essentials#2261]
I reported this to papermc but they said it was an essentials jail issue.

[20:17:02 INFO]: EssentialsX version: 2.15.0.45
https://gist.github.com/EOT3000/d03b96f633d66e97f5d8c5677340be41
Config of no significance

**Comment by mdcfe** [comment]
There is not enough information to provide any support.

[Fill out the issue template, following all the instruction provided.](https://github.com/EssentialsX/Essentials/issues/new?labels=&template=help.md)

**Comment by EOT3000** [comment]
I didn't change anything in the config that affected jails. Look: https://gist.github.com/EOT3000/53c591d5ff885395e0c810a51a94a1d3

**Comment by mdcfe** [comment]
Fill out a proper [support request](https://github.com/EssentialsX/Essentials/issues/new?labels=&template=help.md) or [bug report](https://github.com/EssentialsX/Essentials/issues/new?labels=&template=report-a-bug.md) as requested above.
