### ISSUE TITLE
Being able to break certain blocks?

### ISSUE THREAD

**Issue by Piqori** [EssentialsX/Essentials#2262]
Hi,
So I use WorldGuard but couldn't get it to do this, so I decided to turn to AntiBuild instead. I'd like players to be able to break the snow layers that fall in the world, but that's it. Just the snow layers as they have regions they own and are able to build in. I set the permission to the group: essentials.build.break.80 for snow and essentials.build.break.78 for snow layers but it doesn't work. Am I doing something wrong?
Thanks in advanced!

**Comment by mdcfe** [comment]
There is not enough information here to provide support.

Please fill out a [help request](https://github.com/EssentialsX/Essentials/issues/new?labels=&template=help.md), following the template and instructions provided.
