### ISSUE TITLE
1.13.X Spawner Conversion Issue

### ISSUE THREAD

**Issue by Tomographix** [EssentialsX/Essentials#2264]
### Information

**Full output of `/ess version`**:

```
16.11 18:45:47 [Server] INFO Server version: 1.13.2-R0.1-SNAPSHOT git-Paper-428 (MC: 1.13.2)
16.11 18:45:47 [Server] INFO EssentialsX version: 2.15.0.45
16.11 18:45:47 [Server] INFO LuckPerms version: 4.3.17
16.11 18:45:47 [Server] INFO Vault version: 1.6.1
16.11 18:45:47 [Server] INFO EssentialsXSpawn version: 2.15.0.45
```

https://gist.github.com/Tomographix/d0b9972ea9921a33829c5269cb9a5d45

### Details

**Description**  
Users placing spawners in 1.13 who are no OP turn into pig spawners.
OP users have no issues placing spawners of any type.
Users do have the permissions to place spawners including:
essentials.spawnerconvert.*
essentials.spawnerconvert

**Steps to reproduce**  
1. Summon a spawner: e.g. give {name} mob_spawner:99 1 name:&7&lIron_Golem_Spawner
2. Place spawner
3. Spawner is a pig

**Expected behavior**  
1. Summon a spawner: e.g. give {name} mob_spawner:99 1 name:&7&lIron_Golem_Spawner
2. Place spawner
3. Spawner is an iron golem one

**Comment by mdcfe** [comment]
Can you replicate this behaviour without EssentialsX installed?

In addition, can you try using the [experimental builds](https://ci.ender.zone/job/EssentialsX-Experimental)?

**Comment by Tomographix** [comment]
Tested without EssentialsX on, the spawner still turns into a pig.
Tested with latest experimental builds, spawner now places correctly! Thank you for fixing.
