### ISSUE TITLE
[HELP] /speed command won't work while flying!

### ISSUE THREAD

**Issue by Zipper213** [EssentialsX/Essentials#2268]
Hello, I can't do /speed for flying with essentials.  I've had this problem for all of today.  I do /speed 10 while flying, and I go at speed 1.  /speed 10 works for walking, but not flying.  I can fly, /speed 10, exit server, rejoin server, and I go speed 10, but when I stop flying then fly again, it's back to /speed 1.

I'm using Essentials 1.8. All other commands work except for /speed while flying.  /speed <1-10> doesn't work, not just /speed 10.

**Comment by mdcfe** [comment]
Please [fill out the appropriate template](https://github.com/EssentialsX/Essentials/issues/new/choose). There is not enough information for us to help.
