### ISSUE TITLE
Spawners Skipping BlockEntity

### ISSUE THREAD

**Issue by NoopyyGaming** [EssentialsX/Essentials#2270]
### Information

**Full output of `/ess version`**:

Server version: 1.8.8-R0.1-SNAPSHOT git-Spigot-21fe707-e1ebe52 (MC: 1.8.8)
EssentialsX version: 2.15.0.55
PermissionsEx version: 1.23.4
Vault version: 1.7.1-b91
 EssentialsXChat version: 2.15.0.55
 EssentialsXSpawn version: 2.15.0.55

https://gist.github.com/NoopyyGaming/d20ece1b2cad06d044e9690771fdc65e

https://gist.github.com/NoopyyGaming/0b26714911d9708935e6b8a9ed22e18a

### Details

**Description**  
I use the plugin SilkSpawners, and when users mined them with a SilkTouch pickaxe and after place it, i get this in console : Skipping BlockEntity with id

**Steps to reproduce**  
1. Giving myself a spawner with /ss give NoopyyGaming MobName 1
2. Place the spawners
3. WARN message in console about it

**Screenshots**  
![spawner](https://user-images.githubusercontent.com/33123515/48747180-b14f6f00-ec72-11e8-8b9a-ab5ec756d32f.PNG)

**Comment by mdcfe** [comment]
This is a vanilla message. You can safely ignore it.
