### ISSUE TITLE
/spawn crashes server 1.13.2

### ISSUE THREAD

**Issue by Arkobat** [EssentialsX/Essentials#2272]
The server crashes, whenever I use /spawn

### Information
Essential version:
```
21.11 18:20:44 [Server] INFO [18:20:44 INFO]: EssentialsXSpawn version: 2.15.0.1
21.11 18:20:44 [Server] INFO [18:20:44 INFO]: Vault version: 1.6.7-b${env.TRAVIS_BUILD_NUMBER}
21.11 18:20:44 [Server] INFO [18:20:44 INFO]: LuckPerms version: 4.3.17
21.11 18:20:44 [Server] INFO [18:20:44 INFO]: EssentialsX version: 2.15.0.1
21.11 18:20:44 [Server] INFO [18:20:44 INFO]: Server version: 1.13.2-R0.1-SNAPSHOT git-Paper-454 (MC: 1.13.2)
```

Server log:
https://gist.github.com/arkobat/3a7ddab5066ae63fcd7ccf64de30586c

Essential Config:
https://gist.github.com/arkobat/036803a98e472533bae571f4454e886a

How to reproduce
Change the spawn with /setspawn
Restart server
Type /spawn

**Comment by mdcfe** [comment]
Thanks for reporting this!

---

Can you reproduce this on [1.13.x experimental builds](https://ci.ender.zone/job/EssentialsX-Experimental)?

This seems to be linked to wider issues regarding config saving on 1.13+, possibly linked to the SnakeYAML upgrade.

**Comment by Arkobat** [comment]
Seems to work. I've reused my old config, where the problem was.
After I deleted it 3 times or so before, it was magically fixed as well.

When using the old config, and setting new spawn etc, it doesn't seem like the error occurs more.

**Comment by FuneralSuits** [comment]
This issue has now started happening to me, doing /spawn or /setspawn completely crashes the server

**Comment by Arkobat** [comment]
@FuneralSuits with the experimental build, or the regular?
The experimental fixed it for me.

**Comment by FuneralSuits** [comment]
I believe regular, I'm going to update to the experimental now and see if that solves it

**Comment by FuneralSuits** [comment]
@arkobat Just loaded it up using the most recent experimental build and it works great!
Thanks!
