### ISSUE TITLE
tppos @p

### ISSUE THREAD

**Issue by seema84** [EssentialsX/Essentials#2274]
Server version: 1.13.2-R0.1-SNAPSHOT git-Spigot-9b4b0a2-f489f0f (MC: 1.13.2)
EssentialsX version: dev-39.182
PermissionsEx version: 1.23.4
Vault version: 1.7.1-b91
EssentialsXChat version: dev-39.182

i cant use @p with tppos in commandblocks
output: player not found

example: /tppos @p 1 2 3 0 0

**Comment by Xeyame** [comment]
Looks like #2217

**Comment by BluePlastics** [comment]
For now I'd suggest using something like CommandHook or PsuedoCommands.

**Comment by mdcfe** [comment]
Closing as a duplicate of #2217.
