### ISSUE TITLE
Problem with UUID, help requested

### ISSUE THREAD

**Issue by TobiasDeBruijn** [EssentialsX/Essentials#2276]
### Information

Full output of `/ess version`:

Essentials reloaded TeamCity

**Server log:** https://gist.github.com/TheDutchMC04/0e632e7de5a1d66588088182708b464e

**EssentialsX config** https://gist.github.com/TheDutchMC04/b19bd8af665f814d552399c3108f8263

### Help request

**Problem**
I wrote a plugin using UUIDs, as soon as I add Essentials it stops functioning, no errors thrown though. 

**What I have tried**
Contacted some fellow plugin devs I know for help, they agreed my method of getting the UUID is ok and should work

**Plugin code:** https://gist.github.com/TheDutchMC04/273849761da5ba89fe674b97a001b287

**Comment by Xeyame** [comment]
You are not using essentialsX. Download it for your version (1.13.2) [here](https://ci.ender.zone/job/EssentialsX-Experimental/)

**Comment by TobiasDeBruijn** [comment]
Yup that fixed it, thanks!
