### ISSUE TITLE
1.13.2 only default chat format

### ISSUE THREAD

**Issue by MartinLaum** [EssentialsX/Essentials#2277]
### Information
Running 1.13.2 Bukkit
EssentialsX 2.15.0.55
EssentialsXchat 2.15.0.55
Vault
PermissionsEX a.k.a PEX

**[Server log](https://gist.github.com/neegripoiss/d7d27d05c18b476fec6f1f64ecab6f6f)**

**[EssentialsX config](https://gist.github.com/neegripoiss/1e9dc9d97059561f6be39fac96ad8814)** 

### Help request

**Problem**
Plugin only uses default chat format

**What I have tried**
Disabling and deleting the default format

**Screenshots**
![image](https://user-images.githubusercontent.com/27521368/48971728-32698600-f026-11e8-9ada-33c48b6a93a2.png)

**Comment by Xeyame** [comment]
Deleting would indeed make it default to that, what other plugins are you running (that may mess with chat). Also what is your config with the desired prefix? I also suggest using [These](https://ci.ender.zone/job/EssentialsX-Experimental/) buids for 1.13

**Comment by MartinLaum** [comment]
![image](https://user-images.githubusercontent.com/27521368/48972077-457f5480-f02c-11e8-93d8-adad93a717bd.png)
Current plugins that server loads and shown as green with /pl.
Prefix that I want is: '&7{PREFIX}&r{DISPLAYNAME}&7:&r {MESSAGE}'
pretty much looking like this(wo color): [Owner]UnknownSlav: blablabla
I'll try the 1.13 builds then write if it works.

**Comment by MartinLaum** [comment]
> Deleting would indeed make it default to that, what other plugins are you running (that may mess with chat). Also what is your config with the desired prefix? I also suggest using [These](https://ci.ender.zone/job/EssentialsX-Experimental/) buids for 1.13

The up above mentioned build has no effect and still plugin is showing default format and yes I did change the newer build's config.

**Comment by Xeyame** [comment]
It might be your factions plugin. If that is not changing chat, I can only suggest to check if you have latest vault and migrate to luckperms, as PEX is unsupported iirc

**Comment by MartinLaum** [comment]
Okay it was the factions plugin, but any hints as to what exactly should be changed in the factions plugin to avoid this problem?

**Comment by Xeyame** [comment]
Not sure, best would be to ask the factions author. Probably look in the config for something with chat or some file for it?

**Comment by MartinLaum** [comment]
Okay, will do but Thank You! for finding the problem.
