### ISSUE TITLE
Problems with /weather 

### ISSUE THREAD

**Issue by austriancoding1** [EssentialsX/Essentials#2279]
Hello!
My friends and I are making a Xmas-Server on the Bukkit Version 1.13.2. Now we want to let it snow the whole time. So we created a world with the biome: snowy mointains.
And we typed /weather storm. The console said that the weather is set to stormy, but nothing happened.
Are we using the command wrong or is it a bug?

**Comment by mdcfe** [comment]
There is not enough information to help. Please fill out the [appropriate issue template](https://github.com/EssentialsX/Essentials/issues/new/choose).
