### ISSUE TITLE
Suggestion: money pay alias for pay

### ISSUE THREAD

**Issue by EvilOlaf** [EssentialsX/Essentials#228]
Hey there,

just switched from iConomy to EssentialsX Eco and I miss the `/money pay` command.
EssentialsX uses `/pay` for transactions only. Since all my players are accustomed with `/money pay` for sending cash it would be nice to get this alias back.
I tried to fix this myself by using a 3rd party plugin to modify existing commands but had no luck for some reason.

I know that `/money` is used to check a players current balance but as it is very unlikely that the player called pay (this is actually a premium account oO) will join a server this would be no real issue as `/balance` could do the job too.

Thanks for reading.

Best regards
Olaf

**Comment by drtshock** [comment]
I don't see this happening. I would just try to get a command alias plugin working.
