### ISSUE TITLE
Obsolete entries in items.csv should be removed

### ISSUE THREAD

**Issue by Bobcat00** [EssentialsX/Essentials#2282]
### Information

**Full output of `/ess version`**:

```
Server version: 1.12.2-R0.1-SNAPSHOT git-Bukkit-acbc348 (MC: 1.12.2)
EssentialsX version: 2.15.0.1
LuckPerms version: 4.3.17
Vault version: 1.6.7-b${env.TRAVIS_BUILD_NUMBER}
EssentialsXChat version: 2.15.0.1
EssentialsXGeoIP version: 2.15.0.1
EssentialsXSpawn version: 2.15.0.1

```

### Details

**Description**  

items.csv has the following obsolete entries. They were from an April Fools joke in 2011, and were removed in version 1.7.2.  Also note that 95 is the ID for stained glass.  These entries should be removed from the items.csv.

```
lockedchest,95,0
lockchest,95,0
jokechest,95,0
```

**Comment by mdcfe** [comment]
Feel free to open a PR to remove these.

Edit for clarification: we don't intend to actively maintain the `items.csv` file any more as it is not used on 1.13+. These aliases are not in the 1.13 `items.json`.
