### ISSUE TITLE
Add "item damage" settings to EssentialsX Protect

### ISSUE THREAD

**Issue by ProblemsSender** [EssentialsX/Essentials#2284]
TNT at any types until now it already has block damage-player, damage-block, these are worked fine for me. Just need to add a feature called "TNT block damage-items"
It's good to see everybody raiding others player base, it makes Minecraft more realistic. But what if using TNT could destroy all that "reward" by mistake placing it next to item drop from chest when breaking it(mistake)??
This feature would be a term of essentials protect
tnt-itemdamage: true/false
tnt-minecart-itemdamage: true/false
creeper-itemdamage: true/false
witherskull-itemdamage: true/false
fireball-itemdamage: true/false
lava-itemdamage: true/false
(etc)
In fact it's worth swimming in lava pool if we could get back our value items without effect xD
Thanks.

**Comment by mdcfe** [comment]
I don't think these are all easily achievable with the Bukkit API, but it would be great if someone looked into this.

**Comment by latiku** [comment]
https://github.com/EssentialsX/Essentials/pull/2495 offers functionality for this, enjoy!
