### ISSUE TITLE
setwarp abc to land on "stripped birch log" incorrect positioning

### ISSUE THREAD

**Issue by smmmadden** [EssentialsX/Essentials#2286]
EDIT: I'm running with PaperSpigot 1.13.2 Build 473 with Essentials 2.15.0.52 on my production server and 2.15.0.55 on my test server - both results in the same.  If you have a /home set or /warp and use it to teleport, you'll end up in the block (but not take damage).  If you leave and issue a /back, you will end up in the block and start taking damage.

![image](https://user-images.githubusercontent.com/10309346/49351741-d7b5d700-f682-11e8-961b-e92b8e8de9fd.png)

If you are reporting a bug with commands or something else in-game, please include screenshots to help us diagnose the problem.
![image](https://user-images.githubusercontent.com/10309346/49351776-fae08680-f682-11e8-8641-2e986af212e3.png)
![image](https://user-images.githubusercontent.com/10309346/49351779-fe740d80-f682-11e8-944e-98e33fea9360.png)

**Description**  
Setting a Warp location to end up on top of a "stripped birch log" will teleport the player one block forward and one block down.  You're not stuck and can jump out of the block, but it shouldn't place you one block forward or one block below the setblock location.  It should the be the exact xyz being set.

**Steps to reproduce**  
I tried to place a carpet on top of the block over the stripped birch log and that had the same behavior.  I replaced the block below me and in front with cobblestone and while I was one block forward, I did not end up one block below.

Errors: None, no warning or anything, just the command showing in the log of /warp or /setwarp StevesHome.  I am using [EssentialsX Extras](https://www.spigotmc.org/resources/essentialsx-extras.23822/), so not sure if he's doing anything special. It's more a UI Inventory system to make it easier to select a warp location.  Thanks! -Steve

**Comment by mdcfe** [comment]
Could you update to the [latest experimental build](https://ci.ender.zone/job/EssentialsX-Experimental) to see whether the issue is present in 1.13 versions? This is not a guaranteed stable build, but teleport safety is updated to work with 1.13.

**Comment by smmmadden** [comment]
sure, I'll test it later today and provide an update on the results.  Thanks! -Steve

**Comment by smmmadden** [comment]
@md678685 - confirmed with dev-39.182, the teleporting is properly placing players "on top of" the stripped birch log.  
Are these warnings known issues that can be ignored for now or would you like a separate bug for them?  I did not reset any configuration files when going from 2.15.0.55 to dev39.182 in case that might be the problem.  -Steve
[11:57:25 INFO]: [EssentialsGeoIP] Enabling EssentialsGeoIP vdev-39.182*
[11:57:25 INFO]: [EssentialsGeoIP] This product includes GeoLite2 data created by MaxMind, available from http://www.maxmind.com/.
[11:57:25 INFO]: [EssentialsAntiBuild] Enabling EssentialsAntiBuild vdev-39.182
[11:57:25 ERROR]: [Essentials] Unknown item 10 in protect.alert.on-placement list.
[11:57:25 ERROR]: [Essentials] Unknown item 11 in protect.alert.on-placement list.
[11:57:25 ERROR]: [Essentials] Unknown item 46 in protect.alert.on-placement list.
[11:57:25 ERROR]: [Essentials] Unknown item 327 in protect.alert.on-placement list.
[11:57:25 ERROR]: [Essentials] Unknown item 327 in protect.alert.on-use list.
[11:57:25 ERROR]: [Essentials] Unknown item 10 in protect.blacklist.placement list.
[11:57:25 ERROR]: [Essentials] Unknown item 11 in protect.blacklist.placement list.
[11:57:25 ERROR]: [Essentials] Unknown item 46 in protect.blacklist.placement list.
[11:57:25 ERROR]: [Essentials] Unknown item 327 in protect.blacklist.placement list.
[11:57:25 ERROR]: [Essentials] Unknown item 327 in protect.blacklist.usage list.
[11:57:25 INFO]: [EssentialsSpawn] Enabling EssentialsSpawn vdev-39.182*

**Comment by mdcfe** [comment]
> ```java
> [11:57:25 ERROR]: [Essentials] Unknown item 10 in protect.alert.on-placement list.
> [11:57:25 ERROR]: [Essentials] Unknown item 11 in protect.alert.on-placement list.
> [11:57:25 ERROR]: [Essentials] Unknown item 46 in protect.alert.on-placement list.
> [11:57:25 ERROR]: [Essentials] Unknown item 327 in protect.alert.on-placement list.
> [11:57:25 ERROR]: [Essentials] Unknown item 327 in protect.alert.on-use list.
> [11:57:25 ERROR]: [Essentials] Unknown item 10 in protect.blacklist.placement list.
> [11:57:25 ERROR]: [Essentials] Unknown item 11 in protect.blacklist.placement list.
> [11:57:25 ERROR]: [Essentials] Unknown item 46 in protect.blacklist.placement list.
> [11:57:25 ERROR]: [Essentials] Unknown item 327 in protect.blacklist.placement list.
> [11:57:25 ERROR]: [Essentials] Unknown item 327 in protect.blacklist.usage list.
> ```

You need to update your AntiBuild and Protect config sections to use the new 1.13 [Bukkit Material enum names](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html#enum.constant.summary) instead of item IDs.

**Comment by smmmadden** [comment]
That did the trick.  Thanks @md678685
