### ISSUE TITLE
EssentialsX 1.13.1

### ISSUE THREAD

**Issue by Straikerinos** [EssentialsX/Essentials#2288]
Server version: 1.13.1

Plugin version: 2.15.0.55

Need help !
Plugin is not working fine !!
If i have trident (broken) and i send command /repair all
it say me anything to repair, but trident still broken..
Next.
I have big problem.. if i look to spawner and send command /spawner irongolem .. nothing do it only say me You must look to spawner...
 
Thanks for reapir this bugs.

No errors.

**Comment by StealWonders** [comment]
Duplicate of #2254

**Comment by mdcfe** [comment]
> If i have trident (broken) and i send command /repair all
> it say me anything to repair, but trident still broken..

As noted by @StealWonders, this is a duplicate of #2254.

> I have big problem.. if i look to spawner and send command /spawner irongolem .. nothing do it only say me You must look to spawner...

This is fixed in the 1.13 [experimental builds](https://ci.ender.zone/job/EssentialsX-Experimental).

**Comment by Straikerinos** [comment]
thanks!
