### ISSUE TITLE
[Essentials] Plugin Essentials v2.15.0.1 generated an exception while executing task 31

### ISSUE THREAD

**Issue by BlakeWrong** [EssentialsX/Essentials#2290]
### Information

**Full output of `/ess version`**:

```
05.12 14:23:00 [Server] INFO [14:23:00 INFO]: EssentialsXSpawn version: 2.15.0.1
05.12 14:23:00 [Server] INFO [14:23:00 INFO]: EssentialsXChat version: 2.15.0.1
05.12 14:23:00 [Server] INFO [14:23:00 INFO]: Vault version: 1.6.7-b${env.TRAVIS_BUILD_NUMBER}
05.12 14:23:00 [Server] INFO [14:23:00 INFO]: PermissionsEx version: 1.23.4
05.12 14:23:00 [Server] INFO [14:23:00 INFO]: EssentialsX version: 2.15.0.1
05.12 14:23:00 [Server] INFO [14:23:00 INFO]: Server version: 1.13.2-R0.1-SNAPSHOT git-Paper-474 (MC: 1.13.2)
```

**Server log**: https://gist.github.com/BTDubbzzz/0d5a5387f637e4590f3aa264982b7405#file-latest-log

**EssentialsX config**: https://gist.github.com/BTDubbzzz/4bcd75d4c3ce35a783e561f7462bd231

### Details

**Description**  
Essentials is creating an exception on startup. I know that it is essentials only because when I set essentials.jar.disable then there is no exception

**Steps to reproduce**  
This happened when I was running on spigot 1.13.1 out of nowhere (nothing specific caused it that I Know of), so I updated to paper-1.13.2 and it still gave the exception

**Expected behavior**  
No exceptions, I guess

**Screenshots**  
N/A

**Comment by kennyrkun** [comment]
NoSuchMethodError

Something isn't matching up quite how it should, have you tried running the server with only Essentials enabled?

Might have something to do with [this](https://github.com/EssentialsX/Essentials/blob/b8a8232bc3db6ce8ca52cfd66e5eabe010a7e1c5/Essentials/src/com/earth2me/essentials/storage/BukkitConstructor.java#L38)

**Comment by BlakeWrong** [comment]
So I just tried this and still got it to generate an exception from essentials. I disabled every plugin except essentialsX.jar   essentialsXchat.jar  and essentialsXSpawn.jar

**Comment by BlakeWrong** [comment]
OK! Definitely making progress. When I disabled essentialsXchat.jar and essentialsXspawn.jar there was no exception thrown

**Comment by BlakeWrong** [comment]
Alright I narrowed it down, and it's _definitely_ EssentialsXspawn.jar creating the issue. I'm wondering if it's fighting over multiverse to control players' spawns or maybe the file is corrupted. Either way, I'll upload the jar file in case anyone smarter than myself can look deeper into this. For now I think I'll just delete it, because I don't think I really need it anyway.

Well apparently I can't upload a .jar so, not sure what I should do

**Comment by mdcfe** [comment]
You're running a version of EssentialsX that is over 8 months old.

For 1.8.8-1.12.2, download the [latest stable version](https://ci.ender.zone/job/EssentialsX).

For 1.13.2+, download the [latest experimental version](https://ci.ender.zone/job/EssentialsX-Experimental).

**Comment by BlakeWrong** [comment]
Weird, I thought I had the most recent version. Thanks
