### ISSUE TITLE
do not take material in [trade]

### ISSUE THREAD

**Issue by andfont** [EssentialsX/Essentials#2294]
1.
12:00:29 INFO]: CONSOLE issued server command: /ess version
[12:00:29 INFO]: Server version: 1.13.1-R0.1-SNAPSHOT git-Spigot-f6a273b-a639ae4 (MC: 1.13.1)
[12:00:29 INFO]: EssentialsX version: 2.15.0.56
[12:00:29 INFO]: PermissionsEx version: 1.23.4
[12:00:29 INFO]: Vault version: 1.7.1-b91
[12:00:29 INFO]: EssentialsXGeoIP version: 2.15.0.56
[12:00:29 INFO]: EssentialsXChat version: 2.15.0.56
[12:00:29 INFO]: EssentialsXProtect version: 2.15.0.56
[12:00:29 INFO]: EssentialsXAntiBuild version: 2.15.0.56
[12:00:29 INFO]: EssentialsXSpawn version: 2.15.0.56
Version:  Essentials version 2.15.0.56
2.No records just do not take the materials well when you indicate it on the poster
3. It's not a performance problem
4.it is not this error
5.this is not the problem
**Description**  
there are many materials that you can not use for commercial, such as diorite among many others, it tells you that you do not have the material in the inventory but it is false if it is and there is no way to work it [only] with very few materials, It is a very SERIOUS mistake please fix!

**Steps to reproduce**  
crate wall and type example: [trade] $1 1 diorite:1    
but it happens in many materials

**Comment by mdcfe** [comment]
You are using a version of EssentialsX that does not support 1.13.x.

Can you replicate this when running an [experimental build](https://ci.ender.zone/job/EssentialsX-Experimental) with 1.13.x support?

In addition, update your server to 1.13.2.

**Comment by andfont** [comment]
It works worse because it does not allow ID's and they are needed for POSTERS! so the solution is worse, please can you make the ID's work for the trade posters? Thank you! it is very necessary and the only solution is the ID per theme of space, please I am not until the experimental version because the / give 276 etc. does not work. does not allow id, I need it to work in 2 ways for [TRADE] mainly thanks!

**Comment by mdcfe** [comment]
Item IDs don't exist in Minecraft 1.13 and above and it is impossible for EssentialsX 1.13 to support them. You should update your signs to use **item names** instead.

By "posters", are you referring to [`[trade]` signs](http://wiki.mc-ess.net/wiki/Sign_Tutorial#Trade_Sign)? They should accept item names (like `cobble` or `dsword`).

**Comment by andfont** [comment]
it is very difficult to use the short names people do not know how to use it and many believe that it does not detect them! please make a database! with ID's to be able to use ID please! I have done it for my plugins and it is perfectly possible to create a database with ID's, in this way it is much easier! Thank you! with the names is not practical!

**Comment by andfont** [comment]
it does not work either [BUY] takes out the money but does not give the item! super BUG!

**Comment by kennyrkun** [comment]
/itemdb will show you all the names for the item in your hand. this should make it easier for people to get the proper names on the signs

**Comment by andfont** [comment]
has the same problem many names do not fit in the poster of [trade] and other names we do not know what it is, users can not do the posters well! please make it possible to use the id's of the file: items.csv is very simple! you already have the base of dice now please that they can use the ID's that you have saved! that way it will work with names and the one that has problems by ID's thanks!

**Comment by kennyrkun** [comment]
there are many different names you can use on signs. the only item I can think of whose name would not fit on a sign would be `redstone comparator`. but there are many names for this item which *do* fit on a sign, like `comparator`, `compare`, `comparer`, `rscompare`.

Item IDs should not be supported by Essentials if they have been removed from the game. If you *really* need IDs you should look into having a custom plugin made.

**Comment by mdcfe** [comment]
I intend to add a means to automatically convert item IDs to item name aliases, but item IDs will not be added back to the plugin as they do not exist in versions above 1.13 and there is no reliable way of mapping them to item names.

**Comment by andfont** [comment]
as I have command before you can use ID with a simple database that essences already has what is called items.csv, so it is really EASY! that can work and thus not have problems with users, the solution is very simple even if the 13 does not have essential ID can use them perfectly with the database items.csv that already has, so the solution is really simple and in this way I will not have more problems with USERS! I hope the PATCH thank you!

**Comment by mdcfe** [comment]
`items.csv` does **not** map item IDs to **1.13 item names**. It maps old Essentials(X) item names **to** old item IDs. The 1.13 server only understands **1.13 item names** and **not** item IDs. None of the data in items.csv means *anything* to the 1.13 server.

EssentialsX on 1.13 uses an entirely different item database called `items.json`. This maps **new EssentialsX item aliases** to **1.13 item names**. There is no guaranteed link between old and new EssentialsX names due to Minecraft and Spigot's internal technical changes as well as decisions made previously when updating the `items.csv` to previous versions of Minecraft. This means that even if we tried to use the old `items.csv` file for item IDs, most items would not have any ID at all, let alone the right one.

Other plugins can load the new flat item database with custom aliases (including ones that mimic item IDs) if they want, but EssentialsX will not be doing this.

**Comment by andfont** [comment]
it is perfectly possible to make a database compatible with all the versions and with little implementation work but you do not want to do it, ok then very badly! I do not agree, my users have many problems with short names! for the poster is a big problem where the solution is the GLOBAL database that can be done perfectly! but you do not want to do it. Well, having started with this information, I am already looking for other accessories that HAVE ECHO! thanks for nothing!. Greetings.

**Comment by mdcfe** [comment]
I think there's a problem with translation here.

The IDs in `items.csv` don't do anything in Spigot 1.13. **I am working on a way to convert IDs to names when you click on signs.** This will help people moving from 1.12 to 1.13.

If we make IDs work completely again, we will be stuck in the past with random numbers that don't exist any more.

IDs do not exist in 1.13 and will never exist again. Use item names.

**Comment by mdcfe** [comment]
In the [latest experimental build](https://ci.ender.zone/job/EssentialsX-Experimental), you can now set `allow-old-id-signs` to `true` in `config.yml`. This allows you to interact with existing `[trade]` signs that were created previously with item IDs. (You cannot create new signs with item IDs.)
