### ISSUE TITLE
[BUG] Riding an entity for hundreads of blocks then teleporting kills you will fall daange

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#2298]
### Information

```
This server is running Paper version git-Paper-1589 (MC: 1.12.2) (Implementing API version                     1.12.2-R0.1-SNAPSHOT)

2018-12-10 11:21:16 | CONSOLE issued server command: /ess version                                                          2018-12-10 11:21:16 | Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1589 (MC: 1.12.2)                                     2018-12-10 11:21:16 | EssentialsX version: 2.15.0.45
2018-12-10 11:21:16 | LuckPerms version: 4.3.2
2018-12-10 11:21:16 | Vault version: 1.6.6-b${env.TRAVIS_BUILD_NUMBER} 
2018-12-10 11:21:16 | EssentialsXChat version: 2.15.0.45
2018-12-10 11:21:16 | EssentialsXGeoIP version: 2.15.0.45
2018-12-10 11:21:16 | EssentialsXSpawn version: 2.15.0.45
```

**EssentialsX config**: https://gist.github.com/FrozenBeard/db053aef2677b9a2f822ec50d0e0c062

### Details

**Description**  
For over a year now this bug has existed, when people teleport they are being killed., my users have figured out its when you travel for hundreads of blocks on an entity and then do something like /home
For example sailing on a small boat. Some players think that the distance travelled incurs the amount of damage given to the player. 
A video with descriptive messages has been recorded by a player to demonstrate this bug. 
https://drive.google.com/file/d/1dqHxlnfOvAkGyCU3NW2L0aFwniGprKDV/view?usp=sharing

**Steps to reproduce**  
Sail on a boat for a few hundred blocks in gm 0, use /home, you die.

**Expected behavior**  
You should be teleported home without damage/death.

**Video**  
https://drive.google.com/file/d/1dqHxlnfOvAkGyCU3NW2L0aFwniGprKDV/view?usp=sharing

**Comment by mdcfe** [comment]
> ```
> 2018-12-10 09:28:21 | CONSOLE issued server command: /ess ver 
> ```

Please run `/ess version`.

---

This does not appear to be an EssentialsX issue - I imagine this is caused by Minecraft calculating the change in the `y` coordinate. Can you replicate this with vanilla teleportation commands and/or teleportation commands from other plugins?

**Comment by TomLewis** [comment]
@md678685 Update post with /ess version.

There only using Essentials TP commands, /home <name>, /tpahere etc
I will find out about the other teleports and update!

**Comment by pop4959** [comment]
I'm not able to replicate this issue at all in Paper 1.13.2. I followed the steps to reproduce (rode about 300 blocks in a boat, then used /home home) and I was completely fine.

Any updates, FrozenBeard?

**Comment by TomLewis** [comment]
@pop4959 Im not using 1.13.2 im using 1.12.2

**Comment by mdcfe** [comment]
> I will find out about the other teleports and update!

Did you test with other teleport commands in the end?

**Comment by pop4959** [comment]
@FrozenBeard I'm aware, was just wondering if you are still having this issue in 1.12.2. Also, updates as in what md quoted you as saying

**Comment by pop4959** [comment]
Closed due to lack of response and inability to confirm the bug. As md mentioned, this is also probably an issue in Minecraft itself and not fixable in Essentials.

I think getting off the entity before teleporting can also avoid this issue.
