### ISSUE TITLE
New /sleep command

### ISSUE THREAD

**Issue by mart-r** [EssentialsX/Essentials#2299]
### Feature request

**Feature description**
A `/sleep` command that starts a (potentially one-tick) sleep session

**How the feature is useful**
It would help get rid of those pesky phantoms, at least for a while.

**Comment by Xeyame** [comment]
Basically a command for reseting your sleep timer? Maybe `/reset-sleep` or whatever would fit for that better, but i'm not sure if this is something that should be included in essentials. You can probably find another plugin already doing that.

**Comment by mart-r** [comment]
There are commands such as `/heal` and `/feed`. I feel like this falls into the same "category".

Of course there are other possibilities. I just thought the users of this fine plugin might benefit from such a command.

**Comment by mdcfe** [comment]
I think a `/sleep` command would be ambiguous as there's not an easy way to figure out what it does from the name - does it make you instantly fall asleep? Does it make everyone fall asleep? In fact, I'd argue preventing phantoms isn't at all what I'd expect a command called `/sleep` to do.

I'm not opposed to this, but I agree with @Xeyame that it's probably better suited to another plugin.

**Comment by pop4959** [comment]
I'm not sure that this is easily possible, since as far as I know you actually need a valid bed location to [sleep](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/HumanEntity.html#sleep-org.bukkit.Location-boolean-) at. If it was possible though, maybe a name like "/rest" would be better, since it is setting your status to rested. I think the only way to add this might be hacky right now though.

**Comment by mart-r** [comment]
> I'm not sure that this is easily possible, since as far as I know you actually need a valid bed location to [sleep](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/HumanEntity.html#sleep-org.bukkit.Location-boolean-) at. If it was possible though, maybe a name like "/rest" would be better, since it is setting your status to rested. I think the only way to add this might be hacky right now though.

It's not all that difficult. All you need to do is [Player#setStatistic](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Player.html#setStatistic-org.bukkit.Statistic-int-) and set the [Statistic.TIME_SINCE_REST](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Statistic.html#TIME_SINCE_REST) to 0.

**Comment by pop4959** [comment]
Good to know, thank you for pointing that out!
