### ISSUE TITLE
Kit bug

### ISSUE THREAD

**Issue by Lunatik934** [EssentialsX/Essentials#2301]
### Information

**Full output of `/ess version`**:

```
Server version: 1.8.8-R0.1-SNAPSHOT git-Spigot-21fe707-e1ebe52 (MC: 1.8.8)
EssentialsX version: 2.15.0.57
PermissionsEx version: 1.23.4
Vault version: 1.7.1-b91
EssentialsXChat version: 2.15.0.57
EssentialsXProtect version: 2.15.0.57
EssentialsXSpawn version: 2.15.0.57
```

**Server log**: https://gist.github.com/Lunatik934/fb65227cd54ff29878f8cfc8ab48d798

**EssentialsX config**: https://gist.github.com/Lunatik934/e87a72b335a599c0416fc140208e2e85

### Details

**Description**  
When I use an kit, the kit name are not barred in the kits list

**Steps to reproduce**  

**Expected behavior**  

**Screenshots**  
https://www.youtube.com/watch?v=2go-3D1eDlw&feature=youtu.be

**Comment by Lunatik934** [comment]
Help

**Comment by Xeyame** [comment]
I don’t think this is a feature. However you did set skip-used-one-time-kits-from-kit-list: true in the config.yml, so is that what you mean as a bug (like it doens't hide them anymore)?

**Comment by kennyrkun** [comment]
I don' think `skip-used-one-time-kits-from-kit-list: true` will help because this looks like a 24-hour cooldown, not a one time use kit. The plugin is behaving exactly as intended, I belive.

**Comment by Lunatik934** [comment]
no.. the plugin have a bug test in ur server

**Comment by Lunatik934** [comment]
i want this  https://puu.sh/Cj24x/cc903bfca8.png

**Comment by kennyrkun** [comment]
that should only happen for kits which are one time uses. it looks like your kit has a 24-hour cooldown, rather than a one time use. try setting the cooldown to -1

**Comment by Lunatik934** [comment]
no ... I want 24heure with barred kit name in the /kit

**Comment by mdcfe** [comment]
Kit delays are broken, yes. I'm hoping to be able to look into this after the 1.13 work is finished off.

**Comment by Lunatik934** [comment]
Please fix quickly if you can :D

**Comment by mdcfe** [comment]
Despite several reports, I can't reproduce this on the latest build.

```
[13:05:38 INFO]: CONSOLE issued server command: /ess version
[13:05:38 INFO]: Server version: 1.14.2-R0.1-SNAPSHOT git-Paper-87 (MC: 1.14.2)
[13:05:38 INFO]: EssentialsX version: 2.16.1.211
[13:05:38 INFO]: Vault is not installed. Chat and permissions may not work.
```

Are you sure you don't have the permission `essentials.kit.exemptdelay`?

**Comment by mdcfe** [comment]
This has finally been fixed! You can download the latest version from the [download page](https://essentialsx.github.io/).
