### ISSUE TITLE
Ability to change swim speed with /speed

### ISSUE THREAD

**Issue by mdcfe** [EssentialsX/Essentials#2302]
### Feature request

**Feature description**
Allow `/speed swim` to change the speed of swimming in 1.13+.

**How the feature is useful**
Who needs flying or walking when you can *swim*!?

**Comment by pop4959** [comment]
Not sure that this is possible in the game currently. I don't think there is a player ability for swim speed, as there is for walking and flying. I did some investigation into this because I was curious whether it would be doable.

**Comment by caojohnny** [comment]
This is legitimately infeasible to do without modifying the client somehow, the server isn't really in control of the way the player moves; it only communicates player movement to the rest of the server. I can imagine somehow hacking this in using entity velocity or something, but I don't think it will look pretty.

**Comment by Xeyame** [comment]
The only way of controlling this from the server i could think of, would be giving the Dolphin’s Grace effect, although that doesn’t have any speed control that i know of

**Comment by ghost** [comment]
relatively hacky to do, we could listen for a `PlayerMoveEvent` then modify the player's velocity but it'd be pretty ugly

**Comment by pop4959** [comment]
yeah probably don't want to do that, there isn't an easy way to change this from the server without making it hacky, and it would probably be more work to maintain on essentials part

**Comment by pop4959** [comment]
Closing for now since this isn't feasible currently. Can consider it again if/when swimming speed is added as an ability that can be adjusted across the client/server.
