### ISSUE TITLE
/bigtree and /tree spawn

### ISSUE THREAD

**Issue by plagoutte** [EssentialsX/Essentials#2306]
### Information

**Full output of `/ess version`**:

```
>ess version
[21:29:36 INFO]: CONSOLE issued server command: /ess version
[21:29:36 INFO]: Server version: 1.11-R0.1-SNAPSHOT git-Spigot-f950f8e-0a81101 (MC: 1.11)
[21:29:36 INFO]: EssentialsX version: 2.15.0.57
[21:29:36 INFO]: PermissionsEx version: 1.23.4
[21:29:36 INFO]: Vault version: 1.5.6-b49
[21:29:36 INFO]: EssentialsXSpawn version: 2.15.0.1
[21:29:36 INFO]: Version mismatch! Please update all Essentials jars to the same version.
>
```

**Server log**: Nothing in relation with the issue

**EssentialsX config**: Tried on a "fresh" server without any config modification

### Details

**Description**  
When using `/tree` or `/bigtree` the tree won't spawn or spawn on an incorrect location.

**Steps to reproduce**  
_Issue 1_
-> Place a block of dirt in the void, then, below, 20 or more blocks or air and a block like bedrock or wood (where a tree can't spawn).
-> Point the top block of dirt, and try to spawn a tree

_Issue 2_
-> Place a block of dirt in the void, then, below, 20 or more blocks or air and a block of **dirt** (where a tree **can** spawn).
-> Point the top block of dirt, and try to spawn a tree

**Expected behavior**  
The tree may spawn on the top block of dirt, in the two cases.

**Real behavior**
1 : The tree doesn't spawn. Error : Big tree generation failure. Try again on grass or dirt.
2 : The tree spawns on **the lowest block of dirt**.

**Picture**
![](https://i.plagoutte.eu/index.php/s/r4Tdtz6b6fdQDnt/preview)
In the 3 cases, I used `/tree tree` command on the top dirt block. 
In the third case, it generated an error.

**Comment by plagoutte** [comment]
Update : picture added.

**Comment by mdcfe** [comment]
Thanks for opening a report and attaching the image, and apologies for the delay in responding to this.

It appears the command looks for the lowest block it can find with the same X and Z coordinates. I'm not sure why this behaviour is the case or if it's intended - we'd need to investigate how this works to figure out what the cause is.
