### ISSUE TITLE
Format money across the plugin

### ISSUE THREAD

**Issue by Terrobility** [EssentialsX/Essentials#231]
What is money formatting?
Without it: $1378987.23
With it: $1,378,987.23

There's already another plugin that formats money:
https://www.spigotmc.org/resources/1-8-vault-balance-formatter.9757/
But it only uses a custom /bal command. If essentials could add support for formatting money all throughout the plugin (e.g. /balance, /baltop, /sell and so on) that would be great.

**Comment by drtshock** [comment]
I suppose we could make https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/utils/NumberUtil.java#L16 configurable.
