### ISSUE TITLE
Overworld bed homes becoming obstructed because of Nether & End vanilla mechanics

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#2313]
### Information

**Full output of `/ess version`**:
Server version: `1.13.2-R0.1-SNAPSHOT git-Paper-485 (MC: 1.13.2)`
EssentialsX version: `2.16-pre1.11`
LuckPerms version: `4.3.17`
Vault version: `1.7.1-b91`
EssentialsXChat version: `2.16-pre1.11`
EssentialsXGeoIP version: `2.16-pre1.11`
EssentialsXSpawn version: `2.16-pre1.11`

**Server log**: Not necessary.

**EssentialsX config**: Not necessary.

### Details

**Description**  
Players can set bed homes in the Nether and End dimensions. The bed will instantly explode upon right-clicking it (Vanilla behavior) and the `/home bed` will become unusable. For an example: if a player uses beds to fight the Ender Dragon, they are prone to losing their `/home bed` since it will become obstructed upon the explosion.

__Expected behavior:__ `/home bed` can only be created in Overworld dimensions.

**Steps to reproduce**  
1. Place a bed in the Overworld.
2. Right-click the bed, creating `/home bed`.
3. Place a bed in the **Nether** or **End** dimension.
4. Right-click the bed.
5. The bed will explode, and `/home bed` will become obstructed.

Beds are generally used as a weapon outside of the Overworld.

**Expected behavior**  
`/home bed` can only be created in Overworld dimensions.

**Comment by triagonal** [comment]
I was able to reproduce this bug on a clean 1.13.2 Paper install with Essentials 2.16-pre1.25 and Vault 1.7.1.
```
[19:06:48 INFO]: CONSOLE issued server command: /ess version
[19:06:48 INFO]: Server version: 1.13.2-R0.1-SNAPSHOT git-Paper-485 (MC: 1.13.2)
[19:06:48 INFO]: EssentialsX version: 2.16-pre1.25
[19:06:48 INFO]: Vault version: 1.7.1-b${env.TRAVIS_BUILD_NUMBER}
[19:06:48 INFO]: EssentialsXSpawn version: 2.16-pre1.25
[19:06:48 INFO]: EssentialsXChat version: 2.16-pre1.25
[19:06:48 INFO]: EssentialsXGeoIP version: 2.16-pre1.25
```

The video below shows the creation and use of /home bed in the overworld, and then the creation and use of /home bed in the nether.

https://www.youtube.com/watch?v=v30pTDH8A0w
(at the end the chat is a slightly unreadable, but it gives the "Your bed is either unset, missing or blocked." error message)

Console output with /ess debug - https://hastebin.com/ofisaxahob.md
