### ISSUE TITLE
EssentialsX subsequent spawn location incorrect

### ISSUE THREAD

**Issue by smmmadden** [EssentialsX/Essentials#2314]
Using the EssentialsX Experimental builds (2.16-pre1.25) and PaperSpigot 1.13.2 Build 488 behind Waterball build 241 thru 243 (current).
![image](https://user-images.githubusercontent.com/10309346/50406791-2691f080-0799-11e9-8b89-75d59d50508c.png)
My spawnpoint for my world is set to the below for each user type:
![image](https://user-images.githubusercontent.com/10309346/50406799-47f2dc80-0799-11e9-9802-2c10c76149eb.png)
When I join the game the first time, I am spawned in the correct location.  However, if I exit and then rejoin after that, I get teleported underground and die.  Since I've been sent to the same spot repeatedly, I went into creative mode immediately and broke blocks around me to see where I ended up and it is 0 20 0 which is very odd since it isn't setup anywhere to do this.  Has something broke in the EssentialsXSpawn for the experimental builds of 2.16-pre1.11 or 2.16-pre1.25?  I'm able to reproduce in both.
![image](https://user-images.githubusercontent.com/10309346/50406814-b33cae80-0799-11e9-8bcb-fe0c2c906f4a.png)

I can also see in the console/logs that I'm logged in at ([world]0.0, 20.0, 0.0)
Let me know if you need to see any config files or can confirm if others see the same. -Thanks, Steve

**Comment by mdcfe** [comment]
Can you confirm that this doesn't occur when EssentialsXSpawn is not
present?

**Comment by smmmadden** [comment]
Yes I can confirm that renaming the EssentialsXSpawn.jar to .old **still** sends me to the spawn location in the image above (0,20,0).  I've deleted the playerdata file and the usercache.json file to ensure no cache was being used.

**Comment by smmmadden** [comment]
It's not Essentials afterall.  I went through all the config files and found that the latest update to WorldSystem reset the spawn point when leaving the private worlds and returning to the main world.  It was of course set to 0, 20, 0.  Once I updated it, I now go to the correct spawn point.

Apologies for not catching it on my end sooner. -Steve
