### ISSUE TITLE
What is this command and what it suppose to do?

### ISSUE THREAD

**Issue by ProblemsSender** [EssentialsX/Essentials#2317]
These are the commands I mention at the title, please help me clarify its function:
/jump lock
/kittycannon
/nuke
Thanks
*I already know /kittycannon and /nuke are related to explosion, but what kind of it? I used to heard a command that make a TNT rain

**Comment by mdcfe** [comment]
`/jump lock` makes you teleport whenever you click on a block.

`/kittycannon` fires (non-damaging) exploding kittens in the direction you are facing.

`/nuke` causes TNT to rain down from the sky around each player.

**Comment by kennyrkun** [comment]
the tnt dropped by `/nuke` has never been damaging on my server? I thought it wasn't supposed to do damage?

**Comment by ProblemsSender** [comment]
> `/jump lock` makes you teleport whenever you click on a block.
> 
> `/kittycannon` fires (non-damaging) exploding kittens in the direction you are facing.
> 
> `/nuke` causes TNT to rain down from the sky around each player.

Hello again, sorry for disturbing-but somehow /jump lock command hasn't work as intended, here's my ess versions
[14:04:41 INFO]: Server version: 1.12.2-R0.1-SNAPSHOT git-Spigot-dcd1643-e60fc34
 (MC: 1.12.2)
[14:04:41 INFO]: EssentialsX version: 2.15.0.57
[14:04:41 INFO]: PermissionsEx version: 1.23.4
[14:04:41 INFO]: Vault version: 1.6.7-b${env.TRAVIS_BUILD_NUMBER}
[14:04:41 INFO]: EssentialsXProtect version: 2.15.0.57
[14:04:41 INFO]: EssentialsXSpawn version: 2.15.0.57
[14:04:41 INFO]: EssentialsXChat version: 2.15.0.57
[14:04:41 INFO]: EssentialsXAntiBuild version: 2.15.0.57

Pls help me make this command to work, is this required some config to work? At first I thought that my problem is I didn't give my player a permissions to build.* - I added that and it still appear, what is the requirement to make this work? And additional question, can we use /jump lock instead of /jump?

**Comment by ProblemsSender** [comment]
@md678685 and essentials.pvpdelay.exempt, what it suppose to do? I can't find anything as "pvp_delay" in the config files, but the description said "Exempts players from the 'pvp delay' option in the config file."

**Comment by Xeyame** [comment]
It probably excempts you from the join or teleport PvP delay

**Comment by ProblemsSender** [comment]
> It probably excempts you from the join or teleport PvP delay

And the /jump lock? I can't use this command to right click teleport to block, and essentials.pvpdelay.exempt. As you said it definitely need to use luckperm timed permission to work right? I said that I can't find the exact "pvp_delay" or sort of that in the config file, if I add this permission to a player, does it mean he is protected by pvpdelay.exempt forever?

**Comment by mdcfe** [comment]
> It probably excempts you from the join or teleport PvP delay

Correct, this is what it does.

> Hello again, sorry for disturbing-but somehow /jump lock command hasn't work as intended

@ProblemsSender Please open and fill out a [support request](https://github.com/EssentialsX/Essentials/issues/new?template=help.md).
