### ISSUE TITLE
invalid selector/target for kill command

### ISSUE THREAD

**Issue by rjohnson98126** [EssentialsX/Essentials#2319]
running latest Spigot 1.13.2, latest EssentialsX release

```
[21:49:57 INFO]: Server version: 1.13.2-R0.1-SNAPSHOT git-Spigot-29ab5e4-2bc7d1d (MC: 1.13.2)
[21:49:57 INFO]: EssentialsX version: 2.15.0.59
[21:49:57 INFO]: LuckPerms version: 4.3.53
[21:49:57 INFO]: Vault version: 1.7.1-b91
[21:49:57 INFO]: EssentialsXProtect version: 2.15.0.59
[21:49:57 INFO]: EssentialsXChat version: 2.15.0.59
[21:49:57 INFO]: EssentialsXGeoIP version: 2.15.0.59
[21:49:57 INFO]: EssentialsXSpawn version: 2.15.0.59

```

i try to run a /kill command (either from the server console, or from a permission-granted admin player

```
>kill @e[type=skeleton,distance=..99]
[21:38:46 INFO]: CONSOLE issued server command: /kill @e[type=skeleton,distance=..99]
[21:38:46 INFO]: Error: Player not found.

>kill @e[type=minecraft:skeleton]
[21:39:43 INFO]: CONSOLE issued server command: /kill @e[type=minecraft:skeleton]
[21:39:43 INFO]: Error: Player not found.
```

there is apparently something wrong with Essentials kill understanding the vanilla @e selector.   i am aware that the command /minecraft:kill will behave properly, however because of other plugin dependencies upon Essentials, Essentials kill must work properly.

**Comment by triagonal** [comment]
The Essentials `/kill` command can only be used on players. The command that would be best suited to what you'd want is the Essentials `/remove` command (aliases `/butcher`, `/killall`). The `/remove` command can take all entities as arguments, and optionally mob type, radius, and world. 

`/kill @e[type=minecraft:skeleton]` becomes `/remove skeleton` (ingame)
`/kill @e[type=skeleton,distance=..99]` becomes `/remove skeleton 99` (ingame)

When executing the command from the console, you need to specify a world name. To kill all the skeletons in a world named "my_world", you would use `remove skeleton my_world`.

Also, if I'm not mistaken (and it hasn't already been fixed), Spigot builds for 1.13+ don't support selectors in plugin commands anymore. This means that any non-vanilla command won't be able to use selectors like `@e, @a` etc. You can attempt to bypass this using utility plugins like [PsudoCommands](https://www.spigotmc.org/resources/psudocommands-add-the-function-to-plugin-commands.56738/).

**Comment by mdcfe** [comment]
Thanks @triagonal for the detailed response.

@rjohnson98126 If you have any further queries, feel free to respond to this, but if your issue is solved, could you close the issue?

**Comment by rjohnson98126** [comment]
my issue isnt solved, but i guess it's not something that essentials is doing.   it's either in spigot 1.13.2 or vanilla mc problem with the /execute command.   im so frustrated lol, but okay i'll close this.
