### ISSUE TITLE
2 createkit issues

### ISSUE THREAD

**Issue by cloakfox** [EssentialsX/Essentials#232]
First issue is with splash potions, after grabbing those from my creative inventory and using the /createkit test 10 (10seconds duh) Splash potions return normal drinkable potions when using /kit test

Second issue is with colored leather armor also with the /createkit command after setup it returns "That kit is improperly defined. Contact and administrator."

Here are both kits in the config file: http://pastebin.com/iV34Rd2E

**Comment by drtshock** [comment]
Which build are you using?

**Comment by cloakfox** [comment]
http://imgur.com/lZCWHDc

**Comment by cloakfox** [comment]
I am using latest jenkins build..

**Comment by SupaHam** [comment]
Please separate your issues next time. 
Regarding the former issue, I've tested out and have confirmed that the command does infact generate non-splash potions. I will try to look into this.

Regarding the latter issue, I'm going to have to ask you to try once more regarding the coloured leather armor. I have tested it and it works.

Please try setting your `unsafe-enchantments` property to true like so `unsafe-enchantments: true`. Also when it says "That kit is improperly defined. Contact and administrator.", be sure to check the console and give information about that. In case it was an issue of unsafe-enchantments the issue with the `Vampire` kit should have been 

> [Essentials] Enchantment KNOCKBACK: Specified enchantment cannot be applied to this itemstack

**Comment by ItsCubeTime** [comment]
The `unsafe-enchantments: true` should be mentioned in the error message displayed when you have it disabled

**Comment by mbax** [comment]
Thank you for your contribution to this ticket closed *nine years ago*!
