### ISSUE TITLE
Phantoms Bypass /God on Spigot 1.13.2

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [EssentialsX/Essentials#2320]
### Information

**Full output of `/ess version`**:

```
28.12 00:42:48 [Server] INFO Server version: 1.13.2-R0.1-SNAPSHOT git-Spigot-82e117e-2b2d084 (MC: 1.13.2) 28.12 00:42:48 
[Server] INFO EssentialsX version: 2.15.0.57 28.12 00:42:48
[Server] INFO LuckPerms version: 4.3.17 28.12 00:42:48 
[Server] INFO Vault version: 1.7.1-b91 28.12 00:42:48 
[Server] INFO EssentialsXChat version: 2.15.0.57 28.12 00:42:48 
[Server] INFO EssentialsXSpawn version: 2.15.0.57
```

**Server log**: https://gist.github.com/pinkpig3777/79abae7caf6dfb3ea30fd5b11d2fe60e

**EssentialsX config**: https://gist.github.com/pinkpig3777/a0921ed63375a4c5e62522c7da0c7778

### Details

**Description**  
Phantoms can kill you when /god is enabled. 

**Steps to reproduce**  
1. Be on a 1.13.2 server
2. Don't sleep long enough for phantoms to spawn and attack you.
3. Enable /god.
4. Watch them kill you.

**Expected behavior**  
Phantoms shouldn't be able to damage / kill players that have /god enabled.

**Screenshots**  
N/A

**Comment by LaxWasHere** [comment]
@pinkpig3777 Could you reproduce this with the 1.13 [build](https://ci.ender.zone/job/EssentialsX-Experimental/) of EssentialsX?

**Comment by mdcfe** [comment]
From some unrelated 1.13 testing I did a couple of days ago, I don't recall this happening, but I'm not certain about this.

**Comment by mdcfe** [comment]
@pinkpig3777 Could you replicate this with just EssentialsX installed, preferably with a prerelease build?

**Comment by pop4959** [comment]
Unable to replicate this issue in recent versions of Paper/Essentials
[Short video of it working](https://gyazo.com/2a5322eb79b28684d47fa770c14cf182)

Edit: Noticed he's using 2.15, not 2.16. Probably an issue of being significantly out of date.

**Comment by mdcfe** [comment]
@pop4959 I couldn't replicate this on a recent (not latest) version of EssentialsX and Paper, and @triagonal couldn't replicate this on several combinations of EssentialsX and servers, including 2.15 (massive shoutout for helping investigate this btw).

**Comment by mdcfe** [comment]
Closing as this cannot be replicated.
