### ISSUE TITLE
EssentialsX Spawnmob Tnt Bug With 1.13.2 Spigot 

### ISSUE THREAD

**Issue by ProMan987** [EssentialsX/Essentials#2321]
Server Version: Spigot 1.13.2
Essentails Version: EssentialsX-2.15.0.59

Bug Description: When Using /tnt or /spawnmob they spawn on the palyer location not in the target location when his eyes looking . please fix!

**Comment by LaxWasHere** [comment]
Could you reproduce this with the 1.13 [build](https://ci.ender.zone/job/EssentialsX-Experimental/) of EssentialsX?

**Comment by ProMan987** [comment]
yes it worked thanks
