### ISSUE TITLE
Signs not Working

### ISSUE THREAD

**Issue by smokscreen145** [EssentialsX/Essentials#2323]
### Information

**Full output of `/ess version`**:

```
[03:47:00] [Server thread/INFO]: Server version: 1.8.8-R0.1-SNAPSHOT git-Spigot-21fe707-e1ebe52 (MC: 1.8.8)
[03:47:00] [Server thread/INFO]: EssentialsX version: 2.15.0.1
[03:47:00] [Server thread/INFO]: PermissionsEx version: 1.23.4
[03:47:00] [Server thread/INFO]: Vault version: 1.7.1-b91
[03:47:00] [Server thread/INFO]: EssentialsXProtect version: 2.15.0.1
[03:47:00] [Server thread/INFO]: EssentialsXChat version: 2.15.0.1
[03:47:00] [Server thread/INFO]: EssentialsXSpawn version: 2.15.0.1
```

https://gist.github.com/smokscreen145/a11aae4a66fe846449356401c372425c

https://gist.github.com/smokscreen145/885442515a0fa4fb3990143c5d413628

### Details

**Description**  
I don't have anywhere in my config to enable the signs. In-game, they don't work. (Buy, sell, etc.)

**Steps to reproduce**  
I tried to create a buy sign and when I did (followed correct format and double checked) nothing happened. I did some online research and most people were saying to enable signs in config but I don't have the signs part in my config.

**Expected behavior**  
I expected to have a normal, working buy sign.
**Screenshots**

**Comment by triagonal** [comment]
The config section that controls signs seems to have been removed, likely accidentally when your config file was edited. To restore functionality, you can add the following somewhere in your config file and uncomment the signs you want to use.
```
# Essentials Sign Control
# See http://wiki.ess3.net/wiki/Sign_Tutorial for instructions on how to use these.
# To enable signs, remove # symbol. To disable all signs, comment/remove each sign.
# Essentials colored sign support will be enabled when any sign types are enabled.
# Color is not an actual sign, it's for enabling using color codes on signs, when the correct permissions are given.

enabledSigns:
  #- color
  #- balance
  #- buy
  #- sell
  #- trade
  #- free
  #- disposal
  #- warp
  #- kit
  #- mail
  #- enchant
  #- gamemode
  #- heal
  #- info
  #- spawnmob
  #- repair
  #- time
  #- weather
```
You can find a clean copy of the default config file [here](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/config.yml).

**Comment by mdcfe** [comment]
Thanks for filling out a support request!

---

You appear to have a `config.yml` file that has been edited and saved by the old version of `/createkit`, removing all the instructions in the comments. You can add the `enabledSigns:` section to your config manually:
```
enabledSigns:
- buy
- color
- <whatever other signs you want here>
```

However, I'd recommend resetting your config by renaming `config.yml` to `config.yml.old` and running `/ess reload` in your server console. This will create a new `config.yml` file with all the instructions and sections that should normally be there.

**Comment by smokscreen145** [comment]
It worked out. Thank you.

**Comment by mdcfe** [comment]
Good to hear you solved this.
