### ISSUE TITLE
[Idea] /tempbanip command

### ISSUE THREAD

**Issue by voodootje0** [EssentialsX/Essentials#233]
Hey drtshock,

First nice that you have updated essentials <3

I have a idea for the ban commands, now you have /ban, /tempban and /banip.
But there is no /tempbanip, I hope you will add that command.

Thanks for reading it.
- voodootje0

**Comment by EvilOlaf** [comment]
https://github.com/drtshock/Essentials/issues/115

**Comment by drtshock** [comment]
duplicate of ^
