### ISSUE TITLE
Jail: Break Blocks Option

### ISSUE THREAD

**Issue by NotGeri** [EssentialsX/Essentials#2336]
### Feature request

**Feature description**

So, I'm a moderator on a server which has around 20-25 players online all the time. Recently we have problems with players stealing and such. Banning them wouldn't be fair, as they played a lot on the server and also payed in real life money. Everyone can get another chance! Our system would be to jail them and let them chop trees until we think they're OK to come back playing. Theres a /jail system in essentialsX, which is really helpfull, BUT players can not destroy blocks if they're in prison. My suggestion is: Add an option in the config.yml file, to turn on block breaking on and off while in jail. We'd protect the area with another plugin.

**How the feature is useful**

This would be usefull in a number of different jail designs, for example if an owner decidedes he wants people to dig an area or such.

**Comment by mdcfe** [comment]
Thanks for opening a feature request!

Out of interest, would bypass permissions work? For example, something like `essentials.jail.allow-break`. This could be more useful for servers that may want different users to have different abilities to break blocks. In contrast, config options would still let you turn this on or off, but aren't configurable per-player or per-group.

In addition, EssentialsX's jails feature is very simple, and I feel your use case may be better suited to a dedicated jail plugin, especially as I don't think most servers will need this. I'd be happy to hear from anyone else to the contrary, however.

**Comment by NotGeri** [comment]
Ohh thanks!! Yes a permission would work.

**Comment by latiku** [comment]
https://github.com/EssentialsX/Essentials/issues/2336 adds this functionality :)

**Comment by triagonal** [comment]
Separate permissions for breaking, placing, damaging, and interacting with blocks in jails have been added in dbc0562. See #2503 for the exact permission nodes.
