### ISSUE TITLE
Add delay to /r switching who to reply

### ISSUE THREAD

**Issue by Kakifrucht** [EssentialsX/Essentials#234]
It happens pretty often that mid chat somebody sends you a message right before / when you send yours, leading it to the wrong recipient. It would be nice if /reply would have like a 5 seconds period between somebody messaging the player and making him the person to reply to, to prevent this.

**Comment by EvilOlaf** [comment]
:+1:

**Comment by SupaHam** [comment]
I don't think a timed option would be ideal, unless it were to be one second tops, but I have another proposal. How about when you message a player that instantly becomes the recipient of your quick reply. No matter who messages you, in order for you to reply to them, you'll have to /msg your new recipient.

> **SupaHam: /msg Kakifrucht Hi**
> _SupaHam -> Kakifrucht: Hi_
> **Kakifrucht: /r Hi**
> _"Invalid usage"..._
> **Kakifrucht: /msg SupaHam Hi**
> _Kakifrucht -> SupaHam: Hi_
> **EvilOlaf: /msg Kakifrucht Hi**
> _EvilOlaf -> Kakifrucht: Hi_
> **Kakifrucht: /r Hi back to you!**
> _Kakifrucht -> SupaHam: Hi back to you!_

**Comment by Kakifrucht** [comment]
Well that would kinda defeat the fact that the command is called reply if you can only reply after having sent at least one direct message. I'm not sure whats the best take on this matter though.

**Comment by EvilOlaf** [comment]
I agree with @SupaHam that using time is not a good solution.

How about this:

```
SupaHam: /msg Kakifrucht Hi
SupaHam -> Kakifrucht: Hi
Kakifrucht: /r Hi
Kakifrucht -> SupaHam: Hi

EvilOlaf: /msg Kakifrucht Hi
EvilOlaf -> Kakifrucht: Hi
Kakifrucht: /r Hi back to you!
Kakifrucht -> SupaHam: Hi back to you!
```

The `r` stays at the first known user that messaged me. To solve this:

```
Kakifrucht: /msg EvilOlaf Hi back to you.
Kakifrucht -> EvilOlaf: Hi back to you!
```

This particular msg (could also be m,w,t,tell,wisp,whatever) will set a new last known user. 

However, regardless the final solution in this case, this option should be disableable to restore the old behaviour as some may like that more.

**Comment by Kakifrucht** [comment]
I actually do like EvilOlaf's idea.

**Comment by SupaHam** [comment]
#240

**Comment by Kakifrucht** [comment]
Works perfectly, thanks alot!

**Comment by EvilOlaf** [comment]
Nice

**Comment by Kakifrucht** [comment]
Suggestion for improvement:
Using this one day and came across a small issue. I was messaged by a player, whom I wanted to answer with /r, but since /r was locked to my old conversation parter, who was offline by then, it showed me that I have nobody I can reply to. Would this be possible to check if the player it "locked" to is still online, and if not, get the next best (in that case, the last person messaging me)?

**Comment by SupaHam** [comment]
I'll work on something in the upcoming days hopefully.

**Comment by drtshock** [comment]
Can you make a new ticket for that @Kakifrucht
