### ISSUE TITLE
Nickname per player

### ISSUE THREAD

**Issue by Olzie-12** [EssentialsX/Essentials#2340]

**Comment by kennyrkun** [comment]
You can't bypass by using colour codes if it ignores them.

**Comment by mdcfe** [comment]
EssentialsX doesn't allow users to change their nicknames to be the same as other online players' nicknames. Similar to several other issues, it isn't possible to protect offline players' nicknames without storing a separate copy of everyone's nicknames, and this is not something we intend to do.
