### ISSUE TITLE
Essentials blacklisted colours

### ISSUE THREAD

**Issue by Olzie-12** [EssentialsX/Essentials#2341]
### Feature request

**Feature description**

Make it in the config option so that some colour codes aren’t allowed in your nick
And it will say for the message ‘These current colour codes are banned: whatever’

**How the feature is useful**
 
So some colours look really awful ‘&1’ and ‘&0’ some players on my server really  don’t like that colour and sometime it can cause epilepsy or make it worse.

**Comment by Olzie-12** [comment]
### Feature request

**Feature description**

Make it in the config option so that some colour codes aren’t allowed in your nick
And it will say for the message ‘These current colour codes are banned: whatever’

**How the feature is useful**

**Comment by mdcfe** [comment]
Duplicate of #415 - please search before opening new issues.
