### ISSUE TITLE
What is this command and what it suppose to do?

### ISSUE THREAD

**Issue by ProblemsSender** [EssentialsX/Essentials#2344]
essentials.sleepingignored
*This seems buggy, while I can't place any block next to it and right click to it when I don't have this permission.

**Comment by kennyrkun** [comment]
The player is not required to be sleeping for time to be reset.

This means if the player has this permission, he does not need to be in a bed at night with all the other players in order for the time to be set to day.

**Comment by pop4959** [comment]
Closing since this question appears to be long already answered
