### ISSUE TITLE
EssentialsX Spawner Shop Signs Spigot 1.13.2

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [EssentialsX/Essentials#2347]
### Information

Full output of `/ess version`:
https://hasteb.in/jodocudu.css

**Server log:** https://gist.github.com/pinkpig3777/f8ccaef00d0b457b8f5e38bc40ac3119

**EssentialsX config** https://gist.github.com/pinkpig3777/995bdcda48e5faa1122eea72e208d623

### Help request

**Problem**
In EssentialsX for Spigot 1.12 and below, you could sell spawner types like so: https://gyazo.com/4b137ee416832fd0b4c5a1f89f1bbf58

How can you sell spawner types in the updated version of EssentialsX for Spigot 1.13? The method in the picture is broken. Please note: I'd like to sell spawner types, not spawn eggs.

**What I have tried**
- Changing the item id/name line to: "mob_spawner:3", "spawner:3", and "BlazeSpawner". None of which worked.

**Comment by mdcfe** [comment]
97cc3d00661664debfac791f06a6b94ee22c7907 and 4adb669cddf7bb57799864ffc3710db1f508da8e add support for spawners on 1.13+ - aliases such as `pigspawner` and `blazecage` are now recognised.

Edit: you can download EssentialsX 2.16.0.11 or newer from the [build server](https://ci.ender.zone/job/EssentialsX).

**Comment by PiggiesGoSqueal** [comment]
@md678685 It doesn't appear to be fixed. I used this EssentialsX build: https://ci.ender.zone/job/EssentialsX/lastStableBuild/

I tried the following sign setups:
https://gyazo.com/ce2552b41b18bc30d45194b6ff88b50c

**Comment by mdcfe** [comment]
Did you try typing the items in lowercase?

**Comment by PiggiesGoSqueal** [comment]
Yes, I just did. Still doesn't work. 

Now using the latest EssentialsX version (not the one before).
 /ess version: https://gyazo.com/8e16bc7c42712209e7e9c185e1b28f26

Also, it's somewhat unrelated but it is still regarding sign shops:
Oak sapling, birch sapling, acacia sapling, jungle sapling, and dark oak sapling buy & sell signs are broken. The buy signs will take money but not give any items. The only sapling signs that work are spruce

Sapling Sign Setups:
https://gyazo.com/c3d6cd6b03b532ede9b5af7729fbcc27
https://gyazo.com/e7b90a4e8adb96c70068268834b6f895

Edit: When I try to sell saplings it says "Error: You do not have 4x potted_dark_oak_sapling." so the issue is with potted vs normal saplings.

Edit 2: /i OakSapling, for example, doesn't work either.

Edit 3: /i Oak_Sapling works though and Oak_Sapling on the shop sign.

**Comment by mdcfe** [comment]
@pinkpig3777 Could you try deleting your `plugins/Essentials/items.json` file and recreating it? It seems like that file isn't getting updated automatically.

**Comment by PiggiesGoSqueal** [comment]
@md678685 Apologies for the late reply. That fixed it, thank you!

EDIT: skeletonspawner and SkeletonSpawner doesn't work. But blazecage does. So my issue has been fixed, but I'd still recommend adding those aliases or other people may create bug reports / have trouble.

**Comment by mdcfe** [comment]
Somehow I managed to miss the word "spawner" in all the aliases - I'll add these when possible. For now, you can use `skeletoncage` or similar.

**Comment by PiggiesGoSqueal** [comment]
@md678685 MooshroomCage doesn't work btw for spawner shop signs. All other mobs work though.

**Comment by mdcfe** [comment]
Seems like mooshroom spawners are completely missing from the items database - I'll fix this when I get an opportunity to.

**Comment by PiggiesGoSqueal** [comment]
Okay thanks. Also, prismarine crystals don't have an alias short enough to fit on a shop sign. Perhaps:
PrisCrystals?

**Comment by mdcfe** [comment]
@pinkpig3777 I believe all the issues raised here should be solved now. You can get the latest build from the [build server](https://ci.ender.zone/job/EssentialsX) - make sure you reset your `items.json`.
