### ISSUE TITLE
Broken "Sandstone" Sign Shop & Other Sign Shop Bugs

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [EssentialsX/Essentials#2348]
### Information

**Full output of `/ess version`**: https://hasteb.in/jodocudu.css

**Server log**: https://gist.github.com/pinkpig3777/f8ccaef00d0b457b8f5e38bc40ac3119

**EssentialsX config**: https://gist.github.com/pinkpig3777/995bdcda48e5faa1122eea72e208d623

### Details

**Description**  
1. First, "Sandstone" shop signs are broken. If you create a [Buy] sign with that then it'll give you smooth sandstone. Sign Setup: https://gyazo.com/4f929f3a9476aa7201b3f9b6b7e35552. Also, when I do /itemdb while holding a sandstone block it shows this msg/error in chat: https://gyazo.com/0a28e71561a4ade3107a9230889a97ef
2. Some aliases for blocks are messed up. "OakLog" used to work for Oak_Log items for shop signs. However, with the 1.13 update it will give stripped oak logs instead. It requires switching it to Oak_Log on the sign to work correctly. I recommend fixing that as it makes more sense for the alias "OakLog" to work for Oak_Log blocks. :P 
3. Some item names cannot fit on shop signs, even with their shortest aliases. It'd be nice if there were shorter alias options for those items. Two of the blocks I've come across with this issue are:
  - Lime Concrete Powder (Alias Ideas: LCPowder, LimeCPowder, LimeCP)
  - Gray Concrete Powder (Alias Ideas: GCPowder, GrayCPowder, GrayCP)
  - Enchanted Golden Apple (Alias Ideas: GodApple, NotchApple, EnchGodApple)

**Steps to reproduce**  
1. Use the EssentialsX version provided in the /ess version info above.
2. Create shop signs like the ones provided/described above.
3. Try to Buy/Sell from those signs.

**Expected behavior**  
The shop signs with certain aliases should give the proper block. Sandstone should also give sandstone instead of smooth sandstone.

**Comment by mdcfe** [comment]
Thanks for opening a bug report.

I can definitely replicate the `oaklog` issue - it appears there was a regression when generating the item alias list. In addition, I don't think we ever added shorter aliases for coloured concrete powder, so I've added that to a to-do.

I haven't yet had the opportunity to replicate the sandstone problem, hence the double tag - could anyone else try and replicate this?

You can see the status of the fixes at md678685/essx-scripts#3.

**Comment by triagonal** [comment]
I was able to replicate the sandstone problem (both the shop sign and /itemdb) using the following:
```
[17:47:40 INFO]: Server version: 1.13.2-R0.1-SNAPSHOT git-Paper-492 (MC: 1.13.2)
[17:47:40 INFO]: EssentialsX version: 2.16.0.3
[17:47:40 INFO]: Vault version: 1.7.1-b91
```
Console output with `/ess debug`:  https://hastebin.com/mifekehiqe.md
(spacing around ingame chat for better readability)

**Comment by mdcfe** [comment]
Thanks for opening an issue about these. I've addressed all of these concerns in 97cc3d00661664debfac791f06a6b94ee22c7907 - update to 2.16.0.5 or newer at [the build server](https://ci.ender.zone/job/EssentialsX/).

**Comment by PiggiesGoSqueal** [comment]
@md678685 Thank you, everything has been fixed **except** adding shorter enchanted god apple aliases.

Alias Ideas: GodApple, NotchApple, EnchGodApple

I updated to the latest EssentialsX version and deleted my plugins/Essentials/items.json file.

/ess version: https://gyazo.com/1bcee274449128528a09a9277ddfa1dc

**Comment by mdcfe** [comment]
I'll reopen this until I've added new golden apple aliases.

**Comment by Blatower21** [comment]
A similar problem happens with the mossy_cobblestone, all aliases (mcobble,mosscobble,mosscobblestone,mosscstone and the others) give you mossy_cobblestone_wall so is not possible create a [Buy] sign that allow you buy mossy_cobblestone.

Another item that cant be in a sign is popped_chorus_fruit that the only aliase is poppedchorusfruit and neither fits in a sign.

fermented_spider_eye the same.
