### ISSUE TITLE
Can't use basic commands like /home /tp /list

### ISSUE THREAD

**Issue by ReikiLights** [EssentialsX/Essentials#235]
I have a new server and only OP can do everything successfully.  When I DeOP myself I get a message that I don't have permission.  I don't know what I'm missing here.  I'm trying to keep it simple for better troubleshooting.  Here's what I have in place.

CURRENT PLUGINS:
NoSwear
Essentials
Factions
MassiveCore
PermissionsEx
SimplifiedSpawns

CURRENT PERMISSIONS.YML FILE
schema-version: 1
groups:
  Member:
    default: true
    permissions:
    - modifyworld.*
    - essentials.home
    - essentials.warp
    - essentials.warps.*

I've tried with - essentials.home and without the dash now as above.  Neither makes a difference.  I tested code in http://yaml-online-parser.appspot.com/ to make sure code is without errors.
What am I doing wrong here?  I'm prepared to wipe all plugins and start over if necessary.

**Comment by EvilOlaf** [comment]
Sounds more like a permission issue rather than an issue with EssentialsX

**Comment by ReikiLights** [comment]
Yes it is, sine OP has no issue using Essentials commands. But I have problems using permissions to do anything.  I've seen many videos and samples but I must by typing something wrong and I have no idea.  For whatever reason I copied and pasted this again and rebooted the server and /home works now but warp doesn't.  I guess I just need to keep playing with it since no one on any forum can seem to help and they all just point fingers at least other.

**Comment by drtshock** [comment]
Not an issue with essentials. Sounds like not having permissions configured correctly.

**Comment by ReikiLights** [comment]
Yes you are correct.  Strangely after all the advice I've seen online saying "4 spaces to indent, no tabs" it turns out 4 spaces is incorrect.  I had to use 2 spaces and everything started working.  Not sure why my permissions.yml needed 2 spaces to indent each section when everyone else says 4 spaces, but that was the solution for me.  Thought I'd share incase anyone else having the same problem.
