### ISSUE TITLE
/enchant cause java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by robinstiege** [EssentialsX/Essentials#2351]
### Information

**Full output of `/ess version`**:

```
[21:32:54 INFO]: Server Version: 1.12.2-R0.1-SNAPSHOT git-Spigot-dcd1643-e60fc34 (MC: 1.12.2)
[21:32:54 INFO]: EssentialsX Version: 2.16.0.4
[21:32:54 INFO]: LuckPerms Version: 4.3.17
[21:32:54 INFO]: Vault Version: 1.7.1-b91
[21:32:54 INFO]: EssentialsXSpawn Version: 2.16.0.4
```

**Server log**: https://gist.github.com/StiegeRobin/7fd785025ef04402610b5285a943c114

**EssentialsX config**: https://gist.github.com/StiegeRobin/2f6447078b6c0cd898f0d693913df277

### Details

**Description**  
Enchanting items won't work.

**Steps to reproduce**  
1. Get an item
2. Try /enchant alldamage 1
3. See console error

**Comment by mdcfe** [comment]
Could you update to [2.16.0.6 or later](https://ci.ender.zone/job/EssentialsX) and see if this is resolved?

**Comment by robinstiege** [comment]
Yes, this fixed it. Thank you!

**Comment by mdcfe** [comment]
No worries - glad to hear this fixed the issue.
