### ISSUE TITLE
All players can see all warp names via command autocompletion

### ISSUE THREAD

**Issue by YanisBft** [EssentialsX/Essentials#2353]
### Information

**Full output of /ess version:**

Server version: 1.13.2-R0.1-SNAPSHOT git-Paper-493 (MC: 1.13.2)
EssentialsX version: 2.16.0.4
PermissionsEx version: 1.23.4
Vault version: 1.6.7-b${env.TRAVIS_BUILD_NUMBER}
EssentialsXChat version: 2.16.0.4
EssentialsXSpawn version: 2.16.0.4

### Details

**Description:** All players, including non-op players, can see the names of all the warps created via the command autocompletion system.

**Steps to reproduce:**
1. Create a warp (_/setwarp foo_)
2. Make sure non-op players don't have access to this warp
3. Connect to your server with a non-op account
4. Run **/warp** - _you don't see the warp foo in the list_
5. Type **/warp** in chat - _the command autocompletion shows the warp foo_

**Expected behavior:** When EssentialsX didn't support command autocompletion, the only way to see warp list was _/warp_, and the list appeared in the chat. Non-op players could not see the warps they don't have access to.
Now, the way above still work as expected, but the command autocompletion system allows non-op players to see all warp names.

**Screenshot:**
![image](https://user-images.githubusercontent.com/16228338/50724062-53be9700-10e7-11e9-81f7-ddcd9b3e147f.png)

EDIT: added steps to reproduce

**Comment by mdcfe** [comment]
This is fixed in bd8ef2a25d50fc6e0579ff7c66496a5cc196eda3 - download version 2.16.0.8 or later from the [build server](https://ci.ender.zone/job/EssentialsX).

**Comment by YanisBft** [comment]
Oh, already fixed! Thanks a lot!
