### ISSUE TITLE
Feature Request: Please allow for PAPI placeholders to be used in the MOTD.txt

### ISSUE THREAD

**Issue by axemwa** [EssentialsX/Essentials#2354]
### Feature request

**Feature description**

I suggest adding a feature that allows placeholderapi placeholders to be read from the motd.txt
**How the feature is useful**

Placeholders have many uses one of them could be that you want players that are in a certain rank appear in the MOTD, for highscores, which admins are online etc

**Comment by mdcfe** [comment]
This was in progress (see #1945), but hasn't been touched recently due to the complexity of implementing it. I think PlaceholderAPI integration may need to wait until we're ready to do larger work on message sending in general (which could also enable JSON formatting etc).

**Comment by axemwa** [comment]
ah ok should I close this then since one is already open?

**Comment by mdcfe** [comment]
I'd keep this open for now, since it's specifically for text files (rather than the whole plugin).

**Comment by axemwa** [comment]
Agreed :)

**Comment by pop4959** [comment]
Please follow and comment on #2391 to discuss how chat changes like this should be implemented in Essentials.
