### ISSUE TITLE
/clearinventory player item name not work 1.13.2

### ISSUE THREAD

**Issue by andris155** [EssentialsX/Essentials#2357]
### Information

**Full output of `/ess version`**:

```
05.01 21:06:29 [Server] INFO Server version: 1.13.2-R0.1-SNAPSHOT git-Paper-492 (MC: 1.13.2)
05.01 21:06:29 [Server] INFO EssentialsX version: 2.16.0.3
05.01 21:06:29 [Server] INFO LuckPerms version: 4.3.17
05.01 21:06:29 [Server] INFO Vault version: 1.7.1-b${env.TRAVIS_BUILD_NUMBER}
05.01 21:06:29 [Server] INFO EssentialsXGeoIP version: 2.16.0.3
05.01 21:06:29 [Server] INFO EssentialsXChat version: 2.16.0.3
05.01 21:06:29 [Server] INFO EssentialsXSpawn version: 2.16.0.3
```

**Server log**: 
I upload if need this.

**EssentialsX config**: 
https://pastebin.com/BxzYuWaX

### Details

**Description**  

/clearinventory player item name not work 1.13.2

**Steps to reproduce**  

1. place ender pearl to inventory
2. write /ci name ender_pearl
3. Ender pearl not cleared.

**Expected behavior**  

Clear item

**Screenshots**

**Comment by darbyjack** [comment]
Hey there,

I just tested myself and found out how to fix this. So you ALMOST have the command correctly. When you do `/ci <name> <item>` you also need to provide a number to it, so for example, I placed a single ender pearl in my inventory, and I did `/ci <name> ender_pearl 1` and it removed that ender pearl!

Hope this helps.

**Comment by kennyrkun** [comment]
Don't you think it should clear all the items of that type if no number is provided?

**Comment by andris155** [comment]
It works perfectly with the number. Thanks for help.
