### ISSUE TITLE
Typo in german language file

### ISSUE THREAD

**Issue by Phreag** [EssentialsX/Essentials#236]
Line 387&388 now:
seenOffline=\u00a76SSpieler\u00a7c {0} \u00a76ist \u00a74offline\u00a76 seit \u00a7c{1}\u00a76.
seenOnline=\u00a76SSpieler\u00a7c {0} \u00a76ist \u00a74online\u00a76 seit \u00a7c{1}\u00a76.

Correct:
seenOffline=\u00a76Spieler\u00a7c {0} \u00a76ist \u00a74offline\u00a76 seit \u00a7c{1}\u00a76.
seenOnline=\u00a76Spieler\u00a7c {0} \u00a76ist \u00a74online\u00a76 seit \u00a7c{1}\u00a76.

(Shows SSpieler instead of Spieler)

**Comment by Kakifrucht** [comment]
There are actually quite alot of small errors in the german translation file. Just extract it from the jar and correct the values.

**Comment by EvilOlaf** [comment]
And concern sharing your fixes ;)

**Comment by drtshock** [comment]
PR the fixes <3
