### ISSUE TITLE
Amount of Kits

### ISSUE THREAD

**Issue by FrezzCrisis** [EssentialsX/Essentials#2362]
### Feature request

**Feature description**
 
Command /kit (kit) (player) (amount), in (amount) would be the number of times the kit will be given to someone, this command would work to give several times a kit without having to use many times the command.

**How the feature is useful**

This command would be more useful for owners of servers, they would not have the need to create several kits that give more items. Example: If I have a kit called coupons (in the configuration it would only be a 1 coupon) and if I want to give 5 coupons to someone the command would be /kit coupons MarcusX 5

**Comment by mdcfe** [comment]
I don't see many people needing this. You can easily just press up to repeat the command, or you can set up an alias with `commands.yml` or a plugin to do this for you.
