### ISSUE TITLE
/mail /msg /r /ignore could be used on player's nick instead of username(suggestion)

### ISSUE THREAD

**Issue by ProblemsSender** [EssentialsX/Essentials#2368]
Player's nickname was just perks in essentials for a very long time since it's born, today it must be changed, to make it more useful even for securing player's profiles, it would be a term for nick like this
completely_mask_username: true/false
If true, any output of such commonly commands /mail, /r, /msg, /ignore will be required the exact nickname, no longer username is used. This was just the base command, some command as /tpa still required this
*How the feature is useful**
/ignore still output real username
/msg /mail still output when player use username instead of nickname
Just make it not possible for some raider to abuse, the username information is so fortuned for them to hacking
And this was not a brand new function, so this could be needed for EssentialsX
Thanks to EssentialsX developer

**Comment by mdcfe** [comment]
This is not what the word "nickname" means. A nickname is what you choose to be called, but it doesn't hide who you are.

There are probably very hacky plugins that will break **everything** to try and do what you described, but EssentialsX will not be rewriting half of the Minecraft server to do something that less than 1% of servers would ever bother to use.
