### ISSUE TITLE
fly safelogin

### ISSUE THREAD

**Issue by joeridukker** [EssentialsX/Essentials#2372]
I gave players with permission essentials.fly the permission essentials.fly.safelogin. However, players that logout out while in fly mode do not get their fly on login but fall down. This issue is caused my multiverse core plugin overriding essentialsx behaviour I think. Because when i added the permission mv.bypass.gamemode.Skyblock people ARE put in fly mode as it should be. Is there any way to fix this without having to give people this mv bypass permission. Because with this permission people can be put into creative in Skyblock when coming from a creative world

**Comment by Magnum97** [comment]
I could not replicate. My versions output: 

```
22.06 18:52:43 [Server] INFO This server is running Paper version git-Paper-1613 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
22.06 18:52:43 [Server] INFO You are 2 version(s) behind

22.06 18:53:14 [Server] INFO Plugin Information: Multiverse-Core
22.06 18:53:14 [Server] INFO - Version: 2.6.0-bUNKNOWN
22.06 18:53:14 [Server] INFO - Author(s): Rigby, fernferret, lithium3141, main--, dumptruckman
22.06 18:53:14 [Server] INFO - Status: Enabled

22.06 18:53:20 [Server] INFO Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1613 (MC: 1.12.2)
22.06 18:53:20 [Server] INFO EssentialsX version: 2.15.0.45
22.06 18:53:20 [Server] INFO LuckPerms version: 4.3.29
22.06 18:53:20 [Server] INFO Vault version: 1.7.2-b107
22.06 18:53:20 [Server] INFO EssentialsXGeoIP version: 2.15.0.45
22.06 18:53:20 [Server] INFO EssentialsXSpawn version: 2.15.0.45
```

**Comment by mdcfe** [comment]
@Magnum97 Thanks for testing this, but: 
> `2.15.0.45`

I seem to recall minor changes to safelogin since 2.15.x (could be wrong), so I'm not sure exactly whether this accurately reflects the state of the issue.

@Joeripoes Did you ever resolve this or is this still an issue?

**Comment by pop4959** [comment]
Create a new issue if this is still a problem on the latest version of Essentials, without running any other plugins. You should also fully complete the issue template (which gives us information required to look into the problem), and a way to reproduce it reliably.
