### ISSUE TITLE
Multihome Groups Cause Corrupt Config

### ISSUE THREAD

**Issue by Boastful1353** [EssentialsX/Essentials#2374]
### Information

**Full output of `/ess version`**:
[Thu, 10. Jan 2019 19:09:55 UTC INFO] CONSOLE issued server command: /ess version
[Thu, 10. Jan 2019 19:09:55 UTC INFO] Server version: 1.13.2-R0.1-SNAPSHOT git-Spigot-947a8e7-3a91182 (MC: 1.13.2)
[Thu, 10. Jan 2019 19:09:55 UTC INFO] EssentialsX version: 2.16.0.26
[Thu, 10. Jan 2019 19:09:55 UTC INFO] LuckPerms version: 4.3.17
[Thu, 10. Jan 2019 19:09:55 UTC INFO] Vault version: 1.7.1-b91
[Thu, 10. Jan 2019 19:09:55 UTC INFO] EssentialsXGeoIP version: 2.16.0.26
[Thu, 10. Jan 2019 19:09:55 UTC INFO] EssentialsXChat version: 2.16.0.26
[Thu, 10. Jan 2019 19:09:55 UTC INFO] EssentialsXSpawn version: 2.16.0.26
[latest.log](https://github.com/EssentialsX/Essentials/files/2746733/latest.log)

```
<!-- Run the command in your console, and copy and paste the whole output here -->
```

**Server log**: https://gist.github.com/marvinej/ebd2a19b616851419e7844268ed5f168

**EssentialsX config**: https://gist.github.com/marvinej/0a0223d67d962b1657da40a352c38889
### Details

**Description**  

**Steps to reproduce**  
Changed Sethome-Multiple from
sethome-multiple:
  default: 3
  vip: 5
  staff: 10

to

sethome-multiple:
  twohomes:2
  threehomes:3
  fivehomes: 5
  redstone: 10
  staff: 20

**Expected behavior**  
This used to work fine for having seperate home amounts on my server, but the latest update makes it so that doing this causes it to mark my config as corrupted and put the default config back in

**Screenshots**

**Comment by darbyjack** [comment]
Hey there,

I just tested myself and confirm that it works. One thing I noticed is that on the first two entries, you don't have a space between the `twohomes:2` where it should be `twohomes: 2`

I went ahead and recreated this so maybe you can just copy and paste it for your use:

```YAML
sethome-multiple:
  twohomes: 2
  threehomes: 3
  fivehomes: 5
  redstone: 10
  staff: 20

**Comment by Boastful1353** [comment]
that seems to have done the trick. That's strange that the parser didn't care before, then suddenly it was broken.
