### ISSUE TITLE
spawner only spawns friendly mobs

### ISSUE THREAD

**Issue by karlheidar** [EssentialsX/Essentials#2377]
Mob spawners aren't spawning any hostile mobs (except for the Iron Golem). I am seeing absolutely zero console errors so I don't know what to do.
EssentialsX-2.16.0.26.jar
Spigot-Paper-489 (1.13.2)

**Comment by Xeyame** [comment]
Maybe your game is set on peaceful? Are you using any other plugins?

**Comment by mdcfe** [comment]
You havent provided us with any useful information to help solve this.

Please fill out the [appropriate issue template](https://github.com/EssentialsX/Essentials/issues/new/choose), including the *actual output* of `/ess version` and a full server startup log.

**Comment by karlheidar** [comment]
13.01 02:23:10 [Multicraft] Starting server!
13.01 02:23:10 [Multicraft] Loaded config for "PaperSpigot-500"
13.01 02:23:10 [Server] INFO Patching original jar...
13.01 02:23:13 [Server] INFO System Info: Java 1.8 (OpenJDK 64-Bit Server VM 25.191-b12) Host:  Linux 3.10.0-957.1.3.el7.x86_64 (amd64)
13.01 02:23:13 [Server] INFO Loading libraries, please wait...
13.01 02:23:14 [Server] INFO 2019-01-13 02:23:14,166 main WARN Disabling terminal, you're running in an unsupported environment.
13.01 02:23:16 [Server] INFO Loaded 0 recipes
13.01 02:23:16 [Server] INFO Starting minecraft server version 1.13.2
13.01 02:23:16 [Server] INFO Loading properties
13.01 02:23:16 [Server] INFO Default game type: SURVIVAL
13.01 02:23:16 [Server] INFO This server is running Paper version git-Paper-500 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
13.01 02:23:16 [Server] INFO Server Ping Player Sample Count: 12
13.01 02:23:16 [Server] INFO Using 4 threads for Netty based IO
13.01 02:23:16 [Server] INFO Debug logging is disabled
13.01 02:23:16 [Server] INFO Generating keypair
13.01 02:23:17 [Server] INFO Starting Minecraft server on 0.0.0.0:25565
13.01 02:23:17 [Server] INFO Using epoll channel type
13.01 02:23:19 [Server] INFO [WorldEdit] Loading WorldEdit v7.0.0-beta-04;17f52cb
13.01 02:23:19 [Server] INFO [AntiCooldown] Loading AntiCooldown v1.0
13.01 02:23:19 [Server] INFO [GroupManager] Loading GroupManager vGMBuildVer (Phoenix)
13.01 02:23:19 [Server] INFO [PlaceholderAPI] Loading PlaceholderAPI v2.9.2
13.01 02:23:19 [Server] INFO [AdvancedBan] Loading AdvancedBan v2.1.5-RELEASE
13.01 02:23:19 [Server] INFO [WorldGuard] Loading WorldGuard v7.0.0-beta01;01dfebe
13.01 02:23:19 [Server] INFO [NetherBlock] Loading NetherBlock v2.0
13.01 02:23:19 [Server] INFO [TitleWelcomeMessage] Loading TitleWelcomeMessage v3.0.1
13.01 02:23:19 [Server] INFO [AdminChat] Loading Admin-Chat v1.4.4
13.01 02:23:19 [Server] INFO [ViaVersion] Loading ViaVersion v2.0.0-SNAPSHOT
13.01 02:23:19 [Server] INFO [ViaVersion] ViaVersion 2.0.0-SNAPSHOT is now loaded, injecting!
13.01 02:23:20 [Server] INFO [ViaVersion] Loading block mapping...
13.01 02:23:20 [Server] INFO [ViaVersion] Loading item mapping...
13.01 02:23:20 [Server] INFO [ViaVersion] Loading new tags...
13.01 02:23:20 [Server] INFO [ViaVersion] Loading enchantments...
13.01 02:23:20 [Server] INFO [ViaVersion] Loading sound mapping...
13.01 02:23:20 [Server] INFO [ViaVersion] Loading translation mappping
13.01 02:23:20 [Server] INFO [Vault] Loading Vault v1.7.1-b91
13.01 02:23:20 [Server] INFO [StaffPlus] Loading StaffPlus v3.2.8.2
13.01 02:23:20 [Server] INFO [ViaBackwards] Loading ViaBackwards v2.4.0-SNAPSHOT
13.01 02:23:20 [Server] INFO [MassiveCore] Loading MassiveCore v2.14.0
13.01 02:23:20 [Server] INFO [HawkEye] Loading HawkEye v1.7.2
13.01 02:23:20 [Server] INFO [Essentials] Loading Essentials v2.16.0.26
13.01 02:23:20 [Server] INFO [MineCordBot] Loading MineCordBot v2.2.5
13.01 02:23:20 [Server] INFO [LWC] Loading LWC v2.1.1-46e9fa0
13.01 02:23:20 [Server] INFO [ProtocolLib] Loading ProtocolLib v4.4.0
13.01 02:23:20 [Server] WARN [ProtocolLib] Detailed error reporting enabled!
13.01 02:23:20 [Server] WARN [ProtocolLib] Version (MC: 1.13.2) has not yet been tested! Proceed with caution.
13.01 02:23:20 [Server] INFO [TradePlus] Loading TradePlus v3.13
13.01 02:23:20 [Server] INFO [EssentialsChat] Loading EssentialsChat v2.16.0.26
13.01 02:23:20 [Multicraft] Skipped 11 lines due to rate limit (30/s)
13.01 02:23:20 [Server] INFO [Vault] Enabled Version 1.7.1-b91
13.01 02:23:20 [Server] INFO [ViaBackwards] Enabling ViaBackwards v2.4.0-SNAPSHOT*
13.01 02:23:20 [Server] INFO [MassiveCore] Enabling MassiveCore v2.14.0*
13.01 02:23:20 [Server] INFO [MassiveCore 2.14.0] === ENABLE START ===
13.01 02:23:20 [Server] INFO [MassiveCore 2.14.0] Loading Cachefile datas...
13.01 02:23:20 [Server] INFO [MassiveCore 2.14.0] Loading Onlineplayer datas...
13.01 02:23:20 [Server] INFO [MassiveCore 2.14.0] Loading Registry datas...
13.01 02:23:20 [Server] INFO [MassiveCore 2.14.0] Saving Cachefile...
13.01 02:23:21 [Server] INFO [MassiveCore 2.14.0] Setup of IdUtil took 32ms.
13.01 02:23:21 [Server] INFO [MassiveCore 2.14.0] Integration Activated IntegrationLiabilityAreaEffectCloud
13.01 02:23:21 [Server] INFO [MassiveCore 2.14.0] Integration Activated IntegrationVault
13.01 02:23:21 [Server] INFO [MassiveCore 2.14.0] === ENABLE COMPLETE (Took 909ms) ===
13.01 02:23:21 [Server] INFO [LWC] Enabling LWC v2.1.1-46e9fa0
13.01 02:23:21 [Server] INFO [LWC] Connecting to SQLite
13.01 02:23:22 [Server] INFO [ProtocolLib] Enabling ProtocolLib v4.4.0*
13.01 02:23:22 [Server] INFO [ProtocolLib] Started structure compiler thread.
13.01 02:23:22 [Server] INFO Preparing level "world"
13.01 02:23:22 [Server] INFO Reloading ResourceManager: Default, bukkit
13.01 02:23:22 [Server] INFO Loaded 524 recipes
13.01 02:23:22 [Server] INFO -------- World Settings For [world] --------
13.01 02:23:22 [Server] INFO Mob Spawn Range: 6
13.01 02:23:22 [Server] INFO Experience Merge Radius: 4.0
13.01 02:23:22 [Server] INFO Cactus Growth Modifier: 100%
13.01 02:23:22 [Server] INFO Cane Growth Modifier: 100%
13.01 02:23:22 [Server] INFO Melon Growth Modifier: 100%
13.01 02:23:22 [Server] INFO Mushroom Growth Modifier: 100%
13.01 02:23:22 [Server] INFO Pumpkin Growth Modifier: 100%
13.01 02:23:22 [Server] INFO Sapling Growth Modifier: 100%
13.01 02:23:22 [Server] INFO Beetroot Growth Modifier: 100%
13.01 02:23:22 [Server] INFO Carrot Growth Modifier: 100%
13.01 02:23:22 [Server] INFO Potato Growth Modifier: 100%
13.01 02:23:22 [Server] INFO Wheat Growth Modifier: 100%
13.01 02:23:22 [Server] INFO NetherWart Growth Modifier: 100%
13.01 02:23:22 [Server] INFO Vine Growth Modifier: 100%
13.01 02:23:22 [Server] INFO Cocoa Growth Modifier: 100%
13.01 02:23:22 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
13.01 02:23:22 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
13.01 02:23:22 [Server] INFO Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
13.01 02:23:22 [Server] INFO Random Lighting Updates: false
13.01 02:23:22 [Server] INFO Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
13.01 02:23:22 [Server] INFO Max TNT Explosions: 100
13.01 02:23:22 [Server] INFO Tile Max Tick Time: 1000ms Entity max Tick Time: 1000ms
13.01 02:23:22 [Server] INFO View Distance: 4
13.01 02:23:23 [Multicraft] Skipped 72 lines due to rate limit (30/s)
13.01 02:23:23 [Server] INFO WEPIF: Vault detected! Using Vault for permissions
13.01 02:23:23 [Server] INFO [AntiCooldown] Enabling AntiCooldown v1.0*
13.01 02:23:23 [Server] INFO Das Plugin wurde aktiviert.
13.01 02:23:23 [Server] INFO [GroupManager] Enabling GroupManager vGMBuildVer (Phoenix)
13.01 02:23:23 [Server] INFO GroupManager - INFO - World Found: world
13.01 02:23:23 [Server] INFO GroupManager - INFO - Superperms support enabled.
13.01 02:23:23 [Server] INFO GroupManager - INFO - Scheduled Data Saving is set for every 10 minutes!
13.01 02:23:23 [Server] INFO GroupManager - INFO - Backups will be retained for 24 hours!
13.01 02:23:23 [Server] INFO GroupManager version GMBuildVer (Phoenix) is enabled!
13.01 02:23:23 [Server] INFO WEPIF: GroupManager detected! Using GroupManager for permissions.
13.01 02:23:23 [Server] INFO [Vault][Permission] GroupManager hooked.
13.01 02:23:23 [Server] INFO [Vault][Chat] GroupManager - Chat hooked.
13.01 02:23:23 [Server] INFO [PlaceholderAPI] Enabling PlaceholderAPI v2.9.2
13.01 02:23:23 [Server] INFO [PlaceholderAPI] Placeholder expansion registration initializing...
13.01 02:23:23 [Server] INFO [PlaceholderAPI] Fetching available expansion information...
13.01 02:23:23 [Server] INFO [AdvancedBan] Enabling AdvancedBan v2.1.5-RELEASE*
13.01 02:23:24 [Server] INFO []=====[Enabling AdvancedBan]=====[]
13.01 02:23:24 [Server] INFO | Information:
13.01 02:23:24 [Server] INFO |   Name: AdvancedBan
13.01 02:23:24 [Server] INFO |   Developer: Leoko
13.01 02:23:24 [Server] INFO |   Version: 2.1.5-RELEASE
13.01 02:23:24 [Server] INFO |   Storage: HSQLDB (local)
13.01 02:23:24 [Server] INFO | Support:
13.01 02:23:24 [Server] INFO |   Skype: Leoko33
13.01 02:23:24 [Server] INFO |   Mail: Leoko4433@gmail.com
13.01 02:23:24 [Server] INFO |   Github: https://github.com/DevLeoko/AdvancedBan/issues
13.01 02:23:24 [Server] INFO |   Discord: https://discord.gg/ycDG6rS
13.01 02:23:24 [Server] INFO | Update:
13.01 02:23:24 [Multicraft] Skipped 68 lines due to rate limit (30/s)
13.01 02:23:24 [Server] INFO [Staff+] Staff+ has been enabled! Initialization took 50ms.
13.01 02:23:24 [Server] INFO [Staff+] Plugin created by Shortninja.
13.01 02:23:24 [Server] INFO [HawkEye] Enabling HawkEye v1.7.2*
13.01 02:23:24 [Server] INFO [HawkEye] Starting HawkEye 1.7.2 initiation process...
13.01 02:23:24 [Server] INFO [HawkEye] Searching for updates..
13.01 02:23:24 [Server] INFO [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Starting...
13.01 02:23:24 [Server] WARN [HawkEye] Could not reach BukkitDev file stream for update checking. Is dev.bukkit.org offline?
13.01 02:23:24 [Server] INFO [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Start completed.
13.01 02:23:24 [Server] INFO [HawkEye] Version 1.7.2 enabled!
13.01 02:23:24 [Server] INFO [Essentials] Enabling Essentials v2.16.0.26
13.01 02:23:24 [Server] INFO [Essentials] Attempting to convert old kits in config.yml to new kits.yml
13.01 02:23:24 [Server] INFO [Essentials] No kits found to migrate.
13.01 02:23:24 [Server] INFO [Essentials] Using 1.8.3+ BlockStateMeta provider as mob spawner provider.
13.01 02:23:24 [Server] INFO [Essentials] Using 1.13+ flat spawn egg provider as spawn egg provider.
13.01 02:23:24 [Server] INFO [Essentials] Using 1.9+ BasePotionData provider as potion meta provider.
13.01 02:23:24 [Server] INFO [Essentials] Loaded 15457 items from items.json.
13.01 02:23:24 [Server] INFO [Essentials] Using locale en_US
13.01 02:23:24 [Server] INFO [Essentials] ServerListPingEvent: Spigot iterator API
13.01 02:23:24 [Server] INFO [Essentials] Starting Metrics. Opt-out using the global bStats config.
13.01 02:23:24 [Server] INFO [Vault][Economy] Essentials Economy hooked.
13.01 02:23:24 [Server] INFO [Essentials] Using Vault based permissions (GroupManager)
13.01 02:23:24 [Server] INFO [MineCordBot] Enabling MineCordBot v2.2.5*
13.01 02:23:24 [Server] INFO [TradePlus] Enabling TradePlus v3.13
13.01 02:23:25 [Server] INFO You appear to be running version 113
13.01 02:23:25 [Server] INFO [EssentialsChat] Enabling EssentialsChat v2.16.0.26
13.01 02:23:25 [Server] INFO [EssentialsGeoIP] Enabling EssentialsGeoIP v2.16.0.26
13.01 02:23:25 [Server] WARN [com.fasterxml.jackson.databind.ext.Java7Support] Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
13.01 02:23:25 [Server] INFO [EssentialsGeoIP] This product includes GeoLite2 data created by MaxMind, available from http://www.maxmind.com/.
13.01 02:23:25 [Server] INFO [EssentialsSpawn] Enabling EssentialsSpawn v2.16.0.26
13.01 02:23:25 [Server] INFO [BuycraftX] Enabling BuycraftX v11.0.0*
13.01 02:23:25 [Multicraft] Skipped 1 lines due to rate limit (30/s)
13.01 02:23:25 [Server] INFO [BuycraftX] Fetching all server packages...
13.01 02:23:26 [Server] INFO [Factions] Enabling Factions v1.6.9.5-U0.2.1-RC-1.6-BETA
13.01 02:23:26 [Server] INFO [Factions] [Factions v1.6.9.5-U0.2.1-RC-1.6-BETA] ==== Setup ====
13.01 02:23:26 [Server] INFO [Factions] [Factions v1.6.9.5-U0.2.1-RC-1.6-BETA] Minecraft Version 1.13 found, New Items will be used.
13.01 02:23:26 [Server] INFO [Factions] [Factions v1.6.9.5-U0.2.1-RC-1.6-BETA] Starting conversion of legacy material in config to 1.13 materials.
13.01 02:23:26 [Server] INFO File was not found for players.json, assuming there is no need to migrate old players.json file.
13.01 02:23:26 [Server] INFO [Factions] [Factions v1.6.9.5-U0.2.1-RC-1.6-BETA] ==== End Setup ====
13.01 02:23:26 [Server] INFO [Factions] [Factions v1.6.9.5-U0.2.1-RC-1.6-BETA] === ENABLE START ===
13.01 02:23:26 [Server] INFO [Factions] [Factions v1.6.9.5-U0.2.1-RC-1.6-BETA] Loaded 132 players
13.01 02:23:26 [Server] INFO [Factions] [Factions v1.6.9.5-U0.2.1-RC-1.6-BETA] Loaded 32 Factions
13.01 02:23:26 [Server] INFO [Factions] [Factions v1.6.9.5-U0.2.1-RC-1.6-BETA] Loading board from disk
13.01 02:23:26 [Server] INFO [Factions] [Factions v1.6.9.5-U0.2.1-RC-1.6-BETA] Loaded 0 board locations
13.01 02:23:26 [Server] INFO [Factions] [Factions v1.6.9.5-U0.2.1-RC-1.6-BETA] CoreProtect not found, disabling Inspect
13.01 02:23:26 [Server] INFO [Factions] [Factions v1.6.9.5-U0.2.1-RC-1.6-BETA] Enabling FactionsTop command, this is a very basic /f top please get a dedicated /f top resource if you want land calculation etc.
13.01 02:23:26 [Server] INFO [Factions] [Factions v1.6.9.5-U0.2.1-RC-1.6-BETA] Economy integration through Vault plugin successful.
13.01 02:23:26 [Server] INFO [Factions] [Factions v1.6.9.5-U0.2.1-RC-1.6-BETA] NOTE: Economy is disabled. You can enable it with the command: f config econEnabled true
13.01 02:23:26 [Server] INFO [Factions] [Factions v1.6.9.5-U0.2.1-RC-1.6-BETA] Minecraft Version 1.9 or higher found, using non packet based particle API
13.01 02:23:26 [Server] INFO .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-
13.01 02:23:26 [Server] INFO / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \
13.01 02:23:26 [Server] INFO `-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'
13.01 02:23:26 [Server] INFO You are using a BETA version of the plugin!
13.01 02:23:26 [Server] INFO This comes with risks of small bugs in newer features!
13.01 02:23:26 [Server] INFO For support head to: https://github.com/ProSavage/SavageFactions/issues
13.01 02:23:26 [Server] INFO .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-
13.01 02:23:26 [Server] INFO / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \
13.01 02:23:26 [Server] INFO `-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'
13.01 02:23:26 [Server] INFO [Factions] [Factions v1.6.9.5-U0.2.1-RC-1.6-BETA] Successfully registered placeholders with PlaceholderAPI.
13.01 02:23:26 [Server] INFO [Factions] [Factions v1.6.9.5-U0.2.1-RC-1.6-BETA] === ENABLE DONE (Took 712ms) ===
13.01 02:23:26 [Server] INFO [CombatLogX] Enabling CombatLogX v9.3.1.0
13.01 02:23:27 [Server] Startup Done (5.065s)! For help, type "help"
13.01 02:23:27 [Server] INFO Starting GS4 status listener
13.01 02:23:27 [Server] INFO Query running on 0.0.0.0:25565
13.01 02:23:27 [Server] INFO Timings Reset
13.01 02:23:27 [Server] INFO [ViaVersion] ViaVersion detected server version: 1.13.2(404)
13.01 02:23:27 [Server] WARN [ViaVersion] ViaVersion does not have any compatible versions for this server version, please read our resource page carefully.
13.01 02:23:27 [Server] INFO [Vault] Checking for Updates ... 
13.01 02:23:27 [Server] INFO [CombatLogX] Loaded 0 expansions
13.01 02:23:27 [Server] INFO [CombatLogX] CombatLogX is now enabled.
13.01 02:23:27 [Server] INFO GroupManager - INFO - Bukkit Permissions Updated!
13.01 02:23:27 [Server] INFO [net.dv8tion.jda.core.JDA] Login Successful!
13.01 02:23:27 [Server] INFO [MineCordBot] - Bukkit commands registered.
13.01 02:23:27 [Server] INFO [MineCordBot] - Plugin hooks registered.
13.01 02:23:27 [Server] INFO [MineCordBot] - Reporters registered.
13.01 02:23:27 [Server] INFO [MineCordBot] - Starting plugin framework initialization.
13.01 02:23:27 [Server] INFO [MineCordBot] - Module classes injected.
13.01 02:23:27 [Server] INFO [MineCordBot] - HelpTopics indexed.
13.01 02:23:27 [Server] INFO [MineCordBot] - Finished plugin framework initialization.
13.01 02:23:27 [Server] INFO [MineCordBot] - Initialized Minecraft listeners.
13.01 02:23:27 [Server] INFO [MineCordBot] - Successfully Hooked Essentials and now listening for events.
13.01 02:23:27 [Server] WARN [HawkEye] [!] Failed to initialize WorldEdit logging [!]
13.01 02:23:27 [Server] WARN [HawkEye] [!] Please upgrade WorldEdit to 6.0+       [!]
13.01 02:23:27 [Server] WARN [ViaVersion] You are running a development version, please report any bugs to GitHub.
13.01 02:23:27 [Server] INFO [Vault] No new version available
13.01 02:23:27 [Server] INFO [CombatLogX] Checking for updates using Spigot API...
13.01 02:23:28 [Server] INFO [net.dv8tion.jda.core.requests.WebSocketClient] Connected to WebSocket
13.01 02:23:28 [Server] INFO ==============================================
13.01 02:23:28 [Server] INFO CombatLogX Update Checker
13.01 02:23:28 [Server] INFO You are using the latest version!
13.01 02:23:28 [Multicraft] Skipped 1 lines due to rate limit (30/s)
13.01 02:23:28 [Server] INFO [BuycraftX] Fetching all due players...
13.01 02:23:28 [Server] INFO [PlaceholderAPI] 126 placeholder expansions are available on the cloud.
13.01 02:23:28 [Server] INFO [BuycraftX] Fetched due players (0 found).
13.01 02:23:29 [Server] INFO [net.dv8tion.jda.core.JDA] Finished Loading!

**Comment by karlheidar** [comment]
13.01 02:26:43 [Server] INFO Plugins (26): Admin-Chat*, AdvancedBan*, AntiCooldown*, BuycraftX*, CombatLogX, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, Factions, GroupManager, HawkEye*, LWC, MassiveCore*, MineCordBot*, NetherBlock*, PlaceholderAPI, ProtocolLib*, StaffPlus, TitleWelcomeMessage, TradePlus, Vault*, ViaBackwards*, ViaVersion*, WorldEdit, WorldGuard
