### ISSUE TITLE
[Request a feature] Withdraw money/exp

### ISSUE THREAD

**Issue by wingcwf** [EssentialsX/Essentials#2379]
### I hope add a built-in withdraw feature to make it easy for players to sell their experience at the auction. And adding maximum/minimum Withdraw quantities

Command:
withdraw -  Withdraws money onto a item
withdrawxp - withdraws experience onto a item

### The following is an example format:
  numbers:
    max-exp-withdraw: 30970
    max-money-withdraw: 1000000
    min-exp-withdraw: 7
    min-money-withdraw: 1

  banknote:
    signed:
      item: "PAPER:0"
      name: "&r&lBank Note &7(Right Click)"
      lore:
        - "&rValue &a${value}"
        - "&rWithdrawn by &7{signer}"
  bottle:
    signed:
      item: "EXP_BOTTLE:0"
      name: "&r&lEXP Bottle &7(Right Click)"
      lore:
        - "&rValue &7{value} EXP"
        - "&rWithdrawn by &7{signer}"

**Comment by Xeyame** [comment]
I don't think this is something that would be in the scope of EssentialsX. You can use a plugin like this for that: https://www.spigotmc.org/resources/moneynote-1-7-1-13-convert-money-into-moneynotes.59554/

**Comment by mdcfe** [comment]
You can already buy and sell experience through Essentials signs, but I agree with @Xeyame that this feature would be better served by another plugin like the one linked above.
