### ISSUE TITLE
Spectator mode not working

### ISSUE THREAD

**Issue by xXBarchticXx** [EssentialsX/Essentials#238]
Hi, spectator mode doesn't work when you do /gm or /gamemode. Nuff said

**Comment by SupaHam** [comment]
No, Nuff not said. The way this works is you tell us your issue, followed by some information to help us track down the issue. You go on to your server, you type `/ess reload` you give us the information given on the screen, then we get back to you regarding the "Nuff said" part.

**Comment by EvilOlaf** [comment]
Spectator mode works well with `/gm`. Maybe a permission issue.
Did you make sure that you read the wiki page about changes to Essentials carefully? 
If not, do so and you will be able to fix your problem by yourself.
https://github.com/drtshock/Essentials/wiki
