### ISSUE TITLE
Spectator sign won't work in essentialsx dev build 2.16.0.26

### ISSUE THREAD

**Issue by axemwa** [EssentialsX/Essentials#2383]
### Information

Full output of `/ess version`:

[00:40:48 INFO]: Server version: 1.13.2-R0.1-SNAPSHOT git-Paper-503 (MC: 1.13.2)
[00:40:48 INFO]: EssentialsX version: 2.16.0.26
[00:40:48 INFO]: LuckPerms version: 4.3.73
[00:40:48 INFO]: Vault version: 1.7.1-b91
[00:40:48 INFO]: EssentialsXGeoIP version: 2.16.0.26
[00:40:48 INFO]: EssentialsXChat version: 2.16.0.26

### Help request

**Problem**
When trying to use 

[Gamemode] 
Spectator 

on a sign and attempting to click on it causes a client error which says  Error: Line 2 on this sign is invalid.
There are no errors in console

**What I have tried**
as above

**Screenshots**

![image](https://user-images.githubusercontent.com/37608633/51391924-5909f000-1b83-11e9-9ae3-ec9b4dd3f3c0.png)

**Comment by darbyjack** [comment]
Thanks for pointing that out. I opened a PR to fix this.

**Comment by axemwa** [comment]
On an unrelated not should I open a new issue for this to update for material names? This below is in the default worth.yml but I thought data values are no longer used in 1.13? Not sure wat to do soz so thought I'd ask incase it's just something simple that I can fix

worth:

   Items not listed in this file will not be sellable on the server
   Setting the worth to 0 will sell items for free, delete the item or set to -1 to disable.

   This will set the worth of all logs to '2'
  log: 2.0  

   This will work similar to the above syntax
  wool:
    '0': 20
    
   This will only allow selling leaves with datavalue '0' and '1'
  leaves: 
    '0': 1.0
    '1': 1.0
    
   This will allow the selling of all, but sells '0' slightly cheaper  
  sapling:
    '0': 2.0  
    '*': 2.5

EDIT - Actually may have already found an issue about it, but it's been closed?
https://github.com/X00LA/Bukkit-Essentials-worth.yml/issues/4

**Comment by mdcfe** [comment]
Regarding the signs: this will be fixed once we merge @derbyjack's PR.

Regarding `worth.yml`: The issue you linked is for a custom `worth.yml` file made by someone else, not us. You can use material names on all versions, as well as IDs + durability on 1.12.2 and below.

**Comment by axemwa** [comment]
Cool thanx I'm using 1.13.2 I know u can use material names etc but the ID's wouldn't work in worth would it? If it doesn't do I have to replace ID's with Material names manually?

EDIT - Or did u mean that ID's will work in 1.13 for essentials worth?

**Comment by axemwa** [comment]
It fixed already? Thanx! :)
