### ISSUE TITLE
I can migrate from Essentials to EssentialsX?

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#2384]
Hi, i want to migrate from Essentials to EssentialsX, is possible without reconfigure all things?

**Comment by Xeyame** [comment]
As EssentialsX is a fork of the original essentials, you can try to just replace the jar iirc. Make sure to backup the Essentials directory as this isn't supported.

**Comment by mdcfe** [comment]
Xeyame's answer should be enough, but let us know if you need any further help.
