### ISSUE TITLE
Items Not Found 

### ISSUE THREAD

**Issue by tropicgbr** [EssentialsX/Essentials#2387]
Fixed

**Comment by Xeyame** [comment]
Download the latest version here: https://ci.ender.zone/job/EssentialsX/

**Comment by tropicgbr** [comment]
@Xeyame It still wont work, it still comes up with this
and when i do /kit {name} in game then it will say "That kit is improperly defined. Contact and administrator.

**Comment by Xeyame** [comment]
Could you do `/essentials version`? @tropicgbr

**Comment by tropicgbr** [comment]
2.16.0.3 is the version
@Xeyame

**Comment by Xeyame** [comment]
Was looking for the full output, one that also includes your server version :P, could you post that?

**Comment by tropicgbr** [comment]
oh, 1.12.2

**Comment by Xeyame** [comment]
Still not full console output, but whatever. The version for 1.8.8-1.12.x can be found here: https://ci.ender.zone/job/EssentialsX/664/

**Comment by tropicgbr** [comment]
Thank you, It is working now
