### ISSUE TITLE
Spawners spawn pigs I want the right essential Id

### ISSUE THREAD

**Issue by IIHERO4** [EssentialsX/Essentials#2389]
### Information

Sign shop all works except spawners , spawners I tried write it in blazecage or 52:<id> e.g 52:55 I don't know what I do now I want ids or solution.

**Comment by darbyjack** [comment]
Please fill out the template it asked you to fill out when you created the issue in order for us to help you.

**Comment by mdcfe** [comment]
Closing due to lack of response.
