### ISSUE TITLE
Request to allows players to be able to use color code for AFK messages  (&,bold,italic,underline etc) support

### ISSUE THREAD

**Issue by axemwa** [EssentialsX/Essentials#2390]
### Feature request

**Feature description**
Request/suggestion to allow players to be able to use color code (&,bold,italic,underline etc) for AFK messages with required permissions added

**How the feature is useful**
Why not, it's something cool, most other features have color code support and it shouldn't require much coding

**Comment by triagonal** [comment]
This is possible by editing your locale of `messages_<locale>.properties`.
For example, editing these strings in the [English locale](https://github.com/EssentialsX/Essentials/blob/827217823efc9965d68809761bddc5db94a84aad/Essentials/src/messages_en.properties#L566-568) will control the formatting of the AFK messages:

https://github.com/EssentialsX/Essentials/blob/827217823efc9965d68809761bddc5db94a84aad/Essentials/src/messages_en.properties#L566-L568

See the link below for more information on editing messages.
https://github.com/EssentialsX/Essentials/wiki/Locale

**Comment by axemwa** [comment]
Thanx but I meant for players to be able to color their AFK messages not the server owners default AFK colored messages, I have renamed the request for better understanding

**Comment by axemwa** [comment]
I also suggest adding a placeholder to PlaceholderAPI that outputs the AFK message the player has set (if they set one)

eg 

%essentials_afk_message%
Output= Coffee Break (depending on what player set as their AFK message)

**Comment by mdcfe** [comment]
We don't control the PlaceholderAPI placeholders - you may want to report that to the [Essentials Expansion issue tracker](https://github.com/PlaceholderAPI/Essentials-Expansion/issues).

I think this would be nice, but also I feel full colour formatting might be overkill for what is supposed to be a short and simple message. If players want to send coloured messages when they're going AFK, they can already use chat, so this doesn't feel completely necessary.

**Comment by axemwa** [comment]
K ill report to placeholderapi for that one then,
as for color codes ur right color code for message isnt neccesary but it does make it look more appealing and noticable to other players making it eaiser for the eyes in certain situations (eg: white afk msg in snowworld might be hard to read so players being able to change color code to something else like black would be more of a benefit to them more than the server itself)

**Comment by darbyjack** [comment]
Wouldn't this require someone to store extra data just to get their custom AFK mesasge?

**Comment by mdcfe** [comment]
@axemwa
> white afk msg in snowworld might be hard to read

I always thought the background of the chat box was dark enough 🤔

@darbyjack EssentialsX already stores custom AFK messages. This request is to have EssentialsX parse the colour codes before sending the message in chat or `/msg`.

**Comment by axemwa** [comment]
> 
> 
> @axemwa
> 
> > white afk msg in snowworld might be hard to read
> 
> I always thought the background of the chat box was dark enough thinking
> 
Actually that was a bad example, my bad. I guess a better example would be that sometimes a paragraph of chat might be the same color as the default AFK messeage color and because of that the players might miss another players afk message since it blends in, but if players could optionally change the color code of their message then it would be easier to tell what their afk message was

**Comment by axemwa** [comment]
@md678685 the "/afk (reason)" placeholder has been added to PlaceholderAPI
https://github.com/PlaceholderAPI/Essentials-Expansion/issues/9

**Comment by axemwa** [comment]
> 
> 
> Thanx but I meant for players to be able to color their AFK messages not the server owners default AFK colored messages, I have renamed the request for better understanding
>
> 
> I think this would be nice, but also I feel full colour formatting might be overkill for what is supposed to be a short and simple message. If players want to send coloured messages when they're going AFK, they can already use chat, so this doesn't feel completely necessary.

If you don't intend to add this then I'll close it. Thanx for replying either way
