### ISSUE TITLE
/Give or /Item Mob Spawner with ID

### ISSUE THREAD

**Issue by sOxTw** [EssentialsX/Essentials#2392]
### Information

Full output of `/ess version`: 2.15.0.1

**Server log:** It does not generate error logs.

**EssentialsX config** https://gist.github.com/sOxTw/47656fed2664ef1f6a1fdc56aa10670d

### Help request

**Problem**
I'm doing a menu of spawners, all by Skript. What I generate a **/give** with ID **52: #** the problem is that in version 1.12 I do not have the ids of the mobs of that version, could you provide them?
_Example /give% player% 52: 100 name: Lore_Horse Generator: Redeemed_by_% player%_

**What I have tried**
/give <player> mob_spawner 1 0 {EntityTag:{id:evoker}}
/give <player> mob_spawner 1 0 {EntityTag:{EntityId:evoker}}
and the / give% player% 52: **[ID EVOKER?]**

**Screenshots**
It is not necessary, I believe.

**Comment by mdcfe** [comment]
Please run the command `/ess version` and paste the full output - it looks like you didn't type it properly or didn't copy the full output.

You can find entity IDs for mobs at the [Minecraft wiki](https://minecraft.gamepedia.com/Java_Edition_data_values/Pre-flattening/Entity_IDs). To give a spawner with a specific mob, you would do `/give spawner:<ID>`, where the ID comes from the page above.
