### ISSUE TITLE
/skull broken on newest version of essx

### ISSUE THREAD

**Issue by SinlesFlyer376** [EssentialsX/Essentials#2397]
**Full output of `/ess version`**:
```
[INFO] CONSOLE issued server command: /essentials version
[INFO] Server version: 1.8.8-R0.1-SNAPSHOT git-Spigot-21fe707-e1ebe52 (MC: 1.8.8)
[INFO] EssentialsX version: 2.16.0.31
[INFO] LuckPerms version: 4.2.58
[INFO] Vault version: 1.7.1-b91
[INFO] EssentialsXChat version: 2.16.0.31
[INFO] EssentialsXSpawn version: 2.16.0.31
```
*edit by @md678685: formatting*

**EssentialsX config**: https://www.hastebin.com/kaduyularu.coffeescript

### Details

**Description**  
There's no error in console with this.
I do /skull and it doesn't give me my head, but gives me a steve or alex skull.

**Steps to reproduce**  
Download EssentialsX Latest on 1.8.8

**Expected behavior**  
I expect a skull with my name on it and with my head on it

**Comment by triagonal** [comment]
I wasn't able to reproduce this bug on a clean 1.8.8 spigot install with the latest version of EssentialsX - `/skull` worked as intended.
http://prntscr.com/mcpce3
```
[14:53:37 INFO]: Server version: 1.8.8-R0.1-SNAPSHOT git-Spigot-21fe707-e1ebe52 (MC: 1.8.8)
[14:53:37 INFO]: EssentialsX version: 2.16.0.32
[14:53:37 INFO]: EssentialsXProtect version: 2.16.0.32
[14:53:37 INFO]: EssentialsXSpawn version: 2.16.0.32
[14:53:37 INFO]: EssentialsXChat version: 2.16.0.32
[14:53:37 INFO]: EssentialsXGeoIP version: 2.16.0.32
[14:53:37 INFO]: EssentialsXAntiBuild version: 2.16.0.32
```
I was opped for testing.

**Comment by mdcfe** [comment]
@SinlesFlyer376 Could you post a full startup log on https://gist.github.com?

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to respond and reopen the issue.

**Comment by RubenBarrionuevo** [comment]
I have the same error

**Comment by pop4959** [comment]
@RubenStryker Make a new bug report issue and fill out the template.
