### ISSUE TITLE
My Minecraft server wont allow players to sethome aside form OPs with the newest file

### ISSUE THREAD

**Issue by CaptEm** [EssentialsX/Essentials#2398]
### Information

Full output of `/ess version`:
Version 2.16.0.3

**Server log:** 

**EssentialsX config** 

### Help request

**Problem**

My Server won't allow players to set home even though i just installed the latest version and it worked with the last version (Minecraft)
**What I have tried**

I have looked through the config file but it seems to say that players are allowed to use that command so I don't know where else to look. I am NOT a programmer so i'm sort of lost.
**Screenshots**

![image](https://user-images.githubusercontent.com/47123306/51868925-2e572e80-231d-11e9-8157-00749636b8a4.png)
![image](https://user-images.githubusercontent.com/47123306/51868948-3ca54a80-231d-11e9-8b95-565653afbac9.png)

**Comment by Xeyame** [comment]
Please fully fill in the template.

**Comment by CaptEm** [comment]
I filled in the whole template. I don't understand what it means by "set use.bukkit.permissions to false"

**Comment by Xeyame** [comment]
You should use some permissions plugin and give the player the correct permission from there.
Permission plugin: https://luckperms.github.io/ 
Permission list: https://essinfo.xeya.me/permissions.php

**Comment by CaptEm** [comment]
I don't understand why I need to do that though. I had the pervious essentials version in my server from November until now and i never had to ALLOW my players to access those commands. it was automatic.

**Comment by Xeyame** [comment]
Not sure why that is. Anyways, using no permissions manager is kind of unsupported. Please install one, it will make your life easyer (especially when using more then 1 plugin). Also lots of plugins just require one.

**Comment by CaptEm** [comment]
does Vault count as a permission manager?

**Comment by Xeyame** [comment]
Nope, its an economy bridge.

**Comment by CaptEm** [comment]
so after installing Luckperms do i need to do anything specific or will the plug in take care of things?

**Comment by Xeyame** [comment]
You need to add the permissions to the default group.
Something like `/lp group default permission set essentials.home` Repeat that for the other required permissions. I also suggest you read though the luckperms guide/iki. It is very detailed and pretty easy to understand :) https://github.com/lucko/LuckPerms/wiki

**Comment by CaptEm** [comment]
okay, i have done everything except allow players to hit a button and teleport them. I have a "phonebook" set up where i have command blocks under coloured wool and a button on each wool and the command blocks are set to tp to people's homes. they buttons work for me but not for everyone else and I don't know which permission is needed to allow them to do it.

**Comment by Xeyame** [comment]
You can try to enable `/lp verbose on yourplayername` and press the button, the required permission should show up then

**Comment by triagonal** [comment]
Closing due to author inactivity. If further support is required, please comment on this issue.

**Comment by allykellar** [comment]
i tried the /lp command and it still isnt working? ive been programming for hours at this poing trying to figure out how to give my players permission commands

**Comment by mdcfe** [comment]
@allykellar Did you install LuckPerms and Vault?

In addition, could you open a new issue?
