### ISSUE TITLE
Essentials cancels 'p.setAllowFlight(true);' if you don't have the Fly permission

### ISSUE THREAD

**Issue by TheRealDomm** [EssentialsX/Essentials#2399]
### Information

Full output of `/ess version`:

Server Version: 1.8.8-R0.1-SNAPSHOT git-Spigot-db6de12-18fbb24 (MC: 1.8.8)
EssentialsX Version: 2.16.0.34
LuckPerms Version: 4.3.11
Vault Version: 1.5.6-b49

Log & Config
https://gist.github.com/TheRealDomm/05336485fd7706fa676b141f2327f0fe

### Help request

**Problem**
Essentials always overrides my p.setAllowFlight(true); wich I'am using for another Plugin (FlyPerk on Players Plot). When I remove Essentials or add them the permission "essentials.fly" it just works fine.

**What I have tried**
Seeting the permission "essentials.fly" => works but I don't wan't to give all them players this Node.
Removed Essentials.

Thanks in advance for your help an keep going like this with your plugin. There is nothing better than this plugin!

TheRealDomm

**Comment by mdcfe** [comment]
Thanks for opening a support request.

The only place that EssentialsX changes the fly state are when the player logs in:

https://github.com/EssentialsX/Essentials/blob/dd41b10522b512a450a97907f36bd71fd8cd6554/Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java#L295-L304

...and when the player changes world:

https://github.com/EssentialsX/Essentials/blob/dd41b10522b512a450a97907f36bd71fd8cd6554/Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java#L551-L577

Are you sure you don't have another plugin hooking into EssentialsX? In addition, using `/ess debug` can you see a `essentials.fly` permission check when you call `player.setAllowFlight`?

**Comment by TheRealDomm** [comment]
Im not sure if any other plugins hook into EssentialsX i think mine is the only one. So this Issue happens when I listen on PlayerEnterPlotEvent from PlotSquared. Fly plan i to set players with the right permission fly on their plots my code is pasted [here](https://hastebin.com/bojovowope.java)
I delayed the PlotEnterEvent before it is fired for 5 seconds an then it works for some seconds but when you dont have the permission for /fly allow flight will be always removed. :( 

//edit: ess debug gives no change

**Comment by mdcfe** [comment]
Can you replicate this with **only EssentialsX, PlotSquared and your plugin** (plus Vault and LP) installed?

**Comment by TheRealDomm** [comment]
sure i will set this up

**Comment by TheRealDomm** [comment]
Hmm now it works i don't have a clue why...
I will test it later in my productive system and then we will see... I really thought it must be Essentials because of this strage thing with the permissionnode essentials.fly

**Comment by mdcfe** [comment]
Closing due to lack of response. Feel free to respond if this is an issue with EssentialsX.
