### ISSUE TITLE
give item with enchants 1.13.2

### ISSUE THREAD

**Issue by anemul** [EssentialsX/Essentials#2404]
### Details

**Description**  
/give anemul minecraft:bow{Enchantments:[{id:"minecraft:infinity",lvl:1}]} 1 does not work in 1.13.2 with ESS installed . ESS uninstalled , the command works fine , the only error our puts is there is no such item named minecraft:bow{Enchantments:[{id:"minecraft:infinity",lvl:1}]}

**Steps to reproduce**  
just copy and paste with ESS installed , changing to your name of course .

**Expected behavior**  
to receive an enchanted bow with infinity arrows

**Screenshots**

**Comment by mdcfe** [comment]
> `/give anemul minecraft:bow{Enchantments:[{id:"minecraft:infinity",lvl:1}]} 1`
That command is the vanilla Minecraft `/give` syntax. If you want to use the vanilla command, run `/minecraft:give`.

The Essentials equivalent is `/give anemul bow 1 infinity:1`.
