### ISSUE TITLE
Issues with essentials commands checking for permissions which players have and then denying access (LuckPerms Latest build)

### ISSUE THREAD

**Issue by turtlshell** [EssentialsX/Essentials#2406]

**Comment by AbbeLabben** [comment]
Hello there! Thanks for posting about this issue.

What you are describing here is the exact same problem that I am experiencing. Whenever a player types /warp or /home it says nothing in the chat and they have to type the command 10x or even relog for it to work. 

I have tried updating to the latest version, updating my config, removing plugins etc but nothing seems to work. So this must be an issue with the plugin. Hope this will get fixed soon!

**Comment by caojohnny** [comment]
It would be immensely helpful if you followed the [issue format](https://github.com/EssentialsX/Essentials/blob/2.x/.github/ISSUE_TEMPLATE/report-a-bug.md).

Some of the things that would be useful are a server log, your essentials config, and the version output. It would also help if you elaborated on exactly what is happening and if you turned on `debug` mode in the essentials config and paste the server log.

**Comment by pop4959** [comment]
Closing due to insufficient information. Open a new issue and follow the issue format as AgentTroll mentioned if you want this issue being investigated to any degree.
