### ISSUE TITLE
/createkit with 2.16 essx builds on 1.8.8 results in improperly defined kits

### ISSUE THREAD

**Issue by triagonal** [EssentialsX/Essentials#2408]
### Information

**Full output of `/ess version`**:

```
[16:19:19 INFO]: Server version: 1.8.8-R0.1-SNAPSHOT git-Spigot-21fe707-e1ebe52 (MC: 1.8.8)
[16:19:19 INFO]: EssentialsX version: 2.16.0.34
```

**Server log**: https://gist.github.com/triagonal/ff4b40c1309064d88e28d393ce23f26b

**EssentialsX config**: default config, but here it is anyway https://gist.github.com/triagonal/e71b6f0052881e456771e24d0f235951

**Kits file**: https://gist.github.com/triagonal/4768b348f987c1f0112d73856005a73c

### Details

**Description**  
Originally reported by AirCraze#5407 on Discord:
AirCraze's `/ess version`: http://prntscr.com/mfwxu6
AirCraze's kits.yml: https://hasteb.in/ugahevuk.yaml
AirCraze's server log: http://prntscr.com/mfwy3j

It seems like 1.13 compatible builds of EssentialsX (2.16+) will define kits improperly when using `/createkit` on older minecraft versions.

Tested only on 1.8.8 so far. Possibly related to #2387, which was solved by downgrading to the stable 1.8.8 build.

**Steps to reproduce**  
1. Place an item into your inventory (this may not happen with all items, but it does happen with an iron pickaxe)
2. Use /createkit to define a kit
3. Attempt to redeem kit - error occurs

**Expected behavior**  
The kit should work as intended

**Comment by triagonal** [comment]
As far as I can tell, this issue is caused when using LegacyItemDB, and by createkit using the item's material enum name for the kit configuration (via `AbstractItemDB#serialize()`): 

https://github.com/EssentialsX/Essentials/blob/fb779533e6dbff299f45376286ce9aab695e9832/Essentials/src/com/earth2me/essentials/items/AbstractItemDb.java#L66-L67

So when an iron pickaxe is registered in a kit, the kit's configuration will contain `IRON_PICKAXE` to refer to the item. The error then occurs when attempting to redeem the kit and find the appropriate ItemStack (via `FlatItemDB#get()` and `FlatItemDB#getByName()`):

https://github.com/EssentialsX/Essentials/blob/fb779533e6dbff299f45376286ce9aab695e9832/Essentials/src/com/earth2me/essentials/items/FlatItemDb.java#L102-L106

https://github.com/EssentialsX/Essentials/blob/fb779533e6dbff299f45376286ce9aab695e9832/Essentials/src/com/earth2me/essentials/items/FlatItemDb.java#L146-L152

Since `items.csv` doesn't contain the actual Material enum names (with underscores), the lookup of `IRON_PICKAXE` fails, and by extension any Material enum name containing underscores.

This could be fixed by adding the list of 1.12.2 Material enum names to `items.csv` and mapping them to their respective values, or possibly trying to parse again without underscores before throwing the exception:

```java
   public ItemStack get(String id) throws Exception {
        id = id.toLowerCase();
        final String[] split = id.split(":");

        ItemData data = getByName(split[0]);

        if (data == null) {
            data = getByName(split[0].replace("_", ""));
        }

        if (data == null) {
            throw new Exception(tl("unknownItemName", id));
        }
```

**Comment by triagonal** [comment]
This issue also occurs if the item db provider is manually specified as "csv" on 1.13+, which supports my speculation about FlatItemDB being the cause of the error.

https://gist.github.com/triagonal/0bc1a6d69d3f692df879047c253cc4fe

**Comment by triagonal** [comment]
(don't mind the deleted comment before this, no clue where I was going with that after re-reading it - obviously got confused somewhere)

This issue also occurs if the item db provider is manually specified as "csv" (`item-db-type: "csv"`) on 1.13+, so it seems that the issue may be caused by LegacyItemDB.

https://gist.github.com/triagonal/0bc1a6d69d3f692df879047c253cc4fe

**Comment by mdcfe** [comment]
@triagonal `item-db-type` isn't an officially supported feature. It's unlikely that the issue on 1.8.8 and 1.13.x have a common root cause.

**Comment by mdcfe** [comment]
I've merged a couple of fixes that both ensure `/createkit` works as intended and fix kits that were created with broken versions. Download the [latest build](https://ci.ender.zone/job/EssentialsX/) from the build server.

@triagonal Thanks for posting the report on GitHub and helping to replicate it.
