### ISSUE TITLE
Teleporting bug with warps

### ISSUE THREAD

**Issue by Castiella** [EssentialsX/Essentials#2410]
**Full output of `/ess version`**:

```
1.13.2-R0.1-SNAPSHOT git-Paper-498 (MC: 1.13.2)
Groupmanager Version: GMBUILDVER (pHEONIX)
essx: 2.16.0.3
Vault Version: 1.71-b91
Spawn:  2.16.0.3
Chat:  2.16.0.3
```

https://gist.github.com/Castiella/5b5db7afb6beb160a3d438aa45b83f70

https://gist.github.com/Castiella/747acaca35f0189388de7ff2fee3116e

### Details

**Description**  

See here: https://github.com/Multiverse/Multiverse-Core/issues/1964

Was told to report it here as you guys provide the warp command. :)

**Steps to reproduce**  

Warp to a warp that is in a different world to the one you're in. It will take you to your last known location in that world, rather than the warp. You then need to repeat the command to teleport to the warp.

**Expected behavior**  
To only run the command once.

**Screenshots**  
n/a

I know we are running groupmanagerX which is unsupported (just saw in /ess) which ones do you support? So i can change and you can help this issues hopefully

**Comment by mdcfe** [comment]
Please copy and paste the `/ess version` output - don't retype it as we can't verify whether you're on a supported version.

We support [LuckPerms](https://luckperms.github.io), and other permissions plugins are not supported.

**Comment by Castiella** [comment]
03.02 13:58:33 [Server] INFO Server version: 1.13.2-R0.1-SNAPSHOT git-Paper-498 (MC: 1.13.2)
03.02 13:58:33 [Server] INFO EssentialsX version: 2.16.0.3
03.02 13:58:33 [Server] INFO GroupManager version: GMBuildVer (Phoenix)
03.02 13:58:33 [Server] INFO Vault version: 1.7.1-b91
03.02 13:58:33 [Server] INFO EssentialsXSpawn version: 2.16.0.3
03.02 13:58:33 [Server] INFO EssentialsXChat version: 2.16.0.3
03.02 13:58:33 [Server] INFO You are running unsupported plugins!

**Comment by Castiella** [comment]
Shall I switch to Luck Perms and see if the problem persists?

**Comment by Xeyame** [comment]
Yea, Groupmanager is really old :P

**Comment by Castiella** [comment]
Hello, reopening this -

We are still having the issue, even with luckperms. Please let me know what you need from me to progress this issue.

**Comment by mdcfe** [comment]
Closin favour of #2445 which has updated information from the author.
