### ISSUE TITLE
short names do not work [TRADE]

### ISSUE THREAD

**Issue by andfont** [EssentialsX/Essentials#2411]
Server 1.13.1
Essentials version 1.16.0.34
BUG:
is it not possible to put short names of item.csv or from somewhere? when you create a new store with [trade] $ 1 1 prismarineblocks: 1 is impossible and many others! there is no way it does not work! please, is there a list with short names that works? What we see is that this since 1.13 has not worked well please some solution?

**Comment by triagonal** [comment]
If you hold an item in your hand and run `/itemdb`, it will show you a list of all available short names for that material.

**Comment by andfont** [comment]
We already know this, but the problem is that it does not fit in the poster! since you can not use ID's it does not fit! the official list with short names like item.csv or jitems.json does not fit in the poster to make the trade! [trade], we repeat! please fix the list of items.csv so that the short names work on the poster thank you

**Comment by andfont** [comment]
for example we intend to put / itemdb prismarinebricks the name is too long! does not fit! but in the items.csv if there are short names that do fit if you can put the poster of [trade] but they DO NOT WORK! please fix this great BUG! there is no way to use the [trade] thanks!

**Comment by triagonal** [comment]
Oh, I see. Got it.

@md678685, could you please add a shorter alias for prismarine bricks? As you've likely already gathered, the [available shortnames](http://prntscr.com/mgf5c1) are a bit too long for trade signs. Perhaps `pbricks` as in items.csv?

@andfont, do you know of any other blocks that are affected apart from prismarine bricks?

**Comment by andfont** [comment]
please fix this problem! with / itemdb there are names that do not fit in the poster! please the perfect solution is that you can use ID's again with an OWN database! of essentials! please fix the problem thank you!

**Comment by mdcfe** [comment]
@andfont There are now shorter names for prismarine bricks. Update EssentialsX and delete `items.json`, then start your server.
