### ISSUE TITLE
ItemIDs

### ISSUE THREAD

**Issue by GoodLuckXD** [EssentialsX/Essentials#2412]
I cant use my kit with the ID 276 AKA diamond sword it doesnt work. it says unknown ID.
[latest.log](https://github.com/EssentialsX/Essentials/files/2825924/latest.log) is my startup log so you can see there are alot of erros and spams from item.csv. IDK what I need to do

**Comment by Xeyame** [comment]
What version of essentials are you running? This is the latest one for 1.8.8: https://ci.ender.zone/job/EssentialsX/664/

The 1.13 versions don't fully support item id's on older versions iirc

**Comment by GoodLuckXD** [comment]
the newest

**Comment by Xeyame** [comment]
Well please try the version i linked above

**Comment by mdcfe** [comment]
Closing due to lack of resposne.
