### ISSUE TITLE
Permission for last reply message option

### ISSUE THREAD

**Issue by AngelDeaD** [EssentialsX/Essentials#2415]
### Feature request

**Feature description**
I know there are feature `last-message-reply-recipient` and for it `last-message-reply-recipient-timeout`, but those are config line. I would like it as permission.

**How the feature is useful**
Certain players that like this feature can enoy it, while rest of them who do not like it can enoy old way of "/r" working.

**Comment by mdcfe** [comment]
If I'm understanding this correctly, you want individual players to be able to control which reply recipient setting they want to use? If this is the case, how would a permission be better than being able to run a single command?

**Comment by AngelDeaD** [comment]
What `single command` are you talking about?
If you are talking about `last-message-reply-recipient` it's not command it's an option in config file.
Currently, I do not see way, how can 1 player have `last-message-reply-recipient` false and other player (at the same time) `last-message-reply-recipient` true

I think the best way would be with permission, unless there is already something like /msgreplytoggle

**Comment by mdcfe** [comment]
I was suggesting adding a command.

I don't see the point of adding a permission? It's unclear to users and requires additional setup from server administrators.

**Comment by AngelDeaD** [comment]
You are right. On second though, users can not abuse it, so it can be a command. Will it be `/msgreplytoggle` or something else and when it will be?
