### ISSUE TITLE
Can not use /enchant command on Paper Spigot 1.12.2

### ISSUE THREAD

**Issue by neodreen** [EssentialsX/Essentials#2416]
Essentials by default let me enchant everything but with the command /enchant and a different syntax than the original enchant command. This bug is very annoying because I need to create special items for my community  (I'm a server owner) and don't know why this happens. Pastebin: https://pastebin.com/a9p1vZWw

**Comment by mdcfe** [comment]
EssentialsX has always had its own `/enchant` command. If you want to use the vanilla command, use `/minecraft:enchant`.
