### ISSUE TITLE
EssentialsX Maven Repository?

### ISSUE THREAD

**Issue by Haileykins** [EssentialsX/Essentials#2417]
I am trying to use EssentialsX in my own plugin, and I don't want to have to build the jar and add it ass an artifact local jar, is there a current Maven repository for EssentialsX? If not can we please get one?

**Comment by mdcfe** [comment]
See the [Common Issues](https://essentialsx.github.io/#/Common-Issues?id=how-do-i-add-essentialsx-as-a-dependency) page.

**Comment by quiquelhappy** [comment]
link is broken, information can be found here:
https://essentialsx.net/wiki/Common-Issues.html#how-do-i-add-essentialsx-as-a-dependency

**Comment by LaxWasHere** [comment]
They're links you're suppose to add to your IDE, if you wish to browse the repository click [here](https://repo.essentialsx.net/#/).

**Comment by quiquelhappy** [comment]
> [Common Issues](https://essentialsx.github.io/#/Common-Issues?id=how-do-i-add-essentialsx-as-a-dependency)

Was referring to the <common issues> link posted my mdcfe

**Comment by Evidentsinger14** [comment]
It’s also a 4.5 year old post. the link has a redirect to the new site 😃
