### ISSUE TITLE
Colors of potions

### ISSUE THREAD

**Issue by mclegendary1** [EssentialsX/Essentials#2418]
**Description**  
If in kits are potions with metaid(it's must be if u want colored potions)

**Steps to reproduce**  
Just add to kits.yml
potion:16800 2 splash:true name:&4Granate effect:harm power:4 duration:1

**Screenshots**  
[https://imgur.com/a/IPux0kc](https://imgur.com/a/IPux0kc)

(and splash potions can't have two effects if they are in kits)

**Comment by mdcfe** [comment]
Please [fill out the template](https://github.com/EssentialsX/Essentials/issues/new?template=report-a-bug.md) fully, following the instructions given.
