### ISSUE TITLE
Can not creat kits on 1.12.2 with /createkit not even with the pestebin option

### ISSUE THREAD

**Issue by baloghdominik** [EssentialsX/Essentials#2419]
### Information

Full output of `/ess version`:

**Server log:** 

**EssentialsX config** 

### Help request

**Problem**

**What I have tried**

**Screenshots**

**Comment by mdcfe** [comment]
There are instructions in the template for a reason. Please [fill out the template](https://github.com/EssentialsX/Essentials/issues/new?template=report-a-bug.md) properly, following all the instructions given.
