### ISSUE TITLE
TP Toggle Bypass Perm?

### ISSUE THREAD

**Issue by Disorbs** [EssentialsX/Essentials#2420]
2.16.0.32

So when i give players the permission to do /TPToggle

why isnt there a permission for staff to still be able to tp but normal players cant request to them?
or am i blind and cant see it lol

**Comment by Xeyame** [comment]
You can use /tpo for this iirc

**Comment by mdcfe** [comment]
You can use the `/tpo` command (with permission `essentials.tpo`) to teleport to players that have disabled teleportation.

**Comment by GenOpenDiesel** [comment]
The tpo command isn't a workaround. It teleports you to the last entry/exit location...

It'll be great to finally get around to it.

**Comment by mdcfe** [comment]
`/tpoffline` teleports you to a player's last known location when they're offline, and didn't exist when this ticket was closed. `/tpo` teleports you to a player's current location.

If you're having trouble with this command, please reach out in MOSS for help.
