### ISSUE TITLE
Killall still not working

### ISSUE THREAD

**Issue by Partyille** [EssentialsX/Essentials#2421]
### Information

**Full output of `/ess version`**:

```
<!-- Run the command in your console, and copy and paste the whole output here -->
```

**Server log**: 

**EssentialsX config**: 

### Details

**Description**  

**Steps to reproduce**  

**Expected behavior**  

**Screenshots**

**Comment by mdcfe** [comment]
There are instructions in the template for a reason. Please fill out the template properly, following all the instructions given.
