### ISSUE TITLE
unknown item name 

### ISSUE THREAD

**Issue by supercrimeyt** [EssentialsX/Essentials#2423]
### Information

Full output of `/ess version`:

**Server log:** ![screenshot 2](https://user-images.githubusercontent.com/40644343/52831484-d3eef980-30a2-11e9-9154-3823d609779c.png)

**EssentialsX config** *arbitrary zip file removed*

### Help request

**Problem**
wont give items saying unknown item

**What I have tried**
306/iron_helmet/Iron_helmet/ironhelmet/minecraft:iron_helmet

**Screenshots**

![screenshot 4](https://user-images.githubusercontent.com/40644343/52831777-df8ef000-30a3-11e9-82a0-691bc1a2a793.png)
![screenshot 5](https://user-images.githubusercontent.com/40644343/52831778-df8ef000-30a3-11e9-8aa6-904a758465f3.png)
![screenshot 6](https://user-images.githubusercontent.com/40644343/52831779-df8ef000-30a3-11e9-8d56-04e4bfece908.png)
![screenshot 7](https://user-images.githubusercontent.com/40644343/52831780-e0278680-30a3-11e9-95c1-6b31cb53d7e3.png)
![screenshot 8](https://user-images.githubusercontent.com/40644343/52831781-e0278680-30a3-11e9-9c16-892830f01195.png)
![screenshot 9](https://user-images.githubusercontent.com/40644343/52831782-e0278680-30a3-11e9-86ba-ee4a24b3d23e.png)

**Comment by Xeyame** [comment]
Why did you zip the .kits file lol, also please include a written descrioption as this screenshot is pretty much the laziest way you could do it and isn't easlily readable. Please do `/essentials version`, paste the output into here. Also please put in a console log when using iron_helmet in the kits.yml (and rebooting after changing)

**Comment by mdcfe** [comment]
As Xeyame pointed out, you haven't included the output of `/ess version`.

Please read and follow the instructions given in the template next time - you need to remove the arrows from the template before posting.

**Comment by triagonal** [comment]
Closing due to lack of response.
