### ISSUE TITLE
Allow setting / removing nick name based on their UUID.

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#2424]
Would it be possible to allow nicknaming players via UUID while offline? That way you can have the command ```/nick {UUID] off``` run automatically at the end of the month to remove nicknames from players who should no longer have access to nick in the event they changed their minecraft name.

**Comment by mdcfe** [comment]
I think this is supposed to already be possible - have you tried it?

**Comment by mibby** [comment]
Yes, I've tried it @md678685. However it does not seem to work when the player is offline. Only while they are online does it match the UUID to a player.

**Comment by mibby** [comment]
@md678685 Any possible update on this issue? :(

**Comment by mdcfe** [comment]
This can be fixed by trying to call `UserMap#getUser(UUID)` at the start of this method: https://github.com/EssentialsX/Essentials/blob/b831713737d556e31aa5df9849e4503dd761b727/Essentials/src/com/earth2me/essentials/UserMap.java#L87-L106

**Comment by triagonal** [comment]
Closed by #2606 - loop commands (like `/nick`) can now accept UUIDs as parameters.
