### ISSUE TITLE
Server Console Material Error

### ISSUE THREAD

**Issue by uwuscutely** [EssentialsX/Essentials#2425]
I'm getting an error for EssentialsX that says Failed to find material for sstone and a bunch of other materials. The server is on 1.12.2. Using Spigot 1.12.2

**Comment by uwuscutely** [comment]
16.02 03:51:19 [Server] WARN Failed to find material for sstone
16.02 03:51:19 [Server] WARN Failed to find material for smoothstone
16.02 03:51:19 [Server] WARN Failed to find material for rock
16.02 03:51:19 [Server] WARN Failed to find material for granite
16.02 03:51:19 [Server] WARN Failed to find material for gstone
16.02 03:51:19 [Server] WARN Failed to find material for polishedgranite
16.02 03:51:19 [Server] WARN Failed to find material for pgranite
16.02 03:51:19 [Server] WARN Failed to find material for pgstone
16.02 03:51:19 [Server] WARN Failed to find material for polishedgstone
16.02 03:51:19 [Server] WARN Failed to find material for diorite
16.02 03:51:19 [Server] WARN Failed to find material for dstone
16.02 03:51:19 [Server] WARN Failed to find material for polisheddiorite
16.02 03:51:19 [Server] WARN Failed to find material for pdiorite
16.02 03:51:19 [Server] WARN Failed to find material for pdstone
16.02 03:51:19 [Server] WARN Failed to find material for polisheddstone
16.02 03:51:19 [Server] WARN Failed to find material for andesite
16.02 03:51:19 [Server] WARN Failed to find material for astone
16.02 03:51:19 [Server] WARN Failed to find material for polishedandesite
16.02 03:51:19 [Server] WARN Failed to find material for pandesite
16.02 03:51:19 [Server] WARN Failed to find material for pastone
16.02 03:51:19 [Server] WARN Failed to find material for greendirt
16.02 03:51:19 [Server] WARN Failed to find material for greenearth
16.02 03:51:19 [Server] WARN Failed to find material for greenland
16.02 03:51:19 [Server] WARN Failed to find material for earth
16.02 03:51:19 [Server] WARN Failed to find material for land
16.02 03:51:19 [Server] WARN Failed to find material for cdirt
16.02 03:51:19 [Server] WARN Failed to find material for grasslessdirt
16.02 03:51:19 [Server] WARN Failed to find material for grasslessearth
16.02 03:51:19 [Server] WARN Failed to find material for grasslessland
16.02 03:51:19 [Server] WARN Failed to find material for coarsedirt
16.02 03:51:19 [Server] WARN Failed to find material for coarseland
16.02 03:51:19 [Server] WARN Failed to find material for coarseearth
16.02 03:51:19 [Server] WARN Failed to find material for podzol
16.02 03:51:19 [Server] WARN Failed to find material for cstone
16.02 03:51:19 [Server] WARN Failed to find material for cobble
16.02 03:51:19 [Server] WARN Failed to find material for plank
16.02 03:51:19 [Server] WARN Failed to find material for woodenplank
16.02 03:51:19 [Server] WARN Failed to find material for woodplank
16.02 03:51:19 [Server] WARN Failed to find material for wplank
16.02 03:51:19 [Server] WARN Failed to find material for plankwooden
16.02 03:51:19 [Server] WARN Failed to find material for plankwood
16.02 03:51:19 [Server] WARN Failed to find material for plankw
16.02 03:51:19 [Server] WARN Failed to find material for oakplank
16.02 03:51:19 [Server] WARN Failed to find material for oakwoodenplank
16.02 03:51:19 [Server] WARN Failed to find material for oakwoodplank
16.02 03:51:19 [Server] WARN Failed to find material for oakwplank
16.02 03:51:19 [Server] WARN Failed to find material for oakplankwooden
16.02 03:51:19 [Server] WARN Failed to find material for oakplankwood
16.02 03:51:19 [Server] WARN Failed to find material for oakplankw
16.02 03:51:19 [Server] WARN Failed to find material for oplank
16.02 03:51:19 [Server] WARN Failed to find material for owoodenplank
16.02 03:51:19 [Server] WARN Failed to find material for owoodplank
16.02 03:51:19 [Server] WARN Failed to find material for owplank
16.02 03:51:19 [Server] WARN Failed to find material for oplankwooden
16.02 03:51:19 [Server] WARN Failed to find material for oplankwood
16.02 03:51:19 [Server] WARN Failed to find material for oplankw
16.02 03:51:19 [Server] WARN Failed to find material for pineplank
16.02 03:51:19 [Server] WARN Failed to find material for pinewoodenplank
16.02 03:51:19 [Server] WARN Failed to find material for pinewoodplank
16.02 03:51:19 [Server] WARN Failed to find material for pinewplank
16.02 03:51:19 [Server] WARN Failed to find material for pineplankwooden
16.02 03:51:19 [Server] WARN Failed to find material for pineplankwood
16.02 03:51:19 [Server] WARN Failed to find material for pineplankw
16.02 03:51:19 [Server] WARN Failed to find material for pplank
16.02 03:51:19 [Server] WARN Failed to find material for pwoodenplank
16.02 03:51:19 [Server] WARN Failed to find material for pwoodplank
16.02 03:51:19 [Server] WARN Failed to find material for pwplank
16.02 03:51:19 [Server] WARN Failed to find material for pplankwooden
16.02 03:51:19 [Server] WARN Failed to find material for pplankwood
16.02 03:51:19 [Server] WARN Failed to find material for pplankw
16.02 03:51:19 [Server] WARN Failed to find material for darkplank
16.02 03:51:19 [Server] WARN Failed to find material for darkwoodenplank
16.02 03:51:19 [Server] WARN Failed to find material for darkwoodplank
16.02 03:51:19 [Server] WARN Failed to find material for darkwplank
16.02 03:51:19 [Server] WARN Failed to find material for darkplankwooden
16.02 03:51:19 [Server] WARN Failed to find material for darkplankwood
16.02 03:51:19 [Server] WARN Failed to find material for darkplankw
16.02 03:51:19 [Server] WARN Failed to find material for dplank
16.02 03:51:19 [Server] WARN Failed to find material for dwoodenplank
16.02 03:51:19 [Server] WARN Failed to find material for dwoodplank

**Comment by mdcfe** [comment]
You haven't provided enough information.

Please [fill out the template](https://github.com/EssentialsX/Essentials/issues/new?template=help.md), following the instructions given.
