### ISSUE TITLE
Item DB issues with 1.8.8 Spigot

### ISSUE THREAD

**Issue by mattyokan** [EssentialsX/Essentials#2427]
### Information

**Full output of `/ess version`**:

I'm putting this on Hastebin cause it's over 5000 lines long: https://paste.md-5.net/yucifopize.md

**Server log**: https://paste.md-5.net/codicixoge.md

**EssentialsX config**: Default

### Details

**Description**  
When using 2.16.X on 1.8.x versions, I am running into strange issues with the Item DB. Doing things like /i tripwire_hook and /i stained_glass_pane doesn't work, and this also breaks item loading for ALL of my plugins that use Essentials ItemDB.

**Steps to reproduce**  
Use 1.8.8 spigot/paperspigot with the latest essentials version (2.16.0.3 is what I tested) and try what I mentioned above.

**Expected behavior**  
The Item database should work as normal, but it has strange issues like this (probably because of the 1.13 update)

**Screenshots**  
Not applicable, this should be thorough enough hopefully.

**Comment by triagonal** [comment]
Hi - The Spigot release version (2.16.0.3) is known to have this issue. You should update to the latest build at the build server: https://ci.ender.zone/job/EssentialsX/

**Comment by mattyokan** [comment]
Awesome, sorry for the late response but thank you. I didn't check to use the dev builds since this was a very sudden issue (I got a message about it then had to rush to find a fix lol).

Glad to see this is fixed already!
