### ISSUE TITLE
Build #697 breaks teleporting to spawn on join

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#2433]
Error: https://pastebin.com/7eu7tYv4
Using Paper build # 525 for 1.13.2
(Discovered while using build # 700 for Essx)

**Comment by mdcfe** [comment]
This should be fixed by 289d34d96c04f0e2db5994e1c6996eb33518b378 (thanks @kashike) - grab the [latest version](https://ci.ender.zone/job/EssentialsX/) from the build server.
