### ISSUE TITLE
[Feature] redirect commands output

### ISSUE THREAD

**Issue by vPrapo** [EssentialsX/Essentials#2440]
**Feature request**
Send current position to someone in private.

**Feature description**
A combination of /w and the output of /position
Can be something like `/spos <player>`
(send position)

**How the feature is useful**
In a pvp/survival server this is useful to send your position to your allies quickly.

**Comment by caojohnny** [comment]
IMHO this feature is pretty narrow in scope. I don't know if enough people will find this a useful addition to Essentials such that it would warrant an entirely separate command. Thoughts on this?

**Comment by mdcfe** [comment]
I agree that this is limited in scope, as it doesn't serve much purpose for most servers beyond letting players communicate when teleportation isn't available. This might be better suited to a combat-focussed plugin instead of EssentialsX (which has to account for lots of different types of servers).

**Comment by vPrapo** [comment]
Well, can this be for redirect **any command** output to a user? is that possible?
for e.g. when a user don't have permission to use server info command
but as an admin I want to show him my output without giving him permission.
in the same time it can be used as well for /position and send its output to a user privately.
or if a user getting error for a command he can show the admin what it says.
I don't have to guess that it's useful this way.

with the option to send the output in chat or privately.

**Comment by pop4959** [comment]
This doesn't seem like a very popular addition. Also, please don't change the topic of the issue completely as this is very misleading. Instead, you should create a new issue relating to the new topic if you would like to see discussion on it. Although, in this case, I don't think it's possible to redirect command output to another user. Even if it were shoehorned in, I don't see anyone really using it.

**Comment by mdcfe** [comment]
While the second request is technically *possible*, it would require reworking the whole EssentialsX command system for something that, as pointed out by pop, few people would use.
