### ISSUE TITLE
EssentialsX canceling flight on world change

### ISSUE THREAD

**Issue by Kbryst** [EssentialsX/Essentials#2444]
EssentialsX version: 2.16.1.0
Paper Spigot 1.13.2

So I have an enchant plugin that toggles /fly on for players. I have fly disabled in essentials under disabled commands. 

My issue is that its auto toggling off flight on world change, and thats causing issues with the enchant plugin. 

I am able to recreate this on a test server with just the enchants and essentialsX.

**Comment by mdcfe** [comment]
You can give players `essentials.fly` to prevent this - they won't be able to use `/fly` if you've disabled it in the config, but they will be able to keep their fly status with that permission.

**Comment by Kbryst** [comment]
Oh that's brilliant! Thank you
