### ISSUE TITLE
Teleportation sending players to wrong area when warping.

### ISSUE THREAD

**Issue by Castiella** [EssentialsX/Essentials#2445]
**Full output of `/ess version`**:

```
[14:20:31 INFO]: Server version: 1.13.2-R0.1-SNAPSHOT git-Paper-551 (MC: 1.13.2)
[14:20:31 INFO]: EssentialsX version: 2.16.1.0
[14:20:31 INFO]: LuckPerms version: 4.3.73
[14:20:31 INFO]: Vault version: 1.7.1-b91
[14:20:31 INFO]: EssentialsXSpawn version: 2.16.1.0
[14:20:31 INFO]: EssentialsXChat version: 2.16.1.0
```

### Details

LOG: https://gist.github.com/Castiella/d1c59674b6eae61a652811ab90d80a7f

**Description**  

See here: https://github.com/Multiverse/Multiverse-Core/issues/1964

Was told to report it here as you guys provide the warp command. :)

**Steps to reproduce**  

Warp to a warp that is in a different world to the one you're in. It will take you to your last known location in that world, rather than the warp. You then need to repeat the command to teleport to the warp.

**Expected behavior**  
To only run the command once.

**Screenshots**  
n/a

**Comment by mdcfe** [comment]
Is there any way you could replicate this on default worlds without Multiverse-Core?

To my knowledge, no changes occurred in EssentialsX's teleport code between 2.15.0 and 2.16.0 (where the issue could be replicated as per #2410). I suspect this is related to a change in Paper or Spigot 1.13.2 that occurred recently - this needs further investigation.

**Comment by Castiella** [comment]
I can’t warp between worlds without multiverse core though? I’m confused about what you want from me.

This has also been happening since we updated to 1.13 paper, so that sounds plausible.

**Comment by aikar** [comment]
Please update Paper, that was fixed already in 554

**Comment by Castiella** [comment]
I am now running the recent paper and it is still doing this.

**Comment by mdcfe** [comment]
I can't replicate this on the latest version of EssentialsX and Paper without Multiverse installed, using the default Overworld and Nether worlds created by Minecraft. (Multiverse Core doesn't interfere as far as I can tell.)

![image](https://user-images.githubusercontent.com/1917406/53906224-46b81880-4042-11e9-9ebf-caec3b828c8b.png)

**Comment by Castiella** [comment]
Reviving this as the issue has come back. Im using most recent paper build. has anyone else been aware of this?

**Comment by JRoy** [comment]
@Castiella if you're still experiencing this, open a new issue and make sure to fill out all the fields and give us specific instructions on how to reproduce it.
