### ISSUE TITLE
/enchant with id?

### ISSUE THREAD

**Issue by mclegendary1** [EssentialsX/Essentials#2446]
### Feature request

**Feature description**
/enchant with id
Expample: /enchant 34 10 (durability 10)
On servers 1.12.2 and belows.

**How the feature is useful**
It's much easier than write full name of enchant.

I know, it's mb hard with version 1.13 in the plugin, but it's very useful function i think.
If you can't - it's okay.

**Comment by mdcfe** [comment]
This should already work.

Could you post the output of running `/ess version` on your server?

**Comment by mclegendary1** [comment]
I'm sorry for that long time no-answering.
Here is ess version https://imgur.com/bnQAOJV

**Comment by pop4959** [comment]
Please update the plugin and if you are still experiencing problems feel free to make a new issue (that is, if you still care about this being resolved / haven't found an answer). Be sure to fill out the issue template in its entirety, and ideally a way to replicate the issue.
