### ISSUE TITLE
No @'s

### ISSUE THREAD

**Issue by AlvoriGaming** [EssentialsX/Essentials#2447]
### Allow @'s

**Allows to specify a player in a range, nearest, all, and entitys**

**Help with other plugins and thing mainly I need it for the things I the am working on.**

**I would like if you do that and for reading have a good day bye**

**Not for vanilla but for outsided  plugin commands like Pex, CratePlus, and etc.**

**Comment by kennyrkun** [comment]
similar to #2102

**Comment by md678685** [comment]
Duo)ovate of

**Comment by mdcfe** [comment]
Duplicate of #2102 - see [this response](https://github.com/EssentialsX/Essentials/issues/2102#issuecomment-444973081) for the current state of command selectors.
