### ISSUE TITLE
[Feature] Ignore teleport cooldown

### ISSUE THREAD

**Issue by CryLegende** [EssentialsX/Essentials#2448]
### Feature request

**Feature description**
Add in the essentials configuration an option to bypass the teleportation cooldown in some worlds
Like:
```
ignore-teleport-cooldown-in-world:
  - ASkyBlock
  - lobby
```

**How the feature is useful**
It would (for example) activate cooldown only in the pvp world or the end / nether worlds

**Comment by LaxWasHere** [comment]
Just give them bypass permissions on those worlds.

**Comment by CryLegende** [comment]
With my permission plugin ?

**Comment by Remski01** [comment]
Yes

**Comment by CryLegende** [comment]
It's done thank you but it is possible to put a cooldown on a non-essentials order?

**Comment by triagonal** [comment]
Closing - feature can be simulated using per-world permissions and any decent permissions plugin.
