### ISSUE TITLE
send command prior to command execution

### ISSUE THREAD

**Issue by cicatrice74** [EssentialsX/Essentials#2453]
### Feature request

**Feature description**

**How the feature is useful**

**Comment by cicatrice74** [comment]
Is there a way to add the possibility to have a command executed prior to any command ?
I would like to send titles on screen prior to teleports, maybe something like, "Don't move, teleportation in 3.2.1..

**Comment by Xeyame** [comment]
This is probably also not something for essentialsX, The best i can think of is the plugin Titlemanager; Also are you like requesting ether commands to be executed only for waiting command (that could be done with commands.yml), add titles to the teleportation commands, or just what your requesting in your title (that can also be done in commands.yml)?
