### ISSUE TITLE
Essntials kits doesn't like enchanted shields

### ISSUE THREAD

**Issue by EOT3000** [EssentialsX/Essentials#2456]
enchant a shield with curse of bunding, then create a kit with it, the kit breaks. unecnchant it, redo kit, and everything works

**Comment by EOT3000** [comment]
as it turns out, that happens with any enchant

**Comment by Xeyame** [comment]
Please run the command `/ess version` and paste the full output

**Comment by EOT3000** [comment]
[Sun, 10. Mar 2019 14:01:44 EDT INFO] CONSOLE issued server command: /ess version
[Sun, 10. Mar 2019 14:01:44 EDT INFO] Server version: 1.13.2-R0.1-SNAPSHOT git-Paper-554 (MC: 1.13.2)
[Sun, 10. Mar 2019 14:01:44 EDT INFO] EssentialsX version: 2.16.0.3
[Sun, 10. Mar 2019 14:01:44 EDT INFO] LuckPerms version: 4.3.2
[Sun, 10. Mar 2019 14:01:44 EDT INFO] Vault version: 1.7.1-b91

**Comment by EOT3000** [comment]
@Xeyame I did it

**Comment by mdcfe** [comment]
There is nowhere near enough information to help. Please [fill out the relevant issue template](https://github.com/EssentialsX/Essentials/issues/new/choose).
