### ISSUE TITLE
Include mute reason and duration in MuteStatusChangeEvent

### ISSUE THREAD

**Issue by mdcfe** [EssentialsX/Essentials#2459]
### Feature request

**Feature description**
[`MuteStatusChangeEvent`](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/net/ess3/api/events/MuteStatusChangeEvent.java) currently doesn't expose the mute timestamp or reason. This event could be extended to include these. Note that the timestamp and reason arguments would need to be parsed before sending the event, but currently they aren't parsed until after this.

**How the feature is useful**
Developers will be able to retrieve the mute reason and timestamp without waiting for 
EssentialsX to determine and save them.

**Comment by Stupremee** [comment]
How about adding the timestamp to every StatusChangeEvent or even in every event?

**Comment by mdcfe** [comment]
@Stupremee The `timestamp` in this case is the mute duration (it's referred to as `timestamp` in the mute code). There isn't any point adding the timestamp to every event - you wouldn't gain anything over just checking the current time in your listener.

**Comment by Stupremee** [comment]
Ohh okay. I misinterpreted it.
