### ISSUE TITLE
[AtomMC] /world Command with more then 3 world causes Client to respawn in an incorrect dimension

### ISSUE THREAD

**Issue by CDAGaming** [EssentialsX/Essentials#2460]
### Information

**Full output of `/ess version`**:

```
[22:57:20] [Server thread/INFO] []: Server version: 1.12.2-R0.1-SNAPSHOT null (MC: 1.12.2) - This is Atom from https://gitlab.com/divinecode/atom/Atom
[22:57:20] [Server thread/INFO] []: EssentialsX version: 2.16.1.0
[22:57:20] [Server thread/INFO] []: LuckPerms version: 4.3.108
[22:57:20] [Server thread/INFO] []: Vault version: 1.7.1-b91
[22:57:20] [Server thread/INFO] []: EssentialsXProtect version: 2.16.1.0
[22:57:20] [Server thread/INFO] []: EssentialsXChat version: 2.16.1.0
[22:57:20] [Server thread/INFO] []: EssentialsXGeoIP version: 2.16.1.0
[22:57:20] [Server thread/INFO] []: EssentialsXAntiBuild version: 2.16.1.0
[22:57:20] [Server thread/INFO] []: EssentialsXSpawn version: 2.16.1.0
```

**Server log**: https://gist.github.com/CDAGaming/df5fe366c619b556a1702491eeb979d5

**EssentialsX config**: https://gist.github.com/CDAGaming/84c9f240c965c0f25400a84b8c742272

### Details

**Description**  
With Atom allowing both Bukkit/Spigot plugins and forge mods to be used together, /world as well as re-spawning is no longer working properly. Instead of respawning in the Overworld like normal, I am now re-spawning in the nether, often times above lava. As an example, I'm using the mods Aether Legacy and Aether II in my example

**Steps to reproduce**  
- Set up an AtomMC Server (Or Join nodats.doucl.com and type /server atom) with EssentialsX, and Aether II and Aether Legacy
- /suicide or /kill <Your IGN> and try to respawn

**Expected behavior**  
- Being able to re-spawn in the overworld and being able to use /world for as many dimensions that exist.

**Screenshots**  
N/A

**Comment by Xeyame** [comment]
Essentials is only supported on Paper/Spigot as far as i know. Also your huge log is a pain to read. Anyways, this is probs cause that server software does weird stuff with worlds (or some misconfiguration with multiverse if you use that)

**Comment by CDAGaming** [comment]
Slimmed down the Gist, sorry about that. It may be just the Server Software so Im waiting for the dev over there to see if he can do anything about it

**Comment by mdcfe** [comment]
EssentialsX aims to support Spigot, Paper and Glowstone, and we don't support hybrid servers. (I recommend using Sponge; it's maintained by a large team that know how to integrate plugins and mods.)

The Bukkit API and Forge have traditionally always had different conventions for identifying worlds/dimensions. Forge follows the vanilla convention, where a "world" contains several dimensions, but in Bukkit, a "world" is a single dimension.

I'm guessing that somewhere along the line, Atom isn't matching its Bukkit world names to the right vanilla/Forge dimensions. From your log, dimensions 1 and -1 are just called `DIM1` and `DIM-1` to Bukkit, whereas they're usually called `world_nether` and `world_the_end` on Bukkit servers.

**Comment by mdcfe** [comment]
Closing as there isn't anything we can do about this ~~other than recommending SpongeForge and Nucleus~~.
