### ISSUE TITLE
Elytra selling with /sellall command

### ISSUE THREAD

**Issue by milothedalmador** [EssentialsX/Essentials#2462]
### Information

**EssentialsX config** https://gist.github.com/milothedalmador/978374844d04472db53d3deaeb95cf3a.js

### Help request

**Problem**
Players with access to /sellall seem to sell their elytra even if it's being worn and not just in their inventory.

**What I have tried**
I've hunted through the Spigot pages and google but haven't yet found a solution.

**Screenshots**
N/A

**Comment by milothedalmador** [comment]
As per the request on Discord - here is the output when doing /ess version:
![2019-03-20_12 14 13](https://user-images.githubusercontent.com/46726096/54683594-eaf19300-4b09-11e9-9eb4-b3472f100611.png)

**Comment by triagonal** [comment]
Replace all of your old EssentialsX jars with the [latest version on the build server](https://ci.ender.zone/job/EssentialsX/lastBuild/), and then test again to see if the problem persists.

**Comment by milothedalmador** [comment]
I'll get on that now!

**Comment by triagonal** [comment]
@milothedalmador - Did you end up solving your issue?

**Comment by triagonal** [comment]
Closing due to lack of response.
