### ISSUE TITLE
Hiding non-accessible commands from the autofill

### ISSUE THREAD

**Issue by JIH97** [EssentialsX/Essentials#2463]
### Information

Full output of `/ess version`:

Server version:1.13.2-r0.1-SNAPSHOT git-spigot-518206a-a5b9c7 (MC: 1.13.2)
EssentialsX version: 2.16.1.80
Luckperms version: 4.3.73

### Help request

**Problem**
To remove non_accessible commands from the autofill function.
and when i do /data get entity "player" i get no feedback, but if i do it in the consol i get it

**What I have tried**
Tried to change this to false (hide-permissionless-help: true) as it was the only thing i could find in the config that could help

**Screenshots**
![image](https://user-images.githubusercontent.com/11247113/54883881-bc0d5100-4e6a-11e9-94b1-b8be6c24f54b.png)

**Comment by mdcfe** [comment]
This has been fixed in #2469 - you can download the latest version from the [build server](https://ci.ender.zone/job/EssentialsX).
