### ISSUE TITLE
Issue teleportating to location atop barriers

### ISSUE THREAD

**Issue by silverwolfg11** [EssentialsX/Essentials#2464]
### Information

**Full output of `/ess version`**:

```
24.03 17:34:58 [Server] INFO Server version: 1.13.2-R0.1-SNAPSHOT git-Spigot-3cb9dcb-0f708cb (MC: 1.13.2)
24.03 17:34:58 [Server] INFO EssentialsX version: 2.16.1.0
24.03 17:34:58 [Server] INFO LuckPerms version: 4.3.17
24.03 17:34:58 [Server] INFO Vault version: 1.6.6-b${env.TRAVIS_BUILD_NUMBER} 
24.03 17:34:58 [Server] INFO EssentialsXChat version: 2.16.1.0 
24.03 17:34:58 [Server] INFO EssentialsXSpawn version: 2.16.1.0
```

**Server log**:  N/A

**EssentialsX config**: https://gist.github.com/silverwolfg11/ef863d8f4c660617b9bf05a4a433a69d

### Details

**Description**  
Teleporting to a location that is atop barriers will register as an unsafe location and teleport players below the barriers. 

**Steps to reproduce**  
Create an area of barriers above the ground (not touching other blocks). Set a location (or teleport to a player) while standing on top of the barriers. Then simply teleport to the location while in survival mode (and not flying).

**Expected behavior**  
To teleport atop the barriers and not below them.

**Screenshots**  
N/A

**Comment by pop4959** [comment]
This is intentional, as far as I can tell. Essentials will not allow teleportation onto transparent blocks. The block must be opaque. As a possible workaround, if you must be able to teleport someone, either disable safe teleportation or use an alternative teleportation command (like /minecraft:tp).
