### ISSUE TITLE
Lag Notice Slow Economy Response

### ISSUE THREAD

**Issue by GunacP40** [EssentialsX/Essentials#2465]
EssentialsX version: 2.16.1

Server software: spigot-21fe707-e1ebe52 1.8.8 R0.1

Error: [22:55:34 INFO]: [Essentials] Lag Notice - Slow Economy Response - Request took
over 299.994ms!

When does this happen? I run a SkyWarsReloaded Server with MySQL, I've linked the plugin to PlayerPoints, and PlayerPoints to Vault. SkyWarsReloaded needs an Economy plugin to work, so I've installed EssentialsX, but if PlayerPoints is linked to Vault the error keeps pooping up and lags the server. I've tried updating plugins, I've contacted the SWR Developer and he told me that the problem comes from your plugin. I've tried with another economy plugins and this does not happen, but your plugin is unique and I do need for another purposes.

What plugins do you have? https://imgur.com/a/GWh0hCT

What is your Vault version? 1.5.6-b49

Thanks. I sincerely hope you can help me.

**Comment by GunacP40** [comment]
I also tried optimizing the MySQL server but that didn't help at all. This problem only happens with your plugin. I have a SkyBlock and Factions server running your plugin and MySQL and this doesn't happen.

**Comment by GunacP40** [comment]
bump

**Comment by Xeyame** [comment]
This happens because your Economy plugin is slow in responding, so that message is put in your console. This is not an issue with essentials, seems like your sql database is indeed too slow then. However If your not using Essentials, this shouldn't pop up. SkyWarsreloaded can just use PlayerPoints as an economy provider for vault (if im understanding correctly what you are saying). Anyways this is not an issue with essnetialsx, its just that essentialsx alerts you that economy is really slow in responding whilst other plugins don't.

**Comment by mdcfe** [comment]
> EssentialsX version: 2.16.1
> 
> Server software: spigot-21fe707-e1ebe52 1.8.8 R0.1

Please follow the instructions in the template, and please don't bump issues (especially not within 24 hours of posting).

---

PlayerPoints is an economy plugin, so every plugin on your server will use PlayerPoints as the economy backend, including EssentialsX. EssentialsX's economy features will manipulate your PlayerPoints economy, and removing EssentialsX won't affect SkyWarsReloaded or PlayerPoints.

The message occurs when your economy plugin is taking an unusually long amount of time to do economy operations. This is only a warning, and doesn't affect how EssentialsX works, but the warning is there to inform you that your economy plugin could potentially be slowing down the server (and other plugins) with economy operations.

If you're absolutely certain that you can't make any further optimisations to your database, you should contact PlayerPoints' support to see if there are any potential improvements you could make.

**Comment by GunacP40** [comment]
Ok thank you. I noticed you said that if I remove EssentialsX then SWR will use PlayerPoints as the economy provider. Well, unfortunately that is not possible, if I remove EssentialsX, SWR won't start and will say that I need an economy plugin (even if I have playerpoints and vault installed)

**Comment by GunacP40** [comment]
Also, sorry for bumping within 24 hours. I didn't know the rules, now I do.

**Comment by GunacP40** [comment]
So, I just finished optimizing the database and the mysql server, and the problem is still there. I don't understand how this is a problem of optimization when the lag issue and the message does not happen or appear in any of my other servers, which also are connected to the same database. (The database saves a global coin)

**Comment by mdcfe** [comment]
If SWR isn't picking up PlayerPoints as an economy plugin, that isn't a problem on EssentialsX's end. You haven't provided anywhere near enough information for us to figure out whether there is an issue on EssentialsX's end or not.

This isn't support for SkyWarsReloaded nor PlayerPoints. If you're not planning to use EssentialsX, you need to contact the support for those plugins.

If you're *sure* that you actually want and need EssentialsX and that EssentialsX isn't functioning properly, please [fill out a support request](https://github.com/EssentialsX/Essentials/issues/new/choose), following all the required steps in the template.
