### ISSUE TITLE
worth.yml

### ISSUE THREAD

**Issue by ColorsASD** [EssentialsX/Essentials#2467]
Hi. Please update worth.yml to `1.13` material list.

**Comment by Xeyame** [comment]
What exactly do you mean with this?

As far as i can see, worth.yml is using material names that are supported on 1.13.

**Comment by ColorsASD** [comment]
If it were supported with 1.13 item list I wouldn't have indicated it and the file is not updated because there are no data data objects in the file and can still be found. Exemplary oak_log material does not work. The /worth command use and not found ID, but barrier ID found and try:

```
worth:
  oak_log: 15
  oaklog: 15
  log: 15
  log:
    0: 15
```

But said not found material.

I use PaperSpigot 1.13.2 build 595 and Essentials 2.16.1.80 build 713.

Please test worth options and fix.

**Comment by ColorsASD** [comment]
And can I get the EssentialsProtect supplement? (newMob, dangerousAbility)
For example snowman do not pull on snow.

**Comment by mdcfe** [comment]
> I use PaperSpigot 1.13.2 build 595 and Essentials 2.16.1.80 build 713.

In the future, please [fill out the template properly](https://github.com/EssentialsX/Essentials/issues/new/choose) for support.

> Exemplary oak_log material does not work. [...] Please test worth options and fix.

`worth.yml` works on 1.13 without any problems. You can use `/setworth` to put the right item name in `worth.yml`:
```java
> setworth log 500
[14:55:24 INFO]: CONSOLE issued server command: /setworth log 500
[14:55:24 INFO]: Worth value set
```
```yaml
worth:
  oaklog: 500.0
# ...
```

---

> And can I get the EssentialsProtect supplement? (newMob, dangerousAbility)
> For example snowman do not pull on snow.

Please [open a separate feature request](https://github.com/EssentialsX/Essentials/issues/new?template=request-a-feature.md) for this, as it's difficult keep track of lots of different things in one thread.
