### ISSUE TITLE
Title on Countdown

### ISSUE THREAD

**Issue by xsovietbear** [EssentialsX/Essentials#2468]
### Feature request

**Feature description**

Title for commencing teleportation. For example, if I type /home, an title would appear on my screen with a countdown instead the boring chat message.

**How the feature is useful**

It is useful for players if they want to know how many seconds passed from the command and the actual teleport, also would increase the server design and originality.

**Comment by kennyrkun** [comment]
It would not increase server originality, because every server running Essentials would have this feature.

I don't think this is useful, and I think it would become annoying quickly.

If this is implemented, I believe it should be optional by way of the configuration.

**Comment by drtshock** [comment]
Things like this would always be configurable if implemented.

**Comment by mdcfe** [comment]
I don't see a need for this within EssentialsX itself - if we add the necessary API events, this could be easily implemented within a separate plugin. As far as I know, to use the title API you need to depend on the actual Spigot API, whereas we're currently depending on their updated Bukkit API.

**Comment by mdcfe** [comment]
Closing in favour of #2506.
