### ISSUE TITLE
Add player variable to TPPos.

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#2470]
Would it be possible to add a player variable to the tppos command? So you can force players to a specific coordinate in a specific world via console commands that auto-replace a %player% placeholder with the player name?

i.e.

``/tppos <x> <y> <z> [yaw] [pitch] [world] [player]``

With a condition if [player] is used, don't teleport yourself -- check for that player instead.

**Comment by Leomelonseeds** [comment]
Couldn’t you use /tp [player] (x y z)?

**Comment by pop4959** [comment]
The command that Leomelonseeds mentioned should work fine. If you still insist that this should be in Essentials itself, feel free to make a PR.
