### ISSUE TITLE
EssentialsXGeoIP cannot detect local host's (127.0.0.1) IP address

### ISSUE THREAD

**Issue by axemwa** [EssentialsX/Essentials#2471]
### Feature request

**Feature description**
**EssentialsXGeoIP cannot detect local host's (127.0.0.1) IP address**, if that is the case when ppl join via localhost then to either not display the "User is from (country)" message when they join (since it cannot be tracked when joining via localhost), or to change it so that it says
something like "User joined from localhost." or "User joined from an unknown location."
or even an option to select between the two cause atm it displays
"User is from ." which confuses ppl.

Unless there's a way it can track the users IP regardless of joining via local host then maybe that instead because it would be good if the country from where the user joined gets displayed whether they join form localhost or not

**Comment by ghost** [comment]
if a user joins from 'localhost', it's impossible to find their external IP address, so unfortunately the most I could do is offer a message saying the user's country could not be found.

my changes are offered in https://github.com/EssentialsX/Essentials/pull/2494

**Comment by mdcfe** [comment]
This has now been implemented in b4baa28f01a6e40a76a2c24e1b57fad1a97102ad - you can download the latest version from the [build server](https://ci.ender.zone/job/EssentialsX).

Thanks @latiku for the PR!
