### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by ShredRum** [EssentialsX/Essentials#2473]
[Google Translate]
Hey. Today I have a need to fix whois for myself by removing the player’s coordinates from there. To do this, I downloaded the sources, installed BuildTools according to the instructions, and for the sake of interest I made the test compilation of the plugin unchanged. As a result, I received an error:
[ERROR] D: \ BuildTools \ apache-maven-3.6.0 \ bin \ Essentials \ src \ com \ earth2me \ essenti
als \ OfflinePlayer.java: [39,7] error: OfflinePlayer is not abstract and does not
override abstract method setRotation (float, float) in Entity
Since I use maven for the first time - most likely the problem is in me. Help me solve it, please. Thank.
OS: Win 7 x32, Java (JRE & JDK 1.8.0_201)

**Comment by ShredRum** [comment]
Screenshot http://prntscr.com/n8i323

**Comment by mdcfe** [comment]
This is quite common - often Spigot updates and causes the build process to break. I'll update the source soon.

For now, if you're using an IDE like IntelliJ IDEA or Eclipse, you should be able to generate the missing methods by opening EssentialsX's `OfflinePlayer` class and implementing the missing methods.

**Comment by ShredRum** [comment]
Thanks a lot, now I can forbid players to watch the coordinates of other players in whois!

**Comment by mdcfe** [comment]
This has been fixed by 3d97e93831f56450762f41b816321a30ede5a1b1 - you can download the latest source and it should now compile without error.
