### ISSUE TITLE
Invisible usernames

### ISSUE THREAD

**Issue by Cobwebster** [EssentialsX/Essentials#2479]
If I use /nick &a it just gives me a empty name, given &a are accepted characters but when u go to type its just blank.

example,

https://images-ext-1.discordapp.net/external/mlBEdOUy0jKKDKRbZIQwHAvjs0o0m-TzfFllct312Tk/https/cdn.discordapp.com/attachments/400328165870010370/565186533506809856/2019-04-09_15.48.30.png?width=501&height=313

**Comment by kennyrkun** [comment]
I can't reproduce this behaviour with EssentialsX 2.16.1.0 -- inputting `&a` alone for /nick gives me the error `Error: Nicknames must be alphanumeric`. 

As far as I'm aware there is no configuration option to allow the use of blank nicknames or non-alphanumeric characters, even with `essentials.nick.allowunsafe`.

Perhaps you're running an outdated version?

**Comment by mdcfe** [comment]
@Cobwebster Could you get the output of `/ess version` as requested in the template?

**Comment by Cobwebster** [comment]
> @Cobwebster Could you get the output of `/ess version` as requested in the template?

EssentialsX version: 2.16.1.0

Probably a little dated.

**Comment by Cobwebster** [comment]
Ah, looks like another plugin is causing this. sorry guys.
