### ISSUE TITLE
/shop error

### ISSUE THREAD

**Issue by Alex802c** [EssentialsX/Essentials#2482]
### Information

Full output of `/ess version`:

**Server log:** 
https://pastebin.com/2PzEE9eV

**EssentialsX config** 
https://pastebin.com/cRENvHDS
### Help request

**Problem**

/shop doesn't work. I use GuiShop+ and essentials are somehow blocking /shop "Error: that warp does not exist" please help

**What I have tried**

Scrolled through the intire confiq 100 times. My eyes are bleeding
**Screenshots**

**Comment by mdcfe** [comment]
EssentialsX doesn't interfere with the `/shop` command. Are you sure you didn't set up an alias in Bukkit's `commands.yml`?

**Comment by triagonal** [comment]
Closed due to lack of response.
