### ISSUE TITLE
Kit Cooldown not showing up

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#2483]
### Help request

**Problem**
Already used kit is not showing up, by that I mean the kit name is not in strikethrough.

**What I have tried**
Different EssentialsX versions, but those which work mess up the item ID's with other plugins.

**Screenshots**
![image](https://user-images.githubusercontent.com/11699611/56086165-97007280-5e59-11e9-834f-74d74de2c477.png)

**Comment by ghost** [comment]
Duplicate.

#2301

**Comment by mdcfe** [comment]
Closing as a duplicate of #2301 - it's easier to keep one issue updated.
