### ISSUE TITLE
Allow players to look around without cancelling teleport

### ISSUE THREAD

**Issue by mdcfe** [EssentialsX/Essentials#2485]
### Feature request

**Feature description**
Allow players to look around during the teleportation warmup, without cancelling their teleport. This could be behind a config option to avoid changing existing behaviour.

**How the feature is useful**
It can be frustrating for players to not be able to even move their mouse until they teleport.

Requested in the Discord by `Thomoski#1154`.

**Comment by caojohnny** [comment]
Isn't there a permission to disable this?

**Comment by mdcfe** [comment]
There's `essentials.teleport.timer.move`, but this just lets anyone move around during the teleport delay.

However, it appears EssentialsX doesn't actually consider the head rotation at all when determining whether players can move, so this feature request appears to be moot.
