### ISSUE TITLE
Inconsistent saving of NPC UUID -> name

### ISSUE THREAD

**Issue by leonardo-dgs** [EssentialsX/Essentials#2490]
I want to reopen the inconsistencies regarding UUID -> name saving of NPCs, exposed in the issue #2016, because that inconsistency can happens with every plugin that uses NPCs, not only with Towny.
I think that should be done a converter for existing NPCs, and put a setting in the file `upgrades-done.yml`.

**Comment by pop4959** [comment]
I'm not sure I follow this issue entirely, but md mentioned Essentials does not use online-mode UUIDs for NPCs, so I don't believe there should be any issue. If there is, then it's probably more or less the responsibility of that other plugin. Not sure that Essentials (or any other plugin really) has the responsibility to manage fake profiles.

**Comment by leonardo-dgs** [comment]
> I'm not sure I follow this issue entirely, but md mentioned Essentials does not use online-mode UUIDs for NPCs, so I don't believe there should be any issue. If there is, then it's probably more or less the responsibility of that other plugin. Not sure that Essentials (or any other plugin really) has the responsibility to manage fake profiles.

@pop4959 the plugins that handles the NPCs can't do anything to fix that, and this happens even if online mode is true, because in the `usermap.csv` the names are saved with name as key and UUID as value, and NPC names aren't prefixed with `NPC:` in `usermap.csv`, so if a player joins the server with a name that is equal to that of one NPC, the NPC's UUID is replaced (in `usermap.csv`) with that of the player.

**Comment by mdcfe** [comment]
NPC accounts are awkward, but upon rereviewing I think we should look into the impact of having an `NPC:` prefix in the usermap. The main issue that comes to mind is that there are many cases where NPC accounts are created for economy purposes, and as it may be possible to access them by name alone we need to avoid making existing NPC accounts inaccessible when we make this change.

**Comment by JRoy** [comment]
Hello, this issue has been mitigated in recent EssentialsX dev builds!

If you currently have damaged data, you can read more about the steps you can take to fix this and prevent further issues of this sort [here](https://github.com/EssentialsX/Essentials/issues/3956#issuecomment-779254544).

Download the latest dev build [here](https://essentialsx.net/downloads.html).
