### ISSUE TITLE
[Question] How to spawn Charged Creeper with /spawnmob command.

### ISSUE THREAD

**Issue by GewoonLeonYT** [EssentialsX/Essentials#2491]
How do I spawn a Charged Creeper with the /spawnmob command?

**Comment by triagonal** [comment]
You can spawn in mobs with mob data using `/spawnmob [mob]:[data]` - in this case, you would use `/spawnmob creeper:powered`, or `/spawnmob creeper:charged`.

**Comment by triagonal** [comment]
Closing - question seems to be resolved.

**Comment by Redstone91210** [comment]
?

**Comment by LeZ-Firm** [comment]
you can use /minecraft:summon creeper ~ ~ ~ {powered:1}

**Comment by Redstone91210** [comment]
Or /spawnmob creeper:powered or /spawnmob creeper:charged.

**Comment by Redstone91210** [comment]
This is about Essentials.

**Comment by Redstone91210** [comment]
`/spawnmob creeper:charged` or `:powered` may be old data now and might not work for Essentials / EssentialsX 1.17.
