### ISSUE TITLE
Double Bed - /Home goes to Spawn

### ISSUE THREAD

**Issue by trentnbauer** [EssentialsX/Essentials#2492]
### Information

**Full output of `/ess version`**:

```
ess version=> [00:44:54 INFO]: CONSOLE issued server command: /ess version
[00:44:54 INFO]: Server version: 1.13.2-R0.1-SNAPSHOT git-Paper-618 (MC: 1.13.2)
[00:44:54 INFO]: EssentialsX version: 2.16.1.0
[00:44:54 INFO]: LuckPerms version: 4.3.73
[00:44:54 INFO]: Vault version: 1.7.1-b91
[00:44:54 INFO]: EssentialsXChat version: 2.16.1.0
[00:44:54 INFO]: EssentialsXSpawn version: 2.16.1.0
```

**Server log**: https://gist.github.com/xardoniak/4ca2296aff566cc65d49f5cc1f298519

**EssentialsX config**: https://gist.github.com/xardoniak/5ad6c425e7d54f1e1f389f153f6af683

### Details

**Description**  
When sleeping in a double bed, the /home command is reset to spawn. After removing and replacing a single bed, /home then works as expected

**Steps to reproduce**  
Place double bed, sleep in it. Type /home and you will end up at spawn
Remove both beds, place just 1. Type /home and you will end up next to the bed

**Expected behavior**  
/home going to bed

**Screenshots**

**Comment by darbyjack** [comment]
Could not replicate this bug. Following the steps provided above, I placed down a double bed, which then when I slept in it, set my Bed Home. After doing /home it proceeded to take me to the bed and not the spawn.

**Comment by trentnbauer** [comment]
Will try to replicate the issue again and let you know. Maybe something weird on my end

**Comment by triagonal** [comment]
Closing as the issue couldn't be replicated. If you're still experiencing this problem, feel free to reply to this thread.
