### ISSUE TITLE
Human Readable Banner colors

### ISSUE THREAD

**Issue by chexo3** [EssentialsX/Essentials#2493]
### Feature request

**Feature description**

Human readable banner meta color

**How the feature is useful**

Just add the ability to refer to colors in banners by their [DyeColor](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/DyeColor.html)

**Comment by jvdoorn** [comment]
I'm on it 😃

**Comment by chexo3** [comment]
Oh nice. I forgot about this. Thank you for your help!

**Comment by pop4959** [comment]
Closing as duplicate of #123, which also suggests both banner colors + meta tags.
