### ISSUE TITLE
Add teleport warmup event to API

### ISSUE THREAD

**Issue by mdcfe** [EssentialsX/Essentials#2506]
### Feature request

**Feature description**
An event called when teleport warmups start.

**How the feature is useful**
This would allow other plugins to listen to the event and add their own functionality (like #2468).

**Comment by triagonal** [comment]
Implemented in #2590.

**Comment by mdcfe** [comment]
#2590 doesn't implement this despite its name - it adds an event that is called between the end of the warmup and the teleport safety checks, which is... not particularly useful. I'm considering reverting this and adding two events in their place, a `TeleportWarmupEvent` (before the warmup) and a `PreTeleportEvent` (in place of that PR's event). The `PlayerTeleportEvent` implemented in #2590 is largely useless in its current form.
