### ISSUE TITLE
Essentials Private Chat

### ISSUE THREAD

**Issue by Platinteufel** [EssentialsX/Essentials#251]
1. Since I've updated to the latest dev build yesterday I can't read private messages from Admins, even I denied them the permission - -essentials.chat.spy.exempt a few weeks ago. It worked on build #194.
2. Since one of the latest dev builds essentials says
   [Sender] ist gerade nicht da und antwortet wahrscheinlich nicht. [German]
   In English (roughly): [Sender] is afk right now and probably doesn't reponse.

instead of: [Receiver] is afk right now and properly doesn't reponse.

**Comment by SupaHam** [comment]
1. I'm going to say that's a permission issue on your end. It has not been touched since build 194.
2. This was fixed in Build 215

**Comment by Platinteufel** [comment]
Are you sure you didn't touch it since build 194 @drtshock ?
It worked until I've updated from this build to the latest dev, so it can't be a permission problem.

**Comment by SupaHam** [comment]
Okay, I lied, there was a very irrelevant change, one whitespace addition to the line that has the check. So still my statement stands, it probably is a permissions error on your end.

a844e8b is the commit in which the whitespace was added.

**Comment by Platinteufel** [comment]
You're right, just tested it again and it's working now. Seems like I messed up some permissions. Sorry.
