### ISSUE TITLE
Enderchest Vanish bug

### ISSUE THREAD

**Issue by Roux84** [EssentialsX/Essentials#2511]
Found a Bug in Essentials/Essentials/src/com/earth2me/essentials/commands/Commandenderchest.java

If an admin is in Vanish you can still open the enderchest when he is online. On invsee its fixxed but on enderchest not.

**Comment by pop4959** [comment]
Not able to reproduce this issue. Can you fill out the bug report template fully, please?

**Comment by kennyrkun** [comment]
Also unable to produce this bug on the latest released version.

**Comment by triagonal** [comment]
Closing due to lack of response (and apparent inability to reproduce).
