### ISSUE TITLE
/jump goes through vanilla world border

### ISSUE THREAD

**Issue by Leomelonseeds** [EssentialsX/Essentials#2512]
This is a bug report/feature request.

The /jump command can currently teleport you right through the vanilla world border. Maybe make a detection and/or togglable option for that?

Thanks.

**Comment by pop4959** [comment]
I don't think it's a bug, but adding some sort of check sounds possible. Jump isn't the only command that can let a player teleport through the border though, as most other teleportation commands can also do this (such as tppos). So I think a good question would be whether this is a good feature to add to teleportation in general.

Just out of curiosity, what is the use case? I'm not trying to shoot you down, but I can't think of any reason why this particular feature request would be relevant, off the top of my head. Why would servers want to toggle this?

**Comment by Leomelonseeds** [comment]
Going past the worldborder can have many negative effects for a server, even if block placing and breaking is disabled.

For starters, it can cause many new chunks which were previously unfilled with the WorldBorder pre-gen feature to be loaded, causing server lag.

Land claiming plugins will normally not have a check for claiming past the worldborder, posing a problem with unraidable land.

Going far past the worldborder may even raise disk space issue, as the world beyond is massive.

I made this issue because /jump is a command a normal player would have, while other commands like /tppos a normal player would not have.

Thank you for your quick reply and consideration.

**Comment by willjallen** [comment]
#2518

**Comment by willjallen** [comment]
This can now be toggled with the permission
essentials.jump.pastWorldBorder

**Comment by Xeyame** [comment]
> This can now be toggled with the permission
> essentials.jump.pastWorldBorder

Once #2518 has been merged, @Leomelonseeds can download the latest build from [here](https://ci.ender.zone/job/EssentialsX/)

**Comment by mdcfe** [comment]
To clarify: this is **not in the plugin yet**. @willjallen has written the code for it, but it is not part of EssentialsX yet and needs several changes before we can add it.

**Comment by Leomelonseeds** [comment]
Alright, thanks for your hard work guys.

**Comment by Andre601** [comment]
I personally see it as somewhat of a bug that you can TP outside of the Worldborder while not in spectator (Which is the only way you can get past the WB without teleportation in vanilla).

I find it even weirder, that the vanilla TP command teleports you straight to the coordinates defined, while /tppos for example is capped at 1 block after the WB (i.e. `/tppos 6000 100 6000` in a world with a 5000 radius WB teleports you to 5001 100 5001)

Again do I personally see it as a bug (Perhaps even an MC bug that is) that you can teleport past the worldborder while not being in spectator or something...
Would appreciate if a setting or perm could be implemented to prevent this.

**Comment by pop4959** [comment]
@Andre601 As of a relatively recent version of Essentials, the world border is counted towards the teleportation safety mechanic. That is to say that a player that would die by being teleported beyond the border will be teleported to safety in the case that they attempt to. If they're in creative / god mode, etc, of course, they will be able to teleport past the world border.

I'm not sure what you mean with spectator, but it sounds like it may be unrelated to this issue and if so, you should probably create a new one for this.

Can you confirm whether the teleportation safety with world borders addresses the concerns presented by the OP?

**Comment by Andre601** [comment]
Due to the setup of my server can I not check this without severe changes to the perm system.

But I'm pretty sure that the system *should* work. But again can I sadly not check this.

**Comment by Andre601** [comment]
I would like to give the little note, that vanilla borders themself seem to be very odd sometimes.

When I, for example, have a WB set to 7501, so that it aligns with the edges of the blocks, can I go one block further out on one direction, but not the other. In my case was this with positive X. Probably a bad rounding thing or something? Because setting the centre again fixes this...
Just a little FYI.

Funny enough does Essentials now no longer teleport me outside of the WB but instead, keep me inside of it. Did you add this perm-functionality in a recent commit, or is that just a weird coincidence?

**Comment by pop4959** [comment]
Nothings been changed, it's probably just the same rounding issue that occurs with the vanilla border. As long as the final location is safe, everything should be correctly working.
