### ISSUE TITLE
Essentials Signs not working on 1.14

### ISSUE THREAD

**Issue by motelcoconut** [EssentialsX/Essentials#2514]
The title says it all. On Spigot 1.14, signs do not work. I have tried [Warp], [Buy], and [Sell] and nothing happens when you right click them. They were working fine on 1.13.2. I assume this has to do with there being new signs in 1.14. There is no exception on the console. They just don't do anything.

**Comment by robimoli** [comment]
Me too, any solution?

**Comment by delocura** [comment]
Any solution?

**Comment by triagonal** [comment]
> Any solution?

The solution is to wait until EssentialsX has been fully updated to support 1.14. You can follow update progress at #2510.

**Comment by ghost** [comment]
I did my own alteration, the problem is on the MaterialUtil, you need to change the old IDs Sign to new IDs Sign

**Comment by mdcfe** [comment]
@Jonasslv This was fixed in the 1.14 branch a while ago, but I'm keeping this issue open until the 1.14 branch is ready for experimental builds.

**Comment by BrandonAdduci** [comment]
@Jonasslv Where did you change the sign IDs? Sorry, I don't really know much about this stuff and would like to fix the issue.

**Comment by ghost** [comment]
> @Jonasslv Where did you change the sign IDs? Sorry, I don't really know much about this stuff and would like to fix the issue.

Actually you dont need to change anything, just download the snapshot version of essentials 1.14 that they made available

**Comment by ElectricFreak** [comment]
Nevermind, using experimental version now and sign are working. Thanks

**Comment by BrandonAdduci** [comment]
@Jonasslv Just saw that after digging around a bit more. Thanks, sign are working again :D

**Comment by jwandel** [comment]
> @Jonasslv Just saw that after digging around a bit more. Thanks, sign are working again :D

Could you send me a link to that? I'm having trouble finding it.

**Comment by md678685** [comment]
This has been fixed in the latest experimental build for 1.14.x - you can download it from the [build server](https://ci.ender.zone/job/EssentialsX-Experimental).

**Comment by iTheCuteKitten** [comment]
Would also like a link to that... signs aren't working at all. (necropost???)

**Comment by mdcfe** [comment]
@jwandel @iTheCuteKitten You can download experimental builds for 1.14.x [here](https://ci.ender.zone/job/EssentialsX-Experimental/).
