### ISSUE TITLE
Can't reload config using /ess , no matter the permissions

### ISSUE THREAD

**Issue by WoophRadu** [EssentialsX/Essentials#2522]
### Information

**Full output of `/ess version`**:
```
04.05 22:46:15 [Server] Server thread/INFO Server version: 1.14-R0.1-SNAPSHOT git-Spigot-1eece4f-68e72f6 (MC: 1.14)
04.05 22:46:15 [Server] Server thread/INFO EssentialsX version: 2.16.1.153
04.05 22:46:15 [Server] Server thread/INFO LuckPerms version: 4.4.17
04.05 22:46:15 [Server] Server thread/INFO Vault version: 1.7.2-b107
04.05 22:46:15 [Server] Server thread/INFO EssentialsXSpawn version: 2.16.1.153
04.05 22:46:15 [Server] Server thread/INFO EssentialsXChat version: 2.16.1.153
04.05 22:46:15 [Server] Server thread/INFO EssentialsXGeoIP version: 2.16.1.153
04.05 22:46:15 [Server] Server thread/INFO You are running an unsupported server version!
```

**Server log**: https://gist.github.com/WoophRadu/18b82d649cd708c1f0f5b1855bd885a2

**EssentialsX config**: https://gist.github.com/WoophRadu/ee33d2da8c810b6b62853fa8597ae346

### Details

**Description**  
I can't run the /ess command, no matter the permissions.

**Steps to reproduce**  

1. Have perm: essentials.*

2. Run command: /ess reload

3. You don't have perm.

It doesn't even work if you have the wildcard '*' permission.

**Expected behavior**  
I should be able to reload the config if I have essentials.* or some other permission (idk which).

**Screenshots**  
Not necessary.

**Comment by Xeyame** [comment]
Could you try running `/ess debug` from console, then `/ess reload` ingame, and post the output from the console here?

**Comment by WoophRadu** [comment]
```
04.05 23:50:28 [Server] Server thread/INFO checking if Wooph has essentials.mail - true
04.05 23:50:28 [Server] Server thread/INFO checking if Wooph has essentials.essentials - false
04.05 23:50:28 [Server] Server thread/INFO Wooph was denied access to command.
```

After adding essentials.essentials to my group it worked. It seems like essentials.essentials is not included in essentials.\* somehow? I tested both with LuckPerms and with GroupManager, behaviour is the same.
