### ISSUE TITLE
essentials.keepinventory (on death)

### ISSUE THREAD

**Issue by Goldenphelix** [EssentialsX/Essentials#2524]
### Feature request

**Feature description**
A perm node that serves kinda the same purpose as /gamerule keepInventory 
but it tracks only the players with the node.
"essentials.keepinventory"
Allows the user to keep their inventory on death, instead of dropping it.

(Very similar to essentials.keepxp)

**How the feature is useful**
To have certain players be able to keep their inventory on death without having to effect the whole server with the /gamerule keepInventory
Perhaps server owners could give this node as a reward to certain players or rank benefits.

**Comment by lostinikea** [comment]
I dont understand. What do i type????????????

**Comment by MasterDavodXLPRO** [comment]
use the permission keepitems.keep or check another plugin
