### ISSUE TITLE
Armour Stripping Command

### ISSUE THREAD

**Issue by RazihelYT** [EssentialsX/Essentials#2525]
**Feature description**

I want to suggest adding a command to strip a player of their armour and put it in the player's inventory.
**How the feature is useful**

Authorized users such as staff members of a server would be able to run the command on the targeted user and strip them of their worn armour. In events such as PvP or minigames based on pvp or pve and a user is suspected of cheating by auto-equipping armour, an authorized user may run the command on the targeted user and see if the target user is using auto-armour cheats.

**Comment by mdcfe** [comment]
This sounds like a feature for an anticheat plugin, which EssentialsX is not. Could you elaborate on how this is useful outside countering cheaters?

**Comment by pop4959** [comment]
This seems overly specialised for Essentials. In addition, with the lack of response I assume this isn't too important of an issue to anyone. There are probably also already anticheat or pvp plugins that provide this already.
