### ISSUE TITLE
Spigot-1eece4f-6ceffb0 (MC: 1.14) - spigot-1.14-b2280 BlockBreakEvent to Essentials v2.16.1.169-mc114-b86

### ISSUE THREAD

**Issue by minecraft7net** [EssentialsX/Essentials#2529]
BlockBreakEvent to Essentials v2.16.1.169-mc114-b86

https://pastebin.com/yxpqzy5k

**Comment by Straikerinos** [comment]
This problem is only on signs that perform command for eg. [Warp], [Buy], and more.

**Comment by EnderCjh** [comment]
This happens to me but instead of just those signs it is every sign that is placed or broken

**Comment by mdcfe** [comment]
This has been fixed in the latest experimental build for 1.14.x - you can download it from the [build server](https://ci.ender.zone/job/EssentialsX-Experimental).
