### ISSUE TITLE
Spigot-1eece4f-6ceffb0 - b2280 - AsyncPlayerChatEvent to Essentials v2.16.1.169-mc114-b86

### ISSUE THREAD

**Issue by minecraft7net** [EssentialsX/Essentials#2530]
AsyncPlayerChatEvent to Essentials v2.16.1.169-mc114-b86

https://pastebin.com/vPD0xFUx

**Comment by mdcfe** [comment]
Closing in favour of #2545, which is the same bug as this but with a different stack trace.
