### ISSUE TITLE
Just a question that doesnt seems to be listed anywhere

### ISSUE THREAD

**Issue by Nextshot** [EssentialsX/Essentials#2537]
/homes is a command that is supposed to list the homes of the player on the chat so he can remember each, but that doesnt seems to be working that way, /homes works as /home home

Iam doing something wrong ?

**Comment by mdcfe** [comment]
If you only have one home called "home", then running `/home` will teleport to it. `/homes` is an alias of `/home`, so does the same thing.

**Comment by Nextshot** [comment]
But /homes shouldnt list all the homes that a player have set ?

**Comment by mdcfe** [comment]
It should if they have multiple homes, but if they only have one it should just teleport them to it.

**Comment by Nextshot** [comment]
True, I didnt know why I had such a doubt even thought I didnt tested it (I tought that I did it earlier and it didnt work, thanks :))
