### ISSUE TITLE
My configs for the warp delay time doesn't work.

### ISSUE THREAD

**Issue by Joseph0430** [EssentialsX/Essentials#2538]
The warp delay is clearly set as 4, but neither the console nor the play in-game waits 4 seconds before actually warping or tp-ing.

```
# The delay, in seconds, required between /home, /tp, etc.
teleport-cooldown: 4

# The delay, in seconds, before a user actually teleports. If the user moves or gets attacked in this timeframe, the teleport is cancelled.
teleport-delay: 4

# The delay, in seconds, a player can't be attacked by other players after they have been teleported by a command.
# This will also prevent the player attacking other players.
teleport-invulnerability: 4

# Whether to make all teleportations go to the center of the block; where the x and z coordinates decimal become .5
teleport-to-center: true
```
edit by @triagonal: fixed code formatting

**Comment by Joseph0430** [comment]
This is the full config. (Changed to txt from yml to upload)
[config (2).txt](https://github.com/EssentialsX/Essentials/files/3171174/config.2.txt)

**Comment by triagonal** [comment]
The console doesn't take delay into account when warping or teleporting other players. 

This could be caused by your permission settings. If you're opped or have `'*'` in your permissions, then you're inheriting `essentials.teleport.timer.bypass` which bypasses the teleport delay. Could you double check to make sure your permissions are correct?

**Comment by Joseph0430** [comment]
where are the permissions?

**Comment by Joseph0430** [comment]
I'm using Spigot, and the permissions in the config file when i deop myself, and doesn't work even if i set use-bukkit-permissions to false. Every command i use says you do not have access to this command when i'm deopped.

**Comment by triagonal** [comment]
Right, but if you're opped then you'll inherit the bypass permission. I've found that permissions changes (for `player-commands` permissions) sometimes require a server restart / player relog to take effect. Try setting up your permissions via `player-commands` in the config, restarting, and then trying it again.

**Comment by Joseph0430** [comment]
alright, thanks.
