### ISSUE TITLE
Help for developing a plugin that uses money!

### ISSUE THREAD

**Issue by AwesomeKalin** [EssentialsX/Essentials#2540]
Help! I use gradle and I need to make a plugin for my server that uses EssentialsX and WorldGuard to make hotels and houses to rent and buy. Have any idea?

**Comment by triagonal** [comment]
Information on using EssentialsX as a dependency in your project can be found in the README: https://github.com/EssentialsX/Essentials#using-essentialsx-in-your-plugin

**Comment by AwesomeKalin** [comment]
Thank you
