### ISSUE TITLE
Add Permission to limit /speed

### ISSUE THREAD

**Issue by Phreag** [EssentialsX/Essentials#255]
I would suggest to add a permission to change the max speed a user is allowed to set by himself.

Because i want to give /speed to player on a creative world, but if they are flying around with speed 10 it causes lags. Speed 5 is quite okay.

If you could add this it would be awesome.

**Comment by drtshock** [comment]
Isn't there already a config setting for this?

**Comment by Phreag** [comment]
Ohhh...

Now i understood how it works O.o
Sorry, can be closed :P
