### ISSUE TITLE
New feature: Armor on /kits and space in the inventory

### ISSUE THREAD

**Issue by Xm4g1kZzXj0k3** [EssentialsX/Essentials#2552]
Hi.
for now, when i use the command /createkit, the armor slot are not considered and space position in the inventory are ignored.
![Cattura](https://user-images.githubusercontent.com/50754984/57957145-9c8b2580-78fb-11e9-96ae-0dc1d21d8728.PNG)

I think that can be a helpful get a kit with items in the same position of when i create it, and with the same armor/head.

Waiting the status update :)

Thanks for work.

**Comment by pop4959** [comment]
Closing in favor of #347
