### ISSUE TITLE
Add tropical fish base/pattern colour to /spawnmob

### ISSUE THREAD

**Issue by mdcfe** [EssentialsX/Essentials#2554]
### Feature request

**Feature description**
Add entries to `MobData` to allow spawning tropical fish with different base colours and pattern colours, as you can currently only pick the pattern and not the colours of the fish.

**How the feature is useful**
Colourful fish!

**Comment by pop4959** [comment]
Possible now that the raiders branch (which also fixed and added many more features to spawnmob) has been merged.
