### ISSUE TITLE
Items not dropping on death

### ISSUE THREAD

**Issue by YourCoal** [EssentialsX/Essentials#2559]
### Information

**Full output of `/ess version`**:
EssentialsX version: 2.16.1.156

**Server log**:
NO ERRors show up
https://gist.github.com/YourCoal/e720555e0c88b57596a661e257678c19

**EssentialsX config**:
default generated by plugin

### Details

**Description**  
When EssentialsX is installed, items do not drop when the player dies.

**Steps to reproduce**  
Install EssentialsX. Kill yourself, or die normally. Items do not drop.

**Expected behavior**  
When you die, items should drop.

As far as I could tell, there was no setting to change to toggle this.

**Comment by Xeyame** [comment]
Are you sure players do *not* have the permission essentials.keepinv?

If anyone can confirm this happening too, we should roll back #2531

**Comment by mdcfe** [comment]
This should not happen by default. If this started happening when you updated, you're probably using wildcard permissions which we do not support.

Run `/ess debug` then try killing yourself again and give us the full console output on death.

**Comment by YourCoal** [comment]
This appears to be an issue with being OP (reference: https://www.spigotmc.org/threads/ops-keep-there-items-on-death-essentialsx.374456/ )

I ended up getting this fixed using the dev bulilds from https://ci.ender.zone/job/EssentialsX-Experimental/ build 95 (EssentialsX-2.16.1.180-mc114-b95)

**Comment by mdcfe** [comment]
@YourCoal Those builds don't include the latest features, including `essentials.keepinv`, and those builds should not be used in production.

Could you update to the [latest stable build](https://ci.ender.zone/job/EssentialsX) and check whether you still have the permission when opped?

**Comment by YourCoal** [comment]
It looks like it gives all OPs the keepinv perm, happens in latest build

/ess debug output: https://pastebin.com/8wk1kaUS

**Comment by mdcfe** [comment]
You're using Bukkit permissions without a permissions plugin installed. We don't officially support this, so there isn't anything we can do to help.

Use a permissions plugin like LuckPerms for proper permissions management.
