### ISSUE TITLE
Prefix in Playerlist is still shown

### ISSUE THREAD

**Issue by NickCloudAT** [EssentialsX/Essentials#2562]
### Information

**Full output of `/ess version`**:
Server version: 1.8.8-R0.1-SNAPSHOT git-PaperSpigot-"4c7641d" (MC: 1.8.8)
EssentialsX version: 2.16.1.156
LuckPerms version: 4.4.1
Vault version: 1.6.7-b${env.TRAVIS_BUILD_NUMBER}
EssentialsXSpawn version: 2.16.1.156
EssentialsXChat version: 2.16.1.156
```
<!-- Run the command in your console, and copy and paste the whole output here -->
```

### Details

**Description**  
I disabled "add-prefix-in-playerlist" but the prefix is still shown in the tablist

**Steps to reproduce**  
Pretty obv I think

**Expected behavior**  
Prefix should not be shown in tablist

**Screenshots**  
http://prntscr.com/ntdd5n

**Comment by mdcfe** [comment]
You didn't include a copy of your config as requested in the template. Could you paste your config on [Gist](https://gist.github.com) then post the link here?

**Comment by Xeyame** [comment]
Are you sure it's not another plugin doing this? Also did you reboot your
server (as you might just be doing /ess reload). Sending a full startup log
might help finding the cause too.

**Comment by NickCloudAT** [comment]
> You didn't include a copy of your config as requested in the template. Could you paste your config on [Gist](https://gist.github.com) then post the link here?

Sorry forgot: https://pastebin.com/YXAPKmf6
And startup log: https://pastebin.com/be9rn1Qb

**Comment by pop4959** [comment]
Doesn't seem like anyone else has been able to confirm this issue. If it's still a problem for you, feel free to re-create this, with more (and updated) information, including if you are using other plugins when this happens.

**Comment by NickCloudAT** [comment]
I would like to re-open this issues.

It still happens to me on paperspigot 1.15.2.

I will try to paste all information here:

Essentials config: https://public.nickcloud.at/paste/?f0da288eff76eff2#J2ZkLVboDQ5yAYwzQPxoninmfaBcsdy771wRr685sQwP

Startup log: https://public.nickcloud.at/paste/?cd875d59dde7166e#HiXM82F9jDMGJpXDbt7J4soqdpsHpVH51tn31htG8nn5

Essentials version command: https://prnt.sc/r37hqm

Plugins installed: Essentialsx/Spawn/Chat, Vault, Luckperms

There are no errors.

If anything else is needed, I will provide it.

**Comment by JRoy** [comment]
Can this still be reproduced?
