### ISSUE TITLE
Error on tabcomplete

### ISSUE THREAD

**Issue by EvilOlaf** [EssentialsX/Essentials#257]
The discussion about this issue started quite a while ago (see  related issues at the report below) and neither BanManager nor PermissionsEx had an answer for this. As a few times suggested maybe Essentials has a final answer for this.

https://github.com/BanManagement/BanManager/issues/444

tl;dr: If you run Spigot 1.8 with Essentials(X), BanManager and PermissionsEx and try to use tab completion of usernames on a BM command an error gets thrown where Essentials also interferes.

Thanks for reading.

**Comment by SupaHam** [comment]
Could you please paste your Essentials config?

I've tried using `/ban`, `/bminfo`, `/unban` with tab completion, and they work just fine with essentials.

**Comment by EvilOlaf** [comment]
http://pastebin.com/ESiPegnN

Tried to reproduce a few minutes ago and failed too. 
I could not perfectly replicate this issue earlier though.

**Comment by SupaHam** [comment]
Essentials config looks solid. What about a list of plugins.

**Comment by Kakifrucht** [comment]
I'm also running both Essentials and BanManager and I can't reproduce neither. Might be something very specific.

**Comment by JANEXLEBJAKOT** [comment]
Have this problem. 
PluginList:
http://puu.sh/lawNp/044691b22f.png

**Comment by Kakifrucht** [comment]
@JANEXLEBJAKOT we share lots of plugins. Maybe Protocollib is interfering somehow?

**Comment by mdcfe** [comment]
Closing, as tab completion has been properly implemented so this should no longer be an issue.
