### ISSUE TITLE
[Feature] Implement a + sign for enchants

### ISSUE THREAD

**Issue by maxlehot1234** [EssentialsX/Essentials#2570]
### Feature request

**Feature description**
Implement something that allow server owners to add + XYZ enchant on a player.
I mean, we can use external plugins to make a GUI, sell the enchant with money for example and in-hand item of the player will get + XYZ enchant.
EX:
Player have a pickaxe with fortune 5 and want to add +10 fortune on it, so in the GUI I configure a +5 and +10 options.
The commands will looks like this:
./enchant fortune +1
./enchant fortune +5
When the player buy 2x fortune +5 he will now have fortune 15 on his pickaxe .

**How the feature is useful**
This will allow op server like prison or any other server type to implement a new way to add enchants on items and this will also allow us to create a lot more things.

Implementing this option allow us to have a better control for enchants and maybe reduce the use of external plugins.

That was my idea and hope this will be implemented :)

Thanks again and have a nice day/night to you and the team

**Comment by caojohnny** [comment]
Honestly I think this is too specific of a use case to justify being in Essentials.

**Comment by pop4959** [comment]
I agree with AgentTroll on this, as I don't think this feature is required. Not only that, but it's extremely niche, and enchanting is already extremely limiting as it is (unless you consider unsafe enchants). This is more suited for a custom plugin.
