### ISSUE TITLE
i cant find the perms

### ISSUE THREAD

**Issue by TKGHocine** [EssentialsX/Essentials#2575]
so when a player use for ex bow he say u dont have perms to use bow not just bow all items plz give me the perms 
that's all ur plugin is really good plz speed i need them

**Comment by Xeyame** [comment]
`/ess debug` shows the permissions when its looked up

**Comment by TKGHocine** [comment]
no dont work
:(

**Comment by Xeyame** [comment]
It probably isn't essentials blocking item usage. Use luckperms and `/lp verbose`

**Comment by TKGHocine** [comment]
nn its work
thx u

**Comment by TKGHocine** [comment]
i see it in the console
thx

**Comment by TKGHocine** [comment]
u will just deop u and do /ess debug and go to console and u will se the perms u dont have thats all :) thx
@Xeyame
