### ISSUE TITLE
Add 1.14.x items to items.json

### ISSUE THREAD

**Issue by mdcfe** [EssentialsX/Essentials#2576]
### Feature request

**Feature description**
Add 1.14.x items to `items.json` to allow them to be spawned in.

**How the feature is useful**
It lets players spawn in 1.14.x items using EssentialsX's commands and kits.

~~you know I'm starting to this this second part of the template is a little bit useless~~

**Comment by mdcfe** [comment]
https://gist.github.com/md678685/b89735ec1dcf4d5f1769add0fbe481c4 contains a 1.14 items.json generated by the old `genItemsFlat` tool. We could use this in the short term?

**Comment by mdcfe** [comment]
Experimental builds now include a combination of `genItemsFlat`'s and `ItemDbGenerator`'s outputs.

**Comment by YourCoal** [comment]
Question... is there somewhere we are suppoed to manually place an updated items.json in? Because it does not auto-generate the items.json with 1.14 items in it. I was going to submit a feature request but saw this, so I'd rather keep it to here since it's the same thing.

**Comment by mdcfe** [comment]
You can delete the `items.json` from the Essentials folder to force it to update, but it *should* have updated by itself when you updated EssentialsX (unless you edited it).

**Comment by YourCoal** [comment]
I deleted it and it updated... I never edit that scary file so not sure why it didn't update. Thanks!
