### ISSUE TITLE
Money suffix

### ISSUE THREAD

**Issue by korhox** [EssentialsX/Essentials#2577]
### Feature request

**Feature description**
Possibility to set suffix instead of/and prefix for money formatting.

**How the feature is useful**
Money is formatted in US and some other countries like $100. However, in Finland and other EU contries money is formatted like 100 €.

In our server we are using money unit markka (Old Finnish money unit) wich is shortened as mk. It would be very nice to have possibility to set this.

**Comment by gelsbern** [comment]
What I did was made the prefix blank and then insert the $ in front of  the format.  So far it seems to work

currency-symbol: ''

#currency-format: "$#,##0.00"

**Comment by AMDBartek** [comment]
I would like this feature as well.
