### ISSUE TITLE
Make /jump not go thru blocks

### ISSUE THREAD

**Issue by Sikatsu** [EssentialsX/Essentials#2580]
### Feature request

**Feature description**
Since we already have /thru to go thru blocks, I was hoping /jump wouldn't go thru blocks or atleast that it is configurable.

**How the feature is useful**
I would like to give the /jump permission to certain players as the one in WorldEdit (/jumpto) is not limited in terms of distance blocks you can jump too.

**Comment by pop4959** [comment]
The command teleports you onto the block that your cross-hair is on. This would probably introduce other issues, and I don't think this is a concern for most people. If you have areas that are meant to be impassible, there are other plugins that will ensure this for you.
