### ISSUE TITLE
Option for /spawn to bypass safety check

### ISSUE THREAD

**Issue by wellnesscookie** [EssentialsX/Essentials#2583]
### Feature request

**Feature description**
Create an option in config to bypass  safety-teleportation check on /spawn command and force tp players to the exact location of /setspawn execution place.

**How the feature is useful**
This would enable server owners to create specific spawns where you can be dropped off an aeroplane, a balloon or zeppelin and make it cool, but still have safety check stick you to the ground on any other kind of teleportation, F.E: /tpahere.

**Comment by caojohnny** [comment]
Wasn't there a config option so you could disable the safety check entirely? Or do you only want it for /spawn?

**Comment by wellnesscookie** [comment]
@AgentTroll

Yes, I meant only for /spawn. There is the global check, but what I asked for was individual spawn setting for it. Wanted to drop players from a plane without making any other teleportations unsafe.

**Comment by pop4959** [comment]
This is a bit too much of a specialised use case for Essentials to handle. You can probably use a custom command / function / plugin to teleport the player if you absolutely need this.
