### ISSUE TITLE
Allow home list from console

### ISSUE THREAD

**Issue by FabioZumbi12** [EssentialsX/Essentials#2584]
### Feature request

**Feature description**
I just want to be able to list all player homes from console!

**How the feature is useful**
I know we already have the in-game command `/<command> [player:]<name>` and using `/<command> [player:]` + TAB i can list all player homes, but not from console.

**Comment by darbyjack** [comment]
Closing because it doesn't make sense to create a tab completion for a command that can't be ran in that logistical instance from console.

**Comment by pop4959** [comment]
In addition to what Glare mentioned, I discovered that you can actually list a player's homes through `/delhome` (since console is permitted to delete homes). It will not list homes in `/home` because console can't use the command.
