### ISSUE TITLE
/unlimited per-item permissions not working

### ISSUE THREAD

**Issue by Cldfire** [EssentialsX/Essentials#259]
So for /unlimited, you're supposed to be able to grant 'essentials.unlimited' in order to give access to the command, and then individual items with 'essentials.unlimited.item-[id]'.

However, I've found that upon giving my users access to 'essentials.unlimited', it gives them access to every single blocktype, no matter what I grant (or don't grant) with 'essentials.unlimited.item-[id]'.

Removing the 'essentials.unlimited' permission prevents the user from even using /ul, no matter what I grant via 'essentials.unlimited.item-[id]'.

/ess debug revealed that Essentials is only checking if the user has the 'essentials.unlimited' permission; it's not checking for the individual item permissions. I even negated 'essentials.unlimited.*', and it still allowed for unlimited anything.

It would be great to see this fixed, as it renders /ul completely useless.

**Comment by SupaHam** [comment]
Did you set `permission-based-item-spawn` to `true` in your config.yml?

**Comment by Cldfire** [comment]
Hmm, don't remember having to do that in the past. That sounds like it's it, though. 

All the 'bugs' I find turn out to be user error :(

EDIT: Yep, that was it. Thank you SupaHam.
