### ISSUE TITLE
ServerListPingEvent

### ISSUE THREAD

**Issue by DesperoKF** [EssentialsX/Essentials#2592]
full output of `/ess version`: https://hasteb.in/owogetig.md

**Server log:** https://hasteb.in/majajiva.md

**EssentialsX config** https://hasteb.in/sovofowu.yaml

### Help request

**Problem**

Could not hide vanished players while handling org.bukkit.event.server.ServerListPingEvent
**What I have tried**
Restart server. Newest Version from EssentialsX

**Screenshots**

**Comment by mdcfe** [comment]
This is caused by CloudNet triggering a server list event - I'll look into this and see whether we should ignore CloudNet or submit a fix on their end.

**Comment by mdcfe** [comment]
This has now been fixed - you can download the latest version from the [build server](https://ci.ender.zone/job/EssentialsX).
