### ISSUE TITLE
Buy, Sell, Balance does not work

### ISSUE THREAD

**Issue by dragoxdk** [EssentialsX/Essentials#2594]
My server Running the last spigot update.
CraftBukkit version git-Spigot-df0eb25-411609d (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT

Your version:
Essentials reloaded 2.16.1.0.

Error:
I have use some Signs for years now.
But after updating to 1.14.2 the Signs does not work anymore.

tp, tpa, tpaccept works fine (text)
Jail works fine (text)

Im using sell, buy, balance signs. - [sell] / [buy] / [balance]
None of them is working anymore.
Can fine create them, and the code line will be Blue.
But nothings happen, when i right click on the signs.

So right now, the Shop is not working on my servers :-)
Let me know, if you need anything more

**Comment by dragoxdk** [comment]
This is the log, when starting/restarting the server:

12.06 08:32:56 [Server] Server thread/INFO [Essentials] Enabling Essentials v2.16.1.0
12.06 08:32:56 [Server] Server thread/ERROR [Essentials] You are running an unsupported server version!

**Comment by packetSent** [comment]
The plugin is not compatible with MC 1.14 yet.

**Comment by triagonal** [comment]
There are [experimental builds](https://ci.ender.zone/job/EssentialsX-Experimental) available at the build server that restore sign support on 1.14+.

Updating to an experimental build should fix your issue.

**Comment by triagonal** [comment]
EssentialsX now supports 1.14 as of the `2.17.0` update (and fixes this issue). If you're still running the experimental builds, please [update to the latest version of EssentialsX.](https://essentialsx.github.io/#/)
