### ISSUE TITLE
home command tab completion

### ISSUE THREAD

**Issue by rybuilder23** [EssentialsX/Essentials#2595]
### Information

**Full output of `/ess version`**:

 Server version: 1.14.2-R0.1-SNAPSHOT git-Paper-76 (MC: 1.14.2)
13.06 08:16:12 [Server] INFO EssentialsX version: 2.16.1.191-mc114-b103
13.06 08:16:12 [Server] INFO LuckPerms version: 4.4.24
13.06 08:16:12 [Server] INFO Vault version: 1.7.2-b107
13.06 08:16:12 [Server] INFO EssentialsXGeoIP version: 2.16.1.191-mc114-b103
13.06 08:16:12 [Server] INFO EssentialsXSpawn version: 2.16.1.191-mc114-b103

### Details

**Description**  
/home tab completion not working.

**Steps to reproduce**  
when i use the tab funtion i get /home (playername) (homename)

**Expected behavior**  
i expected /home (homename)

**Screenshots**  
http://prnt.sc/o18v1v
http://prnt.sc/o18vck

**Comment by triagonal** [comment]
This occurs if you have the permission node `essentials.home.others` (which allows a user to travel to other player homes) - if you only want your homes to be available for tab completion, you should revoke or negate this node.
