### ISSUE TITLE
Hardcap speed

### ISSUE THREAD

**Issue by Sikatsu** [EssentialsX/Essentials#2596]
**Feature description**
Within the configuration i've set the max fly speed to 0.2. However they are still able to use /speed 10 (which is definatly faster then /speed 2)

It would be nice if there was a way that if a player uses a value higher then the one in the configuration, it says the player doesn't have a permission for it.

**How the feature is useful**
Some ranks on my server have a speed perk, but /speed 10 is wayy too fast and causes insane chunk loading lag. With a hardcap players won't be able to bypass the maximum speed set in the configuration.

> #Set the max fly speed, values range from 0.1 to 1.0
> max-fly-speed: 0.2

> #Set the max walk speed, values range from 0.1 to 1.0
> max-walk-speed: 0.3

**Comment by Sikatsu** [comment]
Testing as an operator against a player restricted to the configuration value, we both have the same speed, which makes me wonder if that setting even applies in the first place.

**Comment by mdcfe** [comment]
`max-[fly|walk]-speed` act as a multiplier for the speed, not as limits for the `/speed` argument. `/speed 10` when the config setting is set to `1.0` will be 5 times as fast as `/speed 10` when the setting is set to `0.2`.

**Comment by Sikatsu** [comment]
@md678685 Is this something that could be changed in a more logical way? What should I do if I want them to be just a BIT faster then the default fly speed? Because on 0.2, their speed is still insane. 

That would also mean this setting applies to operators? Because operators and players have the same speed.
