### ISSUE TITLE
Custom Messages not work

### ISSUE THREAD

**Issue by DevJoey** [EssentialsX/Essentials#2598]
Iam using a Linux server and on this, the custom Messages dosent Work.
i have set the locale to en and put a message_de.properties in the plugin folder. after a restart the plugin is english and not german. on my windows pc all works fine. 

Please Fix!

I have used this tutorial: https://www.youtube.com/watch?v=9Uan2oJ9zK8

**Comment by mdcfe** [comment]
The official EssentialsX translation guide can be found [on the wiki](https://essentialsx.github.io/#/Locale?id=switching-language).

Did you change the `locale:` setting in your `config.yml` file? You need to change it to `locale: de` and remove the `#` before it.

**Comment by DevJoey** [comment]
Thanks that de was the problem. Thank you very much!
