### ISSUE TITLE
color don't work

### ISSUE THREAD

**Issue by leoncp9** [EssentialsX/Essentials#2603]
this is photo of config
https://prnt.sc/o2gamj

this is photo on game
https://prnt.sc/o2gan4
Why i set &f✦, but i see on game &b✦ ?

**Comment by montlikadani** [comment]
You should use the "✦" symbol converted to UTF-8: `\u2726`

Or this not helps then you need to put the name to a "" (cat nail), such as:
`- iron_sword 1 name:"&f\u2726_&e&l..._&f\u2726"`

**Comment by leoncp9** [comment]
ok i will try

**Comment by leoncp9** [comment]
photo https://prnt.sc/o2ho4e
first symbol don't work

this is my config
https://prnt.sc/o2hoer

**Comment by montlikadani** [comment]
Then use the original format for symbol with "" mark:
`- iron_sword 1 name:"&f✦_&e&l..._&f✦"`

**Comment by leoncp9** [comment]
my config https://prnt.sc/o2i15t
my game https://prnt.sc/o2i14x
i don't need to see "" on game, is possible remove ""??

**Comment by montlikadani** [comment]
Last option: Remove the "" mark from name and put the `&r` before the &f color.

**Comment by leoncp9** [comment]
ok now work
