### ISSUE TITLE
EssentialsXGeoip player join notification is inconsistent with player names, can this be made configurable?

### ISSUE THREAD

**Issue by axemwa** [EssentialsX/Essentials#2607]
### Feature request

**Feature description**
I noticed that the EssentialsXGeoip player join notification is inconsistent with player names, can this be made configurable? By inconsistent I mean 1st time I join it says "Player shano_dekono (default minecraft name) comes from (country)", 2nd time I join it says "Player ShAnO(essentials nickname) comes from (country)", third time I join it says "[Owner] ShAnO (display name including prefixes and suffixes if set) comes from (country)", rinse and repeat.

It would be good if the name type were configurable so that it was more consistent and didn't confuse people

**How the feature is useful**
If this feature was added it would lessen confusion between both players and staff/admin in case a players default name is similar to another players nickname or display name, for example the wrong players could get banned by accident due to a similar name or something.

It would also look more professional and consistent for server owners so that both players and staff know who is and isn't staff when they join. 

EDIT - It would also be extra cool if certain text symbols could be added to the players name on the join message/from country message as well. Symbols such as these below for cool effects when they join

[radioactive] -> ☢
[peace] -> ☮
[moon] -> ☾
[crown] -> ♔
[note] -> ♩
[snowman] -> ☃
[tools] -> ⚒
[swords] -> ⚔
[warn] -> ⚠

**Comment by mdcfe** [comment]
The bug appears to be the same as #2388 - please don't open duplicate issues.

We won't be adding symbols, but you can already use Unicode escape codes to add them to `messages.properties`.

**Comment by axemwa** [comment]
Oh crap sorry I forgot I already opened an issue for this, my bad
