### ISSUE TITLE
Pay issue?

### ISSUE THREAD

**Issue by Johandrex** [EssentialsX/Essentials#261]
It's possible to pay users 0 cash with "/pay {user} 0.00001"

**Comment by Kakifrucht** [comment]
This can be quite annoying

**Comment by SupaHam** [comment]
I'll add a configurable minimum amount you can pay.

**Comment by EvilOlaf** [comment]
:+1:

**Comment by SupaHam** [comment]
0a876c3

**Comment by Kakifrucht** [comment]
Thanks, appreciated!
