### ISSUE TITLE
Include arguments in muted commands

### ISSUE THREAD

**Issue by TheNoobWar** [EssentialsX/Essentials#2610]
### Feature request

**Feature description**
Currently with the most recent version of EssentialsX on 2.16.1.214, there's no configuration permitted to include muted commands and any of their arguments. I believe if the option is available to include arguments it can be even more handy with chat commands from other popular plugins.

**How the feature is useful**
This feature can be useful as a popular chat plugin such as Herochat, which uses shortened commands like `/g <message>` to speak in global can be circumvented when a user has been muted through Essentials even with the configuration set to block `/g`. As Essentials does not include arguments being blocked, these users can circumvent the mute with `/g <message>`, as `/g` by itself does not execute a message event.

**Comment by pop4959** [comment]
This should probably be implemented in the other plugin(s) by checking Essentials mute via the API, or via contexts (see #2960) if/when implemented.

**Comment by mdcfe** [comment]
FYI you *should* be able to add the command under `mute-commands:` in `config.yml` to block the command and any arguments that follow it.
