### ISSUE TITLE
Ability to make Per Group Cooldowns and Warmups

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#2618]
### Feature request

The ability to make cooldowns and warmups per permission group

With per group cooldowns server owners could make it so different permission groups have different cooldowns. An example of this being useful is the warmup for teleports. I want my staff to instantly tp with /tp but still have a cooldown for /tpa. this is not possible as far as I can tell because there is only one configuration for all teleport commands. An example it could be implemented in the config is below

How it is right now:

command-cooldowns:
     feed: 100

How it could be implemented:

command-cooldowns:
     feed:
            default:  20
            vip: 10

**Comment by pop4959** [comment]
I don't think there is interest currently as the existing cooldowns work well enough. The only reason I can think of for this is server monetisation, which is not an important issue for Essentials.

Keep in mind that there is a tpo (tp override) command that staff can use if you do not want them to have the same delay for that command. Also cooldowns are not required on a server, and so consider removing them if they are impairing your intended game play.
