### ISSUE TITLE
console errors

### ISSUE THREAD

**Issue by ronc617** [EssentialsX/Essentials#2620]
Console errors running the latest spigot 1.14.3 and EssentialsX-2.16.1.215. https://pastebin.com/KqQGAfup

**Comment by crashdemons** [comment]
also this on startup: https://pastebin.com/G0U9UPam
although I didn't expect this to work immediately by any means since it's not officially supported yet.

**Comment by YourCoalAlt** [comment]
Getting this when joining the game: https://pastebin.com/83r3RjF5

And this when trying to type /killall drops (though spams errors for any command it looks like) https://pastebin.com/aAqQxKY9

**Comment by mdcfe** [comment]
This has now been fixed - you can download the latest version from the [downloads page](https://essentialsx.github.io).
