### ISSUE TITLE
[Error] EssentialsX Permission webpage missing essentials.home

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#2625]
### Information

**Full output of `/ess version`**:
Error not on a server.

```

```

**Server log**: Error not on a server.

**EssentialsX config**: Error not on a server.

### Details

**Description**  
To use the "/home" command, you need the "essentials.home" permission node. The [EssentialsX permission webpage](https://essinfo.xeya.me/index.php?page=permissions) does not list this permission node as being required.

The original [Essentials permission page](http://wiki.mc-ess.net/doc/permissions) does list this permission node as being required for "/home".

**Steps to reproduce**  
Check https://essinfo.xeya.me/index.php?page=permissions and use the filter.

**Expected behavior**  
List the "essentials.home" permission node on the [EssentialsX permission webpage](https://essinfo.xeya.me/index.php?page=permissions) for "/home".

---
Though deductive reasoning about permission node formatting may reveal the solution (or knowing to check the original essentials wiki), it is not easily apparent when referencing the EssentialsX webpage permissions list.

**Screenshots**  
None required.

**Comment by Xeyame** [comment]
Added, thanks for noting!

**Comment by ghost** [comment]
Thank you!
