### ISSUE TITLE
1.14.3 - all commands broken

### ISSUE THREAD

**Issue by sportshead** [EssentialsX/Essentials#2626]
## Information

Full output of `/ess version`: _All commands including `/ess version` are broken, cannot get output_
EssentialsX file name: EssentialsX-2.16.1.215.jar
EssentialsX version: 2.16.1.215

[Server log & EssentialsX config](https://gist.github.com/sportshead/efabc9b3ee183001a4d2d7afe6b50ed0)

### Problem
When trying to execute commands, console returns first while typing command: `An internal error occurred while attempting to tab-complete this command`
After hitting <kbd>enter</kbd>, console returns `An internal error occurred while attempting to perform this command`

### What I have tried

- [ ] Restarting server -- fail

### Screenshots

[Video of attempted `/gamemode creative`](https://streamable.com/jz3io)

**Comment by triagonal** [comment]
EssentialsX supports 1.14.3 as of version `2.16.1.216` - you're one build behind. Grab the latest build from [the build server](https://ci.ender.zone/job/EssentialsX/) and your issue should be fixed.

**Comment by sportshead** [comment]
Fixed! Thanks a lot. Didn't realize there was a new update
