### ISSUE TITLE
Bug with invsee commnad: deleted items

### ISSUE THREAD

**Issue by DrewLickman** [EssentialsX/Essentials#2627]
I've been hosting a server for the past couple days with my friends, and sometimes I would use /invsee to check what they have. Unfortunately, sometimes an item from my or their inventory is completely deleted, including enchanted items which really sucks. I'm afraid I don't know the cause since the bug doesn't happen every time, but please try to fix it. (1.14.2)

**Comment by mdcfe** [comment]
Please fill out the [appropriate issue template](https://github.com/EssentialsX/Essentials/issues/new/choose).
