### ISSUE TITLE
Allow changing the inv title of [disposal] through the sign

### ISSUE THREAD

**Issue by Andre601** [EssentialsX/Essentials#2628]
### Feature request

**Feature description**

Allow players (that perhaps also have permission for it like `essentials.disposal.rename`) to rename the inventory-title of the `[Disposal]` sign by adding the name to the lines in the sign (See image for example).

**How the feature is useful**

PR #2461 added an option for server owners (or devs) to rename the default inventory-title through the properties file of essentials.
However this is limited to the just mentioned owner or devs and is only one title.
Perhaps some players want to have an own (funny) title to show instead of the "Disposal" title.
Something like "Black hole".

**Images**
Here is an image that would show how it looks like on a sign.
First line is the default `[disposal]` text while second (And maybe 3rd and 4th) line is for the name.
![image](https://user-images.githubusercontent.com/11576465/60217087-2b308200-986c-11e9-8964-042039863f4c.png)

----
Another Idea that just came to mind is to add a payment option for using disposal (if that isn't already a thing.)
When a player would click on a disposal sign (that perhaps has the price set on the 4th line) EssentialsX would tell them that they have to pay X mones to use it. The player could then rightclick again to confirm it or let it time out.

**Comment by ghost** [comment]
\>Paid disposal
...are Mojang planning to make items undestroyable any time soon or what?

**Comment by ghost** [comment]
Will start working on this anyway, if it's not already taken by someone else.

**Comment by Andre601** [comment]
> \>Paid disposal
> ...are Mojang planning to make items undestroyable any time soon or what?

Maybe some server owners want to have players pay to use disposal? Anything is possible and I saw quite a few cases like this.

**Comment by mdcfe** [comment]
This has now been added - you can download the latest version from the [EssentialsX website](https://essentialsx.cf/downloads.html).
