### ISSUE TITLE
Running Customtext Outputs an Internal Error and Spams Console

### ISSUE THREAD

**Issue by Wpgradford** [EssentialsX/Essentials#2629]
### Information

Full output of `/ess version`:

Server version: 1.14.3-SNAPSHOT git-Spigot-4d2f30f-f1f3355 (MC: 1.14.3)
EssentialsX version: 2.17.0.1
LuckPerms version: 4.4.1
Vault version: 1.7.2-b107
EssentialsXProtect version: 2.17.0.1
EssentialsXChat version: 2.17.0.1
EssentialsXSpawn version: 2.17.0.1
You are running an unsupported server version!

**Server log:** https://gist.github.com/Wpgradford/f407a202f8c5c5428a19d936d948530b

**EssentialsX config:** https://gist.github.com/Wpgradford/c414de184c0804869ac02bda4e80e5f4

### Help request

**Problem**
Whenever the /customtext command was executed, it sent back an internal error and spammed console.

**What I have tried**
I've reset the custom.txt file, including deleting it and uploading a new one. Nothing seems to change the outcome. I'm not entirely sure if this is a bug or something I've done wrong.

**Comment by Wpgradford** [comment]
Update: I seem to have fixed the issue, no idea if it's a temporary fix or a permanent one. I backed up all of Essentials' files, then removed it from the server. When I opened the server again, Essentials reinstalled and it fixed the issue! I reuploaded my old & edited Essentials files and everything seems to be working fine. I'll update again if the issue comes back, but for now, it seems to have fixed itself.

**Comment by Wpgradford** [comment]
Update: Customtext works until you edit it, then it spits out an internal error. It's unclear whether or not commands.yml has any impact, but it seems as if it may.

**Comment by mdcfe** [comment]
Could you post your `commands.yml` file? It looks like you've created a self-referential alias - your `customtext` alias is just running itself over and over.

In addition, you need to update Spigot to a newer version.

**Comment by Wpgradford** [comment]
Oh, you're absolutely right, I did. Thanks for the help! I hadn't even considered that!
