### ISSUE TITLE
Sign arent working

### ISSUE THREAD

**Issue by CrazyAfro** [EssentialsX/Essentials#2630]
The current problem I have is that the sign shops aren't working. I have enabled the signs in the .congif and it tells me they're working by becoming blue but they wont output the command 'buy' and 'sell' commands. I 'm unsure if I have done anything wrong.
im currently hosting my server on 1.14.3

https://gist.github.com/CrazyAfro/51d54c7cf6d64cbd7a35f433b009fe29

**Comment by mdcfe** [comment]
Please post your **full config, startup log and the output of `/ess version`**.

**Comment by CrazyAfro** [comment]
<script src="https://gist.github.com/CrazyAfro/51d54c7cf6d64cbd7a35f433b009fe29.js"></script>
28.06 16:38:19 [Server] Server thread/INFO Server version: 1.14.3-R0.1-SNAPSHOT git-Bukkit-e8b39d4 (MC: 1.14.3)
28.06 16:38:19 [Server] Server thread/INFO EssentialsX version: 2.16.1.0
28.06 16:38:19 [Server] Server thread/INFO PermissionsEx version: 1.23.4
28.06 16:38:19 [Server] Server thread/INFO EssentialsNicknameAddon version: 1.1
28.06 16:38:19 [Server] Server thread/INFO Vault version: 1.7.2-b107
28.06 16:38:19 [Server] Server thread/INFO EssentialsXChat version: 2.16.1.216
28.06 16:38:19 [Server] Server thread/INFO EssentialsXGeoIP version: 2.16.1.0
28.06 16:38:19 [Server] Server thread/INFO EssentialsXAntiBuild version: 2.16.1.0
28.06 16:38:19 [Server] Server thread/INFO EssentialsXSpawn version: 2.16.1.0
28.06 16:38:19 [Server] Server thread/INFO EssentialsXXMPP version: 2.16.1.0
28.06 16:38:19 [Server] Server thread/INFO EssentialsXProtect version: 2.16.1.0
28.06 16:38:19 [Server] Server thread/INFO Version mismatch! Please update all Essentials jars to the same version.
28.06 16:38:19 [Server] Server thread/INFO You are running unsupported plugins!
28.06 16:38:19 [Server] Server thread/INFO You are running an unsupported server version!

**Comment by mdcfe** [comment]
> EssentialsX version: 2.16.1.0

You need to update EssentialsX to the [latest version](https://essentialsx.github.io/#/) which supports 1.14.3.

In addition, the `EssentialsNicknameAddon` plugin is unnecessary - EssentialsX lets you do this with its own [colour permissions](https://essentialsx.github.io/#/Color-Permissions).
