### ISSUE TITLE
I have given permissions to build in group manager and it works for awhile then takes permissions away

### ISSUE THREAD

**Issue by TheJediGamer** [EssentialsX/Essentials#2632]
### Information

Full output of `/ess version`:

**Server log:** 

**EssentialsX config** 

### Help request

**Problem**
I have given permissions to build in group manager and it works for awhile then takes permissions away

**What I have tried**
 Giving the groups the permission and it works for about an hour then doesnt allow it again

**Screenshots**

**Comment by montlikadani** [comment]
GroupManager is not supported anymore. So, you need to use LuckPerms.

**Comment by mdcfe** [comment]
You didn't fill in the template.

We don't support GroupManager. If you're having issues with it, we can't provide any support.
