### ISSUE TITLE
A Player Who Doesn't Have essentials.afk.auto and Has essentials.kick.exempt Spams Console

### ISSUE THREAD

**Issue by Wpgradford** [EssentialsX/Essentials#2633]
### Information

Full output of `/ess version`:

Server version: 1.14.3-SNAPSHOT git-Spigot-4d2f30f-f1f3355 (MC: 1.14.3)
EssentialsX version: 2.17.0.1
LuckPerms version: 4.4.1
Vault version: 1.7.2-b107
EssentialsXProtect version: 2.17.0.1
EssentialsXChat version: 2.17.0.1
EssentialsXSpawn version: 2.17.0.1
You are running an unsupported server version!

**Server log:** https://gist.github.com/Wpgradford/d4da4a7ae0881aa69915bfa3bb4eabd2 (Ignore everything but the spam, it's from a since-resolved issue!)

**EssentialsX config:** https://gist.github.com/Wpgradford/c414de184c0804869ac02bda4e80e5f4

### Help request

**Problem**
Console spams checking if a player has essentials.afk.auto and essentials.kick.exempt if they cannot be automatically made AFK and they can't be kicked for remaining AFK for too long. Of course, this can be removed with a 'no console spam' plugin, but that would be a workaround. Nothing shows up in the chat in-game, so this is only a console issue.

**What I have tried**
I have reloaded essentials using /ess reload, but that's the extent of it.

**Comment by mdcfe** [comment]
Run `/ess debug` to stop EssentialsX logging permissions to the console.
