### ISSUE TITLE
Set respawn point to a set /home rather than bed.

### ISSUE THREAD

**Issue by OverlordFreddo** [EssentialsX/Essentials#2636]
### Feature request

**Feature description**

Config option to force respawning to someone's /home rather than /spawn or their bed.
respawn-at-home: true
**How the feature is useful**

When someone dies, they will respawn at their /home rather than some random bed or /spawn

**Comment by pop4959** [comment]
This wouldn't work because you can have more than one home. How are they supposed to specify this? A config option isn't valid for this.

**Comment by mdcfe** [comment]
EssentialsX does have the config of a "default home" - running `/sethome` or `/home` with no arguments sets/teleports to the home called `home`. However, as pop mentioned above having a config option for this is confusing to the user.
