### ISSUE TITLE
Multiple messages when jailed: "You do the crime, you do the time."

### ISSUE THREAD

**Issue by vcdf** [EssentialsX/Essentials#2637]
### Information

**Full output of `/ess version`**:

```
Server Version: 1.13.2-R0.1-SNAPSHOT git-Spigot-1a3504a-84f3da3 (MC: 1.13.2)
EssentialsX Version: 2.17.0.0
Vault Version: 1.7.2-b107
```

**Server log**: https://gist.github.com/vcdf/4d0d8813ffcde0ba0ba48bec047ee451

**EssentialsX config**: Default config file, nothing changed

### Details

**Description**  
Players get multiple "You do the crime, you do the time." messages when logging in or throwing enderpearls. This happens when Multiverse (newest version, but also for old ones) is installed.

**Steps to reproduce**  
Run fresh Spigot installation with only EssentialsX, Vault and Multiverse. Create a test jail. Jail a player. Make them throw enderpearls or relog.

**Expected behavior**  
One jail message per action, like per login, attempted command or thrown enderpearl.

**Comment by bxzrre** [comment]
can confirm this happens with Multiverse, but not without. seeing if I can look into it now

**Comment by pop4959** [comment]
This is almost certainly a problem with Multiverse. Not sure what could cause it (perhaps throwing duplicate events), but this should be brought up with the developer of that plugin. Nothing in EssentialsX appears as if it should cause this.
