### ISSUE TITLE
buy / sell signs with prices from worth.yml (not player-editable prices)

### ISSUE THREAD

**Issue by HAL9081** [EssentialsX/Essentials#2638]
### Feature request

**Buy / Sell - Signs that respect the worth.yml**

For a working economy, buy and sell signs seem totally useless right now.
Why are they designed that players can write their own prices to it, when there is
a worth.yml available?

I know that worth.yml is for the /sell command - but why not for signs?
The trade sign is very useful. But I would like that my players can use buy and sell signs
that read and fill prices from the worth.yml. (and don't let players set prices)

**How the feature is useful**

Scenario:
- Minecraft server with economy
- starting balance = 0
- don't want the players to have to use commands (like /sell)
- players can make their own sell sign
- easy selling with right click on sign / any item in hand / stack or single (with prices from worth.yml)
- op's can make buy signs / define item / stack or single / prices taken from worth.yml
- trade signs are fine =)

Thank you for reading. And again: sell / buy signs are useless right now when you want to run an economy based on the worth.yml

Best regards
HAL

**Comment by mdcfe** [comment]
The intention is for server staff to set up these signs where appropriate, not players. 

If you want to control buy/sell rates on signs, create a central shop area that players can warp to.

`worth.yml` is only used for the `/sell` command.

**Comment by HAL9081** [comment]
then buy and sell signs and worth.yml are useless. why you want to do this? why not make essentialsx better this way? can you please consider this as a suggestion and discuss about it.

**Comment by HAL9081** [comment]
you see - why should staff edit prices every time when it could be read from worth.yml.
why should I be forced to build central shops, when it would be nice when players can build shops everywhere they want. it would contribute so much more when this would be available.

**Comment by HAL9081** [comment]
... and you would stand out from all other plugins. I can't even find a plugin with this feature. Every plugin I seek requires / gives the player to set own prices. Why? That is not logical when you want to use worth.yml.
I don't want players to sell 1 dirt for a 1.000.000 bucks. I want them to be able to set up sell or buy signs by themselves (creating little shops all over the world) with prices read from worth.yml - an easy feature with great potential!

**Comment by HAL9081** [comment]
sorry for spamming but. if you love your signs the way they are, then please add signs with this function.
for example [wsell] [wbuy] - why the holdback? this is a big great idea!

**Comment by mdcfe** [comment]
They aren't useless; they just don't match your particular use case.

The code that makes Essentials signs work is old and complicated. While I don't oppose the feature, it would be difficult to implement this with the current signs code.

**Comment by HAL9081** [comment]
Then I humbly ask for this feature here. Pleeaase :o) stand out from other plugins and do it.

**Comment by Technoguyfication** [comment]
+1 this feature request. It would be nice to use /setworth to change item values and have signs in the admin shop update the price on their own (even if the update doesn't happen until the next person clicks it, etc.). I'm still getting my server's economy balanced and this feature would be great.

**Comment by pop4959** [comment]
I don't really agree with this change, nor would it be easy to do anything like this. It would almost certainly involve needing to store every trade sign in the world, which is not ideal. I don't think this implementation would be appropriate for Essentials.

**Comment by mdcfe** [comment]
There isn't any central shop system in Essentials currently, and #2795 doesn't appear to be active any more. If this were to be implemented then I'd rather it was done as part of an overhaul of the `worth.yml` and signs system.

**Comment by Techno3600** [comment]
+1. Would love to see this happen.

**Comment by moxventura** [comment]
I've created a PR which might offer a solution. It does basically this:
> +1 this feature request. It would be nice to use /setworth to change item values and have signs in the admin shop update the price on their own (even if the update doesn't happen until the next person clicks it, etc.). I'm still getting my server's economy balanced and this feature would be great.

I added configuration settings which, by default, keep the original behaviour the same.

**Comment by JRoy** [comment]
See #3367 for close reason
