### ISSUE TITLE
[Enhancement] Kit signs to tell cooldown (delay)

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#2642]
### Feature request

**Feature description**
When a player has already used a kit sign, where the kit has a delay/cooldown set,  and there is a cooldown remaining, inform the player of the remaining time.

The /kit command already informs the player of the remaining time.

**How the feature is useful**
Currently, the sign does not inform the player of the remaining time, and it seems as if the sign is useless. Adding this would make it less confusing for players.

----

Additionally, I think there should be a command to reset the kit cooldown that a player may have, as listed in [this](https://github.com/EssentialsX/Essentials/issues/163) suggestion. Sometimes if an admin is configuring a kit, or even changing a kit, there could be a need to reset the cooldown for a player.

**Comment by uf0h** [comment]
This feature currently exists and is working on the latest build `EssentialsX-2.17.1.12`. 

[gif of it working](https://gyazo.com/9ef08ac34133a864d0aa8857ed4488ce)

Make sure you are using the latest build and have given players the correct permission to use kit signs `essentials.signs.use.kit`.

**Comment by pop4959** [comment]
Closing this issue for now, unless the author returns with more information about it not working on the latest version.
