### ISSUE TITLE
Essentials Signs not working??

### ISSUE THREAD

**Issue by LorenBear** [EssentialsX/Essentials#2643]
I cant seem to get the signs to work, I have not set up permissions & don't plan to just because it's only a small server for me and friends. I've enabled the sign types in the config but they don't seem to do anything at all. I am running 1.14.2 if that helps and yes I also have vault.

**Comment by triagonal** [comment]
Please post your **full config, startup log and the output of `/ess version`** as the template asks. Upload the required information to https://gist.github.com/ and post the link(s) here.

**Comment by Goreator** [comment]
Same problem here could be a bukkit problem if you use it.

**Comment by mdcfe** [comment]
@Goreator Please open a separate issue, following the issue template provided.

**Comment by triagonal** [comment]
Closing due to insufficient information.

> 
> 
> Please post your **full config, startup log and the output of `/ess version`** as the template asks. Upload the required information to https://gist.github.com/ and post the link(s) here.

Please reply to the thread with the above information if you still require assistance.
