### ISSUE TITLE
EssentialsTimer Error

### ISSUE THREAD

**Issue by CaszGamerMD** [EssentialsX/Essentials#2652]
### Information

03.07 22:28:07 [Server] INFO Server version: 1.14.2-R0.1-SNAPSHOT git-Paper-94 (MC: 1.14.2)
03.07 22:28:07 [Server] INFO EssentialsX version: 2.16.1.178-mc114-b93
03.07 22:28:07 [Server] INFO LuckPerms version: 4.4.1
03.07 22:28:07 [Server] INFO Vault is not installed. Chat and permissions may not work.
03.07 22:28:07 [Server] INFO You are running an unsupported server version!

**Server log**: https://gist.github.com/CaszGamerMD/a64992e6501d12c64ab843179b937898

**EssentialsX config**: https://gist.github.com/CaszGamerMD/1ea520a56c42db5e1cb039c0dea8c12b

### Details

**Description**  
https://pastebin.com/dVnuNEjU

**Steps to reproduce**  

**Expected behavior**  

**Screenshots**

**Comment by mdcfe** [comment]
> 2.16.1.178-mc114-b93

You need to [update to the latest build](https://ci.ender.zone/job/EssentialsX/) - 1.14 support has been completed and merged into normal builds, and so we don't support the experimental builds any more.
