### ISSUE TITLE
EssentialsX night skipping

### ISSUE THREAD

**Issue by da-jacob** [EssentialsX/Essentials#2653]
### Information

Full output of `/ess version`:
Server version: 1.14.3-R0.1-SNAPSHOT git-Spigot-935adb3-a0e4747 (MC: 1.14.3) 
EssentialsX version: 2.17.0.0 
PermissionsEx version: 1.23.4 
Vault version: 1.7.2-b107 
EssentialsXSpawn version: 2.17.0.0 
EssentialsXChat version: 2.17.0.0 
You are running unsupported plugins! 

**Server log:** (nothing unusual) https://gist.github.com/CreativGraphics/0977c06c907f881accbb46a56fdbaea3

**EssentialsX config** Default config

### Help request

**Problem**
When i try to sleep on my server, the night is skipped immediately. I can't find any config option for this. I even looked at EssentialsX source code. Can you help me please?

**What I have tried**
Search config, search source code of plugin, uninstalling / reinstalling plugin

**Screenshots**
Got something better, there is a video: https://youtu.be/ut87ppLJHb0

**Comment by mdcfe** [comment]
* Don't use `/reload` on a production server.

> `SmoothSleep`

Can you replicate this without the SmoothSleep plugin installed? EssentialsX shouldn't affect time passing unless everyone has `essentials.sleepingignored`.

**Comment by da-jacob** [comment]
Watch the video I linked, there is no other plugin than essentials. When I was posting the log I had installed couple of plugins, but in the video I deleted it

**Comment by mdcfe** [comment]
Please provide clear, consistent replication steps that match the information you provided and do not involve `/reload` at any point.

**Comment by mdcfe** [comment]
@CreativGraphics Did you fix the problem?

**Comment by presetsteam** [comment]
Same problem here! 
EssentialsX Skips the night, I think its EssentialsProtect as It didn't happen before i put that in.
Could this be disabled?

**Comment by MTNooby21gr** [comment]
I have the same problem but I haven't the protect EssentialsProtect any help?

**Comment by Chew** [comment]
Please make a new issue and follow the template. Don't bump old issues
