### ISSUE TITLE
Players can't do /kit

### ISSUE THREAD

**Issue by 169k** [EssentialsX/Essentials#2656]
### Information

Full output of `/ess version`:

**Server log:** 

**EssentialsX config** 

### Help request

**Problem**

**What I have tried**

**Screenshots**

**Comment by montlikadani** [comment]
There is not enough information on how the problem, configurations, version, and console log were generated. And you didn't follow the template.

**Comment by pop4959** [comment]
This issue will now be closed since it does not provide any reasonable attempt to complete the template.

@169k I recommend seeking help on the M.O.S.S. Discord server in the Essentials support channels before posting again, since this is likely a simple misconfiguration problem.
