### ISSUE TITLE
Players can't do /kit 

### ISSUE THREAD

**Issue by rybuilder23** [EssentialsX/Essentials#2657]
### Information

**Full output of `/ess version`**:

```
5.07 14:11:56 [Server] INFO Server versie: 1.14.3-R0.1-SNAPSHOT git-Paper-124 (MC: 1.14.3)
05.07 14:11:56 [Server] INFO EssentialsX versie: 2.16.1.218
05.07 14:11:56 [Server] INFO LuckPerms versie: 4.4.24
05.07 14:11:56 [Server] INFO Vault versie: 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
05.07 14:11:56 [Server] INFO EssentialsXGeoIP versie: 2.16.1.218
05.07 14:11:56 [Server] INFO EssentialsXSpawn versie: 2.16.1.218
```

**Server log**: https://pastebin.com/QGuGsBhu
**EssentialsX config**: https://pastebin.com/Xy7CaYin

### Details

**Description**  
when you use /kit you dont get the kit

i have tried various versions none work

**Steps to reproduce**  
/kit <kit>

**Expected behavior**  
to get the kit

**Screenshots**  
http://prntscr.com/ob1rgt
http://prntscr.com/ob1rtv

**Comment by rybuilder23** [comment]
/kits seem to work 
/kit not
:/

**Comment by montlikadani** [comment]
Same https://github.com/EssentialsX/Essentials/issues/2656
Close this issue.

**Comment by mdcfe** [comment]
@rybuilder23 Could you update to the latest build and post your kits file?
