### ISSUE TITLE
`/reply` commands are typed as if the user has no permission

### ISSUE THREAD

**Issue by GiraffeCubed** [EssentialsX/Essentials#2659]
**Server log**: -Not applicable; no error logs. Bug was non-existent in 2.16.1, only in 2.17.0.0-

**EssentialsX config**: https://gist.github.com/GiraffeCubed/d2dbb24ea1c7d97c844a002fedcc7621

### Details

**Description**  
Users without OP, `*` permissions, or `essentials.*` permissions see `/reply` or `/r` commands as red in the Minecraft typing window. With OP or one of the aforementioned permissions, it works as normal. The issue persists even when users have the permission `essentials.msg`, `essentials.msg.*`, and `essentials.rtoggle`. 

This is mainly a visual bug, as the `/reply` and `/r` commands work as they should, but it causes confusion as people are growing more accustomed to the 1.13 command system.

**Steps to reproduce**  
• Ensure you do not have OP, `*` permissions, or `essentials.*` permissions
• Type `/reply` or `/r` in the chat window
• It's red, as if you have no permission

**Expected behavior**  
Users with the permission `essentials.msg` have the ability to `/reply` or `/r`. It should not appear red in the chat window.

**Screenshots**  
http://prntscr.com/obk485

**Comment by ghost** [comment]
Yeah, noticed that lately too. /r shows up red in command completion even if the user has permission to send private messages.

**Comment by 2ez1alt** [comment]
hey! i'm having the same issue with most of my commands from essentials, even though all permissions are still present. commands work fine, but they show up in red. if i OP a player and then deOP them, they are able to see commands and press tab. but when they relog, the issue persists. this was also not an issue for me in the previous update (2.16.1)

**Comment by triagonal** [comment]
I can reproduce this issue on the following version:
```
[17:53:12 INFO]: Server version: 1.14.3-R0.1-SNAPSHOT git-Paper-134 (MC: 1.14.3)
[17:53:12 INFO]: EssentialsX version: 2.17.0.4
[17:53:12 INFO]: LuckPerms version: 4.4.1
[17:53:12 INFO]: Vault version: 1.7.2-b107
```

**Comment by pop4959** [comment]
Similarly able to replicate this issue (screenshot also provided)

![image](https://user-images.githubusercontent.com/17698576/61589520-d678e200-ab5f-11e9-8181-6774946d238a.png)

```
> essentials version
[02:30:05 INFO]: CONSOLE issued server command: /essentials version
[02:30:05 INFO]: Server version: 1.14.4-R0.1-SNAPSHOT git-Paper-135 (MC: 1.14.4)
[02:30:05 INFO]: EssentialsX version: 2.17.0.5
[02:30:05 INFO]: LuckPerms version: 4.4.1
[02:30:05 INFO]: Vault version: 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[02:30:05 INFO]: EssentialsXProtect version: 2.17.0.5
[02:30:05 INFO]: EssentialsXChat version: 2.17.0.5
[02:30:05 INFO]: EssentialsXGeoIP version: 2.17.0.5
[02:30:05 INFO]: EssentialsXAntiBuild version: 2.17.0.5
[02:30:05 INFO]: EssentialsXSpawn version: 2.17.0.5
```

**Comment by Castiella** [comment]
following, having same issue for non ops

**Comment by mdcfe** [comment]
`/r` requires the permission `essentials.msg` for the command to run. However, due to an oversight, the tab complete code checks for `essentials.r` instead of `essentials.msg`. I'll fix this when I get a chance.
