### ISSUE TITLE
Essentials Anti Build - Users with No Permissions Can Break / Interact with Armor Stands & Item Frames

### ISSUE THREAD

**Issue by tpalaz** [EssentialsX/Essentials#2660]
### Information

**Full output of `/ess version`**:

```
> [18:02:02] [Server thread/INFO]: Server version: 1.14.3-R0.1-SNAPSHOT git-Bukkit-087a2cf (MC: 1.14.3)
> [18:02:02] [Server thread/INFO]: EssentialsX version: 2.17.0.0
> [18:02:02] [Server thread/INFO]: LuckPerms version: 4.4.1
> [18:02:02] [Server thread/INFO]: Vault version: 1.7.2-b107
> [18:02:02] [Server thread/INFO]: EssentialsXProtect version: 2.17.0.0
> [18:02:02] [Server thread/INFO]: EssentialsXChat version: 2.17.0.0
> [18:02:02] [Server thread/INFO]: EssentialsXAntiBuild version: 2.17.0.0
> [18:02:02] [Server thread/INFO]: EssentialsXSpawn version: 2.17.0.0```
```

**Server log**: https://gist.github.com/tpalaz/1a7a68093a7224bb18e144e6b1ea81e8

**EssentialsX config**: https://gist.github.com/tpalaz/491e2ecf992084535ccbccfcbde1ae8c

### Details

**Description**  
Users with the default "essentials.build.* = false permission are able to interact with Item Frames (Remove the items from the frame). As well as destroy armor stands, and take any items that may be attached to the armor stand. 

I further tested by black listing both armor stands & item frames, and still was able to reproduce these results with both items blacklisted for use, place, break, etc. 

Furthermore, testing the broadcasting system of antibuild results in no event being triggered when armor stands / item frames are destroyed or modified. Only when they are placed.

**Steps to reproduce**  
Given the default anti-build, setup 2 ranks - Default, and Member. Member with permissions :
Essentials.build.* 
and Default with no permissions + antibuild enabled in config.

**Expected behavior**  
Default group members should not be able to interact with, use, destroy, or modify armor stands / item frames.

**Comment by mdcfe** [comment]
As far as I know, EssentialsX AntiBuild doesn't protect entities at all - this would need to be added first.

**Comment by mdcfe** [comment]
This has finally been added - you can download the latest version from the [EssentialsX website](https://essentialsx.cf/downloads.html).
