### ISSUE TITLE
2.17.0.3 - non-stop crashes: Exception ticking world

### ISSUE THREAD

**Issue by s1h4d0w** [EssentialsX/Essentials#2663]
### Information

**Full output of `/ess version`**:

I don't have this because I downgraded to 2.17.0 after my server crashed 4 times in the span of minutes

**Server log**: https://gist.github.com/s1h4d0w/5135f87421e937d7f2e04d7a2b8dc7c7

**Crash log**: https://gist.github.com/s1h4d0w/f2f6ddcb972d310b20a30b5d00acd86a

**EssentialsX config**: https://gist.github.com/s1h4d0w/ae3a7a1bae97e39fec684a6d990478ef

### Details

**Description**  
I posted this earlier today: https://github.com/EssentialsX/Essentials/issues/2662

I was told to update to the newest version, where the piston event bug was fixed. However ever since I updated to 2.17.0.3 my server randomly crashes with an exception ticking the world (see log). After it kept crashing over and over I downgraded to 2.17.0 which I was using before 2.17.0.3 and the server seems to be stable again (aside of the piston error).

**Steps to reproduce**  
None, it happens randomly. I've not seen any pattern in commands used by players before it crashes.

**Expected behavior**  
It not to crash

**Comment by mdcfe** [comment]
Your attached crash log shows that the crash occurs when running 2.17.0.0 in addition to 2.17.0.3: https://gist.github.com/s1h4d0w/f2f6ddcb972d310b20a30b5d00acd86a#file-crashlog-txt-L62

Please provide the output of `/ess version` on all affected versions. It provides additional detail that we use to determine potential issues with server software compatibility.

**Comment by s1h4d0w** [comment]
That's weird, I removed the 2.17.0.3 jar, then reuploaded the 2.17.0 jar and then rebooted the server.  As an update, the server worked for a while and has now crashed twice again with the tick exception. I didn't remove the Essentials folder, might that cause problems? I assume there's no config changes between 2.17.0 and 2.17.0.3.

However now the server runs for about an hour before it crashes. I really don't want to put back the 2.17.0.3 jar as it made the server crash every few minutes. I have a bunch of people online and don't want to have them find somewhere else to play because the server crashes again and again. The server is just picking up a small bit of popularity.

This is the current /ess version output (with just the 2.17.0 jar):

```
[23:52:15 INFO]: Server version: 1.12.2-R0.1-SNAPSHOT git-Spigot-79a30d7-acbc348 (MC: 1.12.2)
[23:52:15 INFO]: EssentialsX version: 2.17.0.0
[23:52:15 INFO]: PermissionsEx version: 1.23.4
[23:52:15 INFO]: Vault version: 1.7.2-b107
[23:52:15 INFO]: EssentialsXSpawn version: 2.17.0.0
[23:52:15 INFO]: You are running unsupported plugins!
```

This is the latest crashlog: https://gist.github.com/s1h4d0w/9facdc08da80530604ea64963d8bc35a

**Comment by s1h4d0w** [comment]
Closing this as disabling Orebfuscator seems to have fixed the issue. I guess it was pure chance that it started happening right as I updated EssentialsX.

I also scanned my whole world with Region fixer but no corrupted chunks came up.

**Comment by mdcfe** [comment]
If you're looking for a functional and relatively lightweight anti-xray, [Paper](https://papermc.io) has its own [anti-xray](https://paper.readthedocs.io/en/latest/server/configuration.html#anti-xray) built in. It doesn't require a separate plugin and is much faster than using a separate plugin like Orebfuscator.

Paper also includes numerous performance improvements over Spigot, and all your existing plugins should work on Paper without any compatibility issues.

**Comment by s1h4d0w** [comment]
I've actually tried Paper, but it [prints out random garbage](https://imgur.com/u3mqwt3) into the server console. I've tried getting that fixed with the Paper devs, but they had no idea what was causing it sadly. Probably related to my server provider, but they won't give me any info on the servers and software used.

Might have to go back to a "limit players to x diamonds an hour" plugin.

**Comment by mdcfe** [comment]
You seem to have a wrapper (AutoRestart-Bootloader) that doesn't work properly with Paper. This isn't Paper's fault, and unless your host installed the AutoRestart plugin, it's not your host's fault either.

**Comment by s1h4d0w** [comment]
It’s not the bootloader or Autorestart. I get the same issues when I do a clean install of literally just Paper. Probably related to the web console my server provider uses, but sadly they don’t want to provide technical info on it, with that the Paper devs might have been able to point me in the right direction.

**Comment by mdcfe** [comment]
The message is displayed by the bootloader. There isn't anything else that can display that message - the stack trace specifically mentions the bootloader, and the error wouldn't be there if it wasn't installed.
