### ISSUE TITLE
How to use certain items with the essentials signs

### ISSUE THREAD

**Issue by LorenBear** [EssentialsX/Essentials#2664]
This is less of a technical issue, more of a question. How do you use a buy sign with items that are longer than one sign line like experience_bottle. 

Thanks

**Comment by YourCoal** [comment]
Possibly this fourms post on Spigot will help:
https://www.spigotmc.org/threads/need-help-with-essentials-shops-ids-issue.382723/

**Comment by triagonal** [comment]
You can hold an item in your hand and run `/itemdb` to see a list of available shortnames you can use on signs. You can also add your own aliases for items by editing the `items.json` file.
