### ISSUE TITLE
nickname with chinese or other text

### ISSUE THREAD

**Issue by Command1264** [EssentialsX/Essentials#2665]
### Feature request

**Feature description**
hope  "^[a-zA-Z_0-9§]+$" can change to  "^[a-zA-Z0-9&|\u0000-\uffff§ ]+$|" inside Connandnick.class

**How the feature is useful**
can use nickname with chinese in default

**Comment by mdcfe** [comment]
Use the permission `essentials.nick.allowunsafe` to allow Chinese characters in player nicknames.
