### ISSUE TITLE
EssentialsTimer bug - wont go away

### ISSUE THREAD

**Issue by BMackerill** [EssentialsX/Essentials#2667]
Hi! I installed EssentialsX on my server and then removed it as it had some errors (and I have lost the errors due to this one spamming the console).

Now, it spews out the same error constantly in the console:

> [WARNING] [Essentials] EssentialsTimer Error:
> java.lang.NullPointerException
> at com.earth2me.essentials.perm.PermissionsHandler.getName(PermissionsHandler.java:153) ~[EssentialsX-2.17.0.0.jar:?]
> at com.earth2me.essentials.User.isAuthorizedCheck(User.java:117) ~[EssentialsX-2.17.0.0.jar:?]
> at com.earth2me.essentials.User.isAuthorized(User.java:93) ~[EssentialsX-2.17.0.0.jar:?]
> at com.earth2me.essentials.User.checkActivity(User.java:630) ~[EssentialsX-2.17.0.0.jar:?]
> at com.earth2me.essentials.EssentialsTimer.run(EssentialsTimer.java:58) [EssentialsX-2.17.0.0.jar:?]
> at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
> at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
> at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
> at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
> at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
> at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
> at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

**Comment by mdcfe** [comment]
You haven't provided enough information for us to help. Please [fill out the support template](https://github.com/EssentialsX/Essentials/issues/new?template=help.md).
