### ISSUE TITLE
[Essentials] Lag Notice - Slow Economy Response

### ISSUE THREAD

**Issue by ShanNaeNae** [EssentialsX/Essentials#2669]
### Information

**Full output of `/ess version`**:

```
<!-- Run the command in your console, and copy and paste the whole output here -->
```

**Server log**: 

**EssentialsX config**: 

### Details

**Description**  
[Essentials] Lag Notice - Slow Economy Response

**Steps to reproduce**  
That the thing, I've no idea.

**Expected behavior**  
Requesting any possible help if anyone knows.

**Screenshots**  
No screenshots, just a solid bug "[Essentials] Lag Notice - Slow Economy Response"

**Comment by ShanNaeNae** [comment]
Forgot to add the first thing:

https://gyazo.com/fe632db6afc2810c98e38caa75445910

**Comment by ShanNaeNae** [comment]
> [18:30:38 INFO]: Server version: 1.8.8-R0.1-SNAPSHOT git-PaperSpigot-"4c7641d" (MC: 1.8.8)
> [18:30:38 INFO]: EssentialsX version: 2.17.0.0
> [18:30:38 INFO]: LuckPerms version: 4.4.1
> [18:30:38 INFO]: Vault version: 1.5.6-b49
> [18:30:38 INFO]: EssentialsXSpawn version: 2.17.0.0

**Comment by mdcfe** [comment]
Please don't just ignore the template. It asks for specific detail and without it we can't help.

Could you provide a **full server startup log** and your EssentialsX **`config.yml`**, as well as the actual error you're encountering?

**Comment by pop4959** [comment]
Feel free to re-open this issue if you have further information to share (including the completed full issue template + timings). We can't pursue these sorts of issues at all when it is impossible to reliably reproduce the behaviour described on test systems.
