### ISSUE TITLE
[Compiling] Error when compiling source

### ISSUE THREAD

**Issue by Charkel** [EssentialsX/Essentials#2670]
I have done buildtools.sh install successfully. But when compiling I get this error. Can anyone understand it and try to help. I have not changed anything related to this I know that I only did a small change in one of the functions.

`
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/charkel/Downloads/Essentials-2.x/Essentials/src/com/earth2me/essentials/craftbukkit/FakeWorld.java:[26,9] com.earth2me.essentials.craftbukkit.FakeWorld is not abstract and does not override abstract method getPluginChunkTickets() in org.bukkit.World
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for EssentialsXParent 2.17.0:
[INFO] 
[INFO] EssentialsXParent .................................. SUCCESS [  9.386 s]
[INFO] NMSProvider ........................................ SUCCESS [  4.003 s]
[INFO] UpdatedMetaProvider ................................ SUCCESS [  0.440 s]
[INFO] 1_8_R1Provider ..................................... SUCCESS [  0.471 s]
[INFO] 1_8_R2Provider ..................................... SUCCESS [  0.273 s]
[INFO] LegacyProvider ..................................... SUCCESS [  0.195 s]
[INFO] ReflectionProvider ................................. SUCCESS [  1.810 s]
[INFO] FlattenedProvider .................................. SUCCESS [  0.202 s]
[INFO] EssentialsX ........................................ FAILURE [  6.480 s]
[INFO] EssentialsXAntiBuild ............................... SKIPPED
[INFO] EssentialsXChat .................................... SKIPPED
[INFO] EssentialsXGeoIP ................................... SKIPPED
[INFO] EssentialsXProtect ................................. SKIPPED
[INFO] EssentialsXSpawn ................................... SKIPPED
[INFO] EssentialsXXMPP .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  23.893 s
[INFO] Finished at: 2019-07-15T01:42:49+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project EssentialsX: Compilation failure
[ERROR] /home/charkel/Downloads/Essentials-2.x/Essentials/src/com/earth2me/essentials/craftbukkit/**FakeWorld.java:[26,9] com.earth2me.essentials.craftbukkit.FakeWorld is not abstract and does not override abstract method getPluginChunkTickets() in org.bukkit.World**

`

EDIT:
I just tried to compile with the original source code unchanged. Still same error. Does no one else get it?!

**Comment by pop4959** [comment]
This is due to a recent change in Spigot. To fix the error, simply make the changes shown in #2679. You won't need to include these changes in your PR since they will already by fixed by that PR.

**Comment by pop4959** [comment]
@Charkel Pull the latest commit and it should be fixed. Look forward to the PR you're working on. :smile:
