### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by z7ey** [EssentialsX/Essentials#2682]
![image](https://user-images.githubusercontent.com/53136075/61587835-08397b00-ab57-11e9-92f8-9c99b4e1fde8.png)

this keeps happening and its getting annoying

**Comment by pop4959** [comment]
This issue will be closed if you do not fill out the issue template, thanks.

**Comment by pop4959** [comment]
Please re-open the issue if you plan on filling out the template, and any other relevant information needed in order to help you.
