### ISSUE TITLE
Item Not Found Error

### ISSUE THREAD

**Issue by Dhenier** [EssentialsX/Essentials#2683]
### Information

**Full output of `/ess version`**:

Server version: 1.14.4-R0.1-SNAPSHOT git-Paper-137 (MC: 1.14.4)
EssentialsX version: 2.17.0.5
Vault version: 1.7.2-b107

**Server log**: https://gist.github.com/Whist34/a266faa1531df2e8715fefeeb96e4bb8

**EssentialsX config**: https://gist.github.com/Whist34/b521bb79636318adae8b43b9a3d76852

### Details

**Description**  
Without EssentialsX installed: 
  Player steps on a pressure plate and a command block issues a command to give the player a jungle_boat and the player receives a jungle boat.
  
With EssentialsX installed:
  Player steps on a pressure plate and a command block issues a command to give the player a jungle_boat, but EssentialsX reports an error and no boat is given.

Console output:
  CommandBlock at 574,68,-895 issued server command: /give @p minecraft:jungle_boat
  [Essentials] Error calling the command /give
  java.lang.Exception: §4Unknown item name: minecraft:jungle_boat.
  ...

**Steps to reproduce**  
Login
Step on pressure plate
Command block issues server command: /give @p minecraft:jungle_boat
Error

**Expected behavior**  
Player receives a jungle_boat

**Comment by triagonal** [comment]
You can't use `minecraft:itemname` codes with Essentials' `/give` command. You'll need to use one of Essentials' shortnames. To find a shortname you can hold an item in your hand and type `/itemdb`, which will list all the names you can use.

In addition, Spigot no longer allows non-vanilla commands to use selectors (`@p`, `@r` etc.) on 1.13+, so this wouldn't work unless you were using the vanilla `/minecraft:give` command. It's possible to restore functionality using plugins like [PsudoCommands](https://www.spigotmc.org/resources/psudocommands-add-the-function-to-plugin-commands.56738/) or [CommandHook](https://www.spigotmc.org/resources/commandhook.61415/).

**Comment by Dhenier** [comment]
I am closing this issue. I found a forum thread that discussed the @p issue and how to correct it by using the /minecraft:give command instead of /give.
