### ISSUE TITLE
Blockbreakevent Error Spigot 1.9.4

### ISSUE THREAD

**Issue by flyloris** [EssentialsX/Essentials#2685]
Console Error:
https://pastebin.com/52W19xEe

**Comment by pop4959** [comment]
You have an outdated version of EssentialsX. Please update and let us know if the issue persists (and properly fill out the issue template, as we will not be able to help you further otherwise).

**Comment by triagonal** [comment]
This has been fixed in builds 2.17.0.3 and above - updating as per pop's suggestion should have fixed the issue. If you are still experiencing this problem, please reply to this thread (with a **complete** issue template).
