### ISSUE TITLE
EssentialsX Commands Autocomplete Not Working

### ISSUE THREAD

**Issue by TxmmySmith** [EssentialsX/Essentials#2686]
I have found that using tab to autocomplete commands does not work unless I am OP. I have extensively searched through permissions and old issue topics but cannot figure it out. 

I am on spigot for version: 1.14.3
EssentialsX Version: 2.17.0.5
GroupManager Version: 0.2.0

config.yml: https://pastebin.com/Jj1rV0Ca
My permissions group has "*" permissions.

Thanks for your time.

**Comment by pop4959** [comment]
Please fill out the entire issue template or we will not be able to help you, as the information you provided is insufficient to follow this up.

**Comment by mohamedemasry** [comment]
still got this on default config
