### ISSUE TITLE
[Enchantment] adding 'thunder' to weather

### ISSUE THREAD

**Issue by Androkai** [EssentialsX/Essentials#269]
Essentials weather-command is only able to cast `sun` and `storm`
I wish for a vanilla `clear/sun` `rain/storm` `thunder` commands implementation

**Comment by drtshock** [comment]
wat

It's either raining or not raining.

**Comment by Androkai** [comment]
But if it's raining there can be a thunderstorm or not ;)

**Comment by vemacs** [comment]
No API for this
