### ISSUE TITLE
PermissionsEX and EssentialsX Dont work?

### ISSUE THREAD

**Issue by ToxicDevv** [EssentialsX/Essentials#2691]
Hey Everyone! I've just installed EssentialsX and discovered that I dont have any of my prefixes showing anymore. I have vault installed and have tried to fix it multiple ways. Can someone please help me?

Here is my startup log, 

`Loading libraries, please wait...

[INFO] Starting minecraft server version 1.14.3

[INFO] Loading properties

[INFO] This server is running CraftBukkit version git-Spigot-9a643a6-a77ba00 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)

[INFO] Using 4 threads for Netty based IO

[INFO] Server Ping Player Sample Count: 12

[INFO] Debug logging is disabled

[INFO] Default game type: SURVIVAL

[INFO] Generating keypair

[INFO] Starting Minecraft server on *:25565

[INFO] Using epoll channel type

[WARNING] Plugin PermissionsEx v1.23.4 does not specify an api-version.

[WARNING] Plugin ChatManager v1.6.3 does not specify an api-version.

[INFO] [PermissionsEx] Loading PermissionsEx v1.23.4

[INFO] [Vault] Loading Vault v1.7.2-b107

[INFO] [ChatManager] Loading ChatManager v1.6.3

[INFO] [Essentials] Loading Essentials v2.17.0.0

[INFO] [Vault] Enabling Vault v1.7.2-b107

[INFO] [Vault] [Economy] Essentials Economy found: Waiting

[INFO] [Vault] [Permission] PermissionsEx found: Waiting

[INFO] [Vault] [Permission] SuperPermissions loaded as backup permission system.

[INFO] [Vault] [Chat] PermissionsEx found: Waiting

[INFO] [Vault] Enabled Version 1.7.2-b107

[INFO] Preparing level "world"

[INFO] Reloading ResourceManager: Default, bukkit

[INFO] Loaded 6 recipes

[INFO] -------- World Settings For [world] --------

[INFO] Cactus Growth Modifier: 100%

[INFO] Cane Growth Modifier: 100%

[INFO] Melon Growth Modifier: 100%

[INFO] Mushroom Growth Modifier: 100%

[INFO] Pumpkin Growth Modifier: 100%

[INFO] Sapling Growth Modifier: 100%

[INFO] Beetroot Growth Modifier: 100%

[INFO] Carrot Growth Modifier: 100%

[INFO] Potato Growth Modifier: 100%

[INFO] Wheat Growth Modifier: 100%

[INFO] NetherWart Growth Modifier: 100%

[INFO] Vine Growth Modifier: 100%

[INFO] Cocoa Growth Modifier: 100%

[INFO] Bamboo Growth Modifier: 100%

[INFO] SweetBerry Growth Modifier: 100%

[INFO] Kelp Growth Modifier: 100%

[INFO] Item Merge Radius: 2.5

[INFO] Experience Merge Radius: 3.0

[INFO] View Distance: 10

[INFO] Mob Spawn Range: 6

[INFO] Item Despawn Rate: 6000

[INFO] Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true

[INFO] Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64

[INFO] Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1

[INFO] Arrow Despawn Rate: 1200

[INFO] Zombie Aggressive Towards Villager: true

[INFO] Nerfing mobs spawned from spawners: false

[INFO] Allow Zombie Pigmen to spawn from portal blocks: true

[INFO] Custom Map Seeds: Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911

[INFO] Max TNT Explosions: 100

[INFO] Tile Max Tick Time: 50ms Entity max Tick Time: 50ms

[INFO] -------- World Settings For [world_nether] --------

[INFO] Cactus Growth Modifier: 100%

[INFO] Cane Growth Modifier: 100%

[INFO] Melon Growth Modifier: 100%

[INFO] Mushroom Growth Modifier: 100%

[INFO] Pumpkin Growth Modifier: 100%

[INFO] Sapling Growth Modifier: 100%

[INFO] Beetroot Growth Modifier: 100%

[INFO] Carrot Growth Modifier: 100%

[INFO] Potato Growth Modifier: 100%

[INFO] Wheat Growth Modifier: 100%

[INFO] NetherWart Growth Modifier: 100%

[INFO] Vine Growth Modifier: 100%

[INFO] Cocoa Growth Modifier: 100%

[INFO] Bamboo Growth Modifier: 100%

[INFO] SweetBerry Growth Modifier: 100%

[INFO] Kelp Growth Modifier: 100%

[INFO] Item Merge Radius: 2.5

[INFO] Experience Merge Radius: 3.0

[INFO] View Distance: 10

[INFO] Mob Spawn Range: 6

[INFO] Item Despawn Rate: 6000

[INFO] Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true

[INFO] Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64

[INFO] Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1

[INFO] Arrow Despawn Rate: 1200

[INFO] Zombie Aggressive Towards Villager: true

[INFO] Nerfing mobs spawned from spawners: false

[INFO] Allow Zombie Pigmen to spawn from portal blocks: true

[INFO] Custom Map Seeds: Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911

[INFO] Max TNT Explosions: 100

[INFO] Tile Max Tick Time: 50ms Entity max Tick Time: 50ms

[INFO] -------- World Settings For [world_the_end] --------

[INFO] Cactus Growth Modifier: 100%

[INFO] Cane Growth Modifier: 100%

[INFO] Melon Growth Modifier: 100%

[INFO] Mushroom Growth Modifier: 100%

[INFO] Pumpkin Growth Modifier: 100%

[INFO] Sapling Growth Modifier: 100%

[INFO] Beetroot Growth Modifier: 100%

[INFO] Carrot Growth Modifier: 100%

[INFO] Potato Growth Modifier: 100%

[INFO] Wheat Growth Modifier: 100%

[INFO] NetherWart Growth Modifier: 100%

[INFO] Vine Growth Modifier: 100%

[INFO] Cocoa Growth Modifier: 100%

[INFO] Bamboo Growth Modifier: 100%

[INFO] SweetBerry Growth Modifier: 100%

[INFO] Kelp Growth Modifier: 100%

[INFO] Item Merge Radius: 2.5

[INFO] Experience Merge Radius: 3.0

[INFO] View Distance: 10

[INFO] Mob Spawn Range: 6

[INFO] Item Despawn Rate: 6000

[INFO] Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true

[INFO] Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64

[INFO] Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1

[INFO] Arrow Despawn Rate: 1200

[INFO] Zombie Aggressive Towards Villager: true

[INFO] Nerfing mobs spawned from spawners: false

[INFO] Allow Zombie Pigmen to spawn from portal blocks: true

[INFO] Custom Map Seeds: Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911

[INFO] Max TNT Explosions: 100

[INFO] Tile Max Tick Time: 50ms Entity max Tick Time: 50ms

[INFO] Preparing start region for dimension 'world'/minecraft:overworld

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 85%

[INFO] Time elapsed: 3723 ms

[INFO] Preparing start region for dimension 'world_nether'/minecraft:the_nether

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Time elapsed: 1927 ms

[INFO] Preparing start region for dimension 'world_the_end'/minecraft:the_end

[INFO] Preparing spawn area: 0%

[INFO] Time elapsed: 532 ms

[INFO] [PermissionsEx] Enabling PermissionsEx v1.23.4

[INFO] [PermissionsEx] Initializing file backend

[INFO] [PermissionsEx] Permissions file successfully reloaded

[INFO] [Vault][Permission] PermissionsEx hooked.

[INFO] [Vault] [Vault][Chat] PermissionsEx_Chat hooked.

[INFO] [ChatManager] Enabling ChatManager v1.6.3

[INFO] [Essentials] Enabling Essentials v2.17.0.0

[INFO] Attempting to convert old kits in config.yml to new kits.yml

[INFO] No kits found to migrate.

[INFO] [Essentials] Using 1.8.3+ BlockStateMeta provider as mob spawner provider.

[INFO] [Essentials] Using 1.13+ flat spawn egg provider as spawn egg provider.

[INFO] [Essentials] Using 1.9+ BasePotionData provider as potion meta provider.

[INFO] Loaded 20977 items from items.json.

[INFO] Using locale c.u_US

[INFO] [Essentials] ServerListPingEvent: Spigot iterator API

[INFO] [Essentials] Starting Metrics. Opt-out using the global bStats config.

[INFO] [Vault] [Vault][Economy] Essentials Economy hooked.

[INFO] [Essentials] Using Vault based permissions (PermissionsEx)

[INFO] Server permissions file permissions.yml is empty, ignoring it

[INFO] Done (27.702s)! For help, type "help"

[INFO] Starting GS4 status listener

[INFO] Query running on 0.0.0.0:25565

[INFO] [Vault] Checking for Updates ...

[INFO] [Vault] No new version available`

I am using Server.pro as my hosting service.

**Comment by pop4959** [comment]
PermissionsEx is a dead/outdated plugin. You should probably switch to something more recent like LuckPerms for example.

**Comment by ToxicDevv** [comment]
PermissionsEx isn't a dead plugin? Ive been using it with Essentials for the past year now. I only switched to EssentialsX because it has bux fixes and some commands like /kill etc have been improved.

**Comment by pop4959** [comment]
PermissionsEx has not received updates in over 3 years. Also, the developer of PermissionsEx himself recommends switching to LuckPerms, as seen [here](https://github.com/PEXPlugins/PermissionsEx/blob/master/README.md).

**Comment by ToxicDevv** [comment]
Oh my apologies I wasn't aware of that. Ive now downloaded and installed luckperms, and its very hard to even give myself a prefix. Any way you can help?

**Comment by ToxicDevv** [comment]
Figured it out

**Comment by pop4959** [comment]
No worries. It might take a little while to learn, but using a modern permission plugin should definitely be more reliable. Reading through their wiki can be helpful.
