### ISSUE TITLE
Toggle Keepinv

### ISSUE THREAD

**Issue by kaanakduman** [EssentialsX/Essentials#2692]
### Feature request

**Feature description**
A command to toggle keepinv for players who have the essentials.keepinv perm.

**How the feature is useful**
It allows players who have the essentials.keepinv perm to remove curse of binding items.

**Comment by mdcfe** [comment]
You can now use the keepinv policy config options introduced in EssentialsX 2.18.0 (#3328) to allow players to remove Curse of Binding and Curse of Vanishing items. Quote from [2.18.0 changelog](https://github.com/EssentialsX/Essentials/releases/tag/2.18.0):

> You can now configure how the essentials.keepinv permission behaves when players die while holding items with the Curse of Binding or Curse of Vanishing:
> 
> ```yaml
> # How should essentials handle players with the essentials.keepinv permission who have items with
> # curse of vanishing when they die?
> # You can set this to "keep" (to keep the item), "drop" (to drop the item), or "delete" (to delete the item).
> # Defaults to "keep"
> vanishing-items-policy: keep
> 
> # How should essentials handle players with the essentials.keepinv permission who have items with
> # curse of binding when they die?
> # You can set this to "keep" (to keep the item), "drop" (to drop the item), or "delete" (to delete the item).
> # Defaults to "keep"
> binding-items-policy: keep
> ```
