### ISSUE TITLE
Config isn't auto updating/generating new keys to older config(s)

### ISSUE THREAD

**Issue by axemwa** [EssentialsX/Essentials#2693]
Keys doesn't seem to automatically get added/updated to old configs. 

**The keys known are as follows,**

"allow-old-id-signs", "no-god-in-worlds:", "unprotected-sign-names:", "allow-world-in-broadcastworld:", "is-water-safe:", "safe-usermap-names:" and "sleep-ignores-afk-players".

**_Using EssentialsX Dev/Jenkins build #768 (a.k.a 2.17.1.7)
Paper 1.13.2 build 641_**

**Comment by mdcfe** [comment]
EssentialsX does not currently update old configs due to constraints with the old Essentials config code. If you need to change newly-added config options, you can add them at the bottom of the `config.yml`, or rename your existing `config.yml` and restart the server to create a new one.

**Comment by axemwa** [comment]
Ah ok thanx for explaining that I didn't realize this was just about to close
