### ISSUE TITLE
Duplicated item when an admin dies

### ISSUE THREAD

**Issue by Pistakkio** [EssentialsX/Essentials#2694]
i have Paper 1.14.4 server. when I play as admin I have all the permissions with 'essentials. *', but if I die I have all the items left in the inventory and in addition I drop too. practically duplicate. how do i solve?

**Comment by darbyjack** [comment]
You literally provided no information. No help will be provided until you provide what the template requests.

**Comment by Pistakkio** [comment]
whait.. i'm sorry xD i'm editing now

**Comment by Pistakkio** [comment]
can you change the status?

**Comment by darbyjack** [comment]
No help will be provided until you provide what the template requests.

**Comment by Pistakkio** [comment]
Sorry for bad english

**Comment by Pistakkio** [comment]
can someone help me?
