### ISSUE TITLE
Cannot disable keepinv when having essentials.*

### ISSUE THREAD

**Issue by Brokkonaut** [EssentialsX/Essentials#2697]
I have an account that has the permission essentials.* and explicitly disabled essentials.keepinv. When I ask my permission plugin, I definitely do not have the permission essentials.keepinv. But I still keep the inventory.

**Comment by darbyjack** [comment]
Duplicate of #2698

**Comment by Brokkonaut** [comment]
This is not a duplicate. I just want to disable the keepinv feature...

**Comment by darbyjack** [comment]
Duplicate of #2692

**Comment by mdcfe** [comment]
@Brokkonaut Could you run `/ess debug`, then check the console when you die and post the output?

If `essentials.keepinv` is false, it's not EssentialsX.

(In addition, if you use LuckPerms verbose in-game, it will tell you which *type* of node is granting/denying each permission when you hover over.)

Edit: in the future, use the template.

**Comment by Brokkonaut** [comment]
Ok, I found the cause - I was using an old build of bPermissions. When I tried with LuckPerms it worked as expected. So I think its not an essentials bug.
