### ISSUE TITLE
essentials.keepinv Dupe

### ISSUE THREAD

**Issue by kaanakduman** [EssentialsX/Essentials#2698]
### Information

**Full output of `/ess version`**:
```
[Mon, 29. Jul 2019 18:22:56 EDT] Server version: 1.14.4-R0.1-SNAPSHOT git-Paper-152 (MC: 1.14.4)
[Mon, 29. Jul 2019 18:22:56 EDT] EssentialsX version: 2.17.0.5
[Mon, 29. Jul 2019 18:22:56 EDT] LuckPerms version: 4.4.27
[Mon, 29. Jul 2019 18:22:56 EDT] Vault version: 1.7.2-b107
[Mon, 29. Jul 2019 18:22:56 EDT] EssentialsXChat version: 2.17.0.5
[Mon, 29. Jul 2019 18:22:56 EDT] EssentialsXSpawn version: 2.17.0.5
```
Bug occurs on Paper-152 but not on Paper-151. The changes for that release can be found [here](https://github.com/PaperMC/Paper/commit/93891ad57a8317678c41bad4f755627821db0eaa). I believe this bug may relate to [this](https://hub.spigotmc.org/jira/projects/SPIGOT/issues/SPIGOT-5226?filter=allopenissues).

### Details

**Description**  
On death, the contents of the player's inventory stay in the player's inventory. A copy of the contents are also dropped on death, duplicating the original inventory contents.

**Steps to reproduce**  
1. /gamerule keepinventory false
2. Give a player essentials.keepinv
3. /kill the player

**Expected behavior**  
The contents of the player's inventory should stay in the player's inventory. No items should drop.

**Comment by darbyjack** [comment]
Already known and a fix is in place. Just remove the permission for the time being.
