### ISSUE TITLE
Compass targeting/pointing to a specific coordinates (spawn|first_home|bed|...)

### ISSUE THREAD

**Issue by crizyx** [EssentialsX/Essentials#2699]
Hello everyone,

On my server i have a particular group of players named illuminated that plays with fewer permissions like teleportation (spawn, warp, home) to get as close as possible to vanilla gameplay.

Problem, players often using the compass to identify themselves can not choose which coordinates they wish to see,
it's more interesting for an adventurer to see where is his house and bed than to see the spawn of the map which is irrelevant.

The essentials configuration file "config.yml" allows you to alternate compass pointing between **spawn** and **first home** but this changes the position of the compass for all groups of players. makes the whole thing too restrictive.

```yml
# Controls whether players need the permission "essentials.home.compass" in order to point
# the player's compass at their first home.
#
# Leaving this as false will retain Essentials' original behaviour, which is to always
# change the compass' direction to point towards their first home.
compass-towards-home-perm: false
```
My idea is to make the compass more useful and more customizable.

I suggest adding or modifying the **/compass** command like this
**/compass point or pointing [Bed | Spawn | First_home | Desired_home | Custom_coordinate | Actual_location or Here]**

The resulting permissions may also allow more opportunity for group administration.

esssentials.compass.**pointing**
esssentials.compass.pointing.**bed**
esssentials.compass.pointing.**spawn**
esssentials.compass.pointing.**first_home**
esssentials.compass.pointing.**desired_home**
esssentials.compass.pointing.**custom_coordinates**
esssentials.compass.pointing.**acutual_location or .here**

Example of application, in vanilla servers, the compass of the player can point only the bed of the player or it can use the compass like a GPS provided to have entered the coordinates of its destination.

I hope you will understand this subject like me, my english is poor so used google translation to help me.

**Thanks for work XEssentials Team**

**Comment by pop4959** [comment]
This will be implemented by Mojang in 1.16, believe it or not! See: [Lodestone](https://minecraft.gamepedia.com/Lodestone).

**Comment by BRA1L0R** [comment]
What do lodestones have to do with this I don't understand. Lodestones are a vanilla feature while this might be a solution for people looking for a way to forcefully point a compass towards a specific home.

**Comment by mdcfe** [comment]
@BRA1L0R It's unlikely we'll add the feature described by OP, as it's overly complex and doesn't really fall within the scope of EssentialsX.
