### ISSUE TITLE
Can't disable essentials.keepinv

### ISSUE THREAD

**Issue by Lermatroid** [EssentialsX/Essentials#2702]
### Information

**Full output of `/ess version`**:

```
<!-- Run the command in your console, and copy and paste the whole output here -->
```

**Server log**: 

**EssentialsX config**: 

### Details

**Description**  
I am unable to disable the essentials.keepinv permission using -essentials.keepinv as a OP

**Steps to reproduce**  
I tried to add -essentials.keepinv but it does not follow my permission and forces me to keep my inventory

**Expected behavior**  
The inventory keeping will disbale

**Comment by mdcfe** [comment]
Please fill out the template fully.

**Comment by Charkel** [comment]
I downloaded LuckPerms to do this. You should do the same

**Comment by pop4959** [comment]
Yeah I'm assuming this is due to some outdated permissions plugin. I've seen several reports of this over the last few days, and as @Charkel mentioned it is easily fixed by downloading LuckPerms (or some other permission plugin that properly handles these negated permissions).

**Comment by pop4959** [comment]
Closing since this is effectively answered, and has prompted no further discussion.
