### ISSUE TITLE
EssentialsX onJoinEvent (DelayJoinEvent) Causing Loading terrain lag for all players

### ISSUE THREAD

**Issue by Bxnie** [EssentialsX/Essentials#2704]
> [INFO] EssentialsX version: 2.17.0.3
> [INFO] PermissionsEx version: 1.23.4
> [INFO] Vault version: 1.7.2-b107
> [INFO] EssentialsXGeoIP version: 2.17.0.3
> [INFO] EssentialsXSpawn version: 2.17.0.3

We have been running a server now for a couple of weeks, and one of the biggest complaints we got was that the server join lag was unbearable. on a scheduled maintenance day I ran a timings report and found out that the delayJoinTask in EssentialsX was causing a lot of lag, here is one screenshot: 
![image](https://user-images.githubusercontent.com/44813076/62217753-1f703800-b3a3-11e9-876b-de2e467d9bed.png)

I saw a few threads relating to this issue but many of them were quick to blame other plugins, such as mcmmo etc. after seeing a thread on this Github page the only advice I saw regarding the performance would be to use paper instead of spigot, so I switched over to paper but still, the join lag remained.

after this, I decided to uninstall Essentials and leave all the other plugins to make sure it wasn't just a false positive. after removing essentials, me and some friends were able to join with little to no latency or lag for the other players.

I'm not sure what the delaytask does but it causing a lot of lag when players join the server, not just for the player joining but also for the players already on the server. If you are confident that this isnt EssentialsX's fault, then can you please explain what the JoinDelayTask does as that seems to be the culprit for me.

Edit 1 - our server isn't maxing out on ram or CPU usage, both of maxing out around 30-40% with around 15people online

**Comment by mdcfe** [comment]
Please provide:
* The **full output of `/ess version`**
* Your `config.yml`
* The full startup log of your server

In addition, Spigot's performance is lacking, and Timings v1 is largely unhelpful - you should upgrade to Paper which includes significantly better performance and Timings v2.

**Comment by Bxnie** [comment]
> [INFO] ess version> CONSOLE issued server command: /ess version
> [INFO] Server version: 1.13.2-R0.1-SNAPSHOT git-Paper-641 (MC: 1.13.2)
> [INFO] EssentialsX version: 2.17.0.3
> [INFO] PermissionsEx version: 1.23.4
> [INFO] Vault version: 1.7.2-b107
> [INFO] EssentialsXGeoIP version: 2.17.0.3
> [INFO] EssentialsXSpawn version: 2.17.0.3
> [INFO] You are running unsupported plugins!

[Essentials Config.yml](https://pastebin.com/gpVwfhLg)
[Startup Log](https://pastebin.com/qn3LD1nB)

**Comment by triagonal** [comment]
If you're still having trouble with this issue, could you please also provide the Timings link using Paper's Timings v2 as well?

**Comment by pop4959** [comment]
Assuming this isn't an issue anymore since there has been no further comment. As @triagonal mentioned, Timings v2 would be much more helpful. A problem with v1 is that it might trace indirectly caused lag back to a plugin. For example, teleportation commands prompt world loading, which is a very expensive task. It's likely that other teleportation plugins will show the same symptoms as well.
