### ISSUE TITLE
EssentialsX breaks normal commands

### ISSUE THREAD

**Issue by Charkel** [EssentialsX/Essentials#2708]
If EssentialsX is installed some normal commands stop working. For example the scoreboard command and the "@e" or "@p" target selector

[16:29:50 INFO]: > kill @e
[16:29:50 INFO]: CONSOLE issued server command: /kill @e
[16:29:50 INFO]: Error: Player not found.

[16:30:03 INFO]: > scoreboard
[16:30:03 INFO]: Unknown command
[16:30:03 INFO]: ...scoreboard<--[HERE]

**Comment by mdcfe** [comment]
In 1.13+, vanilla commands don't work unless you type the full syntax - you need to type valid arguments after `scoreboard` for it to work.

For `/kill`, EssentialsX includes its own version of the command - to use the vanilla version, either use `/minecraft:kill` or [override `/kill` with `/minecraft:kill`](https://essentialsx.netlify.com/wiki/Common-Issues.html#essentialsx-overrides-a-command-from-spigot-or-another-plugin).
