### ISSUE TITLE
Possible to change /sell command a bit?

### ISSUE THREAD

**Issue by PsychoNavigator** [EssentialsX/Essentials#271]
I've given my players the ability to sell to server and every now and then someone occasionally does /sell instead of /sell hand and lose all their inventory.

I would think the best option would be to have /sell undo to revert a sale, but there's other methods as well that could work, say a confirmation dialog for selling off all inv, or making specific nodes for hand/inventory/etc however there would be a need to explicitly disable /sell by itself.

**Comment by drtshock** [comment]
There are specific nodes for hand and inventory.
