### ISSUE TITLE
/heal suggestion

### ISSUE THREAD

**Issue by RainDropped** [EssentialsX/Essentials#2710]
### Feature request

**Feature description**

add an option for /heal to just heal you up to max hearts
without taking any potion effects off.

**How the feature is useful**

Lost of server nowadays have custom armor which give potion effects 
and players use /heal to heal up during a fight, and when you /heal it gets rid of their
effects which is really bad for them.

**Comment by darbyjack** [comment]
PR opened https://github.com/EssentialsX/Essentials/pull/2754
