### ISSUE TITLE
heal-cooldown skipped when bound to powertool

### ISSUE THREAD

**Issue by FatherWh0** [EssentialsX/Essentials#2711]
### Information

**Full output of `/ess version`**:

```
02.08 15:31:25 [Server] INFO Gicel [Pumpkin]: Idk
02.08 15:31:19 [Server] INFO EssentialsXSpawn version: 2.0.1-b612
02.08 15:31:19 [Server] INFO EssentialsXGeoIP version: 2.0.1-b612
02.08 15:31:19 [Server] INFO Vault version: 1.6.7-b${env.TRAVIS_BUILD_NUMBER}
02.08 15:31:19 [Server] INFO PermissionsEx version: 1.23.4
02.08 15:31:19 [Server] INFO EssentialsX version: 2.0.1-b612
02.08 15:31:19 [Server] INFO Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1584 (MC: 1.12.2)
```

**Server log**: https://gist.github.com/FatherWh0/89a5dddfbe43113193ff7d4cebb70b72

**EssentialsX config**: https://gist.github.com/FatherWh0/768f3301501a2747e0dc64d5b569daab

### Details

**Description**  
heal-cooldown is set to 600 seconds. However, when a player with /pt binds heal to an item the cooldown is skipped.

**Steps to reproduce**  

set heal-cooldown=600
bind /heal to an item.
spam the item.
**Expected behavior**  

Expect heal to have 600 second cooldown.
**Screenshots**

**Comment by mdcfe** [comment]
Are you sure the player doesn't have the `essentials.heal.cooldown.bypass` permission? *edit: run `/ess debug`, use the powertool then read the console to check.*

> `2.0.1-b612`

You're also running a version that is 160 versions (1 year 4 months) out of date - could you update to the [latest version](https://essentialsx.netlify.com/downloads.html)?

**Comment by FatherWh0** [comment]
I am certain the players do not have the bypass perm. The command running from a powertool seems to follow different rules than a player typing the command.

As far as the version is concerned, that server is running 1.12.2 and therefore isn't receiving updates unless bug fixes are needed. Is it wise to update to the current essX while running 1.12.2?

**Comment by mdcfe** [comment]
> The command running from a powertool seems to follow different rules than a player typing the command.

Powertools bypass entries under `command-cooldowns:`, but they **cannot** bypass `heal-cooldown` as that is part of the command itself. Please post the debug output from using the powertool.

> As far as the version is concerned, that server is running 1.12.2 and therefore isn't receiving updates unless bug fixes are needed. Is it wise to update to the current essX while running 1.12.2?

EssentialsX updates still support 1.12.2. We don't provide support for versions of EssentialsX older than the latest build of the plugin.

**Comment by triagonal** [comment]
I cannot reproduce this bug with the following versions:
```
[21:54:34 INFO]: Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1594 (MC: 1.12.2)
[21:54:34 INFO]: EssentialsX version: 2.17.1.13
[21:54:34 INFO]: LuckPerms version: 4.4.1
[21:54:34 INFO]: Vault version: 1.7.2-b107
```
with `heal-cooldown` set to the default of `60`, and with the user NOT having the heal bypass permission as can be seen in the debug output: https://gist.github.com/triagonal/efd013991fe65a7d0dfe8d165b4b813e

**Comment by FatherWh0** [comment]
We believe it was a conflict with another plugin. Thank you for your time.

**Comment by FatherWh0** [comment]
The debugging showed us that the issue was caused by a conflict with another plugin. I'm sry for wasting your time. Thank you for your help.
