### ISSUE TITLE
Fake quit/join

### ISSUE THREAD

**Issue by Vlader97** [EssentialsX/Essentials#2713]
### Feature request

**Feature description**
If admin use **/fake quit** the server show message that player leave the game. It also removes admin name from the tablist, from /list and from server list (https://prnt.sc/kk2o2j).
And If admin use **/fake join** the server show message that player join the game. It also show admin in tablist, in /list and in server list.

**How the feature is useful**
This feature will be especially useful for admins. It will help find cheaters better because cheaters behave differently when they know that admin is not on the server.

**Comment by kennyrkun** [comment]
I think instead of this being a completely new feature, it should be a part of vanish. Let admins configure it, and if enabled display a join/leave message when they activate vanish, similar to the plugin SuperVanish.

**Comment by Vlader97** [comment]
You're right that's a better option. Extend vanish with the optional feature of that message.

**Comment by darbyjack** [comment]
[W.I.P] PR Started -> https://github.com/EssentialsX/Essentials/pull/2771

**Comment by pop4959** [comment]
Perhaps this would be better off as a "spoofing" command? I'm not going to look into it right now, but this would only be possible if you can reliably get the messages for join/quit/etc and mimic them appropriately.

**Comment by pop4959** [comment]
Closing this because I don't think it's possible to get join/quit messages consistently, especially since any other plugin may be changing them.
