### ISSUE TITLE
Can't find item id Essentialsx

### ISSUE THREAD

**Issue by zBornConfused** [EssentialsX/Essentials#2715]
I'm using the last version of EssentialsX in a server with plugins and mods (pixelmon), and I need to use /give pixelmon:poke_ball (example) but the console says that unknow item name: pixelmon:poke_ball. How I can solve this? 
Thanks for reading!

**Comment by mdcfe** [comment]
We don't support hybrid server implementations (servers combining Bukkit with Forge).

To use plugins alongside Pixelmon, you should check out [Sponge](https://spongepowered.org/) - you can see instructions on setting up a Sponge server over at the [Sponge docs](https://docs.spongepowered.org/stable/en/server/index.html).
