### ISSUE TITLE
Can I disable economy?

### ISSUE THREAD

**Issue by Zhythero** [EssentialsX/Essentials#2717]
Hi is it possible to disable the economy feature of this plugin? I wanna use my own economy.

**Comment by montlikadani** [comment]
Remove the Vault from your server or writing the `max-money` option to -1.

**Comment by mdcfe** [comment]
What economy are you using?

If you install a different economy plugin, Vault should disable the Essentials economy and EssentialsX will use the other plugin instead.

**Comment by pop4959** [comment]
Closing as this appears to be solved.

**Comment by Harsh-7821** [comment]
hi uh so i want to delete/disable essentials economy cuz i don't want any economy in my server but i need essentials other commands any help?

**Comment by enigma072485** [comment]
> hi uh so i want to delete/disable essentials economy cuz i don't want any economy in my server but i need essentials other commands any help?

You can just not give your players the permissions to use any of the economy commands. You can also set a maximum money limit of 0 or such so they are not accruing funds. Also....make sure you don't accidentally enable any of the economy signs by accident. ;)
