### ISSUE TITLE
Adding glowstone in the /block command

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#2718]
Hi, Our players often ask us to integrate the glowstone into the /blocks features. Can you add it?

Thank you to you.

**Comment by montlikadani** [comment]
You not completed the template that we needed for more information.

I didn't know there was a `/block` command. There is none.

**Comment by mdcfe** [comment]
`/condense` only condenses blocks that have a two-way crafting recipe. 4 glowstone dust can be converted into 1 glowstone block in a crafting table, but you cannot place 1 glowstone block into a crafting table to get 4 glowstone dust back.

Manually adding glowstone would require us to hardcode recipes and bypass datapacks, so we're not planning to do this.

In *theory*, if you use a plugin or datapack to add the reverse recipe (1 glowstone = 4 dust) to your server, EssentialsX should pick that up and `/condense` will work. However, I haven't tested this so I can't confirm if this works.
