### ISSUE TITLE
Idea > Balance Formatting

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#272]
Hey,
So I thought a new idea to integrate could be this plugin here 

> https://www.spigotmc.org/resources/1-8-vault-balance-formatter.9757/

**Comment by Terrobility** [comment]
https://github.com/HunterGPlays/Essentials/commit/e131aeac4a1f308b37c1d84fd3766271435147e8
https://github.com/HunterGPlays/Essentials/commit/8130fb079a542061996bd9b42ef5f8321d41bfd4

I'm not going to pull request it, but this is what would need to be done. Also, a config option would be needed (but I don't have the time to add one in).

**Comment by mdcfe** [comment]
I believe this was implemented a while ago.
