### ISSUE TITLE
Kit Notch Bug

### ISSUE THREAD

**Issue by Sharquisha** [EssentialsX/Essentials#2726]
### Information

**Full output of `/ess version`**:
Latest ( 2.17.1.0)

**Server log**: 
Dont need no damn logs because that is the only error, Running regular TacoSpigot 1.8.8 hasnt been updated in years and I know for a damn fact that it has worked .

**EssentialsX config**: 
Default

### Details

**Description**  
Error whilst running /kit notch
https://gist.github.com/Sharquisha/0b1f1e862bcdfd5a3d952e0ad310d45c

**Steps to reproduce**  
Do /kit Notch

**Expected behavior**  
Supposed to give you shit but damn thing fucking errored

**Screenshots**  
Cant screenshot that shit

**Comment by mdcfe** [comment]
Please post the **full output** of `/ess version` and your **full startup log**. If we didn't need them, we wouldn't ask for them.

**Comment by triagonal** [comment]
Closing due to author inactivity. If you're still experiencing this issue, please reply here.
