### ISSUE TITLE
Support for names on /clear

### ISSUE THREAD

**Issue by iGabyTM** [EssentialsX/Essentials#2727]
### Feature request

**Feature description**
As the title says, add support for names on the `/clear` command.

**How the feature is useful**
It's annoying that nor default minecraft `/clear` command or ess' support names and sometimes you want to clear a specific item instead of a random one. Would be useful if it would also support regex.
Eg: `/clear [player] STONE 1 name:&aTest_Item` `/clear [player] DIAMOND_SWORD 1 name:(Epic|Rare)_Sword`

**Comment by pop4959** [comment]
Closing this issue since it looks like `/minecraft:clear` does support this now, and it's unlikely that Essentials will add this. You can also use `/invsee` to remove a specific item from someone's inventory.
