### ISSUE TITLE
Location of player balance config files?

### ISSUE THREAD

**Issue by CrikNJW** [EssentialsX/Essentials#2729]
### Information

Full output of `/ess version`:

**Server log:** 

**EssentialsX config** 

### Help request

**Problem**

I would like to know where i can find and edit the player balance config files, i have searched high and low for it but i cannot find it at all. I would also like to be able to edit the player balance to negative values.(Not using /economy command)
**What I have tried**

I have looked in FTP File Access as well as all EssentialsX related config files (including Vault).
**Screenshots**

**Comment by Radoje17** [comment]
It's is in plugins/userdata/
every player has it's own file

**Comment by triagonal** [comment]
As @Radoje17 mentioned above, you should find the player data files in `plugins/Essentials/userdata` in separate files named `<uuid>.yml` for each player.
