### ISSUE TITLE
Can't access cactus_green or green_dye with "/i" and "/give" command

### ISSUE THREAD

**Issue by axemwa** [EssentialsX/Essentials#2732]
### Possible Bug

**Description**
Can't access cactus_green or green_dye with "/i" and "/give" command

CACTUS_GREEN doesn't appear to be in the material list anymore
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

/essentials version output

[10:00:33 INFO]: **Server version: 1.13.2-R0.1-SNAPSHOT git-Paper-641 (MC: 1.13.2)**
[10:00:33 INFO]: EssentialsX version: 2.17.1.0
[10:00:33 INFO]: LuckPerms version: 4.4.1
[10:00:33 INFO]: Vault version: 1.7.2-b107
[10:00:33 INFO]: EssentialsXGeoIP version: 2.17.1.0

**Comment by mdcfe** [comment]
Have you tried deleting `items.json` and restarting the server? The latest `items.json` includes names for both 1.13 and 1.14 and should work on both versions.

**Comment by axemwa** [comment]
I tried that but now I get these errors

![image](https://user-images.githubusercontent.com/37608633/62820377-c1153780-bba2-11e9-970b-419a1b433c3c.png)


Do you think it might have to do with the fact that I'm using paper?
Cactus green is showing up in creative menu I just can't access it from essentials give or i commands

**Comment by mdcfe** [comment]
Could you run `/ess debug`, then try `/i green_dye 1` and post the error from the console log?

**Comment by axemwa** [comment]
sure

**Comment by axemwa** [comment]
https://pastebin.com/SRAXzHer

**Comment by axemwa** [comment]
I also use ViaVersion (so newer client versions can join) and ProtocolSupport (so older client versions can join) whether they be affecting it I dunno. I am joining with a 1.13.2 client same as the server though when I test this

**Comment by axemwa** [comment]
any luck identifying the issue?

**Comment by triagonal** [comment]
Can reproduce on the following version:
```
[01:23:00 INFO]: CONSOLE issued server command: /ess version
[01:23:00 INFO]: Server version: 1.13.2-R0.1-SNAPSHOT git-Paper-624 (MC: 1.13.2)
[01:23:00 INFO]: EssentialsX version: 2.17.1.11
```

Running `/itemdb` ingame while holding cactus green returns this along with [this stacktrace](https://gist.github.com/triagonal/f9f47fe6f713bf459a86bbbfb5ba6612) in debug mode:

![image](https://user-images.githubusercontent.com/10545540/63178595-b8829c80-c08d-11e9-9972-9d89735b456d.png)

**Comment by pop4959** [comment]
I can also confirm this in 1.15. Going to remove the "not enough info" label since I think it's pretty clear how to replicate this bug. The command `/minecraft:give <player> green_dye` works, but `/essentials:give <player> green_dye` does not.

Server details:
```
[15:25:39 INFO]: Server version: 1.15.1-R0.1-SNAPSHOT git-Paper-29 (MC: 1.15.1)
[15:25:39 INFO]: EssentialsX version: 2.17.1.29
[15:25:39 INFO]: LuckPerms version: 4.4.1
[15:25:39 INFO]: Vault version: 1.7.2-b107
[15:25:39 INFO]: EssentialsXProtect version: 2.17.1.29
[15:25:39 INFO]: EssentialsXGeoIP version: 2.17.1.29
[15:25:39 INFO]: EssentialsXChat version: 2.17.1.29
[15:25:39 INFO]: EssentialsXAntiBuild version: 2.17.1.29
[15:25:39 INFO]: EssentialsXSpawn version: 2.17.1.29
```

**Comment by mdcfe** [comment]
Could you test this with the `items.json` file from #2897? That should include fallbacks for items that changed between versions.

**Comment by pop4959** [comment]
@md678685 It fixes green_dye but not cactus_green. I'm assuming this may have been what you meant by "it doesn't quite have the same amount of aliases as the previous items.json" though, since I'm not sure if the game ever did call it cactus_green or if that was just an essentials built-in alias. In any case, I'd say it's working though with the PR.

**Comment by mdcfe** [comment]
Both legacy aliases and fallbacks to the old materials have been added as of d92f5ce71c96e1f0a7fb93eeab28ed97eb13e7a0 - you can download the latest build from the [downloads page](https://essentialsx.cf/downloads).
