### ISSUE TITLE
Add Phantom to spawn prevention list

### ISSUE THREAD

**Issue by maever** [EssentialsX/Essentials#2733]
### Feature request

**Feature description**
I would like Phantom to be added to the "Prevent the spawning of creatures" list.

**How the feature is useful**
Considering all other creatures already added to this list it would seem obvious to add.

**Comment by mdcfe** [comment]
Thanks for letting us know it's missing by default - we'll update it accordingly.

As far as I know, for now you can add `phantom` to the list yourself and it should prevent phantoms being spawned.
