### ISSUE TITLE
Ignore /tpa from a specific player

### ISSUE THREAD

**Issue by haeiven** [EssentialsX/Essentials#2734]
### Feature request

**Feature description**

Add a way to block TP requests from a specific player.

**How the feature is useful**

This could be a good thing against teleport requests spam from players. This was already asked 3 years ago by someone else but it was rejected.

**Comment by T1mTheEnchanter** [comment]
Pretty sure doing /ignore [player] will block tpa requests from them as well as chat/messages

**Comment by haeiven** [comment]
The idea isn't blocking the messages from a specific player too. Just blocking TP requests ^^

**Comment by pop4959** [comment]
I believe tptoggle already exists for this purpose. If players want to teleport to you, they can then just ask you themselves. You can also try ignore as mentioned above. As such, I'm not really convinced either that this adds much value.

**Comment by mdcfe** [comment]
As with #548, I'm not sure that most people would use this. Considering the additional complexity in both implementation and user experience of having a second ignore list, I don't see that this is worth adding.
