### ISSUE TITLE
ERROR [Essentials] You are running an unsupported server version!

### ISSUE THREAD

**Issue by Kasperfma** [EssentialsX/Essentials#2735]
### Information

**Full output of `/ess version`**:
"Unknown command. Type "/help" for help."

**Server log**: 
https://gist.github.com/Kasperfma/662aaa5f21f5a05b430a0ac9ba61472c

**EssentialsX config**: 
https://gist.github.com/Kasperfma/359617f93b52e801d4c8fddb60a5f9e2

### Details

**Description**  
I have restarted my whole server and started on a fresh. I want to install Essentials, but i can't and it gives me the error everytime i start up my server. It makes my server really weird and essentially wont work at all. I am running spigot 1.8.8

**Steps to reproduce**  
Start a fresh server, running spigot 1.8.8, and install the latest EssentialsX jar files. (version 2.17.1.11)

**Expected behavior**  
I expected it to work and i don't really know why it doesn't.

**Comment by md678685** [comment]
You're running Spigot 1.8, not 1.8.8.

You c

**Comment by mdcfe** [comment]
You're running Spigot's "CraftBukkit" 1.8, not Spigot 1.8.8.

You can obtain different versions of "CraftBukkit" or Spigot by running [BuildTools](https://www.spigotmc.org/wiki/buildtools/) to get a copy of the server - see the SpigotMC wiki for more info.

You can alternatively download the latest version of Paper 1.8.8 (which we recommend over "CraftBukkit" or Spigot) [here](https://papermc.io/api/v1/paper/1.8.8/latest/download).

**Comment by Kasperfma** [comment]
I've downloaded the 1.8.8 jar file from getbukkit and now it seems to work. Thanks alot for the help.
