### ISSUE TITLE
Make drop-items-if-full work on Essentials kits

### ISSUE THREAD

**Issue by KarlPro123** [EssentialsX/Essentials#2736]
# Shall we drop items instead of adding to inventory if the target inventory is full?
drop-items-if-full: false

I don't know what this option is currently affecting, but I wish that items would not drop if I use kit that has more items in it than room in my inventory and these items wouldn't drop. This is a issue, because I use a pvp server with no cooldown kits, and people spam it // it drops items on the ground and will generate lag.

Or another solution is a configurable option to make kit usable only one time per life so if you die you can get another kit, but it wouldn't give you 2 kits, get it?

**Comment by mdcfe** [comment]
The option currently only affects `/give`, but this could be added by checking whether the whole kit can fit in the inventory before we give it to the user.

**Comment by KarlPro123** [comment]
It would be amazing if it gets added!

**Comment by KarlPro123** [comment]
Hi, when would this be added or is it already added?

**Comment by kennyrkun** [comment]
This feature has not already been added. It will be added when a generous developer takes the time out of their day to implement it.

all we can do now is wait.

**Comment by rye761** [comment]
Looking into it.
