### ISSUE TITLE
Add option for custom AFK-kick message

### ISSUE THREAD

**Issue by Andre601** [EssentialsX/Essentials#2739]
### Feature request

**Feature description**

Implement a config option to customize the AFK-kick reason.

**How the feature is useful**

Customizing the kick message and reason would be useful for letting the player know why he was kicked.
While it is true that you could just f.e. edit the messages_en.properties file to change the AFK reason is it, in my opinion, a bit overkill to do this just for like one message in general.

**Comment by mdcfe** [comment]
You can create an empty `messages_en.properties` file (or the relevant version for your locale) and add individual lines to the empty file to customise them. This is documented on the [wiki](https://essentialsx.netlify.com/wiki/Locale.html#minor-changes).
