### ISSUE TITLE
Kits

### ISSUE THREAD

**Issue by mikebar12** [EssentialsX/Essentials#2741]
What am i doing wrong with essentials kits?? i can't understand, can you please help me? 

kits:
  newbie:
    delay: 7200
    items:
    - dpickaxe 1 efficiency:1 durability:1 fortune:1 name:&4Gigadrill lore:The_drill_that_&npierces|the_heavens
    - 298 1
    - 299 1
    - 300 1    
    - 301 1
    - 272 1
    - 273 1
    - 274 1
    - 275 1
    - 291 1
    - 364 10
  member:
    delay: 518400
    items:
    - 306 1 durability:1 protection:1
    - 307 1 durability:1 protection:1
    - 308 1 durability:1 protection:1
    - 309 1 durability:1 protection:1
    - 267 1 durability:1 sharpness:1 knockback:1
    - 258 1 durability:1 efficiency:1 fortune:1
    - 257 1 durability:1 efficiency:1 fortune:1
    - 256 1 durability:1 efficiency:1 fortune:1
    - 292 1 durability:1
    - 384 16
    - 264 16
    - 364 32
    - 322 8
    - 322:1 2
  vip:
    delay: 518400
    items:
    - 310 1 durability:1 protection:2
    - 311 1 durability:1 protection:2
    - 312 1 durability:1 protection:2
    - 313 1 durability:1 protection:2
    - 276 1 durability:1 sharpness:3 fire_aspect:2 looting:1
    - 278 1 durability:1 efficiency:3 fortune:1
    - 277 1 durability:1 efficiency:3 fortune:1
    - 279 1 durability:1 efficiency:3 fortune:1
    - 293 1 durability:1
    - 322:1 5
    - 364 64
    - 264 32
    - 384 32
  vip+:
    delay: 518400
    items:
    - 310 1 durability:2 protection:3
    - 311 1 durability:2 protection:3
    - 312 1 durability:2 protection:3
    - 313 1 durability:2 protection:3
    - 276 1 durability:2 sharpness:4 fire_aspect:2 looting:2
    - 278 1 durability:2 efficiency:4 fortune:2
    - 277 1 durability:2 efficiency:4 fortune:2
    - 279 1 durability:2 efficiency:4 fortune:2
    - 293 1 durability:2
    - 322:1 7
    - 364 64
    - 264 64
    - 384 64
  vip++:
    delay: 518400
    items:
    - 310 1 durability:3 protection:4
    - 311 1 durability:3 protection:4
    - 312 1 durability:3 protection:4
    - 313 1 durability:3 protection:4
    - 276 1 durability:3 sharpness:5 fire_aspect:2 looting:3
    - 278 1 durability:3 efficiency:5 fortune:3
    - 277 1 durability:3 efficiency:5 fortune:3
    - 279 1 durability:3 efficiency:5 fortune:3
    - 293 1 durability:3
    - 322:1 10
    - 364 64
    - 264 128
    - 384 128

**Comment by triagonal** [comment]
You can't use item IDs any longer, you instead must use item names. To find an item name you can hold an item in your hand and run `/itemdb`. Most item names will match their in-game names.
