### ISSUE TITLE
balancetop

### ISSUE THREAD

**Issue by GaMingN21** [EssentialsX/Essentials#2742]
When you use balancetop, it loads correclty and works 
correctly but it doesn't our own balance on balancetop.

Screenshot of the balancetop bug: https://prnt.sc/osuxj8

ESS Version: https://prnt.sc/osuxyx

**Comment by triagonal** [comment]
If you're opped, or have a wildcard like `*` or `essentials.*` then you're inheriting the permission `essentials.balancetop.exclude`, which will hide your balance from the balancetop list. Please ensure you haven't granted yourself this permission.

**Comment by thenullmatrix** [comment]
Yeah we had the same issue no wild card applied. All I did was to add essentials.balancetop.exclude false and works just fine now.

**Comment by pop4959** [comment]
Closing since this issue has been solved.
