### ISSUE TITLE
Adventure commands

### ISSUE THREAD

**Issue by KotixxCZ** [EssentialsX/Essentials#2744]
Hi,
if I write this command: /give KotixxCZ water_bucket 1 0 {"can_place_on":{"blocks":["sand"]}}
It will give me a water bucket, but I can't place it on a sand.
Is a problem somewhere in a plugin?

**Comment by mdcfe** [comment]
Check that the NBT was set correctly using `/minecraft:give`. EssentialsX doesn't intentionally touch adventure mode mechanics.

**Comment by triagonal** [comment]
It seems that the NBT is incorrect. The correct command syntax (on 1.14 at least) would be something like `/give player water_bucket 1 {CanPlaceOn:["minecraft:sand"]}`.

Using this command on the following version produces the desired effect (able to place on sand in adventure mode):
```
Server version: 1.14.4-R0.1-SNAPSHOT git-Paper-162 (MC: 1.14.4)
[22:55:04 INFO]: EssentialsX version: 2.17.1.13
```

**Comment by pop4959** [comment]
Closing due to no further response. If you're still having this issue, please let us know. It's likely that triagonal's answer is the solution here.
