### ISSUE TITLE
Essentials activates keepinventory for all players

### ISSUE THREAD

**Issue by Hyronymos-Old** [EssentialsX/Essentials#2748]
Essentials Version: 2.17.1.12

Startup Log: https://hasteb.in/gebeqoze.yaml

EssentialsX config: https://hasteb.in/oyifayis.yaml

Video: https://youtu.be/Zk3vpDp7U2o

Problem: Keepinventory is activated by EssentialsX

**Comment by Hyronymos-Old** [comment]
fixed by giving people -essentials.keepinv permissions, its default enabled for all

**Comment by darbyjack** [comment]
It's not given by default https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/plugin.yml#L560

**Comment by mdcfe** [comment]
Your log indicates you don't have a permissions plugin, or at least not one we support.

LuckPerms and some other permissions plugins work properly and respect defaults meaning they don't give the keepinv permission by default. PEX 1.x is known to ignore the defaults and we can't provide any guarantee that it will work properly.
