### ISSUE TITLE
Random crash and playerdata loss

### ISSUE THREAD

**Issue by Pet0203** [EssentialsX/Essentials#2749]
###  Information

**Full output of `/ess version`**:
Server version: 1.14.4-R0.1-SNAPSHOT git-Paper-172 (MC: 1.14.4)
EssentialsX version: 2.17.1.12
Vault is not installed. Chat and permissions may not work.

**Server log**: https://gist.github.com/Pet0203/bbc7862861449a187b39464490a94dfc
**EssentialsX config**: https://gist.github.com/Pet0203/4fe68670a7eca450617e881f2368a791
**Crash report**: https://gist.github.com/Pet0203/89c38d3e4b31c42b3e2061f05e250038
**Java runtime error** :https://gist.github.com/Pet0203/7184d06f9f7f95930047589d995cf68f
### Details

**Description**  

Server crashes, sometimes the process just dies without error reporting. Other times it throws crash report. Sometimes you spawn at the place you were when it crashed with your stuff, sometimes there is a rollback to when the world was last saved and other times you spawn as a new player with cleared inventory, interestingly you still keep your balance
**Steps to reproduce**  

Nothing, installed on a clean server running Paper. Same error happens on all 3 of my servers.
**Expected behavior**  

EssentialsX not crashing the server.
**Screenshots**  

**Extra:** This is actually a duplicate with https://github.com/EssentialsX/Essentials/issues/2663. We are running XenoPanel, however the same issue occurs starting the server manually via commandline.

**Comment by Pet0203** [comment]
Issue occurs without Essentials too. Is this a Paper/Spigot fault?

**Comment by mdcfe** [comment]
> Server log: gist.github.com/Pet0203/bbc7862861449a187b39464490a94dfc

This is not a startup log. Do not use `/reload` on a live server.

---

This issue seems to be unrelated to #2663 except for the fact the server crashes.

If this is happening without EssentialsX installed, EssentialsX is not causing the issue. I'd recommend contacting Paper or your host.
