### ISSUE TITLE
Cooldown commands

### ISSUE THREAD

**Issue by zuhir** [EssentialsX/Essentials#2751]
If you make a cooldown on command and you only put the command (without use, ex /helpop (without message)) the cooldown is activated.

Server version: 1.8.8-R0.1-SNAPSHOT
Plugin version: 2.17.1.0 (EssentialsX, EssentialsXChat and EssentialsXSpawn)

Sorry for my bad explanation, i'm no speak english.

**Comment by mdcfe** [comment]
You can use a regular expression like the one below to only enforce a cooldown if players provide arguments:
```
command-cooldowns:
  '^^helpop .*': 30
```

You can read more on the [Command Cooldowns wiki page](https://essentialsx.netlify.com/wiki/Command-Cooldowns.html).

**Comment by zuhir** [comment]
And how i can check if player use commands like /repair hand? Some times i use this command without item in hand and the cooldown is activated

**Comment by mdcfe** [comment]
You can't currently apply cooldowns to successful commands due to the way they work - the cooldowns doesn't know whether the command was successful or not because it's not specific to EssentialsX.
