### ISSUE TITLE
TPS drop after 1 minute

### ISSUE THREAD

**Issue by theocerdan** [EssentialsX/Essentials#2752]
Hello, when I start my server with just the essentials x plugin, after 1 minute and 10 seconds of startup, it makes my TPS drop by half

https://www.youtube.com/watch?v=9XEf7YNPTu0&feature=youtu.be (look the console)

spigot version : https://i.imgur.com/Is5IiUZ.png

**Comment by OverlordFreddo** [comment]
Please fill in ALL information:

**Full output of `/ess version`**:

```
<!-- Run the command in your console, and copy and paste the whole output here -->
```

**Server log**: ```<!-- Upload `logs/latest.log` to https://gist.github.com/, replace this with link -->```

**EssentialsX config**: ```<!-- Upload `plugins/Essentials/config.yml` to https://gist.github.com/, replace this with link -->```

### Details

**Description**  
```<!-- Replace this with a brief summary of the bug. -->```

**Steps to reproduce**  
```<!-- Replace this with exactly what you did to cause the bug. -->```

**Expected behavior**  
```<!-- Replace this with what you expected to happen. -->```

**Screenshots**  
```<!-- Replace this with screenshots, if necessary. -->```

**Comment by theocerdan** [comment]
**Full output of /ess version:**
[03:30:06 INFO]: Server version: 1.8.8-R0.1-SNAPSHOT git-PaperSpigot-"4c7641d" (MC: 1.8.8)
[03:30:06 INFO]: EssentialsX version: 2.17.1.0
[03:30:06 INFO]: Vault is not installed. Chat and permissions may not work.

**Server log:**
https://pastebin.com/HaEehTgD

**EssentialsX config:** 
https://pastebin.com/bkhbJ7Lp

**Description**
Hello, when I start my server with just the essentials x plugin, after 1 minute and 10 seconds of startup, it makes my TPS drop by half

**Steps to reproduce**
launch a server with essentials and wait 1 minute while watching the use of the cpu

**Expected behavior**
why the TPS is falling like this

**Screenshots**
https://www.youtube.com/watch?v=9XEf7YNPTu0&feature=youtu.be

**Comment by theocerdan** [comment]
**the timings paste :**  https://timings.aikar.co/?id=89514756dbbd43bf85dde3c33309cdf5

**Comment by AnnotationThomas** [comment]
May I ask which plugins are used on the server you're running? Most of the time it's not by Essentials why TPS drops

**Comment by mdcfe** [comment]
@ThomasKoreman If you check the provided log, you'll see there are no other plugins installed.

@theocerdan Could you try stopping your server and temporarily moving your existing world files to another folder? I don't see any correlation between lag and EssentialsX from your Timings report.

**Comment by md678685** [comment]
@ThomasKoreman If you check the provided log, you'll see there are no other plugins installed.

@theocerdan Could you try stopping your server and temporarily moving your existing world files to another folder? I don't see any correlation between lag and EssentialsX from your Timings report.

**Comment by theocerdan** [comment]
> May I ask which plugins are used on the server you're running? Most of the time it's not by Essentials why TPS drops

As you can see in the video I don't use any plugin appart Essentials X

**Comment by theocerdan** [comment]
> @ThomasKoreman If you check the provided log, you'll see there are no other plugins installed.
> 
> @theocerdan Could you try stopping your server and temporarily moving your existing world files to another folder? I don't see any correlation between lag and EssentialsX from your Timings report.

I did better. I created a new virgin server with paper spigot (and I tested with spigot too) and it still drops

**Comment by darbyjack** [comment]
Going to guess it's something with your CPU / Machine in general. Just ran a clean server myself, left it running for 3 hours, no TPS drop at all.

**Comment by mdcfe** [comment]
@theocerdan What startup flags are you using to run your server? Did you modify `server.properties`/`bukkit.yml`/`spigot.yml`/`paper.yml`?

**Comment by pop4959** [comment]
Have you tried running the same server on another machine, or running the server without any plugins at all? As others have mentioned, there is no noticeable correlation between the lag and EssentialsX.

**Comment by pop4959** [comment]
Closing due to lack of response
