### ISSUE TITLE
/hat does not work for opped players

### ISSUE THREAD

**Issue by ironik42** [EssentialsX/Essentials#2753]
### Information

Full output of `/ess version`:

**Server log:** 

**EssentialsX config** 

### Help request

**Problem**

**What I have tried**

**Screenshots**

**Comment by triagonal** [comment]
Resolved on the [discord server](https://discord.gg/PHpuzZS).

Related: #2574 

For anyone else having this same issue, if you're opped or have a wildcard such as `*` or `essentials.*`, you can negate the permission `essentials.hat.prevent-type.*` in order to restore functionality.
