### ISSUE TITLE
"Console" title in locale file

### ISSUE THREAD

**Issue by Lammendam** [EssentialsX/Essentials#2756]
### Feature request

**Feature description**
Put "Console" string to locale file. This is that "Console" that appears to player when he receive PM from console.

**How the feature is useful**
This is useful when staff want to say something to the player on behalf of the console. For example, notify the player of some important event but also want to customize Console name to more friendly and interesting name.

**Comment by darbyjack** [comment]
PR opened https://github.com/EssentialsX/Essentials/pull/2758

**Comment by pop4959** [comment]
@darbyjack Still planning to give this a shot? If not, maybe unassign yourself from this.
