### ISSUE TITLE
my inventory deletes when I die

### ISSUE THREAD

**Issue by ZEPPI3** [EssentialsX/Essentials#2759]
### Information

Full output of `/ess version`:
[Server thread/INFO]: Server version: 1.14.4-R0.1-SNAPSHOT git-Bukkit-31adfa7 (MC: 1.14.4)
[Server thread/INFO]: EssentialsX version: 2.17.1.0

[latest.log](https://github.com/EssentialsX/Essentials/files/3527877/latest.log)

[config.txt](https://github.com/EssentialsX/Essentials/files/3527883/config.txt)

 

 

### Help request

When I die all items in my inventory delete. When I die on the "you died" screen i can see all items that were in my hotbar are still there and when i either /back or go to the place where i died the items are gone 

I have deleted essentials x and left everything else in my plugins folder the same and that fixed the problem. I have also tried going into the config and also tried turning off essentials.keepinventory 

![Inked2019-08-21_21 06 12_LI](https://user-images.githubusercontent.com/54382610/63478382-a8850700-c457-11e9-803e-e3526c23f3fa.jpg)

**Comment by triagonal** [comment]
The permission you want to negate is `essentials.keepinv`, not `keepinventory`.
