### ISSUE TITLE
/speed permission

### ISSUE THREAD

**Issue by Rida94** [EssentialsX/Essentials#276]
if a player got essentials.speed permission without having the permission essentials.speed.fly or essentials.speed.walk they will be able to have walking and flying speed and if they only have essentials.speed.fly or essentials.speed.walk they wont be able to use /speed

**Comment by khobbits** [comment]
FYI, it was set up so that if you gave both "ess.speed" and "ess.speed.fly" they could only use speed for flying, not walking.  But if you gave access to 'ess.speed' with no additional permissions, they could do both.

This was because the 'fly/walk' perms were added later.

**Comment by pop4959** [comment]
Not a bug, as Khobbits mentioned it is due to historical reasons. Shouldn't be too confusing. especially with the Essentials Permissions documentation page, which clearly outlines what each permission allows.
