### ISSUE TITLE
World Home Restrictions

### ISSUE THREAD

**Issue by EmbraceTheBass** [EssentialsX/Essentials#2760]
I am trying to set home permissions so that my players will be able to set homes in only the overworld, as I already have warps for both the nether and end. I've enabled world home permissions in attempt to limit sethomes in the nether and end to 0 but all it seems to have done is prevent players from crossing worlds using /home. I'm certain i'm going about this the wrong way and could use a little guidance.

**Comment by mdcfe** [comment]
Most permissions plugins support per-world permissions. You can give `essentials.sethome` in the overworld and not the Nether or End.
