### ISSUE TITLE
Player item meta variable in give command not functional.

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#2765]
Paper dev 175 (Spigot 1.14.4)
EssentialsX dev 780

Spawning in a head with the command ``/give <player> player_head 1 player:<player>`` doesn't seem to work.

Did it break in this commit? 
https://github.com/EssentialsX/Essentials/commit/5f9eb22d23d76dfb5726d25f9caf0a09b6fa54fa

Edit: Downgrading to dev 779 fixes the issue, so commit definitely broke it in 1.14.

**Comment by triagonal** [comment]
Can reproduce issue on the following:
```
[17:06:00 INFO]: Server version: 1.14.4-R0.1-SNAPSHOT git-Paper-176 (MC: 1.14.4)
[17:06:00 INFO]: EssentialsX version: 2.17.1.13
```
Downgrading to 2.17.1.12 does fix the issue as mentioned above.

**Comment by mdcfe** [comment]
@mibby @triagonal Thanks for reporting and testing this. I think I've spotted the issue and  219012bc3579565ebe4b313031f13dd12b542e61 should fix this - could you try the latest build?

**Comment by triagonal** [comment]
Now works as expected on:
```
[10:07:14 INFO]: Server version: 1.14.4-R0.1-SNAPSHOT git-Paper-176 (MC: 1.14.4)
[10:07:14 INFO]: EssentialsX version: 2.17.1.15
```
EDIT: Tested and confirmed to be fixed on all EssentialsX-supported versions using the latest EssentialsX and Paper builds (1.8.8, 1.9.4, 1.10.2, 1.11.2, 1.12.2, 1.13.2, 1.14.4) @md678685

**Comment by mibby** [comment]
Seems to be functional again with the fix commit, thanks!
