### ISSUE TITLE
EssentialsXProtect villager-to-zombie-villager

### ISSUE THREAD

**Issue by Fix3dll** [EssentialsX/Essentials#2766]
I set villager-death to false. We all know villager is functional mob in game and i dont want to see they are dead. When zombie try to attack villager, villager cant transform to zombie villager. I want this option for transform. No damage but can transform. And 1 more option zombie-villager-death for set false. If its possible with code it looks like nice idea.

**Comment by mdcfe** [comment]
This was implemented in #2836.
