### ISSUE TITLE
filled_map is unknown item

### ISSUE THREAD

**Issue by Capri205** [EssentialsX/Essentials#2768]
Hi. Seems I cant get a filled map using the /give command when EssentialsX is enabled. Essentials is intercepting the command and giving the error unknown item. Disabling Essentials I can get the item without issue.

I am using  2.17.1.0 on 1.14.4 spigot.

F451

**Comment by triagonal** [comment]
Cannot reproduce on the following version:
```
[13:21:17 INFO]: Server version: 1.14.4-R0.1-SNAPSHOT git-Paper-176 (MC: 1.14.4)
[13:21:17 INFO]: EssentialsX version: 2.17.1.15
```
Using `/give playername filled_map 1` works as expected. Try updating EssentialsX to the latest build [on the build server](https://ci.ender.zone/job/EssentialsX/) and deleting the `items.json` file in `plugins/Essentials` to let the plugin generate a new copy.

**Comment by Capri205** [comment]
Thanks for checking. I did try that actually, but no luck. I am trying to give myself filled maps with specific ID's. The command above gives me a new map with a new sequence number. I am getting the error giving a specific map ID. For example:

/give playername filled_map{map:691} 1
Error: Unknown item name: filled_map{map:691}

For now I have to start the server without Essentials to get the maps I need, then restart with Essentials to place them. Essentials doesn't appear to parse the meta data.

Cheers.

**Comment by mdcfe** [comment]
To specify NBT in EssentialsX, you need to move the NBT to the end of the command:
```
/give player filled_map 1 {map:691}
```

Alternatively, use `/minecraft:give` for the vanilla syntax.

**Comment by Capri205** [comment]
ah. great. Thanks a lot for that. Works a treat.
