### ISSUE TITLE
hat command

### ISSUE THREAD

**Issue by noikonoikola** [EssentialsX/Essentials#2769]
I'm trying to use the / hat command on my server but there is an error message:
hatfail: You must have something to wear in your hand.
I have permission to that command and op on the server.
The command doesn't work on any item: e.g. Helmet, Zombie head, On any block or item, etc..
Normal players who dont have op has permission to use command /hat can put everything on its head.
![bug](https://user-images.githubusercontent.com/52139801/64068428-a7ff2400-cc40-11e9-9532-df0081faed7e.jpg)

**Comment by triagonal** [comment]
Please do not open duplicate issues. (#2767)
