### ISSUE TITLE
Request: /tmsg - /tr <username> - Toggle PM for player

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#277]
As a server admin the most infurating thing when talking to a player with /msg is that someone ALWAYS messages me that are not part of the conversation, therefor breaking my /r to who I was talking to.

This may not be the best solution, but its an easy one to implement.

Allow a (with permission) to toggle who you are messaging /tr could toggle only replying to the current person thats in your /r or /tmsg could toggle all /msg be sent to that person without having to type their username.

Using it again resets it to its normal use.

**Comment by SupaHam** [comment]
There is a configurable feature you may set called `last-message-reply-recipient` that if set to `true` makes your reply-recipient whoever you messaged last and not whoever messaged you last, with the exception that if you do not have a reply-recipient then whoever messaged you last will be your reply-recipient.

**Comment by TomLewis** [comment]
Oh!? This isn't in my config, was it added recently? 
Does this go in the chat section?
Edit, figured it out after regenerating the configs.
This is flipping amazing, This should be on the main features list.

**Comment by drtshock** [comment]
@SupaHam add to wiki pls

**Comment by SupaHam** [comment]
https://github.com/drtshock/Essentials/wiki#controlled-private-messaging

**Comment by TomLewis** [comment]
After using this, there could be a small change that would improve it.
https://github.com/drtshock/Essentials/issues/279
