### ISSUE TITLE
Offline Player Placeholder Support

### ISSUE THREAD

**Issue by Midnight9746** [EssentialsX/Essentials#2772]
### Feature request

**Feature description**

 Letting Essentials placeholders from Placeholderapi work with offline players
**How the feature is useful**

Server staff could use it in instances of top donor, player of the month, etc. As far as I found no placeholder supports offline rank/nicknames of players. It could also be used for other placeholders

**Comment by mdcfe** [comment]
We don't maintain the PlaceholderAPI Essentials expansion. You should report this at [PlaceholderAPI/Essentials-Expansion](https://github.com/PlaceholderAPI/Essentials-Expansion/issues).

**Comment by Midnight9746** [comment]
Okay, will do!
