### ISSUE TITLE
change messagge

### ISSUE THREAD

**Issue by leoncp9** [EssentialsX/Essentials#2776]
how can i change messagge of this messagge?
https://prnt.sc/p1un1k
i don't find him on messages_en.properties
https://prnt.sc/p1un3u

**Comment by triagonal** [comment]
The key you're looking for is `teleportHome` - line 524 in the default `messages.properties`
```
teleportHome=\u00a76Teleporting to \u00a7c{0}\u00a76.
```

**Comment by leoncp9** [comment]
thank you
