### ISSUE TITLE
Disabling nicks

### ISSUE THREAD

**Issue by willc5** [EssentialsX/Essentials#2779]
Is there a way to completely disable nicknames? I'm trying to change up my chat formatting

I've tried:
- using /nick ** off but it crashes after about 2 minutes because of so many players
- changing {DISPLAYNAME} it chat formatting to {USERNAME} but apparently that doesn't work in the chat format section

**Comment by montlikadani** [comment]
Use the `disabled-commands` found in the config file and put the nick command to the list.
https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/config.yml#L157

**Comment by willc5** [comment]
Will this get rid of players nicks?

**Comment by montlikadani** [comment]
Yes, the players still get the setted nicknames. But the command will be disabled,

**Comment by triagonal** [comment]
That won't remove existing nicknames, no. You could try and write a simple python script to edit the playerdata files and remove the nicks but the only way to do it through Essentials (afaik) is to use the `/nick ** off` function.

**Comment by willc5** [comment]
> That won't remove existing nicknames, no. You could try and write a simple python script to edit the playerdata files and remove the nicks but the only way to do it through Essentials (afaik) is to use the `/nick ** off` function.

Yeah /nick ** off just crashes after like 2 minutes not removing all nicks
If I could make only the username display in chat instead of nick it would not be a problem

**Comment by untuned** [comment]
> > That won't remove existing nicknames, no. You could try and write a simple python script to edit the playerdata files and remove the nicks but the only way to do it through Essentials (afaik) is to use the `/nick ** off` function.
> 
> Yeah /nick ** off just crashes after like 2 minutes not removing all nicks
> If I could make only the username display in chat instead of nick it would not be a problem

If using EssentialsChat, use `{USERNAME}` instead of `{DISPLAYNAME}`.

**Comment by triagonal** [comment]
> If using EssentialsChat, use `{USERNAME}` instead of `{DISPLAYNAME}`.

`{USERNAME}` does not currently exist as a placeholder for EssentialsXChat. Available placeholders are: 

```
{DISPLAYNAME} 
{MESSAGE} 
{GROUP}
{WORLD} 
{WORLDNAME} 
{SHORTWORLDNAME} 
{TEAMPREFIX} 
{TEAMSUFFIX} 
{TEAMNAME}
{PREFIX}
{SUFFIX}
```

PR #2781 would add this functionality, but it hasn't been merged yet.

**Comment by triagonal** [comment]
While this doesn't completely solve your issue, the PR has been merged and you can now use `{USERNAME}` in the chat format with EssentialsX versions `2.17.1.17` and above.
