### ISSUE TITLE
Leather Armor Becoming Improperly Defined

### ISSUE THREAD

**Issue by Dendrobyte** [EssentialsX/Essentials#278]
Hi there!

So my issue is that leather armor, whenever I attempt to dye it with a hexidecimal value or an RGB value, the kit appears to be improperly defined. I have unsafe-enchantments enabled to true. Was curious if this is a known issue?
Things to clarify:
1. A kit I have created within a previous version of essentials that has dyed leather armor still works
2. It doesn't work with or without enchantments, and it doesn't work with or without a name/lore attached
3. /createkit is the only method I am using because I am not aware of any other. I attempted to edit the kits in the config, but to no avail.

Thanks in advance!

**Comment by SupaHam** [comment]
What version of EssentialsX are you using?

**Comment by Dendrobyte** [comment]
Currently on EssentialsX 2.0.1-b192

**Comment by SupaHam** [comment]
That is your issue. Before reporting issues, make sure you're on the latest version of EssentialsX.
