### ISSUE TITLE
color code blocking

### ISSUE THREAD

**Issue by untuned** [EssentialsX/Essentials#2783]
### Feature request

**Feature description**

Allow blocking specific color codes in many places, such as signs, nicks, chat, etc.
**How the feature is useful**

Allows us to block color codes we don't want users to use, such as black, or dark blue.

**Comment by triagonal** [comment]
This is already possible for both chat and nicks, as far as I know. However, I don't believe it's possible for signs (yet).

To block a certain color code (e.g. red) from being used in chat by a certain user, you can negate the permission `essentials.chat.red`.

Similarly, to block a certain color code (e.g. aqua) from being used in nicknames, you can negate the permission `essentials.nick.aqua`.

You can find a full list of the color names [here](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/ChatColor.html).
