### ISSUE TITLE
Condense snowballs into snow blocks.

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#2784]
Would it be possible to allow condense to merge snowballs into snow blocks?

**Comment by triagonal** [comment]
Please see [this answer](https://github.com/EssentialsX/Essentials/issues/2718#issuecomment-518139894) as to why EssentialsX will not condense certain materials.

(tl;dr since you can't **craft** snow blocks into snowballs, EssentialsX won't condense snowballs into snow blocks)

**Comment by mibby** [comment]
Perfectly understandable, no problem.
