### ISSUE TITLE
"spawn-on-join: true" doesn't work

### ISSUE THREAD

**Issue by 100petr** [EssentialsX/Essentials#2786]
### Information

**Full output of `/ess version`**:

```
<!-- Run the command in your console, and copy and paste the whole output here -->
```
https://gist.github.com/100petr/95e1c44df92a8c2bbf358250e19b009f
**Server log**: 
https://gist.github.com/100petr/1e92817f56113c498fb592a9107bcdf2
**EssentialsX config**: 
https://gist.github.com/100petr/c42ca73a795433f047a680b1ac869a78
### Details

**Description**  

"spawn-on-join: true" doesn't work
**Steps to reproduce**  

I connected to the server
**Expected behavior**  

**Screenshots**

**Comment by triagonal** [comment]
Only **one** of the `spawn-on-join` options in the config should be uncommented. If you want all players to teleport to spawn when joining, use the following:
```
# Teleport all joining players to the spawnpoint
spawn-on-join: true
# The following value of `guests` states that all players in group `guests` will be teleported to spawn when joining.
#spawn-on-join: guests
# The following list value states that all players in group `guests` and `admin` are to be teleported to spawn when joining. 
#spawn-on-join:
#- guests
#- admin
```
 If you only want one or some groups to be teleported to spawn when joining, you should use 
```
# Teleport all joining players to the spawnpoint
#spawn-on-join: false
# The following value of `guests` states that all players in group `guests` will be teleported to spawn when joining.
spawn-on-join: guests
# The following list value states that all players in group `guests` and `admin` are to be teleported to spawn when joining. 
#spawn-on-join:
#- guests
#- admin
```
or
```
# Teleport all joining players to the spawnpoint
#spawn-on-join: false
# The following value of `guests` states that all players in group `guests` will be teleported to spawn when joining.
#spawn-on-join: guests
# The following list value states that all players in group `guests` and `admin` are to be teleported to spawn when joining. 
spawn-on-join:
- guests
- admin
```

Note that in each example, only a single `spawn-on-join` option is uncommented at any one time. 

**Also, any player with the permission `essentials.spawn-on-join.exempt` (such as an OP or a player with wildcard permissions) will not be teleported to spawn on join.**

Please ensure you correct your config file and check that your permissions are set correctly.

**Comment by triagonal** [comment]
Closing due to no response from author. Feel free to reply to this thread (or join [the MOSS discord](https://discord.gg/PHpuzZS)) if you require further help with this problem.

**Comment by canoliedev** [comment]
Thanks it worked the last `essentials.spawn-on-join.exempt` thing
