### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by Derrpo** [EssentialsX/Essentials#2787]
so im working on a server atm and for some reason my essentials commands lag the server such as /fly, /tp and even /op
we have tried to find many solutions to the problem
we looked into the possibility of it being a different plugin but when we added and removed every plugin one by one the one that fixed the lag problem when we removed it was essentials
if you could let me know some possible solutions that would be great thanks

**Comment by triagonal** [comment]
Please fill out the issue template completely - we can't help without the information it provides. In addition, please include a recent timings report.

**Comment by pop4959** [comment]
Closing due to lack of response
