### ISSUE TITLE
Request: last-message-reply-recipient: add a cooldown

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#279]
last-message-reply-recipient is a great enhancement, but its main flaw is if you had a conversation, then a long while past then someone else messages you, out of habit you would instinctively do /r to reply to them. Adding a cooldown period would allow this to time out the last conversation to this new one IF a cooldown period has passed since the last message was sent. This could be based on the time the last person messaged you thats kept in /r.

**Comment by drtshock** [comment]
Sounds like a good idea.

**Comment by SupaHam** [comment]
Yeah, I like this idea a ton. I'll add it sometime soon. Thanks :D

**Comment by SupaHam** [comment]
ca38768
