### ISSUE TITLE
Notification Issue For sethome, delhome, home

### ISSUE THREAD

**Issue by xXxDarkGhostxXx** [EssentialsX/Essentials#2791]
Ok so i have a weird issue. I use homespawnwarp plugin to manage homes and warps. I have disabled essentials home options in the config file. When setting a home, deleting a home, wrapping to a home myself and members are getting a weird notification under the homespawnwarp notification. (The white notification is what i am referring to and is unwanted). 

If i remove EssentialsX it goes away. I even tried the default config for EssentialsX and it still shows up.

![sajaiksd gh](https://user-images.githubusercontent.com/55526542/65366934-62f35f80-dbf8-11e9-8917-2527cc5c450f.jpg)

Any help would be appreciated. Thanks!

**_Server Version: Spigot Jar 1.14.4
Plugins In Use Currently
-AsyncWorldEdit-3.6.10
-BetterSleeping-2.5.2
-ChestSort
-EssentialsX-2.17.1.0
-EssentialsXChat-2.17.1.0
-HomeSpawnWarp
-LuckPerms-Bukkit-4.4.1
-PlaceholderAPI-2.10.4
-PluginConstructorAPI
-SimpleBackup-1.8
-TAB v2.5.2
-Vault
-worldedit-bukkit-7.0.1
-worldguard-bukkit-7.0.1-rc2-dist_**

**Comment by mdcfe** [comment]
Don't use `disabled-commands`. It doesn't disable commands, it's just a leftover from the original Essentials plugin.

---

It looks like an issue on HomeSpawnWarp's side. It looks like you're only using it for homes - what home functionality from that plugin do you need that you can't achieve with EssentialsX?

**Comment by xXxDarkGhostxXx** [comment]
Alright i will remove those and put that section back to its defaults. But there is still the matter of those notifications popping up. Any ideas on how to remove or at least hide them?

       __________________________________________________

Edit: Didn't see your second part. I just like being able to customize the notification from homespawnwarp for when commands are used. (The blue text displaying in the picture)
I may honestly just end up scrapping the plugin and setup home limits and stuff through essentials if i cannot find a solution to this.

**Comment by pop4959** [comment]
You can use [commands.yml](https://bukkit.gamepedia.com/Commands.yml) to disable commands. This is the recommended way, since it is done through the server itself, and not through the individual plugins you are concerned with.

**Comment by xXxDarkGhostxXx** [comment]
But if i disable the commands no one will be able use them as homespawnwarp uses the same commands as essentialsX. (/delhome, /sethome, home)

**Comment by pop4959** [comment]
Disable them using the fully qualified name. Ie. `essentials:home`

**Comment by xXxDarkGhostxXx** [comment]
Correct me if i am wrong but this is what it should look like in my commands.yml file.
![001](https://user-images.githubusercontent.com/55526542/65393893-15403980-dd55-11e9-8ed7-0fcd5dd756a0.PNG)

If so this method is not working. I still get that weird white text from essentials.

**Comment by xXxDarkGhostxXx** [comment]
Closing my ticket.

I edited the plugin.yml inside EssentialsX.jar file to not have those commands anymore. So essentially hard coding the plugin itself to not have those instead of trying to block them (since this didn't seem to work). This resolved the issue for me. Thanks for the help pop4959 & md678685

**Comment by pop4959** [comment]
Sorry my bad, it should be something like this:
```  home: homespawnwarp:home```

This will tell the server that when someone types `/home`, they mean to use `/homespawnwarp:home` and not `/essentials:home`.

Anyways, you fixed it in an interesting way. If it works for you, great! Glad you were able to find a solution.

**Comment by mdcfe** [comment]
FYI, you can customise almost every EssentialsX message: [Locale](https://essentialsx.netlify.com/wiki/Locale.html)
