### ISSUE TITLE
[Request] Whitelist of crafting recipes to include in /condense

### ISSUE THREAD

**Issue by aeonlamb** [EssentialsX/Essentials#2792]
### Feature request

**Feature description**
A configurable list of crafting recipes to include when a player runs the /condense command, possibly in config.yml. For example, being able to modify it to prevent people from condensing diamonds, or allow for condensing quartz to quartz blocks, or otherwise accommodating for custom crafting recipes introduced by datapacks.  

**How the feature is useful**
The players on my server use /condense when mining quite a lot, and they complain to me often about the command not being able to condense other items like quartz into quartz blocks, etc. We also have a custom crafting recipe on the server which allows you to craft furnaces back into cobblestone, as a form of "compacting" cobblestone. I think a lot of servers would benefit from such a feature, as I'm sure there are plenty of others which allow un-crafting items that you normally couldn't in vanilla.

**Comment by mdcfe** [comment]
`/condense` detects any 2x2 or filled 3x3 square pattern on the server provided there is an equivalent reverse crafting recipe. I don't see any need for a whitelist - the command respects all valid crafting recipes on the server as long as Bukkit makes them visible to plugins (which includes data pack recipes as far as I know). If you have both a quartz item -> block and block -> item recipe on your server and they aren't being picked up, please file a separate bug report.

---

What you're asking for is instead a way to add custom recipes specific to the `/condense` command. This has been requested before, and while this might seem useful, allowing this fundamentally changes the behaviour of the command. The defined behaviour of the command is to respect all valid recipes registered with Bukkit as long as they are reversible. Allowing non-reversible recipes or recipes that don't match the vanilla convention of a filled square in `/condense` only creates confusion and potentially frustration at the behaviour not working in the same expected manner across different servers - a player may be carrying redstone or coal that they want to condense, but they may also be carrying quartz or wood and probably don't want to convert it to quartz blocks or crafting tables without a way to turn it back.

I don't see most servers having a use case for this, and combined with the usability issues, we will not be implementing this in the foreseeable future.
