### ISSUE TITLE
After installing bungecord issues happened/Player data not being read but was there

### ISSUE THREAD

**Issue by testablebox048** [EssentialsX/Essentials#2794]
# Information

Full output of `1.12 version`:

**Server log:** 

**EssentialsX config** 

### Help request

**Problem**

**What I have tried**

**Comment by mdcfe** [comment]
In the future, please read and follow the instructions in the template.

---

When using BungeeCord, you need to set up [IP forwarding](https://www.spigotmc.org/wiki/bungeecord-ip-forwarding/) for your server to know what player is who. This is not an EssentialsX issue.
