### ISSUE TITLE
 https://ci.drtshock.net/job/EssentialsX is DOWN

### ISSUE THREAD

**Issue by drhax9908** [EssentialsX/Essentials#2798]
I went to go to the jenkins build site today, and it gave me a name resolution error. I did a dns lookup and it turns out the domain has no IP's set for the root of the domain or for the jenkins build server. It seems to be resolving to cloudflare without an IP address set, so it won't resolve. Please fix this

**Comment by triagonal** [comment]
The CI server listed in the README and on the Spigot page is https://ci.ender.zone/job/EssentialsX/ - I'm not sure where you found the above link, but you should probably use this one instead.

**Comment by mdcfe** [comment]
`ci.drtshock.net` has been offline for several years. You can use `ci.ender.zone` as mentioned above.
