### ISSUE TITLE
/tppos yaw is wrong

### ISSUE THREAD

**Issue by neokyle** [EssentialsX/Essentials#280]
Originally opened issue #225 which was closed about a month ago and labeled fixed.

Issue is still occurring, using version 2.0.1-b227

**Comment by LHammonds** [comment]
The /tppos command is incorrect in version 2.0.1-b301. The yaw is reversed from the results of /getpos. All the teleportation signs I had setup are sending players to expected locations but are facing 180 degrees in the wrong direction.

Example: If /getpos says you are at 150 50 140 0 0, then you have to use /tppos 150 50 140 180 0 to get to the same facing direction.

**Comment by RENMX** [comment]
I'm still having this issue on the latest version of EssentialsX - Is there any chance of a working fix? Thanks.

**Comment by SupaHam** [comment]
@RenMX I've tested it and it works just fine. It does not match `/getpos` which I am fixing now.

**Comment by SupaHam** [comment]
@LHammonds `/getpos` now returns proper number based on `/tppos`.

This has been fixed in 5540683. You can grab the fix from [build 406](https://ci.drtshock.net/job/EssentialsX/) on the CI server.

**Comment by RENMX** [comment]
@SupaHam It never occurred to me that it was /position or /getpos that was wrong. Thank you.
