### ISSUE TITLE
essentials duplicating glitch from hat

### ISSUE THREAD

**Issue by Simonk02** [EssentialsX/Essentials#2803]
### Information

Full output of `/ess version`:

**Server log:** 

**EssentialsX config** 

### Help request

**Problem**
 When i hold any items and hold shift and spam right clicks on the helmat it duplicates the items. 

**What I have tried**
 i changed allow-direct-hat to false from config but it still duplicates

**Screenshots**

**Comment by pop4959** [comment]
Please fill out the issue template entirely please, so that it can be reproduced reliably without potentially wasting contributors' time. All of the information is important.

**Comment by MrFlacko** [comment]
This is still an issue though happens when you get someone to kill you while wearing a shulker box on your head

**Comment by Chew** [comment]
Please open a new issue, filling out the template completely.
