### ISSUE TITLE
/back only to death location

### ISSUE THREAD

**Issue by 777Ricky** [EssentialsX/Essentials#2809]
### Feature request

**Feature description**

A feature to make it so people can only /back to their death location instead of death location and previous teleport location

**How the feature is useful**

So you can prevent people teleporting back to previous location and only use it for when they die

**Comment by Tommeh1** [comment]
Players do not have permissions to use /back on death even though they got the essentials.back.ondeath permission

**Comment by pop4959** [comment]
@CraftalotReloaded That's because `essentials.back` is required to use `/back` to any capacity. All commands have a base permission like that. This would require changing the functionality of the command, probably through some config option.

**Comment by Tommeh1** [comment]
Although i have ever since that comment shutdown my server due to immature co-owners and the unreliable nature of plugins i would like to note that i am well aware that they require essentials.back for that and that it didn't work.
My plans shifted to making as many things as possible that are usually handled by plugins as mods

**Comment by triagonal** [comment]
This is possible by granting `essentials.back` and `essentials.back.ondeath`, and setting `essentials.back.onteleport` to false in your permissions plugin. If this doesn't work, try updating your EssentialsX version to v2.19.0 or above (behaviour was temporarily broken, re-added in #4264).

Players have `essentials.back.onteleport` by default, so it needs to be negated for death-only /back functionality.
