### ISSUE TITLE
AFK Message Backwards

### ISSUE THREAD

**Issue by DrChiz** [EssentialsX/Essentials#281]
So if someone is afk and you message them, it tells you that YOU are afk and cannot/may not response.

Example in the pictures below.
https://gyazo.com/7a374e1e38690fdfa9e9e5bbfb4e40cb
https://gyazo.com/e185a690510633d2177f5b3e440562b3

Thank you.

**Comment by SupaHam** [comment]
What version of Essentials are you using?

**Comment by DrChiz** [comment]
Sorry for taking so long.

We are running, Essentials version 2.0.1-b214

**Comment by SupaHam** [comment]
This was fixed in b215. I suggest you upgrade to the latest version for the best experience! :)
