### ISSUE TITLE
Trade Signs

### ISSUE THREAD

**Issue by omeedoski** [EssentialsX/Essentials#2810]
i have this issue when i make a sign even with /itemno like for example iron_ingot i use ibar
in a sign i use 
[trade]
$500
32 ibar:2

it says
Quantities must be greater than 0
please give me a fix for this
![2019-10-05_02 28 37](https://user-images.githubusercontent.com/56178546/66245864-112ef700-e719-11e9-8934-513a6eecbbfc.png)

**Comment by pop4959** [comment]
Please don't ignore the issue template. Please fill out all the information requested, or we will not be able to look into the issue.

**Comment by omeedoski** [comment]
> Please don't ignore the issue template. Please fill out all the information requested, or we will not be able to look into the issue.

sorry didnt really get your point ... i think i made my issue clear .... i cant make trade signs for all item in minecraft 
for example if i want to make a trade sign to trade scaffoldings for money 
i sell scaffolding 32 items per 550$
so i go to make the trade sign as follows and as shown in the picture above

[trade]
$500
32 scaffolding:4

when i press enter 
the sign turns red and a message shows in console saying quanitites must be greater than 0
what i want is a fix to the issue if there is one
or a simple answer to why this is happening
i have read alot forum nothing can really get me an answer
i have thought that it might be as simple as the sign text limit is reaches that is why it shows that why but even so then how can i get around that issue if there is no a short way to write scaffolding in essentials like there is for example for iron_blocks you can just write iblock and the sign turns blue and functions normally

**Comment by pop4959** [comment]
Thank you for the details, but please still fill out the template with the required information. You probably deleted it when you created this issue, which makes things needlessly difficult. Go to Issues -> New Issue -> Report a bug -> Get started -> copy the template here and fill it out carefully.

**Comment by VirtualParticle** [comment]
Read the tutorial for how to use signs [here](https://wiki.mc-ess.net/wiki/Sign_Tutorial#Trade_Sign). Where you're going wrong is that the number after the colon is how much of that item (or money) you're putting into the shop. The first number is how much of the item you want or are selling per transaction. For this reason, you must put at least as much of that item after the colon as the number before the item.

In your first example your sign is charging $500 for 32 iron, but you're only putting 2 iron in the shop. A working example would be:
```
[trade]
$500
32 ibar:64
```

In this example, you're putting 64 iron in the shop, with each sale taking out 32 iron. Everything I've said applies to money as well; the amount you're putting in the shop must exceed or equal the amount you're giving away.

**Comment by omeedoski** [comment]
Dear virtual particle
See i get what you saying and i have tried that too.... But when i write 
32 ibar 2
The game automatically assumes that i have 2X 32 ibars 
And it takes 64 ibars from my inventory that is all working just fine 
But now i think this is a charachter exceeding thing
That the sign is not capable of selling some stuff ass there names are too long 
When i write iron_ingot it shows as red... But with ibars it shows as blue and it works fine

**Comment by pop4959** [comment]
Yes, some names are too long for signs, and there is no avoiding that. Use /itemdb to find a shorter name for the item stack you are trying to sell, and if there is none then you can add it to items.json and/or make an issue for it here.

Closing the issue now as I believe your question should be fully answered at this point. If not, please make a new issue *clearly* explaining the problem, and provide complete information as per the issue template.
