### ISSUE TITLE
1.14.2 God armour gets all protection enchantments removed when updated.

### ISSUE THREAD

**Issue by NotConor** [EssentialsX/Essentials#2813]
Not much else to say.
Armour with all types of protection (eg: chestplate with fire prot 4, blast prot 4, proj prot 4 and plain prot 4) gets those enchantments removed when a player removes the armour piece from their body and updates it. I'm aware that this might just be a setting that I've got wrong, but I'm not sure how to fix it. Thanks for any help you can give.

**Comment by mdcfe** [comment]
Please provide the details requested in the template.

EssentialsX doesn't alter item enchantment except for when you spawn an item in or when you run `/enchant`. Are you sure you don't have another plugin installed interfering with it?

**Comment by NotConor** [comment]
Might be another plugin, I just tested it on a server with only essentialsx and it seemed fine. Thought it was essentials at first because the items got fixed when I removed it. Sorry for wasting your time.

**Comment by mdcfe** [comment]
No worries!
