### ISSUE TITLE
More options for EssentialsProtect

### ISSUE THREAD

**Issue by ensorcell** [EssentialsX/Essentials#2815]
### Feature request

**Feature description**
More additions to the EssentialsProtect section, such as enhanced options for mob griefing (endermen picking up blocks and creeper/ghast explosions are a great baseline, but other useful things could include zombies breaking down doors, ravagers breaking leaves, villagers harvesting/planting crops, sheep eating grass)

**How the feature is useful**
The mobGriefing rule in vanilla is very general and either prevents or allows ALL types of griefing, having more specific options in Essentials would allow for more control over which behaviors are allowed

**Comment by darbyjack** [comment]
Started a W.I.P PR https://github.com/EssentialsX/Essentials/pull/2828
