### ISSUE TITLE
Essentials hat no longer puts anything in the head slot.

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#2817]
Paper dev 210 (Spigot 1.14.4)
Essentials dev 784

The command ``/hat`` no longer seems to work, nor am I able to drag blocks into the head slot with the correct permissions. It only outputs `` You must have something to wear in your hand.`` when typing ``/hat`` despite holding something you could normally have worn, like a lapis block.

**Comment by triagonal** [comment]
Likely duplicate of  #2763 - please check whether the solution in that thread fixes your issue.

**Comment by mibby** [comment]
@triagonal Thanks, that does seem to be the issue!
