### ISSUE TITLE
Vanish bug

### ISSUE THREAD

**Issue by KristianHansen94** [EssentialsX/Essentials#282]
Bug:
 I'm in vanish for players who log in after I do.

How to replicate: 
If I have been in /vanish at any point, I will get this bug. The player doesn't have to have the vanish join permission node for this to happen. I fixed this with someone by deleting their essentials and world playerdata.

This is consistent. I log in, then anyone who logs in after me won't be able to send me a message or see my name in the tab list, while others will be able to do so.

Extra:
This bug was also there with the previous versions of essentials, before the essentialsX fork.
There are no errors in the console and this happens with a complete default config or a very edited one. 

Would it be possible to fix this or maybe even have a version of essentials without the vanish feature entirely?

Thank you for taking the time to read this.

**Comment by ChanceSD** [comment]
+1 for this
If i use vanish and then unvanish, only players already on the server will see me.
Players logging in after that won't see me and it only gets fixed by unvanishing again.

**Comment by Terrobility** [comment]
:+1: This issue is very annoying as a server owner, and it's gone on for quite some time.

**Comment by vemacs** [comment]
This is a Spigot/Minecraft 1.8 issue. There's nothing we can do to fix it.

**Comment by Agazed** [comment]
Is there an open bug report on this? @vemacs

**Comment by mdcfe** [comment]
Closing in favour of #1764 as they appear to be the same bug.
