### ISSUE TITLE
customModelData in kits

### ISSUE THREAD

**Issue by HexedHero** [EssentialsX/Essentials#2829]
### Feature request

**Feature description**

Add customModelData support for kits

**How the feature is useful**

So we can add model data to our kit items

**Comment by mdcfe** [comment]
You can add arbitrary NBT tags to the end of the kit item using the appropriate vanilla format for the server version you're running. You can also add `/minecraft:give` commands with `{player}` as the player name to the kit to use the vanilla give command syntax.
