### ISSUE TITLE
JSON in .txt files

### ISSUE THREAD

**Issue by Plumeex** [EssentialsX/Essentials#283]
The various .txt files (rules, motd, custom, info...) could be a lot more interesting with the power of JSON, while remaining simple.
I suggest adding a way to integrate JSON into these files, so that their content can be sent to the players with fancy hover and click actions (just as if we were using /tellraw).

I guess it would not work in the books.txt file, though.
Thanks.

**Comment by TomLewis** [comment]
I WISH they would implement json throughout so we could have hover over and click in all text, including chat, so then we could have clickable & hover over username information.

**Comment by joshua-am** [comment]
Recently introduced this myself, and by far enjoying it. Except the issues with chatcolor breaking on next lines and the only solution I found being ChatColor.getLastColors()
But yeah, neat and fun feature to add. https://gyazo.com/04fd851a88369dbd98d10a1f7390d95a

**Comment by pop4959** [comment]
Closing in favour of the discussion of this issue in #2391.
