### ISSUE TITLE
hey i cant get prefixes working 

### ISSUE THREAD

**Issue by goonowmoo2** [EssentialsX/Essentials#2840]
### Information

Full output of `/ess version`:

**Server log:** 

**EssentialsX config** 

### Help request

**Problem**

my prefixes do not show up i did format it right and i have tryed things such as youtube
**What I have tried**

youtube and some other online sources
**Screenshots**

**Comment by kennyrkun** [comment]
Please complete the bug report template in order for us to help you with your problem.

**Comment by pop4959** [comment]
Closing due to no response.
