### ISSUE TITLE
Config Option Sell Enchanted/Lore for Base Item Price?

### ISSUE THREAD

**Issue by Epykest** [EssentialsX/Essentials#2842]
I want players to be able to /sell items that have been randomly generated by the MythicDrops plugin.

Some of these items contain enchantments and lore.

HOWEVER, obviously it would be too difficult to set a price for all of these items.

This is why I am requesting a config option to sell enchanted/lore items at BASE ITEM PRICE.

So when MythicDrops gives a wooden Socket Sword? It will only be worth a normal wooden sword.

**Comment by pop4959** [comment]
This seems similar to #2117, perhaps this can more broadly be described as being able to sell items which have been modified (either renamed, enchanted, or lore / other metadata added by plugins).

**Comment by pop4959** [comment]
Closing in favor of #2117.
