### ISSUE TITLE
Turkish localization is terrible !

### ISSUE THREAD

**Issue by unwillexist** [EssentialsX/Essentials#2844]
Turkish localization of EssentialsX is left from early 2010s, every word starts with capital letter, lots of grammer mistakes etc. I corrected them all at crowdin.com (took 7 hours) please accept my all suggestions I also messaged you guys at crowdin too.. I want to see my work at my server ASAP, so please apply my suggestions ASAP.

**Comment by darbyjack** [comment]
Hey there,

Thanks for submitting the localization fixes! We typically put that PR live right before we release the update. If you want to use it on your server, just download the file and add it into your localization files! It will go live for everyone when we do the next official update!

**Comment by unwillexist** [comment]
There is no way to download it with my corrections before your approval, when I download that file it downloads not corrected ones. I must copy and paste line by line to use it on my server which is also a work probably will take another several hours from me.

**Comment by mdcfe** [comment]
I've approved all the Turkish translations on Crowdin - we'll add them to EssentialsX as soon as we can.

**Comment by unwillexist** [comment]
Thank you very much ! You only approved translations with issues but I saw that you gave me permission to approve translations so I approved them all. Thank for permission, see you at next update !

**Comment by mdcfe** [comment]
No worries - thanks for submitting and improving the translation!
