### ISSUE TITLE
Console spamming /list command

### ISSUE THREAD

**Issue by Smokie233** [EssentialsX/Essentials#2846]
### Information

Full output of `/ess version`:
Server version: 1.14.4-R01-SNAPSHOT git Paper-225 (MC: 1.14.4)
EssentialsX version: 2.17.1.19
LuckPerms version: 4.4.1
Vault version: 1.7.2-b107
EssentialsXSpawn version: 2.17.1.19
EssentialsXChat version: 2.17.1.19

**Server log:** 
[latest.log](https://github.com/EssentialsX/Essentials/files/3802737/latest.log)

**EssentialsX config** 
[config.txt](https://github.com/EssentialsX/Essentials/files/3802758/config.txt)

### Help request

**Problem**
Server spamming /list command in the console every 30 seconds

**What I have tried**
removing essentialsx.jar and it goes away.  I install essentialsx.jar and it spams.  I tried to go through config to find the problem and nothing worked.

**Screenshots**

**Comment by pop4959** [comment]
Essentials shouldn't be doing this. Have you tried removing all of the other plugins?

**Comment by Smokie233** [comment]
Yes sir.  It's come down to this jar and only this jar.  I removed all plug-ins from server except essentialsx.jar and it spammed.  I removed the .jar and it stopped.  I have reinstalled all other plugins and left essentialsx out and it didn't spam.  I don't know what or how it is doing this.  It seems nobody else is getting this spamming.  I have a multicraft server and have reached out to them but no reply yet.

**Comment by pop4959** [comment]
The only other thing I can think of is to re-install. If it still happens with the latest files from [here](https://ci.ender.zone/job/EssentialsX/), and a fresh configuration, then it is probably caused by something else. Could likely be your host, if you don't have any other plugins installed. Beyond that, not sure. It's definitely not a known issue that anyone else is experiencing.

**Comment by Smokie233** [comment]
Re-installing doesn't do nothing and fresh config.  Host + essentialsX...that's just odd.  I can't see why a server hosting company would install something on the back-end to spam the console with a command for a certain plug-in.  If that's the case, I'm switching hosts.

**Comment by pop4959** [comment]
Well all I'm saying is that Essentials does not run a list command on its own. It could be run manually yourself, or automatically via a command block, function, another plugin, etc. I think you get the idea. You could try running a second test server on another machine to confirm that this doesn't happen usually.

**Comment by mdcfe** [comment]
Multicraft (and potentially other panels) run `/list` periodically to make sure the server hasn't locked up. If you don't want this to show up, you can use a plugin to filter your logs, but be aware hiding this message may interfere with your panel or cause unexpected server reboots.

**Comment by EmanYm** [comment]
I apologise for necroing an old post, but I have a potential solution to this for anyone searching for a solution four years later.

If your host uses MultiCraft...
On the main page of that server's control panel, scroll to the bottom and expand "Advanced Settings"
Find "Crash Detection" and set that to "Disabled"
https://gyazo.com/b19db13be1c93c2f3ca9ff748ce839ba

I you don't have that option you will need to talk to your host's support to have it enabled.

What used to post every three minutes has not been seen for an hour (and counting)

**Comment by Newspoet** [comment]
I'm having the same issue. Thanks for the potential solution. I'll try it.
