### ISSUE TITLE
/butcher kills armor stands

### ISSUE THREAD

**Issue by rybreuer** [EssentialsX/Essentials#285]
Exactly what it says on the tin. /butcher (without the -a flag) kills armor stands as if they are hostile mobs. Is this a bug or intended functionality? If intentional, could the categorization for armor stands be changed to passive mobs so it's possible to butcher hostiles without loosing items stored on armor stands?

**Comment by SupaHam** [comment]
`/butcher` is not a valid command in EssentialsX, I am assuming you are using WorldEdit, which in that case, please refer your issues to http://youtrack.sk89q.com/
