### ISSUE TITLE
Slow Economy Response

### ISSUE THREAD

**Issue by skerit** [EssentialsX/Essentials#2853]
I'm getting a lot of warnings in my log like this:

`[Essentials] Lag Notice - Slow Economy Response - Request took over 49.838ms!`

I'm not here to ask why that is, because I already know: I use Gringotts, and it stores money in actual chests as gold, so I assume accessing that chest data isn't as efficient as a simple mysql query.

Is there a way to disable this notice?

**Comment by pop4959** [comment]
There exist easter egg configuration options for this (add them manually to config.yml):

economy-lag-warning: 25
permissions-lag-warning: 25

Increase 25 (milliseconds) to something that your plugin won't trigger.
