### ISSUE TITLE
Essentials Config (BROKEN)

### ISSUE THREAD

**Issue by iTzRockGamez** [EssentialsX/Essentials#2856]
The config is broken. Every single time I configure it, it creates a new filed named 
"config.yml.broken(then some long number)" Pretty much I can not configure it at all.

**Comment by pop4959** [comment]
This can happen if you messed up the formatting of the file. It must be YML format. Generate a fresh valid config file and only change one thing at a time carefully. If it breaks you did something wrong. If you're still having trouble, come on the discord support server and someone will probably be able to point out what that might be.
