### ISSUE TITLE
Add option to log buy/sell/trade to console

### ISSUE THREAD

**Issue by vityav** [EssentialsX/Essentials#2857]
### Feature request

**Feature description**
I'd like the option to send all buy/sell/trade logs directly to the console instead of the trade.log file.

**How the feature is useful**
- This saves me from having to cross reference multiple files when tracing an issue, since most other mods output debug info to the console. 
- My console is more easily accessible than a text file on the server.
- Console output already gets written to logs which are automatically compressed, backed up, and are easy to clear out when old. The trade.log file would require custom scripts to replicate all of this.

**Comment by pop4959** [comment]
After some consideration, I think this is still a bit too niche to include. The trade log has all of the information, and you should be able to easily filter that.
