### ISSUE TITLE
empty config file

### ISSUE THREAD

**Issue by Desoru** [EssentialsX/Essentials#2859]
### Information

Full output of `/ess version`: 

This server is running Essentials 2.17.1.19

**Server log:** [latest.log](https://github.com/EssentialsX/Essentials/files/3865165/latest.log)

**EssentialsX config** 
[config.zip](https://github.com/EssentialsX/Essentials/files/3865172/config.zip)

### Help request

**Problem**
The config file is empty. Only "#to do" is inside.

**What I have tried**
searched for the newest version

**Comment by pop4959** [comment]
Download the latest version from the download portal [here](https://essentialsx.netlify.com/downloads.html). Put it in your plugins folder. It will create a config.yml file as well as various others in the plugins/Essentials/ folder.

**Comment by Desoru** [comment]
I had the newest version but I had essentials-bridge-API installed (for Bssentials plugin). I removed it and now it works fine. I have never noticed it in the log because it never sayed that it that there is a conflict.
