### ISSUE TITLE
 [Essentials] Task #343 for Essentials v2.0.1-b226 generated an exception

### ISSUE THREAD

**Issue by AdminZero** [EssentialsX/Essentials#286]
Using Spigot 1.8.8 and EssentialsX and this error just keep repeating and repeating in my console and now sure why? http://pastebin.com/FGJFeu9u

If there is something i can do to fix let me know if not please fix... thanks.

**Comment by SupaHam** [comment]
Please provide the EssentialsX version you are using as well as a list of plugins.

**Comment by AdminZero** [comment]
Here is a list of more of the same errors since you have not fixed it yet maybe they give you more information... 

Recent Errors: http://pastebin.com/uVMJYK8q
Plugins Report: http://timings.aikar.co/?url=13765670

If you can't read the title and figure out the Essentials version i can't help you there sorry.

Let me know if you need any further information.
