### ISSUE TITLE
EssentialsX not loading problem

### ISSUE THREAD

**Issue by XPLevels** [EssentialsX/Essentials#2860]
### Information

Full output of `/ess version`:
`19.11 20:53:09 [Server] INFO CONSOLE issued server command: /ess version
19.11 20:53:09 [Server] INFO Server version: 1.8.8-R0.2-SNAPSHOT git-TacoSpigot-04511af6 (MC: 1.8.8)
19.11 20:53:09 [Server] INFO EssentialsX version: 2.17.1.19
19.11 20:53:09 [Server] INFO LuckPerms version: 4.4.1
19.11 20:53:09 [Server] INFO PlaceholderAPI version: 2.9.2
19.11 20:53:09 [Server] INFO Vault version: 1.7.2-b107
19.11 20:53:09 [Server] INFO You are running an unsupported server version!`

**Server log:** 
https://gist.github.com/XPLevels/70da8d4861994093c93656b0c8793efb

**EssentialsX config** 
https://gist.github.com/XPLevels/1afad6704b316abe4b168164177d8e1a

### Help request

**Problem**

After loading specifically more than 48 plugins *INCLUDING ESSENTIALSX* essentials X doesn't load.

**What I have tried**

- I have tried putting Spigot 1.8.8 Jar rather than Stellar.Jar
- I have tried putting EssentialsX.jar alone with not other essentials addons/plugins.
- I have tried resetting all configs.
- I have tried removing plugins 1 by 1 while maintaining 50 plugins to see if EssentialsX loaded and it didn't.

**Comment by pop4959** [comment]
Can you please update the issue to show logs and information using either Spigot or Paper. Other forks and modified versions are not officially supported and we will not be able to look into it any further. Also provide any other information that may be relevant to reproducing your issue on our side. This may include your plugin list, links to the source of those plugins, and downloads for those plugins.

**Comment by pop4959** [comment]
Closing due to lack of response.
