### ISSUE TITLE
async chunk problem

### ISSUE THREAD

**Issue by PhanaticD** [EssentialsX/Essentials#2861]
this loads the chunk so the whole paperlib async teleport is completely negated https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/Teleport.java

"LocationUtil.isBlockUnsafeForUser"

**Comment by montlikadani** [comment]
~~Firstly, complete the whole template before posting issues.~~

**Comment by PhanaticD** [comment]
nah

**Comment by pop4959** [comment]
I'm assuming you mean the calls to getBlockX/Y/Z are causing this problem. Can probably fix using getChunkAtAsync in that case.

**Comment by PhanaticD** [comment]
yea, I managed to fix it by doing that, but the whole throws exceptions thing gets messy and Im not sure what to do about it properly

**Comment by CircusCow** [comment]
Literally the only lag spikes I get on my network are from essentials TP. Please fix!

**Comment by gp-Airee** [comment]
Bump. This is extremely important.

**Comment by pop4959** [comment]
@gp-Airee Just so you know, "bumping" isn't really a thing on GitHub. This isn't a forum.

**Comment by gp-Airee** [comment]
Eh, I meant it more so in that people who watch it are notified. I
understand the list of issues aren't ordered by recent reply.

**Comment by JRoy** [comment]
Should be fixed by #3102

If anyone here could test the PR and report any bugs you find!

**Comment by mdcfe** [comment]
EssentialsX now has async teleporting in the latest dev builds! You can download them from the [EssentialsX website](https://essentialsx.net/downloads.html).
