### ISSUE TITLE
 Add customizable Impact on all players. Stars chatting.

### ISSUE THREAD

**Issue by AndriyYaremenkoDev** [EssentialsX/Essentials#2865]
Screen - https://drive.google.com/file/d/1VHyoAE46OemEDVoZzPhKygQGIDfVwTW_/view
Sorry if the speech is not clear, I use a translator.

I ran into this problem when I was designing the server and chat. I noticed that in an ordinary player with any team (example: /m [TAB] *, players) these **stars** are visible **(see screen)**.

**Issues:**

1. Make switchable the ability to act on all players **[example: action-on-all-players: true-false]** or make this function permissions. The main thing is that ordinary players do not see the stars)

2. These stars appear even for ordinary players with teams that can not act on all players **[/m *, /t *, tell *, and so on]** And these commands do not work. _(Example on the screen)_

3. This will make the chat cleaner, and add the flexibility to configure some commands. Also
 the developers-perfectionists will be happy)

_I hope you are listening to this sentence, thanks for reading!)_

**Comment by mdcfe** [comment]
I don't even know what this was asking for.

**Comment by pop4959** [comment]
I don't think anyone does. Pretty sure this is lost in translation.
