### ISSUE TITLE
Time command breaks vanilla method world.getWorldTime()

### ISSUE THREAD

**Issue by TheDarkDnKTv** [EssentialsX/Essentials#2866]
When essentails installed on server, and running command /time set 0 world time not resets to 0, just added 24000 ticks. After this vanilla method world.getWorldTime return really long value like world.getTotalWorld time. I writing mod under my client and have installed craftbukkit+forge build, after i find out this bug. After some debug i am sure, what problem in your plugin.

MC version: 1.12.2
CraftbukkitAPI version: 1.12.2-R0.1-SNAPSHOT
ess version output:
```Server version: 1.12.2-R0.1-SNAPSHOT git-CatServerAsync-1.12.2-f8c3924 (MC: 1.12.2)
EssentialsX version: 2.17.1.0
PermissionsEx version: 1.23.4
EssentialsXSpawn version: 2.17.1.0
Vault is not installed. Chat and permissions may not work.
You are running unsupported plugins!

**Comment by pop4959** [comment]
Can you explain more why this is a breaking feature? Vanilla also has a time command, which does much the same as Essentials. This sounds like it is much more likely a problem with your mod.

**Comment by TheDarkDnKTv** [comment]
In minecraft we have method ```world.getWorldTime()``` applies to world variable. In vanilla/forge it is return long value [0-24000). When world time gets 24000 this variable automaticly resets to 0. But when essentials installed on server, this variable do not resets to 0 by command or just when worldtime is 24000. It is increasing unlimited. It is bug, because we have also method ```world.getTotalWorldTime()``` which return overall time of world. But somehow with essentials this two methods works same. I checked it on my server build with all mods & plugins installed, when removing essetials - bug disappears.

**Comment by TheDarkDnKTv** [comment]
I do not know how, but essentials somehow changing behaviour of minecraft's method. Please check it.

**Comment by mdcfe** [comment]
This discrepancy lies with your server software. Bukkit and MCP/Forge expose different time-related methods to plugins and mods respectively, and your server software doesn't appear to implement the Bukkit methods in a way that works properly with MCP/Forge mods. Please report this to the developer of your server software. EssentialsX does not and will not support hybrid servers.
