### ISSUE TITLE
createkit "item is not a potion"

### ISSUE THREAD

**Issue by PhanaticD** [EssentialsX/Essentials#2867]
on a 1.13 server i put some splash potions in my inventory and did /createkit and it says "item is not a potion" and was unable to make the kit

**Comment by pop4959** [comment]
What version of essentials and which potions?

**Comment by PhanaticD** [comment]
was latest off build server and idk I have a few types

**Comment by DebuffPvP** [comment]
phanaticD owner of phanatic mc you it's not just that version i don't think they have it set to detect the internal id's of the pots or just doesn't understand if they are splash pots or is it just doing it for certain splash ones?

**Comment by triagonal** [comment]
Has existed for a while now. The error occurs when attempting to use splash or lingering potions when creating a kit. Here is the stacktrace for any interested parties:
https://gist.github.com/triagonal/c1650c1a7ebe52c362d9aac7e68f0a4d

Confirmed and reproduced on:
```
[23:53:00 INFO]: Server version: 1.14.4-R0.1-SNAPSHOT git-Paper-226 (MC: 1.14.4)
[23:53:00 INFO]: EssentialsX version: 2.17.1.37
[23:53:00 INFO]: Vault is not installed. Chat and permissions may not work.
```

edit: Duplicates #1119 - issue has existed since 2017.

**Comment by mdcfe** [comment]
`org.bukkit.potion.Potion` isn't designed for 1.9 and above, and [refuses to get the potion meta of anything that isn't a `minecraft:potion`](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/potion/Potion.java#356-361). We should probably look up and find an appropriate potion in the item database, at least for 1.13+.

**Comment by Cryptite** [comment]
FWIW Still doesn't work on latest...

**Comment by JRoy** [comment]
yeah this is pending #3248

**Comment by Chew** [comment]
No need to pointlessly bump issues that are still issues (especially since there's a linked PR). We know. Only comment if it's no longer an issue.

**Comment by lambros-stef** [comment]
So, I was trying to make an OP Kit and when I types the /createkit command its said: Error: item is not a potion and in that kit, I didn't have any potions. Also, I had enabled unsafe enchantments because the sword had fortune and it still said that. Thank you.

**Comment by illumeleet** [comment]
confirmed on 2.19.0-dev+221-1556b91
![image](https://user-images.githubusercontent.com/51333325/126653647-7283bbb5-6854-44a9-b754-20192b6c1b1b.png)
issue still occurs when creating kit with tinted arrows / splash potions / lingering potions, ordinary potions do work tho

UPD: just noticed the "use-nbt-serialization-in-createkit:" option. With it turned on, everything works like a charm.
