### ISSUE TITLE
Java Assertion Error: TRAP

### ISSUE THREAD

**Issue by RFSMassacre** [EssentialsX/Essentials#2878]
### Information

**Full output of `/ess version`**:

```
<!-- Run the command in your console, and copy and paste the whole output here -->
> [19:28:04] [Server thread/INFO]: Server version: 1.15-R0.1-SNAPSHOT git-Spigot-530f668-4633e6c (MC: 1.15)
> [19:28:04] [Server thread/INFO]: EssentialsX version: 2.17.1.25
> [19:28:04] [Server thread/INFO]: EssentialsXSpawn version: 2.17.1.25
> [19:28:04] [Server thread/INFO]: Vault is not installed. Chat and permissions may not work.
```

**Server log**: 

https://gist.github.com/RFSMassacre/91c0f566d691d6b97b64c9a32742159b 

**EssentialsX config**:

https://gist.github.com/RFSMassacre/91c0f566d691d6b97b64c9a32742159b 

### Details

**Description**  

If a creeper explodes on you while you are holding a red mushroom, the server crashes with a Java assertion error. This only happens when you are in the protected spawn zone of the world.

**Steps to reproduce**  

1.) Stand in the protected spawn zone.
2.) Hold a red mushroom in your main hand.
3.) Spawn a creeper via spawn egg next to you or find one naturally.
4.) Hit it and let it explode on you while holding the item.
5.) The server crashes with an assertion error on the console.

**Expected behavior**  

The creeper is supposed to kill you and drop the items normally without causing any errors.

**Screenshots**  

I decided to record the video of the steps in action. Hopefully, it's helpful.
https://youtu.be/Va7DRIx8mE4

**Comment by pop4959** [comment]
Essentials is not responsible for this error. This is caused by your server software, according to the error messages.
