### ISSUE TITLE
Any future plans to support groupmanager?

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#288]
Groupmanager has stood the test of time being the most bullet proof Permissions system to date, It frustrates me there are so many kids out their praising PEX when its so badly made, causing more people to use it, and the circle continues. GroupManager was made to stand solo and not worry about changing version of Bukkit/Spigot. It does however lack a few needed features in today's server world, MySQL & Bungeecord. PEX/Zpermissions are not options as they are so poorly made and designed. 
I would love this team to take hold of adding enhancements to GroupManager, the core is rock solid, it just need some expansion.

**Comment by Kakifrucht** [comment]
I agree with you, however last time I asked they said that they didn't want to support it.

**Comment by TomLewis** [comment]
@Kakifrucht It The core dousnt even need to be touched, it just needs expanding to have a switch to use MySQL and an additional bungee support, the use of groupmanager would dominate if it had these features. Im setting up a new network and I would still prefer to rsync across servers with groupmanager than use any of the god awful childish PEX alternatives.

**Comment by vemacs** [comment]
I don't know why you think zPermissions is poorly made and designed... GM performs terribly compared to it.

Either way, I don't think there's enough interest (or large networks running GM) for maintenance to be worth the effort.

**Comment by drtshock** [comment]
plz no
