### ISSUE TITLE
dev builds warp issue.

### ISSUE THREAD

**Issue by FallingCactus** [EssentialsX/Essentials#2880]
Full output of /ess version:

12.12 05:32:09 Server version: 1.15-R0.1-SNAPSHOT git-Spigot-f39a89e-73698cf (MC: 1.15)
12.12 05:32:09 EssentialsX version: 2.17.1.26
12.12 05:32:09 PlaceholderAPI version: 2.10.4
12.12 05:32:09 LuckPerms version: 4.4.1
12.12 05:32:09 Vault version: 1.7.2-b107
12.12 05:32:09 Citizens version: 2.0.26-SNAPSHOT (build 1785)
12.12 05:32:09 EssentialsXChat version: 2.17.1.26
12.12 05:32:09 EssentialsXSpawn version: 2.17.1.26

EssentialsX config: https://hastebin.com/qumayaxoya.coffeescript

Details
Description
Upon testing the dev builds in 1.15 I have found that warps to Nether worlds and End worlds do not work. my normal worlds warps seem to work just fine, I have tried to remake the warps in nether and end worlds but after putting in the warp command nothing happens, no outpout to console at all.

Steps to reproduce
1 - Set a warp in end or nether worlds.
2 - Try to warp to set warps. 

Expected behavior
Warping to these warps just like they were in 1.1.4.4

EDIT: Any new warp is no longer working. I only have 1 warp that works from 1.14.4 others from 1.14.4 fail to teleport. any new warp in any world sets but does not teleport.

**Comment by pop4959** [comment]
Unable to reproduce the issue on the same versions. Essentials warps seem to be working fine, on a clean server with no other plugins.
