### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#2881]
[18:29:33] [Server thread/ERROR]: Error occurred while enabling Essentials v2.17.1.0 (Is it up to date?)
--
241 | java.lang.NoClassDefFoundError: com/google/gson/JsonElement
242 | at com.earth2me.essentials.Essentials.onEnable(Essentials.java:277) ~[?:?]
243 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[minecraft_server.jar:git-Spigot-550ebac-7019900]
244 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [minecraft_server.jar:git-Spigot-550ebac-7019900]
245 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [minecraft_server.jar:git-Spigot-550ebac-7019900]
246 | at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [minecraft_server.jar:git-Spigot-550ebac-7019900]
247 | at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [minecraft_server.jar:git-Spigot-550ebac-7019900]
248 | at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [minecraft_server.jar:git-Spigot-550ebac-7019900]
249 | at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [minecraft_server.jar:git-Spigot-550ebac-7019900]
250 | at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [minecraft_server.jar:git-Spigot-550ebac-7019900]
251 | at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [minecraft_server.jar:git-Spigot-550ebac-7019900]
252 | at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [minecraft_server.jar:git-Spigot-550ebac-7019900]
253 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
254 | Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonElement
255 | at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_222]
256 | at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[minecraft_server.jar:git-Spigot-550ebac-7019900]
257 | at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[minecraft_server.jar:git-Spigot-550ebac-7019900]
258 | at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_222]
259 | at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
260 | ... 12 more
261 | [18:29:33] [Server thread/INFO]: [Vault][Economy] Essentials Economy hooked.
262 | [18:29:33] [Server thread/INFO]: [EssentialsProtect] Enabling EssentialsProtect v2.17.1.0
263 | [18:29:33] [Server thread/ERROR]: [EssentialsProtect] Essentials not installed or failed to load. Essentials Protect is in emergency mode now.

**Comment by pop4959** [comment]
Please fill out the issue template template entirely.
