### ISSUE TITLE
Help! i have a 1.8 server

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#2882]
16.12 21:01:47 [Server] INFO [21:01:47 INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
16.12 21:01:47 [Server] INFO [21:01:47 ERROR]: java.lang.NoClassDefFoundError: com/google/gson/JsonElement
16.12 21:01:47 [Server] INFO [21:01:47 WARN]: java.lang.NoClassDefFoundError: com/google/gson/JsonElement
16.12 21:01:47 [Server] INFO [21:01:47 WARN]: 	at com.earth2me.essentials.Essentials.onEnable(Essentials.java:277)
16.12 21:01:47 [Server] INFO [21:01:47 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
16.12 21:01:47 [Server] INFO [21:01:47 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
16.12 21:01:47 [Server] INFO [21:01:47 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
16.12 21:01:47 [Server] INFO [21:01:47 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356)
16.12 21:01:47 [Server] INFO [21:01:47 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316)
16.12 21:01:47 [Server] INFO [21:01:47 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402)

**Comment by TheMolkaPL** [comment]
1.8 isn't supported.

**Comment by pop4959** [comment]
Duplicate of #2881.

Lowest supported version is 1.8.8. Also, please DO NOT create duplicate issues. If you felt your other one was closed by mistake, please say so (and give us a reason to re-open it) instead of making another one. Thank you.
