### ISSUE TITLE
Possible Memory Leak (Critical)

### ISSUE THREAD

**Issue by SkyLicks** [EssentialsX/Essentials#2883]
### Information

**Full output of `/ess version`**:
[22:00:04 INFO]: Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
[22:00:04 INFO]: EssentialsX version: 2.17.1.0
[22:00:04 INFO]: LuckPerms version: 4.4.1
[22:00:04 INFO]: Vault version: 1.5.6-b49

**Server log**:
Sorry, I can not provide as the logs contain information which we rather not make public. However, it is not needed for this report.

**EssentialsX config**: https://gist.github.com/SkyLicks/97b3ce5d81abd8eb51f962571a232f5e

### Details

**Description**  
There is a memory leak involving essentials. Refer to the below screenshot for the heap dump info.

**Steps to reproduce**  
Not needed / Unknown

**Expected behavior**  
There should not be a memory leak.

**Screenshots**  
<img width="1725" alt="download" src="https://user-images.githubusercontent.com/34877092/70961462-dd911700-204f-11ea-9699-55dcf1b4027b.png">

**Comment by pop4959** [comment]
Indeed the server log should not be needed here, however keep in mind that it does not generally include player chat or other personally identifiable or personal information. Just the startup log and any errors.

Moving on... can you give more information about why you believe there is a memory leak? I see in your screenshot that it would appear Essentials may be using a lot of RAM, but that doesn't necessarily indicate a leak. Have you observed the memory usage steadily increasing from Essentials? Did your server crash after some time (and how long)? More background and details are necessary.

Steps to reproduce is required. You should test if this occurs on a fresh server with nothing else installed but Essentials on the latest server software for your version. See if the problem persists. If it does, please tell us exactly what you are doing to set up the server and how you are measuring and identifying leaks. If you do this, someone can then confirm if this is an issue and fix it if necessary.

**Comment by caojohnny** [comment]
Attach the hprof file please

**Comment by pop4959** [comment]
Closing this since there has been no response. If this is a real problem, it would probably be quite evident on most servers (especially a leak involving several GB).

If the author of this (or someone else in the future) believes there is a leak somewhere, please make a new issue, and either explain exactly what the leak is, or at least give enough conclusive evidence to indicate that there may be one, and in what situation it is caused.
