### ISSUE TITLE
I can't get my usernames to be prefixed in group formats ...

### ISSUE THREAD

**Issue by TheLegendGinger** [EssentialsX/Essentials#2884]
For example i have chat:

  # If EssentialsChat is installed, this will define how far a player's voice travels, in blocks.  Set to 0 to make all chat global.
  # Note that users with the "essentials.chat.spy" permission will hear everything, regardless of this setting.
  # Users with essentials.chat.shout can override this by prefixing text with an exclamation mark (!)
  # Users with essentials.chat.question can override this by prefixing text with a question mark (?)
  # You can add command costs for shout/question by adding chat-shout and chat-question to the command costs section."
  radius: 0

  # Chat formatting can be done in two ways, you can either define a standard format for all chat.
  # Or you can give a group specific chat format, to give some extra variation.
  # For more information of chat formatting, check out the wiki: http://wiki.ess3.net/wiki/Chat_Formatting
  # For EssentialsX changes, take a look at the EssentialsX wiki: https://github.com/EssentialsX/Essentials/wiki

  #format: 
  #format: '&7[{GROUP}]&r {DISPLAYNAME}&7:&r {MESSAGE}'
  #format: '&7{PREFIX}&r {DISPLAYNAME}&r &7{SUFFIX}&r: {MESSAGE}'

  group-formats:
    Bubbles: '&l&b[Bubbles]&r {DISPLAYNAME}&7:&r {MESSAGE}'
    

But it always comes out as (username): (words in chat) With out the group formats or anything ... help please

**Comment by pop4959** [comment]
Make sure you have the basic requirements for chat to work (Server such as Spigot or Paper, Permissions plugin such as LuckPerms, Essentials, EssentialsChat, and Vault).

Try asking on the [Discord server](https://discord.gg/PHpuzZS) in the EssentialsX channels. You're more likely to get quality help with usage there, from other server owners. It's also live chat, making it much quicker to debug what you have set up wrong. Making an issue here on GitHub is generally only useful if you have something along the lines of a bug or feature request.
