### ISSUE TITLE
Command Cooldown Issue

### ISSUE THREAD

**Issue by DebuffPvP** [EssentialsX/Essentials#2885]
Full output of /ess version:
[22:00:04 INFO]: Server version: 1.8.8 TacoSpigot
[22:00:04 INFO]: EssentialsX version: 2.17.1
[22:00:04 INFO]: MineagePermissions: 1.0.0
[22:00:04 INFO]: Vault version: 1.7.2

command-cooldowns:
  feed: 60
  fix: 300
  fixall: 8000

When i do /fix and /fixall in game the /fixall uses the fix cooldown instead and not the fixall cooldown i've tried all the possible ways of writing the fixall cooldown am i doing something wrong?

**Comment by caojohnny** [comment]
`/fixall` isn't a command or it is aliased to `/fix all`, which is probably why it uses the `/fix` cooldown
