### ISSUE TITLE
Give blocks an enchantment in kits file

### ISSUE THREAD

**Issue by joeridukker** [EssentialsX/Essentials#2886]
I have a kit spawner in the kits file:
  spawner:
    delay: 1209600
    items:
    - spawner 1 name:&fKit_spawner lore:&7Right_click_to_receive mending:1
When /kit spawner, unlike all my other kits this gives an error in chat. BUT when I get rid of the enchantment it works. I think this is the issue: You cannot give an item an enchantment if its not supposed to be able to have that enchantment, like blocks cant have mending on it. Though this worked in 1.14.

I use 2.17.1.26 essentialsx on a paper 1.15 server

**Comment by caojohnny** [comment]
Do you have unsafe enchantments enabled?

**Comment by joeridukker** [comment]
this worked thax

Op wo 18 dec. 2019 om 21:18 schreef Johnny Cao <notifications@github.com>:

**Comment by caojohnny** [comment]
Remember to follow the [issue template](https://github.com/EssentialsX/Essentials/issues/new?template=help.md) next time. Having a full config would have meant this question could be answered with certainty sooner.
