### ISSUE TITLE
/seen

### ISSUE THREAD

**Issue by mickare** [EssentialsX/Essentials#289]
Hello, it's me again!

You missed some essential commits to fix the broken seen command.
It still is broken!

PS: I did not format, so I would appreciate if someone could auto format it. ^^

https://github.com/drtshock/Essentials/pull/213#issuecomment-160463458

**Comment by vemacs** [comment]
If you could make it pass the unit tests, we can reconsider. I didn't manage to do it.

**Comment by vemacs** [comment]
Hopefully the mojang fallback and shallow copy of the UUID map will resolve this.
