### ISSUE TITLE
Inventory was full , placing kit on floor

### ISSUE THREAD

**Issue by samuelparfitt24** [EssentialsX/Essentials#2894]
i am using 2.0.1-b488
when a player does /kit or right clicks a kit sign, if there isnt enough space in their inventory it goes on the floor.
item drops are denied in worldguard
and in the essentials config: drop items if full is false

**Comment by pop4959** [comment]
You ignored the issue template, and you also are using a version several years out of date.

Please update, and if you are still having the problem on the *latest* version of the plugin, please fill out the issue template in its entirety, or we will not be able to help you.
