### ISSUE TITLE
getPrefix/Suffix assume players always have a primary group

### ISSUE THREAD

**Issue by zml2008** [EssentialsX/Essentials#2901]
[EssX line in question](https://github.com/EssentialsX/Essentials/blob/8a04c1e232216b851fc28ed518513675ad4126bb/Essentials/src/com/earth2me/essentials/perm/impl/AbstractVaultHandler.java#L50)

So Essentials' permissions provider acts under the assumption that all players are always in at least one group. I'd guess this hasn't come up much because most permissions plugins implement default data as a group -- or at least in their default settings actually have every player in a default group. 

When someone comes along with a setup where their player is not in a group (as they might when starting with a dev build of PEX2), the EssX assumption results in errors like https://pastebin.com/MYEpYXM9

VaultAPI's specification is unclear on whether getPrimaryGroup is actually allowed to return null, but giving a null result for a user with no data makes the most sense to me. I also don't see what sort of response requesting with a null group name would give -- so I'd like to see EssX only querying for a prefix/suffix if a player's primary group is not null.

-----

As a side note, PEX doesn't need essentials emulating wildcard permissions and inheritance -- it shouldn't cause any problems, but does do more work than is necessary. at some point it might be useful to override some of the check methods in EssX's PEX resolver to not do that.

**Comment by pop4959** [comment]
So effectively what you're suggesting is for getPrefix/getSuffix to return null if playerGroup == null?

I may be misunderstanding something, but is there any particular reason not to just have a default group, or a "no group" dummy group (returning an empty name/prefix/suffix) in PEX2? If most other permission plugins already do that it might lead to better compatibility with other existing plugins.

**Comment by zml2008** [comment]
Not exactly -- right now your vault permissions resolver only checks for a primary group if the user's prefix is null -- really the issue would be resolved if Essentials checked that the primary group was non-null, or didn't have its fallback system in place for PEX.

PEX doesn't need a default group -- and in fact there are entirely valid configurations in PEX1 that would have no default group either. This issue could have potentially come up earlier, especially since the Vault implementation for PEX 1 (at https://github.com/MilkBowl/Vault/blob/master/src/net/milkbowl/vault/permission/plugins/Permission_PermissionsEx.java#L275) explicitly takes into account returning a null primary group. The only change is in what PEX2's default configuration is, since PEX's ways of defining defaults are not generally exposed as groups.

I don't see why PEX should return falsified information just to make broken plugins happy either, especially when the fix is so easy.

**Comment by mdcfe** [comment]
Thanks for spotting this - it should no longer be an issue in the latest dev builds.
