### ISSUE TITLE
New to MC server management. I could use some help

### ISSUE THREAD

**Issue by SirMichael87** [EssentialsX/Essentials#2905]
### Information

Server version: 1.14.4-RO.1-SNAPSHOT git-Paper-226 (MC:1.14.4)
EssentialsX version: 2.17.1.0
Vault version:1.7.2-b107
EssentialsXProtect version 2.17.1.0
EssentialsXGeoIP version: 2.17.1.0
EssentialsXChat version 2.17.1.0
EssentialsXSpawn version: 2.17.1.0
EssentialsXXMPP version: 2.17.1.

<script src="https://gist.github.com/SirMichael87/1cafd2c3f5213f88cbfa07542920c2e8.js"></script>

<script src="https://gist.github.com/SirMichael87/8efaf65724e6d8c342854987dddeca62.js"></script>

### Help request

**Problem**
I have a plan to only add certain permissions for members and admin. /w and /msg are not working for members. I also want members to be able to /pay /sell and /balance.
I have tried to add permissions plugins, but i don't know what I am doing. please help

**What I have tried**

**Screenshots**

**Comment by Zegameus** [comment]
You could use a permissions manager like PermissionsEx or Permissions Manager.
Try to do that.
:)

**Comment by SirMichael87** [comment]
To be honest someone might have to walk me through the permissions apps because I can't make sense of it.

**Comment by triagonal** [comment]
We endorse using LuckPerms as your permissions manager. You should work through this page https://github.com/lucko/LuckPerms/wiki/Usage to get your installation set up.

If you have any more questions regarding permissions, I would advise joining the LuckPerms discord server https://discordapp.com/invite/luckperms as there are many people there who would be willing to assist you in getting your permissions setup up and running.

Good luck! :)

**Comment by pop4959** [comment]
As mentioned above, ***please*** use LuckPerms. Some older permission plugins such as PermissionsEx are no longer supported and you will have problems if you try to use them in 2019 (almost 2020).

For live help with Essentials, I recommend visiting the MOSS [Discord server](https://discord.gg/PHpuzZS). You should be able to get your questions answered here more quickly by other server owners, as well as helpers.
