### ISSUE TITLE
invalid plugins.

### ISSUE THREAD

**Issue by SirMichael87** [EssentialsX/Essentials#2906]
Full output of `/ess version`:

Server Version: 1.14.4-R0.1-SNAPSHOT git-Paper-226 (MC:1.14.4)
Essentialsx version: 2.17.1.0
LuckPerms version: 5.0.39
Vault Version 1.7.2-b107
EssentialsXChat version: 2.17.1.0
EssentialsXSpawn version: 2.17.1.0

**Server log:** https://gist.github.com/SirMichael87/d28dc9a94f2868671899917a3bc230c3

**EssentialsX config** 
https://gist.github.com/SirMichael87/49f6144665b4c52a0f980495e2eaf5c8

### Help request

**Problem**
Well I am having trouble adding permissions for members using luck perms. The guys at the LuckPerms forums pointed out that my plugins.yml are invailid. I have tried to reinstall them in the plugins server and I appear to have the same result. what am I doing wrong?

**What I have tried**
I stopped the server. Deleted the files. I then put the jars back in the plugin folder.

**Screenshots**

**Comment by pop4959** [comment]
You're using an old version, and possible using the zip instead of the jars. Get rid of the ones you have and download the latest version from <https://essentialsx.netlify.com/downloads.html>.

**Comment by SirMichael87** [comment]
> You're using an old version, and possible using the zip instead of the jars. Get rid of the ones you have and download the latest version from https://essentialsx.netlify.com/downloads.html.

i am definitely using the Jars.. i installed the new versions and it's saying in the logs that they are the older versions still...

**Comment by SirMichael87** [comment]
![image](https://user-images.githubusercontent.com/59315833/71550753-8ec77380-29a5-11ea-93e4-7722f6810d2c.png)

**Comment by pop4959** [comment]
Looks correct as far as I can tell. Maybe you have them in the wrong folder (they need to be in the plugins folder). This would explain it loading the wrong version.

If you still can't figure it out, I recommend asking your server hosting provider for help properly installing the plugin.

**Comment by triagonal** [comment]
The plugin files you're seeing causing the error are "dot underbar" files - notice the `._` prepended before their filenames. They are junk files, don't contain any useful information, and are usually remnants of whichever system built the jar files.

Normally these files are hidden from view, especially on hosting providers. You'll need to find a way to reveal the hidden files and delete the offending jar files. This could be done with an FTP client like FileZilla if you have FTP credentials. Otherwise, contact your hosting provider like pop advised above.

**Comment by pop4959** [comment]
Didn't even notice that to be honest. Good catch triagonal! Now ***that*** would probably be why it is loading the wrong version even when you put in the new one.
