### ISSUE TITLE
Suggestion: Changing /say format for Console

### ISSUE THREAD

**Issue by LukeFlynn** [EssentialsX/Essentials#291]
Until recently, I had been a user of CommandBook for nearly 4 years.. I switched to EssentialsX to reduce the amount of plugins needed on my server (CommandBook was missing some features I needed, and it looks like development is winding down on that project anyways). One thing I miss (call me nitpicking) is the ability to change the Console's /say format.. 

For example:
I could change "[Server] Message" to "Console: Message" with a color.

I'm aware there are various plugins that can do this, but most of them don't work correctly.

I was hoping you might consider adding this feature to EssentialsX? 

Thanks! :)

**Comment by drtshock** [comment]
/say is a bukkit command. Perhaps you should look at /bcast which is an essentials command of which you can change the format.

**Comment by LukeFlynn** [comment]
Sounds like a plan. Just thought it might be a bit nice to have the /say functionality too.
