### ISSUE TITLE
Don't alert when not really used lava bucket

### ISSUE THREAD

**Issue by TheNety** [EssentialsX/Essentials#2915]
### Feature request

**Feature description**

In Essentials Anti-Build, don't alert on "used LAVA_BUCKET" when it's been "used" in residence, where the player has no permission to use it

**How the feature is useful**

It won't spam the chat when player try to use lava bucket in residence.

**Comment by pop4959** [comment]
What do you mean by "us[ing] in residence"? I would appreciate if you could explain further.

**Comment by TheNety** [comment]
I mean, now when player tries to place lava on the ground AND he's in residence where he has no permissions to place it SO the lava doesn't place on the ground but it still notifies like he placed the lava.

**Comment by TheNety** [comment]
Also I'm talking about residences by this plugin https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-15.11480/

**Comment by pop4959** [comment]
We can't fix problems with premium plugins. Also, technically this isn't a bug, since it is indeed alerting the player when they use the lava (which is intended behaviour). Sounds like this is a minor inconvenience at worst. You can always turn it off if this is not what you wanted.

**Comment by TheNety** [comment]
In the description on the spigot page I sent there is "you are welcome to download the same versions for free here" -> https://zrips.net/Residence/

**Comment by pop4959** [comment]
Ah OK. Moreover the problem you seem to have is you don't want "use" to happen when something is placed, but there is a specific "place" action which also has it's own alert. If something is blocked from placement, that doesn't mean you didn't use the item. Hope that makes sense. The best fix for this is to try seeing if alert on placement works better for you, or simply remove the message.
