### ISSUE TITLE
Change showkit output to GUI?

### ISSUE THREAD

**Issue by Aberzhulan** [EssentialsX/Essentials#292]
Hello,
I really like this Essentials, but I have one request if possible.
The /showkit command outputs what's in the kit, would it be possible to make it show what is in the kit as if it was in a chest. I.e., a gui?
There's a plugin called Kitspreview that does that and I'd like to get rid of the extra kit plugins I have (like Kitspreview and kitadder) since EssentialsX handles that.

Thanks!

**Comment by drtshock** [comment]
The reason I didn't do this is because there always seems to be an issue with some server having lag or something that allows players to pull things out of GUIs.

**Comment by pop4959** [comment]
It's been 5 years, I think there are other plugins that add GUI features for Essentials already. It doesn't support it itself, however adding GUI would probably be something that would need to be a plugin-wide change, as adding it as an option to one specific command and not adding it to others would be silly (people would complain, and it would be a mess to maintain). This probably deserves its own discussion thread if anyone wants to consider this more seriously. For now, this is not something that Essentials supports currently or in the foreseeable future.

**Comment by Bosar18** [comment]
So we still dont have this closing this fixed nothing
