### ISSUE TITLE
Keep Inventory Problem

### ISSUE THREAD

**Issue by TrapToes** [EssentialsX/Essentials#2920]
### Help request

**Problem**
Can't Disable Keep Inventory if I have OP

**What I have tried**
I've tried to disable it with every command possible

**Comment by triagonal** [comment]
You need to negate `essentials.keepinv` in your permissions plugin to stop Essentials' keep inventory function.

**Comment by TrapToes** [comment]
Imma be honest I don't have any clue how to do that

**Comment by triagonal** [comment]
Well, first you need to get a permissions plugin. We recommend using [LuckPerms](https://luckperms.net/). After that, you should follow the [Usage and Getting Started](https://github.com/lucko/LuckPerms/wiki/Usage) guide on the LuckPerms wiki. After setting up the plugin, you can then run `/lp (user or group here) permission set essentials.keepinv false`

**Comment by TrapToes** [comment]
im using apexminecrafthosting. Is there any plugins on their list that can do what you suggest?

**Comment by triagonal** [comment]
I'm not familiar with Apex. You may be able to ask their support for assistance in setting up a permissions plugin. When you eventually do get a permissions plugin up and running, negating `essentials.keepinv` should solve your issue.
