### ISSUE TITLE
Can't get the <> around name to go away.

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#2923]
### Information

Full output of `/ess version`:

[00:23:03 INFO]: Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
[00:23:03 INFO]: EssentialsX version: 2.17.1.0
[00:23:03 INFO]: LuckPerms version: 5.0.39
[00:23:03 INFO]: Vault version: 1.7.2-b107
[00:23:03 INFO]: EssentialsXGeoIP version: 2.17.1.0
[00:23:03 INFO]: EssentialsXChat version: 2.17.1.0
[00:23:03 INFO]: EssentialsXSpawn version: 2.17.1.0

**Server log:** https://gist.github.com/ilavywavy/cb6696283af1b141ded7ca3450f4e8df

**EssentialsX config** https://gist.github.com/ilavywavy/90b7f34ad393f42d3967b24c6f8edfcf

### Help request

**Problem**
I removed the <> out of the "format: '<{DISPLAYNAME}> {MESSAGE}'" and the <> still show up around my name in game

**What I have tried**
Reinstalling everything to make sure it was all the latest update

**Screenshots**
![image](https://user-images.githubusercontent.com/59464382/71708565-49011580-2dc0-11ea-99f6-298b3c167560.png)

**Comment by pop4959** [comment]
Try restarting the server fully, and make sure you have saved the config.yml file before doing that. If it's still not working try asking for help on the [MOSS Discord server](https://discord.gg/PHpuzZS) in the #support channel for EssentialsX. This is almost certainly a usage issue, so you should be able to get the appropriate help setting it up there.
