### ISSUE TITLE
"head/hat" command doesn't work.

### ISSUE THREAD

**Issue by nesscoffee** [EssentialsX/Essentials#2927]
I'm on a 1.15.1 server and i installed EssentialsX, i configured everything and tested every command and head didn't work.

![image](https://user-images.githubusercontent.com/40587996/71771315-8d92cb00-2efe-11ea-9048-31f802020da0.png)

Even though i have an item on my hotbar and have it selected, it shows this.

![image](https://user-images.githubusercontent.com/40587996/71771328-bb780f80-2efe-11ea-9955-a47509e75933.png)

Translation: 

> You need to have an item in your hand to be able to wear it as a hat.

**Comment by nesscoffee** [comment]
Duplicate of #2763

**Comment by pop4959** [comment]
Thanks for marking and closing your own issue! Glad to see you figured it out yourself. :smile:
