### ISSUE TITLE
Balance reset when you change mc name

### ISSUE THREAD

**Issue by AggerTV** [EssentialsX/Essentials#2933]
### Information

Full output of `/ess version`:

https://gyazo.com/5e2b3ea5d55f84d634d6e25ead8213eb

**Server log:** https://gist.github.com/AggerTV/3cd6e6cd05afdf235e74a7c526a0b5f9

**EssentialsX config** https://gist.github.com/AggerTV/7bcf0530266a6a93047067c1e00752ff
I couldn't upload the entire file, so I just uploaded the config file

### Help request

**Problem**

Players balances are reset when they change their name. Aren't essentials saving the players uuid?? If essentials did so, this shouldn't be a problem right?

**What I have tried**

contacting my server hosty apexhosting, looking through the config file ect.

**Screenshots**

**Comment by mdcfe** [comment]
EssentialsX does save player data by UUID, and shouldn't reset it when a player changes their name.

Is your server running behind a proxy (BungeeCord, Waterfall, LilyPad, Velocity etc)?

**Comment by AggerTV** [comment]
Yeah, I have a bungeecord server

**Comment by pop4959** [comment]
Make sure that your servers are running in online mode. If so, this should certainly not be an issue.
