### ISSUE TITLE
New items from 1.15 are not available in /i or /give

### ISSUE THREAD

**Issue by Brokkonaut** [EssentialsX/Essentials#2934]
New items from 1.15 are not available in /i or /give.

For example /i bee_spawn_egg

**Comment by pop4959** [comment]
This will be fixed by #2897

**Comment by mdcfe** [comment]
1.15 items have been added in d92f5ce71c96e1f0a7fb93eeab28ed97eb13e7a0 - you can download the latest build from the [downloads page](https://essentialsx.cf/downloads). If you've modified your items.json file, be sure to move or delete it to get the updated file.
