### ISSUE TITLE
Adding Essentials /speed info into /whois

### ISSUE THREAD

**Issue by Tomographix** [EssentialsX/Essentials#2935]
### Feature request

**Feature description**

The player's essentials /speed level is included in the /whois command.

**How the feature is useful**

This would make it much easier to be able to tell if the player is using a hacked client.
/whois already displays if the player is flying or has god on. This would be similar to that.
Thanks!

**Comment by pop4959** [comment]
This suggestion doesn't really make sense, as you mention hacks, but speed hacks in hacked clients have nothing to do with the /speed command.

That aside, EssentialsX isn't designed to be a solution to hacking. You will probably want to find another plugin that is specially designed and maintained for detecting and preventing the latest hacks.

**Comment by Tomographix** [comment]
Hi @pop4959 
I'm not sure you entirely understood what I meant.
I'm not asking for essentials x to prevent hacked clients.
I was more asking if it would be possible to add in the player's speed into the /whois data so that you can tell if the player has an increased speed on or not. If they don't, then you can conclude it is a hacked client.

**Comment by mdcfe** [comment]
Out of interest, why would you give people access to `/speed` (or flight or god mode) if you don't trust those same users to not hack? Just trying to understand the use case here.

**Comment by Tomographix** [comment]
Good question. The server is 8 years old, so it was setup well before the existing EULA stuff came into place. As a result, we have introduced a 'global timed perks' system which allows for everyone online to use fly, god, speed etc if the perk is active. This allowed us to let the existing players with ranks and perks to keep them. :)

**Comment by mdcfe** [comment]
While this is a low priority, I'm not opposed to adding this in the future, and it's a small enough feature that I'm happy to target 2.18 for this.

**Comment by pop4959** [comment]
Fair enough. I did slightly misunderstand the original use case. As long as it's just including speed in whois that should be fine. Key distinction being that you are using the feature to identify hacks, not expecting Essentials to do that for you.
