### ISSUE TITLE
UUID

### ISSUE THREAD

**Issue by NEIKI19914** [EssentialsX/Essentials#2936]
[02:27:30 INFO]: [Essentials] [Economy] Found player Xing_WY by UUID 74514a27-6fe8-3522-9ba3-96e3c9720dfe but not by their actual name - they may have changed their username

### Information

Full output of `/ess version`:
 Server 版本n: 1.14.4-R0.1-SNAPSHOT git-Paper-238 (MC: 1.14.4)
[04:55:49 INFO]: EssentialsX 版本n: 2.17.1.48
[04:55:49 INFO]: LuckPerms 版本n: 5.0.39
[04:55:49 INFO]: PlaceholderAPI 版本n: 2.10.4
[04:55:49 INFO]: Vault 版本n: 1.7.2-b107
[04:55:49 INFO]: EssentialsXProtect 版本n: 2.17.1.48
[04:55:49 INFO]: EssentialsXAntiBuild 版本n: 2.17.1.48
[04:55:49 INFO]: EssentialsXSpawn 版本n: 2.17.1.48

**Server log:** 
https://github.com/NEIKI19914/no/blob/master/2020-01-11-1.log

**EssentialsX config** 
https://github.com/NEIKI19914/no/blob/master/config.yml

### Help request

**Problem**
[02:27:30 INFO]: [Essentials] [Economy] Found player Xing_WY by UUID 74514a27-6fe8-3522-9ba3-96e3c9720dfe but not by their actual name - they may have changed their username
It will repeat all the time. And the user name didn't change.

**What I have tried**
no

**Screenshots**

**Comment by pop4959** [comment]
I don't think this is an error. It looks like it's just notifying you that the user's name changed.

**Comment by NEIKI19914** [comment]
> 我不认为这是一个错误。好像只是在通知您用户名已更改。

It will repeat all the time. And the user name didn't change.

**Comment by pop4959** [comment]
OK. Do you have steps on how to replicate this? You must also include your log (just startup, not chat) and config.

**Comment by NEIKI19914** [comment]
> 好。您是否有步骤复制该文件？您还必须包括您的日志（只是启动，而不是聊天）和配置。

No copies. Configuration and logging wait.

**Comment by NEIKI19914** [comment]
> OK. Do you have steps on how to replicate this? You must also include your log (just startup, not chat) and config.

https://github.com/NEIKI19914/no/blob/master/config.yml
https://github.com/NEIKI19914/no/blob/master/config.yml

**Comment by pop4959** [comment]
Can you include the beginning of the log. It seems to be missing the startup portion. Also, does any additional information show when using `/essentials verbose`?

**Comment by NEIKI19914** [comment]
> essentials verbose

https://github.com/NEIKI19914/no/blob/master/2020-01-11-2.log
When using / essentials verbose, nothing else is shown, only the debug mode is turned on.
The log is too big. Most of them are. [Essentials] [Economy] Found player Xing_WY by UUID 74514a27-6fe8-3522-9ba3-96e3c9720dfe but not by their actual name - they may have changed their username

**Comment by NEIKI19914** [comment]
> 您可以包括日志的开头吗？它似乎缺少启动部分。此外，使用时还会显示任何其他信息`/essentials verbose`吗？



> Can you include the beginning of the log. It seems to be missing the startup portion. Also, does any additional information show when using `/essentials verbose`?
https://github.com/NEIKI19914/no/blob/master/2020-01-11-2.log
When using / essentials verbose, nothing else is shown, only the debug mode is turned on.
The log is too big. Most of them are. [Essentials] [Economy] Found player Xing_WY by UUID 74514a27-6fe8-3522-9ba3-96e3c9720dfe but not by their actual name - they may have changed their username

**Comment by NEIKI19914** [comment]
> Can you include the beginning of the log. It seems to be missing the startup portion. Also, does any additional information show when using `/essentials verbose`?

https://github.com/NEIKI19914/no/blob/master/2020-01-11-2.log
When using / essentials verbose, nothing else is shown, only the debug mode is turned on.
The log is too big. Most of them are. [Essentials] [Economy] Found player Xing_WY by UUID 74514a27-6fe8-3522-9ba3-96e3c9720dfe but not by their actual name - they may have changed their username

**Comment by pop4959** [comment]
Does this issue occur without any other plugins installed?

**Comment by NEIKI19914** [comment]
> Does this issue occur without any other plugins installed?

Thank you. It's caused by bungee tab list plus-2.8.12. It seems that essentials is queried according to tab.

**Comment by pop4959** [comment]
OK, you may want to report this to the author of that plugin then. Glad I was able to help you identify the issue.
