### ISSUE TITLE
Exception enabling Essentials v2.17.1.49

### ISSUE THREAD

**Issue by Bobcat00** [EssentialsX/Essentials#2937]
### Information

**Full output of `/ess version`**:

```
Plugin was disabled. Essentials, Chat, GeoIP, and Spawn all 2.17.1.49
```

**Server log**: https://gist.github.com/Bobcat00/4786aac6f7aa185cd3d13a84e9f23952

**EssentialsX config**: https://gist.github.com/Bobcat00/8d9d16abf3f43caaa8cb94f0d7cc9d5f

### Details

**Description**  
Attempted to update from 2.17.1.47 to 2.17.1.49 and got the exception.  Essentials then disabled itself.

Note that upgrades-done.yml is present: https://gist.github.com/Bobcat00/d80e844c888ab953271e8a0ae227748c

Spigot version git-Spigot-492a779-d208733 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
You are running the latest version

Went back to 2.17.1.47 and it works fine.

**Steps to reproduce**  
Update to 2.17.1.49 and start the server.

**Expected behavior**  
No exception.

**Screenshots**

**Comment by triagonal** [comment]
Thanks for the report! We're aware of the issue and are taking steps to fix it. Currently this issue only affects the latest build, `2.17.1.49`.

For now, just use builds `2.17.1.48` or below (as you've already done).

**Comment by Bobcat00** [comment]
OK, good to know it's not just me.  It looks very strange.  I was trying to use the new GeoIP download.  I think I deleted the contents of plugins/EssentialsGeoIP, if that helps you.

**Comment by mdcfe** [comment]
`ci.ender.zone` has been updated to Java 11, but this prevents EssentialsX from working on Java 8. While we work on a fix, you can download a working build from the [PaperMC CI](https://papermc.io/ci/view/%20%20Plugins/job/EssentialsX/).

**Comment by mdcfe** [comment]
This has been fixed in the [latest build](https://essentialsx.cf/downloads.html) (fa06cd825343ae8469cb99c0dbdf3c2d9fe4bf3c).

**Comment by Bobcat00** [comment]
Confirmed that it is fixed.
