### ISSUE TITLE
Kit Deletion

### ISSUE THREAD

**Issue by vosque** [EssentialsX/Essentials#2939]
### Information

Full output of `/ess version`:

**Server log:** 

**EssentialsX config** 

### Help request

**Problem**

There are premade kits and I don't know how to delete them. The /delkit command doesn't work
**What I have tried**

/delkit /kitdel /delete /deletekit /kitdelete etc. 
**Screenshots**

**Comment by pop4959** [comment]
In the latest version, delete in config or with `/delkit`. Please fill out all of the required information in the issue template if you need more support.
