### ISSUE TITLE
1.15.1 Vanilla Teams

### ISSUE THREAD

**Issue by wybran** [EssentialsX/Essentials#2940]
EssentialsX-2.17.1.50
In my Java Code:
Player player = chat.getPlayer();
Team team = player.getScoreboard().getEntryTeam(player.getDisplayName());
With EssentialsX on server a team is null but without EssentialsX is returned correct value

**Comment by pop4959** [comment]
As far as I can see, Essentials does not set or modify teams. This is most likely an issue in your code. Please feel free to file a bug report if you can methodically describe something that Essentials is doing which causes adverse behaviour.
