### ISSUE TITLE
[1.15.1] EssentialsX’s /give command not working with target selectors

### ISSUE THREAD

**Issue by Nevrai** [EssentialsX/Essentials#2941]
### Information

**Full output of `/ess version`**:
_Server version: 1.15.1-R0.1-SNAPSHOT git-Paper-42 (MC: 1.15.1)
EssentialsX version: 2.17.1.0
Vault is not installed. Chat and permissions may not work.
You are running an unsupported server version!_

```
Error: Player not found.
```

**Server log**: Not necessary

**EssentialsX config**: https://gist.github.com/DeleteMetaInf/d96f42818c27af6eae4b3b656983a10a

### Details

**Description**  
EssentialsX’s /give command does not work with [target selector variables](https://minecraft.gamepedia.com/Commands#Target_selector_variables), such as @p and @a. It simply says “Error: Player not found,” both when using it in-game and in the console.

When using /minecraft:give command instead of EssentialsX’s /give command, target selectors work as expected.

I’m using [PaperMC](https://papermc.io/) for Minecraft 1.15.1.

**Steps to reproduce**  
1. Use a /give command with a target selector (e.g., `/give @p dirt`).

**Expected behavior**  
The command should, presumably, work with target selectors as the vanilla one that it replaces does.

**Screenshots**  
Not necessary.

**Comment by mdcfe** [comment]
In 1.13, Spigot removed its support for vanilla selectors in plugin commands. You can use a plugin like [PsudoCommands](https://www.spigotmc.org/resources/psudocommands-add-the-target-selector-to-plugin-commands.56738/) or [CommandHook](https://www.spigotmc.org/resources/commandhook.61415/) to restore selector functionality for plugins.

Edit: in EssentialsX loop commands that can run on multiple players, you can use `*` or `**` to select all players.

**Comment by Nevrai** [comment]
Oh, I see. Thanks.

Now I’m wondering why Spigot removed its support for this feature when it can just be re-added by a plugin.

**Comment by Bonnetwalker** [comment]
the @p command isn't working on essentialsX how to fix? Can you explain it a bit easier pls?

**Comment by MajorMistakes** [comment]
Is there any way I could restore @s with a server mod instead of a plugin? Google isn't helping me.
