### ISSUE TITLE
World/Region Teleport Warmup Bypass

### ISSUE THREAD

**Issue by GiansCode** [EssentialsX/Essentials#2949]
### Feature request

**Feature description**
Allow admins to specify worlds (or WorldGuard regions?) where players could instantly teleport/warp, bypassing the cooldown. 

Ideally, there is a warmup feature for /warp, /spawn, /home, etc, and, in some cases, such as if they come to /spawn to use a Crate Key and then go back to /home, there is a wasted x seconds during the spawn to home tp. So, if they're in the spawn region, or the spawn world, they will bypass any warmup

**How the feature is useful**
It's a simple QOL change that improves player experience.

**Comment by mdcfe** [comment]
You can use the `essentials.teleport.timer.bypass` permission to allow a user to skip the teleport delay (warmup), and you can enable this conditionally in certain worlds/regions using LuckPerms to allow people to teleport without the delay.

What would this achieve that you can't achieve using conditional permissions?
