### ISSUE TITLE
Saving data on quit Crash

### ISSUE THREAD

**Issue by AguaDeLaMiseria** [EssentialsX/Essentials#2951]
### Information

Full output of `/ess version`:
Server version: 1.15.1-R0.1-SNAPSHOT git-Paper-32 (MC: 1.15.1)
EssentialsX version: 2.17.1.34
LuckPerms version: 4.4.1
PlaceholderAPI version: 2.10.4
 Vault version: 1.7.2-b107
EssentialsXSpawn version: 2.17.1.34

**Server log:** https://pastebin.com/NT8zrV9L

**EssentialsX config** https://pastebin.com/2yQeanmA

### Help request

**Problem**
Server crash when a player quit the server, I believe by reading the error that Essentials had a problem saving in userdata file

**What I have tried**
I have searched in forusm yet haven't found anything or any solution, except something related to chmod but my linux knowledge is limited

**Screenshots**

**Comment by pop4959** [comment]
Watchdog dumps stack traces regardless of whether a plugin caused it or not when the server has been lagging or unresponsive for a certain period of time.

Most likely this is not a problem with Essentials but with your server. If you only received this error once, I would not worry. If you crash consistently with the same stack trace pointing to `com.earth2me.essentials.EssentialsConf.delayedSave` then there may be an actual issue. Still, it may be worth checking timings and looking for other sources of lag that may have caused your server to crash.

**Comment by AguaDeLaMiseria** [comment]
Aight thank you for the response, it has been the first time so if it happens again pointing to delayedSave I'll make sure to reply.

**Comment by pop4959** [comment]
Cleaning up for now, but if you do find further evidence on this feel free to respond and we can consider re-opening the issue.
