### ISSUE TITLE
[1.15.1] Player prefix does not appear in the player list

### ISSUE THREAD

**Issue by Nevrai** [EssentialsX/Essentials#2956]
### Information

Full output of `/ess version`:

```
Server version: 1.15.1-R0.1-SNAPSHOT git-Paper-51 (MC: 1.15.1)
EssentialsX version: 2.17.1.52
LuckPerms version: 5.0.39
Vault version: 1.7.2-b107
EssentialsXChat version: 2.17.1.52
```

**EssentialsX config**
https://gist.github.com/DeleteMetaInf/c30463266b852d00fea0f1fa6db82b4e#file-config-yml

### Help request

**Problem**
The player list (`Tab`) displays my username, ping, etc., but it doesn’t show my prefix, which is set by [Luck Perms](https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/).

The prefix appears just fine in the chat but not in the player list. If I give myself a nickname with /nick, it does display in the player list as expected, but my prefix doesn’t.

change-displayname, change-playerlist, and add-prefix-in-playerlist are all set to true.

**Screenshots**
![Tab list not showing prefix](https://user-images.githubusercontent.com/59761487/72657878-50bcde80-39aa-11ea-9ec2-1c0cea116392.png)

The number after my username is part of a scoreboard added by a datapack.

**Comment by montlikadani** [comment]
Please next time complete the issue templates.
List out what plugins are you installed to your server? Maybe there is some plugins which overwrites the tab names.

**Comment by pop4959** [comment]
Please try it without any other plugins installed besides those listed in `/ess version`.

**Comment by Nevrai** [comment]
I didn’t think that the server log was relevant. Apologies.

I tried removing every plugin, datapack, and mod I had installed—except EssentialsX, EssentialsXChat, Vault, and LuckPerms—and I also created a new world. However, I’m still having the same issue, so it’s not a plugin conflict.

[Here is the server log after this test.](https://pastebin.com/raw/wzGTaueE)

![Tab list not showing prefix 2](https://user-images.githubusercontent.com/59761487/72672973-a7d2ba00-3a63-11ea-8bc6-fae5d24b8653.png)
![Hello!](https://user-images.githubusercontent.com/59761487/72672974-aacdaa80-3a63-11ea-97bb-5cb9b538e666.png)

After taking those screenshots, I also tried removing my active resource packs, but that didn’t change anything other than making the font look all pixelated again.

**Comment by Nevrai** [comment]
I also tried to set a custom join message including the display name of the player joining:
`custom-join-message: "{PLAYER} &ejoined the game"`

However, it just shows their name, not their prefix. For some reason, the prefix doesn’t seem to be counted as part of the person’s display name.

**Comment by mdcfe** [comment]
Change `add-prefix-suffix: false` back to `true`. When set to false, EssentialsX will never add the prefix/suffix to the player's display name, even when you set other options to `true`.
