### ISSUE TITLE
Extra commands for kits

### ISSUE THREAD

**Issue by SirBlobman** [EssentialsX/Essentials#296]
You guys already have /createkit, which is awesome
I would like to see these commands:
- /deletekit - Deletes a kit
- /addtokit - Adds current held item to a kit
- /kitgui - Shows a GUI for available kits

**Comment by drtshock** [comment]
There's /showkit <name> which prints items in a kit.
/kit will list all kits available to you.
Delete and add would cause issues with comments in your config being erased. The /createkit is meant as a step you can do to create the kit section, and then copy that over to a production config to preserve your comments. It's not meant as an on-the-fly command to use regularly.

**Comment by SirBlobman** [comment]
Oh ok
