### ISSUE TITLE
Contexts - Brainstorming

### ISSUE THREAD

**Issue by zml2008** [EssentialsX/Essentials#2960]
**Feature description**
Since modern permissions plugins have context support, what sort of contexts would be useful for permissions matching? Here are a few based on things that I've seen in the discord, other ideas are appreciated since I don't know much about EssX's full feature set.

Context | Values | Purpose
---------- | -------- | -------------
`afk`      | `true`/`false` | Indicate whether or not a player is marked AFK
`jail`      | jail name | List the current jail a player is in, when they are in a jail

Probably not worth implementing these until we get a common permissions API together? Gives time to think about what's useful though.

**How the feature is useful**

These contexts allow users to customize the affected EssX features by choosing which permissions are applicable in each context. For example, this allows preventing a player from taking damage while afk without having that specifically be a feature of Essentials' AFK handling.

**Comment by mdcfe** [comment]
A few more based a quick glance at other plugins' integrations with EssentialsX:

Context | Values | Purpose
---|---|---
`god` | `true/false` | Indicates whether a player is in god mode.
`flight` | `true/false` | Indicates whether a player has flight mode enabled.
`vanished` | `true/false` | Indicates whether a player is vanished.
`mute` | `true/false` | Indicates whether a player has been muted.

I'm happy to consider implementing these when there is a stable context API we can rely upon, whether that's LP or a common API.

**Comment by pop4959** [comment]
Closing this since the context system now exists in EssentialsX. Further issues can be opened to request additional contexts.
