### ISSUE TITLE
[1.15.1] Full stops are removed from lore text except from the last line

### ISSUE THREAD

**Issue by Nevrai** [EssentialsX/Essentials#2962]
### Information

**Full output of `/ess version`**:

```
Server version: 1.15.1-R0.1-SNAPSHOT git-Paper-57 (MC: 1.15.1)
EssentialsX version: 2.17.1.52
LuckPerms version: 5.0.39
Vault version: 1.7.2-b107
EssentialsXChat version: 2.17.1.52
```

**Server log**: https://gist.github.com/DeleteMetaInf/7f17c850e81712d22dfc3835d4d72205

**EssentialsX config**: https://gist.github.com/DeleteMetaInf/6efe4f8a47e1addf2a0c99945d5a0c0e

### Details

**Description**
Items from kits lack full stops at the end of each line in the lore text except the last line. In this case, I created a stone block with three lines of lore text, each ending with a full stop. The lore text displays the full stops as one would expect, but when I created a kit with this item in it and gave myself that kit, the first two lines lacked full stops.

Strangely, the full stops _are_ present in kits.yml:

```
  stonetest:
    delay: 1
    items:
    - stone 1 lore:testing123.|test123.|test3.
```

In another instance, I had done this with an item with two lines of lore text, and the first line lacked a full stop but not the second line. It’s always the last line that has a full stop while the other lines lack them.

**Steps to reproduce**
1. Create an item.
2. Give it at least two lines or lore text.
3. Create a kit with that item using the kitcreate command.
4. Give yourself that kit using the kit command.

**Expected behavior**
The full stops should be in the lore text.

**Screenshots**
##### Item with lore:
![1](https://user-images.githubusercontent.com/59761487/72872260-36a63780-3ced-11ea-9dee-3e7131760dcf.png)

##### The same item added to my inventory using the kit command:
![2](https://user-images.githubusercontent.com/59761487/72872259-36a63780-3ced-11ea-9dd9-60282acc82ad.png)

**Comment by LazyGon** [comment]
give command has same problem.
`/essentials:give {player} stone 1 lore:|testing123.|test123.|test3.`
This command gave me this item:
![img](https://i.gyazo.com/80c02ecc04e2076b4c866faa9e4b6cd8.png)

※ lore:| means first line should be empty.

**Comment by Nevrai** [comment]
Thanks for the fix! ☕
