### ISSUE TITLE
[1.15.2] EssentialsX is unable to load (java.lang.NoSuchMethodError)

### ISSUE THREAD

**Issue by lucasluqui** [EssentialsX/Essentials#2964]
### Information

**Full output of `/ess version`**:

Can not run the command as the plugin is unable to start.

**Server log**: https://gist.github.com/lucas-allegri/b1e4a75124bc2d25f2841d2e0f594877

**EssentialsX config**: https://gist.github.com/lucas-allegri/94b6602c88d82d27d08d958d0079348f

### Details

**Description**  
Upon starting the server (Spigot 1.15.2), EssentialsX fails to load, throwing a java.lang.NoSuchMethodError.

**Steps to reproduce**  
No steps required, simply starting the server with the plugin in it causes it.

**Expected behavior**  
Plugin should start correctly.

**Screenshots**  
-

**Comment by mdcfe** [comment]
This may be related to SPIGOT-5532.

Could you rebuild Spigot using BuildTools and try again? Spigot made some changes to legacy support in git-Spigot-800b93f-efd6cf5 but subsequently pushed another commit to fix a bug introduced by that version.

**Comment by lucasluqui** [comment]
Indeed, that seems to have fixed the issue, thank you!
