### ISSUE TITLE
KeepInventory & TeleportDelay

### ISSUE THREAD

**Issue by Forhael** [EssentialsX/Essentials#2969]
1. Hello, I using EssentialsX and when I die my inventory is keeping, I tried with OP and without OP, but same result. Permission  "essentials.keepinv false" don't working, I using PermissionsEx. Please Help!

2. Problem number two, teleport waiting tme don't working only for me! With OP or no I haven't got any waiting time, but my friends on same server have! 

(I'm Owner)

All my plugins: WorldEdit, OpenInv, LogBlock, PlaceholderAPI, WorldGuard, Clans, ProtocolLib, BloodEffects, SkinsRestorer, UberEnchant, PermissionsEx, TabListPro, TreeGravity, GSit, Vault, DailyRewards, ID-Library, MassiveCore, AdvancedRegionMarket, Essentials, GChestShop, GCore, Admin-GUI, Prison, Matrix, Jobs, KillRewards, HolographicDisplays, ActionHealth, Marriage, Vote, EssentialsXMPP, GParticles, Shopkeepers, EssentialsProtect, EssentialsGeoIP, EssentialsChat, EssentialsAntiBuild, EssentialsSpawn

Thanks!

**Comment by triagonal** [comment]
You need to make sure you're negating the permissions correctly with PermissionsEx. As per the [PEX wiki](https://github.com/PEXPlugins/PermissionsEx/wiki/Basic-Permissions-Setup#important-file-back-end-notes-top), your negated permissions need to be declared **before** any wildcards like `essentials.*` or `*`.

Your first problem will be solved be correctly negating `essentials.keepinv`, and your second will be solved by correctly negating `essentials.teleport.timer.bypass`.

We also recommend switching to [LuckPerms](https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/), as PermissionsEx is no longer maintained and may cause compatibility issues with EssentialsX.

**Comment by Forhael** [comment]
Admin:
    default: false
    prefix: '&8[&cAdmin&8]&7'
    permissions:
    - essentials.teleport.timer.bypass
    - essentials.keepinv
    - '*'

Is this correct? It's not working!

**Comment by pop4959** [comment]
As triagonal mentioned earlier, we don't actually support PermissionsEx currently (because it has numerous issues) so we cannot tell you whether that is correct or not. For help with proper usage of the plugin, we recommend using the [Discord server](https://discord.gg/PHpuzZS) to ask your questions. Perhaps other server owners may know the answer.
