### ISSUE TITLE
msgtoggle resets on restart

### ISSUE THREAD

**Issue by EvilOlaf** [EssentialsX/Essentials#297]
I am not absolutely sure but it seems like that if a player sets `msgtoggle` for himself this switches back to default when the server has been restarted.

Not sure if this is wanted or not. Anyway way not a big deal at all.

Build 206 (yes, a bit outdated, I know)

**Comment by mdcfe** [comment]
This could be implemented by moving `ignoreMsg` from User to UserData and saving it, but it seems like a relatively minor enhancement.

**Comment by mdcfe** [comment]
Is this no longer worth adding?
