### ISSUE TITLE
[1.15.1] /unlimited fireworkrocket does not give unlimited firework rockets

### ISSUE THREAD

**Issue by TheCashFire** [EssentialsX/Essentials#2971]
Just as the title says, /unlimited fireworkrocket and /unlimited firework_rocket both respond with 'Giving unlimited amount of fireworkrocket to USER, but do not actually result in unlimited firework rockets as they are consumed normally. I tested it on other items like sand, dirt, and netherwart, and it works properly for all of them, so it appears to be isolated to this item as far as I can tell. Tested it both standing still placing on the ground and using them as propellant for an elytra, same effect.

Using EssentialsX version 2.17.1.50 .

**Comment by TheCashFire** [comment]
What more info can I provide? I'm looking to see if there can be a fix for this.

**Comment by pop4959** [comment]
I automatically added that label to this issue because you deleted / did not fill out the issue template.

**Comment by TheCashFire** [comment]
Fine. New ticket made.

**Comment by pop4959** [comment]
Thanks, that'll help ensure that the issue can be reproduced reliably (and confirm that there are no other issues in your server or configuration). Definitely saves the developers and testers a lot of time.
