### ISSUE TITLE
/nick command error

### ISSUE THREAD

**Issue by Lyrians** [EssentialsX/Essentials#2972]
### Information

**Full output of `/ess version`**:

```
24.01 00:46:46 [Server] INFO CONSOLE issued server command: /ess version
24.01 00:46:46 [Server] INFO Server version: 1.14.4-R0.1-SNAPSHOT git-Paper-156 (MC: 1.14.4)
24.01 00:46:46 [Server] INFO EssentialsX version: 2.17.1.52
24.01 00:46:46 [Server] INFO LuckPerms version: 5.0.39
24.01 00:46:46 [Server] INFO PlaceholderAPI version: 2.10.4
24.01 00:46:46 [Server] INFO Vault version: 1.7.2-b107
24.01 00:46:46 [Server] INFO Citizens version: 2.0.26-SNAPSHOT (build 1804)
24.01 00:46:46 [Server] INFO EssentialsXProtect version: 2.17.1.52
24.01 00:46:46 [Server] INFO EssentialsXChat version: 2.17.1.52
24.01 00:46:46 [Server] INFO EssentialsXSpawn version: 2.17.1.52
```

**Server log**: https://gist.github.com/Lyrians/6a95ed8e09126b441a54ea48c65dea26

**EssentialsX config**: https://gist.github.com/Lyrians/ddb48f6241c891f5d8f9bb1113b9f85c

### Details

**Description**  
When trying to change the nick, throw error

**Steps to reproduce**  
Enter the command / nick

**Expected behavior**  
Obviously the command will work.

**Screenshots**

**Comment by pop4959** [comment]
The reason is you have disabled `change-displayname` in config.yml. Change the value back to `true` and it should work again.
