### ISSUE TITLE
Add essentials.nick.changeformatting

### ISSUE THREAD

**Issue by Weasel-Beans** [EssentialsX/Essentials#2973]
There is a permission, 'essentials.nick.changecolors', which only allows you to change the colors in your nickname. Can it please be made possible to also have a permission node that only allows you to change formatting with /nick?

This would be great for different supporter tiers. It would definitely help me if this feature was added. 

Edit: I believe that 'essentials.nick.changecolors' actually includes formatting. It would be very nice if this was split into separate nodes for colors and formatting though. Not including magic.

**Comment by mdcfe** [comment]
You can use EssentialsX's [colour and format permissions](https://essentialsx.cf/wiki/Color-Permissions.html) alongside `essentials.nick.changecolors` to restrict which formatting codes are allowed. You can either allow/deny specific colours and formatting types, or you can allow/deny all colours or types with `essentials.nick.color` or `essentials.nick.format`.
