### ISSUE TITLE
[1.15.2] /unlimited fireworkrocket does not make firework rockets unlimited

### ISSUE THREAD

**Issue by TheCashFire** [EssentialsX/Essentials#2974]
### Information

Full output of `/ess version`:
[01:19:36] [Server thread/INFO]: Server version: 1.15.1-R0.1-SNAPSHOT git-Spigot-492a779-fde78ef (MC: 1.15.1)
[01:19:36] [Server thread/INFO]: EssentialsX version: 2.17.1.52
[01:19:36] [Server thread/INFO]: LuckPerms version: 5.0.39
[01:19:36] [Server thread/INFO]: PlaceholderAPI version: 2.10.4
[01:19:36] [Server thread/INFO]: Vault version: 1.7.2-b107

**Server log:** 
https://gist.github.com/TheCashFire/b07b77f3483461dfe79e39f65675ec71

**EssentialsX config** 
https://gist.github.com/TheCashFire/b8e93fdb45b29cab1ec16ba398797eba

### Help request

**Problem**
When attempting to use /unlimited fireworkrocket or /unlimited firework_rocket, the message is sent back to the user saying that the user now has access to unlimited firework rockets, but they aren't actually unlimited as the stack still drains as normal.

**What I have tried**
Tried updating to the most recent version of EssentialsX. Tried removing plugins in groups down to just EssentialsX, still didn't work. All other /unlimited items that I have tried have allowed unlimited items, but firework rockets don't seem to work for some reason.

**Comment by AMDBartek** [comment]
I can confirm that this is a bug.

**Comment by mdcfe** [comment]
This is not a bug. `/unlimited` only supports block placement, not item usage - as far as Bukkit is concerned, those are two distinct things.

**Comment by JRoy** [comment]
Not possible on spigot, would require Paper and since that would produce inconsistent behavior I don't think this is something we can add.
