### ISSUE TITLE
can i stop players from recieving /pay from others?

### ISSUE THREAD

**Issue by Stoniasawsome** [EssentialsX/Essentials#2978]
can i stop players from recieving /pay from others? or a eco blacklist. 
if not could that be arranged like essentials.eco.use option or something or essentials.eco.blacklist

**Comment by pop4959** [comment]
For what purpose is this? You didn't elaborate on how this is useful.

**Comment by pop4959** [comment]
Please feel free to create a new feature request issue and fill out the template so that we have more details about what you want, and why it is useful.

**Comment by Stoniasawsome** [comment]
I would like to have the ability for some ranks not to be included into the eco, 1 example could be for having a jailed rank not be able to take payments from others. another example could be if you wanted to enforce the rule of no begging, people couldn't undermine you and pay the beggar.  I dont prefer to share the main reason i would like this included is so that i can use the economy money for many things like games and roleplay.

**Comment by Stoniasawsome** [comment]
oh sorry where is the new feature request thing?
