### ISSUE TITLE
A permission to bypass the nickname identifier (~ by default)

### ISSUE THREAD

**Issue by Nevrai** [EssentialsX/Essentials#2979]
### Feature request

**Feature description**
A permission that, if they have it, removes the tilde (`~`) (or whatever the nickname identifier is set to in EssentialsX’s config.yml) from a player’s nickname.

#### Example:

| Player without essentials.nick.bypass  | Player _with_ essentials.nick.bypass |
| ------------- | ------------- |
| /nick JohnSmith  | /nick JohnSmith  |
| ~JohnSmith  | JohnSmith  |

If a player with the permission _does_ want the tilde at the beginning of their nickname, they could simply add it themselves (e.g., `/nick ~JohnSmith`).

**How the feature is useful**
This feature would be useful for admins, mods, VIPs, and players of other important roles to be able to use a nickname without it looking like a nickname. It’s useful, for instance, if a user is well-known by the community as a certain name that isn’t the same as their in-game username and don’t need the tilde to make it clear that it’s a nickname. Admins and mods are unlikely to use nicknames to pretend to be other players, too—and besides, they usually have special rank tags such as “[Admin]” and “[Mod],” which makes that impossible in the first place.

It could also be a permission to give as a perk for donators to make their nicknames prettier by removing the distracting tilde from the nickname.

**Comment by thehydrogen** [comment]
+1

**Comment by Nevrai** [comment]
What is your opinion on my idea?

Is this something that could potentially be added to EssentialsX? 🙂

**Comment by pop4959** [comment]
I don't think this will be added to EssentialsX. Just set the nickname prefix in config. If you don't want a nickname prefix, don't set it. The nickname command does not let you set a nickname that exactly matches another player. In addition, there is a /realname command. All of that, plus proper moderation on your server, should fix your issues regarding names. The only other reasons for adding this are superficial.
