### ISSUE TITLE
can we get a permission to disable econ per user/group

### ISSUE THREAD

**Issue by Stoniasawsome** [EssentialsX/Essentials#2981]
I am suggesting a permission that allows you to disable economy for users and or groups. An example of the permission node could be essentials.eco.ban or essentials.eco.blacklist so that players could not recieve /pay from others or the server.

This feature would be useful. 1 example could be for having a jailed rank not be able to take payments from others. another example could be if you wanted to enforce the rule of no begging, people couldn't undermine you and pay the beggar. I dont prefer to share the main reason i would like this included in public, but i can give a spoiler. it is so that i can use the economy money for many things like games and roleplay. With other money plugins installed like banknotes you can use essentials economy for more useful things like im suggesting.

**Comment by pop4959** [comment]
There doesn't seem to be much interest in this, and it's probably too niche to consider adding to Essentials. Feel free to use another economy plugin though if this is important to your server, as there are many.
