### ISSUE TITLE
kit lore drops last char from each line

### ISSUE THREAD

**Issue by CaszGamerMD** [EssentialsX/Essentials#2984]
Kit lore drops the last character in each line
example from kit.yml
"end_portal_frame 1 name:&d&k..._&dGamble_Loot_Noot_&k... lore:&k..._&5This_box_contains_&91-3|&k..._&5Loot_Noots_of_Various_Sorts.|&9GambleBox"

ingame
![Screen Shot 2020-02-01 at 3 19 03 AM](https://user-images.githubusercontent.com/37286039/73589891-ad87c100-44a1-11ea-82cb-dec2003ed977.png)

**Comment by pop4959** [comment]
Seems to be a similar problem to #2962

**Comment by pop4959** [comment]
Closed in favour of #2962. Please follow that issue for further updates on this.
