### ISSUE TITLE
The EssentialsX clear command will not let me clear all items of a specific type

### ISSUE THREAD

**Issue by AMDBartek** [EssentialsX/Essentials#2986]
### Help request
**Output of /ess version**

Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
EssentialsX version: 2.17.1.53
LuckPerms version: 5.0.39
Vault version: 1.7.2-b107
EssentialsXProtect version: 2.17.1.53
EssentialsXChat version: 2.17.1.53
EssentialsXSpawn version: 2.17.1.53

**Problem**
Whenever I use the EssentialsX clear inventory command I cannot get it to clear ALL items of a specific type it just says: "Removed 0 of [Item] from [Username]"

**What I have tried**
I have tried using the Minecraft clear command with /Minecraft:clear but I do not want to have to use the Minecraft command as I would rather use the EssentialsX command

**Screenshots**

**Comment by pop4959** [comment]
We are aware of this problem, it is currently not a feature but it might be added in the future. It does certainly make much more sense for the clear command to remove all items rather than zero items by default (as that is quite useless functionality).

**Comment by AMDBartek** [comment]
I would also recommend for "/clear [USERNAME] [ITEM] -1" to clear all items of the specified type. (However, I would like the default to be all items of the specified type.)

**Comment by pop4959** [comment]
This is actually a bug as it appears the command is intended to clear all items in the cases you described.

**Comment by pop4959** [comment]
@AMDBartek It's finally fixed in the latest version 😄
