### ISSUE TITLE
Config option to specify worlds where flying is always enabled if the player has essentials.fly

### ISSUE THREAD

**Issue by Nevrai** [EssentialsX/Essentials#2987]
#### Feature description
New option in the config:
```
flying-always-enabled-in-world:
  - world1
  - world2
```

In this case, if the player is in world1 or world2, they’ll either have their fly mode set to enabled as soon as they enter world1 or world2, or their f lying mode will always be set to enabled while they are in either world—provided that they have the _essentials.fly_ permission, of course.

#### How the feature is useful
On my upcoming server, certain donators will be able to fly in the hub world only. I gave the relevant group the _essentials.fly_ permission in the [context](https://github.com/lucko/LuckPerms/wiki/Context) of _world=hub_ using [LuckPerms](https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/), and that works fine. When a player leaves the hub with flying enabled, their fly mode is set to disabled, and they can’t re-enable it, which is what I want.

However, when they teleport back to the hub, they can’t fly unless they enable their fly mode. They _can_ set their own fly mode to enabled and fly just fine, but I want their fly mode to be enabled by default when they’re in the hub so that they don’t have to use the fly command every time they go to the hub.

I believe this feature would be useful to many other server owners as well.

**Comment by Nevrai** [comment]
What do you think of my idea? Is this something that could be implemented?

**Comment by pop4959** [comment]
I don't think this is an appropriate addition, as it is extremely niche. There are almost certainly hub plugins that will do this for you.
