### ISSUE TITLE
/ess version says Vault is not installed but Vault is installed

### ISSUE THREAD

**Issue by AMDBartek** [EssentialsX/Essentials#2988]
## Details

**EssentialsX config

https://hasteb.in/raw/reyeqero (GitHub would not let me upload a yml file so I put it on Hastebin)

**Server log**

[2020-02-03-14.log](https://github.com/EssentialsX/Essentials/files/4149832/2020-02-03-14.log)

**Output of /ess version**

Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
EssentialsX version: 2.17.1.54 (Still happens with 2.17.1.56)
LuckPerms version: 5.0.39
Vault is not installed. Chat and permissions may not work.

**Description**  
/ess version says that Vault is not installed even though Vault is installed

**Steps to reproduce**  
1. Install EssentialsX 2.17.1.54
2. Install Vault
3. Do /ess version
4. Check the output

**Expected behavior**  
For /ess version to say that Vault is installed and provide version info about Vault

**Info**

This only started happening with EssentialsX version 2.17.1.54 and not version 2.17.1.53

**Screenshots**

**Comment by pop4959** [comment]
This is an known issue in build 54. It will be fixed, but I believe it's mostly just a visual problem. The Vault integration should still be working. You can use build 53 for now if this is a nuisance to you, though.

**Comment by pop4959** [comment]
Should be fixed in the latest build, due to 5503e1e14c4848199ba1f4f1c8dcf16f56ae49ee which reverts the change that introduced this bug.
