### ISSUE TITLE
Turn off socialspy on logout

### ISSUE THREAD

**Issue by Mikgreg** [EssentialsX/Essentials#299]
A very useful feature would be a config option to have socialspy turned off on every log out, often our staff when leaving or being removed from the team keep their socialspy as when you lose permissions for it the socialspy will still remain on. This becomes very difficult to administer with large teams on networks with many servers.

**Comment by SupaHam** [comment]
Will need to confirm this with the team, but in general you should be checking their user config file for whatever reason.

**Comment by Mikgreg** [comment]
Regular checking of their user files across 6+ servers for a team that sometimes reaches over 50 people is impractical :( Hence my suggestion

**Comment by drtshock** [comment]
Yeah we could make that a config option. Just have your social-spy status not persist and default to off.

**Comment by drtshock** [comment]
Actually, @SupaHam thought of a better solution.

**Comment by drtshock** [comment]
That commit should be a great solution to this @Mikgreg
