### ISSUE TITLE
Hello. I have suggestions.

### ISSUE THREAD

**Issue by Minecraftdf** [EssentialsX/Essentials#2990]
1) Would be good have commands /setspawn /spawn

2) GUI for /homes /help /warps

3) Hide/Unhide command from TAB

4) Color signs permission

**Comment by pop4959** [comment]
1. Those commands already exist, download EssentialsXSpawn.

2. Gui probably won't come anytime soon, but it has been under discussion.

3. That already exists. It's called vanish.

4. That already exists, refer to the Essentials permissions page.
