### ISSUE TITLE
Not able to store wheat seeds in signs.

### ISSUE THREAD

**Issue by Mihoshika** [EssentialsX/Essentials#2995]
Wheat seeds not added to items.csv in Essentials 2.x

Seeds name changed to Wheat seeds. Namespaced ID is now "wheat_seeds"

Seeds/seed don't work as an alias for it.

**Comment by pop4959** [comment]
Please create a new issue and properly fill out the given template. Ignoring it does not allow us to diagnose the problem or provide you with a solution.

**Comment by Mihoshika** [comment]
... There is nothing more to be said. Wheat seeds can not be stored in signs. 

Just looking at https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/items.csv#L5031 you will notice there is no correct alias to account for the change of seeds to wheat seeds. As such, you are not capable of storing them in signs via "seeds" "seed" or "wheatseed" or "wheat_seed" or any similar variant. 

I ignore the "given template" because this is simple enough that it shouldn't warrant it. I specifically said the issue, as well as how to resolve it.

**Comment by pop4959** [comment]
The identifier "wheat_seeds" is working properly for me on the latest version of Essentials. I'm not sure why you have such a huge aversion to filling out the template. In the time you have spent complaining, you could have done so already. If it really is a simple issue, it should be resolved in a timely manner once you have provided all of the necessary details. Please either create a new issue, or edit this one to include the filled-out template.
