### ISSUE TITLE
How to disable Item Meta?

### ISSUE THREAD

**Issue by Tenkomanker** [EssentialsX/Essentials#2996]
### Information

Full output of `/ess version`:

**Server log:** 

**EssentialsX config** 

### Help request

**Problem**

**What I have tried**

**Screenshots**

So I'm trying to spawn custom potions and other items and I'm having trouble using it to get a custom color for potions even though I know its possible. Is there a way to disable the item meta to use the normal minecraft item meta?

**Comment by pop4959** [comment]
Use /minecraft:give instead of /essentials:give (or usually just /give). The EssentialsX item meta format does not support all tags for all items, due to limitations imposed by Spigot.
