### ISSUE TITLE
XP Command Tab Complete

### ISSUE THREAD

**Issue by JasonHorkles** [EssentialsX/Essentials#3000]
### Information

**Full output of `/ess version`**: 

```
Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-90 (MC: 1.15.2)
EssentialsX version: 2.17.1.53
LuckPerms version: 5.0.72
Vault version: 1.7.2-b107
Citizens version: 2.0.26-SNAPSHOT (build 1804)
EssentialsXGeoIP version: 2.17.1.53
EssentialsXSpawn version: 2.17.1.53
```

**Server log**: https://gist.github.com/JasonHorkles/8be1369b79583965bf552f28edbfe130

**EssentialsX config**: https://gist.github.com/JasonHorkles/84e99ae8d7e2f7fb1ff6885ba779c8bc

### Details

**Description**  
The tab complete for the xp command is a bit messed up. When doing /xp give/set/take it won't suggest a player but will suggest adding `l` after you type a number, and then will suggest names after you press space. /xp reset also doesn't suggest anything at all.

**Steps to reproduce**  
Type `/xp give` (or set / take)
Type a number and it'll suggest adding `l`
Press space
It suggests names

Type `/xp reset`
It suggests nothing

**Expected behavior**  
/xp give/set/take should have the tab suggestions flipped as you have to type the username first and then the amount of xp

/xp reset should act like /xp show where it suggests a name to use

**Comment by mdcfe** [comment]
Needs investigating, but this sounds like the tabcomplete for the command wasn't updated when its syntax was updated.

**Comment by AMDBartek** [comment]
I can confirm that the XP command has a broken tab-complete.
