### ISSUE TITLE
The essentials.balancetop.exclude permission does not work when the player is offline

### ISSUE THREAD

**Issue by AMDBartek** [EssentialsX/Essentials#3004]
### Details

**Server files**

EssentialsX config: https://hasteb.in/raw/tizotene

No server log provided because there was no errors or warnings.

**Output of /ess version**

Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
EssentialsX version: 2.17.1.53
LuckPerms version: 5.0.39
PlaceholderAPI version: 2.10.4
Vault version: 1.7.2-b107
EssentialsXProtect version: 2.17.1.53
EssentialsXChat version: 2.17.1.53
EssentialsXSpawn version: 2.17.1.53

**Description**  
A player with the essentials.balancetop.exclude permission will still show up in /baltop when offline however when the player is online it hides them from baltop. This happens in the newest EssentialsX release as well.

TestUser with permission essentials.balancetop.exclude when offline:

There are 0 out of maximum 35 players online.
Top balances (09/02/20 11:42)
 ---- Balancetop -- Page 1/1 ----
Server Total: £9,666
1. Mario27639, £9,259
2. User2, £107
3. User3, £100
4. User4, £100
5. TestUser, £100

TestUser with permission essentials.balancetop.exclude when online:

There are 1 out of maximum 35 players online.
Players: [Player] TestUser
Top balances (09/02/20 11:49)
---- Balancetop -- Page 1/1 ----
Server Total: £9,566
1. Mario27639, £9,259
2. User2, £107
3. User3, £100
4. User4, £100

**Steps to reproduce**  
1. Give a user the permission essentials.balancetop.exclude
2. Make that user go offline
3. The user still shows up in /baltop and /balancetop

**Expected behavior**  
The user to be hidden from /baltop and /balancetop even when offline

**Screenshots**

**Comment by pop4959** [comment]
The behaviour of permissions for offline players depends on your permission plugin. Generally, permissions cannot be checked for players who are offline.
