### ISSUE TITLE
The /unlimited and /unl command does not work for arrows

### ISSUE THREAD

**Issue by AMDBartek** [EssentialsX/Essentials#3006]
### Details

**Server files**

Server log: not provided due to not being necessary

EssentialsX config: https://gist.githubusercontent.com/AMD-Mario27639/51410838c4a3ddf16cf4f8b88003c02f/raw/fc8eb20d5107a5962308021918e5de08f8ca6bba/config.yml

**Description**  
When using the command “/unlimited arrow” or “/unl arrow” the arrows still run out when using them with a bow

**Steps to reproduce**  
1. Use the command “/unlimited arrow” or “/unl arrow”
2. Shoot the arrows using the bow
3. The arrows run out like normal

**Expected behavior**  
The arrows to be unlimited while using a bow

**Screenshots**

**Comment by AMDBartek** [comment]
@pop4959 I have realized that #3005 is a duplicate because of #2974 but I do not believe that this issue is a duplicate because it mentions that arrows don't work with bows while using the /unlimited arrow command and not fireworks.

**Comment by pop4959** [comment]
It is still a duplicate because they are the same bug. Please comment about it on the other issue thread so that the discussion is not split. Thanks :smiley:
