### ISSUE TITLE
VIPs cannot fly even though they have perms.

### ISSUE THREAD

**Issue by coolpringles** [EssentialsX/Essentials#3007]
I set a friend's rank to VIP (through PermissionsEX) and VIPs have the fly permission on my server. I can do the command (I have permission '*') but he can't. It says "Flying is not allowed in this area."

Please help.

**Comment by coolpringles** [comment]
I appears that the /fly command only works on ops. I gave VIP the permission essentials.fly. Did I give them the wrong permission?

**Comment by JasonHorkles** [comment]
You must be using some other plugin that's blocking the fly because I don't think that's an essentials message

**Comment by coolpringles** [comment]
The plugins I have are:
LeakParkour, ColoredSigns, FastAsyncWorldEdit, VoidWorld, PermissionsEx, PerWorldPlugins, PlugMan, CrispyDisguise, ViaVersion, Vault, Multiverse-Core, ProtocolLib, HubBasics, Citizens, WorldEdit, Essentials, Multiverse-Inventories, EssentialsChat, CreateYourOwnMenus, HolographicDisplays, Multiverse-Portals, SuperVanish, WorldGuard, CitizensCMD, ASkyBlock

Sorry, I'm a noob when it comes to server managing.

**Comment by JasonHorkles** [comment]
If you actually had a modern permission plugin (like LuckPerms) you could find out what the missing permission is

**Comment by coolpringles** [comment]
I once tried LuckPerms and found it extremely confusing. Is there any other permission plugins that are simple like PEX?

**Comment by pop4959** [comment]
PEX should not be an issue in this particular case (although I recommend switching since it hasn't been supported in years), but it's likely that your configuration is simply incorrect. Check the permissions [here](https://essinfo.xeya.me/permissions.html) and see if you're missing anything. Otherwise, perhaps try the [Discord server](https://discord.gg/PHpuzZS) for advice from other Essentials users.

**Comment by JasonHorkles** [comment]
https://youtu.be/uYg_bOEQFIk use this to help you set up LuckPerms. It's going to be the best one in the long run, and once you understand it then it'll be easier to use.

**Comment by coolpringles** [comment]
Alright, well I'll give LuckPerms a try and report back if the issue persists.
Thanks! =)
Edit: Seems there's an option to migrate from PEX to LuckPerms which helps a lot.

**Comment by coolpringles** [comment]
After switching to LuckPerms, deop-ing myself and setting my rank to VIP, the /fly command works in one world, but not the hub world, which is the default "world" folder. Maybe it's worldguard.

**Comment by coolpringles** [comment]
I've looked it up and there doesn't appear to be any flags for worldguard that allow or disallow flying on my version, 6.1. If anyone can re-open the issue, please do. Any further help would be appreciated!

**Comment by JasonHorkles** [comment]
GitHub isn't the best place for support, so you should go to the [LuckPerms Discord server](https://discord.gg/LuckPerms) for support on permission stuff.

**Comment by coolpringles** [comment]
I'm not sure this has anything to do with the permission though. It might be spawn protection, the region you can't fly in is called "spawn".

**Comment by JasonHorkles** [comment]
You can get [WorldGuardExtraFlags ](https://www.spigotmc.org/resources/worldguard-extra-flags.4823/)to possibly allow fly, but again this isn't the place for support, especially if it's not Essentials

**Comment by coolpringles** [comment]
Well, thanks for all the help. Much appreciated.
(after allowing flag fly, it still doesn't work, now everyone can fly)
Edit 11th February: The problem was too simple. I feel so dumb for not seeing it. /fly is not one of the allowed-cmds in the spawn region for non-ops.
