### ISSUE TITLE
I need some help with the EssentialsX /list command

### ISSUE THREAD

**Issue by AMDBartek** [EssentialsX/Essentials#3008]
### Help request

**Server files**

EssentialsX config: https://gist.githubusercontent.com/AMDBartek/6fdc97e6c241252f15efcf965be9ab52/raw/8b9fd52669607f646d301f1a29a65cf34aa19ca8/config.yml

Server log: Not required as no errors or warnings occurred

**Output of /ess version**

Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
EssentialsX version: 2.17.1.60
LuckPerms version: 5.0.39
PlaceholderAPI version: 2.10.4
Vault version: 1.7.2-b107
EssentialsXProtect version: 2.17.1.60
EssentialsXChat version: 2.17.1.60
EssentialsXSpawn version: 2.17.1.60

**Problem**
I have encountered a problem with the EssentialsX /list command where when I have vanished with SuperVanish and execute the /list command this is what it outputs (even for players with the essentials.list.hidden permission set to false): 

There are 1/1 out of maximum 35 players online.
Players: [Mod] User, [HIDDEN]Mario27639

**What I have tried**
Applying the essentials.list.hidden false to the player/group permission with LuckPerms

**Screenshots**

**Comment by pop4959** [comment]
Do the players in question also have the permission `essentials.vanish.interact`? If they do, this may additionally cause them to be able to see someone that is vanished.

**Comment by AMDBartek** [comment]
@pop4959 Thank you, that has fixed the issue.
