### ISSUE TITLE
Java API: get player mute state

### ISSUE THREAD

**Issue by car1ot** [EssentialsX/Essentials#3009]
### Information

Full output of `/ess version`:

**Server log:** 

**EssentialsX config** 

### Help request

**Problem**
Java API: How to get player mute state (is player muted <true/false> or mute expires time)?

**What I have tried**
Importing EssentialsX and looking around .api

**Screenshots**
No screenshots

**Comment by pop4959** [comment]
Essentials -> getUser -> isMuted

**Comment by quiquelhappy** [comment]
Hello.
Is there any event for handling this change automatically without having to periodically check on the player mute status? Thank you

**Comment by triagonal** [comment]
> Hello.
> Is there any event for handling this change automatically without having to periodically check on the player mute status? Thank you

You can use [MuteStatusChangeEvent](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/java/net/ess3/api/events/MuteStatusChangeEvent.java) for this purpose. You can also see all available events at https://github.com/EssentialsX/Essentials/tree/2.x/Essentials/src/main/java/net/ess3/api/events and https://github.com/EssentialsX/Essentials/tree/2.x/Essentials/src/main/java/net/essentialsx/api/v2/events
