### ISSUE TITLE
[Essentials] Permissions Lag Notice

### ISSUE THREAD

**Issue by AdminZero** [EssentialsX/Essentials#301]
Server: Spigot-1.8.8
EssentialsX: 2.0.1-b226
Plugin Report: http://timings.aikar.co/?url=13765670
Errors Log: http://pastebin.com/vnvbWrSL

Can you please look into fixing this issue or tell me what i possibly might need to fix? 

Thanks

**Comment by vemacs** [comment]
This is a problem with bPermissions returning groups slowly via Vault. Update to the latest beta, and contact them about this issue.

**Comment by AdminZero** [comment]
K thanks
