### ISSUE TITLE
Add "Used memory" in the /gc command

### ISSUE THREAD

**Issue by AMDBartek** [EssentialsX/Essentials#3011]
### Feature request

**Feature description**
Add the amount of memory (RAM) that the server is using to the /gc command.

Example:

Uptime: 49 minutes 29 seconds
Current TPS = 19.72
Maximum memory: 910 MB.
Allocated memory: 861 MB.
Used memory: [Amount of used memory]
Free memory: 567 MB.
World "world": 441 chunks, 38 entities, 10 tiles.

**How the feature is useful**
It is useful for developers and staff on the server to see how much memory is being used by the server.

**Comment by pop4959** [comment]
Free = Allocated - Used

You should be able to eyeball it roughly, and the exact amount does not matter to most people. It looks like your server needs more RAM though, as that is not very much for 1.15.2.

**Comment by AMDBartek** [comment]
I still think that this would be a good addition as it eliminates the need for a separate plugin, yes you could eye-ball it but that is not always the most accurate way of calculating. I also think that it shouldn’t be difficult to implement (in my opinion) and I'm sure this would benefit some other people as well.

 (As for the low amount of allocated RAM it is because that server is for plugin testing/debugging only.)

**Comment by pop4959** [comment]
Then pull out a calculator, lol.

On a more serious note, if you are trying to use EssentialsX for more than just getting a rough estimate of your memory usage, you are probably doing something wrong. Try a real memory profiler, or if you want a plugin, perhaps something like [spark](https://www.spigotmc.org/resources/spark.57242/) would suit your fancy.

**Comment by AMDBartek** [comment]
Alright, thanks for the recommendation.
