### ISSUE TITLE
[1.15.2] EssentialsXXMPP Doesn't Seem to Work

### ISSUE THREAD

**Issue by syeare** [EssentialsX/Essentials#3012]
### Information

**Full output of `/ess version`**:
```
[13:50:16 INFO]: CONSOLE issued server command: /ess version
[13:50:16 INFO]: Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-102 (MC: 1.15.2)
[13:50:16 INFO]: EssentialsX version: 2.17.1.57
LuckPerms version: 5.0.70
Vault is not installed. Chat and permissions may not work.
```

Vault IS installed (version 1.7.2, listed to be compatible according to [this guide](https://www.spigotmc.org/wiki/spigot-1-15-plugin-compatibility-list/) ), but does not appear to be detected by EssentialsX. I do not think this is relevant to my issue, however, as there is a message where Essentials Economy hooks into Vault. It's just that EssX seems not to recognize that it's there. Look at this:
 ```
[13:50:07 INFO]: [Vault] [Vault][Economy] Essentials Economy hooked.
[13:50:07 INFO]: [Essentials] Using Vault based permissions (LuckPerms)
``` 

**Server log**: 
https://gist.github.com/syeare/291824fcdedfb63b6e13cc79cbaf0ac0

**EssentialsX config**: 
https://gist.github.com/syeare/25bf4e632457688b7ebae6c3f7141fd8

**EssentialsXXMPP config**:
https://gist.github.com/syeare/4908f60ebd634c8d80beb06d9481f115

### Details

**Description**  

I am running Paper spigot version 102, MC 1.15.2. Don't know if it (the XMPP plug-in) connects successfully to the XMPP server or not, it just says "connecting" and says nothing related before or after. Every other (EssentialsX) plug-in works except for this, and I don't have anything else that affects EssentialsX.

**Steps to reproduce**  

Literally just try using the XMPP plug-in.

**Expected behavior**  

I wanted to receive some type of confirmation that it has connected successfully to the XMPP server using myaccount@example.com, but I got nothing. I have the proper permissions and I am using LuckPerms, but using `/xmpp inGameUsername messageHere` does nothing, they receive nothing (yeah, they had permission to do `/setxmpp addresshere`, but it still doesn't work). I know all the details in the XMPP config are correct because they work in "normal" XMPP clients, but it doesn't seem to work in the server.

**Screenshots**
![image](https://user-images.githubusercontent.com/11952166/74476454-f7dc4b00-4e6e-11ea-9c41-e63ae280b5b9.png)

**Comment by AMDBartek** [comment]
To fix the /ess version Vault issue upgrade EssentialsX to the latest version. Vault functionality is unaffected but the /ess version command will say that "Vault isn't installed".

**Comment by syeare** [comment]
> 
> 
> To fix the /ess version Vault issue upgrade EssentialsX to the latest version. Vault functionality is unaffected but the /ess version command will say that "Vault isn't installed".

Wut? EssX IS the latest version though. Anyway, that doesn't really concern me as much as the XMPP issue.

**Comment by pop4959** [comment]
He just meant that there has been a fix for #2988 so downloading the latest version will probably fix that displaying incorrectly.

**Comment by mdcfe** [comment]
Could you post a **full** server startup log?

**Comment by pop4959** [comment]
Closing due to lack of response. Can re-open if further details become available as requested.
