### ISSUE TITLE
custom_items.yml doesn't work on my server. Was told on discord to post here :D

### ISSUE THREAD

**Issue by MiniTheMB** [EssentialsX/Essentials#3018]
### Information

**Full output of `/ess version`**:
Server version: 1.14.4-R0.1-SNAPSHOT git-Paper-243 (MC: 1.14.4)
EssentialsX version: 1.17.1.58
LuckPerms version: 4.4.1
EssentialsXSpawn version: 1.17.1.60
(Vault is not installed..)
```
Console below  v
```

**Server log**: https://gist.github.com/MiniTheMB/d0c60c6a442835e1fc1965f67f353cee

**EssentialsX config**: https://gist.github.com/MiniTheMB/20992a469e4e60116f8d9c979568a10a

### Details

**Description**  
When i type: /give Mini_The_MB bluepaint it doesn't give me anything, and the chat also says nothing.

**Steps to reproduce**  
I typed /give Mini_The_MB bluepaint

**Expected behavior**  
I expected the custom_items.yml to give me blue_dye. It's the same for snad: sand and breakfast: cooked_porkchop.. A link to my file, in case you'll need a look: I https://gist.github.com/MiniTheMB/3e216c9e8bce3d5c17c1be73193d3f16 I haven't changed anything in the file, this is what essentials give me.

**Screenshots**  
My chat don't say anything, and the console is up above :D

**Comment by triagonal** [comment]
I can reproduce this bug on the following:
```
[01:57:38 INFO]: Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-98 (MC: 1.15.2)
[01:57:38 INFO]: EssentialsX version: 2.17.1.61
[01:57:38 INFO]: LuckPerms version: 5.0.39
[01:57:38 INFO]: Vault version: 1.7.2-b107
```
Below is the same error output with debug enabled:
https://gist.github.com/triagonal/0b00acc7d78b847800e22b991e6e2194

It appears that the custom item resolution process triggers an infinite loop which causes the bug to occur.

**Comment by mdcfe** [comment]
This has now been fixed - you can download the latest version from the [build server](https://ci.ender.zone/job/EssentialsX).
