### ISSUE TITLE
The /storm [worldname] and /sun [worldname] require an unnecessary argument when used in console.

### ISSUE THREAD

**Issue by AMDBartek** [EssentialsX/Essentials#3020]
### Help request/Bug report (I am not sure)

**Problem**
When I use the /sun [worldname] or /storm [worldname] command it still wants me to specify the type of weather to change to.

The syntax for /storm is: When running from console, usage is: /storm <world> <storm/sun> [duration]

The syntax for /sun is: When running from console, usage is: /sun <world> <storm/sun> [duration]

The <storm/sun> argument is unnecessary because already specify the type of weather depending on what command you use.

**What I have tried**
Adding the <storm/sun> argument which fixes the issue but this should not be necessary.

**Screenshots**
![Console](https://user-images.githubusercontent.com/46637209/74755882-b29f8b00-526b-11ea-82f2-fa97987f63d0.PNG)

**Comment by pop4959** [comment]
Like issue to #2989.
