### ISSUE TITLE
Playtime

### ISSUE THREAD

**Issue by Boastful1353** [EssentialsX/Essentials#3023]
### Feature request

**Feature description**

/playtime command that displays a players total online time on the server
**How the feature is useful**

This information is somewhat available in the statistics section of the pause menu but i have seen instances of it being reset and inaccurate. Essentials already displays this information with /whois but if it could be displayed by its self with /playtime so that we can allow players to check their own playtime it would be helpful.

**Comment by mdcfe** [comment]
EssentialsX reads and displays exactly the same playtime data as the in-game statistics menus do. If the statistics menu resets, it's an issue with either plugins or your server software and will also reset the playtime in EssentialsX's `/whois`.

We're not going to add a command to duplicate a feature that's already part of both EssentialsX and Minecraft itself.
