### ISSUE TITLE
Economy Console Error

### ISSUE THREAD

**Issue by LucidAPs** [EssentialsX/Essentials#3030]
Minecraft : 1.15.2
Paper Build : 118
EssentialsX Bundle : 2.17.2.0

https://pastebin.com/vZ0X76UK

**Comment by pop4959** [comment]
Please properly fill out the issue template and provide information on how to reproduce this issue, if you want us to investigate it further. Although, I will say that based on the error, this looks to be a bug with QuickShop passing null as the player name (which is illegal behaviour). You should ask that plugin's author instead.

Closing for now, but can re-open if you can reproduce this issue without QuickShop and can provide all of the required information.
