### ISSUE TITLE
A /warn command where you can warn a player

### ISSUE THREAD

**Issue by AMDBartek** [EssentialsX/Essentials#3037]
### Feature request

**Feature description**
A /warn command where you could warn a player, for example, if they break a rule you could warn them with the /warn command. Also, it says how many times a player has been warned.

It could show something like this in their chat:

Warning: [Warning reason]

**How the feature is useful**
When a player is breaking a rule an admin/moderator could give them a warning.

**Comment by pop4959** [comment]
I don't really see how this is much more useful than just messaging the player a warning or mailing them. Also, there are plenty of plugins which provide more elaborate moderation tools than Essentials (which just has a basic /mute /kick /ban).
