### ISSUE TITLE
/fireball trident - Allows players to get free tridents

### ISSUE THREAD

**Issue by MrButtersDEV** [EssentialsX/Essentials#3039]
Version:
```
27.02 13:34:32 [Server] Server thread/INFO Server version: 1.15.1-R0.1-SNAPSHOT git-Spigot-037559e-5c6b0dc (MC: 1.15.1)
27.02 13:34:32 [Server] Server thread/INFO EssentialsX version: 2.17.2.0
27.02 13:34:32 [Server] Server thread/INFO LuckPerms version: 5.0.39
27.02 13:34:32 [Server] Server thread/INFO PlaceholderAPI version: 2.9.2
27.02 13:34:32 [Server] Server thread/INFO Vault version: 1.7.2-b107
27.02 13:34:32 [Server] Server thread/INFO ChestShop version: 3.10-SNAPSHOT (build 149)
27.02 13:34:32 [Server] Server thread/INFO Citizens version: 2.0.26-SNAPSHOT (build 1790)
27.02 13:34:32 [Server] Server thread/INFO EssentialsXChat version: 2.17.2.0
27.02 13:34:32 [Server] Server thread/INFO EssentialsXSpawn version: 2.17.2.0
27.02 13:34:32 [Server] Server thread/INFO You are running an unsupported server version!
```

**Description**  
When someone runs /fireball trident a player can pick up the trident thrown.

**Steps to reproduce**  
/fireball trident

**Expected behavior**  
Should not allow a player to pick up a trident like one thrown by a mob.

**Comment by mdcfe** [comment]
I can't currently investigate this, but to work around this temporarily you can prevent players spawning arrows by negating the `essentials.fireball.arrow` and `essentials.fireball.trident` permissions.

**Comment by mdcfe** [comment]
Update: this is difficult to fix as Paper and Spigot have had various different APIs for tridents and arrows over the past few years. A fix should be coming shortly, but as mentioned above if you want to prevent spawning in unlimited arrows and tridents, disable the permissions listed above.

**Comment by mdcfe** [comment]
This is now fixed in the [latest build](https://essentialsx.cf/downloads.html).
