### ISSUE TITLE
Console error/warning

### ISSUE THREAD

**Issue by Sikatsu** [EssentialsX/Essentials#304]
Hello,

Within the console sometimes it shoots messages like these:

[13:05:27 WARN]: [Essentials] Using potentially blocking Bukkit UUID lookup for: sexylexy
[13:05:27 INFO]: zCydaz issued server command: /nick SexyLexy

What exactly does it mean?

**Comment by EvilOlaf** [comment]
https://github.com/drtshock/Essentials/issues/295 https://github.com/drtshock/Essentials/issues/294

**Comment by Sikatsu** [comment]
Well, my debug mode is turned to False. I'm using the latest devbuild from EssentialsX, so why exactly is it still showing these things?

**Comment by SupaHam** [comment]
What is the latest devbuild from EssentialsX, please give me the exact version from /ess reload.

**Comment by Sikatsu** [comment]
It shows up as #237. But if the messages can't go away, i just want to know
what it means. :p

Op wo 9 dec. 2015 16:40 schreef SupaHam notifications@github.com:

**Comment by SupaHam** [comment]
It means you aren't on build 237. Download [here](https://ci.drtshock.net/job/EssentialsX/lastSuccessfulBuild/artifact/Essentials/target/EssentialsX-2.0.1.jar).

**Comment by Sikatsu** [comment]
Is this even for real? Wow. This support. Do you want me to make a whole
video about it or something to prove i'm on that build? Damn, bullshit.

**Comment by mbax** [comment]
Prompt replies for support on a plugin for which you paid nothing? Wow. This support.

I'm going to quote what @SupaHam said earlier, hoping that you will follow his instructions so he can help you better:

> please give me the exact version from /ess reload.

Do that, and he can probably help you more.

**Comment by Sikatsu** [comment]
Yeah look i don't care anymore, i'm not plain stupid, i did that step. Besides that i wondered what it meant, instead if only getting rid of it.

I always support developers by paying, but with such replies i won't do that.

Anyways, he closed it, let's keep it that way.^^

**Comment by mbax** [comment]
You did not give him the exact version from /ess reload

You failed.

**Comment by Sikatsu** [comment]
Well i think mentioning 2.0.1 won't make sense. I mentioned that it is build 237.

Proof: http://prntscr.com/9cfsm2 

But forget about it.
