### ISSUE TITLE
Glitch Through Barrier Blocks With /TPA (bug)

### ISSUE THREAD

**Issue by TristonStuart** [EssentialsX/Essentials#3041]
### Information

[15:37:50 INFO]: Server version: 1.14.4-R0.1-SNAPSHOT git-Paper-243 (MC: 1.14.4)
[15:37:50 INFO]: EssentialsX version: 2.17.2.0
[15:37:50 INFO]: LuckPerms version: 5.0.79
[15:37:50 INFO]: Vault version: 1.7.2-b107
[15:37:50 INFO]: EssentialsXProtect version: 2.17.2.0
[15:37:50 INFO]: EssentialsXChat version: 2.17.2.0
[15:37:50 INFO]: EssentialsXSpawn version: 2.17.2.0

**Server log**: https://gist.github.com/TristonStuart/404ddc3c0d1b7634223d30d4eb54163b

**EssentialsX config**: https://gist.github.com/TristonStuart/d7852bc81fc9797ca74e6dc1dfce232e

### Details

**Description**  
Using /tpa you can glitch through barrier blocks.
It seems to work with OP and Non-OP players.
Works in survival but not in creative.

**Steps to reproduce**  
Stand over barrier block. Have some /tpa to you. Do /tpaccept.
They will then be teleported below the barrier block to the next full block.
Video : https://www.youtube.com/watch?v=jvlw2nqg0LA
(Note, Video Was On This Version : https://gist.github.com/TristonStuart/2624c9e2f9c8909522cf15612cbb8870
But It Works on Version Stated Above)

**Expected behavior**  
Be teleported ontop of barrier blocks.

**Screenshots**  
Video : https://www.youtube.com/watch?v=jvlw2nqg0LA

**Updates :**
*Works with /tp
*Barrier Blocks Considered Unsafe

**Comment by TristonStuart** [comment]
***This Also Works With /tp**

**Comment by pop4959** [comment]
This is intentional behaviour. By default, Essentials will only allow players to teleport on top of solid blocks. Barriers are not solid blocks, so Essentials' teleport safety feature will kick in. If you do not want this, you should set `teleport-safety` and `force-disable-teleport-safety` in the config accordingly. Also, if your problem is that players are able to access "restricted" areas, you should get another plugin for that. Essentials will not do this for you.

**Comment by TristonStuart** [comment]
There should be a setting for barrier blocks. For the means of my server I need teleport-safety and force-disable-teleport-safety to what I have them set as per my config I linked. If I change those values people will be able to glitch into factions bases. My problem is that I want to use barrier blocks for the decoration aspect but I can’t restrict tpa entirely. I have to use a different plugin to restrict execution of teleport commands in that specific area.
