### ISSUE TITLE
Kits: Timed item deletion

### ISSUE THREAD

**Issue by williumat** [EssentialsX/Essentials#3044]
### Feature request

**Feature description**
The addition of items in kits that disappear after a set amount of time. For example, if set up this way, players that acquire kit tools would lose those items after 10 minutes.

**How the feature is useful**
I hate when I find piles of unused starter kit items in chests all over my server, this would solve that issue. It would also allow players to have an easier start (e.g starter kit might have some diamond tools) but after a certain amount of time, they would lose those tools but keep the benefits of them. (Resources acquired using them)

**Comment by JRoy** [comment]
Can you uhhhh....fill out the issue template and describe what you want beyond 3 words?

**Comment by williumat** [comment]
I did but I guess it all got deleted.

Feature Description:
The ability to set timed deletion of items in a kit. For example 10 minutes after using kit tools the items from the kit will automatically be removed.

How the feature is useful: 
It helps remove the cluttering of unused starter kit items and allows players to get an easier start and acquire the benefits of a starter kit without getting free items. For example a starter kit could have diamond tools and this would make it easier for the player to get a good amount of early game resources. After say, an hour those diamond tools could be deleted but the player would still have those resources without having free diamond gear.

**Comment by pop4959** [comment]
@williumat I see what you did now, and I went ahead to fix your post for you. Just keep in mind that anything between the `<!---` and `--->` is a comment and does not appear in the post (it's a comment).

**Comment by pop4959** [comment]
I don't think this idea really works. The argument of finding unused piles of starter gear is a pretty shallow one, and ensuring that kit items are removed from a player after a certain period of time is not really feasible because players could just move items out of their inventory to avoid them being removed. It doesn't really make much sense, unfortunately.
