### ISSUE TITLE
Bed home.

### ISSUE THREAD

**Issue by En0tS** [EssentialsX/Essentials#3045]
### Information

**Full output of `/ess version`**:
![image](https://user-images.githubusercontent.com/36606833/75870621-e8b83f80-5e13-11ea-8443-0195f87ba118.png)

### Details

**Description**  
Player with permissions essentials.home.bed and essentials.sethome.bed can't use bed as home.
And I with all permissions (*) can't set home while clicking on bed.

**Steps to reproduce**  
Just try to click on bed, there is no "home set" message.

**Expected behavior**  
...

**Screenshots**  
-

**Comment by triagonal** [comment]
This has been fixed in EssentialsX versions 2.17.2.15 and above. Download the latest version
from https://essentialsx.cf/downloads.html.
