### ISSUE TITLE
Disables fly permission

### ISSUE THREAD

**Issue by Safsofx** [EssentialsX/Essentials#3046]
A feature or a permission when i permission settemp essentials.fly. when the time passes it toggles the /fly from the player so they couldn't stay at flight mode.
If it's possible to add this asap because i have 2 days to release my server.
Thanks.

**Comment by pop4959** [comment]
Fly disables itself when the player logs out / dies, unless they still have the safelogin permission.

**Comment by Safsofx** [comment]
Okay thanks.
