### ISSUE TITLE
Feature Requests - multiple misc features

### ISSUE THREAD

**Issue by Azulw** [EssentialsX/Essentials#305]
sorry for my bad english.
Hello,  Features Request:
1: More Economy things like:
- Taxes (for transactions and deposits)

2: More "Sudo" Features:
- add this (is very useful and poweful): 
  "/vssudo < p/c > < Permission > < Player > < CommandBase+Args > +vsign < More Args >"
  - what do this do?= open a sign or anvil  and that ask a text,  and next when player write a text the     command will be executed with the text who the player put
    - what do the <p/c>?= Player or console (which will execute the command)
    - what do <Permission>?= if player has the permission the command will be executed
    - what do <Player>?= the player name
    - what do <CommandsBase+Args>?= The Command and her arguments
      -what do +vsign?= is the part where the data are obtained from the signs or anvils and placed in   these part (+vsign are an arguments)
    - what do <more Args>?= more arguments or noting
    - Example1: /vssudo  p plot.add Azulw Plotme  add +vsign
    - Example2: /vssudo c custom.banperm Azulw ban +vsign +vsign
      (first +vsign are the name of the player, secod +vsign are the reason)
      -Why this are super Powerful?= This can be used for so many applications like create a amazing Smart gui whit another plugin, create a ultra customized things like a smart command blocks, Custom Commands whit that. create a GUIS For all whit any chest commands or like this.

3: Prefix, suffix, support in tablist, Player Name (the name above the player) will be afected whit the ./nick
- that be customizable

4: Leverage the new  powerful features of 1.8 like a titles, subtitles, actionbar.
for what ?
- For messages (in actionbar)
- For Notifications (in action bar like: payments, mail notifications, taxes, kit notifications like: time coldown and so moch more)
- All configurable And Compatible with other plugins

5: async Features, for best perforance, only load which is used.
- Features can be disabled or enabled

6: an extensible and flexible api-core.
- a api can allow store-Modiffy  information in the userdata
- a Json based Player data stored, or similar (that suport "stream-read-write")
- the data through  the API can be with async features
- An api That allow store data in the essentials dir.
- Not "cache world" (that help perforance but eat the ram) i suggest a temp-cache and get helped from the json or similar.
- More Options for /Kits, /give, /i (such as more NBT options)
- Only load the data who is used.
- clean code, less jar size.
## \- _

Thank for read ;) , I hope added that some of these improvements, ;)
have a good day.

**Comment by drtshock** [comment]
You're making it hard for us to be lazy.

**Comment by pop4959** [comment]
Please make this into separate requests. There is way too much here to keep track of, especially in a single issue.
