### ISSUE TITLE
Make kit commands required to be surrounded by quotes

### ISSUE THREAD

**Issue by JasonHorkles** [EssentialsX/Essentials#3053]
### Feature request

**Feature description**
Kit commands should be required to have quotes surrounding them to prevent issues with `:` and other characters that might make the kit invalid. For example, you'd have to do `"/title {PLAYER} title {""text"":""Kit Redeemed"",""color"":""green""}"` (quotation marks inside it can be doubled like in that command)

**How the feature is useful**
Those who want to use custom books or titles with a minecraft command will be able to do so easier since the current way it works can be complicated and confusing with kits becoming invalid.

**Comment by pop4959** [comment]
Have you tested putting single quotes around that instead of double quotes? This should already be possible in YAML.

**Comment by JasonHorkles** [comment]
Yeah using `'` seems to work actually haha

**Comment by pop4959** [comment]
@JasonHorkles Well, it is part of the YAML specification. 😛
