### ISSUE TITLE
There is a bug with the speed command where it doesn’t fully change language

### ISSUE THREAD

**Issue by AMDBartek** [EssentialsX/Essentials#3054]
### Details

**Output of /ess version**

Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-129 (MC: 1.15.2)
EssentialsX version: 2.17.2.3
LuckPerms version: 5.0.88
Vault version: 1.7.2-b107
EssentialsXProtect version: 2.17.2.3
EssentialsXChat version: 2.17.2.3
EssentialsXSpawn version: 2.17.2.3

**Description**  
When you use a language other than English with the speed command only the type of speed gets translated, for example, with Polish for /speed fly 10 [Username]: Set latanie speed to 10 for [Username]

It should be fully translated.

**Steps to reproduce**  
1. Use the speed command
2. Only the speed type will be translated and the rest of the message will be in English

**Expected behavior**  
The message to be fully translated.

**Screenshots**
https://imgur.com/0mj0gEy

**Comment by pop4959** [comment]
This is not a bug. The polish translation is missing for that message. You can contribute by helping translate it at <https://crowdin.com/project/essentialsx-official>.
