### ISSUE TITLE
/top [Username] and /repair [Username] all|hand does not work

### ISSUE THREAD

**Issue by AMDBartek** [EssentialsX/Essentials#3056]
### Help request

**Output of /ess version**

Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-129 (MC: 1.15.2)
EssentialsX version: 2.17.2.3
LuckPerms version: 5.0.88
Vault version: 1.7.2-b107
EssentialsXProtect version: 2.17.2.3
EssentialsXChat version: 2.17.2.3
EssentialsXSpawn version: 2.17.2.3

**Problem**
/top [Username] and /repair [Username] all|hand does not work.

**What I have tried**
Using the sudo command but the player has to have the permission, which is inconvenient.

**Screenshots**

**Comment by pop4959** [comment]
This is not a bug. It is intentional. Those commands can only be used by the player (or with sudo if they do have permission).
