### ISSUE TITLE
Nickname Color Codes broken

### ISSUE THREAD

**Issue by Neeonn** [EssentialsX/Essentials#3059]
**Full output of `/ess version`**:

```
> [22:38:58 INFO]: Server version: 1.8.8-R0.1-SNAPSHOT git-PaperSpigot-5e57ea3 (MC: 1.8.8)
> [22:38:58 INFO]: EssentialsX version: 2.17.2.3
> [22:38:58 INFO]: PlaceholderAPI version: 2.10.4
> [22:38:58 INFO]: LuckPerms version: 5.0.83
> [22:38:58 INFO]: Vault version: 1.7.2-b107
> [22:38:58 INFO]: Citizens version: 2.0.24-SNAPSHOT (build 1605)
> [22:38:58 INFO]: EssentialsXProtect version: 2.17.2.3
> [22:38:58 INFO]: EssentialsXSpawn version: 2.17.2.3
```

**Server log**: https://gist.github.com/Neeonn/2aeb4e7d2c87a7dc510fbe9ee472e827

**EssentialsX config**: https://gist.github.com/Neeonn/676d35f7e53b8f60f86642cf77f7ee8a

### Details

**Description**  
Formatting nicknames using & doesn't get converted, instead the nick gets shown as `&bExample` in the command output. This doesn't happen if the player is opped and/or has * perm.

**Steps to reproduce**  
Remove every permission from yourself, give yourself all nickname based permissions, try to set a nickname. You should see that the output is as `&bExample` instead of `Example` (in aqua).

**Expected behavior**  
`Example` (aqua) instead of `&bExample` when using `/nick` as a player. 

**Screenshots**  
Not necessary.

**Comment by Xeyame** [comment]
does the player have the `essentials.nick.color` permisison?

**Comment by Neeonn** [comment]
Yes.

**Comment by pop4959** [comment]
`This doesn't happen if the player is opped and/or has * perm.`

Clearly this is not a bug then, but a problem with your permissions. Please visit the [Discord support server](https://discord.gg/PHpuzZS) and see the EssentialsX channel to ask for help from others on how to fix your setup.
