### ISSUE TITLE
I have problems with the tpa command

### ISSUE THREAD

**Issue by Ahryzth** [EssentialsX/Essentials#3071]
**Problem**

Player1 when he sends the tpa command is fine, player2 receives it, but when he puts the / tpaccept command in the chat he comes out that he has no request sent. if you can help me I would really appreciate it.

**What I have tried**

What I have tried is to put the permissions back in the luck perms plugin, but even so I get the message that no requests have arrived.

**Screenshots**

![image](https://user-images.githubusercontent.com/61889670/76689435-939adb80-6614-11ea-9dbe-f08c1ca08304.png)

**Comment by pop4959** [comment]
Please visit the [Discord support server](https://discord.gg/PHpuzZS) and find the EssentialsX support channel for help. It's difficult to help you on Github for an issue like this, also especially since you have not properly filled out the issue template.
