### ISSUE TITLE
Is there any way to change type of spawnerminecart with /spawnmob?

### ISSUE THREAD

**Issue by UDPSendToFailed** [EssentialsX/Essentials#3073]
### Help request

**Problem**

As the title says. Is it possible to change spawnerminecart's type while using /spawnmob command?

**What I have tried**

/spawnmob spawnerminecart:chicken

I got pig spawner, doesn't matter what mob type I used.

**Comment by pop4959** [comment]
After considering this more, I think the answer is a hard no, since doing this would most likely involve NBT.
