### ISSUE TITLE
Config to Kick AFK after set player limit

### ISSUE THREAD

**Issue by JMCY26** [EssentialsX/Essentials#3074]
Can we have a configuration please where if players online exceed the set number, it checks for players AFK and kicks them with a configurable message?

enable-max-kick-afk: true/false
MaxPlayers-before-kick-AFK: 16
Kick Message: "You were kicked because the server is busy and you are AFK!"

This will check for players that are AFK once hitting 16 players online, kicking them with the set message.

A permission node to bypass being kicked if beyond player limit would go well with this too if possible.

This will help keep servers clear of AFK members if full/busy. **This still allows AFK timers to work but is an extra measure to go ontop.**

**Comment by mdcfe** [comment]
I'm not sure whether I agree with this in principle - players are accustomed to only being kicked after a certain period of time rather than at an unspecified time. However, I'm willing to leave this open to PR if someone wants to implement it.

**Comment by JMCY26** [comment]
Well it would be a optional configuration within the config, not required. There wouldn't be any nasty surprises, and the kick message would clearly state the reason that they were removed was because they are currently AFK and the player setting has been exceeded.

I would really appreciate this being added if someone could do it.

AFK timers are great during normal hours, but the ability to remove members that are AFK without manually removing/waiting for timers at busy hours where server limits are peaking would be really useful to keep availability.

**Comment by JMCY26** [comment]
> I'm not sure whether I agree with this in principle - players are accustomed to only being kicked after a certain period of time rather than at an unspecified time. However, I'm willing to leave this open to PR if someone wants to implement it.

If you can consider my reasoning I just commented, I'd really appreciate the implementation.

**Comment by JMCY26** [comment]
I've updated my original post to suggest an enable: true/false, with it being false by default.

**Comment by pop4959** [comment]
I think the appropriate fix for this is to reduce the AFK kick time, if you find that players are able to idle around longer than you would like them to.
