### ISSUE TITLE
Disable everything but the AFK feature

### ISSUE THREAD

**Issue by MeridianGH** [EssentialsX/Essentials#3075]
Hey guys!
I would like to disable every feature of EssentialsX except for the /afk command. Is this easily possible or do I have to create a list in the config that manually disables all commands?
In case you're wondering why I need this: I'm moderating a pure Vanilla server, without any cheats whatsoever. I don't want to go through every command permission to disable access to it, because even I shouldn't be allowed to cheat. Also I want to use the plugin BetterSleeping that utilizes the AFK feature of EssentialsX.

**Comment by pop4959** [comment]
Adjust the configuration accordingly and don't give players permission to anything except for AFK.

**Comment by MeridianGH** [comment]
How would I adjust the config? And I would like to avoid giving permissions if possible.
I found that I could use 'disabled-commands:' in the config, but I think I would have to type every command in there by hand. With every alias...

**Comment by pop4959** [comment]
The configuration files can be found in the Essentials plugin folder. You will also need a permission plugin such as [LuckPerms](https://luckperms.net/) to properly handle permissions (disabled-commands is old and not recommended). Basically everything you do not give permission for is automatically disabled.

Keep in mind that the GitHub issues here are mostly used for bug reports and feature requests. For basic plugin usage and questions feel free to join the [Discord support server](https://discord.gg/PHpuzZS) and visit the Essentials channels.

**Comment by MeridianGH** [comment]
Okay, thank you!
