### ISSUE TITLE
Fireball command permission. ( 2.17.2.12 )

### ISSUE THREAD

**Issue by AmazedMender16** [EssentialsX/Essentials#3078]
### Information

**Full output of `/ess version`**:

```
Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-137 (MC: 1.15.2)
EssentialsX version: 2.17.2.12
PlaceholderAPI version: 2.10.4
LuckPerms version: 5.0.16
Vault version: 1.7.2-b107
EssentialsXSpawn version: 2.17.2.12
```

### Details

**Description**  
essentials.fireball permission doesn't seem to be working, users with that permission still don't have permission for the command.

**Steps to reproduce**  
Start a server
Get a permission plugin, example luckperms
give the user permission for essentials.fireball

**Expected behavior**  
Users with the permission should have permission for the command

**Comment by mdcfe** [comment]
You need to add permissions for each type of projectile as well: `essentials.fireball.<fireball|small|large|arrow|skull|egg|snowball|expbottle|dragon|splashpotion|lingeringpotion|trident>`.
