### ISSUE TITLE
When players use /tpa <target>, the target player has no pending request even within the accept timeout

### ISSUE THREAD

**Issue by travilist** [EssentialsX/Essentials#3081]
### Information

Full output of `/ess version`:
[Sat, 21. Mar 2020 22:19:18 UTC INFO] Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-143 (MC: 1.15.2)
[Sat, 21. Mar 2020 22:19:18 UTC INFO] EssentialsX version: 2.17.2.9
[Sat, 21. Mar 2020 22:19:18 UTC INFO] LuckPerms version: 5.0.39
[Sat, 21. Mar 2020 22:19:18 UTC INFO] Vault version: 1.7.2-b107
[Sat, 21. Mar 2020 22:19:18 UTC INFO] Citizens version: 2.0.26-SNAPSHOT (build 1842)
[Sat, 21. Mar 2020 22:19:18 UTC INFO] EssentialsXProtect version: 2.17.2.9
[Sat, 21. Mar 2020 22:19:18 UTC INFO] EssentialsXChat version: 2.17.2.9
[Sat, 21. Mar 2020 22:19:18 UTC INFO] EssentialsXGeoIP version: 2.17.2.9
[Sat, 21. Mar 2020 22:19:18 UTC INFO] EssentialsXAntiBuild version: 2.17.2.9
[Sat, 21. Mar 2020 22:19:18 UTC INFO] EssentialsXSpawn version: 2.17.2.9

**Server log:** 
https://gist.github.com/anony55/6980a052e8a9cb47bc2e4e546130c57a

**EssentialsX config** 
https://gist.github.com/anony55/9fccbb426e0edb856f6fc991625f7e75

### Help request

**Problem**

When a player attempt to /tpa <target> and the other player executes /tpaccept or /tpyes, the target player receives an error reading "Error: You do not have a pending request." and no teleportation occurs.

**What I have tried**

I have tried messing with the permissions to make sure that all involved players have the correct permissions. I have looked through my EssentialsX config to verify that the system is set up correctly.

**Screenshots**

**Comment by pop4959** [comment]
This is not a known bug in Essentials at this time. I recommend resetting your configuration and removing other plugins temporarily to check if that helps. Otherwise, feel free to come on the [Discord server](https://discord.gg/PHpuzZS) and visit the support channel for help.
