### ISSUE TITLE
Method to receive message from another plugin to ignore essentials.sleepingignored permission

### ISSUE THREAD

**Issue by JoelGodOfwar** [EssentialsX/Essentials#3082]
### Feature request

**Feature description**
Method to receive a message from another plugin to ignore essentials.sleepingignored permission, whether a player has it or not.

**How the feature is useful**
This permission conflicts with one of my plugins, and because a lot of admins like to give * permissions, it would be nice if a message could tell Essentials to ignore that permission. (essentials.sleepingignored)

**Comment by Xeyame** [comment]
Aren't you the author of that single player sleep plugin? Anyways Yea i agree we should implement this, but for now you could also look into using the permission plugin's api, and server owners shouldn't be giving * anyway. Litte rant that is so true from mbaxter :) :
![afbeelding](https://user-images.githubusercontent.com/34656654/77250120-0116bf80-6c46-11ea-850a-0653a57d803e.png)

**Comment by mdcfe** [comment]
We recommend users set up their permissions properly (ie not using wildcards). You should inform your users in your plugin's setup guide to not use wildcards or to deny the `essentials.sleepingignored` permission.

**Comment by pop4959** [comment]
In addition to what md mentioned, this issue has been partially alleviated with #3141, which no longer makes `essentials.sleepingignored` a default permission for OPs.
