### ISSUE TITLE
Localized command descriptions?

### ISSUE THREAD

**Issue by emanuele3d** [EssentialsX/Essentials#3083]
### Information

Full output of `/ess version`:

[22-03-2020 17:39:48] EssentialsX Version: 2.17.1.0
[22-03-2020 17:39:48] LuckPerms Version: 5.0.100
[22-03-2020 17:39:48] Vault ist nicht installiert. Der Chat und die Rechte knnten nicht funktionieren.

### Help request

Hi there, thank you for your work on EssentialsX: your projects delivers a lot of very useful functionality for admins and users.

I am in the processing of setting up a Spigot 1.14.4 MC server for the children of our neighborhood, to help a little in these unusual pandemical times. Having the chance to roam freely in a huge 3d (multi)world if you are forced to stay home and isolate when it rains or if full curfew is enacted, will be useful for the spirit, I am sure.

We are located in Switzerland in a German-speaking Canton. I set EssentialsX locale to "de" in its config.yml and I can see the result, i.e. in the ouput of /ess version above.

As far as I can see however, the descriptions of commands such as /afk or /tpa all remain in English, even those seemingly provided by EssentialsX.  Even changing the language of the client doesn't change the outcome. Is this the expected behaviour? And if so, is there any resource on how to change the description of those commands?

Thank you in advance for your help.

Kind regards,

Manu

**Comment by pop4959** [comment]
The command descriptions are located in the plugin.yml file inside the EssentialsX jar. I don't think there is currently a way to change them except for editing the file inside the jar.

**Comment by emanuele3d** [comment]
So, to switch languages one would literally have to swap jars? Or is the file in the jar multi-language-capable?

**Comment by pop4959** [comment]
@emanuele3d They're located in the plugin.yml file. As with most plugins, the file is written in English and Spigot uses this file when looking for command syntax and description. Some people have had luck editing it directly from inside the jar, which may be difficult depending on how savvy you are.

**Comment by emanuele3d** [comment]
Ok, thank you for letting me know @pop4959. I'll close the issue as my question have been answered. Thank you again. =)
