### ISSUE TITLE
A way to toggle receiving payment from others

### ISSUE THREAD

**Issue by AMDBartek** [EssentialsX/Essentials#3088]
**Feature description**
A command that allows you to toggle receiving payment from other players (for yourself or others).

**How the feature is useful**
The feature is useful if a player does not want to receive payment from others or an admin wants to stop a player from receiving payment.

**Comment by pop4959** [comment]
Closing as duplicate of #3087

**Comment by AMDBartek** [comment]
@pop4959 Yes I understand that the issue is a duplicate, but I made this issue to explain the request more thoroughly because #3087 had the `not enough info` tag and this would be a good feature to have.

**Comment by pop4959** [comment]
Please allow the other person to clarify it themselves, as their request can be re-opened (or they can open a new one). There is no reason for you to post on their behalf.

**Comment by AMDBartek** [comment]
Ok, sorry about that.
