### ISSUE TITLE
Sign won't work at EssentialsX-2.17.2.12.jar, please help!

### ISSUE THREAD

**Issue by agungwrdn** [EssentialsX/Essentials#3089]
### Information

Full output of `/ess version`:

**Server log:** 
https://gist.github.com/agungwrdn/fddfbe48e84a2c2d5342c92a46bec69a

**EssentialsX config** 
https://gist.github.com/agungwrdn/3df4ef1a8f5a0f4919403d2a6e196bbc
### Help request

**Problem**
sign buy etc. won't working

**What I have tried**
change config.yml remove #

**Screenshots**
https://ibb.co/ZY76dBY

**Comment by JRoy** [comment]
Do you have the proper permissions & did you actually reload the config?

**Comment by pop4959** [comment]
Try capital 'B'. Make sure they have proper permissions, and restart the server. Also read: <https://wiki.mc-ess.net/wiki/Sign_Tutorial#Buy_Sign>. If that doesn't work join the [Discord server](https://discord.gg/PHpuzZS) and ask in the Essentials channel for help.

**Comment by agungwrdn** [comment]
> Do you have the proper permissions & did you actually reload the config?
how give permission for sign?

**Comment by agungwrdn** [comment]
> Try capital 'B'. Make sure they have proper permissions, and restart the server. Also read: https://wiki.mc-ess.net/wiki/Sign_Tutorial#Buy_Sign. If that doesn't work join the [Discord server](https://discord.gg/PHpuzZS) and ask in the Essentials channel for help.

i've already for write capital but auto change to lowercase.
