### ISSUE TITLE
Nickname code blacklist, code limits, and exp collecting option.

### ISSUE THREAD

**Issue by BradyMitch** [EssentialsX/Essentials#309]
Suggestions:
1) Blacklist in config for color and formatting codes that can't be used in /nick
2) Limits on how many different color and formatting codes can be used with /nick
3) Toggle if exp orbs drop or if experience goes straight to the player.

**Comment by drtshock** [comment]
1 and 2 just seem unnecessary.
3 seems like the job of another plugin.

**Comment by BradyMitch** [comment]
Okay, but for 1 it would block players being able to add colors like black that would be hard to see in chat, and dark red which is often associated with admins.

**Comment by mdcfe** [comment]
Related PR for 1: #1441 
Closing as 2 and 3 are unlikely to get implemented and 1 is a duplicate of #187.

**Comment by mdcfe** [comment]
...actually closing this time.
