### ISSUE TITLE
Reset /speed on world change

### ISSUE THREAD

**Issue by Giorgis20** [EssentialsX/Essentials#3090]
### Feature request
Reset /speed on world change

**Feature description**

When someone teleports to another worlds they should have their /speed reset back to the default

**How the feature is useful**

If a server is running in non-Bungee mode, has multiple minigames on one server and players have permission to use /speed only in one world (for example Creative Plots), the speed should be reset when they teleport to another world in order to avoid cheating in other minigames/gamemodes, such as KitBatte

**Comment by pop4959** [comment]
This feature is already in Essentials:

```yml
# When a player changes world, should we reset their speed according to their permissions?
# This resets the player's speed to the default if they don't have essentials.speed.
# If the player doesn't have essentials.speed.bypass, this resets their speed to the maximum specified above.
world-change-speed-reset: true
```
