### ISSUE TITLE
Better sell item amount for signs

### ISSUE THREAD

**Issue by corentingosselin** [EssentialsX/Essentials#3093]
### Feature request

**Feature description**
Sneak + left or right click can sell everything inside the inventory not just 1 stack

**How the feature is useful**
Faster for players when you have to sell thousand of items

**Comment by pop4959** [comment]
Don't feel like this is necessary, since you could just use `/sell`, or also alternatively increase the amount sold per sign. Plus, I feel like the UX of this would be a disaster.
