### ISSUE TITLE
Give suspicious stew with effects using /item command

### ISSUE THREAD

**Issue by c0wg0d** [EssentialsX/Essentials#3096]
### Feature request

**Feature description**

Add suspicious stew to /item command with effect.

For example:
/i suspicious_stew 1 effect:blindness

https://minecraft.gamepedia.com/Suspicious_Stew/Effects

Allium	Fire Resistance	2s	4s
Azure Bluet	Blindness	6s	8s
Blue Orchid
Dandelion	Saturation	?	0.35s
Cornflower	Jump Boost	4s	6s
Lily of the Valley	Poison	10s	12s
Oxeye Daisy	Regeneration	6s	8s
Poppy	Night Vision	4s	5s
Tulips	Weakness	7s	9s
Wither Rose	Wither	6s	8s

**How the feature is useful**

I can never remember how to spawn it in with the vanilla Minecraft /give command, and it would be useful if EssentialsX supported it.

**Comment by JRoy** [comment]
Essentials' /give supports NBT data. `/give <player> <item> <amount> <nbt>` Please use that.
