### ISSUE TITLE
Createkit command does not save book metadata

### ISSUE THREAD

**Issue by JustOneMoreBlock** [EssentialsX/Essentials#31]
Hello,

I've tested your /createkit command and I've been wanting this as a plugin for ages and now it's in a fork of Essentials, that's a plus. Good work!

Works on almost everything except for books and I'm not sure if this is something you can fix.

After creating a book with same text and adding it as kit. It saves the title and author just fine. However the books says.
- Invalid book tag *

I know there are plugins that can read books and convert them to text, so I'm pretty sure this could be possible using the books feature in Essentials.

**Comment by drtshock** [comment]
Yes :( I never added that and was waiting for someone to notice. The book code is kinda meh and I just wanted to get it out.

This is definitely needed though.

**Comment by Kakifrucht** [comment]
+1, would be nice if the 'book:' tag was supported.

**Comment by Kakifrucht** [comment]
You can use the command function to give the kit though!

**Comment by chillerkraft** [comment]
BUMP :)

**Comment by ShameMate** [comment]
Any idea when this is going to get added?

**Comment by ghost** [comment]
@ShameMate in the mean time, you could use a kit command to give the player the book

**Comment by ShameMate** [comment]
> @ShameMate in the mean time, you could use a kit command to give the player the book

I'm using /kitcreate <name> <cooldown>

It then gives the error " invalid book tag" when opening the book

**Comment by ghost** [comment]
Yeah. Instead, you could use a custom give command (using /minecraft:give, presumably) and put that command in the kit.

```yaml
my_cool_kit:
    - steak 1
    - /minecraft:give {USERNAME} book_with_nbt_data
```

something like that

**Comment by ShameMate** [comment]
Info:
    delay: 100
    items:
    - cookie 1
    - /minecraft:give {USERNAME} book_with_nbt_data  

That didn't work :/ How would i make it find the desired book i want players to be given tho?

**Comment by ghost** [comment]
Heh, `book_with_nbt_data` was just a placeholder for your book. You can generate a /give command with a site like https://minecraft.tools/en/book.php.

Sorry, should've been clearer :^)

**Comment by ShameMate** [comment]
> Heh, `book_with_nbt_data` was just a placeholder for your book. You can generate a /give command with a site like https://minecraft.tools/en/book.php.
> 
> Sorry, should've been clearer :^)

Sorry i'm stupid haha.

I just tried it, and it's still not working :/

I'm using the 1.15 code the website gave me.

/give @p written_book{pages:['["",{"text":"------------------- \\u0020 \\u0020 \\u0020"},{"text":"Belong Arena\'s","color":"light_purple"},{"text":"\\n \\u0020Offical Server Guide\\n-------------------\\n \\u0020 \\u0020 \\u0020 \\u0020 \\u0020Index\\n-------------------\\n\\n2-3: Useful Commands\\n4: Joining A Tribe\\n5-13: Factions\\n14: Protection\\n15: Ban\'s & Mute\'s","color":"reset"}]','["",{"text":" \\u0020 \\u0020Useful Commands","color":"dark_green"},{"text":"\\n-------------------\\n","color":"reset"},{"text":"/TPA","color":"red"},{"text":"\\nThis allows you to teleport to friends.\\n\\n","color":"reset"},{"text":"/SetHome","color":"red"},{"text":"\\nThis allows you to set a home. You can return with ","color":"reset"},{"text":"/Home","color":"red"},{"text":"\\n\\nYou can also reset your home with the above command.","color":"reset"}]','["",{"text":" \\u0020 \\u0020Useful Commands","color":"dark_green"},{"text":"\\n-------------------\\n","color":"reset"},{"text":"/MSG","color":"red"},{"text":"\\nThis command allows you to PM Friends, and they can reply with ","color":"reset"},{"text":"/R","color":"red"},{"text":"\\n\\n","color":"reset"},{"text":"/Spawn","color":"red"},{"text":"\\nUse this to return to Spawn, X:0 Z:0\\n\\n","color":"reset"},{"text":"/Help","color":"red"},{"text":" \\u0020/F Help","color":"red"},{"text":"\\nThis will help explain commands further.","color":"reset"}]','["",{"text":" \\u0020 \\u0020 Joining A Tribe","color":"red"},{"text":"\\n-------------------\\nAt Spawn you will be able to select which tribe you are from!\\n\\nSimply click on the sign!\\n\\nIf you aren\'t from one of our tribes, have a look on our website for the Arena closest to you!","color":"reset"}]','["",{"text":" \\u0020 \\u0020 \\u0020 \\u0020 Factions","color":"blue"},{"text":"\\n-------------------\\nA Faction is a Clan. Whether it\'s on your own, or with friends!\\n\\nAnyone can create a faction, and can also choose their enemy\'s & allys!\\n\\nNow let\'s talk about what a player means to a faction:","color":"reset"}]','["",{"text":" \\u0020 \\u0020 \\u0020 \\u0020 Factions","color":"blue"},{"text":"\\n-------------------\\nPlayers have \\"Power\\". This Power allows you to claim land and protect it from others.\\n\\n","color":"reset"},{"text":"Each player has \\"20 Claims\\"\\n1x Claim = \\n1x Chunk =\\n16x16Blocks","color":"red"}]','["",{"text":" \\u0020 \\u0020 \\u0020 \\u0020 Factions","color":"blue"},{"text":"\\n-------------------\\n","color":"reset"},{"text":"/F Create <Name>","color":"red"},{"text":"\\nThis allows you to create your Faction.\\n\\n","color":"reset"},{"text":"/F Who/Show <Name>","color":"red"},{"text":"\\nThis tells you all the info about that Player/Faction\\n\\n","color":"reset"},{"text":"/F Tag <Name>","color":"red"},{"text":"\\nUse this to change your Factions name!","color":"reset"}]','["",{"text":" \\u0020 \\u0020 \\u0020 \\u0020 Factions","color":"blue"},{"text":"\\n-------------------\\n","color":"reset"},{"text":"/F Invite <Name>","color":"red"},{"text":"\\nTo invite a player to the Faction\\n\\n","color":"reset"},{"text":"/F Join <Name>","color":"red"},{"text":"\\nTo join that desired Faction\\n\\n","color":"reset"},{"text":"/F Kick <Name>","color":"red"},{"text":"\\nTo Remove a player from your Faction","color":"reset"}]','["",{"text":" \\u0020 \\u0020 \\u0020 \\u0020 Factions","color":"blue"},{"text":"\\n-------------------\\n","color":"reset"},{"text":"/F List","color":"red"},{"text":"\\nList all the Factions on the server!\\n\\n","color":"reset"},{"text":"/F Map","color":"red"},{"text":"\\nSee who owns Land near you!\\n\\n","color":"reset"},{"text":"/F Desc","color":"red"},{"text":"\\nUpdate your Factions description!","color":"reset"}]','["",{"text":" \\u0020 \\u0020 \\u0020 \\u0020 Factions","color":"blue"},{"text":"\\n-------------------\\n","color":"reset"},{"text":"/F Sethome","color":"red"},{"text":"\\nSet a home for your whole faction to use!\\n\\n","color":"reset"},{"text":"/F SetWarp <Name>","color":"red"},{"text":"\\nCreate a TP Location for your Faction!\\n","color":"reset"},{"text":"(Each Faction Has 5x)","color":"red"},{"text":"\\n\\n","color":"reset"},{"text":"/F Warps","color":"red"},{"text":"\\nView the warps your Faction has set!","color":"reset"}]','["",{"text":" \\u0020 \\u0020 \\u0020 \\u0020 Factions","color":"blue"},{"text":"\\n-------------------\\n","color":"reset"},{"text":"/F Claim <radius>","color":"red"},{"text":"\\nThis will claim 1 chunk.\\nIf you enter a radius, this claim\'s a square.\\nNo one outside of your faction can edit this land.\\n\\n","color":"reset"},{"text":"/F Unclaim","color":"red"},{"text":"\\nThis will unclaim the land you have selected.","color":"reset"}]','["",{"text":" \\u0020 \\u0020 \\u0020 \\u0020 Factions","color":"blue"},{"text":"\\n-------------------\\n","color":"reset"},{"text":"/F SeeChunk","color":"red"},{"text":"\\nThis command will allow you to see what chunk you are in! This is done by 4 Red Pillars.\\n\\n","color":"reset"},{"text":"/F Fly","color":"red"},{"text":"\\nThis allows you to Fly in your claimed land! Use the command to Toggle it on and off!","color":"reset"}]','["",{"text":" \\u0020 \\u0020 \\u0020 \\u0020 Factions","color":"blue"},{"text":"\\n-------------------\\n","color":"reset"},{"text":"/F Perms","color":"red"},{"text":"\\nYou can edit, everything to do with your faction! Like ranks, enemies, etc.\\n\\n","color":"reset"},{"text":"/F Mod <Name>\\n/F CoLeader <Name>","color":"red"},{"text":"\\nThis will give players a higher rank in your Faction.","color":"reset"}]','["",{"text":" \\u0020 \\u0020 \\u0020 \\u0020Protection","color":"dark_green"},{"text":"\\n-------------------\\nYou can lock your chests & doors by placing a Sign on them.\\n\\nThis makes it so other players cannot open them, except you. \\n\\nYou can add other players by using another sign!","color":"reset"}]','["",{"text":" \\u0020 \\u0020 Ban\'s & Mute\'s","color":"red"},{"text":"\\n-------------------\\nIf you have any issue with Ban\'s & Mute\'s on the server, please raise this on our Discord.\\n\\nYou can do this by messaging in the Minecraft section, or DMing and Admin.","color":"reset"}]'],title:"Belong's Guide",author:ShameMate}

Tried the command it gave me, and the one you gave me :(

**Comment by ghost** [comment]
You'll need to append `/minecraft:` to the command, so it looks like `/minecraft:give @p written_book{nbt_stuff}`.

In the Essentials config, replace `@p` with `{USERNAME}` so it can use the player's username placeholder.

**Comment by ShameMate** [comment]
> You'll need to append `/minecraft:` to the command, so it looks like `/minecraft:give @p written_book{nbt_stuff}`.
> 
> In the Essentials config, replace `@p` with `{USERNAME}` so it can use the player's username placeholder.

Still not working xD

- /minecraft:give {USERNAME} written_book{pages:['["",{"text":"------------------- \\u0020 \\u0020 "},{"text":" Belong Arena\'s","color":"light_purple"},{"text":"\\n \\u0020Offical Server Guide\\n-------------------\\n \\u0020 \\u0020 \\u0020 \\u0020 \\u0020Index\\n-------------------\\n\\n2-3: Useful Commands\\n4: Joining A Tribe\\n5-13: Factions\\n14: Protection\\n15: Ban\'s & Mute\'s","color":"reset"}]','["",{"text":" \\u0020 \\u0020Useful Commands\\n-------------------\\n"},{"text":"/TPA","color":"red"},{"text":"\\nThis allows you to teleport to friends.\\n\\n","color":"reset"},{"text":"/SetHome","color":"red"},{"text":"\\nThis allows you to set a home. You can return with ","color":"reset"},{"text":"/Home","color":"red"},{"text":"\\n\\nYou can also reset your home with the above command.","color":"reset"}]','["",{"text":" \\u0020 \\u0020Useful Commands\\n-------------------\\n"},{"text":"/MSG","color":"red"},{"text":"\\nThis command allows you to PM Friends, and they can reply with ","color":"reset"},{"text":"/R","color":"red"},{"text":"\\n\\n","color":"reset"},{"text":"/Spawn","color":"red"},{"text":"\\nUse this to return to Spawn, X:0 Z:0\\n\\n","color":"reset"},{"text":"/Help \\u0020/F Help","color":"red"},{"text":"\\nThis will help explain commands further.","color":"reset"}]','["",{"text":" \\u0020 \\u0020 Joining A Tribe\\n-------------------\\nAt Spawn you will be able to select which tribe you are from!\\n\\n"},{"text":"Simply click on the sign!","color":"red"},{"text":"\\n\\nIf you aren\'t from one of our tribes, have a look on our website for the Arena closest to you!","color":"reset"}]','{"text":" \\u0020 \\u0020 \\u0020 \\u0020 Factions\\n-------------------\\nA Faction is a Clan. Whether it\'s on your own, or with friends!\\n\\nAnyone can create a faction, and can also choose their enemy\'s & allys!\\n\\nNow let\'s talk about what a player means to a faction:"}','["",{"text":" \\u0020 \\u0020 \\u0020 \\u0020 Factions\\n-------------------\\nPlayers have \\"Power\\". This Power allows you to claim land and protect it from others.\\n\\n"},{"text":"Each player has \\"20 Claims\\"\\n1x Claim = \\n1x Chunk =\\n16x16Blocks","color":"red"}]','["",{"text":" \\u0020 \\u0020 \\u0020 \\u0020 Factions\\n-------------------\\n"},{"text":"/F Create ","color":"red"},{"text":"\\nThis allows you to create your Faction.\\n\\n","color":"reset"},{"text":"/F Who/Show ","color":"red"},{"text":"\\nThis tells you all the info about that Player/Faction\\n\\n","color":"reset"},{"text":"/F Tag ","color":"red"},{"text":"\\nUse this to change your Factions name!","color":"reset"}]','["",{"text":" \\u0020 \\u0020 \\u0020 \\u0020 Factions\\n-------------------\\n"},{"text":"/F Invite ","color":"red"},{"text":"\\nTo invite a player to the Faction\\n\\n","color":"reset"},{"text":"/F Join ","color":"red"},{"text":"\\nTo join that desired Faction\\n\\n","color":"reset"},{"text":"/F Kick ","color":"red"},{"text":"\\nTo Remove a player from your Faction","color":"reset"}]','["",{"text":" \\u0020 \\u0020 \\u0020 \\u0020 Factions\\n-------------------\\n"},{"text":"/F List","color":"red"},{"text":"\\nList all the Factions on the server!\\n\\n","color":"reset"},{"text":"/F Map","color":"red"},{"text":"\\nSee who owns Land near you!\\n\\n","color":"reset"},{"text":"/F Desc","color":"red"},{"text":"\\nUpdate your Factions description!","color":"reset"}]','["",{"text":" \\u0020 \\u0020 \\u0020 \\u0020 Factions\\n-------------------\\n"},{"text":"/F Sethome","color":"red"},{"text":"\\nSet a home for your whole faction to use!\\n\\n","color":"reset"},{"text":"/F SetWarp ","color":"red"},{"text":"\\nCreate a TP Location for your Faction!\\n","color":"reset"},{"text":"(Each Faction Has 5x)","color":"red"},{"text":"\\n\\n","color":"reset"},{"text":"/F Warps","color":"red"},{"text":"\\nView the warps your Faction has set!","color":"reset"}]','["",{"text":" \\u0020 \\u0020 \\u0020 \\u0020 Factions\\n-------------------\\n"},{"text":"/F Claim ","color":"red"},{"text":"\\nThis will claim 1 chunk.\\nIf you enter a radius, this claim\'s a square.\\nNo one outside of your faction can edit this land.\\n\\n","color":"reset"},{"text":"/F Unclaim","color":"red"},{"text":"\\nThis will unclaim the land you have selected.","color":"reset"}]','["",{"text":" \\u0020 \\u0020 \\u0020 \\u0020 Factions\\n-------------------\\n"},{"text":"/F SeeChunk","color":"red"},{"text":"\\nThis command will allow you to see what chunk you are in! This is done by 4 Red Pillars.\\n\\n","color":"reset"},{"text":"/F Fly","color":"red"},{"text":"\\nThis allows you to Fly in your claimed land! Use the command to Toggle it on and off!","color":"reset"}]','["",{"text":" \\u0020 \\u0020 \\u0020 \\u0020 Factions\\n-------------------\\n"},{"text":"/F Perms","color":"red"},{"text":"\\nYou can edit, everything to do with your faction! Like ranks, enemies, etc.\\n\\n","color":"reset"},{"text":"/F Mod \\n/F CoLeader ","color":"red"},{"text":"\\nThis will give players a higher rank in your Faction.","color":"reset"}]','{"text":" \\u0020 \\u0020 \\u0020 \\u0020Protection\\n-------------------\\nYou can lock your chests & doors by placing a Sign on them.\\n\\nThis makes it so other players cannot open them, except you. \\n\\nYou can add other players by using another sign!"}','{"text":" \\u0020 \\u0020 Ban\'s & Mute\'s\\n-------------------\\nIf you have any issue with Ban\'s & Mute\'s on the server, please raise this on our Discord.\\n\\nYou can do this by messaging in the Minecraft section, or DMing and Admin."}'],title:"Belong's Guideawdwadawdawda",author:"http://minecraft.tools"}}
