### ISSUE TITLE
Exempt players from balancetop, even if offline

### ISSUE THREAD

**Issue by untuned** [EssentialsX/Essentials#3100]
### Feature request

**Feature description**
Add an entry in the UUID.yml userdata file to show if a player is exempt from the balancetop, such as `baltopexempt: true`. Example data file: https://gist.github.com/untuned/7051f673825dc61de9ae6f4c0444ba9e

**How the feature is useful**
If server owners don't want to show specific players having exorbitant amounts of economy, they can be hidden from the balancetop.

Based on issue #3004

**Comment by AMDBartek** [comment]
This would be an extremely useful feature to have. +1
