### ISSUE TITLE
Request to add two constructors to make MockBukkit compatible

### ISSUE THREAD

**Issue by Markyroson** [EssentialsX/Essentials#3105]
### Feature request

**Feature description**

Adding these two constructors to Essentials.java
````
public Essentials()
    {
        super();
    }

    protected Essentials(JavaPluginLoader loader, PluginDescriptionFile description, File dataFolder, File file)
    {
        super(loader, description, dataFolder, file);
    }
````

**How the feature is useful**

Allows the plugin to be loaded by [MockBukkit](https://github.com/seeseemelk/MockBukkit) so that plugins with Essentials as a dependency can be tested with the framework. It would be a nice ability for plugin developers to have.

**Comment by triagonal** [comment]
Implemented in #3106
