### ISSUE TITLE
[Feature Request] Cost to ANY server commands

### ISSUE THREAD

**Issue by manrovich** [EssentialsX/Essentials#3108]
### Feature request

**Feature description**
Cost to ANY server commands (using java regular expressions in config)

**How the feature is useful**
This feature is already in EssentialsX, but only for a limited set of commands.
This will make ANY service on the server paid (and integrate any plugin with the economy)
This will add a service market to the server (which is very lacking)
A similar plugin is available on the old version of minecraft for iConomy and is no longer supported. Here you can find more detailed information.
https://bukkit.org/threads/econ-command-iconomy-make-any-plugin-an-iconomy-plugin-1-4-7-1-5beta.19349/

**Comment by pop4959** [comment]
This sounds like something that should be its own plugin (if at all). Yes, Essentials does have costs for its commands, however they care carefully integrated into the functionality of each command. I believe having the broad functionality of adding a cost to random commands of other plugins wouldn't fit in well, nor would it behave exactly the way you would expect. You should probably request that each plugin (which you wish to have command charges for) implements their own method of charging the player when their commands are used.
