### ISSUE TITLE
Bed home still not works on legacy versions.

### ISSUE THREAD

**Issue by En0tS** [EssentialsX/Essentials#3109]
### Information

**Full output of `/ess version`**:
![image](https://user-images.githubusercontent.com/36606833/77882883-ab0bd280-726a-11ea-9ebc-4f8662b6e94e.png)

### Details

**Description**  
Bed home still not works: https://github.com/EssentialsX/Essentials/issues/3045

**Steps to reproduce**  
Just try to click on bed, there is no "home set" message.

**Expected behavior**  
...

**Comment by triagonal** [comment]
This bug should be fixed when #3048 is merged. It has not yet been merged but should be in the near future. Subscribe to #3048 to be alerted when the change is merged.

**Comment by triagonal** [comment]
Turns out "near future" actually meant "in 15 minutes from now"! Download the latest version
 from https://essentialsx.cf/downloads.html for a build that includes this fix.
