### ISSUE TITLE
UUID check

### ISSUE THREAD

**Issue by Botanistt** [EssentialsX/Essentials#311]
Hi there.

Could you add command to check uuid?
/uuid <player> I have cracked server and this would be awesome

**Comment by drtshock** [comment]
no

**Comment by khobbits** [comment]
(FYI, you can do /ess uuidtest [name] as an admin, but there are also lots of other scary secret commands hidden in /ess so don't give access out to people :P)

**Comment by Kakifrucht** [comment]
Oh wow, /ess nya is pretty neat.

**Comment by ChanceSD** [comment]
Really, where do i find a list of these secret commands? xD

**Comment by Kakifrucht** [comment]
[here](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/commands/Commandessentials.java)

**Comment by ChanceSD** [comment]
Thanks :+1:
