### ISSUE TITLE
Kit "name:" and "lore:" format using "_" for spaces, replaces the "_" within the {USERNAME} and {PLAYER} placeholders with spaces

### ISSUE THREAD

**Issue by accLarson** [EssentialsX/Essentials#3114]
### Information

**Full output of `/ess version`**:

```
[11:29:24 INFO]: CONSOLE issued server command: /ess version
[11:29:24 INFO]: Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-155 (MC: 1.15.2)
[11:29:24 INFO]: EssentialsX version: 2.17.2.1
[11:29:24 INFO]: EssentialsXSpawn version: 2.17.2.1
[11:29:24 INFO]: Vault is not installed. Chat and permissions may not work.
[11:29:24 INFO]: EssentialsXChat version: 2.17.2.1
```

**EssentialsX config**: https://gist.github.com/accZerek/58ae108121353f20ebbcc1d7ca596704

**EssentialsX Kit**:
```
kits:  
  testPlaceholders:
    delay: -1
    items:
    - feather 1 name:&ctest lore:&4Official:_{USERNAME}
```
### Details

**Description**  
When creating a kit which included placeholder {USERNAME} or {PLAYER} all "`_`" within the username/displayname are replaced with spaces. This is specifically an issue as players on our server are using alts with usernames for example "`accZerek_`" to spoof official "`accZerek`" items

**Steps to reproduce**  
Use {USERNAME} or {PLAYER} placeholder in name: or lore: of a kit. If the username or display name contains an underscore, it will appear as a space within the kits name: or lore:

**Expected behavior**  
The placeholder {USERNAME} and {PLAYER} should display the exact username/displayname, including underscores within kit name: and lore:

**Comment by JRoy** [comment]
Fixed with the following commits

2828901927d57ad5bccd0a56fa5a79538b2c6bc3
fc3dabf8f5cc697fc49ec633ac17f55a979b0d62
8d07c4bb0fc9eddafd00d03eb1c1f06326cd7538
8b2c7d7ad14271c9e6ad4a901db7e6fb2182139e
