### ISSUE TITLE
Weird bug with /home

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#3115]
When you type /home without a home, it will send the player to some random coordinates out in the millions. Even if you set "spawn-if-no-home: false", players can still use /home to get millions of blocks away from spawn.

How to reproduce, use version 2.17.2.40 essentials and essentials spawn, then type /home without op or perms, then watch as you get sent millions of blocks out into the wilderness.

**Comment by pop4959** [comment]
@DragonMaster606 Can you fill out / provide the rest of the information provided in the issue template?

**Comment by pop4959** [comment]
Closing this issue since there is not enough information to look into it.

**Comment by ghost** [comment]
Why do you need extra information? Its not rocket science bro, just get the essentials version that I said and type /home without op and the other parameters, only other things I can think of that would be relevant is that I'm on paper 1.15.2 and I tried it on a test server with only essentials and essentials spawn and everything default and it still happens.

**Comment by ghost** [comment]
Just because you think something isn't relevant, it doesn't mean that it is.

**Comment by pop4959** [comment]
I also asked you about 2 weeks ago to fill in the rest of the required information in the issue template, which you conveniently ignored/deleted. I think that was a fair warning. If you complete it, we can re-open this issue.

**Comment by ghost** [comment]
Thats funny because i cant find an issue reporting template, I don't know if you just expect people to know the correct format, or its just somewhere unconventional, but it would be nice to give people who don't follow the format an example template. Were here to report issues and I believe you would get more coherent bug reports if the actual template was easy to find.

**Comment by ghost** [comment]
Im not trying to be rude, but it is what it is.

**Comment by triagonal** [comment]
The template is literally the first thing you see when you start a new issue, which you seemingly deleted as it's not present in your original post.

![image](https://user-images.githubusercontent.com/10545540/79669045-47871c00-81fc-11ea-9b61-a607cc1d9ac5.png)

![image](https://user-images.githubusercontent.com/10545540/79669048-4bb33980-81fc-11ea-9ae1-a458b0e3c0c8.png)

If you'd like a version that you can copy and paste again, here:
```
<!-- EssentialsX bug reporting guide

Don't put anything inside this block, as it won't be included in the issue.

If you are reporting a bug, please follow the following steps:

1.  Fill out the template in full.
      Run the commands in the console. Don't just put "latest" as a version,
      or we will ignore it.

2.  When linking files, do not attach them to the post!
      Copy and paste any logs into https://gist.github.com/, then paste a
      link to them in the relevant parts of the template. Avoid using
      Hastebin or Pastebin, as this makes providing support more difficult.
      **DO NOT drag files into this box!**

3.  If you are reporting a performance issue, please include a link to a
    Timings and/or profiler report.

4.  If you are reporting a bug with commands or something else in-game,
    please include screenshots to help us diagnose the problem.

5.  Make sure not to write between the arrows, as anything there will be
    hidden.

6.  Delete this line and all above lines before posting your issue!       -->

### Information

**Full output of `/ess version`**:

<!-- Run the command in your console, and copy and paste the whole output here -->

**Server log**: <!-- Upload `logs/latest.log` to https://gist.github.com/, replace this with link -->

**EssentialsX config**: <!-- Upload `plugins/Essentials/config.yml` to https://gist.github.com/, replace this with link -->

### Details

**Description**  
<!-- Replace this with a brief summary of the bug. -->

**Steps to reproduce**  
<!-- Replace this with exactly what you did to cause the bug. -->

**Expected behavior**  
<!-- Replace this with what you expected to happen. -->

**Screenshots**  
<!-- Replace this with screenshots, if necessary. -->
```

**Comment by ghost** [comment]
That did not happen to me when I opened an issue, it was blank but ok

**Comment by ghost** [comment]
Well, either way, you can ignore this, the bug in question seems to have resolved itself in the latest builds on jenkins.

**Comment by pop4959** [comment]
Fair enough, glad to hear it appears to no longer be a problem.
