### ISSUE TITLE
Warp and log out , log in

### ISSUE THREAD

**Issue by duckweedvn** [EssentialsX/Essentials#312]

**Comment by joshua-am** [comment]
Vouch for this, from what I've been told on logging out, then logging back in. Inventories are cleared.
I've tried to personally replicate it myself and I only managed to that once when I restarted the server. 
Both OPs & None OPs are affected by this and from what I've been told it happens in any world, but also their /echest is cleared. 
PlayerVaults remain in tact though.

**Comment by duckweedvn** [comment]
https://www.youtube.com/watch?v=-B3sFpoccRM
And /warp does not work, you can fix it ??

**Comment by mdcfe** [comment]
Closing; there's nothing to indicate this is EssentialsX's fault, and this is a very old issue.
