### ISSUE TITLE
Request for EssentialsX

### ISSUE THREAD

**Issue by NoopyyGaming** [EssentialsX/Essentials#3125]
### Feature request

**Feature description**

I'm suggesting to make EssentialsX compatible with TacoSpigot.

**How the feature is useful**

It could be usefull for everyone i should say, because the plugin doesn't support TacoSpigot right now, and i though about it to suggest it here for all peoples who want to use the server file with the plugin. Right now, EssentialsX does not support it, so i wanted to get an answer on my question by coming here on the github of the plugin.

Best Regards

**Comment by mdcfe** [comment]
As a team, we generally don't provide assistance for running EssentialsX on anything other than Spigot and Paper (with the exception of Glowstone whose stable builds we aim to support). EssentialsX *may or may not* work on other server software not maintained by the Spigot, PaperMC or Glowstone teams. You're free to try running EssentialsX on other server software, but we won't assist you with it and we do not test the plugin again said alternative servers.
