### ISSUE TITLE
Sell sign and firework_rocket

### ISSUE THREAD

**Issue by corentingosselin** [EssentialsX/Essentials#3126]
### Details

**Description**  
sell sign with:
[sell]
64
fireworkrocket or firework_rocket
$1000

does not work, it says we do not have 64 rockets

**Steps to reproduce**  
Place a sign
[sell]
64
fireworkrocket
$1000

**Expected behavior**  
Sell items

**Comment by pop4959** [comment]
Sell signs will not work if the item does not have the same item metadata.

**Comment by Wafflexboy** [comment]
I'm not sure why this was closed, is there then no way to buy/sell the rockets?

**Comment by mdcfe** [comment]
You can only sell firework rockets if they don't have any metadata. As far as I'm aware you can't obtain firework rockets without metadata in survival (they all have power even if there's no explosion effect iirc), so you can only sell firework rockets that have been spawned in through commands.
