### ISSUE TITLE
EssentialsXMPP but with Discord

### ISSUE THREAD

**Issue by 1337god** [EssentialsX/Essentials#3129]
### Feature request

**Feature description**
A new EssentialsXMPP-like addon, but with Discord, maybe using DiscordSRV* API, that allows:
- Players who use Discord service are able to set their Discord ID ingame, which allows for other players to message them when they are not connected to minecraft.
- If you enable Discord spy for a user, that player will get a copy of ingame messages sent to their Discord account, as if they were connected and ingame.

**How the feature is useful**
Most servers now-a-day use Discord, I still use XMPP but I think it's something most users don't use nor admins. It would be a different direction of EssentialsX moving to Discord instead of keeping locked to XMPP.

*https://www.spigotmc.org/resources/discordsrv.18494/

**Comment by darbyjack** [comment]
This was something we started a while back but essentially just decided it wasn't a priority for now. No idea when that'll change. https://github.com/EssentialsX/Essentials/tree/feature/discord-module
