### ISSUE TITLE
Compatibility with command block

### ISSUE THREAD

**Issue by manrovich** [EssentialsX/Essentials#3131]
### Feature request

**Feature description**
I’m not quite sure if it’s your responsibility to do this, but can you do that when executed by the command block of the /eco take PlayerName Sum command, with a lack of funds, command block was false.

**How the feature is useful**
I needed this when I tried to exchange money for coins using a conditional command block, but even with a lack of funds, it gives the truе and the next command block gives the player a coins

![image](https://user-images.githubusercontent.com/23138330/78451395-0df7d200-768e-11ea-8be0-bb830b7b20ba.png)

Right command block: eco take @p 100. If it gives an error in the chat, then for the command block this is still true
Left command block: give @p ORDINARYCOINS_COINBRONZE 100

**Comment by pop4959** [comment]
As far as I know, there's no way Essentials could change this. You should probably also use plugins to execute the commands instead of command blocks.
