### ISSUE TITLE
Items don't drop upon death, both OP and Non-OPS

### ISSUE THREAD

**Issue by rcpancakes** [EssentialsX/Essentials#3133]
Hey guys items/levels dont seem to drop upon death, ive set the gamerules, also looked into the config.yml to remove the -essentials.keepInv but its not there. so im not too sure how to fix this.
plugins used
-essentialsx
-luckperms
-singleplayersleep
-timber
-worledit

version 1.15.2

**Comment by pop4959** [comment]
Lower case "I" in keepinv.
