### ISSUE TITLE
Add /gmg alias to gmsp command (Add "ghost" alias for "spectator" gamemode)

### ISSUE THREAD

**Issue by Adondriel** [EssentialsX/Essentials#3134]
### Feature request

**Feature description**
Add "ghost" as an alias for the "spectator" gamemode. (for example)
Add /gmg as an alias for /gmsp
My logic here is that "gmg" stands for "gamemode ghost" because spectator makes the player appear/act similar to a ghost

**How the feature is useful**
Makes the spectator gamemode command the same length as all the other gamemode commands, and can make it easier to memorize.

**Comment by pop4959** [comment]
Add the alias yourself in `commands.yml`. There is no reason to add user aliases directly to Essentials.
