### ISSUE TITLE
allow-old-id-signs doesn't work

### ISSUE THREAD

**Issue by pabloalba16** [EssentialsX/Essentials#3138]
### Information

**Full output of `/ess version`**: https://imgur.com/LcFKpES

```https://imgur.com/6QcYzJY
<!-- Run the command in your console, and copy and paste the whole output here -->
```

**Server log**: 

**EssentialsX config**:  https://pastebin.com/yfDnVFVR

### Details

**Description**  

**Steps to reproduce**  

**Expected behavior**  

**Screenshots**

**Comment by pop4959** [comment]
"Doesn't work" is not a proper bug report. Please fill out the template entirely, and do not leave out any section (unless it is truly not applicable, in which case please specify).
