### ISSUE TITLE
essentials nick

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#3139]
so i instal nick plugin, but essentials overwrite this plugin and that plugin not work.
have change-displayname: false but that not help
ps sorry for my bad english

**Comment by pop4959** [comment]
you might need to turn off your essentials nickname with `/nick off` before using the other one. otherwise, it might be a problem with the other plugin.

**Comment by ghost** [comment]
ok i fix it and now nick plugin work but essentials overwrite /nick command so i can't use /nick command from my nick plugin

**Comment by pop4959** [comment]
You can remove the nick command from Essentials via the [commands.yml](https://bukkit.gamepedia.com/Commands.yml#Alias_Examples) file in your server.
