### ISSUE TITLE
Add an order in the tab

### ISSUE THREAD

**Issue by DjeyMute** [EssentialsX/Essentials#3143]
Hi,

Almost 1 year ago you added the possibility that Essentials displays the tab by logging into groupmanager.
I suggest that we can choose the order of poster in the tab list so as not to mix all the grades of the servers.
That we can rank the ranks in order in the tablist (owner, admin ...)

And if possible add also above the player's head the name of the rank he has in groupmanager.
In this case the display would be complete!

I think it would help a lot of small server and would not add a plugin that does just that.

Ps: Sorry for my English i'm french ^^

Thank you in advance.

**Comment by pop4959** [comment]
Can you be specific about what the configuration is that you are talking about? A screenshot of what it looks like now, and an example of what you would like it to look like would be helpful.

Also, GroupManager has not been supported for 5+ years or something. It is recommended that you switch to a newer plugin like LuckPerms.

**Comment by DjeyMute** [comment]
Hello this is what I would find interesting to do : 
Ranked by rank the connected players.

**_Before_:**
[https://image.noelshack.com/fichiers/2020/15/3/1586370437-2020-04-08-20-22-45.png
](url)

**After :** 
[https://image.noelshack.com/fichiers/2020/15/3/1586370481-2020-04-08-20-22-26.jpg
](url)

**Comment by pop4959** [comment]
It looks like you have this already working, are you using a different plugin for the second picture?

**Comment by DjeyMute** [comment]
No it does not work with Essentials. ^^

Yes for the second image I use my own plugin.
But this one does not work in my lobby.

**Comment by pop4959** [comment]
Nice! If you already know how to program it, why not just make a pull request to Essentials? This is probably the fastest and most likely way the feature will make its way into the plugin.

**Comment by DjeyMute** [comment]
Oh ! Did I get the wrong place to post my idea?
I don't know how to code ^^ (my plugin is the plugin of my friend)

**Comment by pop4959** [comment]
AFAIK the only way to do this is via teams (at least in current versions of MineCraft). It's a bit of a hacky way to do this. If your friend is doing it another way, feel free to ask them to PR though.
