### ISSUE TITLE
Prefixes not showing

### ISSUE THREAD

**Issue by ItamarDenkberg** [EssentialsX/Essentials#3147]
### Information

Full output of `/ess version`:
```
Server version: 1.15.2-R0.1-SNAPSHOT git-Spigot-800b93f-8160e29 (MC: 1.15.2)
[15:45:21] [Server thread/INFO]: EssentialsX version: 2.17.2.0
[15:45:21] [Server thread/INFO]: LuckPerms version: 5.0.125
[15:45:21] [Server thread/INFO]: PlaceholderAPI version: 2.10.5
[15:45:21] [Server thread/INFO]: Vault version: 1.7.2-b107
[15:45:21] [Server thread/INFO]: Citizens version: 2.0.24-SNAPSHOT (build 1605)
```

**Server log:** 
https://pastebin.com/p3tPT9Zh

**EssentialsX config** 
https://pastebin.com/GnYNnmWz

### Help request

**Problem**
Prefix and Surfix not showing

**What I have tried**
Looking at the config of Essentials and other plugins to see why is it happening.

I have Vault and Luckperms and I changed the config and nothing works.
I want the prefix to be [{PREFIX}] {DISPLAYNAME}: {MESSAGE}
but in the chat it's <{DISPLAYNAME}> {MESSAGE}

**Comment by JasonHorkles** [comment]
Did you install EssentialsXChat

**Comment by ItamarDenkberg** [comment]
No, I tried to find the download link everywhere and then I watched a video that said I don't need EssentialsXChat.
If I do need can you please send me a download link?

**Comment by JasonHorkles** [comment]
1: You do
2: Downloads can be found [here](https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild)

If you need more support, you can also [join the MOSS Discord server](https://discord.gg/PHpuzZS)
