### ISSUE TITLE
Console spam /list command

### ISSUE THREAD

**Issue by albertomanzini** [EssentialsX/Essentials#3155]
Hello i have last release of essentialx on my server on multicraft and console spam /list command every minute. I asked to my host why and he said that is essentialx plugin. Can you confirm that? 
Thanks.

**Comment by zml2008** [comment]
That's often done by bad or misconfigured server control panels trying to get information about the server for whatever readouts they provide- they'll run certain commands at a regular frequency, so if it's exactly every minute it's most likely something like that
