### ISSUE TITLE
Reopening Request#592

### ISSUE THREAD

**Issue by x3mp** [EssentialsX/Essentials#3159]
Reopening.
Invsee does not do the job for command execution. I want to be able to clear a specific item with a specific item meta from a player their inventory.
This can not be done with any /take or /clear command
I have a renamed rotten_flesh that I want to be cleared but when I do /eclean or any clean/clear command it says 0 rotten_flesh removed from their inventory even though they have it in there.

I use color codes and lore with multiple lines for this item.

**Comment by pop4959** [comment]
This bug has already been reported in issue #2986. It should be fixed sometime soon(tm), just keep an eye on it.

**Comment by x3mp** [comment]
Reopening, custom named items still don't clear.
