### ISSUE TITLE
Pex Prefix doesn't work with EssenitalsXChat

### ISSUE THREAD

**Issue by Dooleylabs** [EssentialsX/Essentials#316]
For the life of me, I cannot get the prefix from pex to show up on the player's messages. It works with normal essentials, but not EssentialsX. I'd like to implement EssentialsX into our server, as it has desirable features, but I can't unless it cooperates with Pex's prefixes.

Essentials config: https://gist.github.com/Dooleylabs/6e6492f7365412bd9f7b
[This is the regular config that I had merged with the EssX one, but lost that one -- but this one's basically it.

EssentialsX: 2.0.1 build 237
Pex: 1.23.3

**Comment by vemacs** [comment]
Do you have Vault installed?

**Comment by Dooleylabs** [comment]
I'm an idiot xD. I had it on the main server, but not on the test server. I copied it into the test one and it works wonderfully xD. Thanks for the last minute fix! I read through the documentation, even seeing the vault requirement, but failed to realize it wasn't on both servers. You guys are the best.
