### ISSUE TITLE
Add a Global/Local chat PlaceHolder

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#3161]
### Feature request

**Feature description**
**Add a new placeholder that shows the chat type format on which the player is sending a message on the chat. An example would be %essentials_chat_format%, so if the player send a message locally, it would display as "[L]", and if he send it globally, then it would display as "[Shout]" (Or as how it is set on the message.properties of the plugin).**

**How the feature is useful**
**There are a lot of people that uses other chat format handlers in cause of its different unique features (for example hovering statistics or events) and also want to have altogether, those beautiful features that EssentialsChat brings like the ChatRadius and its algorithm.
Currently there is no single way to show or display either if a player is sending a message globally or locally in the chat because it is only included on the EssentialsChat chat format. It would be very useful and helpful to have a placeholder for that.**

**Comment by pop4959** [comment]
Placeholders are currently not supported in Essentials, but it is something that may be added in the future. Watch #2391 for more details.

**Comment by ghost** [comment]
Alright, first off thanks for answering my feature request. I've been reading the thread you sent me and got amazed with the idea of even adding JSON support to EssentialsX.That would be like killing two birds with one shot, since I needed those placeholders to actually show if the player was talking either in Global or Local in the plugin DeluxeChat and the reason I use that plugin for handling the chat format, is because of its JSON with full support for every type of hover click event. Anyways, I don't find it unnecessary to add placeholdersAPI support to EssentialsX, since it would help a lot to players that need to display certain information or statistics of EssentialsX either on scoreboards, tablists, displaymessages, the chat format, or even the serverlistmotd. Take this more as an opinion. 
Regards!

**Comment by pop4959** [comment]
No problem. Please feel free to add to the discussion I linked above. I've closed most other issues relating to specific chat enchantments / placeholder additions, since this should be done globally once such features are supported.
