### ISSUE TITLE
Be able to change "Shout" symbol, EssentialsChat

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#3162]
### Feature request

**Feature description**
**Be able to change the symbol required to "Shout" a message on EssentialsChat. The default symbol required to shout is "!".**

**How the feature is useful**
Would be very useful for avoiding conflicts with other plugins also using that symbol as command. In my case, it would be more helpful than useful, since it would be for simple esthetic because everyone in my network is very used to use "@" symbol more than "!" for shouting messages.

**Comment by darbyjack** [comment]
Will implement this tomorrow.

**Comment by ghost** [comment]
Thanks a lot for accepting my suggestion darbyjack!

**Comment by darbyjack** [comment]
Keeping this open until I implement the PR.

**Comment by darbyjack** [comment]
After further investigation, this looks to be an easter egg and can already be modified if you create a section in the config called `chat.shout` and you set the character for it, meaning it can already be changed.

**Comment by ghost** [comment]
Oh! Didn't know about it, thanks darbyjack! But... could you please give me a more detailed description on how to create it? I tried creating a new node on EssentialsChat section of the config named chat.shout, with a value '@' so the shout would require @ symbol instead of ! but didn't work :(

**Comment by mdcfe** [comment]
You'll need to add the option inside the `chat:` section of your `config.yml`:

```diff
  ############################################################
  # +------------------------------------------------------+ #
  # |                   EssentialsX Chat                   | #
  # +------------------------------------------------------+ #
  ############################################################
  
  # You need to install EssentialsX Chat for this section to work.
  # See https://essentialsx.cf/wiki/Module-Breakdown.html for more information.
  
  chat:
+   shout: '@'
  
    # If EssentialsX Chat is installed, this will define how far a player's voice travels, in blocks. Set to 0 to make all chat global.
    # Note that users with the "essentials.chat.spy" permission will hear everything, regardless of this setting.
    # ...
```

Make sure you've indented it properly.

**Comment by ghost** [comment]
Thanks a lot @md678685 !!!
