### ISSUE TITLE
reload and free kits

### ISSUE THREAD

**Issue by falken91** [EssentialsX/Essentials#3167]
Hi, mi issue is simple. I don't want to use essentials.* permission and if I don't use it, I can't reload the server, I request essentials.reload permission and also a essentials.kit.free? If I use .* I recieved all the kits by free

Sorry about my english, the plugins runs perfectly on paper-spigot 1.15.2 with LuckPerms.

Thanks!

**Comment by pop4959** [comment]
All of the permissions are listed [here](https://essinfo.xeya.me/permissions.html). Read through it and give only the permissions that you need.
