### ISSUE TITLE
Update Translation files... maybe?

### ISSUE THREAD

**Issue by khobbits** [EssentialsX/Essentials#317]
Here is the 'current' batch of TL files from crowdin, in case you want to consider merging them.

Obviously, if you've added/removed keys, you need to account for that, also some of the files require renaming ;)

[essentials-2 TLPACK.zip](https://github.com/drtshock/Essentials/files/68070/essentials-2.TLPACK.zip)

**Comment by drtshock** [comment]
Thank you :)

**Comment by khobbits** [comment]
[essentials-2.TLPACK.zip](https://github.com/drtshock/Essentials/files/165959/essentials-2.TLPACK.zip)

Updated TL Pack

**Comment by mdcfe** [comment]
Most of our translations have been updated by PRs by now, but there might be some useful changes in these I guess.

**Comment by pop4959** [comment]
Yeah... been about 4 years. :laughing: We'll probably survive without this, especially since most of the translations have already been updated/changed by now. EssentialsX is also using Crowdin again now.
