### ISSUE TITLE
Anything wrong with fly

### ISSUE THREAD

**Issue by RedXStone** [EssentialsX/Essentials#3171]
### Information
Full output of `/ess version`:
https://gist.github.com/CrazyRussianBro/fcdff90b07ff6090a8feb6eba95dac3c
**Server log:** 
https://gist.github.com/CrazyRussianBro/d7c39e4caca9f6e8e2aaaa1e5a80dec5
**EssentialsX config** 
https://gist.github.com/CrazyRussianBro/30e18a28c42a3947ca91f3877423637f
### Help request

**Problem**
Hello, I have a problem with fly. 
Commands fly doesn't work
**What I have tried**
When I tried to get fly to myself when I typed and Enter,
nothing happened, I looked on console (with enabled debug), I got an empty output in console too

**Comment by RedXStone** [comment]
Accidently closed, I was thinking about allow-flight in server.properties, but this not was helped

**Comment by JRoy** [comment]
First of all, remove EssentialsXMPP, you probably don't need it. Secondly, what was printed in the console after this line:
`[00:24:54] [Server thread/INFO]: RedysXStone issued server command: /fly`

**Comment by RedXStone** [comment]
> First of all, remove EssentialsXMPP, you probably don't need it. Secondly, what was printed in the console after this line:
> `[00:24:54] [Server thread/INFO]: RedysXStone issued server command: /fly`

I'll was said, nothing, just empty line
Screenshot:
![Аннотация 2020-04-16 013806](https://user-images.githubusercontent.com/46400591/79395726-f6b8be80-7f82-11ea-864b-325ef3f93bfc.png)
Or just no line

**Comment by RedXStone** [comment]
I have tried this again and looked on console, there nothing happened, as if I registered a command without debugging, although I turned on debug to look at the problem in more detail
![image](https://user-images.githubusercontent.com/46400591/79396044-b6a60b80-7f83-11ea-860c-91551b117573.png)

**Comment by mdcfe** [comment]
Could you post the output *with* `/ess debug` enabled?

**Comment by RedXStone** [comment]
> Could you post the output _with_ `/ess debug` enabled?

Yep

**Comment by triagonal** [comment]
Closing due to author inactivity. If you'd like us to continue looking into this, please follow the instructions above and post the results in this thread.
