### ISSUE TITLE
/msg more people?

### ISSUE THREAD

**Issue by Botanistt** [EssentialsX/Essentials#318]
Would be cool if it was possible to send same Private Message to multiple people.
Instad of writing
/msg Bob hey there.
/msg Alice hey there.

We could write

/msg Bob,Alice hey there.

Thanks

**Comment by RoboMWM** [comment]
Sounds like a great way to mass-spam. Probably would want to add a permission to this, if there really is a need to be implemented. Might as well make a group or something via another plugin if you need to repeat messages to more than one player.

**Comment by drtshock** [comment]
There's already *\* 

I do disagree with this though.
