### ISSUE TITLE
[AFK] Prevent afk player from falling

### ISSUE THREAD

**Issue by scannerGT** [EssentialsX/Essentials#3180]
### Information

Full output of `/ess version`:

[11:14:04] [Server thread/INFO]: CONSOLE issued server command: /ess version
[11:14:04] [Server thread/INFO]: Server version: 1.15.2-R0.1-SNAPSHOT git-Spigot-ae72bf4-183139d (MC: 1.15.2)
[11:14:04] [Server thread/INFO]: EssentialsX version: 2.17.2.0
[11:14:04] [Server thread/INFO]: LuckPerms version: 5.0.72
[11:14:04] [Server thread/INFO]: Vault version: 1.7.2-b107
[11:14:04] [Server thread/INFO]: EssentialsXProtect version: 2.17.2.0
[11:14:04] [Server thread/INFO]: EssentialsXAntiBuild version: 2.17.2.0
[11:14:04] [Server thread/INFO]: EssentialsXSpawn version: 2.17.2.0

**Server log:** 

**EssentialsX config**

https://gist.github.com/scannerGT/6b3613551c4349d557a8f7448ea58e63

### Help request

**Problem**

Player X has been set as afk, standing on the ground. Other players dug the hole to the lowest level, which caused player X to fall to the bottom. The hole was filled with lava and water, which caused the player to get stuck in the rock (on Y=2!), without the possibility of escape (teleportation is disabled on our server). Because he had a lot of valuable equipment, and the server mode is set to survival, so as not to lose the goods he quickly logged out. To save him, I had to edit the player's data file, forcing him to a different start position when logging in.

**What I have tried**
I was looking for an option that would block the player from falling when he has the afk mode (player's movement in the options is off), but I didn't find one.
**Screenshots**

https://cdn.discordapp.com/attachments/700047535007596605/700617990231818320/Bez_tytuu.png
https://cdn.discordapp.com/attachments/700047535007596605/700618324928888842/unknown.png

**Comment by pop4959** [comment]
This sounds extremely niche and probably not something we would add to Essentials. In addition, logically, I don't see how this would help. First of all, when the player goes un-AFK, they would just fall anyway. Second of all, it would not help with any other situations where the player gets themselves stuck. You should probably have an "oh-shit button" on your server, such as a teleport to spawn, or somewhere else unoffensive to game play. That, or allow someone like a moderator to teleport people around. It's the least you could do to make sure this situation doesn't happen.

**Comment by scannerGT** [comment]
Of course, when the player leaves the AFK and there is a void below it, it falls - but the exit from the akf requires interaction - so it would be time to realize that something is wrong - while burying is already a bigger problem: in my case, before the victim figured out that something is wrong, she was buried in bedrock with one heart of health :)
Sure - I assume that this is a very rare case and if there is no point in rebuilding the plugin, that's cool :) I was wondering if this is not a bug :)

**Comment by pop4959** [comment]
Yeah it's not really a bug. The AFK system is used to determine if people are AFK or not, but doesn't do any protection. Try doing a teleport or figuring out some other way to get around this issue (or, if it doesn't happen often, just try to make sure that players report people for abusing AFK).
