### ISSUE TITLE
Can't disable creeper block damage

### ISSUE THREAD

**Issue by yorick22** [EssentialsX/Essentials#319]
I am trying to disable the damage caused by mobs.
Like creeper blockdamage enderman block pick up and so..

I set the settings in the config file to "true" but the creepers still damage blocks ( i haven't checked the endermans)

The gamerule MobGrieving is on true

**Comment by drtshock** [comment]
Do you have essentialsprotect installed?

**Comment by Rum-ura** [comment]
> 
thanks
