### ISSUE TITLE
legacy /hat

### ISSUE THREAD

**Issue by En0tS** [EssentialsX/Essentials#3193]
### Information

**Full output of `/ess version`**:
![image](https://user-images.githubusercontent.com/36606833/80137699-5713b580-85ac-11ea-9547-56fc1d179006.png)

### Details

**Description**  
/hat command doesn't works, just 'hatFail' message with any block in hand, no errors.

**Steps to reproduce**  
get item in your hand and type /hat

**Comment by pop4959** [comment]
Did you give yourself OP or * permission? If so, you have `essentials.hat.prevent-type.<type>` which prevents you from using blocks as a hat.

**Comment by En0tS** [comment]
Aww. Thanks!
