### ISSUE TITLE
Offhand Invsee

### ISSUE THREAD

**Issue by TommyJ100** [EssentialsX/Essentials#3194]
### Information

Full output of `/ess version`:

**Server log:** 

**EssentialsX config** 

### Help request

**Problem**
Is there a way to see what a player has in their off hand. We can access the inventory and armor but I have not been able to find a command for the off hand, ultimately causing players to be able to hide illegal items in their off hand.

**What I have tried**
/invsee offhand (different variations of the word offhand as well)
/invsee

**Comment by pop4959** [comment]
No I don't think this feature exists. Let's leave this open as a feature request.
