### ISSUE TITLE
boat bug help me!

### ISSUE THREAD

**Issue by dugulingping** [EssentialsX/Essentials#3198]
Hello, I'm having problems transporting villagers and other npc by boat. You can get them into the boat but you cannot get into the boat with them. I believe this plugin is causing the issue.

Any help on this would greatly be appreciated. If it isnt your plugin, could you possibly give me your best guess of what to check?

**Comment by pop4959** [comment]
Only file a bug report if you have proof that Essentials is causing it. You should be able to tell us what you are doing for the bug to occur, and fill out the issue template entirely.
