### ISSUE TITLE
GroupManager and EssentialsX Severe Error (1.14.4 Spigot)

### ISSUE THREAD

**Issue by daniel15navarro** [EssentialsX/Essentials#3199]
**Server log:** 

**EssentialsX config** 

### Help request

**Problem**

I am currently running EssentialsX version 2.17.2.0 and GroupManager version 0.2.0. Whenever I try to type any GroupManager-related commands, I get an error message saying "All commands are locked due to an error. Check plugings/groupmanager/error.log or console and then a /manload." I checked console and it gave me this error message: "PLEASE COPY AND PASTE THE ERROR.LOG FROM THE GROUPMANAGER FOLDER TO AN ESSENTIALS  DEVELOPER". 

**What I have tried**

I have tried downloading different versions of GroupManager, including older and newer versions. I have also tried different configs and double checked my files for any errors. 

**Screenshots**

![image](https://user-images.githubusercontent.com/54896541/80269550-bf32cc00-867e-11ea-825d-941a1e632c86.png)
![image](https://user-images.githubusercontent.com/54896541/80269564-e1c4e500-867e-11ea-8967-2c66805ca2eb.png)

**Comment by pop4959** [comment]
GroupManager is no longer supported. Use [LuckPerms](https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/) instead.
