### ISSUE TITLE
Allow teleporting over the void when flying or using an appropriate gamemode

### ISSUE THREAD

**Issue by blanitzaone** [EssentialsX/Essentials#3201]
### Feature request

**Feature description**

Ability to teleport to someone who is over the void. 

**How the feature is useful**

Currently, when attempting to teleport to someone that is over the void, an error pops up stating that there is a hole in the floor, thus not allowing you to teleport to them, even if flying. By being able to teleport to someone over the void, this will allow much faster response times for staff teleporting to each other, especially when every second counts, such as someone possibly duping or hacking in any way. 

Additionally, some type of permission check would be very beneficial, since disabling the method within the configuration would allow everyone to be able to do so, which would result in most players falling to their death since they do not have access to fly.

**Comment by editid1** [comment]
yep, I was confused when I was in fly and couldn't teleport because of that

**Comment by pop4959** [comment]
Have you tried turning off teleport safety in the config?

**Comment by blanitzaone** [comment]
By turning off teleport safety, since the majority of players do not have access to being able to fly, doing so will result is most of them falling to their deaths when they teleport, so turning the safety off is unfortunately not a viable solution. Approximately 80-90 percent of players do not have access to fly, so this would cause a bigger problem

**Comment by editid1** [comment]
It should Be off (maybe toggleable) if you are in fly

**Comment by mdcfe** [comment]
The latest dev builds include #3102 which should fix this. You can download them from the [EssentialsX website](https://essentialsx.net/downloads.html).
