### ISSUE TITLE
/heal for phantoms' spawn

### ISSUE THREAD

**Issue by survetman** [EssentialsX/Essentials#3202]
### Feature request

Hello ! 
I know that the /heal command cleans all effects and other things to make us full life without effect etc... but do you know if it's possible to add something with this command ?
I explain you what and why. 
When we are in creative mode, we never slept. The counter for phantoms' spawn continue to increment. And if we teleport us on player, a lot of phantoms spawn. 
It will be very great that when running this command, the sleep counter is reset. 

**How the feature is useful**

For owner and players, this feature could improve their gameplay and to avoid some player death because someone in the staff comes to a player.

**Comment by pop4959** [comment]
This is essentially the same request as #2299, so I will close this issue in favor of that one.
