### ISSUE TITLE
reminder for /kit

### ISSUE THREAD

**Issue by Melvout** [EssentialsX/Essentials#3203]
### Feature request

Hi !

**Feature description :**

On my server, several players can access to the command **/kit** ( with various kits ) every 24h. However some of them forget to use it.
Is it possible to **add a reminder** when the cooldown of a kit is finished ? In the same way of the message that you receive in the chat for the **/mail** when you have an unread message.

Thanks for the work and have a good day !

**Comment by mdcfe** [comment]
This seems like a pretty niche feature (and personally I'd find this incredibly annoying if I was constantly reminded "claim this kit now!" over and over). This is out of scope for EssentialsX.
