### ISSUE TITLE
[Enhancement] add option to format socialspy

### ISSUE THREAD

**Issue by Dooleylabs** [EssentialsX/Essentials#321]
The purpose of this is to have a clear separation of socialspy from the default chat layout.

In the config, we have format: `'{DISPLAYNAME}: {MESSAGE}'` located in the chat section. Is it possible to add something similar to that which would allow the format of socialspy to be changed? Maybe `spy-format: '&7[{DISPLAYNAME}] {MESSAGE}'`?

It's difficult to distinguish between regular chat and socialspy commands, which is why I'm requesting this be added.

**Comment by drtshock** [comment]
I thought there was already a way to configure it O_O

**Comment by Dooleylabs** [comment]
If there is, please tell me. Our default rank has white text and it bothers the higher staff members when they're trying to read both the chat and the commands being sent. I know I don't pick up on everything, but I looked everywhere for this in the config and could not find something for it.

**Comment by AllieQpzm** [comment]
I remember I used to find this annoying back when I used Essentials too. Unfortunately there's not a way to configure it, @drtshock - it just sends it as you can see here https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java#L380

**Comment by drtshock** [comment]
Ah, then yes, this needs to be configurable!

**Comment by pop4959** [comment]
These can be configured in [messages.properties](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/messages.properties#L504-L507).
