### ISSUE TITLE
Message files don't work

### ISSUE THREAD

**Issue by Jakaboii** [EssentialsX/Essentials#3214]
### Information

Full output of `/ess version`: https://hatebin.com/nleqpylkab

**Server log:** https://hatebin.com/vlqoqqnygw

**EssentialsX config** https://hatebin.com/jgbizkueyo

### Help request

**Problem**
EssentialsX doesn't use my locale files, and when I got something working (I can't even remember at this point) it just had loads of smiley faces and NOT what I wrote in the language file AT ALL

**What I have tried**
I've tried multiple things, I've tried tons of aliases for `locale:` in the config, I've tried editing the message files straight from the jar, I've tried renaming the message file that was in my Essentials folder to multiple things - all of which have failed

**Comment by pop4959** [comment]
Messages and translations help: <https://github.com/EssentialsX/Essentials/wiki/Locale>
Contribute: <https://crowdin.com/project/essentialsx-official>

If you are still need help, please visit the official [EssentialsX Discord](https://discord.gg/PHpuzZS) chat. There are many people who will be able to help you.

**Comment by Jakaboii** [comment]
I've tried the first link, and I got told to come here from the discord :/

**Comment by pop4959** [comment]
rip
