### ISSUE TITLE
Command cooldown regexs issue

### ISSUE THREAD

**Issue by DebuffPvP** [EssentialsX/Essentials#3215]
### Help request

**Problem**
So i am trying to add a cooldown for /repai hand but the repair one won't include the hand in the command cooldowns section and i don't know what regexes i should use
as well as another command that being for my custom plugin
/mobcoins pay

**What I have tried**
I have tried everything the helpers have given me on discord, they didn't really know how to use regexes but helped me as much as they could

Here is what i already got in
command-cooldowns:
  '^mobcoins +pay': 3
  trade: 3
  pay: 3
  mail: 30
  helpop: 60
  feed: 60
  '^repair': 30
  '^repair( *all)+': 60

The repair all one works fine though i also tried the same setup for hand but doesn't work

**Comment by pop4959** [comment]
If "repair all" is working, "repair hand" will also work in the same fashion.
