### ISSUE TITLE
Players not OP cant place TNT in wildreness

### ISSUE THREAD

**Issue by Alekhedjran** [EssentialsX/Essentials#3217]
### Information
Server is 1.15.2
Full output of `/ess version`:
latest.

**EssentialsX config** 

### Help request

**Problem**

Players cant place TNT in wilderness. it Gives them error message "not permitted to use tnt in this area"
**What I have tried**

checked blacklist to see if tnt in on the list. it isnt.

**Comment by pop4959** [comment]
Please join the [Discord server](https://discord.gg/PHpuzZS) for help with plugin setup & usage.
