### ISSUE TITLE
Curses with essentials.keepinv

### ISSUE THREAD

**Issue by kaanakduman** [EssentialsX/Essentials#3219]
### Feature request

**Feature description**
Add configuration options to 
1. Make items with curse of vanishing disappear on death, even if the player has essentials.keepinv
2. Make items with curse of binding drop on death, even if the player has essentials.keepinv

**How the feature is useful**
Curse of vanishing is supposed to disappear when the player dies. However, if the player has essentials.keepinv, then the player keeps their inventory, essentially making the enchantment pointless.

Curse of binding is supposed to be unremovable except by either the player dying or the durability reaching 0. However, if the player has essentials.keepinv, then the only way that the player can remove an item with binding is by allowing the durability reach 0. This means getting attacked a lot and potentially dying multiple times. This can spam the server with death messages, and it's even worse if the armor has unbreaking or mending.

**Comment by zml2008** [comment]
There are probably multiple ways to handle this, dunno which one is the most correct, but here's a few other alternatives

- Match the behaviour of the vanilla gamerule `keepInventory`, which is what the current behaviour does
- Remove the curse of binding from affected items, and make curse of vanishing items be removed anyways
- Strip the enchantment from both sets of items

**Comment by xHydration** [comment]
What if keepinv was able to be toggled on and off by the player?

**Comment by zml2008** [comment]
that is uh what permissions do
