### ISSUE TITLE
Use command block without being op

### ISSUE THREAD

**Issue by D0lab** [EssentialsX/Essentials#3221]
Hi, I noticed that because of Essentials we can't use command blocks other than op and gamemode 1, is there a way to change that so we can use them without being op and with permissions?

**_Sincerely 
Dolab_**

**Comment by JRoy** [comment]
You need to be op and be in creative mode in order to use command blocks. This is not an essentials bug.

**Comment by D0lab** [comment]
Okay, but is there a plugin that would change that?

**Comment by triagonal** [comment]
There might be, but I doubt EssentialsX will ever be that plugin.
