### ISSUE TITLE
Socialspy revamp

### ISSUE THREAD

**Issue by Avizoh** [EssentialsX/Essentials#3222]
### Feature request

**Feature description**

Now I know EssentialsX already has socialspy, but when you have socialspy toggled and you send a message it repeats it. This is a mere annoyance to me, and possibly others. I'd like to use EssentialsXChat but until the repeated message is removed, I am sticking with DeluxeChat.

Honestly, depending on how it is set up, you could add a check. If the player with socialspy toggled on is sending/receiving PMs then cancel the socialspy message for the sender/recipient.

**How the feature is useful**

It is useful to prevent the clogging of chat. Especially if the chat is flowing due to players or plugins sending messages in chat!

**Comment by pop4959** [comment]
You can [change ](https://github.com/EssentialsX/Essentials/wiki/Locale#customising-messages) or [remove](https://github.com/EssentialsX/Essentials/wiki/Locale#disabling-messages) messages in Essentials to match your desired behaviour.
