### ISSUE TITLE
Radiuschat "lonely" message

### ISSUE THREAD

**Issue by roopekoo** [EssentialsX/Essentials#3224]
### Feature request

**Feature description**
If chat radius is enabled and there is no other user in that radius and after the player sends a message there could be the following message displayed :
_"There's no one near you! Try using ! or ? prefixes in your message"_
or some other similar message.
Also, an automatic cooldown between sending that info message would be a great addition to this(eg. 1 minute), so the info message would not be sent after every lonely message.

**How the feature is useful**
This would be a great feature for those servers who use radius chat and a lonely player would not chat by themselves in vain.

**Comment by mdcfe** [comment]
This message already exists as `localNoOne` in `messages.properties`, but it's empty by default. You can enable it by adding the message to the `localNoOne=` line of your messages file.

**Comment by roopekoo** [comment]
Although, no source has said that such a feature exists. Thas why I asked it as a feature. But thanks for clarifying.
