### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by CustomEnchants** [EssentialsX/Essentials#3229]
### Details

**Description**  
-essentials.spawnerconvert.* does not prevent disabling this function
https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/EssentialsBlockListener.java lines 36:48

**Steps to reproduce**  
Add -essentials.spawnerconvert.* to your user directly or group 
Place a spawner
Use a mobegg on the spawner

**Expected behavior**  
I expect it to not change a spawner if it is negative

**Screenshots**

**Comment by ghost** [comment]
I updated my response to your question in the MOSS, but I'll put it here as well:

This permission is not for the egg spawner placement, sorry for saying that it was. It's actually checking if you have permission to place the spawner, from what I gather.

Essentials doesn't handle egg spawner conversion, it is a vanilla MC thing (you can confirm this by going into a SP world and doing it). You'll need another plugin to block this kind of action.

**Comment by mdcfe** [comment]
`essentials.spawnerconvert.<type>` is a compatibility feature for certain older server implementations to ensure that stacks of spawners that were spawned in using `/give` have their types applied properly when you place them. If you read the code you linked, you'll notice that EssentialsX doesn't actually *do* anything unless you have this permission.

As @kadenscott noted, EssentialsX doesn't handle changing the type of spawners using spawn eggs. You'll need another plugin to prevent that type of behaviour.
