### ISSUE TITLE
Enchantments Don't work properly

### ISSUE THREAD

**Issue by Rohanm0121** [EssentialsX/Essentials#3232]
I enchant my leather helmet to unbreaking 30 but it isn't working properly at all... Instead it says unbreaking 30 on the armour piece but in reality it's using enchantment unbreaking 3 I need Enchantment unbreaking 30 not 3... however swords enchants work just fine.

**Comment by pop4959** [comment]
Sorry, but filling out the issue template is required if you are attempting to make a bug report. We can't properly look into the issue since you haven't provided enough information.
