### ISSUE TITLE
Enchantments not working properly

### ISSUE THREAD

**Issue by Rohanm0121** [EssentialsX/Essentials#3233]
Server log:

EssentialsX config

**Help request**
Problem

I enchant my leather helmet to unbreaking 30 but it isn't working properly at all... Instead it says unbreaking 30 on the armour piece but in reality it's using enchantment unbreaking 3 I need Enchantment unbreaking 30 not 3... however swords enchants work just fine.

What I have tried

Nothing, as I'm not sure how to fix it.

Screenshots

![4c4a8e5378c9e3c81c5ec1fdf3ea76eb](https://user-images.githubusercontent.com/56348680/81107937-d8a20680-8f0f-11ea-992a-c31d66ddf82d.png)

**Comment by Rohanm0121** [comment]
You can come on the server and you'd see the problem, this needs to be fixed asap!!!

**Comment by pop4959** [comment]
It looks like Essentials is doing its job correctly. You can see it says it is unbreaking level 30.

**Comment by Rohanm0121** [comment]
What do you mean?

**Comment by Rohanm0121** [comment]
yeah it says Unbreaking 30 but in reality it isn't! For me its working on unbreaking 3 durability. You can come on my server and we can test this please!
