### ISSUE TITLE
I have a drop in tps and in the timings you are accusing the essentials

### ISSUE THREAD

**Issue by LordRamma** [EssentialsX/Essentials#3235]
Please I need help, I have a drop in tps and in the timings you are accusing the essentials or something that I do not know to inform. If you can see my timings thank you very much. Use paper 1.15.2
If you need anything else just ask. THX

https://timings.aikar.co/?id=aa45f0f961784d7ca8664ded98022d0f

List plugins:
Plugins (85): ActionHealth, AdvancedAchievements, AnimatedInventory, AutoMessage, BetterRTP, BetterSleeping, CactusLimiter, ChatReaction, Chunkmaster, Citizens, CitizensBooks, CitizensCMD, CitizensHologram, ClearLag, CommandButtons, CommandPanels, CoreLibs, CrazyAuctions, CrazyCrates, CustomHeads, DamageIndicator, DangerousNether, DeathMessagesPrime, DungeonsXL, DWG_OasisDesert, Elevator, EnchantmentsEnhance, EntityTrackerFixer, Essentials, EssentialsAntiBuild, EssentialsChat, FlightControl, Genie, GSit, HolographicDisplays, ID-Library, ItemEdit, ItemParticles, LibsDisguises, LightAPI, LimitPillagers, LoreAttributesRecoded, Magic, MagicWorlds, MarriageMaster, mcMMO, MineableSpawners, MobHunting, Multiverse-Core, MyCommand, MyPet, MythicMobs, NerfPhantoms, nLogin, PermissionsEx, PexTabCompleter, PixelVip, PlaceholderAPI, PlugMan, ProtocolLib, Quests, Rankup, RedProtect, SAML, Shopkeepers, SignShop, SimpleClans, SkinsRestorer, STN-Blocker, SystemProperties, TAB, TeleportAPI, UltimateAutoRestart, UltimateChat, UltimateTrash, Vault, VillagerOptimiser, Votifier, VotingPlugin, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, XPBottler, ZeroTickStopper

**Comment by pop4959** [comment]
Essentials doesn't appear to be causing any significant lag on your server. Some of the lag appears to also likely be caused by PermissionsEx v1, which is a dead plugin. I recommend using LuckPerms instead, and maybe PermissionsEx v2 when that is released (if you prefer).
