### ISSUE TITLE
any mods item id not exist

### ISSUE THREAD

**Issue by sweetapple-233** [EssentialsX/Essentials#3236]
ess version:
[04:31:15] [Server thread/INFO] [Minecraft]: CONSOLE issued server command: /ess version
[04:31:15] [Server thread/INFO] []: Server 版本n: 1.12.2-R0.1-SNAPSHOT git-CatServer-1.12.2-d2395e4 (MC: 1.12.2)
[04:31:15] [Server thread/INFO] []: EssentialsX 版本n: 2.17.2.70
[04:31:15] [Server thread/INFO] []: EssentialsXProtect 版本n: 2.17.2.70
[04:31:15] [Server thread/INFO] []: EssentialsXSpawn 版本n: 2.17.2.70
[04:31:15] [Server thread/INFO] []: EssentialsXChat 版本n: 2.17.2.70
[04:31:15] [Server thread/INFO] []: Vault 未安装. 聊天与权限系统也许无法使用.
                                                      (Vault not installed,chat and permissions sysyem may not working)

letest.log : https://gist.github.com/sweetapple-233/2285097268ec1b8e65ad4d8500132fb5

config.yml : https://gist.github.com/sweetapple-233/a1755511ed9df7f9b34ec6b7fe86b454

kits.yml : https://gist.github.com/sweetapple-233/b59e75c23ab39d116a67ca39c11f743a

![](https://i.loli.net/2020/05/07/4nI1esul3OpyERS.png)
when I try add mod item into kits.yml ,then use"/kit tools"it said:
"this kit it may not exist or be refuse,please contact op."
then I  used /give sweetapple waystones_waystone,it tell me "error:unknown item name:waystones_waystone"
if kit only have vanilla minecraft things is fine,no error.once I add any mod item,ic2/forestry/waystones etc.just all error.

![](https://i.loli.net/2020/05/07/hO1438xEGYV5Lcu.png)
*in this pic it said   item: id: error:
I tried many way to figure out the actual "id"
such as 
①/itemdb
②see coreprotest container transactions
③just enough item
④f3+h
edit kits.yml, /ess reload , then tested it one by one.

also,I've tried upgrade or downgrade essX and "catserver"....

![](https://i.loli.net/2020/05/07/7ZGfT5mnMoIH1cb.png)
AND IT JUST NOT WORKING.
I'm going crazy,hope anyone can help me,THANK YOU!
if you need more information,just asking me.sorry for my bad english

**Comment by pop4959** [comment]
EssentialsX only officially supports CraftBukkit, Spigot, Paper, and Glowstone. Please report this as a bug to the developers of CatServer, as they will more likely be able to fix the issue.
