### ISSUE TITLE
Chat Issues

### ISSUE THREAD

**Issue by Attila144** [EssentialsX/Essentials#3237]
### Information

Full output of `/ess version`:

07.05 17:17:11 [Server] INFO Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-77 (MC: 1.15.2)
07.05 17:17:11 [Server] INFO EssentialsX version: 2.17.2.0
07.05 17:17:11 [Server] INFO PlaceholderAPI version: 2.10.6
07.05 17:17:11 [Server] INFO PermissionsEx version: 1.23.4
07.05 17:17:11 [Server] INFO Vault version: 1.7.2-b107
07.05 17:17:11 [Server] INFO Citizens version: 2.0.26-SNAPSHOT (build 1854)
07.05 17:17:11 [Server] INFO EssentialsXChat version: 2.17.2.0
07.05 17:17:11 [Server] INFO EssentialsXSpawn version: 2.17.2.0
07.05 17:17:11 [Server] INFO ChestShop version: 3.9.0 (build #52)
07.05 17:17:11 [Server] INFO You are running unsupported plugins!

**Server log:** 
https://gist.github.com/Attila144/fbda8e59e57dfbb4ac8833bc84f52a3e

**EssentialsX config** 
https://gist.github.com/Attila144/071628291e6174372fc2e46b8f4730fc

### Help request

**Problem**

Trying to use a placeholder in chat config

**What I have tried**

different ways and plugins but none worked.

**Screenshots**

![2020-05-07_16 48 08](https://user-images.githubusercontent.com/61101267/81265619-94834300-9082-11ea-99c5-ebeaa8ab450f.png)

**Comment by pop4959** [comment]
EssentialsChat currently doesn't support placeholders from other plugins. Please follow https://github.com/EssentialsX/Essentials/issues/2391 to discuss or follow updates regarding this.
