### ISSUE TITLE
Sell Sign

### ISSUE THREAD

**Issue by xYuki94x** [EssentialsX/Essentials#3240]
### Information

Full output of `/ess version`:

**Server log:** 

**EssentialsX config** 

### Help request

**Problem**

Sell Sign dont work - everything works, but not whis. Buy is ok, but when i do [Sell] and rest of text, it changes for [sell] and its just regular text.
**What I have tried**

Looking in google, looking few times it is for sure enabled, ask on discord in support.
**Screenshots**

![2020-05-07_23 36 31](https://user-images.githubusercontent.com/64990031/81347005-9d443b00-90bb-11ea-8c06-d0b18685d023.png)

**Comment by xYuki94x** [comment]
Sorry, dont get where wrtore it. I have latest version for today, 7.05.2020 and play on 1.15.2

**Comment by pop4959** [comment]
"Latest" is not a version. Can you please provide the rest of the information from the template, as asked for?

**Comment by xYuki94x** [comment]
2.17.2.0

**Comment by ice-fly** [comment]
Cannot confirm bug... I typed:
```
[sell]
1
Dirt
$1
```
And it automatically took format/upgraded to [Sell] ... Running latest EssX & Paper. I'm guessing user error.

**Comment by JRoy** [comment]
Possibly related to #3252 

Does this jar fix the problem for you guys: https://cdn.discordapp.com/attachments/480176903911636994/709115038325145650/EssentialsX-2.17.2.80.jar

**Comment by mdcfe** [comment]
Reopening for now as #3253 isn't guaranteed to fix the issue. (This will be closed if it still can't be replicated.)

**Comment by pop4959** [comment]
Cannot replicate, same result as @ice-fly. I think most likely @xYuki94x doesn't have the buy sign enabled, and/or doesn't have permission to create it. If he did, the [Sell] text turns blue.
