### ISSUE TITLE
Update disposal command

### ISSUE THREAD

**Issue by Destitution-SC** [EssentialsX/Essentials#3244]
**Feature description**
I'm suggesting to update disposal command so i request to add a argument "hand" if no arguments provided then use the GUI if the argument "hand" is provided then removes the item in your hand and the other items that are the same item from the item in your hand.

**How the feature is useful**
It can be easy to delete one item from your inventory, for example you have a full inventory of red roses & iron ingot from your ig spawner farm in a server, you can take the red rose in your hand and use **/disposal hand** if only the red roses needs to be removed from your inventory but not the iron ingot in your inventory.

**Comment by mdcfe** [comment]
This is what `/clear` will do once we've finished restoring its original functionality. We're not going to add this to `/disposal` because that doesn't make sense - it's a carbon copy of the `[disposal]` sign.

Edit: you can follow #3191 for progress on this.

**Comment by editid1** [comment]
oof
