### ISSUE TITLE
/Hat instruction cannot be executed normally

### ISSUE THREAD

**Issue by Black233455** [EssentialsX/Essentials#3245]
I'm using Paper 1.15.2 #261, but I can't use the handheld box / Hat normally, but I can use the plug-in of the old version, which is 2.17.2.77
![QQ截图20200508231907](https://user-images.githubusercontent.com/65030553/81420778-0a6ed380-9183-11ea-806a-9a3aecd25fe0.png)

**Comment by pop4959** [comment]
Make sure you have the correct hat [permissions](https://essinfo.xeya.me/permissions.html). If you have `essentials.hat.prevent-type.<item-name>` (such as if you are OP), Essentials will prevent you from using the hat.
