### ISSUE TITLE
Blank nickname bug.

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#3246]
EssentialsX dev 897

By typing && twice, you are able to bypass the alphanumeric nick check and have a blank nickname.

```
08.05 13:03:54 [Server] INFO mibby issued server command: /nick &4&&d
```

The second & registers as an alphanumeric character and strips itself. This turns your username into just ``~`` that is colored your prefix.

```
# A color code between 0-9 or a-f. Set to 'none' to disable.
ops-name-color: 'none'

# The character(s) to prefix all nicknames, so that you know they are not true usernames.
nickname-prefix: '~'

# The maximum length allowed in nicknames. The nickname prefix is included in this.
max-nick-length: 15

# A list of phrases that cannot be used in nicknames. You can include regular expressions here.
# Users with essentials.nick.blacklist.bypass will be able to bypass this filter.
nick-blacklist:
#- Notch
#- '^Dinnerbone'

# When this option is enabled, nickname length checking will exclude color codes in player names.
# ie: "&6Notch" has 7 characters (2 are part of a color code), a length of 5 is used when this option is set to true
ignore-colors-in-max-nick-length: true

# When this option is enabled, display names for hidden users will not be shown. This prevents players from being
# able to see that they are online while vanished.
hide-displayname-in-vanish: false

# Disable this if you have any other plugin, that modifies the displayname of a user.
change-displayname: true

# When this option is enabled, the (tab) player list will be updated with the displayname.
# The value of change-displayname (above) has to be true.
change-playerlist: true

# When EssentialsChat.jar isn't used, force essentials to add the prefix and suffix from permission plugins to displayname.
# This setting is ignored if EssentialsChat.jar is used, and defaults to 'true'.
# The value of change-displayname (above) has to be true.
# Do not edit this setting unless you know what you are doing!
add-prefix-suffix: true

# When this option is enabled, player prefixes will be shown in the playerlist.
# This feature only works for Minecraft version 1.8 and higher.
# This value of change-playerlist has to be true
add-prefix-in-playerlist: true
```

**Comment by pop4959** [comment]
Not really a bug as far as I can tell, as the nickname you provided is actually considered alphanumeric (essentials ignores & as part of the requirements since it is used for chat colors). The problem here appears to be more so that there are no visible characters when the display name is shown in chat. While this in it of itself is not really technically an issue, I can see why it would be annoying (for example, if you are trying to look up who that user is with `/realname`). Essentials may want to consider requiring that nicknames are at least one visible character.

**Comment by pop4959** [comment]
Tried looking into this, but in no way am I able to replicate it. Looks like the code for nicknames already checks that the length is at least one character. In addition, I am not able to set the nickname in your example unless I use the `essentials.nick.allowunsafe` permission, which is not enabled by default. Apparently having `&` in the nickname is *only* allowed normally when used for color, which is a good distinction to make.
