### ISSUE TITLE
Silent join-leave

### ISSUE THREAD

**Issue by JonasFS2002** [EssentialsX/Essentials#3249]
When you join the server as an OP, you have automatic the Silent join and silent left. In the config file I have this: **allow-silent-join-quit: false**   
And still operators gets no joining and leaving message and all other players do have the message.

**Comment by editid1** [comment]
make sure they don't have the permission node to do that and also I think this was changed in the newest version which you can find on their jenkins, try doing that then maybe ask for help in their support discord server
