### ISSUE TITLE
Players with sign color permission still able to create essentials signs

### ISSUE THREAD

**Issue by VoxaDub** [EssentialsX/Essentials#325]
ok so I've figured out how to do this (thanks to TitanicFreak) and it currently works on the 238 build (latest build currently)
If you have perms for colored signs and you type &1&1[[Disposal]](or any other sign type enabled on the server) you're then able to make a working essentials sign. TitanicFreak has also tested it on his server and it is working as well, along with my 3 other servers it being an issue.

**Comment by drtshock** [comment]
@adamqpzm is going to take a stab at this.

**Comment by VoxaDub** [comment]
Do you guys even test your bug fixes? This did not fix it.

**Comment by VoxaDub** [comment]
Still works exactly as before

**Comment by AllieQpzm** [comment]
Of course I tested it, but I appreciate the insinuation that I didn't :)

You can view it working here: https://youtu.be/2Z4Hnqdl8j4 - I even downloaded the latest version from the CI to make sure there was no version mismatch.

**Comment by VoxaDub** [comment]
Not sure how thats possible, I updated it on all of my servers, including my test server which has ONLY essentials and pex I then gave myself the color and use perm for signs, no other perm, and I am still able to create essentials signs using the multiple color codes.

**Comment by VoxaDub** [comment]
This is the ip of my test server if you dont beleive me. 192.99.35.188:25585

**Comment by AllieQpzm** [comment]
Having visited the server, I can confirm this issue is fixed.

**Comment by drtshock** [comment]
:boom:

**Comment by VoxaDub** [comment]
So this actually still DOES work, one of my players just showed me a different way. Is  there really not a better way of patching this?
https://i.gyazo.com/da6915f9179ff7546263e6602bf2c806.png

**Comment by AllieQpzm** [comment]
Does that even produce a workable sign? It shouldn't since the default sign requires it to be &1[repair]. The screenshot you've provided results in a sign with &f[repair], which wouldn't work. I tested for situations like this, and it didn't work for me.

**Comment by VoxaDub** [comment]
Yeah I'm just as confused as you are, it works for some reason.

**Comment by AllieQpzm** [comment]
Would you like to demonstrate the sign working and not being blocked? It's not a valid sign when I test it, so I'm not having the issue you seem to.

**Comment by drtshock** [comment]
Hi. This has been fixed. If you still think it's not fixed, post a video proving it is not in a new ticket. Thanks for being so patient and nice with us as we're helping you during the holidays instead of being with family :)
