### ISSUE TITLE
Eco reset incorrectly takes an amount

### ISSUE THREAD

**Issue by Destitution-SC** [EssentialsX/Essentials#3251]
**Description**  
Hello, /eco reset is supposed to reset our balance right? I'm pretty sure it's supposed to be **/eco reset [player]** but not **/eco reset [player] 10** (Sets to starter's server balance) It only works if we put an amount which isn't supposed to be like that, I know it's a small issue but just wanted to report it 💯 

**Steps to reproduce**  
- I did **/eco reset Notch**, It gives the usage.
- Then i tried **/eco reset Notch 10** and then it set it to 100 wich is supposed to be like that.

**Expected behavior**  
If possible fix that small issue? 👍 

**Screenshots**  
![Screenshot_2](https://user-images.githubusercontent.com/43219594/81500021-a574c400-92cf-11ea-90f4-d459d24e683a.png)

**Comment by pop4959** [comment]
Not able to reproduce this issue. Reset resets the player's balance, and it appears to be doing that correctly.

**Comment by Destitution-SC** [comment]
Yes it does it correctly but did you 3 args or 2 args?

**Comment by pop4959** [comment]
Ah yeah not sure why I was unable to reproduce it before. It doesn't make sense for there to be an amount in reset (that is what set is for).

**Comment by pop4959** [comment]
@Destitution-SC Should be fixed in the latest version!
