### ISSUE TITLE
Enchant Book Issue Along with Repairs

### ISSUE THREAD

**Issue by DebuffPvP** [EssentialsX/Essentials#3259]
**Problem**
So when unsafe-enchants is true in the config and i give a player an enchantment with protection 8 and the book also says that but when using it on an anvil to enchant an item it only allows to enchant with the vanilla amounts not anything above that.

Another issue is when players use all the fix commands and they got nothing to fix it still proceeds to give players a cooldown.

I am currently using the latest version of essentials on spigot

**Comment by mdcfe** [comment]
> I am currently using the latest version of essentials on spigot

Latest is not a version.

---

> So when unsafe-enchants is true in the config and i give a player an enchantment with protection 8 and the book also says that but when using it on an anvil to enchant an item it only allows to enchant with the vanilla amounts not anything above that.

This is how unsafe enchantments work - it allows you to create items with nonsense enchantments, but EssentialsX does not modify how Minecraft works to deal with them, meaning that in certain cases they won't work properly. We don't support unsafe enchantments, so this isn't something we're interested in fixing - I'd recommend looking for a custom enchantment plugin if you want non-vanilla enchantments.

> players use all the fix commands and they got nothing to fix it still proceeds to give players a cooldown

Command cooldowns don't check for whether the command was successful. I'd recommend informing your players that they check their inventory before using `/fix` to see if they actually need to use it.
