### ISSUE TITLE
not connecting with dadabase GEO-IP

### ISSUE THREAD

**Issue by johnorlic** [EssentialsX/Essentials#3278]
### Information

Full output of `/ess version`: 2.17.2.77

**Server log:** 

**EssentialsX config** https://gist.github.com/johnorlic/2295e63acef9b578ae6a84ab22d4d8b9

### Help request

**Problem**
The database will not connect 
**What I have tried**

**Screenshots** 
https://gyazo.com/e73eccad99717f19569fe416138538fd

**Comment by pop4959** [comment]
Read the warning on startup. As of December 2019 you need a license key from MaxMind in order to use GeoIP. Update to the latest version of EssentialsX and EssentialsXGeoIP if you do not see this warning.

**Comment by johnorlic** [comment]
I have a key from MaxMind and i have now de latest version of EssentialsX and EssentialsXGeoip.
See the link for the screen with the error [https://gyazo.com/e73eccad99717f19569fe416138538fd](url)

**Comment by pop4959** [comment]
Ah I see. 401 Unauthorized means the license key was incorrect. You can see in the link you wrote in extra curly brackets `{` and `}`. Those should not be there.

Do not edit `download-url` and `download-url-city` (unless you want to change the location the database is downloaded from). Only change the license key field.

**Comment by pop4959** [comment]
These are the correct links (fix them in your config):
```
  # Url for country
  download-url: "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key={LICENSEKEY}&suffix=tar.gz"
  # Url for cities
  download-url-city: "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key={LICENSEKEY}&suffix=tar.gz"
```
