### ISSUE TITLE
Group still prefixing chat

### ISSUE THREAD

**Issue by Tikkle** [EssentialsX/Essentials#3280]
### Information

**Full output of `/ess version`**:

```
>.... [19:57:30 INFO]: Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-282 (MC: 1.15.2)
>.... [19:57:30 INFO]: EssentialsX version: 2.17.2.0
>.... [19:57:30 INFO]: LuckPerms version: 5.1.15
>.... [19:57:30 INFO]: PlaceholderAPI version: 2.10.6
>.... [19:57:30 INFO]: Vault version: 1.7.2-b107
>.... [19:57:30 INFO]: Citizens version: 2.0.26-SNAPSHOT (build 1959)
>.... [19:57:30 INFO]: EssentialsXProtect version: 2.17.2.0
>.... [19:57:30 INFO]: EssentialsXChat version: 2.17.2.0
>.... [19:57:30 INFO]: EssentialsXAntiBuild version: 2.17.2.0
>.... [19:57:30 INFO]: EssentialsXSpawn version: 2.17.2.0
```

**Server log**: https://gist.github.com/Tikkle/c3a6d03c3581d1ebae95eb3fefea9a8c

**EssentialsX config**: https://gist.github.com/Tikkle/e7630c4b1fb7255a04336b77f187e5e5

### Details

**Description**  
The chat-format section shows that the group placeholder should not be displayed, yet in-game the group tag is still shown before the user's display name

**Steps to reproduce**  
all I did was change from format to group-formats and add my per-group chat formats.

**Expected behavior**  
I expected it to looked like: (Admin) Tikkle

What happened was: [Administrator] (Admin) tikkle

**Screenshots**  
https://imgur.com/a/pjZII6Q

**Comment by pop4959** [comment]
You can use `{USERNAME}` instead of `{DISPLAYNAME}` if you only want to show the username and not the entire display name (prefix + username + suffix). Also, it looks like you might have more than one chat plugin installed, because the other stuff there doesn't appear to be in your config. Join the [Discord server](https://discord.gg/PHpuzZS) if you need more help figuring it out.

**Comment by Tikkle** [comment]
Issue persists even after switching to {USERNAME} tag

**Comment by pop4959** [comment]
It seems pretty clear to me you have another plugin formatting your chat. Remove all plugins except for EssentialsX, EssentialsXChat, Vault, and LuckPerms and you should be able to figure it out. Good luck!

**Comment by Tikkle** [comment]
I've Isolated EssentialsX, EssentialsXChat, Vault, and LuckPerms on their own private server, the Issue still persists.

When I use the "chat.format" option this issue goes away, but I don't want to use that option because it doesn't fit what I'm trying to do.

**Comment by pop4959** [comment]
As I mentioned before, please join the Discord server and ask for help in the Essentials channel. It will be much easier, and there are many very capable people there. We primarily deal with feature requests and bug reports on Github. Chat is one of the most stable components of Essentials, so this is definitely a usage/configuration problem on your end, and almost certainly not a bug.
