### ISSUE TITLE
Affected is null on nick change from console.

### ISSUE THREAD

**Issue by V0mcog** [EssentialsX/Essentials#3281]
This might be a problem with the API: NickChangeEvent.getAffected gives a null value when I change the nick of a player from console.
Testing code: 

@EventHandler
public void nickChanged(NickChangeEvent e)
{
	Log.info("fired");
	if(e.getAffected() == null)
	{
		Log.info("r1");
		return;
	}

	if(e.getAffected().getName() == null)
	{
		Log.info("r2");
		return;
	}

	Log.info("success");
}

I type "/nick <mynick> asd" for example, the event fires, and cancels with "r1". I was online all the time, and didn't misspell my name. Everything works fine when using the command in-game.

**Comment by pop4959** [comment]
Is this related to #3043 by chance?

**Comment by V0mcog** [comment]
Hmm, probably. Just found it, didn't browse for it before posting. Sorry. :)

**Comment by pop4959** [comment]
No problem. That event has issues, but it seems like no one wants to change it until a major release. It's a minor inconvenience for now...
