### ISSUE TITLE
java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by ShadowChi1d** [EssentialsX/Essentials#3282]
### Information

**Full output of `/ess version`**: Unknown command

**Server log**: https://gist.github.com/ShadowChi1d/339c7e628ef93505e30dc9c2e5530a53

**EssentialsX config**: https://gist.github.com/ShadowChi1d/25ba83ab6d674d2f3071a55a3f20ad1a

### Details

**Description**  
I'm getting the error `java.lang.UnsupportedOperationException` during start up

**Steps to reproduce**  
Unsure

**Expected behavior**  
Not get the error

**Screenshots**

**Comment by pop4959** [comment]
Does this happen on startup or any time someone tries to connect?

**Comment by ShadowChi1d** [comment]
On startup @pop4959

**Comment by triagonal** [comment]
Related: #2592 (another CloudNet-related `ServerListPingEvent` issue)

**Comment by ShadowChi1d** [comment]
> Related: #2592 (another CloudNet-related `ServerListPingEvent` issue)

I am running the very latest build from the Jenkins. That issue was closed stating it was fixed

**Comment by triagonal** [comment]
> I am running the very latest build from the Jenkins. That issue was closed stating it was fixed

Just another related issue, not a duplicate. Just linking them together so whoever chooses to solve it has more information to work with :)

**Comment by JRoy** [comment]
@ShadowChi1d can you try https://cdn.discordapp.com/attachments/480176903911636994/710865918204313611/EssentialsX-2.17.2.98.jar and confirm that this error goes away

**Comment by pop4959** [comment]
@ShadowChi1d Any updates? Have you tried Roy's fix?

**Comment by ShadowChi1d** [comment]
@pop4959 I've just tried it, it appears to have solved the issue.
