### ISSUE TITLE
Config Version Number

### ISSUE THREAD

**Issue by LordOmen** [EssentialsX/Essentials#3287]
### Feature request
Add Config Version Number to the beginning of the config.yml

**Feature description**

See Above
**How the feature is useful**

Allows the user to more easily identify what version they are running which is helpful for admins, particularly when frequently having to update multiple plugins.

**Comment by triagonal** [comment]
This already exists - when a new config is generated by EssentialsX, it puts the version number right at the top of `config.yml` as can be seen here (the placeholder is replaced with the version of the jar file): https://github.com/EssentialsX/Essentials/blob/b960ee365a5fb7bdf3393fc6483aaa300f4e5c5f/Essentials/src/config.yml#L8 

I'm closing this in favor of #3286 which could include a form of version number that may assist in configuration auto-updates.
