### ISSUE TITLE
/broadcast /bc

### ISSUE THREAD

**Issue by Someone-NEW** [EssentialsX/Essentials#329]
Hello i have a suggestion to be possible in some world feature make so that can be enabled or disabled /broadcast /bc in some world only in one wordl and chose in witch worlds will be globaly and witch separate or a make a group for broadcasting ans will be possible this group enable/disabel in config.yml this is by me realy usefule beacause some game use broadcasting and is seeing in all worlds but not need to be more spam from there. So when you can will be realy cool feature. nice work man thank you.

**Comment by SupaHam** [comment]
I don't like the idea of incorporating this idea into /broadcast directly as it might be confused, I think we can do this in a separate new command though. Maybe /broadcastworld and /bcw.

**Comment by SupaHam** [comment]
`/broadcastworld` or `/bcw` along with a few other aliases will allow you to broadcast to just a world as of [build 244](https://ci.drtshock.net/job/EssentialsX/244).

**Comment by Someone-NEW** [comment]
Yes will be welcome this /broadcastworld or /bcw is OK and add separate permission idk is this need but thank you whn i have some other siggestion i will open other ticket thaks alot ;)
Nice work i use this command on kingkits plugin on kitname.yml for using command:
- broadcastworld &e<player> &dhas chosen the &b<kit> &dkit!

and
- bcw &e<player> &dhas chosen the &b<kit> &dkit!

But is nothing happen when i type this on chat work but not on kitpvp using command
on console sometime i se this:
03.01 03:15:12 [Server] INFO Error: Invalid world.
03.01 03:15:11 [Server] INFO Error: Invalid world.

Thanks for fixing ;)
