### ISSUE TITLE
/Skull command don't work

### ISSUE THREAD

**Issue by RubenBarrionuevo** [EssentialsX/Essentials#3290]
Version Server: CraftBukkit Spigot 1.15.2-R0.1-SNAPSHOT
Version EssentialsX: Essentials v2.17.2.96
Logs url: https://pastebin.com/NSQNScV5
Screenshot: https://i.imgur.com/GkR2bj5.png
Complete logs: https://pastebin.com/twJ3Wx2j

**Steps to reproduce**  
1. Only try to execute the command /skull Notch, and error appear

**Expected behavior** 
1. Receive the head correctly

**Comment by JRoy** [comment]
@RubenStryker can you please give the full server log

**Comment by RubenBarrionuevo** [comment]
Of course, the issue has been update.
Complete logs: https://pastebin.com/twJ3Wx2j

**Comment by JRoy** [comment]
@RubenStryker are you running bungeecord?

**Comment by RubenBarrionuevo** [comment]
No, i don't use bungee

**Comment by JRoy** [comment]
In that case, you're using offline mode which is not supported by the EssentialsX team.

Additionally, this error is not reproducible

**Comment by RubenBarrionuevo** [comment]
In this case, tomorrow i will change the Mode of server and i see if the
problem persist
