### ISSUE TITLE
All signs (buy, sell, trade, balance, etc...) do not work. They only work for oped players.

### ISSUE THREAD

**Issue by Sophoster** [EssentialsX/Essentials#3293]
### Information

Full output of `/ess version`: 

Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-224 (MC: 1.15.2)
EssentialsX version: 2.17.2.0
PermissionsEx version: 1.23.5-SNAPSHOT
Vault version: 1.7.2-b107
EssentialsXSpawn version: 2.17.2.0
EssentialsXChat version: 2.17.2.0
You are running unsupported plugins!

**Server log:** 

**EssentialsX config** 
https://gist.github.com/SophieEFoster/39a27826c7f06ef1ddeb1a108f800615

### Help request

**Problem**

None of the Essentials signs have worked. When you right click them nothing happens. Only oped players can interact with them. 
**What I have tried**

I have tried adding permissions for signs with PEX (essentials.signs.use.<type>) and restarting the server.
**Screenshots**

**Comment by pop4959** [comment]
You need to give the sign permissions. Look [here](https://essinfo.xeya.me/permissions.html) to see what these are.

**Comment by Sophoster** [comment]
I did add the sign permissions. The signs still do not work. (I added essentials.signs.use.buy, and essentials.signs.use.sell, and essentials.signs.use.kit, and essentials.signs.use.balance, and essentials.signs.use.warp)

**Comment by pop4959** [comment]
Join the [Discord server](https://discord.gg/PHpuzZS) and visit the Essentials support channel as someone there might be able to help you figure out what you have configured incorrectly.
