### ISSUE TITLE
Offenses of a player.

### ISSUE THREAD

**Issue by Destitution-SC** [EssentialsX/Essentials#3294]
**Feature description**
Logs offenses done by staff with mute/jail/tempbanip/tempban/ipban/ban and maybe /warn if that's ever going to be a thing in EssentialsX.

**How the feature is useful**
It could be useful to receive recent offenses of players to check their behaviour or anything else.
And with page support so as baltop but then with offenses that has the time displayed as when they got an offenses and by who + reason of the offense. The command could be **/offenses <player>** or **/history <player>** and maybe also **/offenses [player] clear** to clear their history.

**Comment by Sophoster** [comment]
Yes

**Comment by mdcfe** [comment]
EssentialsX doesn't currently track offenses history. This feels like the job of a dedicated punishments plugin.

**Comment by pop4959** [comment]
I agree with MD here. There are other plugins meant to provide much more elaborate punishment systems, and I don't necessarily think Essentials needs this feature. The commands Essentials has for moderation are pretty basic, and if your server is actually large enough to warrant needing an offense log to keep track of people, you're probably going to be using something else anyways.
