### ISSUE TITLE
When I change the confil.yml file, and save it, and then reload essentials, nothing changes.

### ISSUE THREAD

**Issue by Sophoster** [EssentialsX/Essentials#3297]
### Information

Full output of `/ess version`:

Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-224 (MC: 1.15.2)
EssentialsX version: 2.17.2.0
PermissionsEx version: 1.23.5-SNAPSHOT
Vault version: 1.7.2-b107
EssentialsXSpawn version: 2.17.2.0
EssentialsXChat version: 2.17.2.0
You are running unsupported plugins!

**Server log:** https://gist.github.com/SophieEFoster/cb67256171327828ddef0802a4cd9224

**EssentialsX config** The config.yml file is broken.

### Help request

**Problem**
Before the config.yml file broke, when I changed something in the file and saved it, nothing happened, even after I did /ess reload.

**What I have tried**
I have tried restarting the server, waiting for a while, and changing different things in the config than what I was trying to change, to see if it was just the thing I was trying to change that wasn't working.

**Screenshots**

**Comment by pop4959** [comment]
You need to save the file, and restart your server completely. If the config file says it's broken, that means you didn't format the file correctly. Google is your friend here, if you need to figure out how YAML works. Also, there are YAML linters that might help find where the issues are (although I'd suggest only changing one option at a time and if it breaks, you know you did something wrong with it).

**Comment by Sophoster** [comment]
Oke
