### ISSUE TITLE
/msg while muted

### ISSUE THREAD

**Issue by Mikgreg** [EssentialsX/Essentials#330]
Hi, back with another suggestion.

Currently while players are muted they are still able to communicate with each other and staff using the private message commands, this frequently opens staff up to abuse from the player and defeats the purpose of the mute command. Can the /mute command be expanded to cover private messaging too? 

Thanks!

**Comment by drtshock** [comment]
https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/config.yml#L157
