### ISSUE TITLE
Add an option that can prevent Essentials from overriding vanilla commands.

### ISSUE THREAD

**Issue by cs127** [EssentialsX/Essentials#3308]
### Feature request

**Feature description**

Add an option that prevents Essentials from overriding vanilla commands such as `/kill`.
However, the Essentials command should still be accessible by typing either `/essentials:kill`, or aliases like `/ekill`. But typing `/kill` should default to `/minecraft:kill`.

**How the feature is useful**

The feature might be useful when having to use a vanilla command that has the same name as an essentials command. For example, typing the command `/kill @e[type=zombie,limit=3]` won't work because the command will default to the Essentials `/kill` command, not the vanilla one.

**Comment by JRoy** [comment]
This isn't essential or easily doable with the current codebase. Just prefix your commands that you want to use the vanilla equivalence of with minecraft: so like `/minecraft:kill @e`

**Comment by pop4959** [comment]
This is due to the way that Bukkit handles commands. Vanilla commands are *ALWAYS* overridden by plugin commands. Also, a good portion of the vanilla commands are much newer (Essentials had them first!). You can always force overrides through the server's commands.yml file.

**Comment by CyanChanges** [comment]
> This isn't essential or easily doable with the current codebase. Just prefix your commands that you want to use the vanilla equivalence of with minecraft: so like `/minecraft:kill @e`

Why don't essentials add option to add a prefix for essentialsx commands, so vanilla commands is not overriden though

**Comment by JRoy** [comment]
> > This isn't essential or easily doable with the current codebase. Just prefix your commands that you want to use the vanilla equivalence of with minecraft: so like `/minecraft:kill @e`
> 
> Why don't essentials add option to add a prefix for essentialsx commands, so vanilla commands is not overriden though

We do, you can also add commands you don't want Essentials to override to the disabled-commands section of the config.yml.

**Comment by CyanChanges** [comment]
> > > This isn't essential or easily doable with the current codebase. Just prefix your commands that you want to use the vanilla equivalence of with minecraft: so like `/minecraft:kill @e`
> > 
> > 
> > Why don't essentials add option to add a prefix for essentialsx commands, so vanilla commands is not overriden though
> 
> We do, you can also add commands you don't want Essentials to override to the disabled-commands section of the config.yml.

> Disabling commands here will prevent Essentials handling the command, this will not affect command conflicts.

Like It says literally says it won't affect conflicts in the comments

**Comment by Doppel-R101** [comment]
> > > This isn't essential or easily doable with the current codebase. Just prefix your commands that you want to use the vanilla equivalence of with minecraft: so like `/minecraft:kill @e`
> > 
> > 
> > Why don't essentials add option to add a prefix for essentialsx commands, so vanilla commands is not overriden though
> 
> We do, you can also add commands you don't want Essentials to override to the disabled-commands section of the config.yml.

Which line would this be at, assuming no major line changes to a default config?

**Comment by JRoy** [comment]
> > > > This isn't essential or easily doable with the current codebase. Just prefix your commands that you want to use the vanilla equivalence of with minecraft: so like `/minecraft:kill @e`
> > > 
> > > 
> > > Why don't essentials add option to add a prefix for essentialsx commands, so vanilla commands is not overriden though
> > 
> > We do, you can also add commands you don't want Essentials to override to the disabled-commands section of the config.yml.
> 
> Which line would this be at, assuming no major line changes to a default config?

https://github.com/EssentialsX/Essentials/blob/2.x/Essentials%2Fsrc%2Fmain%2Fresources%2Fconfig.yml#L178
