### ISSUE TITLE
/sit

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#3315]
Hello,

I wanted to request the feature to have /sit and even perhaps /lay

It would be a nice quality of life feature added into Essentials.

It will be off by default and can be toggled on in the config.

Next to that a list of blocks that you are able to right click so you can sit on them.

As for example:

Sittable blocks:
OAK_SLAB
OAK_STAIRS

**Comment by pop4959** [comment]
I don't think this fits in with the other features in Essentials, and is probably better off in another plugin. It looks like there are many options, according to a quick google search.
