### ISSUE TITLE
In chat it shows worldname when players type. how to disable? 

### ISSUE THREAD

**Issue by N-gct** [EssentialsX/Essentials#3316]
I know it may seem basic, but in chat when i type it shows the worldname. Im not sure how to disable this. This is my config for EssentialsChat

config: https://pastebin.com/GnCCaQRc
(The configs on the pastebin because i culdnt figure out how to format it correctly here)

I know it may seem basic, and i dont know if its related to essentials.

The group formats used to be like this:
  group-formats:
  #  default: '{WORLDNAME} {DISPLAYNAME}&7:&r {MESSAGE}'
  #  admins: '{WORLDNAME} &c[{GROUP}]&r {DISPLAYNAME}&7:&c {MESSAGE}'
but when i removed the {WORLDNAME} nothing changed.

https://ibb.co/26K9vfd

Update: In the creative world, and a few others, it shows this: 
https://ibb.co/sWygpwf

In other worlds it still shows this:
https://ibb.co/26K9vfd

**Comment by JRoy** [comment]
Make sure you restart your server too, if that doesn't do it, it's likely something in multiverse causing it
