### ISSUE TITLE
Empty shout double charges user

### ISSUE THREAD

**Issue by SMD404** [EssentialsX/Essentials#3317]
**Information**
Essentials version

[22:47:32 INFO]: Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-304 (MC: 1.15.2)
[22:47:32 INFO]: EssentialsX version: 2.17.2.99
[22:47:32 INFO]: Vault version: 1.7.2-b107
[22:47:32 INFO]: EssentialsXChat version: 2.17.2.99

**latest.log** https://gist.github.com/SMD404/b6d814b027b4738f6707f482bc96edfc
**EssentialsX** config: https://gist.github.com/SMD404/fb72b6aaee2a8bd86a57a800702c4dfc

**Description**  
Hello, i use cost for global chat, and when a player sends to chat "!" without message, then they pay double price. 

**Steps to reproduce**  
Message in chat as in the screenshot (! and no message - chat local + double price, ! and message - chat global + normal price)

**Expected behavior**  
! - There should be no fee for local chat (BUG)
! + message - everything is working

**Screenshots**  
https://i.imgur.com/EcgqsoG.png

**Comment by pop4959** [comment]
Can you fill out the rest of the information in the issue template?

**Comment by SMD404** [comment]
> Can you fill out the rest of the information in the issue template?

Yes, I updated the information.

**Comment by pop4959** [comment]
@SMD404 Should be fixed in the latest version! The new patch makes sure that empty shout/question messages are not double counted, as they are properly considered local messages now (as in your screenshot).
