### ISSUE TITLE
Feature: A permission that allows users to have the same name as another person who has joined.

### ISSUE THREAD

**Issue by Weasel-Beans** [EssentialsX/Essentials#3319]
At the start of the year one of my players changed their Minecraft username to Weasel_Beans, which I was using as my nick. At one point I tried changing my nickname to test something, but I was unable to change it back to 'Weasel_Beans' as it was apparently already taken. Eventually that player changed their username back through Mojang, but the plugin still claimed "That name is already in use". I decided to buy another account named "Weasel_Beans" to prevent that impersonation, but I still need to use my main account for many reasons.

I think that a permission node that allows users like myself to bypass the "name is already in use" feature would be necessary and useful. Also, it shouldn't block you from having the same nick as a username that somebody USED to use either way.

And "essentials.nick.allowunsafe" doesn't work for this purpose, I tested it.

**Comment by pop4959** [comment]
Did the impersonating player logged in again since changing their name? You might be able to forcibly set their nickname to something else or remove their old name from usermap.csv (make a backup before attempting to edit this).

`essentials.nick.allowunsafe` is intended for allowing a player to use non-ascii characters in their nickname (which sometimes don't display properly in chat).

**Comment by Weasel-Beans** [comment]
Yes they changed their username back after a month, and I did change their nickname until they did that. However, as I also stated: I currently have an alt account with that name on my server, so removing the username from that file probably wouldn't work.

**Comment by pop4959** [comment]
It's worth checking that there are not two entries for the same name to different UUIDs (if that is possible), or that the wrong entry (not yours) is in there. In both cases, you might wish to manually delete it, at least for an immediate solution to your problem.

**Comment by pop4959** [comment]
Yeah it looks like all you need to do is remove their old account name from the user data file.

**Comment by Weasel-Beans** [comment]
Yes, but again: I have an alt account that I now use to test things on the server with the same name, so my suggestion to have a permission to allow you to use a nickname that matches another player's username still stands.

**Comment by mdcfe** [comment]
Giving people the ability to set a nickname that exactly matches another user's nickname is confusing to users. We're not going to support this.

**Comment by Weasel-Beans** [comment]
That's why I suggested to have it be a permission. There's no reason why I as the sole admin of the server cannot use the same nickname I used for a year just because someone else stole it and joined with it at some point. And I should be able to use the name of my alt account as a nickname. The plugin should never have prevented me from doing it in the first place. Operators should have this power, it wouldn't confuse anyone.

**Comment by mdcfe** [comment]
You can delete userdata for players if you want to use their username as a nickname and they're no longer active. Different accounts are different accounts. As I said before, we're not going to support overriding this for current, active player names.
