### ISSUE TITLE
Kit problem - How is this not fixed already?

### ISSUE THREAD

**Issue by Botanistt** [EssentialsX/Essentials#332]
Hey.
I wanted to create kit with gold spade which had 0 durability. Everything is fine. Then I tried to get kit twice and items were stacked. Thats huge problem in essentials in general that items like armour,tools and potions are beeing stacked instead of beeing placed in other slots.
When I got 2 spades with 0 durability stacked I broke block for funz and 1 spade disappeared (logic) BUT the 2nd one had max durability.

**Comment by Kakifrucht** [comment]
Kits do not stack for me. Only when having the stack permission.

**Comment by drtshock** [comment]
^ this is based on permission.
