### ISSUE TITLE
errors 

### ISSUE THREAD

**Issue by threlief** [EssentialsX/Essentials#3321]
### Information

Full output of `/ess version`:

< Server version: 1.15.2-R0.1-SNAPSHOT git-Spigot-2f5d615-d07a78b (MC: 1.15.2)
 EssentialsX version: 2.17.2.0
PlaceholderAPI version: 2.10.5
LuckPerms version: 5.0.39
 Vault version: 1.7.2-b107
Citizens version: 2.0.26-SNAPSHOT (build 1792)
EssentialsXChat version: 2.17.2.0
EssentialsXXMPP version: 2.17.2.0
EssentialsXProtect version: 2.17.2.0
EssentialsXGeoIP version: 2.17.2.0
 EssentialsXAntiBuild version: 2.17.2.0
EssentialsXSpawn version: 2.17.2.0

**Server log:** 
https://gist.github.com/threlief/50f5a13d6fd5521f77583bc98b035dc8

**EssentialsX config** 
here is the essentials https://gist.github.com/threlief/924dde4a5fa2d7ae277d09e422aeaa8f
here is the ess geoip https://gist.github.com/threlief/a9f70f2ad5b2438388221c3d679ea2c8

### Help request

**Problem**

i just keep getting errors on the geoip and the xmpp manager just wanting to get rid of the errors 

**What I have tried**

finding the latest update and we have it installed tried looking up what the error means but we can not figure it out 
**Screenshots**

**Comment by JRoy** [comment]
Remove EssentialsXXMP, you don't need it. Also it appears you put bungeecord plugin in your plugins folder.

**Comment by threlief** [comment]
we are part of bungee thats y we have bungee plugins

**Comment by threlief** [comment]
also what about the geoip thing it keeps popping up errors

**Comment by JRoy** [comment]
> we are part of bungee thats y we have bungee plugins

you have bungee plugins in a bukkit server, don't do that

> also what about the geoip thing it keeps popping up errors

Delete geoip or configure it properly.
