### ISSUE TITLE
Some of the NBT Tags still aren't saved in /kits.

### ISSUE THREAD

**Issue by MateoNikolic** [EssentialsX/Essentials#3323]
Some of the NBT Tags still aren't saved while creating the kit.
Some examples:

Unsupported flags:
HIDE_ENCHANTS
HIDE_ATTRIBUTES
HIDE_UNBREAKABLE
HIDE_DESTROYS
HIDE_PLACED_ON
HIDE_POTION_EFFECTS

Unsupported attributes:
DAMAGE
MOVEMENT_SPEED
ATTACK_SPEED
KNOCKBACK_RESISTANCE
MAX_HEALTH
LUCK

Unsupported misc:
UNBREAKABLE

Also there are some NBT Tags that are being saved like Armor and Armor Toughness.
This were tested with plugin called MythicMobs, it allows creating custom items with nbt tags.

**Comment by JRoy** [comment]
You literally just copied this from #1105
