### ISSUE TITLE
Label prefixed errors correctly

### ISSUE THREAD

**Issue by partydev** [EssentialsX/Essentials#3326]
### Feature request

**Feature description**
A small amount of errors in the messages.properties file are prefixed, but it is not known which ones are so currently they must all be tested via trial and error. I suggest these be labelled to improve future use.

**How the feature is useful**

Less work when customizing your messages.properties file.

Here is a list of all entries that I found that were prefixed. There are likely many more

- errorWithMessage
- playerNotFound
- warpListPermission
- warpUsePermission
- maxHomes
- unknownItemId
- unknownItemInList
- unknownItemNamecorrectly?
- healDead
- holeInFloor
- nothingInHand

**Comment by JRoy** [comment]
(Most) Messages which start with `\u00a74` are going to be prefixed with the `errorWithMessage` string. Changing the names of the translation keys would be a big hassle so looking out for `\u00a74` is your best bet. In the future, I think we can start to prefix translation keys with error if they are prefixed in that way.
