### ISSUE TITLE
Add Support for Economy Signs to Pull Data from worth.yml

### ISSUE THREAD

**Issue by Techno3600** [EssentialsX/Essentials#3332]
### Feature request

**Feature description**
Add Support for Economy Signs to Pull Data from worth.yml

**How the feature is useful**
It's extremely annoying for server managers like myself to spend a lot of time making a worth.yml only to find that I can't just pull the worth.yml data straight to my signs. I wish there was a way to simply put a placeholder to get whatever the sign is selling/buying from the worth.yml so if you change a value in there, you don't have to go to your shop and manually go and update everything.

**Comment by mdcfe** [comment]
Duplicate of #2638.
