### ISSUE TITLE
/xp take | EssentialsX Bug

### ISSUE THREAD

**Issue by ChaoticKiller** [EssentialsX/Essentials#3333]
### Information

**Full output of `/ess version`**:
> [22:16:46 INFO]: Server version: 1.8.8-R0.2-SNAPSHOT TacoSpigot (MC: 1.8.8)
> [22:16:46 INFO]: EssentialsX version: 2.17.1.48
> [22:16:46 INFO]: PlaceholderAPI version: 2.10.6
> [22:16:46 INFO]: LuckPerms version: 5.0.24
> [22:16:46 INFO]: Vault version: 1.7.2-b107
> [22:16:46 INFO]: Citizens version: 2.0.24-SNAPSHOT (build 1605)
> [22:16:46 INFO]: EssentialsXChat version: 2.17.1.48
> [22:16:46 INFO]: EssentialsXSpawn version: 2.17.1.48

**Server log**: https://gist.github.com/ChaoticKiller/701d5697b9be6ab7619e4d3e2e7fcf61

**EssentialsX config**: https://gist.github.com/ChaoticKiller/b1be29ef4f9820cc956b145e18fd9a99

### Details

**Description**  
When using %player% as a placeholder to take xp away from a player it does not work and says "Error player cannot be found".

**Steps to reproduce**  
1. Go to your Console
2. Type xp take %player% <amount>
3. Hit enter

This command works when doing xp give %player%

**Expected behavior**  
The plugin should be able to take away the experience from the player and should be able to find the player using %player%

**Screenshots**  
Not Necessary.

**Comment by pop4959** [comment]
Can confirm the bug without using placeholders. Essentials itself does not support placeholders currently.

**Comment by Xeyame** [comment]
Found missing part in EssentialsX/Essentials@7adb931ea8dbcc0c37052f3c0e996e8d8b54310e, making PR to fix it

**Comment by Xeyame** [comment]
Fix is in Xeyame/Essentials@136dfc8a50aea457ce5f21f2f2da08e9ace9e602 but seems like something else is messing up as `xp show player` and `xp reset player` require a 3th argument to run
