### ISSUE TITLE
rewrite all the commands that look like they're from the 1800s

### ISSUE THREAD

**Issue by JRoy** [EssentialsX/Essentials#3336]
this code hasn't been touched since java 1.4 and it shows

**Comment by pop4959** [comment]
This can't possibly be finished by the 2.18 milestone

**Comment by JRoy** [comment]
lmao bet

**Comment by darbyjack** [comment]
I thought this said "make all commands look like they were from the 1800s".

**Comment by zml2008** [comment]
ah yes, use 1.16's RGB colours to give every message a sepia tone

**Comment by JRoy** [comment]
![image](https://user-images.githubusercontent.com/10731363/82964889-9c087e80-9f94-11ea-8150-971e124164c2.png)

this color best color
