### ISSUE TITLE
Improvements to EssentialsSpawn commands

### ISSUE THREAD

**Issue by SrBedrock** [EssentialsX/Essentials#3339]
### Information

**Full output of `/ess version`**:

```
[23:11:42 INFO]: Server versão: 1.15.2-R0.1-SNAPSHOT git-Tuinity-"d8b8905" (MC: 1.15.2)
[23:11:42 INFO]: EssentialsX versão: 2.17.2.138
[23:11:42 INFO]: PlaceholderAPI versão: 2.10.6
[23:11:42 INFO]: LuckPerms versão: 5.1.29
[23:11:42 INFO]: Vault versão: 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[23:11:42 INFO]: EssentialsXSpawn versão: 2.17.2.138
```

**Server log**: 

It is not necessary

**EssentialsX config**: 

It is not necessary

### Details

**Description**  

1. Do not suggest `/setspawn` if you do not have `essentials.setspawn` permission;

2. Suggest player names after the `/spawn` command when the player has the `essentials.spawn.others` permission.

**Steps to reproduce**  

1. Without `essentials.setspawn` permission try using the `/setspawn` command;

2. When you have the `essentials.spawn.others` permission the player names are not suggested after `/spawn`

**Expected behavior**  

1. Do not suggest command;

2. Suggest player names.

**Screenshots**  

![image](https://user-images.githubusercontent.com/51332006/83090656-a51a4e00-a06f-11ea-9ee7-d848d4f84b96.png)

**Comment by SrBedrock** [comment]
Perhaps it can be done through the pull request #3337

**Comment by JRoy** [comment]
Nothing we can do here, essentials is unaware of possible group names.

**Comment by mdcfe** [comment]
We *could* add a listGroups method to the permissions plugin handler, but the only use for this would be for `/setspawn` which feels a bit pointless. I'll leave this open to PR but it's not a priority.

**Comment by SrBedrock** [comment]
> Nothing we can do here, essentials is unaware of possible group names.

Could you add at least the two suggestions made to follow the EssentialsX standard?

1. Do not suggest `/setspawn` if you do not have essentials.setspawn permission;
2. Suggest player names after the `/spawn` when the player has the essentials.spawn.others permission.

**Comment by pop4959** [comment]
Could you create a separate feature request for each suggestion? The problem here is that you have several in one issue, which must be kept open or closed together.

**Comment by JRoy** [comment]
> 1. Do not suggest `/setspawn` if you do not have essentials.setspawn permission;

This already doesn't happen or at least shouldn't happen.

> 2. Suggest player names after the `/spawn` when the player has the essentials.spawn.others permission.

This happens in the command rewrite

**Comment by pop4959** [comment]
@JRoy I think the problem with 1. is that the main Essentials plugin handles removing completions for commands that players don't have permission to, however since Spawn is a different module, I'm not entirely sure that this works properly.
