### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by fakename131** [EssentialsX/Essentials#3343]
When I had EssentialsX installed, I ran the command: `/speed 3` or something like that. A few days later, I no longer had a need for EssentialsX so I uninstalled it. After I uninstalled it, I still had the speed effect so I ran the command `/effect clear @s minecraft:speed`, but it gave an error like `No effects found.`. I still have the speed effect and I can't get rid of it.

**Comment by JRoy** [comment]
Speed applies an attribute to the user, not a potion effect. The only way to remove it is to install Essentials again and do `/speed 1`. There really isn't anything Essentials can do for you besides that.
