### ISSUE TITLE
Tiny bug on command /msgtoggle on\off

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#3346]
**Full output of `/ess version`**: [https://pastebin.com/xCqbxikY](url)

### **Description**  
**Hello back! There is a tiny bug or mistake on the /msgtoggle command. So basically when you do `/msg toggle on` it disables the receiving of messages, and when you do `/msgtoggle off` it enables it. The funcionality of the command is in reverse.**

### **Steps to reproduce**  
**/msgtoggle on - It disables the receiving of messages when supposed to enable it**
**/msgtoggle off - It enables the receiving of messages when supposed to disable it**

**Comment by JRoy** [comment]
This is the intended behavior. The command toggles the blocking of messages. If we were to change this, it would break the command for people who rely on the current behavior.
