### ISSUE TITLE
Space upon join

### ISSUE THREAD

**Issue by Blouko** [EssentialsX/Essentials#335]
Greetings,

I have tried to completely remove join messages and the motd although each time I join the game there is a space, only on my screen, not on other's.

Removing join messages in the config by setting them to "none" didn't work so I have installed HideStream.

I would be guessing the space exists because the motd.txt file is empty.

Sincerely,
Victhetiger

**Comment by Kakifrucht** [comment]
This is NoCheatPlus.

**Comment by Blouko** [comment]
No, I don't have NoCheatPlus on my server.

**Comment by Kakifrucht** [comment]
Can you absolutely confirm that this is Essentials related? Try without it installed and with it.

**Comment by Blouko** [comment]
Found it, fixed.

**Comment by EvilOlaf** [comment]
May you tell us how? Maybe others have a similar issue and on this way your solution could be found in Google or other search websites ;)
