### ISSUE TITLE
Prefixes in /motd

### ISSUE THREAD

**Issue by NicBOMB** [EssentialsX/Essentials#3350]
### Information

**Full output of `/ess version`**:

```
> ess version
[17:04:12 INFO]: CONSOLE issued server command: /ess version
[17:04:12 INFO]: Server version: 1.14.4-R0.1-SNAPSHOT git-Paper-243 (MC: 1.14.4)
[17:04:12 INFO]: EssentialsX version: 2.17.2.110
[17:04:12 INFO]: LuckPerms version: 5.1.32
[17:04:12 INFO]: Vault version: 1.7.2-b107
[17:04:12 INFO]: EssentialsXProtect version: 2.17.2.110
[17:04:12 INFO]: EssentialsXChat version: 2.17.2.110
[17:04:12 INFO]: EssentialsXAntiBuild version: 2.17.2.110
[17:04:12 INFO]: EssentialsXSpawn version: 2.17.2.110
```

**Server log**: https://gist.github.com/NicBOMB/b0bd97945a7c02a78b1081d34663a3fb

**EssentialsX config**: https://gist.github.com/NicBOMB/711eab96c0fea198feadada43e721a5e

### Details

**Description**  
Prefixes do not load in motd upon server start. After starting the server with ess version 2.17.2.77 and 2.17.2.110 then running '/essentials reload' prefixes are added.
**Steps to reproduce**  
Line in motd in question: {PLAYER}&6, you are in the &9{WORLD}&6.
Also tried: {DISPLAYNAME}&6, you are in the &9{WORLD}&6.
And: {PREFIX}{PLAYER}&6, you are in the &9{WORLD}&6.
**Expected behavior && Screenshots**  
Expected the {PLAYER} or {DISPLAYNAME} placeholders to be replaced with a joining player's username with prefixes applied or {PREFIX} to contain the luckperms provided prefixes.
It should look like this: 
![image](https://user-images.githubusercontent.com/19939315/83366199-61229400-a362-11ea-8055-f903588fa09b.png)
But I got this:
![image](https://user-images.githubusercontent.com/19939315/83366376-8532a500-a363-11ea-8a99-ae2010281c53.png)
I then ran:
![image](https://user-images.githubusercontent.com/19939315/83366385-9aa7cf00-a363-11ea-8caa-e1c8d3e20032.png)
and the next /motd in that image produced this output:
![image](https://user-images.githubusercontent.com/19939315/83366398-aeebcc00-a363-11ea-88fc-14fcb1a24b84.png)
Which showed that my username had been updated to include the prefixes provided by luckperms.

I would like to not need to /essentials reload in order to get my prefix to load in /motd. 
This inconsistent /motd prefixing is obviously a small bug.

**Comment by triagonal** [comment]
I can't seem to replicate this issue on my end. The prefix is retrieved successfully without needing a reload.
```
[20:36:07 INFO]: CONSOLE issued server command: /ess version
[20:36:07 INFO]: Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-334 (MC: 1.15.2)
[20:36:07 INFO]: EssentialsX version: 2.17.2.110
[20:36:07 INFO]: LuckPerms version: 5.1.43
[20:36:07 INFO]: Vault version: 1.7.2-b107
[20:36:07 INFO]: EssentialsXChat version: 2.17.2.110
```
When testing with your config, the motd `"{DISPLAYNAME}&6, you are in the &9{WORLD}&6."` along with your join message displays correctly upon initial join:

![image](https://user-images.githubusercontent.com/10545540/83627392-304c9400-a5da-11ea-9126-23afbcda87ff.png)

As for your `{PREFIX}` issue, the `{PREFIX}` placeholder exists only for the EssentialsXChat chat formatting section, not for the [help files](https://wiki.mc-ess.net/wiki/Help_Files), which explains why it isn't working in the motd.

**Comment by NicBOMB** [comment]
I think I had some weird configuration issue. I logged in using another account (with default permissions on a separate device) and the player logged in, saw their 'prefixed username connected line' and motd all correctly displaying prefixes. I realized it must have been a permission error with my 'owner' group, so I removed all permissions except for prefixes, weights, and parents from 'owner'. I logged in and sure enough my problem went away. What's weird is when I gave myself wildcard permissions for plugins, the problem didn't return. Example: I now have all plugins with commands set to [plugin].* in the group (a terrible idea but it hits home the next point) and when I login it gives me the correct prefixes in connection and motd messages. I don't know if some other buried/nested permission setting was interfering with my group's chat messages, but the wildcard seems to not have triggered the issue. I definitely don't recommend using any wildcard permissions in the first place, but I thought they might have been useful for testing here. I don't know why the problem occurred nor do I care since my problem was resolved after flushing my permissions and starting from scratch. It's unfortunate I have to redo my permissions, but I hope this helps anyone else running into motd player name issues.

**Comment by pop4959** [comment]
You can also try using LuckPerms' verbose feature to try to find stray permissions if this happens again. If it's permission related you might be able to find what is triggering when people join.

**Comment by NicBOMB** [comment]
> You can also try using LuckPerms' verbose feature to try to find stray permissions if this happens again. If it's permission related you might be able to find what is triggering when people join.

It's funny you mention that since I had used verbose to setup my permissions in the first place. I must have overlooked something and caused the issue. I'll update this thread if I can replicate the issue in the future, but resetting my permissions fixed it. (literally "lp group owner permission unset" for each node then 'set' again). I have exactly the same permissions as previously, but 'owner' now gets the correct prefix. I'll reopen if the issue comes back, and close again with an updated solution.
