### ISSUE TITLE
Server crashing when players teleport (Paper)

### ISSUE THREAD

**Issue by MithrandirCraft** [EssentialsX/Essentials#3351]
### Information

**Full output of `/ess version`**:
```
[18:04:15 INFO]: CONSOLE issued server command: /ess version
[18:04:15 INFO]: Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-333 (MC: 1.15.2)
[18:04:15 INFO]: EssentialsX version: 2.17.2.0
[18:04:15 INFO]: LuckPerms version: 5.1.26
[18:04:15 INFO]: PlaceholderAPI version: 2.10.6
[18:04:15 INFO]: Vault version: 1.7.2-b107
[18:04:15 INFO]: EssentialsXSpawn version: 2.17.2.0
```

**Server log**:
Paper's watchdog report during crash, after various teleportations occur (commands included): 
https://gist.github.com/MithrandirCraft/64358f18970dc4875ab90f16f856b497

**EssentialsX config**: https://gist.github.com/MithrandirCraft/83736b5fdc1cef95e64da6abf230d9e5

### Details

**Description**  
The server starts to lag, and then eventually crashes. I understand some timings may be convenient for further analizing this, but keep in mind it's quite hard to get them without being capable of keeping a constant watch on when the server is going to crash.

This may actually have some relation with essentials still not fully supporting asincronous chunk loading on teleportation, as described here: https://github.com/EssentialsX/Essentials/pull/3102
but since I'm not entirely sure, I decided I'd just make a separate report.

**Steps to reproduce**  
Just start the server with essentials installed and have some players teleport around simultaneously.
My server usually tends to crash once or twice a day, it can't really be reproduced consistently with the described method of teleporting, but the crash ALWAYS occurs after essentials teleportations.

**Expected behavior**  
Server shouldn't crash for just a few teleportations.

**Comment by JRoy** [comment]
I have doubts that this is caused by Essentials teleport code (or Essentials at all as I don't see essentials' packages in the thread stack dumps) but you should try out the public test build for async teleportation here: https://github.com/EssentialsX/Essentials/pull/3102#issuecomment-636377539
