### ISSUE TITLE
AFK not cancelled on chat event when "cancel-afk-on-interact" is false

### ISSUE THREAD

**Issue by EvModder** [EssentialsX/Essentials#3353]
### Information

**Full output of `/ess version`**:
```
[21:15:09 INFO]: Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-333 (MC: 1.15.2)
[21:15:09 INFO]: EssentialsX version: 2.17.2.45
[21:15:09 INFO]: Vault is not installed. Chat and permissions may not work.
```

**Server log**: not needed
**EssentialsX config**: not needed

### Details

**Description**  
I think this behavior should be changed.
Currently, if `cancel-afk-on-move: true` and `cancel-afk-on-interact: false` in the config, the player will be leave AFK state on move, but not for chat, despite the comments in the Ess config implying otherwise

**Steps to reproduce**  
Set two config values as specified above

**Expected behavior**  
Interact event cancel includes clicking blocks etc, but not chat

Possibly could also rephrase this GitHub Issue as a feature request instead, to separate out a config setting for `cancel-afk-on-chat-or-command` to distinguish from `cancel-afk-on-interact`... thoughts?

**Comment by Laarryy** [comment]
I believe interact is meant to be any form of server interaction, of which chat is arguably a part. Changing this to a feature request for a `cancel-afk-on-chat` toggle in the config, unless others would like to chime in?
