### ISSUE TITLE
/weather storm does not make a storm

### ISSUE THREAD

**Issue by MODKILLER1001** [EssentialsX/Essentials#3356]
### Information

**Full output of `/ess version`**: I cannot use this command on the server I am on

```
<!-- Run the command in your console, and copy and paste the whole output here -->
```

**Server log**: 

**EssentialsX config**: 

### Details

**Description**  

doing /weather storm makes it rain, it does not thunder.
**Steps to reproduce**  

https://github.com/EssentialsX/Essentials/issues/2160
**Expected behavior**  

It should cause it to thunder, not just rain
**Screenshots**

**Comment by pop4959** [comment]
Not a bug. Use `/thunder` to make it thunder. `/weather` only changes the weather from clear (sunny) to rain (stormy).

**Comment by MODKILLER1001** [comment]
Just look at issue https://github.com/EssentialsX/Essentials/issues/2160

**Comment by pop4959** [comment]
I have looked at it. What is the issue? Both commands appear to work as expected.

**Comment by MODKILLER1001** [comment]
I do not get lightning when i do /weather storm

**Comment by pop4959** [comment]
`/weather storm` is not intended to create thunder. That is the `/thunder` command, as mentioned above. This is how it has always worked, and it is *not* a bug.

**Comment by MODKILLER1001** [comment]
thank you

**Comment by MODKILLER1001** [comment]
I was just confused since https://minecraft.gamepedia.com/Commands/weather said differently.

**Comment by pop4959** [comment]
Essentials `/weather` command has existed for much longer than Vanilla Minecraft's (which might have copied the idea from Essentials 😛 ). This is why the terminology is a bit inconsistent. We cannot easily rename these commands anymore because it would confuse people who are already used to how it works normally. If you want to use the Vanilla command, type `/minecraft:weather thunder`. Hope that clears things up for you.

**Comment by VL4DST3R** [comment]
Will this ever be implemented? As it is now essentials command is objectively inferior to the vanilla one, and we have to override it to access it which is quite annoying.
