### ISSUE TITLE
Can't teleport to a bed where the chunks are unloaded

### ISSUE THREAD

**Issue by MCHalfAssed** [EssentialsX/Essentials#3357]
### Information

**Full output of `/ess version`**:

```
[Fri, 5. Jun 2020 03:43:15 GMT INFO] Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-334 (MC: 1.15.2)
[Fri, 5. Jun 2020 03:43:15 GMT INFO] EssentialsX version: 2.17.1.52
[Fri, 5. Jun 2020 03:43:15 GMT INFO] PlaceholderAPI version: 2.10.6
[Fri, 5. Jun 2020 03:43:15 GMT INFO] PermissionsEx version: 1.23.4
[Fri, 5. Jun 2020 03:43:15 GMT INFO] Vault version: 1.7.2-b107
[Fri, 5. Jun 2020 03:43:15 GMT INFO] Citizens version: 2.0.26-SNAPSHOT (build 1979)
[Fri, 5. Jun 2020 03:43:15 GMT INFO] EssentialsXProtect version: 2.17.1.52
[Fri, 5. Jun 2020 03:43:15 GMT INFO] EssentialsXSpawn version: 2.17.1.52
[Fri, 5. Jun 2020 03:43:15 GMT INFO] You are running unsupported plugins!
[Fri, 5. Jun 2020 03:43:15 GMT INFO] You are running an unsupported server version!
```

**Server log**: Not relevant 

**EssentialsX config**: Not relevant 
### Details

**Description**  
If the chunks are not loaded, using /home :bed gives a "Error: Your bed is either unset, missing, or blocked."

If I manually teleport to the bed, and then use the command again, it successfully teleports me to the designated bed with no errors.

**Steps to reproduce**  
Video of the bug - https://www.youtube.com/watch?v=kUQDnLRrl5M

**Expected behavior**  
Using /home :bed takes me to the bed that the player last set their home at using a bed.

**Screenshots**  
https://www.youtube.com/watch?v=kUQDnLRrl5M

**Comment by pop4959** [comment]
You're over 100+ updates behind. I'm not able to reproduce this on the latest version.

**Comment by JRoy** [comment]
As mentioned by @pop4959 you're over 100 builds out of date, please update your essentials or use the test build for async teleporting here: https://github.com/EssentialsX/Essentials/pull/3102#issuecomment-636377539 

Edit: I can also not reproduce on either builds

**Comment by MCHalfAssed** [comment]
I have updated to the latest version and I'm still running into this issue exactly the same way as before. Current version now - 

[Fri, 5. Jun 2020 04:37:51 GMT INFO] CONSOLE issued server command: /ess ver
[Fri, 5. Jun 2020 04:37:51 GMT INFO] Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-334 (MC: 1.15.2)
[Fri, 5. Jun 2020 04:37:51 GMT INFO] EssentialsX version: 2.17.2.111
[Fri, 5. Jun 2020 04:37:51 GMT INFO] PlaceholderAPI version: 2.10.6
[Fri, 5. Jun 2020 04:37:51 GMT INFO] PermissionsEx version: 1.23.4
[Fri, 5. Jun 2020 04:37:51 GMT INFO] Vault version: 1.7.2-b107
[Fri, 5. Jun 2020 04:37:51 GMT INFO] Citizens version: 2.0.26-SNAPSHOT (build 1979)
[Fri, 5. Jun 2020 04:37:51 GMT INFO] EssentialsXProtect version: 2.17.2.111
[Fri, 5. Jun 2020 04:37:51 GMT INFO] EssentialsXSpawn version: 2.17.2.111
[Fri, 5. Jun 2020 04:37:51 GMT INFO] You are running unsupported plugins!



Would you like me to make another video showing the latest version as proof?

**Comment by MCHalfAssed** [comment]
**EDIT - Just saw the  async pr, will be trying that now. Sorry for the trouble.

**Comment by MCHalfAssed** [comment]
Alright, I tried both the latest version AND test version;
[Fri, 5. Jun 2020 04:54:59 GMT INFO] CONSOLE issued server command: /ess ver
[Fri, 5. Jun 2020 04:54:59 GMT INFO] Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-334 (MC: 1.15.2)
[Fri, 5. Jun 2020 04:54:59 GMT INFO] EssentialsX version: test-async-teleport.1
[Fri, 5. Jun 2020 04:54:59 GMT INFO] PlaceholderAPI version: 2.10.6
[Fri, 5. Jun 2020 04:54:59 GMT INFO] PermissionsEx version: 1.23.4
[Fri, 5. Jun 2020 04:54:59 GMT INFO] Vault version: 1.7.2-b107
[Fri, 5. Jun 2020 04:54:59 GMT INFO] Citizens version: 2.0.26-SNAPSHOT (build 1979)
[Fri, 5. Jun 2020 04:54:59 GMT INFO] EssentialsXProtect version: test-async-teleport.1
[Fri, 5. Jun 2020 04:54:59 GMT INFO] EssentialsXSpawn version: test-async-teleport.1
[Fri, 5. Jun 2020 04:54:59 GMT INFO] You are running unsupported plugins!

Still was having the same issue. Can we re-open this ticket? Or shall I make another?

**Comment by pop4959** [comment]
Can you try to replicate this without any other plugins installed *except for Essentials*. If it is still not working I will re-open this issue for the time being.

**Comment by MCHalfAssed** [comment]
I believe I just now solved it. In my test server, I wasn't having the issue.

So in the real server, I removed the bed. Placed a new one. And now the issue is gone. Not sure exactly what was happening here, but at least it's solved now. Thanks for the support.

**Comment by MCHalfAssed** [comment]
Alright, this is just plain odd. I'm sorry to loop you back in, but please watch this video of the bug happening again and let me know what you think. Obviously, this player will survive just fine with moving his bed over two blocks. However, I would like to know if this issue is caused by essentials or perhaps maybe some chunk corruption? 

https://youtu.be/LrVK9GUIaUs

**Comment by pop4959** [comment]
Not sure, maybe the way you've placed the beds makes Essentials think it's blocked.
