### ISSUE TITLE
Add quartz to /condense

### ISSUE THREAD

**Issue by DjeyMute** [EssentialsX/Essentials#3360]
Hello,

I have a simple request.
I would simply add the quartz in the /condense.
All the minerals are already present except him, so many players wonder why it is not condensed.

Thank you in advance.

**Comment by mdcfe** [comment]
`/condense` only condenses reversible recipes (that is, where you can craft 4/9 items -> 1 block **and** 1 block -> 4/9 items).

If you want `/condense` to condense quartz into quartz blocks, add a datapack recipe to make quartz blocks craftable to quartz items.
