### ISSUE TITLE
extended /seen permissions

### ISSUE THREAD

**Issue by MODKILLER1001** [EssentialsX/Essentials#3362]
### Feature request

**Feature description**

Adding more support for /seen permissions

**How the feature is useful**

Some servers do not want people to see if others are jailed or muted and /seen makes them see it. Having a permission or something to see if they are jailed or muted like essentials.seen.punish would help.

**Comment by pop4959** [comment]
Can you be more specific as to exactly which things you think should be blocked by a permission and why? Is it just jail and mute?
