### ISSUE TITLE
Essentials Kits Book give 

### ISSUE THREAD

**Issue by okamiesport** [EssentialsX/Essentials#3365]
### Information

Full output of `/ess version`:

**Server log:** 

No logs
**EssentialsX config** 

### Help request

**Problem**

I'm trying to give the Book named "Colors" on my welcome kit. I'm using this code:
kits:
  bienvenue:
    delay: -1
    items:
    - stone_sword 1
    - stone_pickaxe 1
    - stone_axe 1
    - stone_shovel 1
    - bread 30
    - torch 20
    - leather_helmet 1
    - leather_chestplate 1
    - leather_leggings 1
    - leather_boots 1
    - book:Colors 1

**What I have tried**

I tried     - book:Colors and a lot of others, still don't give the book and says that "The kit is not good defined try to contact an administator"

Can you guys help me ? Huge thanks

**Comment by editid0** [comment]
use discord

**Comment by mdcfe** [comment]
You need to follow the [book item meta format](https://wiki.mc-ess.net/wiki/Item_Meta#Books), which is as follows:
```yaml
- written_book title:Colors author:Mr_Author book:Colors 
```

You can optionally include `lore:` or other metadata too, but you must include a title and author.
