### ISSUE TITLE
Powertool triggers on right click air with throwables

### ISSUE THREAD

**Issue by GriffinCodes** [EssentialsX/Essentials#3368]
### Information

**Full output of `/ess version`**:
![image](https://user-images.githubusercontent.com/12417961/84326617-5d092a00-ab4b-11ea-8c4f-e8b1cea36409.png)

### Details

**Description**  
Powertools trigger on right click with throwables and honey bottles (maybe more, idk). This is caused by https://hub.spigotmc.org/jira/browse/SPIGOT-5435 - in short, playerinteractevent is wrong.

```	@EventHandler
	public void onPlayerInteract(final PlayerInteractEvent event) {
		BNCore.log("interact event: action: " + event.getAction() + " / hand: " + event.getHand());
	}
```
Throwing one snowball (one right click of mouse):
```
[18:42:33] [Server thread/INFO]: [BNCore] interact event: action: RIGHT_CLICK_AIR / hand: HAND
[18:42:33] [Server thread/INFO]: [BNCore] interact event: action: LEFT_CLICK_AIR / hand: HAND
```
Since this is an upstream bug that's marked as invalid, any fix would have to be a workaround at the plugin level. Not expecting a fix, but figured it was worth mentioning.

**Steps to reproduce**  
- Assign a powertool to a snowball/potion/expbottle/any throwable (or honeybottle)
- Throw the projectile with right click
- Powertool is activated

**Expected behavior**  
- Powertool doesnt activate (left click only)

**Comment by pop4959** [comment]
Not sure if this is important enough to fix in Essentials, because I wouldn't expect many people to be trying to user power tools with projectiles. Definitely weird though that upstream throws a left click event for what is actually a right click.

**Comment by pop4959** [comment]
Essentials already filters the event to left click, and there isn't otherwise any way to distinguish between them, other than some nasty hackery.
