### ISSUE TITLE
Help Request

### ISSUE THREAD

**Issue by RocketManKian** [EssentialsX/Essentials#3372]
### Information

Full output of `/ess version`: N/A

**Server log:** N/A

**EssentialsX config** N/A

### Help request

**Problem**
What problem did you encounter? Hi there! This isn't really a problem just a support case. I was just wondering if it's possibly for essentials commands (specifically essentials economy) to work with command blocks in the following way. So I want to use the /execute command to basically have a way of tracking when players reach '£0' I was wondering if there is a command or way to track that. Thanks a lot!

**What I have tried**
What have you tried so far? The /sudo command and tried installing different plugins too but no luck unfortunately.

**Screenshots**
If relevant, include any screenshots here. N/A

**Comment by pop4959** [comment]
Not really, it isn't intended to be used in this way. You probably want to get / make another plugin that tracks when the balance reaches zero.

**Comment by mdcfe** [comment]
To clarify: EssentialsX doesn't have a feature to automatically run a command when a player's balance drops below a certain amount. Another plugin could, however, listen to EssentialsX's `UserBalanceUpdateEvent` and run a command. This is quite a trivial feature but it's too niche to include in EssentialsX.
