### ISSUE TITLE
Backport for 1.7.10

### ISSUE THREAD

**Issue by emkirsh** [EssentialsX/Essentials#3373]
### Feature request

**Feature description**

I'd love to see a backport to 1.7.10 for those who want to play on modpacks with KCauldron or Thermos, but want LuckPerms instead of PEX.

**How the feature is useful**

This is useful to server owners and players because despite how old it is, 1.7.10 is still a very popular modding version. Some finished mods that no longer receive updates are only available for 1.7.10, and the ability to have an updated EssentialsX plugin would make people's lives 1000% easier. Sponge didn't start until 1.8, so there isn't a 1.7.10 version, but Essentials is a classic plugin whose backwards compatibility would allow for a much greater experience with mods! No need to pick between an outdated plugin and LuckPerms! You don't even have to include the spawner fixes in the 1.7.10 version! We just need a working version of Essentials that recognizes LuckPerms!

**Comment by JRoy** [comment]
No :D

You can use classic Essentials, EssentialsX has no interest on maintaining yet another version which is many years old.
