### ISSUE TITLE
Cant start server

### ISSUE THREAD

**Issue by MrKubaCZ3** [EssentialsX/Essentials#3374]
10:15:19[ERROR] The server has stopped responding! This is (probably) not a Paper bug.
10:15:19[ERROR] If you see a plugin in the Server thread dump below, then please report it to that author
10:15:19[ERROR] *Especially* if it looks like HTTP or MySQL operations are occurring
10:15:19[ERROR] If you see a world save or edit, then it means you did far more than your server can handle at once
10:15:19[ERROR] If this is the case, consider increasing timeout-time in spigot.yml but note that this will replace the crash with LARGE lag spikes
10:15:19[ERROR] If you are unsure or still think this is a Paper bug, please report this to https://github.com/PaperMC/Paper/issues
10:15:19[ERROR] Be sure to include ALL relevant console errors and Minecraft crash reports
10:15:19[ERROR] Paper version: git-Paper-192 (MC: 1.15.2)
10:15:19[ERROR] Server thread dump (Look for plugins here before reporting to Paper!):
10:15:19[ERROR] Current Thread: Server thread
10:15:19[ERROR] PID: 17 | Suspended: false | Native: false | State: RUNNABLE
10:15:19[ERROR] Stack:
10:15:19[ERROR] java.io.FileInputStream.available0(Native Method)
10:15:19[ERROR] java.io.FileInputStream.available(FileInputStream.java:306)
10:15:19[ERROR] sun.nio.cs.StreamDecoder.inReady(StreamDecoder.java:363)
10:15:19[ERROR] sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:324)
10:15:19[ERROR] sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
10:15:19[ERROR] java.io.InputStreamReader.read(InputStreamReader.java:184)
10:15:19[ERROR] java.io.BufferedReader.fill(BufferedReader.java:161)
10:15:19[ERROR] java.io.BufferedReader.readLine(BufferedReader.java:324)
10:15:19[ERROR] java.io.BufferedReader.readLine(BufferedReader.java:389)
10:15:19[ERROR] org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:152)
10:15:19[ERROR] org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128)
10:15:19[ERROR] org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:183)
10:15:19[ERROR] cz.thezak.Warps.Utils.ConfigFile.<init>(ConfigFile.java:19)
10:15:19[ERROR] cz.thezak.Warps.Main.config(Main.java:100)
10:15:19[ERROR] cz.thezak.Warps.Main.onEnable(Main.java:84)
10:15:19[ERROR] org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
10:15:19[ERROR] org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364)
10:15:19[ERROR] org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
10:15:19[ERROR] org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470)
10:15:19[ERROR] org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384)
10:15:19[ERROR] net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488)
10:15:19[ERROR] net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
10:15:19[ERROR] net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908)
10:15:19[ERROR] java.lang.Thread.run(Thread.java:748)
10:15:19[ERROR] Entire Thread Dump:
10:15:19[ERROR] Current Thread: HikariPool-1 housekeeper
10:15:19[ERROR] PID: 71 | Suspended: false | Native: false | State: TIMED_WAITING
10:15:19[ERROR] sun.misc.Unsafe.park(Native Method)
10:15:19[ERROR] java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
10:15:19[ERROR] java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
10:15:19[ERROR]
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
10:15:19[ERROR] java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
10:15:19[ERROR] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
10:15:19[ERROR] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
10:15:19[ERROR] Current Thread: Keep-Alive-Timer
10:15:19[ERROR] PID: 70 | Suspended: false | Native: false | State: TIMED_WAITING
Stack:
10:15:19[ERROR] java.lang.Thread.sleep(Native Method)
10:15:19[ERROR] sun.net.www.http.KeepAliveCache.run(KeepAliveCache.java:172)
10:15:19[ERROR] Current Thread: pool-21-thread-1
10:15:19[ERROR] PID: 68 | Suspended: false | Native: false | State: WAITING
10:15:19[ERROR] java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
10:15:19[ERROR] java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
10:15:19[ERROR] java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
10:15:19[ERROR] ------------------------------
10:15:19[ERROR] Current Thread: Thread-26
10:15:19[ERROR] PID: 67 | Suspended: false | Native: true | State: RUNNABLE
10:15:19[ERROR] sun.nio.fs.LinuxWatchService.poll(Native Method)
10:15:19[ERROR] sun.nio.fs.LinuxWatchService.access$600(LinuxWatchService.java:47)
10:15:19[ERROR] sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:314)
10:15:19[ERROR] Current Thread: Thread-25
10:15:19[ERROR] PID: 66 | Suspended: false | Native: true | State: RUNNABLE
sun.nio.fs.LinuxWatchService.poll(Native Method)
10:15:19[ERROR] Current Thread: Thread-24
10:15:19[ERROR] PID: 65 | Suspended: false | Native: true | State: RUNNABLE
10:15:19[ERROR] Stack:
10:15:19[ERROR] Current Thread: Thread-23
10:15:19[ERROR] PID: 64 | Suspended: false | Native: true | State: RUNNABLE
10:15:19[ERROR] Current Thread: Thread-22
10:15:19[ERROR] PID: 63 | Suspended: false | Native: true | State: RUNNABLE
10:15:19[ERROR] Current Thread: Thread-21
10:15:19[ERROR] PID: 62 | Suspended: false | Native: true | State: RUNNABLE
10:15:19[ERROR] Current Thread: mysql-cj-abandoned-connection-cleanup
10:15:19[ERROR] PID: 61 | Suspended: false | Native: false | State: TIMED_WAITING
10:15:19[ERROR] java.lang.Object.wait(Native Method)
10:15:19[ERROR] java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
10:15:19[ERROR] com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:80)
10:15:19[ERROR] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
10:15:19[ERROR] Current Thread: ExpiringMap-Expirer
10:15:19[ERROR] PID: 60 | Suspended: false | Native: false | State: TIMED_WAITING
10:15:19[ERROR] java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
10:15:19[ERROR] java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
10:15:19[ERROR] Current Thread: Paper RegionFile IO Thread
10:15:19[ERROR] PID: 59 | Suspended: false | Native: false | State: WAITING
com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)
10:15:19[ERROR] Current Thread: Paper Async Task Handler Thread - 0
10:15:19[ERROR] PID: 58 | Suspended: false | Native: false | State: WAITING
10:15:19[ERROR] Current Thread: ViaRewind-1_8TO1_9
10:15:19[ERROR] PID: 57 | Suspended: false | Native: false | State: WAITING
10:15:19[ERROR] java.lang.Object.wait(Object.java:502)
10:15:19[ERROR] java.util.TimerThread.mainLoop(Timer.java:526)
10:15:19[ERROR] java.util.TimerThread.run(Timer.java:505)
10:15:19[ERROR] Current Thread: Thread-18
10:15:19[ERROR] PID: 56 | Suspended: false | Native: true | State: RUNNABLE
10:15:19[ERROR] java.lang.Thread.run(Thread.java:748)
10:15:19[ERROR] Current Thread: Thread-17
10:15:19[ERROR] PID: 55 | Suspended: false | Native: true | State: RUNNABLE
10:15:19[ERROR]
10:15:19[ERROR] Current Thread: Thread-16
10:15:19[ERROR] PID: 54 | Suspended: false | Native: true | State: RUNNABLE
10:15:19[ERROR] Thread is waiting on monitor(s):
10:15:19[ERROR] Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
10:15:19[ERROR] sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
10:15:19[ERROR] sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
10:15:19[ERROR] sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
10:15:19[ERROR] sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
10:15:19[ERROR] sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
10:15:19[ERROR] sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:352)
10:15:19[ERROR] Current Thread: server-timer
10:15:19[ERROR] PID: 53 | Suspended: false | Native: false | State: TIMED_WAITING
10:15:19[ERROR] java.util.TimerThread.mainLoop(Timer.java:552)
10:15:19[ERROR] Current Thread: pool-7-thread-1
10:15:19[ERROR] PID: 45 | Suspended: false | Native: false | State: WAITING
10:15:19[ERROR] sun.misc.Unsafe.park(Native Method)
10:15:19[ERROR] java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
10:15:19[ERROR] java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
10:15:19[ERROR] java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
10:15:19[ERROR] java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
10:15:19[ERROR] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
10:15:19[ERROR] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
10:15:19[ERROR] ------------------------------
10:15:19[ERROR] Current Thread: Thread-14
10:15:19[ERROR] PID: 44 | Suspended: false | Native: true | State: RUNNABLE
10:15:19[ERROR] sun.nio.fs.LinuxWatchService.poll(Native Method)
10:15:19[ERROR] sun.nio.fs.LinuxWatchService.access$600(LinuxWatchService.java:47)
10:15:19[ERROR] sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:314)
10:15:19[ERROR] Current Thread: Timer-1
10:15:19[ERROR] PID: 43 | Suspended: false | Native: false | State: TIMED_WAITING
10:15:19[ERROR] Stack:
10:15:19[ERROR] Current Thread: Thread-12
PID: 42 | Suspended: false | Native: true | State: RUNNABLE
10:15:19[ERROR] Current Thread: Thread-11
10:15:19[ERROR] PID: 38 | Suspended: false | Native: true | State: RUNNABLE
10:15:19[ERROR] Current Thread: Thread-10
10:15:19[ERROR] PID: 37 | Suspended: false | Native: true | State: RUNNABLE
10:15:19[ERROR] Current Thread: TConfigWatcherService-1
10:15:19[ERROR] PID: 36 | Suspended: false | Native: false | State: TIMED_WAITING
10:15:19[ERROR] java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
10:15:19[ERROR] java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
10:15:19[ERROR] Current Thread: Netty Epoll Server IO #0
10:15:19[ERROR] PID: 35 | Suspended: false | Native: true | State: RUNNABLE
10:15:19[ERROR] io.netty.channel.epoll.Native.epollWait0(Native Method)
10:15:19[ERROR] io.netty.channel.epoll.Native.epollWait(Native.java:114)
10:15:19[ERROR] io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:239)
10:15:19[ERROR] io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:256)
10:15:19[ERROR] io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
10:15:19[ERROR] Current Thread: ObjectCleanerThread
10:15:19[ERROR] PID: 34 | Suspended: false | Native: false | State: TIMED_WAITING
java.lang.Object.wait(Native Method)
10:15:19[ERROR] java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
10:15:19[ERROR] io.netty.util.internal.ObjectCleaner$1.run(ObjectCleaner.java:54)
10:15:19[ERROR] io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
10:15:19[ERROR] Current Thread: Timer-0
10:15:19[ERROR] PID: 33 | Suspended: false | Native: false | State: TIMED_WAITING
10:15:19[ERROR] java.lang.Object.wait(Native Method)
10:15:19[ERROR] java.util.TimerThread.run(Timer.java:505)
10:15:19[ERROR] Current Thread: Paper Watchdog Thread
10:15:19[ERROR] PID: 32 | Suspended: false | Native: false | State: RUNNABLE
10:15:19[ERROR] sun.management.ThreadImpl.dumpThreads0(Native Method)
10:15:19[ERROR] sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:454)
10:15:19[ERROR] org.spigotmc.WatchdogThread.run(WatchdogThread.java:125)
10:15:19[ERROR] Current Thread: Paper Async Chunk Urgent Task Thread
10:15:19[ERROR] PID: 31 | Suspended: false | Native: false | State: WAITING
10:15:19[ERROR] com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)
10:15:19[ERROR] Current Thread: Paper Async Chunk Task Thread #2
10:15:19[ERROR] PID: 30 | Suspended: false | Native: false | State: WAITING
10:15:19[ERROR] Current Thread: Paper Async Chunk Task Thread #1
10:15:19[ERROR] PID: 29 | Suspended: false | Native: false | State: WAITING
10:15:19[ERROR]
sun.misc.Unsafe.park(Native Method)
10:15:19[ERROR] Current Thread: Paper Async Chunk Task Thread #0
10:15:19[ERROR] PID: 28 | Suspended: false | Native: false | State: WAITING
10:15:19[ERROR] Current Thread: Java2D Disposer
10:15:19[ERROR] PID: 26 | Suspended: false | Native: false | State: WAITING
10:15:19[ERROR] java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
10:15:19[ERROR] sun.java2d.Disposer.run(Disposer.java:148)
10:15:19[ERROR] java.lang.Thread.run(Thread.java:748)
10:15:19[ERROR] Current Thread: Server console handler
10:15:19[ERROR] PID: 21 | Suspended: false | Native: false | State: RUNNABLE
10:15:19[ERROR] java.io.FileInputStream.read0(Native Method)
10:15:19[ERROR] java.io.FileInputStream.read(FileInputStream.java:207)
10:15:19[ERROR] org.jline.terminal.impl.AbstractPty$PtyInputStream.read(AbstractPty.java:73)
10:15:20[INFO] Stopping server
10:15:20[ERROR] [Essentials] java.lang.ThreadDeath
10:15:20[WARN] java.lang.ThreadDeath
10:15:20[WARN]
at java.lang.Thread.stop(Thread.java:853)
10:15:20[WARN] at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:745)
10:15:20[WARN] at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:752)
10:15:20[WARN] at net.minecraft.server.v1_15_R1.MinecraftServer.close(MinecraftServer.java:724)
10:15:20[WARN] at org.spigotmc.WatchdogThread.run(WatchdogThread.java:155)
10:15:20[ERROR] Error occurred while enabling Essentials v2.17.2.0 (Is it up to date?)
java.lang.NullPointerException: null
at com.earth2me.essentials.Essentials.onDisable(Essentials.java:371) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[server.jar:git-Paper-192]
at com.earth2me.essentials.Essentials.handleCrash(Essentials.java:733) ~[?:?]
at com.earth2me.essentials.Essentials.onEnable(Essentials.java:303) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:git-Paper-192]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[server.jar:git-Paper-192]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[server.jar:git-Paper-192]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[server.jar:git-Paper-192]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[server.jar:git-Paper-192]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[server.jar:git-Paper-192]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[server.jar:git-Paper-192]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[server.jar:git-Paper-192]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]

**Comment by triagonal** [comment]
It looks like this is being caused by whichever plugin `cz.thezak.Warps` belongs to - likely your warps plugin. Try again without this plugin installed.

If you can reproduce this issue with **only** EssentialsX installed, then we'll be able to assist you further on the [MOSS discord support server](https://discord.gg/PHpuzZS).

**Comment by MrKubaCZ3** [comment]
Thanks, closed.
