### ISSUE TITLE
Helpop translate

### ISSUE THREAD

**Issue by Bricec6** [EssentialsX/Essentials#3376]
![image](https://user-images.githubusercontent.com/51750055/84573829-2e858c00-ada3-11ea-9ffa-11caaaede4e2.png)

**Feature description**
Hello I noticed that there is no line to translate the sentences on the screenshot.

**How the feature is useful**
This feature will allow us to translate well for our players or to add nice colors.

thank you

EDIT:
Same for:
![image](https://user-images.githubusercontent.com/51750055/84573906-9b008b00-ada3-11ea-9ddb-4556d20254e6.png)

**Comment by pop4959** [comment]
It's not possible to translate the command description/usage currently. This will be addressed if #3284 is merged.
