### ISSUE TITLE
error sentinel npc .withdrawPlayer

### ISSUE THREAD

**Issue by llronaldoll** [EssentialsX/Essentials#3379]
### Information

**Full output of `/ess version`**:

EssentialsX versão: 2.17.2.116

```
<!-- Run the command in your console, and copy and paste the whole output here -->
```

**Server log**: 

**EssentialsX config**: 

### Details

**Description**  

the problem occurs when a citizen sentinel npc dies, essentials tries to withdraw some money from it because he thinks he is a player
https://pastebin.com/DaP73LN1
**Steps to reproduce**  

create a sentry with citzen sentinel, and wait for him to die for something

**Expected behavior**  

essential should ignore the event

**Screenshots**

**Comment by pop4959** [comment]
Seems to be a problem with the coins plugin:
```
[01:25:07 ERROR]: Could not pass event PlayerDeathEvent to Coins v1.9.5
```

In any case, closing this until you have filled out the issue template entirely. You should also test this problem using only Essentials and the plugin you suspect is not working properly with it.
