### ISSUE TITLE
New danish translation file!

### ISSUE THREAD

**Issue by falcken** [EssentialsX/Essentials#338]
I made a new translation of the messages_da.properties file, of Essentials X. As I'm a Danish citizen, i thought it was time, to fix some of the gramma issues. I did.

There you go: http://pastebin.com/2LnVBstE

**Comment by vemacs** [comment]
Please submit this as a pull request

**Comment by falcken** [comment]
oh ok :D

**Comment by ghost** [comment]
I dont agree with 'alertUsed=brugte:' as it could also mean 'alertUsed=benyttet:'

Also if you look at 'givenSkull=\u00a76Du er blevet givet \u00a7c{0}\u00a76s kranie.' it should be 'givenSkull=\u00a76Du er blevet givet \u00a7c{0}\u00a76s kranium.'

You might want to check the file over again (:

**Comment by mdcfe** [comment]
Related PR: #342
