### ISSUE TITLE
Rest translate

### ISSUE THREAD

**Issue by Momonche** [EssentialsX/Essentials#3380]
### Feature request

**Feature description**
The output of /rest is not translable "You fell well rested"

**How the feature is useful**
This feature will allow us to translate well for our players or to add nice colors.

**Comment by triagonal** [comment]
These messages can be changed - their default keys and values are as follows:
```
rest=\u00a76You feel well rested.
restOther=\u00a76Resting\u00a7c {0}\u00a76.
```
Some locales are not fully up to date with the latest features of EssentialsX. You can add the above keys to your custom messages.properties file in order to customize them.

**Comment by Momonche** [comment]
Ok, thanks !
