### ISSUE TITLE
It is possible to have two prefix ?

### ISSUE THREAD

**Issue by Also00** [EssentialsX/Essentials#3381]
#2721 # Information

Full output of `/ess version`:

Server version: 1.14.4-R0.1-SNAPSHOTgit-Spigot-cbd1a1b-009d8af (MC: 1.14.4)
EssentialsX version: 2.17.2.0
PlaceholderAPI version: 5.0.72
LuckPerms version: 3.10.1 (build 174)
EssentialsXChat version: 2.17.2.0

**EssentialsX config**:  https://gist.github.com/Also00/924a82390e010b0550ca56d690163c85

### Help request

**What I have tried**
I have tried to make two prefix: X1 is used for the level of an island, and X2 is used for the group of a player (example: Admin). I want it to be like {X1} {X2} {USERNAME} in the chat,

Thanks for the help.

**Comment by triagonal** [comment]
This is not possible with EssentialsX alone. 

Your best bet is to use a PAPI placeholder providing the island level in your chat format with [ChatInjector](https://www.spigotmc.org/resources/chatinjector.38327/), and to use the regular {PREFIX} or {GROUP} placeholder for the group name/prefix.

**Comment by mdcfe** [comment]
FYI, you can use LuckPerms' [meta stacking](https://github.com/lucko/LuckPerms/wiki/Prefix-&-Suffix-Stacking) for this, but only if there's a suitable context for LP and you're already comfortable with LP's tracks system. In your case, ChatInjector + PAPI seems like a better bet.
