### ISSUE TITLE
/clean custom color named and lored items!

### ISSUE THREAD

**Issue by x3mp** [EssentialsX/Essentials#3383]
### Feature request

**Feature description**
Clearing an item with a custom colored name and/or lore.

**How the feature is useful**
This feature is not currently in the game that makes it easy for server developers.
A long hassle with the Minecraft:clear command will still get you nowhere as this is not a feature.

**Comment by pop4959** [comment]
Unlike `/clearinventory`, `/invsee` is better suited for the purpose you are looking for. You can remove very specific items of any type with it.

**Comment by x3mp** [comment]
I'm trying to clear these by command as it's part of a plugin that I'm trying to use.
Stop altering the subject to just /invsee when this is clearly not an automated solution.

**Comment by pop4959** [comment]
No need to get upset with me; you made no mention of using the `/clear` command for automation or with other plugins. I simply gave you an answer that seemed entirely reasonable as a solution.

Your use case sounds like it is quite niche, so for that reason this probably doesn't make sense as something to add to Essentials. For automation, you should be able to use `/minecraft:clear` with your custom tags or get a specialized plugin (if the one you are using doesn't already have this feature) that removes the item for you.
