### ISSUE TITLE
Broken /seen command

### ISSUE THREAD

**Issue by taberruu** [EssentialsX/Essentials#339]
We found 2 Issues:
1. /seen [Old Name of an renamed User] is not working. It results in a "Error: Player not found."
2. /seen [Name] says "has never joined the Server".
As an example.

[21:24:10 INFO]: CONSOLE issued server command: /seen _N1gg0_
[21:24:10 INFO]: Warning: The user '_n1gg0_' has never joined this server.

...

Files:
usermap.csv
_n1gg0_,e98ef0e3-8a8a-39e0-9b9b-de287e02598d
(This is a wrong uuid, check: https://de.namemc.com/s?_n1gg0_)

Essentials/userdata/4a6004f6-db66-4662-8dcf-c9021046df7c.yml (Removed some personal data)
timestamps:
  login: 1450722137646
  logout: 1450725070105
  lastteleport: 1449612594272
ipAddress: 00.000.00.000
lastlocation:
  world: world
  x: 0.0
  y: 0.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0
logoutlocation:
  world: world
  x: 0.0
  y: 0.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0
uuid: 4a6004f6-db66-4662-8dcf-c9021046df7c
money: '0'
lastAccountName: _N1gg0_

...
There is a Player Profile for the user, but EssentialsX says there is no user.

**Comment by vemacs** [comment]
What does /seen 4a6004f6-db66-4662-8dcf-c9021046df7c yield

**Comment by taberruu** [comment]
The Result ist: "Error: Player not found."
(I thought /seen is only for playernames?)

**Comment by drtshock** [comment]
Which ess version are you on?

**Comment by SupaHam** [comment]
Added support for /seen with UUIDs in 2e903ac.

**Comment by taberruu** [comment]
I was running
Essentials version 2.0.1-b239

Now i updated to 
Essentials version 2.0.1-b241

/seen [UUID] is now working (Thanks a lot for this!)

But the main problem isn't solved with this:

[11:51:58 INFO]: CONSOLE issued server command: /seen 4a6004f6-db66-4662-8dcf-c9021046df7c
[11:51:58 INFO]: Player _N1gg0_ has been offline since 11 days 15 hours 40 minutes.
[11:51:58 INFO]:  - IP Address: 00.000.00.000
[11:51:58 INFO]:  - Location: (world, 0, 0, 0)

[11:52:08 INFO]: CONSOLE issued server command: /seen _N1gg0_
[11:52:08 INFO]: Warning: The user '_n1gg0_' has never joined this server.

What I forgot.
I have a Bungeecord network and so the server is in Offline mode.
However, the problem did not occur when Essentials from the spigot-team and should therefore be solvable.

**Comment by AllieQpzm** [comment]
I'm willing to bet the incorrect UUID in usermap is causing this - you should try getting those corrected.

**Comment by d1rty-pixel** [comment]
Hi,

I have the same issue on my server setup (bungeecord and spigots in offline mode) and would love to see that fixed. 
Can you give us an estimation on when this can be fixed?

Thank you!

**Comment by vemacs** [comment]
Enable ip-forwarding and bungeecord in Bungee's config.yml and Spigot's spigot.yml, respectively. Latest EssX versions should also fix usermap data loss.
