### ISSUE TITLE
essentials.* keeps inventory

### ISSUE THREAD

**Issue by MadServlet** [EssentialsX/Essentials#3405]
### Information

**Full output of `/ess version`**:

```
[19:56:25 INFO]: Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-298 (MC: 1.15.2)
[19:56:25 INFO]: EssentialsX version: 2.17.2.123
[19:56:25 INFO]: LuckPerms version: 5.1.26
[19:56:25 INFO]: Vault version: 1.7.2-b107
[19:56:25 INFO]: EssentialsXSpawn version: 2.17.2.123
[19:56:25 INFO]: EssentialsXChat version: 2.17.2.123
```

**Server log**: NA

**EssentialsX config**: NA

### Details

**Description**  
Adding essentials.* to permissions of player does not drop inventory upon death.

**Steps to reproduce**  
add essentials.* on player's permissions
ess reload if needed
kill player

additional information: 
based on the code of https://github.com/EssentialsX/Essentials/pull/3328
Essentials/src/com/earth2me/essentials/EssentialsEntityListener.java 
```
if (user.isAuthorized("essentials.keepinv")) {
            event.setKeepInventory(true);
```
Since the user has access to all essentials permissions, it will default to keep inventory to true.
Resolved the issue by removing essentials.* from player.

If this is an expected behavior, please close the ticket. thank you.

**Expected behavior**  
Items should drop

**Screenshots**  

NA

**Comment by triagonal** [comment]
Yes, this is expected, given that the permission which grants this ability is `essentials.keepinv` and that using `essentials.*` grants all Essentials permissions. 

Consider looking through the [permissions list](https://essinfo.xeya.me/permissions.html) and only granting the permissions you need. Alternatively, you can negate `essentials.keepinv` (and any other unwanted permissions) in your permissions plugin to stop this behaviour.
