### ISSUE TITLE
Call PlayerCommandPreprocessEvent on essentials commands as well (or at least have a own event)

### ISSUE THREAD

**Issue by Kongolan** [EssentialsX/Essentials#3406]
I was writing some anti spam plugin to prevent bot attacks, and it works all fine if they spam the commands. But EssentialsX is not compatible since there is no PlayerCommandPreprocessEvent called for the essential commands. So add a own or call the PlayerCommandPreprocessEvent, please. Else i can't build on top of Essentials with my plugins.

**Comment by pop4959** [comment]
The server should be throwing the event for **all** commands registered on the server, including Essentials. Are you sure you have it installed properly? Can you also please fill out the issue template in its entirety, which will help us potentially look into the issue?

**Comment by pop4959** [comment]
Closing this early because there has been no response, and I'm almost certain that this is a bug in your code, or at worst it is a bug with upstream. There's no reason why Essentials would need to add a duplicate PlayerCommandPreprocessEvent for its own commands.
