### ISSUE TITLE
Placeholder essentials bug

### ISSUE THREAD

**Issue by StevenAVC** [EssentialsX/Essentials#3409]
### Information

**Full output of `/ess version`**:

```
[01:16:45 INFO]: Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-356 (MC: 1.15.2)
[01:16:45 INFO]: EssentialsX version: 2.17.2.0
[01:16:45 INFO]: PlaceholderAPI version: 2.10.6
[01:16:45 INFO]: LuckPerms version: 5.0.72
[01:16:45 INFO]: Vault version: 1.7.2-b107
[01:16:45 INFO]: Citizens version: 2.0.26-SNAPSHOT (build 1967)
[01:16:45 INFO]: EssentialsXSpawn version: 2.17.2.0
[01:16:45 INFO]: ChestShop version: 3.10.1 (build 174)

```

**Server log**: https://gist.github.com/TrizzerArts/e4ce89e3c16e4808c193550d8b513843

**EssentialsX config**: https://gist.github.com/TrizzerArts/f1c0804513f02bef3fb7952e25abe995

### Details
![bugess](https://user-images.githubusercontent.com/28847942/85485952-fb9f7d00-b586-11ea-87e4-c6de134314cf.png)

**Description**  
I want to report a bug or error in the placeholderapi plugin. The bug I have is when I use the placeholder %essentials_kit_time_until_available_<kitname>% . The bug begins with the delay that each kit of the essentials has, I am trying to put this placeholder to my kit that has a delay of 7889400 but at the time of visualizing the placeholder the time appears in 0 and not in the time that corresponds to the kit . And if I add a delay of 1209600 to my kit, you can see the time. The placeholder doesn't work with 7889400 delay and i need to use this delay.

**Expected behavior**  
If I set my kits with delay of 7889400 have the time appear within the placeholder.

**Comment by pop4959** [comment]
Essentials does not maintain Placeholder API placeholders. Please report this to whomever is responsible for them.
