### ISSUE TITLE
Players still able to create essentials signs

### ISSUE THREAD

**Issue by VoxaDub** [EssentialsX/Essentials#341]
So sorry the screenshot in the last ticket I posted my player had it backwards
it still works if you do it this way
http://i.imgur.com/zlJaPsn.png
and if need be you can hop on my test server with the latest builds and what not
192.99.35.188:25585

Just an idea, but rather than doing whatever patch you're trying to do couldnt you do something along these lines
On sign place it goes through every line of the sign and checks if theres duplicate '&' IF it contains one of the essentials signs  ([buy], [sell], etc) on the top row and just cancel it if it find s a duplicate '&' symbol.

**Comment by SupaHam** [comment]
Who is attempting to create the sign, is it someone with permissions to actually create the Sign? I just tried to create the sign on your server and it doesn't work. So whoever is creating the sign has more than enough permissions to actually create the Sign. 

Please don't make another issue without a video detailing the issue from start to end, showing that the player can't actually create a normal sign by typing [repair] and hand.

**Comment by VoxaDub** [comment]
Its because you dont have the permissions, so before you jump saying it doesnt work you need to actually test it before hand. You need the essentials.signs.color and essentials.signs.use.(sign)  tell me your username and I'll add those perms.

**Comment by VoxaDub** [comment]
Ive added the perms to the default pex group so feel free to test it now

**Comment by SupaHam** [comment]
Please confirm whether you are able to reproduce this issue with [build 243](https://ci.drtshock.net/job/EssentialsX/243/).
