### ISSUE TITLE
/skull no longer works after Paper patch #355

### ISSUE THREAD

**Issue by CW-UK** [EssentialsX/Essentials#3410]
### Information

**Full output of `/ess version`**:

```
Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-355 (MC: 1.15.2)
EssentialsX version: 2.17.2.127
LuckPerms version: 5.1.26
EssentialsXChat version: 2.17.2.127
EssentialsXGeoIP version: 2.17.2.127
PlaceholderAPI version: 2.10.6
Vault version: 1.7.2-b107
EssentialsXSpawn version: 2.17.2.127
```

**Server log**: [https://gist.github.com/CW-UK/7825908d6cccfe9e83dd845fcf4c60a7](https://gist.github.com/CW-UK/7825908d6cccfe9e83dd845fcf4c60a7)

**EssentialsX config**: [https://gist.github.com/CW-UK/acc42b6ac821a2626ccfb63333f463bb](https://gist.github.com/CW-UK/acc42b6ac821a2626ccfb63333f463bb)

### Details

**Description**  
Player heads from offline players or players not known to the server fail to be loaded with /skull. This only occurs after [Paper's revision #355](https://papermc.io/ci/job/Paper-1.15/355/) for [commit a70618c](https://github.com/PaperMC/Paper/commit/a70618cd5cb493fe9fe2a2a7375a7b1949d427d7) which introduces skull texture lookups from the user cache. Reverting to any revision before 355 instantly fixes the issue and the /skull command regains normal functionality.

**Error in chat**:
![image](https://user-images.githubusercontent.com/6217127/85611721-1c7fd500-b650-11ea-898d-692cc2549083.png)

**Steps to reproduce**  
Use Paper 1.15.2 with any revision from 355 onwards.
Attempt to get a /skull of an offline/unknown player

**Expected behavior**  
To be given the skull of the requested player.

**Screenshots**  
N/A

**Comment by pop4959** [comment]
Essentials doesn't support offline mode. In addition, this is a Paper problem; Paper is expected to retain consistent API behavior with Spigot. Please follow a relevant issue such as PaperMC/Paper/issues/3611.
