### ISSUE TITLE
Essentials fails to load because the Field PIG_ZOMBIE doesn't exist anymore

### ISSUE THREAD

**Issue by meepdude121** [EssentialsX/Essentials#3411]
### Information

**Full output of `/ess version`**:
/ess version can't be run because the plugin doesn't get enabled.

**Server log**: https://gist.github.com/meepdude121/a0afb8307c1812df5a7e3918fd6222ce

**EssentialsX config**: https://gist.github.com/meepdude121/2e7f6e49c5df4589e4d31618d6a2edb9

### Details

**Description**  
EssentialsX can't be enabled because the Field PIG_ZOMBIE doesn't exist anymore.

**Steps to reproduce**  
Install Spigot, install EssentialsX, launch server.

**Expected behavior**  
EssentialsX should load normally.

**Comment by meepdude121** [comment]
Essentials version is v2.17.2.129, /version output is CraftBukkit version git-Spigot-758abbe-2b00831 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by pop4959** [comment]
Was there any error? Please include it in the log if there was.

**Comment by techchrism** [comment]
Here's the error I got: https://gist.github.com/TheTechdoodle/8b10c4b3588fe52a02bec4b568e1426b

**Comment by meepdude121** [comment]
Sorry, posted wrong log. Updated

**Comment by pop4959** [comment]
Can you try updating to the latest version (and possible a couple before that) from here? <https://ci.ender.zone/job/EssentialsX/>

**Comment by techchrism** [comment]
Now I get a similar error: https://gist.github.com/TheTechdoodle/15abe1c04a2f359589fd5e159d084575

**Comment by pop4959** [comment]
Try something a few builds older from the link above. There were some changes today that might be affecting this

**Comment by meepdude121** [comment]
Version v2.17.2.126 works perfectly for me.

**Comment by TheTechdoodle** [comment]
I'm getting the same error from EssentialsX-2.17.2.126 build 938 from June 19

**Comment by pop4959** [comment]
Fixed in c043416b11c6d586310baefb13b91f79f6477ccc, latest builds should work
