### ISSUE TITLE
nicknames don't apply to the player

### ISSUE THREAD

**Issue by ErikDombi** [EssentialsX/Essentials#3414]
### Information

**Full output of `/ess version`**:
```
25.06 17:13:56 [Server] Server thread/INFO Server version: 1.16.1-R0.1-SNAPSHOT git-Spigot-758abbe-2b00831 (MC: 1.16.1)
25.06 17:13:56 [Server] Server thread/INFO EssentialsX version: 2.17.2.130
25.06 17:13:56 [Server] Server thread/INFO PermissionsEx version: 1.23.5
25.06 17:13:56 [Server] Server thread/INFO Vault version: 1.7.2-b107
25.06 17:13:56 [Server] Server thread/INFO You are running unsupported plugins!
25.06 17:13:56 [Server] Server thread/INFO You are running an unsupported server version!
```

**Server log**: https://gist.githubusercontent.com/wickedlizerd/06ed1d5bfff98284f296afabb362de57/raw/50559a6a8504a6bb28740fe8be8f98f0e8074e87/latest.md

**EssentialsX config**: https://gist.github.com/wickedlizerd/1e12afb236ddf52492c2fd81886421ea

### Details

**Description**  
/nick doesn't apply nickname. Confirmation message appears, but the name doesn't stick.

**Steps to reproduce**  
use /nick on yourself

**Expected behavior**  
New nickname

**Screenshots**  
N/A

**Comment by triagonal** [comment]
Cannot reproduce on the following:
```
[03:23:47] [Server thread/INFO]: Server version: 1.16.1-R0.1-SNAPSHOT git-Spigot-758abbe-3f0c333 (MC: 1.16.1)
[03:23:47] [Server thread/INFO]: EssentialsX version: 2.17.2.130
[03:23:47] [Server thread/INFO]: Vault version: 1.7.2-b107
```
I see in your log you reloaded the server to switch between EssentialsX versions. Try again ensuring that you turn the server off and back on again.

If that doesn't work, I'd say it's a plugin conflict. Try with just EssentialsX installed.

**Comment by pop4959** [comment]
If you're still having trouble with this, please visit our [Discord server](https://discord.gg/PHpuzZS) and join the EssentialsX support channel for help.
