### ISSUE TITLE
Editable signs

### ISSUE THREAD

**Issue by JasonHorkles** [EssentialsX/Essentials#3416]
### Feature request

**Feature description**
Allowing players to edit their sign by crouching and clicking on it would be a cool feature. If it's too much work to remember who placed what sign, then there could be a perm node so only staff can edit any sign with said perm.

**How the feature is useful**
Everyone makes mistakes or wants to change something, so instead of having to break the sign and start over, they could easily edit the sign to change what they want.

**Comment by JRoy** [comment]
Funny you'd say that

**Comment by osum54** [comment]
I'd love this idea, because my editsign plugin I was using broke in 1.16

**Comment by JasonHorkles** [comment]
Closed because it's not possible

**Comment by JRoy** [comment]
This is impossible due to the fact that in modern Minecraft versions, the client will no longer render text sent to it from the server in the sign editor.

The /editsign command has been added to in build 950 however.

**Comment by Nch0001** [comment]
> This is impossible due to the fact that in modern Minecraft versions, the client will no longer render text sent to it from the server in the sign editor.
> 
> The /editsign command has been added to in build 950 however.

its not impossible, its been done on other plugins in 1.20.4
