### ISSUE TITLE
Respawn Anchors + SinglePlayerSleep + EssentialsXSpawn not working

### ISSUE THREAD

**Issue by winnipeg21** [EssentialsX/Essentials#3423]
### Information

Full output of `/ess version`:

```
28.06 13:21:32 [Server] INFO EssentialsX version: 2.17.2.133
28.06 13:21:32 [Server] INFO PermissionsEx version: 1.23.4
28.06 13:21:32 [Server] INFO Vault version: 1.7.2-b107
28.06 13:21:32 [Server] INFO EssentialsXChat version: 2.17.2.133
28.06 13:21:32 [Server] INFO EssentialsXSpawn version: 2.17.2.133
28.06 13:21:32 [Server] INFO You are running unsupported plugins!
```

**Server log:** https://gist.github.com/winnipeg21/0db4715135c7eb4b6ad2c44f7520d264

**EssentialsX config** https://gist.github.com/winnipeg21/1e708b4482019822a111986c1f79bb44

### Help request

**Problem**
On my server players like skipping to day, so we added SinglePlayerSleep which allows night skipping, this worked nicely with EssentialsX up til 1.16.1 when Respawn Anchors were added. The issue is now that Respawn Anchors don't work with EssentialsX controlling Respawn but the SinglePlayerSleep.

**What I have tried**
I've done a few test to figure out how to allow both the plugin and Anchors to work. I also tried another SinglePlayerSleep plugin and got the same issue.

**Test # 1 - Anchors work but not SinglePlayerSleep**
- Set "**respawn-listener-priority**" to "**none**"
- Restart the server

**Test # 2 - SinglePlayerSleep works but not Respawn Anchors**
- Set "**respawn-listener-priority**" to "**high**" 
- Restart the server

**Test # 3 - Anchors and SinglePlayerSleep both work but no EssentialsX Spawn**
- Remove EssentialsX Spawn
- Restart the server

On Test # 2 I also tried setting it to "lowest" and "highest" with the same result. When the Anchors do not work it simply teleports players to spawn like a normal death.

Since I removed EssentialsX Spawn so I believed it's an EssentialsX Spawn issue. If this is intended could there be an option to force allow Anchors to work or maybe add an Anchor home much like with beds?

**Comment by pop4959** [comment]
Can you replicate this without other plugins installed?

**Comment by winnipeg21** [comment]
Yes, these tests were actually done on both my main server (the log and config above) and a private test server with EssentialsX, EssentialsXSpawn, EssentialsXChat, and SinglePlayerSleep. Same results on both servers.

**Comment by pop4959** [comment]
Can you verify the issue without SinglePlayerSleep installed, and provide reproduction steps?

**Comment by winnipeg21** [comment]
if you are talking about if Anchors work without SinglePlayerSleep and default Essentials config, sure.

Test # 4 

- SinglePlayerSleep removed _(only using EssentialsX, EssentialsXSpawn and EssentialsXChat)_
- Head to the Nether
- Place a Respawn Anchor and fill it with GlowStone
- Set Respawn point
- /kill winnipeg21

Conclusion, same issue as before, player teleports to Server Spawn Point. I also tried changing the "**respawn-listener-priority**" doing the same test with highest, high and lowest.

Test # 5
- SinglePlayerSleep removed _(only using EssentialsX and EssentialsXChat)_
- Head to the Nether
- Place a Respawn Anchor and fill it with GlowStone
- Set Respawn point
- /kill winnipeg21

Conclusion, same thing as Test # 1 and Test # 3, after removing EssentialsXSpawn the player respawns at the Anchor

**Comment by pop4959** [comment]
Alright, thank you. Then it appears SinglePlayerSleep is unrelated to this issue.

**Comment by winnipeg21** [comment]
No problem!
