### ISSUE TITLE
/weather and /pweather not working

### ISSUE THREAD

**Issue by Stoniasawsome** [EssentialsX/Essentials#3425]
### Information

**EssentialsX-2.17.2.132.jar`**:

```
28.06 14:33:02 [Server] INFO CONSOLE issued server command: /weather world sun
28.06 14:33:02 [Server] INFO You set the weather to sun in world.
```

**Server log**: 

**EssentialsX config**: 

### Details

**Description**  
typing /weather into the console or from in game produces 0 results also typeing /pweather sunny from in game produces 0 results

**Steps to reproduce**  
type /weather sunny or /pweather sunny in game. or /weather world sunny from console

**Expected behavior**  
the rain should stop

**Screenshots**  
Replace this with screenshots, if necessary.

**Comment by pop4959** [comment]
Don't create duplicate issues, and don't bother making one if you aren't going to properly fill it out. Thank you.

**Comment by Stoniasawsome** [comment]
stop that! what is wrong with it im trying to help. what have i dont wrong now i added what you wanted and now you close it again. stop it

**Comment by Stoniasawsome** [comment]
i put everything in the arrows and it didnt show up

**Comment by Stoniasawsome** [comment]
i dont understand how its a duplicate, and i dont understand how to fix it if you close it and i cant make a new one..

**Comment by Stoniasawsome** [comment]
youre confusing me i just want to report a bug

**Comment by pop4959** [comment]
It's a duplicate because you just made another issue. We can re-open that one if you fix it. We do not accept bug reports that fail to provide all of the requested information in the template.

**Comment by Stoniasawsome** [comment]
plz help

**Comment by Stoniasawsome** [comment]
i put the description and all that in between the arrows
is that not what im suppose to do?

**Comment by Stoniasawsome** [comment]
is that what im suppose to do?

**Comment by ToonTown0909** [comment]
As Pop said above, In order for your bug report to be accepted, it must be submitted correctly. Please make sure you follow the template _in its entirety_ and don't leave anything out.

**Comment by Stoniasawsome** [comment]
im trying but nothing shows up in the description when i type between the arrows and send it

**Comment by Stoniasawsome** [comment]
why does this have to be so difficult

**Comment by Stoniasawsome** [comment]
when i type between the arrows it removes what i typed when i send it

**Comment by Stoniasawsome** [comment]
i have filled out the description and all that it just aint showin up

**Comment by triagonal** [comment]
Anything you put between `<!-- -->` will **not** be shown when the comment is posted. You should replace the entire section with your content, not type between the arrows.

**Comment by Stoniasawsome** [comment]
better?

**Comment by triagonal** [comment]
> 
> 
> better?

Almost! We also need the full output of `/ess version`, your `latest.log` file, and your `config.yml` file.

**Comment by JRoy** [comment]
My players are experiencing this issue as well, so can confirm. I suspect this is an upstream issue

**Comment by Stoniasawsome** [comment]
jroy can you make the issue i have a terrible high blood pressure problem, and these guys are making me sweat rn

**Comment by ToonTown0909** [comment]
We're here to help, don't worry. I observe that the server log and essentialsx config are both still missing. Please continue to fill out the missing parts of the bug report so that developers will be able to best assist you.

**Comment by Stoniasawsome** [comment]
i dont know what an ess version is i thought it was essentials jar file latest log from what? and essentials config, i dont even know how to get that stuff here

**Comment by Stoniasawsome** [comment]
ive never had to do this on github for any plugin
im sorry to be ignorant

**Comment by ToonTown0909** [comment]
You can open a new issue **but don't submit it** if you want to view a fresh template. Here's the relevant sections though, which has detailed instructions that should help you fill in the missing information.

**Server log**: Upload `logs/latest.log` to https://gist.github.com/, replace this with link
**EssentialsX config**: Upload `plugins/Essentials/config.yml` to https://gist.github.com/, replace this with link

**Comment by Stoniasawsome** [comment]
no i dont know how, ill just wait for someone else to report it because ill pass out on the floor if my blood pressure goes much higher

**Comment by Stoniasawsome** [comment]
these guys should have a test server they can test this stuff on for themselves and stop being so pigheaded

**Comment by Stoniasawsome** [comment]
gooday
