### ISSUE TITLE
/whois location permission

### ISSUE THREAD

**Issue by Roydrick** [EssentialsX/Essentials#3429]
### Feature request

**Feature description**
a permission that hides the player's location in /whois

**How the feature is useful**
Allows the players to use /whois without seeing a player's location

**Comment by pop4959** [comment]
This already exists. Please refer to the [permissions ](https://essinfo.xeya.me/permissions.html) page.

**Comment by Roydrick** [comment]
No? i mean /whois not /seen

**Comment by pop4959** [comment]
`essentials.whois.ip` for plain IP and `essentials.geoip.show` for location if GeoIP is installed.

**Comment by Roydrick** [comment]
I mean the ingame location
