### ISSUE TITLE
Signs not working

### ISSUE THREAD

**Issue by obliviaxel** [EssentialsX/Essentials#343]
I'm using EssentialsX and when I make the buy signs, they don't work. The other plugins that I have running are mcmmo and worldedit. Does anyone know how to fix this.

**Comment by vemacs** [comment]
They need to be enabled in the config, this has been the case for months: http://ess.khhq.net/wiki/Sign_Tutorial

**Comment by obliviaxel** [comment]
The config that it shows is not what mine shows, here is a link to the config. http://pastebin.com/PmTUeczE.

**Comment by vemacs** [comment]
Copying the values should work
