### ISSUE TITLE
Kit money duplicate issue when not enough space in inventory

### ISSUE THREAD

**Issue by ericskh2** [EssentialsX/Essentials#3431]
### Information

**Full output of `/ess version`**:

[INFO] ....>.... CONSOLE issued server command: /ess version

[INFO] .... Server 版本: 1.16.1-R0.1-SNAPSHOT git-Paper-26 (MC: 1.16.1)

[INFO] .... EssentialsX 版本: 2.17.2.133

[INFO] .... LuckPerms 版本: 5.1.26

[INFO] .... Vault 版本: 1.7.2-b107

[INFO] .... Citizens 版本: 2.0.27-SNAPSHOT (build 2006)

[INFO] .... EssentialsXGeoIP 版本: 2.17.2.133

[INFO] .... EssentialsXChat 版本: 2.17.2.133

[INFO] .... EssentialsXSpawn 版本: 2.17.2.133

**Server log**: 
https://gist.github.com/ericskh02/d159c3c2078b2c405e131024d90fe3c3

**EssentialsX config**: 
config.yml
https://gist.github.com/ericskh02/c4a81f675810ceb02119182c1bd5d391
kits.yml
https://gist.github.com/ericskh02/1ebb4ec5fc9419a49feccda90f508e6f

### Details

**Description**  
If player does have enough space in their inventory for storing a kit, they can always get the money in the kit repeatedly without applying the delay time.

**Steps to reproduce**  
1.Create a kit with money and stuff
2. Put stuff in inventory to create lack of space in the inventory
3. Use /kit test.
Result: Player cannot get the items of a kit but they can get money of the kit without applying the -1 delay.
This makes money duplication possible. 

**Expected behavior**  
Player shouldn't be able to get any money or item if they don't have enough space in the inventory.

**Screenshots**  
![image](https://user-images.githubusercontent.com/42265526/86084614-e8813580-bacf-11ea-8497-e25f115cb532.png)

![image](https://user-images.githubusercontent.com/42265526/86084641-f59e2480-bacf-11ea-9757-24288b986b13.png)

![image](https://user-images.githubusercontent.com/42265526/86084466-94765100-bacf-11ea-8ab3-d9bf316f44a5.png)
The green message means money has been successfully added to player's bank balance,
while the red message means the player does not have enough space in their inventory.

**Comment by triagonal** [comment]
This has been fixed in EssentialsX versions `2.17.2.137` and above. Download the latest build [here](https://essentialsx.net/downloads.html).
