### ISSUE TITLE
Cant disable /fly

### ISSUE THREAD

**Issue by Mineinjava** [EssentialsX/Essentials#3435]
### Information

Full output of `/ess version`:

```
Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-334 (MC: 1.15.2)
EssentialsX version: 2.17.2.0
LuckPerms version: 5.1.26
Vault version: 1.7.2-b107
EssentialsXChat version: 2.17.2.0
```

**Server log:** 
irrelevant
**EssentialsX config** 

### Help request

**Problem**
players on my server can fly.

**What I have tried**
I have tried denying them the permission to fly.
**Screenshots**

**Comment by pop4959** [comment]
This is almost certainly not a bug. Most likely you have permissions set up incorrectly. If you are in need of help using the plugin, please join the [MOSS Discord server](https://discord.gg/PHpuzZS) and visit the EssentialsX support channel.

**Comment by Mineinjava** [comment]
I fixed it, thanks
hmmm, I thought I put it in the help category
