### ISSUE TITLE
[REQUEST] Please add support for &x&1&1&1&1&1&1 color coding

### ISSUE THREAD

**Issue by zettlinger** [EssentialsX/Essentials#3436]
### Feature request

**Feature description**

I use Multichat and they use the &x&1&1&1&1&1&1 for color coding when i issue a command with essentials my nickname now shows as &xNICKNAME  Could you please support the &x type color codes too or at least filter out the &x in the nickname ?

**How the feature is useful**

It will eliminate a visual bug where the nickname gets printed with &x in front and in the wrong color (last & used)

**Comment by JRoy** [comment]
I don't quite understand what you're on about, Essentials (in the latest dev builds) added support for rgb color codes under the `&#rrggbb` format. If that's now what you want could you please clarify further

**Comment by zettlinger** [comment]
Some plugins (Multichat being one) use the format   /nick NICKNAME &x&1&1&1&1&1&1NICKNAME to set the RGB colors.  When i do that and issue an essential command the nickname will read as &xNICKNAME in the color of the last & used.

What i would like to see is either: Convert &x with codes to the Hex color code OR filter out the &x in front of the name and i can live with it having the wrong color there :)

(Thank you for replying)

**Comment by JRoy** [comment]
I quickly just looked into the code of Multichat and it seems they're setting unformatted color codes into the display name of a player which is just wrong and not how it should be done. I don't think Essentials should be the one fixing this for them here. They need to properly update to the more universal rgb format of `&#rrggbb` and stop placing untranslated color into the user's display names.

Please raise an issue with Multichat and you can let them know they are free to reach out for assistance on the [MOSS discord](https://discord.gg/casfFyh) on how to best implement this.
