### ISSUE TITLE
Empty chat message is allowed after color code is used

### ISSUE THREAD

**Issue by takatalvi** [EssentialsX/Essentials#3440]
### Information

**Full output of `/ess version`**:

```
Server version: 1.16.1-R0.1-SNAPSHOT git-Paper-29 (MC: 1.16.1)
EssentialsX version: 2.17.2.136
LuckPerms version: 5.1.26
Vault version: 1.7.2-b107
EssentialsXGeoIP version: 2.17.2.136
EssentialsXChat version: 2.17.2.136
EssentialsXSpawn version: 2.17.2.136
```

### Details

**Description**  
When a player with permissions `essentials.chat.color` and/or `essentials.chat.rgb` enters a chat message with nothing but valid formatting codes, the message is sent anyway as an empty line, containing the name and no text. Sending an actual empty message is not allowed so I believe this workaround should not be either.

**Steps to reproduce**  
Type a chat message containing only a valid formatting code (e.g. `&f`).

**Expected behavior**  
An empty message should not be sent to chat even when using a formatting code.

**Screenshots**  
![2020-07-02_16 05 38](https://user-images.githubusercontent.com/35687568/86368905-0e4c3d00-bc7e-11ea-95a6-c257635f4b04.png)

**Comment by pop4959** [comment]
Is this the behavior prior to 1.16 / RGB chat?

**Comment by takatalvi** [comment]
I just tested the same on 1.15.2, it works the same, my guess is it's been around for a long time.

**Comment by pop4959** [comment]
I thought so. In that case, not many people have complained about this in the past 10 years. Definitely not a bug, but feel free to re-create this issue as a feature request instead. Maybe an option can be added to chat.

**Comment by takatalvi** [comment]
Oh, that makes sense, I'll submit it as a feature request, thanks!
