### ISSUE TITLE
MobSpawners with silk touch

### ISSUE THREAD

**Issue by brasilcraft54** [EssentialsX/Essentials#3441]
version: Essentials v2.17.2.143

Hello I would like the Essentials to have mobspawners with silk touch and permission too, sorry my bad English I am from Brazil, so I would like it to be possible to remove mobspawners with too silk, this would replace the silkspawners, and leave the essentials 100% more complete, and also wanted to hear a permission for this exemple essentials.dropspawners.* or essentials.dropspawners.creeper

**Comment by pop4959** [comment]
This doesn't sound like a very essential feature to me, and is probably best left as its own discrete plugin. Essentials is not meant to be a replacement for every plugin you run on your server. I don't think there is anything wrong with SilkSpawners, and certainly nothing that Essentials would do better.

**Comment by brasilcraft54** [comment]
I don't think silkspawners is good, I just think essentials should replace several plugins, like CMI, if essentials has that system it would be -1 plugin on your server do you think that good no?

**Comment by mdcfe** [comment]
EssentialsX provides a specific set of essential commands - silk touch spawners doesn't fit the scope of EssentialsX. If you're running into issues using SilkSpawners, I'd recommend getting in touch with their support - as far as I know they're fairly active, and many people use SilkSpawners without issue.

EssentialsX is a small team and as such we can't maintain every single possible feature for every single possible Minecraft server. We decide which features we add based on a few criteria:
- What types of server will benefit? If it's only useful to a select few people, it probably belongs in a separate plugin.
- Are there high-quality, well-known (ideally FOSS) alternatives? If there are, why should we build our own version?

CMI is the example of why EssentialsX should *not* try and cover every possible feature - I've heard continuous reports of CMI being buggy and broken, as so many features are added to CMI that they are made with the minimum amount of effort possible and receive little-to-no support from the author. (CMI also has some major performance issues and game-breaking bugs from what I've heard, so take that as you will.)

Reducing the plugin count does not improve your server in any way. Reducing the number of features on your server or removing specific laggy plugins might improve performance, but plugin count alone literally does not mean anything. If you're concerned about performance, look into Timings reports to see which plugins are affecting performance (you might want to watch a tutorial on YouTube).
