### ISSUE TITLE
Do not allow sending blank chat messages after color code is used

### ISSUE THREAD

**Issue by takatalvi** [EssentialsX/Essentials#3442]
### Feature request

**Feature description**
When a player with permissions to use formatting codes enters a chat message with nothing but valid formatting codes, the message is sent anyway as an empty line, containing the name and no text. Sending an actual empty message is not allowed for obvious reasons so I believe this workaround should not be either.

**Comment by latiku** [comment]
I have solved this in https://github.com/EssentialsX/Essentials/pull/3505

**Comment by takatalvi** [comment]
Nice work, looking forward to seeing it in action!

**Comment by takatalvi** [comment]
Thank you!
