### ISSUE TITLE
add an option

### ISSUE THREAD

**Issue by cicatrice74** [EssentialsX/Essentials#345]
Can u also add an option to have spawn on join?

**Comment by SupaHam** [comment]
What do you mean have spawn on join? As in teleport to spawn when you join the server?

**Comment by cicatrice74** [comment]
yes. someone like me needs to force-spawn players upon join..is it possible
to add this?
Il 03/Gen/2016 01:49, "SupaHam" notifications@github.com ha scritto:

**Comment by SupaHam** [comment]
Yes, I'll do it when I can.

**Comment by cicatrice74** [comment]
great tnx
Il 03/Gen/2016 01:59, "SupaHam" notifications@github.com ha scritto:

**Comment by EvilOlaf** [comment]
I have a kind a similar suggestion.

Sometimes player logging out while flying for example and under some circumstances they are getting kicked by anticheat for flying or related.

Therefore I would like to see an option or command to reset the spawn location on join for a particular player. This could also be achieved by allowing the use of the `/spawn` command on offline players.

Thanks for reading and a happy new year even though it is a bit late :D

**Comment by SupaHam** [comment]
This has been fixed in b673630. You can grab the fix from [build 361](https://ci.drtshock.net/job/EssentialsX/361/) on the CI server.
