### ISSUE TITLE
Jail Time ignores AFK players

### ISSUE THREAD

**Issue by LoSCraft-Network** [EssentialsX/Essentials#3454]
### Feature request

**Feature description**

Jailed players when marked as AFK will not have jail time counted
**How the feature is useful**

It will prevent people to just go watch netflix or something while in jail

**Comment by ToonTown0909** [comment]
This sounds like an amazing feature. I think something like this could be a great asset to many players and servers. Big +1. As a thought, maybe make a setting for it in the config as I can easily see that some people might not want this change "forced" on them. Either way, a great suggestion! :D

**Comment by LoSCraft-Network** [comment]
This is possible now just setting context to the permission using
essentials:jailed=false

Not really a needed feature anymore
