### ISSUE TITLE
Warps using precise position

### ISSUE THREAD

**Issue by ShayBox** [EssentialsX/Essentials#3455]
### Feature request
A config option to switch warps and spawn to use player pos/exact pos instead of block pos

**Feature description**

Currently warps and spawn save the exact position of the person that set the warp in the config, but it then uses that to get the block position they were standing on, I suggest an option that, instead uses the exact position from the file allowing warps and spawn to be set precisely.

**How the feature is useful**

This is a very niche feature that probably won't get much use, but from my limited knowledge I don't think it would be too difficult to add, it would require being enabled in the config to not be a breaking change.

If this feature can't/won't be added, I ask how I would import your in-repo `com.earth2mc` fork so I can create my own plugin that overrides the ess warp/spawn commands to do this.

**Comment by mdcfe** [comment]
This already exists:
```yaml
# Whether to make all teleportations go to the center of the block; where the x and z coordinates decimal become .5
teleport-to-center: true
```

Change this option to `false` to disable teleport destination rounding.

**Comment by ShayBox** [comment]
Oh nice, sorry for bothering you then, I didn't see that :+1:
