### ISSUE TITLE
Support more command *

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#346]
I want to add /give \* and /effect \* command
like /nuke *

**Comment by drtshock** [comment]
?

**Comment by ghost** [comment]
Give an item to all players....

**Comment by xMrPoi** [comment]
This would better be achieved with /giveall and /effectall. /nuke with no arguments will nuke everyone on the server.

**Comment by Kakifrucht** [comment]
Couldn't the whole \* functionality just be abstracted?
Or one could write a plugin that did this either way. Would be pretty simple.

**Comment by vemacs** [comment]
Sorry, seems beyond the scope of this plugin.
