### ISSUE TITLE
Jailed Player Permissions

### ISSUE THREAD

**Issue by TheNylox** [EssentialsX/Essentials#3461]
### Information

Full output of `/ess version`:

07.07 17:05:33 [Server] INFO You are running an unsupported server version!
07.07 17:05:33 [Server] INFO You are running unsupported plugins!
07.07 17:05:33 [Server] INFO Towny version: 0.96.2.0
07.07 17:05:33 [Server] INFO Vault version: 1.7.2-b107
07.07 17:05:33 [Server] INFO PermissionsEx version: 1.23.4
07.07 17:05:33 [Server] INFO PlaceholderAPI version: 2.10.7-DEV-${BUILD_NUMBER}
07.07 17:05:33 [Server] INFO EssentialsX version: 2.17.2.0
07.07 17:05:33 [Server] INFO Server version: 1.16.1-R0.1-SNAPSHOT git-Paper-39 (MC: 1.16.1)

https://pastebin.com/BN63XayB Essential Config

Usig PermissionEX

### Help request

**Problem**
I'm looking for where i can set the Jailed Player Permission . I mean , i want jailed can break blocks . Actually i've got a jailed protected with Towny Plot Perms . For towny  they can destroy cause i setted the Destroy perm ON but seem like something in essential overwrite that and they cant break .

**What I have tried**
I tryed many thing that devs say me on Discord but noone works .

/ees debug give that :
06.07 22:12:28 [Server] INFO charge user TheNylox completed
06.07 22:12:28 [Server] INFO calculated command (essentials) cost for TheNylox as 0
06.07 22:12:28 [Server] INFO attempting to charge user TheNylox

i've tryed that too :
MD (not that one)Yesterday at 11:13 PM
@🇮🇹TheNylox You can use essentials.jail.allow-break, ...allow-place, ...allow-blockdamage and ...allow-interact to control all blocks/items

Tryed adding this perm node to default users
essentials.build.break.obsidian

Tryed to run server only with LP and EssentialX . jailed still cant break

**Screenshots**

**Comment by JRoy** [comment]
Please use our [Discord server](https://discord.gg/PHpuzZS) to ask any usage related questions in the Essentials support channel.

**Comment by TheNylox** [comment]
I've allready . Noone can help me or just dont answer , thats why i opened this.

**Comment by TheNylox** [comment]
The problem still not solved . Tryed to use LP too and noone solved it. What can i do?

**Comment by ToonTown0909** [comment]
For the sake of record-keeping I would like to confirm that this issue has been resolved via Discord.

**Comment by TheNylox** [comment]
Yeah ToonTown solved it  , thank you !
