### ISSUE TITLE
Read other user's mail from the console or an Opped player

### ISSUE THREAD

**Issue by PepsiSardines** [EssentialsX/Essentials#3465]
### Feature request

**Feature description**

The ability to read other user's mail from the console, or a player that has the permission to do so. Somewhat like the ability to see and use other player's homes with /home player:home.

**How the feature is useful**

This feature will be useful for administrators who are using the server console and need to check their mail, or other staff member's mail for any issues on the server. It is also useful as a Social Spy feature, to make sure players are not sharing IP addresses to other servers, etc.

**Comment by ToonTown0909** [comment]
I really like this idea, assuming it's possible. As a thought, maybe can an in-game command be added something like `/mail read <username>` maybe? Or maybe just `/mail <username>`?

**Comment by chuckthemole** [comment]
I would be interested in looking into this and see if there is a solution.

**Comment by pop4959** [comment]
Mail is private and cannot be read by other players. Only the server owner can check users' mails, which are stored in their user data file.
