### ISSUE TITLE
Editsign command modification

### ISSUE THREAD

**Issue by JasonHorkles** [EssentialsX/Essentials#3467]
### Feature request

**Feature description**
A modification to the `/editsign` command where doing `/editsign set 1` without specifying anything to put on the sign will let you copy the command with the text that's already on the sign. For example, if you do that command, it'll say "Click here to copy line 1's content" and clicking it will autofill `/editsign set 1 <whatever was on the sign>`

You could also do something like `/editsign get <line>` instead if you think that'd be better.

**How the feature is useful**

If you have a ton of groovy color codes on the sign and don't really want to type them in again, it'd be useful to just get the raw text that was on the sign put into your chat box so you can easily and quickly modify it. This was previously able to be accomplished by other sign edit plugins via the sign gui, [which is no longer possible](https://github.com/EssentialsX/Essentials/issues/3416#issuecomment-652646315).

**Comment by TheNety** [comment]
Or maybe it would be better via tab completion suggestion? `/editsign set 1 <here it will suggest you the current content on the first line>`
