### ISSUE TITLE
Auto equip armor from kit

### ISSUE THREAD

**Issue by xMrPoi** [EssentialsX/Essentials#347]
There should be an option to automatically equip armor from a kit. It could there could be a separate helmet, chestplate, pants, and boots node to put in an item.

**Comment by EncryptedPixel** [comment]
+1

**Comment by voodootje0** [comment]
Very good idea +1

**Comment by drtshock** [comment]
How do you suggest we implement this?

**Comment by voodootje0** [comment]
I think
[chestplate] diamondchestplate 1 (etc)

When inventory is full drop it.

**Comment by FlippantCactus** [comment]
Or items:
- x
- y
- z

armour:
- Helmet ID
- Chestplate ID
- Leggings ID
- Shoes ID

**Comment by drtshock** [comment]
I think just attempt to equip any piece of armor if there is currently nothing in that specific armor slot.

**Comment by FlippantCactus** [comment]
Sounds good if it auto equips from list

**Comment by xMrPoi** [comment]
Attenpting to equip any armor in the inventory could work but then you're sacrificing 4 inventory slots which will always be empty.

**Comment by FlippantCactus** [comment]
auto-equip-armour: true/false.
Don't see it being an issue @xMrPoi

**Comment by SupaHam** [comment]
Adding on to the item deserialization specifications, maybe we could have an `auto-equip` property that automatically equips that item.

**Comment by xMrPoi** [comment]
It could look something like this: http://i.imgur.com/S1aVGzG.png

**Comment by EncryptedPixel** [comment]
@xMrPoi's example is probably the best one

**Comment by drtshock** [comment]
I would rather just attempt to equip pieces of armor if the player's armor slots are empty.

**Comment by iLemon** [comment]
Was this ever implemented?

**Comment by pop4959** [comment]
No. Feel free to write the code and make a pull request if you would like to add it.

**Comment by MatteoGauthier** [comment]
Any update ?

**Comment by EvilSlime** [comment]
We need this

**Comment by ManiakMCPE** [comment]
has anyone made a plugin that does this already? i have one but it only works when you run the command in chat
