### ISSUE TITLE
Multiverse Support with /sethome & /home

### ISSUE THREAD

**Issue by PvMHQ** [EssentialsX/Essentials#3470]
### Feature request

**Feature description**

Homes Limited to World style for Multiverse. Configure per world limit use of /home.
**How the feature is useful**

I have a Multiverse server running where 1 server runs vanilla and a second runs an EliteMobs plugin through multiverse and the players would like to make use of both overworlds for a /home when in the multiverse group

**Comment by SrBedrock** [comment]
If you use the luckperms plugin it is already possible to do this through `contexts`, but it would not be possible to define a home with the same name in two worlds.
