### ISSUE TITLE
Disabled /tpa worlds

### ISSUE THREAD

**Issue by Giorgis20** [EssentialsX/Essentials#3471]
Feature request
Feature description
Add an option in the config to disable teleporting to certain worlds using /tpa

If a player uses the /tpa command and then joins for example a minigame in a non-bungee server, the player would
teleport outside the allowed arena

How the feature is useful

In multi-minigame non-bungee servers it is possible for someone to /tpa and then join a minigame. If the other player accepts the teleport request it would teleport the player outside the playable arena

**Comment by ToonTown0909** [comment]
This is already a feature, you can use permissions to accomplish this. `essentials.worlds.<worldname>`. Here's a link to the permissions wiki as well if you're interested. https://essinfo.xeya.me/permissions.html
<img width="1209" alt="Screen Shot 2020-07-08 at 1 49 55 PM" src="https://user-images.githubusercontent.com/2454717/86953099-ee0afb00-c121-11ea-84e9-85c30e4ff32f.png">

**Comment by FlashLight34** [comment]
and that work??? because player on my server with perm for /tp can teleport to player in the nether but i negated essentials.worlds.nether :(

maybe we need to check where is the player to tp to no?

**Comment by ToonTown0909** [comment]
If you you the [M.O.S.S. Discord server](https://discord.gg/PHpuzZS), it'll be a lot easier to give you support for this. :D
