### ISSUE TITLE
Optimizing the `/nick off` command

### ISSUE THREAD

**Issue by ToonTown0909** [EssentialsX/Essentials#3472]
### Feature request

**Feature description**
Currently, the ability to use `/nick off` is accessible if and only if the `essentials.nick` permissions is given. What I would like to request please is that the ability to turn off your nickname, `/nick off`, is allowed with the other nicknames permissions as well. 

**How the feature is useful**
This feature will be useful because when people have `essentials.nick.changecolors` and maybe with `essentials.nick.rgb` they will now be able to reset their nickname if they choose.

**Comment by SrBedrock** [comment]
You must have `essentials.nick` to access the command, just the `essentials.nick.changecolors` permission is not enough.

The permission `essentials.nick.changecolors` allow to only change your nickname's colors (And not the name itself) and you need `essentials.nick` to use the `/nick` command.

The `/nick off` command uses the `essentials.nick` permission.
