### ISSUE TITLE
Run TPR from console/command block

### ISSUE THREAD

**Issue by Artuto** [EssentialsX/Essentials#3479]
### Feature request

**Feature description**
Allow the console to run the TPR command passing the name of the player as an argument.

**How the feature is useful**
On the spawn of my wilderness world I have a button to get teleported randomly. Since the command can only be used by players the command block will not work

**Comment by pop4959** [comment]
Thanks for the feedback. There were some ideas about adding random teleport functionality into EssentialsSpawn as well. I'll probably look into this later after there has been some more thought put into it.

**Comment by untuned** [comment]
Would be helpful, as it would allow them to tp if they click a button at spawn too. I'd use this.

**Comment by pop4959** [comment]
> Would be helpful, as it would allow them to tp if they click a button at spawn too. I'd use this.

Random tp signs was also another idea someone had. There's certainly a couple ways Essentials can make use of this new functionality, when it's more matured. 😛
