### ISSUE TITLE
tprandom enhancement

### ISSUE THREAD

**Issue by botany111** [EssentialsX/Essentials#3482]
Feature request

Feature description
1.Add cooldown time for tprandom and have permission to ignore him essentials.tpr.delay.bypass

2.Need to configure the world's largest range

How the feature is useful
Otherwise, he will break through the border, my server range is only 10000X10000

**Comment by pop4959** [comment]
You should be able to do both of these things already:

1) Try `teleport-cooldown` or `command-cooldowns` in the config, and the `essentials.commandcooldowns.bypass` permission.

2) Try `/settpr maxrange <value>` to reduce the size of the border. By default it is going to be your vanilla world border.

**Comment by botany111** [comment]
Can I configure random transmission for multiple worlds?

**Comment by pop4959** [comment]
No, it currently doesn't support that, as the implementation is very basic. You can configure it for one world currently with the `/settpr` command to set the center location. A player running `/tpr` from any world will randomly teleport into that world. Multi-world random teleport is a planned update for later, you can follow #3469 for progress on it.

If Essentials' basic random teleport is lacking too much for your server, I would also suggest getting an additional plugin to handle it such as [this one](https://www.spigotmc.org/resources/random-teleport-full-nether-support.76021/) by DarkEyeDragon.

**Comment by zefir-git** [comment]
Cooldown and delay bypass would be much appreciated. I would also add an `rtp` command alias to the list.

**Comment by PaBox** [comment]
I think it is a valid point to split the cooldown for tpr and tp requests - that just makes sence. Please just add a config setting for that or should I make a push request?

**Comment by pop4959** [comment]
> I think it is a valid point to split the cooldown for tpr and tp requests - that just makes sence. Please just add a config setting for that or should I make a push request?

Per command cooldowns already exist. Use the existing configuration for that, there is no need for a separate option specific to tpr.

**Comment by PaBox** [comment]
tysm!
