### ISSUE TITLE
Afk message is sent despite AfkStatusChangeEvent being cancelled

### ISSUE THREAD

**Issue by xtomyserrax** [EssentialsX/Essentials#3485]
I noticed that after cancelling the event (with ACTIVITY cause), the you are AFK message is being sent depiste me being not AFK.

![image](https://user-images.githubusercontent.com/6054192/87186734-614b7300-c2c2-11ea-906d-e2956303acc5.png)

A good way to fix this could be by making setAfk method to return a boolean instead of void, so if it returns true it means that it could set the player, if its false, its because the event was cancelled. (https://github.com/EssentialsX/Essentials/blob/8046b8594a092ffa6657d654e4b9dc94327c7e65/Essentials/src/com/earth2me/essentials/User.java#L526 )

So for example, you could check here what it returns and depending on that to send the message: https://github.com/EssentialsX/Essentials/blob/8046b8594a092ffa6657d654e4b9dc94327c7e65/Essentials/src/com/earth2me/essentials/User.java#L686

(Im using latest released Essentials version 2.18.0.0)

Wish I was clear! Thank you!

**Comment by pop4959** [comment]
These is currently a PR open for this issue already at #3402.
