### ISSUE TITLE
Allow server owners to configure disabling respawn at beds when a respawn anchor is active

### ISSUE THREAD

**Issue by Legoman99573** [EssentialsX/Essentials#3491]
### Feature request

**Feature description**
So basically instead of respawning the player at their beds, it will respawn them back at the respawn anchor if the charges are 1 through 4. When the charges are at 0, respawn the user back at their beds ofc.

**How the feature is useful**
Makes it easier for server owners to allow respawn anchors to be used as intended as it takes you back to the bed instead of the respawn anchors location.

**Comment by JRoy** [comment]
Could you further explain this? It's my understanding that Essentials itself doesn't override respawn anchors. Do you mean EssentialsSpawn should have an option to spawn a player at respawn anchors when `respawn-at-home` is true in the config?

**Comment by Legoman99573** [comment]
> Could you further explain this? It's my understanding that Essentials itself doesn't override respawn anchors. Do you mean EssentialsSpawn should have an option to spawn a player at respawn anchors when `respawn-at-home` is true in the config?

something like that is what i was trying to talk about
