### ISSUE TITLE
command-cooldowns

### ISSUE THREAD

**Issue by Bricec6** [EssentialsX/Essentials#3492]
hello, i followed the tutorial of the command-cooldowns of essentials, except that i would like to make my /repair all last 60 seconds, and my /repair hand last 30 seconds, in game it doesn't detect it i tried with '' , "" and https://github.com/EssentialsX/Essentials/issues/2950 but nothing works, what can i do? thanks

![image](https://user-images.githubusercontent.com/51750055/87227137-21a38a80-c399-11ea-8a9a-d2b734ca233b.png)

**Comment by pop4959** [comment]
Try single quotes `'` instead of double quotes `"`.

**Comment by Bricec6** [comment]
not work

**Comment by Bricec6** [comment]
we can commnade infinitely with the quotes
"repair all"
'repair all'
its same

**Comment by Bricec6** [comment]
not work, its a feature?

**Comment by Bricec6** [comment]
UP UP , its not work

**Comment by Bricec6** [comment]
command-cooldowns:
  "^(repair) +(hand)": 30
  "^(repair) +(all)": 60

its good thank Triangle
