### ISSUE TITLE
The permission is already defined

### ISSUE THREAD

**Issue by XXY233** [EssentialsX/Essentials#3494]
### Information

Full output of `/ess version`:
Sorry, I cannot execute this command...
EssentialsX-2.18.0.0
EssentialsXChat-2.18.0.0
EssentialsXSpawn-2.18.0.0

**Server log:** 
https://gist.github.com/XXY233/a3d39e10b0cd0da59825541e5a2de509

**EssentialsX config** 
https://gist.github.com/XXY233/1f44959f2a403c5c663df99acb5f6f60

### Help request

**Problem**
I use CatServer 1.12.2, "The permission essentials.hat.prevent-type.pixelmon_healer is already defined!" is prompted when the server is loaded, and no ESSX commands can be used after the server is loaded

**What I have tried**
After I deleted "Pixelmon-1.12.2-8.0.2" from the mods folder, all the commands of ESSX can be used normally, then no error occurs
I need Pixelmon and ESSX. Is there any way to make them work together?

**Screenshots**
![20200711232918](https://user-images.githubusercontent.com/46647646/87227555-6dbcf200-c3ce-11ea-89a3-d8e3675c958b.png)

**Comment by JRoy** [comment]
EssentialsX only supports Craftbukkit, Spigot, and Paper.

Forge mods never usually play nice with Bukkit plugins.
