### ISSUE TITLE
Spam in my console

### ISSUE THREAD

**Issue by zasnaz** [EssentialsX/Essentials#3495]
Hello, every time I log out of my server I see this in my console 

-----------------------------------
11.07 15:10:32 [Disconnect] User Zasnaz has disconnected, reason: Disconnected
11.07 15:10:32 [Server] Server thread/INFO Zasnaz is now offline.
11.07 15:10:32 [Server] Server thread/WARN Task #1443 for Essentials v2.17.2.0 generated an exception
11.07 15:10:32 [Server] INFO java.lang.NullPointerException: null
11.07 15:10:32 [Server] INFO at com.earth2me.essentials.xmpp.XMPPManager.updatePresence(XMPPManager.java:142) ~[?:?]
11.07 15:10:32 [Server] INFO at com.earth2me.essentials.xmpp.EssentialsXMPP.updatePresence(EssentialsXMPP.java:113) ~[?:?]
11.07 15:10:32 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[Spigot_Latest_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
11.07 15:10:32 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) [Spigot_Latest_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
11.07 15:10:32 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [Spigot_Latest_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
11.07 15:10:32 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [Spigot_Latest_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
11.07 15:10:32 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [Spigot_Latest_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
11.07 15:10:32 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [Spigot_Latest_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
--------------------------------------------------------

Is there any possibility to fix this

**Comment by ToonTown0909** [comment]
This issue doesn't follow any of the available formats. Are you able to please use one of those? Many thanks! :D

**Comment by JRoy** [comment]
Remove EssentialXXMP from your plugins folder as you have no use for it

Also, please update as there is a new version available.
