### ISSUE TITLE
Change spigot site so it doesn't provide every jar

### ISSUE THREAD

**Issue by JasonHorkles** [EssentialsX/Essentials#3500]
### Feature request

**Feature description**

Change the spigot site so it either links to https://essentialsx.net/downloads.html or make a new page on that site that has the "stable" builds on it so people from spigot can easily download what they want instead of everything that's provided

**How the feature is useful**

90% of the people have antibuild and xmpp installed without realizing what they do. Creating a page that lets you choose what to download with a breakdown of each module should easily stop people from having unwanted add-ons.

**Comment by ToonTown0909** [comment]
I really like the idea of being able to provide more clarity on what modules users download.

**Comment by pop4959** [comment]
Just FYI the spigot distribution no longer contains XMPP by default.

**Comment by JasonHorkles** [comment]
That's a step in the right direction I suppose, but it'd still be good to have a way to let people install what they want

Heck even putting a README file in the zip with a breakdown might work - just putting some suggestions on the table tho

**Comment by pop4959** [comment]
Yeah we've already talked about this internally and I think MD is well aware of the option. So I'll close this for now, since there isn't really much more to be discussed about it.

**Comment by mdcfe** [comment]
For now, we're including all modules in the Spigot distribution except XMPP, as the other modules are likely to be used by servers. There's also a readme in the Spigot distribution with a link to the breakdown page, which should hopefully help users figure out what they need to use.

**Comment by JasonHorkles** [comment]
Good to know, thanks

**Comment by JasonHorkles** [comment]
still a problem now that these changes seem to be reverted

**Comment by AstralisVox** [comment]
I personally think this would be a good idea, have the spigot page link to the essx downloads page because people are just downloading the zip and immediately installing all the modules thinking they need to without knowing what they are actually for. Which causes a lot of problems. I don't think I have seen too many people actually using antibuild, xmpp, geoip and protect as much as the other main ones like spawn and chat. 

Having the link point to the site will allow people to only download the ones they are needing and save a lot of time for everyone.

The downloadable ZIP from the spigot site does not contain a readme and it still contains the XMPP

**Comment by Evidentsinger14** [comment]
Going along what Omega has stated, the zip file from SpigotMC does have XMPP, which a lot of people have no idea what it does. The same thing could be said about Protect. 
As far as Anti-Build goes, it's a great resource, but only in certain situations. If the person is downloading Anti-Build, they most likely have some idea of what they're doing, and knows the functionality of it.

The idea of a README going into the zip would help in the situation that it is read, but more often than not, people will not take the time to do so.
I like the idea of having the Download link go to https://essentialsx.net/downloads.html/ so people can get what they need.

Alternatively, if this is not something that will be done, the idea of having the zip folder contain the Core Jar, as well as Spawn, and Chat with a README letting them know to go to the site if others are needed would also be a good idea in my opinion.

**Comment by JasonHorkles** [comment]
if u dont believe us u can see how many times we've had to do `??ab` 🙃

**Comment by Bobcat00** [comment]
I like having everything in one zip file, because:

1. I only need to download one file instead of four
2. It keeps the matching versions of the files all together in one place, so I can keep it on my hard drive and I know I have a consistent set of files
3. I open it with WinRAR, click on the four files I need, click on Export, select a destination and I'm done

**Comment by JasonHorkles** [comment]
> I like having everything in one zip file, because:
> 
> 1. I only need to download one file instead of four
> 2. It keeps the matching versions of the files all together in one place, so I can keep it on my hard drive and I know I have a consistent set of files
> 3. I open it with WinRAR, click on the four files I need, click on Export, select a destination and I'm done

most people aren't smart enough to get rid of the modules they don't need

**Comment by Bobcat00** [comment]
> most people aren't smart enough to get rid of the modules they don't need

I dunno.  My daughter was able to figure that out when she was 13.  Maybe you're only seeing the stupid people having trouble, not the 99% of people who can handle this just file.  70k servers using EssentialsX according to bStats, and you're just seeing a few with problems.

Anyway, that's my opinion.  I just started building my own version of EssentialsX so I could get three lines of customizations (Social Spy format change and logging /tpr destinations), so I won't be using your download links.
