### ISSUE TITLE
/back error

### ISSUE THREAD

**Issue by Bricec6** [EssentialsX/Essentials#3501]
<!-- EssentialsX bug reporting guide

Hello since the essentials update, my players who die in a different basic world and do /back end up kicking with an error message:

![image](https://user-images.githubusercontent.com/51750055/87423280-57838180-c5da-11ea-8137-3ff22dedd977.png)

**Comment by Bricec6** [comment]
My message didn't put
Hello when my players die in a different world and make /back it up to them:

![image](https://user-images.githubusercontent.com/51750055/87435038-7cccbb80-c5eb-11ea-962f-8baa879888a5.png)

**Comment by JRoy** [comment]
Please follow the issue template and resubmit your issue
