### ISSUE TITLE
Banned for helping someone????????!

### ISSUE THREAD

**Issue by moom0o** [EssentialsX/Essentials#3503]
I was helping someone in the M.O.S.S discord with their server, and now I'm banned?

**Comment by moom0o** [comment]
Why closed? I didn't break any rules.

**Comment by Blamo27** [comment]
@moom0o Don't create an issue on GitHub to know the ban reason of a Discord server ...
Go back to the SkyBlock island MooMoo : 

![image](https://user-images.githubusercontent.com/971712/87437145-37f65400-c5ee-11ea-8012-fa2c1b856fb4.png)

**Comment by moom0o** [comment]
But all I did was help someone. I didn't break any rules?

**Comment by 3Q6Dev** [comment]
If this isn't the correct place, then where should they appeal their ban?
