### ISSUE TITLE
Missing config parts

### ISSUE THREAD

**Issue by Gumpah** [EssentialsX/Essentials#3507]
### Information

Full output of `/ess version`:
```
Version Server : 1.15.2-R0.1-SNAPSHOT git-Paper-284 (MC: 1.15.2)
Version EssentialsX : 2.18.0.0
Version LuckPerms : 5.1.26
Version Vault : 1.7.2-b107
Version EssentialsXChat : 2.18.0.0
Version EssentialsXSpawn : 2.18.0.0
Version ChestShop : 3.11 (build 213)
```

### Help request

**Problem**

Hi, there are missing parts in my config.yml file, like the command-cooldowns one.

**What I have tried**

Well, nothing for now.

Thanks for your time!

**Comment by pop4959** [comment]
Config has never been updated automatically for Essentials. You can check the update notes for changes on what got added, and add in any that you find are missing. There is a reference config [here](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/config.yml) as well, if you want to compare it to yours.

**Comment by Gumpah** [comment]
Thank you!
