### ISSUE TITLE
AFK system

### ISSUE THREAD

**Issue by danechek** [EssentialsX/Essentials#3511]
I would like there to be a function for assigning a point for afk players - players go to afk and teleport them to this place until they leave the afk.

**Comment by jellz** [comment]
What do you want to happen once the player becomes active again?

Just keep them at the AFK point? Teleport them back to their previous location? Teleport them to spawn?

**Comment by danechek** [comment]
Keep them at the AFK point while they are AFK, and then return them to their place.

**Comment by danechek** [comment]
> What do you want to happen once the player becomes active again?
> 
> Just keep them at the AFK point? Teleport them back to their previous location? Teleport them to spawn?

Keep them at the AFK point while they are AFK, and then return them to their place.

**Comment by sarah-oreilly** [comment]
I'd like to claim this issue. Should I draft the interface or would the maintainers do that?

**Comment by Laarryy** [comment]
This is out of scope for the basic AFK functionality that EssentialsX offers, and likely will not be implemented anytime soon, if ever. If you'd like this feature, you'll need to use a more advanced AFK plugin.
