### ISSUE TITLE
/world doesn't work as expected; doesn't teleport you to set location.

### ISSUE THREAD

**Issue by Osome101** [EssentialsX/Essentials#3512]
### Information

**Full output of `/ess version`**:

```
[17:16:11] [Server thread/INFO]: Server version: 1.16.1-R0.1-SNAPSHOT git-Spigot-05da6fa-b0c6dfe (MC: 1.16.1)
[17:16:11] [Server thread/INFO]: EssentialsX version: 2.17.2.0
[17:16:11] [Server thread/INFO]: LuckPerms version: 5.1.26
[17:16:11] [Server thread/INFO]: PlaceholderAPI version: 2.10.6
[17:16:11] [Server thread/INFO]: Vault version: 1.7.2-b107
[17:16:11] [Server thread/INFO]: Citizens version: 2.0.27-SNAPSHOT (build 2019)
[17:16:11] [Server thread/INFO]: EssentialsXChat version: 2.17.2.0
[17:16:11] [Server thread/INFO]: EssentialsXSpawn version: 2.17.2.0
[17:16:11] [Server thread/INFO]: You are running an unsupported server version!
```

**Server log**: osome101 issued server command: /world castle-bw

**EssentialsX config**: https://gist.github.com/Osome101/83ddaf56c8c5a627879c0da644387168

### Details

**Description**  
When I run the /world command, it tells me "Error: Hole in floor!"

Before everyone starts yelling at me that this is an unsupported server version, this also happened in 1.15.2 which I'm pretty sure is supported. I have already upgraded my server and I'm unable to run 1.15.2 without corrupting my worlds, and going through a tremendous hassle. I understand if you cant help me, but any help would be appreciated.
**Steps to reproduce**  
Download a bedwars/skywars map (void world), load in with multiverse. run ``/setworldspawn`` where you would want the spawn point to be. Now go to a different world. I went to _world_. When I execute the ``/world [world name]``, I get the error. Error: Hole in floor!

Even without a void world, when my server was running 1.15.2, I was unable to set a location I wanted everyone to ``/world`` to.

I checked all of the essentials commands here: https://sites.google.com/site/mhnpsminecraft/plugins/essentials-commands due to the one in the wiki being down at the moment (https://essinfo.xeya.me/index.php?page=commands), and was uable to find anything related to setting up ``/world``
**Expected behavior**  
I expected to be teleported to the specified world at the spawn locations (even logout location should be fine)
**Screenshots**  
none

**Comment by pop4959** [comment]
It seems to work as expected, no bugs here. The `/world` command does *not* teleport you to the world's spawn. It teleports you to the *same location* you are currently at, in the other world. If you want to teleport to a *specific* location, use `/tppos` instead, or another appropriate command.

MC 1.16.1 is supported on Essentials 2.18.0 and higher -- please update immediately to avoid any issues on your server version.

The `Error: Hole in floor!` message means that it failed to teleport you because the location was unsafe to teleport to, due to there being no blocks to teleport onto.
