### ISSUE TITLE
Trade signs bug (suffix)

### ISSUE THREAD

**Issue by EliasRipley** [EssentialsX/Essentials#3514]
Version: 2.18.05
Issue: Trade signs do not function correctly if "currency-symbol-suffix:" is set to true.
https://media.discordapp.net/attachments/426460575971672064/734064501229486090/2020-07-18_16.08.27.png?width=936&height=527
You are able to sell items for currency, but you cannot set the sign to buy items with currency in this circumstance.
Have confirmed that when setting the "currency-symbol-suffix" back to false, the trade signs function correctly again.

**Comment by pop4959** [comment]
The bottom sign looks like it has more than one problem with it, I don't think the stock is supposed to have a currency symbol in it.

**Comment by EliasRipley** [comment]
From what I remember, it was throwing that in when I was just inputting numeric data. (Which works when trading the other way fine.)
I'll swap the config back and double check this for you though.

**Comment by EliasRipley** [comment]
Yup. With this setting as false, I am able to not have to worry about using the currency symbol (which is **c** in our server, short for "coins" and why we would prefer it as a suffix.)
However, if true, it throws up this "Error: Quantities must be greater than 0"

**Comment by EliasRipley** [comment]
Actually this is stranger than expected, trying just numbers on third line (10:2) gets the screenshot result "sign has nothing for you"
If I try:
10c:2 - I get "quantities must be greater than 0"
c10:2 - I get "null"

**Comment by EliasRipley** [comment]
Switching back to **false** for now though. 😄

**Comment by pop4959** [comment]
@EliasRipley I couldn't replicate the issue as you described it here so I'll probably close this later unless there is more information. Can you provide your full Essentials config as well as other required information for the bug report (server version, /essentials version, etc)? An example of setting up working signs vs not when the option is switched to true would be helpful as well.

**Comment by JRoy** [comment]
Should be fixed as of latest dev builds, let me know if the issue persists
