### ISSUE TITLE
Does EssentialsX work with GriefPrevention?

### ISSUE THREAD

**Issue by sophie462** [EssentialsX/Essentials#3515]
When I use /containertrust public or /accesstrust public, players are not allowed to interact with objects. However, when I removed EssentialsX, the permission commands worked. I know that EssentialsX does not recognize @'s, so maybe it does not recognize 'public' either? Is there a way to work around this problem?

**Comment by pop4959** [comment]
Essentials does not have a `/containertrust` command. If you are having trouble with GriefPrevention you should go ask their support instead. It's extremely unlikely that Essentials is the issue here.
