### ISSUE TITLE
Unable to have no currency symbol

### ISSUE THREAD

**Issue by YanisBft** [EssentialsX/Essentials#3517]
### Information

**Full output of `/ess version`**:

```
Server Version: 1.16.1-R0.1-SNAPSHOT git-Paper-79 (MC: 1.16.1)
EssentialsX Version: 2.18.0.0
PermissionsEx Version: 1.23.4
Vault Version: 1.7.3-b131
EssentialsXChat Version: 2.18.0.0
EssentialsXSpawn Version: 2.18.0.0
```

**Server log**: https://gist.github.com/Yanis48/64eb91b37a977980344945925b8a4547
**Essentials Config**: https://gist.github.com/Yanis48/ac0d5a36a4579c220422d813d2fdb6f3

### Details

**Description**  
It's not possible to not have any currency symbol shown. Instead, the dollar symbol is shown.

**Steps to reproduce**
1. Open the config file
2. Set the `currency-symbol` config option to `''`
3. Run `/ess reload` command on the server

**Expected behavior**  
I expected to not have any currency symbol shown next to the money, but instead dollar symbol was shown.

**Comment by ToonTown0909** [comment]
Hello! I see that you're missing the server log and `config.yml` from your bug report. Would you be able to include those please?

**Comment by YanisBft** [comment]
@ToonTown0909 done

**Comment by pop4959** [comment]
Was this possible before? Or is this a suggestion? I don't think there was any ever intention to use no currency symbol.

**Comment by YanisBft** [comment]
I'm sure it worked before 2.18.0, as my server's money did not have any symbol

**Comment by JRoy** [comment]
Fairly certain this was never possible. This would add a lot of problems with detecting money strings let alone ones we can easily find with how big the codebase it.

**Comment by triagonal** [comment]
This can be accomplished (visually) by editing the `currency` key in `messages.properties`. See #127 for more information.
