### ISSUE TITLE
When freed from jail players are teleporting back to previous position

### ISSUE THREAD

**Issue by Magiks21** [EssentialsX/Essentials#3520]
### Information

**Full output of `/ess version`**:
```
Server version: 1.16.1-R0.1-SNAPSHOT git-Paper-83 (MC: 1.16.1).
EssentialsX version: 2.18.0.0.
LuckPerms version: 5.0.72.
Vault version: 1.7.2-b107.
EssentialsXChat version: 2.18.0.0.
```
**Server log**: https://gist.github.com/Magiks21/c6f8466ffe6272916684b7dd9019bf6d
**Essentials Config**: https://gist.github.com/Magiks21/009fd6c5ea137fb753e8ae712d20e80a

### Details

**Description**  
Despite having the teleport-back-when-freed-from-jail node set to "false" in the configuration, players are still being returned to previous position.

**Steps to reproduce**  
Set teleport-back-when-freed-from-jail node to "false". Jail Player. Unjail Player.

**Expected behavior**  
Player is not teleported back to previous position

**Screenshots**
Player Returning to previous position 2000+ blocks from jail
![2020-07-19_11 02 39](https://user-images.githubusercontent.com/2476446/87879455-eddbec80-c9b8-11ea-8072-3e3ac86461d3.png)

**Comment by ToonTown0909** [comment]
Hello! Would you please fill out the full bug report format? Many thanks! https://github.com/EssentialsX/Essentials/issues/new?template=report-a-bug.md

**Comment by Magiks21** [comment]
Sorry about that. Got a bit ahead of myself. Should be in line with report guidelines
