### ISSUE TITLE
invsee armor suggestion

### ISSUE THREAD

**Issue by bojaspie** [EssentialsX/Essentials#3521]
I suggest to make invsee PlayerName Armor to be editable, it will make it a bit easier to catch auto armor hackers
thanks.

**Comment by ToonTown0909** [comment]
This is already a feature. You'll need the following permission nodes.

1. essentials.invsee
2. essentials.invsee.equip
3. essentials.invsee.modify

**Comment by bojaspie** [comment]
this works for /invsee "player"
but it doesnt work for /invsee "player" armor

**Comment by JRoy** [comment]
Duplicate of #472 

See https://github.com/EssentialsX/Essentials/issues/472#issuecomment-196002401 for more information on why this feature isn't in Essentials.

We suggest you use a plugin like [OpenInv](https://dev.bukkit.org/projects/openinv) if you need this functionality.
