### ISSUE TITLE
Pay using units representing various quantities

### ISSUE THREAD

**Issue by Superalex0102** [EssentialsX/Essentials#3524]
### Feature request

**Feature description**

**How the feature is useful**

Hey!
I would like to suggest an idea to upgrade the pay command as it would help players to transfer money easier!

You could use single units in the pay command
e.g: /pay Steve 100k

In the economy configuration there would be a new section which allows to edit the units as a lot of countries have it differently.

**Comment by JRoy** [comment]
I see this leading to confusion among users as the currency symbol is configurable and can be set to one of these units. For that reason I don't think this is something we can add.
