### ISSUE TITLE
Disabling Creeper Explosions Also Disables Damage

### ISSUE THREAD

**Issue by Qrbaker** [EssentialsX/Essentials#3526]
### Information

**Full output of `/ess version`**:

```

[21:22:46 INFO]: Server version: 1.16.1-R0.1-SNAPSHOT git-Paper-90 (MC: 1.16.1)
[21:22:46 INFO]: EssentialsX version: 2.18.0.0
[21:22:46 INFO]: LuckPerms version: 5.1.75
[21:22:46 INFO]: EssentialsXProtect version: 2.18.0.0

```

**Server log**: https://gist.github.com/Qrbaker/5d755a16e753ddf4b9afed3a78a8986e

**EssentialsX config**: https://gist.github.com/Qrbaker/31b2be392f2f742555d21e21defd9ad8

### Details

**Description**  
I noticed that when setting `creeper-explosion` to `true` under the EssentialsX protect section, Creepers *also* stopped having any damage, despite all other creeper damage settings left on `false`

**Steps to reproduce**  
Set `creeper-explosion` to true in `config.yml`

Approach a creeper in game and you will receive no damage when it explodes.

**Expected behavior**  
I expect no _block damage_ to occur, but all other explosive damage to be as normal

**Screenshots**  
https://streamable.com/8rf45h

**Comment by pop4959** [comment]
Creeper explosion probably disables it entirely. You probably mean this:

```
    creeper-explosion: false
    creeper-playerdamage: false
    creeper-itemdamage: true
    creeper-blockdamage: true
```

**Comment by Qrbaker** [comment]
I'll give that a shot and report back.

**Comment by Qrbaker** [comment]
Yep, seems to do the trick, thanks. I'll submit a PR for updated docs.
