### ISSUE TITLE
Limit Baltop - Show Only Those Online

### ISSUE THREAD

**Issue by Ergenta** [EssentialsX/Essentials#3527]
### Feature request

**Feature description**
Add ability to only show those online when the command /baltop is run

**How the feature is useful**
Stops lag from loading all player data

**Comment by pop4959** [comment]
Baltop caches data so it actually shouldn't cause much/any lag at all. It just takes a while for updated information to display. Is there another reason why you only want online players to show? It kind of defeats the purpose of it listing the "top" players, when the top players aren't even online.

**Comment by Ergenta** [comment]
Lag was the only reason. If there's really no difference, I suppose this is moot
