### ISSUE TITLE
SUGGESTION More Permisions for Essentials Speed. essentials.speed.fly.10

### ISSUE THREAD

**Issue by jokbon** [EssentialsX/Essentials#3533]
### Feature request

**Feature description**

**Please add aditional speed permisions.**
essentials.speed.fly.10 
essentials.speed.walk.10

**How the feature is useful**
It will help players deliver theyr builds faster. 

Instead of flying hours ower empty plots players could reach theyr destinations faster. 

Useful for donator ranks.
 
If server starts laging speed can be slowed down.

**Comment by pop4959** [comment]
The speed is based on a scaling factor, which can be edited in the config. You can use that to make it slower.

**Comment by jokbon** [comment]
But then permisions per ranks wont work.

**Comment by pop4959** [comment]
You can already do this. Please read <https://essinfo.xeya.me/permissions.html>.

**Comment by jokbon** [comment]
Not posible for automation it will require server owner interaction to scale slower than vanila. but thanks anyway.

**Comment by jokbon** [comment]
if limit was 0.5 in config
