### ISSUE TITLE
Error: Nicknames can only have their colors changed

### ISSUE THREAD

**Issue by RoboMWM** [EssentialsX/Essentials#354]
Build 245

I get the above error message when attempting to use /nick even if doing /nick off or a nickname without color or formatting as an op. This doesn't seem to affect those who only have essentials.nick.color (and essentials.nick iirc).

**Comment by SupaHam** [comment]
You have to negate the `essentials.nick.changecolor` permission.

**Comment by RoboMWM** [comment]
Could you add documentation about this permission node as it isn't in the upstream Essentials documentation?
