### ISSUE TITLE
essentials.balancetop.exclude doesn't work when the player is offline

### ISSUE THREAD

**Issue by Bloodlex** [EssentialsX/Essentials#3540]
### Information

**Full output of `/ess version`**:

```
26.07 05:56:19 [Server] INFO Server wersja: 1.15.2-R0.1-SNAPSHOT git-Paper-380 (MC: 1.15.2)
26.07 05:56:19 [Server] INFO EssentialsX wersja: 2.18.0.0
26.07 05:56:19 [Server] INFO PlaceholderAPI wersja: 2.10.6
26.07 05:56:19 [Server] INFO LuckPerms wersja: 5.1.26
26.07 05:56:19 [Server] INFO Vault wersja: 1.7.3-b131
26.07 05:56:19 [Server] INFO EssentialsXChat wersja: 2.18.0.0
26.07 05:56:19 [Server] INFO EssentialsXSpawn wersja: 2.18.0.0
```

**Server log**: 
Not relevant

**EssentialsX config**: 
https://pastebin.com/X4WEinAU

### Details

**Description**  
Although a user has essentials.balancetop.exclude, is still visible in /baltop view. I think that it tries to check the permission of offline player and can't get it. If this player is online sometimes is not visible and visible if offline.
--

**Steps to reproduce**  
Add essentials.balancetop.exclude and go offline with this user.

**Expected behavior**  
User should never be visible on baltop view. Maybe some config option instead of permission if it is not available offline.

**Screenshots**

**Comment by pop4959** [comment]
This issue is already known (see #3004) but we were not planning on fixing it, because it is a permission related issue. Although, I don't know that anyone actually looked into it much. I've heard contradictory things recently about whether or not permission checks can be done while the player is offline. I'll give it a closer look, but if it isn't fixable this will be closed again.

**Comment by Bloodlex** [comment]
Can we base it on a config rather than permission if it can't be done? It would be really useful for my server. Please don't close this :(

**Comment by pop4959** [comment]
There is a separate issue open for that already, so I will close this issue in favor of that one if the permissions problem is not fixable.

**Comment by Bloodlex** [comment]
Thank you I really would need that to work :)
