### ISSUE TITLE
RGB Gradient for text

### ISSUE THREAD

**Issue by CaszGamerMD** [EssentialsX/Essentials#3541]
example of how it could be done:
&(#22ff00,#0e49a6)this text starts green and ends teal

ideally would support multiple stops in the gradient:
&(&#FF0000,#ff5c00,#ff9e00,#ffe400,#9cf000,#22ff00,#158080,#0800ff,#3707d5,#6c0ea6)Rainbow text with a pretty smooth gradient

**Comment by ToonTown0909** [comment]
This idea is 😍

**Comment by pop4959** [comment]
Closing in favor of #2391, as this will almost certainly not happen before then. I recommend downloading another chat plugin that already has gradient support if you want this kind of advanced feature right now on your server.

**Comment by ConaII** [comment]
ServerlistMOTD does a pretty good job at this!
![image](https://user-images.githubusercontent.com/72966048/142705042-b99738d9-2bf6-480c-9f70-8bc4b07665e8.png)
<g:#FF4B00:#FFAA00>

https://github.com/strumswell/ServerlistMOTD-X/blob/master/src/cloud/bolte/serverlistmotd/util/Gradient.java
https://github.com/strumswell/ServerlistMOTD-X/blob/master/src/cloud/bolte/serverlistmotd/util/HexResolver.java
