### ISSUE TITLE
com.earth2me.essentials.signs.SignPlayerListener.onSignPlayerInteract

### ISSUE THREAD

**Issue by Marcuri02** [EssentialsX/Essentials#3542]
### Information

**Full output of `/ess version`**: **Essentials X 2.18.0.7**

```
**Essentials X 2.18.0.7**
```

**Server log**: 

https://gist.github.com/Marcuri02/ac89cef5aa9b3cd57f0f91377803106b

**EssentialsX config**: 

**https://gist.github.com/Marcuri02/8522f66dfbf16f82a9b335f780e69118**

### Details

**Description**  
My server falls because of error with 
com.earth2me.essentials.signs.SignPlayerListener.onSignPlayerInteract

**Steps to reproduce**  
Don't know

**Expected behavior**  
Load it async?

**Screenshots**

**Comment by pop4959** [comment]
I don't see any error from Essentials in your log. You should fix your other plugins though.

**Comment by Marcuri02** [comment]
Logs didn't posted well. You can see it here:
https://paste.gg/p/anonymous/070f560bca934fd0944e84b25a998f9c

**Comment by JRoy** [comment]
You have tens of other errors in your server, this error hasn't come up from anyone else and the line this error is generating from makes no sense for it to be generating from.

Make sure you're on the latest Paper and EssX builds too
