### ISSUE TITLE
/eco take ** <percentage> is not removing properly

### ISSUE THREAD

**Issue by GLufano** [EssentialsX/Essentials#3547]
### Information
**Full output of `/ess version`**:

```
>.... [03:30:44 INFO]: Server version: 1.16.1-R0.1-SNAPSHOT git-Paper-117 (MC: 1.16.1)
>.... [03:30:44 INFO]: EssentialsX version: 2.18.0.0
>.... [03:30:44 INFO]: PlaceholderAPI version: 2.10.7-DEV-${BUILD_NUMBER}
>.... [03:30:44 INFO]: LuckPerms version: 5.1.81
>.... [03:30:44 INFO]: Vault version: 1.7.3-b131
>.... [03:30:44 INFO]: EssentialsXGeoIP version: 2.18.0.0
>.... [03:30:44 INFO]: EssentialsXAntiBuild version: 2.18.0.0
>.... [03:30:44 INFO]: EssentialsXSpawn version: 2.18.0.0
```

**Server log**: https://gist.github.com/GLufano/e760ae4e02a33f7219ce7bf5aea11509
 **Essentials Config**: https://gist.github.com/GLufano/b1b9de24e20e515a98285c16f008ee5c

### Details
 **Description**
Trying to remove from all players balance with /eco take ** 1% and is not removing properly.
He starts by taking out the correct balance, but goes to a slightly strange amount and I get "insufficient money" and just stop, i have about 130 registered players, but he stops in the fourth. (Lines 841 - 846)
```
[03:52:24] [Server thread/INFO]: CONSOLE issued server command: /eco take ** 1%
[03:52:24] [Server thread/INFO]: 10,80₽ removido de Frajolao conta. Novo saldo: 1.069,74₽
[03:52:24] [Server thread/INFO]: 21,20₽ removido de David conta. Novo saldo: 175,03₽
[03:52:24] [Server thread/INFO]: 68,07₽ removido de JoneesXD conta. Novo saldo: 252,94₽
[03:52:24] [Server thread/INFO]: 743,46₽ removido de iblack__ conta. Novo saldo: 348,72₽
[03:52:24] [Server thread/INFO]: Erro: Dinheiro insuficiente.
```
I only have logs with Essentials translated into pt-BR, I hope you understand.
`<amount>₱ removed from <user> account. New balance: <new balance>₱`

**Steps to reproduce**

1. Send command `/eco take ** 1%`

**Expected behavior**
It is expected that 1% of the total balance is withdrawn from all players already registered.

**Comment by JRoy** [comment]
Fixed by #3337
