### ISSUE TITLE
Potion bug when type give or kit command

### ISSUE THREAD

**Issue by ItsCrazyFrog** [EssentialsX/Essentials#3550]
I found a bug with potions. When i type /give playername 373:8226 (speed 2) potion this error is in console:

30.07 18:39:07 [Server] INFO ItsCrazyFrog issued server command: /i potion:8233
30.07 18:39:07 [Server] ERROR Командата i беше неуспешна:
30.07 18:39:07 [Server] INFO java.lang.NoClassDefFoundError: org/bukkit/potion/PotionData
30.07 18:39:07 [Server] INFO at net.ess3.provider.providers.BasePotionDataProvider.createPotionItem(BasePotionDataProvider.java:56) ~[Essentials.jar:?]
30.07 18:39:07 [Server] INFO at com.earth2me.essentials.items.LegacyItemDb.get(LegacyItemDb.java:202) ~[Essentials.jar:?]
30.07 18:39:07 [Server] INFO at com.earth2me.essentials.items.AbstractItemDb.get(AbstractItemDb.java:87) ~[Essentials.jar:?]
30.07 18:39:07 [Server] INFO at com.earth2me.essentials.commands.Commanditem.run(Commanditem.java:29) ~[Essentials.jar:?]
30.07 18:39:07 [Server] INFO at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:168) ~[Essentials.jar:?]
30.07 18:39:07 [Server] INFO at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:615) [Essentials.jar:?]
30.07 18:39:07 [Server] INFO at com.earth2me.essentials.Essentials.onCommand(Essentials.java:525) [Essentials.jar:?]
30.07 18:39:07 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [custom.jar:git-TacoSpigot-unknown]
30.07 18:39:07 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:144) [custom.jar:git-TacoSpigot-unknown]
30.07 18:39:07 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:670) [custom.jar:git-TacoSpigot-unknown]
30.07 18:39:07 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1247) [custom.jar:git-TacoSpigot-unknown]
30.07 18:39:07 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1062) [custom.jar:git-TacoSpigot-unknown]
30.07 18:39:07 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [custom.jar:git-TacoSpigot-unknown]
30.07 18:39:07 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [custom.jar:git-TacoSpigot-unknown]
30.07 18:39:07 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [custom.jar:git-TacoSpigot-unknown]
30.07 18:39:07 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
30.07 18:39:07 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
30.07 18:39:07 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [custom.jar:git-TacoSpigot-unknown]
30.07 18:39:07 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:808) [custom.jar:git-TacoSpigot-unknown]
30.07 18:39:07 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:384) [custom.jar:git-TacoSpigot-unknown]
30.07 18:39:07 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:745) [custom.jar:git-TacoSpigot-unknown]
30.07 18:39:07 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:647) [custom.jar:git-TacoSpigot-unknown]
30.07 18:39:07 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**Comment by JRoy** [comment]
You didn't follow the issue template. Please follow the issue template and resubmit your issue.
