### ISSUE TITLE
Potion bug when type give or kit command

### ISSUE THREAD

**Issue by ItsCrazyFrog** [EssentialsX/Essentials#3551]
### Information

**Full output of `/ess version`**:
```
<!-- Run the command in your console, and copy and paste the whole output here -->
```
EssentialsX версия: 2.18.0
EssentialsXChat версия: 2.18.0
EssentialsXProtect версия: 2.18.0
EssentialsXSpawn версия: 2.18.0
**Server log**: 
https://gist.github.com/ItsCrazyFrog/10f707bba44f6a9e903dc0030069bc44

**EssentialsX config**: 
https://gist.github.com/ItsCrazyFrog/8155fc10aa08ba36f053378fbfebaf9f
### Details

**Description**  

I found a bug with potions. When i type /give playername 373:8226 (speed 2) potion i can't receive and have error
**Steps to reproduce**  

**Expected behavior**  

**Screenshots**

**Comment by JRoy** [comment]
you're missing the output of the `/ess version` command, please put that in the issue

**Comment by ItsCrazyFrog** [comment]
This si the output:
EssentialsX версия: 2.18.0
EssentialsXChat версия: 2.18.0
EssentialsXProtect версия: 2.18.0
EssentialsXSpawn версия: 2.18.0

**Comment by JRoy** [comment]
you're missing the `Server version` that comes right before that, please include that

if that doesn't show up, please share the output of `/icanhasbukkit`

**Comment by ItsCrazyFrog** [comment]
Server версия: 1.8.8-R0.2-SNAPSHOT Elapsed (MC: 1.8.8)
EssentialsX версия: 2.18.0
EssentialsXChat версия: 2.18.0
EssentialsXProtect версия: 2.18.0
EssentialsXSpawn версия: 2.18.0

**Comment by JRoy** [comment]
Your server software modifies the server version to something nonexistent, `1.8.8-R0.2`. Please either switch to [Paper](https://papermc.io/legacy) or ask your server software maker to fix their version string.

**Comment by ItsCrazyFrog** [comment]
In 2.17.2 version haven't this bug

**Comment by JRoy** [comment]
Correct, a new system in Essentials relies on manually checking versions to use certain features. Your spigot fork is unsupported and modified the server version to something that breaks said Essentials feature. Please either switch to [Paper](https://papermc.io/legacy) or ask your server software maker to fix their version string.
