### ISSUE TITLE
Custom Death Message

### ISSUE THREAD

**Issue by SkrillzPlayz** [EssentialsX/Essentials#3559]
###Custom Death Message

**Feature description**
Can customise death messages the same way as the join and leave in the config file. Additional option to have a single death message or have the vanilla ones but you are able to change stuff like the username display etc.

**How the feature is useful**
As some players are nicked or have colored names, it would be cool to be able to see that in death messages. Some of my friends have had their Minecraft account for years or are borrowing one and their username there is not the same or close at all to what they go by in Discord, so we use /nick but when they die it's hard to know who is who.

**Comment by pop4959** [comment]
Good idea, but I don't think it's something that needs to be a part of Essentials. Most people don't want to change a single death message, and having the option to change *every* death message in the game is an entire system in and of itself which is going to be a huge added maintenance burden, only for few people to actually utilize it. I recommend getting another specialized plugin for this such as [DeathMessagesPrime](https://www.spigotmc.org/resources/deathmessagesprime.3789/).
