### ISSUE TITLE
FLYSAFELOGIN

### ISSUE THREAD

**Issue by Someone-NEW** [EssentialsX/Essentials#356]
Hello i have new problem my players cand login i thing permission for flysafelogin not work when login to server and kick me before i can type any command. is there some other permission or what i can do?
I use NCP to but this is protection for hackers there is nothing wrong here is my print from console:

05.01 09:59:22 [Server] WARN handleDisconnection() called twice
05.01 09:59:22 [Server] INFO (CONSOLE) Kicked TEST : Kicked for flying (or related)
05.01 09:59:22 [Server] INFO - TEST
05.01 09:59:22 [Disconnect] User bigrazer has disconnected, reason: Kicked for flying (or related)

**Comment by SupaHam** [comment]
This has nothing to do with Essentials. This sounds like vanilla Minecraft.

**Comment by Someone-NEW** [comment]
Ok i solved this to downgrade NCP. butproblem with safelogin still. When player with all permissions login to server they are on the air and then fall down and fly and flysafelogin dont work. In that case flysafelogin not work correctly

**Comment by SupaHam** [comment]
I'm not entirely sure if this is our fault at all. As I said, this sounds like something vanilla Minecraft is doing based on that kick message.

**Comment by drtshock** [comment]
^
