### ISSUE TITLE
Switching Id's to Minecraft/Mod:Item in the items file

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#3560]
### Feature request

**Feature description**
Switching the ids to Minecraft/mod:Item in the items file

**How the feature is useful**-
Makes it more efficient filling the items file with modded and custom items

**Comment by pop4959** [comment]
Essentials does not officially support modded or hybrid style servers. You should file a bug report / question with your specific server vendor if you are having trouble specifying modded items.

**Comment by ghost** [comment]
I am the server vendor
It's that it uses ids which is a pain to find for different mods

**Comment by pop4959** [comment]
I highly doubt that you are the server vendor based on this interaction, however if you are, please make a PR to implement this feature and give a detailed explanation of why this would make sense for Essentials to consider maintaining this.

**Comment by mdcfe** [comment]
If you are the server vendor:
- Regardless of MC version, inject values into the Material enum with a sensible prefix such as `<modid>_<itemname>` - colons are messy for plugins to support in their configs.
- If your hybrid server supports 1.12.2 or older, expose modded items to methods that accept legacy IDs, and provide your users with a compatible `items.csv` file or a way to generate one from the game's item registry.
- If your hybrid server supports 1.13 or above, provide your users with a method to generate an `items.json` file from the game's item registry.

Given that I can't see any contributions to a hybrid server on your GitHub profile, and you don't seem to understand how EssentialsX handles items, I am also in doubt that you are a server vendor. EssentialsX does not and will not provide support or assistance for hybrid servers - if you want help using a hybrid server, contact the developer of that server.
