### ISSUE TITLE
/es alias for /editsign

### ISSUE THREAD

**Issue by TheNety** [EssentialsX/Essentials#3562]
Hey, sorry for removing the template but it would just make no difference at this simple request.
Could you please add `/es` alias for `/editsign` command? (Adding it on my own, in commands.yml doesn't work well, because the tabcomplete doesn't work there.)

**Comment by pop4959** [comment]
Have you tried the alias `es: essentials:editsign $1-`?

**Comment by TheNety** [comment]
Yes, that also throws a player names instead of the line content as tabcomplete suggestion.

**Comment by pop4959** [comment]
We will not be adding additional aliases for this command, as you can already use `/sign` or `/esign` as shorthand.

Also, it seems like tab completion for aliases not working is an upstream bug. Please report it to Spigot/Paper instead, as we cannot fix that in Essentials.
