### ISSUE TITLE
Tpa request still persists even after accepted

### ISSUE THREAD

**Issue by wellnesscookie** [EssentialsX/Essentials#3563]
### Information

**Full output of `/ess version`**:

```
[22:42:44 INFO]: Server version: 1.13.2-R0.1-SNAPSHOT git-Paper-655 (MC: 1.13.2)
[22:42:44 INFO]: EssentialsX version: 2.18.0.0
[22:42:44 INFO]: LuckPerms version: 5.1.26
[22:42:44 INFO]: Vault is not installed. Chat and permissions may not work.
```

**EssentialsX config**: https://gist.github.com/wellnesscookie/eb047f01596b0a24e3143fdf2d6ada81

### Details

**Description**  

**Steps to reproduce**  
- Use builds as above
- Use our configuration
- Be sure not to be an operator, but rather a default player with tpaccept and tpa permissions
- Send a /tpa request to another player
- Have that player type /tpyes (success)
- Have that player **retype** /tpyes (success and is able to spam it for another 120 seconds)

**Expected behavior**  
I cannot reproduce this bug on original 2.17.2 release, but I can reproduce it on 2.17.2.136 and I can reproduce it on 2.18.2 as well! The tpa request should become INVALID or GONE after it's accepted for the first time as the request has been approved. If you wish to tpa again to the player, then you should send another request.

I reproduced this on a localhost, fresh server, with Essentials and Luckperms only.

**Screenshots**  
From two perspectives: 

One sends, and one accepts (maybe the order of the videos is not good, but you will understand)
_________________________________
VIDEO 1
vimeo.com/443980713/
_________________________________
VIDEO 2
vimeo.com/443982415/
__________________________________

**Addiditonal information:**
- If you test as OP, your TPA request will be completed after first acceptance and you won't be able to spam it, as it will require you to request another. If you do this, you will not be able to reproduce this bug.

**Comment by pop4959** [comment]
Thanks for reporting! I was able to confirm the bug, and found the source of the problem. Should hopefully be fixed soon.

**Comment by MithrandirCraft** [comment]
> 
> 
> Thanks for reporting! I was able to confirm the bug, and found the source of the problem. Should hopefully be fixed soon.

Do you still need my logs/config?

**Comment by pop4959** [comment]
@MithrandirCraft Check if it's fixed first on the latest build
