### ISSUE TITLE
Essentials Eggs Issue

### ISSUE THREAD

**Issue by DebuffPvP** [EssentialsX/Essentials#3565]
**Description**  
So the current issue i am having is when i updated essentials to the newest version which is 2.18.0 and i do /give [player] 383:50 it won't give them a creeper egg it just gives an egg without a mob called spawn egg is there a way to fix this?

**Spigot Version**  
1.8.8 tacospigot

**Comment by pop4959** [comment]
Please fill out the entire issue template and reproduce it on a supported server software
