### ISSUE TITLE
Teleport Safety

### ISSUE THREAD

**Issue by Mikgreg** [EssentialsX/Essentials#357]
Hey, sorry for bugging with tickets.

FBasics says to add the following line to your config to prevent people glitching into bases with 'unsafe' tpas:

force-disable-teleport-safety: true

I enabled this, but soon after many people reported not being able to teleport to their homes that they have set. Is there a way to just make it teleport them into the unsafe area instead of just completely cancelling the tp?

**Comment by vemacs** [comment]
Yes. Read the documentation: https://github.com/drtshock/Essentials/wiki

> EssentialsX adds a force-disable-teleport-safety option (default false) that when **combined** with teleport-safety: true, disables conversion to safe locations and teleports the user to their exact location.

**Comment by Mikgreg** [comment]
I have read the documentation however I'm afraid I'm misunderstanding it... I've combined the two and people still report not being able to teleport to places. They can't even teleport to spawn which is in a safe location.
