### ISSUE TITLE
CREEPER EGGS

### ISSUE THREAD

**Issue by crazyspider12** [EssentialsX/Essentials#3571]
d

**Comment by pop4959** [comment]
Are you able to replicate this without ViaVersion installed (nor other non-critical plugins)?

**Comment by arockstar28** [comment]
> Are you able to replicate this without ViaVersion installed (nor other non-critical plugins)?

Yes. Still does not work.

**Comment by JRoy** [comment]
A new system in Essentials relies on manually checking versions to use certain features. Your spigot fork is unsupported and modified the server version to something that breaks said Essentials feature. Please either switch to [Paper](https://papermc.io/legacy) or ask your server software maker to fix their version string.
