### ISSUE TITLE
Command cost behaviour with teleporting

### ISSUE THREAD

**Issue by elijahblooom** [EssentialsX/Essentials#3573]
### Feature request
Add additional customisation to how a player is charged in regards to the success of a teleport.

**Feature description**
There should be an option in the config to determine whether players are charged either when initiating a teleport (whether that is a /tpa request, /warp, /spawn etc..) or whether they are charged once a teleport is successful.

Something like:
`    charge-on-teleport-success: true`
could determine whether players are charged for initating a teleport, or charged for successfully teleporting.

**How the feature is useful**
This would allow a server owner to prevent users from being charged for failed teleports, such as moving during the wait delay, or being denied a teleport request. It is unknown to the player whether a teleport will be successful, and so implementing this could mitigate teleporting being a gamble, where a player risks wasting their money for no reason.

Implementation might also solve #3518

**Comment by hqppyz** [comment]
Why would there be two options, one for initiating the teleport and one when the event completed successfully?
When would you charge someone for unsuccessful teleports?

My idea is to move the payment strictly to successful teleports rather than charging it before.

**Comment by JRoy** [comment]
> My idea is to move the payment strictly to successful teleports rather than charging it before.

this is how it *should* be. if you're being charged for failed teleports thats a bug which should be fixed

**Comment by hqppyz** [comment]
> if you're being charged for failed teleports thats a bug which should be fixed

Should this be labeled as an (unconfirmed) bug rather than enhancement?

**Comment by JRoy** [comment]
Should be fixed as of latest dev builds, please let me know if that is not the case.
