### ISSUE TITLE
Extend the essentials.nick.rgb permission

### ISSUE THREAD

**Issue by Sikatsu** [EssentialsX/Essentials#3574]
### Feature request

**Feature description**
Allow only certain hexcodes. Allowing every hexcode in the world requires a lot of moderation.

essentials.nick.rgb.FFFFFF would allow the use of &#FFFFFF

**How the feature is useful**
Requires less moderation, and you can define the hexcodes they are allowed to use.
For example only allow the hexcodes that are used in the server ranks, so they can atleast mix&match their nickname with that.

**Comment by Octol1ttle** [comment]
I don't think that's possible, adding a permission in the code manually for each HEX combination. Maybe it can be done, but there's no method I know of

**Comment by Sikatsu** [comment]
It is possible, as CMI has recently added this ^^

**Comment by pop4959** [comment]
Closing this since it doesn't seem like this is a very popular request. I don't think CMI is a good example in this case, since for users it would be extremely annoying to only have access to individual hex codes. All or nothing is a good policy here.
