### ISSUE TITLE
Getting a skull of an offline player causes lag

### ISSUE THREAD

**Issue by ChrisTaylor201** [EssentialsX/Essentials#3575]
#### Full output of `/ess version`:

```
[14:25:42] [Server thread/INFO]: Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-384 (MC: 1.15.2)
[14:25:42] [Server thread/INFO]: EssentialsX version: 2.18.0.18
[14:25:42] [Server thread/INFO]: Vault is not installed. Chat and permissions may not work.
```

**Server log:** https://gist.github.com/christaylor201/54ca7c5a575314395371c0d25f1a0403

**EssentialsX config:** https://gist.github.com/christaylor201/b8435f6d240c1df640edc779676ba1e6

### Help request

**Problem**
Getting a skull of an offline player using `/skull` command causes lag. I've noticed similar issue with other plugins using skulls in GUIs ([BossShopPro](https://www.spigotmc.org/resources/222/), [VotingPlugin](https://www.spigotmc.org/resources/15358/)) or on armor stands ([LeaderHeads](https://www.spigotmc.org/resources/2079/)).

**What I have tried**
I've tried to replicate this issue on a local server with nothing but EssentialsX installed; it was a success, see the [Timings report](https://timings.aikar.co/?id=80de7fb028444b32ac41d4743e515021). It isn't that noticeable on a local server, but on a production server with ~10 players online and 50 plugins it drops TPS quite a bit.

**Screenshots**
none

**Comment by pop4959** [comment]
Almost certainly not an EssentialsX issue. Please see #3410 and #3555 for recent problems with this command. Notably, you should  try either 1) updating Paper, or 2) downgrading Paper to build 354 or lower (according to the former mentioned issue).

**Comment by ChrisTaylor201** [comment]
Okay, thank you, I wanted to be 100% sure. I'll forward this issue to PaperMC.

**Comment by ChrisTaylor201** [comment]
I was told by aikar that you should create the item asynchronously to avoid this issue, see the [ticket](https://github.com/PaperMC/Paper/issues/4075).

**Comment by JRoy** [comment]
Closing in favor of #3579. I'll handle this on my command rework PR.

**Comment by ChrisTaylor201** [comment]
Oh, sorry for reopening, I haven't checked the issues before commenting.
