### ISSUE TITLE
/pay for offline users

### ISSUE THREAD

**Issue by partydev** [EssentialsX/Essentials#3577]
### Feature request

**Feature description**
Implement being able to pay users even if they are offline. /eco give [offlineplayer] is an option, so I do not see why this cannot be implemented.

**How the feature is useful**
Brings me peace of mind because my players complain about features that make sense being added too often.

This is very similar to #1772, if it is difficult as said in there, would appreciate a little clarification because it seems potentially trivial.

**Comment by oranges13** [comment]
This would be a really great addition if it could be added, thanks!

**Comment by JRoy** [comment]
see #3625

**Comment by oranges13** [comment]
Yes I'm asking them to merge it :)
