### ISSUE TITLE
Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.0.1-b245

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#358]
Hello, my console is spamming this error http://pastebin.com/nUX66wyj (sorry for not providing full error, cant find the full error log). I hope this will be fixed next patch.

**Comment by drtshock** [comment]
Which version of pex are you using?

**Comment by ghost** [comment]
v1.19.6 since I don't need UUID support as I have a offline-mode server :)

**Comment by vemacs** [comment]
We don't support legacy software OR cracked servers.

**Comment by ghost** [comment]
but.. why not, I mean what is so bad about it?
