### ISSUE TITLE
Add json clickables to /tpa and /tpahere

### ISSUE THREAD

**Issue by imDaniX** [EssentialsX/Essentials#3582]
### Feature request

**Feature description**
Add clickable json messages for /tpyes and /tpno commands in /tpa and /tpahere commands.
Alternately - possibility to hide messages with TPARequestEvent, so some third-party plugin can send custom messages.

**How the feature is useful**
Sometimes it's easier to click a message instead of using commands.

**Comment by pop4959** [comment]
Please discuss this in #2391, as this includes discussion for future chat related improvements including JSON messages.

**Comment by imDaniX** [comment]
@pop4959, seems like this issue/discussion is pretty "long-termy"... What about alternative from my initial message?

**Comment by pop4959** [comment]
You can set the message to blank in a custom language file and that will disable it, if you want to send your own via the event. Adding this directly to Essentials will not happen as that is purely feature bloat, when this really should be properly implemented as discussed in the above issue.

**Comment by imDaniX** [comment]
Alrighty, thank you for helping. Wasn't thinking about removing the message from lang file by myself.
