### ISSUE TITLE
UUID offline mode

### ISSUE THREAD

**Issue by Niko302** [EssentialsX/Essentials#3583]
### Information

**Full output of `/ess version`**:
![2020-08-09_17 20 50](https://user-images.githubusercontent.com/40739919/89735704-b7980700-da64-11ea-8313-a3013d437465.png)

**Server log**:  https://pastebin.com/Lrw5hmrc

**EssentialsX config**:  Not needed

### Details

**Description**  
When using /PAPI ECLOUD DOWNLOAD VAULT
Essentialsx will create offline UUIDS that will break the /bal and /seen command randomly when a player is not online

**Steps to reproduce**  
Placeholder api plugin
/papi ecloud download vault

**Expected behavior**  
Not to create hundreds of offline mode files like the following
```
npc: true
lastAccountName: infinite_mist
money: '0'
```

I contacted placeholder api staff and got told it is an essentialsx issue.

**Comment by pop4959** [comment]
Essentials does not officially support offline mode servers.

**Comment by Niko302** [comment]
pop4959 it is bungeecord.

**Comment by Niko302** [comment]
and this have been issues before but not with placeholderapi vault. Well at least didn't see it mentioned in any of the following two threads:
https://github.com/EssentialsX/Essentials/issues/349
https://github.com/EssentialsX/Essentials/issues/1605
and upon removing the PlaceholderAPI for vault everything is working fine.

**Comment by pop4959** [comment]
@Niko302 Please provide a full server log and config as well.

**Comment by Niko302** [comment]
> 
> 
> @Niko302 Please provide a full server log and config as well.

It has nothing to do with the config it is default.
and server log just outputs creation of offline uuids.

**Comment by TKwSni** [comment]
This happened to me after using the essentials cleanup and then restart, something this command did that messed with all my players files now if they dont login their accounts money are in 0, removing papi extension Vault stops creating files, and yes I tried removing all plugins but these two... 

And is not adding an offline uuid, is just a random uuid.

**Comment by Niko302** [comment]
Bump, even after removing vault it started happening again.

**Comment by Chew** [comment]
is Bungeecord set to true in spigot.yml

**Comment by TKwSni** [comment]
Yes

> 
> 
> is Bungeecord set to true in spigot.yml

Yes

**Comment by Niko302** [comment]
Can someone please look at this ?

**Comment by pop4959** [comment]
Can you link to the issue on PlaceholderAPI where they explained why it is not their issue? I really doubt that this is an Essentials issue unless otherwise proven. Any plugins hooking into Essentials also need to be responsible about using the API.

**Comment by darbyjack** [comment]
This has been fixed with the latest release of the Vault expansion 3 days ago.

**Comment by pop4959** [comment]
Awesome, glad to hear! I guess we can close this then. @Niko302 @TKwSni Please update the expansion.
