### ISSUE TITLE
Unable to use Essentials signs with crimson or warped signs despite being created successfully

### ISSUE THREAD

**Issue by TrekkieEndermom** [EssentialsX/Essentials#3584]
### Information

**Full output of `/ess version`**:
[21:01:50] [Server thread/INFO]: Server version: 1.16.1-R0.1-SNAPSHOT git-Spigot-9639cf7-8fb6585 (MC: 1.16.1)
[21:01:50] [Server thread/INFO]: EssentialsX version: 2.18.0.0
[21:01:50] [Server thread/INFO]: LuckPerms version: 4.4.1
[21:01:50] [Server thread/INFO]: Vault version: 1.7.2-b107

**Server log**: https://gist.github.com/TrekkieEnderman/7d1da4544693526c6d918918736bb724

**EssentialsX config**: https://gist.github.com/TrekkieEnderman/bd04828f9e88abf39fb4474d8423eeb5

### Details

**Description**  
All the Essentials signs appeared to be created successfully on both crimson and warped signs, however right clicking these signs does nothing. No errors were thrown in the server console.

**Steps to reproduce**  
1. Opped myself on the server.
2. Gave myself a crimson sign and warped sign.
3. Placed both and wrote "[Disposal]" on both. Noted the text turned blue.
4. Right clicked both of the signs.
5. They did nothing.

**Expected behavior**  
I expected them to open the disposal GUI for me. Same with other Essentials signs such as Warp and Kit.

**Screenshots**  
https://youtu.be/wgUko4R8MW0

**Comment by pop4959** [comment]
You're on an outdated version of Essentials. This was fixed a while back, as signs were something that got missed among the other updates for 1.16. Download the latest version at [essentialsx.net](https://essentialsx.net/downloads.html) and it should work.
