### ISSUE TITLE
Essentials cause Residence speed setting invalid

### ISSUE THREAD

**Issue by flandretw** [EssentialsX/Essentials#3585]
### Information

Full output of `/ess version`:

[17:32:32 INFO]: Server 版本：1.15.2-R0.1-SNAPSHOT git-Paper-379 (MC: 1.15.2)。
[17:32:32 INFO]: EssentialsX 版本：2.18.0.18。
[17:32:32 INFO]: GroupManager 版本：0.3.0。
[17:32:32 INFO]: PlaceholderAPI 版本：2.10.9。
[17:32:32 INFO]: Vault 版本：1.7.2-b107。
[17:32:32 INFO]: Citizens 版本：2.0.26-SNAPSHOT (build 1861)。
[17:32:32 INFO]: EssentialsXChat 版本：2.18.0.18。
[17:32:32 INFO]: EssentialsXProtect 版本：2.18.0.18。
[17:32:32 INFO]: EssentialsXGeoIP 版本：2.18.0.18。
[17:32:32 INFO]: EssentialsXAntiBuild 版本：2.18.0.18。
[17:32:32 INFO]: EssentialsXSpawn 版本：2.18.0.18。
[17:32:32 INFO]: 你正在運行不被支援的插件！

**Server log:** https://gist.github.com/gregman98/78a9d042b4d9ec9b12f8bd1475481a74

**EssentialsX config** https://gist.github.com/gregman98/93c7c76a772266982308cc7ed36f62a3

### Help request

**Problem**
Essentials cause Residence speed(wspeed) flag invalid.
I'm not sure if it is the Residence or Essentials issue, so I have a asked on both sides.

**What I have tried**
Removed the Essentials and Residence speed working well.
Adjust the speed setting of Essentials, but it still doesn't work.
I have reported this situation to Residence author, but I don’t seem to get a response.

**Screenshots**
Not needed.

(Sorry for my bad English.)

**Comment by pop4959** [comment]
Does this happen still when you uninstall the other non-Essentials plugin(s)? If it doesn't, then it is a problem with those plugins, and not Essentials.

**Comment by flandretw** [comment]
Yes, and I use the following environment for testing.
Plugins: Essentials, EssentialsChat, GroupManager, Residence, Vault.
Residence config: https://gist.github.com/gregman98/edc2920f8660921e9afcd6f380d5dc2c
There is a speed setting in line 130, which can be set from 0 to 5.
Will it conflict with Essentials 'max-walk-speed' and 'max-fly-speed'?

**Comment by mdcfe** [comment]
`max-walk-speed` and `max-fly-speed` are only checked when players use the EssentialsX `/speed` command or aliases of it. If Residence sets player speed manually, EssentialsX should not interfere.

**Comment by flandretw** [comment]
It seems that giving the player '/op' will eliminate this problem, maybe it is a permission problem?

**Comment by pop4959** [comment]
check using luckperms verbose to see what permissions are happening
