### ISSUE TITLE
Gamemode from console

### ISSUE THREAD

**Issue by 100petr** [EssentialsX/Essentials#3587]
### Information

**Full output of `/ess version`**:

![unknown](https://user-images.githubusercontent.com/29830635/89977499-89384880-dc6b-11ea-84ea-900a473af11d.png)

**Server log**: https://gist.github.com/100petr/74a48bbc6e9f693f1e388ff4533c9549

**EssentialsX config**: https://gist.github.com/100petr/db3dffa1a78e22cc784a30d325233b76

### Details

**Description**  
Can't change gamemode from console. It worked yesterday before the update

**Steps to reproduce**  
Change gamemode from console
It always writes using the command

**Expected behavior**  
I change players gamemode from console

**Screenshots**  
![unknown](https://user-images.githubusercontent.com/29830635/89977785-52aefd80-dc6c-11ea-98e3-af58fd407afe.png)
![unknown2](https://user-images.githubusercontent.com/29830635/89977789-53479400-dc6c-11ea-85a7-2a6c76025295.png)
![unknown3](https://user-images.githubusercontent.com/29830635/89977791-53479400-dc6c-11ea-9bf6-fc75dbc23b96.png)
![unknown4](https://user-images.githubusercontent.com/29830635/89977792-53e02a80-dc6c-11ea-8242-a576fa475a18.png)

**Comment by 100petr** [comment]
It don't work at tuinity, paperspigot or spigot. I tried it on two servers. config: https://gist.github.com/100petr/62cbe777bd30ed3d42896facadc86076 paper log: https://gist.github.com/100petr/a2d3670c745e9d10cd3fd51f22997b72
spigot log: https://gist.github.com/100petr/e0f6efc3c6fc9ac0f5ce503b16228bd3
Log  spigot server without editing essentials files https://gist.github.com/100petr/83c9f9e61a1b3fdeeea3732a92cd6cbc

**Comment by triagonal** [comment]
This has now been fixed in EssentialsX versions 2.18.0.27 and above. Download the latest version [here](https://essentialsx.net/downloads.html).
