### ISSUE TITLE
Cannot get potions with health boost power 4

### ISSUE THREAD

**Issue by VoltroXP** [EssentialsX/Essentials#3589]
### Information

**Full output of `/ess version`**:

```
Server version: 1.16.1-R0.1-SNAPSHOT git-Paper-135 (MC: 1.16.1)
EssentialsX version: 2.18.0.8
PlaceholderAPI version: 2.10.8
PermissionsEx version: 1.23.4
Vault version: 1.7.3-b131
```

**Server log**: https://gist.github.com/ElectricEzo/251c1e3d404466a6b548e07da09eb113

**EssentialsX config**: https://gist.github.com/ElectricEzo/2c727f4b203632273b28a11c9947cf7c

### Details

**Description**  
When using /potion or having potions in kits, potions with health boost power 4 have power 5 and potions with health boost power 5 have power 6. This means that potions cannot have health boost power 4 on them.

**Steps to reproduce**  
1. Get a water bottle.
2. Do /potion effect:healthboost power:4 duration:100 (any duration works)
3. Notice that the potion has Health Boost V, not Health Boost IV
4. (Extra) Do /potion effect:healthboost power:5 duration:100
5. (Extra) Notice that the potion has Health Boost VI, not Health Boost V

**Expected behavior**  
I expected to have gotten a potion with the appropriate health boost level.

**Screenshots**  
![2020-08-12_03 21 00](https://user-images.githubusercontent.com/48335543/89986719-f25b9400-dc4a-11ea-917d-da4662119bb9.png)
![2020-08-12_03 15 43](https://user-images.githubusercontent.com/48335543/89986481-a1e43680-dc4a-11ea-83a5-ab47f442a9b1.png)

**Comment by uf0h** [comment]
https://github.com/EssentialsX/Essentials/blob/bc52ca856ee3666a62ab7995da8df5c40fa7d341/Essentials/src/com/earth2me/essentials/MetaItemStack.java#L364-L366

**Comment by mdcfe** [comment]
As of EssentialsX 2.18.0.23, you can now replace `power:` with `amplifier:` in item meta to use raw potion strength values (which are 1 lower than the display name). This means for an effect of strength IV, you can now use `amplifier:3` in place of a `power` value.
