### ISSUE TITLE
Essential Spawn bug

### ISSUE THREAD

**Issue by jajamic** [EssentialsX/Essentials#3593]
### Information

Full output of /ess version: 2.18.0.18
Server 1.15.2 - R0.1-SNAPSHOT git-Paper-385

```
/setspawn errant
dosent work
```

**Server log**: no error in my log

**EssentialsX config**:  https://pastebin.com/yDaRUfx2
spawn config : https://pastebin.com/uUVQnLbX

### Details

**Description**  
I am using luckperm, and I wanted to make respawn zones according to the group names in which the players are. It used to work but now I notice that for no reason it doesn't work anymore.

**Steps to reproduce**  
EssentialX + EssentialXSpawn

**Comment by pop4959** [comment]
Try setting the group display name in LuckPerms. I think someone else had a similar issue and that was the solution.

**Comment by jajamic** [comment]
![image](https://user-images.githubusercontent.com/3524258/90113942-52892d80-dd52-11ea-96e5-78094ee1b235.png)


I have try but that dosen t work :/
/lp group posiatir setdisplayname psosiatir

**Comment by jajamic** [comment]
No it s ok ! THX :)
I have missing WEIGHT on this group

**Comment by pop4959** [comment]
Cool! Glad you figured it out.
