### ISSUE TITLE
/settpr command is inconsistent with its responses

### ISSUE THREAD

**Issue by HeavenCrafter** [EssentialsX/Essentials#3595]
I've been playing around with the TPR (RTP) feature for a few hours now and I've run into a few issues. For normal players, the severity of it isn't major but for new EssentialsX users, these might come as a problem for them. *I'll list all server and plugin details below.*

First major issue. **Lacking command responses when using /settpr**
At first, I thought I was doing something wrong cause when I first did `/settpr min 100`, the response given to me was the following:
> Set random teleport min to 100

At first, I thought nothing of it and I expected it to work right off the bat, apparently not. Of course, It was absolutely my fault that I did not read the new update or the GitHub pull request properly as it clearly states "minrange" and not "min". I mostly read the new `tpr.yml` config file and saw `min-range` expecting the alias to be "min" so that part was absolutely my fault but this did make me discover a new issue. You can put **any text** after /settpr and it will still respond with
> Set random teleport (whatever) to 100

I've did some testing with this theory and it does seem to be the case.
![image](https://user-images.githubusercontent.com/22242534/90283597-1ca78e80-dea3-11ea-8607-ab7a8f532a13.png)

This isn't the biggest deal in the world but for me whos just ignorant half of the time when it comes to doing proper research, this can be confusing at times.

**Server and Plugin Details**
- Server Version - Paper-655 1.13.2 (Build 655)
- Related Plugins - Essentials v2.18.0.21

**Comment by pop4959** [comment]
Thanks for testing out the new random teleport features and giving your feedback. The command should probably be giving an error for that kind of incorrect input (and also maybe allowing "min" and "max" as an alias). I'll make sure to address this issue for the next major update of Essentials. Sorry for any confusion!

Hope you're liking the random teleport feature itself though, once you had it properly set up. 😉

**Comment by HeavenCrafter** [comment]
Like it? I absolutely adore it. Everything about it is exactly what I've been looking for. I originally was going to use some other plugins alternative but I was never sure if I wanted to cause I won't be using 90% of the features that other plugins offer. Most of the time, I just needed something quick, easy, and reliable and this has everything I need without the extra features that I won't need to ever use in my case. I have to admit, I was genuinely and absolutely not expecting it to be a core feature built into EssentialsX.

**Comment by pop4959** [comment]
Glad to hear! 😃 

Yeah, the main idea was to include something in Essentials since random teleportation is more or less an "essential" part of many modern survival servers. Goal is just to have something simple & fast, and if anyone wants something fancy that's when you go for another plugin to handle it (as you'd do with any other Essentials feature that you might not find up to par).

**Comment by Evidentsinger14** [comment]
Closing as completed! the changes in the issue have been made 🙂
