### ISSUE TITLE
Problem with /back

### ISSUE THREAD

**Issue by DjeyMute** [EssentialsX/Essentials#3597]
Hi !

When a player join the server and make /back the player is teleported on other location out of the spawn.

Paper version : 1.16.1 version 131
Essentials version : 2.18.0.18

**Comment by triagonal** [comment]
You didn't fill out the [issue template](https://github.com/EssentialsX/Essentials/issues/new?template=report-a-bug.md) properly. Please completely fill out the issue template and resubmit your issue.
