### ISSUE TITLE
[Bug] Cracked server duplicate

### ISSUE THREAD

**Issue by voodootje0** [EssentialsX/Essentials#360]
Hey,

When player1 join the server it has his own account and inventory and if PLAYER1 join the server it has another account and inventory but the balance is the same, and sometimes the first user (player1) will lose their rank and the second player has it (player2).

I'm using vault (1.5.6) so maybe the problem is vault, or it is default minecraft I really don't know.

Now I'm fixing this problem by using DatDuplicateRemover in the hub but that also bug sometimes.

Hope you can fix this =D

**Comment by EvilOlaf** [comment]
Probably not as offline mode is not supported.

**Comment by AllieQpzm** [comment]
The solution is to buy the game.
