### ISSUE TITLE
When console is executing a command when a player receives a kit, the {PLAYERNAME} seems to be invalid

### ISSUE THREAD

**Issue by dixiatielu** [EssentialsX/Essentials#3602]
### Information

Full output of `/ess version`:
[10:20:53 INFO]: Server Version: 1.15.2-R0.1-SNAPSHOT git-Paper-385 (MC: 1.15.2)
[10:20:53 INFO]: EssentialsX Version: 2.18.0.8
[10:20:53 INFO]: LuckPerms Version: 5.1.84
[10:20:53 INFO]: Vault Version: 1.7.3-b131
[10:20:53 INFO]: EssentialsXProtect Version: 2.18.0.8
[10:20:53 INFO]: EssentialsXChat Version: 2.18.0.8
[10:20:53 INFO]: EssentialsXAntiBuild Version: 2.18.0.8
[10:20:53 INFO]: EssentialsXSpawn Version: 2.18.0.8
[10:20:53 INFO]: PlaceholderAPI Version: 2.10.9

**Server log:** 
[https://gist.github.com/dixiatielu/cb6b375077f771bd5deb578e37b36ef2](https://gist.github.com/dixiatielu/cb6b375077f771bd5deb578e37b36ef2)

**EssentialsX config** 
[Config Here](https://gist.github.com/dixiatielu/5c93b95378a09ecd88708fda0708293e)

### Help request

**Problem**

I tried to add a sever command in `kits.yml`, which includes `{PLAYER}`. Like this:
```
  ten_online_gift: 
    delay: -1
    items:
      - /lp user {PLAYER} parent add sponsori
``` 
When I tried to give the kit to the player, the console said it's not a valid username.
![image](https://user-images.githubusercontent.com/29675002/90352108-eae62180-e074-11ea-9c7d-42a314f2cc9c.png)

**What I have tried**

I tried to change the `/lp` command to `/give {PLAYERNAME} acacialog `, but it worked successfully.
But when I tried `/setvip {PLAYER} SponsorI 1`, it doesn't work again.
![image](https://user-images.githubusercontent.com/29675002/90352423-ea01bf80-e075-11ea-81e0-cc5d02cc56ef.png)

**Screenshots**

See above.

**Comment by Octol1ttle** [comment]
Can confirm.
![image](https://user-images.githubusercontent.com/61277953/90361146-e7ec3080-e076-11ea-9a46-3eb0882ac2cd.png)
What seems to be the issue is that EssentialsX provides usernames with color codes in them

**Comment by triagonal** [comment]
Try using the `{USERNAME}` placeholder instead. The `{PLAYER}` placeholder returns the player's display name, including any prefixes/suffixes/coloring.

**Comment by dixiatielu** [comment]
> Try using the `{USERNAME}` placeholder instead. The `{PLAYER}` placeholder returns the player's display name, including any prefixes/suffixes/coloring.

Yeah that works. Could you update the comments in `kits.yml`?

**Comment by triagonal** [comment]
> Yeah that works. Could you update the comments in `kits.yml`?

`kits.yml` already reflects this: https://github.com/EssentialsX/Essentials/blob/73d2457feac4861de214143e5160e2b6795f5e57/Essentials/src/kits.yml#L8-L9

**Comment by dixiatielu** [comment]
> > Yeah that works. Could you update the comments in `kits.yml`?
> 
> `kits.yml` already reflects this:
> 
> https://github.com/EssentialsX/Essentials/blob/73d2457feac4861de214143e5160e2b6795f5e57/Essentials/src/kits.yml#L8-L9

OK, thanks. Maybe that's just because my config is a little bit old.
