### ISSUE TITLE
Add support for PlaceholderAPI

### ISSUE THREAD

**Issue by nisutec** [EssentialsX/Essentials#3605]
### Feature request

**Feature description**

Please add support for PlaceholderAPI (https://github.com/PlaceholderAPI/PlaceholderAPI) to EssentialsX.

**How the feature is useful**

This extension will give EssentialsX many customizability. It will give great possibilities for the motd, the chat, and custom language files to add many relevant and nice placeholders to this features.

**Comment by pop4959** [comment]
Closing as a duplicate of #2391. Please discuss this subject there!
