### ISSUE TITLE
Blocks blacklisted from being pushed by pistons are still pulled by sticky pistons

### ISSUE THREAD

**Issue by NikoEatsPancakes** [EssentialsX/Essentials#3609]
### Information

**Full output of `/ess version`**:

```
Server version: 1.16.1-R0.1-SNAPSHOT git-Tuinity-"650532a" (MC: 1.16.1)
EssentialsX version: 2.18.0.0
LuckPerms version: 5.1.26
Vault version: 1.7.3-b131
EssentialsXChat version: 2.18.0.0
EssentialsXProtect version: 2.18.0.0
EssentialsXAntiBuild version: 2.18.0.0
EssentialsXSpawn version: 2.18.0.0
```

**Server log**: Don't think it's relevant to the issue, would prefer not to attach for privacy reasons; if absolutely needed would prefer to DM

**EssentialsX config**: https://gist.github.com/NikoEatsPancakes/16a8f9cad95b6ff6270f657bb5be9e38

### Details

**Description**  
Blocks that are added to the piston blacklist in the config for EssentialsXAntiBuild can be pulled by extended sticky pistons.

**Steps to reproduce**  
1. Place sticky piston
2. Activate sticky piston with lever
3. Place a blacklisted block in front of the now extended sticky piston face
4. Deactivate sticky piston with lever

The blacklisted block will have retracted with the sticky piston.

**Expected behavior**  
Blocks in the piston blacklist are not pulled by sticky pistons.

**Screenshots**  
https://imgur.com/a/z8mLhxG

**Comment by triagonal** [comment]
This has now been fixed in EssentialsX versions 2.18.0.26 and above. Download the latest version [here](https://essentialsx.net/downloads.html).

Thank you for all your help testing this on the Discord server! ❤️
