### ISSUE TITLE
/kit command exposes vanished players

### ISSUE THREAD

**Issue by piotrskibapl** [EssentialsX/Essentials#3611]
### Information

**Full output of `/ess version`**:

```
Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-385 (MC: 1.15.2)
EssentialsX version: 2.18.0.0
PlaceholderAPI version: 2.10.9
LuckPerms version: 5.1.93
Vault version: 1.7.3-b131
Citizens version: 2.0.27-SNAPSHOT (build 2072)
EssentialsXChat version: 2.18.0.0
EssentialsXSpawn version: 2.18.0.0
```

**Server log**: there's no errors in the console - not relevant

**EssentialsX config**: https://gist.github.com/piotrskibapl/901bde367422ed7422ac6952f71a609b

### Details

**Description**  
The "/kit tools <tab>" command exposes all vanished players by tab suggestions.

**Steps to reproduce**  
1. Log in on the server
2. Make sure there's another vanished player you can't see
3. Type in "/kit tools " and press tab
4. You should see the vanished player username on the tab completions list

**Expected behavior**  
The vanished player should be hidden from the completions

**Comment by JRoy** [comment]
I cannot see any possible way this is happening, it *could* be an upstream bug?

**Comment by mdcfe** [comment]
@piotrskibapl Could you update to the [latest build](https://essentialsx.net/downloads.html) and see if this is still an issue?

**Comment by piotrskibapl** [comment]
Right, it looks like this bug is not present on the latest build anymore.
