### ISSUE TITLE
/list command exposes vanished groups

### ISSUE THREAD

**Issue by piotrskibapl** [EssentialsX/Essentials#3612]
### Information

**Full output of `/ess version`**:

```
Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-385 (MC: 1.15.2)
EssentialsX version: 2.18.0.0
PlaceholderAPI version: 2.10.9
LuckPerms version: 5.1.93
Vault version: 1.7.3-b131
Citizens version: 2.0.27-SNAPSHOT (build 2072)
EssentialsXChat version: 2.18.0.0
EssentialsXSpawn version: 2.18.0.0
```

**Server log**: there's no errors in the console - not relevant

**EssentialsX config**: https://gist.github.com/piotrskibapl/901bde367422ed7422ac6952f71a609b

### Details

**Description**  
If a group has only vanished members online, it's still in the "/list" tab completions even if a player can't see any players that belong to this group.

**Steps to reproduce**  
1. Log in on the server
2. Make sure that there's at least one member of a certain group online, and all of the online group members are vanished and you can't see them
3. Type in "/list " and press tab
4. The list of groups that have any online members is displayed in the tab completions. It also contains the group that has only vanished players online.

**Expected behavior**  
A group shouldn't be exposed in the tab completions if you can't see any members of it.

**Comment by piotrskibapl** [comment]
It looks like this bug is present again on the latest dev builds.
Could this be reopened?

**Comment by benwoo1110** [comment]
you should create a new issue with all the necessary details for a bug report.
