### ISSUE TITLE
Permissions for changing time in world not being checked.

### ISSUE THREAD

**Issue by emilyy-dev** [EssentialsX/Essentials#3613]
### Information

**Full output of `/ess version`**:

```
CONSOLE issued server command: /ess version
Server version: 1.16.1-R0.1-SNAPSHOT git-Paper-137 (MC: 1.16.1)
EssentialsX version: 2.18.0.27
LuckPerms version: 5.1.93
Vault version: 1.7.3-b131
You are running an unsupported server version!
```

**Server log**: https://gist.github.com/Fefo6644/3c82439498e12fa59890937b82df7724

**EssentialsX config**: https://gist.github.com/Fefo6644/d56e7bc7527778b789195825d35bbe30

### Details

**Description**  
The permission for setting time (`essentials.time.set`) is not being checked when running commands to change time.

**Steps to reproduce**  
1_ Set `essentials.time` to true, either directly to the user or in an inherited group.
2_ Set `essentials.time.set` to false, either directly to the user or in an inherited group.
3_ Run any command to change world time, such as `/day`, `/night` or any variation of `/time set <time>`

**Expected behavior**  
The action shouldn't be allowed and the world time shouldn't change.

**Screenshots**  
![](https://media.discordapp.net/attachments/642062687374934032/746609731497361428/unknown.png)

**Comment by muzak23** [comment]
Can confirm, I've had this issue too in my issue #3615 (which I made before realizing someone beat me to it)
