### ISSUE TITLE
Respawn Bug - After death the player is teleported to the wrong place

### ISSUE THREAD

**Issue by XANT3R** [EssentialsX/Essentials#3618]
### Information
Full output of /ess version:
CONSOLE issued server command: /ess version
Server version: 1.16.1-R0.1-SNAPSHOT git-Paper-131 (MC: 1.16.1)
EssentialsX version: 2.18.0.18
PlaceholderAPI version: 2.10.6
LuckPerms version: 5.1.62
Vault version: 1.7.2-b107
Citizens version:  2.0.27-SNAPSHOT (build 2084)
EssentialsXChat version: 2.18.0.18
EssentialsXSpawn version:  2.18.0.18

Server Log: https://pastebin.com/yM8JEQvv
EssentialsX Config:  https://pastebin.com/pHsnfZ8x
Data of the affected player:  https://pastebin.com/zsFWf1gP

### Details
**Description**
After death the player is teleported to the wrong place and this appears in the console.

This bug may also be affected by the situation that some time ago I moved players from a damaged map to a new one. They may have kept the bed on this damaged map. However userdata does not indicate this because there is only one home, and that is in the correct world. I haven't seen a fix to that in the development version, so I suppose no one caught this bug. Spawn is in world nether.

**Steps to reproduce**
The player died and appeared in the evil world where there is no spawn, I have no idea how to recreate it.

**Comment by pop4959** [comment]
Can you explain what the "damaged" world is, and what you did when you changed worlds?

**Comment by XANT3R** [comment]
@pop4959 The Broken World was a modified overworld that looked a nether. A certain change has damaged this world and made it normal overworld.

I transferred player data from one world to another. The player was required to overwrite /home.

**Comment by JRoy** [comment]
@XANT3R are you able to reproduce this error on demand? Or does it only happen once?

**Comment by XANT3R** [comment]
> are you able to reproduce this error on demand? Or does it only happen once?

In the case of a new player, this did not happen

**Comment by JRoy** [comment]
I submitted a fix to Paper in https://github.com/PaperMC/Paper/pull/4238 which should fix this issue. Once it has merged, I'll close this issue

**Comment by JRoy** [comment]
@XANT3R This should now be fixed in the latest Paper build which you can download [here](https://papermc.io/downloads).

Please let me know if the issue persists.
