### ISSUE TITLE
EssentialsX spamming /list in console

### ISSUE THREAD

**Issue by joelimgu** [EssentialsX/Essentials#3619]
### Information

Full output of `/ess version`:

23.08 06:13:06 [Server] Server thread/INFO Server version: 1.16.1-R0.1-SNAPSHOT git-Spigot-758abbe-2b00831 (MC: 1.16.1)
23.08 06:13:06 [Server] Server thread/INFO EssentialsX version: 2.18.0.0
23.08 06:13:06 [Server] Server thread/INFO LuckPerms version: 5.1.93
23.08 06:13:06 [Server] Server thread/INFO Vault version: 1.7.3-b131
23.08 06:13:06 [Server] Server thread/INFO EssentialsXChat version: 2.18.0.0

### Help request

**Problem**
The server is spamming / list command every second or so, if I delete the essentialsX plugin it stops so I supposo the problem comes from here but I coud't fnd any info about it. How can I make it stop?

Thank you in advance!

**Comment by Octol1ttle** [comment]
Not caused by EssentialsX,
Control panels are known to use `/list` every few seconds/minutes.

**Comment by joelimgu** [comment]
Ok, thaks a lot, but is there any way to make it stop?

**Comment by Octol1ttle** [comment]
If you are using a hosting, contact them
If you set up control panel yourself, seek for that feature, Google can help you with it

**Comment by joelimgu** [comment]
Great!, Thank you for your time, I know it is a preaty noob question!
