### ISSUE TITLE
Add support for BungeeCord Chat Colors

### ISSUE THREAD

**Issue by aurorasmiles** [EssentialsX/Essentials#3627]
### Feature request

**Feature description**
Add support for BungeeCord chat color format, like &x&r&r&g&g&b&b

**How the feature is useful**
Would be useful for cross-compatibility with other plugins, especially bungee plugins

**Comment by JRoy** [comment]
Essentials has RGB support in the (hopefully now standardized) format of `&#rrggbb`. In our implementation, we translate that to `§x§r§r§g§g§b§b` so we can continue using legacy strings.

The `&x&r&r&g&g&b&b` format is worse than the `&#rrggbb` format for any use case that I can think of and would cause us to do further regex parsing & permission checks. Also, we'd now supporting two different formats of doing the same thing. That's generally what has made Essentials a PITA to maintain in the past so I'd personally like to avoid that for the future.

If you could either explain your use case or if I'm somehow misunderstanding your feature request, please let me know!
