### ISSUE TITLE
ugly messages format. (and some other issue)

### ISSUE THREAD

**Issue by Kixot14** [EssentialsX/Essentials#363]
Thanks for your work, but, please, can you fix some things?

1.2) SUGGESTION: Can you add possible to change channels format (Like global, local chat...)
Or global and local messages color at least? 
At this time can only change the general chat format and prePrefix in Local-File at chatType string

1.3) Why command /nick can change only nick-color? Can you add possible to change the nickname with that command??

1.4) Can you separate the private 'msgFormat' to messageToPlayer and  messageFromPlayer ??
For set format like this:
If i sent the message --- [You sent the private message to player Notch]: <message>
If someone sent message to me --- [player Notch sent private message to you]: <message>

1.6) BUG: Money for /tpa, /tpahere commands is taken, even if teleport event is failed cause player deny his request or have tp-cooldown...

1.7) BUG: Money for /hat command is taken, even if you use this command with item in hand, which is impossible to whear on head. (Like tools or armor...)

1.8) perms for give themselves exp (with /exp give [playername] [amount|L<level>]) don't work.
Just send a: For input string: "{player}", when tried.

1.9) BUG: Can you add option for disable possible to use symbols, like cyrillic, brackets, and others, when you set home, or warp...?? Allows only numbers and latin letters.
Because, for example, when you
set home with hame: *)?№Gіл{oощ&^ш-L=?&
This home save as: ____g___o______l___
Just allow use only numbers and latin letters! And limit the symbols in warp/home names...

1.10) SUGGESTION: Can you add possible for moders, who have '- essentials.chat.spy' permission,  to toggle listening a local chat? Cause when he have this all time, they get a lot of spam.
Or do this feature the similar with /socialspy
/LocalChatSpy [player1,2,3] [radius] - Toggle chat listening.
- And if you some ever wish to add the possibility to divide shout-chat between worlds:
  /ShoutChatSpy [WORLD1,2,3] [player1,2,3] [radius]

1.11) SUGGESTION: Can you add command, or perms for delete only that warp, which you set ??

1.12) SUGGESTION: Need add possible to set multiple spawn for multiple worlds (ont only for groups)
If you die in one world, you must spawn in spawn of this world. (and when use /spawn cmd to)

1.13) SUGGESTION: How to prevent other peoples set home in nonOwn, nonMember WG-regions? Can you implement this?? And allow to set warp only in players own region.

1.14) BUG: You can do teleport to your bed-home in another world, even if world-home-permissions set to true.

1.15) SUGGESTION: Can you a little change mute feature in Essentials?
• Add time for broadcast notify.
• Add mute reason
• Add mute max time (like ban max time)
• Add option for stop mute timer, when player offline.
• And just add one second to all standart mute/ban timer. Because, for example, if you
set mute/ban time to 10 min, it shown 9 min, 59 sec. If set 10min, 1 sec than shown 10 min.

1.16) BUG: Impossible to disable toggling AFK status by negative permission '- -essentials.afk.auto'.
Essentials shown info about your afk status even if you have vanish.

1.17) BUG: Disable death-messages dont disable death messages! Just always shown "Player died", for all type of death!

1.18) SUGGESTION: Essentials have custom join and leave messages. Can you add message for first join ? (not as in the announce-format from EssentialsSpawn). This "first join message" just must go instead the "join message".
## 

My Server: CraftBukkit version git-Spigot-2f787bd-ea28011 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT
EssentialsX at moment of test: 2.0.1-b245

**Comment by Kixot14** [comment]
UPD:
1-st may be fix with remove PEx prefixes and suffixes. And add them in 'group-formats'. So already not actual!

**Comment by Kixot14** [comment]
Missing or wrong some messages in Local_ File:

2.1. For /tpdeny command (just sending 'null' message, but no in local file)

2.2. Message 'now' in string 300 is broken. Always shown 'now', even if delete

2.3. Format for SocialSpy.

2.4. Part of translate for /near command in 'nearbyPlayers' string. When use this command, it shown you nearby players and (distant in meters). So missed this (distant in meters).

2.5. Message for 'minimum-pay-amount' string in config.yml
(The minimum amount you can pay is ...)

2.6. Help messages - when you use commands like /tpa, /speed, /pay, /gamemode, /mail or etc.
For example: It shows: Change player gamemode. 
/gm survival|creative|adventure|spectator [player] <-- This messages missing in localFile

2.7. When try to repair the repaired item with /repair, it take message from string 373: repairInvalidType=\u00a74This item cannot be repaired.
But must be from string 371: repairAlreadyFixed=\u00a74This item does not need repairing.

2.8. I not find format for players, when use /balancetop command!

2.9. When 'update-bed-at-daytime' set to false, you have not sent a message about home-bed is set. Even in night! bed-home updated, but without message. 
If set to true, than yes!

2.10. Message from string 167(InfoPages) using for /BalanceTop, /mail read and /rules commands. Can you separate this at individual messages for this commands?
P.s. No sub-costs for /mail read|send|clear. And many other cmds.

2.11. No format for ban/tempban messages, when moder banned player, and than this player try to rejoin

2.12. Can you add minor currency value, separated from major?? Example:
Old format:  879,156,756,545.52 dollars
New format:  879,156,756,545 dollars, 52 cents

**Comment by Kixot14** [comment]
home permission, which must give access to tp to your home from some worlds: 'essentials.worlds.<worldname>'  Dont work!

**Comment by Kixot14** [comment]
Sorry, I incorrectly gave some information, but now it must be corrected!

**Comment by Kixot14** [comment]
Sorry, I not correctly gave some information, but now it must be corrected!

**Comment by Kixot14** [comment]
Does it make sense to write about all of this? Or project manager don't read this ?

**Comment by SupaHam** [comment]
Thanks for creating this very detailed issue. However, this is not how you report issues. You need to break down each individual issue you have (suggestion, bug, etc.) into one report each. Make sure that the issues created are as detailed as possible, but also don't create many issues that all make up to be the same feature.

**Comment by Kixot14** [comment]
ok
