### ISSUE TITLE
essentials.setwarp.# permission node for player warps

### ISSUE THREAD

**Issue by Fr0sto** [EssentialsX/Essentials#3630]
### Feature request

**Feature description**

A permission node that would allow servers to set/limit how many warps, if any, a player or permissions group is allowed to set.

**How the feature is useful**

This would be very useful for servers that allow players to create public areas or player shops, and want to allow players to set a certain amount of server warps.

**Comment by pop4959** [comment]
I think you are confused between warps and homes. You can already do this for homes, it is not ever planned for warps (and it doesn't make any sense, as warps are not tied to users or groups).

**Comment by Fr0sto** [comment]
@pop4959 I am not confused between warps and homes, I was asking for users to be able to set 1 or more warps that other players could then access with the typical `/warp <warp>`. Basically, a player could make a shop at his base, or whatever, and set a warp there so other players could visit on their own time.

**Comment by JRoy** [comment]
This is something we will not be adding into Essentials. It would require us to store the UUID of people who create warps and that's just not worth it for such a small use case.

However, you can accomplish this same thing in a custom plugin that interfaces with the Essentials API.
