### ISSUE TITLE
Could you please add support for MarksAPI?

### ISSUE THREAD

**Issue by yueyinqiu** [EssentialsX/Essentials#3631]
### Feature request

**Feature description**  
Add support for MarksAPI - Just implement a marks provider which can provider the warps as marks.  
It's a new plugin written by myself.

Its purpose is to put all the plugins' marks together, so I'm here creating the issue.

**How the feature is useful**  
I think it will be better to paste the link than describe here: [https://www.spigotmc.org/resources/.83087/](https://www.spigotmc.org/resources/83087/).

If you won't add this feature, please tell me the reason so I can improve it.

Sorry for my poor English. If there is any ambiguity, please leave a comment.

**Comment by pop4959** [comment]
Essentials doesn't add hooks for random plugins -- you should use the API to implement this yourself, in your plugin.

**Comment by yueyinqiu** [comment]
Um, it makes sense, otherwise you'll have too much work to do. Sorry that I was a little thoughtless.
