### ISSUE TITLE
SocialSpy Not Working - EssentialsX 

### ISSUE THREAD

**Issue by IkovRaven** [EssentialsX/Essentials#3632]
### Information

**Full output of `/ess version`**:

```
7:33:11 AM CONSOLE: [INFO] CONSOLE issued server command: /ess version
7:33:11 AM CONSOLE: [INFO] Server version: 1.16.2-R0.1-SNAPSHOT git-Spigot-379750e-f26d8e8 (MC: 1.16.2)
7:33:11 AM CONSOLE: [INFO] EssentialsX version: 2.18.1.0
7:33:11 AM CONSOLE: [INFO] PermissionsEx version: 1.23.4
7:33:11 AM CONSOLE: [INFO] Vault version: 1.7.3-b131
7:33:11 AM CONSOLE: [INFO] EssentialsXProtect version: 2.18.1.0
7:33:11 AM CONSOLE: [INFO] EssentialsXSpawn version: 2.18.1.0
7:33:11 AM CONSOLE: [INFO] ChestShop version: 3.11 (build 213)
7:33:11 AM CONSOLE: [INFO] You are running unsupported plugins!
```

**Server log**: https://gist.github.com/IkovRaven/b8f47fd2f10e4b6f37ad18222a23de61

**EssentialsX config**: https://gist.github.com/IkovRaven/a35c959b91179575da443b358cfcb1cf

### Details

**Description**  
Running a public roleplay/survival Minecraft server. All staff members try to use the /social spy command and we receive no input of peoples private messages, etc in game.

**Steps to reproduce**  
./social spy
direct message or whisper or reply to someone's private message. 
social spy returns no input of conversations to any staff member who has the command enabled.

**Expected behavior**  
social spy to return all detailed whispered or private message conversations between players to staff members on the server.
**Screenshots**  
![ssnotworking](https://user-images.githubusercontent.com/70208677/91175710-d3c3b700-e6a6-11ea-99d7-e4cf9dd53a88.png)

**Comment by JRoy** [comment]
When you enable socialspy, it doesn't show messages you either send or receive.
