### ISSUE TITLE
"hide-displayname-in-vanish: true" causing "player is now AFK" messages to not be shown

### ISSUE THREAD

**Issue by ItsDed** [EssentialsX/Essentials#3633]
### Information

**Full output of `/ess version`**:

```
>.... [14:37:35 INFO]: Server version: 1.16.2-R0.1-SNAPSHOT git-Purpur-747 (MC: 1.16.2)
>.... [14:37:35 INFO]: EssentialsX version: 2.18.0.22
>.... [14:37:35 INFO]: PlaceholderAPI version: 2.10.9
>.... [14:37:35 INFO]: LuckPerms version: 5.1.93
>.... [14:37:35 INFO]: Vault version: 1.7.3-b131
>.... [14:37:35 INFO]: Citizens version: 2.0.27-SNAPSHOT (build 2100)
>.... [14:37:35 INFO]: EssentialsXGeoIP version: 2.18.0.22
>.... [14:37:35 INFO]: EssentialsXSpawn version: 2.18.0.22
>.... [14:37:35 INFO]: ChestShop version: 3.11.1-SNAPSHOT (build 227)
```

### Details

**Description**  
Setting `hide-displayname-in-vanish: true` to true causes chat to not display "player is now AFK" for staff members. When set to false, AFK messages work as expected.

**Steps to reproduce**  
1. Set `hide-displayname-in-vanish:` to `true`
2. Go afk
3. Go un-afk

**Expected behavior**  
Expected AFK messages in chat to still show.

**Screenshots**

**Comment by JRoy** [comment]
You're hundreds of versions out of date, please update [here](https://essentialsx.net/downloads.html) and re-open this issue if it persists.

EDIT: Additionally, this may be expected as if you're vanished no messages about being AFK should show.
