### ISSUE TITLE
Essentials Eggs Issue

### ISSUE THREAD

**Issue by DebuffPvP** [EssentialsX/Essentials#3634]
**Description**  
So before let's say for creeper egg i used to be able to do /give [player] 383:50 1
to give a player 1 creeper egg and since i switched to 2.18.0 and waited thinking a new update might fix it so i updated again to 2.18.1 and when eggs are given and doesn't matter what kinda egg it is, it still gives the spawn egg item with no actual mob for it just an egg that does nothing.

**Steps to reproduce**  
/give [player] 383:50 1

**Expected behavior**  
It's supposed to give the player the defined egg type but it's not doing it

**Screenshots**  
https://gyazo.com/4bb67da9c914df65c6ab18b7fec7969e

This is a gif so you can see for yourself ^^

**Version**
[01:47:22 INFO]: This server is running Hyperion version TacoSpigot (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

**Comment by Chew** [comment]
Not an essentials expert, but I think you need to specify `/give me creeper_spawn_egg`, though you are using a 5 year old Minecraft version so idk

**Comment by JRoy** [comment]
A new system in Essentials relies on manually checking versions to use certain features. Your spigot fork is unsupported and modified the server version to something that breaks said Essentials feature. Please either switch to [Paper](https://papermc.io/legacy) or ask your server software maker to fix their version string to `1.8.8-R0.1-SNAPSHOT`
