### ISSUE TITLE
Request: Custom command on verified payment. (/pay) for sounds/titles/anything we want.

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#3635]
### Feature request

**Feature description**
Add a config option to run commands based on verified payment (Once its gone through) for sender and receiver, so we can add sounds for payment and then titles/hotbar titles if we so wish.  

**How the feature is useful**
When chat is moving extremely fast, the payment you have been sent will be lost in seconds, and you have to be eagle hawk eyed to spot it.

Sounds and big titles would help dramatically tell you you just got a payment.

**Comment by Chew** [comment]
While there likely won't be an option for a command, an event that a plugin could hook into for successful payments may seem more viable. Perhaps "TransactionEvent"?

**Comment by TomLewis** [comment]
TransactionEvent would be a good start! I'm sure someone could whip up a plugin in no time if its just to listen to one event.
