### ISSUE TITLE
Cannot give some items using EssentialsX's /item and /give commnads.

### ISSUE THREAD

**Issue by AMDBartek** [EssentialsX/Essentials#3642]
### Information

**Full output of `/ess version`**:

```
Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
EssentialsX version: 2.18.1.3
PlaceholderAPI version: 2.10.9
LuckPerms version: 5.0.72
Vault version: 1.7.3-b131
EssentialsXChat version: 2.18.1.3
EssentialsXProtect version: 2.18.1.3
EssentialsXSpawn version: 2.18.1.3
```

**Server log**: Not necessary (if needed please say)

**EssentialsX config**: https://gist.githubusercontent.com/AMDBartek/7cf0c8e5e53e16d1e6c073be0f58eb3b/raw/f59c506c29e240c92731b0be12746daa2d1ca427/gistfile1.txt

### Details

**Description**  
You cannot give yourself some items using EssentialsX's /i and /give commands, for example, doors while you can give yourself a normal oak door, you can't give yourself any other wooden door using the command. This may happen with other items as well.

I have a feeling that this only happens on < 1.13 servers due to the item ID and name changes introduced in that version.

**Steps to reproduce**  
1. Join a Minecraft server with EssentialsX
2. Run (for example) `/i darkoakdoor`
3. EssentialsX will say that you have been given a dark oak door but you will not actually receive one

**Expected behavior**  
For the command to actually give me the item of choice.

I have tried deleting `custom_items.yml` and `items.csv` then restarting the server, this did not fix the issue.

**Screenshots** 
![2020-08-31_17 31 21](https://user-images.githubusercontent.com/46637209/91743819-54574b80-ebb0-11ea-99ad-5a4fe15013d3.png)

**Comment by JRoy** [comment]
Can you do `/ess debug`, run the give command of the darkoakdoor, and then share the server log?

**Comment by JRoy** [comment]
You're also hundreds of versions out of date, please update before doing the steps above

**Comment by AMDBartek** [comment]
Sure, what do I need to update? I will run /ess debug

**Comment by AMDBartek** [comment]
This is the only thing `/ess debug` and then `/i darkoakdoor` outputted.

https://gist.github.com/AMDBartek/ff489b3f5113ad724ef888b57ea47d21

**Comment by JRoy** [comment]
Update to the latest version [here](https://essentialsx.net/downloads.html) and see if your issue persists

**Comment by AMDBartek** [comment]
That's the version I am using `2.18.1.3`

![image](https://user-images.githubusercontent.com/46637209/91749966-355db700-ebba-11ea-8dc7-c9ff7385442b.png)

**Comment by JRoy** [comment]
Oh my bad, I misread your version in the original post :p

**Comment by AMDBartek** [comment]
Any info on this?

**Comment by Octol1ttle** [comment]
Can confirm this issue
![2020-09-14_10 08 02](https://user-images.githubusercontent.com/61277953/93046067-56221400-f672-11ea-886f-996a07b6bcf0.png)

**Comment by AMDBartek** [comment]
Any updates on this issue?
