### ISSUE TITLE
Essentials sets the displayname after its already accessible in multiple places

### ISSUE THREAD

**Issue by AZFire1** [EssentialsX/Essentials#3646]
### Information

Full output of `/ess version`:

https://pastebin.com/d5rkZ4FW

**Server log:** https://gist.github.com/AZFire1/ad52ed712cc16d2ea6ff1f9e48fdde33

**EssentialsX config** https://gist.github.com/AZFire1/c2eff724b223ba9b5377874a4dcb933f

### Help request

**Problem**
I have add-prefix-suffix on to change the displayname of users. I am using {PLAYER} in basically everything and it's showing the displayname that essentials modifies, though on the first time players join, I have it set to show the display name and it only shows it 50% of the time. The other 50% it just shows their regular name. Which, I'd appreciate if it could just show the display name that essentials modifies 100%?

**What I have tried**
Set the displayname to true.

**Screenshots**
None, I think it's self explanatory though.

**Comment by JRoy** [comment]
Where is the display name shown and where is it not shown. Screenshots would be nice.

**Comment by AZFire1** [comment]
It's shown everywhere but when a player joins for the first time, it's shown around 50% of the time. If you look in the config, I have it set to show the players displayname on the welcome message. It shows it 50% of the time while the other 50%, it just doesn't show it. Only for the first join welcome messages though. I don't currently have screenshots, I'll post them the next time a new player joins and this happens.

**Comment by JasonHorkles** [comment]
It probably has something to do with LuckPerms not being able to add the meta to the user fast enough before the welcome message is displayed

**Comment by AZFire1** [comment]
Then, what would you suggest I do?

**Comment by triagonal** [comment]
There's nothing you can do at the moment. You'll have to wait until the issue has a fix.

Related: #2388, which also involves player display names not being loaded in time for a join message (iirc player meta and nicknames are applied in the same method).

**Comment by JRoy** [comment]
I've mitigated this solution in parts of the Essentials codebase that we're able to control. For join messages, it's difficult because we don't want to override other plugins who handle join messages unless we're specifically told to. If you set `custom-join-message` in the config to the type of join message you want using the `{PLAYER}` placeholder for display names, that should work as intended.
