### ISSUE TITLE
Cannot find line in Message.Properties for Command-Cooldown message

### ISSUE THREAD

**Issue by JMCY26** [EssentialsX/Essentials#3647]
When I set a Command Cooldown such as:

command-cooldowns:
   home: 70

When a player attempts to use the command again, there is a unique message that pops up.
"You cannot type that command for #minute # seconds"

I've scanned the message.properties for this message saying "You cannot type that command" and I cannot find it.
This is a different message to if you just made a global teleport-cooldown.

If this in fact not currently editable, could be it made so, please?

![image](https://user-images.githubusercontent.com/51828613/92236544-89fc7d00-eead-11ea-8b14-8766f42af4a6.png)

**Comment by triagonal** [comment]
https://github.com/EssentialsX/Essentials/blob/dc6b9b89cd7cb1a3f1ee3b55b4ebe2cbf2ac8402/Essentials/src/messages.properties#L102
