### ISSUE TITLE
Nicknames can only have their colors changed

### ISSUE THREAD

**Issue by Coolfeather2** [EssentialsX/Essentials#365]
b245
adding permission node `- essentials.nick.changecolor` does not fix this for me

**Comment by SupaHam** [comment]
Make sure you're adding `-essentials.nick.changecolor` in most plugin that space can make a difference.

**Comment by Coolfeather2** [comment]
Yeah, using PermissionsEX, MySQL Database.
Given the wildcard perm `essentials.nick.*` too if that makes any difference
![image](https://cloud.githubusercontent.com/assets/14107982/12226895/31b48d3e-b85e-11e5-9a75-1e8ddb74de2c.png)

**Comment by AllieQpzm** [comment]
This was fixed in build 246. Please update :)

**Comment by Coolfeather2** [comment]
Thanks
