### ISSUE TITLE
[Feature Request] "TurtleHelm" shorter way to get a helmet.

### ISSUE THREAD

**Issue by AZFire1** [EssentialsX/Essentials#3650]
# Feature request

**Feature description**
Add the shorter term for "turtlehelmet" named "turtlehelm" like you did with every other helmet, so I'd be able to do /i turtlehelm. It's very useful, not very important. But, I'd find it useful.

**How the feature is useful**
It shortens having to type out the entire "turtlehelmet" out. And, it let's you stay on track with the way you have been doing it for Essentials for other helmets & armor pieces..

**Comment by Chew** [comment]
Good news! In the custom_items.yml file in your Essentials folder, you can define aliases of your items, in this case, turtlehelm instead of turtlehelmet.

Example:
```yml
aliases:
  turtlehelm: turtlehelmet
```

Or whatever you wanna put there.

Hope this helps!
