### ISSUE TITLE
Customizable Teleport Cooldowns for home, spawn etc.

### ISSUE THREAD

**Issue by bloggy** [EssentialsX/Essentials#3652]
### Feature request

**Feature description**
Add config option to customize the teleport cooldown for each command like /home or /spawn instead of having only one option for all these commands

**How the feature is useful**
Customizable teleport cooldowns

**Comment by pop4959** [comment]
You should be able to do this using the `command-cooldowns` section of the config, which allows specifying any command and a custom cooldown duration.
