### ISSUE TITLE
Feature Request - Collection of Items for Enchant Signs

### ISSUE THREAD

**Issue by AstralisVox** [EssentialsX/Essentials#3653]
### Feature request 

**Feature description**
With the EssentialsX Signs, there is the option of being able to enchant just a single item (i.e DIAMOND_SWORD). Now, it would be cool if there was a way to add something like `Swords` and this will allow you to use the sign to enchant all the different swords through the same sign.

The sign would look something like

[Enchant]
Swords
sharpness:5

**How the feature is useful**
It would be useful in a way that people would be able to allow certain types of items would be able to be enchanted instead of having to do a new sign for each item individually. 

So, say if you had like a pvp arena where you could enchant your swords. You'd currently need room for each different type of sword, for each different type of enchant you want. Where, if there was a way to specify a collection of items (Swords, Axes, Shovels, Leather Armour). It would save a lot of time and space.

**Comment by pop4959** [comment]
May be possible using tags in more recent versions of MC

**Comment by pop4959** [comment]
@OmegaWeaponDev I implemented this for you and it's been merged. Enjoy!
