### ISSUE TITLE
/sell all returns {1} instead of total sold value

### ISSUE THREAD

**Issue by AetherisMC-Squid** [EssentialsX/Essentials#3654]
### Information

**Full output of `/ess version`**:

```
>.... [05:27:29 INFO]: Server version: 1.16.2-R0.1-SNAPSHOT git-Paper-184 (MC: 1.16.2)
>.... [05:27:29 INFO]: EssentialsX version: 2.18.1.3
>.... [05:27:29 INFO]: PlaceholderAPI version: 2.10.9
>.... [05:27:29 INFO]: LuckPerms version: 5.1.98
>.... [05:27:29 INFO]: Vault version: 1.7.3-b131
>.... [05:27:29 INFO]: EssentialsXProtect version: 2.18.1.3
>.... [05:27:29 INFO]: EssentialsXSpawn version: 2.18.1.3
>.... [05:27:29 INFO]: ChestShop version: 3.11 (build 213)
```

**Server log**: Not necessary (If needed please ask)

**EssentialsX config**: https://gist.github.com/EtherealSquid/39c7f4e612bfde2cf837be07b2716d59

### Details

**Description**  
When using /sell all to sell all items, the total sold worth is reported as the placeholder {1} instead of the running total.

**Steps to reproduce**  
1. Have multiple sellable items in your inventory.
2. /sell all.

**Expected behavior**  
When selling all items, the total worth of all sales should be added up and reported as a lump sum at the bottom of the returned text for the transaction.

**Screenshots**  

![image](https://user-images.githubusercontent.com/69995451/92437669-73884700-f175-11ea-8e41-3ab80a8acff6.png)
![image](https://user-images.githubusercontent.com/69995451/92437677-76833780-f175-11ea-8565-8d185432feed.png)

**Comment by Chew** [comment]
https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/messages.properties#L816-L819

**Comment by Octol1ttle** [comment]
Are you using custom locale?

**Comment by Chew** [comment]
Can confirm with latest build, fix was changing {1} to {0}.

**Comment by Octol1ttle** [comment]
Does that mean that {1} needs to be changed to {0} in every single locale?

**Comment by Chew** [comment]
Eh, not the most ideal. Best bet is probably adding the useless variable back into the tl() so everyone doesn't have to change their locale.
