### ISSUE TITLE
Duplication Bug with /invsee on own inventory

### ISSUE THREAD

**Issue by AetherisMC-Squid** [EssentialsX/Essentials#3657]
### Information

**Full output of `/ess version`**: 

```
>.... [00:49:04 INFO]: Server version: 1.16.2-R0.1-SNAPSHOT git-Paper-186 (MC: 1.16.2)
>.... [00:49:04 INFO]: EssentialsX version: 2.18.1.4
>.... [00:49:04 INFO]: PlaceholderAPI version: 2.10.9
>.... [00:49:04 INFO]: LuckPerms version: 5.1.106
>.... [00:49:04 INFO]: Vault version: 1.7.3-b131
>.... [00:49:04 INFO]: EssentialsXProtect version: 2.18.1.4
>.... [00:49:04 INFO]: EssentialsXSpawn version: 2.18.1.4
>.... [00:49:04 INFO]: ChestShop version: 3.11 (build 213)
```

**Server log**: Not necessary (if needed please ask)

**EssentialsX config**: https://gist.github.com/EtherealSquid/39c7f4e612bfde2cf837be07b2716d59

### Details

**Description**  
By opening /invsee on yourself, splitting a stack into smaller stacks and shift-clicking it into your real inventory, you copy some of the smaller stacks and create duplicates.

**Steps to reproduce**  
1. Have more than one of any stackable object (preferrably 8+) .
2. Use /invsee on yourself.
3. Hover over to the /invsee 'copy' of your inventory, and go to the stack of items.
4. Split the stack, as many times as you want, into smaller stacks (I made a stack of 16 bread into a stack of 8 and two stacks of 4, for example).
5. Shift-click the new smaller stacks from the /invsee 'copy' of your inventory into your actual inventory. 
6. Close /invsee. 
 You now will have more than what you started with.

**Expected behavior**  
Expected to split stacks on both /invsee inventory and actual inventory, thereby keeping consistent and not duplicating items. Alternatively, should not be able to /invsee your own inventory.

**Screenshots**  
https://imgur.com/a/YLMvehd
https://imgur.com/xghPMZd

**Comment by Chew** [comment]
Duplicate (sorta) of #3065.
