### ISSUE TITLE
Item-based server currency

### ISSUE THREAD

**Issue by Richienb** [EssentialsX/Essentials#3658]
It would be useful if an item could be used as the server currency instead of money. In my case, I want to use emeralds as the currency.

**Comment by Laarryy** [comment]
There already exist plugins, such as [Gringotts](https://www.spigotmc.org/resources/gringotts.42071/) which accomplish this - no need to add an extra module to EssentialsX imo

**Comment by JRoy** [comment]
As Larry said, there are other plugins that accomplish this through the standard Vault-APIs.
