### ISSUE TITLE
Prefixes and suffixes are not being added to the player list.

### ISSUE THREAD

**Issue by Sophoster** [EssentialsX/Essentials#3663]
Full output of `/ess version`:

Server version: 1.16.1-R0.1-SNAPSHOT git-Paper-129 (MC: 1.16.1)
EssentialsX version: 2.18.1.0
PermissionsEx version: 1.23.5-SNAPSHOT
Vault version: 1.7.3-b131
EssentialsXSpawn version: 2.18.1.0
EssentialsXChat version: 2.18.1.0
You are running unsupported plugins!
You are running an unsupported server version!

**Server log:** https://gist.github.com/SophieEFoster/2eccf1af14c93d55332e31872b1f6a0e

**EssentialsX config** https://gist.github.com/SophieEFoster/c157ac6d4f3555840e3d18886a4c37de

### Help request

**Problem**
No prefix or suffix appears on the tab list.

**What I have tried**
I have enabled add-prefix-suffix, and tried going into different versions.

**Screenshots**
![image](https://user-images.githubusercontent.com/65441911/92965523-c9d1e000-f42a-11ea-9019-783fe4a7e0a2.png)

**Comment by triagonal** [comment]
You forgot to uncomment the config options. Right now they look like this:
```yaml
#change-playerlist: true
```
When to take effect, the `#` needs to be removed:
```yaml
change-playerlist: true
```

Try again with the appropriate config options uncommented and enabled.
