### ISSUE TITLE
Spawn issue *URGENT*

### ISSUE THREAD

**Issue by AggerTV** [EssentialsX/Essentials#3665]
### Information

Full output of `/ess version`:

https://gist.github.com/AggerTV/2e2eebf4777c587745a955a799eae7e2

**Server log:**  https://gist.github.com/AggerTV/cdf2226dfeee29896422a76c7ccb9635

**EssentialsX config** 
https://gist.github.com/AggerTV/e37039416d1e813ac43e0fdb04b9a353

### Help request

**Problem**

Players with the group "B" respawns at "B"'s spawnpoint, but if they then also have the donator group "AG" then they respawn at the group "C"'s spawnpoint, even though AG doesn't have any spawnpoint set and players therefor should respawn at "B"'s spawnpoint.

**What I have tried**

Contacted the discord support chat in MOSS
https://gist.github.com/AggerTV/e5ec28a11eb4c3d9d2fe43a4c45a756f

**Screenshots**

**Comment by AggerTV** [comment]
Hello? I would like for this to be resolved as soon as possible.

**Comment by whalehub** [comment]
@AggerTV EssentialsX is maintained by a few people in their spare time, so it could be weeks or even months before someone volunteers to investigate/fix your issue.

If you want this issue to be resolved as soon as possible, you'll have to pay someone to do it.

**Comment by Chew** [comment]
Sounds like some sort of permission issues. Does AG inherit C?

**Comment by triagonal** [comment]
EssXSpawn does not support multiple weighted or inherited group spawns. The only spawn or respawn points it attempts to find for the player (without considering other config options like `respawn-at-home`) are:

1. the spawn named after their **primary group**
2. if that doesn't exist, the spawn named `default`
3. if that doesn't exist, the world spawn

If anyone needs this issue's functionality, it may be a good idea to look into a more advanced spawns plugin.
