### ISSUE TITLE
/lightning allows smiting other players without the .others permission

### ISSUE THREAD

**Issue by ExceptedPrism3** [EssentialsX/Essentials#3667]
### Information

**Full output of `/ess version`**:

```
Nothing displays on the console as the command is normal
```

**Server log**: -

**EssentialsX config**: 

### Details

**Description**  
I have a rank that has essentials.lightning but they can smite other players with /smite <player> even tho they have essentials.lightning.others as false for all the rank system

**Steps to reproduce**  
apply essentials.lightning and smite someone else

**Expected behavior**  
- 

**Screenshots**  
-

**Comment by triagonal** [comment]
Confirmed:
```
>.... [23:55:46 INFO]: Server version: 1.16.2-R0.1-SNAPSHOT git-Paper-185 (MC: 1.16.2)
>.... [23:55:46 INFO]: EssentialsX version: 2.18.1.9
>.... [23:55:46 INFO]: LuckPerms version: 5.1.107
>.... [23:55:46 INFO]: Vault version: 1.7.3-b131
```

**Comment by ExceptedPrism3** [comment]
Will there be a fix for it?

**Comment by JRoy** [comment]
yes fix soon™

**Comment by Chew** [comment]
Build available: https://ci.ender.zone/job/EssentialsX/1017/
Hope this fixes it!
