### ISSUE TITLE
issue with /nick

### ISSUE THREAD

**Issue by AcesGamingUK** [EssentialsX/Essentials#367]
hi, i currently have this on a few servers but since updating i am unable to change /nick, 
i have \* perms and i get the error message "nicknames can only have their color changed"
any advice?

**Comment by SupaHam** [comment]
You have to negate the `essentials.nick.changecolor` permission.

**Comment by AcesGamingUK** [comment]
this still does not work with those with \* permissions, the same error shows

**Comment by SupaHam** [comment]
I gave you the wrong permission, it's actually `essentials.nick.changecolors`, but instead of negating that, update to the latest version for a more convenient fix. :)

**Comment by AcesGamingUK** [comment]
ok ty will try now

ty issue resolved

now to update 13 servers :(
