### ISSUE TITLE
Connected players without the vanish players

### ISSUE THREAD

**Issue by MrSuricate2** [EssentialsX/Essentials#3672]
### Feature request

**Would it be possible to add a placeholder to display the number of logins without the vanish players?**

**This would allow the admin not to be unmasked when he joins a server with the vanish on join.**

**Comment by Octol1ttle** [comment]
If you mean PlaceholderAPI placeholders, these aren't maintained by the EssX team

**Comment by Chew** [comment]
We do not manage the PlaceholderAPI expansion, try here: https://github.com/PlaceholderAPI/Essentials-Expansion
