### ISSUE TITLE
Tpr taking players to different worlds

### ISSUE THREAD

**Issue by Bananapocalypse** [EssentialsX/Essentials#3673]
### Information

Full output of `/ess version`:

14.09 15:11:11 [Server] Server thread/INFO Server version: 1.16.2-R0.1-SNAPSHOT git-Spigot-b5a13e6-0d8350a (MC: 1.16.2)
14.09 15:11:11 [Server] Server thread/INFO EssentialsX version: 2.18.1.0
14.09 15:11:11 [Server] Server thread/INFO LuckPerms version: 5.1.93
14.09 15:11:11 [Server] Server thread/INFO Vault version: 1.7.3-b131
14.09 15:11:11 [Server] Server thread/INFO EssentialsXChat version: 2.18.1.0
14.09 15:11:11 [Server] Server thread/INFO Towny version: 0.96.2.0

https://gist.github.com/Bananapocalypse/6b11c5220f20afaf3e39f89a9a953299

### Help request

**Problem**
I've got two separate worlds on the server, one is for PvE, one is for PvP. If you use /tprandom in the PvP world, it takes you back to the PvE world.

**What I have tried**
I've tried adding the PvP world center to the tpr.yml file, but that just creates the opposite problem, i.e. typing /tprandom in either world takes you to the PvP world, even if you started in the PvE world.

**Screenshots**
N/A

**Comment by pop4959** [comment]
Essentials random teleport currently only supports a single world as a target, which means that using the command will always teleport players to that world. Issue #3469 already requests multi-world support, and this is planned to be added via #3538 (in fact, it already does work, but I'm looking to continue improving upon it before it gets added).

For the time being, if you need two or more different random teleport locations, you will have to use a dedicated random teleport plugin like [RandomTeleport](https://www.spigotmc.org/resources/random-teleport-full-nether-support.76021/) or [Jake's RTP](https://www.spigotmc.org/resources/jakes-rtp.80201/). If you only need one, you can still prevent players from teleporting across worlds by only giving them permission to the command in the worlds you would like them to teleport from.

**Comment by Bananapocalypse** [comment]
Whoops! Sorry, I had searched for /tpr in the open tickets, I hadn't seen it had already been addressed. Thanks for the reply though, I'll try one of those out!
