### ISSUE TITLE
[Feature Request] Force AFK

### ISSUE THREAD

**Issue by crizyx** [EssentialsX/Essentials#3674]
### Feature request

**Feature description**
Force AFK is a AFK command argument, it can do make yourself or itself AFK when the player is in action like moving or interacting.

Command Example : 
`/afk [force] [username]`
`/afk force crizyx`

Permission Example : 
`essentials.afk.force`

**How the feature is useful**
This feature allows players who use their factories or farms to get into **AFK without disturbing** other players if they wish to spend the night. 
On the side of moderation, this makes it possible to avoid kicking the player who wants to use his factory when he left for work and not to see to put this player in AFK.

This feature will in no way interfere with the administration of the server because it allows the player to deliberately leave the choice to put themselves in AFK, if the auto-kick has been configured the player will still be kicked.

**Comment by Chew** [comment]
`/sudo user afk`

**Comment by Chew** [comment]
Nvm, this is already a thing, just type `/afk user`, permission node is essentials.afk.others

**Comment by crizyx** [comment]
> 
> 
> `/sudo user afk`

> 
> 
> Nvm, this is already a thing, just type `/afk user`, permission node is essentials.afk.others

That's not my request, I just want an additional command argument to force AFK when the player is in action like moving or interacting. If I move or else I interact after activating the force afk I will **not exit this mode**, that's the point.

**Comment by Chew** [comment]
Ohh, I see, like force them to remain AFK? Not sure what you mean then? Like they can never exit this state?

**Comment by pop4959** [comment]
Still don't understand how this feature is useful. It sounds like you don't really want AFK since you are asking for something to deliberately bypass it, which defeats the point.

**Comment by crizyx** [comment]
Yes that's force them or him to remain AFK in that sense.

This feature allows players who use their factories or farms to get into AFK without disturbing other players if they wish to spend the night. 

On my server it happens that very regularly players do not switch to AFK because they use their factory, the problem being that if the player does not switch to AFK while he is IRL he will therefore interfere with the players who need to spend the night.

**Comment by Chew** [comment]
You could do the auto-afk timeout, there's a config for that. Do nothing for 5 mins, you get marked as AFK, then the AFK timer starts (I believe is how that works)

**Comment by crizyx** [comment]
I was just saying that this feature (auto-afk) was not going to be affected and that it would be good if she kept the same behavior.

**Comment by crizyx** [comment]
What do you think ?

**Comment by crizyx** [comment]
Can you again change the label for "type: enhancement" ?

Thanks
