### ISSUE TITLE
essentials geoip bug

### ISSUE THREAD

**Issue by Yamiru** [EssentialsX/Essentials#3676]
1.  Fill out the template in full. (versions:)
**paperspigot latest 196 (same problem with older version)
essentialsx 2.18.1.12  (same problem with older version)**

2.  When linking files, do not attach them to the post! (log)
**[https://gist.github.com/Yamiru/a6ada4178d4103f18d1eadce6290be8d#file-gistfile1-txt](https://gist.github.com/Yamiru/a6ada4178d4103f18d1eadce6290be8d#file-gistfile1-txt)**

3.  If you are reporting a performance issue, please include a link to a
    **-**

4.  If you are reporting a bug with commands or something else in-game,
**not showing join locations and whois**

**Comment by Chew** [comment]
1) https://essentialsx.net/wiki/GeoIP.html
2) It's called Paper, not PaperSpigot

**Comment by Yamiru** [comment]
and where is problem?

**Comment by benwoo1110** [comment]
the problem is you didnt set it up. See the link sent by Chew.

So the solution is either delete EssentialXGeoIP if you don't want to use to, or read the wiki to set it up
