### ISSUE TITLE
Add own /data support

### ISSUE THREAD

**Issue by Andre601** [EssentialsX/Essentials#3679]
### Feature request

**Feature description**

It would be a neat addition, if EssentialsX would take over/override the `/data` command, to provide more useful information and features.

One idea would be to enhance the `/data get <option>` command, to have the returned data to be clickable using JSON, allowing players to copy (1.15+) the value(s) into their clipboard.

Some other idea:
`/data get <option> <target> --single` would return the data with a single copyable text (The whole data) instead of per-key copy which would be the default.

**How the feature is useful**

There can be cases where a dev may ask for the NBT data of a specific block or entity, in order to find the cause of an issue (I myself had this a few times already) and it is a huge pain to copy the text by hand as MC itself doesn't offer a way to just copy it.

Screenshots are of course an option but not always the best solution.

I don't see this as a important thing, so this could be done whenever.

**Comment by JRoy** [comment]
This would require essentials having the ability to access NBT data which is not possible in either the Spigot or Paper API(s) at this time. For that reason we cannot add this command to EssentialsX. Sorry.

**Comment by Andre601** [comment]
Fair enough.

**Comment by pop4959** [comment]
This would be really cool though. Maybe someone can add API for it.
