### ISSUE TITLE
EssentialsX interferes with JEI cheat mode /give command

### ISSUE THREAD

**Issue by VL4DST3R** [EssentialsX/Essentials#3681]
### Information

**Full output of `/ess version`**:

```
Server version: 1.16.1-R0.1-SNAPSHOT git-Spigot-9639cf7-4b9bc9d (MC: 1.16.1)
EssentialsX version: 2.18.1.0
Vault is not installed. Chat and permissions may not work.
You are running an unsupported server version!
```

**Server log**: no logs generated related to the issue neither on the server nor client latest.log.

**EssentialsX config**: entirely default config.

### Details

**Description**  
This is a crossover from the JEI issues git page, [here](https://github.com/mezz/JustEnoughItems/issues/2094), and may also be linked with the isse #3642.
We believe EssentialsX is interfering with the JEI /give command when in survival. It results in it not being able to spawn any item.
More info can be found on the JEI issue page.

**Steps to reproduce**  
1. Install JEI and join a server running EssentialX.
2. Enable cheat mode in JEI and while in survival, attempt to get an item.
3. No item is given to the player.

**Expected behavior**  
`/give` command does not interfere with the JEI mod.

**Screenshots**  
Not needed, i think.

**Comment by mezz** [comment]
JEI uses this code to figure out if the player can use `/give`:
https://github.com/mezz/JustEnoughItems/blob/4f83a971e91beb97547bb3fab58a7fa2a7d42f6e/src/main/java/mezz/jei/util/CommandUtilServer.java#L72-L88

I am guessing EssentialsX may be accidentally changing the `CommandNode.canUse` check so that it fails.

**Comment by VL4DST3R** [comment]
I've also updated essentials to the latest version (EssentialsX-2.18.1.12) and the issue is still present.

**Comment by Octol1ttle** [comment]
I don't think that it's Essentials' issue, and I believe that JEI should do something about that on their end

**Comment by JRoy** [comment]
Talked about this with mezz on Paper discord, from what I understand not an Essentials issue and more a Forge/Bukkit interop issue I've talked with mezz on how to resolve this on their end
