### ISSUE TITLE
EssentialsEco wrong commands cost for repair and repair-all

### ISSUE THREAD

**Issue by FeozRu** [EssentialsX/Essentials#3684]
### Information

**Full output of `/ess version`**:

```
23.09 12:30:25 [Server] INFO Server версия: 1.16.1-R0.1-SNAPSHOT git-Paper-123 (MC: 1.16.1)
23.09 12:30:25 [Server] INFO EssentialsX версия: 2.18.0.0
23.09 12:30:25 [Server] INFO PlaceholderAPI версия: 2.10.6
23.09 12:30:25 [Server] INFO LuckPerms версия: 5.1.26
23.09 12:30:25 [Server] INFO Vault версия: 1.7.2-b107
23.09 12:30:25 [Server] INFO Citizens версия: 2.0.27-SNAPSHOT (build 2067)
23.09 12:30:25 [Server] INFO EssentialsXProtect версия: 2.18.0.0
23.09 12:30:25 [Server] INFO EssentialsXAntiBuild версия: 2.18.0.0
23.09 12:30:25 [Server] INFO EssentialsXSpawn версия: 2.18.0.0
```

**EssentialsX config**: https://gist.github.com/FeozRu/a387141badc23b335008f15034b589f2

### Details

**Description**  
When I use "/repair all" ingame, plugin take money and for "/repair" and for "/repair all". In my test config it's $3.

**Steps to reproduce**  
Set "/repair" and "/repair all" commands cost and use "/repair all"

**Expected behavior**  
I expected one payment for $2.

**Screenshots**  
![изображение](https://user-images.githubusercontent.com/20014738/93995960-144c4880-fdab-11ea-996e-5308e4706d1e.png)

**Comment by pop4959** [comment]
Not a bug. `repair all` is the same command as `repair` (with just one more argument added), so they both match what you entered in your config. If you want to differentiate them, you need to write a regex that explicitly states that `repair` has no further arguments/text afterward, so it does not match with `repair all`.
