### ISSUE TITLE
/itemdb doesn't show aliases from custom_items.yml

### ISSUE THREAD

**Issue by LeeSpork** [EssentialsX/Essentials#3686]
We've been using shop signs to trade on our server, and to make that work well we've been setting custom item names to make sure all the items fit on signs.

I recently found out about this new custom_items.yml file, so I changed over to using that instead, however now I'm noting that my custom item names don't show up when I use /itemdb.

This is an issue since I don't know of any other command that lets my players easily find out what item names I've set.

**Comment by AetherisMC-Squid** [comment]
The custom_items.yml file also says:

> This file stores custom item aliases.
> We recommend you use the `/itemdb alias` command to manage these.'

AFAIK such command does not exist, or if it does, it does not work for me.

**Comment by Technoguyfication** [comment]
Can confirm this is still happening on 2.18.1.36. One of the default aliases is snad -> sand. Use `/itemdb sand` and the alias snad doesn't show up.

**Comment by DannyDelusion** [comment]
Still an issue on 3.12.1.-SNAPSHOT (build 334)
![image](https://user-images.githubusercontent.com/20606646/145161970-24c23f5d-7f4b-46f8-b415-4136faa6aff4.png)

**Comment by Chew** [comment]
Please open a new issue
