### ISSUE TITLE
Remove nickname when name changed

### ISSUE THREAD

**Issue by kaanakduman** [EssentialsX/Essentials#3687]
### Feature request

**Feature description**
When a player changes their mojang name, remove their nickname. This would probably be best as a config option.

**How the feature is useful**
On my server, players have the ability to use /nick to change their name colors, but not the name itself through the permission node essentials.nick.changecolors. When players change their name on Mojang, their old nick persists. Their username changes but their display name does not. I want these two to be in sync, and that's not possible without this feature.

**Comment by Chew** [comment]
This seems out of scope of essentials and more likely much more easier to do with an API that accesses the nickname, checks to see if it matches display name, if not, reset it. Not entirely sure if it is possible to get/set nickname from API, but if it's not, that should be the suggestion here.

**Comment by JRoy** [comment]
Like chew said, largely out of the scope of essentials. Should use a third party plug-in
