### ISSUE TITLE
Request: Formatted Balance

### ISSUE THREAD

**Issue by whoshenry** [EssentialsX/Essentials#369]
Redo the balance language, so if a player has $1500 it'll be shown when they do /bal as $1,500. This'll make it more formatted and easier to understand than a load of numbers, especially for higher balances - $5969241.94 = $5,969,241.94.

**Comment by voodootje0** [comment]
Good idea +1

**Comment by Kixot14** [comment]
Than need to separate a major and minor values:  5,969,241 dollars, 94 cents
because someone might be confuse, and read a penny with a general value.

Or just change the balance with spaces: $5 969 241.94 // 5 969 241.94 dollars

**Comment by SupaHam** [comment]
This feature has been implemented in [build 251](https://ci.drtshock.net/job/EssentialsX/251).
