### ISSUE TITLE
Show Total Available Homes in /home

### ISSUE THREAD

**Issue by AetherisMC-Squid** [EssentialsX/Essentials#3692]
### Feature request

**Feature description**
Showing your used and available homes when using /home to list all your set homes.
When you /home, the format would be along the lines of Your Homes: (9 out of 50)

**How the feature is useful**
Players on my server earn additional homes as they rankup, and can also get homes with donator ranks. They would like to know how many they have available at any given time.

**Comment by pop4959** [comment]
This is already possible; it is simply not the default. You just need to edit the `homes` translation key (by adding a custom language file with that key).

Here is an example:

`/plugins/Essentials/messages.properties` (create this file if it doesn't already exist):
```
homes=\u00a76Homes ({1}/{2})\:\u00a7r {0}
```
