### ISSUE TITLE
User are randomly invincible

### ISSUE THREAD

**Issue by Nussi1986** [EssentialsX/Essentials#370]
Some Player are randomly invincible, tested Plugin by Plugin. Its caused by EssentialsX. No Error in the Console or Chat.

**Comment by SupaHam** [comment]
More information please. We can't assume the environment you tested everything in.
Who were the player? (Permissions they have)
What plugins were enabled at the time?
etc.

**Comment by Nussi1986** [comment]
Sorry for the lack of Infos. There where a lot players been invincible, EssX was the only running Plugin at this time.

Plugins normaly installed on the Server

AsyncWorldEditInjector, WorldEdit, gReqBukkit, AdminFun, UltimateBungeeClient, OpenInv, PacketListenerApi, PlugMan, WorldBorder, Modifyworld, Votifier, Yamler, ProtocolLib, WorldGuard, Multiverse-Core, AutoSaveWorld, LibsDisguises, AsyncWorldEdit, TitleAPI, IPWhitelist, SimpleList, SimpleHeads, DeathMessages, PermissionsEx, FeatherBoard, Multiverse-Portals, GAListener, Vault, GriefPrevention, Prism, RedstoneClockPreventer, Essentials, InSigns, LWC, TrailGUI, Citizens, EssentialsChat, SelfPromote, ClickSort, ServerSigns, RandomLocation, EssentialsSpawn, ChopTree3

Permissions of the Main Group:

```
- essentials.kit
- essentials.kits.gebiet
- serversigns.use.info
- serversigns.use.spiel
- serversigns.use.randomtp
- -lwc.protect
- -essentials.me
- -selfpromote.unlock.chat
- greq.ticket
- essentials.tpaccept
- essentials.tpdeny
- essentials.warp
- -essentials.warps.angel
- essentials.warps.verlosung
- essentials.warps.Handel
- essentials.warps.Lotto
- essentials.warps.1.8
- essentials.warps.Game
- -essentials.warps.talkswg
- RandomLocation.Use
- citizens.npc.talk
- multiverse.portal.access.survival2015
- multiverse.portal.access.survival2015_nether
- multiverse.portal.access.survival2015_the_end
- multiverse.access.berge
- multiverse.access.survival
- multiverse.access.survival2015
- multiverse.access.survival2016
- multiverse.access.survival_nether
- multiverse.access.survival2015_nether
- multiverse.access.survival2016_nether
- multiverse.access.survival_the_end
- multiverse.access.survival2015_the_end
- multiverse.access.survival2016_the_end
- modifyworld.*
- essentials.signs.use.disposal
- citizens.npc.talk
- essentials.ignore
- essentials.list
- essentials.afk.auto
- essentials.msg
- essentials.mail
- essentials.mail.send
- essentials.delhome
- essentials.home
- essentials.sethome.multiple
- essentials.sethome.multiple.Neuling
- essentials.sethome
- essentials.spawn
- essentials.afk
- essentials.help
- essentials.back
- essentials.back.ondeath
- essentials.jail.allow.rules
- teamlist.team
```

**Comment by SupaHam** [comment]
Thank you for getting back to me. I'm unable to track down the issue with just this information. Could you please http://pastebin.com the essentials user file of the player this is happening to, and also pastebin the server.properties file in the root folder?

**Comment by vemacs** [comment]
This is a  Spigot bug IIRC. PaperSpigot and SportBukkit have a patch to mitigate this. It has nothing to do with Essentials(X).
