### ISSUE TITLE
[06:01:02] [Server thread/ERROR]: [Essentials] You are running an unsupported server version!

### ISSUE THREAD

**Issue by Fargus-Van-Crystal-de-Mindark** [EssentialsX/Essentials#3706]
When I start the server I get this error:

[06:01:02] [Server thread/ERROR]: [Essentials] You are running an unsupported server version!

I'm on the latest paper build version.

**Comment by pop4959** [comment]
Download the latest version of Essentials for 1.16.3 here: <https://essentialsx.net/downloads.html>

The version you are using is most likely outdated.

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
ok thanks
