### ISSUE TITLE
How to prevent lava damage for players and except other entities

### ISSUE THREAD

**Issue by crizyx** [EssentialsX/Essentials#3707]
### Information

Full output of `/ess version`:

```JAVA
[12:10:23 INFO]: This server is running Essentials 2.18.1.13
```

**Server log:** [latest.log](https://github.com/EssentialsX/Essentials/files/5322989/latest.log)

**EssentialsX config** config.yml can't be upload ![image](https://user-images.githubusercontent.com/46645389/95012709-13cd7080-063b-11eb-92c5-e37f8d7c1aab.png)

### Help request

**Problem**
Since version 2.18 entities no longer take lava damage when the configuration parameter is "lavadmg: true" by looking at the description just above it seems normal to me (# Should damage via lava be disabled? Items that fall into lava will still burn to a crisp.;)) but however the logic would also want it to be for this parameter also "firedmg: true" or this is not the case.

I deduce that it is an oversight or a bug but what I want is to find the behavior that the plugin had in 2.17 when the entities took damage even when the lavadmg was on true.

If it is important for you to prevent all entities from taking damage you should create a new option because I am using the "essentials.protect.damage.lava" permission for a group of players who must not take damage lava and it conflicts with the entities that they must take lava damage.

**What I have tried**
I compared the behavior of version 2.17 and 2.18 and set lavadmg to true and false.

**Screenshots**
![image](https://user-images.githubusercontent.com/46645389/95013800-f69ca000-0642-11eb-9b79-9fc78a1e7d01.png)
![image](https://user-images.githubusercontent.com/46645389/95013829-1f249a00-0643-11eb-9783-5fc1d976ee70.png)

**Comment by benwoo1110** [comment]
you should use a paste service for your config and server logs. https://pastebin.com/

**Comment by crizyx** [comment]
Essentials config : https://pastebin.com/kYMJsqnd

Server Logs : https://pastebin.com/Nf6398fn

**Comment by crizyx** [comment]
Do you have any idea ?
