### ISSUE TITLE
Comma Separated Money

### ISSUE THREAD

**Issue by GiansCode** [EssentialsX/Essentials#371]
Hello,

i was wondering if it would be possible to add comma separated money styling to all economy based/money based commands. This will make it easier for everyone to read, as well as more ascetically pleasing.

Thanks.

**Comment by SupaHam** [comment]
Duplicate of #369

**Comment by SupaHam** [comment]
This feature has been implemented in [build 251](https://ci.drtshock.net/job/EssentialsX/251).
