### ISSUE TITLE
Sleep Timer

### ISSUE THREAD

**Issue by derbygamer84** [EssentialsX/Essentials#3714]
Is there any way to change how many players are required to skip time to day and how long it takes to sleep, and if not could you add this feature.

**Comment by Chew** [comment]
For the amount of people to skip the day, this seems out of the scope of essentials.
For the how long it takes to sleep... is that even customizable?

**Comment by derbygamer84** [comment]
Some sleep skip plugins, that are outdated now, had an option to change length because in essentials it’s instant to day instead of actually getting into the bed

**Comment by crizyx** [comment]
Nice idea

**Comment by mdcfe** [comment]
EssentialsX's bed functionality is fairly simple, and I don't feel this is something we're likely to expand significantly. If you want more control over skipping the night, you can try [BetterBeds](https://www.spigotmc.org/resources/betterbeds.1824/).
