### ISSUE TITLE
Add /fixall and /repairall as aliases for /fix all and /repair all

### ISSUE THREAD

**Issue by blastoise186** [EssentialsX/Essentials#3718]
### Feature request

**Feature description**
With modern versions of Minecraft now supporting full tab command completion, it can be much faster to execute commands without having to type out the entire command manually. However, it can't autofill flags with a space between the command and the flag in the same way.

One thing I would find helpful, would be if the "all" flag with /fix and /repair could be aliased to /fixall and /repairall to enable full tab completion to work, while still allowing the existing method to work as it does now (to avoid confusion). I feel that it can be a small time saver for when you're using these commands a lot.

**How the feature is useful**
For the most part, providing these aliases would mainly be a time saver for players more than anything else, but it may also improve accessibility slightly for players who rely heavily on tab completion. Other than allowing the commands to be executed without needing a space, they remain identical to how the commands are now.

Currently, the tab completion in Minecraft simply stops as soon as a space would be needed, so this might be useful to avoid having to use other workarounds for the same thing.

**Comment by rye761** [comment]
Just define it in your commands.yml. Still works with tab complete.

```
aliases:
  repairall:
  - "repair all"
```

**Comment by blastoise186** [comment]
Thanks for the answer!

That sounds pretty easy then.
