### ISSUE TITLE
Fly permission not checked on nether portal teleport

### ISSUE THREAD

**Issue by AetherisMC-Squid** [EssentialsX/Essentials#3722]
### Information

**Full output of `/ess version`**:

```
>.... [19:51:19 INFO]: Server version: 1.16.3-R0.1-SNAPSHOT git-Paper-220 (MC: 1.16.3)
>.... [19:51:19 INFO]: EssentialsX version: 2.18.1.23
>.... [19:51:19 INFO]: PlaceholderAPI version: 2.10.9
>.... [19:51:19 INFO]: LuckPerms version: 5.1.107
>.... [19:51:19 INFO]: Vault version: 1.7.3-b131
>.... [19:51:19 INFO]: EssentialsXProtect version: 2.18.1.23
>.... [19:51:19 INFO]: EssentialsXSpawn version: 2.18.1.23
>.... [19:51:19 INFO]: ChestShop version: 3.11 (build 213)
```

**Server log**: Not necessary for this issue

**EssentialsX config**: https://gist.github.com/AetherisMC-Squid/39c7f4e612bfde2cf837be07b2716d59

### Details

**Description**  
When entering the nether via nether portal, players are not checked for their fly permission. This means that players can enable their fly in a world that has fly enabled and use a nether portal to keep that fly status within the nether, even if they are not supposed to have it.  A hard teleport like /warp or /home does not produce this issue.

**Steps to reproduce**  
Enable /fly in a world you have permission.
Teleport to the nether via a nether portal, while not having essentials.fly defined or having it false in the nether world context (luckperms)
/fly will still be enabled despite not having permission.

**Expected behavior**  
Fly permission should be checked on any world change and should be disabled if undefined or false in the world upon entry.

**Screenshots**  
N/A

**Comment by JasonHorkles** [comment]
After checking the debug, it does indeed check the permission and properly disables fly when you enter the Nether
You can find the log here: https://hasteb.in/zikibopa.md

**Comment by AetherisMC-Squid** [comment]
Are you standing on the ground when going through the portal? I am using a larger-than-standard size portal and flying the middle of it.

**Comment by JasonHorkles** [comment]
Just flying thru a normal one at the top

**Comment by AetherisMC-Squid** [comment]
I may have phrased my issue incorrectly - the actual command /fly is properly disabled, and the permission is checked as such, however users currently in the air when going through the portal still have the ability to fly around. Their fly status is disabled, but they still have the ability to fly.

**Comment by JasonHorkles** [comment]
I am still unable to reproduce this issue with only Paper-244 (1.16.3), Essx 2.18.1.24, LP 5.1.93, and Vault 1.7.3-b131 installed, all on default configs

**Comment by JRoy** [comment]
Cannot reproduce
