### ISSUE TITLE
respawn-anchor-explosion is still explosion

### ISSUE THREAD

**Issue by LightExplorer** [EssentialsX/Essentials#3723]
### Information

**Full output of `/ess version`**: 
```
Server version: 1.16.3-R0.1-SNAPSHOT git-Spigot-988b411-2a3ca13 (MC: 1.16.3)
EssentialsX version: 2.18.1.23
GroupManager version: 2.0.1-b332
PlaceholderAPI version: 2.10.10-DEV-110
Vault version: 1.7.3-b131
Citizens version: 2.0.27-SNAPSHOT (build 2133)
EssentialsXChat version: 2.18.1.23
CMI version: 8.7.8.3
EssentialsXProtect version: 2.18.1.23
EssentialsXAntiBuild version: 2.18.1.23
```

**Server log**: 

**EssentialsX config**: 
https://gist.github.com/LightExplorer/e8300d697d25d1199de0a9f473e881ee
### Details

**Description**  
respawn_anchor use glowstone recharge and click it is explosion .
I set respawn-anchor-explosion to true, but it still explosion .
TNT or creeper set true is not explosion .

**Steps to reproduce**  

**Expected behavior**  

**Screenshots**  

https://i.imgur.com/VtoAIGH.png

**Comment by JRoy** [comment]
Cannot reproduce on latest. Please make sure you edited your actual config and reload the config by doing `/ess reload`

There may a slight chance another issue I found while testing causes this so I'll keep this open until I fix that

**Comment by LightExplorer** [comment]
`/ess version:`
```
Server version: 1.16.4-R0.1-SNAPSHOT git-Paper-279 (MC: 1.16.4)
EssentialsX version: 2.18.2.0
GroupManager version: 2.0.1-b332
PlaceholderAPI version: 2.10.10-DEV-110
EssentialsXProtect version: 2.18.2.0
EssentialsXChat version: 2.18.2.0
CMI version: 8.7.10.5
```
Uh... as shown in the video, it still explosion.

https://youtu.be/uu04OgInusE

**Comment by JRoy** [comment]
Ohhhh, didn't realize they explode when not full charge. Fix coming soon
