### ISSUE TITLE
New player kit is duplicated with EssentialsAntiBuild

### ISSUE THREAD

**Issue by crizyx** [EssentialsX/Essentials#3731]
### Information 

**Full output of `/ess version`**:

```
https://pastebin.com/H1mYrjZM
```

**Server log**: https://pastebin.com/DP0CFRi0

**EssentialsX config**: https://pastebin.com/jxN8jgMx
### Details

**Description**  
Server running version : **Paper 1.16.3**

When a player logs in he receives the welcome kit twice.

**Steps to reproduce**  
Go to the config file to EssentialsAntiBuild part and set **use** to **true**.

Like this :
```
    # Should people without the essentials.build permission be allowed to use items?
    # Set true to disable using for those people.
    # Setting to false means EssentialsAntiBuild will never prevent you from using items.
    use: true
```

Now delete your playerdata to simulate a new player and see.

**Expected behavior**  
The player have not the permission to drop and pickup items when is logs in, the kit is overflowed.

**Comment by pop4959** [comment]
Unable to replicate this in the way you described, seems to work just fine.
