### ISSUE TITLE
/time set commands not functioning on command blocks

### ISSUE THREAD

**Issue by DrWolfyLords** [EssentialsX/Essentials#3732]
All commands related to time adjustments are met with "Error: null".
![image](https://user-images.githubusercontent.com/17698576/96056313-19953400-0e3b-11eb-864b-6f91395ab047.png)

**Comment by triagonal** [comment]
Duplicate of #3621.

This was fixed in #3622. Download the newest version of EssentialsX [here](https://essentialsx.net/downloads.html).

**Comment by pop4959** [comment]
@DrWolfyLords There isn't any reason to hide your post when it's closed -- it just makes it more annoying to search back through old issues.

Hope the latest version works for you. 😃
