### ISSUE TITLE
Cooldown for tp will not work

### ISSUE THREAD

**Issue by chemaholic77** [EssentialsX/Essentials#3736]
### Information

Full output of `/ess version`:

**Server log:** 

**EssentialsX config** 

### Help request

**Problem**
I am trying to set a 5 minute cooldown timer for the tp command. I have edited the config file for essentialsx a few different ways. Currently my cooldown looks like this:

command-cooldowns:
  tp: 300

I am using Luckperms as well so I do not know if that is causing an issue. I have given the player permission to use the tp commands in Luckperms and they function properly, but the cooldown does not work.

The cooldown timer I set for requesting a kit a setup works fine although I set that timer up in the essentialsx kits config file.

**What I have tried**
I have tried a couple of different syntaxes in addition to the one posted above to no avail.

command-cooldowns:
  "^(tp)": 300

tp-cooldowns: 300

**Screenshots**

**Comment by JRoy** [comment]
A recent dev build should fix this, if you still cannot get it to work on the latest dev build please let me know
