### ISSUE TITLE
Command Block limit a lot lower than Minecraft's one

### ISSUE THREAD

**Issue by Inky1003** [EssentialsX/Essentials#3737]
### Information

**Full output of `/ess version`**:

```
[17:05:04 INFO]: Server versão: 1.16.3-R0.1-SNAPSHOT git-Paper-208 (MC: 1.16.3)
[17:05:04 INFO]: EssentialsX versão: 2.18.1.28
[17:05:04 INFO]: Vault versão: 1.7.3-b131
[17:05:04 INFO]: EssentialsXSpawn versão: 2.18.1.28
[17:05:04 INFO]: EssentialsXChat versão: 2.18.1.28
```

**Server log**: https://gist.github.com/Inky1003/62e1dbcf59ad39d772e75fb81a9b1188

**EssentialsX config**: https://gist.github.com/Inky1003/95cf7e0570af6b49dc16bf38cddbc2ac

### Details

**Description**  
Huge command in a command block throws internal error and kicks me.

**Steps to reproduce**  
1 - Put a command with a minimun length of 2048 in a command block
2 - Boom, you instantly get kicked from the server. (Screenshot)

**Expected behavior**  
Nothing special... just the command as It is.

**Screenshots**  
![image](https://user-images.githubusercontent.com/13457223/96778413-0d245480-13c2-11eb-93ea-6a16e040642a.png)

**Comment by JRoy** [comment]
Can you reproduce this on the latest Paper and EssentialsX versions without any other plugins installed?

**Comment by Inky1003** [comment]
Sure, testing right now...
Apparently the same things occur.
Sending the /ess version
```
[17:55:30 INFO]: Server versão: 1.16.3-R0.1-SNAPSHOT git-Paper-244 (MC: 1.16.3)
[17:55:30 INFO]: EssentialsX versão: 2.18.1.28
[17:55:30 INFO]: Vault versão: 1.7.3-b131
[17:55:30 INFO]: EssentialsXSpawn versão: 2.18.1.28
[17:55:30 INFO]: EssentialsXChat versão: 2.18.1.28
```

and the latest log didn't changed so much, but here It is:
https://gist.github.com/Inky1003/1bd9a18d9fb4b0699d88d30fc25da3d4

**Comment by Chew** [comment]
Just tested.
Fresh Paper (no plugins) - No kick
Install Essentials (no configuring) - No kick


<details>
<summary>
My command:
</summary>
/tellraw @p {"text":"gljhguidregj[edtjgierfghierulgh9er0u84ewtuj4wptuew0-rwietejtsnr9tpwriutjeroupw9ueathiwetq2i04-i]3w095ritk erigutretyutydhirtdgre9teisrtfghs;o9fthiafsf8ygts89esr9ty49wt057et9e0tpuwiotoewsus's6ty8sotyse6tyhews9[0w754--wq50w45w90tyrus7otysotra9yr8tsuilytraspyrawyrw385y2379 yu9p127y2109y2057yo98&Y%^$(*Y%($^*%$(%Y(^$(*%$Y(%$^ghty8t68s9y9syus80tydt;8esotyes9typw4et7w4u;pt9w4e7utp9wt7wb9cn0t798w46vyt4w980t6w49ytw4896ty8retyo8s;et894eyo48y;4o89tyw4ityrw498yt5956ty9849yslohs8dhgdfughsdghdsoyg8reudghdygsisdygr;tgir;dotyurd'97ydrpdr9t7retypdrtilhdyugygyui8d8gdytr9e8ydt8r9ty80rtysertyre8t09yr8t;s9trs9t98pt70re7ter709te07es07997s75984e7565476gfgvbjvclbxuioygidroytoiut0'[ds09t'sd87t90[r7te-90er7tyui8rsyosi8ytuo75w375903yru5t890o4tyu08475tP &%P(*%$(*Y69*yt*(O7rywyf08fy8(YfrS*()rtywTi98oy*(Oye4tu8IOtyr*Tyw8ty8e94tyert8e05ryterertiugrteyy089YT0t9807tyurtp9ireyuert9i8yert9yert8yreu;9pwp;7yt9p05w7ty495ty6945y5ty8754t5t4y7895y978ty9i78T&TSETYU()P$TU($WTeue49t[ue[rgueryt]-htrujht6rujh6trfujh6trujht6rfujtr6ututdyrdhdfhttfhtfhdrbkrdtbukrdethgiurtrter8tyu]-8ty]ety\\eer\\treuijhirehgiureghtrhrt4h5rt94hrt94h87rh4rh56rt1h5rt63h1tr23h13g2h0132fgh132yi1yu3o131v2b13x2zfv103x21g32m13ghk165tfzOIHERST*SITY(*&TYS(*&ETr7sete478e489756498746548u5794587uy4587u4y95465udrgtdrghuirhitretyh8uiretyi7rety7rety7er6t87re6guyugdguifiuhfdjhldsyuiyuutyjf6trdw34swxrtctbyuhnkom,komjibftceswzxdrcvgybhinjinuyhvtrfxcerxcrtbhunjiniuhvgtyvr5ctybuyhnoknuyf67456356f7ygioyy0097y86c54w43z2xe57u vtv7yuto798y987p0987y9ty786fr567e65efghfghfghgfhfghgfhfghgfhgfh65465gh86gfh789gh79fg87hfg7hfg456hgf546hg45f6h12h2314564568786hgf1221^^^^^^sdhgyfhygfhgdshfdhdhfhfjfkjkjhdghdfkgjhdghjdlghdglutdlhudhuigbcvjb m,xc.bjclxloisjsk;rsjdfkashelelewo tgher geenerla kaejolcvneie heleowowow ueu nayaaah ugashjksdgfisdgfisdigufsdufgsdghkfsdghfdhsgfsdgbjksdgbksgbhjdhsgdiehgigjiofmnjodgeerggrrggrreehfgut9800pl,nbvdw5r678i967urthbtrfhydfhdfhfghfggffgdgdgdgdfdfhydtdyustufjtjggghkjgjhckjkygjyjgjhcfutfjyytrtryd1tyrehjtyfugjghfggfgugfghfgjyjghjygfjrtfttjfjh","bold":true,"italic":true,"underlined":true,"strikethrough":true,"obfuscated":true,"color":"#805B5B","font":"minecraft:default"}
</details>

Maybe provide your command? Not sure what could be going on here, and why Essentials could/would be interfering here.

If it matters:
```
[18:57:36 INFO]: CONSOLE issued server command: /ess version
[18:57:36 INFO]: Server version: 1.16.3-R0.1-SNAPSHOT git-Paper-244 (MC: 1.16.3)
[18:57:36 INFO]: EssentialsX version: 2.18.1.28
[18:57:36 INFO]: Vault is not installed. Chat and permissions may not work.
```

**Comment by Inky1003** [comment]
https://gist.github.com/Inky1003/69a6e24c025b8e5c9cf1f17278f18314
This is the command

**Comment by pop4959** [comment]
Have you tried using a vanilla command, or using the vanilla Minecraft server? This doesn't sound like it would be an Essentials issue.

**Comment by Inky1003** [comment]
this is an vanilla command, the problem is, I can't put It in a command block because of EssentialsX. I just removed It and It works fine.

**Comment by pop4959** [comment]
Are you sure you are running minecraft's give command, and not the one that Essentials provides?

Try `/minecraft:give` instead of `/give` (which is probably the same as `/essentials:give`).

**Comment by Chew** [comment]
I don't think the command is the issue, it would be the length since the reproduction steps never indicated you needing to *run* the command. I'll try the provided command, with the provided steps, and come back.

**Comment by Inky1003** [comment]
Guys, It was It. Just changing from EssentialsX give to minecraft's one.

**Comment by pop4959** [comment]
Cool. My hunch was just that plugin commands have a lower limit than Minecraft's. Something I noticed some time ago myself, so glad to hear that fixed it for you.
