### ISSUE TITLE
Wolf don't spawn

### ISSUE THREAD

**Issue by C00kiekiller** [EssentialsX/Essentials#374]
Hi,

i've tried a lot with my plugins. After all i find out that EssentialsX is preventing wolf spawn.
To be sure that it is up to EssentialsX I created a new spigot 1.8.8 server only with EssentialsX and no wolf likes to spawn. When I disabled EssentialsX wolves are spawning in my Taiga Biom.

Problem:
- wolf don't spawn

Server:
- CraftBukkit version git-Spigot-db6de12-07c3001 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
- java version "1.8.0_66"
  Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
  Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

Plugins:
- EssentialsX latest build

Regards

Cookie

**Comment by SupaHam** [comment]
Please list all the plugins you have when this issue occurs. (Type /plugins in the console or game)

**Comment by C00kiekiller** [comment]
To be sure that it is up to EssentialsX I created a new spigot 1.8.8 server only with EssentialsX and no other plugin.

In our normal world I use the following Plugins:
- WorldEdit
- OpenInv
- BetterBeds
- LogBlock
- Lift
- PermissionsEx
- MZServerInfo
- MOTDColor
- Vault
- CommandSigns
- Multiverse-Core
- WorldGuard
- ProtocolLib
- ChopTree3
- Essentials
- CraftBook
- BetterShops
- RecipeManager
- SuperVanish
- LWC
- Timeismoney

Greetings :)

**Comment by SupaHam** [comment]
My request was to list all of the plugins you have enabled at the time, EssentialsX consists of multiple modules.

**Comment by C00kiekiller** [comment]
Hi, :

sry I'm a german guy.
Sometimes it is hard for me to understand the meaning of the written englisch word. :grin: 
Here is the list of all enabled plugins.
Also you can find attached my EssentialsX config file.

<details> <summary>

List of Active Plugins</summary>


- WorldEdit
- OpenInv
- BetterBeds
- LogBlock
- Lift
- PermissionsEx
- MZServerInfo
- MOTDColor
- Vault
- CommandSigns
- Multiverse-Core
- WorldGuard
- ProtocolLib
- ChopTree3
- Essentials
- CraftBook
- BetterShops
- RecipeManager
- SuperVanish
- LWC
- Timeismoney
  </details>

[EssentialsX config.txt](https://github.com/drtshock/Essentials/files/92971/config.txt)

Greetings :smile:

**Comment by kashike** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-815

**Comment by SupaHam** [comment]
With the help of Kashike, this issue has been tracked down to be a vanilla issue and Spigot refuses to fix it in order to follow their conventions I suppose. Sorry. https://hub.spigotmc.org/jira/browse/SPIGOT-815

**Comment by C00kiekiller** [comment]
Hi, 

thanks 4 reply but the link https://hub.spigotmc.org/jira/browse/SPIGOT-815 describes the problem with 1.8 and 1.8.3 but not for 1.8.8.

I've done a few tests to resolve this issue.
- Test 1:
  I install a clean vanilla server (latest build from https://minecraft.net/download)
  Resolution:
  The wolf spawns :+1: 
- Test 2:
  Now I installed a clean spigot server (latest build with BuildTools) 
  Resolution:
  The wolf spawns :+1: 
- Test 3:
  I installed a spigot server (latest build) with all my plugins but NO EssentialsX
  Resolution:
  The wolf spawns :+1: 
- Test 4:
  Finally I installed a spigot server (latest build) with all my plugins  WITH EssentialsX
  Resolution:
  The wolf do not spawn :-1: 

In this case I can't understand why it shoudl be a vanilla issue?

Greetings,
Cookie :cookie:

**Comment by SupaHam** [comment]
I'll try to look into this more, but I've already spent 30 minutes roaming taiga biomes in the hopes that I would find a pack of wolves, but I found nothing.

Mojang have not reported any fixes for this supposed bug either: http://minecraft.gamepedia.com/Version_history
