### ISSUE TITLE
Add/Buy Sethomes

### ISSUE THREAD

**Issue by JWSchmidt1** [EssentialsX/Essentials#3740]
### Feature request

**Feature description:**  

An add "sethome" to a specific user/ a buy feature to buy new sethomes

**How the feature is useful:**  

Its highly suggested in our community, it would help players getting around better

**Comment by Chew** [comment]
This seems out of the scope of essentials. Since sethomes are permission based, you could set multiple groups and have another plugin give them the permission to set more homes.

**Comment by JRoy** [comment]
Closing for reason above, we're not going to fragment how we decide how many sethomes each person has.
