### ISSUE TITLE
People can TP to people in vanish

### ISSUE THREAD

**Issue by JHarris12345** [EssentialsX/Essentials#3746]
### Information

**Full output of `/ess version`:**

```
https://gyazo.com/c4f06ac234ef0dd63681af28983ca7da
```

**Server startup log:**

https://pastebin.com/V0GEv64p

**EssentialsX config:**

https://pastebin.com/CX1ydVC1

### Details

**Description:**  

People can TP to those in vanish

**Steps to reproduce:**  

Use /tp on someone who is in vanish

**Expected behavior:**  

You shouldnt be able to

**Console stack trace:**  

```

```

**Screenshots:**

**Comment by pop4959** [comment]
Not able to replicate this on paper-204 and Essentials 2.18.1.12. Seems to be working perfectly fine.

Have you checked this using Paper, or without other plugins installed?

**Comment by JHarris12345** [comment]
Yes and it is an issue

**Comment by JHarris12345** [comment]
the name wont tab complete so you need to type /tp <full name> but it will work

**Comment by JRoy** [comment]
Cannot reproduce either, likely an issue with whatever "Steadfast" is

**Comment by JHarris12345** [comment]
Please re-open this, this is a bug I have just tested on the latest paper (#265) and on the latest essentials dev build too with NO plugins.

Startup log: https://pastebin.com/sFFSKyZB

You can see right at the bottom of the startup log, JHarris goes into /v and then princess_lyds teleports to him successfully (with no perms allowing it). I repeat the issue that it WONT tab complete the name, you need to type the name in full and it will TP.

As you can see, no plugins and on default paper @JRoy

**Comment by Chew** [comment]
What command are they running to teleport?

**Comment by JHarris12345** [comment]
use /tp <full name>. It wont tab complete so it will look like the command doesnt work. But upon executing the command it teleports them
