### ISSUE TITLE
URL in chat are broken by the formating

### ISSUE THREAD

**Issue by Vlammar** [EssentialsX/Essentials#3747]
### Information

**Full output of `/ess version`:**

```

```

**Server startup log:**

**EssentialsX config:**

### Details

**Description:**  

When providing a dynmap URL for example the formating doesn't detect the link and break it.
**Steps to reproduce:**  

Send a dynamp link in chat that use various formating characters used by essentials
**Expected behavior:**  

Link should display like this: https://map.zcraft.fr/?worldname=V5apname=surface&zoom=6=-3136&y=64&z=-6847
**Console stack trace:**  

```

```

**Screenshots:**  

Result
https://imgur.com/a/6ayfOnS

**Comment by pop4959** [comment]
Can you please fill out the issue template completely.

**Comment by ram1660** [comment]
Hello,
I can't confirm this behavior as you expressed there.
Please provide more info for us to understand the problem. :)
