### ISSUE TITLE
Having trouble with Minecraft essentials chat formatting

### ISSUE THREAD

**Issue by bdmrsmokesganj** [EssentialsX/Essentials#3748]
Player names are displaying as '[]<player name>' and I would like to remove the '[]' but I am unsure of what to do. This is my plugin list : 
![PluginList](https://user-images.githubusercontent.com/73685474/97668043-86bde180-1a57-11eb-858b-8d6dc049e2de.png) Any and all help would be appreciated and let me know if any other info is needed from me. Thank you!

**Comment by pop4959** [comment]
IIRC it's because of Multiverse. If you uninstall it briefly you should be able to double check that.

**Comment by bdmrsmokesganj** [comment]
> IIRC it's because of Multiverse. If you uninstall it briefly you should be able to double check that.

Omg thank you so so much I have been trying so hard to figure that out have an amazing night/day

**Comment by benwoo1110** [comment]
you can set `chatprefix: false` in mv config
