### ISSUE TITLE
Socialspy doesn't show /whisper

### ISSUE THREAD

**Issue by Platinteufel** [EssentialsX/Essentials#375]
Hey,

I don't know if it's already fixed in the latest dev-builds, but in b239 socialspy only shows /msg messages and doesn't transmit private messages via /w or /whisper.

**Comment by Kakifrucht** [comment]
Go in your config.yml, find socialspy-commands node and add it to the list.

**Comment by Platinteufel** [comment]
Oh okay, thanks!
