### ISSUE TITLE
Configurations Not Applying

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#3751]
### Information

**Full output of `/ess version`:**

```
2.18.1.0
```

**Server startup log:**

https://gist.github.com/BeesusBrist/be91cc244449f81cf6c690e88472311c
**EssentialsX config:**

https://gist.github.com/BeesusBrist/d34aaa933696a9bb91002a5ae0196734

### Help request

**Problem:**  

The configurations I am making in the EssentialsX config.yml file do not apply themselves even after I save, reload, and restart the server. The changes show that they are saved in the config file, but they do not show up on the actual server.
**What I have tried:**  

I have tried to reset the line of code that I am editing in the config and making my changes again. I have tried writing the line in different ways to see if I was simply messing the code up. I've tried reloading and restarting the server numerous times. 
**Console stack trace:**  

```

```

**Screenshots:**

**Comment by benwoo1110** [comment]
can you say with exact configuration option are you referring to?

**Comment by ghost** [comment]
> can you say with exact configuration option are you referring to?

There are 2 mainly. 
nickname-prefix: '~' -> nickname-prefix: ''
format: '<{DISPLAYNAME}> {MESSAGE}' -> format: '&f{DISPLAYNAME}&8&l:&r {MESSAGE}'

**Comment by benwoo1110** [comment]
from what I can tell, you dont have essentialsXChat installed. https://essentialsx.net/downloads.html

**Comment by ghost** [comment]
> from what I can tell, you dont have essentialsXChat installed. https://essentialsx.net/downloads.html

Oml of course I didn't. I couldn't find it either, so thank you!!

**Comment by JasonHorkles** [comment]
If this is no longer a problem please close your issue @BeesusBrist
