### ISSUE TITLE
Cant use any tools and break blocks

### ISSUE THREAD

**Issue by PixGuy** [EssentialsX/Essentials#3752]
The title says it all...Do I need to add any perms to the default role?
It says "You Don't Have Permission To Use XYZ"

**Comment by benwoo1110** [comment]
look at build permission from: https://essinfo.xeya.me/permissions.html

Or you can just delete essentialsXAntiBuild if you just intend to let all players build.

**Comment by Chew** [comment]
Basically what benwoo1110 said. Please fill out the template next time, very important for figuring out your problem. Configuration helps with this too.
