### ISSUE TITLE
Can see player who use /vanish in Player menu while type "P" 1.16.4

### ISSUE THREAD

**Issue by LowScarlet** [EssentialsX/Essentials#3754]
### Information

**Full output of `/ess version`:**

```
[06:14:43 INFO]: (!) Server version: 1.16.3-R0.1-SNAPSHOT git-Paper-253 (MC: 1.16.3)
[06:14:43 INFO]: (!) EssentialsX version: 2.18.1.23
[06:14:43 INFO]: (!) LuckPerms version: 5.1.93
[06:14:43 INFO]: (!) PlaceholderAPI version: 2.10.6
[06:14:43 INFO]: (!) Vault version: 1.7.3-b131
[06:14:43 INFO]: (!) Citizens version: 2.0.27-SNAPSHOT (build 2113)
[06:14:43 INFO]: (!) EssentialsXSpawn version: 2.18.1.23
```

**Server startup log:**

**EssentialsX config:**

### Details

**Description:**  

Can see player who use /vanish 
**Steps to reproduce:**  

Type "P" in keyboard and check player 
**Expected behavior:**  

it shouldn't be like that
**Console stack trace:**  

```

```

**Screenshots:**  

![image](https://user-images.githubusercontent.com/64282946/97929444-c8be8e80-1d9b-11eb-823f-ec30d03d1d8d.png)

**Comment by JRoy** [comment]
@Scarlet2031 can you reproduce this on spigot 1.16.4

**Comment by Chew** [comment]
or Paper 1.16.4

**Comment by LowScarlet** [comment]
> @Scarlet2031 can you reproduce this on spigot 1.16.4

I use ViaVersion for this

**Comment by LowScarlet** [comment]
A player: use /vanish
B Player: type B on keyboard
B Player: See player A on Player menu (1.16.4 Update If press "P" Key)

**Comment by benwoo1110** [comment]
> > @Scarlet2031 can you reproduce this on spigot 1.16.4
> 
> I use ViaVersion for this

what they are asking for is test with your actual server version being 1.16.4, not viaversion.

**Comment by pop4959** [comment]
The reason is because it's possible that your 1.16.3 server doesn't properly support vanished players in the player menu. If this is the case, updating to 1.16.4 should fix this.

**Comment by LowScarlet** [comment]
ok thanks I think this bug
