### ISSUE TITLE
/baltop isnt updating peoples balances 

### ISSUE THREAD

**Issue by ayoitsbrandon** [EssentialsX/Essentials#3757]
I tried eco reseting everyone but like the balances arent changing once all the players recieve money or buy stuff from shop. Please help.
![2020-11-04_11 27 15](https://user-images.githubusercontent.com/73965982/98164460-2b498480-1e99-11eb-9117-d8ab96792c28.png)
![2020-11-04_11 27 27](https://user-images.githubusercontent.com/73965982/98164464-2c7ab180-1e99-11eb-88d8-555cdf7e1b73.png)

**Comment by pop4959** [comment]
Baltop doesn't update instantly, you will need to wait a while for it to display the new numbers.

**Comment by Chew** [comment]
If you want it to update, run `/baltop force` (you need permission for this)
