### ISSUE TITLE
config: last-message-reply-recipient-timeout

### ISSUE THREAD

**Issue by Platinteufel** [EssentialsX/Essentials#376]
If last-message-reply-recipient is true, this specifies the duration, in seconds, that would need to elapse for the 
reply-recipient to update when receiving a message.
Default is 180 (3 minutes)
last-message-reply-recipient-timeout: 60

will be generated at the end of EssentialsEco and should be found after 

Changes /reply functionality. If true, /r goes to the person you messaged last, otherwise the first person that messaged you. 
If false, /r goes to the last person that messaged you.
last-message-reply-recipient: true

at Essentials (Global)

**Comment by SupaHam** [comment]
FIxed.
