### ISSUE TITLE
Allow sethome if homes limit exceeded but home with that name already set

### ISSUE THREAD

**Issue by molor** [EssentialsX/Essentials#3761]
### Feature request

Currently, if homes limit is set to 2 (for example), player can't set more than 2 homes using `/sethome`.

But **admins** still can set _home_ for this _player_ using `/sethome` _player:home_, and _player_ can't update any of their existing homes until one of them is deleted.

**Comment by pop4959** [comment]
I feel like I'm missing something here. Can admins set homes past the limit if the name is *not* "home"? I just want to clarify since you've made it a bit vague (or I don't understand) what the feature request here is.

**Comment by Laarryy** [comment]
From what I'm reading, they want players to be able to set homes already set, so like if I had /home churros and I exceeded my limit, I could `/sethome churros` again in another location and it'll simply replace the home destination without having to `/delhome churros` first

**Comment by molor** [comment]
@pop4959, Laarryy said exactly what I mean :D

**Comment by molor** [comment]
Me and 4 other players really wants this :c

**Comment by Chew** [comment]
Essentials is an open source project

**Comment by JRoy** [comment]
Changed to status to bug as players are currently unable to modify any of their homes if they're above the max home limit; Which can happen by the manual lowering of the home limit, an admin setting a home for them over their limit manually, etc.

**Comment by accLarson** [comment]
Could this feature be implemented as a toggle in the config.yml?

I prefer if a player cannot change current homes until their actual home count matches their limit defined in the config.
