### ISSUE TITLE
/hat not working on 1.12.2

### ISSUE THREAD

**Issue by FishbirdDD** [EssentialsX/Essentials#3766]
### Information

**Full output of `/ess version`:**

```
Server version: 1.12.2-R0.1-SNAPSHOT git-Spigot-79a30d7-acbc348 (MC: 1.12.2)
09.11 16:48:03 [Server] INFO EssentialsX version: 2.18.1.36
09.11 16:48:03 [Server] INFO LuckPerms version: 5.1.93
09.11 16:48:03 [Server] INFO Vault version: 1.7.3-b131
09.11 16:48:03 [Server] INFO EssentialsXProtect version: 2.18.1.36
09.11 16:48:03 [Server] INFO EssentialsXChat version: 2.18.1.36
09.11 16:48:03 [Server] INFO EssentialsXSpawn version: 2.18.1.36
09.11 16:48:03 [Server] INFO You are running a server with limited API functionality. EssentialsX will still work, but certain features may be disabled.
```

**Server startup log:**

[logs_latest.log](https://paste.gg/p/anonymous/86ddb2bdafc44589b3e0db7b6a503fc9)

**EssentialsX config:**

https://gist.github.com/FishbirdDD/ba58aaea979abcd79879af03ca2c5836

### Details

**Description:**  

/hat does not work on 1.12.2
**Steps to reproduce:**  

I put an item in my hand and typed /hat. I got an error that I needed to hold an item in my hand. This happened when holding any item in my hand; even a helmet.
**Expected behavior:**  

I expected the item to go on my head.
**Console stack trace:**  

```
n/a
```

**Screenshots:**

**Comment by pop4959** [comment]
Unable to replicate this issue. My guess is you probably have OP and so you have the `essentials.hat.prevent-type.*` permission which prevents you from using any hat. The solution to this is to set up permissions properly, or negate that permission.

Read more here: https://essinfo.xeya.me/permissions.html
