### ISSUE TITLE
EssentialsX intergration with Worldguard

### ISSUE THREAD

**Issue by J3fftw1** [EssentialsX/Essentials#3767]
This feature would allow server owners to disable some functionality from essentials

**How the feature is useful:**  

This is useful for server owners to disable for example sethome in a region, right now you have to add all types of /sethome,/esethome, /createhome, /ecreatehome. To the command blocklist.
This would also be really helpful for /tp, and all aliases for it

**Comment by benwoo1110** [comment]
I feel that this should be done either by worldguard itself or a permission plugin like luckperms with its wg-region context feature?

**Comment by pop4959** [comment]
Essentials does not plan to directly provide integrations for any specific plugins except for permissions and economy, so you will need to find a way to do this either with WorldGuard itself or via a bridging plugin as @benwoo1110 is suggesting. There is an API which plugins can use to hook into Essentials to provide the desired functionality.
