### ISSUE TITLE
Support to accept multiple simultaneous /tpa requests

### ISSUE THREAD

**Issue by Crumb5** [EssentialsX/Essentials#3769]
### Feature request

Currently the player to player teleport system only holds one pending value for a receiving player even if multiple teleport requests are made.

**Feature description:**  

The system should hold more than one pending teleport.
The`/tpaccept <PlayerName>` argument should be able to select for valid pending teleport requests from `<PlayerName>`
Subsequent uses of `/tpaccept` should iterate through pending teleports until there are no more left.

**How the feature is useful:**  

This prevents confusion to Player A who currently gets no feedback that their teleport request to Player C was overwritten by Player B

**Comment by molor** [comment]
\+ `/tpaccept *` to accept all pending requests
