### ISSUE TITLE
Add Kick warning message to AFK Plugins

### ISSUE THREAD

**Issue by Thenzyne** [EssentialsX/Essentials#3771]
### Feature request

**Feature description:**  

Add kick warning message to AFK plugins for ex: "1 minute until AFK kick" maybe add some notification sound
**How the feature is useful:**  
It can help to remind players who are not moving (AFK)

This can avoid player from being kicked out while they are only chilling in the server (not entirely AFK)

**Comment by pop4959** [comment]
Don't see the issue with this. Even if they're kicked, can they not just log back in? They should probably be aware of the AFK timeout and avoid getting kicked themselves if they need to.

**Comment by Chew** [comment]
Forgot to respond but that was exactly my methodology. If they're already "chilling" they'll be able to notice and rejoin fairly quickly.

**Comment by JRoy** [comment]
Closing for reasons above.
