### ISSUE TITLE
OP

### ISSUE THREAD

**Issue by Hellyxx** [EssentialsX/Essentials#3772]
When my friend installed the Essentials plugin, I and others couldn't do anything on the server, including placing blocks, destroying them, eating, etc. So I don't really know what to do.
But everything is fine when my friends give OP to everyone else, and it's working as normal.

**Comment by pop4959** [comment]
Sounds like you installed EssentialsX Anti Build. If you aren't going to configure it, it prevents you from doing anything on the server by default (as the name might imply). Fix it or uninstall that plugin if you don't need it.

**Comment by Hellyxx** [comment]
> Sounds like you installed EssentialsX Anti Build. If you aren't going to configure it, it prevents you from doing anything on the server by default (as the name might imply). Fix it or uninstall that plugin if you don't need it.

But how do I configure it?

**Comment by Chew** [comment]
plugins/Essentials/config.yml. Near the bottom, it's commented to help you

**Comment by BlueTree242** [comment]
> > Sounds like you installed EssentialsX Anti Build. If you aren't going to configure it, it prevents you from doing anything on the server by default (as the name might imply). Fix it or uninstall that plugin if you don't need it.
> 
> But how do I configure it?

Remove the Essentials Anti Build.
