### ISSUE TITLE
Add tab completion for players own homes to "/delhome"

### ISSUE THREAD

**Issue by Puremin0rez** [EssentialsX/Essentials#3774]
### Feature request

**Feature description:**  
I would like for `/delhome` to support the suggesting of a players own homes.
It currently doesn't support tab completion for a players own homes. (but does for the `<player>:` if you have access to others homes)
It would be great for it to support this just as wonderfully as `/home` already does.

**How the feature is useful:**  
Being able to tab complete partial home names and view a list of homes while typing would be a great quality of life feature.

**Comment by pop4959** [comment]
Confirmed as actually being a bug in the current tab completions.
