### ISSUE TITLE
Bug with essentials nick

### ISSUE THREAD

**Issue by SladeHazard** [EssentialsX/Essentials#3781]
Yeah so this is a simple bug 
server ver : 1.12.2 paper
basically when you guys added new permission for /nick it broke.
now I give my players the following permissions:
essentials.nick
essentials.nick.format
essentials.nick.color
essentials.nick.color

Player types command: /nick &ltest
it works fine.
but if player does /nick &6&l test
it says nicknames can not be alphanumeric. 
if player types /nick &6test
it works...

but now I'm having to give players this permission essentials.nick.gold
only then /nick &6&ltest
works how to fix this?!

**Comment by Octol1ttle** [comment]
Please fill out the issue template.

**Comment by SladeHazard** [comment]
it's not needed. the bug will happen I tested on a new server localhost aswell.
player can't run /nick &6&ltest
with having only these perms: essentials.nick, essentials.nick.color, essentials.nick.format

essentials ver = dev builds.
server ver = 1.12.2

**Comment by mdcfe** [comment]
The issue template is required for us to investigate the issue. Please fill it out in full.

**Comment by Chew** [comment]
`/nick &6&l test`
You can't have spaces in nicknames...

**Comment by SladeHazard** [comment]
? i made a typo here.

**Comment by SladeHazard** [comment]
https://github.com/EssentialsX/Essentials/issues/3784
