### ISSUE TITLE
baltop problem

### ISSUE THREAD

**Issue by ttt0** [EssentialsX/Essentials#3783]
Does anyone know what is the reason some of my players /baltop is also missing?

![image](https://user-images.githubusercontent.com/66686400/99876057-61129b00-2c05-11eb-894d-981ce7d1dc08.png)
![image](https://user-images.githubusercontent.com/66686400/99876060-653eb880-2c05-11eb-8839-63c07e363aba.png)

![image](https://user-images.githubusercontent.com/66686400/99876073-72f43e00-2c05-11eb-892a-814addf57ffe.png)

**Comment by pop4959** [comment]
They probably have the baltop exempt permission. Check using Luckperms verbose.

**Comment by ttt0** [comment]
I have no idea how I can do it. Can you help me :'(

**Comment by benwoo1110** [comment]
https://github.com/lucko/LuckPerms/wiki/Verbose

**Comment by pop4959** [comment]
Closing this assuming that you figured out the issue. If it's not baltop exemption and you are still having issues let us know.
