### ISSUE TITLE
Requesting Alias's for TPR

### ISSUE THREAD

**Issue by SteeltonMC** [EssentialsX/Essentials#3786]
### Feature request

**Feature description:**  

I am requesting that /TPR recognizes command alias's. Example, /Wild and /RTP are not protected with cooldowns. 

**How the feature is useful:**  

Currently, if you have TPR set up, under the Command Cooldowns, it does not recognize Commands.yml entries. This is an issue because players may /wild and /rtp with no cooldown which can be taxing on the server.

If it comes down to being an issue with Commands.yml not being compatible with EssentialsX commands, may I request additional alias's to be added in the next EssentialsX update? It was mentioned they were purposely left out to avoid conflicts, but maybe make them toggleable so users may set the alias TRUE or FALSE. 

![CommandsYML](https://user-images.githubusercontent.com/45464775/99911105-2faad580-2cc0-11eb-8493-97e6709c110c.png)
![Essentials Config](https://user-images.githubusercontent.com/45464775/99911106-30436c00-2cc0-11eb-8514-cea78d65d2a9.png)

**Comment by pop4959** [comment]
This is currently being worked on in #3744.
