### ISSUE TITLE
Issues with Essentials Chat

### ISSUE THREAD

**Issue by PixelInspector** [EssentialsX/Essentials#3787]
There seems to be an issue when I try to block players from writing in the chat with color / hex codes. 
I have tried negating the permission using LuckPerms but the issue was not solved. I negated the following:

essentials.chat.color
essentials.chat.rgb
essentials.chat.format
essentials.chat.magic

I feel like the problem might be from the recent minecraft update and from the actual Essentials plugin itself. Please comment if anyone else experienced anything similar.
Feel free to leave any suggestions if you know a way to fix this.

**Comment by pop4959** [comment]
Color permissions are not given by default. There is no need to negate them unless you gave players access in the first place.

It might be helpful if you can use LuckPerms verbose and check what permissions are being checked. You'll want to pay special attention to it when players attempt to write with color in chat.

**Comment by PixelInspector** [comment]
Oh, I was not aware of such a feature. I am going to try it and update you on it as soon as I get the chance. Thank you

**Comment by PixelInspector** [comment]
> Color permissions are not given by default. There is no need to negate them unless you gave players access in the first place.
> 
> It might be helpful if you can use LuckPerms verbose and check what permissions are being checked. You'll want to pay special attention to it when players attempt to write with color in chat.



Oh, I was not aware of such a feature. I am going to try it and update you on it as soon as I get the chance. Thank you

**Comment by PixelInspector** [comment]
![Capture](https://user-images.githubusercontent.com/49351856/100028750-84953b80-2de7-11eb-999b-bf56bd16be7f.PNG)

This is what shows when I do [/lp verbose on essentials]
As you can see whenever I type all of these permissions are checked. I have just set them to false and when I tried to write in the chat using colors it still worked. Before I negated them, they were displaying undefined .

**Comment by PixelInspector** [comment]
I found the solution. The problem was not with essentials at all. It was a different plugin that was overriding Essentials and those negations. Thank you for help.

**Comment by cwilde98** [comment]
> I found the solution. The problem was not with essentials at all. It was a different plugin that was overriding Essentials and those negations. Thank you for help.

My friend can you please share which plugin was overriding/conflicting? I am having the exact same issue.

**Comment by Evidentsinger14** [comment]
Please don’t necro issues from > 3 years ago. If you are having plugin conflicts, start removing your jars and seeing when it stops happening.

**Comment by Fxllen04** [comment]
> > I found the solution. The problem was not with essentials at all. It was a different plugin that was overriding Essentials and those negations. Thank you for help.
> 
> My friend can you please share which plugin was overriding/conflicting? I am having the exact same issue.

You can set **interactivechat.chatcolor.translate** to false for your groups who you don't want to let them have access to use color codes in chat if you are using InteractiveChat
