### ISSUE TITLE
Make real names in /list only appear when the player has a nickname

### ISSUE THREAD

**Issue by Technoguyfication** [EssentialsX/Essentials#3790]
### Feature request

**Issue:**  

When the configuration option `real-names-on-list` is enabled, real names are displayed for **all** players, even players who don't have a nickname. This takes up a lot of space to say their username twice.

![example](https://tkno.pw/2V83xiZ)

**Proposed solution:**
Just don't put the real name in parenthesis if the player doesn't have a nickname.

**Comment by JRoy** [comment]
what plugin are you using for your ranks?

**Comment by Technoguyfication** [comment]
I'm using LuckPerms

**Comment by JRoy** [comment]
could you send a copy of your Essentials config file if that's the case?

**Comment by Technoguyfication** [comment]
@JRoy Here you go, sorry for the delay! https://paste.ubuntu.com/p/xmhVmRJmBf/

**Comment by Bobcat00** [comment]
I would also like this change.

**Comment by triagonal** [comment]
I've labelled this as a bug instead of a feature request since the real names are only supposed to appear if the player has a nickname (as stated in the comment above the config option).
