### ISSUE TITLE
Disable item pickups while vanished

### ISSUE THREAD

**Issue by marzeq** [EssentialsX/Essentials#3792]
### Feature request

**Feature description:**  
Option to disable item pickups while vanished. It would be in the config file like: `pickup-items-while-vanished`.

**How the feature is useful:**  
For example: 
* *If an admin teleports to a suspicious player, and he (the admin) picks up an item from the player by accident, the suspicious player will know that someone is watching him, and might take more precautions while cheating.*

This optional feature would prevent these kinds of situations from happening.

**Comment by ram1660** [comment]
In my opinion, the vanish is really lacking of core features like this. 
This should be implemented...

**Comment by JRoy** [comment]
The way I see us adding this is an option to force players into spectator mode when in vanish, as anything else is probably grounds to just use a dedicated vanish plugin

**Comment by ram1660** [comment]
> The way I see us adding this is an option to force players into spectator mode when in vanish, as anything else is probably grounds to just use a dedicated vanish plugin

Is there a good way to store the last player's gamemode?

**Comment by marzeq** [comment]
This issue was inactive for quite some time so I'm closing it
