### ISSUE TITLE
Bug with command /more

### ISSUE THREAD

**Issue by PioMine** [EssentialsX/Essentials#3796]
I have big bug on my server with essentials.more
everything i make in my video: https://youtu.be/jyGfjP15-xs
but i wanna say it: if you get a block and make it more it get normal
but if you just build something, drop it and someone or you pick up it: your inventory get filled up with this block. 
example: you doing this glitch with 1 diamond block because you got permission to essentials.more and you have infinite diamonds! 
Please repair it

**Comment by Chew** [comment]
Missing the entire template. Please fill it out and resubmit
