### ISSUE TITLE
Issue with join messages

### ISSUE THREAD

**Issue by mrdastt** [EssentialsX/Essentials#380]
Hello, there is an ongoing issue with essentials join messages not working correctly.
When setting the messages to "none" or even left blank, on join it still shows the player join message.
There currently isn't a way to disable these messages without a third party plugin.

Would appreciate a fix, thanks!

**Comment by drtshock** [comment]
but closed? probably another plugin interfering.

**Comment by mrdastt** [comment]
Well, using ' ' doesn't work, i had to use the permissions for silent join

**Comment by SupaHam** [comment]
When `custom-join-message` is `none` that means don't change default behaviour, not actually nullify the message. Setting the message to blank will only broadcast a blank message. Currently, in order for a player to join silently, they must have the permission `essentials.silentjoin`.
