### ISSUE TITLE
When placing dirt then the dirt is placed and kept in inventory

### ISSUE THREAD

**Issue by Sv3tr1k** [EssentialsX/Essentials#3805]
When I place dirt it is actually placed but also the 1 dirt stays in inventory so basically i can duplacite dirt. This is my config:

https://pastebin.pl/view/9daac368

**Comment by Sv3tr1k** [comment]
Also my plugin list
![Uploading 4646609C-7CF5-40ED-8A30-B85BDC4B9079.jpeg…]()

**Comment by ghost** [comment]
facepalm. WHAT DOES ESSENTIALS DO HERE?

**Comment by Sv3tr1k** [comment]
Cause it is essentialsx issue. I have deleted only essentialsx and the bug was fixed.

**Comment by Chew** [comment]
1) Template is not filled out, in fact it's been completely removed.
2) Pastebin never loads for me. Can you try something like https://paste.gg?
3) If it is a bug, fill out the bug report template.
