### ISSUE TITLE
Bug with dirt

### ISSUE THREAD

**Issue by Sv3tr1k** [EssentialsX/Essentials#3806]
### Information

**Full output of `/ess version`:**

```
01.12 17:42:26 [Server] INFO CONSOLE issued server command: /ess version
01.12 17:42:26 [Server] INFO Server version: 1.16.4-R0.1-SNAPSHOT git-Paper-300 (MC: 1.16.4)
01.12 17:42:26 [Server] INFO EssentialsX version: 2.18.2.1
01.12 17:42:26 [Server] INFO LuckPerms version: 5.2.35
01.12 17:42:26 [Server] INFO PlaceholderAPI version: 2.10.9
01.12 17:42:26 [Server] INFO Vault version: 1.7.3-b131
01.12 17:42:26 [Server] INFO Citizens version: 2.0.27-SNAPSHOT (build 2186)
01.12 17:42:26 [Server] INFO Essentials_WarpGUI version: 2.2.1
01.12 17:42:26 [Server] INFO You are running unsupported plugins!

```

**Server startup log:**
https://gist.github.com/Sv3tr1k/f4ae4e048a857cebe79287dcd4d9917f

**EssentialsX config:**
https://gist.github.com/Sv3tr1k/60e0fe7184253b2848bddbc170c1f54e

### Details

**Description:**  
 When I am in survival and place block of dirt (have not found any other block that causes this bug)  then the block is placed but also stays in inventory so i can do duplication of dirt

**Steps to reproduce:**  
 I do not know. I did not change the config that much.

**Expected behavior:**  
 When block of dirt is placed it should not stay in inventory

**Screenshots:**  
![Snímka obrazovky (39)](https://user-images.githubusercontent.com/75327075/100778202-00564000-3407-11eb-827c-dfaa01f6c47e.png)
![Snímka obrazovky (40)](https://user-images.githubusercontent.com/75327075/100778207-02b89a00-3407-11eb-87d8-e6a21c2d8613.png)
![Snímka obrazovky (41)](https://user-images.githubusercontent.com/75327075/100778214-04825d80-3407-11eb-9c73-99efbf3e1adb.png)

**Comment by Sv3tr1k** [comment]
NOTE: Removing the EssentialsX plugin fixes this bug

**Comment by pop4959** [comment]
Instead of only removing EssentialsX, can you also try removing everything *except* for EssentialsX. Other plugins could still be doing something depending on whether or not the plugin is installed.

**Comment by pop4959** [comment]
Also check that you didn't run /unlimited because this could cause the "issue" (it's an intended feature).

**Comment by Sv3tr1k** [comment]
oh the /unlimited did work. Thank you!
