### ISSUE TITLE
AFK status in tablist

### ISSUE THREAD

**Issue by Kixot14** [EssentialsX/Essentials#381]
Is it possible to add feature for change nickname(with prefixes and suffixes from ColoredTags) transparency in the tablist, when player go AFK?
Transparency, like when you set 3-rd GameMode. As in this screenshot - http://prntscr.com/9rync1

**Comment by vemacs** [comment]
I don't think this is possible with Bukkit APIs. It probably requires packet manipulation with NMS/OBC/ProtocolLib.

**Comment by SupaHam** [comment]
Sadly, transparency would have to be hacked via packets, which may cause issues considering the way this is done is by telling all online players that player _x_ is in spectator mode. Changing the colour name of the player when they're AFK is easy but it could cause issues with other enabled plugins.

**Comment by SupaHam** [comment]
This feature has been implemented in [build 263](https://ci.drtshock.net/job/EssentialsX/263).
