### ISSUE TITLE
/sell hand with the same item in offhand results in error

### ISSUE THREAD

**Issue by MoshiBar** [EssentialsX/Essentials#3810]
### Information

**Full output of `/ess version`:**
```
Server version: 1.16.4-R0.1-SNAPSHOT git-Paper-313 (MC: 1.16.4)
EssentialsX version: 2.18.2.0
LuckPerms version: 5.1.93
Vault version 1.7.3-b131
EssentialsXProtect version: 2.18.2.0
EssentialsXGeoIP version: 2.18.2.0
EssentialsXChat version: 2.18.2.0
EssentialsXAntiBuild version: 2.18.2.0
EssentialsXSpawn version: 2.18.2.0
```

**Server startup log:**
[latest.log](https://paste.gg/p/anonymous/a3d9d7df7ed1447c9103d6ee83dd61bf)

**EssentialsX config:**
[config.yml.txt](https://paste.gg/p/anonymous/0dd9f4b661ea4637ad03eef6a94922c5)

### Details

**Description:**  
using /sell hand when the same type of item is in the offhand results in the following error: `Error: Trying to remove more items than are available`

**Steps to reproduce:**  
Use /sell hand on an item with the same item in the offhand

**Expected behavior:**  
Items should be sold as normal

**Comment by triagonal** [comment]
I was able to reproduce this on the following:
```
[01:43:39 INFO]: Server version: 1.16.4-R0.1-SNAPSHOT git-Paper-337 (MC: 1.16.4)
[01:43:39 INFO]: EssentialsX version: 2.19.0-dev+27-c4ca0e5
[01:43:39 INFO]: LuckPerms version: 5.2.63
[01:43:39 INFO]: Vault version: 1.7.3-b131
```

I was also able to identify another issue involving /sell with items in the offhand:

Using `/sell all` while holding sellable items in both the inventory and the offhand as per
![image](https://user-images.githubusercontent.com/10545540/102747360-3fe3cc80-43b4-11eb-8aaa-03ee550e6a56.png)
results in this message with no items being sold: 
![image](https://user-images.githubusercontent.com/10545540/102747376-4a9e6180-43b4-11eb-9540-49a819e70a3e.png)

**Comment by JRoy** [comment]
Issue appears to be bukkit's `Inventory#containsAtLeast` not including extra slots in the calculation. Will require more hackery from us if that's the case :/

**Comment by TailedPoog420** [comment]
Any ETA on when a fix for this might be released? @JRoy

**Comment by Chew** [comment]
no (whenever someone decides to fix it, really)

**Comment by Luminous-Journey** [comment]
pls fix, really irritating when you have armor on and want it deleted
