### ISSUE TITLE
custom-join-message feature not working.

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#3813]
Version: 2.18.2

The join custom message is not working, I'm getting the default "(User) joined the game" the quit custom message works fine.
Debug on join: https://gist.github.com/ImHumbug/2760c57c453d691287bcd23320b8c579
My config:
custom-join-message: "&8[&a+&8] &7{PLAYER}"
custom-quit-message: "&8[&c-&8] &7{PLAYER}"

**Comment by pleaseFixyourstuff22** [comment]
Same problem Wont take custom join msgs stays the default, please fix. Bug: confirmed - Needs fixing

**Comment by triagonal** [comment]
Cannot reproduce on the following:
```
[23:29:43 INFO]: Server version: 1.16.4-R0.1-SNAPSHOT git-Paper-337 (MC: 1.16.4)
[23:29:43 INFO]: EssentialsX version: 2.19.0-dev+29-318df64
[23:29:43 INFO]: LuckPerms version: 5.2.63
[23:29:43 INFO]: Vault version: 1.7.3-b131
[23:29:43 INFO]: EssentialsXChat version: 2.19.0-dev+29-318df64
```

Using the custom messages in the original issue:
<img width="408" alt="image" src="https://user-images.githubusercontent.com/10545540/103119160-4b8e0680-46c6-11eb-81d1-6328a552d54a.png">

Try again with only EssentialsX + Your permissions plugin + Vault installed to see if it's a plugin conflict.

**Comment by ghost** [comment]
I'm sorry, my bad, the problem was BotSentry, in order to fix it you have to go to BotSentry config and set sendjoinmessagelater to false.
