### ISSUE TITLE
Magma server but the item ID seem some wrong

### ISSUE THREAD

**Issue by martin1194** [EssentialsX/Essentials#3814]
I run my Magma server and use EssentialsX. I can't use give command to get any forge mod item. I really sure item ID is right. I hope it can be fix and i can add something in blacklist. 

### Information

**Full output of `/ess version`:**

```

```

**Server startup log:**

**EssentialsX config:**

### Details

**Description:**  

**Steps to reproduce:**  

**Expected behavior:**  

**Console stack trace:**  

```

```

**Screenshots:**

**Comment by Octol1ttle** [comment]
Do not use Mohist or Magma on your server. These server implementations include dangerous, non-standard behavior, such as altering the Bukkit permissions system and modifying EssentialsX at runtime.
EssentialsX team will not help you with these server implementations

**Comment by JRoy** [comment]
as @l1ttleO said, Essentials doesn't support modded server hybrids, it's on them to create a decent bukkit impli. We're not going to patch around them.

Also please make sure you fill out your issue template.
