### ISSUE TITLE
AntiBuild Version 2.19.0-dev+17-dda4d58

### ISSUE THREAD

**Issue by VimaMT** [EssentialsX/Essentials#3818]
I'm running paper 1.16.4, and I'm trying out this version 2.19.0-dev+17-dda4d58 of EssentialsX.

Is there any reason why AntiBuild would stop protecting my worlds with this version? Version 2.18.2.1 works fine.

**Comment by JRoy** [comment]
Could you provide a log from the new version?

**Comment by VimaMT** [comment]
[2020-12-09-3.log](https://github.com/EssentialsX/Essentials/files/5668604/2020-12-09-3.log)
Sorry ... not sure there's a lot in that log.   This is a rather bare-bones system. I would paste the config in too, but when I went back to the older version I wiped that new config out.  The Luckperms verbose function does not seem to catch it when I try setting it.

**Comment by VimaMT** [comment]
Ok ... fresh installation, everything default ... works.  Let me mess with this more. If I have issues again, I'll yell again.  I did switch subdomain names in prep to ask you to sign on if necessary. I don't know if something was caching weird on the client side, or not.

**Comment by VimaMT** [comment]
One more comment before I'm done with this.  If I restart the server with my current setup there appears to be a 5 to 10 second delay before AntiBuild becomes effective. During that time I can knock over grass and do all kinds of things. After that time is up, those items come back, and I start seeing the error messages stating I cannot interact again.  That's not an issue, but it may be a tidbit to hang onto.
