### ISSUE TITLE
Add toggleable nickname displays for commands like /ss, /msg, /baltop, /bal, /seen, etc. individually

### ISSUE THREAD

**Issue by amongus9000** [EssentialsX/Essentials#3826]
### Feature request

**Feature description:**  

Right now, you can only toggle nickname using the change-display-name config option. However, that toggles the display name for everything that displays nickname. My suggestion is to be able to toggle it for some displays but keep it for some. For example, when using /socialspy, it's messy to display their nickname because if someone types a questionable command, we still have to /realname them instead of knowing their real name right off the bat. However, while having this feature, I still want nicknames in /chat, /msg, etc.

**How the feature is useful:**  

This feature is useful because it can help de-clutter the chat for most servers. I think having to /realname 20 people just to know the top 50 in baltop is annoying.

**Comment by Bobcat00** [comment]
The Social Spy output should be configurable via the messages files, instead of being hardcoded to use displayname, as mentioned in #1995

**Comment by JRoy** [comment]
Closing in favor of #1406
