### ISSUE TITLE
Add a way to see the amount of time another player has played on the server, e.g. /playtime (player)

### ISSUE THREAD

**Issue by amongus9000** [EssentialsX/Essentials#3827]
### Feature request

**Feature description:**  

The feature I'm suggesting is a way to see how much time another player has played in total on the server, possibly with a config option that disables counting AFK time.

**How the feature is useful:**  

This feature is useful because it allows server owners to check how much a player has played without using plugins aside from Essentials. It would be very convenient to have this.

**Comment by Octol1ttle** [comment]
EssentialsX has `/whois` command which can be used to see the total playtime. (not sure if it counts AFK time, and only works when the player is online)

**Comment by SrBedrock** [comment]
Maybe a `/playtime` where players have access and show only online time and no other information.

**Comment by Konpaku-LVX** [comment]
>possibly with a config option that disables counting AFK time.

 any chance to come back to this possibility?

**Comment by Konpaku-LVX** [comment]
as in /playtime = total playtime minus all time spent in afk mode?

Would be a great way to see which players are playing the most
