### ISSUE TITLE
/nick error

### ISSUE THREAD

**Issue by DaggerDagz** [EssentialsX/Essentials#383]
I'm trying to nickname myself "&cDagz" and it gives me the error "Error: Nicknames can only have their colors changed." I'm all out of solutions to this and I would rather not have to install a Nickname plugin to fix this. I've checked the config file as well and there seems to be nothing there. Please help!

**Comment by SupaHam** [comment]
[Please update to the latest EssentialsX version](https://ci.drtshock.net/job/EssentialsX/).
