### ISSUE TITLE
EssentialsSpawn - Option to respawn at bed, otherwise use set spawn location.

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#3836]
### Feature request

**Feature description:**  
Expand EssentialsSpawn to respawn at the set spawn location if players don't have a bed or respawn anchor set.

**How the feature is useful:**  
If you enable respawn-at-home & respawn-at-anchor and you have neither a bed set or an anchor, Essentials tries to use a random ``/sethome`` location instead. If you have numerous home locations set, it seems to pick one at random and outputs ``You have no home bed or charged respawn anchor, or it was obstructed``. Likewise, it seems to not care what world the player died in.

I would like Essentials to only check for beds and respawn anchors, otherwise use the set spawn location for the group.

```
# What priority should we use for handling respawns?
# Set this to none, if you want vanilla respawning behaviour.
# Set this to lowest, if you want Multiverse to handle the respawning.
# Set this to high, if you want EssentialsSpawn to handle the respawning.
# Set this to highest, if you want to force EssentialsSpawn to handle the respawning.
respawn-listener-priority: high

# What priority should we use for handling spawning on joining the server?
# See respawn-listener-priority for possible values.
# Note: changing this may impact or break spawn-on-join functionality.
spawn-join-listener-priority: high

# When users die, should they respawn at their first home or bed, instead of the spawnpoint?
respawn-at-home: true

# When users die, should EssentialsSpawn respect users' respawn anchors?
respawn-at-anchor: true
```

I have the default spawn set to my actual spawn location.
```
spawns: 
  default: 
    world: spawn
    x: 9.5
    y: 58.0
    z: 0.5
    yaw: -269.9234
    pitch: 13.349924
```
    
---
    
Secondarily, is it possible to override the vanilla minecraft message ``You have no home bed or charged respawn anchor, or it was obstructed`` when using both options so it doesn't occur when teleporting players to spawn if they don't have a home set?

**Comment by JRoy** [comment]
I believe this was added in e2c6170ebae0d179e2a9f0bee9ab0749f72a6289, let me know if not.

**Comment by mibby** [comment]
Thanks @JRoy, this works great. You forgot to add it to the default config.yml resource though.

Is there any way to disable this message from appearing when you die and _don't_ have a home bed or respawn anchor? I just want to silently teleport players to spawn if those aren't present. The message only occurs when special respawn condition settings are enabled. When you _don't_ use anchors / bed home and just force players back to spawn, there is no message on death.

![link2](https://i.imgur.com/p1GfwWR.png)

```
# What priority should we use for handling respawns?
# Set this to none, if you want vanilla respawning behaviour.
# Set this to lowest, if you want Multiverse to handle the respawning.
# Set this to high, if you want EssentialsSpawn to handle the respawning.
# Set this to highest, if you want to force EssentialsSpawn to handle the respawning.
respawn-listener-priority: high

# What priority should we use for handling spawning on joining the server?
# See respawn-listener-priority for possible values.
# Note: changing this may impact or break spawn-on-join functionality.
spawn-join-listener-priority: high

# When users die, should they respawn at their first home or bed, instead of the spawnpoint?
respawn-at-home: false

# When users die, should EssentialsSpawn respect users' respawn anchors?
respawn-at-anchor: true

respawn-at-home-bed: true
```
