### ISSUE TITLE
EssentialsX random teleportation bug

### ISSUE THREAD

**Issue by ItsCrazyFrog** [EssentialsX/Essentials#3840]
### Information

**Full output of `/ess version`:**

```
Server version: 1.8.8-R0.2-SNAPSHOT Elapsed (MC: 1.8.8)
EssentialsX version: 2.17.2.0
LuckPerms version: 5.1.26
PlaceholderAPI version: 2.10.6
Vault version: 1.7.2-b107
EssentialsXChat version: 2.17.2.0
EssentialsXProtect version: 2.17.2.0
EssentialsXSpawn version: 2.17.2.0
```

**Server startup log:**
 https://gist.github.com/ItsCrazyFrog/fe4d513b5f4c8442bf0cb8ef5dd91f04

**EssentialsX config:**
 https://gist.github.com/ItsCrazyFrog/1d260edecfc624dea040809d383bc0a4

### Details

**Description:**  
 Basically every now and then a random tp starts. Without triggering anything, it doesn't even output a error. I tried with latest version and have same bug

**Steps to reproduce:**  
Random players type /warp somename and teleport to warp and when move they teleport in home

**Expected behavior:**  

**Console stack trace:**  

```
none
```

**Screenshots:**  
I see old report and video: https://www.youtube.com/watch?v=iBwBN_HkeA4
same in my server

**Comment by JRoy** [comment]
You're thousands of versions out of date, please update to the latest version at [essentialsx.net](https://essentialsx.net/downloads.html)

**Comment by ItsCrazyFrog** [comment]
I tried with latest EssentialsX version and have same bug......

**Comment by pop4959** [comment]
You also didn't fill out the template completely, as it's missing important information.

Make sure to also use a supported server software (e.g. Spigot, Paper) when testing.

**Comment by ItsCrazyFrog** [comment]
I user paper fork

**Comment by pop4959** [comment]
> I user paper fork

You will need to test without using a fork before creating an issue, to ensure that this is not a bug in the fork.

**Comment by ItsCrazyFrog** [comment]
I tested with paper 1.8.8 also ....

**Comment by ItsCrazyFrog** [comment]
Hello! Now i updated with latest essentials and paper 1.8.8 and have same bug

**Comment by ItsCrazyFrog** [comment]
@JRoy @pop4959

**Comment by JRoy** [comment]
Please don't ping us, fill out a new issue with the template reflecting your updated tests.
