### ISSUE TITLE
[enhancement] Add a <Reason> for Ess Mute.

### ISSUE THREAD

**Issue by Done84** [EssentialsX/Essentials#385]
Would be nice to be able to set a "Reason" after the amount of time of a /Mute.
/emute PlayeName 5min Spamming.

**Comment by AntZaro** [comment]
I second this. And reasons for jails too. Sometimes you jail someone and even you forget why. Though these reasons would have to appear in /seen and /whois which I suppose is a lot of work :/

**Comment by mdcfe** [comment]
This is implemented by #1557 - I'll close this when merged.

**Comment by mdcfe** [comment]
This feature is now available in [builds 711 and above](https://ci.ender.zone/job/EssentialsX).
