### ISSUE TITLE
Barrier is not a safe block for warps. Players appear under it.

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#3851]
### Information

**Full output of `/ess version`:**
```
[22:01:01] [Server thread/INFO]: Server version: 1.16.4-R0.1-SNAPSHOT git-Paper-"d5f3458" (MC: 1.16.4)
[22:01:01] [Server thread/INFO]: EssentialsX version: 2.19.0-dev+24-f320705
[22:01:01] [Server thread/INFO]: PlaceholderAPI version: 2.10.10-DEV-118
[22:01:01] [Server thread/INFO]: LuckPerms version: 5.2.61
[22:01:01] [Server thread/INFO]: Vault version: 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[22:01:01] [Server thread/INFO]: Citizens version: 2.0.27-SNAPSHOT (build 2197)
[22:01:01] [Server thread/INFO]: EssentialsXAntiBuild version: 2.19.0-dev+24-f320705
[22:01:01] [Server thread/INFO]: EssentialsXSpawn version: 2.19.0-dev+24-f320705
```

**Server startup log:**
Not relevant.

**EssentialsX config:**
```
# If the teleport destination is unsafe, should players be teleported to the nearest safe location?
# If this is set to true, Essentials will attempt to teleport players close to the intended destination.
# If this is set to false, attempted teleports to unsafe locations will be cancelled with a warning.
teleport-safety: true

# This forcefully disables teleport safety checks without a warning if attempting to teleport to unsafe locations.
# teleport-safety and this option need to be set to true to force teleportation to dangerous locations.
force-disable-teleport-safety: false

# If a player is teleporting to an unsafe location in creative, adventure, or god mode; they will not be teleported to a
# safe location. If you'd like players to be teleported to a safe location all of the time, set this option to true.
force-safe-teleport-location: false

# Consider water blocks as "safe," therefore allowing players to teleport
# using commands such as /home or /spawn to a location that is occupied
# by water blocks
is-water-safe: true

# Whether to make all teleportations go to the center of the block; where the x and z coordinates decimal become .5
teleport-to-center: true
```

### Details

**Description:**  
When you have a warp on top of barriers, Essentials doesn't seem to think it's a safe location and spawns players inside the barrier instead of on top.

**Steps to reproduce:**  
Create a new warp location on top of barriers.

B = Barrier Block
S = Sea Lantern
W = Warp Location

W
B
S

Try to use the warp as a member. Get put in-between B & S instead of on top of B.

**Expected behavior:**  
Spawning above barriers. Works for OPs, not for normal members.

**Comment by pop4959** [comment]
Essentials safe teleportation currently doesn't allow you to teleport onto non-opaque blocks. I've looked into this before and that's not a bug, it's just how it works currently, as most of the time you don't want to be teleported onto these types of blocks.

That being said, this has been requested several times already so maybe there is some reason to make an exception to that rule. Or perhaps add a whitelist or something so that people can explicitly allow teleporting onto certain blocks that are otherwise not considered "safe".
