### ISSUE TITLE
Ability to add attributes to items in kits

### ISSUE THREAD

**Issue by olivercool103** [EssentialsX/Essentials#3854]
I want to be able to modify for example the attack_damage attribute and save that item in a kit. As of now the attributes do not save over and I would love this to be a feature!

**Comment by triagonal** [comment]
Kits do already have the ability to accept vanilla NBT, which can be used to apply attributes. The `/createkit` command does not currently have the functionality to read this data, so it must be done manually. The format for using NBT in Essentials kits is as follows:

`- <itemname> <amount> {nbt...}`

Note that vanilla NBT is incompatible with Essentials meta, so essentials tags like `name` and `<enchantment>:<level>` cannot be used simultaneously with NBT on a single item.

**Comment by olivercool103** [comment]
Oh thanks!
