### ISSUE TITLE
/alts command

### ISSUE THREAD

**Issue by akdukaan** [EssentialsX/Essentials#3864]
### Feature request

**Feature description:**  
I'd like a new command /alts <player> which shows you all players who have connected from the player's IP.

**How the feature is useful:**  
As it is now, to see other accounts that have connected from the same IP as another player, I need to first use /seen on the player to get the player's IP, then /seen on the IP to get all players who have connected from that IP. I use this method often and would prefer if this could be shortened to just 1 command. I would like a command that allows players to more easily see which players have connected from the same IP as a certain player. For example, I would use the command /alts DrBot and it would return all players who have connected with the same IP as the player DrBot.

EDIT: 
Alternatively, I think it could make sense for /seen \<player> to also show the other accounts which connected from that player's IP.

**Comment by JRoy** [comment]
/seen \<ip-address\> is the command you're looking for. It will show you all users whos last-known ip was that one.

**Comment by JRoy** [comment]
Realized the OP was talking about a convenience command. Will reopen this as low-priority.

For contributors:
This should probably be added as a label to the seen command that uses the very same seenIp method
