### ISSUE TITLE
Staff on server not losing items on death

### ISSUE THREAD

**Issue by terminator96NL** [EssentialsX/Essentials#3869]
i dont know how to disable keep inventory on death for staff members while in the server itself keepinventory is off

**Comment by Chew** [comment]
They probably have one or both:
`essentials.keepxp`
`essentials.keepinv`

Negate these or don't grant them to begin with

**Comment by terminator96NL** [comment]
for some reason it cant find the whole permission in group manager within the owner group

This permission node doesn't match any node.
 But might match node: *

**Comment by Chew** [comment]
You shouldn't give anyone `*`, as this causes permission issues like this. Give users what they need. Also, not sure if GroupManager can even negate permissions. Maybe check out [LuckPerms](https://luckperms.net)?

**Comment by terminator96NL** [comment]
is that easier than groupmanager?

**Comment by JRoy** [comment]
Yes, and supported
