### ISSUE TITLE
Issue with EssentialsEconomy and KitMaster plugin

### ISSUE THREAD

**Issue by Kixot14** [EssentialsX/Essentials#387]
In KitMaster plugin (http://www.curse.com/bukkit-plugins/minecraft/kitmaster#t1:description) you can set cost of kits, and cash, which that kit give to you when you take a kit. But with Essentials economy it's don't work! Before essentials i used iConomy plugin and and everything was fine...

EssX: b251

**Comment by drtshock** [comment]
I don't remember there ever being costs for kits. You could do a cost for command if you want. But currently, there's no cost feature.

**Comment by Kixot14** [comment]
I talking about cost in the KitMaster plugin!
http://www.curse.com/bukkit-plugins/minecraft/kitmaster#t1:description
