### ISSUE TITLE
Beds don't do player damage when tnt-explosion is disabled

### ISSUE THREAD

**Issue by DatSpace** [EssentialsX/Essentials#3872]
### Information

**Full output of `/ess version`:**

```
>.... [13:33:25 INFO]: Server version: 1.16.4-R0.1-SNAPSHOT git-Paper-345 (MC: 1.16.4)
>.... [13:33:25 INFO]: EssentialsX version: 2.18.2.0
>.... [13:33:25 INFO]: LuckPerms version: 5.2.35
>.... [13:33:25 INFO]: PlaceholderAPI version: 2.10.10-DEV-111
>.... [13:33:25 INFO]: Vault version: 1.7.3-b131
>.... [13:33:25 INFO]: EssentialsXProtect version: 2.18.2.0
>.... [13:33:25 INFO]: EssentialsXSpawn version: 2.18.2.0
>.... [13:33:25 INFO]: Citizens version: 2.0.27-SNAPSHOT (build 2190)
>.... [13:33:25 INFO]: Towny version: 0.96.5.7
```

**Server startup log:**

https://gist.github.com/DatSpace/97f6545c94b7503f285d6528c8936f32

**EssentialsX config:**

https://gist.github.com/DatSpace/1cc29b1526e38e0991e9b7c86ea5ed75

### Details

**Description:**  

Beds in nether do not give player damage, even though they break blocks etc.

**Steps to reproduce:**  

Simply set tnt-explosion: true in the config. You can have everything else to false, it doesnt matter. Then go to nether in survival mode and try to sleep. Everything will break, but player takes 0 damage.

**Expected behavior:**  

I expected the player to take explosive damage

**Console stack trace:**  

```

```

**Screenshots:**

**Comment by triagonal** [comment]
Confirmed on:
```
[08:43:34 INFO]: Server version: 1.16.4-R0.1-SNAPSHOT git-Paper-337 (MC: 1.16.4)
[08:43:34 INFO]: EssentialsX version: 2.19.0-dev+29-318df64
[08:43:34 INFO]: LuckPerms version: 5.2.63
[08:43:34 INFO]: Vault version: 1.7.3-b131
[08:43:34 INFO]: EssentialsXProtect version: 2.19.0-dev+29-318df64
```

Config (default except for `protect.prevent.tnt-explosion` to true): https://gist.github.com/triagonal/d1cc2d7db072dda2e5f5fd682973ba7e
