### ISSUE TITLE
Anvil GUI for /nickname

### ISSUE THREAD

**Issue by HexedHero** [EssentialsX/Essentials#3873]
### Feature request

**Feature description:**  
Add an anvil GUI with /nickname - Maybe being /nickname gui or having a config setting.

**How the feature is useful:**  
Just a nice QOL feature that will help newer players to the game having to try nicknames command over and over again to see if their formats work, especially now with Hex colors it's a big mess with an anvil GUI the player could see the result of their nickname before actually accepting it.

**Comment by pop4959** [comment]
Last I checked anvils have a maximum character count of 35, which is quite low when trying to rename items with hex colors. Unless there is a way around this I don't think this is a feasible addition in the current minecraft release.

**Comment by JRoy** [comment]
As mentioned by pop, there is a client-imposed limit on the character count of anvils. Additionally, nothing else on Essentials uses this and it really isn't a good fit for the plugin. Another plugin can hook into essentials (either by using our FormatUtil and User APIs directly or just using the raw nick command) to do the same thing, albeit, with a limited character count.
