### ISSUE TITLE
/seen causing lag spikes evertime its used

### ISSUE THREAD

**Issue by VoxaDub** [EssentialsX/Essentials#388]
So whenever any of my players use /seen to check any other player or what not it causes a 2~5 second lag spike. Idk if it has to do with having a lot of people who have joined the server like 100k+ or so. Is there anyway to prevent/fix this other than taking away the perm?

**Comment by EvilOlaf** [comment]
Did you check your IO activity while doing this command?

**Comment by VoxaDub** [comment]
How do I do this?

**Comment by vemacs** [comment]
https://github.com/drtshock/Essentials/commit/5968a6bc2750c572f0dc30e2998edba9b40c16f2

**Comment by EvilOlaf** [comment]
Confirmed.
Thanks for looking into @vemacs 
:+1:
