### ISSUE TITLE
The ability for /spawn to adhere to or have an option like world-teleport-permissions

### ISSUE THREAD

**Issue by ZombieZMB** [EssentialsX/Essentials#3888]
### Feature request

**Feature description:**  

Have /spawn teleporting to have an option that will prevent people from teleporting from one world to another (eg. from the nether to the overworld) without the proper permission from essentials.worlds.(worldname) . Similar to how world-teleport-permissions or world-home-permissions do the same for /world, /tp[a|o][here|all], /back and /home.

**How the feature is useful:**  

 This would be useful to me as a server owner so that on my server I can let people teleport as they wish in a world but not be able to hop between worlds without using the different worlds respective portals and it helps deliver a consistent experience for users. Both teleporting with /world, /tp[a|o][here|all], /back and /home have options for it, so I don't see why /spawn shouldn't either.

**Comment by JRoy** [comment]
This can be accomplished by using the LuckPerms world context on the `essentials.spawn` permission. It doesn't make sense for the spawn command (which is a single location) to adhere to a per-world system.
