### ISSUE TITLE
Every time I run a command nothing happens and it gives me this error.

### ISSUE THREAD

**Issue by Teoxex** [EssentialsX/Essentials#3890]
Hi everyone, I have a problem with EssentialX: every time I run a command it gives me this error and nothing is written in chat on Minecraft.

[https://gist.github.com/Teoxex/ffaf67b2e2f72018ab8deeb6c9d517a8](https://gist.github.com/Teoxex/ffaf67b2e2f72018ab8deeb6c9d517a8)

Can anyone help me?

**Comment by Octol1ttle** [comment]
Please show us the output of `/ess version`

**Comment by pop4959** [comment]
I can already tell from your stack trace that you are not running a supported server software.

EssentialsX only supports Bukkit (CraftBukkit, Spigot, Paper) and Glowstone servers.
