### ISSUE TITLE
Shout triggering despite not having EssentialsX-Chat installed

### ISSUE THREAD

**Issue by Brandin** [EssentialsX/Essentials#3896]
### Information

**Full output of `/ess version`:**
```
[19:42:51 INFO]: Server version: 1.16.4-R0.1-SNAPSHOT git-Paper-318 (MC: 1.16.4)
[19:42:51 INFO]: EssentialsX version: 2.18.2.1
[19:42:51 INFO]: LuckPerms version: 5.2.35
[19:42:51 INFO]: Vault version: 1.7.3-b131
[19:42:51 INFO]: EssentialsXChat version: 2.18.2.1
[19:42:51 INFO]: EssentialsXSpawn version: 2.18.2.1
```

**Server startup log:**
https://gist.github.com/brandinarsenault/556ec3e4c0f583575d43f6701c167a8d

**EssentialsX config:**
https://gist.github.com/brandinarsenault/f78dcdb1e4bcb3deb631ddec3955e693

### Details

**Description:**  
Despite not having EssentialsX Chat installed and using another chat plugin, using the `!` prefix triggers the EssentialsX `You are not authorized to shout` language which means it is causing it to go through EssentialsX which it should not.
https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/resources/messages_en.properties#L541

**Steps to reproduce:**  
1. Install EssentialsX
2. On a non-OP'd user try to use `!` with a message, eg. `!test`
3. It should return the permission denied error

**Expected behavior:**  
If EssentialsX Chat is not installed, the shouting mechanism should not be impacted since these are sub-settings of the Chat Module

**Screenshots:**  
https://i.imgur.com/y8bzm8g.png

**Comment by JRoy** [comment]
I'm seeing EssentialsChat in your startup log and in the output of your `/ess version` command?

**Comment by Brandin** [comment]
I was almost certain I removed it...apparently, my eyes aren't working today. Thank you for noticing this!

**Comment by JRoy** [comment]
😂 all good
