### ISSUE TITLE
Add player's UUID to /seen output.

### ISSUE THREAD

**Issue by codebycam** [EssentialsX/Essentials#3897]
### Feature request

**Feature description:**  

As per title, add the player's UUID to the output when using `/seen`. I'm unsure what chat functionality EssentialsX currently has, however having it clickable (to copy) would be ideal.
https://i.imgur.com/yNDAOHs.png

**How the feature is useful:**  

There's many cases where I've needed to quickly grab a player's UUID but have to rely on an alternative method. If the name and (with permission) the IP is being shown, I don't see the reason their UUID shouldn't be. 

Cheers! 🥳

**Comment by Bobcat00** [comment]
You should also output the getFirstPlayed() and getLastPlayed() date/time values.

I have a [plugin](https://github.com/Bobcat00/BetterSeen/blob/master/src/main/java/com/bobcat00/betterseen/CommandSeen.java) which outputs the UUID/first/last times as part of the /seen command. It's a big improvement, and my players like the additional timestamps.
