### ISSUE TITLE
Grab server full message from spigot.yml

### ISSUE THREAD

**Issue by JasonHorkles** [EssentialsX/Essentials#3898]
### Feature request

**Feature description:**  

Currently the server full message [cannot be as easily changed](https://github.com/EssentialsX/Essentials/blob/01987a03744f7bbe5b0c15af71d48f65ba230ace/Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java#L475) without needing a language file, regardless of changing it in spigot.yml. What the plugin should do is grab the message from spigot.yml first, and if the file/key is null, it can use the `Server full` locale message as a fallback (for compatibility with CraftBukkit servers)

**How the feature is useful:**  

This would reduce confusion on why the spigot.yml's server full message isn't working

**Comment by JRoy** [comment]
Closed with #3899 

Disable `use-custom-server-full-message` to use bukkit's default message
