### ISSUE TITLE
Sell and Buy signs improvement.

### ISSUE THREAD

**Issue by zRiaz** [EssentialsX/Essentials#39]
I think there should be a option in the config to enable this:
http://gyazo.com/f1f148c78c73198847a65857d3eff72a
http://gyazo.com/a5516b54d64f69076f576b72f5f8c08c

Basically displaying the money you get or loose from usage of the Essentials Signs gets displayed in the middle of the screen like shown above.

Why? Because selling a ton of stuff could spam your chat  so much that you wont catch much of whats going on there when buying a lot of stuff/selling a lot of stuff.

I think these messages displayed on the screen could be configurable, and editable to add color coding and rewrite what will be displayed (probs in the lang file.)

**Comment by drtshock** [comment]
So in titles? It sucks because there isn't API for this in spigot yet :(

**Comment by zRiaz** [comment]
Yea in titles I guess it would be, oh but wouldnt it be able to use another API to do this though? (As Ive seen it be done a lot around servers)

**Comment by minecrafter** [comment]
Looks like named items and item frames. As for the action bar, like @drtshock said, there's no Spigot API interface to send them (you have to use either reflection or link against NMS, both inelegant solutions).

**Comment by zRiaz** [comment]
I was not talking about the item frames.. But yea..

**Comment by pop4959** [comment]
Closing this since in 2020, there is still not a consistent API for doing this on all servers. Adding title bars to various parts of the plugin in general should probably be better discussed in #2391.
