### ISSUE TITLE
Homes Placeholder shows minimum 1 home

### ISSUE THREAD

**Issue by JustJP2K** [EssentialsX/Essentials#3908]
if you use %essentials_homes_set%/%essentials_homes_max%
To display the amount of homes you have set vs the amount you have it will always display 0/1 even if you have 0 homes.

example: 
sethome.multiple.default:
    default: 0
sethome.multiple.extra:
    extra: 2

then it display for the default one 0/1 which is incorrect, it should say 0/0
it displays it correctly for extra 0/2.

**Comment by Octol1ttle** [comment]
Placeholders for PlaceholderAPI are not made nor maintained by the EssentialsX team.

**Comment by JustJP2K** [comment]
> 
> 
> Placeholders for PlaceholderAPI are not made nor maintained by the EssentialsX team.

who maintains them? so i could ask for support there

**Comment by Octol1ttle** [comment]
It looks like they are maintained by PlaceholderAPI team. Try opening an issue [here](https://github.com/PlaceholderAPI/Essentials-Expansion)

**Comment by JustJP2K** [comment]
> 
> 
> It looks like they are maintained by PlaceholderAPI team. Try opening an issue [here](https://github.com/PlaceholderAPI/Essentials-Expansion)

thanks
