### ISSUE TITLE
Jail time

### ISSUE THREAD

**Issue by 100petr** [EssentialsX/Essentials#3916]
### Information

**Full output of `/ess version`:**

```
[19:19:26 INFO]: CONSOLE issued server command: /ess version
[19:19:26 INFO]: Server version: 1.16.4-R0.1-SNAPSHOT git-Paper-404 (MC: 1.16.4)
[19:19:26 INFO]: EssentialsX version: 2.19.0-dev+51-e287600
[19:19:26 INFO]: Vault is not installed. Chat and permissions may not work.
```

**Server startup log:**

https://gist.github.com/100petr/426514d68ed04b899beb11ea8825056a

**EssentialsX config:**

https://gist.github.com/100petr/bae06e92cee474caa6387c59cf88f728

### Details

**Description:**  

If I jail a player for 1 hour, he get a jail of more than 51 years
**Steps to reproduce:**  

Create jail 
Jail a player for 1h
Type /whois player
see Jail
(it requires jail-online-time: true)
**Expected behavior:**  

jail-time will be correct
**Console stack trace:**  

```
N/A
```

**Screenshots:**  

![image](https://user-images.githubusercontent.com/29830635/104222450-99369d00-5442-11eb-8619-823bf4a09d1d.png)
![image](https://user-images.githubusercontent.com/29830635/104222469-a18ed800-5442-11eb-8dbc-99133fa7edc2.png)

**Comment by 100petr** [comment]
what helper wrote me so maybe it works properly and maybe it's just a visual-bug

**Comment by JRoy** [comment]
Yeah it's a visual bug 😄 I'll get a fix for it out soon.
