### ISSUE TITLE
Virtual inventory signs

### ISSUE THREAD

**Issue by ArtelGG** [EssentialsX/Essentials#3919]
### Feature request

**Feature description:**  

Implement virtual inventory commands into signs.

**How the feature is useful:**  

I've always found the sign implementations within Essentials to be extremely useful. I believe implementing the rest of these virtual inventories into signs would be beneficial to users of Essentials who work with said signs.

- [X] Disposal
- [x] Workbench
- [x] Anvil
- [x] Cartography Table
- [x] Loom
- [x] Grindstone
- [x] Smithing Table

**Comment by imDaniX** [comment]
I see a reason to add anvils - it won't break - but what the purpose of other blocks to be implemented this way? I mean, it's possible to just... place a corresponding block.

**Comment by Chew** [comment]
All of these can and should be implemented with a command sign plugin. They're just running their respective command.

**Comment by JRoy** [comment]
The use case for signs in my eyes is so you can restrict the space in which these functions can be run. Giving a command allows the user to run the command anywhere which may not be what server users want.
