### ISSUE TITLE
bPermissions doesn't show up as an unsupported plugin in /ess version

### ISSUE THREAD

**Issue by alau740** [EssentialsX/Essentials#3920]
### Information

**Full output of `/ess version`:**

```
[11:07:31 INFO]: Server version: 1.16.4-R0.1-SNAPSHOT git-Paper-412 (MC: 1.16.4)
[11:07:31 INFO]: EssentialsX version: 2.19.0-dev+51-e287600
[11:07:31 INFO]: bPermissions version: 2.12.3
[11:07:31 INFO]: Vault is not installed. Chat and permissions may not work.
```

**Server startup log:**

https://gist.github.com/alau740/a59210ae37b1f98fd8a320370a63c173

**EssentialsX config:**

https://gist.github.com/alau740/7327c96a02a4f20404d3aeffe8f484bb

### Details

**Description:**  

The bPermissions plugin shows up in green as a supported plugin in `/ess ver` when it actually isn't (the last update to it was in 2019 and it is classed as unsupported in the moss discord).

**Steps to reproduce:**  

1. Install EssentialsX and bPermissions into a server
2. Op yourself through the console.
3. Run the `/ess ver` command.

**Expected behavior:**  

The bPermissions plugin should appear in `/ess ver` as an unsupported plugin (purple) and a message should also be displayed saying that the server has unsupported plugins.

**Console stack trace:**  

```
n/a
```

**Screenshots:**  

<img width="326" alt="bperms" src="https://user-images.githubusercontent.com/77434904/104583683-54d11a00-5659-11eb-8cbc-8c1bbe4fde74.PNG">

**Comment by triagonal** [comment]
Confirmed:
https://github.com/EssentialsX/Essentials/blob/e287600c34d832f95d0d3e6c48f0dd2ab9b79e9e/Essentials/src/main/java/com/earth2me/essentials/commands/Commandessentials.java#L65-L69
