### ISSUE TITLE
Player lookup is not correctly working, wrong uuids in usermap.csv

### ISSUE THREAD

**Issue by DahunDev** [EssentialsX/Essentials#3929]
```

```

**Server startup log:**

https://pastebin.com/z6SuXFix

https://pastebin.com/AcR6Lg4Z : Seems associated with this problem.

**EssentialsX config:**

https://gist.github.com/mckite/cf672d9611561e80a7977adeaa571a44

### Details

**Description:**  

![image](https://user-images.githubusercontent.com/17083624/104988632-36af4500-59de-11eb-8c4e-f616d64b9336.png)
![image](https://user-images.githubusercontent.com/17083624/104989617-75de9580-59e0-11eb-8404-bdd20278c956.png)

I don't know how to cause it, but after someday, some player's UUID in usermap,csv is not correct and
/seen <player> is not working correctly.

When using /seen <offlineplayer> or /balance <offlineplayer>

**Steps to reproduce:**  

I don't know how to cause it, but after someday, some player's UUID in usermap,csv is not correct and
/seen <player> is not working correctly.

When using /seen <offlineplayer> or /balance <offlineplayer>
<offlineplayer> : The player that at least joined the server more than 1 time. ,
It should correct amount of money(instead of default balance) and show the correct last seen date and time instead of shows "that layer had never joined the server"

**Expected behavior:**  

/seen and /balance command should work correctly.

correct uuid should be in usermap.csv and updated.

<offlineplayer> : The player that at least joined the server more than 1 time. ,
When using /seen <offlineplayer> or /balance <offlineplayer>

It should correct amount of money(instead of default balance) and show correct last seen date and time instead of shows "that layer had never joined the server"

**Console stack trace:**  

```

```

**Screenshots:**  

![image](https://user-images.githubusercontent.com/17083624/104989610-71b27800-59e0-11eb-96ef-36dd820edfc6.png)

**Comment by pop4959** [comment]
The UUIDs shown in your link are offline mode ones, which means your server is in offline mode. If you set your server to online mode the UUIDs may be corrected, although you might just want to delete the usermap to avoid having mixed types.

**Comment by DahunDev** [comment]
> The UUIDs shown in your link are offline mode ones, which means your server is in offline mode. If you set your server to online mode the UUIDs may be corrected, although you might just want to delete the usermap to avoid having mixed types.

No, server is online mode, and some uuid is correct while some uuid is not cottect.

**Comment by DahunDev** [comment]
> The UUIDs shown in your link are offline mode ones, which means your server is in offline mode. If you set your server to online mode the UUIDs may be corrected, although you might just want to delete the usermap to avoid having mixed types.

Might associated with SpleefX, so I also reported this bug to that plugin author.
