### ISSUE TITLE
command /time don't work!

### ISSUE THREAD

**Issue by Kixot14** [EssentialsX/Essentials#393]
Another broken permission...
essentials.time must give access to command /time (for checking the time).
But it work only if players have essentials.time + essentials.time.set.

**Comment by SupaHam** [comment]
What is the exact command being used and what essentials version are you on?

**Comment by Kixot14** [comment]
EssX build 251.
command /time show time only if you have essentials.time + essentials.time.set perms.

**Comment by SupaHam** [comment]
Please update to [build 265](https://ci.drtshock.net/job/EssentialsX/) for a fix.
