### ISSUE TITLE
Command works regardless of perms

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#3930]
### Information

**Full output of `/ess version`:**

![image](https://user-images.githubusercontent.com/77670907/105025051-c4933a80-5a87-11eb-9d75-8d03651cb64e.png)

[config.txt](https://github.com/EssentialsX/Essentials/files/5835466/config.txt)

**EssentialsX config:**

### Details

**Description:**  
I can see perms in /help that I'm not supposed to. Not only the plugin Angelchest, but many others
I don't have OP or *

**Steps to reproduce:**  
typing /help

**Expected behavior:**  
Commands that I don't have no perms for not to show

**Screenshots:**  

![image](https://user-images.githubusercontent.com/77670907/105025120-dc6abe80-5a87-11eb-91b2-9a5f8aa8194c.png)
![image](https://user-images.githubusercontent.com/77670907/105025204-002e0480-5a88-11eb-81c9-1bb8577ca115.png)

**Comment by imDaniX** [comment]
At the very least you have the `angelchest.use` permission, which allows you to use the `/aclist` command, so the plugin appears in the help list.

**Comment by ghost** [comment]
> At the very least you have the `angelchest.use` permission, which allows you to use the `/aclist` command, so the plugin appears in the help list.

That's ridiculous though, I disabled its help in LuckPerms, it should not show no matter what if the essentials.help.angelchest.* Is set to False

**Comment by mdcfe** [comment]
@fabmm This is intended. As stated in the Essentials wiki's [Help Files tutorial](https://wiki.mc-ess.net/wiki/Help_Files#Automatic_1):

> In this mode Essentials will loop through all available plugin information and build a customised /help list, of just commands it is certain players can use.
> [...]
> If a plugin **does not provide the appropriate permissions node in its plugin.yml**, the commands listed within will be ignored. You can manually add plugins to this list by giving the group access to a special permission.

If a plugin registers permissions for commands in `plugin.yml`, those permissions alone are checked to determine whether a command should show up in the help menu. `essentials.help.<pluginname>` permissions are only used to **add** commands that do not have permissions defined in `plugin.yml`, and does **not** remove commands that already have permissions.
