### ISSUE TITLE
Fly on Spawn

### ISSUE THREAD

**Issue by Bobdibildur123** [EssentialsX/Essentials#3932]
Whenever an op joins flight is on for the op This is extremely annoying having to turn it off every time u log. Is there a way to fix this please

**Comment by imDaniX** [comment]
Try to negate `essentials.fly.safelogin` permission in your permissions manager plugin.

**Comment by Chew** [comment]
That and people shouldn't be OP (or `*`) especially if you have a permission plugin. Negate the above perm or don't give it, to begin with.
For simple questions please ask on our Discord.
