### ISSUE TITLE
uuid in usermap.csv is not correct in online-mode. seen command works wrong

### ISSUE THREAD

**Issue by DahunDev** [EssentialsX/Essentials#3933]
```

```

**Server startup log:**

https://pastebin.com/z6SuXFix

https://pastebin.com/AcR6Lg4Z : Seems associated with this problem.

Might be a compatible issue with the SpleefX plugin, so I also reported this to the SpleefX plugin's author. 

**EssentialsX config:**

https://gist.github.com/mckite/d2f37ad8a053c11d0fb7020adfca3ff2
### Details

**Description:**  

![image](https://user-images.githubusercontent.com/17083624/104988632-36af4500-59de-11eb-8c4e-f616d64b9336.png)
![image](https://user-images.githubusercontent.com/17083624/104989617-75de9580-59e0-11eb-8404-bdd20278c956.png)

I don't know how to cause it, but after someday, some player's UUID in usermap,csv is not correct and
/seen <player> is not working correctly.

When using /seen <offlineplayer> or /balance <offlineplayer>

**Steps to reproduce:**  

I don't know how to cause it, but after someday, some player's UUID in usermap,csv is not correct and
/seen <player> is not working correctly.

Might be a compatible issue with the SpleefX plugin, so I also reported this to the SpleefX plugin's author. 

When using /seen <offlineplayer> or /balance <offlineplayer>
<offlineplayer> : The player that at least joined the server more than 1 time. ,
It should correct amount of money(instead of default balance) and show the correct last seen date and time instead of shows "that layer had never joined the server"

**Expected behavior:**  

/seen and /balance command should work correctly.

correct uuid should be in usermap.csv and updated.
When the server mode is online-mode, it should be updated.

<offlineplayer> : The player that at least joined the server more than 1 time. ,
When using /seen <offlineplayer> or /balance <offlineplayer>

It should correct amount of money(instead of default balance) and show correct last seen date and time instead of shows "that layer had never joined the server"

**Console stack trace:**  

```

```

**Screenshots:**  

![image](https://user-images.githubusercontent.com/17083624/104989610-71b27800-59e0-11eb-96ef-36dd820edfc6.png)

**Comment by JRoy** [comment]
This cannot be an Essentials issue, something is either poisoning the Bukkit or Essentials UserCache (maybe offline mode).
