### ISSUE TITLE
/sell multipliers with permissions

### ISSUE THREAD

**Issue by Soapiee** [EssentialsX/Essentials#3934]
### Feature request

**Feature description:**  

/sell multipliers that can be set with permission nodes.
The multipliers are to increase/multiply the sell price that someone can get via the /sell command. It basically multiplies the worth.

Example permissions:
essentials.sell.multiplier.0.5 > multiplies the worth/sell price by 0.5
essentials.sell.multiplier.2 > multiplies the worth/sell price by 2
essentials.sell.multiplier.X > multiplies the worth/sell price by X
OR
essentials.worth.multiplier.0.5 > multiplies the worth/sell price by 0.5
essentials.worth.multiplier.2 > multiplies the worth/sell price by 2
essentials.worth.multiplier.X > multiplies the worth/sell price by X

**How the feature is useful:**  
It is useful as it allows you to give a certain benefit to certain groups whilst still taking advantage of the EssentialsX worth and /sell features.
Its particular useful to server owners as it means they do not need to search and potentially purchase a separate plugin for such a small addition. You would have to re-create the shops and all their prices again.
The feature is player friendly as they can still use one command, rather than needing to visit different sign shop areas, or using different commands to access different shops that have different prices.

**Note**
I filtered through the issues (open and closed) and also checked changelogs on the GitHub to make sure I was not making a duplicate and/or denied request. My apologises if I missed one.

**Comment by Chew** [comment]
If implemented, this should match what we have in the config with homes. essentials.sell.multiplier (to allow access to the multiplier) and essentials.sell.multiplier.mod, for example.

**Comment by tatteaid** [comment]
> If implemented, this should match what we have in the config with homes. essentials.sell.multiplier (to allow access to the multiplier) and essentials.sell.multiplier.mod, for example.

essentials.sell.multiplier wouldn't be needed. For example, if they already have a mod sell multiplier applied to them, then there wouldn't be a point in having a permission to allow them access to the multiplier, nor would it make much sense.

**Comment by Chew** [comment]
Not sure you understand the concept of it, or I'm not understanding your message. The permission node is what tells the server what multiplier to give the user. It's the same thing as described with the sethome.multiple thing.
