### ISSUE TITLE
Custom Help Files

### ISSUE THREAD

**Issue by LordOmen** [EssentialsX/Essentials#3935]
![70848282-E1C3-424B-9A7E-723C36ADA25E](https://user-images.githubusercontent.com/65407056/105510959-51fba800-5c9d-11eb-83fa-e4fb3ce286b6.jpeg)
Problem:  Using custom help files In the format of help_<groupname>.txt per the wiki does not work when I replace <groupname> with a permission group.  If I just uses help.txt, the custom file works correctly. If I use help_default.txt for example, the game will not read the file correct and just spit out the standard essentials help output.

**Comment by mdcfe** [comment]
Please use the support template, not the bug report template, and provide all the information requested in the format, as well as relevant `/ess debug` outputs when users run the command.
