### ISSUE TITLE
Addition to command

### ISSUE THREAD

**Issue by Kixot14** [EssentialsX/Essentials#394]
Can you add saving status for /socialSpy command? When player do relog, socialSpy automatically disabled and every time need to enable it again for self!

Also need to add feature for change socialSpy format in the locale_en.

**Comment by SupaHam** [comment]
In order for a player to retain social-spy status when they log in, the must have the `essentials.socialspy` permission.

**Comment by Kixot14** [comment]
Nope. I have  - '*'  perm. But it's don't save socialSpy status.
All time need to enable it by command.

**Comment by drtshock** [comment]
Don't use \* perm. The persistence works.
