### ISSUE TITLE
Blank currency symbol

### ISSUE THREAD

**Issue by Chopnex** [EssentialsX/Essentials#3945]
### Feature request

**Feature description:**  

The ability to have a none and blank currency for balance. This was possible before the newest dev update but now it replaces the " " with a $ sign. Not quite sure if this is actually a bug.

**How the feature is useful:**  

The future is usefull for people who wants to use their own type of currency through skript or other plugins using balance.

**Comment by kashike** [comment]
Caused by https://github.com/EssentialsX/Essentials/commit/c6de77130fd683fbf79c4a1816d3e6513aa1f656.

**Comment by JRoy** [comment]
Can you explain where Essentials is showing the `$` symbol and how setting a blank currency symbol affects Skript? I don't think it would be a big deal to allow this, just curious about what problem this has on your end, so if you could share some examples (and maybe some screenshots) that would be nice

Note to self:
change the length check to > 1 rather than == 1 https://github.com/EssentialsX/Essentials/commit/c6de77130fd683fbf79c4a1816d3e6513aa1f656#diff-b8e0c618de42d4f3393256c3c8e2cc43b20b16b0633c772d3284d2e4c85ab40cR760

**Comment by Chopnex** [comment]
Its simply because the blank spot has been replaced with a dollar sign. This was not the case in earlier versions of Essentials. I linked you screenshots to show you exactly what the problem is.

![image](https://user-images.githubusercontent.com/75689956/106133552-b61ee000-6165-11eb-8e3a-2d229ea50a45.png)
![image](https://user-images.githubusercontent.com/75689956/106133588-c46cfc00-6165-11eb-9425-e1e5ea6963fe.png)

**Comment by Henriiig** [comment]
Hello, anything new about this? :)

**Comment by Chopnex** [comment]
> Can you explain where Essentials is showing the `$` symbol and how setting a blank currency symbol affects Skript? I don't think it would be a big deal to allow this, just curious about what problem this has on your end, so if you could share some examples (and maybe some screenshots) that would be nice
> 
> Note to self:
> change the length check to > 1 rather than == 1 [c6de771#diff-b8e0c618de42d4f3393256c3c8e2cc43b20b16b0633c772d3284d2e4c85ab40cR760](https://github.com/EssentialsX/Essentials/commit/c6de77130fd683fbf79c4a1816d3e6513aa1f656#diff-b8e0c618de42d4f3393256c3c8e2cc43b20b16b0633c772d3284d2e4c85ab40cR760)

Hello, anything new about this problem? :)

**Comment by JRoy** [comment]
> Hello, anything new about this? :)

I have an open PR, #3946, which fixes this. It's currently waiting on approval but feel free to test the jars found [here](https://github.com/EssentialsX/Essentials/suites/2071539417/artifacts/41889050)

**Comment by Chopnex** [comment]
> > Hello, anything new about this? :)
> 
> I have an open PR, #3946, which fixes this. It's currently waiting on approval but feel free to test the jars found [here](https://github.com/EssentialsX/Essentials/suites/2071539417/artifacts/41889050)

Thanks, im glad to hear that :)

**Comment by mdcfe** [comment]
@Henriiig #3946 has been merged which should allow this once again. You can download the latest version from the [EssentialsX website](https://essentialsx.net/downloads.html).
