### ISSUE TITLE
[Suggestion] Support for custom enchantment in anvil

### ISSUE THREAD

**Issue by Misio12320** [EssentialsX/Essentials#3948]
### Feature request

**Feature description:**  
I would like to have in Minecraft a custom anvil recipes via Essentials with special config for it.
For example:
Diamond sword with sharpness V + enchanted book Sharpness V = Diamond sword with sharpness VI for x amount of expierence level which is set in config created after install Essentials.

**How the feature is useful:**  
Easy to write some new recipes by developers, permission for them, balance, a better Minecraft expierence for players with new things.
The config of EssentialsX:
Allow custom recipes for anvil: false/true
The config of EssentialsX Custom Anvil Recipes:
Something + Something = something for x xp + custom xp for name and tool

**Comment by imDaniX** [comment]
I think it should be implemented with some custom plugin rather than with EssX, isn't it? Essentials doesn't affect vanilla gameplay besides adding various basic multiplayer commands and some other misc stuff(well, that's why it's called _Essentials_). This idea not only isn't basic, but it also changes overall balance of the game.

**Comment by Misio12320** [comment]
If Essentials allow to have custom enchantments which is allowed in config so why not custom tools in survival mode without cheating? 🤔 then I do not have ideas, let developers think and say their opinion.

**Comment by pop4959** [comment]
There is an option to allow unsafe enchantment levels when spawning items but I think that's a bit different than this which affects gameplay as well. I'm fairly certain you can find a plugin that exists which already does this.

**Comment by JRoy** [comment]
Closing as this isn't within the scope of Essentials
