### ISSUE TITLE
EssentialsChat + Dynmap

### ISSUE THREAD

**Issue by Kixot14** [EssentialsX/Essentials#396]
Can you disable broadcasting local messages in to the dynmap web-chat??
Only global messages should be enabled.

**Comment by SupaHam** [comment]
What do you mean local messages? Do you have the chat radius set in the essentials' config.yml?

**Comment by Kixot14** [comment]
Exactly! Under local messages i mean chat radius!

**Comment by Kixot14** [comment]
And one more suggestion:
When chat-radius is enabled, we have double sending messages in the console:

Example: 

> [17:26:53 INFO]: [L]<Notch> Hi! It's a example message.
> 
> [17:26:53 INFO]: [m[0;30;1m[[0;33;22mPlayer[0;30;1m] [0;33;1mNotch[0;33;22m: [0;37;1mHi! It's a example message.[m
> 
> [17:26:58 INFO]: [L]<Notch> It's a another example message.
> 
> [17:26:58 INFO]: [m[0;30;1m[[0;33;22mPlayer[0;30;1m] [0;33;1mNotch[0;33;22m: [0;37;1mIt's a another example message.[m

Can you fix that?? (Remove from console messages, which prefixed with [L]).

**Comment by pop4959** [comment]
Seems like an issue with Dynmap. Don't see why it would be pulling messages that are only broadcast to nearby players.
