### ISSUE TITLE
EssentialsSpawn

### ISSUE THREAD

**Issue by Kixot14** [EssentialsX/Essentials#398]
Why you not add individual spawns for all worlds ?
When player use command /spawn or when he died in Nether, for example, after that he should spawn on the Nether spawnpoint. But instead of that he spawn in the general spawnpoint of the World.

**Comment by Kixot14** [comment]
So i should to find another teleport plugin, or you will add this feature soon ??

**Comment by drtshock** [comment]
The /spawn is for the server spawn, not the world spawn.

**Comment by Kixot14** [comment]
Exactly. My question is "Did you will add something for individual worlds spawn" ??
