### ISSUE TITLE
AsyncTeleport CompletableFuture never completed

### ISSUE THREAD

**Issue by webcrawls** [EssentialsX/Essentials#3980]
**Type of bug**

Other unexpected behaviour

**`/ess version` output**

TODO @Jroy

**Server startup log**

TODO @Jroy

**EssentialsX config files**

TODO @Jroy

**Error log (if applicable)**

TODO @Jroy

**Bug description**

When using EssentialsX's AsyncTeleport (User#getAsyncTeleport), the CompletableFuture passed in is never completed.
Code example: https://github.com/kadenscott/Quantum/blob/822aa43ed4ea39548cda1f41d51bae6aa24f7cee/QuantumWild/src/main/java/dev/kscott/quantumwild/wild/WildManager.java#L362 

**Steps to reproduce**

TODO @Jroy

**Expected behaviour**

The CF is completed.

**Actual behaviour**

The CF is never completed.

jroy FORCED me to do this at GUNPOINT.

**Comment by tadhgboyle** [comment]
:shipit:

**Comment by JRoy** [comment]
TODO: @JRoy

**Comment by JRoy** [comment]
see discord :p https://ptb.discord.com/channels/712294044490793002/712294045312876586/809528563438452766
