### ISSUE TITLE
Option to disable bed missing / obstructed message when using respawn settings.

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#3988]
**`/ess version` output**

```
[18:48:06] [Server thread/INFO]: Server version: 1.16.5-R0.1-SNAPSHOT git-Paper-468 (MC: 1.16.5)
[18:48:06] [Server thread/INFO]: EssentialsX version: 2.19.0-dev+69-adef08a
[18:48:06] [Server thread/INFO]: PlaceholderAPI version: 2.10.10-DEV-122
[18:48:06] [Server thread/INFO]: LuckPerms version: 5.2.106
[18:48:06] [Server thread/INFO]: Vault version: 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[18:48:06] [Server thread/INFO]: EssentialsXAntiBuild version: 2.19.0-dev+69-adef08a
[18:48:06] [Server thread/INFO]: EssentialsXSpawn version: 2.19.0-dev+69-adef08a
[18:48:06] [Server thread/INFO]: Citizens version: 2.0.27-SNAPSHOT (build 2264)
```

**EssentialsX config files**

https://paste.gg/p/anonymous/2fc013729ee348f2b5af6fcf6b1f8332/files/3740581da091432cad8d0ec922fc9107/raw

**Feature request**
A way to disable the missing / obstructed message from appearing when you die and don't have a home bed or respawn anchor. I just want to silently teleport players to spawn if those aren't present. The message only occurs when special respawn condition settings are enabled. When you don't use anchors / bed home and just force players back to spawn, there is no message on death and Essentials falls back to the spawn point gracefully without notifying.

![link2](https://i.imgur.com/p1GfwWR.png)

```
# What priority should we use for handling respawns?
# Set this to none, if you want vanilla respawning behaviour.
# Set this to lowest, if you want Multiverse to handle the respawning.
# Set this to high, if you want EssentialsSpawn to handle the respawning.
# Set this to highest, if you want to force EssentialsSpawn to handle the respawning.
respawn-listener-priority: high

# What priority should we use for handling spawning on joining the server?
# See respawn-listener-priority for possible values.
# Note: changing this may impact or break spawn-on-join functionality.
spawn-join-listener-priority: high

# When users die, should they respawn at their first home or bed, instead of the spawnpoint?
respawn-at-home: false

# When users die, should EssentialsSpawn respect users' respawn anchors?
respawn-at-anchor: true

respawn-at-home-bed: true
```

**How the feature is useful:**

Less chat spam / verbose causing confusion to players when they respawn.

**PS: Jroy forgot to add ``respawn-at-home-bed`` to the default config.yml resource in https://github.com/EssentialsX/Essentials/commit/e2c6170ebae0d179e2a9f0bee9ab0749f72a6289**

Moving issue from https://github.com/EssentialsX/Essentials/discussions/3983 since it isn't really a new idea or feature to implement in Essentials.

**Comment by triagonal** [comment]
Answered in #3983.
