### ISSUE TITLE
Chat world aliases don't work

### ISSUE THREAD

**Issue by Bobcat00** [EssentialsX/Essentials#3999]
**Type of bug**

Other unexpected behaviour

**`/ess version` output**

19:49:02 [INFO] Server version: 1.16.5-R0.1-SNAPSHOT 3013-Spigot-73fb609-0cd8f19 (MC: 1.16.5)
19:49:02 [INFO] EssentialsX version: 2.19.0-dev+80-81571fc
19:49:02 [INFO] LuckPerms version: 5.2.76
19:49:02 [INFO] Vault version: 1.7.3-b131
19:49:02 [INFO] EssentialsXChat version: 2.19.0-dev+80-81571fc
19:49:02 [INFO] EssentialsXGeoIP version: 2.19.0-dev+80-81571fc
19:49:02 [INFO] EssentialsXSpawn version: 2.19.0-dev+80-81571fc

**Server startup log**

https://paste.gg/p/anonymous/dabc90f3cd264e2c8798351afe56e1a2

**EssentialsX config files**

https://paste.gg/p/anonymous/6b259bdab2514901ba047070d484dd2c

**Error log (if applicable)**

_No response_

**Bug description**

The new chat world aliases feature doesn't work. The chat is showing the regular world name instead of the alias defined in the config.

I'll cut to the chase - If you look at https://github.com/EssentialsX/Essentials/blob/81571fc014b973f7edaa5395d127b8362855159d/Essentials/src/main/java/com/earth2me/essentials/Settings.java#L553 you'll see it reads all the top-level keys from the config file (yes, the entire config file!) instead of reading chat.world-aliases. So it never gets the defined aliases.

**Steps to reproduce**

Define aliases, use WORLDNAME in the chat format, type a chat message.

**Expected behaviour**

The alias should be used in place of WORLDNAME.

**Actual behaviour**

The regular world name is used instead of the alias.

If you look at https://github.com/EssentialsX/Essentials/blob/81571fc014b973f7edaa5395d127b8362855159d/Essentials/src/main/java/com/earth2me/essentials/Settings.java#L553 you'll see it reads all the top-level keys from the config file (yes, the entire config file) instead of reading chat.world-aliases. So it never gets the defined aliases.

**Comment by JRoy** [comment]
oops

**Comment by Bobcat00** [comment]
I have a PR for this.  I don't know what you're doing.

It's just taking me forever to fill out the template and make screenshots and stuff.  It's tested and everything.
