### ISSUE TITLE
Trouble with HyperConomy and EssentialsX

### ISSUE THREAD

**Issue by galacticwarrior9** [EssentialsX/Essentials#400]
Hey there,
I've had some trouble with hyperconomy-0.975.6-SNAPSHOT.jar (latest dev build) and EssentialsX 2.0.1-b245.
An error occurs on startup. After that, I am not able to execute any HyperConomy related commands - there's no error or message in console or chat.
Here's my startup log to the point where the startup error stops (it starts at line 1001):
http://pastebin.com/7mCXtMYm

Here's what the HyperConomy author had to say about it:
http://dev.bukkit.org/bukkit-plugins/hyperconomy/#c2897

Many thanks!
galactic

**Comment by drtshock** [comment]
Can you reproduce this on the most recent essentialsx build?

**Comment by galacticwarrior9** [comment]
Sorry for the late reply!
Yes, it does still occur.

Many thanks,
galactic
