### ISSUE TITLE
Exception when tab-completing using /ban

### ISSUE THREAD

**Issue by Tikkle** [EssentialsX/Essentials#4005]
**Type of bug**

Error in console, Other unexpected behaviour

**`/ess version` output**

Server version: 1.16.5-R0.1-SNAPSHOT git-Paper-484 (MC: 1.16.5)
EssentialsX version: 2.18.2.0
LuckPerms version: 5.2.109
Vault version: 1.7.3-b131
EssentialsXSpawn version: 2.18.2.0

**Server startup log**

https://gist.github.com/Tikkle/761306891f5eb6e204a43c4ed97d51e8

**EssentialsX config files**

https://gist.github.com/Tikkle/12b0cc85f7bf9b7f8176838ccd1c5716

**Error log (if applicable)**

https://gist.github.com/Tikkle/181b7a8df264857a66237254353d800e

**Bug description**

When running "/ban playername reason" essentials spams in chat "An internal error occurred while attempting to tab-complete this command". Upon inspection of the console, the Error log attached displays an "Exception when Tikkle attempted to tab complete ban Michaeloky Theft".

**Steps to reproduce**

1. Have 1 person online only.
2. Have AdvancedBan version 2.3.0 installed.
3. Have EssentialsX & Spawn module version 2.18.2.0 installed.
4. Use Paper 1.16.5 build 484 running.
5. Run "/ban username reason"
- As you **type out** the reason the error will spam as well as the in-game message.
- You can execute the command just fine and the user will be banned through AdvancedBan.

**Expected behaviour**

No error should spam in-game or in console when typing out the ban reason.

**Actual behaviour**

EssentialsX spams an error as you type out a ban reason when executing "/ban playername ban-reason".

https://gyazo.com/26a3b2c91128337404c5d3b972984737.png <- in-game
https://gyazo.com/b6e5361bd134a5226c273ed7d97b6301.png <- part of the console spam

**Comment by JRoy** [comment]
this actually has nothing to do with essentials, we're passing the command off to AdvancedBan, report the error to them.
