### ISSUE TITLE
/baltop and /nearhomes causing server crash

### ISSUE THREAD

**Issue by Castiella** [EssentialsX/Essentials#4008]
**Type of bug**

Error in console

**`/ess version` output**

>.... [11:19:53 INFO]: Server version: 1.16.5-R0.1-SNAPSHOT git-Tuinity-"2006b9b" (MC: 1.16.5)
>.... [11:19:53 INFO]: EssentialsX version: 2.19.0-dev+81-6719837
>.... [11:19:53 INFO]: PlaceholderAPI version: 2.10.9
>.... [11:19:53 INFO]: LuckPerms version: 5.2.76
>.... [11:19:53 INFO]: Vault version: 1.7.3-b131
>.... [11:19:53 INFO]: EssentialsXChat version: 2.19.0-dev+81-6719837
>.... [11:19:53 INFO]: EssentialsXProtect version: 2.19.0-dev+81-6719837
>.... [11:19:53 INFO]: EssentialsXSpawn version: 2.19.0-dev+81-6719837
>.... [11:19:53 INFO]: Citizens version: 2.0.27-SNAPSHOT (build 2225)
>.... [11:19:53 INFO]: ChestShop version: 3.11.1-SNAPSHOT (build 238)

**Server startup log**

https://gist.github.com/Castiella/904008aedaf77068fb9d91ad54b2ac31

**EssentialsX config files**

not required

**Error log (if applicable)**

not required

**Bug description**

Whenever anyone runs /baltop or /nearhomes the server crashes.

**Steps to reproduce**

type /baltop or /nearhomes

**Expected behaviour**

Server should just return the list of the top players/near homes

**Actual behaviour**

Server crashes

**Comment by Castiella** [comment]
Looks like the log is too big for it to be pasted. Sorry- heres the file.
[latest (8).log](https://github.com/EssentialsX/Essentials/files/6035547/latest.8.log)

**Comment by JRoy** [comment]
Hello, this issue has been mitigated in recent EssentialsX dev builds!

If you currently have damaged data, you can read more about the steps you can take to fix this and prevent further issues of this sort [here](https://github.com/EssentialsX/Essentials/issues/3956#issuecomment-779254544).

Download the latest dev build [here](https://essentialsx.net/downloads.html).
