### ISSUE TITLE
AFK in Tablist (#2)

### ISSUE THREAD

**Issue by Kixot14** [EssentialsX/Essentials#402]
In build 263 you implemented feature for change players nickname/color in tablist. But if i enable it, this remove player prefixes and suffixes from plugin ColoredTags.

Can you a little change this feature for change ONLY players nickname (and save prefixes/suffixes in tablist).

Or you can just add group for AFK players.

**Comment by Kixot14** [comment]
And maybe it's possible to change nicknames on the player head, if this player is afk? (By group to.)

**Comment by SupaHam** [comment]
Sadly, I can't do that. This is the main reason this was made configurable and disabled by default. Other plugins also use the same features and it creates this interference, You must use one or the other.
