### ISSUE TITLE
EssentialsX commands not working 

### ISSUE THREAD

**Issue by KentBrought** [EssentialsX/Essentials#4021]
**Type of bug**

Other unexpected behaviour

**`/ess version` output**

[Sat, 27. Feb 2021 21:44:50 GMT INFO] Server version: 1.13.2-R0.1-SNAPSHOT git-Spigot-1a3504a-e7700ab (MC: 1.13.2)
[Sat, 27. Feb 2021 21:44:50 GMT INFO] EssentialsX version: 2.19.0-dev+80-81571fc
[Sat, 27. Feb 2021 21:44:50 GMT INFO] PlaceholderAPI version: 2.10.2
[Sat, 27. Feb 2021 21:44:50 GMT INFO] PermissionsEx version: 1.23.4
[Sat, 27. Feb 2021 21:44:50 GMT INFO] Vault version: 1.7.2-b107
[Sat, 27. Feb 2021 21:44:50 GMT INFO] Citizens version: 2.0.27-SNAPSHOT (build 2224)
[Sat, 27. Feb 2021 21:44:50 GMT INFO] Towny version: 0.96.2.0-for-1.13.2
[Sat, 27. Feb 2021 21:44:50 GMT INFO] You are running unsupported plugins!
[Sat, 27. Feb 2021 21:44:50 GMT INFO] You are running a server with limited API functionality. EssentialsX will still work, but certain features may be disabled.

**Server startup log**

https://gist.github.com/128912891289/8e804abb161fb3b5b4698cbcb2763608

**EssentialsX config files**

https://gist.github.com/128912891289/7871bd6aca199b4b812a74b6cecc61d4

**Error log (if applicable)**

Not applicable

**Bug description**

Whenever I try to run any basic EssentialsX commands they do not work on first try and have to be spammed multiple times for them to work. This issue is only happening with EssentialsX commands on my server. 

**Steps to reproduce**

1. Turn on server. 
2. Try to run /gm <any gamemode>, /warp <any warp>, /msg <any person> <any message>, /tpa <any one, anywhere>

**Expected behaviour**

What should happen is that players should only have to run the command once for it to work. 

**Actual behaviour**

Commands do not run on first try and have to be spammed multiple times for them to work.

**Comment by imDaniX** [comment]
Well, besides one `/gamemode 1` fail, which was caused because of permissions, I don't see any spam in your log whatsoever.
As you can see in your `/ess version`, you're running unsupported plugins - PermissionsEx to be exact.

**Comment by pop4959** [comment]
Closing this issue since your log is littered with errors from other plugins, and there's no real indication that Essentials is doing anything wrong. If you're absolutely sure this is an Essentials bug, please make a new report after first testing with all other plugins removed, as it's most likely an issue with another plugin.
