### ISSUE TITLE
[Essentials] Account creation was requested for NPC user zider593, but an account file with UUID 87e1d65d-9933-3def-aa4e-95de8378728f already exists.

### ISSUE THREAD

**Issue by WhiTe-Yak** [EssentialsX/Essentials#4024]
**Type of bug**

Error in console

**`/ess version` output**

[13:43:30 INFO]: CONSOLE issued server command: /ess version
[13:43:30 INFO]: Server версия: 1.16.5-R0.1-SNAPSHOT git-Paper-505 (MC: 1.16.5)
[13:43:30 INFO]: EssentialsX версия: 2.19.0-dev+86-ee5f4b9
[13:43:30 INFO]: PlaceholderAPI версия: 2.10.10-DEV-122
[13:43:30 INFO]: LuckPerms версия: 5.2.121
[13:43:30 INFO]: Vault версия: 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[13:43:30 INFO]: EssentialsXSpawn версия: 2.19.0-dev+86-ee5f4b9

**Server startup log**

https://paste.gg/p/anonymous/f4f19f239deb4a019650e9ddb6533ce0

**EssentialsX config files**

https://paste.gg/p/anonymous/d9b351d2a3f641e69bc12f7d01cade30

**Error log (if applicable)**

https://paste.gg/p/anonymous/0592805813fc41be93a700845498b6ad

**Bug description**

https://paste.gg/p/anonymous/0592805813fc41be93a700845498b6ad

**Steps to reproduce**

Run server

**Expected behaviour**

Stable operation without errors

**Actual behaviour**

Errors

Pls help fix it

**Comment by WhiTe-Yak** [comment]
Solved by deleting files: usermap; userdata

**Comment by Hallowhead1** [comment]
I too have this problem

**Comment by LucidAPs** [comment]
Same here and removing PlaceholderAPI solved it, although not really a solution.

**Comment by ImperatusMaximus** [comment]
hello i'm facing the same problem :/

**Comment by LucidAPs** [comment]
I don't understand why this is still in unconfirmed.

**Comment by triagonal** [comment]
> 
> 
> I don't understand why this is still in unconfirmed.

This isn't a bug - the label is automatically assigned by the issue form. These messages aren't errors themselves, and were purposefully added to help us investigate and fix issues relating to other plugins corrupting the EssentialsX usermap.

Read this for more information: https://github.com/EssentialsX/Essentials/issues/3956#issuecomment-779254544

**Comment by LucidAPs** [comment]
> This isn't a bug - the label is automatically assigned by the issue form. These messages aren't errors, and were purposefully added to help us investigate and fix issues relating to other plugins corrupting the EssentialsX usermap.
> 
> Read this for more information: [#3956 (comment)](https://github.com/EssentialsX/Essentials/issues/3956#issuecomment-779254544)

All I know is that removing the vault and essentials extensions from PAPI these "non errors" that can lead to crashes from using /baltop /seen /near /alts etc. Don't seem to happen. https://github.com/EssentialsX/Essentials/issues/3974 https://github.com/EssentialsX/Essentials/issues/3974 https://github.com/EssentialsX/Essentials/issues/3991 https://github.com/EssentialsX/Essentials/issues/4008 https://github.com/EssentialsX/Essentials/issues/3978

**Comment by Hallowhead1** [comment]
any updates on this?

**Comment by LucidAPs** [comment]
Yeah push Roy's update upstream please!

**Comment by Hallowhead1** [comment]
bump?

**Comment by Chew** [comment]
nah

**Comment by JRoy** [comment]
Hello, this issue has been mitigated in recent EssentialsX dev builds!

If you currently have damaged data, you can read more about the steps you can take to fix this and prevent further issues of this sort [here](https://github.com/EssentialsX/Essentials/issues/3956#issuecomment-779254544).

Download the latest dev build [here](https://essentialsx.net/downloads.html).
