### ISSUE TITLE
Custom blocks are not protected

### ISSUE THREAD

**Issue by 100petr** [EssentialsX/Essentials#4027]
### Type of bug

Compatibility issue

### `/ess version` output

[11:52:00 INFO]: Server version: 1.16.5-R0.1-SNAPSHOT git-Paper-507 (MC: 1.16.5)
[11:52:00 INFO]: EssentialsX version: 2.19.0-dev+87-b43790e
[11:52:00 INFO]: EssentialsXProtect version: 2.19.0-dev+87-b43790e
[11:52:00 INFO]: Vault is not installed. Chat and permissions may not work.

### Server startup log

https://paste.gg/p/anonymous/030bade884c64ea5ae3f4544b9edd037

### EssentialsX config files

https://paste.gg/p/anonymous/3bb600ed39c1476fa814e81dbf3997c9

### Bug description

EssentialsProtect does not protect custom blocks from the ItemsAdder (https://www.spigotmc.org/resources/✅must-have✅-itemsadder✨custom-items-huds-guis-mobs-3dmodels-emojis-blocks-wings-hats-liquids.73355/) plugin from explode & destroy

### Steps to reproduce

1. Set tnt-explosion to true
2. Place a block from the ItemsAdder
3. Place and ignite the TNT
4. Vanilla blocks are not destroyed, but ItemsAdder yes

### Expected behaviour

ItemsAdder blocks will not be destroyed

### Actual behaviour

ItemsAdder blocks are destroyed

![2021-03-02_11 59 00](https://user-images.githubusercontent.com/29830635/109638799-bd635000-7b4e-11eb-9129-414606ef89e6.png)
![2021-03-02_11 59 06](https://user-images.githubusercontent.com/29830635/109638809-be947d00-7b4e-11eb-87b4-06438da37abf.png)

**Comment by pop4959** [comment]
Sounds like an issue with the other plugin

**Comment by 100petr** [comment]
At that time, I had only the ones needed to work on the server.
Essentials, EssentialsProtect, ItemsAdder, LoneLibs, ProtocolLib, LightAPI
And on the ItemsAdder discord they wrote me that it was a Essentials thing.

**Comment by JRoy** [comment]
It looks like they're doing some stuff with resource packs, I don't know how we would individually support those kinds of things so probably will not see support in Essentials.
