### ISSUE TITLE
Dying breaks multiple essentials commands until relog

### ISSUE THREAD

**Issue by SilentStarling** [EssentialsX/Essentials#4028]
### Type of bug

Other unexpected behaviour

### `/ess version` output

Server version: 1.16.5-R0.1-SNAPSHOT 1.16.5-380 (MC: 1.16.5)
02.03 15:44:48 [Server] INFO EssentialsX version: 2.19.0-dev+86-ee5f4b9
02.03 15:44:48 [Server] INFO LuckPerms version: 5.2.67
02.03 15:44:48 [Server] INFO Vault version: 1.7.3-b131
02.03 15:44:48 [Server] INFO EssentialsXChat version: 2.19.0-dev+86-ee5f4b9
02.03 15:44:48 [Server] INFO EssentialsXSpawn version: 2.19.0-dev+86-ee5f4b9

### Server startup log

https://paste.gg/p/anonymous/b80d2c576df14254881525c3250c4628

### EssentialsX config files

https://paste.gg/p/anonymous/bbb02c240fbf4648a98c0b877753e5c4

### Bug description

Once a player dies, many of essentials warping commands stop working. Once player respawns after death /back, /warp, and variations of /tp no longer work. It lets the player run the command, says it is working, then never does anything. Console does not show any errors, acts as if the command has been run with no problems. Also, players who have access to /fly have found that if they run /fly after they have died, they take fall damage with /fly on, both from descending with shift and from double tapping space to stop flying. All of these start working again upon relogging into the server, although obviously at that point the /back is lost.

### Steps to reproduce

1: player dies
2: player respawns
3: player tries to run /warp, /tp, or /back
4: player runs /fly, lands, takes damage
5: player logs out of and back into server
6: all commands work again

### Expected behaviour

To my knowledge, when someone has /fly on they shouldn't take fall damage at all. 

I searched config for any sort of death-delay-commands setting and didn't find one, so commands should be working immediately after player death

### Actual behaviour

Players with /fly on take fall damage, and eventually die from fall damage if landing from high enough up.

players are able to run the /back /warp and /tp commands, and chat says all the appropriate messages (for back, it says "Returning to previous location") but it doesn't actually teleport the player anywhere.

**Comment by Chew** [comment]
Hey there! Per our downloads page, "[EssentialsX does not support Akarin, Yatopia, __Mohist__, or Magma as your server software. These servers include dangerous non-standard behavior, which can not only impact EssentialsX's functionality but also cause damage to your worlds.](https://essentialsx.net/downloads.html)" 

If you are able to reproduce this on supported software, please reply or open a new issue. Thank you for reporting!

**Comment by scarlettcloud** [comment]
Silent, did you figure out a way to fix? I know this install type is not supported by EssentialsX but I'm experiencing the same issue on Magma and wondering if you have a way to resolve.

**Comment by mdcfe** [comment]
The EssentialsX downloads site asks Magma users to contact Magma for support and not to use this issue tracker. Magma's changes to the CraftBukkit server implementation make it fundamentally incompatible with most Bukkit plugins. There is very little that can be done on EssentialsX's side without imposing compromises onto the platforms we *do* support. 

In the future, please avoid bumping old issues about software we explicitly do not support. This issue has been inactive for over a year.
