### ISSUE TITLE
Toggle for local chat

### ISSUE THREAD

**Issue by Kixot14** [EssentialsX/Essentials#403]
Players with permission - essentials.chat.spy be able to hear all local messages.
This is useful for moderators, but sometime it annoys them, because they receive a lot of spam.

Maybe you can add something like command for moderators with - essentials.chat.spy be able to disable/enable this feature for himself??

**Comment by mibby** [comment]
I was just about to create a ticket similar to this. :P But more so for users to be able to toggle between local and global chat. Such as having global chat by default and have an option to toggle local chat for events to avoid chat spam. (Either chat toggle command or a shortcut alias for local chat, like typing ~ before text results in it outputted to local chat? `~example`)

**Comment by drtshock** [comment]
Isn't the point of chatspy to be able to hear everything?

**Comment by Kixot14** [comment]
Yes, it is! But sometime moders just wanna play as a usual player and  wanna disable chatSpy due to spam!

**Comment by Sebas-Re** [comment]
i would love to see this implemented :D

**Comment by AMDBartek** [comment]
This would be great to have.

**Comment by pop4959** [comment]
`/socialspy` exists for this use case. If you want players to be able to toggle whether they see messages, you should be using this.
