### ISSUE TITLE
 Account creation was requested for NPC user

### ISSUE THREAD

**Issue by ImperatusMaximus** [EssentialsX/Essentials#4036]
### Type of bug

Error in console

### `/ess version` output

[Sat, 6. Mar 2021 09:23:30 CET INFO] CONSOLE issued server command: /ess version
[Sat, 6. Mar 2021 09:23:30 CET INFO] Server version: 1.16.5-R0.1-SNAPSHOT git-Purpur-1001 (MC: 1.16.5)
[Sat, 6. Mar 2021 09:23:30 CET INFO] EssentialsX version: 2.19.0-dev+87-b43790e
[Sat, 6. Mar 2021 09:23:30 CET INFO] PlaceholderAPI version: 2.10.10-DEV-122
[Sat, 6. Mar 2021 09:23:30 CET INFO] LuckPerms version: 5.3.0
[Sat, 6. Mar 2021 09:23:30 CET INFO] Vault version: 1.7.3-b131
[Sat, 6. Mar 2021 09:23:30 CET INFO] Citizens version: 2.0.27-SNAPSHOT (build 2269)
[Sat, 6. Mar 2021 09:23:30 CET INFO] ChestShop version: 3.11 (build 213)
[Sat, 6. Mar 2021 09:23:30 CET INFO] EssentialsXChat version: 2.19.0-dev+87-b43790e

### Server startup log

https://paste.gg/p/anonymous/016993e996184e9ab21b9f73d9b7c791

### EssentialsX config files

https://paste.gg/p/anonymous/0fc85f23bf36487692111c214d2252c7

### Error log (if applicable)

https://paste.gg/p/anonymous/e69eb333ba5544f1adb4d33a710e3308

### Bug description

EssentialsX unsuccesfully tries to create a new account which appearantly already exists.

### Steps to reproduce

It suddenly started at some point which is unknown to me.

### Expected behaviour

I expect that it should be creating that account or atleast overwrite the old data and just stops spamming the console

### Actual behaviour

It doesn't do that.

**Comment by JRoy** [comment]
Hello, this issue has been mitigated in recent EssentialsX dev builds!

If you currently have damaged data, you can read more about the steps you can take to fix this and prevent further issues of this sort [here](https://github.com/EssentialsX/Essentials/issues/3956#issuecomment-779254544).

Download the latest dev build [here](https://essentialsx.net/downloads.html).
