### ISSUE TITLE
join message not appearing if silent join is set to true

### ISSUE THREAD

**Issue by Kristoffeh** [EssentialsX/Essentials#4041]
### Type of bug

Other unexpected behaviour

### `/ess version` output

07.03 15:26:04 [Server] INFO You are running an unsupported server version!
07.03 15:26:04 [Server] INFO Vault is not installed. Chat and permissions may not work.
07.03 15:26:04 [Server] INFO LuckPerms version: 5.3.0
07.03 15:26:04 [Server] INFO EssentialsX version: 2.18.2.0
07.03 15:26:04 [Server] INFO Server version: 1.16.5-R0.1-SNAPSHOT git-Paper-508 (MC: 1.16.5)
07.03 15:26:04 [Server] INFO CONSOLE issued server command: /ess version

### Server startup log

https://paste.gg/p/anonymous/89cd592f21cb45389c1dbe49d0670730

### EssentialsX config files

https://paste.gg/p/anonymous/07bc13363fb946978573a7d7e4a0aa53

### Bug description

if the setting allow-silent-join-quit is set to true, and users with the following permissions are allowed to join silently:
- essentials.silentjoin
- essentials.silentquit

I have set the permissions to false, so users that doesnt have the permissions, for example members will just show a blank space. And for users like admins that have the setting set to true will have it working like it should, no blank space and no join/leave message.

### Steps to reproduce

Set the setting allow-silent-join-quit to true, and set the permission entries to false.

### Expected behaviour

allow-silent-join-quit is set to true. Both permission entries are set to 

### Actual behaviour

When permissions are set to true it works as it should, but when permissions are set to false it will show a blank space (but should show join message)

[Blank space insead of join message](https://prnt.sc/10fbqgg)

**Comment by JRoy** [comment]
This was a Paper bug, can you update to the latest Paper version and see if you still have this problem?

**Comment by Kristoffeh** [comment]
> This was a Paper bug, can you update to the latest Paper version and see if you still have this problem?

The server is already using the latest version, [1.16.5](https://i.ibb.co/8mccnG8/Screenshot-1.png).
EDIT: Already using latest version of PaperMC. 1.16.5!

**Comment by JRoy** [comment]
Your issue says you're using Paper 508 of 1.16.5, the latest is Paper 529. Please ask your host to update their Paper version

**Comment by Kristoffeh** [comment]
That gotta be it. All sorted then!
