### ISSUE TITLE
Not work command (/more)

### ISSUE THREAD

**Issue by WhiTe-Yak** [EssentialsX/Essentials#4046]
### Type of bug

Other unexpected behaviour

### `/ess version` output

Server версия: 1.16.5-R0.1-SNAPSHOT git-Paper-534 (MC: 1.16.5)
EssentialsX версия: 2.19.0-dev+86-ee5f4b9
PlaceholderAPI версия: 2.10.10-DEV-122
LuckPerms версия: 5.3.0
Vault версия: 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
EssentialsXSpawn версия: 2.19.0-dev+86-ee5f4b9

### Server startup log

-

### EssentialsX config files

https://paste.gg/p/anonymous/2c3d86cd0d74487883fae493c76aab6c

### Bug description

When writing a command /more, the item does not stack.
There was no such problem before

### Steps to reproduce

/more

### Expected behaviour

Stack item "1 -> 64"

### Actual behaviour

No stack item's & block's & more

**Comment by JRoy** [comment]
Cannot reproduce. Reopen with a proper and detailed way to reproduce.
