### ISSUE TITLE
Private message and socialspy format

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#405]
Hello there,
1. Is there an option to add the [Prefix] to private messages? So instead of only the player's name, it will also show the rank?
2. Is there an option to change the private message format at all? For example now it is:
   Sikaru -> me
   me -> Sikaru
   Can we change the the format and the colors? Example:
   Sikatsu > Sikaru
   Sikaru > Sikatsu
3. Can we in any way change the color of the socialspy format?

Looking forward to your reply,

Sikatsu

**Comment by ghost** [comment]
Maybe something like this:

https://github.com/drtshock/Essentials/issues/321

Some plugins support to change the whole look of private messages and socialspy in a config file, including colors and how you want the format to be.

Do you understand what I mean?

Not sure if I'm clear enough about what I mean.

**Comment by drtshock** [comment]
321 is formatting socialspy, not private messages. But why not both!

**Comment by Sikatsu** [comment]
Thanks for your reply!

I know that one was about socialspy, I linked it to make sure you understood what I meant. :)

Being able to add a prefix and change the colors ect. Just the whole privatemessage/socialspy format.

So you will add it? :D

**Comment by Dooleylabs** [comment]
I want this._.

**Comment by Sikatsu** [comment]
@drtshock Any clue on when you are going to work on this or?

**Comment by FlippantCactus** [comment]
@Sikatsu Trent apparently has what I now know as a "life" so he probably doesn't keep an open source and public plugin at the height of his life. Be patient. That being said he's one fast hoe with fixes.

**Comment by Sikatsu** [comment]
@TWSSYesterday I was just hoping for a confirm, sorry for that.

To fullfill this topic, this is something I mean: http://prntscr.com/a2wqiy

**Comment by NoobPlayer03** [comment]
@ghost The essentials locale is used to change messages

**Comment by Sikatsu** [comment]
I'm ghost, however that's not working for socialspy or privatemessage formats.

**Comment by PurPLeEPiC** [comment]
where can i find this http://prntscr.com/a2wqiy

**Comment by Sikatsu** [comment]
This is DeluxeChat.

**Comment by PurPLeEPiC** [comment]
is deluxechat working with essentialsx and permissionsex ? so can i remove essentialsxchat for deluxechat  ?

**Comment by Sikatsu** [comment]
Yup it is, no worries! However, I currently use ChatControl, but it doesn't offer this option, that's why I requested this option in Essentials. (I'm ghost btw)

**Comment by PurPLeEPiC** [comment]
ok tnx 
so with deluxechat you can do this http://prntscr.com/an62du ?

**Comment by PurPLeEPiC** [comment]
does server FadeCloud have deluxechat ?

**Comment by Sikatsu** [comment]
Correct, you can change the private message format to your liking.

I don't know FadeCloud.

**Comment by PurPLeEPiC** [comment]
oh its on 4 th place on minecraft-mp

**Comment by PurPLeEPiC** [comment]
hi Sikatsu can you help me with this

essentials.fly
essentials.afk.kickexempt
essentials.afk.auto 
don't work my players have permision for this but they can't do /fly and after 5 min they not get kick from server

**Comment by pop4959** [comment]
Closing for the reason described in #321
