### ISSUE TITLE
Alternative method for balance check / Economy account supporting.

### ISSUE THREAD

**Issue by Kixot14** [EssentialsX/Essentials#406]
Can you add feature to check account balances due UUID
(Ideally, with specific permission, like - balance.check.< uuid >), or add custom command and option in config to link some account with this command, for balance checking...

That need for one thing:
I have server economy account. This account stored in essentials user data as NPC and exact name of this account is §2SERVER.BANK§r (With color codes, which unreal to paste in minecraft chat.)
Need give for players possible to check balance of this account.
Yes, this acc displayed in /balancetop list, but if balance of server economy account if very low, it go back under 1000+ pages.
So need some supporting for economy accounts...

**Comment by pop4959** [comment]
I don't really see what the purpose of this is, but if you still need this feel free to open a new issue explaining why this is necessary and what exactly needs to be done (since this is also a bit vague).
