### ISSUE TITLE
Not work command (/more)

### ISSUE THREAD

**Issue by WhiTe-Yak** [EssentialsX/Essentials#4062]
### Type of bug

Other unexpected behaviour

### `/ess version` output

Server версия: 1.16.5-R0.1-SNAPSHOT git-Paper-534 (MC: 1.16.5)
EssentialsX версия: 2.19.0-dev+86-ee5f4b9
PlaceholderAPI версия: 2.10.10-DEV-122
LuckPerms версия: 5.3.0
Vault версия: 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
EssentialsXSpawn версия: 2.19.0-dev+86-ee5f4b9

### Server startup log

По данной проблеме лог не нужен (Ошибок в консоли нет!)

### EssentialsX config files

https://paste.gg/p/anonymous/2c3d86cd0d74487883fae493c76aab6c

### Error log (if applicable)

В консоли нет ошибок!

### Bug description

Команда не работает должным образом.

### Steps to reproduce

Запустить сервер в штатном режиме.
Зайти на него.
Взять в руку ведро. (Любой нестакаемый предмет)
Написать команду /more
Ошибка.

### Expected behaviour

Вместо одного предмета в руке, после написания команды его должно стать 64.

### Actual behaviour

После написания команды в чате пишет ошибку.
Что-то на подобие того, что предмет не может быть стакнут.

This issues is a response to a comment on this https://github.com/EssentialsX/Essentials/issues/4046#event-4428929821

**Comment by triagonal** [comment]
Unable to reproduce:
```
[01:04:34 INFO]: Server version: 1.16.5-R0.1-SNAPSHOT git-Paper-542 (MC: 1.16.5)
[01:04:34 INFO]: EssentialsX version: 2.19.0-dev+96-1cf2b11
[01:04:34 INFO]: LuckPerms version: 5.3.5
[01:04:34 INFO]: Vault version: 1.7.3-b131
```
Following the reproduction steps led to me having a stack of 64 buckets in my inventory. In order to gain an oversized stack of normally unstackable items, you also need the `essentials.oversizedstacks` permission. The oversized stack size can be controlled in the config with the `oversized-stacksize` option.
