### ISSUE TITLE
enchantments not working

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#407]
I think unsafe enchantments is not working on the latest version. I have it enabled in the config but when I try to spawn in items and use kits with unsafe enchants it doesnt work. Here is the error. http://pastebin.com/Z8puLH5M Using 1.7.10 btw.

**Comment by ghost** [comment]
Now enchants just dont work at all. When I do /enchant nothing shows up.

**Comment by Stimulation** [comment]
Same here, Using Cauldron 1.7.10:

http://pastebin.com/zsTKCiU9

**Comment by vemacs** [comment]
Try the latest build

**Comment by Stimulation** [comment]
Thank you, Works like a charm!
