### ISSUE TITLE
Using iConomy I reset the balance of all my players but essentials is still showing the old balance for the players.

### ISSUE THREAD

**Issue by RSNFreud** [EssentialsX/Essentials#4075]
Using iConomy I reset the balance of all my players but essentials is still showing the old balance for the players.

**Comment by JRoy** [comment]
Where is essentials showing the old balance. (In what command)

**Comment by RSNFreud** [comment]
Bal and baltop

**Comment by JRoy** [comment]
Can you replace your existing essentials jars with the onea located here: https://github.com/EssentialsX/Essentials/suites/2308466137/artifacts/48448610 and tell me if your problem persists?

**Comment by RSNFreud** [comment]
Still happens

**Comment by Agaloth** [comment]
I'm getting the same issue since the latest essentialsx dev builds.

I think this build broke essentialsx with iconomy: https://github.com/EssentialsX/Essentials/actions/runs/829236993

This one should be normally working (I can't remember the version I used but I know it was before the one I sent on top): https://github.com/EssentialsX/Essentials/actions/runs/829077444

**Comment by JRoy** [comment]
> I'm getting the same issue since the latest essentialsx dev builds.
> 
> I think this build broke essentialsx with iconomy: [EssentialsX/Essentials/actions/runs/829236993](https://github.com/EssentialsX/Essentials/actions/runs/829236993)
> 
> This one should be normally working (I can't remember the version I used but I know it was before the one I sent on top): [EssentialsX/Essentials/actions/runs/829077444](https://github.com/EssentialsX/Essentials/actions/runs/829077444)

Can you share;

`/vault-info` and the **full** output of `/ess version`

**Comment by Agaloth** [comment]
![image](https://user-images.githubusercontent.com/33335971/118861489-da512900-b8dc-11eb-9176-ca9cbaa387f5.png)

![image](https://user-images.githubusercontent.com/33335971/118861519-e1783700-b8dc-11eb-90f0-779f4d03201b.png)

**Comment by JRoy** [comment]
Are you sure that after doing `/baltop force` the problem doesn't fix itself? Can you show an example in a screenshot or video somehow showcasing exactly what you're referring to?

**Comment by Agaloth** [comment]
This is basically the issue, essentials will show me this balance (5,439.03) 
![image](https://user-images.githubusercontent.com/33335971/118868807-eccf6080-b8e4-11eb-9bc4-3e6060b41003.png)

But vault will show 5383.03
![image](https://user-images.githubusercontent.com/33335971/118868938-15575a80-b8e5-11eb-957e-d5d87ed2cbdc.png)

All of these commands have been done after doing /baltop force

**Comment by Agaloth** [comment]
Keep me updated, this seems to happen with every players on the server.

**Comment by Agaloth** [comment]
Any updates on that?

**Comment by JRoy** [comment]
Should be fixed by https://github.com/EssentialsX/Essentials/suites/3146539215/artifacts/72312913
@Agaloth want to try that build and let me know
