### ISSUE TITLE
RGB does not work in messages_xx.properties

### ISSUE THREAD

**Issue by Noxillio** [EssentialsX/Essentials#4077]
### Type of bug

Other unexpected behaviour

### `/ess version` output

[Mon, 22. Mar 2021 02:20:40 GMT INFO] Server version: 1.16.5-R0.1-SNAPSHOT git-Tuinity-"2f298d3" (MC: 1.16.5)
[Mon, 22. Mar 2021 02:20:40 GMT INFO] EssentialsX version: 2.18.2.0
[Mon, 22. Mar 2021 02:20:40 GMT INFO] PlaceholderAPI version: 2.10.9
[Mon, 22. Mar 2021 02:20:40 GMT INFO] LuckPerms version: 5.2.126
[Mon, 22. Mar 2021 02:20:40 GMT INFO] Vault version: 1.7.3-b131
[Mon, 22. Mar 2021 02:20:40 GMT INFO] EssentialsXSpawn version: 2.18.2.0
[Mon, 22. Mar 2021 02:20:40 GMT INFO] Citizens version: 2.0.27-SNAPSHOT (build 2276)
[Mon, 22. Mar 2021 02:20:40 GMT INFO] You are running an unsupported server version!

### Server startup log

https://gist.github.com/Noxillio/2e0d3b725031f61fc180981717e99ea7

### EssentialsX config files

https://gist.github.com/Noxillio/30cb920f99fbd10ff8b05c6cfd2c6f0b

### Bug description

RGB colors do not work in messages_xx.properties files.

### Steps to reproduce

1. Make an essentials_en.properties file.
2. Try to use RGB codes as described in the changelog from when they were added to EssentialsX.

### Expected behaviour

RGB should work.

### Actual behaviour

RGB doesn't work. The hex code is simply returned without # and §.

**Comment by Chew** [comment]
I'm going to go out on a limb and assume you need to do the dumb, stinky way of doing color codes, which is something like: `&x&r&r&g&g&b&b`, but you may need to do `§` instead of `&`

**Comment by Noxillio** [comment]
> &x&r&r&g&g&b&b

That was it, how dumb and stinky :( thanks a ton
