### ISSUE TITLE
Console spammed with "Essentials will create a new account as requested by the other plugin..." Error

### ISSUE THREAD

**Issue by WhatsTheBadNews** [EssentialsX/Essentials#4079]
### Type of bug

Error in console

### `/ess version` output

[13:58:53 INFO]: Server version: 1.16.5-R0.1-SNAPSHOT git-Tuinity-"44e8e5d" (MC: 1.16.5)
[13:58:53 INFO]: EssentialsX version: 2.19.0-dev+96-1cf2b11
[13:58:53 INFO]: PlaceholderAPI version: 2.10.10-DEV-122
[13:58:53 INFO]: LuckPerms version: 5.3.11
[13:58:53 INFO]: Vault version: 1.7.3-b131
[13:58:53 INFO]: Citizens version: 2.0.27-SNAPSHOT (build 2269)
[13:58:53 INFO]: EssentialsXSpawn version: 2.19.0-dev+96-1cf2b11
[13:58:53 INFO]: Fetching version information...
[13:58:54 INFO]: You're 3 EssentialsX dev build(s) out of date!
[13:58:54 INFO]: Download it here: https://essentialsx.net/downloads.html

### Server startup log

https://gist.github.com/WhatsTheBadNews/b0f7fed63bbdb0dd3feb5ef52a1d9a61

### EssentialsX config files

https://gist.github.com/WhatsTheBadNews/be889e30bec52377077380a4c5a9a7f7

### Error log (if applicable)

https://gist.github.com/WhatsTheBadNews/7d728185e2f0a0e29e653f202bc995d1

### Bug description

My console spammed with a "Essentials will create a new account as requested by the other plugin..." error, like the one I provided. I can provide more if needed, but they are all very similar.

### Steps to reproduce

I am not sure

### Expected behaviour

Console not to be spammed with this error

### Actual behaviour

Console is spammed with this error

**Comment by JRoy** [comment]
Try the builds from here: https://github.com/EssentialsX/Essentials/suites/2308466137/artifacts/48448610

**Comment by hkkongou** [comment]
hi, my console show ``Essentials will create a new account as requested by the other plugin``
but there are some difference between the log
log:
https://pastebin.com/uvtnLq8q


![image](https://user-images.githubusercontent.com/61608872/112086351-0135fc00-8bc7-11eb-9ad4-67c93d7e8c06.png)


the essentials build i use is EssentialsX-2.19.0-dev+99-1e0d7fb
but i haven't try to build 100 provided above

hope these extra info can help

**Comment by JRoy** [comment]
> hi, my console show `Essentials will create a new account as requested by the other plugin`
> but there are some difference between the log
> log:
> [pastebin.com/uvtnLq8q](https://pastebin.com/uvtnLq8q)
> 
> ![image](https://user-images.githubusercontent.com/61608872/112086351-0135fc00-8bc7-11eb-9ad4-67c93d7e8c06.png)
> 
> the essentials build i use is EssentialsX-2.19.0-dev+99-1e0d7fb
> but i haven't try to build 100 provided above
> 
> hope these extra info can help

try the one i linked :)

**Comment by WhatsTheBadNews** [comment]
> Try the builds from here: https://github.com/EssentialsX/Essentials/suites/2308466137/artifacts/48448610

I've upgraded to the version of EssentialsX you provided and I I am still getting these messages.

One example: https://gist.github.com/WhatsTheBadNews/d0aaf0740d4bd4593f95203a36fcd254

**Comment by Drizzy-America** [comment]
Any other options to fix this?

**Comment by Drizzy-America** [comment]
> > hi, my console show `Essentials will create a new account as requested by the other plugin`
> > but there are some difference between the log
> > log:
> > [pastebin.com/uvtnLq8q](https://pastebin.com/uvtnLq8q)
> > ![image](https://user-images.githubusercontent.com/61608872/112086351-0135fc00-8bc7-11eb-9ad4-67c93d7e8c06.png)
> > the essentials build i use is EssentialsX-2.19.0-dev+99-1e0d7fb
> > but i haven't try to build 100 provided above
> > hope these extra info can help
> 
> try the one i linked :)

I am on the latest build and still have the same issue.

**Comment by hkkongou** [comment]
similar problem still exist at dev+106
it open account for fake players too 
![image](https://user-images.githubusercontent.com/61608872/116492919-17bf2980-a8d0-11eb-93d0-a096d07433f5.png)

**Comment by JRoy** [comment]
Hello, this issue has been mitigated in recent EssentialsX dev builds!

If you currently have damaged data, you can read more about the steps you can take to fix this and prevent further issues of this sort [here](https://github.com/EssentialsX/Essentials/issues/3956#issuecomment-779254544).

Download the latest dev build [here](https://essentialsx.net/downloads.html).
