### ISSUE TITLE
Errors when placing a spawner

### ISSUE THREAD

**Issue by punchinglikes** [EssentialsX/Essentials#4093]
### Type of bug

Error in console

### `/ess version` output

[19:02:04 INFO]: Server version: 1.8-R0.1-SNAPSHOT git-Spigot-c3c767f-33d5de3 (MC: 1.8)
[19:02:04 INFO]: EssentialsX version: 2.18.2.0
[19:02:04 INFO]: LuckPerms version: 5.3.3
[19:02:04 INFO]: PlaceholderAPI version: 2.10.9
[19:02:04 INFO]: Vault version: 1.7.3-b131
[19:02:04 INFO]: EssentialsXChat version: 2.18.2.0
[19:02:04 INFO]: EssentialsXSpawn version: 2.18.2.0
[19:02:04 INFO]: You are running an unsupported server version!

Yes I know I'm running 1.8, however it is listed on spigot that this is supported.

### Server startup log

https://paste.gg/p/anonymous/bcbd7ecdd8bd485697e90668d0717ead

### EssentialsX config files

https://paste.gg/p/anonymous/ddb220685364409698a09a8bf4e131b1

### Error log (if applicable)

https://paste.gg/p/anonymous/78f88a083cd545c2b324a0e45034f690

### Bug description

Whenever a spawner is place, an error about not being able to pass the BlockPlaceEvent to Essentials occurs.

### Steps to reproduce

Use a spawner plugin like Silkspawners to give yourself a spawner of any type.
Place the spawner that you gave yourself.

### Expected behaviour

No errors should occur

### Actual behaviour

Errors occur and it get's quite annoying.

**Comment by JRoy** [comment]
1.8 is not supported, you should be using Spigot or Paper 1.8.8

**Comment by punchinglikes** [comment]
This is Spigot 1.8.8

**Comment by punchinglikes** [comment]
> 
> 
> This is Spigot 1.8.8

My apologizes, i for some reason had Spigot 1.8, not 1.8.8

**Comment by JRoy** [comment]
> My apologizes, i for some reason had Spigot 1.8, not 1.8.8

You can download Paper 1.8.8 [by clicking here](https://papermc.io/api/v2/projects/paper/versions/1.8.8/builds/443/downloads/paper-1.8.8-443.jar) :)

**Comment by punchinglikes** [comment]
> 
> 
> > My apologizes, i for some reason had Spigot 1.8, not 1.8.8
> 
> You can download Paper 1.8.8 [by clicking here](https://papermc.io/api/v2/projects/paper/versions/1.8.8/builds/443/downloads/paper-1.8.8-443.jar) :)

paper actually threw a lot of errors for it's 1.8 version or else I would be using that over spigot

**Comment by punchinglikes** [comment]
Switching my server from 1.8 to 1.8.8 causes a huge error to occur on an attempt to login, just like how paper did it...

**Comment by JRoy** [comment]
> Switching my server from 1.8 to 1.8.8 causes a huge error to occur on an attempt to login, just like how paper did it...

what error?

**Comment by punchinglikes** [comment]
https://paste.gg/p/anonymous/ece24048a7a34afa81423d92ed3ed6b9 the error is repeated multiple times until i force kill it.

**Comment by punchinglikes** [comment]
> 
> 
> https://paste.gg/p/anonymous/ece24048a7a34afa81423d92ed3ed6b9 the error is repeated multiple times until i force kill it.

this is fairly interesting, if it happens on both spigot and paper, what could be the problem here? I have used these versions on other servers before with no issues.
