### ISSUE TITLE
Hex codes aren't added to kits correctly

### ISSUE THREAD

**Issue by Evidentsinger14** [EssentialsX/Essentials#4094]
### Type of bug

Other unexpected behaviour

### `/ess version` output

>....=>.... [20:25:25 INFO]: CONSOLE issued server command: /ess version
>.... [20:25:25 INFO]: Server version: 1.16.5-R0.1-SNAPSHOT git-Purpur-1022 (MC: 1.16.5)
>.... [20:25:25 INFO]: EssentialsX version: 2.19.0-dev+99-1e0d7fb
>.... [20:25:25 INFO]: LuckPerms version: 5.3.13
>.... [20:25:25 INFO]: PlaceholderAPI version: 2.10.9
>.... [20:25:25 INFO]: Vault version: 1.7.3-b131
>.... [20:25:25 INFO]: EssentialsXChat version: 2.19.0-dev+99-1e0d7fb
>.... [20:25:25 INFO]: EssentialsXSpawn version: 2.19.0-dev+99-1e0d7fb
>.... [20:25:25 INFO]: Fetching version information...
>.... [20:25:25 INFO]: Update checking disabled in config.

### Server startup log

https://paste.gg/p/anonymous/02fd0035cd414651ac54d087de862f56

### EssentialsX config files

https://paste.gg/p/anonymous/46c2f85e7b6e49b0abeb6c14a0793e7f

### Error log (if applicable)

n/a

### Bug description

Hex codes aren't added correctly to a kit when using /createkit in-game 

### Steps to reproduce

1. get an item
2. run /itemname &#FF0000Test
3. run /createkit test 1
4. run /kit test

### Expected behaviour

i should get the item named test in red

### Actual behaviour

i get an item named "&xTest" where "test" is in black

**Comment by triagonal** [comment]
Confirmed on:
```
[16:37:15 INFO]: Server version: 1.16.5-R0.1-SNAPSHOT git-Paper-571 (MC: 1.16.5)
[16:37:15 INFO]: EssentialsX version: 2.19.0-dev+99-1e0d7fb
[16:37:15 INFO]: Vault version: 1.7.3-b131
```
