### ISSUE TITLE
EssentialsX - New Player Spawn Rotation

### ISSUE THREAD

**Issue by MackenzieMolloy** [EssentialsX/Essentials#4102]
### Type of bug

Other unexpected behaviour

### `/ess version` output

Server version: 1.16.5-R0.1-SNAPSHOT git-Paper-579 (MC: 1.16.5)
EssentialsX version: 2.18.2.0
LuckPerms version: 5.3.3
PlaceholderAPI version: 2.10.9
Vault version: 1.7.3-b131
EssentialsXChat version: 2.18.2.0
EssentialsXSpawn version: 2.18.2.0

### Server startup log

https://paste.gg/p/anonymous/1caa68e8fbd64f84885d821bf20fa909

### EssentialsX config files

https://paste.gg/p/anonymous/90a077bd6c5c471e84a016b1ead347f5

### Error log (if applicable)

N/A

### Bug description

New-players spawn facing south, even when the set spawn location is set facing in another direction.

This only happens when the "newbies spawnpoint" location is set to "none", if set to "default" spawns new players facing the correct direction.

### Steps to reproduce

1. Set a spawn location that isn't facing south.
2. In the config of EssentialsX, set spawnpoint location to "none"
3.  Reload the essentials config
4. Join on a new account (to join as a new player), and you'll spawn facing south.

### Expected behaviour

The new player should spawn facing the direction set.

### Actual behaviour

The new player spawns facing south.

**Comment by triagonal** [comment]
This isn't an EssentialsX issue - while I was able to reproduce this behaviour, it also occurred without the plugin installed.

When setting the newbies spawn to `"none"`, EssentialsXSpawn doesn't attempt to influence where the player spawns at all. In this case, spawn location behaviour falls back to the world spawn, defined with `/setworldspawn`. If you run `/setworldspawn` with no arguments the default yaw angle is set to `0.0`, which is south. 

If you want your vanilla world spawn to spawn players using a different rotation, you need to use the full command `/setworldspawn <x> <y> <z> <angle>` where `<angle>` "Must be a yaw angle, measured in degrees with float number. -180.0 for due north, -90.0 for due east, 0.0 for due south, 90.0 for due west, to 179.9 for just west of due north, before wrapping back around to -180.0. Tilde notation can be used to specify a rotation relative to the executor's yaw angle." (https://minecraft.fandom.com/wiki/Commands/setworldspawn)
