### ISSUE TITLE
Server crash with /hat

### ISSUE THREAD

**Issue by LucidAPs** [EssentialsX/Essentials#4106]
### Type of bug

Error in console

### `/ess version` output

https://nekobin.com/biworatuki

### Server startup log

https://nekobin.com/gomecavuca

### EssentialsX config files

https://nekobin.com/linawebepi

### Error log (if applicable)

https://nekobin.com/viqesekiwi

### Bug description

I figure out why it happened, I had a command that would run /hat with an OP status but if the user had air in their hand then the crash would happen.

### Steps to reproduce

https://github.com/Spottedleaf/Tuinity/issues/281

### Expected behaviour

It shouldn't crash the server.

### Actual behaviour

It shouldn't crash the server.

**Comment by triagonal** [comment]
Cannot reproduce:
```
[03:36:58 INFO]: Server version: 1.16.5-R0.1-SNAPSHOT git-Paper-597 (MC: 1.16.5)
[03:36:58 INFO]: EssentialsX version: 2.19.0-dev+104-5171215
[03:36:58 INFO]: LuckPerms version: 5.3.21
[03:36:58 INFO]: Vault version: 1.7.3-b131
```

These are the steps I followed:
1. Log onto server as an OP.
2. Attempt to run /hat with nothing in my hand - no crash
3. Use /hat while holding another block - other block is now on my head
4. Attempt to run /hat again with nothing in my hand - no crash

When using /hat with nothing in my hand, all I received was the error "You must have something to wear in your hand!". Could you please try and reproduce your problem on one of our supported server implementations (CraftBukkit, Spigot, or Paper)?

**Comment by triagonal** [comment]
Closing - no response from OP. If this is still an issue and can be reproduced on supported server software, please reply to this thread with proper reproduction steps.
