### ISSUE TITLE
messages_en parameter for msgtoggle that others see when they try to message

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#411]
When a player tries to message another player with ./msgtoggle on, it tells them they have msg disabled, I wish to be able to customize this message in the messages_en.yml Or maybe I just cannot find it?

**Comment by drtshock** [comment]
It's `msgDisabledFor` in the messages.properties file.

**Comment by TomLewis** [comment]
Fantastic, my configs were outdated. 
Does it support new lines? \u00a7n?

**Comment by drtshock** [comment]
Possibly ;o

**Comment by TomLewis** [comment]
msgDisabledFor is not the correct variable. 
I changed this, and when people msg me with my toggle it just says:
"Has messages disabled" which is nowhere to be found in this document "messages_en"

**Comment by drtshock** [comment]
It is definitely the correct one :)

**Comment by TomLewis** [comment]
Nope.
`msgDisabledFor=\u00a76If you have an issue please create a support ticket; http://bit.ly/piratesupport Receiving messages \u00a7cdisabled \u00a76for \u00a7c{0}\u00a76.`
The message players get when /msg that person is _"Has messages disabled"_
I have reloaded both essentials and the serer. No dice.
