### ISSUE TITLE
StackOverflow on tab complete for disabled commands. [1.16.5] [PAPER] [2.19.0]

### ISSUE THREAD

**Issue by alekso56** [EssentialsX/Essentials#4115]
### Type of bug

Error in console

### `/ess version` output

v2.19.0-dev+104-5171215

### Server startup log

irrelevant

### EssentialsX config files

irrelevant, disable a command.

### Error log (if applicable)

irrelevant

### Bug description

[Server thread/ERROR]: [Essentials] Command pm failed:
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/pm ' in plugin Essentials v2.19.0-dev+104-5171215	
at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:141) ~[patched_1.16.5.jar:git-Paper-585]
	at com.earth2me.essentials.Essentials.onTabCompleteEssentials(Essentials.java:574) ~[?:?]
	at com.earth2me.essentials.Essentials.onTabComplete(Essentials.java:540) ~[?:?]
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:141) ~[patched_1.16.5.jar:git-Paper-585]
Caused by: java.lang.StackOverflowError

### Steps to reproduce

Disable a command;
attempt to use said disabled command.
If error doesn't happen immediatly, you can try adding a plugin that listens for that spesific command.

### Expected behaviour

No errors.

### Actual behaviour

Big errors.

**Comment by Octol1ttle** [comment]
Could not reproduce on 
![image](https://user-images.githubusercontent.com/61277953/115185242-e6d53c80-a0f8-11eb-8595-f304ddf696a8.png)
What did I do:
1) Disable /nick and /clear in the config, restart the server
2) Check if tab-completing works, it doesn't, and it doesn't throw any errors
3) Check if running the command works, it doesn't, and it doesn't throw any errors
4) Add [a plugin](https://github.com/l1ttleO/SamplePlugin) has the /nick command, restart the server
5) Check if tab-completing works, it does, and no errors are thrown
6) Check if running the command works, it does, and no errors are thrown

**Comment by Chew** [comment]
Can you please provide the full `/ess version` output? You only provided the Essentials version...

**Comment by alekso56** [comment]
It's the latest git version, downgrading to 2.19.0-dev-56 resolved the issue, it seems to happen after a certain amount of time has passed, im just going to stay on this old version and forget about the problem, i can't recreate it immediatly either. 
so the problem started somewhere between dev 56 to 105. latest paper version.

**Comment by JRoy** [comment]
Downgrading isn't a proper fix lol. Will investigate further sooner than later
