### ISSUE TITLE
[REQUEST] The ability to toggle payments

### ISSUE THREAD

**Issue by GiansCode** [EssentialsX/Essentials#413]
Much like we have /msgtoggle, it'd be nice to see the same or a similar thing for payments. This will help solve the paying issues on some servers where they get YTers to play and players just pay them; thus; ruining the fun.

**Comment by Twi5TeD** [comment]
great idea :+1:

**Comment by SupaHam** [comment]
The [`minimum-pay-amount`](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/config.yml#L602) config option was added to combat this a little. Is it not good enough for you?

**Comment by Twi5TeD** [comment]
Would be better for a toggle option

**Comment by GiansCode** [comment]
The reason for this is because players pay the YouTubers their money and stuff

**Comment by SupaHam** [comment]
So does this feature stop players paying other players completely or does it just hide the message and still accept the money?

**Comment by Twi5TeD** [comment]
Stops them paying them until they toggle it back on

**Comment by SupaHam** [comment]
This has been introduced in 2493c65. You can grab the feature from [build 416](https://ci.drtshock.net/job/EssentialsX/) on the CI server.

Check out the [Pay Toggle](https://github.com/drtshock/Essentials/wiki#pay-toggle) section in the wiki for documentation.
