### ISSUE TITLE
Unexpected /v behavior

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#4134]
### Type of bug

Other unexpected behaviour

### `/ess version` output

[19:42:43 INFO]: Server Version: 1.8.8-R0.1-SNAPSHOT git-Spigot-21fe707-e1ebe52 (MC: 1.8.8)

[19:42:43 INFO]: EssentialsX Version: 2.18.2.0

[19:42:43 INFO]: PlaceholderAPI Version: 2.10.9

[19:42:43 INFO]: LuckPerms Version: 5.3.0

[19:42:43 INFO]: Vault Version: 1.7.3-b131

[19:42:43 INFO]: EssentialsXChat Version: 2.18.2.0

[19:42:43 INFO]: You are running a server with limited API functionality. EssentialsX will still work, but certain features may be disabled.

### Server startup log

https://gist.github.com/GeGrieftGames/4d09c91ea44c19ebf7a47bffa94a1a7e

### EssentialsX config files

https://gist.github.com/GeGrieftGames/96437a2986eeb03f48546dfdfbc64c5c

### Bug description

When a Player1 is  using "/v Player2" instead of "/ev Player2" or "/essentials:v Player2" he gets vanished instead of unvanishing Player2.

### Steps to reproduce

1. Have two players online (Player: 1)
2. Have one player vanished (Player: 2)
3. Player1 enters "/v Player2"
4. Player1 get vanished
5. Player1 enters "/essentials:v Player2" or "/ev Player2"
6. Player2 get unvanished

### Expected behaviour

When Player1 enters "/v Player2" (Player2: Vanished) Player2 should get unvanished.

### Actual behaviour

When Player1 enters "/v Player2" (Player2: Vanished) Player1 gets vanished.

**Comment by Octol1ttle** [comment]
You have a plugin that overrides `/v`, therefore EssentialsX is not causing this issue
You can see which commands are being handled by other plugins by using `/ess commands`

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/68118361/116823705-2df60f80-ab86-11eb-870a-7f9ca089fde4.png)

**Comment by ghost** [comment]
==> No plugin is overriding the command. ("/v" ist the essentials command) I have the same problem on my private friend server with only essentials for 1.8.8 installed

**Comment by pop4959** [comment]
Unable to reproduce this bug on `2.19.0-dev+103-cfc5ea2`. Since you're running an old version I would recommend trying to update first and see if the issue still persists.

**Comment by ghost** [comment]
> Unable to reproduce this bug on `2.19.0-dev+103-cfc5ea2`. Since you're running an old version I would recommend trying to update first and see if the issue still persists.

I'm having the latest Version: EssentialsX 2.18.2 or is there any Dev Version
![image](https://user-images.githubusercontent.com/68118361/116823895-77932a00-ab87-11eb-9ce8-3171eed0305b.png)

**Comment by pop4959** [comment]
That's the spigot release, you can find the latest here: https://essentialsx.net/downloads.html

**Comment by ghost** [comment]
> That's the spigot release, you can find the latest here: https://essentialsx.net/downloads.html

Ohh. I have tested the last Dev-Version and have the same problem.

**Comment by pop4959** [comment]
Try reproducing without any other plugins installed except Essentials. Does it still happen?

**Comment by GeGrieftGames** [comment]
> Try reproducing without any other plugins installed except Essentials. Does it still happen?

Yes i have already tested it on my friend server without any other plugin and it doesn't work.

**Comment by ghost** [comment]
The problem on the second server was my mistake. On the main server I found an Plugin that is adding some essentials commands to the commands.yml file.
