### ISSUE TITLE
UUID error for non -3 userdata

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#4146]

**Comment by JRoy** [comment]
uhhhhHHH, has `BloofMC` ever joined your server, and what about `Sky_BlueMC`?

**Comment by iielijah** [comment]
Sky_BlueMC hasn't but bloofmc has

**Comment by iielijah** [comment]
oh wait i see.. if they haven't played on the server or better yet joined then is safe to delete those uuid files.

**Comment by iielijah** [comment]
ope now it's just spamming my console with that error from the log

**Comment by iielijah** [comment]
Resolved by deleting those uuids from main overworld folder. My bad.
