### ISSUE TITLE
Option to disable certain color codes

### ISSUE THREAD

**Issue by Sikatsu** [EssentialsX/Essentials#415]
Is there an option to blacklist certain color codes? Like the dark ones? To keep the chat cleaned.

And not sure if this is possible, but a limit on the amount of color codes? So they can't make a rainbow name.

**Comment by drtshock** [comment]
No. But you can differentiate between color and format (rainbow, bold, etc).

**Comment by Sikatsu** [comment]
Thanks for your answer, then I'll just add it to the server rules. :)

**Comment by mdcfe** [comment]
This will be resolved once #1441 is merged.

**Comment by Sikatsu** [comment]
What are the exact permissions? This applies to nicknames too right?

**Comment by mdcfe** [comment]
The permissions are `essentials.<base>.<format>`, where `<base>` is exactly like the old formats (`nick`, `chat` etc) and the `<format>` is the relevant format from [ChatColor](https://papermc.io/javadocs/paper/1.13/org/bukkit/ChatColor.html#enum.constant.summary) - for example, `essentials.nick.dark_aqua`.

**Comment by Sikatsu** [comment]
Cool, thanks!
