### ISSUE TITLE
Socialspy improvement

### ISSUE THREAD

**Issue by Sikatsu** [EssentialsX/Essentials#416]
Are you able to make a configurable option that when someone sends a message to me, it will not also show the socialspy message? Why would I want to see the socialspy message if he already sends it to me? Currently when I'm chatting with someone in private, every message will be double :/

**Comment by drtshock** [comment]
Simple but genius.

**Comment by Sikatsu** [comment]
:smiley:

**Comment by Omarlatif** [comment]
You can do that, quite simply. For the duration of your 'private conversation' with someone, turn off socialspy, i'm sure that you have other staff members that are able to check on socialspy while you doing that.

**Comment by Sikatsu** [comment]
That's just stupid, how many times do we have a private conversation? Do we really need to think about disabling socialspy everytime? It just doesn't make sense and will be a nice fix.

**Comment by ChanceSD** [comment]
I agree, i think this would be a nice addition.

**Comment by drtshock** [comment]
I'm thinking we can just check on player join. I believe that's what I do in Factions.

**Comment by Sikatsu** [comment]
What do you mean check on player join?

**Comment by drtshock** [comment]
If they have social spy enabled on join and they don't have the permission, set it to false.

**Comment by Sikatsu** [comment]
But what has that to do with me seeing double messages if I'm having a private conversation with a player?

**Comment by drtshock** [comment]
oh sorry, I was thinking this was a different ticket. not embarrassing at all.

**Comment by Sikatsu** [comment]
Haha, confusing, no problem ;)

**Comment by SupaHam** [comment]
This has been fixed in c4c303db. You can grab the fix from [build 409](https://ci.drtshock.net/job/EssentialsX/) on the CI server.
