### ISSUE TITLE
Essentialsx disabled

### ISSUE THREAD

**Issue by HeberonYT** [EssentialsX/Essentials#4162]
### Type of bug

Error in console

### `/ess version` output

Essentials v2.19.0-dev+121-d00b90c

### Server startup log

https://pastebin.com/raw/6YJRE18Z

### EssentialsX config files

https://pastebin.com/raw/PDyBF34b

### Bug description

Hi, I have updated essentialsx and all versions higher than # 117 spam the console and disable all essentials commands. I must stick to version # 117 to avoid this bug.

paper-1.16.5-#704
EssentialsX-2.19.0-dev+121-d00b90c
Java 8

### Steps to reproduce

1-Install version EssentialsX-2.19.0-dev + 121-d00b90c
2-Start the server
3-Connect to the server and use any essentials command, example, / etps
4-You will get a lot of spam on the console.

### Expected behaviour

I would like it to work

### Actual behaviour

the plugin is disabled when starting the server, it only happens with versions higher than Dev 117

**Comment by mdcfe** [comment]
I can't replicate this on a plain install of dev+121 and Paper 704 (tested on both Oracle JRE 8u51 and AdoptOpenJDK 16.0.1+9):
```
[12:14:45 INFO]: Server version: 1.16.5-R0.1-SNAPSHOT git-Paper-704 (MC: 1.16.5)
[12:14:45 INFO]: Brand version: Paper
[12:14:45 INFO]: EssentialsX version: 2.19.0-dev+121-d00b90c
[12:14:45 INFO]: Vault is not installed. Chat and permissions may not work.
[12:14:45 INFO]: Fetching version information...
[12:14:45 INFO]: You're running the latest EssentialsX dev build!
```

Could you try replicating this with only EssentialsX installed and no other plugins?

**Comment by JRoy** [comment]
Considering we have at least 624 other users running these changes I'm going to assume there is something wrong with your java version or this is a bug with another plugin.

**Comment by HeberonYT** [comment]
I hope they pay more attention to the reports and not be guided by the crowd.
https://github.com/EssentialsX/Essentials/pull/4166

**Comment by mdcfe** [comment]
> I hope they pay more attention to the reports and not be guided by the crowd.
> #4166

We asked for more information in your issue and you chose not to provide it. 

As mentioned in #4166, bloodshot provided a test case that could reliably replicate the issue, triagonal was able to pinpoint the exact logic that triggered it, and bloodshot then was able to establish that the cause was specific third-party plugins (hence why we asked you to replicate with no third-party plugins), which in turn triggered a JDK bug.
