### ISSUE TITLE
Sign Creating Bug/Plugin Clash

### ISSUE THREAD

**Issue by xtechgamer735** [EssentialsX/Essentials#417]
Hey,

Ive found the plugin SignEdit (and maybe other similar plugins which change colour of signs) causes users to create any enabled signs without permissions. They are able to use '&1&1' and maybe some other colour code, which seems to override all creation permissions given or denied in permissions. 

1: &1&1[sell]
2: 1
3: cobble
4: $9999

That allows the player to sell 1 cobble for $9999. Im on 2.0.1-b267, and have tested it with Sell/Disposal and in theory will work on all signs.

**Comment by drtshock** [comment]
It's an issue with that plugin. We've fixed that issue.
