### ISSUE TITLE
Bug with /hat

### ISSUE THREAD

**Issue by msmanui** [EssentialsX/Essentials#4179]
### Type of bug

Other unexpected behaviour

### `/ess version` output

Using the last version dev build

### Server startup log

Nothing to do here.

### EssentialsX config files

Nothing to do here.

### Bug description

I have a helmet that when u put it on it will apply some effects like nightvision.
The issue come if i put /hat will remove the helmet but the effect will stay anyway 

### Steps to reproduce

1. Put a helmet that run effect on apply
2. Put any block in your hand and run /hat
3. The block will replace the helmet but the effect will stay
4. 

### Expected behaviour

Removing the effect when u run /hat

### Actual behaviour

It doesnt remove the effect, it stays.

**Comment by mdcfe** [comment]
The `/ess version` output, startup log and config files fields are required for a reason. Please fill out a bug report with the full details as requested in the template.

**Comment by msmanui** [comment]
> The `/ess version` output, startup log and config files fields are required for a reason. Please fill out a bug report with the full details as requested in the template.

There is no need, this happens with every .jar. U only need to remove effects when applying /hat command, nothing else

**Comment by Chew** [comment]
It's extremely crucial you provide information when requested. There's nothing we can do without the required information. You are more than welcome to test on multiple JARs, but if you can reproduce it, send the complete, unmodified `/ess version` output. Otherwise, there's nothing we can do.

**Comment by JasonHorkles** [comment]
Also I should note it seems they're using a plugin to apply effects since u can't do that with vanilla, so there's no reason essx should really fix it anyways
