### ISSUE TITLE
Essentials UUID issue

### ISSUE THREAD

**Issue by AdnanMia** [EssentialsX/Essentials#418]
Player on my server changed his name to ThatFrazbo from CaptainFrazbo. His balance on /baltop stayed and showed his new name, however when you checked his balance with the /bal command it shows $40 (old balance 250k+).

.

**Comment by drtshock** [comment]
Can you paste your server startup log.

**Comment by AdnanMia** [comment]
https://paste.ee/p/pHsX9

**Comment by AdnanMia** [comment]
Hmm, maybe /baltop is bugged since I removed his userdata file. It even recreated it however he still shows on baltop.

**Comment by drtshock** [comment]
That + your server is running in offline mode so you probably didn't get switched over to the new UUID.

**Comment by AdnanMia** [comment]
I'm using BungeeCord which is in online mode. Restarted the server multiple times, he still shows on /baltop.
