### ISSUE TITLE
Got this error

### ISSUE THREAD

**Issue by Thefluffypvper1** [EssentialsX/Essentials#4185]
### Type of bug

Error in console

### `/ess version` output

![image](https://user-images.githubusercontent.com/74934708/120137718-4191a600-c218-11eb-86b3-3dacb7ee2c86.png)

### Server startup log

https://paste.helpch.at/nuqovogiwa.md

### EssentialsX config files

https://paste.helpch.at/vageresuru.coffeescript 

### Error log (if applicable)

https://paste.helpch.at/ogujaqetap.bash

### Bug description

When I log in it gives that error

### Steps to reproduce

Latest version of dev build, I just logged in

### Expected behaviour

No get this error in console 

### Actual behaviour

Just gives a error in console.

**Comment by pop4959** [comment]
WineSpigot isn't a supported server software.
