### ISSUE TITLE
Essentials not start (gson execption)

### ISSUE THREAD

**Issue by Nobodyno-boop** [EssentialsX/Essentials#4187]
### Type of bug

Error in console

### `/ess version` output

Essentials not loaded. but we use `EssentialsX-2.18.2.0.jar`

### Server startup log

https://hastebin.com/jaqufisice.yaml

### EssentialsX config files

https://paste.gg/p/anonymous/20765c5559bf4e5b8402c08cc84fabbc

### Error log (if applicable)

https://paste.gg/p/anonymous/62784fc80d884ca2b110c57abefd3f36

### Bug description

Its a restart daily by the server, but for no reseaon essentials won't work with a strange error log see : https://imgur.com/a/NRDEd6H

### Steps to reproduce

1. start the server... :x 

### Expected behaviour

start normaly...

### Actual behaviour

Just start the server and its not work :/

**Comment by JRoy** [comment]
Your items.json was messed with, remove it from your Essentials folder (found in your plugins folder)
