### ISSUE TITLE
Prefix placeholder in front of the name when a player joins

### ISSUE THREAD

**Issue by Sikatsu** [EssentialsX/Essentials#419]
Is it possible that a players rank will also show up when he joins? 
When I try to use PlaceholderAPI it shows up like this: http://prntscr.com/a37pez

**Comment by drtshock** [comment]
Where are you setting the join message?

**Comment by Sikatsu** [comment]
In the essentials config.yml?

**Comment by drtshock** [comment]
I'm confused what you mean by placeholderapi then.

**Comment by Sikatsu** [comment]
Well that's me being hopeless, but is there anyway to get the rank prefix in it using essentials?

**Comment by Jumpy91** [comment]
Im using essentialsxchat there are the ranks displayd in joinmessages. without the chat module not.

**Comment by mdcfe** [comment]
EssentialsX doesn't support PlaceholderAPI replacements, so it can't be used with PlaceholderAPI placeholders. There currently isn't a way to include prefixes or ranks in the custom join message.

**Comment by pop4959** [comment]
Discussion for placeholders and other chat enhancements in Essentials should be moved to #2391. Currently it does not support this, as md mentioned.
