### ISSUE TITLE
The user User not found! does not exist.

### ISSUE THREAD

**Issue by JRoy** [EssentialsX/Essentials#4195]
### Discussed in https://github.com/EssentialsX/Essentials/discussions/4194

<div type='discussions-op-text'>

<sup>Originally posted by **AaronBDesign** June  4, 2021</sup>
This error has been showing up frequently in my console with seemingly no cause. Happens multiple times every minute.

https://pastebin.com/ESxwCKUq</div>

**Comment by AaronBDesign** [comment]
**/ess version:**
Server version: 1.16.5-R0.1-SNAPSHOT git-Paper-585 (MC: 1.16.5)
Brand version: Paper
EssentialsX version: 2.19.0-dev+134-fbb3a9a
LuckPerms version: 5.1.93
PlaceholderAPI version: 2.10.9
Vault version: 1.7.3-b131
EssentialsXGeoIP version: 2.19.0-dev+134-fbb3a9a
EssentialsXSpawn version: 2.19.0-dev+134-fbb3a9a
Citizens version: 2.0.27-SNAPSHOT (build 2295)
Fetching version information...
Unable to check your version! Self-built? Build information: id:'fbb3a9a' branch:'2.x' isDev:true.

**/plugins:**
Plugins (124): AcoWorth*, AdvancedCrates, AdvancedDiscordLogger*, AdvancedMinecraft*, ajLeaderboards, ajParkour, Alice, AnCasino, AnimatedFrames*, ArmorStandAdjustor, AtlasioX-AnvilNS*, AutoRestart*, BeastWithdraw, BetterRTP, BetterStaffChat*, BKCommonLib, Blackjack, BossShopPro, BuildMyText, BungeeGuard, BuycraftX, ChatEmojis, ChatInjector, ChatSentry, Citizens, CitizensGUI, CitizensIntergration*, ColorGradient, CoreProtect, DeluxeAnnounce, DeluxeCombat, DeluxeMenus, DeluxeTags, Denizen, DiscordSRV, Donation-Store-Bukkit*, DoorsReloaded, eco, EcoEnchants, eGlow, Essentials, EssentialsGeoIP, EssentialsSpawn, EvenMoreFish, EvolutionWebhook, EZColors, GambleBarPro*, GCoreLegacy, GiveMeSomeSpace, GoldenCrates, Graves, GriefPrevention, GSit, GSlotMachine, Harbor, HeadDatabase, HeadDisplays, HolographicDisplays, HolographicExtension, HolographicPlaceholders, ImageOnMap, InfoHeads, InsaneAnnouncer, Interactions, InteractiveChat, InteractiveChatDiscordSrvAddon, InventorySaver, ItemFilter, Jobs, JoinEventsPro, LastLoginAPI, LibsDisguises, LiteBans, LitePlaytimeRewards, LuckPerms, MCStatistics*, MineChess, MiniaturePets, Multiverse-Core, NexEngine, PacketListenerApi*, PL-Hide, Pl3xMap, PlaceholderAPI, Plan, PlayerParticles, PlayerWarps, PremiumVanish, ProdigyNightclub, ProperAlias, ProtectionLib, ProtocolLib, QuickShop, QuickShopList, ReportSystem*, RocketPlaceholders, RotatingHeads*, Roulette, SAML, SimplePets, SimplePortals, SimpleRename, SkyChanger, spark, SpawnRateControl, SpecializedCrates, StaffProtection*, StatTrackers, STN-Studios-API, TAB, Trade, Vault, VentureChat, Votifier, VotingPlugin, VoxelSniper, WeatherVote, WolfyUtilities, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, zAuctionHouse-Discord, zAuctionHouseV3
