### ISSUE TITLE
Error when going to a warp after updating the plugin

### ISSUE THREAD

**Issue by 4drian3d** [EssentialsX/Essentials#4207]
### Type of bug

Other unexpected behaviour

### `/ess version` output

07.06 18:08:09 [----] -----@gmail.com ran command: ess version
07.06 18:08:09 [Server] INFO CONSOLE issued server command: /ess version
07.06 18:08:09 [Server] INFO Server version: 1.16.5-R0.1-SNAPSHOT git-Purpur-1159 (MC: 1.16.5)
07.06 18:08:09 [Server] INFO Brand version: Purpur
07.06 18:08:09 [Server] INFO EssentialsX version: 2.19.0-dev+141-300daea
07.06 18:08:09 [Server] INFO PlaceholderAPI version: 2.10.10-DEV-123
07.06 18:08:09 [Server] INFO LuckPerms version: 5.3.42
07.06 18:08:09 [Server] INFO Vault version: 1.7.3-b131
07.06 18:08:09 [Server] INFO EssentialsXChat version: 2.19.0-dev+141-300daea
07.06 18:08:09 [Server] INFO EssentialsXSpawn version: 2.19.0-dev+141-300daea
07.06 18:08:09 [Server] INFO Citizens version: 2.0.27-SNAPSHOT (build 2315)
07.06 18:08:09 [Server] INFO Towny version: 0.97.0.2
07.06 18:08:09 [Server] INFO Obteniendo información de versión...
07.06 18:08:09 [Server] INFO ¡Estás ejecutando la última compilación de EssentialsX!

### Server startup log

https://pastebin.com/kJKF2cSL

### EssentialsX config files

https://pastebin.com/9xw2bRgS

### Bug description

When upgrading from a previous EssentialsX dev build(138) to the dev build 141 version, the error https://imgur.com/a/qsuYh73 occurs when using "/warp survival", "/warp nether" and other commands to go to a warp.
The configuration file for "/warp survival", in case it is useful, contains:

world: Arcadia
x: -213.42463933908064
y: 74.0
z: -188.50185919665637
yaw: -90.59122
pitch: -1.5686792
name: Survival
lastowner: 489234b2-ac67-3f26-88d0-c0116bdd8f00

### Steps to reproduce

1. Previously use a version of EssentialsX 2.19(dev build) with warps set.
2. Upgrade to EssentialsX dev build 141
3. It will not transport to the warp set in the previous version and will show the error only on the client.

### Expected behaviour

That the warp set in a previous version works correctly.

### Actual behaviour

It shows an error when executing the command only in the user https://imgur.com/a/qsuYh73

**Comment by JRoy** [comment]
I just fixed a bug about 10 seconds before you posted this, try the latest build from [https://essentialsx.net/downloads.html](https://essentialsx.net/downloads.html) and let me know if this is still a problem.
