### ISSUE TITLE
players data duping

### ISSUE THREAD

**Issue by Twi5TeD** [EssentialsX/Essentials#422]
so i looked onto baltop and see that my players have 2 versions of themselves one being capitalized and one being lowercased 
https://gyazo.com/2d662718f4cb239b58144b90d1da8d68 these two data files are from the same person how can i fix this?

lowercased version
npc: true
lastAccountName: rubricals
money: '0'

capitalized version
lastAccountName: Rubricals
timestamps:
  login: 1455806600153
  lastteleport: 1455810419065
  logout: 1455811195504
  kits:
    epic: 1455791608263
    unigod: 1455791840521
ipAddress: ip
lastlocation:
  world: PlotWorld
  x: -53.30000001192093
  y: 60.200000047683744
  z: -8.699999988079075
  yaw: 197.04492
  pitch: 83.34807
logoutlocation:
  world: PlotWorld
  x: -50.75506947029412
  y: 66.0
  z: -21.207848158532563
  yaw: 351.77637
  pitch: 24.33907
afk: false
godmode: false
money: '1000000000'

**Comment by drtshock** [comment]
Use online mode.

**Comment by Twi5TeD** [comment]
im using this on bungee my prison has to be offline mode

**Comment by vemacs** [comment]
Enable ip-forwarding in Bungee's configuration and bungeecord in spigot's configuration. Consider reading the wiki before setting up your server.

**Comment by Twi5TeD** [comment]
ip-forwarding in the bungee config is set to true and bungeecord is set to true in the spigot.yml and inside the server properties online mode is set to false 
i don't need to read the wiki as i have already set it up correctly.

**Comment by vemacs** [comment]
If it was set up and firewalled correctly, you wouldn't have the issue. Are you sure the UUIDs are proper online-mode UUIDs in userdata?

**Comment by Twi5TeD** [comment]
5890cbd1-e2ff-3cc8-a44a-d3acc1d24714 this one i looked up on namemc and does show anything so this must be the fake one and this one 008027a2-26df-44c7-89b4-2c4f4fd71b07 i looked up and it shown the correct person. plus im not the only one whos had this issue

**Comment by drtshock** [comment]
This isn't an issue that's possible with online mode. There is something wrong with your setup.
