### ISSUE TITLE
Renamed items cannot be deleted with /eclear

### ISSUE THREAD

**Issue by 4drian3d** [EssentialsX/Essentials#4227]
### Type of bug

Other unexpected behaviour

### `/ess version` output

CONSOLE issued server command: /ess version
12.06 13:42:53 [Server] INFO Server version: 1.16.5-R0.1-SNAPSHOT git-Purpur-1169 (MC: 1.16.5)
12.06 13:42:53 [Server] INFO Brand version: Purpur
12.06 13:42:53 [Server] INFO EssentialsX version: 2.19.0-dev+154-def4180
12.06 13:42:53 [Server] INFO PlaceholderAPI version: 2.10.10-DEV-null
12.06 13:42:53 [Server] INFO LuckPerms version: 5.3.42
12.06 13:42:53 [Server] INFO Vault version: 1.7.3-b131
12.06 13:42:53 [Server] INFO Citizens version: 2.0.27-SNAPSHOT (build 2302)
12.06 13:42:53 [Server] INFO Fetching version information...
12.06 13:42:53 [--------] ------@gmail.com ran command: ess version
12.06 13:42:53 [Server] INFO You're 4 EssentialsX dev build(s) out of date!
12.06 13:42:53 [Server] INFO Download it here: https://essentialsx.net/downloads.html

### Server startup log

https://pastebin.com/wzB8txNy

### EssentialsX config files

https://pastebin.com/ACA9hybv

### Bug description

When executing: "/eclear %player% gold_ingot 1" on a new item, it is deleted correctly. 
But if you rename the item on an anvil to any name, e.g. "golden ingot", it will say: "Player 'player name' does not do 1 of gold_ingot".

### Steps to reproduce

1. Having several items of the same type in the inventory.
2. Use /eclear (user) (item) (quantity), it will work correctly.
3. Rename the other items on an anvil.
4. Execute the same command.
5. The items will not be removed and the message will appear as if you have none.

### Expected behaviour

Renamed items are deleted correctly.

### Actual behaviour

It does not recognize renamed items when trying to delete them.

**Comment by triagonal** [comment]
This is intended behaviour for the Essentials `/clear` command. If you need to clear every item of the same type regardless of item meta then you can use the vanilla `/minecraft:clear` command.
