### ISSUE TITLE
EssentialsX /clear Not Working As Expected

### ISSUE THREAD

**Issue by TailedPoog420** [EssentialsX/Essentials#4248]
### Type of bug

Other unexpected behaviour

### `/ess version` output

Server version: 1.16.5-R0.1-SNAPSHOT 2991-Spigot (MC: 1.16.5)
EssentialsX version: 2.18.2.0
EssentialsXChat version: 2.18.2.0
LuckPerms version: 5.3.47

### Server startup log

https://paste.gg/p/anonymous/0312d1109ab0492bbc52b0978fa64021

### EssentialsX config files

https://paste.gg/p/anonymous/0312d1109ab0492bbc52b0978fa64021

### Error log (if applicable)

https://paste.gg/p/anonymous/0312d1109ab0492bbc52b0978fa64021

### Bug description

When executing ` clear PLAYERNAMEHERE COBBLESTONE 64 ` in console, if a player has any number of cobblestone in their off-hand slot, it is not removed.

I expected to be able to remove any specified number of an item using that command even if it was in their off-hand slot or in their inventory.

Pls fix. ;o;

### Steps to reproduce

Execute ` clear PLAYERNAMEHERE COBBLESTONE 64 ` in console while a player has any number of cobblestone in their off-hand slot and it will not be removed.

### Expected behaviour

I expected to be able to remove any specified number of an item using that command even if it was in their off-hand slot or in their inventory.

### Actual behaviour

Only removes the specified number of items from the inventory, not their armor or off-hand slot as well.

**Comment by JRoy** [comment]
related to #3810
