### ISSUE TITLE
Early 1.9 Support

### ISSUE THREAD

**Issue by Platinteufel** [EssentialsX/Essentials#425]
Hey Essentials-Team :)
According to this thread in spigot forums
 https://www.spigotmc.org/threads/minecraft-1-9-more-info.124273/ 
Spigot/Bukkit 1.9 will be released at Feb 26th. The 1.9 API should be already available on git. Is it possible to support early builds in time? That would be awesome, I really like your work. :)

**Comment by drtshock** [comment]
Yes, we plan on updating to 1.9

**Comment by Platinteufel** [comment]
Nice to hear :) How complex it will be updating Essentials to 1.9?

**Comment by BradyMitch** [comment]
The unbreakable tag still isn't available within /item and kits, wish it was :(

**Comment by drtshock** [comment]
The plugin will mostly work with 1.9 the second it's released. Though we will need to add in support for new materials and nms support for spawners. If spigot for 1.9 is released on Friday, I don't see a reason we can't have a dev build out over the weekend.

**Comment by vemacs** [comment]
We shouldn't need additional NMS for spawners as 1.9 should have BlockStateMeta. New entities and such need to be implemented, however.

> The unbreakable tag still isn't available within /item and kits, wish it was :(

Unbreakable is Spigot-only, not Spigot-CraftBukkit. I'll see about implementing it, however.
