### ISSUE TITLE
Skull command performance

### ISSUE THREAD

**Issue by LucidAPs** [EssentialsX/Essentials#4253]
### Type of bug

Performance issue or memory leak

### `/ess version` output

https://nekobin.com/sixolaxiba

### Server startup log

https://nekobin.com/janiduzoxi

### EssentialsX config files

https://nekobin.com/toboqelacu

### Bug description

The skull command has a noticeable performance impact.
![image](https://user-images.githubusercontent.com/42933023/122674826-71144c80-d1df-11eb-958b-07dff689f34b.png)
https://timings.pl3x.net/?id=49e130b748624813b32b0644a9a79495

### Steps to reproduce

Using the /skull command

### Expected behaviour

No or less of a performance hit.

### Actual behaviour

A noticeable performance impact

**Comment by imDaniX** [comment]
Isn't it because of offline mode and/or SkinsRestorer?

**Comment by JRoy** [comment]
The skull command is as optimized as it can get at the moment, owner lookups are done off the main thread and not much else can be done async.
