### ISSUE TITLE
error in console

### ISSUE THREAD

**Issue by Bobbbe** [EssentialsX/Essentials#4254]
### Type of bug

Error in console

### `/ess version` output

thread/INFO]: [Essentials] Enabling Essentials v2.19.0-dev+166-d4e194f

### Server startup log

https://pastebin.com/zE5bDGec

### EssentialsX config files

https://pastebin.com/xJppr7xF

### Bug description

just an error report

### Steps to reproduce

Spigot 1.17
essentialsx v2.19.0-dev+166-d4e194f

### Expected behaviour

error in console

### Actual behaviour

error in console

**Comment by Chew** [comment]
The log is incredibly useless... we need an ENTIRE latest.log before we can begin to solve this. You probably also need the 1.17 branch but not sure: https://github.com/EssentialsX/Essentials/actions/runs/939460984
