### ISSUE TITLE
My zombie not attacking villager

### ISSUE THREAD

**Issue by ZayanPlayz** [EssentialsX/Essentials#4263]
### Type of bug

Other unexpected behaviour

### `/ess version` output

Error: zip file closed

### Server startup log

No need

### EssentialsX config files

https://paste.gg/p/anonymous/5afb27d2007742e881f8d5391ae5f586

### Error log (if applicable)

No need

### Bug description

zombie is not attacking villager. Plugins
AccountGuard*, AltDetector, AureliumSkills, BedWars, BlockVPN*, DiscordSRV, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, floodgate, Geyser-Spigot, GriefPrevention, HolographicDisplays, LoginSecurity*, Multiverse-Core, NoMobLag, NoPlugins, OnePlayerSleep*, PlaceholderAPI, PowerRanks, SBAHypixelify, TAB, Vault, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion, WorldEdit, WorldGuarddoes 

### Steps to reproduce

1. spawned villager
2. spanned zombie
3. in creative
4. zombie not attacking villager

### Expected behaviour

I want the villager to turn into a zombie

### Actual behaviour

I want the villager to turn into a zombie

**Comment by Chew** [comment]
You've provided nothing we can use to help diagnose the issue. If `/ess version` isn't working then we NEED a startup log before we can even look into the issue. 
Additionally, I don't believe Essentials messes with this. It's vanilla or whatever server software you use behavior. I believe the difficulty needs to be hard and the local difficulty needs to be high or something.

**Comment by ferdinand-ypsilant** [comment]
I am using Minecraft PE and that too in hard mode and never changed to creative mode. But the day before th Last update, everything was okay and surprisingly after update zombie and villagers got a new kind of friendship 🥲. What to do to transform them into zombie villager!?
