### ISSUE TITLE
give commands

### ISSUE THREAD

**Issue by anemul** [EssentialsX/Essentials#427]
@drtshock I don't mean to a be a pest , I just figure that the lack of response is from a lack of me being able to convey what I mean , so here is a video of what I am talking about . In the video it shows me giving the command give and the essentials response in chat , then it shows winning at chat reaction , but with no response of being given an item , even though I was given an emerald . There is a screen shot at the end of the video showing the exact same response in server console that I got from manually issuing the command .[http://www.kwik-kar.net/Console Commands.mp4
 ](url)

**Comment by drtshock** [comment]
Can you please properly explain what you did, what's happening, and what you expect to happen?

**Comment by anemul** [comment]
When I type /give Synather diamond 1 , Essentials passes the output of Giving 1 of diamond to Synather. 
But when someone/me wins at Chat Reaction and you win an item instead of money , it uses  /give Synather diamond 1 to give them the reward for winning , but Essentials does not output to chat Giving 1 of diamond to Synather . 
I expect Essentials to pass the same output as in the first example when we win Chat Reaction . I have recorded it if that helps , it may help clear things up a little . Thanks in advance . [http://www.kwik-kar.net/Console Commands.mp4](http://www.kwik-kar.net/Console Commands.mp4)

**Comment by drtshock** [comment]
How does vanilla minecraft behave?

**Comment by anemul** [comment]
I'm not sure what you are asking ? If you are asking how it works without EssentialsEX plugin installed , it just returns the default output : [17:19:00 INFO]: CONSOLE issued server command: /give Synather diamond 1 
but with EssentialsEX installed it is as I said above .

**Comment by drtshock** [comment]
Yes but do it with /minecraft:give to see what the behavior is. We just mimic what they do.

**Comment by anemul** [comment]
drtshock When I do /give Synather diamond 1 Essentials returns Giving 1 of diamond to Synather
 When I do /minecraft:give Synather diamond 1 it returns Given [Diamiond] x 1 to Synather that is basically the same when typed manually from both methods , except EssEX is colored and worded slightly different . 
However when we win the Chat Reaction typeing game , that plugin uses the very same command as EssEX does : /give @p diamond 1 but returns nothing to let anyone know that they received the reward . Now without EssEX in the plugin folder it returns CONSOLE issued server command: /give Synather diamond 1 .

**Comment by drtshock** [comment]
Yes but when you do /minecraft:give does it show it to the player receiving the item?

**Comment by anemul** [comment]
no not to them .

**Comment by anemul** [comment]
it does show for myself , except when the command is issued through Chat Reaction . I can see what you are driving at .

**Comment by drtshock** [comment]
Sounds like we are mimicking vanilla behavior just fine :)

Why not have your plugin also execute a command to tell the players they are getting an item?

**Comment by anemul** [comment]
It's not my plugin :( . However I did do a alias in command.yml to message then what they won , but your default replies is much cleaner , I didn't think about the reg player not having access to that command and therefore couldn't see the output , sorry for wasting your time .
