### ISSUE TITLE
Asynch error

### ISSUE THREAD

**Issue by TheRealVariousgaming** [EssentialsX/Essentials#4272]
### Type of bug

Error in console

### `/ess version` output

26.06 00:11:03 [Server] INFO Server version: 1.17-R0.1-SNAPSHOT git-Paper-46 (MC: 1.17)
26.06 00:11:03 [Server] INFO Brand version: Paper
26.06 00:11:03 [Server] INFO EssentialsX version: 2.19.0-dev+167-9bd35a2
26.06 00:11:03 [Server] INFO LuckPerms version: 5.3.3
26.06 00:11:03 [Server] INFO Vault version: 1.7.3-b131
26.06 00:11:03 [Server] INFO Citizens version: 2.0.28-SNAPSHOT (build 2328)
26.06 00:11:03 [Server] INFO EssentialsXProtect version: 2.19.0-dev+167-9bd35a2
26.06 00:11:03 [Server] INFO EssentialsXChat version: 2.19.0-dev+167-9bd35a2
26.06 00:11:03 [Server] INFO EssentialsXSpawn version: 2.19.0-dev+167-9bd35a2
26.06 00:11:03 [Server] INFO Towny version: 0.97.0.6
26.06 00:11:03 [Server] INFO You are running a server that does not properly support Bukkit plugins that rely on internal Mojang code. Consider using an Essentials replacement for your server software.
26.06 00:11:03 [Server] INFO Status determining class: !net.minecraft.server.v1_17_R1.MinecraftServer
26.06 00:11:03 [Server] INFO Fetching version information...
26.06 00:11:04 [Server] INFO You're running the latest EssentialsX dev build!

### Server startup log

https://paste.gg/p/anonymous/c76fb9c71f974968bfbea70527f100ef

### EssentialsX config files

https://paste.gg/p/anonymous/6cd0d919e2df4feca3a238a5e059bb80

### Bug description

see log.: ERROR Could not pass event AsyncPlayerChatEvent to EssentialsChat v2.19.0-dev+167-9bd35a2

### Steps to reproduce

Just start the server.
This error occurs instantly when its up and running

### Expected behaviour

Not throwing errors to console

### Actual behaviour

ERROR Could not pass event AsyncPlayerChatEvent to EssentialsChat v2.19.0-dev+167-9bd35a2

**Comment by Chew** [comment]
Are you using the 1.17 branch? https://github.com/EssentialsX/Essentials/actions/runs/964338673

**Comment by pop4959** [comment]
EssentialsX does not support placeholders in the chat format except for the ones provided. `%townyadvanced_town%` is what is causing this error.
