### ISSUE TITLE
Sethome limit not enforced correctly

### ISSUE THREAD

**Issue by zefir-git** [EssentialsX/Essentials#4278]
### Type of bug

Other unexpected behaviour

### `/ess version` output

```
[18:54:58 INFO]: Server version: 1.16.5-R0.1-SNAPSHOT git-Paper-777 (MC: 1.16.5)
[18:54:58 INFO]: EssentialsX version: 2.18.2.0
[18:54:58 INFO]: PlaceholderAPI version: 2.10.9
[18:54:58 INFO]: LuckPerms version: 5.3.47
[18:54:58 INFO]: Vault version: 1.7.3-b131
[18:54:58 INFO]: EssentialsXSpawn version: 2.18.2.0
[18:54:58 INFO]: ChestShop version: 3.12 (build 307)
[18:54:58 INFO]: You are running an unsupported server version!
```

### Server startup log

https://paste.gg/p/anonymous/5bbb1e01143740fabba52a3338265c2d

### EssentialsX config files

https://paste.gg/p/anonymous/19a9a5b70e6547c5b4b9e6e9356f4ac3

### Bug description

A player is allowed to set an *arbitrary* number of homes (nowhere defined).
![image](https://user-images.githubusercontent.com/66572326/123520685-7cbdb280-d6ba-11eb-9983-9cbf3329ec54.png)
![image](https://user-images.githubusercontent.com/66572326/123520689-85ae8400-d6ba-11eb-8cb5-58e02ba9ceea.png)
Upon `/sethome d` 
![image](https://user-images.githubusercontent.com/66572326/123520698-9101af80-d6ba-11eb-8090-ce1b128483a7.png)
Permission:<br>
![image](https://user-images.githubusercontent.com/66572326/123520714-a1b22580-d6ba-11eb-985b-a5ea16a0c5ce.png)

### Steps to reproduce

1. Use reported software versions
2. Copy the config section shared
3. Give permissions
  * `essentials.sethome`
  * `essentials.sethome.multiple`
  * `essentials.sethome.multiple.tier1`
4. Run `/sethome a`, `/sethome b`, `/sethome c` until error is shown.

### Expected behaviour

The player should only be able to set 2 homes

### Actual behaviour

The player is able to set 3 homes. A number nowhere used in the configuration

**Comment by triagonal** [comment]
This is because Essentials tries to find the greatest number of homes that a user can have, and because the default `default` sethome limit is 3. Any user with the permission `essentials.sethome.multiple` is automatically considered for the `default` limit. 

You can set the `default` key to `0` or something less than any other key under `sethome-multiple` to have your desired behaviour.

**Comment by zefir-git** [comment]
> This is because Essentials tries to find the greatest number of homes that a user can have, and because the default `default` sethome limit is 3. Any user with the permission `essentials.sethome.multiple` is automatically considered for the `default` limit.
> 
> You can set the `default` key to `0` or something less than any other key under `sethome-multiple` to have your desired behaviour.

How is the default 3? Where do I change that? My `default` group does not have `essentials.sethome.multiple`

**Comment by triagonal** [comment]
Essentials uses the `sethome-multiple.default` key to determine what the default home limit is. If the key is not present in the config, Essentials uses 3 as the value as a fallback. You can manually override it by explicitly setting a `default` key in your config, like this:

```yaml
sethome-multiple:
  default: 1
  tier1: 2
```
