### ISSUE TITLE
Vanilla Spawning Behavior Issue

### ISSUE THREAD

**Issue by kolakz** [EssentialsX/Essentials#4284]
### Type of bug

Other unexpected behaviour

### `/ess version` output

[22:19:06 INFO]: [KOLAKZ] Server version: 1.16.5-R0.1-SNAPSHOT git-Purpur-1171 (MC: 1.16.5)
[22:19:06 INFO]: [KOLAKZ] Brand version: Purpur
[22:19:06 INFO]: [KOLAKZ] EssentialsX version: 2.19.0-dev+176-4e4eb35
[22:19:06 INFO]: [KOLAKZ] PlaceholderAPI version: 2.10.9
[22:19:06 INFO]: [KOLAKZ] LuckPerms version: 5.3.48
[22:19:06 INFO]: [KOLAKZ] Vault version: 1.7.3-b131
[22:19:06 INFO]: [KOLAKZ] Citizens version: 2.0.28-SNAPSHOT (build 2329)
[22:19:06 INFO]: [KOLAKZ] EssentialsXChat version: 2.19.0-dev+176-4e4eb35
[22:19:06 INFO]: [KOLAKZ] EssentialsXSpawn version: 2.19.0-dev+176-4e4eb35
[22:19:06 INFO]: Fetching version information...
[22:19:06 INFO]: Update checking disabled in config.

### Server startup log

N/A

### EssentialsX config files

https://gist.github.com/KolakZ/b387d94f38d8c22b4582ab2c9133be27

### Bug description

Putting the `respawn-listener-priority` to `none` uses vanilla respawning behavior. But if the player hasn't set a respawn point with a bed or home, they would respawn at spawn, but since it uses vanilla respawning behavior, they spawn in a radius around the spawn point rather than on the spawn point directly.

### Steps to reproduce

1. Set the `respawn-listener-priority` to `none` .
2. /Kill yourself without setting a home or respawn point via bed.
3. You will spawn in a radius around the /spawn point rather than on the spawnpoint directly.

### Expected behaviour

I expect the user to respawn directly onto the spawnpoint if they don't have a home or respawn point via bed setup.

### Actual behaviour

The user respawns in a radius around the spawnpoint if they don't have a home or respawn point via bed setup.

**Comment by Chew** [comment]
> You will spawn in a radius around the /spawn point rather than on the spawnpoint directly.

This is vanilla behavior. Change with `/gamerule spawnRadius`

From the wiki:
> New players initially spawn within a small area surrounding the world spawn point when the server is not in Adventure mode. This area is 21×21 blocks by default, but can be changed by the spawnRadius gamerule in both single and multiplayer. Upon death or return from the End dimension, the player respawns within this area unless the player's individual spawn point changed (by using a bed or respawn anchor, or the /spawnpoint command).

^ which lines up perfectly with your issue

**Comment by kolakz** [comment]
If I do `/gamerule spawnRadius 0`, will they spawn exactly on the spawnpoint?

**Comment by Chew** [comment]
Likely, try it and see ™

**Comment by kolakz** [comment]
Alright.
