### ISSUE TITLE
Lag with Essentials In Timings

### ISSUE THREAD

**Issue by Error404-RedRose** [EssentialsX/Essentials#4287]
### Type of bug

Performance issue or memory leak

### `/ess version` output

Essentials 2.18.2.0

### Server startup log

https://paste.gg/p/anonymous/10771fac53f24e5b950126704c37bbc8

### EssentialsX config files

https://paste.gg/p/anonymous/ed8869b397884c1a8e8a40143148123c

### Bug description

com.earth2me.essentials.EssentialsPlayerListener$1DelayJoinTask (Single)

Is freezing game and causing memory leak.

### Steps to reproduce

1. have multiple worlds with multiverse
    have essentials spawn
    have magic plugin
2. create a lobby world with multiverse and do /setspawn in lobby world

info
-----
Lobby will lag and freeze because of listeners and world will not

### Expected behaviour

To Not Lag

### Actual behaviour

Freezing and having memory leak on clients and server

**Comment by Error404-RedRose** [comment]
timings: https://timings.pl3x.net/?id=954a69186d28494a81cbd2cc70a01b2a

**Comment by pop4959** [comment]
Nothing in your timings suggests Essentials is causing significant lag on your server.

**Comment by Error404-RedRose** [comment]
then why when I use setspawn in a world it freezes randomly every 5 seconds

**Comment by Error404-RedRose** [comment]
you didnt have to be so fast at closing the issue when I know its essentials causing it

**Comment by Error404-RedRose** [comment]
shows how helpful you guys are for anyone else who comes with freezing and memory leak issues

**Comment by Error404-RedRose** [comment]
you didnt even try to reproduce

**Comment by Error404-RedRose** [comment]
thanks allot mr. I Wanna Speedrun Issues

**Comment by Error404-RedRose** [comment]
![image](https://user-images.githubusercontent.com/57733446/123770556-c23bd480-d8a0-11eb-9c34-1640cc77ed76.png)

![image](https://user-images.githubusercontent.com/57733446/123770690-daabef00-d8a0-11eb-8eb1-dedd4baf8637.png)

**Comment by Error404-RedRose** [comment]
now prove to me this isnt an essentials issue
since you clearly didnt look at a thing

**Comment by Error404-RedRose** [comment]
and read the two things
Full Server Tick and com.earth2me.essentials.EssentialsPlayerListener$1DelayJoinTask (Single)

**Comment by Error404-RedRose** [comment]
someone better reopen this issue or Im calling abuse of support terms

**Comment by pop4959** [comment]
It's obvious that it isn't the cause of your lag because there were only two instances where it took 47ms in your entire timings report. This amounts to less than a tenth of a second of potential lag (and by far nothing you would be capable of noticing to begin with, much less a lag spike).

There is a video in the top right where you can learn to read timings, which I would recommend watching. Please don't report something like this unless you actually know what you're talking about.

**Comment by mdcfe** [comment]
You appear to have severely high tick durations from chunk loading. This is what you should be concerned about, not EssentialsX. 

> causing memory leak

This is highly unlikely and you've provided no evidence whatsoever for this. If you're sure you're encountering a memory leak, please provide us with proper evidence. 

> Full Server Tick

This statistic includes *every single thing* that happens in a server tick, including mob actions, players actions, redstone, physics, and plugin actions. The Full Server Tick metric only *highlights* that you may have performance issue, but it *cannot* be used to diagnose the cause of performance issues. 

> DelayJoinTask [...] count(2)

As you can see in your Timings report, DelayJoinTask does not run frequently - it ran twice in your screenshot. DelayJoinTask runs once when a player logs in to load their data from disk, and is very unlikely to have more than an occasional impact on your server. A high duration in DelayJoinTask means EssentialsX had to wait for your host machine to load the user's data and likely indicates that your host machine has slow IO performance. This is not an EssentialsX issue.
