### ISSUE TITLE
Option to jail for online time only

### ISSUE THREAD

**Issue by Turbotailz** [EssentialsX/Essentials#429]
Title is a bit vague, I want the option to jail a player for a certain time while they remain online.

Say for example, I jail a player for 20 minutes, they stick around for 5 minutes then they log off because, well, "fuck this shit", they are then able to log in 15 minutes later and they will no longer be jailed - kinda counter productive!

Instead, it would be awesome if it were possible to change this to a time based on cumulative server time. So take the above example, if player logs out after 5 minutes of being jailed, then logs back in 15 minutes later, they are still jailed and must remain online for a further 15 minutes to be automatically unjailed.

Hopefully you understand my request, I tried to explain it as well as I can :P If this might seem like too much work, that's cool, happy to look elsewhere for this feature.

Thanks!

**Comment by anemul** [comment]
I like this idea , it makes sense .

**Comment by saturnux** [comment]
i like too 

:+1:

**Comment by pop4959** [comment]
Perhaps this could be implemented by tracking how many ticks the player has been online, or tracking the sum of the differences between log-in and log-off.

**Comment by LoSCraft-Network** [comment]
I love that!

Maybe logging the playtime the player has when he got jailed and count from that (?)

**Comment by Danielpeter-99** [comment]
Up,

It would be a very useful feature
