### ISSUE TITLE
Update Essentials' spigotmc.org version compatibility for 1.17

### ISSUE THREAD

**Issue by combe15** [EssentialsX/Essentials#4299]
### Type of bug

Compatibility issue

### `/ess version` output

N/A

### Server startup log

N/A

### EssentialsX config files

N/A

### Bug description

Essentials' [README](README.md) states that this plugin is compatible with 1.17 yet this is not shown in [spigotmc.org](https://www.spigotmc.org/resources/essentialsx.9089/).

Please update the [spigotmc.org](https://www.spigotmc.org/resources/essentialsx.9089/) plugin page to reflect that this plugin is compatible with 1.17.

https://www.spigotmc.org/resources/essentialsx.9089/
![image](https://user-images.githubusercontent.com/11339091/124197643-a3059880-da94-11eb-9813-bd1eb57b5346.png)

### Steps to reproduce

N/A

### Expected behaviour

N/A

### Actual behaviour

N/A

**Comment by pop4959** [comment]
A version that officially supports 1.17 has not been posted to SpigotMC yet, so the page is correct. Please use the dev builds from [essentialsx.net](https://essentialsx.net/downloads.html) for now if you need a version that supports 1.17. When it's ready, the Spigot page will be updated.
