### ISSUE TITLE
[SUGGESTION] CreateKit Command

### ISSUE THREAD

**Issue by nandox5** [EssentialsX/Essentials#430]
For /createkit

so that the config comments dont get removed, why not move the kits to a kits.yml file
and have essentials read the kits from the kits.yml

**Comment by drtshock** [comment]
Because that would break everyone's current setup. Though I do agree that the current config file is wayyyyy too big.

**Comment by Terrobility** [comment]
You could make the kits.yml thing use a config option and set that config option to false by default. That way, it wouldn't break any setups and it'd be optional

-----Original Message-----

**Comment by nandox5** [comment]
and it probably would be an easy copy and paste fix from the current config to the kits.yml as long as the structure is kept the same (i dont see why it would change anyways)..

**Comment by drtshock** [comment]
I think this is a larger issue of redoing the entire config setup instead of just looking at kits.

**Comment by mdcfe** [comment]
Closing as `pastebin-createkit` now exists, but this can be reopened if we're still planning to rework the config system.
