### ISSUE TITLE
With essentials.build.* you still can use LAVA_BUCKET with the default AntiBuild config

### ISSUE THREAD

**Issue by ProblemsSender** [EssentialsX/Essentials#4316]
### Type of bug

Other unexpected behaviour

### `/ess version` output

[INFO] Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)

[INFO] EssentialsX version: 2.18.2.0

[INFO] PermissionsEx version: 1.23.4

[INFO] Vault version: 1.7.3-b131

[INFO] EssentialsXSpawn version: 2.18.2.0

[INFO] EssentialsXGeoIP version: 2.18.2.0

[INFO] EssentialsXChat version: 2.18.2.0

[INFO] EssentialsXAntiBuild version: 2.18.2.0

[INFO] EssentialsXProtect version: 2.18.2.0

### Server startup log

nothing wrong with this

### EssentialsX config files

USE THE DEFAULT GENERATED CONFIG.YML

### Error log (if applicable)

nothing wrong with this

### Bug description

I was just messing around with the config file to find if there's something wrong with it, and I found that AntiBuild can't stop the user from using lava bucket while it's just the default settings.
`PLEASE NOTE THAT AT DEFAULT SETTINGS, TNT CAN STILL BE PREVENTED FROM PLACING. BUT NOT THE LAVA BUCKET`

### Steps to reproduce

1/ Start a totally new, fresh server

2/ Give yourself essentials.build.*

3/ Give yourself a `LAVA_BUCKET`, and a `TNT`

4/ Try to place it on the ground...

### Expected behaviour

You CANNOT place `LAVA` and `TNT`. Or use `TNT_BUCKET` as defined in config.yml.

### Actual behaviour

You CAN place `LAVA`, and use `LAVA_BUCKET`. BUT NOT `TNT`.

**Comment by triagonal** [comment]
Unable to reproduce:
```
[01:15:24 INFO]: Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
[01:15:24 INFO]: Brand version: Paper
[01:15:24 INFO]: EssentialsX version: 2.19.0-dev+194-6535edf
[01:15:24 INFO]: LuckPerms version: 5.3.48
[01:15:24 INFO]: Vault version: 1.7.3-b131
[01:29:10 INFO]: EssentialsXAntiBuild version: 2.19.0-dev+194-6535edf
```

With either `essentials.build` or `essentials.build.*`, both `TNT` and `LAVA_BUCKET` were unable to be placed. I wasn't able to spawn in `LAVA` itself (is that even possible on the versions EssentialsX supports?), but the other two were blocked as expected.

**Comment by ProblemsSender** [comment]
> Unable to reproduce:
> 
> ```
> [01:15:24 INFO]: Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
> [01:15:24 INFO]: Brand version: Paper
> [01:15:24 INFO]: EssentialsX version: 2.19.0-dev+194-6535edf
> [01:15:24 INFO]: LuckPerms version: 5.3.48
> [01:15:24 INFO]: Vault version: 1.7.3-b131
> [01:29:10 INFO]: EssentialsXAntiBuild version: 2.19.0-dev+194-6535edf
> ```
> 
> With either `essentials.build` or `essentials.build.*`, both `TNT` and `LAVA_BUCKET` were unable to be placed. I wasn't able to spawn in `LAVA` itself (is that even possible on the versions EssentialsX supports?), but the other two were blocked as expected.

Oh I forgot, I was opped. But how the operator is allowed to place `LAVA` and use `LAVA_BUCKET`?

This is a minor bug I guess... it's actually the /op player are allowed to place `LAVA` and use `LAVA_BUCKET`.  BUT NOT `TNT`.

**Comment by ProblemsSender** [comment]
> Unable to reproduce:
> 
> ```
> [01:15:24 INFO]: Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
> [01:15:24 INFO]: Brand version: Paper
> [01:15:24 INFO]: EssentialsX version: 2.19.0-dev+194-6535edf
> [01:15:24 INFO]: LuckPerms version: 5.3.48
> [01:15:24 INFO]: Vault version: 1.7.3-b131
> [01:29:10 INFO]: EssentialsXAntiBuild version: 2.19.0-dev+194-6535edf
> ```
> 
> With either `essentials.build` or `essentials.build.*`, both `TNT` and `LAVA_BUCKET` were unable to be placed. I wasn't able to spawn in `LAVA` itself (is that even possible on the versions EssentialsX supports?), but the other two were blocked as expected.

This is unfortunate, i really can't tell if it's because of Essentials of any plugin. This is my plugin list on my test server:
`AuthMe, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, PermissionsEx, ProtocolLib, Vault`

It's like giving yourself essentials.build.* and when you place blacklist blocks on somewhere then it starts to be glitchy and you couldn't break anything by hand, even when you use blacklist items to interact within the chunk. It does not output anything whatsoever. But when you /op yourself, you can now break it.

But it looks like when you reloading Essentials and using blacklist items. It doesn't alert the console anything while it's suppose to.

I think I will close this issue for lacking evidence, may reopen it if I found something. Thanks!
