### ISSUE TITLE
Add toggle to disable number format

### ISSUE THREAD

**Issue by Kakifrucht** [EssentialsX/Essentials#432]
Currently the currency number format is in American style, which shouldn't be forced upon users. Either make it configurable or add a toggle.

Commit: https://github.com/drtshock/Essentials/commit/419d2d828245dafa8bb55abd0d179fee45422015

**Comment by SupaHam** [comment]
This has been fixed in 785bd5b. You can grab the fix from [build 373](https://ci.drtshock.net/job/EssentialsX/) on the CI server.
