### ISSUE TITLE
PlaceholderAPI support

### ISSUE THREAD

**Issue by foxi69** [EssentialsX/Essentials#434]
i think should add placeholderapi support and editable messages in config :)

**Comment by drtshock** [comment]
what is placeholderapi

Almost all the messages are configurable http://ess.khhq.net/wiki/Locale

**Comment by foxi69** [comment]
https://www.spigotmc.org/resources/placeholderapi.6245/

**Comment by drtshock** [comment]
Yeah that won't happen. Not going to add more dependencies.

**Comment by foxi69** [comment]
and why?

**Comment by FlippantCactus** [comment]
> Is "Essential"
> Requires more "Non Essential" dependencies.
> Isn't obvious?

**Comment by SupaHam** [comment]
@rErEaT There's a few things to consider when it comes to dependencies in any project. Is this a hard or soft dependency, meaning does Essentials need to have this dependency present at all times in order for it to function? On the other hand you have a soft dependency, this is one which does not require the dependency, but if present, the dependency will extend Essentials' features.

After all that noise, you need to worry about staying up to date with said dependency, which at times can be very major factors if the dependency is not consistent. In this case, PlaceholderAPI looks to be a hard dependency. All in all, Essentials is a big enough plugin as it is, having to worry about unnecessary things breaking would be more work, than it is worth.

**Comment by drtshock** [comment]
It would be easier for placeholderapi to hook into ess. They already did it for my factions plugin :)

**Comment by foxi69** [comment]
so then I can use placeholders in the messages.yml?

**Comment by realdarek** [comment]
bump, add placeholderapi pls
