### ISSUE TITLE
CRITICAL BUG with money dupe!

### ISSUE THREAD

**Issue by Kixot14** [EssentialsX/Essentials#435]
Sometime, when player join with the same nickname, but different case, him balance is dupped from first account. And he can transfer this dupped money to anywhere!
I don't know in what case this dupe exactly can happens, but it's not the first time when i see it.

**Core:** CraftBukkit version git-Spigot-2f787bd-ea28011 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT
**EssX:** build-266

**Comment by drtshock** [comment]
use online mode.
