### ISSUE TITLE
Bug with vanish!

### ISSUE THREAD

**Issue by foxi69** [EssentialsX/Essentials#436]
After some minutes the players doesnt see me on tab and my body on server!

I have to reconnect to fix this

(no i was no vanished.)

**Comment by drtshock** [comment]
Can you give me the steps to reproduce this as well as your spigot and essentialsx versions.

**Comment by foxi69** [comment]
Spigot version: git-Spigot-db6de12-3f3c65f (1.8.8)
EssentialsX: #268 http://ci.drtshock.net/job/essentialsx/

**Comment by foxi69** [comment]
sorry the problem was the skinsrestorer, now fixed!
