### ISSUE TITLE
[Critical] Safe teleport ignore not working on world change

### ISSUE THREAD

**Issue by Kakifrucht** [EssentialsX/Essentials#438]
When having both force-disable-teleport-safety and teleport-safety on true, and teleporting between worlds, it will ignore the value of force-disable-teleport-safety and still find a safe place to teleport to. This can once again be used to glitch into bases.

**Comment by vemacs** [comment]
I personally can't reproduce this.

**Comment by Kakifrucht** [comment]
I can reproduce it 100%.

Steps:
1. Go into Nether, stand somewhere.
2. Make the spot unsafe (WorldEdit)
3. TP into normal world
4. Use /back, you will be teleported to safe location.

**Comment by drtshock** [comment]
Sounds more like an issue with /back then

**Comment by Kakifrucht** [comment]
Happens with /home, too. That was just an example.
If you still can't reproduce, I'm gonna do more testing on my end if necessary.

**Comment by RoboMWM** [comment]
Apparently this is a Bukkit thing. Paper provides a config option to disable this check. It only occurs on cross-world teleportations. https://github.com/PaperSpigot/Paper/commit/7a4bea3aebc9652637ef39aa1feaa32b6d020f91

**Comment by Kakifrucht** [comment]
:/ thanks for clarifying.
I'm guessing a workaround won't be added then?

**Comment by vemacs** [comment]
Not something we want to touch. Might put an entry in the wiki suggesting to set that config option.

**Comment by Kakifrucht** [comment]
Just for reference: https://hub.spigotmc.org/jira/browse/SPIGOT-1519
