### ISSUE TITLE
EssentialsX 2.19 doesnt update items.json

### ISSUE THREAD

**Issue by Chris6ix** [EssentialsX/Essentials#4388]
### Type of bug

Compatibility issue

### `/ess version` output

[23:57:55 INFO]: Server version: 1.17.1-R0.1-SNAPSHOT git-Paper-121 (MC: 1.17.1)
[23:57:55 INFO]: Brand version: Paper
[23:57:55 INFO]: EssentialsX version: 2.19.0-dev+221-1556b91
[23:57:55 INFO]: Economy Layer: None
[23:57:55 INFO]: Vault is not installed. Chat and permissions may not work.
[23:57:55 INFO]: Fetching version information...
[23:57:55 INFO]: You're running the latest EssentialsX dev build!

### Server startup log

https://paste.gg/p/anonymous/a0d613651d78490480d2a8ecb93d2022

### EssentialsX config files

https://paste.gg/p/anonymous/31d8b21c34c840cd977840de3fa9494e

### Bug description

When updating from EssX 2.18.2 (MC 1.16.5) to EssX 2.19 (MC 1.17.1) i noticed that i cannot /give myself any of the new 1.17 items...
I have "tracked down" the issue to the items.json file now being updated with the new 1.17 stuff when you load your existing EssX 2.18.2 folder with EssX 2.19

I'm not sure tho if this is a bug (If EssX is suppose to update its files like that) or if this is intended (That you have to manually update it)

### Steps to reproduce

Load a EssX 2.18.2 folder with EssX 2.19 on 1.17.1

### Expected behaviour

Idk..should probably automatically update the items.json when its contents change...

### Actual behaviour

items.json stays on 1.16.5, causing not being able to /give 1.17 items

**Comment by triagonal** [comment]
This is correct, EssentialsX doesn't update its configuration files automatically (unless absolutely necessary), we intend for users to manually update their files.

In the future, we *might* start automatically updating files like `config.yml` and `items.json`, but there's currently no ETA for such a feature.

**Comment by Chris6ix** [comment]
Oh, okay I didn't know that, thanks :)
