### ISSUE TITLE
Crash with command

### ISSUE THREAD

**Issue by Sitmobedaf** [EssentialsX/Essentials#439]
http://pastebin.com/VB5vdg4n

/mute nick 900000000y

**Comment by drtshock** [comment]
interesting

**Comment by juIio** [comment]
Could be wrong but the first thing that came to mind was this
https://en.m.wikipedia.org/wiki/Year_2038_problem

**Comment by vemacs** [comment]
Can you test if https://github.com/drtshock/Essentials/commit/7c59d61b32685f11579280c3a830e51f00b04ea6 fixes the issue?

**Comment by Sitmobedaf** [comment]
A good reason to make the limit for mute and to togglejaing through config file.

**Comment by vemacs** [comment]
Eh, I think 100000 years is a reasonable limit for now
