### ISSUE TITLE
/tpa or /tpaccept might be broken

### ISSUE THREAD

**Issue by kurimanju-dev** [EssentialsX/Essentials#4391]
### Type of bug

Other unexpected behaviour

### `/ess version` output

23.07 14:09:15 [Server] INFO You're running the latest EssentialsX dev build!
23.07 14:09:15 [Server] INFO Fetching version information...
23.07 14:09:15 [Server] INFO Economy Layer: None
23.07 14:09:15 [Server] INFO ChestShop version: 3.12 (build 307)
23.07 14:09:15 [Server] INFO EssentialsXSpawn version: 2.19.0-dev+221-1556b91
23.07 14:09:15 [Server] INFO EssentialsXChat version: 2.19.0-dev+221-1556b91
23.07 14:09:15 [Server] INFO Vault version: 1.7.3-b131
23.07 14:09:15 [Server] INFO PlaceholderAPI version: 2.10.10
23.07 14:09:15 [Server] INFO LuckPerms version: 5.3.47
23.07 14:09:15 [Server] INFO EssentialsX version: 2.19.0-dev+221-1556b91
23.07 14:09:15 [Server] INFO Brand version: Paper
23.07 14:09:15 [Server] INFO Server version: 1.16.5-R0.1-SNAPSHOT git-Paper-782 (MC: 1.16.5)

### Server startup log

https://paste.gg/p/anonymous/c084a2a8a1244b63b2d58ab2b0fcdb37

### EssentialsX config files

https://paste.gg/p/anonymous/6814e7a3efc448c58fc76904e0ffd267

### Bug description

Well, when i try to send someone a tpa or tpahere, everything works. But after like 10 seconds, when the other person wants to accept the tpa, it just says "You don't have any pendig requests!". It works like 3 Times after a server reboot, but then it just doesn't works anymore.

### Steps to reproduce

1. Have 5-10 People Online
2. Send someone a normal tpa or tpahere
3. accept it at least after 5-10 seconds

### Expected behaviour

The Request should stay for 120 seconds, how it says in the Chat. But it only works if you accept it instantly. I expected a normal Teleport. 

### Actual behaviour

When you send someone a request, and he accept it in at least. 5-10 seconds, the chat will say "You don't have any pending Request!". You have to accept the request instantly, otherwise it won't work.

**Comment by Iseason2000** [comment]
purpur 1.17.1
I had a similar problem. It is completely random and the players whose TPA has failed is also random. Occurs about every few days, lasting about half an hour each time. Whenever I tested it myself, everything was fine.
No logs.

**Comment by mdcfe** [comment]
Hey, apologies for the lack of response on this issue. We're currently working on an overhaul of the TPA system in #3801, so once these changes are in dev builds, we'll update this issue.

**Comment by SirKillian** [comment]
Is it possible to raise priority on this? A lot of our players are currently complaining about tpa's timing out instantly. seems like an important issue considering the command is used a lot.

**Comment by rhystedstone** [comment]
> Is it possible to raise priority on this? A lot of our players are currently complaining about tpa's timing out instantly. seems like an important issue considering the command is used a lot.

You could try compiling the source in the pull request: https://github.com/EssentialsX/Essentials/pull/3801
However, it may have bugs or unintended changes, so ensure you do a backup first!
