### ISSUE TITLE
`/break` an inventory won't drop its contents in paper 127

### ISSUE THREAD

**Issue by djytw** [EssentialsX/Essentials#4392]
### Type of bug

Other unexpected behaviour

### `/ess version` output

[14:05:19 INFO]: CONSOLE issued server command: /ess version
[14:05:19 INFO]: Server version: 1.17.1-R0.1-SNAPSHOT git-Paper-127 (MC: 1.17.1)
[14:05:19 INFO]: Brand version: Paper
[14:05:19 INFO]: EssentialsX version: 2.19.0-dev+221-1556b91
[14:05:19 INFO]: Economy Layer: None
[14:05:19 INFO]: Vault is not installed. Chat and permissions may not work.
[14:05:19 INFO]: Fetching version information...
[14:05:19 INFO]: You're running the latest EssentialsX dev build!

### Server startup log

https://paste.gg/p/anonymous/1df4edab3bc94aab8fb00ccc4e7c02af

### EssentialsX config files

default config

### Bug description

Any plugins that call Block#breakNaturally on an inventory(chests, hoppers, etc) on Paper 1.17.1 build 127 with EssentialsX installed will NOT drop its contents.

Old paper builds (tested build 100) work well (contents will drop)

If remove EssX, and use build 127, the contents will also drop.

This also applies to the `/break` command in Ess. (In paper build 100, `/break` a chest will drop contents; in build 127, `/break` a chest drop nothing)

### Steps to reproduce

- Put a chest
- insert several items
- `/break`
- drop nothing

### Expected behaviour

should drop contents

### Actual behaviour

 drop nothing

**Comment by Laarryy** [comment]
Can confirm that chests do not naturally drop contents in 2.19.0 or newer dev builds - not sure if this was an intended change somewhere along the line or not however.

**Comment by djytw** [comment]
> Can confirm that chests do not naturally drop contents in 2.19.0 or newer dev builds - not sure if this was an intended change somewhere along the line or not however.

Well... that's not the case. Any plugin that uses bukkit's `Block#breakNaturally()` on a chest will drop nothing, so there must be a complicated reason I believe.  This method works well in all paper builds if EssX is not installed, so it's not a paper issue either.

**Comment by JRoy** [comment]
> > Can confirm that chests do not naturally drop contents in 2.19.0 or newer dev builds - not sure if this was an intended change somewhere along the line or not however.
> 
> Well... that's not the case. Any plugin that uses bukkit's `Block#breakNaturally()` on a chest will drop nothing, so there must be a complicated reason I believe.  This method works well in all paper builds if EssX is not installed, so it's not a paper issue either.
> 

Essentials doesn't use `Block#breakNaturally()` in /break so I don't know why you keep bringing it up, we use `Block#setType()`

**Comment by djytw** [comment]
Then both are unfunctional, isn't it a bug?

**Comment by JRoy** [comment]
Considering the code for this command hasn't ever changed, this isn't an Essentials bug but likely a Spigot/Paper one. Please take it up with them.

**Comment by Machine-Maker** [comment]
See [here](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/8d244b0b7e35596b160452c1aa7ec4fc21de4d50), they changed the functionality of setType (used in the break command) so now it doesn't drop items when replaced by air. This was a 100% intentional change to fix [this issue](https://hub.spigotmc.org/jira/browse/SPIGOT-3725).
