### ISSUE TITLE
[1.9] /gamemode spectator does not work

### ISSUE THREAD

**Issue by Gaelan** [EssentialsX/Essentials#443]
These work:

```
/gamemode creative
/gamemode sp
/gamemode 3
/gmsp
```

This does not work:

```
/gamemode spectator
```

It just prints out `/gamemode`'s help message. Unfortunately, `/gamemode spectator` is the command used by 1.9's F3+N (toggle creative/spectator). Not sure what's going on here.

---

Spigot 1.9
CraftBook, WorldEdit, PEx, EssentialsX

**Comment by vemacs** [comment]
Spectator wasn't defined in the command processor, i've dealt with it now

https://github.com/drtshock/Essentials/commit/f94e242a754a2e0156bb2ac7ce540a88e16e1793
