### ISSUE TITLE
Possible Boat Bug?

### ISSUE THREAD

**Issue by eldhrin** [EssentialsX/Essentials#4436]
### Type of bug

Other unexpected behaviour

### `/ess version` output

Server version: 1.17.1-R0.1-SNAPSHOT git-Paper-151 (MC: 1.17.1)
Brand version: Paper
EssentialsX version: 2.19.0-dev+232-b84207f
LuckPerms version: 5.3.47
PlaceholderAPI version: 2.10.9
Vault version: 1.7.3-b131
EssentialsXChat version: 2.19.0-dev+232-b84207f
EssentialsXSpawn version: 2.19.0-dev+232-b84207f
DiscordSRV version: 1.23.0
Economy Layer: None
You're running the latest EssentialsX dev build!

### Server startup log

https://paste.gg/p/anonymous/7cba95c7125b4aae9e704c0b8eab242a

### EssentialsX config files

https://paste.gg/p/anonymous/f887d8cd0b4d4c71b0f7688901f37b36

### Bug description

Boats cannot be placed on land, however it can be placed on anything that is on the block (ie. grass, snow, azalea, flowers)

### Steps to reproduce

1. Try to place boat on land (grass block, sand, etc)
2. Boat doesn't appear on land :(

### Expected behaviour

Boat should appear on the chosen block and you should be able to get in

### Actual behaviour

Boat does not appear on block and remains in inventory

**Comment by JRoy** [comment]
This was a (now fixed) issue in Paper: https://github.com/PaperMC/Paper/issues/6312

Update here: https://papermc.io/downloads

**Comment by eldhrin** [comment]
Thanks JRoy, apologies for the trouble
