### ISSUE TITLE
EssentialsX UUID Console Flood

### ISSUE THREAD

**Issue by rentexgfx** [EssentialsX/Essentials#4437]
### Type of bug

Compatibility issue, Error in console

### `/ess version` output

>.... [01:50:36 INFO]: Economy Layer: None
>.... [01:50:36 INFO]: Fetching version information...
>.... [01:50:36 INFO]: You're running the latest EssentialsX dev build!

### Server startup log

https://paste.gg/p/anonymous/b7491c760eeb4a5995589cc3a8881359

### EssentialsX config files

https://paste.gg/p/anonymous/998e66cb5455405da2328a962df632c7

### Error log (if applicable)

https://paste.gg/p/anonymous/bb606b5a8128417a956b7edc08d5041d

### Bug description

I just start server and error comes up. Everything  running fine but i'm afraid it can be really dangerous for userdata in future.

### Steps to reproduce

1. Start server
2. here u go.

### Expected behaviour

Everything  running fine but i'm afraid it can be really dangerous for userdata in future.

### Actual behaviour

Everything  running fine but i'm afraid it can be really dangerous for userdata in future.

**Comment by Builder45** [comment]
Someone else already made an issue for this, check out #4342 
There are also some possible fixes there
