### ISSUE TITLE
[1.9] Error when using shop signs: Invalid inventory size; expected 36 or less

### ISSUE THREAD

**Issue by Titanium922** [EssentialsX/Essentials#444]
Whenever you try to use buy signs, you get the following error:

Error: Invalid inventory size; expected 36 or less

(Using EssentialsX build #269)

**Comment by Titanium922** [comment]
Whenever you try to use buy signs, you get the following error:

Error: Invalid inventory size; expected 36 or less

(Using EssentialsX build #269)

**Comment by vemacs** [comment]
Are there any stacktraces that appear in the console, or just that error

**Comment by blha303** [comment]
Confirmed, no stacktrace, just that error.

![game screenshot](https://s.b303.me/vYlB.png)

https://s.b303.me/oe6s.log

**Comment by vemacs** [comment]
https://github.com/drtshock/Essentials/commit/844a4a05748c0131901b4909fabbb8948d2901a8

**Comment by blha303** [comment]
And the link to the build where the issue is fixed, just cos I'm feeling super helpful today :D https://ci.drtshock.net/job/EssentialsX/272/
