### ISSUE TITLE
It changes vanilla command and REI mod using /give command didn't work

### ISSUE THREAD

**Issue by CyanChanges** [EssentialsX/Essentials#4443]
### Type of bug

Compatibility issue

### `/ess version` output

Server version: 1.16.5-R0.1-SNAPSHOW git-Paper-782 (MC: 1.16.5)
EssentialsX version: 2.18.2.0
PlaceholderAPI version: 2.10.9
LuckPerms version: 5.3.57
Vault version: 1.7.3-b131
You are running an un supported server version!

### Server startup log

None

### EssentialsX config files

None

### Bug description

When I use "/give @s minecraft:xxxxx", It didn't work
then Fabric REI Mod using "/give {player_name} {item_identifier}{nbt} {count}" and {item_identifier} is minecraft:xxxxxxx
I usually use "/give @s" but it can't work!!!!
My friend hite it, but EssentialsXChat required it

### Steps to reproduce

Example:

1. use "/give @s minecraft:diamond_block"
2. command didn't work

### Expected behaviour

shouldn't added control in config
and I will toggle it off

### Actual behaviour

Command didn't work

**Comment by Chew** [comment]
Fabric commands on paper 🤨 

Just do `/minecraft:give [the rest of the commands here]`

**Comment by CyanChanges** [comment]
But I usually use /give, And not /minecraft:give and if REI run command /minecraft:give, when the server is not a plugins server
, Then there is no command /minecraft:give ,And it will throw error, So I will reconfigure the config to use!!

**Comment by CyanChanges** [comment]
> Fabric commands on paper 🤨
> 
> Just do `/minecraft:give [the rest of the commands here]`

And when you are open a block container, It will use vanilla command(/give) to give items, But this plugins changes it
