### ISSUE TITLE
config.yml.broken.1628651946377

### ISSUE THREAD

**Issue by Aernhard** [EssentialsX/Essentials#4457]
### Type of bug

Data loss

### `/ess version` output

Server Version: 1.16.5-R0.1-SNAPSHOT git-Paper-771 (MC: 1.16.5)
Brand Version: Paper
EssentialsX version: 2.19.0-dev+232-b84207f
EssentialsXChat Version: 2.19.0-dev+232-b84207f
EssentialsXSpawn Version: 2.19.0-dev+232-b84207f

### Server startup log

https://pastebin.com/hxBEXeMX

### EssentialsX config files

https://pastebin.com/uJ9aaZMC

### Error log (if applicable)

config.yml.broken.1628651946377

### Bug description

Every time I change the config, the essentials config crashes.

### Steps to reproduce

idk?

### Expected behaviour

config loads correctly

### Actual behaviour

Nothing?

**Comment by Chew** [comment]
Your configuration is invalid, toss it into a yaml parser like https://yaml-online-parser.appspot.com to see where the issue occurs. If the config you've provided is exactly what you're using, that "download to view more than 1000 files" is causing you issues...
