### ISSUE TITLE
PermissionsEx permissions handler depends on internal PEX classes

### ISSUE THREAD

**Issue by zml2008** [EssentialsX/Essentials#446]
For PermissionsEx 2.0, there are a significant number of API breaks, meaning that users running that version of PEX will not be able to use EssX as it is currently. [This line](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/perm/impl/PermissionsExHandler.java#L11) should be adjusted to check an option through the Vault chat service rather than directly hooking into PEX.

This will reduce breaks as more users switch to PEX2.

**Comment by vemacs** [comment]
I'm confused, that method does nothing with the chat service? It checks for build permissions.

**Comment by zml2008** [comment]
That line gets the PEX user, and the next line gets an option from the PEX user (using PEX's own API). Vault's chat service provides an implementation-abstract way of fetching the same data (the `build` option).

**Comment by vemacs** [comment]
Ah, I wasn't aware that Vault's chat service provided metadata capabilities. I'll take a look.

**Comment by vemacs** [comment]
Would this work? https://github.com/drtshock/Essentials/commit/7d33814d5b9971bfb14f43fe701dbf5b595607a9

**Comment by zml2008** [comment]
Looks like that fixes it! Thanks a ton.

**Comment by drtshock** [comment]
Thanks for reporting :)
