### ISSUE TITLE
Waking sleeping villagers sets /home location.

### ISSUE THREAD

**Issue by Xarius86** [EssentialsX/Essentials#4461]
### Type of bug

Other unexpected behaviour

### `/ess version` output

[14:46:15 INFO]: Server version: 1.17.1-R0.1-SNAPSHOT git-Purpur-1330 (MC: 1.17.1)
[14:46:15 INFO]: Brand version: Purpur
[14:46:15 INFO]: EssentialsX version: 2.19.0-dev+248-1179caa
[14:46:15 INFO]: LuckPerms version: 5.3.57
[14:46:15 INFO]: PlaceholderAPI version: 2.10.10-DEV-132
[14:46:15 INFO]: Vault version: 1.7.3-b131
[14:46:15 INFO]: DiscordSRV version: 1.23.0
[14:46:15 INFO]: EssentialsXChat version: 2.19.0-dev+248-1179caa
[14:46:15 INFO]: EssentialsXSpawn version: 2.19.0-dev+248-1179caa
[14:46:15 INFO]: Economy Layer: None
[14:46:15 INFO]: Fetching version information...
[14:46:15 INFO]: You're running the latest EssentialsX dev build!

### Server startup log

https://pastebin.com/XK0mFFvg

### EssentialsX config files

https://pastebin.com/Hzx3frF3

### Bug description

Waking up a sleeping villager by right clicking sets that bed as your `/home` location.

### Steps to reproduce

1) Download latest Paper or Purpur jar.
2) Run jar, accept EULA, re-run jar, shutdown server.
3) Add latest EssX, LuckPerms to plugins
4) Run jar.
5) Join game. 
6) Run `lp editor` and add `essentials.sethome.bed` and `essentials.home` permissions. Apply edits.
7) Enter _creative_ and find a village. After finding one, go back to _survival_.
8) Give yourself a bed. Right click it to set it as your `/home`
9) Use `/time set night` to force villagers to sleep.
10) Right click on a sleeping villager to wake them up.
11) Walk away.
12) Use `/home` -- you'll be taken to the villagers bed rather than your own.

### Expected behaviour

Right clicking a sleeping villager should only wake them.

### Actual behaviour

Right clicking a villager sets your /home location to the bed of the villager you woke.

**Comment by nsgwick** [comment]
This isn't a bug.
Experiment on the latest release of EssX with one home set (the one in the picture):
I clicked once when the villager was in the bed:

![2021-09-12_15 24 33](https://user-images.githubusercontent.com/90180047/132991584-1f1f3181-52af-42f3-8dba-ba6401056722.png)
![2021-09-12_15 24 40](https://user-images.githubusercontent.com/90180047/132991586-e756603b-dcb6-4cfa-9c52-53b2d551b972.png)
![2021-09-12_15 24 55](https://user-images.githubusercontent.com/90180047/132991587-187685e0-c396-42ae-a90b-ebf3525a6bc2.png)

**Comment by Nicholamsious** [comment]
I can say this isn't a bug on the latest build of paper and latest release of EssX (tested as op and with the perms set with luckperms).


![2021-09-12_15 24 40](https://user-images.githubusercontent.com/90180047/132991724-6657bdb8-c60e-4e6b-a315-9e117de7aa55.png)
![2021-09-12_15 24 55](https://user-images.githubusercontent.com/90180047/132991725-186120e3-4503-4236-99aa-34332a15714a.png)

![2021-09-12_15 24 33](https://user-images.githubusercontent.com/90180047/132991723-611182d4-0bbc-449a-bfff-8113ea917a12.png)
