### ISSUE TITLE
Incompatibility with ACF

### ISSUE THREAD

**Issue by BoBoBalloon** [EssentialsX/Essentials#4462]
### Type of bug

Compatibility issue, Error in console

### `/ess version` output

 Server version: 1.17-R0.1-SNAPSHOT 3147-Spigot-9472b09-d7ef1e9 (MC: 1.17)
[15:12:44] [Server thread/INFO]: Brand version: CraftBukkit
[15:12:44] [Server thread/INFO]: EssentialsX version: 2.19.0-dev+248-1179caa
[15:12:44] [Server thread/INFO]: Economy Layer: None
[15:12:44] [Server thread/INFO]: Vault is not installed. Chat and permissions may not work.
[15:12:44] [Server thread/INFO]: You are running an unsupported server version!
[15:12:44] [Server thread/INFO]: Fetching version information...
[15:12:44] [Craft Scheduler Thread - 2/INFO]: You're running the latest EssentialsX dev build!

### Server startup log

https://paste.gg/p/anonymous/9699942740874423909b207479350a93

### EssentialsX config files

https://paste.gg/p/anonymous/62bf9377de444b2583cc51405de636e4

### Error log (if applicable)

https://paste.gg/p/anonymous/e30a91ca5b40493ab060d5b81bb99910

### Bug description

From what I understand this bug occors because of the interaction of [ACF](https://github.com/aikar/commands) and [the array call on line 36 of the AlternativeCommandsHandler class](https://github.com/EssentialsX/Essentials/blob/1179caab883d59b0f389cd2ed0e581d89d86a85f/Essentials/src/main/java/com/earth2me/essentials/AlternativeCommandsHandler.java#L36).

### Steps to reproduce

1. Make a plugin using ACF and register the command
2. Download EssentialsX
3. Exception should be thrown and a stack trace should be in console when the plugin enables

### Expected behaviour

Essentials should either ignore commands built in ACF or support them like any other command built using the bukkit api.

### Actual behaviour

The command helper class will be null and cause null pointers for the rest of the runtime

**Comment by triagonal** [comment]
Fixed in #4508. Download the [latest dev build](https://essentialsx.net/downloads.html) for a version that includes this fix.
