### ISSUE TITLE
[Essentials] /ci result: null

### ISSUE THREAD

**Issue by Sikatsu** [EssentialsX/Essentials#448]
Using latest devbuilds Essentials, EssentialsSpawn, EssentialsGEOIP

`01.03 19:40:21 [Server] ERROR null
01.03 19:40:21 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'ci' in plugin Essentials v2.0.1-b276
01.03 19:40:21 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.9.jar:git-Spigot-604e046-4831c56]
01.03 19:40:21 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.jar:git-Spigot-604e046-4831c56]
01.03 19:40:21 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.jar:git-Spigot-604e046-4831c56]
01.03 19:40:21 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1302) [spigot-1.9.jar:git-Spigot-604e046-4831c56]
01.03 19:40:21 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1137) [spigot-1.9.jar:git-Spigot-604e046-4831c56]
01.03 19:40:21 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.jar:git-Spigot-604e046-4831c56]
01.03 19:40:21 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.jar:git-Spigot-604e046-4831c56]
01.03 19:40:21 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-604e046-4831c56]
01.03 19:40:21 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
01.03 19:40:21 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
01.03 19:40:21 [Server] INFO at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-604e046-4831c56]
01.03 19:40:21 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:716) [spigot-1.9.jar:git-Spigot-604e046-4831c56]
01.03 19:40:21 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-604e046-4831c56]
01.03 19:40:21 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot-1.9.jar:git-Spigot-604e046-4831c56]
01.03 19:40:21 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.9.jar:git-Spigot-604e046-4831c56]
01.03 19:40:21 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
01.03 19:40:21 [Server] INFO Caused by: java.lang.NullPointerException
01.03 19:40:21 [Server] INFO at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:354) ~[?:?]
01.03 19:40:21 [Server] INFO at com.earth2me.essentials.Essentials.onCommand(Essentials.java:348) ~[?:?]
01.03 19:40:21 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.9.jar:git-Spigot-604e046-4831c56]
01.03 19:40:21 [Server] INFO ... 15 more`

**Comment by drtshock** [comment]
Can you use pastebin please? Also explain why you closed your ticket.

**Comment by Sikatsu** [comment]
Next time I will use pastebin, sorry for that.
I closed it because this error showed up for every essentials command, restarted the server and it worked fine.
