### ISSUE TITLE
[1.9] change-playerlist doesn't work

### ISSUE THREAD

**Issue by Platinteufel** [EssentialsX/Essentials#449]
Hey, 

with Spigot 1.9 change-playerlist doesn't work, my tablist is just white.

**Comment by vemacs** [comment]
This is a Spigot issue with setTabListName, there's nothing we can do about it. Wait for the server implementation to stabilize.

**Comment by vemacs** [comment]
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/ffacb6cf79601980e752878f84742f7e87af5973
