### ISSUE TITLE
/Fix all works but not /Fixall

### ISSUE THREAD

**Issue by DebuffPvP** [EssentialsX/Essentials#4498]
### Type of bug

Other unexpected behaviour

### `/ess version` output

NA

### Server startup log

NA

### EssentialsX config files

NA

### Bug description

This is probably a quick fix but you guys forgot to add /fixall combined instead of just spaced out /fix all
as you have it for /repair all and /repairall so prior to a stable release on spigot a lot of us would greatly appreciate it if you guys could make that possible without us having to use 3rd part plugins for aliases

### Steps to reproduce

try /fixall it will not work

### Expected behaviour

i was expecting it to work

### Actual behaviour

it says the command doesn't exist

**Comment by fahlur** [comment]
iirc the command is /fix all not /fixall

**Comment by imDaniX** [comment]
> without us having to use 3rd part plugins for aliases

Well, you can use Bukkit's commands.yml for that.

**Comment by DebuffPvP** [comment]
well if /repairall and /repair all are on essentials and it also has /fix all but not /fixall that doesn't make any sense to do it through bukkit when they can just add it

**Comment by imDaniX** [comment]
Just wanted to tell that it's possible without third-party plugins.

**Comment by DebuffPvP** [comment]
i know i appreciate the reply

**Comment by JRoy** [comment]
/repairall isn't an Essentials thing, and /fixall won't be for the same reason. Feel free to make your own alias with commands.yml or so on
