### ISSUE TITLE
seen command giving uuid

### ISSUE THREAD

**Issue by elaineandsparky** [EssentialsX/Essentials#4499]
### Type of bug

Other unexpected behaviour

### `/ess version` output

30.08 13:01:51 [Server] INFO Server version: 1.17.1-R0.1-SNAPSHOT git-Paper-176 (MC: 1.17.1)
30.08 13:01:51 [Server] INFO Brand version: Paper
30.08 13:01:51 [Server] INFO EssentialsX version: 2.19.0-dev+257-4bee159
30.08 13:01:51 [Server] INFO PlaceholderAPI version: 2.10.10
30.08 13:01:51 [Server] INFO LuckPerms version: 5.3.47
30.08 13:01:51 [Server] INFO Vault version: 1.7.3-b131
30.08 13:01:51 [Server] INFO EssentialsXChat version: 2.19.0-dev+257-4bee159
30.08 13:01:51 [Server] INFO EssentialsXProtect version: 2.19.0-dev+257-4bee159
30.08 13:01:51 [Server] INFO EssentialsXSpawn version: 2.19.0-dev+257-4bee159
30.08 13:01:51 [Server] INFO Citizens version: 2.0.28-SNAPSHOT (build 2357)
30.08 13:01:51 [Server] INFO DiscordSRV version: 1.23.0
30.08 13:01:51 [Server] INFO Economy Layer: None
30.08 13:01:51 [Server] INFO Fetching version information...
30.08 13:01:51 [Server] INFO You're running the latest EssentialsX dev build!

### Server startup log

https://paste.gg/p/anonymous/dd2760b9fba74d47a6f6b83f8178f662

### EssentialsX config files

https://paste.gg/p/anonymous/fa1651b9a9764152a160f131f8891309

### Bug description

players with just the essentials.seen permission can see the uuid of a player.

Note, these players only have the basic seen permission not essentials.seen.extra/ip/location

### Steps to reproduce

give player essentials.seen permission
use the seen command as that player

### Expected behaviour

for /seen to only return how long that player has been online or how long since they last logged on

### Actual behaviour

gives the above information plus the players uuid

**Comment by Chew** [comment]
UUID isn't private information, you can easily get any user's UUID...

**Comment by molor** [comment]
> UUID isn't private information, you can easily get any user's UUID...

But is it really necessary for regular players, many of whom do not even know what it is?..

**Comment by Chew** [comment]
Fair, this is more of a feature request, though (ability to hide the UUID)

**Comment by elaineandsparky** [comment]
If it is working as intended then what's the difference between seen and seen.extra  please as I saw no difference when testing.
I do also agree it's not needed for normal players and doesn't look good to show it even if it is easily accessible elsewhere, which not everyone knows about.
