### ISSUE TITLE
Issues with [Buy] Signs 1.9

### ISSUE THREAD

**Issue by boredhero** [EssentialsX/Essentials#450]
This is really bad...whenever someone uses a buy sign in 1.9 it just outputs "Error: Invalid Inventory Size; Expected 36 or less."
![2016-03-01_21 21 36](https://cloud.githubusercontent.com/assets/12053148/13449147/9d74628c-dff6-11e5-927c-1ebbd088590d.png)

**Comment by vemacs** [comment]
This was fixed 12 hours ago. Use build 272 or above.

In the future, try the latest builds before reporting issues.
