### ISSUE TITLE
Spawner issue caused by essentials

### ISSUE THREAD

**Issue by DebuffPvP** [EssentialsX/Essentials#4511]
### Type of bug

Error in console

### `/ess dump *` output

https://essentialsx.net/dump.html?id=f47a6022b105471dac7520dda8df41f6

### Bug description

So when i place spawners that are from silkspawners it generates 2 logs per spawner that is placed that spam the console and i turned towards the silkspawners developer and he said it's an issue coming from essentials not his plugin and essentials somehow causes it and it's not just me but 5 of my friends as well whom it's happening to.

### Steps to reproduce

I don't know because i don't know what the issue is dependent on.

### Expected behaviour

To not show anything in console when a spawner is placed

### Actual behaviour

It spams logs

**Comment by triagonal** [comment]
Can you provide an example of the logs that are shown when a spawner is placed?

**Comment by DebuffPvP** [comment]
https://gyazo.com/eae17f209015289b90e30ac7509f6ba4  There you got i didn't realize that. So the blockentity message is t he messaged displayed by silkspawners when a spawner is being placed and the second is the essentials debug message as to why it's doing it. but when essentials plugin isn't present it doesn't show the blockentity message at all

**Comment by JRoy** [comment]
What did you use to get the spawner you placed down?

**Comment by DebuffPvP** [comment]
i used silkspawners but that only happens when essentials is present but when it's not there is no issue and the owner told me to contact you guys cause he said it seems to be an issue with essentials. So when i do place the spawner from silkspawners with essentials on my server and turn debug on it shows this msg [20:29:00 WARN]: Skipping BlockEntity with id 
[20:29:00 INFO]: [Essentials] checking if DebuffPvP has essentials.spawnerconvert.pig - true along with the silkspawners one

**Comment by JRoy** [comment]
The only way said code gets called is with spawners from the /give command in Essentials (as of 2.19.0). I don't cannot reproduce this in that case.

**Comment by DebuffPvP** [comment]
so why does silkspawners trigger that message? only when essentials is present and when when you turn on debug mode on essentials it also generates the debug msg
