### ISSUE TITLE
1 user with 2 uuids

### ISSUE THREAD

**Issue by FakEEE14** [EssentialsX/Essentials#4516]
### Type of bug

Data loss, Error in console

### `/ess dump *` output

https://essentialsx.net/dump.html?id=399fe2c9132f46879a96929e063e8402

### Error log (if applicable)

https://pastebin.com/wqAwENnQ

### Bug description

hi
i use geyser for pocket edition players
some times a player have java user that called Mrunkown and join the server and play
after a while
the same player will create a pocket edition user with same name Mrunkown and join the server thinking that the uuidis is same and everything should be fine but it's not 
after that essentials go look for the user and found 1 user with 2 uuidis and drop the error

### Steps to reproduce

you need a pocket edition user
then you need to setup a server (essentials,vault,...etc) and install geyser mc on your server
then join the server with pocket edition 
after that join the server with java user but as the same user that pocket edition have
then close restart the server and the error will be popped when the server is booted

### Expected behaviour

just don't pop the error every time.
i don't know it's possible to fix this because user have data

### Actual behaviour

it's pop the error when the server boots up or player joins

**Comment by JRoy** [comment]
https://github.com/EssentialsX/Essentials/issues/3956#issuecomment-779254544
