### ISSUE TITLE
How to fix this error log?

### ISSUE THREAD

**Issue by ZayanPlayz** [EssentialsX/Essentials#4519]
d

**Comment by Chew** [comment]
Update to 2.19.0 (stable) or latest dev builds to see if the issue resolves. If not, please provide the entire latest.log since we can't do anything otherwise (and you'd be able to `/ess dump *` anyway)

**Comment by ZayanPlayz** [comment]
ok done what you asked.
https://essentialsx.net/dump.html?id=986683d0132845a6aad691f19470a78e

**Comment by ZayanPlayz** [comment]
NOW EVEN THE ADDONS ARE GONE AND ONLY ESSENTIALS IS THERE

**Comment by ZayanPlayz** [comment]
someone please help another error log has come
https://paste.gg/p/anonymous/dfd93423bb6848788423fd37cf928bc3

**Comment by ZayanPlayz** [comment]
still the error is there even when updated
https://paste.gg/p/anonymous/aab458cf76bd4a24af5f5f30adc05251

**Comment by JRoy** [comment]
Outdated, failed to provide new error log.
