### ISSUE TITLE
[SUGGESTION] Bans and money in MySQL

### ISSUE THREAD

**Issue by DarwinTrue** [EssentialsX/Essentials#452]
It would be great to be able to connect the bans and the economy in the mysql, and use it on multiple servers.

**Comment by drtshock** [comment]
:(

**Comment by DarwinTrue** [comment]
Why are you sad? :(
Multiserver bans it's important for me. On 1.8 i used MaxBans, but it is no working on 1.9. Iconomy still working fine, but it would be great to use 1 plugin instead of 3.

**Comment by khobbits** [comment]
Essentials doesn't handle the ban list, that is bukkit.
The Essentials commands just call the bukkit api, so a plugin designed to sync ban lists would work with Essentials.

As for money, Essentials supports Vault, so any mysql eco api will work.
