### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by PanHaskins** [EssentialsX/Essentials#4523]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=f2d249574086435b8433f5da590f6b6f

### Error log (if applicable)

Anything

### Bug description

Config does not support characters such as a period (.)
In Chat, it does not display prefixes, etc.

    Zk.Builder: '&7&lZk.Builder &f{DISPLAYNAME}{alonsotags_tag_chat} &8&l»&7 {MESSAGE}'
    Zk.Helper: '&7&lZk.Helper &f{DISPLAYNAME}{alonsotags_tag_chat} &8&l»&7 {MESSAGE}'

I apologize that the server is in OFFLINE mode. 

### Steps to reproduce

In Essentials config (Essentials chat section)    

    Zk.Builder: '&7&lZk.Builder &f{DISPLAYNAME}{alonsotags_tag_chat} &8&l»&7 {MESSAGE}'
    Zk.Helper: '&7&lZk.Helper &f{DISPLAYNAME}{alonsotags_tag_chat} &8&l»&7 {MESSAGE}'

### Expected behaviour

In Chat, it does not display prefixes, etc.

### Actual behaviour

In Chat, it does not display prefixes, etc.

**Comment by JRoy** [comment]
Dots are special characters in YAML, doing something this should fix your issue;
```yaml
"Zk.Builder": '&7&lZk.Builder &f{DISPLAYNAME}{alonsotags_tag_chat} &8&l»&7 {MESSAGE}'
"Zk.Helper": '&7&lZk.Helper &f{DISPLAYNAME}{alonsotags_tag_chat} &8&l»&7 {MESSAGE}'
```

**Comment by PanHaskins** [comment]
I'm sorry to bother you unnecessarily, but when will the fixed bug be applied to the plugin for possible download?

**Comment by Chew** [comment]
No update or download is needed, just wrap your `Zk.Builder` in quotes as stated above...

**Comment by PanHaskins** [comment]
'Zk.Builder': '&7&lZk.Builder &f{DISPLAYNAME}{alonsotags_tag_chat} &8&lÂ»&7 {MESSAGE}'
    'Zk.Helper': '&7&lZk.Helper &f{DISPLAYNAME}{alonsotags_tag_chat} &8&lÂ»&7 {MESSAGE}'

Don´t working
