### ISSUE TITLE
Teleport with passenger

### ISSUE THREAD

**Issue by RinNiko** [EssentialsX/Essentials#4528]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=6738446bd44b4b8eac04c55e6d1a3144

### Bug description

teleport-passenger-dismount: true

### Steps to reproduce

Have a mob riding you
Then try to use teleport /tp or /warp

### Expected behaviour

Should be teleported

### Actual behaviour

It not teleport me :(

**Comment by JRoy** [comment]
Cannot reproduce

https://user-images.githubusercontent.com/10731363/133504105-bb2d8071-7d04-47f4-b0d2-9ff63f125d13.mp4

Make sure you are on the latest version of Essentials and possible try using paper: https://papermc.io/downloads

**Comment by RinNiko** [comment]
Hi there I have make a plugin that will make armor stand mount player and I cancel event Dismount
