### ISSUE TITLE
duplications of users on baltop with capitalized names

### ISSUE THREAD

**Issue by Twi5TeD** [EssentialsX/Essentials#453]
i found the problem and spoke with the creator of leaderboad heads and he told me its something to do with with how the essentials api is handling the data as all he is doing is hooking into it. please can you look into it thanks

**Comment by drtshock** [comment]
use online mode

**Comment by Twi5TeD** [comment]
i have it on an online server same thing ive also tried with an offline server

**Comment by drtshock** [comment]
This doesn't happen in online mode.
