### ISSUE TITLE
Confirmed: vanish bug!

### ISSUE THREAD

**Issue by foxi69** [EssentialsX/Essentials#454]
After a bit time, the server owners is removed from tab and get ghost!

but if I use /vanish 2x, its fixed.
so I think its a bug

**Comment by Agazed** [comment]
This had been posted several times here. As far as I know, it's a Bukkit glitch and there is nothing the EssentialsX developers can do about it for now.

**Comment by foxi69** [comment]
I am using spigot.

**Comment by vemacs** [comment]
Spigot is CraftBukkit-based.
