### ISSUE TITLE
console always shows this error

### ISSUE THREAD

**Issue by vubaolinh123** [EssentialsX/Essentials#4543]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=750f39ff5ecb4024b661e2e9e4b71fa5

### Error log (if applicable)

https://paste.gg/p/anonymous/b988627e6eae4fa9b63e5c7fbf79d673

### Bug description

i don't know what error this is but the console always shows this error

### Steps to reproduce

No

### Expected behaviour

No

### Actual behaviour

No

**Comment by JRoy** [comment]
Not an Essentials issue, likely a PurPur one
