### ISSUE TITLE
@everyone and @here not blocked

### ISSUE THREAD

**Issue by GoudronViande24** [EssentialsX/Essentials#4548]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

not relevant for now, I'll add if needed

### Bug description

When any player in Minecraft type @everyone or @here in the chat, the Discord webhook sends it and spam everyone on the server. 

### Steps to reproduce

Setup Essentials with Discord bridge
Type @everyone in Minecraft chat

### Expected behaviour

There should be a way to add an optional filter in the config to prevent spam

### Actual behaviour

Everyone on the Discord server get tagged
![image](https://user-images.githubusercontent.com/42936037/134784156-5c6eeb28-fb20-463d-927a-e197143a575b.png)

**Comment by JRoy** [comment]
The `/ess debug all` is relevant for now!

In addition to providing that, Please do `/ess debug`, have your players do @here or @everyone and then send your log during that

**Comment by GoudronViande24** [comment]
Nevermind, I found what I wanted, idk why but the users had essentials.discord.ping perm.
