### ISSUE TITLE
Changing currency-symbol from '$' to '£' breaks config

### ISSUE THREAD

**Issue by richieh92** [EssentialsX/Essentials#4550]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=84fec2c399324737b7ad467ad8ce4338

### Bug description

When changing the default currency symbol in config.yml from '$' to '£', the configuration is marked as broken and a new configuration is generated with default values. This does this also with a fresh config file, with all defaults with just the currency symbol changed to '£'.

I previously had the currency symbol set to '£' but after updating to the latest version of EssentialsX (previously EssentialsX-2.18.2.0), this no longer works.

### Steps to reproduce

1. Shutdown server.
2. Modify EssentialsX config.yml file and change currency-symbol: '$' to currency-symbol: '£'.
3. Save the changes and start the server.
4. The server console reports that the EssentialsX config file is broken and generates a new one.

### Expected behaviour

EssentialsX should set the currency symbol to '£', without re-generating the config file with defaults.

### Actual behaviour

EssentialsX re-generates the config.yml file if you change the currency-symbol from '$' to '£'.

**Comment by JRoy** [comment]
Save the config file as UTF-8
