### ISSUE TITLE
pom.xml: Missing artifact org.bstats:bstats-bukkit:jar:1.8

### ISSUE THREAD

**Issue by rhystedstone** [EssentialsX/Essentials#4554]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

This is an API issue

### Error log (if applicable)

Logs from VSCode devtools:
[languageServerLogs.log](https://github.com/EssentialsX/Essentials/files/7263212/languageServerLogs.log)
(These logs may not be useful as they only really show language server errors)

### Bug description

When updating the Essentials API from `v2.18.2` to `v2.19.0`, the `pom.xml` throws the following error: `Missing artifact org.bstats:bstats-bukkit:jar:1.8`:
![An image, displaying the error above](https://user-images.githubusercontent.com/12123847/135542445-e4785a9e-39bd-4d1e-9ed0-d9f39c72e87f.png)
![image](https://user-images.githubusercontent.com/12123847/135542797-24e63925-06a9-4fc9-b3ca-f43937c0e0b4.png)
This can be worked-around by inserting the maven dependency for bstats:
![This image shows the editor with the dependency installed. There is no error,](https://user-images.githubusercontent.com/12123847/135542626-b5212a59-0fa4-483a-8098-0819ec2082b9.png)

BTW: The message at the bottom of the bug-report refers to another box, however, it is missing:
![This image is not relevant to the bug-report](https://user-images.githubusercontent.com/12123847/135544171-e4b13187-c350-46d4-a47a-6df4c770cba8.png)

### Steps to reproduce

1. Update the EssentialsX API to version `2.19.0` in `pom.xml`

### Expected behaviour

I expected nothing to happen, apart from deprecations becoming visible.

### Actual behaviour

An error is shown: `Missing artifact org.bstats:bstats-bukkit:jar:1.8`

**Comment by imDaniX** [comment]
Add bStats to exclusions of the dependency.
```xml
<dependency>
    <groupId>net.essentialsx</groupId>
    <artifactId>EssentialsX</artifactId>
    <version>2.19.0</version>
    <scope>provided</scope>
    <exclusions>
        <exclusion>
            <groupId>org.bstats</groupId>
            <artifactId>bstats-bukkit</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```
Unfortunately, natively Maven doesn't work well with Gradle projects.
