### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by PanHaskins** [EssentialsX/Essentials#4556]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=2b8f938bad3843ec865ab00cac50e4d4

### Error log (if applicable)

https://paste.gg/p/anonymous/81abf5d6ae3440ecb2b608183574cc03

### Bug description

I don´t know.

### Steps to reproduce

I update Essentials plugin 1.10.2021 (Version 2.19.1-dev+11-b3692d1)
And console write this error.

### Expected behaviour

The plugin continues to work. I don't know what could have caused this error.

### Actual behaviour

The plugin continues to work. I don't know what could have caused this error.

**Comment by Chew** [comment]
You got rate-limited or blocked from access the update checker, essentially. It's nothing to worry about.

Not sure if this should be catched though, a random stack trace for a marginal error does indeed seem scary.
