### ISSUE TITLE
EssentialsX flooding console with UUID errors (Tried the common issue solutions already!)

### ISSUE THREAD

**Issue by Alexz1008** [EssentialsX/Essentials#4566]
### Type of bug

Performance issue or memory leak, Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=317b9484794c46a68e32eeed61c83ed8

### Error log (if applicable)

The server dump has it all

### Bug description

Essentials spams my console with newfound UUIDs but player already has UUIDs. It is exactly as is stated here: https://github.com/EssentialsX/Essentials/issues/3956#issuecomment-779254544

Here is a list of things I did to try to fix the bug:
1. I did everything said in the above link, but most of the errors in my console log are actually v4 UUID files (you can see in the logs that though some of them are v3, most are v4). I checked the yml files and I found none of them that actually had npc: true in them. They were real files.
2. I rebuilt essentials myself and set line 150 of UserMap.java from if(replace) to if(true) so that it would automatically replace the UUIDs, as in all cases I saw, the UUID essentials was trying to replace with is the CORRECT UUID.
3. This didn't fix it, even after deleting usermap.csv multiple times and letting essentials run replacements. I saw it "replace" the same name several times.
4. I added my own code that basically renamed Essentials/userdata/uuid.yml file to the new UUID, and then deleted usermap.csv. This didn't do anything, the same names were still being "replaced".
5. I completely removed every plugin except for 1, which read through my console log and did what I did in step 4, except without Essentials running, in hopes that the issue was because Essentials was running while I was replacing files. After that, I restarted essentials and noticed that it was actually starting to find the wrong UUIDs: https://gyazo.com/e6a442c09f2920ff9821ef85e6446c12
6. In the gyazo link I provided above, you'll see "Neoblade298" in there. That's actually my username. If you look me up on namemc.com, you'll notice that "c5b19383" is actually the correct UUID, and the UUID it's setting to replace that is wrong. However, some other UUIDs, like bransonevans, are correctly being replaced.

At this point I was exhausted and had no idea what to do, and my server is still lagging atrociously due to it. For what it's worth, the reason it's spamming I gather is due to the vault placeholder that does a baltop task. I do need the placeholder, so I have to leave it on.

### Steps to reproduce

Unfortunately I have no idea. I can tell you that I am using bungee though, but other plugins that get UUID seem to work just fine, including my own.

### Expected behaviour

Either Essentials should be able to make these replacements without issue or these errors shouldn't appear.

### Actual behaviour

Big console error!

**Comment by Bobcat00** [comment]
I get exceptions from /baltop using Essentials 2.19.1-dev+18-58b0fb0. It always seems to be the same players. Here's an example of one:
`[Essentials] Found UUID becf5e47-803e-4951-ae47-0f006f56e123 for player GemHuntress, but player already has a UUID (e77ca267-a020-4066-a97f-56eeafb024d7). Not replacing UUID in usermap.`
Both these UUIDs used the name GemHuntress at some point.

My server is in online mode and always has been.

Full list of exceptions - https://pastebin.com/2bnJpnX5
