### ISSUE TITLE
EssentialsX cannnot check version from API response code 403

### ISSUE THREAD

**Issue by johncsuti** [EssentialsX/Essentials#4574]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=62f22a80edf74826842e09249ea17236

### Error log (if applicable)

https://paste.gg/p/anonymous/6807d6df838a4981a4554929bb20a61a

### Bug description

Just installed essentialsx for the first time on this server and it cant connect to the API for version information? I can access the API from my browser on the same network as the server.

### Steps to reproduce

1. Install essentialsx
2. error on startup

### Expected behaviour

No errors

### Actual behaviour

Spamming chat due to version check fail.

**Comment by JRoy** [comment]
Fixed in latest dev builds.

**Comment by johncsuti** [comment]
Thanks ill download the dev build until a new version is pushed.
