### ISSUE TITLE
UUIDS Error

### ISSUE THREAD

**Issue by xEllesi** [EssentialsX/Essentials#4578]
### Type of bug

Performance issue or memory leak, Error in console, Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=77020d11ec72407b80c8748e42e5fcd4

### Error log (if applicable)

https://paste.gg/p/anonymous/137731e7d74f46b6acc7edd988832df9

### Bug description

I follow the guide https://github.com/EssentialsX/Essentials/issues/3956 deleted all corrupted uuids, deleted usermap but every time i restart the server all of them are created again. The strange thing is that most of them just have like 50's kbs size and the only thing in the config is npc: true

### Steps to reproduce

1. Delete all corrupted uuids
2. delete usermap
3. restart

### Expected behaviour

its suposed to not create empty files

### Actual behaviour

I cant use some commands like /baltop or the server crashes

**Comment by JRoy** [comment]
This should be mitigated by #4581 once it is complete.
