### ISSUE TITLE
[Suggestion] - EssentialsX GeoIP - Ban Players by Country

### ISSUE THREAD

**Issue by clovisd** [EssentialsX/Essentials#458]
Hey!

Would it be possible to add support to Essentials GeoIP to ban players connecting from certain countries or regions?

Thanks,
C

**Comment by drtshock** [comment]
why racist? :(

**Comment by Kakifrucht** [comment]
This sounds like something an external plugin should / can accomplish. Take a look at BanManager.

**Comment by drtshock** [comment]
Debatable. I can see the justification for just banning an IP range. Just don't frame it as racism!

**Comment by Platinteufel** [comment]
AuthMe Reloaded already implements this.

**Comment by pop4959** [comment]
If someone feels like implementing this eventually, feel free. Although as mentioned this sounds like something you could just use another ban plugin for.
