### ISSUE TITLE
Inconsistent /back behavior

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#4582]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=e6b995e340284612af824ea36572f4fb

## Problem: /back has inconsistent behavior

**Details:*

Running EssentialsX with no permissions plugin and using /back as an OP results in being randomly teleported with no error stating you don't have permission. It just teleports you to a random location in your world. /back does appear to work correctly otherwise.

***Expected Behavior**

EssentialsX despite technically having permission to use /back as an OP should send a message to the user that they do not have permission to use /back and do nothing else.

### Steps to reproduce

1. OP yourself
2. Kill yourself in game
3. attempt to use /back without having the permission: ```essentials.back.ondeath```

### Expected behaviour

Using /back without permission even as an operator should send an error to the client about a lack of correct permissions

### Actual behaviour

/back will teleport you to a random location in the world.

**Comment by Octol1ttle** [comment]
![image](https://user-images.githubusercontent.com/61277953/138029617-466ea27d-7e78-44cf-bec8-a1e0e0c13ac4.png)
Can't replicate, but got `Error: No valid location found` in all attempts instead o_O

**Comment by Laarryy** [comment]
I can replicate this with Paper 1.17 - to add, it seems to teleport me to somewhere I *was* but rather long before my death.

I don't think it should say "No Permission", though @0xD3ADC0W, because OPs are supposed to have permission to run any command/do any 'positive' action. Only things like preventative permissions should really be denied to OPs

**Comment by JRoy** [comment]
`/back` is behaving as expected for OP'd players. 
* `essentials.back.ondeath` defaults to false for OP'd players.
* `/back` doesn't teleport you to "random" locations, it teleports you to the last place you were teleported to by Essentials (or depending on your config, teleported in general).
