### ISSUE TITLE
delhome usage

### ISSUE THREAD

**Issue by seema84** [EssentialsX/Essentials#4583]
### Type of bug

Other unexpected behaviour

### Bug description

**Version:**

Server Version: 1.16.5-R0.1-SNAPSHOT git-Paper-786 (MC: 1.16.5)
Brand Version: Paper
EssentialsX Version: 2.19.1-dev+17-90e4845
LuckPerms Version: 5.3.0
Vault Version: 1.7.3-b131
EssentialsXChat Version: 2.19.1-dev+17-90e4845
Citizens Version: 2.0.27-SNAPSHOT (build 2317)
ChestShop Version: 3.12 (build 307)
Economy Layer: Vault Compatibility Layer (Fe)
Fetching version information...
You're running the latest EssentialsX dev build!

Usage2 is displayed even if i have no perms. I think that should not be so.

### Steps to reproduce

1. set the essentials.delhome perm (without essentials.delhome.others)
2. set two or more homes
3. use /delhome (without a name)
4. look at the command description

![567](https://user-images.githubusercontent.com/2832339/137717721-fbadcee9-55cc-4212-99fe-5f8cf7291c3c.PNG)

the usage2 for essentials.delhome.others will display

### Expected behaviour

a description only for what you have perms for

### Actual behaviour

currently the complete description is displayed

**Comment by Laarryy** [comment]
Please take the time to fill out the rest of the issue, especially the dump output. If you can't run the command, you need to update Essentials.

**Comment by seema84** [comment]
the dump information is not required for the problem

**Comment by JRoy** [comment]
Usage messages are displayed irrespective of permissions, this is not a bug.
