### ISSUE TITLE
Can't delete warps if the world is unloaded

### ISSUE THREAD

**Issue by JasonHorkles** [EssentialsX/Essentials#4584]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=46e21378e02b470890009e549eeae648

### Bug description

When using `/delwarp <warp>` on a warp in a no-longer-existent world, it says the warp doesn't exist

### Steps to reproduce

1. Create a warp in a world
2. Unload the world
3. Try to delete the warp

### Expected behaviour

It should delete the warp

### Actual behaviour

It doesn't delete the warp

**Comment by Octol1ttle** [comment]
![image](https://user-images.githubusercontent.com/61277953/138032979-e034f1b9-4166-4781-8675-9361ab13504e.png)
Successfully replicated
