### ISSUE TITLE
Why does my console brush the frequency "/ clear"???

### ISSUE THREAD

**Issue by QianMuu** [EssentialsX/Essentials#4596]
### Type of bug

Error in console

### `/ess dump all` output

CONSOLE issued server command: /clear
CONSOLE issued server command: /clear
CONSOLE issued server command: /clear

### Bug description

I use forge + bukkit server, and my console will brush the information of "console issued server command: / clear" every once in a while.

It will also be displayed when attacking entities.

After a long time of testing, I found that it was the "Essentials" problem.

Who can tell me why?

### Steps to reproduce

Irregular continuous errors!

An error will also occur when attacking all entities!

### Expected behaviour

solve the problem

### Actual behaviour

I don't know the problem

**Comment by Chew** [comment]
> I use forge + bukkit server

All Forge+Bukkit hybrids are unsupported. Please reproduce on a non-hybrid server.

**Comment by QianMuu** [comment]
> > 我使用伪造 + bukkit 服务器
> 
> 不支持所有 Forge+Bukkit 混合动力车。请在非混合服务器上重现。



> > 我使用我好 + bukkit 服务器
> 
> 不支持所有 Forge+Bukkit 混合动力车。请在非混合服务器上再现。

But forge + paper doesn't work either. Doesn't it support mod?
