### ISSUE TITLE
Every player that joins since the switch to EssentialsX treated as new players.

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#460]
Since I switched to EssentialsX every time a player joins for the first time since I switched to EssentialsX gets their inventory reset because they are treated like a new player joining for the first time.

They keep their homes, money and everything else, only their inventory's gets reset and the welcome-to-the-server-message pops up.

All the userdata-files in the Essentials Config are still there.

**Comment by ghost** [comment]
It seems to be something about their UUID's: http://hastebin.com/tasutopoce.vbs

**Comment by drtshock** [comment]
Did you switch from offline to online mode?
