### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by LuluxClient** [EssentialsX/Essentials#4607]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=a771b0e6ea0144d799080957d2b2757b

### Bug description

Even if I have encoding to UTF-8 and I made sure to save and the server was offline I still get these weird boxes when doing /xp https://gyazo.com/eb3cc7de35ca26df489ccdc6a27f434f 

### Steps to reproduce

1. do /xp set PlayerName 10000L
2. read your chat

### Expected behaviour

I shouldn't see these small boxes

### Actual behaviour

I should see a " , " or a " . " no Idea where I could edit that in the config (using default config) I'm on paperspigot 1.17.1 essentialsX dev ver

**Comment by JRoy** [comment]
This is a font issue on the client, make sure you're using the actual ASCII characters supported by the MC font.
