### ISSUE TITLE
EssentialsX is flooding my console with UUID errors!

### ISSUE THREAD

**Issue by Ironic8b498** [EssentialsX/Essentials#4609]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=cf119eee37bb4e409c2f455ec6ae60b2

### Error log (if applicable)

https://paste.helpch.at/ezeguqugek.md

### Bug description

at bootup I get above message in logs

### Steps to reproduce

This server is running on Java8
I have stopped server, deleted these folders and file
userdata
usermap.csv

and at start of server no one joining I get the warn in logs

### Expected behaviour

not to see players with two UUID's

### Actual behaviour

sees players with two UUID's upon login

**Comment by JRoy** [comment]
#4581 will resolve this
