### ISSUE TITLE
[Bug] Big exp duplication

### ISSUE THREAD

**Issue by voodootje0** [EssentialsX/Essentials#462]
Hey,

There is a EXP bug with queue voting on my server.
First the player joins 
![image](https://cloud.githubusercontent.com/assets/6852308/13547011/35e3da86-e2c0-11e5-8f2d-92beed1e113e.png)
A few seconds later
![image](https://cloud.githubusercontent.com/assets/6852308/13547018/7e40db6c-e2c0-11e5-866d-f7805e0d4cc4.png)
The voting rewards are 100 EXP + 500 balance.
How this can happen?
- voodootje0

**Comment by drtshock** [comment]
Can you describe what the issue is and what the expected behavior should be?

**Comment by AcesGamingUK** [comment]
also are you sure is giving 100 xp, and not 100xp levels
maybe add a copy of the config
