### ISSUE TITLE
Some items cannot be given.

### ISSUE THREAD

**Issue by supportcorp** [EssentialsX/Essentials#4623]
### Type of bug

Data loss

### `/ess dump all` output

https://essentialsx.net/dump.html?id=10e2a64315f7459b9527af5d3ee750e7

### Bug description

Initially, I was creating advancement for my server and came across that with the correct advancement configuration I was getting errors with some items (gilded_blackstone or netherite_ingot). I created a separate server where I checked each plugin (because everything works fine on an empty spigot) and realized that the problem was in the essentials (any version 2.19.0 or 2.19.1). The problem is this: you cannot even give items using the standard command (give @p minecraft: gilded_blackstone) or with netherite_ingot. Returns the "unknown item name", the same the console swore at when creating advancement with the participation of these items

### Steps to reproduce

1) Start server with essentials plugins only
2) Login to the game with administrator rights
3) Try to issue netherite_ingot or gilded_blackstone using the give command
4) Result (incorrect item name)

### Expected behaviour

The item issues, everything is fine with id, advancemets will work

### Actual behaviour

No item identifiers, violation of the identifier system

**Comment by supportcorp** [comment]
do not pay attention to chunk loading logs

**Comment by supportcorp** [comment]
I found an error in the advancement settings, but it's not a problem that the item does not give out via give

**Comment by JRoy** [comment]
Cannot reproduce.


https://user-images.githubusercontent.com/10731363/141221852-e7b73365-2ab4-413a-ab33-5e937d2e209c.mp4

Either drop the `minecraft:` before your item name or instead use the `/minecraft:give` command
