### ISSUE TITLE
[Trade] signs become inaccessible if player changes their username

### ISSUE THREAD

**Issue by whimsicalities** [EssentialsX/Essentials#4625]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=673e83ed82cd484f8ac8bcea60ea1181

### Bug description

A player on the server who changed their minecraft username reported that they could no longer access their [Trade] signs.

### Steps to reproduce

1. Create a [Trade] sign
2. Change minecraft account name
3. Try to access trade sign earnings

### Expected behaviour

Able to access earnings.

### Actual behaviour

Unable to access. Resources are locked into sign.

**Comment by JRoy** [comment]
~~Duplicate of #81~~

Edit by @mdcfe: no it isn't

**Comment by mdcfe** [comment]
#4713 implements player UUID storage using `PersistentDataContainer` on 1.14+.

**Comment by mdcfe** [comment]
In addition, for the sake of clarity, this issue was a duplicate of #1117.

**Comment by TheMattVid** [comment]
Is this still an issue? I had a player lose access to their trade signs on EssentialsX 2.19.7 after changing usernames.
