### ISSUE TITLE
WorldGuard 'invincible' flag is not working with EssentialsX

### ISSUE THREAD

**Issue by rona-tombo** [EssentialsX/Essentials#4627]
### Type of bug

Compatibility issue

### `/ess dump all` output

https://essentialsx.net/dump.html?id=2662566d22bb45a9a8c21c67ddb41803

### Bug description

When we use 'invincible' flag on WorldGuard with EssentialsX, but the flag doesn't not work.
ref: https://github.com/EngineHub/WorldGuard/issues/1852

### Steps to reproduce

1. Install WorldEdit / WorldGuard / EssentialsX to the server.
2. Start a server and define a region (`/rg define test`) and set a flag to allow (`/rg flag test invincible allow`).

### Expected behaviour

The flag works good, player makes as a god mode.

### Actual behaviour

Nothing error but player won't be invincible.

**Comment by Bobcat00** [comment]
Invincible works with EssentialsX on my server.

Stand in the region and do `/region info`. What does it say?

**Comment by rona-tombo** [comment]
![](https://user-images.githubusercontent.com/41550858/141840839-f0e85053-db74-4f08-98a1-721d9a65a790.png)
I only set invincible flag.

**Comment by oskarkk** [comment]
What are you doing that deals you damage?

Also you must know that for a flag like this to take effect, you must leave the region (walk out of it) and enter it again. That's how WorldGuard works, and I once thought that I found some bug, because I wasn't invincible when I set that flag in a region I was in.

**Comment by JRoy** [comment]
Cannot reproduce, make sure you don't have the `*` permission.
