### ISSUE TITLE
tp saftey not turning off

### ISSUE THREAD

**Issue by SilverHammer09** [EssentialsX/Essentials#4632]
### Type of bug

Performance issue or memory leak

### `/ess dump all` output

https://essentialsx.net/dump.html?id=e902dd33e5a1448ba1ce1c361e34ddcb

### Bug description

im tring to turn off tp safety i go in config and i turn true on "This forcefully disables teleport safety checks without a warning if attempting to teleport to unsafe locations. teleport-safety and this option need to be set to true to force teleportation to dangerous locations. force-disable-teleport-safety: true" i load up and its still there i changed other ones to what do i do im i missing somthing? i have also checked my bed no monsters nothing that is bad

### Steps to reproduce

1.home bed or tpa someone or just tp
thats all and it just pops up on anything and its super annoying

### Expected behaviour

tp me to my bed or my freind or home

### Actual behaviour

it wont tp and it tells me its unsafe place and thats tp saftey is disabiled??

**Comment by Chew** [comment]
Not seeing a config in your paste, did you run `/ess dump all`? Not much we can do without seeing it and telling you to make sure `teleport-safety` and `force-disable-teleport-safety` are set to true.

**Comment by SilverHammer09** [comment]
i did not do ess dump all i will do that and where do you find teleport-safety i could never find that

**Comment by SilverHammer09** [comment]
https://essentialsx.net/dump.html?id=e902dd33e5a1448ba1ce1c361e34ddcb

**Comment by JRoy** [comment]
While I can't reproduce or find anything that would cause this issue, I did find an issue with setting unsafe homes with force-disable-teleport-safety enabled.
