### ISSUE TITLE
seems that ess.getUser is called repeatedly instead of just once.

### ISSUE THREAD

**Issue by WarnDa** [EssentialsX/Essentials#4636]
### Type of bug

Performance issue or memory leak

### `/ess dump all` output

https://essentialsx.net/dump.html?id=5c7e6b350d7b493aa5b163b69dd1d189

### Bug description

I opened an issue on luckperms because I needed to optimise it.
The dev found the issue was the "getcontect" that had performances issue.
He fixed it but he told me 
> The remaining %s are mostly coming from the EssentialsX context calculators. You could open an issue there for them to track it - problem seems to be that ess.getUser is called repeatedly instead of just once.
I had a quick look but it's not a super strightforward fix without changing their current design.

https://github.com/LuckPerms/LuckPerms/issues/3209#issuecomment-974338588

I don't know if he is right or not, but I create an issue, we never know :)

### Steps to reproduce

https://github.com/LuckPerms/LuckPerms/issues/3209#issuecomment-974338588

### Expected behaviour

*

### Actual behaviour

*

**Comment by JRoy** [comment]
This would likely be fixed in #4581

**Comment by WarnDa** [comment]
I'll try to update tomorrow and tell you, thanks !

**Comment by WarnDa** [comment]
It's better thanks !
