### ISSUE TITLE
[Very Important Feature Request] Spawn eggs in shop signs

### ISSUE THREAD

**Issue by boredhero** [EssentialsX/Essentials#465]
Hey, so can you PLEASE make it so that we can use strings like HorseEgg to sell and buy mob eggs. Right now if you use those ids it just gives you blank eggs that don't work. You need to make an adjustment so that when someone makes a sign, it checks for HorseEgg and it gives the person an egg and tags it with a metadata that mojang uses to make the spawn eggs different from each other. I know this might be a decent amount of work but its a really important feature that I feel alot of people /especially/ me, need.

**Comment by Kakifrucht** [comment]
Why would you tag this as very important? It is clearly not.

**Comment by boredhero** [comment]
yes it is. its a serious bug in the shops.

**Comment by Done84** [comment]
Its working fine for me for all mobs including horses.
http://prntscr.com/abt37y

Use item id 383:100

**Comment by boredhero** [comment]
I'll give it a try tomorrow and report back. For me all the eggs have an ID of 383:0

**Comment by Done84** [comment]
Make sure you using the latest build and use /itemdb wile holding the eggs to get the correct ID. If that fails then you might have an issue in the items.csv, if thats the case and unless you customized names there, just delete it and reload to regen a new one.

**Comment by SupaHam** [comment]
In 1.9, Minecraft no longer supports the item data value as a unique type of monster egg, instead they use NBT tags. To spawn an egg with EssentialsX use: `/i 383 1 {EntityTag:{id:"Creeper"}}, where`Creeper` is the Minecraft entity id. For a list of all minecraft entities and their ids click [here](http://minecraft.gamepedia.com/Data_values/Entity_IDs).

**Comment by Done84** [comment]
Oh. I didnt know he was on 1.9.. But he asked about sell/buy sign support not /i /give.

**Comment by SupaHam** [comment]
Sadly, the current itemdb which provides these aliases doesn't support NBT tags as mentioned above, instead they alias item:data, so you will have to wait for further updates regarding this issue specifically in order to be able to sell mob eggs.

**Comment by boredhero** [comment]
Okay. Thanks. I just wanted to make sure someone knew it was an issue in 1.9. I ended up buying a Plugin to do it. Sadly I can still only buy and sell 1 at a time. In 1.7 you couldnt use datavalues to buy spawners anymore,  so my workaround was to configure a Plugin so my players could buy a mob egg and right click the ground and rather than spawning a mob it would place the respective spawner. Now the paid Plugin I bought only supports buying one spawner at a time but at least my players can buy spawners again.
