### ISSUE TITLE
Hex Codes not working on 1.16.

### ISSUE THREAD

**Issue by tangerine349** [EssentialsX/Essentials#4652]
### Type of bug

Compatibility issue

### `/ess dump all` output

https://essentialsx.net/dump.html?id=0cc18c64d96e4c1f9e14697838a3f578

### Error log (if applicable)

No errors

### Bug description

When using Hex codes on 1.16.5 with Luckperms Prefixes, the hex codes dont show up

### Steps to reproduce

1. Have a prefix with Hex Codes under luckperms
2. Type in chat.

### Expected behaviour

https://gyazo.com/d2fd8879edbc908a4aa25a3e66d17dcf (In 1.17.1)

### Actual behaviour

https://gyazo.com/e045a1bd5d0800ded25f5472083e7240

**Comment by triagonal** [comment]
Unable to reproduce. 

```
[19:41:41 INFO]: Server version: 1.16.5-R0.1-SNAPSHOT git-Paper-783 (MC: 1.16.5)
[19:41:41 INFO]: Brand version: Paper
[19:41:41 INFO]: EssentialsX version: 2.19.1-dev+39-f8ca1ba
[19:41:41 INFO]: LuckPerms version: 5.3.83
[19:41:41 INFO]: Vault version: 1.7.3-b131
```

Using the below group meta and your chat format, the hex code was correctly parsed and the prefix colored on both 1.16.5 and 1.17.1. Could you try again with just EssentialsX, EssentialsXChat, Vault, and LuckPerms installed?

![image](https://user-images.githubusercontent.com/10545540/144013678-785bed29-db12-427d-92ce-e6d635b477cf.png)
