### ISSUE TITLE
Essentials Spawn with TP-Command not working

### ISSUE THREAD

**Issue by colaman90** [EssentialsX/Essentials#4654]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=3a58e7ba3f61463d807253fae6f8773c

### Bug description

Hi all,

we have a command in commands.yml like this:

`  teleport-with-back:
  - warp spawn $$1
  - minecraft:execute in minecraft:overworld run teleport $$1 $$2-`

This command should warp the player to the "spawn" and then teleport him to a given location.

In this case, the warp and TP Command will be executed, but you will stand on the warp spawn, not the TP Coordinates.

We tried it simply with just Paper 1.17.1,  EssentialsX 2.19.0 and Multiverse (4.3.1)

If you type the command manually in the console, it will work probably. I think there should be a wait or delay timer in Essentials to avoid this behavior. 

In prev Versions (like 2.18) this Bug is not happening in all cases.

### Steps to reproduce

1. Load a Overworld and any other world.
2. Insert a Warp Spawn in Essentials Config
3. Insert into commands.yml
 `  teleport-with-back:
  - warp spawn $$1
  - minecraft:execute in minecraft:overworld run teleport $$1 $$2-`
4. Go the other world and execute: /teleport-with-back %PLAYER% ANY OTHER COORDINATES THAN SPAWN
5. You will see, you will be spawned, but you will not be teleportet to the coordinates.

### Expected behaviour

You should be spawned and then teleported.

### Actual behaviour

You will be spawned, but you will not be teleportet to the coordinates.

**Comment by WhiteColors** [comment]
![image](https://user-images.githubusercontent.com/49518591/144668570-0537f26b-0cbc-4967-91e7-f637c33bac81.png)
We can just type rank+name, and we can be teleported to the player

**Comment by JRoy** [comment]
This is likely due to async teleportation. If you need sync teleportation, use vanilla commands.
