### ISSUE TITLE
Possible issue with PEX and/or EssentialsX?

### ISSUE THREAD

**Issue by KCQuetzal** [EssentialsX/Essentials#466]
I have noticed on my testing server that some permissions don't seem to be working as they should.

Example:

Having set the perm essentials.gamemode to a group yet I still get the message that I do not have the perm when trying to use /gm or any of the aliases for gamemode.  I am only able to use the command as Op.

Using PEX 1.23.4, EssentialsX Build #301, and Spigot 1.9 build b39373b-249c5f0

**Comment by AcesGamingUK** [comment]
Have you given essentials.gamemode   and essentials.gamemode.(gamemode)?

**Comment by KCQuetzal** [comment]
Thank you very much for your response and assistance!  That indeed was the issue.  I did not see the need for specifying (gamemode) on the main permissions list page but once you pointed out to me what you did I looked up on https://github.com/drtshock/Essentials/wiki and saw exactly what you stated.  Sorry for not noticing that before reaching out for assistance!  Thanks again!

**Comment by drtshock** [comment]
@AcesGamingUK thanks for helping him.

@KCQuetzal thanks for coming to the right place for help!
