### ISSUE TITLE
Under y=0 Fly gets reenabled automatically

### ISSUE THREAD

**Issue by Comitant** [EssentialsX/Essentials#4665]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=c041cea1f72941fbbffdc7bad17c00d4

### Bug description

While opped, fly mode gets reenabled every time I rejoin the server under a certain y level. This does not happen normally, only under y=-1. This command "essentials.fly.safelogin" may be doing it, it describes itself as only enabling on rejoin if you're in the air, so I would assume that it thinks everything under y=-1 is void since 1.18 added new stuff.

### Steps to reproduce

1. Start as a server op.
2. Make a hole down to y=-1
3. Go into survival mode.
4. Make sure fly is already toggled off and try rejoining.

### Expected behaviour

It should log me back in without enabling fly mode unless I'm currently in the air.

### Actual behaviour

It thinks I'm in the void at y=-1 and below so it is always enabling fly regardless.

**Comment by Pirgosth** [comment]
Re, this fix is incomplete, it still does not work below Y=0 for versions above 1.18, here you can find the PR that truly fixed it #4715. 
The reason is simple, you did not updated the world minimum height in the else condition for the shouldFly test function.
