### ISSUE TITLE
/tpaccept BUG

### ISSUE THREAD

**Issue by Laminatik** [EssentialsX/Essentials#4669]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=b343fead561a492f87335dbe1757b41e

### Bug description

After a player has sent another player a teleport request (/ call <nick>), the second player can only accept this request in the first few seconds. Which is strange, since the config says tpa-accept-cancellation: 120
I tried to change this value to 0 but nothing changed the teleportations just canceled itself after 3-5 seconds.

### Steps to reproduce

Have 2 players
Player1: /call Player2
Player2: wait 10 seconds and /tpaccept
But Player2 receives a message stating that it cannot accept this request because it was canceled(but it has not been canceled and the 120 second time has not elapsed.).
--------
Have 2 players
Player1: /call Player2
Player2: instantly writes a command /tpaccept
Player1 successfully teleports to Player2
------
Config:
tpa-accept-cancellation: 120

### Expected behaviour

Have 2 players
Player1: /call Player2
Player2: within 120 seconds has the ability to accept the player's request. (/tpaccept)
Player1 successfully teleports to Player2
------
Config:
tpa-accept-cancellation: 120

### Actual behaviour

The plugin is behaving strangely.

**Comment by Chew** [comment]
You are out of date, please reproduce on the latest dev build. https://essentialsx.net/downloads.html

We've just made some changes to TPA that may have solved this.

**Comment by JRoy** [comment]
The latest dev builds have a brand new TPA system in it, likely fixes this issue.
