### ISSUE TITLE
Unban not working.

### ISSUE THREAD

**Issue by Done84** [EssentialsX/Essentials#467]
I had this bug for ages, and it still persists in EssentialsX.
If I ban a player and then unban the players is not removed from the banned-players.json and my only option is to edit the file manually and restart the server.

**Comment by drtshock** [comment]
Increase your usercache

**Comment by tteeee** [comment]
user-cache-size: 1000?

**Comment by saturnux** [comment]
if player don't log on server (and it's kicked fon banned) you can't pandon her.
(si le client n'essai pas de se connecter on ne peut pas le pardonner)
it's a minecraft isue on 1.8 (i think it's 1.8 but 1.7 ?¿ the source is json file )

**Comment by andris155** [comment]
Use: /minecraft:pardon playername

**Comment by drtshock** [comment]
not an actual issue
