### ISSUE TITLE
EssentialsDiscord stuck on logging in (in Docker)

### ISSUE THREAD

**Issue by GGORG0** [EssentialsX/Essentials#4672]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

(The server doesn't start up)

### Bug description

When starting up the server, EssentialsDiscord is stuck on
```
[14:48:36 INFO]: [EssentialsDiscord] Enabling EssentialsDiscord v2.19.0
[14:48:36 INFO]: [EssentialsDiscord] Starting Metrics. Opt-out using the global bStats config.
[14:48:36 INFO]: [EssentialsDiscord] Attempting to login to Discord...
```
and doesn't let the server start up. My config: https://paste.gg/p/anonymous/16ac52acb4b04fa99f94c75d3b80fc8c .
EssentialsX and EssentialsDiscord verison: 2.19.0 stable
Server: Paper 1.17.1-391

### Steps to reproduce

1. Use my config and invite the bot using https://essentialsx.net/wiki/Discord-Tutorial.html
2. Start the server up.

### Expected behaviour

The server starts up and the bot works.

### Actual behaviour

The plugin is stuck.

**Comment by JRoy** [comment]
Can you please try the latest dev build and see if you still have the issue?

**Comment by GGORG0** [comment]
Ok.

**Comment by GGORG0** [comment]
No, unfortunately the issue it still there on Essentials/EssentialsDiscord v2.19.1-dev+52-41861a8
Also, sorry for late replies :).

**Comment by JRoy** [comment]
@GGORG0 can you share you're entire `latest.log`

**Comment by GGORG0** [comment]
Where is it?

**Comment by JRoy** [comment]
`logs/latest.log`

**Comment by GGORG0** [comment]
Oh ok, I thought it was somewhere in the plugins folder. Here: https://paste.gg/p/anonymous/8bdbcd61369c436f86eadb63d1ec6f2c

**Comment by JRoy** [comment]
> Oh ok, I thought it was somewhere in the plugins folder. Here: [paste.gg/p/anonymous/8bdbcd61369c436f86eadb63d1ec6f2c](https://paste.gg/p/anonymous/8bdbcd61369c436f86eadb63d1ec6f2c)

Can you stop your server, enable debug in `server.properties`, enable debug in `plugins/Essentials/config.yml`, start your server and then share your startup log

**Comment by GGORG0** [comment]
Also, I don't know if that matters, but I use https://github.com/itzg/docker-minecraft-server/ . I'll share the debug logs in a minute.

**Comment by GGORG0** [comment]
> > Oh ok, I thought it was somewhere in the plugins folder. Here: [paste.gg/p/anonymous/8bdbcd61369c436f86eadb63d1ec6f2c](https://paste.gg/p/anonymous/8bdbcd61369c436f86eadb63d1ec6f2c)
> 
> Can you stop your server, enable debug in `server.properties`, enable debug in `plugins/Essentials/config.yml`, start your server and then share your startup log

Here: https://paste.gg/p/anonymous/a81d255516974cb3976f996d5e112ed6

**Comment by GGORG0** [comment]
@JRoy Any news?

**Comment by JRoy** [comment]
> @JRoy Any news?

can you reproduce this on your local machine and outside the docker environment

**Comment by GGORG0** [comment]
I was doing this right now (just finished downloading the files)

**Comment by GGORG0** [comment]
Well, it works on my machine without docker....

**Comment by JRoy** [comment]
> Well, it works on my machine without docker....

In that case it's probably something firewall related blocking the websocket connection to discord.

**Comment by GGORG0** [comment]
Oh, so what could I do?

**Comment by JRoy** [comment]
> Oh, so what could I do?

No idea, I'm not that familiar with docker.

**Comment by GGORG0** [comment]
Well, it works in docker on my machine. Also, the same goes for command tab completion. I think something is wrong with my VPS...

**Comment by DJGiggles** [comment]
I also have this issue, working on my computer but does not work in a docker container

**Comment by GGORG0** [comment]
> Well, it works in docker on my machine. Also, the same goes for command tab completion. I think something is wrong with my VPS...

Well, yes there is something wrong with my VPS, because it works in docker on my PC, and it doesn't work on the VPS even if I run it manually. The VPS is running Ubuntu Server 20.04 and my PC is running Arch Linux.

**Comment by gregkeys** [comment]
I'm having the same issue, stuck loggin in but we're running docker containers on kubernetes

**Comment by WiseHollow** [comment]
This issue also exists when running docker containers from Pterodactyl panel.

**Comment by gregkeys** [comment]
@GGORG0 im also using the https://github.com/itzg/docker-minecraft-server/ docker image

**Comment by SubwooferNL** [comment]
i have the same thing with pterodactyl like WiseHollow

**Comment by Radiant-Xyz** [comment]
I am using PufferPanel in Docker and experience the same issue.

Server: Paper-398 (MC: 1.17.1)
Plugins:
- Dynmap 3.2.1
- EssentialsX-2.19.1-dev+52-41861a8
- EssentialsXChat-2.19.1-dev+52-41861a8
- EssentialsXDiscord-2.19.1-dev+52-41861a8
- EssentialsXSpawn-2.19.1-dev+52-41861a8
- floodgate-spigot-53
- Geyser-Spigot-957
- LuckPerms-Bukkit-5.3.87
- Vault-1.7.3

**Comment by GGORG0** [comment]
Also, if that matters, I use Docker CE version 20.10.11, build dea9396

**Comment by HyplexMC** [comment]
can confirm this is happening to me as well with pterodactly

**Comment by JRoy** [comment]
Likely an issue with single core systems

Related to https://github.com/DV8FromTheWorld/JDA/issues/1858

**Comment by WiseHollow** [comment]
> Likely an issue with single core systems
> 
> Related to [DV8FromTheWorld/JDA#1858](https://github.com/DV8FromTheWorld/JDA/issues/1858)

Thank you for that link. You're correct. There is a workaround until OpenJDK fixes this issue. Use this within your startup parameters when launching your server jar file.

-Djava.util.concurrent.ForkJoinPool.common.parallelism=1

For example, here is my Pterodactyl startup command-

java -Xms128M -Xmx{{SERVER_MEMORY}}M -Dterminal.jline=false -Dterminal.ansi=true -Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -jar {{SERVER_JARFILE}}

**Comment by gregkeys** [comment]
This workaround worked for us.

**Comment by Radiant-Xyz** [comment]
The dev build 5f98d3f which contains #4711 does not fix the issue for me. I still need to use the workaround.

This line from the console in Pufferpanel seems to contain version information.
`System Info: Java 17 (OpenJDK 64-Bit Server VM 17+35-Ubuntu-120.04) Host: Linux 5.10.81+truenas (amd64)`
Maybe the check used in the mitigation does not work here? The info message does not appear in the log at all.

**Comment by ciubciubpl** [comment]
This issue is still not fixed and should be re-opened.

**Comment by pop4959** [comment]
> This issue is still not fixed and should be re-opened.

Can you elaborate? What isn't fixed. If you mean the JDK bug itself, that isn't on us and you should use existing workarounds until further notice. Don't solely rely on the mitigations in place.

**Comment by mdcfe** [comment]
> This issue is still not fixed and should be re-opened.

@ciubciubpl This is an OpenJDK bug, there's nothing we can do about it. You need to update your Java runtime to 17.0.2 or later.
