### ISSUE TITLE
Potion and Tipped Arrow's metadata/potiondata not saved with /createkit

### ISSUE THREAD

**Issue by ajthemacboy** [EssentialsX/Essentials#468]
When trying to create a kit using `/createkit` with a tipped arrow, the kit returns an "Arrow of Splashing" with no effects.

Please make this work with all tipped arrows, such as levitation arrows which can only be summoned with a command!

Edit: Actually, potions don't work either; they just return water bottles.

**Comment by SupaHam** [comment]
1.9 fundamentally changed the way some items work by introducing NBT tags as opposed to limited item damage values, `/give SupaHam tipped_arrow 1 {Potion:"swiftness"}` will give me one Tipped Arrow with a default swiftness effect, click [here](http://minecraft.gamepedia.com/Potion#Item_data) for a list of Potion types.

Alternatively and more complexly, you can use `CustomPotionEffects` to define custom effects: `/give SupaHam tipped_arrow 1 { CustomPotionEffects: [ {Id: 25, Amplifier: 1, Duration: 200} ] }` will give me one Tipped Arrow with a levitation effect, amplifier 1, and a duration of 200 ticks (10 seconds).

For more information, see: http://minecraft.gamepedia.com/Arrow

**Comment by ajthemacboy** [comment]
I was just playing around with this and realized that. 

It turns out the issue is that the `/createkit` command doesn't save potion data or arrow data. When manually creating kits, they seem to work fine; the command just doesn't.

**Comment by ajthemacboy** [comment]
Can you confirm this issue is real and re-open, or should I create another issue?

**Comment by drtshock** [comment]
Duplicated by https://github.com/drtshock/Essentials/issues/455

It is an issue, but you can also use @SupaHam's command in kits for now until we get it implemented.
