### ISSUE TITLE
[1.9] Incompatibility with SIlkSpawners and Ops placing spawners. Config flag?

### ISSUE THREAD

**Issue by boredhero** [EssentialsX/Essentials#469]
Hello, because essentials x supports natively changing spawner types, it tries to regularly override the plugin SilkSpawners whenever people who are op or have certain perms place spawners. According to console:

06.03 15:44:11 [Server] INFO checking if boredherobrine13 has essentials.spawnerconvert.pig - true
06.03 15:44:11 [Server] WARN Skipping BlockEntity with id 

Anyone who has the permissions essentials.spawnerconvert.pig (or is op) it will automatically convert their spawners of various types to pig when placed. Note that they only change after one mob has spawned. This occurs on the latest build of spigot and latest build of essentials x. I understand the reasoning behind this but is it possible to maybe add a configuration flag to hand over all control of spawners to other plugins (aka disable the part of the code that handles spawner conversions if a config flag is set to true)

Thanks.

**Comment by boredhero** [comment]
Anyone seen this?

**Comment by philip-ulrich** [comment]
I have. Didn't know it was because of EssentialsX though. Super annoying bug.

**Comment by boredhero** [comment]
Yeah but it shouldn't be hard to fix... Hope  a dev sees this

**Comment by philip-ulrich** [comment]
I wish you could vote for issues on github. :)

**Comment by drtshock** [comment]
There's :+1: :)

**Comment by philip-ulrich** [comment]
@drtshock It's not the same, Trent! :-1:

**Comment by boredhero** [comment]
Any idea if this is doable drtshock?

**Comment by NCSGeek** [comment]
I seem to have this bug, if no fix is found.

**Comment by mdcfe** [comment]
Is this even a bug? As far as I can tell, `essentials.spawnerconvert.<mob>` is doing what it's supposed to be doing. If you don't want this behaviour, revoke/negate the permission.

**Comment by pop4959** [comment]
Yeah as far as I can tell, this is fixed by giving proper permissions, and is intended (akin to what md is saying). If this is not true, please notify us and give more details as to what exactly you are expecting Essentials to do differently.
