### ISSUE TITLE
essentials cooldown bypass won't work with /back

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#4696]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=195d3c37428147609b9fcafdd6932fbd

### Bug description

Have a rank with the permissions;
essentials.teleport.cooldown.bypass.* and essentials.teleport.cooldown.bypass.back but for a reason the cooldown for /back command it's still there.

### Steps to reproduce

Set a cooldown to back on config.yml
Give the permissions essentials.teleport.cooldown.bypass.* or essentials.teleport.cooldown.bypass.back to a rank.
Try to use /back 2 times.

### Expected behaviour

/back should't have cooldown.

### Actual behaviour

/back have the cooldown set on config.yml

**Comment by mdcfe** [comment]
We don't have the information required to determine how your cooldown is configured. Either you didn't run `/ess dump all` or you're not running the latest version of EssentialsX. Please ensure you're on `2.19.2` or `2.19.3-dev` then post a full dump with `/ess dump all`.

**Comment by ghost** [comment]
[16:11:13 INFO]: Creando volcado del servidor...
[16:11:13 INFO]: Se ha creado el volcado del servidor: https://essentialsx.net/dump.html?id=e382ba982ec14090b8eb04b64d65cc0a
[16:11:13 INFO]: Si quieres eliminar este volcado más adelante, usa la siguiente tecla de eliminación: fd4a2d40-effc-45b1-a2bb-07d0a1226119

**Comment by AstralisVox** [comment]
@mdcfe I have just done some testing regarding this and it appears that you need the permission `essentials.commandcooldowns.bypass` for it to work. Adding `.back` or `.*` to the end of the permission does not work and the cooldown remains. After checking with the Luckperms verbose recorder as well, It is only checking for the `essentials.commandcooldowns.bypass` permission.

**Comment by mdcfe** [comment]
@ImHumbug You're using the `command-cooldowns:` section of the config, so as OmegaWeaponDev noted, you just need to grant the `essentials.commandcooldowns.bypass` permission.

(There is a separate config option called `teleport-cooldown`, which sets a cooldown for every type of teleport, and has multiple subpermissions for different types of teleports (eg `essentials.teleport.cooldown.bypass.back`), but those permissions only work if you use that separate config option. For your use case, you're better off using the regular command cooldowns config and permission.)
