### ISSUE TITLE
GeyserMC: bedrock players cannot purchase from essentials signs

### ISSUE THREAD

**Issue by GreatThane** [EssentialsX/Essentials#4698]
### Type of bug

Compatibility issue

### `/ess dump all` output

https://essentialsx.net/dump.html?id=dda79998466c4c959f877796c76bb978

### Bug description

Users connected via GeyserMC are able to create (and by extension sell) using trade signs. However, they cannot purchase from trade signs made by other users. Instead, they are given the message
"Error: This sign is full!"

### Steps to reproduce

Create a server and install essentials, geyser, and floodgate (geyser addon)
enable trade signs in essentials and give players necessary permissions (create, break, use)
Log in with a java account or other bedrock account and create a trade sign
With a bedrock account, attempt to interact with the sign

### Expected behaviour

Standard trade sign interaction, with money taken and items received.

### Actual behaviour

Chat message of "Error: This sign is full!" and no transaction is made.

**Comment by Camotoy** [comment]
Unless this does not happen without Floodgate installed (implying an incompatibility in Floodgate's prefix) this likely isn't an Essentials issue.
