### ISSUE TITLE
nicknames cleared on login

### ISSUE THREAD

**Issue by minimuscle** [EssentialsX/Essentials#4699]
### Type of bug

Data loss

### `/ess dump all` output

https://essentialsx.net/dump.htmld=91842758c8ec4f08843cf45876f51eee

### Bug description

nicknames set with /nick are being set fine, but logging back in resets them for some reason.

### Steps to reproduce

/nick <nickname>
Logout
Login

### Expected behaviour

Nicknames should persist

### Actual behaviour

nicknames are wiped on login

**Comment by JRoy** [comment]
Few things;
* You're using an outdated version (1.18 not 1.18.1), you should also use [Paper](https://papermc.io)
* Another plugin is likely setting display names, probably ChatControlRed, TAB, or Rankup.
* You're using an unsupported permission plugin, GroupManager. Please use [LuckPerms](https://luckperms.net)
