### ISSUE TITLE
[12:10:43] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to EssentialsChat v2.19.2

### ISSUE THREAD

**Issue by Ganome** [EssentialsX/Essentials#4700]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=ae5c4ff20a5f44fcabfd00673d937a48

### Bug description

Whenver a play says anything in chat.  I get this Async chat error.  I think this is causing lag overtime.

### Steps to reproduce

1. Start the server
2. Type in chat

### Expected behaviour

No error log in chat whenever a user types

### Actual behaviour

Filling logs with errors and io think long term lag

**Comment by Octol1ttle** [comment]
You (accidentally) used the `%` (percent) symbol in group formats and EssXChat did not like this. I highlighted them for you so you can fix them (it seems like you wanted to use `&`)
![image](https://user-images.githubusercontent.com/61277953/146821639-2ad25d41-438f-43e7-ab42-f436b9c48a40.png)

**Comment by Ganome** [comment]
thank you!!
