### ISSUE TITLE
EssentialsDiscord PlayerAdvancementDoneEvent error

### ISSUE THREAD

**Issue by PetyXbron** [EssentialsX/Essentials#4705]
### Type of bug

Error in console

### `/ess dump all` output

Version `2.19.3-dev+1-05ce11f`
UPDATE BRANCH `2.x`
BUKKIT VERSION `1.18.1-R0.1-SNAPSHOT`
SERVER VERSION `git-Paper-99 (MC: 1.18.1)`
JAVA VERSION `17.0.1`

### Error log (if applicable)

https://paste.gg/p/anonymous/c29c6446e28e438d9f61da28e35124ee

### Bug description

Got this error when a player got a  Minecraft `[Hot Tourist Destinations]` advancement.
Message (announcement) isn't sent to primary (or staff) channel when set.

### Steps to reproduce

1. Use EssentialsDiscord when server running and set in config.yml `advancement: primary`
```
# Achievement/advancement messages sent when a player is awarded an achievement/advancement.
  advancement: primary
```
2. Get [Hot Tourist Destinations] advancement (Nether)
3. View the console

### Expected behaviour

Get a new message in Discord channel (primary or staff one) without any errors in console

### Actual behaviour

Error received to console when player received achievement.
![image](https://user-images.githubusercontent.com/35902119/147143092-f3da12e3-e206-4eae-9d7c-239c3e805cff.png)
`[20:00:10 INFO]: vojtas456 has completed the challenge [Hot Tourist Destinations]`

**Comment by mdcfe** [comment]
This is caused by a [recent Paper change](https://github.com/PaperMC/Paper/commit/26fbb02aaee9a00f3fa45edab66e4104f8de13da) which breaks the method we use to get plain text versions of the advancement messages.

**Comment by PetyXbron** [comment]
Same thing happened. Player received achievement and I got an error to console.
`[20:16:10 INFO]: xilyx11 has made the advancement [Caves & Cliffs]`
Error: https://paste.gg/p/anonymous/3e1fb141a7964830b3a4d8aa7ae47793
**So this doesn't happens only with [Hot Tourist Destinations] advancement**

**Comment by PetyXbron** [comment]
> This is caused by a [recent Paper change](https://github.com/PaperMC/Paper/commit/26fbb02aaee9a00f3fa45edab66e4104f8de13da) which breaks the method we use to get plain text versions of the advancement messages.

So it will be fixed when Paper releases Stable 1.18.1 update?

**Comment by mdcfe** [comment]
> > This is caused by a [recent Paper change](https://github.com/PaperMC/Paper/commit/26fbb02aaee9a00f3fa45edab66e4104f8de13da) which breaks the method we use to get plain text versions of the advancement messages.
> 
> So it will be fixed when Paper releases Stable 1.18.1 update?

I doubt that. We will likely need to add a second Paper advancement provider for 1.18.1+, unless Paper decides to revert and preserve the legacy serializer method.

**Comment by PetyXbron** [comment]
Okay. This seems to be a problem for a long time. Thank you for your quick response, and I hope it will be fixed soon.

**Comment by JRoy** [comment]
Reopening so we can track this

**Comment by JRoy** [comment]
I have fixed this in Paper, https://github.com/PaperMC/Paper/commit/1ce4281666bfb2419ed5ce29e4f25392244863b6 (build 100). 

Since the method we use is deprecated, I will also add a mitigation in Essentials to assure this doesn't become an issue when Paper removes it.

**Comment by Yukigamine** [comment]
I appreciate the hard work. I just came poking around GitHub after seeing the same issue on build 99 and I see you got a fix out just over an hour ago. Thanks!

**Comment by PetyXbron** [comment]
Using **Essentials** `2.19.3-dev+2-c4e62ae` and **Paper**`git-Paper-100` it works:

![image](https://user-images.githubusercontent.com/35902119/147226590-adf962fc-9918-42e2-a15e-1df7238459f9.png)
without errors. Thanks!
