### ISSUE TITLE
Cannot use nicknames without changing displayname

### ISSUE THREAD

**Issue by sudothefox** [EssentialsX/Essentials#4709]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=8460d2ce23044b5f8642c2d21aed7c25

### Bug description

We'd like to use nicknames and limit them to modify chat messages - everything else, including command output, still uses the user's username. I suggest EssentialsXChat support a variable for playernickanem and `change-displayname` is not required to be true to use nicknames.

### Steps to reproduce

Set `change-displayname` to false.
Try to use `/nick`

### Expected behaviour

Can still set nickname. Nickname is only used if chat plugin (EssentialsXChat) uses variable named "{NICKNAME}" in the chat format config.

### Actual behaviour

Cannot set nickname without changing displayname which affects multiple parts of the server.

**Comment by AstralisVox** [comment]
Hi @bdagenais2 

There is already the option to have `{NICKNAME}` in the chat formats.

**Comment by triagonal** [comment]
> There is already the option to have `{NICKNAME}` in the chat formats.

While `{NICKNAME}` is an existing chat format keyword, the `/nick` command prevents users from setting nicknames entirely if the `change-displayname` option is set to `false` in the config. Marking as feature request.

**Comment by sudothefox** [comment]
This would fix formatting in messages, like SocialSpy for example:

![image](https://user-images.githubusercontent.com/77643321/149648650-f60d8850-de82-4180-b7a1-77d824150c00.png)

![image](https://user-images.githubusercontent.com/77643321/149648653-6753b2f0-db73-4354-8351-fc944eb85253.png)
