### ISSUE TITLE
/create kit Armor & Shield

### ISSUE THREAD

**Issue by HunterJacobs** [EssentialsX/Essentials#471]
Something I have always wanted in essentials is to have the ability to allow the armor to spawn on the player when the /kit command is executed. Also, there is no way to keep shield textures in kits. Shields would also be nice to have spawn in the secondary spot.

**Comment by NoobPlayer03** [comment]
This would be amazing!

**Comment by HunterJacobs** [comment]
It would be very nice!

**Comment by mdcfe** [comment]
Closing, as this is a duplicate of #347.
