### ISSUE TITLE
[Free] sign item name dose not match because line is cut

### ISSUE THREAD

**Issue by AbsDataStruct** [EssentialsX/Essentials#4716]
### Type of bug

Data loss

### `/ess dump all` output

https://essentialsx.net/dump.html?id=5c1245eea4354bd8b8755022f023ca2f

### Bug description

When making a sign of type [free]
the line is too short to enter the minecraft item's name so it does not match the item.
Should be able to find the item eventhough the name is cut by searching the existing item matching the beginning of what is entered on the sign

### Steps to reproduce

put a sign
1 [free]
2 eggwither_skeleto | n
the sign shows error !

### Expected behaviour

eventhough the name of the item could not be entered fully,
it should be able to find out which item it is ...

### Actual behaviour

Sign shows red error

**Comment by AstralisVox** [comment]
Hi @AbsDataStruct 

You can get around this by adding the item to the custom_items.yml file and setting a custom name for the item that is smaller and will fit on the sign.

**Comment by triagonal** [comment]
You can also use the `/itemdb` command while holding the item to find shortnames you can use on signs, or use the `custom_items.yml` method like @OmegaWeaponDev suggested.

**Comment by AbsDataStruct** [comment]
Thank you very much, sorry I didn't know.  ^_^
