### ISSUE TITLE
[NOT A BUG] "Do not use Mohist" Page out of date

### ISSUE THREAD

**Issue by Chris6ix** [EssentialsX/Essentials#4718]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

/

### Error log (if applicable)

/

### Bug description

Hey, I read the ["Do not use Mohist" Page](https://essentialsx.net/do-not-use-mohist.html) of you guys and checked it out a bit further and found that some parts of it are out of date / not correct.
I also found this [document](https://github.com/Shawiizz/MohistEssentialsX/blob/main/README.md) from Mohist explaining / updating some problems and other "miscommunications".
The things that I found are not up-to-date / not correct:
-"Injecting block/item types added by Forge into the Bukkit Material enum twice" has apparently been fixed in Mohist 1.16.5
-The message of their "plugin checker" was misunderstood, as the Mohist team is not native English.
This message did not mean that the plugin is at fault (like you guys understood it) but simply that Mohist had some incompatibilities with EssentialsX that were on Mohists side.
-That their version of EssX that it wanted you to download was "arbitrary code from an unknown source" while their modified version of EssX was [Open source on Github](https://github.com/KR33PY/Essentials)...
Plus, this modified version isn't even needed anymore, as they seem to have fixed these incompatibilities with the regular EssX.
-That there is no SpongeForge version for newer versions than 1.12.2, but they have builds for 1.16.5

### Steps to reproduce

/

### Expected behaviour

/

### Actual behaviour

/

**Comment by JRoy** [comment]
Thanks for your interest
