### ISSUE TITLE
%essentials_home_<number>% cannot do more then 9

### ISSUE THREAD

**Issue by Kosett15** [EssentialsX/Essentials#4720]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=c18ff33a8cbe4acbab2ac099b655ab1c

### Bug description

Hello,

Whenever using place holder %essentials_home_<number>% any number above 9 does not show the home name at all and shows %essentials_home_10% for example.

### Steps to reproduce

Example:
1. Download PAPI Ecloud essentials stuff
2. Use in for example Command Panels
3. use any number for the placeholder above 9
4. observe doesnt show anything further

### Expected behaviour

Would expect it to find the 10 home

### Actual behaviour

Just shows the %essentials_home_10% and not the actual home name
![2021-12-29_14 28 31](https://user-images.githubusercontent.com/96830996/147672431-4cb2340d-168e-4c59-bf22-aefabcb6a533.png)

**Comment by mdcfe** [comment]
The EssentialsX team does not maintain the PlaceholderAPI Essentials expansion. Please use the [PlaceholderAPI/Essentials-Expansion](https://github.com/PlaceholderAPI/Essentials-Expansion) repository for any PAPI expansion issues or feature requests.
