### ISSUE TITLE
Failed to get data for custom chart with id permsPlugin

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#4726]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=ac867d369ae74c8fbd2e8a4b69e14d7b

### Error log (if applicable)

https://paste.gg/p/anonymous/8497da8c184a412ba0f924a83f939065

### Bug description

Im using the latest paper 1.17.1, latest essentialsx version and latest luckperms version.

### Steps to reproduce

Just start the Server with the latest versions

### Expected behaviour

No console error

### Actual behaviour

theres console errors

**Comment by mdcfe** [comment]
Closing as original author is gone and there is only [one other report of this ever occurring](https://discord.com/channels/390942438061113344/426460575971672064/915438531755786311), despite the thousands of servers running both EssentialsX and LuckPerms.
