### ISSUE TITLE
Deprecated event listener warning, "Server performance will be affected"

### ISSUE THREAD

**Issue by femboyfin** [EssentialsX/Essentials#4730]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=3f10b234afd949eb870c45fbf64e4cce

### Error log (if applicable)

https://paste.gg/p/anonymous/6478cb83a83f47b89f0822cd3b76b6c2

### Bug description

Warning in console about registereing a deprecated event listener, "Server performance will be affected".

### Steps to reproduce

0. Dowload the [latest build of Paper](https://papermc.io/downloads) (currently [1.18.1-121](https://papermc.io/api/v2/projects/paper/versions/1.18.1/builds/121/downloads/paper-1.18.1-121.jar)) and the [latest version of EssentialsX](https://essentialsx.net/downloads.html) (currently [2.19.2](https://github.com/EssentialsX/Essentials/releases/download/2.19.2/EssentialsX-2.19.2.jar))
1. `java -jar paper-1.18.1-121.jar` (change jar name if necessary)
2. Set `eula=true` in eula.txt
3. `java -jar paper-1.18.1-121.jar` again
4. Run `stop` in the server console to stop the server gracefully
5. Change settings.deprecated-verbose in bukkit.yml from `default` to `true`
6. Place the core EssentialsX-2.19.2.jar file in ./plugins/
7. `java -jar paper-1.18.1-121.jar` again
8. Observe the second listener warning (about org.bukkit.event.player.PlayerPickupItemEvent)

### Expected behaviour

No deprecated event warnings saying "Server performance will be affected".

### Actual behaviour

There is a warning in console about a deprecated event listener saying "Server performance will be affected".

**Comment by JRoy** [comment]
These can be ignored
