### ISSUE TITLE
Custom Banners in kits not returning patterns

### ISSUE THREAD

**Issue by RoachBoi** [EssentialsX/Essentials#4737]
### Type of bug

Compatibility issue, Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=6287b62a1e534b29b249e067f785f764

### Bug description

The /kit command doesnt return the exact banner and patterns that was used when creating the kit.  The kit config file does have the banner with some of the information:
- green_banner 4 name:Farmers_Banner basecolor:6192150 cs,16383998 flo,16701501
but for some reason this string of information only gives the player a banner with the base color and name.

### Steps to reproduce

Make a banner with some patterns, the use /kitcreate name 604800 to create the kit. Then use /kit name to return the kit and the banner item does not return the same.

### Expected behaviour

I would expect that when you do /kitcreate with the custom banners in hand that the kit is created with the patterns of the banner saved.  It does seem to save some information on the customized banner pattern. So that when you do /kit that player would receive the exact banner with the same patterns. 

### Actual behaviour

When the player uses the /kit with the custom banners it only returns a blank banner with only the base color in the banner that was used to create the kit.

**Comment by pop4959** [comment]
Confirmed on 2.20.0-dev+5-d891268
