### ISSUE TITLE
Can't override /back cooldown using permissions.

### ISSUE THREAD

**Issue by matipoirierg** [EssentialsX/Essentials#4747]
### Type of bug

Other unexpected behaviour.

### `/ess dump all` output

https://essentialsx.net/dump.html?id=54329dd3a0df473b8d71de8223643f4f

### Bug description

I have set a cooldown for the back command on the essentials config, but giving cooldown override permissions to a group isn't working. (Tried with: essentials.teleport.cooldown.bypass.*, essentials.teleport.cooldown.bypass.back and essentials.teleport.timer.bypass)

### Steps to reproduce

1.-Set a cooldown for /back on the config.
2.-Give cooldown override permissions to a group.
3.-Try to use /back twice.

### Expected behaviour

/back cooldown should be overridden on groups with cooldown override permissions.

### Actual behaviour

/back have cooldown even with the override cooldown permissions.

**Comment by LilianLem** [comment]
Can confirm that, I've exactly the same issue. I'm using LuckPerms to manage permissions.

**Comment by matipoirierg** [comment]
Hi been testing this branch for months, working without any issues, could you merge to latest dev builds pls?
