### ISSUE TITLE
Invsee Does not work

### ISSUE THREAD

**Issue by PeterEstephan** [EssentialsX/Essentials#475]
With Invsee command it shows me the player's user bar and what they have in it (I actually don't think that what they have in their bar from what I see actually is it but that is the only thing I see.) I cannot see the inventory nor the items they have in their nor be able to take and put items in their while being OP.

**Comment by drtshock** [comment]
Which build are you on and can you show me the server log with debug on when you run that command?

**Comment by PeterEstephan** [comment]
I am currently running 2.0.1-b309. I will attach a image of the console when i run the command and show you a video of what I am doing in-game so you can see what it looks like. 

Picture: http://imgur.com/fv8UAsZ
Video: https://vid.me/aA7g

Thanks.

**Comment by drtshock** [comment]
Can you tell me if it works as expected on build 308?

**Comment by Platinteufel** [comment]
Same here, needed to downgrade to 308.

**Comment by PeterEstephan** [comment]
However, if I downgrade wont the sign shop not work anymore? Because of the error of 36 slots now being 37?

**Comment by drtshock** [comment]
It's just build 309, 308 works fine.

**Comment by PeterEstephan** [comment]
Alright so when I tried build 309 the /invsee gave me the same kind of weird inventory that I showed in the video. And when I ran build 308 /invsee worked along with the sign shops.

Thanks. - I will keep checking the site for the latest working builds.

**Comment by drtshock** [comment]
I have a fix for invsee that I will push soonish.

**Comment by PeterEstephan** [comment]
Alright Thank You !
