### ISSUE TITLE
Powertool spam

### ISSUE THREAD

**Issue by JHarris12345** [EssentialsX/Essentials#4750]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=9f5c60cdbf514159ac870c8c5f1f66d8

### Bug description

When using a powertool, it outputs to console:

[Essentials] [PT] Bigdmg issued server command: /sell all

I was wondering if this message could not send if the event was cancelled. I have a powertool cooldown and so it spams a lot.

### Steps to reproduce

1. Powertool on cancelled event

### Expected behaviour

Not output for cancelled events

### Actual behaviour

outputs for cancelled events

**Comment by pop4959** [comment]
This cannot be fixed due to how powertool works. Essentials does not know if the command will be successful or not when it is sent. Keep in mind that you can still temporarily disable powertools with `/powertooltoggle`.
