### ISSUE TITLE
A small mistake in Translation（messages_zh.properties）

### ISSUE THREAD

**Issue by Linkerrain** [EssentialsX/Essentials#4751]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

/tptoggle

### Bug description

When I use " /tptoggle", the system will tell me that "传送已禁用" whether it is turned on or off.

![20220114110119](https://user-images.githubusercontent.com/30286249/149444404-beab7fbc-3abc-403c-b201-d563f38ba08f.png)

version:EssentialsX-2.19.3-dev+8-a9585bb

### Steps to reproduce

 /tptoggle
 /tptoggle

### Expected behaviour

messages_zh.properties：

teleportationDisabled=§6传送§c已禁用§6。
teleportationDisabledFor=§6已为§c{0}禁用§6了传送。
teleportationDisabledWarning=§6你必须启用传送功能才能让其他玩家传送到你这里。
teleportationEnabled=§6传送§c已启用§6。

### Actual behaviour

messages_zh.properties：

teleportationDisabled=§6传送§c已禁用§6。
teleportationDisabledFor=§6已为§c{0}禁用§6了传送。
teleportationDisabledWarning=§6你必须启用传送功能才能让其他玩家传送到你这里。
teleportationEnabled=§6传送§c已禁用§6。

![20220114110352](https://user-images.githubusercontent.com/30286249/149444522-99dcde56-68a2-4078-a5bd-e11a543f0242.png)

**Comment by triagonal** [comment]
Thanks for the heads up! We currently only accept translation updates through our [Crowdin](https://crowdin.com/project/essentialsx-official) page. If you believe there's a mistranslation, please submit a correction on there.
