### ISSUE TITLE
 [Suggestion]  eco trade direcly, not by withdrawal

### ISSUE THREAD

**Issue by saturnux** [EssentialsX/Essentials#476]
At this time, for trade sign, you can withdrawal for give your money account.
can you do that "sign trade" directly do the transaction?

**Comment by mdcfe** [comment]
I don't understand this request - any chance you could explain it further?

**Comment by saturnux** [comment]
Can you make trade is direct. by linking by vault or other...

some player use trade sign for stock money, or stuff.

**Comment by mdcfe** [comment]
Oh, my apologies - I didn't understand the first time round.

I'm not sure if there is a reason that Essentials always stored balances in the trade sign, rather than directly depositing it in the user's balance; I'm guessing that it was probably to do with the fact that earlier economy systems didn't support offline players or something similar.

**Comment by saturnux** [comment]
when a player is not on line, you can give  or take money on use "/eco give (or take)"

**Comment by mdcfe** [comment]
If a player isn't online, we can't always do permission checks to ensure that they're still allowed to receive funds from a sign. If an admin revoked the player's perms to use the sign but they had already created one, they wouldn't be able to withdraw funds from it, but if we modify their balance while they're offline, those permission checks won't be guaranteed to work properly.

**Comment by pop4959** [comment]
Yeah I don't think this is possible due to how permission systems still handle offline players, which is a bit flaky. It's probably best to leave this as is. Transferring funds directly would be a welcome convenience, but I think we'd want to see a PR first the proves this can actually be done.
