### ISSUE TITLE
NNBSP narrow no-break space issue

### ISSUE THREAD

**Issue by LuluxClient** [EssentialsX/Essentials#4764]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=eeafd3e8e87642589a5324c2abc13833

### Error log (if applicable)

none

### Bug description

Hello I've been getting issues with essentials giving me this when I do /bal: 
![image](https://user-images.githubusercontent.com/62576432/149937681-073ffebf-56aa-4d6e-8e6c-fd46d26610f5.png)

After some research it is not coming from me and I'm using utf-8 everywhere, I even have a startup flag for it and I tried removing it adding it everything, after that I contacted a dev and this is what he told me + he fixed the issue on one of my plugins : 
![image](https://user-images.githubusercontent.com/62576432/149937856-d09322b1-0d28-4fd1-aedd-a3657aa10d7a.png)

### Steps to reproduce

1. Be french
2. Put your dedi on the french language
3. Put your lang on french
4. do /bal 

### Expected behaviour

It souldn't have this NNBSP error symbol

### Actual behaviour

I have the NNBSP symbol  :(

**Comment by LuluxClient** [comment]
I would like to add that in console this is the output: 
![image](https://user-images.githubusercontent.com/62576432/150449546-9fc3c140-9593-4126-a85e-d8cdd859931d.png)

**Comment by mdcfe** [comment]
This is a known issue when combining Java's currency locales with Minecraft's font rendering, and this isn't something EssentialsX can fix easily. In fact, the `config,yml` even goes as far as to state:

```yaml
# Some formats do not display properly in-game due to faulty Minecraft font rendering.
```

It is unlikely we will add a workaround at this time, unless a sensible one is proposed that renders correctly in Minecraft.
