### ISSUE TITLE
Worth command not working with these 2 blocks

### ISSUE THREAD

**Issue by Thefluffypvper1** [EssentialsX/Essentials#4769]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=1c07723944db4c2cbda2aaa3ada7c7b3

### Error log (if applicable)

https://gyazo.com/dd95c3e903113ad592b40306234c1e38

### Bug description

When you hold birch and jungle leaves in your hand to get the value for them it returns a ingame error message saying its not possible. 

### Steps to reproduce

https://gyazo.com/66b6a932957ea3f718e777765c3e60d6

### Expected behaviour

It should set the worth of the item like other items

### Actual behaviour

It returns a ingame error message

**Comment by JRoy** [comment]
I cannot reproduce this, can you send your `worth.yml` in the Essentials plugins folder?

**Comment by JRoy** [comment]
Closing due to lack of response
