### ISSUE TITLE
Incorrect spawn eggs

### ISSUE THREAD

**Issue by jd1378** [EssentialsX/Essentials#477]
please fix spawn egg ids and data. 
for all of mob eggs , spawn egg is given instead.

**Comment by SupaHam** [comment]
In 1.9, Minecraft no longer supports the item data value as a unique type of monster egg, instead they use NBT tags. To spawn an egg with EssentialsX use: `/i 383 1 {EntityTag:{id:"Creeper"}}`, where `Creeper` is the Minecraft entity id. For a list of all minecraft entities and their ids click [here](http://minecraft.gamepedia.com/Data_values/Entity_IDs).
