### ISSUE TITLE
Command coloring doesn't work with essx disabling commands

### ISSUE THREAD

**Issue by JasonHorkles** [EssentialsX/Essentials#4774]
### Type of bug

Compatibility issue, Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=499a3a0b4f2a44fb9776c469609e5f1b

### Bug description

Disabling commands in the essx config cause other commands' colors to just be white

This bug has been here for almost as long as I can remember, however I just couldn't be bothered to figure out what was causing it until now lol

### Steps to reproduce

1. Install LuckPerms, Vault, and EssentialsX
2. Type a LuckPerms command, see that it has colors in it (before you press enter)
3. Add a disabled command to EssX
4. Reload EssX (or restart the server)
4. Repeat step 2, but see that it is all white

### Expected behaviour

![image](https://user-images.githubusercontent.com/51760372/150656906-cbe47c55-7f39-4b0a-9d14-09d9eddc50fb.png)

### Actual behaviour

![image](https://user-images.githubusercontent.com/51760372/150656893-bad8c5e8-5176-4e3e-9820-53772640a3f4.png)

**Comment by pop4959** [comment]
Unable to produce on my end, looks fine

![image](https://user-images.githubusercontent.com/17698576/150657216-24e38942-dbf0-4b24-9571-d0a4b5d8f43e.png)

**Comment by JasonHorkles** [comment]
What in tarnation, alright to more testing I go

**Comment by JasonHorkles** [comment]
Looks like it must be something in the essx config, as default config doesn't have the problem but mine does

**Comment by JasonHorkles** [comment]
I've updated the issue accordingly

and i now blame josh

**Comment by JRoy** [comment]
Likely an issue with brig mappings not forwarding if you intercept commands via the Bukkit API, will have to take a look

**Comment by pop4959** [comment]
Yep that looks to be the case. Confirmed on 2.20.0-dev+5-d891268.

**Comment by JRoy** [comment]
This is an issue with commodore, LuckPerm's command library. It doesn't use Paper's `CommandRegisteredEvent` and thus fails to register its brig commands when `CraftServer#syncCommands` is called. I've pinged luck and let him know, hopefully he'll have it fixed soon.
