### ISSUE TITLE
/back doesnt work on server running paper 1.18.1

### ISSUE THREAD

**Issue by darkwolfie37** [EssentialsX/Essentials#4779]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=10260a56e11546c2b352108f43e78b9b

### Bug description

When any player runs the /back command, they get a error message saying that there is no valid location. As a OP, this error doesn't happen

### Steps to reproduce

1. At least a non opped player with the permission node essentials.back
2. Use version 1.18.1 Paper
3. then have the non opped user get teleported to a warp or player and try to /back after being tp'ed

### Expected behaviour

Should go back to the last location.

### Actual behaviour

![img](https://user-images.githubusercontent.com/79094301/150910479-f813edc1-3cfa-4021-8dad-a786178863c3.png)

Tried doing the command "/back [username]" and it threw that error.

**Comment by JRoy** [comment]
Going to need a log of you doing what you did but do `/ess debug` first before anything.

**Comment by darkwolfie37** [comment]
> Going to need a log of you doing what you did but do `/ess debug` first before anything.

Sorry Thought it was clear to include a `/ess debug all` on the report. Please look at that dump for a server log. idiot

**Comment by Chew** [comment]
I think you're confusing `/ess dump` and `/ess debug`... you provided an `/ess DUMP` WITHOUT `/ess debug`. You were asked to run `/ess debug`, THEN do your `/back`, or whatever broke, THEN `/ess dump all` again. We did not ask for attitude.

**Comment by darkwolfie37** [comment]
Then I am closing. If you all are going to confuse a 15 yr old and will be reported for harassment

**Comment by Turbotailz** [comment]
Ok Karen

**Comment by mbax** [comment]
@darkwolfie37 [wrote](https://github.com/EssentialsX/Essentials/issues/4779#issuecomment-1028315432)

> Then I am closing. If you all are going to confuse a 15 yr old and will be reported for harassment

@darkwolfie37 [previously wrote](https://github.com/EssentialsX/Essentials/issues/4779#issuecomment-1027605633)
> > Going to need a log of you doing what you did but do `/ess debug` first before anything.
> 
> Sorry Thought it was clear to include a `/ess debug all` on the report. Please look at that dump for a server log. idiot

Please do not attack and then threaten members of this great project. Fifteen is plenty old to know this behavior is unacceptable.

**Comment by darkwolfie37** [comment]
cant even report things when that first dump has a server log... wonder what happened to common sense

**Comment by mbax** [comment]
@darkwolfie37 [wrote](https://github.com/EssentialsX/Essentials/issues/4779#issuecomment-1028426032)
> cant even report things when that first dump has a server log... wonder what happened to common sense


`DivizonYT issued server command: /ess dump all`


@darkwolfie37 [wrote](https://github.com/EssentialsX/Essentials/issues/4779#issuecomment-1027605633)
> > Going to need a log of you doing what you did but do `/ess debug` first before anything.
> 
> Sorry Thought it was clear to include a `/ess debug all` on the report. Please look at that dump for a server log. idiot

# 🤔

**Comment by emilyy-dev** [comment]
The only one causing harassment issues is you, calling people "idiot" and implying they don't have common sense, only because of a slight misunderstanding on your side, you were asked to run another command. No need to blow things out of proportion and using age as an excuse (???)

**Comment by mdcfe** [comment]
JRoy and Chew asked for additional info that was not included in your original report to help diagnose the problem you're having, and both provided steps on how to provide that info.

If you still want help with your original problem, you'll need to do the following steps:

1. Run `/ess debug` to **enable EssentialsX's debug mode**, which adds extra messages to your server log.
2. Get the user who is having problems to run `/back`. Debug mode will add some extra info to your log file about this.
3. Run `/ess dump all` to **upload a *new* dump file**, which will include the extra messages from your log file in addition to the normal ones in your original dump link.
4. Post the updated dump link in this issue.

Once you've done all these steps, we will be able to investigate the issue you're having.
