### ISSUE TITLE
[Suggestion] Additions to /seen

### ISSUE THREAD

**Issue by AntZaro** [EssentialsX/Essentials#478]
I know in the banned-players file, it shows the source and date in addition to the reason for a ban. I was wondering if it would be possible for /seen to return the ban reason, the date the ban happened, and the source. This would help us because it means we don't need to search the file to find out that information. Thanks for reading!

**Comment by saturnux** [comment]
if I'm not mistaken, the only thing missing is the date of the ban.
was the motif of the ban, but it is the date of last connection that is tracked

on my server, the moderator add manualy in motif how ban the player, on ban list (minecraft, bukkit, spigo) the source is "an operator"

**Comment by AntZaro** [comment]
Hmm I don't know. I just know that right now if someone is banned, it will just say "- Banned: [reason]" and I was wondering if they could add two more under that saying "- Source: [player]" and "- Date: [date banned]" since those two data points appear in the banned-players file.

**Comment by saturnux** [comment]
ok after re-verification, you have right.
c'est lors d'un changement de version que les fichier a mal été modifié.
les mentions de l'auteur du ban sont correcte, ainsi que les motifs.

:+1:

**Comment by JRoy** [comment]
@pop4959 this can be closed I'm pretty sure
