### ISSUE TITLE
/Sethome not working on Path block: Unsafe location

### ISSUE THREAD

**Issue by Waterman1001** [EssentialsX/Essentials#4787]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=51f0dca59e444b4f98e36822a704a075

### Error log (if applicable)

The teleport destination is unsafe and teleport-safety is disabled.

### Bug description

When running /sethome on a grass-path block, you get the message "The teleport destination is unsafe and teleport-safety is disabled."
This is probably due to the fact that such blocks are not full blocks but a little lower.

Obviously, these blocks should be considered safe, I think.

I do not want to disable this safety check because then you could set your home on lava for example and I don't want that to happen.

### Steps to reproduce

1. Stand on a Path block.
2. Run /sethome.
3. Home is not being set.

### Expected behaviour

I would expect the home to be set.

### Actual behaviour

It does not set the home :(

**Comment by pop4959** [comment]
Confirming on 2.20.0-dev+5-d891268. Occurs with farmland as well.

**Comment by resi23** [comment]
same with mud in 1.19
