### ISSUE TITLE
Does not accept HEX colors

### ISSUE THREAD

**Issue by Skjolberg** [EssentialsX/Essentials#4788]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

Nothing

### Bug description

I want to put messages with gradient colors but Essentials does not allow that in config.yml for example in the following section:

- announce-format:

It does not accept RGB colors or even classic colors (&a&b&c&c....) to make texts with gradient colors.

An example of what I mean is this:

https://i.gyazo.com/339b2f7759bdfe8c1edacd4db616989c.png

### Steps to reproduce

Nothing

### Expected behaviour

Nothing

### Actual behaviour

Nothing

**Comment by JRoy** [comment]
You need to fill out the issue template, cannot reproduce.
