### ISSUE TITLE
Jails bug message

### ISSUE THREAD

**Issue by DeriksonTM** [EssentialsX/Essentials#4793]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=d9676269023a40bdb152794451d4cccc

### Bug description

If I put a player in jail, he gets two identical notices.

### Steps to reproduce

I give myself a punishment /jail DeriksonTM jail 12h
At the same time, I do it through the console, and I have no op and other rights on the nickname, ie, I'm just a simple player.

### Expected behaviour

I want to receive only one notification, not two of the same.

### Actual behaviour

Instead of one notification, I get two.
![image](https://user-images.githubusercontent.com/92043849/152357527-63291bb7-2e93-4afd-a1e1-53faab232d13.png)
![image](https://user-images.githubusercontent.com/92043849/152357549-8ba90256-178f-48e9-91f4-c4eed9406f89.png)
![image](https://user-images.githubusercontent.com/92043849/152357559-4ebd3fc8-7882-49d3-9cd4-6d9bdfe26a54.png)

**Comment by pop4959** [comment]
Confirming on 2.20.0-dev+5-d891268.

![image](https://user-images.githubusercontent.com/17698576/169675250-52dfb98c-7ef8-4ef1-92b7-805e1cb43790.png)

`/jail Yar jail 1h`
These aren't the same messages as above, but still duplicated in the same fashion.

**Comment by JRoy** [comment]
Cannot reproduce, the message from pop is due to .notify permissions.
