### ISSUE TITLE
Error on spawnmob, home, back, warp

### ISSUE THREAD

**Issue by LudnicaKiller** [EssentialsX/Essentials#4795]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=fefb5ded087244dbae6dff0943b9a4d8

### Error log (if applicable)

https://pastebin.com/6vqt9ajv

### Bug description

This error comes to commands: spawnmob, home, back, warp....

### Steps to reproduce

Just run commands

### Expected behaviour

Needs to go back, home, to warp, to spawnmob but sometimes I can't

### Actual behaviour

Nothing happens, just error in logs

**Comment by pop4959** [comment]
This should already be fixed in the latest [development builds](https://essentialsx.net/downloads.html) of EssentialsX, so please download that and try again.

**Comment by LudnicaKiller** [comment]
@pop4959 nope, not fixed, already have latest version..

**Comment by JRoy** [comment]
> @pop4959 nope, not fixed, already have latest version..

You need to use the development builds

**Comment by LudnicaKiller** [comment]
Using [EssentialsX-2.19.3-dev+10-c6fe160.jar](https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/artifact/jars/EssentialsX-2.19.3-dev+10-c6fe160.jar), that's the latest dev build

**Comment by JRoy** [comment]
> Using [EssentialsX-2.19.3-dev+10-c6fe160.jar](https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/artifact/jars/EssentialsX-2.19.3-dev+10-c6fe160.jar), that's the latest dev build

It's impossible to get the error you reported on the latest dev build

**Comment by LudnicaKiller** [comment]
You want me to record executing the command?

**Comment by JRoy** [comment]
> You want me to record executing the command?

Do the following in order;
* Do `/ess debug`
* Do the command you are doing
* Do `/ess debug all`
* Share link

**Comment by LudnicaKiller** [comment]
https://essentialsx.net/dump.html?id=b68055846b8d41fbad77bc6a0dcf9850

**Comment by JRoy** [comment]
> [essentialsx.net/dump.html?id=b68055846b8d41fbad77bc6a0dcf9850](https://essentialsx.net/dump.html?id=b68055846b8d41fbad77bc6a0dcf9850)

I no longer see the error you reported, however I do see the plugin, `UltimatePlugin`, is overriding the `/enchant` command so this would have nothing to do with EssX

**Comment by mdcfe** [comment]
> [essentialsx.net/dump.html?id=b68055846b8d41fbad77bc6a0dcf9850](https://essentialsx.net/dump.html?id=b68055846b8d41fbad77bc6a0dcf9850)

You didn't run any of the commands that caused the error from the original bug report in this dump.

**Comment by LudnicaKiller** [comment]
There is no ess debug all command, that just stops debuging and no link is printing

**Comment by JRoy** [comment]
> There is no ess debug all command, that just stops debuging and no link is printing

I meant `/ess dump all`, my bad

**Comment by LudnicaKiller** [comment]
Yes, it's UltimatePlugin, my bad.. You can close it
