### ISSUE TITLE
/tpyes and /r bug after 5 seconds

### ISSUE THREAD

**Issue by Elric02** [EssentialsX/Essentials#4798]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=6304345df173445091ca759c8b68f82f

### Bug description

I've upgraded to 1.18 recently and I've got a strange bug : some commands stop working after a 5 seconds delay.
For example, writing a /msg to someone, then responding with /r will only work for 5 seconds before it "forgets" and tells me that I've got nobody to answer to.
The same bug happens with /tpa, I've only got a short timespan of 5 seconds even if it tells me that I've got 120 seconds to accept it or not.
I've also got some various issues, for example people aren't set to afk automatically anymore after 5 minutes, but I don't know if it's linked.

So far, I've tried using the dev builds, I've also tried resetting the config, but nothing worked.

### Steps to reproduce

1. Write a /msg to someone
2. Wait 5 seconds
3. Respond to the message (for example with /r)

### Expected behaviour

The /r will tell you you've got nobody to respond to. 
(also works if someone else /msg you and you try to /r)

### Actual behaviour

The /r should answer to this someone

**Comment by pop4959** [comment]
Unable to reproduce. If you are still having this issue, please make a new report and be sure to test it with only Essentials installed on the server.
