### ISSUE TITLE
Jail/Unjail bug

### ISSUE THREAD

**Issue by Shadownite64** [EssentialsX/Essentials#4802]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=ef4fe47b1d154f6aa56d096047cc9a71

### Bug description

When doing command /unjail it will not unjail the user and submits an error instead. 
Error: Cannot invoke "org.bukkit.Location.getWorld()" because "targetLoc" is null

### Steps to reproduce

1. Do command /jail <user> <jailname> <time>
2. Do command /unjail <user> <jailname>

### Expected behaviour

It should unjail the user and send them back to their previous location.

### Actual behaviour

It keeps them jailed and sends an error.

**Comment by 4b75726169736859** [comment]
hi @Shadownite64,
I have the same problem, did you find a solution?

**Comment by Shadownite64** [comment]
nope, tried looking all over online, didnt find results.

**Comment by pop4959** [comment]
Unable to reproduce this issue on the latest version of Essentials. If it is still occurring, please open a new issue and include the full error message (not just the line which says it is null).
