### ISSUE TITLE
Powertool can be triggered with Thorns

### ISSUE THREAD

**Issue by EpicnessTwo** [EssentialsX/Essentials#4806]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

Not applicable

### Bug description

When a player has a powertool in their hand and thorns on their armour, hitting said player will trigger the powertool

### Steps to reproduce

1. Apply a powertool to an item (/pt sudo {player} c:This is a test)
2. Equip some armour with thorns
3. Have another player hit you

### Expected behaviour

Nothing happens

### Actual behaviour

The attacking player will say "This is a test" in chat

**Comment by pop4959** [comment]
Unable to reproduce this on the latest version of Essentials. If you're still experiencing this, please make a new issue with ess dump and log as that may help.
