### ISSUE TITLE
/unlimited broken

### ISSUE THREAD

**Issue by SkylordBrebro** [EssentialsX/Essentials#4819]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=ea966c55856442989626f523b007fabb

### Bug description

After running the "/unlimited" command and placing something with more than 2 items it'll add more than one back to the stack. 

### Steps to reproduce

1. /Unlimited (block)
2. Place with more than 2 items in stack

### Expected behaviour

Add one item per one used

### Actual behaviour

Adds more than one item to the stack, hence overflowing into a new stack.

**Comment by pop4959** [comment]
Confirmed on 2.20.0-dev+5-d891268
