### ISSUE TITLE
Spawn Eggs question

### ISSUE THREAD

**Issue by Sikatsu** [EssentialsX/Essentials#482]
Hey,

I'm using CustomGUi for my shops to sell spawneggs for players. The command I used on 1.9 was:

`- '[ConsoleCommand] give %player% spawn_egg 1 {EntityTag:{id:"Pig"} }'`

But it seems not to be working anymore since the latest spawnegg changes, how can I sell my spawneggs now? lol :)

**Comment by SupaHam** [comment]
What is CustomGUI? How is it related to EssentialsX?

Edit: The placeholder for player name in kit commands is `{player}` not `%player`.

**Comment by vemacs** [comment]
Just use spawn_egg:90, it's exactly the same as in previous versions.

http://minecraft.gamepedia.com/Data_values/Entity_IDs
