### ISSUE TITLE
RGB color no work

### ISSUE THREAD

**Issue by srfabric** [EssentialsX/Essentials#4820]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=239010bdc2234825a7fe3e669c132bfe

### Bug description

![image](https://user-images.githubusercontent.com/95653654/156009003-7bdb3e59-b3e0-4535-8155-2f40d8c49395.png)

### Steps to reproduce

After update essentials

### Expected behaviour

incorrect view of messages

### Actual behaviour

incorrect view of messages

**Comment by Octol1ttle** [comment]
You must use `&#RRGGBB` instead of `#RRGGBB` (add `&` in front)
Please ask in [MOSS Discord server](https://discord.gg/casfFyh) first
