### ISSUE TITLE
Same Potion IDs in 1.9

### ISSUE THREAD

**Issue by switorik** [EssentialsX/Essentials#483]
In 1.8, potion and splash potions all had separate item IDs based on which kind they were. In 1.9, All potions were merged together, splash potions merged, and lingering potions merged. Meaning there are only 3 different item IDs for potions. (Potion: 373, Splash potion: 438, Lingering potion: 441). 

Essentials no longer recognizes the differences between potions on trade, buy, or sell signs. For example, a strength potion in 1.8 was called: potion:8233. In 1.9, it is called: potion. 

Potions are currently unsellable on trade, buy, and sell signs.

**Comment by mgl** [comment]
They are also impossible to give :/

**Comment by SupaHam** [comment]
1.9 fundamentally changed the way some items work by introducing NBT tags as opposed to limited item damage values, `/give SupaHam potion 1 {Potion:"swiftness"}` will give me one Tipped Arrow with a default swiftness effect, click [here](http://minecraft.gamepedia.com/Potion#Item_data) for a list of Potion types.

Alternatively and more complexly, you can use `CustomPotionEffects` to define custom effects: `/give SupaHam potion 1 { CustomPotionEffects: [ {Id: 25, Amplifier: 1, Duration: 200} ] }` will give me one Tipped Arrow with a levitation effect, amplifier 1, and a duration of 200 ticks (10 seconds).

For more information, see: http://minecraft.gamepedia.com/Arrow

As for signs, they use the item database, which does not support NBT yet, so you'll have to wait on an update.
