### ISSUE TITLE
[Paper 1.18.2] Creepers cause block damage.

### ISSUE THREAD

**Issue by Numpty-Clodpole** [EssentialsX/Essentials#4830]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=d2af9dc5ef864cf8b79322ef39b277ed

### Bug description

As of updating to Paper 1.18.2 and EssentialsX 2.19.3, creeper explosions now damage blocks. 

### Steps to reproduce

1. Be using Paper 1.18.2build 220 and EssentialsX 2.19.3.
2. Ensure `creeper-blockdamage:` is set to `true` within the `config.yml` file.
3. Have a creeper blow up, it will cause block damage.

### Expected behaviour

Well, I would expect there to be no broken blocks when the creeper explodes.

### Actual behaviour

Err... blocks are destroyed upon the creeper exploding.

**Comment by LaxWasHere** [comment]
That option is for the module `EssentialsX Protect` which you do not have installed.

**Comment by Numpty-Clodpole** [comment]
> That option is for the module `EssentialsX Protect` which you do not have installed.

Urgh. I swear I had grabbed that along with the other jarfiles. It appears you are correct:

![image](https://user-images.githubusercontent.com/19168008/157540217-db1f6585-b2a7-4d82-ae0d-62617147752f.png)

I'm glad it just me overlooking something, rather than an actual issue. Thank you, @LaxWasHere.
