### ISSUE TITLE
Essentials hangs on stop with Paper 1.18.2

### ISSUE THREAD

**Issue by Boastful1353** [EssentialsX/Essentials#4832]
### Type of bug

Compatibility issue, Error in console, Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=ffb900d9aeb643d7bc4b71962f9a65f9

### Bug description

/version output:
15:04:39
You are running the latest version
Previous version: git-Paper-221 (MC: 1.18.2)

Essentials X Build #1366 (Mar 5, 2022, 6:35:08 PM)

Error: 
Nag author: 'Zenexer' of 'Essentials' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.

### Steps to reproduce

i've installed Build #1366 (Mar 5, 2022, 6:35:08 PM)
with git-Paper-221 (MC: 1.18.2)

### Expected behaviour

server should shut down without issue.

### Actual behaviour

server starts fine

stopping the server hangs with the following messages

ERROR
15:08:24

Nag author: 'Zenexer' of 'Essentials' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.

INFO
15:08:24

Saving players
Saving worlds

server never stops unless i force kill it

**Comment by JRoy** [comment]
You need to share a full log before we can look into this

**Comment by Sussy42** [comment]
how do you fix this?

**Comment by mbax** [comment]
@Sussy42 [wrote](https://github.com/EssentialsX/Essentials/issues/4832#issuecomment-2028899003)
> how do you fix this?

Well, per JRoy's remark, a full log would be a great starting point to resolving this claimed issue.
