### ISSUE TITLE
Essentials Discord is detected by some virus scanners

### ISSUE THREAD

**Issue by BlockyTheDev** [EssentialsX/Essentials#4833]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=b8373ba3ea094081b123321e2f31c340

### Bug description

Some virus scanners detect EssentialsXDiscord-2.19.3.jar as virus.
Bitdefender: Java.Trojan.GenericGB.29336
==> net/essentialsx/dep/club/minnced/discord/webhook/receive/ReadonlyMessage

### Steps to reproduce

1. Download Essentials-Discord

### Expected behaviour

EssentialsX-Discord should not be detected.

### Actual behaviour

EssentialsX-Discord is detected by some virus scanners like "Bitdefender" or the one by Microsoft.

**Comment by BlockyTheDev** [comment]
I am not sure if the developers can do anything or can have a look into it, but so I can't update it on my server.

**Comment by BlockyTheDev** [comment]
I am already in contact with the laboratory of Microsoft and Bitdefender to remove this false positive.

**Comment by Chew** [comment]
Seems to be an issue with the dependency anyway. Ironically that doesn't show up on the virus checker, so not sure why it's acting extra special today.

**Comment by BlockyTheDev** [comment]
I got the answer auf both that it is added to the whitelist.
