### ISSUE TITLE
Signs lowercasing

### ISSUE THREAD

**Issue by FarisR99** [EssentialsX/Essentials#484]
I do not use EssentialsX other than on my LAN test server to test my plugins. I'm not sure if this has been fixed yet, but basically when I try creating a sign such as [Kit], it would lowercase it instantly to [kit], even if it is disabled in the config.

E.g. My KingKits plugin uses '[Kit]' to recognise it as a kit sign, so therefore 'kit' must be disabled in the Essentials config for this to work. I disabled this in my Ess. config, and then when I create a [Kit] sign it makes it [kit]. I disabled Essentials and it worked fine, [Kit] did not automatically lowercase.

**Comment by drtshock** [comment]
Can you paste your essentials config and startup log in pastebin please

**Comment by FarisR99** [comment]
Config: http://pastebin.com/FiemHEx9
Log: http://pastebin.com/x23rjBDF

Example of what happens: https://www.youtube.com/watch?v=vTC89WzKd_0

**Comment by SupaHam** [comment]
I'll fix it soon, but the culprit is [this](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/signs/SignBlockListener.java#L99]).

**Comment by SupaHam** [comment]
@drtshock @vemacs Thoughts on this issue? Currently, if a sign's first line contains the id of an essentials sign, such as [kit], [repair], etc. Regardless of its availability, the sign will always lowercase. What this does is that it creates the sign's first line in proper format (e.g. [repair] or [kit]) in case the sign is to be enabled at a later time in the configuration file. This was done as a precaution more than an immediate change.

However, this undercase transformation presents an issue with other plugins using the same sign id but with different letter casing. Regardless of the transformation I disagree that sign ids should be that similar anyways to remove any ambiguity or confusion caused for the user.

If a user accidently uses [kit] and they meant to use the other plugin, then they'll be left confused staring at five explicit characters.

**Comment by drtshock** [comment]
I agree that we shouldn't interfere with signs on text for disabled signs.

**Comment by SupaHam** [comment]
Okay, but that still won't fix the issue at hand. Currently typing [Kit] will automatically lowercase to [kit]. Which then interferes with, for example, the named plugin which explicitly checks for signs that start with `[Kit]` not `[kIt]` or `[KIT]`.

**Comment by FarisR99** [comment]
Any updates? I currently use EssentialsX on my test server which is used to test KingKits. I usually have to end up disabling EssentialsX via. PlugMan whenever I want to make a kit sign.

**Comment by OscarWoHA** [comment]
What about setting listener priority to a low level? Or run a check on lowest priority and one after on highest to see if there are any changes that aren't EssentialsX based?

**Comment by SupaHam** [comment]
Please continue this discussion in #699.
