### ISSUE TITLE
stack on head "/hat"

### ISSUE THREAD

**Issue by Focxer** [EssentialsX/Essentials#4841]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=280108c2388d453988871bfe31516b33

### Bug description

When use /hat with a stack, 2/64 items on head, players get disconnected and then crash on every login untill i kill them and drop the hats from head slot

### Steps to reproduce

1. grab 2 items of same
2. do /hat command
3. get 2 or more items of the same type on your head
4. eventually you'll disconnect and cant login again until you get your inv clearead
5. doesnt affect OP's

### Expected behaviour

Nothing or Just 1x item on head

### Actual behaviour

stackable hat item and server disconnect

**Comment by pop4959** [comment]
Unable to reproduce this on the latest version of Essentials. If you're still experiencing this issue please open a new issue and try with only Essentials installed, and provide the error and/or crash message as well.
