### ISSUE TITLE
Hex color codes included in max nick length regardless of setting

### ISSUE THREAD

**Issue by LcorpOfficial** [EssentialsX/Essentials#4842]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=80ea99408ee34d4c835b653a177f6258

### Bug description

Hex color codes are included in char length limit regardless of setting in config.yml

### Steps to reproduce

1. ignore-colors-in-max-nick-length: true
2. max-nick-length: 20
3. set nick to 20 char name with hex codes
4. get error: nick too long

### Expected behaviour

color codes should be omitted from nick, same as `&` codes

### Actual behaviour

hex codes are counted toward char limit on nick.

**Comment by pop4959** [comment]
I'm unable to reproduce this on the latest version of Essentials. It appears to be working as intended using both `&X` and `&#RRGGBB` color formats.

If you are still having this problem after updating, please open a new issue. Also test with only Essentials installed, to make sure that it isn't an issue with one of your 84 other plugins.
