### ISSUE TITLE
I cannot give damaged items anymore

### ISSUE THREAD

**Issue by DevCyntrix** [EssentialsX/Essentials#4852]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=b4e7297d950647ccb089f9809b8ba1ca

### Bug description

I try to give myself an item with a damage of 100 but I get an item without damage

### Steps to reproduce

/give <player> iron_sword 1 100

### Expected behaviour

I get an damaged item

### Actual behaviour

I get an item but without damage

**Comment by pop4959** [comment]
The command for giving a damaged item is `/item <item>:<damage> <amount>`.
