### ISSUE TITLE
TPAing to someone with tpauto on and command costs on charges twice

### ISSUE THREAD

**Issue by aindrigo** [EssentialsX/Essentials#4854]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=38de42e7e07b4460bc278e246f783588

### Bug description

If command costs are enabled for TPA and someone teleports to someone else who has tpauto on, then they are charged twice.
The only solution I can think of right now is just to half the command cost until the bug is fixed.

### Steps to reproduce

1. Set a command cost for TPA (in my case $10)
2. TPA to someone with tpauto on
3. You should get charged twice

### Expected behaviour

You should only get charged once.

### Actual behaviour

You get charged twice.

https://user-images.githubusercontent.com/94946723/158217160-e39e25ca-f0f3-4ea1-91f7-9b965f47e782.mp4

.

**Comment by mdcfe** [comment]
I've opened a PR to fix this at #4862. This fix will be available in normal dev builds soon.

**Comment by mdcfe** [comment]
This has now been fixed in the [latest dev builds](https://essentialsx.net/downloads.html). Thanks for your report!
