### ISSUE TITLE
1.9 potions, and potion arrows kit.

### ISSUE THREAD

**Issue by andris155** [EssentialsX/Essentials#486]
/createkit - not add new 1.9 potions, and potion arrows nbt tags in the config.yml.

**Comment by SupaHam** [comment]
Please http://pastebin.com your config.yml

**Comment by andris155** [comment]
EssentialX not support new potion nbts, and arrow potion nbts(?)

**Comment by SupaHam** [comment]
EssentialsX does support Potion NBT data via the `/give` command, but the /createkit command doesn't do that, at least not yet. So you'll have to insert the NBT yourself: 

1.9 fundamentally changed the way some items work by introducing NBT tags as opposed to limited item damage values, `/give SupaHam tipped_arrow 1 {Potion:"swiftness"}` will give me one Tipped Arrow with a default swiftness effect, click [here](http://minecraft.gamepedia.com/Potion#Item_data) for a list of Potion types.

Alternatively and more complexly, you can use `CustomPotionEffects` to define custom effects: `/give SupaHam tipped_arrow 1 { CustomPotionEffects: [ {Id: 25, Amplifier: 1, Duration: 200} ] }` will give me one Tipped Arrow with a levitation effect, amplifier 1, and a duration of 200 ticks (10 seconds).

For more information, see: http://minecraft.gamepedia.com/Arrow

**Comment by andris155** [comment]
How to use new potions, and potion arrows on [buy], [free], [sell], signs? and on kits?

**Comment by SupaHam** [comment]
You can't do it for signs at the moment. But for kits you can add a command See the [wiki](https://github.com/drtshock/Essentials/wiki#showkit) for more information.

**Comment by Sycholic** [comment]
could this be leading back to Vault by chance?  Im so not enjoying even looking at trying to get my fork of vault to handle it but Im hoping to. (but I do got the new mats already PR'd that up to Milkbowl)
