### ISSUE TITLE
Anvil/Loom/Recipe/Cartographytable/Smithingtable/Stonecutter Commands

### ISSUE THREAD

**Issue by Prelogiix** [EssentialsX/Essentials#4864]
### Type of bug

Compatibility issue, Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=aaae9f63657f42df93fa92dda1f91cfa

### Bug description

Commands above don't work in 1.18.2. No console error but output in chat is "The server platform you are currently running does not provide the capabilities for this feature."

### Steps to reproduce

1. /anvil

### Expected behaviour

Commands should open the specified command

### Actual behaviour

"The server platform you are currently running does not provide the capabilities for this feature."

**Comment by LaxWasHere** [comment]
Those commands only work for paper servers because only paper has an API for it.  Download it here https://papermc.io/
