### ISSUE TITLE
Spawnmob spawning the same type of skeletons and zombies.

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#487]
EssentialsX dev 320
Spigot 1.9 git-Spigot-2dc26f3-4a8818c

Spawning zombies with /spawnmob spawns the same zombies every time. Zombie villagers with gold boots. Same with skeletons - skeletons with gold boots. Shouldn't it be random based on vanilla mob spawns of each type?

**Comment by saturnux** [comment]
all zombie is a villager.
for boots, it's an essentials (original) feature.

**Comment by drtshock** [comment]
https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/SpawnMob.java#L224 is what it does
