### ISSUE TITLE
"essentials.nick.changecolors" not working

### ISSUE THREAD

**Issue by Gardiac** [EssentialsX/Essentials#488]
Group has got permission essentials.nick.changecolors and essentials.nick but it doesnt apply nickname...
Im using 1.7.10Spigot-1649

**Comment by Gardiac** [comment]
@SupaHam @drtshock Please fix it !

**Comment by drtshock** [comment]
please read wiki

**Comment by Gardiac** [comment]
DUDE I KNOW BUT STILL NOT WORKING , Lets say my name is Okay and I got permission essentials.
nick.changecolors & essentials.nick
I tried /nick &6Okay but still not working...
