### ISSUE TITLE
Error constructing new userfile

### ISSUE THREAD

**Issue by lilian-gnt** [EssentialsX/Essentials#4882]
### Type of bug

Data loss, Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=5bf525ee94f84d03b8566d8ab90a9609

### Error log (if applicable)

https://paste.gg/p/anonymous/c8616b61ab3a40b38b0968170707a5ff

### Bug description

In the /ess debug of Essentials it tries to create a user file which it can't find

### Steps to reproduce

I don't know

### Expected behaviour

Nothing

### Actual behaviour

Error in console

**Comment by pop4959** [comment]
A bit embarrassing, but it looks like your dump and paste have both expired, so we're not able to confirm whether this is an issue on our end. I'm going to close this issue but if you're still willing to re-send that information we can take another look at re-opening this.
