### ISSUE TITLE
UUID BALTOP ERROR

### ISSUE THREAD

**Issue by Didyouknow-331** [EssentialsX/Essentials#4887]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=30764fcda0f844e0826f1c2adc986951

### Error log (if applicable)

https://paste.gg/p/anonymous/3da9930c7fdf4fe8865458d00e2a7b74

### Bug description

When runnig /baltop return this error https://paste.gg/p/anonymous/3da9930c7fdf4fe8865458d00e2a7b74

### Steps to reproduce

.

### Expected behaviour

.

### Actual behaviour

.

**Comment by Chew** [comment]
#4342
