### ISSUE TITLE
1.18.2 not supported paper server

### ISSUE THREAD

**Issue by UsefullSpoon** [EssentialsX/Essentials#4889]
### Type of bug

Compatibility issue

### `/ess dump all` output

https://essentialsx.net/dump.html?id=b0d4f4a8a7154fbe9f912ad7bc0e8702

### Bug description

i can't give myself items from 1.18 such as the music disc "otherside" or amethyst

### Steps to reproduce

1. have latest essentials downloaded
2. try to do '/i music_disc_otherside 1' or '/i amethyst_block 1'
3. Returns as: Error: Unknown item name: %item%

### Expected behaviour

give me the item?

### Actual behaviour

error

**Comment by pop4959** [comment]
Both of these items appear to be working for me on the latest build of Essentials. You may need to manually delete your `items.json` file in the Essentials plugin folder. Usually this is updated automatically.
