### ISSUE TITLE
Memory leak in Spigot 1.9?

### ISSUE THREAD

**Issue by Platinteufel** [EssentialsX/Essentials#489]
![essentials1](https://cloud.githubusercontent.com/assets/13700636/13724871/58acaeb6-e893-11e5-8ca8-bb35d8bb6743.png)
![lag2](https://cloud.githubusercontent.com/assets/13700636/13724873/5a80da8c-e893-11e5-9b26-7673bd9b2d5b.png)

**Comment by SupaHam** [comment]
What's the leak exactly? 216 Users? If so, how many players often join the server in a timespan of maybe 30 minutes?

**Comment by Platinteufel** [comment]
That issue is quite old and seems to be resolved in 1.10. Thank you tho ;)
