### ISSUE TITLE
Unable to use @ for player and sub parameters

### ISSUE THREAD

**Issue by Josh65-2201** [EssentialsX/Essentials#4890]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=3273f9381a7f4ffea727b540475fe45f

### Bug description

I carnt use `@a, @e and @s` and ther substant parts like type or radius. I will just get player not found

### Steps to reproduce

Use `/tp @a 0 10 0`

### Expected behaviour

Tp everyone to 0 10 0

### Actual behaviour

Player not found is said

**Comment by 100petr** [comment]
https://github.com/EssentialsX/Essentials/issues/2102 install commandhook
