### ISSUE TITLE
Failed to get data for custom chart with id permsPlugin

### ISSUE THREAD

**Issue by ChrissW-R1** [EssentialsX/Essentials#4892]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=cb5054a935d44b95a1d47384037fd2b8

### Error log (if applicable)

https://pastebin.com/EG2REHSE

### Bug description

It look like there is an incompatible with LuckPerms and Vault. No function is affected, but on a server start an error is shown in the console.

So the chart about the permissions plugin couldn't be filled for bStats.

### Steps to reproduce

1. Install a Paper server (e.g. 1.18.2-283)
2. Add Plugin LuckPerms (e.g. 5.4.18)
3. Add Plugin Vault (e.g. 1.7.3)
4. Add Plugin Essentials (e.g. 2.19.4)

### Expected behaviour

The chart will be sent and no error is shown in the console.

### Actual behaviour

The console shows
`Failed to get data for custom chart with id permsPlugin`
separately for every Essentials module

**Comment by pop4959** [comment]
Is this easily reproducible on your server? There has only been one or two other reports of this ever occurring (re: #4726). These plugins should all be compatible.

**Comment by ChrissW-R1** [comment]
After some updates I can't reproduce this error anymore.
