### ISSUE TITLE
Ender Chests

### ISSUE THREAD

**Issue by BrandonT80** [EssentialsX/Essentials#4893]
### Type of bug

Data loss

### `/ess dump all` output

https://essentialsx.net/dump.html?id=d32336c5a6b84d35b70d77d389e2d791

### Bug description

Ender chests get deleted and someone elses ender chests get copied into them. This was randomly happening and now its constantly happening. 

### Steps to reproduce

No clue. Server restarts and many players ender chests are someone elses copied over

### Expected behaviour

Not have peoples ender chests wiped and copied over by someone elses.

### Actual behaviour

Have to constantly replace peoples ender chest content, even my own.

**Comment by mdcfe** [comment]
You didn't run `/ess dump all` as instructed.

EssentialsX doesn't modify players' ender chests on its own. If you were using EssentialsX's `/echest` command, Bukkit is responsible for opening other players' ender chests, but it appears you're using OpenInv, so there's nothing at all to suggest EssentialsX is the cause. Can you reproduce this with only EssentialsX, Vault and LuckPerms installed, then post the output of `/ess dump all` on that reproduction setup here?

**Comment by BrandonT80** [comment]
I did run the command, here is the dump again:
https://essentialsx.net/dump.html?id=335bb5270a76489fb40cc2f243f4af8d

We haven't been using openinv for ender chests, only /ec 

Just in case we updated to latest paper, got the latest dev build of essentialsx and added an inventorybackup to fix the swap issues.

**Comment by mdcfe** [comment]
> Can you reproduce this with **only EssentialsX, Vault and LuckPerms installed**, then post the output of `/ess dump all` on that reproduction setup here?

**Comment by BrandonT80** [comment]
We are a large server and this does not happen too often. I cant remove all the plugins to reproduce this as we would need many players and a handful of time to actually get this to happen. Doing so is not feasible

**Comment by mdcfe** [comment]
As a large server you should have a replica of your server for testing purposes. It's not feasible for us to download 40+ plugins and try and recreate your server from scratch to test EssentialsX alongside all of your other plugins. Nobody else has reported this issue to us previously and you haven't provided any clear steps to reproduce this issue, so even in the extremely slim chance that there was a fault within EssentialsX here, we wouldn't be able to reproduce or fix it.
