### ISSUE TITLE
Our UUID's got reset after enabling cracked with premium accounts.

### ISSUE THREAD

**Issue by RealmKebab** [EssentialsX/Essentials#4894]
### Type of bug

Data loss

### `/ess dump all` output

https://essentialsx.net/dump.html?id=35a4d6ea2b7f421b89f9627ef89e74fb

### Bug description

Our UUID's got flagged as NPC's. We are using microsoft accounts, Our usernames are RealmLabs and Mattsi

We still have our items.
![image](https://user-images.githubusercontent.com/73048123/163673120-800e5b7b-f1f2-4f26-bfe4-8ccf0891f62e.png)

### Steps to reproduce

Enable cracked with a server that already had premium player data on it.
Join it

### Expected behaviour

UUID's should be same as mojang.

### Actual behaviour

Put our UUID's as new stuff.

**Comment by mdcfe** [comment]
We don't support any cracked or hybrid authentication setups.

**Comment by RealmKebab** [comment]
> We don't support any cracked or hybrid authentication setups.

I can't even restore it because i'm using aternos

**Comment by mdcfe** [comment]
We still don't support any cracked or hybrid authentication setups.
