### ISSUE TITLE
EssentialsX Shop Signs & Spawn Eggs

### ISSUE THREAD

**Issue by Jav0330** [EssentialsX/Essentials#490]
Hiyas!

I'm running a spigot server, (Spigot 1.9.0 (2016-03-10-a)), and trying to use the Essentials Shop Signs to sell spawn eggs to players.

The signs are not passing on the Meta, no real surprise there since Meta is on its way out.

I setup the sign picture perfect, [Sell], 1, 383:90, $3000 .. EssentialsX sees it, makes the "Sell" text on the sign blue.

However, clicking on the sign gives me a white egg named "Spawn" which does nothing.

I can sell it back using an essentialsx sign configured for [Buy] in the same fashion as the sell.

Clicking the sell sign with no egg returns the error "You do not have any pigegg in your inventory."

I cannot seem to find any work around for this issue. I have changed the sell item to pigegg from 383:90, that doesn't work.

The Wiki indicates the Shop Signs feature is still supported, so I am curious as to what I have to do to get it to work with Spawn Eggs. (383:90 - 383:120 or so.)

Thanks in advance for all your time and attention in this matter,

-Jav0330

**Comment by saturnux** [comment]
have you build a last spigot ?
have you get a last build of essentialsx ?

i ask but, i don't have this issue.

**Comment by Jav0330** [comment]
currently running essentialsx2.01 and spigot 1.9.0(2016-03-10-a)) 

----- Original Message -----

**Comment by boredhero** [comment]
I submitted a bug report for this, but people seemd to be offended by the idea that anyone would ever want to sell or buy spawn eggs or spawners and no one seems interested in updating signs to support nbt data so that we can actually use [Buy] 1 GuardianEgg $1000 and have it give us a guardian egg with the proper tags. Meta on spawners broke completely in 1.8 and meta in eggs broke in 1.9. Its just that no one seems interested in updating plugins to work with the new standard.

**Comment by Jav0330** [comment]
Thank you. The biggest issue is that peeps that have upgraded to 1.9 have no issue. 

I have only had spigot 1.9 builds on the box. I do not want to use another plugin for this shop. KISS theory here. "Keep It Simple Stupid". 

I realize its the meta, or lack thereof, honest. The item is still in the game, so it must be a simple translation issue. The functionality works, since I can sell the "Spawn" egg back to an identical sign except for the word [Buy]. 

Unfortunately, my java classes do not start until fall. So this falls a wee bit above my skills in Eclipse. (LOL) 

Thanks again for all your time and attention, 

-Jav0330 

----- Original Message -----

**Comment by boredhero** [comment]
I'm a total noob, 15 yrs old with a teach yourself java book that ive worked through 25% of. I have one minecraft mod that makes more things burnable and I have a plugin that makes notch apples craftable again in 1.9 xD

**Comment by Jav0330** [comment]
Well I feel like I pulled the number 142 at the deli counter when the "Now Serving" sign says 01..
..and only 2 people working behind the counter.

**Comment by boredhero** [comment]
preeeeettyyyy much. it would be nice if someone actually considered this issue because there are clearly multiple people who need it now

**Comment by MCTyler** [comment]
Just edit the /give command and make /egive for now like I have done. That way you and your plugins have access to the Minecraft give command. Works in my Pvp Kits! Won't work for signs tho, Sry, you will have to use like QuickShop or something.

**Comment by MCTyler** [comment]
Wow..I feel like an idiot, and this has probably been there all along...Nice of them to Tell us...Geesh
Try this....
//-----------------------//
//|      [buy]            |//
//|           1             |//
//|  spawn_egg:68 |//
//|         $10           |//
//-----------------------//
            //|
            //|
            //|
            //|

**Comment by MCTyler** [comment]
Nevermind...they must of just fixed it.
383:68 works too.

**Comment by MCTyler** [comment]
This Needs closed......

**Comment by boredhero** [comment]
now is it fixed for spawners too?

**Comment by MCTyler** [comment]
This thread is for Sign Shop and Spawn Eggs...Open another one if you need the Author to fix.

**Comment by drtshock** [comment]
Solved with spawn_egg:68 etc
