### ISSUE TITLE
EssentialsXDiscord can't start console logger

### ISSUE THREAD

**Issue by MCT32** [EssentialsX/Essentials#4900]
### Type of bug

Compatibility issue, Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=6d083f47823447be8a2f14ac6698445c

### Bug description

EssentialsXDiscord is not able to start the console logger even though it have the correct permissions. I've given the bot Manage Webhooks permission both in the whole server and in the console channel

### Steps to reproduce

1. Set up config to use a console channel on Discord.
2. Give bot Webhook permissions.
3. Start server.

### Expected behaviour

Bot logs console to the channel.

### Actual behaviour

Plugin gives error "[16:05:42] [Server thread/INFO]: Discord console logger has been disabled due to insufficient permissions! Please make sure your bot has the "Manage Webhooks" permissions on the server. After fixing that, run "/ess reload"."

**Comment by Chew** [comment]
Just a long shot, if the server requires 2FA for moderation, make sure the bot owner has 2fa enabled.

**Comment by pop4959** [comment]
It sounds like you either didn't set up your bot through [https://essentialsx.net/discord.html](https://essentialsx.net/discord.html) (it adds the correct webhook permissions to the bot automatically) or perhaps more specific permissions are blocking it (e.g. on the channel). I briefly tested creating a new bot via the recommended process and configuring the console channel ID, and that was all that was needed to get it working.

Please visit the #essx-support channel on our [Discord server](https://discord.gg/ZwVJukcNQG) for further help troubleshooting, unless you are absolutely sure that this is a bug with Essentials and can provide steps to reproduce.
