### ISSUE TITLE
Flying player is teleported to ground when moving in AFK mode

### ISSUE THREAD

**Issue by Josh65-2201** [EssentialsX/Essentials#4902]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

Doesnt work (Error while creating dump {"status":"error","error":"internal_server_error"}.)

### Bug description

When im in fly mode then go in afk mode with all protection toggles in the config enabled. Moving with WASD the player is teleported to the ground/close suface possible.

### Steps to reproduce

1. Enable auto afk in config
2. set freeze-afk-players: true, disable-item-pickup-while-afk: true, cancel-afk-on-interact: true, cancel-afk-on-move: true, cancel-afk-on-chat: true
3. fly in game
4. enable afk
5. move around

### Expected behaviour

I should stay were i was.

### Actual behaviour

y position not saved

**Comment by pop4959** [comment]
Confirmed on 2.20.0-dev+5-d891268 with the reproduction steps provided

**Comment by kennyrkun** [comment]
Can this be reproduced with just `freeze-afk-players: true` ?

I think this is our culprit:
https://github.com/EssentialsX/Essentials/blob/253185bd0e908c942ca78689f4ae25686d3d973a/Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java#L220

Perhaps simply not using safe location if the player is flying? I'm not a fan of not using safe location, personally.
