### ISSUE TITLE
Books in book.txt do not work

### ISSUE THREAD

**Issue by FishbirdDD** [EssentialsX/Essentials#4912]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=377206bc9a9649cd8d67b0685541bdf8

### Bug description

When giving myself a book defined in book.txt, it says "invalid book tag".

Book.txt:
`#starter`
`This is the starter book`

Command: 
`/i writtenbook 1 book:starter`

Result:
![image](https://user-images.githubusercontent.com/47217458/169675203-9f6f769b-539e-47fb-bbc9-d26dd7735e84.png)

However, if I give myself a writable book instead, the text shows (typing /book switches it back and forth between a written and writable book, and the text switches back and forth between the intended text and "invalid book tag").
![image](https://user-images.githubusercontent.com/47217458/169675266-8ebc326c-3110-42c1-988d-853a964c9d2b.png)

Thanks!

### Steps to reproduce

1. Define a book in book.txt
2. Use the command `/give <player> writtenbook 1 book:<bookname>`
3. Observe the "invalid book tag" error

### Expected behaviour

The text will show

### Actual behaviour

The "invalid book tag" error shows

**Comment by pop4959** [comment]
Confirmed on 2.20.0-dev+5-d891268
