### ISSUE TITLE
Fix Handling of Fake-Player-Accounts

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#492]
So an issue that was brought over from Essentials to EssentialsX is the inability to properly convert fake-player-accounts.

In conjunction with towny when a user changes their name their balance is reset.

Log from IRC about it:
https://gyazo.com/8f8f8a72a073c7a3877d8094e3a4d8cc

Sorry that I really can't give more information I'm hoping this is enough to explain what is going on :L

**Comment by drtshock** [comment]
It's saved by UUIDs.
