### ISSUE TITLE
Disabled commands do not get disabled entirely

### ISSUE THREAD

**Issue by partydev** [EssentialsX/Essentials#4921]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=4c554df6f40f45fca332d8e9a58494f3

### Bug description

Added /me command to disabled commands, however it is not being disabled after a reboot. Will disable if I do `/ess reload`, but then stops being disabled *after a while*. No idea how long.

Have tried this on multiple stable and dev builds as well.

### Steps to reproduce

1. modify config to have a disabled command (/me)
2. attempt to run the command in-game. it works
3. do /ess reload
4. attempt to run the command in-game, it is now disabled

### Expected behaviour

the command should be fully disabled

### Actual behaviour

the commandd is not disabled

**Comment by partydev** [comment]
made my plugin depend on essentialsx and still have same issue

**Comment by kennyrkun** [comment]
Are you saying that the command is only disabled when `/ess reload` is run, but not when the plugin is loaded for the first time?

**Comment by partydev** [comment]
> Are you saying that the command is only disabled when `/ess reload` is run, but not when the plugin is loaded for the first time?

correct

**Comment by JRoy** [comment]
Cannot reproduce, adding me to the disabled-commands list makes it falls back to the minecraft command as expected.

**Comment by partydev** [comment]
Confirmed to be a plugin conflict (Venturechat), thanks for looking into it. Odd that reloading Essentials somehow temporarily fixed it.
