### ISSUE TITLE
File userdata

### ISSUE THREAD

**Issue by Safarival** [EssentialsX/Essentials#4923]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=3ce007f5c4f2415aac9cc48a727cb602

### Error log (if applicable)

https://paste.gg/p/anonymous/f6bc64b124a64ef6a1c24a0ca5d3dd39

### Bug description

The userdata file is not created when the server is started.
it works if I create it manually.

### Steps to reproduce

1) Download EssentialsX.
2) Mettre EssentialsX dans le fichier plugins.
3) Start the server.

### Expected behaviour

I want the userdata file to be created automatically when the server starts.

### Actual behaviour

The userdata file is not created automatically.

**Comment by osfanbuff63** [comment]
~~You appear to be running in offline mode - try enabling `online-mode` in `server.properties`?~~

Unless you are running BungeeCord, in which case not.

I feel like I saw an issue related recently - but can't find it now.

**Comment by Safarival** [comment]
I just tried to run it in online-mode and I still have the same problem so it's not coming from there...

**Comment by Chew** [comment]
My guess is it doesn't have permission to make the folder? Do files appear when people join?

**Comment by JRoy** [comment]
Likely file system permission or memory allocation issues.
