### ISSUE TITLE
[Feature] Damaged items selling

### ISSUE THREAD

**Issue by jfernandz** [EssentialsX/Essentials#493]
I would like ask for a feature; I've noticed that I can repair (with [Repair] sign) and sell the item in a [Sell] sign, however, if I repair the item using an anvil I cannot do that!

I think that would be right that people could spend his materials in repair a dropped (damaged) weapon and then sell it, for instance, golds swords are not so much used and I think that worth to repair and sell it (for a static price, obviously). [Repair] signs are not so right in the point of that the price to repair any item is always the same and there is wide variety of items with different repairment costs.

Thank you so much and congrats for this great plugin! :D

**Comment by drtshock** [comment]
Can you give us the essx and spigot versions / builds you're using

**Comment by jfernandz** [comment]
Of course; 

Spigot is 129f87a-6bf25cd

Essentials v2.0.1-b324

**Comment by drtshock** [comment]
Not sure why I asked that in retrospect. Probably just a habit and didn't realize this was feature request or that I had like 80 tabs of tickets open D:

Do you know if there's a difference to what anvils do during repairs? All we do is set it to full durability..

Also can you tell me if it works when you do /repair as well.

**Comment by jfernandz** [comment]
Well, the result of use /fix (/repair) is the same that anvil repairing ... So ... I cannot sell the repaired item after use that command but I think that really would not be helpful; since there would have the same issue that [Repair] sign, I could set a price to use that comand (/fix) but would be always the same and there are so many items with so many repairing costs. The ideal behavior, imho, would be repair the item in an anvil to sell the item most expensive than separated materials.

**Comment by pop4959** [comment]
I don't think this issue makes much sense. Of course if you repair an item, it will be worth at least the same if not more. Closing in favor of #3055 which suggests simply scaling the price or disabling broken items from being sold (which makes more sense).
