### ISSUE TITLE
Using /give to grant enchanted books allows illegal stacking

### ISSUE THREAD

**Issue by Complex1t** [EssentialsX/Essentials#4937]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=a5da69bfa2d04c9c8f2389a2261c1ffd

### Bug description

Using the /give command to get enchanted books allows illegal stacking of enchantment books.
**Video:** [https://i.imgur.com/QmhNaAQ.mp4](https://i.imgur.com/QmhNaAQ.mp4)

### Steps to reproduce

1. Execute `/give <username> enchanted_book 1 sharpness:1` twice.
2. Observe that you now have 2 enchanted books stacked.

### Expected behaviour

The enchanted books should follow the stacking rules, and not be able to stack.

### Actual behaviour

The enchanted books stack.

**Comment by osfanbuff63** [comment]
Most likely, you have the `essentials.oversizedstacks` permission. Since you don't have a permissions plugin (say - LuckPerms), this is most likely given to op (?). This will not work without that permission - if I am incorrect let me know though.

**Comment by Complex1t** [comment]
Oh yeah, you're right. Thanks.
