### ISSUE TITLE
Essentials chat not working at all

### ISSUE THREAD

**Issue by Botanistt** [EssentialsX/Essentials#494]
Essentials chat isn't working for me at all. I even tried reseting config, still nothing.

**Comment by SupaHam** [comment]
Yes. Very well. Have you tried the following:
1. Turn the server off and on again
2. Make sure you have the EssentialsXChat plugin, then repeat **step 1**

If so, please http://pastebin.com your config.yml and pass us the link here. :)

**Comment by Botanistt** [comment]
I know, I reseted config, EssentialsXChat was installed and etc.
Turned out it was Factions who changed chat. Fake alarm I guess.
Thanks anyway.
