### ISSUE TITLE
Give command doesn't support minecraft namespace

### ISSUE THREAD

**Issue by Relaxing9** [EssentialsX/Essentials#4946]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=7a619d4eba4e42d592f49ed4997da096

### Bug description

When getting items by their minecraft: id (using the give command) they don't work. If they don't work why is it tab completing for it?

![image](https://user-images.githubusercontent.com/41935047/173741728-1e497b89-b3e8-46ab-ae3a-580a08ad41f9.png)

### Steps to reproduce

1. Run /essentials:give (username) minecraft:(anything)

(Username = your username, anything = any Minecraft item you desire)

### Expected behaviour

Should either give the item or not tab complete for "minecraft:".

### Actual behaviour

Warns user about the item not existing.

**Comment by zefir-git** [comment]
![image](https://user-images.githubusercontent.com/66572326/173911347-1bf7f0e5-83d8-4861-82ba-3951777b22c2.png)
(works with give as well)
2.19.4, Paper 1.18.2 Java 17

**Comment by Relaxing9** [comment]
> ![image](https://user-images.githubusercontent.com/66572326/173911347-1bf7f0e5-83d8-4861-82ba-3951777b22c2.png) (works with give as well) 2.19.4, Paper 1.18.2 Java 17

Incorrect. If you read my Issue I said there is an issue if you use "minecraft:" tags you just used "/i birch_sign 1" what I'm using is "/i minecraft:birch_sign 1" (It tab completes but it doesn't exist, see below)

![image](https://user-images.githubusercontent.com/41935047/173933115-623aaad4-7180-4b21-a31e-25cae1ce7dc1.png)

**Comment by osfanbuff63** [comment]
Confirmed on 2.19.5-dev+19-96c6c95. ([`/ess dump all`](https://essentialsx.net/dump.html?id=83d4e1f17bf7462c81b42fc3f2fd1faa))
