### ISSUE TITLE
EXDiscord Compatibility with PlugManX

### ISSUE THREAD

**Issue by GavinGoGaming** [EssentialsX/Essentials#4957]
### Type of bug

Compatibility issue

### `/ess dump all` output

https://essentialsx.net/dump.html?id=674d5ed2aa794beb97e30ea783cd45f8

### Bug description

Version 2.19.5-dev+19-96c6c95
plugmanx doesnt work with exdiscord

### Steps to reproduce

1. Add PlugManX and EssentialsXDiscord 2.19.5-dev+19-96c6c95
2. restart

### Expected behaviour

PlugManX enables and EssentialsXDiscord also enables and both work

### Actual behaviour

PlugManX disables and essentialsXdiscord breaks

**Comment by JRoy** [comment]
PlugMan isn't supported
