### ISSUE TITLE
Dev Build version check text output prints control characters

### ISSUE THREAD

**Issue by felixtech-msp** [EssentialsX/Essentials#4962]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=a4c35562f0cc4fc08009bc095f8ea8e5

### Bug description

When running a dev build the version check outputs nonsense-characters to the console.

```
[Essentials]: §6Fetching version information...
[Essentials]: §4You're §c1 §4EssentialsX dev build(s) out of date!
[Essentials]: §4Download it here:§c https://essentialsx.net/downloads.html
```

### Steps to reproduce

1. Put some outdated dev build of the core plugin into a Paper server and run it.

### Expected behaviour

Output only text to the console.

### Actual behaviour

Outputs $6, $4 and $c additionally into the text when reporting from the version check.

**Comment by osfanbuff63** [comment]
I would guess this is since it uses the same module for both the chat and console version checkers.

As well, do you have the latest Paper version? If so, it's also possible that your console doesn't support colors, because anything with § is equivalent to the Bukkit color code & (e. g. &3 and §3 are the same color, #00AAAA (or dark aqua) ).

**Comment by mdcfe** [comment]
This is a known issue on Paper. We're planning to fix section symbols appearing in logs on Paper soon (#4941).

**Comment by felixtech-msp** [comment]
Using Paper version #[5593f4e](https://github.com/PaperMC/Paper/commit/5593f4edd3dfec926de3ba9616fc69f2b18c51b6) which is currently the latest version for our AMP production infrastructure. Tested also on Ubuntu Server 22/Bash dev server (supports color; `§6Fetching version information...` is default color; `§4You're §c1 §4EssentialsX dev ...` and `§4Download it here:§c https...` are yellow).

**Comment by JRoy** [comment]
Fixed in the latest dev build
