### ISSUE TITLE
tptoggle command prevents OP players to teleport to players

### ISSUE THREAD

**Issue by YanisBft** [EssentialsX/Essentials#4964]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=257ef6eb34f14d6e99377ca80c0b447b

### Bug description

When a player has disable teleportation requests through /tptoggle command, even OP players cannot teleport to the player with essentials commands.

### Steps to reproduce

1. Make sure to be OP and have another player connected with you
2. Make the other player run /tptoggle to disable teleportation requests
3. Try to use essentials' teleportation commands like /tp, /tpa, etc

### Expected behaviour

OP players should be able to override the teleportation. They should still be able to teleport to players

### Actual behaviour

OP players are affected by the /tptoggle state, so they cannot teleport to players if they disabled teleportation requests

**Comment by 100petr** [comment]
Try the `/tpo` command

**Comment by pop4959** [comment]
Use existing commands and/or permissions such as @100petr mentioned above to override teleportation. In general, using OP to handle permissions is not widely supported nor recommended, and we recommend plugins like [LuckPerms](https://luckperms.net/) instead.
