### ISSUE TITLE
[Essentials] You are running a server fork that is known to be extremely dangerous and lead to data loss. It is strongly recommended you switch to a more stable, high-performing server software, like Paper or Tuinity.

### ISSUE THREAD

**Issue by FeelDayOfficial** [EssentialsX/Essentials#4968]
### Type of bug

Error in console

### `/ess dump all` output

-

### Bug description

[Essentials] You are running a server fork that is known to be extremely dangerous and lead to data loss. It is strongly recommended you switch to a more stable, high-performing server software, like Paper or Tuinity.

### Steps to reproduce

1.start the server
2. an error is shown

### Expected behaviour

what needs to be done to avoid errors?

### Actual behaviour

-

**Comment by osfanbuff63** [comment]
Can you run `ess dump all`? That would give us information that will help us here.

Are you using a server software other than Paper? The server will run fine without using Paper, but it's highly recommended with this plugin. If you aren't using it, you can download it [here](https://papermc.io).

**Comment by Chew** [comment]
Please use a supported software.

**Comment by FeelDayOfficial** [comment]
> Please use a supported software.

it works but i can't calm down seeing this error

**Comment by FeelDayOfficial** [comment]
> Can you run `ess dump all`? That would give us information that will help us here.
> 
> Are you using a server software other than Paper? The server will run fine without using Paper, but it's highly recommended with this plugin. If you aren't using it, you can download it [here](https://papermc.io).

https://essentialsx.net/dump.html?id=17c2ffa4471b466492188e41fd58df32

**Comment by Chew** [comment]
Please download Paper from https://papermc.io/downloads

**Comment by FeelDayOfficial** [comment]
> Please download Paper from https://papermc.io/downloads

Are you saying that I need to switch to another core?
