### ISSUE TITLE
[Essentials] You are running a server fork that is known to be extremely dangerous and lead to data loss. It is strongly recommended you switch to a more stable, high-performing server software, like Paper or Tuinity.

### ISSUE THREAD

**Issue by FeelDayOfficial** [EssentialsX/Essentials#4969]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=17c2ffa4471b466492188e41fd58df32

### Bug description

[Essentials] You are running a server fork that is known to be extremely dangerous and lead to data loss. It is strongly recommended you switch to a more stable, high-performing server software, like Paper or Tuinity.

### Steps to reproduce

1.start the server
2. an error is shown

### Expected behaviour

what should be done to avoid errors without switching to a new kernel?

### Actual behaviour

.

**Comment by Chew** [comment]
Please don't open duplicate issues.

**Comment by FeelDayOfficial** [comment]
> [ bug: unconfirmed ](/EssentialsX/Essentials/labels/bug%3A%20unconfirmed) l

I did not find a solution, so I duplicate
