### ISSUE TITLE
When using Newer Usermap Jar, possible apparent User Perm Caching issue?

### ISSUE THREAD

**Issue by LunarsWorldLLC** [EssentialsX/Essentials#4972]
### Type of bug

Performance issue or memory leak

### `/ess dump all` output

EssentialsX Version: 2.19.5-dev+9-6367237 Luckperms Version: 5.4.18

### Bug description

I'm using the "custom" jar Jroy made, with the new user mapping.

This jar fixed all the usermap errors, and my memory leak. However, now I notice a couple plugins taking up much of the tick, for com.earth2me.essentials.perm.impl.LuckPermsPermissible.hasPermission().

Seems to possibly be a cache issue? I don't really know what I'm talking about though. 

https://imgur.com/a/2G1VzT3

Maybe no support will be given considering I'm using an experimental jar, either way, thought I'd find out.

### Steps to reproduce

Run jroy's essentialsx jar with the new usermapping, with luckperms and other plugins.

Run a spark.

### Expected behaviour

I wasn't experiencing anything perm or essentials related previous to using this jar, now I am.

### Actual behaviour

https://imgur.com/a/2G1VzT3

**Comment by JRoy** [comment]
I'm going to need the `/ess dump all` link and spark link

**Comment by LunarsWorldLLC** [comment]
https://spark.lucko.me/6rQnEVtyRu

https://spark.lucko.me/gAPsysspwT

Ones a regular spark, ones a thread spark. 


https://essentialsx.net/dump.html?id=cc2110c1be15401a95d1bc3036f14c62

**Comment by LunarsWorldLLC** [comment]
![image](https://user-images.githubusercontent.com/78775526/177662218-028a12bf-5506-4646-b5c7-33bb195f9e5c.png)
