### ISSUE TITLE
Balance Wiped After Reloading

### ISSUE THREAD

**Issue by ImMalkah** [EssentialsX/Essentials#4973]
### Type of bug

Data loss

### `/ess dump all` output

https://essentialsx.net/dump.html?id=6538fd4f1e3d4d28ad84c851e259ba23

### Bug description

When I reload the server twice, the balance of all players on the server gets wiped. 

### Steps to reproduce

1. Join the server
2. Give yourself any amount of $
3. Reload once, check balance, you should see you still have it
4. Reload once more, check your balance, it will be reset back to zero

### Expected behaviour

The balance should not be reset, expecting no data loss upon server reload

### Actual behaviour

Reloading the server twice wipes all the players' balances.

https://user-images.githubusercontent.com/80030041/176778859-af6e6530-f566-4e7c-9f48-5a766191b5ea.mp4

**Comment by JRoy** [comment]
The reload command isn't supported

**Comment by osfanbuff63** [comment]
Use `/restart` instead, as I don't believe reloading is supported.
