### ISSUE TITLE
Changing nicknames with change-displayname set to false shows player displayname in feedback message

### ISSUE THREAD

**Issue by Warriorrrr** [EssentialsX/Essentials#4979]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=34094f17582c4cba9d12c427efe92f51

### Bug description

Using /nick with change-displayname set to false will always show the player's display name instead of their new nickname.

### Steps to reproduce

1. Set change-displayname to false in the config
2. Run /nickname test

### Expected behaviour

The feedback message to say "Your nickname is now test".

### Actual behaviour

The feedback message says "Your nickname is now player_name".

**Comment by osfanbuff63** [comment]
I feel like this would be intended, but I don't know.
