### ISSUE TITLE
Repairing doesn't work on Elytras.

### ISSUE THREAD

**Issue by Johandrex** [EssentialsX/Essentials#498]
When using "/fix all" or "/repair all" the Elytras aren't being repaired.

Essentials version: 2.0.1-b190

**Comment by boredhero** [comment]
I believe that was fixed in a recent version.

**Comment by drtshock** [comment]
Can you confirm on the most recent dev build and then post which build it worked / didn't work on please

**Comment by drtshock** [comment]
ok
