### ISSUE TITLE
New mob egg not supported with /give command

### ISSUE THREAD

**Issue by voigtman** [EssentialsX/Essentials#4982]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=31292d8e58824113a62c3e2c43d158b4

### Bug description

Cannot use /give command to receive spawn eggs for new Mobs (1.17-1.19)

Mobs tested and failed:
allay_spawn_egg
axolotl_spawn_egg
glow_squid_spawn_egg
frog_spawn_egg
tadpole_spawn_egg
warden_spawn_egg

### Steps to reproduce

Type the command 
/give playerName frog_spawn_egg

### Expected behaviour

Giving 64 of frog spawn egg to playerName

### Actual behaviour

Error: Unknown item name: frog_spawn_egg

**Comment by triagonal** [comment]
If you updated to 1.19 from an earlier installation, try deleting your `plugins/Essentials/items.json` file and restart your server to update your item data.

**Comment by voigtman** [comment]
Seemed to work, not a straightforward solution, but it worked. Thanks
