### ISSUE TITLE
UUID Issue

### ISSUE THREAD

**Issue by MrUniverse44** [EssentialsX/Essentials#4986]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=fcb206159c844daf8e1abacb34b361c5

### Error log (if applicable)

https://www.toptal.com/developers/hastebin/ojarawituw.properties

### Bug description

Just Appeared one day so i don't know what is causing it

### Steps to reproduce

N/A

### Expected behaviour

Nothing

### Actual behaviour

It appear all the time in console.

**Comment by pop4959** [comment]
The reason why you are seeing that is because at some point your server was in offline mode.

Closing as a duplicate of #4342.
