### ISSUE TITLE
Make amount argument optional in /give and /item commands

### ISSUE THREAD

**Issue by aloki** [EssentialsX/Essentials#4992]
### Type of bug

Compatibility issue

### `/ess dump all` output

N/A

### Bug description

I am using Roughly Enough Items mod. In cheat mode, it is not possible to get an item in a single quantity, since REI does not add an amount argument if it is equal to 1:
/give Reactor diamond_chestplate {Damage:0}

The REI developer refused to change the behavior of the mod as the vanilla command works. Since EssentialsX changes the vanilla commands syntax, can you make both syntaxes valid:
/give <player> <item|numeric> [amount [itemmeta...]]
/give <player> <item|numeric> [amount] [itemmeta...]
/item <item|numeric> [amount [itemmeta...]]
/item <item|numeric> [amount] [itemmeta...]

### Steps to reproduce

1. Use REI mod
2. In the mod settings, change the command for cheating items to /give {player_name} {item_identifier} {count} {nbt}
3. On the mod screen, click on an item, such as Diamond Chestplate

### Expected behaviour

The item must be given

### Actual behaviour

Item not given due to invalid command

**Comment by mdcfe** [comment]
Please don't use bug reports to request features.

It's unlikely that we will change the syntax right now, as there are larger changes for `/give` and `/item` planned. 

You should use `/minecraft:give` in your mod's settings - this is the vanilla command on all Bukkit-based servers, and EssentialsX does not override this command.

For future feature requests, please [follow the instructions for feature requests](https://github.com/EssentialsX/Essentials/issues/new/choose).
