### ISSUE TITLE
nicknames and socialspy bug

### ISSUE THREAD

**Issue by Cruwzky** [EssentialsX/Essentials#4998]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=a6a44d853f4f4840974297bff8ad9c15

### Error log (if applicable)

There are no errors.

### Bug description

If you change the locale "socialSpyPrefix" to something like this "socialSpyPrefix=§8COMMAND: §7"

It will show the player username and message in light gray (§7). If that player uses /nick and chooses a nick name the message is changed to white and the username is using the displayname.

(This makes socialspy messages very hard to distinguish from normal chat for the staff. There is a reason we want it light gray. Why is this locale not configurable? everything else is..)

The bug here is that if the user removes the nickname again the socialspy username and message is still in all white. But for all the rest without nicknames its gray. This completely destroys our coloring schema and makes the chat hard to read.

### Steps to reproduce

Admin:
/socialspy (activate)

User:
/nick nickname
/nick (removes nick again)

The username and message is now showing wrong color in socialspy messages.

### Expected behaviour

It expect it to atlaest use the color choosen in the locale. The best would be too make us able to actually configure this in the locale like we can with any other messages.

### Actual behaviour

Colors are wrong.

**Comment by pop4959** [comment]
This isn't a bug, the prefix only applies to the first part of the message. Make sure you are also setting [socialSpyMsgFormat](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/resources/messages.properties#L1165) correctly.
