### ISSUE TITLE
It is impossible to find out the balance of Offline Player

### ISSUE THREAD

**Issue by moda84** [EssentialsX/Essentials#5000]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=5d95c2d0994b4eb8a935cab67c4ba2f4

### Bug description

When the /bal command is used, if the player is not online, it gives an error that the player is not found.

### Steps to reproduce

1. Player1 have 500$ in /bal
2. Player1 has left the server
3. /bal Player1
4. Error, player not found

### Expected behaviour

Fix it!
Make it so that if a player leaves, his balance can be found out

### Actual behaviour

It is impossible to find out the balance of Offline Player

**Comment by NoobcoreNetwork** [comment]
![AvastBrowser_m1zT3inBqz](https://user-images.githubusercontent.com/62724418/179577783-8cb154a3-31bc-4dae-93af-a0471a749f0b.png)

This is an offline player on my server.

**Comment by moda84** [comment]
> ![AvastBrowser_m1zT3inBqz](https://user-images.githubusercontent.com/62724418/179577783-8cb154a3-31bc-4dae-93af-a0471a749f0b.png)
> 
> This is an offline player on my server.

version?

**Comment by pop4959** [comment]
Can't reproduce either. Most likely another plugin overriding the `/bal` command or some other issue. Try testing this on a fresh server with only Essentials installed, and if you're still experiencing problems we can look into this further.
