### ISSUE TITLE
/ice sending wrong message to target

### ISSUE THREAD

**Issue by minelolpride** [EssentialsX/Essentials#5002]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=b088d4c02516411bae9fe6a57787a058

### Bug description

As a player with full access to `/ice`, using it on another player will send both the `Chilling <playername>.` message as well as the `You feel much colder...` message, while the player issueing the command gets nothing.

### Steps to reproduce

1. Have at least 2 users on a server, with one having full access to `/ice`. (the "admin")
2. Have the "admin" use `/ice` on another user.

### Expected behaviour

The "admin" should get the message saying `Chilling <playername>.`, while the target gets the message `You feel much colder...`.

### Actual behaviour

The "admin" gets no messages, while the target gets both the `Chilling <playername>.` and `You feel much colder...` messages.

**Comment by minelolpride** [comment]
Right after submitting this issue I realize I did not actually download the latest dev build from the downloads page, oops. I went and downloaded the latest dev build right afterwards and found this still happens, no changes there.
`/ess dump all`: https://essentialsx.net/dump.html?id=3ffac1ae167e4e0ba653b8a25556a092

**Comment by pop4959** [comment]
Can reproduce on Essentials 2.19.5-dev+22-9c5536b
