### ISSUE TITLE
Error while reading user config: [money]

### ISSUE THREAD

**Issue by devendrapoonia** [EssentialsX/Essentials#5003]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=bf0d34bfa785484b90e5c80443c5c984

### Error log (if applicable)

https://paste.gg/p/anonymous/779dedd40dba403bafbd8e141faf1387

### Bug description

This error occurs whenever a specific user join who doesn't have Bedrock edition premium. LuckPerms also gives some errors when that player with no premium joins. I think this is the issue with LuckPerms.

### Steps to reproduce

1. Install EssentialsX
2. Install LuckPerms
3. Join using Bedrock cracked.

### Expected behaviour

There should be no error whenever a user joins.

### Actual behaviour

Console is spamming with errors. That user can't execute any commands.

**Comment by JRoy** [comment]
We don't support bedrock nor offline mode
