### ISSUE TITLE
Essentials Login Console Issue

### ISSUE THREAD

**Issue by DebuffPvP** [EssentialsX/Essentials#5006]
### Type of bug

Other unexpected behaviour

### Error log (if applicable)

https://www.toptal.com/developers/hastebin/afulilisal.properties

### Bug description

This happened to me upon login and it's random and i forgot to do the dump command 

### Steps to reproduce

I don't know but was wondering if you guys may know what it means

### Expected behaviour

To not do it

### Actual behaviour

it does it

**Comment by pop4959** [comment]
Duplicate of #4342

**Comment by DebuffPvP** [comment]
that's someone else that posted that?

**Comment by pop4959** [comment]
> that's someone else that posted that?

It's a duplicate because it's the same issue, not because you posted it. That's fine, but generally only one issue is kept open to make things easier to track.
