### ISSUE TITLE
[Suggestion] - Essentials Anti-build Additions

### ISSUE THREAD

**Issue by clovisd** [EssentialsX/Essentials#501]
Hey Guys!

Essentials Antibuild hasn't gotten a whole lot of love in recent months (years?). It's only effective with blocking single items but not their meta objects. For example, if one wanted to block a specific potion, putting 373 in the blacklist would block all potions. However, putting 373:8193 would still block all potions and not just the desired regeneration potion.

Thank you,
Clovis

**Comment by pop4959** [comment]
Item IDs are no longer supported in MineCraft, and "the flattening" in 1.13 probably cause this to no longer be an problem. If it is, please feel free to make a new issue for it.
