### ISSUE TITLE
Essentials not running on Magma servers, plugin gets disabled

### ISSUE THREAD

**Issue by GutiNicolas** [EssentialsX/Essentials#5011]
### Type of bug

Compatibility issue, Error in console

### `/ess dump all` output

5Jul2022 20:45:26.119] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling Essentials v2.19.4 (Is it up to date?) java.lang.NullPointerException: Cannot invoke "net.ess3.provider.ServerStateProvider.isStopping()" because the return value of "com.earth2me.essentials.Essentials.getServerStateProvider()" is null 	at com.earth2me.essentials.Essentials.onDisable(Essentials.java:538) ~[?:?] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[forge-1.18.2-40.1.54-universal.jar%23106!/:?] 	at com.earth2me.essentials.Essentials.handleCrash(Essentials.java:1073) ~[?:?] 	at com.earth2me.essentials.Essentials.onEnable(Essentials.java:481) ~[?:?] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[forge-1.18.2-40.1.54-universal.jar%23106!/:?] 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[forge-1.18.2-40.1.54-universal.jar%23106!/:?] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[forge-1.18.2-40.1.54-universal.jar%23106!/:?] 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:434) ~[forge-1.18.2-40.1.54-universal.jar%23106!/:?] 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:348) ~[forge-1.18.2-40.1.54-universal.jar%23106!/:?] 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.reload(CraftServer.java:834) ~[forge-1.18.2-40.1.54-universal.jar%23106!/:?] 	at org.bukkit.Bukkit.reload(Bukkit.java:801) ~[forge-1.18.2-40.1.54-universal.jar%23106!/:?] 	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[forge-1.18.2-40.1.54-universal.jar%23106!/:?] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[forge-1.18.2-40.1.54-universal.jar%23106!/:?] 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:742) ~[forge-1.18.2-40.1.54-universal.jar%23106!/:?] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9957_(ServerGamePacketListenerImpl.java:1649) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_143628_(ServerGamePacketListenerImpl.java:1561) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7388_(ServerGamePacketListenerImpl.java:1542) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.network.protocol.game.ServerboundChatPacket.m_5797_(ServerboundChatPacket.java:35) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.network.protocol.game.ServerboundChatPacket.m_5797_(ServerboundChatPacket.java:6) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:25) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:931) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:129) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:914) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:908) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:893) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:800) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:253) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at java.lang.Thread.run(Thread.java:833) [?:?]

### Error log (if applicable)

5Jul2022 20:45:26.119] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling Essentials v2.19.4 (Is it up to date?) java.lang.NullPointerException: Cannot invoke "net.ess3.provider.ServerStateProvider.isStopping()" because the return value of "com.earth2me.essentials.Essentials.getServerStateProvider()" is null 	at com.earth2me.essentials.Essentials.onDisable(Essentials.java:538) ~[?:?] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[forge-1.18.2-40.1.54-universal.jar%23106!/:?] 	at com.earth2me.essentials.Essentials.handleCrash(Essentials.java:1073) ~[?:?] 	at com.earth2me.essentials.Essentials.onEnable(Essentials.java:481) ~[?:?] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[forge-1.18.2-40.1.54-universal.jar%23106!/:?] 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[forge-1.18.2-40.1.54-universal.jar%23106!/:?] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[forge-1.18.2-40.1.54-universal.jar%23106!/:?] 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:434) ~[forge-1.18.2-40.1.54-universal.jar%23106!/:?] 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:348) ~[forge-1.18.2-40.1.54-universal.jar%23106!/:?] 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.reload(CraftServer.java:834) ~[forge-1.18.2-40.1.54-universal.jar%23106!/:?] 	at org.bukkit.Bukkit.reload(Bukkit.java:801) ~[forge-1.18.2-40.1.54-universal.jar%23106!/:?] 	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[forge-1.18.2-40.1.54-universal.jar%23106!/:?] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[forge-1.18.2-40.1.54-universal.jar%23106!/:?] 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:742) ~[forge-1.18.2-40.1.54-universal.jar%23106!/:?] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9957_(ServerGamePacketListenerImpl.java:1649) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_143628_(ServerGamePacketListenerImpl.java:1561) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7388_(ServerGamePacketListenerImpl.java:1542) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.network.protocol.game.ServerboundChatPacket.m_5797_(ServerboundChatPacket.java:35) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.network.protocol.game.ServerboundChatPacket.m_5797_(ServerboundChatPacket.java:6) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:25) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:931) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:129) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:914) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:908) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:893) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:800) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:253) ~[server-1.18.2-20220404.173914-srg.jar%23101!/:?] 	at java.lang.Thread.run(Thread.java:833) [?:?]

### Bug description

Essentials not working on magma servers for magma 1.18.2

### Steps to reproduce

run server

### Expected behaviour

enable essentials

### Actual behaviour

disable essentials

**Comment by mdcfe** [comment]
We don't support Magma.
