### ISSUE TITLE
Kicked from server for "Invalid Player Move Packet Received" inconsistently when using any kind of teleport. Issue stops when essentials or citizens is removed.

### ISSUE THREAD

**Issue by Sealflipper** [EssentialsX/Essentials#5012]
### Type of bug

Compatibility issue

### `/ess dump all` output

https://essentialsx.net/dump.html?id=d76e5f30ee3b49bb9080e7309d5dff9d

### Error log (if applicable)

N/A

### Bug description

No error in the console. Players are inconsistently kicked whenever they use any kind of teleport after the 1.19 update. Teleports include /tp, /tpa, /warp, /spawn, /rtp, and even nether portals. The kick they get is for: "Invalid player move packet received".

There is no error logs in console.

I found that when removing either essentials or citizens the problem goes away. 

I found another server owner who also has had the same bug as me. I tested every other plugin we shared between us, but no others fixed the issue when they were removed. The other server owner kick events happened less on their server than mine. We both had similar sizes of RAM and no issue with tps for our servers. They were a smaller server though. 

We imported the other server owners' files on a test server, but couldn't confirm if the bug was present or not because it was much more of a rare occurrence for him. I tried testing with my essentials and citizens files and recreated it.

[server133597 - 25 Jul 2022 17_30_0.zip](https://github.com/EssentialsX/Essentials/files/9185439/server133597.-.25.Jul.2022.17_30_0.zip)
[server133597 - 25 Jul 2022 18_15_42.zip](https://github.com/EssentialsX/Essentials/files/9185440/server133597.-.25.Jul.2022.18_15_42.zip)

### Steps to reproduce

1. upload citizens and essentials
2. Put attached citizens and essentials folders in
3. Go on the server and use /tppos or /spawn until it kicks you

This is as far as I know. Not sure why this problem is happening

### Expected behaviour

You should be able to teleport and not be kicked for bad packets

### Actual behaviour

players are sometimes kicked from the server for bad packets

**Comment by pop4959** [comment]
Likely due to another plugin. If you can reproduce this with just Essentials installed on the server, we can re-open this issue.
