### ISSUE TITLE
com.earth2me.essentials.User.isGodModeEnabled() error

### ISSUE THREAD

**Issue by mrpunky** [EssentialsX/Essentials#5013]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=0928e0050cf842f9bb44431b2e94060a

### Error log (if applicable)

https://paste.gg/p/anonymous/3d98555ecc1c45d8bba85e08c8c1aa52

### Bug description

i am getting an error like this
![image](https://user-images.githubusercontent.com/101196617/181094286-ab03200a-43a1-4104-9d6f-e8cc7d82067f.png)

### Steps to reproduce

When I enter the game, the console keeps giving this error.

### Expected behaviour

problem solving

### Actual behaviour

I don't know what to write here

**Comment by pop4959** [comment]
This bug is caused by WorldGuardExtraFlags, which is not an addon maintained by us. Please report this to them instead.
