### ISSUE TITLE
/speed not working

### ISSUE THREAD

**Issue by JXSnack** [EssentialsX/Essentials#5023]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=3f2b58fa287d4a64bc8399239905a05e

### Error log (if applicable)

There is no error.

### Bug description

Hello, I'm currently building a massive map and need to go from side to side, but /speed is not working. I stay at speed 1. There is no error in the console or something like that or a plugin that would prevent that.

My plugins: Essentials, EssentialsSpawn, GSit, HeadDB, HolographicDisplays, JumpPads, LibsDisguises, LPC, Luckperms, Multiverse-Core, NexEngine, OmegaVision, PlaceholderAPI, PlugManX (PlugMan), ProtocolLib, ServersNPC/ZNPCS, SimplePortals, TAB, Vault, Vehicles, WorldEdit

Server version: 1.18.2
Java: 17.0.3
Minecraft: Paper

### Steps to reproduce

Use /speed

### Expected behaviour

When you do /speed 10, your player speed will increase to 10

### Actual behaviour

The speed still is 10.

**Comment by pop4959** [comment]
Unable to replicate, please make sure that you test this with only Essentials installed to make sure this isn't an issue caused by another plugin. If you're able to provide exact steps to cause this to happen feel free to open another report.
