### ISSUE TITLE
Swift Sneak enchant missing in /enchant

### ISSUE THREAD

**Issue by ItzRobin** [EssentialsX/Essentials#5024]
### Type of bug

Compatibility issue

### `/ess dump all` output

https://essentialsx.net/dump.html?id=928d672b74d745b3b66f27c0b8a06360

### Bug description

The /enchant command doesn't work yet with the new enchant Swift Sneak

### Steps to reproduce

1. Take a legging
2. Run /enchant swiftsneak 1

### Expected behaviour

 The item should be enchanted with swiftsneak level 1

### Actual behaviour

Nothing happens

**Comment by pop4959** [comment]
Thanks for catching this, the enchantment should be available in the latest dev build.
