### ISSUE TITLE
Getting kicked for "Chat message validation failiure" on 1.19.1

### ISSUE THREAD

**Issue by leofleeo** [EssentialsX/Essentials#5031]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=66a2fc09701c4baca7744206fd0c3f07

### Bug description

Getting kicked for "Chat message validation failiure"

### Steps to reproduce

Install esentialsx, essentialsx chat and vault on 1.19.1 with paper.
Configure essentialsx chat format to NAME: MESSAGE
Send a chat message

### Expected behaviour

Not getting kicked on every chat message

### Actual behaviour

Whenever somebody sends a chat message they get kicked for "Chat message validation failiure"
I am not using nochatreports because I had to uninstall it because I thought it was causing the issue but it was not

**Comment by osfanbuff63** [comment]
Could you please upload your `server.properties` to https://gist.github.com and share the link here?

**Comment by mdcfe** [comment]
EssentialsX doesn't support secure chat yet - this should be fixed by #5030.

Would you mind downloading the [`feature/chat-signing` test jars](https://github.com/EssentialsX/Essentials/suites/7635474719/artifacts/317443732) and seeing if that fixes the issue?

**Comment by CloudyWhale** [comment]
> 

It is just the default server.properties but with spawn monsters off

**Comment by leofleeo** [comment]
> Could you please upload your `server.properties` to https://gist.github.com and share the link here?

It is just the default server.properties just with the spawn monsters setting off

**Comment by osfanbuff63** [comment]
> > Could you please upload your `server.properties` to https://gist.github.com and share the link here?
> 
> It is just the default server.properties just with the spawn monsters setting off

OK - for now, try setting `enforce-secure-profile=false` until #5030 is merged and ready.

**Comment by pop4959** [comment]
For what it's worth I've been testing [`feature/chat-signing`](https://github.com/EssentialsX/Essentials/suites/7635474719/artifacts/317443732) for about a day so far and have had zero issues so far. This is with `enforce-secure-profile=false` and `previews-chat=true`.

Would highly recommend anyone with issues to try it out since it's low risk anyways.

**Comment by leofleeo** [comment]
Disabling enforce secure profile does work without the dev build but I will leave this open because it is not a permanent fix

**Comment by JRoy** [comment]
TAB is causing the issue not essentials. Please try without essentials installed.

**Comment by JRoy** [comment]
> TAB is causing the issue not essentials. Please try without essentials installed. 

Sorry I meant without tab installed 😄

**Comment by mdcfe** [comment]
The latest dev builds now support secure chat signing. Let us know if you still have issues on these builds.

**Comment by JRoy** [comment]
Should no longer be an issue on latest Essentials dev builds and latest Paper.
