### ISSUE TITLE
Hide decimal places

### ISSUE THREAD

**Issue by Kixot14** [EssentialsX/Essentials#504]
Add option for hide decimal places in economy (like new **decimal-places** feature in Scavenger plugin). 
I have only integer price and don't want to have any decimals in  costs or when using balances command.

**Comment by Kakifrucht** [comment]
#432 they don't really seem to care, even though it's a quick fix and @SupaHam forced this upon us :/

**Comment by SupaHam** [comment]
This wasn't a quick fix. Completely full feature, this feature was brought up after the fact.

**Comment by Kakifrucht** [comment]
What I meant by quick fix is that it wouldn't waste alot of your time if you could just add a simple boolean to the config to disable the functionality. I thank you for your support you give to the plugin, but you really shouldn't force features upon users, especially if there are quite alot of the users who really don't want it. Europeans generally don't want American number formats.

**Comment by SupaHam** [comment]
This has been fixed in 785bd5b. You can grab the fix from [build 373](https://ci.drtshock.net/job/EssentialsX/) on the CI server.
