### ISSUE TITLE
EssentialsX not loading in latest version of paper

### ISSUE THREAD

**Issue by leofleeo** [EssentialsX/Essentials#5057]
### Type of bug

Compatibility issue

### `/ess dump all` output

I cannot do that

### Error log (if applicable)

https://gist.github.com/CloudyWhale/560fa2a1d41aecb3774420883a367ec0

### Bug description

EssentialsX does not load on server

### Steps to reproduce

1: Run latest version of paper
2: Install essentialsX

### Expected behaviour

EssentialsX loads correctly

### Actual behaviour

EssentialsX does not load at all and the essentials config directory is not created

**Comment by mdcfe** [comment]
Could you post a screenshot of your plugins directory?

**Comment by leofleeo** [comment]
> Could you post a screenshot of your plugins directory?

![image](https://user-images.githubusercontent.com/83542885/184503617-db7bf8ba-50b3-46d5-b28d-07c0df21883b.png)

**Comment by mdcfe** [comment]
You've only installed addon modules, not EssentialsX itself. You need to install the main EssentialsX jar for EssentialsX addons to work.

**Comment by leofleeo** [comment]
Wow. How did I miss that.
