### ISSUE TITLE
Enhance Controlled Private Messaging

### ISSUE THREAD

**Issue by EvilOlaf** [EssentialsX/Essentials#506]
Hey there,

some of my users feel uncomfortable with the new `/r` behavior.
In parts I can understand that, especially for the elder ones who were using /r for years now...including me.

Anyways, I was thinking about how this could be fixed and one came up with the idea to let users decide in which way they want their received messages being handled. So probably a command like `toggle-r` or something like this.

Thanks for reading.

**Comment by drtshock** [comment]
You can simply disable the new functionality. I don't see us adding an option to toggle this per user.

**Comment by EvilOlaf** [comment]
I am aware about the config option. Though it changes the behavior server wide.
As mentioned above only some users do not like this behavior so much.
