### ISSUE TITLE
Suggestion: /rename name (renames item in your hand like anvil does)

### ISSUE THREAD

**Issue by StoneLegion** [EssentialsX/Essentials#508]
Would be nice to have this command unless I'm blind I don't think I saw this anywhere.

**Comment by boredhero** [comment]
I agree with you, this would be a very nice feature

**Comment by drtshock** [comment]
This is a good point.

**Comment by SupaHam** [comment]
See #672 for an implementation.

**Comment by Sikatsu** [comment]
@SupaHam Will you still eventually merge this? Has been closed, but never actually added.
