### ISSUE TITLE
Unsafe Enchants

### ISSUE THREAD

**Issue by IceWaffles** [EssentialsX/Essentials#5083]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=7d9a6dc7192241cfade1d7c384f26861

### Bug description

When doing /enchant, you can have incompatible enchantments such as blast protection and protection on armour. (When unsafe enchants is OFF in the config) I should note that I have tested this with latest but the paste is just the server I was currently on. If you would like a dump from a 1.19.2 stable release (latest) I can do it again, but I guarantee it works there too. Should note that technically enchants like protection x or whatnot don't work, nor do incorrect enchantments (eg protection for a sword)

### Steps to reproduce

Step 1. Turn off unsafe enchants in the config.
Step 2. Do /enchant prot 4 and /enchant blast prot 4 (or whatever armour protection)

### Expected behaviour

Should not go through.

### Actual behaviour

It goes through and item has two incompatible enchants on it.

**Comment by JRoy** [comment]
This is intended and has been behavior since its creation. We use Bukkit's underlying definition of "unsafe" to determine when to apply enchantments or not, which considers enchantment level and whether or not the enchantment is "illegal" for an item.
