### ISSUE TITLE
Unable to use @p @s @e and @a in /tp command

### ISSUE THREAD

**Issue by Attack8** [EssentialsX/Essentials#5095]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=bdeb62b2b138499580c0b53e0167a955

### Bug description

When using the /tp or /teleport commands in game, the @p @e and @a vanilla options are unavailable.

### Steps to reproduce

Try to use the command /tp @p 0 100 0

### Expected behaviour

The closest player should be teleported to 0 100 0

### Actual behaviour

Error: Player not found

**Comment by osfanbuff63** [comment]
EssentialsX doesn't support these options. For `@a` you can use `/tp *`, but with the rest you have to use `/minecraft:tp` which is the vanilla command.

**Comment by Attack8** [comment]
Thank you!
