### ISSUE TITLE
spawn not working

### ISSUE THREAD

**Issue by WiZiSergio** [EssentialsX/Essentials#5099]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

/spawn

### Bug description

This command works only having op, serial range has it and it doesn't work

### Steps to reproduce

/spawn 

### Expected behaviour

/spawn 

### Actual behaviour

You do not have permission to use this command

**Comment by pop4959** [comment]
You need a permission plugin. Commands in Essentials including `/spawn` are not given by default.

Also, in the future, if you are reporting a bug please fill out the template in its entirety.
