### ISSUE TITLE
Kill Commands

### ISSUE THREAD

**Issue by Freddols** [EssentialsX/Essentials#510]
there is a wierd bug where if i use /butcher named it will kill all named entities, including NPC's from the plugin "Civilians2". Is ther a way to stop this? Also, it would be appreciated if i could somehow edit the commands that the plugin changes, and stuff because a lot of stuff that comes with this is just straight up annoying

**Comment by boredhero** [comment]
You /might/ want to let the dev team for civilians2 (are you sure you dont mean citizens 2?) about this issue as well as it could be on there end. I have noticed weird issues with that plugin myself with their npcs turning into named normal entities. Think it might be them, not essentials.

**Comment by drtshock** [comment]
Don't use butcher and have them override it.
