### ISSUE TITLE
Player Joins Causes Lag Spikes

### ISSUE THREAD

**Issue by Joshuak52** [EssentialsX/Essentials#5103]
### Type of bug

Performance issue or memory leak

### `/ess dump all` output

https://gyazo.com/e86a9ec7a2f7c1fc0982c0be08112001

### Bug description

TimingsV2: https://timings.aikar.co/dev/?id=59650ebe208c4401a316a31a1f24777d

Essentials::Task: com.earth2me.essentials.EssentialsPlayerListener$1DelayJoinTask (Single)

When a player joins the game, rather they're new or not this is causing lag spikes

### Steps to reproduce

PaperMC Version: Paper-138 1.19.2
EssentialsX Version: 2.19.8-dev+1-0897ef7

Steps to reproduce
 - have multiple worlds with multiverse
 - have essentials spawn
 - create a lobby world with multiverse and do /setspawn in lobby world

### Expected behaviour

This should not be causing any lag spikes

### Actual behaviour

This is causing lag spikes with high ticks

**Comment by JRoy** [comment]
Going to need a spark, /ess dump (make near the start of a server start). Also, group manager isn't supported.
