### ISSUE TITLE
/me appends player prefix and name 

### ISSUE THREAD

**Issue by Kyrobi** [EssentialsX/Essentials#5109]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=536b484f6dc54bf4878ec06d5e1b292a

### Bug description

When using Minecraft's default /me, the chat will show the name twice along with the prefix.

![image](https://user-images.githubusercontent.com/20980266/190902477-98e42dcd-095d-44b0-bad4-1f75586b798f.png)

This is what it looks like with just EssentialsX, EssentialsXChat, and Vault loaded

![image](https://user-images.githubusercontent.com/20980266/190902527-80538e3f-8171-44f8-8619-6152e74318e6.png)

### Steps to reproduce

1. Join a server
2. Have EssentialsX and EssentialsXChat installed
3. Do /me or /minecraft:me

### Expected behaviour

The chat should not show the player prefix and name again

### Actual behaviour

![image](https://user-images.githubusercontent.com/20980266/190902477-98e42dcd-095d-44b0-bad4-1f75586b798f.png)
![image](https://user-images.githubusercontent.com/20980266/190902527-80538e3f-8171-44f8-8619-6152e74318e6.png)

**Comment by Evidentsinger14** [comment]
Hey @Kyrobi, can you make sure this is still an ongoing issue? 
![image](https://github.com/EssentialsX/Essentials/assets/46200123/e7fee0ce-884d-4829-a3ed-3f9ad7980045)
I don't seem to have that happen with `/minecraft:me` or `/essentials:me`.

**Comment by Kyrobi** [comment]
@Evidentsinger14 This no longer seems to be an issue. Closing issue
