### ISSUE TITLE
SetExpFix for 1.7 versions?

### ISSUE THREAD

**Issue by stanleykerr** [EssentialsX/Essentials#511]
You have support added for 1.7 but you don't have the code for it in
Essentials/src/com/earth2me/essentials/craftbukkit/SetExpFix.java

**Comment by tavonkelly** [comment]
This commit breaks SetExpFix for 1.7 versions https://github.com/drtshock/Essentials/commit/3634cab1a5209bb621322be8a9e18aa4d531508c

**Comment by mdcfe** [comment]
1.7.10 is no longer supported.
