### ISSUE TITLE
Mangrove missing from /clear command

### ISSUE THREAD

**Issue by Cruwzky** [EssentialsX/Essentials#5111]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=5c060c2ba65c490f904d6d603e96a666

### Bug description

Mangrove items are missing in the /clear command.

Example "/clear playername mangrove_log 64" is not possible. It's the same with all mangrove related stuff. The command does nothing then run and the autocomplete does not recognize mangrove items.

### Steps to reproduce

/clear playername mangrove_log 64

### Expected behaviour

I would expect it to remove 64 mangrove logs from the choosen player.

### Actual behaviour

The command does nothing.

**Comment by pop4959** [comment]
Update Essentials, and if that still doesn't work delete the `items.json` file in the Essentials plugin folder to re-generate it.
