### ISSUE TITLE
/home bed is not affected by 'world-home-permissions'.

### ISSUE THREAD

**Issue by Pantera07** [EssentialsX/Essentials#5112]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=9f75d9204aa2491992ffe5fb62633cd9

### Bug description

`/home bed` is not affected by `world-home-permissions`.

### Steps to reproduce

1. Set `world-home-permissions: true`
2. Right click on the bed in the overworld
3. Type `/home bed` in the netherworld

----

1. Set `world-home-permissions: true`
2. Using the respawn anchor in the netherworld
3. Type `/home bed` in the overworld

### Expected behaviour

Players should not be able to teleport to another world using the `/home bed` command. (world-home-permissions: true)

### Actual behaviour

Players can teleport to another world using the `/home bed` command. (world-home-permissions: true)

**Comment by Evidentsinger14** [comment]
Unable to reproduce this behavior. 
setting respawn location in the overworld with a bed, going into nether and using `/home bed` gives me the message `Error: You do not have the essentials.worlds.world permission.` which is intended. 

Make sure you don't have a wildcard permission set somewhere, and try checking your op status to see if that may be bypassing the perm checks.
