### ISSUE TITLE
Getting kicked with "Illegal Characters in chat" when using a nick with &

### ISSUE THREAD

**Issue by Agaloth** [EssentialsX/Essentials#5119]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=218b2384b3f745e38f256dcfb8bfa4db

### Bug description

When a player is using colors in his nickname, the server kicks him.

Example: /nick &4Agaloth

### Steps to reproduce

1. Do /nick and use a color like this: /nick &4Agaloth

### Expected behaviour

The player should have a nickname with the color.

### Actual behaviour

The player gets kicked for "Illegal Characters in chat"

**Comment by Agaloth** [comment]
[12:31:47 INFO]: Agaloth issued server command: /nick &8test
[12:31:47 INFO]: Agaloth lost connection: Illegal characters in chat

I'm using [12:46:19 INFO]: Essentials version 2.20.0-dev+5-0ca58ce

**Comment by Chew** [comment]
I'm going to go out on a limb here and say it's either your server software or one of your 100+ plugins... please try disabling plugins until you cannot reproduce this. If you disable EVERY plugin besides Essentials and this still happens, try running Paper. If it STILL occurs, please let us know.
