### ISSUE TITLE
[1.8/1.9] Issue with [Buy] 64 Arrow Sign DELETING AN ENTIRE cube around it.

### ISSUE THREAD

**Issue by boredhero** [EssentialsX/Essentials#512]
So, basically I have this extremely weird glitch where when i make a sign that is

[Buy]
64
Arrow
(This happens with any price)

And buy from it, (and this issue seems to be only with ops), it deletes an entire cuboid area around the sign. extremely annoying bug. Not sure what causes it. There is no output to console when this happens so I have absolutely no idea what is going wrong...it seems like such a weird glitch.....

**Comment by drtshock** [comment]
Can you paste your server log when this happens with debug mode enabled in essentials

**Comment by lululombard** [comment]
Do you have VoxelSniper ? The arrow is the default brush tool.

**Comment by boredhero** [comment]
Yup

**Comment by lululombard** [comment]
Then there's your issue. Not Essentials, but VoxelSniper ;)
