### ISSUE TITLE
i cant do /nick with the rgb hexcode

### ISSUE THREAD

**Issue by AquaNot** [EssentialsX/Essentials#5124]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=0e798e68968745ab82d3aa17e166bf0d

### Bug description

![image](https://user-images.githubusercontent.com/82337681/194244488-a736be30-d894-4624-8960-d279b303e7a8.png)
that happens whenever i try to do /nick &#RRGGBB and then my ign idk why that happens but its kinda why is there like a fix for it? i'v tried getting help in the discord but i got banned cuz i forgot to turn off reply pings

### Steps to reproduce

type /nick &#RRGGBBAqua_Not and it wont work 

### Expected behaviour

It's supposed to make my ign become rgb

### Actual behaviour

i get an error message :(
![image](https://user-images.githubusercontent.com/82337681/194244859-8f1555f0-dea1-43f3-aac7-af7886961aeb.png)

**Comment by Evidentsinger14** [comment]
Negative. You got banned because you use cracked plugins. Make sure you have the permission to use rgb nicknames. You can find the permission list [here](https://essinfo.xeya.me/permissions.html)

**Comment by AquaNot** [comment]
bro how are cracked plugins bannable ;-;
