### ISSUE TITLE
Command Costs & Command Cooldown Bug

### ISSUE THREAD

**Issue by catches** [EssentialsX/Essentials#5128]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=493f13390021478dba6528f657f129fb

### Bug description

I don't know if this is a bug or intended behavior, but basically, I have command costs and cooldown set. If I don't have enough funds to buy the command, it instead activates the cooldown. What I want is if I don't have funds, it doesn't actually activate the command cooldown, instead, when I have funds, I use the command, then it activates the cooldown.

### Steps to reproduce

1. Set command cost and cooldown
2. Use command without funds

### Expected behaviour

Command cooldown activates after the player has purchased and used the command.

### Actual behaviour

Command cooldown activates when player types in the command.

**Comment by Evidentsinger14** [comment]
Unfortunately, this is exactly how that was intended to work. 
with the current setup, it's not possible to add this, but could be an enhancement for the future. the idea behind this feature is for stuff like /feed /heal /condense, etc. stuff that isn't *usually* cancellable.
