### ISSUE TITLE
/anvil not work on 1.8 spigot

### ISSUE THREAD

**Issue by rejomy** [EssentialsX/Essentials#5134]
### Type of bug

Compatibility issue

### `/ess dump all` output

--------

### Error log (if applicable)

-------

### Bug description

/anvil - not work on 1.8

### Steps to reproduce

1 /anvil
2 profit

### Expected behaviour

nope

### Actual behaviour

nope

**Comment by JRoy** [comment]
It's only supported on Paper 1.15+
