### ISSUE TITLE
Gradle building bug

### ISSUE THREAD

**Issue by Alugor** [EssentialsX/Essentials#5152]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

Didn't come to run the plugin

### Error log (if applicable)

https://gist.github.com/Alugor/d230e20c55bb93c3c1e1c7bb503fa5e4

### Bug description

When I try to build the project with gradlew build, an error is thrown.

This is probably because the gradle version does not support Java 19.
But it should be updated to the latest version

### Steps to reproduce

- Using Java(TM) SE Runtime Environment (build 19.0.1+10-21)
- Cloning the newest git repository
- Executing `gradlew build`

### Expected behaviour

The project should build

### Actual behaviour

It's not building

**Comment by Chew** [comment]
I don't believe gradle officially supports Java 19 yet, so I recommend (and would anyway) building with Java 17. You can do this in IntelliJ by downloading a Java 17 SDK and building with gradle through the IDE. Will see what maintainers have to say, though...
