### ISSUE TITLE
Vanilla Enchantments being removed?

### ISSUE THREAD

**Issue by claegneander** [EssentialsX/Essentials#5153]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

Using newest version and it doesn't exist?

### Bug description

Essentials is removing vanilla enchantments from items with custom enchantments on them.

### Steps to reproduce

Make a plugin with custom enchantments.
Everything works fine until click on the item in inventory.

### Expected behaviour

Didn't expect anything to happen to the item enchantments.

### Actual behaviour

Long story short, making custom enchantments using **NamedspacedKey.minecraft(key)** in another plugin. After several hours of annoyance, we determined that Essentials for some reason was removing the vanilla enchantments on the items with custom enchantments, but leaving the custom enchantments alone. We fixed this issue for now by changing the above line to **NamespacedKey.fromString(key).** Still, some very odd behavior. Not sure what it is that is updating the items like that.

**Comment by JRoy** [comment]
You're not using the latest version if you're unable to get a dump link.
