### ISSUE TITLE
EssentialsX Chat won't let Chat work

### ISSUE THREAD

**Issue by BlueMints000** [EssentialsX/Essentials#5156]
### Type of bug

Compatibility issue

### `/ess dump all` output

https://essentialsx.net/dump.html?id=c972d89746314e8c82899f410e6f8c06

### Bug description

When I type in the chat, nothing appears, and players can't chat with each other, When I removed EssentialsX Chat the problem went away. I checked to see if it was interfering with another plugin, I removed all of the plugins except EssentialsX, EssentialsX Spawn, and EssentialsX Chat, and it still didn't work. So for now I removed EssentialsX Chat entirely so that the chat works.

### Steps to reproduce

1. remove all plugins except EssentialsX Chat, EssentialsX Spawn, and EssentialsX
2. Check to see if the chat is working
3. If not just take out EssentialsX Chat

### Expected behaviour

I expect that typing in chat will work.

### Actual behaviour

When typing in chat and then pressing enter, no words appear

**Comment by BrandonT80** [comment]
Your dump doesnt even have Essentials Chat installed.
