### ISSUE TITLE
Suggestion: Regarding SocialSpy

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#516]
Hey guys, I was just wondering if it would be possible to implement a solution to my current problem. My problem being that the server I'm on has various staff ranks like many other servers, however we use a separate vanish plugin. So senior staff members can vanish without newer staff members knowing, but if a vanished senior staff member teleports to one of the new staff members, social spy kind of gives away that the senior staff are monitoring the new staff.

I was thinking a possible solution could involve checking the permission groups rank weight, then ignoring recipients of a lower weight? Even a in house solution like providing multiple tiers of permissions for social spy would alleviate the problem, as we could assign one node to new staff, then the next node to senior staff and, new staff wouldn't receive social spy events from senior staff. Maybe with a conditional check to see if the senior staff was visible? but not necessarily required. 

Hopefully I've communicated my problem effectively, however if it's unclear I can clarify. Also, If this isn't something you're willing to incorporate into Essentials I can fork the repo and, make the modifications myself. But I thought I would throw out this suggestion, so that I don't have to hack some code together to make it work.

**Comment by drtshock** [comment]
I don't see this happening.

**Comment by pop4959** [comment]
Yeah you might want to fork yourself, as this is not really something that belongs in Essentials. Way too complicated, and I don't think any other servers have your specific issue.
