### ISSUE TITLE
EssentialsX Discord and DeluxeChat compatibility issues

### ISSUE THREAD

**Issue by SemiMute** [EssentialsX/Essentials#5169]
### Type of bug

Compatibility issue

### `/ess dump all` output

https://essentialsx.net/dump.html?id=d7a971c0cb244d8ba14d0bf9d06c53bb

### Bug description

When using DeluxeChat, EssentialsX Discord does not detect/send any of the messages from players to discord

### Steps to reproduce

Use any version of DeluxeChat with EssentialsX Discord

### Expected behaviour

Ingame chat should be sending to discord

### Actual behaviour

Only achievements, login/logout events are showing in discord, no chat related behavior is showing

**Comment by Chew** [comment]
I'm not sure if this is an Essentials issue or DeluxeChat, either way, the plugin is abandoned, so I don't see much benefit looking into it if it's specific to this plugin.

**Comment by JRoy** [comment]
Closing as per Chew's comment
