### ISSUE TITLE
Issue with chat

### ISSUE THREAD

**Issue by TH3N3WN00B** [EssentialsX/Essentials#5178]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=58f937d2dde94935b5e0ed73a8ba4d33

### Error log (if applicable)

https://paste.gg/p/anonymous/add5e31ffe6b475dae7337798aa1ff6e

### Bug description

Every time I write something in chat that error appears, and if I add a plugin that works with chat (interactivechat / interactivechat discordsrv addon) if I type something in chat all the other players get kicked out

### Steps to reproduce

This was done runing purpur and ''bee'' one if its forks
1.- install essentials latest dev or latest ''stable''
2.- install plugins mentioned above
3.- type in chat

### Expected behaviour

Dont kick anyone from the server

### Actual behaviour

Kicked players from server

**Comment by Evidentsinger14** [comment]
> format: '<%luckperms_prefix% %essentials_nickname%> {MESSAGE}'

EssentialsX Chat does not support PlaceholderAPI in its current state. Please use the supported internal placeholders. You can find a list of these right above the format section in the config.yml

**Comment by TH3N3WN00B** [comment]
> > format: '<%luckperms_prefix% %essentials_nickname%> {MESSAGE}'
> 
> EssentialsX Chat does not support PlaceholderAPI in its current state. Please use the supported internal placeholders. You can find a list of these right above the format section in the config.yml

Well, that worked... thanks for the help
