### ISSUE TITLE
[Essentials] You are running an unsupported server version!

### ISSUE THREAD

**Issue by user4302** [EssentialsX/Essentials#5180]
### Type of bug

Compatibility issue

### `/ess dump all` output

https://essentialsx.net/dump.html?id=80c09c244f6a42e4a1eff027b5ddf45d

### Error log (if applicable)

https://gist.github.com/user4302/45c6fab7dc1612da7757444ffb4e25e1

### Bug description

i first changed my launch string from this 
`java -Xmx20G -Xms1G -jar paper-1.19.2-220.jar nogui`

to the one here:
https://docs.papermc.io/paper/aikars-flags
`java -Xms15G -Xmx15G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=20 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Xlog:gc*:logs/gc.log:time,uptime:filecount=5,filesize=1M -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar paper-1.19.2-296.jar --nogui`

i then saw that i was 2 essentialsX dev builds behind, so i updated essentialsX, essentialsSpawn and essentialsChat
then i ran the command again and saw the error, 
i didnt launch the game and join the server yet, im assuming this is safe to ignore, but it says 'Error' so im not sure.

tested the previous launch string and i get the same error.

### Steps to reproduce

1. run java -Xmx20G -Xms1G -jar paper-1.19.2-220.jar nogui
2. see the error in the logs

### Expected behaviour

essentials should activate and run without an error

### Actual behaviour

i get the following error when essentials activates: '[Essentials] You are running an unsupported server version!'

**Comment by mdcfe** [comment]
The latest builds target 1.19.3. You can still use the current builds on 1.19.2 for now, but future dev builds may break on 1.19.2.

**Comment by user4302** [comment]
> The latest builds target 1.19.3. You can still use the current builds on 1.19.2 for now, but future dev builds may break on 1.19.2.

ohhhhhh.
ok so ill have to either roll back to the previous dev build, or use the latest stable build for 1.19.2 then.
thank youu.

**Comment by mdcfe** [comment]
No:

> You can still use the **current builds** on 1.19.2 **for now**

The latest dev build as of writing still works on 1.19.2. The warning exists to let you know that things may break in future dev builds, and that you should consider updating to 1.19.3 in the future.
