### ISSUE TITLE
Error on shutdown 1.19.3

### ISSUE THREAD

**Issue by MetallicGoat** [EssentialsX/Essentials#5181]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=a9e6f5e6d12f4adda2a3119c9cb5f53b

### Error log (if applicable)

https://gist.github.com/MetallicGoat/dfa19b8c7fcf2ae9d3765fefd846d4b1

### Bug description

IllegalStateException error when server is shutting down on 1.19.3. Tested this with the latest dev build where I saw some NMS was updated. Hope this helps you

### Steps to reproduce

1. Shutdown server on 1.19.3 (Spigot)

### Expected behaviour

Everything should NOT explode

### Actual behaviour

Everything explodes, jk, just console error

**Comment by JRoy** [comment]
Likely that you/something modified the jar file while your server was running.
