### ISSUE TITLE
1.19.3 Spawner /give broken

### ISSUE THREAD

**Issue by timr2000** [EssentialsX/Essentials#5189]
### Type of bug

Compatibility issue

### `/ess dump all` output

Not working

### Error log (if applicable)

https://i.imgur.com/dcJUpqo.png

### Bug description

When using the command /give timr2000 cow_spawner (Doesn't matter which mob type) It throws out an error, and won't give the spawner.

### Steps to reproduce

1. use /give <playername> cow_spawner
2. Throw out the error

### Expected behaviour

It should give you the spawner

### Actual behaviour

Throws out an error

**Comment by Evidentsinger14** [comment]
Please send your `/logs/latest.log` including the error you received.

**Comment by timr2000** [comment]
> Please send your `/logs/latest.log` including the error you received.

https://pastebin.com/VEP4LxSD
[latest (2).log](https://github.com/EssentialsX/Essentials/files/10229636/latest.2.log)

**Comment by timr2000** [comment]
it looks like the latest paper/purpur build solved this problem
