### ISSUE TITLE
Duplicate playerdata

### ISSUE THREAD

**Issue by icansc187** [EssentialsX/Essentials#5193]
### Type of bug

Error in console

### `/ess dump all` output

*

### Error log (if applicable)

https://mclo.gs/jVwtigt

### Bug description

 [Essentials] Found UUID 00000000-0000-0000-0009-01f6b16a138c for player Dylannery, but player already has a UUID (c3e5ce7e-73f4-3442-bbeb-66e45e0c0fd7). Not replacing UUID in usermap.
java.lang.RuntimeException: null

### Steps to reproduce

*

### Expected behaviour

*

### Actual behaviour

*

**Comment by Evidentsinger14** [comment]
One is a bedrock UUID, the other is an offline mode Java Edition UUID. Use Floodgate configured properly to have a username prefix
