### ISSUE TITLE
rockets not working with fireworks

### ISSUE THREAD

**Issue by NBS-Paste** [EssentialsX/Essentials#5204]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=4e24c37ecc224cf6bd4789a743cc95d3

### Bug description

wont let me fly my elytra comboed with firework rockets

### Steps to reproduce

try and fly with rockets and elytra

### Expected behaviour

should fly with rockets

### Actual behaviour

doesnt fly with rockets

**Comment by JRoy** [comment]
Unable to reproduce
