### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by icansc187** [EssentialsX/Essentials#5206]
### Type of bug

Error in console

### `/ess dump all` output

*

### Error log (if applicable)

https://paste.gg/p/anonymous/61615c3ecd5d4b4a9449eefb4e6fb8c4

### Bug description

after click npc / citizen

### Steps to reproduce

*

### Expected behaviour

*

### Actual behaviour

*

**Comment by Lunna5** [comment]
Please, fill all the gaps

**Comment by Chew** [comment]
1) This is just a debug message, you can ignore it.
2) Not a bug
3) Fill out the template
4) Use `/ess dump all` when we request it, or everything else is irrelevant.
