### ISSUE TITLE
/tpa payment is broken

### ISSUE THREAD

**Issue by StKillReal** [EssentialsX/Essentials#5211]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=e407eca5aa01408e9e6d021e0186ff2a

### Bug description

if u want set cost for home, spawn or warp teleportation all works fine, but not for /tpa, because it takes money before teleporting.

### Steps to reproduce

1. Set cost for /tpa command
2. Use /tpa <nickname of other player>
3. Move, or player decline your request
You spent your money without teleportation

### Expected behaviour

You pay money for teleport like for /home /spawn and /warp, but not for using command, because /tpa is the similar teleport like commands I've writed before

### Actual behaviour

You spend money without even teleportation

**Comment by Evidentsinger14** [comment]
This does work as the feature intended, and would be better suited for an enhancement issue to add a way to ensure the teleport was completed as stated in #5556
