### ISSUE TITLE
kit equipe armor 1.19.3 bug

### ISSUE THREAD

**Issue by thiagogebrimm** [EssentialsX/Essentials#5214]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=e8d36b3ef6bb40578546e2899469f6d9

### Bug description

When using "kit-auto-equip" as true, kits do not deliver armor

### Steps to reproduce

1. Use /kit with spaces to wear armor

### Expected behaviour

deliver the armor to the player and equip it

### Actual behaviour

the kit does not deliver the armor that is to be worn

**Comment by JRoy** [comment]
Unable to reproduce, also you don't have kits with actual armor in them.
