### ISSUE TITLE
currency-symbol-suffix breaks trade signs

### ISSUE THREAD

**Issue by JareCoder** [EssentialsX/Essentials#5226]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

Latest paper 1.19.3 with Essentials LTS (2.19.7):
https://essentialsx.net/dump.html?id=f948500db7db4d1292648e87ebea2da6

Latest paper 1.19.3 with Essentials dev (2.20.0):
https://essentialsx.net/dump.html?id=8e31b9e5143b416a86ff389f00bd3bdc

### Bug description

When setting currency-symbol-suffix to true in the "Economy" section in config, the trade sign doesn't store money. You can restock and buy from the sign, but the owner can't collect anything, since "There is nothing to collect".

### Steps to reproduce

1. Set currency-symbol-suffix to true in config.
2. Make a [Trade] sign and stock it.
3. Use another player to buy from created sign.
4. Observe that buyer gets money taken from their account and they receive stocked items, but 2nd line stays at XX€:0.
5. Try to collect money.
6. Get error that you have nothing to collect.

If it matters, the currency-symbol is set to '€' and currency-symbol-format-locale to de-DE.

### Expected behaviour

Money would be stored in the sign and you could collect it.

### Actual behaviour

2nd line on sign stays at XX€:0 and doesn't store any money when currency-symbol-suffix is set to true.

**Comment by JareCoder** [comment]
As a workaround I changed the messages_en.properties file to flip the currency amount and suffix order and left currency-symbol-suffix as false. This makes the chat and commands display the currency symbol at the correct place, but doesn't fix signs for obvious reasons.

**Comment by Evidentsinger14** [comment]
Please provide a full dump (`/ess dump all`) like the issue template asked - it provides information such as server version, essentials version(s), and logs for any errors that may occur to help with triage and fixing.

**Comment by JareCoder** [comment]
I was unable to dump on the live server so I created a local test server and copied configs. Dumps edited to issue.

Same issue on both LTS and dev versions. If I recall correctly I had this exact problem last summer, but didn't have time to troubleshoot it back then.
