### ISSUE TITLE
Cannout use /mail sendall

### ISSUE THREAD

**Issue by lostdusty** [EssentialsX/Essentials#5227]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=96e30d26eae646caa94a140ef7d837e6

### Error log (if applicable)

https://hastebin.com/acenafopik.properties

### Bug description

Cannot use /mail sendall and /mail sendtempall, both give the same error. Regular /mail send works fine.

If needed, I'm running:

`/ver`:
```
[Mon 19:35:00 INFO ] Current: git-Purpur-1894 (MC: 1.19.3)*
Previous: git-Purpur-1892 (MC: 1.19.3)
* You are running the latest version
```

`/pl`:
```
[Mon 19:35:58 INFO ] Plugins (29): AuthMe, Citizens, DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, ExoticGarden, ExtraGear, ExtraTools, floodgate, Geyser-Spigot, GriefDefender, GSit, HolographicDisplays, LiteXpansion, LuckPerms, LumberJack, LWC, LWCTrust, NoChatReports, ProtocolLib, SFCalc, SkinsRestorer, Slimefun, SlimefunLuckyBlocks, spark, Vault, WorldEdit, WorldGuard
```

### Steps to reproduce

1. Try sending a mail to everyone using /mail sendall.

### Expected behaviour

Mail should be sent to everyone.

### Actual behaviour

Mail isn't sent.

**Comment by Zaphara94** [comment]
I can confirm this issue on our server as well. You can send mail to one person at a time no problem, but even by console you can't send mail to everyone using /mail sendall without getting this: https://pastebin.com/U9tsrzXz

**Comment by SiuanSong** [comment]
I have the same exact issue
