### ISSUE TITLE
kit-auto-equip doesn't equip armor when serialized

### ISSUE THREAD

**Issue by Evidentsinger14** [EssentialsX/Essentials#5232]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=41d43eafde474485b8af70d2f48d8644

### Error log (if applicable)

No Errors

### Bug description

When claiming a kit that's been serialized, it no longer equips the armor. This was a previous issue, and had been fixed [here](https://github.com/EssentialsX/Essentials/pull/4491). 

### Steps to reproduce

1. Create fresh server running latest development build of EssentialsX (2.20 build 39), and Paper (1.19 build 388)
2. start server to generate configs
3. open `/plugins/EssentialsX/config.yml` and Locate `use-nbt-serialization-in-createkit`, and set to `true`
4. Locate `kit-auto-equip` and set to `true`
5. restart or `/ess reload`
6. get some armor, and a random item just to ensure the kit is actually given
7. run `/createkit JackG 0` 
8. try and claim `/kit JackG` 

### Expected behaviour

Random item is placed into inventory, and armor is equipped to armor slots. 

### Actual behaviour

Only the random item is placed, no armor is equipped.

**Comment by JRoy** [comment]
Fixed in Paper #384

**Comment by JRoy** [comment]
Fixed in Paper build 384 https://github.com/PaperMC/Paper/commit/18fabc08d52ecbddd993d17fb06c51db27941014
