### ISSUE TITLE
vanish kick

### ISSUE THREAD

**Issue by BranTheOtter** [EssentialsX/Essentials#5235]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://i.gyazo.com/073dc777f5ed1e58955285017351da45.png

### Bug description

When someone is OP and goes Vanish and then they type something in chat, It kicks all players from them the server

### Steps to reproduce

1. Go into Vanish
2. Type anything in chat
3. Kicks all players who are not opped in chat

### Expected behaviour

Should be able to type in chat while vanished

### Actual behaviour

Kicks everyone in server

**Comment by Evidentsinger14** [comment]
Duplicate of #5201
