### ISSUE TITLE
ConcurrentModificationException intermittently occurring on logout

### ISSUE THREAD

**Issue by HackuJacku** [EssentialsX/Essentials#5241]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=610057a115e9404aac1044b666ce306c

### Error log (if applicable)

https://pastebin.com/raw/yz76PZ10

### Bug description

Sometimes when a player logs out, a ConcurrentModificationException error occurs

### Steps to reproduce

1. Player logs out
2. Error can happen randomly

### Expected behaviour

The ConcurrentModificationException does not occur

### Actual behaviour

The ConcurrentModificationException can occur

**Comment by pop4959** [comment]
Please do not report bugs unless you are using a supported server setup (CraftBukkit, Spigot, Paper, etc).
