### ISSUE TITLE
Can't overwrite warps using /setwarp

### ISSUE THREAD

**Issue by RavenNevah** [EssentialsX/Essentials#5245]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=848b3b5aa406477bb252f0a7b71e7604

### Bug description

When trying to overwrite warp using /setwarp command I get an error: "You cannot overwrite that warp". I made sure all warp permissions are added to config.yml, yet I cannot overwrite warps. Creating new warps and deleting them works though.

### Steps to reproduce

1. Run `/setwarp test` command
2. Run `/setwarp test` again to overwrite warp coordinates

### Expected behaviour

Chat message:

> Warp test set.

### Actual behaviour

Chat message: 

> Error: You cannot overwrite that warp.

**Comment by RavenNevah** [comment]
enabled player-commands:

![image](https://user-images.githubusercontent.com/60316656/217675672-16b16f6d-abca-4e4e-9d0f-1ad97193487f.png)

`per-warp-permission: false`

**Comment by Chew** [comment]
It looks like you need to give them `essentials.warp.overwrite.{warp name}` individually, there doesn't seem to be a wildcard here.

**Comment by RavenNevah** [comment]
Adding them one by one works so thanks for that. Shouldn't the wildcard option work though? It's listed on [permissions list](https://essinfo.xeya.me/permissions.html) that's linked on EssentailsX wiki. Was it removed?

**Comment by JRoy** [comment]
Please use a supported permissions plugin (LuckPerms) and Vault.
