### ISSUE TITLE
Essentials out of memory

### ISSUE THREAD

**Issue by Sloterr** [EssentialsX/Essentials#5246]
### Type of bug

Performance issue or memory leak

### `/ess dump all` output

https://essentialsx.net/dump.html?id=4e347c723c6f4164bdb2a8563dcb4769

### Bug description

Hi, I have a problem and idk how to fix it or what is causing that problem, I have one skyblock server with 12GB of ram
the skyblock has good and well-known plugins (a total of 58 plugins) but the server runs out of memory fast for no reason,
I run some tests to see what is the problem here and I found out that when I remove essentials from the server all the problems
goes away the server sits on average 3GB of ram with only one player online (and before deleting essentials it runs out of memory with only one player).

So yes i want to know where is the problem but i can't find it.

Latest spark results: https://spark.lucko.me/eJY1sEl2KD

Oh and i have tested dev build and stable and i get the same results.

### Steps to reproduce

I just run around the spawn or at my island and play regularly and the ram goes up and up
until the ram is full.

### Expected behaviour

I expect the ram not to fill up so much and so quickly for no reason.

### Actual behaviour

I explain everything above <3

**Comment by pop4959** [comment]
"This happens with Essentials installed" is not conclusive evidence enough to make a memory leak issue.

For memory leak issues, you **must** additionally include a heap dump (if you want, you can send this privately to an Essentials member on Discord). It also helps if you can tell us what exactly you think is causing a leak in Essentials.

Before you do, I highly suspect this is not an actual memory leak. You have 2GB allocated to your server, which is barely enough for a small vanilla Minecraft server these days. I would suggest increasing to at least 4GB, or more, before you waste any time investigating for leaks.

**Comment by Sloterr** [comment]
How can I provide a heap dump and where I need to send this too??

**Comment by Sloterr** [comment]
I set 4GB to the allocated ram and it's now stable at 4.5GB but still, It goes up!!

My other server has 6GB of ram uses the same essentials version and has 75 plugins, I'm running
5 players online and it uses only 4.5 to 5 GB of ram.

**Comment by Sloterr** [comment]
Now it uses 6GB and im the only one on the server!

**Comment by pop4959** [comment]
For the most part nothing you're saying sounds like a memory leak. I would recommend looking up how garbage collection in Java works, as that is very relevant to how your server is using memory. Do your own research, please.

Again, this doesn't sound like an Essentials issue. Please talk to your host or find a proper avenue to discuss this (e.g. Paper Discord, etc). This issue will be re-opened only if you can provide proof or evidence of a real memory leak in Essentials.
