### ISSUE TITLE
In nether or end, cannot /home back to a home in the overworld at cloudlevel or above.

### ISSUE THREAD

**Issue by amazingsoapx** [EssentialsX/Essentials#5249]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=f11a15b334cd4258b1c20a4928302d43

### Bug description

In nether or end, cannot /home back to a home in the overworld at cloudlevel or above.

In the overworld, you are able to /home to a home at any height level.

### Steps to reproduce

set a /home at cloud level in the overworld.
go to the nether and then try to /home.
happens to all users no matter the permission, including myself OP.

### Expected behaviour

you should be able to teleport home.

### Actual behaviour

language pops up in chat "teleporting to home" but nothing happens. no errors in console either.

**Comment by Evidentsinger14** [comment]
@amazingsoapx can you reproduce this on a server only using EssentialsX, and supported plugins? (Vault, LuckPerms, and Official EssentialsX addons). i'm unable to reproduce this, even with your config.

**Comment by amazingsoapx** [comment]
i don't have a spot where i can test on an additional server. i do have vault, essx, essx protect, essx antibuild, essx spawn, and groupmanager.

edit: i also have multiverse. don't know if it could be this.

**Comment by Evidentsinger14** [comment]
> don't know if it could be this.

that's why i'm asking if you're able to reproduce with **only** supported plugins. 
> i don't have a spot where i can test on an additional server

If you get ahold of me on discord (Evident#0420), i can give you access to a server if you'd be able to assist with triage on this.

**Comment by Evidentsinger14** [comment]
![CF8A0C12-A65D-4F06-9FEC-F3A056F39A18](https://user-images.githubusercontent.com/46200123/218983791-02103234-e1d2-4bfc-8e1a-aa3eecb8df78.jpeg)
