### ISSUE TITLE
Issue updating player prefixes, name colors and suffixes

### ISSUE THREAD

**Issue by TinyMandalorian** [EssentialsX/Essentials#5257]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=9acb2dab51ad4b94a801484a9b440927

### Bug description

When updating player's prefixes, name color or suffix it does not update until you type twice in the chat.

Ive already tried disabling all other plugins talked a bit about this in the luckperms discord and they told me to go to essentialsx after deciphering that it was not luckperms because luckperms is detecting the change to the prefix/suffix.

Ive tried switching essentialsx versions as well ive switched from latest dev build to latest non-dev build but to no avail.
im running 1.19.3

Image Example of bug:

![image](https://user-images.githubusercontent.com/67829574/221331661-6b041561-75b2-4eeb-87fa-2a3f2fe2383a.png)

### Steps to reproduce

Download these plugins

Vault
Luckperms
EssentialsX
EssentialsX Spawn
EssentialsX Chat

OP yourself and type in the chat twice.
or
Use luckperms and assign the default group with a prefix and type in the chat twice.

-SEE BELOW-

![image (1)](https://user-images.githubusercontent.com/67829574/221331565-da7025bf-3181-4f3a-961a-33f6a3642c57.png)
![image (2)](https://user-images.githubusercontent.com/67829574/221331567-937af682-8a86-4d30-8978-7c2782f21b26.png)
![image](https://user-images.githubusercontent.com/67829574/221331568-06d5139c-83cc-42a8-8ec2-1699f88160a3.png)

### Expected behaviour

Chat should update the player's prefix, name color and suffix

### Actual behaviour

changing the player's prefix, name color and suffix but it still takes an additional chat message for chat to reflect that change.
EXAMPLES:

![image](https://user-images.githubusercontent.com/67829574/221331431-59dc6c85-69e7-4cff-b454-c9e1a4f1335a.png)
![image (1)](https://user-images.githubusercontent.com/67829574/221331429-8881518d-8db9-412c-a432-b97fff3f264e.png)
![image (2)](https://user-images.githubusercontent.com/67829574/221331430-52067cfe-7796-4d50-bbfa-4e8be9336305.png)

**Comment by TheCyberQuake** [comment]
That looks more like a luckperms issue not an essentials issue since luckperms itself is showing that it is collecting "ee" as the prefix, and it is what is managing your prefixes not essentials

**Comment by dandud100** [comment]
I got the exact same issue! Also the tablist does only update if you write in chat once. Seems that the update check fires after the message was already sent and not before.

**Comment by mdcfe** [comment]
Hey @Gavins38 and @dandud100, would you be able to test the latest dev build? We've just reverted some chat changes for 1.19.4 which could fix the issue. (You can install the dev build on 1.19.3 just fine - ignore the unsupported version messages.)

**Comment by dandud100** [comment]
Hey @mdcfe I can try the dev tomorrow, do I need to replace every module or just Essentialsx Chat? Also are my configs safe or could something gets corrupt?

**Comment by mdcfe** [comment]
> Hey @mdcfe I can try the dev tomorrow, do I need to replace every module or just Essentialsx Chat? Also are my configs safe or could something gets corrupt?

Always update all jars at the same time. If you're on a 2.20 dev build then your data will be safe. If you're on a 2.19.x version you should back up the `Essentials` beforehand, as your data will be upgraded by the dev build.

**Comment by dandud100** [comment]
> > Hey @mdcfe I can try the dev tomorrow, do I need to replace every module or just Essentialsx Chat? Also are my configs safe or could something gets corrupt?
> 
> Always update all jars at the same time. If you're on a 2.20 dev build then your data will be safe. If you're on a 2.19.x version you should back up the `Essentials` beforehand, as your data will be upgraded by the dev build.

So i now installed the dev build and the chat issue is fixed! One thing i noticed is just, that tablist still only gets updated after a player send a message in chat.
