### ISSUE TITLE
Run into error when using a banner meta

### ISSUE THREAD

**Issue by saeziae** [EssentialsX/Essentials#5264]
### Type of bug

Compatibility issue, Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=739e7bb577b54e00bc610dc53f693626

### Bug description

Run into error when resembling the BannerMeta from website <https://essentialsx.net/wiki/BannerMeta.html>

### Steps to reproduce

add an item `- pink_banner 1 SQUARE_TOP_RIGHT:14188339` to kits, then `/kit <the_kit>` in game.

### Expected behaviour

Getting the banner with specific pattern.

### Actual behaviour

in game it says: `kit improperly defined`
in log it say: `Cannot invoke "org.bukkit.DyeColor.getWoolData()" because the return value of "org.bukkit.block.banner.Pattern.getColor()" is null`

**Comment by JRoy** [comment]
You're using an outdated version of EssentialsX. Also, we recommend using [Paper](https://papermc.io)
