### ISSUE TITLE
Error from the Nukkit engine

### ISSUE THREAD

**Issue by TechAdrianPro** [EssentialsX/Essentials#5266]
### Type of bug

Error in console

### `/ess dump all` output

I can't enter it because the server can't start

### Error log (if applicable)

https://paste.gg/p/anonymous/14e1e0ee71044b1a95eb0728c4422645

### Bug description

When you type /reload and start the server and you get a crash , this crash is on a Nukkit server

### Steps to reproduce

1.Włacz server
2.Poczekaj aż załaduje plugin

### Expected behaviour

Activating the plugin without errors

### Actual behaviour

There is a big server crash and the server shuts down

**Comment by Chew** [comment]
Isn't Nukkit a Bedrock server type..? This is for Java, not Bedrock.

Also, don't `/reload`

**Comment by TechAdrianPro** [comment]
Yes

**Comment by TechAdrianPro** [comment]
Czemu zamknięcie

**Comment by Evidentsinger14** [comment]
@TechAdrianPro EssentialsX is a Bukkit plugin, not related to Nukkit.
