### ISSUE TITLE
Console spam offline player 

### ISSUE THREAD

**Issue by SladeHazard** [EssentialsX/Essentials#5272]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

N/A

### Error log (if applicable)

N/A

### Bug description

i created a lot of offline uuids a while ago
and everytime I restart my server, essentials spams my console with this:

![image](https://user-images.githubusercontent.com/45261094/225431702-1432e894-0a20-4ab7-b9d2-a58f81a3112c.png)

how can I disable it?

### Steps to reproduce

generating uuids through a plugin

### Expected behaviour

not to spam console

### Actual behaviour

spams console

**Comment by JRoy** [comment]
The dump url is not optional, please file another issue filling out the template properly.
