### ISSUE TITLE
CombinedCalculator may cause performance issues

### ISSUE THREAD

**Issue by KioProject123** [EssentialsX/Essentials#5278]
### Type of bug

Performance issue or memory leak

### `/ess dump all` output

https://essentialsx.net/dump.html?id=608120f5f89a42159710cc53049226d7

### Bug description

CombinedCalculator seems to be causing heavy calculations.
I don't know if this is normal, just reporting here in case it's a real problem.

![image](https://user-images.githubusercontent.com/61594596/226964130-a18dda9d-a94b-49dd-9bbd-d9cd29bfccd1.png)
Spark link: https://spark.lucko.me/kuZvSQ1cMT

### Steps to reproduce

Running the server normally, using spark detection

### Expected behaviour

CombinedCalculator does not cause heavy calculations

### Actual behaviour

CombinedCalculator seems to be causing heavy calculations.

**Comment by JRoy** [comment]
Less than half a percent of the server tick, not an issue.
