### ISSUE TITLE
Command on link with essentialsX discord link.

### ISSUE THREAD

**Issue by mrdiploben** [EssentialsX/Essentials#5279]
### Feature description

When you link with essentialsX discord, it can fire a command in the server set in the config.

### How the feature is useful

It allows for more possibilities with the EssentialsX Discord Link. This could allow for kit giving etc without the use of the player having to manually do the command.

**Comment by JRoy** [comment]
The `DiscordLinkStatusChangeEvent` event is fired when a player is linked/unlinked. A separate plugin or even Skript tbh could do what you're asking.
