### ISSUE TITLE
EssentialsX chat

### ISSUE THREAD

**Issue by JJ21112** [EssentialsX/Essentials#528]
All the info is here https://www.spigotmc.org/threads/problem-with-essentials-chat.134319/ I would apprechiate it if you would take 2mins to have a look and see if you can see the problem thanks!

**Comment by drtshock** [comment]
Please put info in the ticket here.

**Comment by JJ21112** [comment]
So I have a server that uses Group Manager and Essentials and there both great. But recently I have wanted to add sub prefixes and suffixes so I tried to add them and they don't work.
I did /manuaddv jdf_ suffix &0[&eMLG&0] and /mangaddv owner suffix &0[&eMLG&0]
I was hoping someone could help me out and I keep my essentials chat format because I really don't want to lose it thanks. I'm not sure if this is to do with essentials format or because I change the groups in the folder called 'world' I really don't know anyways I would appreciate some help!

Essentials config of chat formats:
http://prntscr.com/ajwwkf
GroupManager config of owner:
http://prntscr.com/ajwvdx
In-Game example after I added the suffix:
http://prntscr.com/ajwxs4

**Comment by JJ21112** [comment]
So I just want to know how to add prefixes/suffixes keeping my formats in essentialsX

**Comment by drtshock** [comment]
Groupmanager isn't supported.

**Comment by JJ21112** [comment]
ok
