### ISSUE TITLE
No change (minus) balance 

### ISSUE THREAD

**Issue by arxivi** [EssentialsX/Essentials#5280]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=4849f8813878427fa12a0cd3fe91cf42

### Bug description

I use LNVault https://lnvault.github.io/lnvault/ This plugin works correctly (only two commands output and top up). When the output plugin works, but the game does not minus in-game currency (before the update (I missed which one) it worked. Replenish itself works. Tell me please, you have not changed this basis? Or how to fix it? I just can't figure out what's wrong.

Yes, of course you can write "ask that guy. But there is no connection to him. And this plugin depends on your...

### Steps to reproduce

After all the settings, I press the command

1. I spelled /lnwithdraw <amount>
2. Scanning QR.
3. The amount comes to a real balance, but in the game does not change. 

### Expected behaviour

When the balance should be deducted depending on how many people withdraw. In previous versions of your plugin this worked. 

### Actual behaviour

Balance withdraws, but is not fixed in the game.

**Comment by mdcfe** [comment]
It's possible there was a regression in EssentialsX, but this seems unlikely. I would recommend contacting the LnVault developer.

Can you please let us know which previous versions of EssentialsX worked? Without this it's difficult for us to tell which EssentialsX changes might have caused this issue.
