### ISSUE TITLE
EssentialsChat fix ! format

### ISSUE THREAD

**Issue by rejomy** [EssentialsX/Essentials#5283]
Please add the ability to customize the [Local] and [Global] inscriptions in the config.

- Now to the problem. When a player writes ! message, the plugin displays this message with 2 indents, I suggest to fix it. This is ugly and interferes, I want to enter !message and ! message, there is no difference. Not two spaces instead of one.

**Comment by JRoy** [comment]
`chatTypeLocal` and `shoutFormat` in the `message.properties` can be changed

**Comment by rejomy** [comment]
> 

Do you even read what I write?
If I do as you write, then at !message, it will display
[Shout]Message and I want ! message and !message to have 1 space. ONE FUCKING SPACE!

**Comment by rejomy** [comment]
> `chatTypeLocal` и в можно изменить`shoutFormat``message.properties`

.
