### ISSUE TITLE
Console spams offline players

### ISSUE THREAD

**Issue by SladeHazard** [EssentialsX/Essentials#5285]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=120e5733870a4ca19012ce2063105b83

### Error log (if applicable)

https://essentialsx.net/dump.html?id=120e5733870a4ca19012ce2063105b83

### Bug description

i created a lot of offline uuids a while ago
and everytime I restart my server, essentials spams my console with this:

![image](https://user-images.githubusercontent.com/45261094/227721903-aa3c652a-ff6f-49bc-bbfc-fd94f9c1eb49.png)

how can I disable it?

### Steps to reproduce

start server

### Expected behaviour

not to spam console

### Actual behaviour

spams console

**Comment by pop4959** [comment]
You can disable the spam with `-Dnet.essentialsx.usermap.max-warns=0`.

If you still have problems with users being created for offline players on the latest version, which is not self inflicted, please open a new issue and provide steps to replicate.
