### ISSUE TITLE
/tpr aliases and command in the console.

### ISSUE THREAD

**Issue by rejomy** [EssentialsX/Essentials#5286]
### Feature description

Add aliases to /tpr - /rtp /randomtp /tprandom
And add to the config world in which the supposed team will attack, more add a world limit (ie from -10000 to 10000, etc) And then it will attack in the hole itself (not cool).

Add a command on behalf of the console, ie /tpr player (world, if not specified, then keep in the current), and the player will warm, as if he himself had entered a command.

### How the feature is useful

-

**Comment by pop4959** [comment]
Already planned as part of #4271
