### ISSUE TITLE
essentials.nick.changecolors

### ISSUE THREAD

**Issue by Gardiac** [EssentialsX/Essentials#529]
Dude Ive read the wiki oh god , they cant change their name they got essentials.nick.changecolors & essentials.nick (I put Essentials's data to EssentialsX, Im not sure thats the problem)
Lets say my ign is Okay
I got both permission.
Even if I just type /nick &6Okay it wont work

**Comment by drtshock** [comment]
which version are you on?

**Comment by Gardiac** [comment]
1.7.10 spigot

**Comment by drtshock** [comment]
which version of essx

**Comment by Gardiac** [comment]
latest

**Comment by drtshock** [comment]
pretty sure that's not a version

**Comment by PetKCH** [comment]
I am having issue with this permission too, if I give it, only that perm, directly, players can't use it, if I give basic nick perm, then they can completely rename themselves as usual

I am on latest devbuild from 4 days ago I believe

**Comment by drtshock** [comment]
please be specific on version numbers and read the wiki.

**Comment by CoolLord22** [comment]
I know this is kind of old, but I had the same issue. To fix it, you also need to give essentials.nick (base) permission so they can run./nick in the first place
