### ISSUE TITLE
Players not recieving messages from Discord channel 

### ISSUE THREAD

**Issue by flleeppyy** [EssentialsX/Essentials#5294]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=ba883b8f7bbd4379ac13d1a5caaa28b8

### Bug description

When I type in the primary Discord channel, no messages are sent to the MC server, no players can see the messages. But vice versa does work. I can see everything happening in the MC server show up fine in the Discord channel.

I'm pretty sure I have everything in my config set correctly, the players have the receive permission.

### Steps to reproduce

- Setup config
- Talk in discord channel
- See no message in game

### Expected behaviour

I should be able to see messages from the primary channel show up in game.

### Actual behaviour

No messages from the discord channel show up in game

**Comment by wetzel-cam** [comment]
Seeing similar issue

[/ess dump all output](https://essentialsx.net/dump.html?id=06dd28bdf2674c9b84ffbe6b11079d6b)

Also tried on version 2.19.6 with no change.

Edit: Running with no perms/allow all to see messages in chat set to true in config.

**Comment by wetzel-cam** [comment]
Follow up after some testing and exploring:

My best guess is that Discord API updates and EssentialsXDiscord still relying on 4.4.0 of JDA may have ended up "breaking" the functionality.
When running a test server, the content section of the message is blank from initial receive. My guess is [this](https://discord.com/developers/docs/change-log#message-content-is-a-privileged-intent) change is what may have broken it, but I can't really confirm that, and based on what I've seen and read it should still be working fine... Although since I don't see a lot of reports or complaints of it being broken, it may be very recent? Or not many people use that module.

**Comment by Evidentsinger14** [comment]
Unable to reproduce on EssentialsX 2.20.0-dev 52 & Paper 1.19.4 - build 501
Dump: https://essentialsx.net/dump.html?id=788abd4d42a540749991462aab831057
![image](https://user-images.githubusercontent.com/46200123/230773690-ff48eeb8-3318-4ee3-849a-0f0e3467884a.png)


@flleeppyy @wetzel-cam Neither of you have a permission manager in the dumps you sent, and you did *not* send a full dump like asked, so we're unable to see if you enabled `always-send-primary`.

**Comment by wetzel-cam** [comment]
Apologies; I will admit I didn't look around for post guide, was just trying to respond... Here is the full dump [/ess dump all](https://essentialsx.net/dump.html?id=c486091fef0740758d90efb24f0b31ba)

Like I said in my first comment, I had `always-send-primary: true` and it still wasn't working. After going through some quick-ish troubleshooting, I saw that the bot was receiving the message event, but its content field was empty, so I don't think it's a problem with config. I did notice you are using the latest/dev build, where I'm using the latest release build. I will try again with the latest dev build and see how that goes.

**Comment by wetzel-cam** [comment]
Built in the newest snapshot (same as yours) and still not seeing it...

[/ess dump all](https://essentialsx.net/dump.html?id=e13eae1a80e0427abad15b7938282c27)

Debugger still doesn't show anything in the content field either.

**Comment by Evidentsinger14** [comment]
You also need a chat manager that supports EssentialsX Discord. Use EssentialsX Chat for testing purposes. 

> Like I said in my first comment, I had always-send-primary: true and it still wasn't working. 

Word of mouth unfortunately doesn't help with debugging, being able to actually see it and CONFIRM it is enabled is what we need.

**Comment by wetzel-cam** [comment]
> Word of mouth unfortunately doesn't help with debugging

Touche!

Unfortunately, after adding in EXChat no there has been no change.
[/ess dump all](https://essentialsx.net/dump.html?id=f7c73f99cb77414caef7a634b4fabb15)

Also decided to say damn it all and match your config as close as possible and STILL no luck
[dump](https://essentialsx.net/dump.html?id=c5d2093fda884815a728b47c24da46c0)

I can only think it's a discord problem at this point, but of what I don't know. I joined through the link given (twice), but it's still only receiving empty messages. Anything else I should check?

**Comment by Evidentsinger14** [comment]
> Anything else I should check?

in your developer portal, can you verify that you have enabled `message content intents`?

**Comment by wetzel-cam** [comment]
AH! Dammit discord, why is that off by default?? 

Working good now. Might be helpful to include a note about it in the install/setup guide.

Appreciate the help and tolerating my dumb oversights

Edit: it is there, just a minor sub block I mentally skipped... to others: RTFM
