### ISSUE TITLE
GlobalChatEvent doesn't get fired

### ISSUE THREAD

**Issue by SKBotNL** [EssentialsX/Essentials#5295]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=e672a918240f4702b8a3b848c38a6f68

### Bug description

When using EssentialsX's API the `GlobalChatEvent` doesn't get fired

### Steps to reproduce

1. Create a plugin with an `EventHandler` for `GlobalChatEvent`
2. Send message
3. See error

### Expected behaviour

The `GlobalChatEvent` should be fired

### Actual behaviour

The `GlobalChatEvent` isn't getting fired

**Comment by JRoy** [comment]
You have chat radius set to 0, that even is only enabled/used for when local/radius chat is enabled.
