### ISSUE TITLE
EssentialsX + LuckPerms error

### ISSUE THREAD

**Issue by DonKips** [EssentialsX/Essentials#5298]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=eb746d00eb824ec3a237bb3005c4cd4b

### Error log (if applicable)

https://paste.gg/p/anonymous/e85fc1ddf588406abaef41483f19beb9

### Bug description

When a player logs on to the server for the first time, an error appears

### Steps to reproduce

Have LuckPerms and EssentialsX on the server, log in with a new account

### Expected behaviour

There should be no error

### Actual behaviour

There is an error

**Comment by Evidentsinger14** [comment]
Should be fixed as of #5364 - Closing for now. can be re-opened if new info found.
