### ISSUE TITLE
Player quit messages do not trigger `BroadcastMessageEvent` while join messages do.

### ISSUE THREAD

**Issue by accLarson** [EssentialsX/Essentials#5301]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=059010007c614d29b6b7992318362fd5

### Bug description

Essentials quit messages do not trigger a `BroadcastMessageEvent` while essentials join messages do.

### Steps to reproduce

1. Detect events in whatever method you desire
2. Join the server and note that `BroadcastMessageEvent` triggers.
3. Quit the server and note that `BroadcastMessageEvent` does not trigger

### Expected behaviour

Join and quit both trigger a `BroadcastMessageEvent`

### Actual behaviour

Only join messages trigger a `BroadcastMessageEvent`.

**Comment by Evidentsinger14** [comment]
Closing as not planned
