### ISSUE TITLE
Server Economy reset Error

### ISSUE THREAD

**Issue by ImDarkLaw** [EssentialsX/Essentials#5305]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=9423c81184614831813c9b78333b8c60

### Error log (if applicable)

https://paste.gg/p/anonymous/3ad248771c644f50a1d5fcf4b6fbeb5b

### Bug description

**/eco reset** command produces the error on the paste above and fails to complete the economy reset for all players on the server. Despite this, /eco reset * and /eco reset <player> work properly.

### Steps to reproduce

Steps to reproduce:

**1.** Use one of the latest dev builds on **Purpur 1.19.4** (git-Purpur-1955 (MC: 1.19.4)).

**2.** Use **Vault** for the economy API and have at least 2 players join the server.

**3.** Run /eco reset ** and check on the output in chat.

### Expected behaviour

The expected behaviour, ideally, is to reset all players' balance to the starting balance amount set in the configuration. This would include online and offline players.

### Actual behaviour

Contrariwise, the balance reset does not _go through_ as the economy on the server remains intact and does not reset to the starting amount. Instead the error message is being sent in chat which can be viewed on the paste above.

**Comment by mdcfe** [comment]
Superceded by #5312.
