### ISSUE TITLE
Give /smite a permission

### ISSUE THREAD

**Issue by TigerRageMC** [EssentialsX/Essentials#5306]
### Feature description

/smite is a funny feature and I want to give it to a few friends but there is no permission for it, and I don't want to op them.

### How the feature is useful

It adds a permission for a command

**Comment by ImDarkLaw** [comment]
The permissions for the /smite command is **essentials.lightning** which already exists.

**Comment by TigerRageMC** [comment]
Well that is interesting I was doing research and didn't find that but thank you
