### ISSUE TITLE
Displayname not showing

### ISSUE THREAD

**Issue by DajMiodu** [EssentialsX/Essentials#5309]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=a20f1b0ef3284875b2a6546274e16d71

### Bug description

{DISPLAYNAME} or {USERNAME} not showing in motd. (yes I have papi in case)
![image](https://user-images.githubusercontent.com/93437148/231507512-f0be31e0-8681-49e1-bb69-1e48f39f7f5c.png)
![image](https://user-images.githubusercontent.com/93437148/231507573-712872d0-c04c-4a15-a596-001af189546e.png)

### Steps to reproduce

1. Setup a motd using {username}
2. /ess reload
3. Rejoin the server

### Expected behaviour

I wanted to greet the player

### Actual behaviour

Didnt display the line of text

**Comment by Chew** [comment]
You're missing EssentialsXChat. Also, PlaceholderAPI support isn't currently implemented, so that's irrelevant.
