### ISSUE TITLE
<Insert feature tag here> Check who has SocialSpy

### ISSUE THREAD

**Issue by FlippantCactus** [EssentialsX/Essentials#531]
Would be nice to see who has socialspy, even if they're not online.
A command to paste them in a pastebin/gist would be nice although a print in game would also be good.

**Comment by Kakifrucht** [comment]
This would require essentials to iterate through every user(file).

**Comment by FlippantCactus** [comment]
Or, once socialspy is enabled to a user, it'd write a file; much like the "custom" files it already has in place.

**Comment by drtshock** [comment]
I'm not going to add another file for this.

**Comment by FlippantCactus** [comment]
D'aww :(
