### ISSUE TITLE
Eco Reset Exception

### ISSUE THREAD

**Issue by ImDarkLaw** [EssentialsX/Essentials#5312]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=4443b8d667224fbfbc025eb8ec7cfd37

### Error log (if applicable)

https://paste.gg/p/anonymous/a57f08e926bd406ba85b25ad05bbfdae

### Bug description

Follow up bug report on an existing issue regarding /eco reset ** command execution. 

After using /eco reset ** i receive the following output in chat, while, none of the players' money reset:

**Error: Cannot invoke "com.earth2me.essentials.User.setMoney(java.math.BigDecimal, net.ess3.api.events.UserBalanceUpdateEvent$Cause)" because "player" is null**

Note: Upon giving a quick glance at the debug logs, i feel like my message properties file is outdated or corrupted. Maybe that's what causing the issue. 

### Steps to reproduce

All is required to reproduce is to run /eco reset **. 

### Expected behaviour

Expected to reset all players' balances to the starting amount

### Actual behaviour

Balances do not reset, an the error message below is printed:

**Error: Cannot invoke "com.earth2me.essentials.User.setMoney(java.math.BigDecimal, net.ess3.api.events.UserBalanceUpdateEvent$Cause)" because "player" is null**

**Comment by Evidentsinger14** [comment]
Fixed as of #5339
