### ISSUE TITLE
Hex compatibility for messages_en.properties

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#5317]
### Feature description

There is no HEX code compatibility for any locale messages in EssentialsX. It can be used in-game, but not to actually customize the core messages. Most plugins above 1.16.x support HEX now and when using other plugins with HEX color codes, getting all server messages to match is impossible due to EssentialsX lacking that ability. I know there's *sort-of* a work around using console type messages ( ex. §x§2§8§4§b§6§3T§x§2§8§4§b§6§3e§x§2§8§4§b§6§3s§x§2§8§4§b§6§3t ) - ( color code #284B63 saying "test" ), but using it that way makes messages extremely long and is just impractical. 

### How the feature is useful

I feel that it's almost a necessary feature in the modern age of server development. Everyone knows regular Minecraft color codes and after so many years, they are very boring. Having the option to use HEX brings a lot of customization and opens the door for more creativity and difference from server-to-server.

**Comment by mbax** [comment]
Work is being done on proper modern support, with Minimessage.

**Comment by ghost** [comment]
> Work is being done on proper modern support, with Minimessage.

Ok that's great, do you have any idea of a timeframe for completion?

**Comment by mbax** [comment]
I'm not a part of that work, but my estimate would be it's very much a "when it's done" estimate. which will vary based on how much free time contributors have. Big changes in free projects are hard. 😄
