### ISSUE TITLE
Offline player /r error

### ISSUE THREAD

**Issue by untuned** [EssentialsX/Essentials#5318]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=0265288fc33642c3911c24ad1ce18864

### Error log (if applicable)

https://paste.gg/p/anonymous/5d92e0f5853e44b3a6185c8d5af5395f

### Bug description

When using /r to reply to an offline player, this error shows in console.

### Steps to reproduce

1. Have 2 people online.
2. Have person 1 message person 2.
3. Have person 1 disconnect.
4. Have person 2 use /r to reply to the offline player.
5. Observe the error in console.

### Expected behaviour

No error.

### Actual behaviour

Error.

**Comment by JRoy** [comment]
This is an issue with purpur.
