### ISSUE TITLE
UserMap uses a lot of memory with large number of users

### ISSUE THREAD

**Issue by SladeHazard** [EssentialsX/Essentials#5327]
### Type of bug

Performance issue or memory leak

### `/ess dump all` output

 [03:22:46 INFO]: EssentialsX version: 2.20.0-dev+44-43d84de [THE DUMP failed and i dont think its necessary here]

### Error log (if applicable)

N/a

### Bug description

![image](https://user-images.githubusercontent.com/45261094/235046908-8bcad262-76a0-48d4-bae2-376b9d941282.png)
![image](https://user-images.githubusercontent.com/45261094/235046913-2fc1158e-4060-4966-b995-25e88f8c96ef.png)

EssentialX takes a lot of memory, any way to optimize / fix this ? is the MySQL addon from spigot recommended?

### Steps to reproduce

use the plugin with 60k+ users in the datafile

### Expected behaviour

not take a lot of memory

### Actual behaviour

takes a lot of memory which causes gc drop

**Comment by pop4959** [comment]
Don't recommend using unofficial addons like the MySQL ones. You will receive no support for doing so.

It does seem like there is a good amount of memory usage coming from the UserMap though, which may be worth looking into. While it's intended that profiles are loaded that still seems concerning especially considering ItemDb is also very large and is a mere fraction of the usage.

I may be willing to dive into optimizing this a bit if you would be able to privately send a copy of your UserMap for testing. You can do this on our Discord server.
