### ISSUE TITLE
/toggleshout causing issues with shout/local chat

### ISSUE THREAD

**Issue by hexobt** [EssentialsX/Essentials#5342]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=badbca1662db46938cc7a92ac291aca5

### Bug description

Having `/toggleshout` enabled and typing a question mark by itself in chat outputs **incorrectly** in local when it should be in shout. Note, prefixing with `!` **correctly** outputs in local.

Therefore the only way to type a question mark by itself in shout is to disable shout mode, then type `!?` in chat. 
![Screenshot](https://user-images.githubusercontent.com/132927401/237033630-68321534-1be1-44aa-8aee-78f06383b3e5.png)

### Steps to reproduce

1. Type `/toggleshout` to enable shout mode.
2. Type `?` by itself in chat.

### Expected behaviour

The question mark chat message should appear in Shout.

### Actual behaviour

The question mark chat message appears in Local.

**Comment by mdcfe** [comment]
You have question chat enabled. Question chat is a separate channel to shout chat which is triggered by putting a `?` at the start of the message. However, this shouldn't trigger a switch back to *local* chat.

Could you confirm whether this still happens with `chat.question-enabled: false` set in `plugins/Essentials/config.yml`? (Search for the `question-enabled: true` line and edit it.)

**Comment by hexobt** [comment]
With `chat.question-enabled: false` the behavior is still the same. Single question mark in chat switches back to local while a question mark + other characters correctly goes to shout. In fact, multiple question marks eg. `???` go to shout; it's just messages with a single question mark by itself that's causing this issue.

![Screenshot](https://user-images.githubusercontent.com/132927401/237038478-4dd81e6a-9e02-4987-96c5-c4337ae3741a.png)

**Comment by Evidentsinger14** [comment]
![image](https://github.com/EssentialsX/Essentials/assets/46200123/9aa1a8ee-a977-4deb-94c8-14a9c09b627d)
I am able to replicate this behavior
