### ISSUE TITLE
Thread-120 Error

### ISSUE THREAD

**Issue by wvbigdave** [EssentialsX/Essentials#5347]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=f8d6d51155e04625aed12c46f21af6d7

### Error log (if applicable)

https://paste.gg/p/anonymous/b615f6c6cb0d41b7969aedc18fccfc83

### Bug description

It only occurs during shutdown.  Does repeat itself.  I don't know if it has something to do with another plugin. 

### Steps to reproduce

normal shutdown of the server using stop command via console.

### Expected behaviour

should shutdown without any errors. 

### Actual behaviour

doesn't seem to be detrimental to the server.  but just in case it could.

**Comment by pop4959** [comment]
This error can happen for a variety of reasons such as replacing plugin jar files while the server is running. Shouldn't be an issue with Essentials.
