### ISSUE TITLE
groupmanager

### ISSUE THREAD

**Issue by jwpwnz** [EssentialsX/Essentials#535]
After updating to 1.9 and now it wont let separate worlds have different permissions  and ranks this worked before i updated using the latest version of spigot and this plugin i really need this fixed my server has been using this plugin for years not possible to switch to a new one it will kill it. here is my config  http://pastebin.com/EXn9v9Fw  I have it so all unnamed worlds spawn a folder in the worlds folder  but it no longer does it

**Comment by Kakifrucht** [comment]
groupmanager is not supported

**Comment by jwpwnz** [comment]
Then why even update the plugin its useless if it doesnt work.. not like im asking for help how to set it up  i really need this issue fixed.

**Comment by Kakifrucht** [comment]
I would personally advise you to just switch plugins, you won't get support regarding groupmanager here.

**Comment by jwpwnz** [comment]
The problem is i cant switch plugins its a 5 year old server do you know how much it would mess it up lol so basically if no one can fix this my server is dead.

**Comment by Kakifrucht** [comment]
My server is 4 years old, and even though I have been using GroupManager for forever I was able to switch to bPermissions.

**Comment by jwpwnz** [comment]
yes but the problem is i would have to re promote every player donator ect Tons of players unless you know a automated way to do this.

**Comment by Kakifrucht** [comment]
well don't expect me to spoonfeed you. You are managing your server for 5 years already, you should find a way to port from one format to another.

**Comment by drtshock** [comment]
Groupmanager isn't supported. It says it in huge, bold, red text. I merely compiled it for those that are too stubborn to switch.
