### ISSUE TITLE
Command god doesn't protect againt explosions

### ISSUE THREAD

**Issue by msmanui** [EssentialsX/Essentials#5350]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=3ea847bf4b604fa283e3880116d8ce19

### Bug description

If you have god mod enabled, explosions (eg. end crystals) can kill you anyway.

### Steps to reproduce

1. Place obsidian and crystal
2. Click
3. Explosion will cause damage.

### Expected behaviour

It should not

### Actual behaviour

ok

**Comment by Evidentsinger14** [comment]
https://github.com/EssentialsX/Essentials/assets/46200123/215561bb-aeae-4116-8fde-bf39a3e2e25d

Cannot replicate, using your config.yml. Please replicate only using supported plugins. (LuckPerms, Vault, EssentialsX, and official EssentialsX addons)

**Comment by msmanui** [comment]
In that way i can't replicate. However, if there is a player arround that explosion and has god mod in that case is were he recive damage, when it should not.

**Comment by Evidentsinger14** [comment]
Can you please provide a video of this happening

**Comment by msmanui** [comment]
I can't really but basically make an explosion and the other players arround will get damage (even if they have GOD MOD)

**Comment by Evidentsinger14** [comment]
https://github.com/EssentialsX/Essentials/assets/46200123/e28a9aca-7c50-4a52-bd3f-446893646fee

Still unable to replicate this issue. When you are able to make a video of this happening, using only supported plugins please upload the video here, and send a new `/ess dump all` link.
