### ISSUE TITLE
WARN] [EssentialsDiscord] Task #578 for EssentialsDiscord v2.20.0-dev+67-1a4f639 generated an exception

### ISSUE THREAD

**Issue by CaedenCraft** [EssentialsX/Essentials#5351]
### Type of bug

Error in console, Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=34a988bbde8f422293ad24a6a96b1461

### Error log (if applicable)

Task #578 for EssentialsDiscord v2.20.0-dev+67-1a4f639 generated an exception java.lang.NoClassDefFoundError: net/essentialsx/api/v2/ChatType         at net.essentialsx.discord.listeners.BukkitChatListener.lambda$onChat$0(BukkitChatListener.java:24) ~[?:?]         at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3749-Spigot-7da74da-d9324b4]         at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3749-Spigot-7da74da-d9324b4]         at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1259) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3749-Spigot-7da74da-d9324b4]         at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3749-Spigot-7da74da-d9324b4]         at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3749-Spigot-7da74da-d9324b4]         at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1017) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3749-Spigot-7da74da-d9324b4]         at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3749-Spigot-7da74da-d9324b4]         at java.lang.Thread.run(Thread.java:833) ~[?:?] Caused by: java.lang.ClassNotFoundException: net.essentialsx.api.v2.ChatType         at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]         at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]         at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]         ... 9 more

Also 

[Minecraft] Could not pass event AsyncUserDataLoadEvent to EssentialsDiscord v2.20.0-dev+67-1a4f639

### Bug description

Set up in config and allat, bot is online, Console messages send but in-game chat doesnt?

### Steps to reproduce

Brand New setup 
Bot has administrator perms
Tweak config to be proper 
Start Server
Discord error thing

### Expected behaviour

Send message in channel

### Actual behaviour

error

**Comment by LaxWasHere** [comment]
Hello, please make sure to update all EssentialsX modules to the same version.

**Comment by Evidentsinger14** [comment]
@CaedenCraft was this resolved by updating all jars to the same version?
