### ISSUE TITLE
Support shortened numbers in /pay, /bal and /baltop (1k = 1000, 3.44m = 3440000, etc)

### ISSUE THREAD

**Issue by iLemon** [EssentialsX/Essentials#5352]
### Feature description

Many servers with economies have players dealing with high numbers, even beyond trillions.

It would be a nice QoL feature if the /pay command supported shortened number format.

Instead of /pay iLemon 115000000000000
I could type /pay iLemon 115t

Support K, M, B, T, Q (case insensitive)

Also, have a config option so that the numbers in /bal and /baltop are shortened too.

### How the feature is useful

It saves players from typing long numbers, especially on servers with economies that go into trillions and quadrillions.

**Comment by Evidentsinger14** [comment]
This behavior does exist in EssentialsX - seems like this issue was missed when that PR was made.
