### ISSUE TITLE
SafeFly Error

### ISSUE THREAD

**Issue by AdnanMI** [EssentialsX/Essentials#537]
Hey, this error popped up while in a empty world. Its not a big bug however if gives an error. 
http://paste.ubuntu.com/15564232/

**Comment by drtshock** [comment]
Can you paste the full stack trace please? It looks like you missed some.

**Comment by AdnanMI** [comment]
http://paste.ubuntu.com/15564292/

**Comment by drtshock** [comment]
that's expected.

**Comment by AdnanMI** [comment]
It's expected to give an error? Shouldn't it say hole in floor ?

**Comment by drtshock** [comment]
How do you expect it to find you a safe location in an empty world? ;)
