### ISSUE TITLE
Exception when responding to an offline player via /reply

### ISSUE THREAD

**Issue by Warriorrrr** [EssentialsX/Essentials#5374]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=d1a1064be1124831a478c72c2619bff4

### Error log (if applicable)

https://paste.gg/p/anonymous/394aa06454c24b9eb0ef592433770912

### Bug description

When responding to a player who's gone offline you'll instead be met with an exception in console, the new-ish isVisibleByDefault method doesn't seem to be implemented in essentials' OfflinePlayer which the canSee method uses.

### Steps to reproduce

1. Send a message to an online player.
2. Kick the player from the server.
3. Send another message via /reply.
4. Observe error in console.

### Expected behaviour

The player who used /r getting the "playername recently went offline" message.

### Actual behaviour

No feedback for the player and instead an exception in the console.

**Comment by Evidentsinger14** [comment]
can reproduce
