### ISSUE TITLE
ItemDb's names for Enchanted Golden Apple (eg godapple, notchapple, enchantedapple, etc.) do not work.

### ISSUE THREAD

**Issue by theolensky** [EssentialsX/Essentials#5376]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=6047015c3fe6423095144f3aa85a840c

### Bug description

I am trying to create a shop sign:

[Buy]
1
godapple
500

but no matter which nickname for enchanted golden apples I use from itemdb (items.json) , it just says "unknown item" and doesnt work.

I have not been able to fix it myself by tweaking items.json

I would really appreciate your help :) 

### Steps to reproduce

[Buy]
1
godapple
500

### Expected behaviour

to buy 1 enchanted golden apple for 500

### Actual behaviour

nothing happens, chat result is "unknown item name: godapple."

**Comment by JRoy** [comment]
Cannot reproduce, try deleting your `plugins/Essentials/items.json` file while the server is off and trying again.
