### ISSUE TITLE
/invsee command bug makes item lost

### ISSUE THREAD

**Issue by L2750558108** [EssentialsX/Essentials#5380]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

[23:41:56 INFO]: 6正在创建服务器转储文件... [23:41:56 INFO]: 4在上传cspawn.yml4时发生错误：cplugins\Essentials\spawn.yml [23:41:58 INFO]: 6已创建服务器转储文件：chttps://essentialsx.net/dump.html?id=143a41ea141f4917a6c12bb3efda7c46 [23:41:58 INFO]: 6如果你想在以后删除此转储文件，请使用以下删除密钥：ce569e532-560f-482c-bb5d-815e4dbedd0b

### Bug description

When using the invsee command to view other people's inventory, when picking up and dropping items in the interface, there is a chance that the item will mistakenly enter other compartments, and directly cause the original item of the grid to disappear

When placing items into the two squares circled in the diagram, the above situation seems to appear higher
![屏幕截图 2023-06-04 234813](https://github.com/EssentialsX/Essentials/assets/119792950/98f8a370-93cb-4a2c-bdaa-cea76e74633c)

### Steps to reproduce

See "Bug description"

### Expected behaviour

See "Bug description"

### Actual behaviour

See "Bug description"

**Comment by Octol1ttle** [comment]
You're likely experiencing https://github.com/EssentialsX/Essentials/issues/3956#issuecomment-771694504. If you want to safely modify player inventories, use plugins like OpenInv

**Comment by Chew** [comment]
Cause of close: didn't read before posting 😔 

Basically what octo said, unless you can prove it's not covered in there, gonna close as a duplicate. Thank you for reporting!
