### ISSUE TITLE
Suggestion: Allow Currency Naming

### ISSUE THREAD

**Issue by andrewyunt** [EssentialsX/Essentials#539]
Hello,

I think Essentials Eco should come with an option for currency naming to compete with other economy plugins that have this feature. Currently using Essentials Eco I have currency names added in the locale file, but there is no way to completely remove the currency symbol which is a dollar sign by default and makes the messages look extremely ugly. Another problem with trying to name currencies this way is you can't have parent and child nodes such as dollars and coins. Other economy plugins are extremely unreliable and tend to break often, making Essentials the only practical economy plugin, although it lacks this feature which is a disappointment. Is there any chance we could possibly see this feature in the near future?

Thanks.

**Comment by drtshock** [comment]
https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/config.yml#L542
