### ISSUE TITLE
EssentialsX useing /setspawn command console log out 'Missing translation key "spawnCommandUsage1" in translation file zh'

### ISSUE THREAD

**Issue by IsNott** [EssentialsX/Essentials#5390]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=62cd787a74aa4f2a9c4ceb5c4f7a755c

### Bug description

Using zhcn as server's language,test setspawn command '/setspawn',console output some error log like 'Missing translation key "essentialsCommandUsage9" in translation file zh',but after that log shows using '/spawn' still work and transfer me to the right place.

### Steps to reproduce

1. Service only has me online
2. Run '/setspawn'
3. useing zhcn as language
4.Server config info already shows in https://essentialsx.net/dump.html?id=62cd787a74aa4f2a9c4ceb5c4f7a755c

### Expected behaviour

console should not show error log,I guesss.

### Actual behaviour

looks like something missing when server using zh_cn and that Exception should be catched  but not throw.

**Comment by Evidentsinger14** [comment]
The exception is caught, however you have debug enabled. Disable debug if you wish to not see these messages.
