### ISSUE TITLE
No issues tab on main mod page

### ISSUE THREAD

**Issue by Aceplante** [EssentialsX/Essentials#5396]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

N/a

### Bug description

Title. On the mod page, there is no issues tab so I had to find this on google

### Steps to reproduce

Go to the mod page
look

### Expected behaviour

There should be a issues tab

### Actual behaviour

there is not

**Comment by mdcfe** [comment]
We link to GitHub issues across all platforms we publish EssentialsX on - you're going to need to be more specific than "there is no issues tab".

**Comment by Aceplante** [comment]
(https://www.curseforge.com/minecraft/mc-mods/essential-mod) most mods have an "issues" tab that links to the github, but yours did not

![essentialissues](https://github.com/EssentialsX/Essentials/assets/101857505/e37b0408-d150-4e29-8bfb-f8dfec1bd658)

**Comment by pop4959** [comment]
EssentialsX is not the Essential Mod. These are completely different projects.

**Comment by Aceplante** [comment]
ah, sorry about that. Like i said I got this one by google searching becuase that mod does not appear to have one...
