### ISSUE TITLE
Discord link doesnt work?

### ISSUE THREAD

**Issue by Aceplante** [EssentialsX/Essentials#5397]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

unrelated

### Bug description

Discord link doesnt work

### Steps to reproduce

click the discord link

### Expected behaviour

It should join the discord

### Actual behaviour

it opens discord but does not join

**Comment by mdcfe** [comment]
Please fill out the template properly, detailing what you have actually attempted and what actual result you got.

**Comment by Aceplante** [comment]
What more do you need? I clicked the discord link, it opened discord but did not join

**Comment by pop4959** [comment]
You provided no information at all in the issue such as where you found the link, what the link was, how you clicked on it, what showed up when you clicked it, etc.

I'm assuming this is also again for the Essential Mod (not EssentialsX) which means that it's not something for us to fix.
