### ISSUE TITLE
Discord Exponential Backoff

### ISSUE THREAD

**Issue by untuned** [EssentialsX/Essentials#5400]
### Feature description

When the Discord modules encounter a rate limit, instead of trying once every second, it should instead have an [exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff) that increases the time between retries.

### How the feature is useful

This will help prevent the rate limit from refreshing, and also prevent any blacklists of the server's IP from connecting to Discord. Also prevents the application from being disabled if too many requests are made.

**Comment by Evidentsinger14** [comment]
Seems more like something that should be part of the library EssX Discord uses, rather than EssX Discord itself.

**Comment by mdcfe** [comment]
> Seems more like something that should be part of the library EssX Discord uses, rather than EssX Discord itself.

@Evidentsinger14 I'm inclined to disagree - I'd say it's down to us to handle ratelimiting gracefully. The webhook library should expose ratelimits and failures to us, but otherwise should just fire webhooks as we request.

**Comment by Chew** [comment]
Discord module is also designed around us being able to drop-in a new library if needed, so I agree with having us handling it, even if that ends up utilizing the current library's rate-limiting for the time being.

**Comment by JRoy** [comment]
should be improved with https://github.com/EssentialsX/Essentials/pull/4786
