### ISSUE TITLE
ECONOMY

### ISSUE THREAD

**Issue by 11kk1123** [EssentialsX/Essentials#5403]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=dc78675154dd4b8abb49d926b6a147a7

### Bug description

The problem is, if we write the command /eco give nickname 100 from the console, then in response I will receive the following:

- Code:
- Ⓗ100 credited to kk account. Current balance: Ⓗ100

But when I enter the server, I have no money.
What is the problem?
The console outputs this:

- Code:
- Ⓗ100 credited to kk account. Current balance: Ⓗ200

And I go to the server, I also have 100 ... What's the problem?

I need to be able to give to offline players using the /eco give command.

### Steps to reproduce

When I run a command in the console or I write in the chat myself, it says that the money was given to the player, but they do not come to the offline player.

### Expected behaviour

I want to be able to give money to offline players.

### Actual behaviour

Money is not issued to offline players.

**Comment by JRoy** [comment]
You're using an unsupported server version, mismatched essentials version jars, and unsupported mysql based plugins that likely are causing this issue.
