### ISSUE TITLE
[feature request] [1.20.1] Add a '/removewax sign' command.

### ISSUE THREAD

**Issue by dandud100** [EssentialsX/Essentials#5406]
### Feature description

I would like to see a command that removes the wax from an sign.

/waxremove sign
(/waxremove copper) optional because vanilla minecraft can do this, but if this is added too i would seperate the commands.

Usage: Be in front of the sign and look at it, then use the command.

### How the feature is useful

Since in normal vanilla minecraft there is no option to remove wax from an sign. An command that does this could be useful.

**Comment by JoniDev25** [comment]
Just Use An Axe And Right Click The Sign With It

**Comment by JoniDev25** [comment]
Or Modify The Block NBT With /data

**Comment by dandud100** [comment]
> Just Use An Axe And Right Click The Sign With It

This is a thing? I didn't found that on the Minecraft Wiki.

**Comment by JRoy** [comment]
Not really within the scope of Essentials.
