### ISSUE TITLE
[Suggestion] Commands to Toggle Specific Modes On or Off

### ISSUE THREAD

**Issue by clovisd** [EssentialsX/Essentials#541]
Hey Guys!

Would it be possible to add commands that force disable a mode or toggle?

Right now,to enable / disable god mode (for example), you would use /god (username)

However, would it be possible to add an option such as /godon username and /godoff username.

While the /god command works most of the time, adding it as a force off or on could work great with plugins like Duty. That way, if a player where to enter Staff/Duty mode, it would force it on and then force it off when they leave it. Right now, if a staff enters staff mode, and disconnect, the plugin wouldn't be able to disable their fly/god mode meaning they could bypass it and have fly/god outside staff duties.

Looking forward to your thoughts,
Clovis

(Also, where can I find EssentialsX on IRC?)

**Comment by drtshock** [comment]
The plugin should just hook into essentials then..

We're on #drtshock on esper

**Comment by clovisd** [comment]
I used a plugin as an example. My point is running commands from console and other forms of automation where I want to make sure it will force the status on/off instead of just toggle it.

**Comment by drtshock** [comment]
That's not really what the commands are for.
