### ISSUE TITLE
signing

### ISSUE THREAD

**Issue by iFranticman** [EssentialsX/Essentials#5411]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=36fad3921511496a8bbce05611a62e99

### Error log (if applicable)

Players are randomly like once a day getting kicked with error "Chat message validation failiure"

### Bug description

Players are randomly like once a day getting kicked with error "Chat message validation failiure"

### Steps to reproduce

It's random and happens about once a day

### Expected behaviour

Need them to stay connected

### Actual behaviour

Players are randomly like once a day getting kicked with error "Chat message validation failiure"

**Comment by pop4959** [comment]
Please only report issues that are related to EssentialsX.
