### ISSUE TITLE
/balancetop uses [displayname] only when the player is online

### ISSUE THREAD

**Issue by dandud100** [EssentialsX/Essentials#5413]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=9e075c77c1c14b399e61dd91ce11355b

### Bug description

![image](https://github.com/EssentialsX/Essentials/assets/43549788/8789b4da-7a3e-4b61-9583-431ba7ab340c)

### Steps to reproduce

1. Have two players, one of them needs to be offline
2. Give them an prefix with Luckperms
3. do /balancetop

### Expected behaviour

All Players should be either displayed with the prefix or without, or maybe a * in front of their names to mark that they are online.

### Actual behaviour

See image

**Comment by JRoy** [comment]
This is intended, display names are not persistent across restarts and there is no way to resolve them while the player is offline.

**Comment by dandud100** [comment]
> This is intended, display names are not persistent across restarts and there is no way to resolve them while the player is offline.

Can you add an option, to display online players without the Prefix / (Displayname)? It looks so weird imo.

**Comment by Evidentsinger14** [comment]
You can already do this by setting `add-prefix-suffix` to false, and uncommenting it (Removing the `#`) keep in mind, this will break all uses of displayname, including your chat format if you use EssentialsX Chat, but this can be rectified by utilizing the {PREFIX} and/or {SUFFIX} placeholders in your chat format.
