### ISSUE TITLE
DiscordLink multiple minecraft account link to a discord

### ISSUE THREAD

**Issue by 0kju0** [EssentialsX/Essentials#5415]
### Feature description

It will be very nice if plugins can settings max minecraft accounts (example: 2) to link to a discord account.
Example I have java and bedrock accounts.
I like playing Java version on PC, and use bedrock on mobile.

### How the feature is useful

Player have multilple minecraft account (Java, Bedrock).
It should be link all accounts to a discord account.

**Comment by CatbotTsumi** [comment]
assuming geyser is being used. why not use geyser floodgate to let people /linkaccount (bedrock username) while logged in on java account to turn both accounts into one? No discord linking necessary

**Comment by JRoy** [comment]
Multiple accounts will cause authoritative issues with role sync. I think this is outside of the scope of Essentials
