### ISSUE TITLE
Using /reply to reply to a player who has since left the server throws an error

### ISSUE THREAD

**Issue by ondomatej** [EssentialsX/Essentials#5418]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=6cc997090c4e49a4b54568f9cfac0923

### Error log (if applicable)

https://paste.gg/p/anonymous/1187c71837984f549210ab5036ba3260

### Bug description

When using /r to reply to a player who has since left the server, an error is displayed in the console.

### Steps to reproduce

1. Have a player message you
3. Use the /r command once the player leaves the server

### Expected behaviour

The command should not print an error to the console, but rather display an error to the user

### Actual behaviour

The command throws an unhandled error in the console

**Comment by JRoy** [comment]
This was fixed in the latest dev builds.
