### ISSUE TITLE
/fly not disabeling when switching worlds

### ISSUE THREAD

**Issue by HypiMC** [EssentialsX/Essentials#5420]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

/fly

### Bug description

I want to give players permissions to use /fly. I give them essentials.fly in my luck perms, but by giving them this essentials.fly they can also bypass 
# When a player changes world, should EssentialsX reset their flight?
# This will disable flight if the player does not have essentials.fly.
world-change-fly-reset: true

My question is how can I give players /fly and when they switch worlds their flight gets disabled?
Because if I give players essentials.fly they can bypass this. Is there another permissions that can give /fly?

### Steps to reproduce

/fly

### Expected behaviour

I want to give players ability to use /fly but when they switch world then their flight gets disabled. How can I give players /fly and disabeling their /fly when switching worlds.

### Actual behaviour

When I switch world my flight doesn't gets disabled.

**Comment by Evidentsinger14** [comment]
Please fill the issue template out properly.

**Comment by HypiMC** [comment]
I want to give players permissions to use /fly. I give them essentials.fly in my luck perms, but by giving them this essentials.fly they can also bypass this:
# When a player changes world, should EssentialsX reset their flight?
# This will disable flight if the player does not have essentials.fly.
world-change-fly-reset: true

So my question is how can I give players ability to use /fly command but their /fly gets reset when chaning worlds?

**Comment by HypiMC** [comment]
I want to give players permissions to use /fly. I give them essentials.fly in my luck perms, but by giving them this essentials.fly they can also bypass this:

When a player changes world, should EssentialsX reset their flight?
This will disable flight if the player does not have essentials.fly.
world-change-fly-reset: true

So my question is how can I give players ability to use /fly command but their /fly gets reset when chaning worlds?

**Comment by Evidentsinger14** [comment]
Closing in favor of #5427
