### ISSUE TITLE
Placeholder for /tpauto and /msgtoggle

### ISSUE THREAD

**Issue by MadPanCake** [EssentialsX/Essentials#5421]
### Feature description

Placeholders that say:
- If the player has '/tpauto' command enabled
- If the player '/msgtoggle' enabled

### How the feature is useful

The placeholder returns 'true', 'false'.

That would add up to other, already existing placeholder of this kind in Essentials.
It's also super useful, the more placeholders a plugin has, the more customisable it is and it's usefulness for well-developed servers increases tremendously.

**Comment by Octol1ttle** [comment]
Placeholders for PlaceholderAPI are **not** developed by the EssentialsX team. Please send requests for new placeholders [to the PlaceholderAPI team](https://github.com/PlaceholderAPI/Essentials-Expansion/issues/new)

**Comment by Evidentsinger14** [comment]
Closing due to invalid issue - as l1ttle said, all PlaceholderAPI placeholders in the Essentials expansion are maintained by the PlaceholderAPI team, not us.
