### ISSUE TITLE
Essentials Discord/Discord Link Error

### ISSUE THREAD

**Issue by BackSam6348** [EssentialsX/Essentials#5423]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=133f324103854015ae82bb1591e3a929

### Error log (if applicable)

https://paste.gg/p/anonymous/bc2cd1109c55465ebc918174fe360ef2

### Bug description

![image](https://github.com/EssentialsX/Essentials/assets/47339652/156d4213-0fc2-4c58-8458-78efe3e4b05e)
![image](https://github.com/EssentialsX/Essentials/assets/47339652/a0b4c408-a305-494c-a9b6-429adeb27584)

### Steps to reproduce

Edit Config in plugins\EssentialsDiscord

And Run The Server

### Expected behaviour

I used the /plugins command, but EssentialsDiscordLink is disabled.

### Actual behaviour

I used the /plugins command, but EssentialsDiscordLink is disabled.

**Comment by Octol1ttle** [comment]
You forgot to turn on privileged intents for your bot during setup of EssentialsDiscord. You need to go to [Discord Developer Portal](https://discord.com/developers/applications), select your application, click Bot in the sidebar, scroll down to Privileged Gateway Intents and enable all 3 privileged intents (Presence Intent, Server Members Intent and Message Content Intent).

![disable-public e8b2c9df](https://github.com/EssentialsX/Essentials/assets/61277953/b24822c8-aa25-4e86-89ab-dfe59ac57979)
