### ISSUE TITLE
Accept %player% placeholder on kit items

### ISSUE THREAD

**Issue by thiagogebrimm** [EssentialsX/Essentials#5425]
### Feature description

I wanted that in the kits when adding %player% in the lore or in the name of the item it would replace it with the name of the player who is receiving the kit, it would be very good and would help to create a lot of innovations on the servers

### How the feature is useful

could create custom and exclusive kits with the name of the players in the lore or in the name of the items, it would give many possibilities

**Comment by mdcfe** [comment]
You can use any supported [keywords](https://essentialsx.net/wiki/Keywords.html) inside a kit.
