### ISSUE TITLE
Accept model-data on kits config

### ISSUE THREAD

**Issue by thiagogebrimm** [EssentialsX/Essentials#5426]
### Feature description

Add a way to put model-data in the kits, model-data work with "use-nbt-serialization-in-createkit" active but that way you can't insert the keywords in the kit because it doesn't work, so the way I thought is to add this direct option in kit config without active nbt

### How the feature is useful

It would be possible to create kits with the keywords without having to have the nbt active and it would still give several creation possibilities

**Comment by YanisBft** [comment]
By model-data I assume you mean CustomModelData tag?

**Comment by thiagogebrimm** [comment]
> By model-data I assume you mean CustomModelData tag?

yes
