### ISSUE TITLE
Problem with essentials fly

### ISSUE THREAD

**Issue by HypiMC** [EssentialsX/Essentials#5427]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=c0ef362d4b6f49bca00469c3c0e98f7d

### Bug description

I want to give players permissions to use /fly. I give them essentials.fly in my luck perms, but by giving them this essentials.fly they can also bypass this in the config:
When a player changes world, should EssentialsX reset their flight?
This will disable flight if the player does not have essentials.fly.
world-change-fly-reset: true

But I don't want them to bypass this feature. I want them to reset their flight when entering a new world. I gave my players essentials.fly but they can bypass this. How can I give my players fly but when they switch worlds they reset their flight.

### Steps to reproduce

1. I gave my players essentials.fly permission in luckperms
2. My players can bypass world-change-fly-reset: true , because they have permission to bypass it
3. How can I give my players /fly and world-change-fly-reset: true 

### Expected behaviour

When I give my players essentials.fly permission in luckperms they can bypass world-change-fly-reset: true because it is set that if the player got essentials.fly they can bypass this feature, but I don't want that.

### Actual behaviour

When I give my players essentials.fly permission in luckperms they can bypass world-change-fly-reset: true because it is set that if the player got essentials.fly they can bypass this feature, but I don't want that.

**Comment by Evidentsinger14** [comment]
You missed the `all` argument in the dump command. `/ess dump all` - please send the updated dump link here, and I'll investigate it.

**Comment by HypiMC** [comment]
https://essentialsx.net/dump.html?id=21aa157013b042298d7b46a6a3819b66

**Comment by HypiMC** [comment]
Do you need anything else?

**Comment by mdcfe** [comment]
> Do you need anything else?

Yes, we need the output of `/ess dump all` **with the word `all` at the end**.

**Comment by HypiMC** [comment]
[16:10:36 INFO]: Created server dump: https://essentialsx.net/dump.html?id=665b2caea3b74dd2904d602c4d59134f

[16:10:36 INFO]: If you want to delete this dump at a later date, use the following deletion key: b6bf2611-9cf7-45fb-bd04-55eec8be53aa

**Comment by ImDarkLaw** [comment]
> [16:10:36 INFO]: Created server dump: https://essentialsx.net/dump.html?id=665b2caea3b74dd2904d602c4d59134f
> 
> [16:10:36 INFO]: If you want to delete this dump at a later date, use the following deletion key: b6bf2611-9cf7-45fb-bd04-55eec8be53aa

Still not quite what we've asked for. Please run `/ess dump all`, including the **`all`** argument at the end, as stated earlier, and provide us with a new link.

**Comment by mdcfe** [comment]
Again you ran `/ess dump`, not `/ess dump all` as we've asked. We can't help you unless you run the command as instructed.

2.19.0 is not a version of EssentialsX we support. If you can reproduce this bug while running EssentialsX 2.20.0 and can provide the output of **`/ess dump all`**, then we will be able to help you.

### You need to include the word `all` at the end of the command.

**Comment by HypiMC** [comment]
I did /ess dump all and the console gave me this.

**Comment by HypiMC** [comment]
>ess dump all
[17:29:05 INFO]: CONSOLE issued server command: /ess dump all
[17:29:05 INFO]: Creating server dump...

[17:29:06 INFO]: Created server dump: https://essentialsx.net/dump.html?id=c2061deaa607483faeb26135521952ef

[17:29:06 INFO]: If you want to delete this dump at a later date, use the following deletion key: 0942e7c2-1736-40cb-8a9c-be981487f3ec

**Comment by HypiMC** [comment]
I updated to the latest version and still got this

**Comment by Evidentsinger14** [comment]
Thank you - when someone has some free time, it will be looked into.

**Comment by HypiMC** [comment]
Thank you. Didn't understand at first what you were trying to tell me because I did /ess dump all but then I updated to latest version and worked.

**Comment by Evidentsinger14** [comment]
Was entirely a misunderstanding. `/ess dump all` was added in 2.19.1, and you were on 2.19

**Comment by HypiMC** [comment]
Any progression on the issue?

**Comment by LaxWasHere** [comment]
Unless you can reproduce with the latest stable build of EssentialsX I doubt you'll get any meaningful answer, no.

**Comment by HypiMC** [comment]
I tried with the latest version. The problem is that for giving players ability to fly I need to give them essentials.fly and by giving them this persmission for /fly they can also bypass the change world reset flight. So the only solution is to add another permission. Like essentials.worldchangeflyreset. By adding this I would not have a problem by adding permission to my players for fly. I think is the only solution to giving another permission to world change fly reset, because now is set by default for essentials.fly

**Comment by LaxWasHere** [comment]
That's fantastic news! The new version should have the `all` part of `/ess dump all`. Kindly provide us with the latest dump and we'll have a look at it.

**Comment by HypiMC** [comment]
Created server dump: https://essentialsx.net/dump.html?id=8cf309365b6b44efbc4b7d987f8f4b13

**Comment by LaxWasHere** [comment]
Great! Have you made sure they don't have the `essentials.fly` permission on that specific world they teleported to? Would you mind giving us your `/lp editor` link?

**Comment by HypiMC** [comment]
How can I make in luckperms permission on that specific world when they teleport. And wheere can I send you link, I don't want to be public my link.

**Comment by ImDarkLaw** [comment]
You can use [LuckPerms contexts](https://luckperms.net/wiki/Context) to allow or deny permissions on a per-world basis. Additionally, it's safe to share your [editor](https://luckperms.net/wiki/Web-Editor) link publicly. We wouldn't be asking otherwise.

**Comment by HypiMC** [comment]
Thanks a lot. I fixed my problem. I change in luckperms as you said and It workds. Thanks.

**Comment by HypiMC** [comment]
Fixed my problem.
