### ISSUE TITLE
"essentialdiscord" second discord server

### ISSUE THREAD

**Issue by Yumileashen** [EssentialsX/Essentials#5429]
### Feature description

is it possible to make a second discord server with essentialdiscord?

sync channel between discord server

### How the feature is useful

so other player dont need to join in second discord server

**Comment by TetraTheta** [comment]
I don't think it would be 'common use case' for EssentialsX Discord module.

I don't quite understand how it would work, but if you want to relay chats between two different discord guild, you can write a separate discord bot with Message Content Privileged Intent and post messages between guilds with Webhooks. One for first guild, one for second guild.

But this would be not related to EssentialsX. You'll have to write your bot on your own and host it.

**Comment by mdcfe** [comment]
Bridging two Discord servers is definitely out of scope for EssentialsX Discord.
