### ISSUE TITLE
Problem with /heal (1.20.1)

### ISSUE THREAD

**Issue by aurel85** [EssentialsX/Essentials#5434]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

*

### Error log (if applicable)

/

### Bug description

Hi,

With the essentials.heal permission, /heal no longer works unless you are op.

### Steps to reproduce

1 : Give permission essentials.heal
2 : Make the command /heal for no op
3 : error: you do not have permission

### Expected behaviour

The command heal the player.

### Actual behaviour

Error, no heal for the player.

**Comment by JRoy** [comment]
Heal works as expected, you didn't give an error plus you're also using an unsupported plugin, MysqlPlayerDataBridge

**Comment by aurel85** [comment]
The solution is very simple with you :)

For those who have the same problem the guilty is WorldGuard : 
![Capture](https://github.com/EssentialsX/Essentials/assets/24486147/069a25fa-1361-4593-966f-fd98cf6ded74)
Modify commands.yml with :
  heal:
  - essentials:heal $1-
  
And everything is ok !
