### ISSUE TITLE
Buy/Sell system using Signs but Stock in Chest / not unlimited

### ISSUE THREAD

**Issue by ramanzxo** [EssentialsX/Essentials#5436]
### Feature description

i want to make a buy and sell signs but using only have stock not unlimited.thankyou.

### How the feature is useful

its useful for me and my team because we're working on this server currentl;y and want to have a buy and sell system quite easyly.thankyouu

**Comment by LaxWasHere** [comment]
Just make a trade sign?

**Comment by JRoy** [comment]
As stated above, use a trade sign. You can see a tutorial here: https://wiki.mc-ess.net/wiki/Sign_Tutorial#Trade_Sign
