### ISSUE TITLE
Kits and warps and spawn NOT WORKING

### ISSUE THREAD

**Issue by Afkmcrealspro** [EssentialsX/Essentials#5437]
### Type of bug

Data loss

### `/ess dump all` output

https://essentialsx.net/dump.html?id=b3507d28e23943b88e0cc2e1ea0c5fc7

### Bug description

i did it in a set way, warps calibration kits and spawn stopped working

### Steps to reproduce

1: it didn't work when someone typed spawn or typed "/kits legendary" and typed "spawn" all of these were working but no longer working the same way including warps

### Expected behaviour

1:should give items to kits by pressure
2:When you type spawn, it should teleport to the spawn.
3:When you type warps casino, you must teleport to the casino.

### Actual behaviour

1:it won't work when someone writes kits legendary
2:typing spawn won't go to spawn
3:Warps can't go anywhere when I type warps [name]

**Comment by JRoy** [comment]
I don't see you using any of those commands in the logs you provided and you have no `legendary` kit. CMI likely is overriding those commands, uninstall it.
