### ISSUE TITLE
/tptoggle display error

### ISSUE THREAD

**Issue by Wumor** [EssentialsX/Essentials#5439]
### Type of bug

Data loss, Compatibility issue, Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=1da1c7f48f1c4f288cdca1aac6209ac7

### Bug description

When using /tptoggle disable and /tptoggle enable, only the same output is displayed, which does not clearly show whether the transmission status is turned off.

Actually the command was executed correctly, but there was a problem with the display of the output

### Steps to reproduce

Enter the command in the game: /tptoggle disable, then enter /tptoggle enable

### Expected behaviour

/tptoggle disable has transmission disabled, and /tptoggle enable has transmission enabled

### Actual behaviour

Whether you type /tptoggle disable or /tptoggle enable indicates that transmission is disabled

**Comment by LaxWasHere** [comment]
Could you provide us with pictures of the messages you described.

**Comment by Wumor** [comment]
> 

<img width="1280" alt="Snipaste_2023-07-23_15-53-56" src="https://github.com/EssentialsX/Essentials/assets/49808961/cf7ef1f7-bc9d-4ef3-832a-c11a03489dad">

**Comment by Wumor** [comment]
@LaxWasHere Regardless of which one I enter, the disabled status is displayed

**Comment by LaxWasHere** [comment]
[Confirmed.](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/resources/messages_zh.properties#L1252-L1255)

Thanks for the report, we'll get this sorted out in crowdin. If you wish to be the one to fix it, you can contribute to our crowdin here <https://crowdin.com/project/essentialsx-official>

**Comment by pop4959** [comment]
Please submit a corrected translation on Crowdin and I can approve it. Thanks!

**Comment by Wumor** [comment]
@pop4959 I have submitted, please approve.

**Comment by Wumor** [comment]
@pop4959 
<img width="1239" alt="Snipaste_2023-07-23_20-40-50" src="https://github.com/EssentialsX/Essentials/assets/49808961/15dd500c-62aa-4867-98c9-2bdba82a5e0d">

**Comment by Wumor** [comment]
@pop4959 The submitted content has been modified correctly, when will it take effect on my server？

**Comment by pop4959** [comment]
> @pop4959 The submitted content has been modified correctly, when will it take effect on my server？

I've merged the Crowdin PR so the new translation will be available in the latest dev build.
