### ISSUE TITLE
Can't use Worldedit's mod command since i have essentialsX

### ISSUE THREAD

**Issue by JLSkyzer** [EssentialsX/Essentials#5444]
### Type of bug

Compatibility issue

### `/ess dump all` output

https://essentialsx.net/dump.html?id=43be7faf6f0c4123b1ae979dddfbae4d

### Bug description

Hey !

When i try to use command from the mod "WorldEdit" i have this error:
![image](https://github.com/EssentialsX/Essentials/assets/60830349/447a81ab-be6e-48af-9ef5-2f4ff2af9fa4)
When i disable EssentialsX from my server, all worldedit's mod command work

### Steps to reproduce

- Install Mohist 1.16.5 last build
- Install EssentialsX Plugin
- Install WorldEdit Mod

### Expected behaviour

I can set block, get info of block with /info, can calc etc..

### Actual behaviour

Nothing just error..

**Comment by ImDarkLaw** [comment]
Hey there,

EssentialsX does not support Mohist and we may not provide any support for incompatibility issues with such hybrid software, as stated in the main [EssentialsX Downloads Page](https://essentialsx.net/downloads.html).

For further information as to why that is, feel free to check out the page clicking [here](https://essentialsx.net/do-not-use-mohist.html).
