### ISSUE TITLE
N/A

### ISSUE THREAD

**Issue by JoniDev25** [EssentialsX/Essentials#5448]
N/A

**Comment by JoniDev25** [comment]
N/A

**Comment by Evidentsinger14** [comment]
Hey @JoniDev25 - Looking at your config, it does indeed have an error. Line 309 in [your paste](https://paste.gg/p/anonymous/e156f0a5e8a545928711c5e34a031ee8)
```
list:
owner
admin
...
```
Should actually be
```
list:
    Owner: owner
    Admin: admin
  ...
```
> Oh Yeah And I Lost The Deletion Key Of The EssentialsX Dump.
> I Hope That A Mod Could Delete The Dump After That.

The deletion key can be found in your server logs, right after the message with the link to the dump. You will have to do that, that key is from paste.gg, so it's not something we can do anything about.

**Comment by JoniDev25** [comment]
Ok Thank You.
One More Problem.
After I Fixed The List Thing, It Says That Other Mistakes Exist with "ops-name-colot" line and stuff

**Comment by JoniDev25** [comment]
Could you please do the reproduction steps, fix the problems and fix other occuring bugs

**Comment by JoniDev25** [comment]
And tell me all that i should change

**Comment by JoniDev25** [comment]
Thank you very much

**Comment by Evidentsinger14** [comment]
Multiple broken lists in config, responding on discord. working as intended.

**Comment by JoniDev25** [comment]
Ok Thank You
