### ISSUE TITLE
[1.9] Tablist Updates to display displayname forcibly!

### ISSUE THREAD

**Issue by MrCleverTrevor2** [EssentialsX/Essentials#545]
I have tested this issue with Essentials on and without and it only happens when essentialsx is on the server. It happens when the display name is changed it also updates the tablist. Which i do not want it because it makes things like prefixs show on tablist. I have tested this a lot to try and fix it and it isnt working. There is an option called change-playerlist which is default disabled due to a comment mark, i enabled it and put false. It works like this even while option is still commented. I have reset the config and updated the plugin and nothing works. Please solve this fast as it is a major issue on my server. I have attached a screenshot of exactly what is going on.
![2016-04-01_17 16 28](https://cloud.githubusercontent.com/assets/12944303/14223079/7a2670ae-f82e-11e5-8e8d-cf55c9ed4ecb.png)

**Comment by drtshock** [comment]
Can you tell me:
1. Expected behavior
2. Behavior you see
3. What you did to get that behavior
4. Spigot version
5. Essx version.

**Comment by MrCleverTrevor2** [comment]
1) Username not to be updated with nickname
2) Username being update to nickname
3) Nothing. 
4) Latest.
5) Latest.

**Comment by drtshock** [comment]
can't help you if you're not willing to help me.
