### ISSUE TITLE
Running commands using usernames of players offline since upgrading to 1.20+ cannot find player data

### ISSUE THREAD

**Issue by TheNamesSkylar** [EssentialsX/Essentials#5455]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=650ed3a94749449a830607c802d738da

### Bug description

Running any Essentials commands on player USERNAMES that have not come online since upgrading to 1.20+ returns "Player not found" error. Within testing, it appears players with server op at time of upgrade are not affected by this.

Running the same commands using UUIDs in lieu of usernames will function as intended

### Steps to reproduce

1. Have an account join a server running 1.19.4 or prior
2. Upgrade server to 1.20 or higher
3. Run /seen [Username]

### Expected behaviour

Running commands ie /seen [Username] should return when the player was last online.

### Actual behaviour

![image](https://github.com/EssentialsX/Essentials/assets/121773383/aff0ceaa-ef00-4a14-8563-936985c94437)

**Comment by JRoy** [comment]
Could you please upload all the files in `plugins/Essentials/userdata` as well as your `plugins/Essentials/usermap.bin`  & `plugins/Essentials/uuids.bin` files. You can send them in private by joining our support discord [here](https://discord.gg/PHpuzZS) and DMing out bot Chester. Once you've done this please let me know.

**Comment by TheNamesSkylar** [comment]
Thanks! Sent it over from `@thenamesskylar`
