### ISSUE TITLE
Command in kits

### ISSUE THREAD

**Issue by MrRoboo** [EssentialsX/Essentials#546]
The essentials document says:

"Allow commands in kits and use {player} to replace with player's name."

But how can I set a command in a kit?

**Comment by drtshock** [comment]
read the wiki

**Comment by MrRoboo** [comment]
The wiki doesnt even explain how to use commands in the essentials kits...
It just says "Allow commands in kits and use {player} to replace with player's name."
But how do you add a command in the essentials kits...

**Comment by drtshock** [comment]
Sorry, thought it was a bit more detailed.

Just put the command in there so like `/give {player} diamond 1`
