### ISSUE TITLE
essentials.repair and essentials.repair.enchanted not working when applied with luck perms

### ISSUE THREAD

**Issue by saminator0107** [EssentialsX/Essentials#5460]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=f8ae608f26bf4f8a8bbf8d8e2204ef62

### Bug description

essentials.repair and essentials.repair.enchanted not working when applied with luck perms.

### Steps to reproduce

apply the 2 permissions stated above using luck perms.

### Expected behaviour

the held item should be repaired

### Actual behaviour

Player runs the command /repair and does not have the permission to use the command. I am not sure why this is happening
![noperms](https://github.com/EssentialsX/Essentials/assets/132668102/46d06103-e4b6-4e73-ba02-1329c762fced)
![no perms luckperms](https://github.com/EssentialsX/Essentials/assets/132668102/7047b422-2930-42c0-bbd2-ba16402b6a15)

**Comment by JoniDev25** [comment]
Are You An Operator?

**Comment by JoniDev25** [comment]
When you run the command

**Comment by JoniDev25** [comment]
It might be because 
![image](https://github.com/EssentialsX/Essentials/assets/122311752/3707f5b5-57c4-4f47-a515-a5a6027c04f1)
EssentialsX Is Outdated

**Comment by saminator0107** [comment]
Its another player that is not opped. and let me try updating the plugin rn.

**Comment by saminator0107** [comment]
It still did not work.

new ess dump: https://essentialsx.net/dump.html?id=963a7504809c47f5b8790e04432e2dc3

**Comment by Evidentsinger14** [comment]
That is not an EssentialsX No-Permission message, are you using a modified locale file? (Should be a file in your Essentials folder called “messages.properties”)

**Comment by LaxWasHere** [comment]
![image](https://i.imgur.com/KDcthrW.png)

**Comment by ImDarkLaw** [comment]
The **AEFixItemRepairing** plugin on your server is taking over `/repair` command handling, not EssentialsX. 

Moreover, your EssentialsX addons are not matching versions with your core Essentials plugin. Considering your server's running on Paper 1.20.1, please update all Essentials plugins to latest [dev build](https://essentialsx.net/downloads.html?branch=dev).

![image](https://github.com/EssentialsX/Essentials/assets/44745161/a7a35316-6727-402e-aed3-de5896956c73)
