### ISSUE TITLE
Messages_en.properties changes

### ISSUE THREAD

**Issue by RazihelYT** [EssentialsX/Essentials#5474]
### Feature description

I am suggesting the ability to change the colours UUID, Playtime, and Speed info on the [/whois <player>] command in the messages_en.properties file. As well as the output for the [/mail read] command, the colours for the output on a player's mail is not changeable in the messages_en.properties file and will always read out in gold.
![image](https://github.com/EssentialsX/Essentials/assets/15030460/ac3cd096-0c10-4152-87ad-e110af0c7343)
![image](https://github.com/EssentialsX/Essentials/assets/15030460/d0839519-b798-41e1-b0cd-562b7c49c74c)

### How the feature is useful

It would give server owners the ability to match server messages to their server's theme/colours that they use.

**Comment by LaxWasHere** [comment]
They clearly [exist](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/resources/messages.properties#L1545-L1571), you just have an outdated locale file.
