### ISSUE TITLE
Allow /back for non-essentials teleports

### ISSUE THREAD

**Issue by not-3than** [EssentialsX/Essentials#5478]
### Feature description

Currently, /back only works when using teleportation commands from within Essentials. What I'm asking for is /back so that it works for all teleportations instead of only thru Essentials, so it can be more compatible with other plugins.

### How the feature is useful

Makes /back more useful because I often times try and do /back when I used a teleportation command outside of Essentials and get teleported back to somewhere I was 10-30 minutes prior (Since I only use essentials for /tp)

**Comment by pop4959** [comment]
Enable `register-back-in-listener` in config.yml which will do this.
