### ISSUE TITLE
Ignoring specific player tpa requests.

### ISSUE THREAD

**Issue by Botanistt** [EssentialsX/Essentials#548]
Title says it all.
I suggest adding command to block specific player from sending tpa requests instead of using /tptoggle.
Thanks.

**Comment by drtshock** [comment]
Does /ignore not apply to this?

**Comment by Botanistt** [comment]
But what If I want to ignore only teleportation requests from this player but want to see messages from this player?

**Comment by drtshock** [comment]
Doesn't sound like a very common / reasonable use case.
