### ISSUE TITLE
Essentials will not log any more warnings for net.citizensnpcs.nms.v1_19_R3.entity.EntityHumanNPC$PlayerNPC.

### ISSUE THREAD

**Issue by kailingma** [EssentialsX/Essentials#5480]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=1100275d10b14ec9b83ac7daa42e573e

### Bug description

I use citizens and for a while essentials has been putting console outputs like this:
`[01:54:03 INFO]: [Essentials] Created a User for Archer (e99efdd5-dadd-267e-a199-46f401f95ea7) for non Bukkit type: net.citizensnpcs.nms.v1_19_R3.entity.EntityHumanNPC$PlayerNPC`
After doing this a couple hundred times, it stopped with this message. (To be clear, it would spit out the text above at random times, and it never bothered me. I just ignored it)
`[01:54:03 WARN]: [Essentials] Essentials will not log any more warnings for net.citizensnpcs.nms.v1_19_R3.entity.EntityHumanNPC$PlayerNPC. Please report this to the EssentialsX team.`
![image](https://github.com/EssentialsX/Essentials/assets/61745860/da0cb898-a7e9-46a0-8328-8fe586d0ff36)

### Steps to reproduce

Use essentials with citizens and create some pathfinding npcs and wait a couple weeks

### Expected behaviour

`[01:54:03 INFO]: [Essentials] Created a User for Archer (e99efdd5-dadd-267e-a199-46f401f95ea7) for non Bukkit type: net.citizensnpcs.nms.v1_19_R3.entity.EntityHumanNPC$PlayerNPC`

### Actual behaviour

[01:54:03 WARN]: [Essentials] Essentials will not log any more warnings for net.citizensnpcs.nms.v1_19_R3.entity.EntityHumanNPC$PlayerNPC. Please report this to the EssentialsX team.

**Comment by JRoy** [comment]
Outdated

**Comment by Vlader97** [comment]
It still happens on the latest version 2.20.1.
`[12:43:10] [Server thread/INFO]: [Essentials] Created a User for Survival (20160b2a-b3a6-2bbb-9bc4-8dc3216a08bb) for non Bukkit type: net.citizensnpcs.nms.v1_20_R1.entity.EntityHumanNPC$PlayerNPC`
This should be a debug message.

**Comment by mdcfe** [comment]
This message is not a debug message because it makes it difficult to pin down userdata errors. By the time improper OfflinePlayer types could have caused actual damage to userdata, it would be too late to enable debug and capture a log because the data has already been created/overwritten. Citizens NPCs ideally shouldn't get passed to the userdata system in the first place.
