### ISSUE TITLE
EssentialsX "generated an exception" error after /essentials reload.

### ISSUE THREAD

**Issue by xGioChR** [EssentialsX/Essentials#549]
Hello!
Today I saw this error in my console:
"
[20:26:14 WARN]: [Essentials] Task #722 for Essentials v2.0.1-b320 generated an exception
java.lang.NullPointerException

"
How can this issue be solved?
Thank you!

**Comment by drtshock** [comment]
Can you paste the full stack trace please

**Comment by techied** [comment]
hm

looks like EssentialsX is trying to call a variable that hasn't been initialized xD
nice one                    <3 nullpointerexception
