### ISSUE TITLE
Error occurred while enabling EssentialsDiscordLink v2.20.1 (Is it up to date?)

### ISSUE THREAD

**Issue by MrMeowzz** [EssentialsX/Essentials#5493]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=7ecd6564f22042b2ac3f6e8a28d559e7

### Error log (if applicable)

https://paste.gg/p/anonymous/9186601efc4b4649a6e39742bfdc0681

### Bug description

After updating to v2.20.1 (stable version) from v2.20, EssentialsDiscordLink always errors now when I start the server and never enables.
I tried the dev version and it errors as well.
I also noticed that the bot doesn't start running as well.

### Steps to reproduce

1. Start the server
2. See if it enables correctly with no errors in the console?

### Expected behaviour

Plugin enables correctly without errors

### Actual behaviour

Plugin errors and doesn't enable correctly

**Comment by LaxWasHere** [comment]
You must enable intents as stated in the essx discord tutorial, here's some [simple instructions](https://jda.wiki/using-jda/troubleshooting/#im-getting-closecode4014-disallowed-intents) on how.
