### ISSUE TITLE
EssentialsX spam [Essentials] Essentials updated the underlying Player object for <playeruuid> on console

### ISSUE THREAD

**Issue by ObsidianMC123** [EssentialsX/Essentials#5494]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=e08f88cdc6544528bf7ff719bd1c4c06

### Error log (if applicable)

https://paste.gg/p/anonymous/eab0cd452d0f45418bf5318e76aa73a3

### Bug description

Idk it just make the console spam

### Steps to reproduce

when server start

### Expected behaviour

The console ultra lagging and player got kicked randomly

### Actual behaviour

idk when i started the server the essentails spam console

**Comment by LaxWasHere** [comment]
This is fixed on the latest development build, you may download it [here](https://essentialsx.net/downloads.html).
