### ISSUE TITLE
`essentials.time.world.[world]` permission not being checked

### ISSUE THREAD

**Issue by thiago-solfo** [EssentialsX/Essentials#5500]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=64fc502742034ea1b8987764820961b3

### Bug description

It is possible to change another world time even with essentials.time.world permission
[A similar error was described in the old Essentials](https://github.com/EssentialsX/Essentials/issues/173)

![image](https://github.com/EssentialsX/Essentials/assets/61445366/af9790d9-f782-4820-8446-4699c6b98e50)

### Steps to reproduce

1. Create a second world and enter (example: flat)
2. Set the `essentials.time`, `essentials.time.set` and `essentials.time.world.flat` permissions
3. Test the `/day day world` command in the flat world
4. The permission doesn't work as it should and allows the command run on worlds other than flat

### Expected behaviour

Permission error message

### Actual behaviour

Command executed

**Comment by mdcfe** [comment]
Hi there, the server that hosts dumps is currently offline.
Is there any chance you could [paste](https://pastes.dev/) your `plugins/Essentials/config.yml`? There should be a `world-time-permissions` option that needs enabling before EssentialsX will check the world permissions.

**Comment by JRoy** [comment]
`world-time-permissions: false` is disabled in config
