### ISSUE TITLE
Missing Items for Worth.yml (And /setworth)

### ISSUE THREAD

**Issue by Unipotatoo** [EssentialsX/Essentials#5502]
### Type of bug

Compatibility issue

### `/ess dump all` output

https://essentialsx.net/dump.html?id=5df536ad673947e3a62dec3815aaf0ec

### Bug description

Im setting up an economy for my server and realized some of the newer items are not available to be sold to the server. The list of things Ive tried, and cant get working are

Torchflower
Pitcher_Plant
Pitcher_Pod

### Steps to reproduce

Try to set the worth of them in config or ingame, it doesnt work

### Expected behaviour

You can set the worth and sell the item

### Actual behaviour

You can not set the worth and sell the item

**Comment by Evidentsinger14** [comment]
these items exist in the default [items.json](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/resources/items.json) file. Please stop your server, delete `/Essentials/items.json`, and re-start your server, and see if that fixes your issue.

**Comment by Evidentsinger14** [comment]
Going to assume this is fixed. closing
