### ISSUE TITLE
Help me please with this cash report of EssentialsX, and i have te update 2.20.1 of the plugin

### ISSUE THREAD

**Issue by iBronHD** [EssentialsX/Essentials#5503]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=4604ac97536a4d19836789fa4345a886

### Error log (if applicable)

https://paste.gg/p/anonymous/3625eed44a54425e89336af7f1f7b01e/files/cc9990466a45426da6ec3ebfd02c8893/raw

### Bug description

When running warp, the server drop a crash report and lag all server, need help 

### Steps to reproduce

/warp
/home
/tpa

### Expected behaviour

That players are transported without causing lag on the server and without issues.

### Actual behaviour

drop a crash report and causing lag on the server

**Comment by pop4959** [comment]
Nothing here in your crash report suggests that there is an issue with Essentials. It looks like your server may just be struggling to load chunks. Please join the Discord server if you are still having trouble with this and you can troubleshoot more there if needed.
