### ISSUE TITLE
Support for Mini messages and Motd delay

### ISSUE THREAD

**Issue by Abasing** [EssentialsX/Essentials#5506]
### Feature description

How about adding support for Mini Messages or JSON support in MOTD.txt, and also Motd delay?

### How the feature is useful

There are no better plugins, and the plugin is named Essentials and has Motd.txt why not json and/or mini messages support?

**Comment by LaxWasHere** [comment]
[It's already slated for the next update.](https://github.com/EssentialsX/Essentials/pull/4717)
