### ISSUE TITLE
Add intermediate level of teleportation toggle

### ISSUE THREAD

**Issue by RealSuperRyn** [EssentialsX/Essentials#5508]
### Feature description

Allows players to request teleportation (e.g. /tpa) but be unable to teleport without permission (e.g. /tp). TP being completely disabled would be /tptoggle low, generic teleportation being disabled with teleportation asking being enabled would be /tptoggle mid, TP being completely enabled would be /tptoggle high

### How the feature is useful

Would remove the need for alternative commands to /tpa (e.g. /ride) when someone's TP is disabled. You would still be able to disable requests, but you would also be able to keep requests on.

Scenario A (current implementation):

Person A: /tpa B

_B has teleportation disabled._ 

Person A: B, can you toggle TP on rq?

Person B: Sure!

Person B: /tptoggle enable

Troll: /tp B

Person A: /tpa B

Person B: /tptoggle disable

(The troll proceeds to grief the area he teleported into)

Scenario B (proposed implementation):

Person B: /tptoggle mid

Person A: /tpa B

B: /tpaccept

Troll: /tp B

B has instant teleportation disabled.

Troll: /tpa B

B: /tpdeny

(The troll does not manage to grief B's area.)

**Comment by pop4959** [comment]
It seems like the main problem here is that you're giving players access to `/tp` by default. Removing permission for that fixes your example scenario since an untrusted 3rd party will not be able to directly teleport.

You shouldn't think of `/tptoggle` as a way to protect players from teleports. It is simply a way of saying "I don't want others to teleport to me right now."

If the purpose of granting `/tp` was to avoid requiring teleportation requests, that can already be done using the `/tpauto` command, which automatically accepts teleportation requests. This practically makes `/tpa` the same as `/tp` if the player is okay with others instantly teleporting to them.

**Comment by RealSuperRyn** [comment]
> It seems like the main problem here is that you're giving players access to `/tp` by default. Removing permission for that fixes your example scenario since an untrusted 3rd party will not be able to directly teleport.
> 
> You shouldn't think of `/tptoggle` as a way to protect players from teleports. It is simply a way of saying "I don't want others to teleport to me right now."
> 
> If the purpose of granting `/tp` was to avoid requiring teleportation requests, that can already be done using the `/tpauto` command, which automatically accepts teleportation requests. This practically makes `/tpa` the same as `/tp` if the player is okay with others instantly teleporting to them.

I guess a better way to phrase this then would be as an option like this: "/tp and /tpa", "/tpa only", "no teleports"

**Comment by pop4959** [comment]
> I guess a better way to phrase this then would be as an option like this: "/tp and /tpa", "/tpa only", "no teleports"

You don't need to rephrase, I completely understand the suggestion here, but you will need to provide a better argument for why this is a necessary feature if you want it considered. The point I was trying to make above is that the kind of setup you have (granting *both* `/tp` and `/tpa`) is not standard practice and suitable alternatives already exist. If those alternatives are not acceptable, can you explain why?

**Comment by pop4959** [comment]
Closing since there is no further response here. If the provided solution is not sufficient, let us know.
