### ISSUE TITLE
Vanish uses incorrect potion attributes

### ISSUE THREAD

**Issue by Cats1337** [EssentialsX/Essentials#5509]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=28b0028769fb47038ced378ea0d1caff

### Bug description

this.getBase().addPotionEffect(new PotionEffect(PotionEffectType.INVISIBILITY, **Integer.MAX_VALUE**, 1, **false**));
false shows effect particles making the vanished player visible to anyone paying attention. Since 1.20 allows the value of infinite to be set for the potion time setting MAX_VALUE still displays the effect icon whereas infinite doesn't

### Steps to reproduce

1. /vanish, /v, /ev, /evanish, etc.
2. Potion Particles appear
3. Potion icon appears on screen 

### Expected behaviour

The player should be entirely invisible without particle effects, and no clutter of potion icons on the screen.

### Actual behaviour

The player's Invisibility particles appear, and the time is just set to an integer limit

**Comment by mdcfe** [comment]
Potion particles are intended to be visible to players who can see vanished players. Could you clarify how your permissions were set up when you tested this?

**Comment by Cats1337** [comment]
Sorry for the delayed response. Potion particles should just be hidden, I've had people without permission able to see my particles. The other things is just the time can be applied as Infinite now.

**Comment by pop4959** [comment]
No worries, thanks for responding. To clarify, Essentials _only_ adds a potion effect to the vanished player when the permission `essentials.vanish.effect` is granted. It is implied that you are giving this permission if you are seeing this.

If you believe there is a bug, please run `/lp verbose <username> & essentials.vanish` and see what permissions are being checked to confirm whether it is configured properly.

**Comment by pop4959** [comment]
Closing this for now; if you believe this is still a bug let us know. It's most likely just permission related though.
