### ISSUE TITLE
Players can nick with RGB without proper permissions using legacy format

### ISSUE THREAD

**Issue by SiuanSong** [EssentialsX/Essentials#5513]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=8afacf8fc45c4f2cb9a6c3a67be5c12a

### Bug description

Players without essentials.nick.rgb can use legacy color format (&x&r&r&g&g&b&b) to color their nicknames with rgb colors. 
Legacy Format Generator here: https://www.birdflop.com/resources/rgb/

### Steps to reproduce

1. Give player essentials.nick and essentials.nick.color
2. Use birdflop in Legacy output mode to create an RGB name
3. Run /nick [legacy output] in game

### Expected behaviour

RGB color coded nicks to be blocked

### Actual behaviour

RBG color coded nicks are not blocked :(

**Comment by Evidentsinger14** [comment]
![image](https://github.com/EssentialsX/Essentials/assets/46200123/5d9b4029-d763-4f1b-834d-3daad1d92f17)
Unable to reproduce behavior. Please test only using EssentialsX, LuckPerms, Vault and officially supported addons. 
(in config, i enabled `ignore-colors-in-max-nick-length` as well as increased the max nick length to 100 so these were not limiting factors)
