### ISSUE TITLE
Keep effects on death

### ISSUE THREAD

**Issue by Abasing** [EssentialsX/Essentials#5514]
### Feature description

Can you please add keep effect on death please?

### How the feature is useful

essentials.keepeffect

**Comment by pop4959** [comment]
Can you explain why this feature would be useful to a wider audience (e.g. Essentials users at large)? This seems to be yet another niche gap that can be filled using another existing plugin or with a minimal custom plugin of your own.

**Comment by pop4959** [comment]
Closing due to no response.
