### ISSUE TITLE
Implement allow commands in jail

### ISSUE THREAD

**Issue by kokqi** [EssentialsX/Essentials#5518]
### Feature description

like 

- /customtext
- /afk

etc

basically what im requesting is just allow selected commands in jail

### How the feature is useful

useful when someone use /customtext or /afk to refresh luckperms prefix/suffix for EssentialsX

**Comment by LaxWasHere** [comment]
This can be a achieved by giving the `essentials.jail.allow.<command>` permission.
For a list of all EssentialsX permission, go [here](https://essinfo.xeya.me/permissions.html).
