### ISSUE TITLE
player balances randomly to $0

### ISSUE THREAD

**Issue by MinecraftedGaming** [EssentialsX/Essentials#5521]
### Type of bug

Data loss

### `/ess dump all` output

https://essentialsx.net/dump.html?id=5a32f156cd11427cac7102e38f72da7a

### Error log (if applicable)

none

### Bug description

for some reason players on the my 1.19 paper server are having issues with account balances setting to 0 randomly after server resets/reloads, the current economy plugins are essentials vault and auto-tune, im running latest version of all plugins and cant find the issue resulting in players having to store money in emerald form(as that is locked in auto-tune)

### Steps to reproduce

get money in the server
wait for a server reset

### Expected behaviour

have money
reset server
still have money

### Actual behaviour

have money
reset server
money gone

**Comment by LaxWasHere** [comment]
If `/ess dump all` is not a command on your version then you are not using the latest version.

If you're trying to `/reload` don't. That will cause resets.

**Comment by MinecraftedGaming** [comment]
ees dump worked after waiting a bit
https://essentialsx.net/dump.html?id=5a32f156cd11427cac7102e38f72da7a

**Comment by LaxWasHere** [comment]
![reload](https://i.imgur.com/fgBOZUI.png)
![no help](https://i.imgur.com/msTpxZk.png)

Like I said, don't reload.

**Comment by MinecraftedGaming** [comment]
this is not completed this happens even without reload reopen this

**Comment by mdcfe** [comment]
You did reload and that is almost guaranteed to break userdata.

Please provide full repro steps with logs, screenshots from in-game and a dump, showing the issue occurring on a server that has not been reloaded at any point. Once these are provided we can reopen the issue.

**Comment by MinecraftedGaming** [comment]
update: i found the issue and fixed it myself... thanks for the non-existent help
(no it wasnt caused by reloads it was something else unrelated to that)

**Comment by pop4959** [comment]
Can you explain what caused your issue in case other people encounter it in the future?

We want to help, but in cases like this it is difficult without more information. Also, if this is actually a bug in Essentials we will gladly re-open this issue.
