### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "String.toLowerCase()

### ISSUE THREAD

**Issue by PlayGlowCraft** [EssentialsX/Essentials#5525]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=d78b5b49b7314845820033ee5409fd83

### Error log (if applicable)

https://paste.gg/p/anonymous/1226cb22e7a74be09b203d734de200e7

### Bug description

When using quickshops discord extension i get this error when interacting with a shop.

### Steps to reproduce

Click on Shop using Quickshop-Hikari

### Expected behaviour

Should Report Embed to Discord without eror

### Actual behaviour

I recieve Error in the Console as posted above

Running latest stable Versions of all Plugins and Server Jars

**Comment by pop4959** [comment]
It looks like QuickShop just updated their Vault implementation to accept usernames. Considering that the error you've reported here deals with a null username being passed through, which should never happen, this is something you should report to them in spite of the warning message telling you to do otherwise.

**Comment by PlayGlowCraft** [comment]
I also have a ticket open for them on there Discord.

**Comment by pop4959** [comment]
Did you hear anything back @PlayGlowCraft? If not we'll just assume this is an issue with QuickShop and there is nothing to be done on our side.

**Comment by PlayGlowCraft** [comment]
My Apologies you can Close this We Found out that the error had to do with a shop being registered to a made up account instead of an actual registered playername.
