### ISSUE TITLE
@e not possible

### ISSUE THREAD

**Issue by wwinbb** [EssentialsX/Essentials#5529]
### Feature description

I have a bunch of pre-written command blocks for bosses on a server with essentialsx pluged in. I dont want to take it off but i need to be able to use @e in the command blocks. Is there any way I can fix this, like a other plugin or something. I dont need the * as a sub-command.

Also I cant use /minecraft:@e or any other stuff like that so pls dont suggest it

### How the feature is useful

becuase command blocks wont work, and its all around easier to get rid of mobs of a certain name, type, value or anything like that without having to use the /minecraft prefix

**Comment by LaxWasHere** [comment]
`/minecraft:command`

**Comment by pop4959** [comment]
Selectors can only be used in Minecraft commands, not in Essentials commands, as mentioned above.

If you need help with this, please join our [Discord server](https://discord.gg/h8CnPSw).
