### ISSUE TITLE
[Suggestion] First Join Kit (Automatic Armor Equip)

### ISSUE THREAD

**Issue by BiGUNMAN** [EssentialsX/Essentials#553]
It would be awesome to see an addition to the "kit on first join" where if the first 4 configured items are armor they will automatically be equipt into one's armor slot.

**Comment by drtshock** [comment]
added https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/config.yml#L794

**Comment by BiGUNMAN** [comment]
@drtshock I'm aware of the kit on first join, but I am addressing the automatic armor equipping for the kit.
