### ISSUE TITLE
/kill

### ISSUE THREAD

**Issue by rejomy** [EssentialsX/Essentials#5531]
### Feature description

I want a player to be able to kill himself via /kill

### How the feature is useful

I want a player to be able to kill himself via /kill

**Comment by pop4959** [comment]
The command `/kill` is provided by vanilla, it is not an Essentials command. Essentials has a similarly named `/suicide` command which can be given to players instead if you want, granting the respective permission via a permission plugin such as LuckPerms.

**Comment by rejomy** [comment]
> The command `/kill` is provided by vanilla, it is not an Essentials command. Essentials has a similarly named `/suicide` command which can be given to players instead if you want, granting the respective permission via a permission plugin such as LuckPerms.

Is it so fucking hard to do a /kill to kill yourself?

**Comment by rejomy** [comment]
Where's the fucking essentials.kill.others?

**Comment by pop4959** [comment]
As mentioned previously, `/kill` is not an Essentials command. See [Commands/kill](https://minecraft.wiki/w/Commands/kill) on the minecraft wiki and [here](https://bukkit.fandom.com/wiki/CraftBukkit_Commands) for Bukkit permissions.

For help with `/suicide` which _is_ part of Essentials, please join the [Discord server](https://discord.gg/h8CnPSw).

**Comment by mdcfe** [comment]
You can use EssentialsX's `/suicide` to do what you want, or the EssentialsX `/kill <player>` command on either yourself or other players. You can alias those commands to do different things using `commands.yml` if you desire.

Please come back when you've calmed down. There is no need to create spam issues or get aggressive with folks helping you - we do this in our spare time.
