### ISSUE TITLE
Add placeholderapi support to essentialschat

### ISSUE THREAD

**Issue by rejomy** [EssentialsX/Essentials#5532]
### Feature description

Add placeholderapi support to essentialschat

### How the feature is useful

Add placeholderapi support to essentialschat
```[tasklist]
### Tasks
```

**Comment by pop4959** [comment]
This is already being considered in #2391. Please leave any comments or feedback there. Thank you!

**Comment by rejomy** [comment]
> Это уже рассматривается в #2391. Пожалуйста, оставляйте любые комментарии или отзывы там. Спасибо!

And how long will it be "under review"? Until 2025?

**Comment by pop4959** [comment]
There is no specific date, but creating duplicate issues does not expedite the process.
