### ISSUE TITLE
Remove the space in ! message in essentialschat

### ISSUE THREAD

**Issue by rejomy** [EssentialsX/Essentials#5533]
### Feature description

. So that the message doesn't look like "!  message" double-spaced

### How the feature is useful

. So that the message doesn't look like "!  message" double-spaced

**Comment by pop4959** [comment]
Please see the [wiki](https://essentialsx.net/wiki/Locale.html) for information regarding customization of messages.

**Comment by rejomy** [comment]
You do realize this is a plugin problem, right? Entering !message the player will get the format "space message", and entering !message, the player will get the format "double space message", which is already ugly.



> Please see the [wiki](https://essentialsx.net/wiki/Locale.html) for information regarding customization of messages.

**Comment by pop4959** [comment]
If this is a bug report please submit a bug report instead. You gave no explanation here to indicate otherwise. Thanks.
