### ISSUE TITLE
Please notify author of plugin causing this execution to fix this bug!

### ISSUE THREAD

**Issue by ImYenil** [EssentialsX/Essentials#5536]
### Type of bug

Error in console

### `/ess dump all` output

X

### Error log (if applicable)

https://paste.gg/p/anonymous/29b0aa745ed84dd38fabe9f1235e64af

### Bug description

https://paste.gg/p/anonymous/29b0aa745ed84dd38fabe9f1235e64af

### Steps to reproduce

X

### Expected behaviour

X

### Actual behaviour

X

**Comment by LaxWasHere** [comment]
Please contact the author of your survival games plugin for support.
