### ISSUE TITLE
Regarding Command Blocks

### ISSUE THREAD

**Issue by PRMAOU** [EssentialsX/Essentials#5537]
### Type of bug

Compatibility issue, Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=06b89fb4d7b1402cb55727c59726cbc6

### Bug description

When I installed the EssentialsX on my server the Command_Blocks have been set to True, But when I was using the command blocks started showing blue text as when this happens it means its not working, I tried the same thing on different plugins like luckperms, vault and others they were working with the Command blocks, but when I installed and checked with EssentialsX, it seemed to not accept the command blocks commands...so thats why I wanted to know if there is some command in the config.yml or somewhere in the EssentialsX folder to enable or is it just a bug not letting me use the command block and please also let me know if I need a permission to be enabling it when I install the Luckperms with it.

### Steps to reproduce

Before installing the plugin u can run this command in the Command_Block - /give iiRedskulldot stick{Unbreakable:1,RepairCost:0,CustomModelData:9999,display:{color:11415078},AttributeModifiers:[{AttributeName:"generic.attack_damage",Amount:99999999,Name:"generic.attack_damage",UUID:[I;-123911,10103,104540,-20206]},{AttributeName:"generic.attack_knockback",Amount:99999999999,Name:"generic.attack_knockback",UUID:[I;-123911,10203,104540,-20406]},{AttributeName:"generic.attack_speed",Amount:999999999,Name:"generic.attack_speed",UUID:[I;-123911,10303,104540,-20606]},{AttributeName:"generic.knockback_resistance",Amount:99999999999,Name:"generic.knockback_resistance",UUID:[I;-123911,10403,104540,-20806]},{AttributeName:"generic.max_health",Amount:9999,Name:"generic.max_health",UUID:[I;-123911,10503,104540,-21006]}],Enchantments:[{id:bane_of_arthropods,lvl:255},{id:fire_aspect,lvl:255},{id:knockback,lvl:255},{id:looting,lvl:255},{id:sharpness,lvl:255},{id:smite,lvl:255},{id:sweeping,lvl:255},{id:unbreaking,lvl:255}]} 1

this command will work normally without the use of EssentialsX

after that when u r done with it please try installing the EssentialsX in the server and then try using it 
the same command will now be shown in Blue as it was suppose to be showing yellow but its not showing yellow its showing blue.

### Expected behaviour

The expected behaviour of the command block should have been letting me use it in yellow text while typing inside the command block but it shows the blue text which is not letting it enable . So like if possible could u fix that or let me know what I am doing wrong.

### Actual behaviour

The actual behaviour has now turned to blue inside the command_block and when the lever is turned on the command runs it but not gives the item as the text inside it has turned blue. #

**Comment by pop4959** [comment]
It sounds like you are trying to run vanilla /give instead of Essentials /give. Try `/minecraft:give` instead.

**Comment by PRMAOU** [comment]
Ok I will try

**Comment by PRMAOU** [comment]
I did try the method u suggested but it still shows the command blocks input in Blue text even after typing the command /minecraft:give username minecraft:command_block 1

**Comment by JRoy** [comment]
Cannot reproduce. Works when using `minecraft:give`.
