### ISSUE TITLE
Colour Code signs don't work as intended

### ISSUE THREAD

**Issue by skepiaa** [EssentialsX/Essentials#5544]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=0a285a7da72540c6aa6e448afa4e944d

### Error log (if applicable)

N/A

### Bug description

Color Code signs aren't working as intended
![image](https://github.com/EssentialsX/Essentials/assets/68767065/4b721746-260f-46c7-9a34-2830a3155f5a)

### Steps to reproduce

Create a sign and use any minecraft colour code, such as &e &c

### Expected behaviour

It should automatically change the text colour

### Actual behaviour

It only makes the sign show **<color>text**
Like `&ehello` would become `<yellow>hello`

**Comment by LaxWasHere** [comment]
Another plugin is changing the signs, figure out which one and report back to us. Thanks!

**Comment by skepiaa** [comment]
Not really sure which plugin could interfere with the signs, I'll try to find any plugin which may cause this and report back to you shortly.

**Comment by Maksim-Lipenka** [comment]
@JustSkeppYT did you find out what plugin caused this? I face the same issue

**Comment by tirangaming** [comment]
> @JustSkeppYT did you find out what plugin caused this? I face the same issue

Have you found the issue? I am dealing with the same thing.

**Comment by skepiaa** [comment]
Sadly I was never able to find the problem and to this day I still have the issue. I just use /sign set to fix the signs.

**Comment by tirangaming** [comment]
> Sadly I was never able to find the problem and to this day I still have the issue. I just use /sign set to fix the signs.

Alright, Thanks!

**Comment by Evidentsinger14** [comment]
@tirangaming - We recently had someone say this was caused by Oraxen. I am not sure if you run that plugin or not, but it is at least a place to start. Please update if this is the case, would be nice to have for future reference.

**Comment by tirangaming** [comment]
> @tirangaming - We recently had someone say this was caused by Oraxen. I am not sure if you run that plugin or not, but it is at least a place to start. Please update if this is the case, would be nice to have for future reference.

Indeed it was oraxen. In Oraxen settings.yml at formatting section is needed to set the signs to false in order for them to work again with colors.
![image](https://github.com/EssentialsX/Essentials/assets/46293848/0ae2f2f2-a8dd-4395-b3ed-0e3949fdb4cc)
