### ISSUE TITLE
Compatibility issue, Error in console, Other unexpected behaviour

### ISSUE THREAD

**Issue by Wolrockyan** [EssentialsX/Essentials#5545]
### Type of bug

Error in console

### `/ess dump all` output

output

### Error log (if applicable)

https://paste.gg/p/anonymous/1db1fcf4b33543c593ab25f7d2023d31

### Bug description

Nag author: 'Zenexer' of 'Essentials' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process die

### Steps to reproduce

i've installed Build https://github.com/EssentialsX/Essentials/issues/1366 (Mar 5, 2022, 6:35:08 PM)
with git-Paper-221 (MC: 1.18.2)

### Expected behaviour

server should shut down without issue.

### Actual behaviour

server starts fine

stopping the server hangs with the following messages

Nag author: 'Zenexer' of 'Essentials' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.

**Comment by Chew** [comment]
Based on the log you provided

1. Your Essentials version is severely out of date (you have: 2.19.7, current is: 2.20.1)
2. Your Essentials and EssentialsDiscord versions are inconsistent
3. The logs show you're running `Paper version git-Paper-794 (MC: 1.16.5)`
4. The log you provided doesn't show the error you're talking about
5. You didn't provide a proper `/ess dump all`, you just put output?

Please provide a genuine dump (with all) and we can reopen this if it's an issue.

**Comment by Wolrockyan** [comment]
Unfortunately, I cannot do that because my server shut down before it started.

**Comment by pop4959** [comment]
Fix the other errors you have first, and make sure the server can be started. If it doesn't, it's not a surprise that plugins, including Essentials, cannot shutdown properly or safely. If you are still having problems after that, feel free to open a new issue with the information requested above.
