### ISSUE TITLE
Discord: ignore messages from console relay

### ISSUE THREAD

**Issue by GGORG0** [EssentialsX/Essentials#5547]
### Feature description

The same thing as `chat.discord-filter`, but for the **command** relay (running commands from discord using the console channel - `console.command-relay: true`). 

### How the feature is useful

Sometimes the admins want to quickly exchange thoughts and we forget to switch to another channel  so we just end up running like 20 unknown commands (constantly getting replied with `Unknown command. Type "/help" for help.`), or even worse, when the message starts with an actual command name, we can execute something by mistake. 

If this feature was implemented, we could chat normally in the console channel without running commands, by prefixing each message with (for example) an !.

**Comment by Evidentsinger14** [comment]
This doesn't seem like that high of a priority to be added, It may be a better solution to prevent people from sending messages in your console relay channel, and just using the `/execute` slash command in discord.
