### ISSUE TITLE
/potion is broken

### ISSUE THREAD

**Issue by RulerOfEternity** [EssentialsX/Essentials#5549]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=9a48f7a7630544178e7a8ada5efade14

### Bug description

DO NOT CLOSE AS DUPLICATE If permission is granted for essentials.potion and essentials.potion.*, the plugin doesn't let the player run it, there's no problem regarding that if the user has operator status, however, /potion apply is broken regardless of OP Status

### Steps to reproduce

1. Make sure the player is not OP
2. Use a permissions plugin like LuckPerms and grant essentials.potion and essentials.potion.* permissions
3. Attempt to run the commands mentioned earlier.

### Expected behaviour

The potion ought to be modified according to how the command should work (example: /potion effect:wither power:4 duration:86400)
Using /potion apply should give the effects of a potion you're holding in your hand without consuming it

### Actual behaviour

Even if you grant every permission manually with or without the essentials.potion.* (like essentials.potion.absorption), the command doesn't work without OP status. Like I mentioned earlier, /potion apply doesn't give the effect on the held potion without consuming it at all, this command doesn't work even with operator status.

**Comment by mbax** [comment]
I dunno I kind of want to see this closed as duplicate now 🤔

**Comment by RulerOfEternity** [comment]
The thing is, it's a problem on the latest version, meaning the previous bug report is irrelevant since it was closed years ago

**Comment by Evidentsinger14** [comment]
If you use LuckPerms Verbose command, you can see that the permission being checked is `essentials.potions.<potion name>`. Everything i can find in the code is saying this shouldn't be the case, but i am trying to find out why that is the case.
![image](https://github.com/EssentialsX/Essentials/assets/46200123/79e1fa6d-2bae-4a63-94ab-364b07064f48)


Huge thanks to @Chew, the permission check with the s is coming from [this line](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/java/com/earth2me/essentials/MetaItemStack.java#L501)

**Comment by RulerOfEternity** [comment]
I remember at one point there was an option to change the potion's color but I can't seem to find that option anymore, could it be possible for you guys to re-add it while fixing the bug? Thanks for your time :)
