### ISSUE TITLE
HyperConomy and Essentials not working

### ISSUE THREAD

**Issue by galacticwarrior9** [EssentialsX/Essentials#555]
Update to issue #400 - 

The error still occurs on Spigot 1.9.2 and the latest dev build of both EssentialsX and HyperConomy. To shed new light on the situation, I do believe the error occurs due to my server being on offline mode? If that is the case, is it possible to fix?

New log: 
http://pastebin.com/HzH8ScMR

**Comment by drtshock** [comment]
Can you describe the issue so we don't have to page between tickets please

**Comment by galacticwarrior9** [comment]
An error occurs on startup related to Essentials/Vault. After that, I am not able to execute any HyperConomy related commands - there's no error or message in console or chat. (see log)

Here's what the HyperConomy author had to say about it:
http://dev.bukkit.org/bukkit-plugins/hyperconomy/#c2897

This only occurs on offline mode I do believe, and in addition this only occurs if HyperConomy's use external economy option is set to true rather than its internal economy hooked to Vault.

**Comment by drtshock** [comment]
Linking http://pastebin.com/7mCXtMYm

**Comment by drtshock** [comment]
Looks like it could be an issue in vault's implementation of esseco perhaps.

**Comment by PsychoLynx** [comment]
Hey! I'm having this problem too, using the latest version of EssentialsX (427)

**Comment by galacticwarrior9** [comment]
Hey @PsychoLynx, I managed to fix the problem temporarily by deleting the HyperConomy database file (it ends in .db, can't remember the name). 

Making HyperConomy use a MySQL database is easier, since all you need to do is to drop all the users, which shouldn't matter if you're using use-external on the Hyper config.

Hope this helps

**Comment by PsychoLynx** [comment]
@galacticwarrior9 

Hi! I already ended up remove hyperconomy because of other problems, but thank you for the help!
