### ISSUE TITLE
Help? maybe? please?!

### ISSUE THREAD

**Issue by BluberryPlay** [EssentialsX/Essentials#5557]
### Type of bug

Compatibility issue

### `/ess dump all` output

.

### Error log (if applicable)

https://paste.ee/p/f36al

### Bug description

could anyone help on this?https://paste.ee/p/f36al{}

I was told to report this here?  as it was not working.

### Steps to reproduce

.

### Expected behaviour

.

### Actual behaviour

.

**Comment by Evidentsinger14** [comment]
This is a client log, and has nothing to do with EssentialsX, the Bukkit plugin. for the record, when you fill out an issue template, the questions are there for a reason. don't just put nonsense.

**Comment by BluberryPlay** [comment]
I didnt know what to put said questions. seeing as I was just told to report this issue here. but someone who looked at my crash log.

**Comment by Evidentsinger14** [comment]
Whoever told you to report it here told you wrong. This is the issue tracker for EssentialsX. not a client mod called essential
