### ISSUE TITLE
Potion Colour support

### ISSUE THREAD

**Issue by RulerOfEternity** [EssentialsX/Essentials#5559]
### Feature description

Support custom colours for potions, for example with Hex IDs
Example: /give @p potion{CustomPotionColor:12080983,display:{Name:'[{"text":"Potion"}]'}} 1
(From: https://www.gamergeeks.net/apps/minecraft/give-command-generator/potions)

### How the feature is useful

It would be useful as a cosmetic feature in Magic RP servers among other use instances.

**Comment by Evidentsinger14** [comment]
There is talk of the system used for that being rewritten in EssentialsX, but for right now it's not a high priority. this is already simple enough to achieve by adding the CustomPotionColor to the end of the EssentialsX give command. `/give {USERNAME} potion 1 {CustomPotionColor:12080983}` will allow you to do this.
