### ISSUE TITLE
Sell doesn't work

### ISSUE THREAD

**Issue by Johandrex** [EssentialsX/Essentials#556]
Sometimes the "/sell" command doesn't sell all items, even though it's listed in the sell.yml file. If you drop the items, pick them up and try to use "/sell all" again it works fine.

**Comment by drtshock** [comment]
you need to sell all. sell defaults to hand.

**Comment by Johandrex** [comment]
I know @drtshock, my players and I use "/sell all". But ever since the new 1.9 update some items haven't been possible to sell.

**Comment by drtshock** [comment]
such as?
