### ISSUE TITLE
Item attribute modification command

### ISSUE THREAD

**Issue by RulerOfEternity** [EssentialsX/Essentials#5560]
### Feature description

A command that allows for the addition or removal of attributes such as items being Unbreakable, having custom armor values, giving a certain speed boost, luck, etc..

(From: https://minecraft.fandom.com/wiki/Attribute)

### How the feature is useful

It would make the creation of NBT custom items so much easier

**Comment by mdcfe** [comment]
I would like to implement item metadata editing in the future, but this would only be possible once our ItemMeta system is modernised significantly and would be a relatively low priority. For now, though not ideal you can spawn new items with metadata using `/give` and `/item`, and use the vanilla `/data` command to edit NBT.
