### ISSUE TITLE
Players Not Respawning at the correct spawn

### ISSUE THREAD

**Issue by Skullestery** [EssentialsX/Essentials#5564]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=441875fd3bc843cdbc922f8fe4b0646c

### Bug description

When players place a bed and set their spawn in it, everything goes fine, but when some1 breaks it and they go to a different dimension like the end or the nether, they cannot leave it, if they die they will respawn at 0, 0 in that dimension and going through the end portal still teleports them to 0, 0

### Steps to reproduce

1. place bed and set spawn
2. break bed
3. go to end or nether
4. die/go through end portal

### Expected behaviour

it should spawn you at the overworld's spawn

### Actual behaviour

spawns you in that dimensions 0, 0

**Comment by JRoy** [comment]
Reproduce with ONLY Essentials, likely another plugin is doing this.

**Comment by seema84** [comment]
I can confirm the problem (but I haven't tested it without essentails yet)
