### ISSUE TITLE
/home Thread Deadlock

### ISSUE THREAD

**Issue by austinpilz** [EssentialsX/Essentials#5565]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=9deca0597b54450e8ca0be1f5acc02a2

### Error log (if applicable)

https://gist.github.com/austinpilz/3448975953f2f0c53f563a11ad26ba2d

### Bug description

Sometimes when a player issues the command `/home`, it causes a thread deadlock attempting to identify the home location for the player.

Attached is the gist with the full console logs and the dump.

The user in question has a home, it is in the main world, and is normally accessible with `/home`. 

### Steps to reproduce

Unsure of when this occurs as it's inconsistent

1. Issue `/home`

### Expected behaviour

When executing `/home`, the player should be teleported to their home, or be told they have not set a location.

### Actual behaviour

When executing `/home`, sometimes it will hang, not teleport the user, and then cause a thread deadlock with subsequent server crash.

**Comment by Chew** [comment]
This seems to be an issue with trying to find the bed spawn of a player. It's hard to pin this down to Essentials itself since the error seems to be with Bukkit itself, from what I see. Can you try to reproduce with Spigot (or, preferably, Paper) and see if this issue still happens?

**Comment by JRoy** [comment]
This is slow I/O, not a deadlock. Use Paper to take advantage of async chunk loads, no reason to be using Spigot in 2023
