### ISSUE TITLE
Starter kit is not given when joining for the first time

### ISSUE THREAD

**Issue by danekoenders** [EssentialsX/Essentials#5567]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=9b2c7d89097d45d89bd337c80e34e276

### Bug description

So when joining for the first time, I would like to give my kit "skyblockstarter". But for some reason it won't give me this kit. Other plugins recognise that I'm a new player, but essentials doesn't.  

### Steps to reproduce

Join when playerdata is removed from the world (i've deleted all essentials player data too to be sure. And set the following config option:

  ```
# Do we want to give users anything on first join? Set to '' to disable
  # This kit will be given regardless of cost and permissions, and will not trigger the kit delay.
  #kit: ''
  kit: "starter"
```

### Expected behaviour

It has to give me the skyblockstarter kit when joining for the first time.

### Actual behaviour

It doesn't give me any kit. Other plugins give me the welcome for the first time message.

**Comment by Evidentsinger14** [comment]
Works fine for me - Try reproducing without other plugins installed. [My dump](https://essentialsx.net/dump.html?id=4155916cfa0e429f9ab855699d7b1a2c)

**Comment by danekoenders** [comment]
Thanks for letting me know. It had to do with the setting:
spawn-join-listener-priority: high

Mine was at: none

So when setting it up to high, it worked.

**Comment by JessiWK** [comment]
I hat to install package EssentialsX Spawn too to get it working...
