### ISSUE TITLE
Discord Integration bug after every single restart

### ISSUE THREAD

**Issue by Abgemiked** [EssentialsX/Essentials#5569]
### Type of bug

Data loss

### `/ess dump all` output

https://essentialsx.net/dump.html?id=bf99f621e39a40c5a22b0bb2f49a3c52

### Bug description

i have the problem, when the server restarts (every day at 4am) it resets the permission settings of the discordbot app in the discord integration settings...this leads to the dc-users not being able to use the commands

### Steps to reproduce

Everytime if the plugin is restarting/reloading, the integration settings in discord for the bot are reseted

### Expected behaviour

dont reset the settings, cause there is a case to use this one on discordserver in 2023 :)

### Actual behaviour

i have the problem, when the server restarts (every day at 4am) it resets the permission settings of the discordbot app in the discord integration settings...this leads to the dc-users not being able to use the commands

**Comment by Abgemiked** [comment]
if its possible contact me on Discord **Abgemiked**
i will show you the problem

**Comment by LaxWasHere** [comment]
Please install vault and see if that fixes it.

**Comment by Abgemiked** [comment]
i didnt find vault for 1.20.2, the marked vault-pages is online supported 3 years ago

**Comment by Abgemiked** [comment]
and the other question about this: 

How the vault-plugin will fix the reset-problem for the discord-integration?

**Comment by Abgemiked** [comment]
[Essentials] Plugin Essentials v2.20.1 generated an exception while executing task 13
 every 5 minutes this issue logs in console

**Comment by JRoy** [comment]
> i didnt find vault for 1.20.2, the marked vault-pages is online supported 3 years ago 
> 

https://www.spigotmc.org/resources/vault.34315/

this works for 1.20

**Comment by Abgemiked** [comment]
the same issue...your "solution" doesnt work like i told you before.

![image](https://github.com/EssentialsX/Essentials/assets/79547268/eb1530ee-1725-45cf-9b07-988f0f356d43)
dies settings will be reset after every single restart of the plugin/server, but this makes NO sense, cause its important to set the intents for every role and channel there!!

**Comment by Abgemiked** [comment]
i change the settings in dc yesterday after the restart at 4am the settings were reseted

**Comment by JRoy** [comment]
send a new dump

**Comment by Abgemiked** [comment]
https://essentialsx.net/dump.html?id=04d95c328ea3443db6e2ecb566d1807c

**Comment by JRoy** [comment]
You cannot use discord's permission management at the moment, it is planned but for now you have to use our config to manage permissions
