### ISSUE TITLE
Fly and walk speed limit doesn't work.

### ISSUE THREAD

**Issue by Sikatsu** [EssentialsX/Essentials#557]
Even while these options are set to 0.5, players can still use /speed 10, which is definatly faster then /speed 5. Tested it, so it seems these limits are not working.
# Set the max fly speed, values range from 0.1 to 1.0

max-fly-speed: 0.5
# Set the max walk speed, values range from 0.1 to 1.0

max-walk-speed: 0.5

**Comment by drtshock** [comment]
Can you give your startup log (that will provide essx and spigot versions) as well as your permissions file and your essentials config.yml please :) all in pastebins of course.

**Comment by Sikatsu** [comment]
Sorry for the delayed reply, I had issues with my laptop. Hereby the requests:

Essentials startup log: http://pastebin.com/6BHyh7be
Permissions file: http://pastebin.com/ASpCFaBf
Essentials config: http://pastebin.com/Fjj77gGe

**Comment by Sketaful** [comment]
Isn't those limits more to hinder the vanilla speed, not to stop the speed you can get by essential commands?

**Comment by Sikatsu** [comment]
It would be better if it would deny the use of /speed 6 or higher. When testing 5 against 10, you can see that this setting does not work as expected.

**Comment by mdcfe** [comment]
Closing in favour of #2148.
