### ISSUE TITLE
Authme shouldn't be able to move with the arrow keys before logging in, but EssentialsX breaks this behavior.

### ISSUE THREAD

**Issue by Huge-mistake** [EssentialsX/Essentials#5570]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

EssentialsX 2.20.1

### Error log (if applicable)

null

### Bug description

EssentialsX broke Authme to intercept users from moving before they landed.
Authme shouldn't be able to move with the arrow keys before logging in, but EssentialsX breaks this behavior.

### Steps to reproduce

Authme + EssentialsX

### Expected behaviour

Authme should not be able to move with the arrow keys before logging in

### Actual behaviour

Can be moved within a block

**Comment by Huge-mistake** [comment]
It doesn't have much of an impact, but I want to make it impossible for players to move with the arrow keys until they log in with authme

**Comment by JRoy** [comment]
We don't support offline mode, you didn't include a dump, and I have no idea what you're talking about when you say error keys.

**Comment by CatTeaA** [comment]
https://github.com/EssentialsX/Essentials/assets/135555687/6304a5c4-4f33-4692-aa45-5b5f17408513

@JRoy

**Comment by mbax** [comment]
"We don't support offline mode"

**Comment by CatTeaA** [comment]
> "We don't support offline mode"

Use it to secure your Offline mode server or to “ incrase your Online mode server's protection! ”
![7ede4bd8-531e-40ac-9c91-da330327481f](https://github.com/EssentialsX/Essentials/assets/135555687/e7e3db91-38dc-4241-ad66-303be8840515)
![7d09e14f-c8bd-4028-bad4-a069dcf39d7e](https://github.com/EssentialsX/Essentials/assets/135555687/f1685e7a-03ab-4e21-95a1-4658d6d56dca)
🌚🌚🌚

**Comment by mbax** [comment]
Send a full dump (output of `/ess dump all`) for your active server with uptime of a least 8 hours, where this issue occurred during that same session.

**Comment by CatTeaA** [comment]
I'm not a professional, and it seems like I can reproduce this situation by just installing essentialX + authme
Even if it's a brand new server

**Comment by mbax** [comment]
Okay, sounds like this will be easy for you to provide what's requested then :)
