### ISSUE TITLE
EssentialsX Discord Link

### ISSUE THREAD

**Issue by YazidIlyasBaihaqi** [EssentialsX/Essentials#5575]
### Type of bug

Data loss

### `/ess dump all` output

https://essentialsx.net/dump.html?id=78e201f7b4d54241981a1c1a5a6ed880

### Bug description

In a random interval the plugin EssentialsX Discord Link accounts.json restarted and loose all accounts data information and users has to relink their account again. I don't know what the cause, is it either because the server crashing from insuffecient memory (a small server) or because other external/internal factors?

If the causes is plugins rollback, it's unlikely since the user accounts is more than a day of the data storage and other plugins seems to be unaffected.

### Steps to reproduce

The problem occurs randomly. Sometime only a few data sometimes it's every accounts
Theory
1. Start the server as normal
2. Use the link 

### Expected behaviour

Users account should not be restarted in such way unless the server owner intend to reset it

### Actual behaviour

User accounts reset itself

**Comment by Evidentsinger14** [comment]
We were unable to reproduce this behavior. If you are able to reliably reproduce, please feel free to update the issue and it can be looked into.

**Comment by JakeFrosty** [comment]
I am also experiencing the same situation with my PaperMC server, why was this issue closed?

here's my dump too
https://essentialsx.net/dump?bytebin=syZamPLbMP

**Comment by mbax** [comment]
> why was this issue closed?

As the closing message indicated, they were unable to reproduce the reported issue. Can you, as they indicated in the message, provide more information on what lead up to this?
