### ISSUE TITLE
/give tipped_arrow gives a potion instead

### ISSUE THREAD

**Issue by SnowShae** [EssentialsX/Essentials#5580]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=94c23f3e97ea428396ae3316dc80bfcc

### Error log (if applicable)

none

### Bug description

on the arrow - tipped_arrow 1 splash:false effect:slow power:1 duration:120 this command issues a potion slowing down by the action of 120 seconds, but should issue an arrow.
on the potion I have already done through the following command - potion:34 1 splash:false effect:speed power:1 duration:600 and it works, the potion is given what it needs. The only problem is with the arrow. About the arrow. I gave myself an arrow in the mine through this command / minecraft:give @p minecraft:tipped_arrow{Potion:"minecraft:water",CustomPotionEffects:[{Id:2,Duration:32000,ShowParticles:0b}] }
then I wrote the command /createkit test 0
Then I wrote / kit test, but potions turned out instead of arrows, although there should be arrows with the effect of slowing down for so many seconds of rank 1.

### Steps to reproduce

Combined follow the image
1: / minecraft:give @p minecraft:tipped_arrow{Potion:"minecraft:water",CustomPotionEffects:[{Id:2,Duration:32000,ShowParticles:0b} ] }
2: Says I did /createkit test 0
3: I prescribed the / kit test command, but in the end, instead of an arrow, a deceleration potion is issued.

### Expected behaviour

Combined follow the image
1: / minecraft:give @p minecraft:tipped_arrow{Potion:"minecraft:water",CustomPotionEffects:[{Id:2,Duration:32000,ShowParticles:0b} ] }
2: Says I did /createkit test 0
3: We expect the behavior to be issued a rank 1 arrow for 120 seconds

### Actual behaviour

A deceleration potion is issued instead of an arrow for deceleration

**Comment by Evidentsinger14** [comment]
Can confirm the behavior is accurate. `/give Ev1dent tipped_arrow 1 splash:false effect:slow power:1 duration:120` put an "uncraftable potion" in my inventory. 
![image](https://github.com/EssentialsX/Essentials/assets/46200123/d72afa1a-5b58-4cf4-9595-9e669427b823)
