### ISSUE TITLE
warning in connection with fe economy

### ISSUE THREAD

**Issue by seema84** [EssentialsX/Essentials#5583]
### Type of bug

Error in console

### Error log (if applicable)

https://paste.gg/p/anonymous/ed7ecb13fac2439fa2acfdb88b3dea8a

### Bug description

I get the warning when starting the server.

Vault: v1.7.3-b131
Fe: v0.9
Essentials: v2.21.0-dev+21-c68b277
Paper-196 (MC: 1.20.1)

### Steps to reproduce

A simple server start is enough to reproduce the error.

**Comment by mbax** [comment]
Looks like an error in your economy plugin, triggered by EssX trying to create an account on it for a user.

**Comment by seema84** [comment]
This error only occurs if the PlaceholderAPI plugin and the expansion essentials are used.

Version: PlaceholderAPI-2.11.5

**Comment by pop4959** [comment]
The Essentials expansion for PlaceholderAPI is maintained by a third party, you will want to report this to them instead then.

**Comment by seema84** [comment]
> The Essentials expansion for PlaceholderAPI is maintained by a third party, you will want to report this to them instead then.

Since the warning came from essentails, I thought it might be due to the placeholderapi support in essentials.

**Comment by JRoy** [comment]
There is no placeholder api support in essentials. this is an issue with your economy plugin
