### ISSUE TITLE
/help is not working

### ISSUE THREAD

**Issue by johnnkcool** [EssentialsX/Essentials#5587]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=66e7b46b6e674701964e27a65ab19344

### Bug description

When running /help instead of showing a list of commands it shows "Unknown chapter." in Dark Red Color

### Steps to reproduce

By running /help

### Expected behaviour

Showing a list of commands

### Actual behaviour

Showing "Unknown chapter."

**Comment by Chew** [comment]
It looks like Essentials isn't handling the `/help` command, PerWorldPlugins is (see `net.tonimatasdev.perworldplugins.api.PerWorldCommand$1(help)`). This is probably an issue with that plugin. Try disabling and see if you're still experiencing the issue.

**Comment by TonimatasDEV** [comment]
This can now be closed

**Comment by johnnkcool** [comment]
I dont really understand what are you guys talking about yet.Please explain to me so i know what should i do when i meet this , as it always says "unknown chapter"


Sent with Proton Mail secure email.

**Comment by LaxWasHere** [comment]
The developer of the plugin that is causing your problem just indicated that the problem has been fixed and all you need to do is update said plugin.

**Comment by johnnkcool** [comment]
thx


Sent with Proton Mail secure email.
