### ISSUE TITLE
EssentialsGeoIP no work

### ISSUE THREAD

**Issue by GreatGoal0** [EssentialsX/Essentials#5589]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=1f75155556534662903bfbe864542d8c

### Bug description

When using /whois it does not show the complete information such as the location having the maxmind key and the essentials.geoip.show permission

### Steps to reproduce

1: set maxmind key in config.yml
2: grant essentials.geoip.show permission to the player who will use /whois
3: use /whois <player>

### Expected behaviour

See the player's approximate location (country and continent)

### Actual behaviour

Tell the player's location in the world

**Comment by GreatGoal0** [comment]
Maxmind has changed some things like its keys, on the page https://essentialsx.net/wiki/GeoIP.html it says to set the "This key will be used for GeoIP update" option to no to create a key, which which is no longer possible and now says New license keys will not work with legacy versions of our GeoIP Update program.

EssentialsGeoIP would need to be updated.

**Comment by GreatGoal0** [comment]
![IMG_20231203_151054](https://github.com/EssentialsX/Essentials/assets/106454514/420155c6-378a-4127-a0aa-51afa0633e6e)
![geoip-step4 b249d622](https://github.com/EssentialsX/Essentials/assets/106454514/70e58332-9052-4bc6-9511-52434fbd5bae)

**Comment by mdcfe** [comment]
Your screenshots show MaxMind has removed the option to generate legacy keys, but EssentialsX doesn't use these keys - that's the reason the instructions tell you to tick "no". There's nothing in your logs to indicate that the server failed to update the database either, so this is likely user error.

Could you enable `/ess debug`, try and `/whois` a player and then share the `/ess dump all` output?
