### ISSUE TITLE
Add formatting capability of player names text when using /alts <player> command

### ISSUE THREAD

**Issue by aaronlclark** [EssentialsX/Essentials#5594]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=5b98504219c54891a3f173dc3c776f18

### Bug description

Would it be possible to add formatting capabilities to the player names that appear when the /alts is submitted, please?
i.e allow for the final 'aaronlclark' text to be formatted, as it appears to currently be unformatted.

I cannot seem to locate a line/field for this in either config.yml nor messages_en.properties.

If this already exists, could someone point me in the right direction, please?
![2023-12-09_20 26 05](https://github.com/EssentialsX/Essentials/assets/153395139/968dccc1-e336-4b14-88e3-5f8a45568209)

### Steps to reproduce

type /alts <player>

### Expected behaviour

I'd hope there'd be a way to format the text that shows the player name(s) either via config.yml or messages_en.properties.

### Actual behaviour

I cannot seem to find a way to format this specific text.

**Comment by pop4959** [comment]
Yeah there isn't a way to change this right now, looks like it just gets printed as a string:
https://github.com/EssentialsX/Essentials/blob/bb7b334ace196fcd8889014c90a0f9f6a9b53ccf/Essentials/src/main/java/com/earth2me/essentials/commands/Commandseen.java#L218
