### ISSUE TITLE
Disabled commands

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#5597]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=894dfab42eda47768ccb38b516805e27

### Bug description

Disabling commands here will prevent Essentials handling the command, this will not affect command conflicts.
You should not have to disable commands used in other plugins, they will automatically get priority.
See https://bukkit.fandom.com/wiki/Commands.yml#aliases to map commands to other plugins.
disabled-commands:
[#]  - nick
[#]  - clear
- kill
- locate

### Steps to reproduce

I use /locate but it gives me player names on autotab. 
I need to enter /minecraft:locate to be able to locate a structure or a biome.

### Expected behaviour

/locate autotab

### Actual behaviour

I use /locate but it gives me player names on autotab. 
I need to enter /minecraft:locate to be able to locate a structure or a biome.

**Comment by pop4959** [comment]
Works as intended. Built-in commands are not plugin commands so Essentials does not give priority to them.
Using commands.yml should be sufficient should you need to completely disable an Essentials command to give Minecraft built-in commands priority.

**Comment by ghost** [comment]
My problem is that Essentials does give priority to this command. How to disable this?

aliases:
   locate:
   - "minecraft:locate $1-"
   kill:
   - "minecraft:kill $1-"
   weather:
   - "minecraft:weather $1-"
   
   Like this?

**Comment by pop4959** [comment]
Try `kill: minecraft:kill`. Please join the Discord if you need further help with this as Github is not a great place to troubleshoot.
