### ISSUE TITLE
Sort tablist by pex ranking, then by name

### ISSUE THREAD

**Issue by Platinteufel** [EssentialsX/Essentials#560]
Hey,
at the moment the tablist is just sorted by the players name. Is it possible to add a feature that the tablist is sorted by the pex rank (admin first, then mod, --> finally player) and within this groups by the players name?

**Comment by drtshock** [comment]
we don't touch the tablist.

**Comment by Platinteufel** [comment]
Well .. 

```
# Disable this if you have any other plugin, that modifies the displayname of a user.
change-displayname: true

# When this option is enabled, the (tab) player list will be updated with the displayname.
# The value of change-displayname (above) has to be true.
change-playerlist: true
```

I would really appreciate this feature!

**Comment by drtshock** [comment]
Yes and updating a single player's display name through the Bukkit API is just touching that player. What you're asking is for us to completely modify the layout of the tab list which we won't do.
