### ISSUE TITLE
Chat Problem with mc 1.20.3 and 1.20.4

### ISSUE THREAD

**Issue by Sick-Side** [EssentialsX/Essentials#5604]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=6b9a0bbb8bb347fd81f009b09e1247ad

### Error log (if applicable)

[12:32:25] [Render thread/WARN]: Client disconnected with reason: Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode: Invalid color name: reset; List must have contents {extra:[{color:"reset",text:"<XSickLukeX> gfdsfds",type:"text"}],text:"",type:"text"}

### Bug description

When i write something in the chat with mc versions 1.20.3 and 1.20.4 the game kick me out. If i do the same thing with mc up to 1.20.2 i have no issues.

### Steps to reproduce

Write something in the chat.

### Expected behaviour

The game shouldnt kick me out.

### Actual behaviour

it kicks me out.

**Comment by mdcfe** [comment]
This isn't an EssentialsX problem. Your server is running on 1.15.2 (why!?!?) and EssentialsX is sending legacy format strings as expected. You likely need to update ViaVersion - contact them for support.
