### ISSUE TITLE
Tranlation error

### ISSUE THREAD

**Issue by Sneyzi** [EssentialsX/Essentials#5609]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

-

### Bug description

/help /msgtoggle

### Steps to reproduce

execute command /help /msgtoggle

https://github.com/EssentialsX/Essentials/blob/0af4436c2ffd6fe2eb84f6408fbd4fd18858cafc/Essentials/src/main/resources/messages.properties#L794
and all other languages

### Expected behaviour

msgtoggleCommandUsage1Description=Toggles private messages for yourself or another player if specified
and all other languages

### Actual behaviour

msgtoggleCommandUsage1Description=Toggles fly for yourself or another player if specified
and all other languages

**Comment by Sneyzi** [comment]
"and all other languages"

**Comment by Evidentsinger14** [comment]
Translations are managed through Crowdin, not GitHub. The main messages.properties is the only one that gets changed here.
