### ISSUE TITLE
EssentialsXChat-2.21.0-dev+24-0af4436 conflict with voicechat-bukkit-2.4.30

### ISSUE THREAD

**Issue by BaiRuoQiu** [EssentialsX/Essentials#5615]
### Type of bug

Compatibility issue

### `/ess dump all` output

https://essentialsx.net/dump.html?id=fed51f072e3d42d9b66d069db3b00317

### Error log (if applicable)

https://paste.gg/p/anonymous/2db22c9d2f2c469a8f2e9e2430d25f30

### Bug description

Outbound players can't connect to voice chat after updating ess

### Steps to reproduce

Three people play the game, the LAN can be connected to voice chat, but the other two players on the WAN does not work, after uninstalling the ess back to normal!

### Expected behaviour

You can connect to the voice server normally

### Actual behaviour

Unable to connect to voice server

**Comment by BaiRuoQiu** [comment]
Rolling back to EssentialsX-2.21.0-dev+17-79449ef.jar will allow you to use voicechat normally

**Comment by pop4959** [comment]
I don't see how this has anything to do with us. Report it as an issue to VoiceChat if you are still having issues connecting to their voice servers.
