### ISSUE TITLE
Have no security checks when using command /banip

### ISSUE THREAD

**Issue by whfwtf** [EssentialsX/Essentials#5618]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=5ad6ede52afa40df8dca37cfce40df65

### Bug description

when an operator accidently uses the command :/banip 127.0.0.1
everyone is kicked out from the server.

### Steps to reproduce

1.open a server locally
2.let operator use this command :/banip 127.0.0.1

### Expected behaviour

[Error]You can't ban server itself

### Actual behaviour

[17:42:02 信息]: [Essentials] 操作员****封禁了IP段127.0.0.1，理由：干啥呢。

**Comment by ed-3** [comment]
哥们搞笑呢，让op使用banip![image](https://github.com/EssentialsX/Essentials/assets/69950862/1973565f-995a-4d3f-8875-16d6393f7c29)

**Comment by whfwtf** [comment]
服务器不是我的。。。
他们玩脱了来烦我是我没想到的

**Comment by ed-3** [comment]
> 服务器不是我的。。。
> 
> 他们玩脱了来烦我是我没想到的

后台输入指令/unbanip 127.0.0.1 解封就行了，别叫他们这么玩了🤭

**Comment by pop4959** [comment]
Not a security issue, just don't ban that IP. We will not be adding artificial restrictions to what IPs can be banned using the command, especially given this is something that you need privileged access (moderator / admin permissions) for anyway.
