### ISSUE TITLE
Spawners not spawning

### ISSUE THREAD

**Issue by SteefWayer** [EssentialsX/Essentials#5622]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=417526cd24cc4f9990e9f9e564e379ba

### Bug description

I want to place a spawner and add a egg to it. But it doesnt seem to work. I investigated the bug by looking at other their bug reports but i couldnt find any solution. When running `/minecraft:give @s mob_spawner{BlockEntityTag:{EntityId:Creeper}}` i get a normal spawner. This is on a bukkit 1.20.4 server.

### Steps to reproduce

Get a spawner, place egg, no work :(

### Expected behaviour

Spawner should start spawning the egg i try to insert 

### Actual behaviour

Nothing spawns and spawner stays untouched

**Comment by Evidentsinger14** [comment]
Have you reproduced this issue without EssentialsX installed? As far as I know (I may be wrong) EssentialsX doesn’t modify spawner behavior in any way, except the command to change the type, and the types placeable.

**Comment by SteefWayer** [comment]
before i try this, will my settings dissapear i currently have on the server? (eg worldspawn, diffrent worlds)

**Comment by Evidentsinger14** [comment]
As long as you don’t remove the folders, no. You can just rename the jars so they don’t load to something like EssentialsX.jar.disabled

**Comment by SteefWayer** [comment]
i renamed the file and as expected, it worked now. so its essentialsX that's causing the spawner to not work

**Comment by SteefWayer** [comment]
i did some fiddling with other plugins and it seems fixed now. i also changed to paper instead of spigot. i added a plugin where players can destroy spawners with silk touch pickaxes, so maybe that added support for spawners but im not sure. anyways problem solved but essentialsX still did something to my spawners which made me unable to place spawners in the past. but fixed so thanks for fast replies anyways :3
