### ISSUE TITLE
Unmute/Jail?

### ISSUE THREAD

**Issue by kokqi** [EssentialsX/Essentials#5624]
### Feature description

when there wlll be "/unmute" feature? ik /mute works the same but I want a toggle feature. Don't need /unmute feature if yall added jail disabled commands since there's mute disable commands already but what irony is that there's no jail disable commands. And I'm using betterjails along with essentialsx jail for extra commands on jail so there will no issue at all. All I need is just /unmute or a jail disable commands feature. And lastly there's an issue where you can't unmute yourself with /mute unless you deal with it in your essentialsx file or through console

### How the feature is useful

useful i guess

**Comment by kokqi** [comment]
i just need unmute tbh, there's no need to deal with jail disable commands afterwards

**Comment by kokqi** [comment]
I've checked #1215, obviously they added nothing

**Comment by Evidentsinger14** [comment]
That issue you decided to necro from 4 years ago has nothing to do with an unmute or unjail command. It’s adding the ability for commands to be unusable while a player is jailed. Your suggestion is here, that’s all the more you can do for the time being.

**Comment by kokqi** [comment]
nvm i can just disable those commands with worldguard, the only problem is that you can't unmute yourself with /mute unless you deal with it in your essentialsx file or through console

**Comment by pop4959** [comment]
You can already unmute players with /mute if they are already muted (check /seen to see if they are muted).

You should be able to add /mute to the disabled commands for jail if you need to, although this is a weird use case since presumably the same people who have access to that command are not also being jailed (i.e. your moderators).
