### ISSUE TITLE
Suggestion: Allow Placeholders in Custom Join/Leave Messages

### ISSUE THREAD

**Issue by Dynamite99** [EssentialsX/Essentials#5628]
### Feature description

Pretty simple, but would like to be able to add my prefixes and suffixes to my join/leave messages. Something like the following:

custom-join-message: "&7[&a+&7] {alonsotags_tag_chat}{PLAYER}{luckperms_suffix} has joined the server!"

### How the feature is useful

It would further allow customization on this one feature.

**Comment by pop4959** [comment]
This is a wontfix unless Essentials decides to add PlaceholderAPI support (or any other placeholder support), however this is currently not planned.

You can use other plugins such as [ChatInjector](https://www.spigotmc.org/resources/chatinjector-1-13.81201/) (or any alternative of) to use them with Essentials.
