### ISSUE TITLE
/spawner doesn't change mob type the first time

### ISSUE THREAD

**Issue by pickernickel** [EssentialsX/Essentials#563]
Using /spawner on a freshly placed spawner will not change the mob type regardless of the type of mob the first time you enter the command. It will however spawn one set of the correct mob type and typing the command again will properly change the spawner. There were no console errors and only just noticed the issue in Spigot 1.9.2.

**Comment by Kakifrucht** [comment]
Cannot confirm, am on 1.9.2 and I am not having this issue.

**Comment by pickernickel** [comment]
I am using the following steps to reproduce:

1: /give pickernickel spawner
2: Place spawner anywhere.
3: Look at spawner and type /spawner Zombie
(Command will fail to change mob type but will spawn a set of zombies.)
4: Type /spawner Zombie.
(Command will succeed and change spawner type.)

**Comment by Kakifrucht** [comment]
Yeah, cannot reproduce.

**Comment by pickernickel** [comment]
It seems like the issue isn't Essentials. I went back and tested all the plugins I had installed and the issue only existed in certain worlds. I will have to double check my configs but I would like to thank you for your time.
