### ISSUE TITLE
Adventure API Update

### ISSUE THREAD

**Issue by TrueDarkLord** [EssentialsX/Essentials#5634]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=019ebc066a694bf59fd1d8bd4678bcb5

### Error log (if applicable)

N/A

### Formatting doesn't seem to be correct for:
- /msg 
   ![image](https://github.com/EssentialsX/Essentials/assets/73395689/012d7c5f-cdd6-45ab-871d-6a3808d2f4d0)
- /list
![image](https://github.com/EssentialsX/Essentials/assets/73395689/d7ddad3c-9b52-4b47-92eb-2b65a605649f)
- Essentials' Signs
  - Tested with sell sign 
![image](https://github.com/EssentialsX/Essentials/assets/73395689/0d42d7e4-dba5-4bc9-a108-98f6187083e0)
- Chat Spy

No longer seems to function:
- /mail
 - /nuke 
   - no longer seems to have command feedback.
 - /alts
   - Missing command feedback.
 - /bal
 - /Enchant
Probably more, but going to stop testing them there.

### Steps to reproduce

1. Start up a fresh server.
2. Try out the features.
3. Become sad that they do not work.

### Expected behaviour

For colour codes to be parsed properly/ features to work.

### Actual behaviour

Colour codes are not parsed properly/ features do not work.

**Comment by JRoy** [comment]
/msg is now fixed in #5632

working on the rest now

**Comment by JRoy** [comment]
#5637 should fix everything here. worth noting that /mail, /nuke, /alts, /bal, and /enchant all worked on my end although it could have been from a previous fix i already deployed
