### ISSUE TITLE
color problem - near

### ISSUE THREAD

**Issue by 100petr** [EssentialsX/Essentials#5641]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=f31941b6688645f185f7e5b6cca38ed8

### Bug description

After entering the /near command, the colors are not displayed correctly
![image](https://github.com/EssentialsX/Essentials/assets/29830635/579fdbdc-c245-4475-b6b0-7c4b68a78cf6)

### Steps to reproduce

Update to the latest version of essentials
Have players around
Type /near

### Expected behaviour

The colors will display correctly

### Actual behaviour

Colors are displayed incorrectly

**Comment by 100petr** [comment]
the problem remains

**Comment by melaniebeedot** [comment]
Was just about to report this issue as well, for /near
![near](https://github.com/EssentialsX/Essentials/assets/98659383/4dcf8315-05e6-4de9-b03b-c8b7e1666c2e)

(i'm on the latest dev build)
