### ISSUE TITLE
Afk placeholder.

### ISSUE THREAD

**Issue by foxi69** [EssentialsX/Essentials#565]
Do you know how can I make an %afk% placeholder in PlaceholderAPI?

like this one: http://pastebin.com/HPRxtnfe

or please add a configable afk placeholder to the config.

when its true: &4AFK
when its false: 'nothing'

**Comment by drtshock** [comment]
this isn't placeholder api

**Comment by foxi69** [comment]
then create an afk placeholder plz

**Comment by drtshock** [comment]
see above message.
