### ISSUE TITLE
color problem - kits

### ISSUE THREAD

**Issue by 100petr** [EssentialsX/Essentials#5651]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=ed3700489779403aaf16fc0805282593

### Bug description

For used kits, the color in /kits is displayed incorrectly
![image](https://github.com/EssentialsX/Essentials/assets/29830635/626476e3-66cd-4657-a344-5d950b358617)

### Steps to reproduce

Update to the latest version of essentials
Get some kit
Type /kits (make sure you don't have admin permissions, so that the cooldown applies to you)

### Expected behaviour

The colors will display correctly

### Actual behaviour

Colors are displayed incorrectly

**Comment by takatalvi** [comment]
I can confirm this behavior. The same goes for other lists, like /homes, /warps and others that might work similarly. I found it specifically in /homes, where the bed location is mentioned either in italics or as strikethrough. The attached image displays the string bedMissing:
![Untitled](https://github.com/EssentialsX/Essentials/assets/35687568/0465117d-6b6f-4c5b-9acc-8f66578b1667)
