### ISSUE TITLE
Prefix formatting bleeds into display name

### ISSUE THREAD

**Issue by melaniebeedot** [EssentialsX/Essentials#5652]
### Type of bug

Performance issue or memory leak

### `/ess dump all` output

https://essentialsx.net/dump.html?id=2a7e713c0a5c48d1b5ca90e0a49a40f6

### Bug description

The bold from our prefixes is carrying over into our usernames when we /afk or un-/afk, and switching game modes, and in the /list of players online, even though our prefixes are specifically defined to reset the bold at the end of the prefix:
![bold](https://github.com/EssentialsX/Essentials/assets/98659383/e938e5da-1382-4246-aa75-1d742f51971b)

### Steps to reproduce

1. Update to the latest dev build of EssentialsX
2. /afk or /gm or /list

### Expected behaviour

Prefix is bolded and username is not.

### Actual behaviour

Both prefix and username are in bold.

**Comment by Bobcat00** [comment]
The random format code also causes problems for /list, /whois, /seen, and /msg

Prefix is `&1[&9&k::&9CoOwner&9&k::&1]&7`

EDIT: I tried adding the reset code `&r` to the prefix, but it didn't help.

Essentials v2.21.0-dev+56-1929d41
Paper version git-Paper-430 (MC: 1.20.4)

![image](https://github.com/EssentialsX/Essentials/assets/3617206/e12e10ac-aa98-4c4e-afbf-f621b2a85c83)
