### ISSUE TITLE
formatting in homes list

### ISSUE THREAD

**Issue by melaniebeedot** [EssentialsX/Essentials#5653]
### Type of bug

Performance issue or memory leak

### `/ess dump all` output

https://essentialsx.net/dump.html?id=501a4e00a74c4dea8c2b4836aa4f59fc

### Bug description

Very minor, but I noticed on my homes list, my last home for ''bed'' is showing the \<st> and \<reset> tags instead of being strikethrough.
![homelist](https://github.com/EssentialsX/Essentials/assets/98659383/171edc1f-5387-4688-a05d-b16fde64b84c)

### Steps to reproduce

1. Update to the latest dev build of EssentialsX
2. View existing homes list with /homes

### Expected behaviour

My ''bed'' home is normally strikethrough as I no longer have that bed placed.

### Actual behaviour

The formatting tags are showing instead: \<st>bed\<reset>.

**Comment by takatalvi** [comment]
related to [5651](https://github.com/EssentialsX/Essentials/issues/5651)

**Comment by Goinging** [comment]
I can confirm on the lastest dev build that this is still happening
