### ISSUE TITLE
color problem - me

### ISSUE THREAD

**Issue by 100petr** [EssentialsX/Essentials#5654]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=ed3700489779403aaf16fc0805282593

### Bug description

Color codes are not displayed correctly in /me.
![image](https://github.com/EssentialsX/Essentials/assets/29830635/37b929b1-40a7-4d53-b63f-535a53b704a2)
![image](https://github.com/EssentialsX/Essentials/assets/29830635/fe0a3966-88bb-4ef2-826c-2bb87075bc6a)

(it doesn't matter if it's via commandblock or as a player)

### Steps to reproduce

Update to the latest version of essentials
/me &ctest

### Expected behaviour

/me will display colors correctly

### Actual behaviour

/me displays colors incorrectly

**Comment by bacalhau-seco** [comment]
it does also happen to me:
![image](https://github.com/EssentialsX/Essentials/assets/64091315/c7f0aef1-6cef-44ad-ac09-de34cfd0fcee)
![image](https://github.com/EssentialsX/Essentials/assets/64091315/4ad5b1d7-36c5-4f3a-b79e-2b25054f72e8)
but in my case i didnt add color

**Comment by 100petr** [comment]
It's still broken when its written from commandblocks
![image](https://github.com/EssentialsX/Essentials/assets/29830635/14427ba7-2ade-45c6-bfd4-8d84f007d26a)
