### ISSUE TITLE
formatting in /ptime

### ISSUE THREAD

**Issue by melaniebeedot** [EssentialsX/Essentials#5655]
### Type of bug

Performance issue or memory leak

### `/ess dump all` output

https://essentialsx.net/dump.html?id=41c72a579971417bb241f5814268f605

### Bug description

When using /ptime it seems the \<secondary> and \<primary> colors won't input, the tag shows instead:
![ptime](https://github.com/EssentialsX/Essentials/assets/98659383/829412ec-6e95-4cf5-8261-c9c30fe24acb)

### Steps to reproduce

1. Update to the latest dev build of EssentialsX
2. Use /ptime morning or /ptime @ noon

### Expected behaviour

"Player time is set to 07:00 or 7:00 AM or 1000 ticks for: melaniebeedot."

"Player time is fixed to 12:00 or 12:00 PM or 6000 ticks for: melaniebeedot."

### Actual behaviour

"Player time is set to \<secondary>07:00\<primary> or \<secondary>7:00 AM\<primary> or \<secondary>1000 ticks\<primary> for: melaniebeedot."

"Player time is fixed to \<secondary>12:00\<primary> or \<secondary>12:00 PM\<primary> or \<secondary>6000 ticks\<primary> for: melaniebeedot."

**Comment by MinecraftCitiesNetwork** [comment]
I can confirm this bug.
