### ISSUE TITLE
Legacy formatting codes--unsupported behavior

### ISSUE THREAD

**Issue by GrumpyCatJen** [EssentialsX/Essentials#5657]
### Type of bug

Performance issue or memory leak

### `/ess dump all` output

https://essentialsx.net/dump.html?id=c22a98239f314d22b533dbd205e684e6

### Bug description

When trying to run essentials commands like /back or /tp it fails to run the command and puts in chat "Legacy formatting codes have been detected in a MiniMessage string - this is unsupported behavior.  Please refer to the Adventure documentation (https://docs.advntr.dev) for more information."  This only  happened when updating the plugin to "EssentialsX-2.21.0-dev+35-d4ecfd2.jar" and "EssentialsXSpawn-2.21.0-dev+35-d4ecfd2.jar" and a similar error message was showing up in console when the command /eco ... was being run by another plugin.  I reverted back to "EssentialsX2.21.0-dev+25-fbfd7e9.jar" and "EssentialsXSpawn-2.21.0-dev+25-fbfd7e9.jar"  The error no longer shows up and the plugin and related commands are working as expected.  

### Steps to reproduce

Upgrade to dev 35-d4ecfd2
Try running /back in game chat
or Try running /tp player1 player2
or Try running /eco give player $

### Expected behaviour

/back should teleport the player to a prior location and no error messages should show up in chat/console
/tp player1 player2 should teleport player1 to player2 and no error messages should show up in chat/console
/eco give player $ should give player money and no error messages should show up in chat/console

### Actual behaviour

/back only produces an error message, the player is not teleported back
/tp player1 player2 only produces an error message, the player is not teleported
/eco give player $ only produces an error message, the player does not receive money

Example from one of our players:
![2024-02-07_20 38 42](https://github.com/EssentialsX/Essentials/assets/159399955/78c56735-f233-4b1a-b8d0-57a6790a2ca5)

**Comment by Nacholebraa** [comment]
I have had this same issue however, it just shows the messages not appearing in chat at all but in console displaying that the command is ran.

**Comment by JRoy** [comment]
This is almost certainly an issue with custom locale files, please reach out to our discord with support with this.
