### ISSUE TITLE
formatting in /time command

### ISSUE THREAD

**Issue by melaniebeedot** [EssentialsX/Essentials#5661]
### Type of bug

Performance issue or memory leak

### `/ess dump all` output

https://essentialsx.net/dump.html?id=7fc367e4abe14931a5addf6b9f9feaad

### Bug description

(Related to #5655, maybe? Sorry, I didn't realize until now because I never use the /time command)

When using the /time command, the \<primary> and \<secondary> tags are showing instead of inputting the colors.

![image](https://github.com/EssentialsX/Essentials/assets/98659383/9eaafb50-e7ad-47ab-b07f-3290557954c9)

### Steps to reproduce

1. Update to the latest dev build of EssentialsX
2. Use /time

### Expected behaviour

(in color) 05:09 or 5:09 AM or 23166 ticks

### Actual behaviour

(all white) \<seconday>05:09\<primary> or \<secondary>5:09 AM\<primary> or \<seconday>23166 ticks\<primary>

**Comment by 100petr** [comment]
![image](https://github.com/EssentialsX/Essentials/assets/29830635/67e8ca0e-85a8-4d8a-bdf8-270914f826d2)
I can confirm
