### ISSUE TITLE
Suicide error

### ISSUE THREAD

**Issue by 100petr** [EssentialsX/Essentials#5662]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=0c157b060fca400d95e5889e2046ccea

### Bug description

The Suicide command executes but displays an error
![image](https://github.com/EssentialsX/Essentials/assets/29830635/3d2884d4-ec9f-4e42-a1ae-8f34d0b4fc76)

### Steps to reproduce

Update essentialsx
Type /suicide
There is an error in the chat (there is nothing in the console)

### Expected behaviour

suicide will not write an error

### Actual behaviour

suicide writes an error

**Comment by 100petr** [comment]
my bad :D

**Comment by Evidentsinger14** [comment]
confirmed on dev build 42
![image](https://github.com/EssentialsX/Essentials/assets/46200123/0b7e4738-385f-4a79-866e-d5a4151a0acd)
