### ISSUE TITLE
Reloading EssentialsX and rejoining stops command feedback for players

### ISSUE THREAD

**Issue by Technofied** [EssentialsX/Essentials#5663]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=f1944823226d4428a48db81f70606f33

### Bug description

Players are unable to get command feedback (messages) when they run commands.

### Steps to reproduce

1. Run /ess reload in game
2. Run an essentials command like /pay
3. Log off the server and wait 10 seconds
4. Rejoin and observe that /pay and other commands no longer show any feedback in-game

### Expected behaviour

For command feedback to be consistently available in-game.

### Actual behaviour

For command-feedback to disappear in-game,  and only work in console when commands are ran there.

**Comment by saran-chaz** [comment]
me too last build today
