### ISSUE TITLE
<primary> and <secondary> showing up in the kick message by EssentialsXDiscordLink

### ISSUE THREAD

**Issue by Xandar-YT** [EssentialsX/Essentials#5667]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=f6cc94ee9b1e43ab9825c8a905d9d5b0

### Bug description

`<primary>` and `<secondary>` are showing up in the kick message shown to the unlinked user after being kicked for that.

The message is set to: 
`discordLinkLoginKick=<primary>Morate povezati vas Discord nalog prije nego sto mozete uci na Craftopiu.\n<primary>Da povezete vas Minecraft nalog sa Discordom, kucajte\:\n<secondary>{0}\n<primary>u Discord serveru od ovog servera\:\n<secondary>{1}`

### Steps to reproduce

Just try to login with an unlinked account while kicking for it is on in the config.

### Expected behaviour

It should just say it without `<primary>` and `<secondary>`.

### Actual behaviour

![Screenshot_20240212-123346_PojavLauncher_Minecraft__Java_Edition_for_Android](https://github.com/EssentialsX/Essentials/assets/84316546/983db5af-2ff8-4c85-9320-59abb98f1b60)

(this is a screenshot from PojavLauncher for Android but it does happen on the normal PC version of Minecraft as well)

**Comment by JeremyJenki** [comment]
Same issue here
