### ISSUE TITLE
Request: No Pickup

### ISSUE THREAD

**Issue by FatherWh0** [EssentialsX/Essentials#567]
With all the plugins i have I can not keep from grabbing ppl's drops unless I am disguised. If essentialsx had /np it would be awesome. Thx for your time.

**Comment by pop4959** [comment]
There is not enough details in this feature request to consider implementing. Please re-create the issue and be far more specific as to what you're asking for here.

**Comment by mdcfe** [comment]
This seems like the exact use case for spectator mode - you can watch players without impacting the world, and you also get noclip and flight.
