### ISSUE TITLE
Format parsing bug

### ISSUE THREAD

**Issue by 5rdx** [EssentialsX/Essentials#5670]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=2a531e2ea16041419996fd768ad1b315

### Bug description

When u use /ignore command on console this format parsing bug appears.
![Screenshot_6](https://github.com/EssentialsX/Essentials/assets/75033975/75ab699a-ea1c-451f-8ca5-afd0d5a3eb65)

### Steps to reproduce

1) Use /ignore command on console.
2) its done

### Expected behaviour

The <> color codes shouldn't be in messages.

### Actual behaviour

There's <> color codes in messages.

**Comment by MODNMETL** [comment]
To add, we're also getting similar with social spy messages in game.

Here's our dump all: https://essentialsx.net/dump.html?id=9d03ba682ac44010862bd053a77260c9

![image](https://github.com/EssentialsX/Essentials/assets/89078751/b3ee4c15-48f9-4016-b370-d46ca104f020)
