### ISSUE TITLE
error on execute /kill command in dev build essentials.

### ISSUE THREAD

**Issue by SL-69** [EssentialsX/Essentials#5672]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=e459163dd5054a779f6d0d953e87ecc9

### Error log (if applicable)

https://logpaste.com/1y5NUSWJ

### Bug description

error on execute /kill command in dev build essentials.

### Steps to reproduce

install:
Server: 1.20.4-R0.1-SNAPSHOT git-Purpur-2141 (MC: 1.20.4)
EssentialsX : 2.21.0-dev+42-8a57856
LuckPerms: 5.4.117
Vault: 1.7.3-b131
PlaceholderAPI: 2.11.5
EssentialsXSpawn: 2.21.0-dev+42-8a57856
and execute /kill <player>

### Expected behaviour

kill player

### Actual behaviour

player not die and essentialsx say error in console

**Comment by pop4959** [comment]
This should be fixed in the latest version of Paper. Since you're using Purpur you might need to wait a bit longer for them.
