### ISSUE TITLE
motd.txt do not support russian language

### ISSUE THREAD

**Issue by SL-69** [EssentialsX/Essentials#5673]
### Type of bug

Compatibility issue

### `/ess dump all` output

https://essentialsx.net/dump.html?id=f0d0941322ec47df923ab6a9837e42fd

### Bug description

russian language displayed incorrectly

### Steps to reproduce

1. write russian words in motd.txt

### Expected behaviour

correctly displyed russian in motd.txt

### Actual behaviour

russuan letters displayed incorrectly 
![2024-02-15_01 56 39](https://github.com/EssentialsX/Essentials/assets/137718036/11efe99b-8881-4e64-b5c2-d4d588966a2a)

**Comment by LaxWasHere** [comment]
Save your file as UTF-8, if that does not work add `-Dfile.encoding=UTF-8` to your startup script.
