### ISSUE TITLE
Ptime and Pweather lang formatting

### ISSUE THREAD

**Issue by Jsinco** [EssentialsX/Essentials#5674]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

Not really applicable, mdcfe told me to create this

### Bug description

![image](https://github.com/EssentialsX/Essentials/assets/67713846/6822106f-15a1-4685-8882-547acf90cb66)

Ptime and Pweather langs can't be modified and arent parsed for colors.

### Steps to reproduce

/ptime day
/pweather storm

### Expected behaviour

Should be configurable in lang and color codes should be parsed

### Actual behaviour

Ptime and Pweather langs can't be modified and arent parsed for colors.

**Comment by JRoy** [comment]
Fixed as of 221a6622f38f3e4dad206faaa8844cacfd8bf909
