### ISSUE TITLE
Essentials /msg command not working and /time outputting strange message

### ISSUE THREAD

**Issue by DeanMSalter** [EssentialsX/Essentials#5676]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=5a176dc252474b389dc5ee70ca234f17

### Bug description

When using /msg, /mail and potentially other commands, nothing is outputted in the console or in chat, this is with essentials debug on as well. The usual messages about checking permissions are shown but nothing else.

The /time command outputs the following:
![image](https://github.com/EssentialsX/Essentials/assets/33103575/c0a712d4-4c70-40d9-a0c5-ff160117480e)

### Steps to reproduce

Run /msg , /mail or /time

### Expected behaviour

Msg should output the message sent or atleast the expected format, time should output the time cleanly.

### Actual behaviour

When using /msg, /mail and potentially other commands, nothing is outputted in the console or in chat, this is with essentials debug on as well. The usual messages about checking permissions are shown but nothing else.

The /time command outputs the following:
![image](https://github.com/EssentialsX/Essentials/assets/33103575/c0a712d4-4c70-40d9-a0c5-ff160117480e)

**Comment by JRoy** [comment]
Fixed as of 221a6622f38f3e4dad206faaa8844cacfd8bf909
