### ISSUE TITLE
this may not be an issue; when i started server essentials gave an error when checking version. it did not impact anything about essentialsx!

### ISSUE THREAD

**Issue by anthony1204** [EssentialsX/Essentials#5679]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=bae3577e8ede4614a57ee8f720088775

### Error log (if applicable)

https://paste.gg/p/anonymous/962ac580a1ab4261a30df434f47d3bbe

### Bug description

when starting server, gave error when it said getting version.
is this even a bug? or is it something with my server performance

### Steps to reproduce

no clue how it happened

### Expected behaviour

no error 

### Actual behaviour

error
![image](https://github.com/EssentialsX/Essentials/assets/78404321/2a0f765e-8d6b-4e4c-a530-6dfaa3a06f67)

**Comment by JRoy** [comment]
This is due to bad IO or low ram, not an Essentials bug.
