### ISSUE TITLE
My ranks aren't showing up.

### ISSUE THREAD

**Issue by RebeccaGames** [EssentialsX/Essentials#568]
For some reason ranks on my server quit showing up. I was using essentials and lordpermissions but for some reason ranks quit showing up as prefixes. I changed to essentialsx thinking it might help as it is updated regularly. I must have a wrong setting somewhere. I am wondering if you have any ideas. I am attaching my essentialsx config file in hopes that is where my error is. If you have any other ideas or need other info please let me know. I am on MC version 1.9.2 with Spigot and have essetnialsx chat jar.
[Essentialsx Config.docx](https://github.com/drtshock/Essentials/files/216224/Essentialsx.Config.docx)

**Comment by drtshock** [comment]
Ranks aren't showing up how? You might need esschat for it to show up in chat. Or a permissions plugin for them to work.
