### ISSUE TITLE
Luckperms prefix in chat 

### ISSUE THREAD

**Issue by Ajayrx** [EssentialsX/Essentials#5681]
### Feature description

format: '%luckperms-prefix% {DISPLAYNAME} : &f{MESSAGE}'
  #format: '&7[{GROUP}]&r {DISPLAYNAME}&7:&r {MESSAGE}'
  #format: '&7{PREFIX}&r {DISPLAYNAME}&r &7{SUFFIX}&r: {MESSAGE}'

  group-formats:
  #  default: '{WORLDNAME} {DISPLAYNAME}&7:&r {MESSAGE}'
  #  admins: '{WORLDNAME} &c[{GROUP}]&r {DISPLAYNAME}&7:&c {MESSAGE}'

  # If you are using group formats make sure

### How the feature is useful

I want that essentialsxchat to take luckperms prefix directly if u just put %luckperms-prefix%
https://essentialsx.net/dump.html?id=82075d55859142849f33126129e548a1

**Comment by Evidentsinger14** [comment]
EssentialsX uses Vault to get prefixes/suffixes from other plugins to avoid having to support multiple different plugins. There is a list of all built in placeholders [Here](https://essentialsx.net/wiki/Keywords.html), and you can use {PREFIX} to get the vault prefix.
