### ISSUE TITLE
color problem - me - vol 2

### ISSUE THREAD

**Issue by 100petr** [EssentialsX/Essentials#5689]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=69b59ca2ae7d4b9289927d01f402aaaf

### Bug description

Color codes are not displayed correctly in /me if the command is executed by commandblock/console. (in the previous issue the colors were fixed for messages sent by the player)
![image](https://github.com/EssentialsX/Essentials/assets/29830635/a98afe39-3314-41c7-bada-87358c7d9d00)

### Steps to reproduce

Update to the latest version of essentials
send me test from the console/commandblock

### Expected behaviour

me will display colors correctly

### Actual behaviour

me displays colors incorrectly when sent from commandblock/console

**Comment by Evidentsinger14** [comment]
![image](https://github.com/EssentialsX/Essentials/assets/46200123/147f8e3c-b566-4510-b62c-cd23a25e297c)
![image](https://github.com/EssentialsX/Essentials/assets/46200123/44a033da-23d8-45ac-b3f5-2963dcd80d89)
Confirmed in-game works fine, and console is still broken.
