### ISSUE TITLE
Colors not displaying on error messages (at least the heal one but I believe others may be affected too)

### ISSUE THREAD

**Issue by 777Ricky** [EssentialsX/Essentials#5690]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=905200618ace4b52b38f02e65f92cb9c

### Bug description

![image](https://github.com/EssentialsX/Essentials/assets/12014016/bc20935c-7b2b-4073-a0e5-60ec30332bb4)

This is what my message properties are set as for that message
`timeBeforeHeal=<aqua>Time before next heal\:<aqua> {0}<aqua>.`

### Steps to reproduce

As far as I know the only step to reproduce is being on one of the last handful of dev builds

### Expected behaviour

The message should be colored like all other messages

### Actual behaviour

Message is left unformatted/colored

**Comment by Evidentsinger14** [comment]
![image](https://github.com/EssentialsX/Essentials/assets/46200123/a27764fb-da2c-427e-8e37-99008433c339)
Confirmed
