### ISSUE TITLE
Error message when trying to enter a command

### ISSUE THREAD

**Issue by Z1nnho** [EssentialsX/Essentials#5691]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=0a0d75fb8bf94d3fac8fd3a647f50221

### Bug description

When trying to use a command, be it normal minecraft commands like "gamemode" or essentials commands, you get an error massage in the new essentials version (EssentialsX-2.21.0-dev+55-4386713) (I would also like to add that I downgraded my version to the one I was before and it worked perfectly fine)
![Captura de tela 2024-02-20 180201](https://github.com/EssentialsX/Essentials/assets/105995214/7c8a0bcc-ce8d-4c19-837c-113135bfa599)

### Steps to reproduce

update to the newest version of essentials (EssentialsX-2.21.0-dev+55-4386713) (I also had EssentialsXChat-2.21.0-dev+55-4386713 installed at the moment)

I also deleted config.yml in essentials files so it would also update

restart the server

try to type any command (gamemode, essentials etc)

### Expected behaviour

use the command normally

### Actual behaviour

you get an error massage

**Comment by Evidentsinger14** [comment]
![image](https://github.com/EssentialsX/Essentials/assets/46200123/ee9ff185-5a65-4654-9350-349da30c1086)
I cannot replicate this behavior. I'd suggest trying without other plugins

**Comment by Z1nnho** [comment]
> ![image](https://private-user-images.githubusercontent.com/46200123/306452525-ee9ff185-5a65-4654-9350-349da30c1086.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NzYxMjksIm5iZiI6MTcwODQ3NTgyOSwicGF0aCI6Ii80NjIwMDEyMy8zMDY0NTI1MjUtZWU5ZmYxODUtNWE2NS00NjU0LTkzNTAtMzQ5ZGEzMGMxMDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDAwMzcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhNDRkZjkxNzAyNjIzMWNhMGRlYTBjYzIxYmU1MTJmZmY4YzlhNGI0MTk3NmY3NWEyZGIxNmRkZTgzZmFkNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7IxOne79MJ_XapWAJBgkfk6kDoWq2f8tjZR6uMsDTLA) I cannot replicate this behavior. I'd suggest trying without other plugins

Could the problem be because of old files?

**Comment by pop4959** [comment]
The latest dev builds require you to update your message files. You may need to delete/update the old ones.

Cannot replicate, so closing. Feel free to comment here if you have further information to share, or create a new issue if you believe you have a specific bug to report.
