### ISSUE TITLE
invsee and ec for offline player

### ISSUE THREAD

**Issue by efor89** [EssentialsX/Essentials#5696]
### Feature description

can you add invsee and ec command for offline player with extra permission.
that admins with the permission can see in the inventory.

### How the feature is useful

for admins its good after a safe bann or something else to see the inventory and ec of the offline player.

**Comment by pop4959** [comment]
This has been requested numerous times, but this is out of scope for Essentials especially given there is no API for getting this data for offline players.

Use something like [OpenInv](https://dev.bukkit.org/projects/openinv) if you absolutely need such a feature.
