### ISSUE TITLE
Players automatically getting /vanish even if the aren't typing /vanish

### ISSUE THREAD

**Issue by NightBenMC** [EssentialsX/Essentials#5707]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=23fd9abda2cd43bd84f4af66423f2e3e

### Bug description

If a player with vanish permissions (or op) are getting automatically Vanish (if they type /vanish when they log in it will say that they are now vanished and if they type it again they will finally be unvanished

### Steps to reproduce

1. Connect to server (with permissions)
2. All done you have now vanish
3. (Optional) type 2x Vanish and you are visible again

### Expected behaviour

after connecting i should be seen by other players but i am not

### Actual behaviour

after connecting only op players are seeing me and i need to type 2x /vanish so normal players can see me

**Comment by NightBenMC** [comment]
i apologize for mistakes in Bug Description section i hope that you can understand it

**Comment by pop4959** [comment]
This sounds like you have the `essentials.silentjoin.vanish` permission. Please use the Discord server for help using Essentials and look at the [permission reference](https://essinfo.xeya.me/permissions.html) for additional help with permissions..

**Comment by NightBenMC** [comment]
ok thanks
