### ISSUE TITLE
fly for certain worlds?

### ISSUE THREAD

**Issue by Twi5TeD** [EssentialsX/Essentials#571]
is it possible to have fly in only certain worlds as im using powerfulperms and i gave a user the permission `pp user player add essentials.fly skyblock skyworld` this makes it so you can have fly on skyblock in the skyworld so the user can do /fly in skyworld but not at spawn. when the user goes to spawn they cannot do fly but if you toggle it on the island and go to spawn they still have fly enabled is there anyway to stop this?

**Comment by drtshock** [comment]
multiverse allows you to remove fly on worldchange i think.

**Comment by Twi5TeD** [comment]
already tried that still doesnt work
