### ISSUE TITLE
Server cannot shut down

### ISSUE THREAD

**Issue by pjindras** [EssentialsX/Essentials#5713]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=c239b2eb009a41e48ff1f1a2d9824263

### Error log (if applicable)

https://paste.gg/p/anonymous/a07da6e9aba24390b6c75d5092248653

### Bug description

Server cannot shut down and constantly is spamming errors, when the players use /home before server stop.

### Steps to reproduce

Try to stop the server and on last time /home

### Expected behaviour

Server should stop

### Actual behaviour

I had to kill it with data loss.

**Comment by JRoy** [comment]
Looks like MythicMobs or a Purpur issue not ours
