### ISSUE TITLE
Console spam /list

### ISSUE THREAD

**Issue by vxkShelby** [EssentialsX/Essentials#5718]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=0ace8cc3cf5c4e5e9f104c60f0a15df6

### Bug description

Essentials spam every 3 minutes to console /list .... is it okay or can i turn it of or fix it somewhere 

29.02 12:33:24 [Server] INFO [Essentials] CONSOLE issued server command: /list 
29.02 12:33:24 [Server] INFO There are 2 out of maximum 30 players online.
29.02 12:33:24 [Server] INFO Players: [Member] yassino12, [Owner] vxkShelby
29.02 12:36:31 [Server] INFO [Essentials] CONSOLE issued server command: /list 
29.02 12:36:31 [Server] INFO There are 2 out of maximum 30 players online.
29.02 12:36:31 [Server] INFO Players: [Member] yassino12, [Owner] vxkShelby
29.02 12:39:37 [Server] INFO [Essentials] CONSOLE issued server command: /list 
29.02 12:39:37 [Server] INFO There are 2 out of maximum 30 players online.
29.02 12:39:37 [Server] INFO Players: [AFK][Member] yassino12, [AFK][Owner] vxkShelby
29.02 12:42:44 [Server] INFO [Essentials] CONSOLE issued server command: /list 
29.02 12:42:44 [Server] INFO There are 2 out of maximum 30 players online.
29.02 12:42:44 [Server] INFO Players: [AFK][Member] yassino12, [AFK][Owner] vxkShelby
29.02 12:45:51 [Server] INFO [Essentials] CONSOLE issued server command: /list 
29.02 12:45:51 [Server] INFO There are 2 out of maximum 30 players online.
29.02 12:45:51 [Server] INFO Players: [AFK][Member] yassino12, [AFK][Owner] vxkShelby

### Steps to reproduce

Always ... 

### Expected behaviour

i would like to turn it off becouse of spammin

### Actual behaviour

Its spamming console every 3 minutes

**Comment by Evidentsinger14** [comment]
EssentialsX does not spam it's own commands in console. This is likely your hosting company's panel doing this for crash detection, or for getting online players/ player counts. Multicraft in particular is known for doing this, I would reach out to your host to ask if that is the case, and if so what you can do about it.
