### ISSUE TITLE
Auto afk kick message

### ISSUE THREAD

**Issue by Sikatsu** [EssentialsX/Essentials#572]
Hey,

I would like to disable the message for other players ''(player) is kicked because of being inactive for 20minutes.''

It would be nice if only the kicked player gets a message ''You are kicked because of inactivity.''

Is there anyway to do this? I made sure to check the language file, but if I remove the message of auto afk kick, it says ''(player) is kicked because of'' and for the player it just says you are kicked.

Thanks in advance,

Sikatsu

**Comment by drtshock** [comment]
So you want to remove the broadcast and only send a message to the player?

**Comment by Sikatsu** [comment]
Yes indeed! But it seems the broadcast is linked to the normal kick message of essentials.

**Comment by Sikatsu** [comment]
@SupaHam @drtshock

This is what I basically meant, just saw I requested it earlier.

**Comment by mdcfe** [comment]
I don't see that this is something that will be changed, as EssentialsX uses the regular kick mechanism for disconnecting AFK players.

**Comment by drtshock** [comment]
Can you not remove the message (not the key) for `playerKicked` and then have it not show?
