### ISSUE TITLE
color from /nick transfers into balance on /baltop

### ISSUE THREAD

**Issue by melaniebeedot** [EssentialsX/Essentials#5720]
### Type of bug

Performance issue or memory leak

### `/ess dump all` output

https://essentialsx.net/dump.html?id=51d23c2aac7044efb7ead9697c0c5389

### Bug description

I just noticed recently that the last color in a /nickname is the color of your balance in /baltop, I don't remember this happening before... I tested it with my own name which normally has white at the end:

![baltop1](https://github.com/EssentialsX/Essentials/assets/98659383/6d50607c-a1af-47ee-8405-10a434d28285)
![baltop2](https://github.com/EssentialsX/Essentials/assets/98659383/05d5b8ed-5df2-4e78-b866-b4ba2c8a9c35)

### Steps to reproduce

1. Update to the latest dev build of EssentialsX
2. Have players with colored nicknames
3. View /baltop

### Expected behaviour

I thought all the balances were just supposed to be white numbers?

### Actual behaviour

Apparently the last color used in your nickname is the color your balance will be.

**Comment by Evidentsinger14** [comment]
![image](https://github.com/EssentialsX/Essentials/assets/46200123/6f37e621-5c88-4b6b-a208-cd549140bd37)
Confirmed

**Comment by TiagoFar78** [comment]
Could you assign this issue to me, please? I am doing a school project where I need to fix a bug of an open source project and I would love to fix this one. I will start working on it as soon as possible! Thank you in advance.

**Comment by Evidentsinger14** [comment]
Typically issues aren't assigned to specific people, with the exception being maintainers when it's something that has broken as a result of a specific commit. If you would like to fix this issue, feel free to open a PR, and link to it in the PR template for bug fix and somebody will review it 😄
