### ISSUE TITLE
The text of the ban message is buggy

### ISSUE THREAD

**Issue by PeppoDevStudio** [EssentialsX/Essentials#5721]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=99ab4eb298bf4456bea1c8c1ac1677e4

### Bug description

The text of the ban message is buggy, i have last version dev of plugin.

![IMG_2682](https://github.com/EssentialsX/Essentials/assets/70705179/6b297816-52ec-4780-92c1-ed878a7d7931)

### Steps to reproduce

1. I banned myself for trying

2. I logged back into the server 2 times and saw the buggy message.

### Expected behaviour

The text should appear with colors.

### Actual behaviour

The text appears with hex color and for example <white>

**Comment by Evidentsinger14** [comment]
![image](https://github.com/EssentialsX/Essentials/assets/46200123/c479a968-00f8-4353-9d59-88413082e406)
![image](https://github.com/EssentialsX/Essentials/assets/46200123/4d5821c7-ca8c-4789-becf-aa5f4de9f118)
Confirmed
