### ISSUE TITLE
Essentials Load Bug

### ISSUE THREAD

**Issue by PeppoDevStudio** [EssentialsX/Essentials#5725]
### Type of bug

Error in console

### `/ess dump all` output

Command not work..

### Error log (if applicable)

https://mclo.gs/miPUS25

### Bug description

Hi, I was 42 dev build back, I updated the plugin to the latest version and I got this bug.

### Steps to reproduce

1. Stop server
2. Delete old plugin
3. Upload new version
4. Start server

### Expected behaviour

Plugin load

### Actual behaviour

Plugin not load

**Comment by PeppoDevStudio** [comment]
Full logs: https://mclo.gs/HtJIbSm

**Comment by Evidentsinger14** [comment]
Update your server jar.

**Comment by PeppoDevStudio** [comment]
Okay
