### ISSUE TITLE
Essentials moves player balance to npc file when they change their user name.

### ISSUE THREAD

**Issue by ntall1** [EssentialsX/Essentials#574]
14.04 15:28:22 [Server] INFO YeeeHaww (formerly known as dexmachina) joined the game 14.04 15:28:22 [Server] INFO Found new UUID for YeeeHaww. Replacing e2b7cb0a-312b-3bc2-bade-9d324bdfa831 with 3d1952eb-4279-4f3f-84da-4d057bf1b150

e2b7cb0a-312b-3bc2-bade-9d324bdfa831 ends up as:
`npc: true
lastAccountName: yeeehaww
money: '397.791'`

3d1952eb-4279-4f3f-84da-4d057bf1b150 ends up with all the existing player data minus the balance.

**Comment by mdcfe** [comment]
Closing this in favour of #2400, which is the same issue but has more detail.
