### ISSUE TITLE
respawn-listener-priority - newbie kit

### ISSUE THREAD

**Issue by stormkiller0** [EssentialsX/Essentials#5742]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

1

### Bug description

If you set the respawn-listener-priority and spawn-join-listener-priority parameters to none, then essentials will not extrude sets on the first connection

### Steps to reproduce

1

### Expected behaviour

1

### Actual behaviour

1

### Additional Information

1

**Comment by JRoy** [comment]
You must fill out the template

**Comment by mdcfe** [comment]
If you disable the join listener, you disable everything that EssentialsX Spawn does on join. Set it to lowest priority if you want another plugin to override the spawn location.
