### ISSUE TITLE
GeoIP cant connect to database - Error 401

### ISSUE THREAD

**Issue by cxmorgan** [EssentialsX/Essentials#5744]
### Type of bug

Error in console

### `/ess dump all` output

 https://essentialsx.net/dump.html?id=19167aa04b5d4082b5f76cb5e2f98fb8

### Error log (if applicable)

https://paste.gg/p/anonymous/140d49f93dba4228a865e9f84787a6c4

### Bug description

GeoIP cant connect to maxmind, says - unathorized access

### Steps to reproduce

1. Create a new key in maxmind acount
2. paste into GeoIP config

### Expected behaviour

GeoIP file should be downloaded

### Actual behaviour

GeoIP file didnt downloaded, error in console

### Additional Information

I tried to copy link from console and paste it into a browser to download it manually, but it didnt work. It shows this 
![image](https://github.com/EssentialsX/Essentials/assets/19522113/59ae519a-2ed7-466d-8eff-50ad47636705)

**Comment by pop4959** [comment]
Please create a license key following the instructions from the link printed in the console. You do not have a valid license key, which is why it is not working. This is not a bug with GeoIP.

**Comment by StKillReal** [comment]
@pop4959 It really doesn't work. I suppose because of this
![image](https://github.com/EssentialsX/Essentials/assets/60330193/21640dfe-cea9-4de2-b6fa-a447beba31b3)

**Comment by pop4959** [comment]
> @pop4959 It really doesn't work. I suppose because of this ![image](https://private-user-images.githubusercontent.com/60330193/337405487-21640dfe-cea9-4de2-b6fa-a447beba31b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MDU0NzcsIm5iZiI6MTcxNzcwNTE3NywicGF0aCI6Ii82MDMzMDE5My8zMzc0MDU0ODctMjE2NDBkZmUtY2VhOS00ZGUyLWI2ZmEtYTQ0N2JlYmEzMWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDIwMTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhYTBlMTczZjc4MmI4MzBjMjZlYzg3ZDZhNjEwODA2ODNmYzZhYzQwYzQ4Y2NlMmQxNmFlNDA2YmUzMzk1N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U3yDExZThJ3NUCyUcVu1GwC6Zy1CnjyrMcRncgGxhCQ)


That change was made over a year ago. This is not a bug.

Please join the Discord server if you are having trouble configuring GeoIP.
