### ISSUE TITLE
Language File Broken

### ISSUE THREAD

**Issue by zzkanezz2** [EssentialsX/Essentials#5746]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=fc92e5218b9046a999a0aed035467865

### Bug description

Language files seem to be all janky, will include what I mean in the screenshot attached. I'm using the default language file, still has the # in front of it in config.

### Steps to reproduce

1. Server has to be on
2. Use a repair sign
3. Teleport to player etc.

### Expected behaviour

Clean language file

### Actual behaviour

Language file with broken prefixes:

![image](https://github.com/EssentialsX/Essentials/assets/2730910/9061bd96-17d5-4fe0-8b90-59f1dee40b99)

![image](https://github.com/EssentialsX/Essentials/assets/2730910/20d73414-c6fe-4b4b-98b6-7d3c889d1fbc)

**Comment by zzkanezz2** [comment]
Downgraded to stable release and this fixes the issue.

**Comment by kaua-noleto** [comment]
I would like essentialsX for Brazilian Portuguese language

**Comment by ImDarkLaw** [comment]
> I would like essentialsX for Brazilian Portuguese language

Please do not comment on unrelated posts. This has nothing to do with this bug report. 

Translations are handled on [crowdin](https://crowdin.com/project/essentialsx-official).

**Comment by Evidentsinger14** [comment]
Both messages mentioned (Teleport cooldown, and repair sign + cannot be repaired) have been fixed as of this moment. 
Closing as completed - if  you find any others, please open a new issue.
