### ISSUE TITLE
Player join messages doesn't appear at discord when it's the first time a player joins

### ISSUE THREAD

**Issue by snurre0** [EssentialsX/Essentials#5747]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=38f3f2073da649d8a43938f5865e0649

### Bug description

With the EssentialsX discord addon set up to post chat and join/leave messages to a discord channel, and a brand new player joins the server, their join-message doesn't appear at discord. All other join messages do appear.

### Steps to reproduce

- Set up the discord addon to display chat and join/leave messages in a discord channel
- Have a brand new player that has never been on the server join
- Have a player that has been on the server before also join

### Expected behaviour

Both join messages should appear at discord

### Actual behaviour

Only join messages from the player that has been on the server before appear on discord, not the join message for the brand new player.

### Additional Information

In-game screenshot of one old player and one new player joining:
![image](https://github.com/EssentialsX/Essentials/assets/12727805/bc513180-284e-473d-aeac-8b0894c3831c)

The chat log from discord from the same time:
![image](https://github.com/EssentialsX/Essentials/assets/12727805/905751c5-b71d-4285-8b8f-ab8556f98957)

**Comment by ImDarkLaw** [comment]
Please send a new `/ess dump all` link, as this one's invalid.

**Comment by snurre0** [comment]
> Please send a new `/ess dump all` link, as this one's invalid.

Oh, I see that now. Link in the first post has now been updated.

**Comment by ImDarkLaw** [comment]
I cannot reproduce this on a fresh setup. Your EssentialsX Discord appears to be missing several settings, including the [`first-join`](https://github.com/EssentialsX/Essentials/blob/2.x/EssentialsDiscord/src/main/resources/config.yml#L126) message type. You can compare your current config.yml with the default one found on github linked [here](https://github.com/EssentialsX/Essentials/blob/2.x/EssentialsDiscord/src/main/resources/config.yml) and add any missing settings.

Additionally, I recommend employing the [binary search method](https://docs.bloom.host/binarysearch) to check for conflicting plugins, if any, in your setup causing this.

**Comment by snurre0** [comment]
> I cannot reproduce this on a fresh setup. Your EssentialsX Discord appears to be missing several settings, including the [`first-join`](https://github.com/EssentialsX/Essentials/blob/2.x/EssentialsDiscord/src/main/resources/config.yml#L126) message type. You can compare your current config.yml with the default one found on github linked [here](https://github.com/EssentialsX/Essentials/blob/2.x/EssentialsDiscord/src/main/resources/config.yml) and add any missing settings.
> 
> Additionally, I recommend employing the [binary search method](https://docs.bloom.host/binarysearch) to check for conflicting plugins, if any, in your setup causing this.

All right, thank you for checking it out!
I will look over my config and try to fix whatever is going on with our setup.

Btw, I had the impression that Essentials would update it's config when there were changes to config options, during upgrade. At least that used to be the case, right?
That said, I haven't touched my essentials discord config since I added the first quite early build of essentials discord.

**Comment by snurre0** [comment]
Updating the config did the trick, thanks a lot!
