### ISSUE TITLE
EssentialsX Discord fatal error on start

### ISSUE THREAD

**Issue by Ragchel** [EssentialsX/Essentials#5748]
### Type of bug

Error in console, Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=9eab4ba6c8b14a67908229b58f3cacec

### Error log (if applicable)

[16:31:54] [Server thread/ERROR]: [EssentialsDiscord] An error occurred while logging into Discord, which has caused the plugin to disable itself: 
Cannot invoke "net.essentialsx.discord.util.WrappedWebhookClient.close()" because the return value of "java.util.Map.remove(Object)" is null

### Bug description

When starting the server EssentialsX discord log ins and sends a “server has stopped” message on discord and then logs out again.

### Steps to reproduce

Unsure how to recreate the issue as this happens before server finishes starting up and started happening without any config changes.

### Expected behaviour

Discord addon logs into the bot and syncs chat up

### Actual behaviour

“Server has stopped” message on discord and no further session gets set up

**Comment by ImDarkLaw** [comment]
Please ensure that all fields on the form are filled out completely and provide your `/ess dump all` link crucial in order to properly diagnose and look into this issue.

(You can edit your initial message and insert your /ess dump all output where it's expected.)

**Comment by Ragchel** [comment]
Is the information correct now or am I still missing something?

**Comment by dada-crafter** [comment]
It gives me the same error every time I try to launch the server. The bot connects, sends the message that the server is closing and then disconnects while the server is open. As a result, the bot no longer works. Have you found the solution?

**Comment by dada-crafter** [comment]
I found the solution, in fact it is the avatar system that is bugged. It is necessary to put it in false so that the plugin does not crash.
