### ISSUE TITLE
Badly formatted error message?

### ISSUE THREAD

**Issue by Prof1611** [EssentialsX/Essentials#5749]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=1ee8f287f42f4d00bd552a6b82d3941d

### Bug description

![image](https://github.com/EssentialsX/Essentials/assets/144668269/8873d1d5-be84-467a-936f-ad87f0deecc4)
When attempting to use a buy sign with insufficient funds the text formatting of the error message seems broken. Unsure if this has been reported before.

### Steps to reproduce

1. Create a [Buy] sign
2. Attempt to purchase with insufficient funds
3. View error message

### Expected behaviour

Normal error message

### Actual behaviour

Badly formatted error message

**Comment by pop4959** [comment]
This is the `notEnoughMoney` translation key, so this should be fixed by #5736 when merged.
