### ISSUE TITLE
don't cover "spigot.yml" messages: sever-full:

### ISSUE THREAD

**Issue by CatTeaA** [EssentialsX/Essentials#5750]
### Feature description

"EssentialsX" has a serverfull message
But I want to show it by the spigot.yml's settings
<spigot.yml>
messages:
  server-full: xxxxxxx

### How the feature is useful

"EssentialsX" is updated frequently, and I can't change the prompts every time
<serverfull>

**Comment by mbax** [comment]
The EssX message shouldn't change every update. Are you experiencing loss of messages from your config on upgrade?

**Comment by CatTeaA** [comment]
# Should Essentials override the vanilla "Server Full" message with its own from the language file?
# Set to false to keep the vanilla message.
use-custom-server-full-message: true

sorry
