### ISSUE TITLE
Heal signs do not account for custom max health values

### ISSUE THREAD

**Issue by ImDarkLaw** [EssentialsX/Essentials#5751]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=4d77c9610f5d470ab46f0142b21415fd

### Bug description

The [onSignInteract](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/java/com/earth2me/essentials/signs/SignHeal.java#L19-L33) method inside the [SignHeal](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/java/com/earth2me/essentials/signs/SignHeal.java) class responsible for handling interactions with heal signs, currently, sets the player's health to 20 without considering potential increases in amount of health due to the generic max health attribute.

### Steps to reproduce

Suggested course of action to reproduce this behavior:

1. Ensure heal signs are enabled in the [config](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/resources/config.yml#L365):
```yaml
enabledSigns:
  - heal
 ```
 2. Create a [heal sign](https://wiki.mc-ess.net/wiki/Sign_Tutorial#Heal_Sign) by placing a sign and typing "[Heal]" on the first line.
 3. Use [`/attribute @p minecraft:generic.max_health base set 40`](https://minecraft.fandom.com/wiki/Commands/attribute) to change our base maximum health value, in this case, doubling it to 40.
 4. Right click on the sign and notice that our health is set back to 20 and the health buff removed.

### Expected behaviour

One would expect that [onSignInteract](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/java/com/earth2me/essentials/signs/SignHeal.java#L19-L33) the player's health would be set to the maximum amount respecting modified maximum health values.

### Actual behaviour

Upon interacting with a heal sign, health value is being [set to 20](https://github.com/ImDarkLaw/Essentials/blob/2.x/Essentials/src/main/java/com/earth2me/essentials/signs/SignHeal.java#L26) no matter what, without accounting for an increased amount of hearts.

**Comment by Chew** [comment]
Interesting how this is fixed in the `/heal` but not here. Good catch!

https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/java/com/earth2me/essentials/commands/Commandheal.java#L43-L76

**Comment by ImDarkLaw** [comment]
Yes, it seems like there's already a solution in the `/heal` command implementation. 

I'm currently in the process of implementing a quick fix for the [SignHeal](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/java/com/earth2me/essentials/signs/SignHeal.java) class to address this.

The proposed solution involves retrieving the player's maximum health attribute and setting their health accordingly, instead of the hardcoded 20 value. I've shared the implementation details in [this pastebin](https://pastes.dev/IoUDWv0WXv). Let me know your thoughts and i can proceed to submit a PR.

**Comment by pop4959** [comment]
Something like that should be fine. Doesn't hurt to open a PR so more users can test.

I will note that this may require a version check for feature / API not present in old versions of the game - but aside from that this fix is fairly straightforward (set the proper health, not just 20).
