### ISSUE TITLE
When the player exits, an incorrect value was returned using the {ONLINE} variable in the custom message.

### ISSUE THREAD

**Issue by HotWaterFlask** [EssentialsX/Essentials#5753]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=663f29cfa75f4b91ba4a066aa7668b3f

### Bug description

I set config.yml to
...
custom-join-message: "&6[{ONLINE}/100]&e{USERNAME} Join the game！"
custom-quit-message: "&6[{ONLINE}/100]&e{USERNAME} Left the game！"
...

If two players are online and a player named "abc" leaves the game, the server will send "&6 [2/100]&eabc Left the game!" to the online player.
But the correct thing is that the server should send "&6 [1/100]&eabc Left the game!" to online players.
The server should return the number of online players after the player left, rather than the number of online players before leaving.

### Steps to reproduce

1.At least two online players.
2.Modify config.yml and use the {ONLINE} variable in custom quit message.
3.run /ess reload
4.One of the players disconnects from the server (exits the game).

### Expected behaviour

 server should send "&6 [1/100]&eabc Left the game!" to online players.

### Actual behaviour

the server will send "&6 [2/100]&eabc Left the game!" to the online player.

### Additional Information

The server should return the number of online players after the player left, rather than the number of online players before leaving.

**Comment by Evidentsinger14** [comment]
This was fixed as of #5541. Please update to the latest development build.
