### ISSUE TITLE
Essentials color codes not working?

### ISSUE THREAD

**Issue by Paceski** [EssentialsX/Essentials#5756]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

says error code: 520

### Error log (if applicable)

https://prnt.sc/MXlJ2ZevytGS

### Bug description

I'm having this issue since moving to Dev build to get the Heal sign fix. I've touched nothing config wise, and it worked before!

### Steps to reproduce

Do /baltop or any other essentials commends that have <green> or simmilar.

### Expected behaviour

.

### Actual behaviour

.

### Additional Information

.

**Comment by Evidentsinger14** [comment]
Please provide your message file in a [pastebin](https://pastes.dev) and a full screenshot of `/ess version`

**Comment by Paceski** [comment]
https://pastes.dev/GuBLxwvRIH
https://prnt.sc/eiTjil-hzcdh

**Comment by Paceski** [comment]
Will update to stable version for now since this is just a huge bug for me

**Comment by pop4959** [comment]
Your message file looks to be incorrect and you're running an unsupported server type.
