### ISSUE TITLE
notEnoughMoney it is not formatted

### ISSUE THREAD

**Issue by M0odi** [EssentialsX/Essentials#5758]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=53c7e24a1d3d420baf8aac76d77a61ae

### Bug description

Im using ru language, and my message "notEnoughMoney" not formatted. It is not assigned colors and indents \n. 

My config: notEnoughMoney=\n<white>  У вас недостаточно средств \n
Result (message): Not formatted message

That is, there are no colors or indentation in the message :( 
![Screenshot_1](https://github.com/EssentialsX/Essentials/assets/117448340/f4ef0f3c-7d29-4fe0-be1e-b087b36a987f)

### Steps to reproduce

1) Set in 880 line: notEnoughMoney=\n<white>  У вас недостаточно средств \n
2) Transfer more to the player than you have on your balance

### Expected behaviour

The message is formatted correctly

### Actual behaviour

The message was not formatted

**Comment by M0odi** [comment]
M
![Screenshot_2](https://github.com/EssentialsX/Essentials/assets/117448340/670f3bce-f8b7-40ff-9bdc-79e0d24ffdc6)
y essentials version:

**Comment by M0odi** [comment]
my messages config: https://pastebin.com/HrXh2jR5

**Comment by pop4959** [comment]
This will be fixed by #5736. I will see if we can merge it soon, since this seems to be reported a lot.
