### ISSUE TITLE
cantGamemode message doesn't return the translated values for gamemodes

### ISSUE THREAD

**Issue by davidgb8246** [EssentialsX/Essentials#5763]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=b73afca8ddd842cf93bbbf36454f8c37

### Bug description

When a player runs the command "/gamemode creative", the plugin sends the message "cantGamemode". The issue is that the placeholder {0} of that message doesn't return the values on "adventure", "creative"...

![image](https://github.com/EssentialsX/Essentials/assets/85250523/9aeba2e4-e6ec-4336-8dfc-09cd17e54889)
![image](https://github.com/EssentialsX/Essentials/assets/85250523/489c09d9-11cf-4eea-94dd-c6c0ee600096)
![image](https://github.com/EssentialsX/Essentials/assets/85250523/69e4aa2c-f3ed-4f2f-aa1b-fae86f3d9e6f)

### Steps to reproduce

1. Install the plugin.
2. Change the locale configuration on the plugin's config.
3. Modify the values of the game modes.
4. Run that command.

### Expected behaviour

The plugin should return the translated values instead of the default ones in upper case.

### Actual behaviour

The plugin doesn't return the translated values on that message.

**Comment by Evidentsinger14** [comment]
Confirmed - the plugin is only pulling from the English translation file. should just be as simple as removing that hardcoded value.
