### ISSUE TITLE
po

### ISSUE THREAD

**Issue by Leotamvan** [EssentialsX/Essentials#5765]
### Type of bug

Error in console

### `/ess dump all` output

o

### Error log (if applicable)

ghjg

### Bug description

```java

``` 

### Steps to reproduce

1

### Expected behaviour

u

### Actual behaviour

p

### Additional Information

 knp eror ya padahal mau saya mainin

**Comment by ImDarkLaw** [comment]
If you're reporting a genuine issue, please take the time to properly fill in the fields and ensure you provide sufficient detials regarding the issue you're experiencing. Without proper information, this issue will be closed.
