### ISSUE TITLE
Failed to fetch pom.xml for paperlib-1.0.6

### ISSUE THREAD

**Issue by Greymagic27** [EssentialsX/Essentials#5766]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

N/A

### Bug description

This is a bug when trying to use essentialsX as a dependency for my maven project.

Upon trying to package this it gives an error that it could not find the module 'paperlib-1.0.6.jar'. This is because the pom.xml is not present so it cannot fetch the correct version to download. Manually downloading this .jar solves the issue.
![image](https://github.com/EssentialsX/Essentials/assets/46166848/374e01d9-44cb-424b-8ba8-e007a39d73fc)
![image](https://github.com/EssentialsX/Essentials/assets/46166848/35fbb412-9228-452f-8b49-4f78b0acd30a)

### Steps to reproduce

1) Git clone https://github.com/Greymagic27/advanced-achievements/tree/master
2) Try to run 'mvn clean package'
3) Get presented with the error
4) Try again but this time add the missing ,jar to `C:\Users\Username\.m2\repository\io\papermc\paperlib\1.0.6` https://mvnrepository.com/artifact/io.papermc/paperlib/1.0.6
5) Observe that it now works

### Expected behaviour

The package command would be able to download the paperlib.jar

### Actual behaviour

It cannot download the paperlib.jra leading to an error

**Comment by JRoy** [comment]
Add paper's maven repo to your project

**Comment by Greymagic27** [comment]
I added the paper lib one but the project still didn't like it. I'll play around with it when I can though
