### ISSUE TITLE
/helpop messages not being sent to the sender

### ISSUE THREAD

**Issue by KM-Owner** [EssentialsX/Essentials#5768]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=e7180ab512e44ace9e7732b0a040143f

### Bug description

/helpop messages not being sent to the sender

### Steps to reproduce

.

### Expected behaviour

.

### Actual behaviour

.

**Comment by Evidentsinger14** [comment]
Confirmed. In the future, please fill the entire template out, don't just put dots for the boxes.
