### ISSUE TITLE
Clarrification on "GroupManager is NOT SUPPORTED." message.

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#577]
Im finally getting around to updating my server to 1.9; I have all my legacy plugins working using the spigot specialsource, this includes groupmanager. Now your message "GroupManager is NOT SUPPORTED." are you referring to people asking you to update groupmanager? Or have you completely dropped support for GroupManger in your recent builds??? I hope, that you have just put that message there to stop people nagging you to fork GroupManager.

**Comment by drtshock** [comment]
Sorta both. Groupmanager hooks with vault which we hook. We don't directly support it. We also don't support groupmanager as in we don't update it or maintain it.

**Comment by TomLewis** [comment]
allright, so question being now; can I use your latest builds with GroupManger? Or will something break? Everything seems to be working fine as it stands now.
No other Permissions system even comes close to being at GM standards. Pex is awful and zpermissons setup is terrible. Theres not a good alternative.

**Comment by drtshock** [comment]
not sure. you can use groupmanager but we won't be giving you any help on it.

**Comment by TomLewis** [comment]
Yeah no sweat man, the big red message just freaked me out.

**Comment by drtshock** [comment]
good :)
