### ISSUE TITLE
I can't edit bc message at messages

### ISSUE THREAD

**Issue by PeppoDevStudio** [EssentialsX/Essentials#5773]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

Created server dump: https://essentialsx.net/dump.html?id=9c3c91c0231b4d56872b19da995ff771

### Bug description

Hi, I tried to edit the bc message but every time the file updates and doesn't save the changes...

### Steps to reproduce

1)  Edit bc line at messages.yml
2)  Save file
3) Reload Plugin
4) Reload Server

### Expected behaviour

The bc message had to appear modified and not: "ATTENTION » "

### Actual behaviour

The bc is not updated and remains the default.

**Comment by Evidentsinger14** [comment]
The file is `messages_(locale code).properties`, not .yml.

**Comment by PeppoDevStudio** [comment]
Sorry, I made a mistake in indicating the file, that's what you say. I have the same problem.

**Comment by PeppoDevStudio** [comment]
Could you reopen the report?

**Comment by Evidentsinger14** [comment]
Re-opening issue. Show your Essentials file directory that includes the message file, and send a proper dump link `/ess dump all` (you did not send the correct link. the "all" arg was missing)

**Comment by PeppoDevStudio** [comment]
Created server dump: https://essentialsx.net/dump.html?id=1829723269fa48ef8fd84c1a625e3b11

[Essentials.zip](https://github.com/EssentialsX/Essentials/files/15141775/Essentials.zip)

**Comment by PeppoDevStudio** [comment]
It seems as if it updates itself every time

**Comment by Evidentsinger14** [comment]
![image](https://github.com/EssentialsX/Essentials/assets/46200123/c70e9b12-16f3-4e25-8d0a-aab5bf139a7f)
Your locale file works fine on my server. Make sure you've used `/ess reload` and not `/reload` on the server when making config changes. 

This should be a support question for MOSS. if you're still having issues with it, ask in the support discord. they'll be able to help you better there. https://discord.gg/PHpuzZS

**Comment by PeppoDevStudio** [comment]
Try changing it and restarting the server, the change is not saved.

**Comment by PeppoDevStudio** [comment]
My edit: broadcast=<#f2eeed>⏰ <bold><\#00aeff>ѕᴜʀᴠɪᴠᴀʟ ɴᴇᴡѕ </bold><#f2eeed>» </#f2eeed>{0}

**Comment by Evidentsinger14** [comment]
![image](https://github.com/EssentialsX/Essentials/assets/46200123/e123ee7e-868d-4bac-8bc9-8310ea1bd175)
it works fine. as I said before, you should reach out for support in [MOSS](https://discord.gg/PHpuzZS) as this is a support related issue, not a bug. the plugin is working fine, this seems like a misconfiguration on your end. Closing issue.
