### ISSUE TITLE
I can't edit bc message at message file

### ISSUE THREAD

**Issue by PeppoDevStudio** [EssentialsX/Essentials#5775]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=9c3c91c0231b4d56872b19da995ff771

### Bug description

Hi, I tried to edit the bc message but every time the file updates and doesn't save the changes...

### Steps to reproduce

1) Edit bc line at messages
2) Save file
3) Reload Plugin
4) Restart Server

### Expected behaviour

The bc message had to appear modified and not: "ATTENTION » "

### Actual behaviour

The bc is not updated and remains the default.

**Comment by Evidentsinger14** [comment]
You do not need to create a new issue. If there was a valid reason for your old one to be re-opened, it would have been. This should have been something asked in [discord](https://discord.gg/PHpuzZS) and we would redirect you here if there was a legitimate issue. I will re-open your old issue.
