### ISSUE TITLE
EssentialsXDiscordLink Error

### ISSUE THREAD

**Issue by Elusive62Official** [EssentialsX/Essentials#5781]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=f2183f68ab6f47b7aa483dd95920a1ca

### Bug description

I am trying to set up Discord Link module, I have all I need..., clearly seen in the ess dump, but for the life of me..., I can't figure this one out....,

EssentialsXDiscord is working PERRRRRFECTLY, PLEASE HELP!

I get the /link command appearing, but it shows an error when entering the command...

"An internal error occurred while attempting to perform this command"

### Steps to reproduce

I wish i knew...

### Expected behaviour

I expect it to work...

### Actual behaviour

I just throws that error in the terminal...

### Additional Information

All help appreciated.

**Comment by ImDarkLaw** [comment]
GroupManager is no longer supported. To resolve this, we recommend migrating to [LuckPerms](https://luckperms.net/), a supported permission manager.

You can find instructions for migrating permissions data from GroupManager to LuckPerms in LuckPerms' wiki linked [here](https://luckperms.net/wiki/Migration).
