### ISSUE TITLE
New Placeholder to lang

### ISSUE THREAD

**Issue by itsme-to** [EssentialsX/Essentials#5787]
### Feature description

Add a new placeholder for lang message that return the player name, not displayname.

### How the feature is useful

Really usefull to make clickable button like, tpa accept, tpa cancel,... Otherwise the commands cannot be executed if the person has a nick, a colored name or a prefix. Example, it's try "/tpaaccept &c[Admin] Itsme_to"

**Comment by nobstergo** [comment]
isn't it already available? "{USERNAME}"
https://essentialsx.net/wiki/Keywords.html#:~:text=player%27s%20display%20name.-,%7BUSERNAME%7D,-The%20player%27s%20username

**Comment by itsme-to** [comment]
Not for messages
![CleanShot 2024-05-02 at 11 09 21](https://github.com/EssentialsX/Essentials/assets/43671109/a58cffd8-ae0d-42af-b92d-d45d340da6f6)

**Comment by nobstergo** [comment]
> Not for messages ![CleanShot 2024-05-02 at 11 09 21](https://private-user-images.githubusercontent.com/43671109/327375369-a58cffd8-ae0d-42af-b92d-d45d340da6f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NDIyNzEsIm5iZiI6MTcxNDY0MTk3MSwicGF0aCI6Ii80MzY3MTEwOS8zMjczNzUzNjktYTU4Y2ZmZDgtYWUwZC00MmFmLWI5MmQtZDQ1ZDM0MGRhNmY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDA5MjYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0NmY0MzUyN2JjYWE0MmQ1ZDRhYTk3OGUxOGEzMTgwZGU0NGI0MDQyYTg0MTczNWVkNTUxNjk5YjQxNjc5NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t0Mz87LSjYAgj9NDo2saXtnFd-V4kmRIRQjgtz499sg)

my bad. i thought they're also available for language files. im sorry.

**Comment by Evidentsinger14** [comment]
Message files use a completely different setup for the placeholders. if you need it to be a username, disable `change-displayname` in the config.

**Comment by itsme-to** [comment]
This does not fix the problem, so people can no longer have a nickname

**Comment by Evidentsinger14** [comment]
You will have to reconfigure your chat format to use {NICKNAME} if that's what you're referring to.

**Comment by itsme-to** [comment]
No, I mean any nick plugin or other that change the display name will break the clickable message/

**Comment by Evidentsinger14** [comment]
Not if you do what I just told you to do. EssentialsX will only use the username.
