### ISSUE TITLE
interactible names

### ISSUE THREAD

**Issue by bacalhau-seco** [EssentialsX/Essentials#5795]
### Feature description

i basically want that thing where you can click on someone name and it writes a custom command in the chat like `/wisper` or `/tpa` for example. This could be configured by the server owner.
And also make it so you can acept or deny tpa requests by clicking on them

### How the feature is useful

it makes it so players dont have to write the same commands every time as these commands can be highly used.

**Comment by ImDarkLaw** [comment]
As of the recent dev builds that introduced [Adventure](https://docs.advntr.dev/index.html) support, you can use the [click](https://docs.advntr.dev/minimessage/format.html#click) and [hover](https://docs.advntr.dev/minimessage/format.html#hover) tags to run commands on-click and display MiniMessage strings on-hover. 

You can check out the wiki for an example showcasing the usage of rich text elements [here](https://essentialsx.net/wiki/Locale.html).

**Comment by Evidentsinger14** [comment]
Adventure has been merged into the development builds making this possible. Closing as completed.
