### ISSUE TITLE
PAPI Placeholders in custom-join-message and custom-join-message

### ISSUE THREAD

**Issue by ZepsiZola** [EssentialsX/Essentials#5797]
### Feature description

I should be able to configure PAPI placeholders tp be used in `custom-join-message` and `custom-quit-message`.

![image](https://github.com/EssentialsX/Essentials/assets/49735083/8b661a9b-aaad-4ee2-8387-8a1b3acaefae)

### How the feature is useful

The feature would allow people to have external (non-essentials) nicknames be used in the join/leave messages. I am not using essentials nicknames as they do not carry over seperate servers. The current nickname plugin I use does carry nicknames across servers.

The plugin already allows PAPI placeholders for the `first-join` message, so why not these custom join/leave messages?

**Comment by Evidentsinger14** [comment]
I'm not sure what first join you're referring to, but the only part of EssentialsX that currently supports PlaceholderAPI is the discord module, and related addons. 
 #1945 is where all PlaceholderAPI related discussion will be at, so closing in favor of that issue.
