### ISSUE TITLE
Armor Trims Don't Save on Kit Creation

### ISSUE THREAD

**Issue by jacobjake1** [EssentialsX/Essentials#5799]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

NA

### Error log (if applicable)

NA

### Bug description

Simply just make a kit with any armor trim on it, and redeem the kit. It won't have any trims on it.

### Steps to reproduce

Simply just make a kit with any armor trim on it, and redeem the kit. It won't have any trims on it.

### Expected behaviour

It should have the trim

### Actual behaviour

It doesn't

### Additional Information

I'm on Essentials version 2.20.1

**Comment by mbax** [comment]
The dump output is flagged as required when filing a bug for a reason.

**Comment by jacobjake1** [comment]
> The dump output is flagged as required when filing a bug for a reason.

https://essentialsx.net/dump.html?id=ebf559a0ffa2499cbe4829931050c86d

**Comment by xIdentified** [comment]
Had the same issue, here's my server dump https://essentialsx.net/dump.html?id=4dcc7ae8812b495eac656ee746fb24c7

**Comment by ImDarkLaw** [comment]
Enable the [`use-nbt-serialization-in-createkit`](<https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/resources/config.yml#L357>) setting in your config and recreate the kit.

**Comment by jacobjake1** [comment]
> Enable the [`use-nbt-serialization-in-createkit`](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/resources/config.yml#L357) setting in your config and recreate the kit.

This fixed the issue. Thanks.

**Comment by Gravintation** [comment]
Hello there, I am having a similar issue with armor trims in kits, however I believe my problem stems from formatting as I already have nbt serialization enabled. Would anyone be able to see why the trim is not showing up on the item? There is nothing online that I can find about adding trims and I am not sure where else to ask.

![image](https://github.com/user-attachments/assets/a891903b-e08d-481a-ba83-ac3df008f440)

**Comment by LaxWasHere** [comment]
Please join our discord for support. nbt serialization is disabled based on that picture you provided.
