### ISSUE TITLE
what is this for?

### ISSUE THREAD

**Issue by cicatrice74** [EssentialsX/Essentials#581]
18.04 20:47:45 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
18.04 20:47:45 [Server] WARN at com.earth2me.essentials.Essentials.onCommand(Essentials.java:375)
18.04 20:47:45 [Server] WARN at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:465)
18.04 20:47:45 [Server] WARN at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:146)
18.04 20:47:45 [Server] WARN at com.earth2me.essentials.commands.Commandwarp.run(Commandwarp.java:46)
18.04 20:47:45 [Server] WARN at com.earth2me.essentials.commands.Commandwarp.warpUser(Commandwarp.java:111)
18.04 20:47:45 [Server] WARN at com.earth2me.essentials.Teleport.warp(Teleport.java:258)
18.04 20:47:45 [Server] WARN at com.earth2me.essentials.Teleport.teleport(Teleport.java:201)
18.04 20:47:45 [Server] WARN at com.earth2me.essentials.Teleport.now(Teleport.java:142)
18.04 20:47:45 [Server] WARN at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.teleport(CraftPlayer.java:468)
18.04 20:47:45 [Server] WARN at net.minecraft.server.v1_9_R1.PlayerList.moveToWorld(PlayerList.java:684)
18.04 20:47:45 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
18.04 20:47:45 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
18.04 20:47:45 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
18.04 20:47:45 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
18.04 20:47:45 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:497)
18.04 20:47:45 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18.04 20:47:45 [Server] WARN at sun.reflect.GeneratedMethodAccessor546.invoke(Unknown Source)
18.04 20:47:45 [Server] WARN at com.onarandombox.multiverseinventories.InventoriesListener.playerChangedWorld(InventoriesListener.java:183)
18.04 20:47:45 [Server] WARN at com.onarandombox.multiverseinventories.ShareHandler.handleSharing(ShareHandler.java:56)
18.04 20:47:45 [Server] WARN at com.onarandombox.multiverseinventories.WorldChangeShareHandler.handle(WorldChangeShareHandler.java:33)
18.04 20:47:45 [Server] WARN at com.onarandombox.multiverseinventories.WeakProfileContainer.getPlayerData(WeakProfileContainer.java:87)
18.04 20:47:45 [Server] WARN at com.onarandombox.multiverseinventories.WeakProfileContainer.getPlayerData(WeakProfileContainer.java:98)
18.04 20:47:45 [Server] WARN at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.getPlayerData(FlatFilePlayerData.java:283)
18.04 20:47:45 [Server] WARN at com.onarandombox.multiverseinventories.util.data.DefaultPlayerProfile.<init>(DefaultPlayerProfile.java:76)
18.04 20:47:45 [Server] WARN at com.onarandombox.multiverseinventories.api.share.InventorySerializer.deserialize(InventorySerializer.java:10)
18.04 20:47:45 [Server] WARN at com.onarandombox.multiverseinventories.api.share.InventorySerializer.deserialize(InventorySerializer.java:20)
18.04 20:47:45 [Server] WARN at com.onarandombox.multiverseinventories.api.DataStrings.parseInventory(DataStrings.java:421)
18.04 20:47:45 [Server] WARN java.lang.ArrayIndexOutOfBoundsException: 36

**Comment by drtshock** [comment]
Can you paste the full stack trace in a pastebin or other paste service.

**Comment by cicatrice74** [comment]
i only have this when my players do /warp in another world

**Comment by cicatrice74** [comment]
no more messages on console
