### ISSUE TITLE
was banned from discord for no reason just asking why a plugin wasnt working

### ISSUE THREAD

**Issue by sanitygrey** [EssentialsX/Essentials#5811]
### Type of bug

Error in console

### `/ess dump all` output

...

### Bug description

was banned out of the discord for simply asking why the spawn polugin wasnt working 

### Steps to reproduce

1 join the discord
2 ask why a plugin wasnt working 
3 get banned instantly 

### Expected behaviour

to get some help

### Actual behaviour

get banned

**Comment by Evidentsinger14** [comment]
This is not what GitHub issues are for.
