### ISSUE TITLE
/back command

### ISSUE THREAD

**Issue by Dejf15** [EssentialsX/Essentials#5815]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=405181f79a1e4942a53351c21e05f07d

### Bug description

Players requested to have permission to tp to their death position, so i put essentials.back.ondeath perm node to their permission group and many players has opened ticket that /back after they die and they get the "You don't have a permission to use this command" text.

### Steps to reproduce

1. Player die
2. They run /back
3. It says "You don't have a permission to use this command"

### Expected behaviour

1. Player die
2. They run /back
3. They should teleport to their death location

### Actual behaviour

They don't teleport to their death location :c

**Comment by ImDarkLaw** [comment]
Insufficient permissions to execute a command is not considered a bug. This issue can be better addressed on our [Discord](https://discord.gg/PHpuzZS) server. Please redirect your query there and ensure that users have the necessary permissions:

- `essentials.back` - Required to access the /back command.
- `essentials.back.ondeath` - Allows teleportation back to the player's death location.

If granting the above permissions does not resolve the issue, we may need additional information from you. In this case, please use the support channel on our Discord. Thanks.
