### ISSUE TITLE
Don't force dismount players from vehicles on teleport

### ISSUE THREAD

**Issue by Puremin0rez** [EssentialsX/Essentials#582]
Essentials is forcibly dismounting players from vehicles whenever a teleport is fired from within the plugin.

My best guess is that this logic was done because back in the day, Craftbukkit did not allow a teleport if a player was in a vehicle.

Craftbukkit has forcibly dismounted players from vehicles for quite some time now, so having this code in Essentials feels redundant and in particular breaks setups where the server actually wants the player to stay mounted on the vehicle when a teleport occurs via means of custom server code.

The only issue with removing this code would be for legacy users on really old builds of Craftbukkit (builds prior to July 7, 2013, MC 1.6), so if that's a concern, maybe make it configurable.

**Comment by drtshock** [comment]
This is a long standing issue that Hobbits had mentioned he wanted changed years ago.

**Comment by vemacs** [comment]
EssX doesn't run on any version lower than 1.7.10 anyways
