### ISSUE TITLE
Home name tab completion display wrong characters when they are Non-ASCII

### ISSUE THREAD

**Issue by Clexus** [EssentialsX/Essentials#5821]
### Type of bug

Compatibility issue, Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=994d719497bd4537885fe3bc67991ed6

### Error log (if applicable)

nope

### Bug description

home related commands don't support non-ASCII words, they are all replaced by _

### Steps to reproduce

/sethome 测试
/sethome ÂâĀ
then
/home and tab complete
you'll see /home __ or /home ___
![image](https://github.com/EssentialsX/Essentials/assets/62130504/d9373b7b-69e4-4ad9-99f5-d444d6401216)

### Expected behaviour

/sethome 测试
/home 测试

### Actual behaviour

/sethome 测试
/home __

### Additional Information

no

**Comment by pop4959** [comment]
Home names are alphanumeric. This is working as intended.

Do note there is a feature request already open for supporting non-alphanumeric home names.
