### ISSUE TITLE
Currency won't be changed even IF I change it in the config.yml file

### ISSUE THREAD

**Issue by baph0metsdaughter** [EssentialsX/Essentials#5826]
### Type of bug

Compatibility issue, Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=db7ead4249494bf886f02f70e3bef0a0

### Bug description

As mentioned in the title, me and my friends are having a big issue with the currency change. We want to replace the currency symbol with a word, 14 characters long. No symbols, only letters. The file is saved as UTF-8 like the creator said in the note inside the config

# Set this to a currency symbol you want to use.
# Remember, if you want to use special characters in this document, 
# such as accented letters, you MUST save the file as UTF-8, not ANSI.

And we did, still no change. I also wanted to have the currency in the suffix, after the amount of money. Even with the dollar sign, no change. Is this a bug or am I doing something wrong? Please help and try to describe everything as detailed as possible. Thank you!

### Steps to reproduce

I go into the config.yml

looking for the line where I can change currency (line 803 I guess)
changed it, also set currency-symbol-suffix: true
 
doing /reload on the Server

### Expected behaviour

Should actually change into 

example: 15 Frühlingsrollen
 (Frühlingsrollen should be the currency, insider joke in my Community.)

### Actual behaviour

Keeps being the '$' and being the prefix... No matter what I do

**Comment by gibsonpil** [comment]
It doesn't look like your configuration changes are shown in the dump you posted. 

> doing /reload on the Server

Have you tried reloading EssentialsX using `/essentials reload` and/or restarting your server? `/reload` isn't officially supported by EssentialsX.

**Comment by baph0metsdaughter** [comment]
ah nvm, gimme a second. It now uses the currency as suffix but I can't use letters after all, only symbols. if I try to make a word or any letter it changes back to $, at least as suffix.


dump: https://essentialsx.net/dump.html?id=3b1da9663ea54ddb95a9a9c5625373cd

now it's this one.

**Comment by baph0metsdaughter** [comment]
> Have you tried reloading EssentialsX using `/essentials reload` and/or restarting your server? `/reload` isn't officially supported by EssentialsX.

right now I did but somehow it doesn't change anything, nothing after /essential reload or server reload. Changed back to $

**Comment by baph0metsdaughter** [comment]
and btw how exactly do I say it as UTF-8? I used VSC for it and in the bottom right corner there was the 'UTF-8' so I think it was right. My friend told me he saved it as such already. Clicked on it, chose UTF-8 again and clicked 'save with encoding'

**Comment by gibsonpil** [comment]
I took a look at the [code](https://github.com/EssentialsX/Essentials/blob/3a6fdd9bf30463f68ba819f7583204ff963eb36c/Essentials/src/main/java/com/earth2me/essentials/Settings.java#L910) responsible for setting the currency symbol and unfortunately it appears that this is isn't a bug. Currency symbols that aren't a single non-integer character are deliberately set to "$".

**Comment by LaxWasHere** [comment]
Currency symbols only accepts a single character.

**Comment by baph0metsdaughter** [comment]
> Currency symbols only accepts a single character.

So you can't even change it? To more?

**Comment by Evidentsinger14** [comment]
You can change it. Just not to more than 1 character.

**Comment by baph0metsdaughter** [comment]
yeah but that was exactly what I wanted. Can I change the max length anywhere?

**Comment by gibsonpil** [comment]
No.

**Comment by baph0metsdaughter** [comment]
> No.

bruh. That sucks. Anyway...Any idea with any other economy plug in where we can change the currency?

**Comment by gibsonpil** [comment]
> > No.
> 
> bruh. That sucks. Anyway...Any idea with any other economy plug in where we can change the currency?

No, sorry. An issue tracker probably isn't a great place to ask that kind of a question either. Maybe try the SpigotMC forums or something similar.
