### ISSUE TITLE
/skull gives a head item with wrong metadata. The skull does not apply the skin

### ISSUE THREAD

**Issue by silicondev** [EssentialsX/Essentials#5830]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=bda598042c8d4b28a3f2463dafc1ff60

### Bug description

I have tested various methods of obtaining player heads. Both through vanilla Minecraft /give and the HeadsDatabase plugin, the heads given both have a "textures" property in the metadata, and have an ID system of id: [I; x, y, z, a] with x, y, z, and a being different integers. The heads generated from /skull have an id of [I, 0, 0, 0, 0] and no textures property, and as such only display the default skin.

### Steps to reproduce

1. run /skull <playername>
2. run /minecraft:give <your playername> minecraft:player_head[minecraft:profile={name: "<playername>"}]
3. Place both on the ground and check the textures.

### Expected behaviour

Both heads should have the same texture

### Actual behaviour

The head generated from /skull has the default texture.

### Additional Information

Version: 2.21.0-dev 93

**Comment by abulujayn** [comment]
Could you provide a new link for `/ess dump all`. The one you provided doesn't seem to be working. I've just tested this issue on 1.21 with zero issues so want to confirm your setup.

**Comment by Evidentsinger14** [comment]
Not sure if this is spigot specific or what, but i just addressed an issue exactly like this in the discord support channel, and it seemed like it did not work on spigot. I'm not experiencing this on paper, so i'd give paper a try. will mention this to the developers to see if it's something they want to look into. 
![image](https://github.com/user-attachments/assets/0cda9ea0-3d86-46eb-9f75-6963703eb817)
