### ISSUE TITLE
/nick should ignore color codes for nick character limit

### ISSUE THREAD

**Issue by matipoirierg** [EssentialsX/Essentials#5831]
### Feature description

When setting a nickname with multiple hex colors, the plugin denies it due to the character limit for custom nicks. I suggest that color codes should not count towards the nickname length limit. This would allow for greater flexibility without the need to set an excessively high limit in the config than can couse other issues.

### How the feature is useful

 Greater flexibility without the need to set an excessively high limit in the config than can couse other issues.

**Comment by SrBedrock** [comment]
In the config.yml file there is an option for this, set it to true.
```yml
# When this option is enabled, nickname length checking will exclude color codes in player names.
# ie: "&6Notch" has 7 characters (2 are part of a color code), a length of 5 is used when this option is set to true
ignore-colors-in-max-nick-length: false
```

**Comment by matipoirierg** [comment]
certified dumbass moment
