### ISSUE TITLE
Adding houses

### ISSUE THREAD

**Issue by Playsus1234** [EssentialsX/Essentials#5835]
### Feature description

Make it possible to add houses instead of installing them

2.  Add the clearenderchest and clearenderchestconfirm commands

### How the feature is useful

1234

**Comment by Evidentsinger14** [comment]
I'm not too sure what "add houses instead of installing them" means? 
as for a clearenderchest command that should be it's own suggestion

**Comment by Playsus1234** [comment]
For example, there is e1: 1 and e2: 2, and when a player has e1 and e2 permissions, he can only set up 3 houses.

**Comment by gibsonpil** [comment]
No offense, but you really need to write more detailed issues. I've seen you open vague and undescriptive issues across several Minecraft related projects and nobody ever knows what you're talking about.

**Comment by Playsus1234** [comment]
I'm talking about adding houses

sethome-multiple:
   e1: 1
   e2: 2
 
The player has the e1 and e2 permissions, and can set a maximum of 3 houses, not 2.

Houses are added if the player has these two permissions

**Comment by pop4959** [comment]
The permissions are not additive like that, you would need to create a new one (for example: `e3: 3`) and give that permission for the user to have 3 homes. This works as intended, and there aren't plans to change it at the moment.
