### ISSUE TITLE
Wrong color code format in Essentials messages

### ISSUE THREAD

**Issue by leogianfagna** [EssentialsX/Essentials#5836]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

don't need

### Bug description

```yml
itemsConverted=<\#51ED49>Itens convertidos para blocos\! # works normally
itemSellAir=<\#FF2323>Você tentou vender ar. Segure um item em sua mão para usar esse comando. #doesn't work
```

Translate key **itemSellAir** and **timeFormat** is not working with new format.
![image](https://github.com/EssentialsX/Essentials/assets/142264317/0de262b0-85b6-4f9b-802e-d2ff46d1a7b6)

### Steps to reproduce

Just test it on messages (new format)

### Expected behaviour

Changing to this, will fix it:

```diff
- itemsConverted=<\#51ED49>Itens convertidos para blocos\! # works normally
+ itemSellAir=§x§F§F§2§3§2§3Você tentou vender ar. Segure um item em sua mão para usar esse comando.
```
![image](https://github.com/EssentialsX/Essentials/assets/142264317/27a493f7-c7ca-42b6-a432-9d55dd42b341)

### Actual behaviour

A few updates ago, essentialsx changed the color format for messages to a "mini message" way and there are some keys that doens't work with the new model, but they do with legacy color code. I know about: **itemSellAir** and **timeFormat**

**Comment by leogianfagna** [comment]
`notEnoughMoney` another tag that works only with legacy

**Comment by pop4959** [comment]
Have you tried without the `\`? This may be escaping the tag.

E.g. `itemsConverted=<#51ED49>Itens convertidos para blocos!`

**Comment by dxnnv** [comment]
Have not been able to get minimessage to work on certain lines, even with trying the comment above, `currency` seems to be another line that only works with legacy.

**Comment by leogianfagna** [comment]
@pop4959 sorry my delay but I can confirm the message above. since the hex code it's working, it's fine by me but I thought it would be good to have warned you

**Comment by pop4959** [comment]
> @pop4959 sorry my delay but I can confirm the message above. since the hex code it's working, it's fine by me but I thought it would be good to have warned you

Great to hear. I'll go ahead and close this then.
