### ISSUE TITLE
Command Description string do not respect locale when not exist in the message config

### ISSUE THREAD

**Issue by itsme-to** [EssentialsX/Essentials#5841]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=624a170c9e294469b03506604bcbb935

### Bug description

To give an example, I have a message configuration in French, so all message descriptions and usages are not present in it.

EssentialsX correctly uses the messages it has in its jar to display in the same language except for commandDescription; it's the only message that defaults to English.

### Steps to reproduce

Set the `locale` option to `fr`, create a messages file config for french with only some message, don't include command description. 

### Expected behaviour

All message is style display in french from the default lang of the plugin

### Actual behaviour

commandDescription message is in english

**Comment by itsme-to** [comment]
This issue is not related to per-player-locale, the bug exist even without it enabled. 
![CleanShot 2024-08-26 at 12 59 25](https://github.com/user-attachments/assets/6fd61802-8b80-4333-a379-406e490f5597)

**Comment by AfkF24** [comment]
Same for usage messages, not just descriptions. The new title is lacking that part
