### ISSUE TITLE
make a new command

### ISSUE THREAD

**Issue by BluAxoVR** [EssentialsX/Essentials#5847]
### Feature description

"/kill" doesn't kill mobs or specific entities but "/killentity" is just the original kill command

### How the feature is useful

Makes killing entities like block displays easier

**Comment by Chew** [comment]
You can use `/minecraft:kill` to use the original kill command.

You can also map it to anything you'd like with the `commands.yml` file. https://bukkit.fandom.com/wiki/Commands.yml
