### ISSUE TITLE
add the stack and stackenderchest commands

### ISSUE THREAD

**Issue by Playsus1234** [EssentialsX/Essentials#5852]
### Feature description

add the stack and stackenderchest commands

alias stackenderchest:
stackec

### How the feature is useful

Qqqqq

**Comment by Playsus1234** [comment]
I know there is a stack command in worldguard but not everyone uses it

**Comment by Evidentsinger14** [comment]
You have made a few different suggestions now without any useful information as to what this is supposed to do, or why it should be added. "Qqqqq" means absolutely nothing. Please update your suggestions, and in the future include actual information, otherwise they may be closed.
