### ISSUE TITLE
insufficientFunds message shows <dark_red>

### ISSUE THREAD

**Issue by baailey** [EssentialsX/Essentials#5856]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=1dd3e9cd3a194eb780074a2885095595

### Error log (if applicable)

https://i.imgur.com/LVulDL7.png

### Bug description

When trying to pay someone more than what you have in your /balance, it will send the error without the colour code working

### Steps to reproduce

1. /pay someone more than what you have in your balance
2. Check message

### Expected behaviour

For it to display the message as dark red

### Actual behaviour

It shows the colour code and the message as white

**Comment by Evidentsinger14** [comment]
Closing as duplicate #5759
