### ISSUE TITLE
Vanishing Issues

### ISSUE THREAD

**Issue by NguyenSmart** [EssentialsX/Essentials#5865]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

Doesn't work even I already updated EssentialX Dev builds to the latest build.

### Error log (if applicable)

https://pastes.dev/g5Azhp4jJE

### Bug description

I was visible to server listing on Multiplayer menu while I was vanishing. I was hover over the number of players in the server on another minecraft screen. But the count of players in the server is Okay!
![image](https://github.com/EssentialsX/Essentials/assets/100951560/5d42e532-cfbb-4805-a09d-4f4ce1d031a2)

### Steps to reproduce

1. Use the main account to trigger "/vanish" command in the server.
2. Use another minecraft screen to hover the mouse over the number of players in the Multiplayer tab.
3. The main account which already has vanished is visible on the list.

### Expected behaviour

It shouldn't show up players who has vanished on the list.

### Actual behaviour

It shows up players who has vanished on the list.

**Comment by Evidentsinger14** [comment]
![image](https://github.com/user-attachments/assets/7333cbeb-0031-4a30-9037-a64a070a990d)
![image](https://github.com/user-attachments/assets/36770df3-b3a9-45df-ba29-987c7d584a1c)
I'm not able to reproduce this, it seems to be working as intended - double check that one of your client sided mods are not messing with this behavior.
