### ISSUE TITLE
config option to disable 1.21 raid farm nerf

### ISSUE THREAD

**Issue by kgncengiz** [EssentialsX/Essentials#5866]
### Feature description

a config option to disable 1.21 raid farm nerf.

### How the feature is useful

people who want to make an old-style raid farm in 1.21 can turn on the option in the config.

**Comment by pop4959** [comment]
Are you suggesting a new feature, or are you saying that something in Essentials "nerfs" raid farms (and if so, how)?

**Comment by kgncengiz** [comment]
I am suggesting a new feature that allows disabling Mojang's 1.21 raid farm nerf with a config option.

**Comment by pop4959** [comment]
Got it, yeah that unfortunately is something that would be out of scope for Essentials, since it is rather niche and would be out of place with features currently offered.

Sounds like a good idea for a standalone plugin or server mod though. Hope you're able to find something!
