### ISSUE TITLE
Error when opening (creative) inventory

### ISSUE THREAD

**Issue by LazyColgate** [EssentialsX/Essentials#5868]
### Type of bug

Error in console

### `/ess dump all` output

internal server error (i'm on the latest build)

### Error log (if applicable)

https://gist.github.com/LazyColgate/dca970a671922df06037903c5a88ced9

### Bug description

when opening the inventory, i get tons of error messages. 

### Steps to reproduce

1. start the server
2. be in creative (haven't tested survival yet)
3. open/close the inventory

### Expected behaviour

no error messages should arise.

### Actual behaviour

i get tons of error messages. aside from that, it works fine and no crashes happen.

**Comment by Evidentsinger14** [comment]
Fixed by updating
