### ISSUE TITLE
Does not work @..

### ISSUE THREAD

**Issue by KIRUYXAN** [EssentialsX/Essentials#5871]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

[16:29:16 INFO]: Error while creating dump <html> <head><title>500 Internal Server Error</title></head> <body> <center><h1>500 Internal Server Error</h1></center> <hr><center>nginx</center> </body> </html> .

### Bug description

On my server on version 1.20.1 @.. did not work in some commands via chat, but they worked in command blocks, and now on version 1.21 I have @.. do not work either in commands via chat or in teams via command blocks and even in execution, which is why I can’t properly configure all sorts of server features.

### Steps to reproduce

1. Enter the command with @.. 
2. It is possible to receive an error stating that such a player was not found

### Expected behaviour

The teams will work @..

### Actual behaviour

@.. in teams is considered the player's nickname

**Comment by Chew** [comment]
What commands? If you want to use the Minecraft commands with scopes like that, you'll need `/minecraft:` prepended to it. E.g. `/minecraft:kill`, then you'll be able to do `@..` stuff

**Comment by KIRUYXAN** [comment]
Well, yes, it worked, but it’s still extremely inconvenient to write before many minecraft commands:

**Comment by mbax** [comment]
Have you tried on the latest Paper release for 1.21? I think it resolves the command blocks part: https://github.com/EssentialsX/Essentials/issues/5860#issuecomment-2205014316

**Comment by KIRUYXAN** [comment]
well, yes, I installed the latest version but have not yet checked whether everything works there

**Comment by mbax** [comment]
Okay. Let us know when you have.

**Comment by KIRUYXAN** [comment]
I just checked and tp via execute in the command block does not work, and it does not work that when you teleport very high, it teleports to the ground so as not to crash

**Comment by KIRUYXAN** [comment]
I could try using /world instead /tp via in world, but in it you can’t choose where to teleport to another world, or choose someone else for teleportation

**Comment by Zoriot** [comment]
@KIRUYXAN maybe you can just default to the minecraft tp command?
https://essentialsx.net/wiki/Common-Issues.html#essentialsx-overrides-a-command-from-spigot-or-another-plugin
