### ISSUE TITLE
Attribute support with kits

### ISSUE THREAD

**Issue by ColdSpare** [EssentialsX/Essentials#5879]
### Feature description

If I create a kit with custom attribute changes (ex: I give an armor piece 20 generic armor) it wont save when someone claims a kit. This is pretty important for my server, and likely others as well.

### How the feature is useful

Allows for most customizability with kits.

**Comment by LaxWasHere** [comment]
Just enable nbt serialization in the config.

**Comment by Evidentsinger14** [comment]
as Lax said, nbt serialization is the suggested route to take. locate `use-nbt-serialization-in-createkit: false` in `/plugins/Essentials/config.yml`, change it to `true`, and re-create your kit. 
all of your attribute data will be saved in a serialized format (this won't be human readable, so you will have to re-create if you need to make changes)
