### ISSUE TITLE
msgCommandUsage= not working

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#5882]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

?

### Bug description

msgCommandUsage not working 

### Steps to reproduce

sending custom message in plugin not the editing

### Expected behaviour

?

### Actual behaviour

?

**Comment by mbax** [comment]
If you cannot fill out the template, especially not providing the output of `/ess dump all`, how do you plan to get help?

**Comment by ghost** [comment]
why do we need such information if it is not a critical error, it just does not send the message that is set and it is the same on every version of the server

**Comment by mbax** [comment]
Hey man, I'm just trying to warn you that the maintainers will probably close this if you can't even add the output of `/ess dump all`

**Comment by ghost** [comment]
https://essentialsx.net/dump.html?id=a5c44132b4574b509a06db971819ed5e
