### ISSUE TITLE
/kittycannon doesn't work (in 1.20.6)

### ISSUE THREAD

**Issue by Illusioner2520** [EssentialsX/Essentials#5885]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=911f40d6f2b0463ba7b2d367dbdb68a1

### Error log (if applicable)

https://paste.gg/p/anonymous/88fbe9d7fcb3431da72f1891ae81ca29

### Bug description

When running `/kittycannon`, only a cat spawns but doesn't get launched or disappears, effectively making it an infinite cat spawner. The error linked above appears in the console each time.

### Steps to reproduce

1. Execute the command /kittycannon
2. See the console error

### Expected behaviour

The cat should launch out from the player and explode

### Actual behaviour

The can just spawns at the player's head and is a normal cat

**Comment by justabluejay** [comment]
can confirm same bug on 1.20.4 essentials version 2.21.0-dev+110-f1a5caf

**Comment by Astolate** [comment]
Can verify, same bug on 1.20.4 essentials version 2.21.0-dev+110-f1a5caf
