### ISSUE TITLE
Can you turn off this annoying compass transmission?

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [EssentialsX/Essentials#5886]
### Feature description

Every time you click on the screen with a compass, you will throw the player into the block and get stuck alive.
This is not a strange function of essentials, but seems to be a mandatory function that comes with the server. Can the omnipotent ESS add a program that can intercept it?

### How the feature is useful

I~~ DON T~~KNOW~~~

**Comment by baailey** [comment]
Do you use WorldEdit? If so, that is the cause https://worldedit.enginehub.org/en/latest/usage/navigation/

**Comment by MinecraftEarthVillage** [comment]
> Do you use WorldEdit? If so, that is the cause https://worldedit.enginehub.org/en/latest/usage/navigation/

ok ...This is a problem with WorldEdit... Restart the server and successfully disable this feature (I previously ruled out this possibility because  //we reload, left clicking will still bounce the player away)
