### ISSUE TITLE
/bcw not supporting colour codes

### ISSUE THREAD

**Issue by baailey** [EssentialsX/Essentials#5888]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.htmld=424799e7c5b64a02a084d4f9cc7a3415

### Bug description

When using /bcw to send a broadcast in a specific world, it will not apply any colour codes https://i.imgur.com/aFR6Zzb.png

### Steps to reproduce

1. /bcw world &btest

### Expected behaviour

For the specific world broadcast to be full of colour as desired

### Actual behaviour

No colour

**Comment by Slimified** [comment]
Hey, I have created a pull request for this issue here:
https://github.com/EssentialsX/Essentials/pull/5913
