### ISSUE TITLE
Command-cost not working

### ISSUE THREAD

**Issue by justoboy** [EssentialsX/Essentials#589]
I set the price of kit-dtools to 100 (kit-dtools: 100) but when i do the command i get the kit but no money is deducted

**Comment by drtshock** [comment]
do you have vault installed?

can you paste the log file when doing this in essentialsx debug mode please

**Comment by justoboy** [comment]
No I don't have vault installed if I need that for it can u post link to download.

I can't put log up at moment but I will try to remember to do it later today

**Comment by justoboy** [comment]
[latest.txt](https://github.com/drtshock/Essentials/files/233591/latest.txt)

**Comment by justoboy** [comment]
here is new log with vault installed:
[latest.txt](https://github.com/drtshock/Essentials/files/233751/latest.txt)
 it looks like the problem is essentials.nocommandcost.all=true how do I change that?

**Comment by ClankyPoo** [comment]
that is a permission if you are OP or have given yourself ' \* ' the kits will be free
or have given that permission
