### ISSUE TITLE
No Nickname when enabling /vanish

### ISSUE THREAD

**Issue by DeoviserYT** [EssentialsX/Essentials#5891]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=897d32543bc5413cb5cb6e3d8ed13a9d

### Bug description

When enabling vanish with /v or /vanish it dosent show nickname in the vanish message but does when you unvanish

### Steps to reproduce

Do /v or /vanish

### Expected behaviour

The vanish enable message should have the player's nickname

### Actual behaviour

The vanish enable message shows the player's username

**Comment by Slimified** [comment]
Yes, this is occurring on my end as well with the latest version of Essentials on a new server.

**Comment by Slimified** [comment]
It turns out that this is actually a setting in the config. In the config.yml file, you must ensure that this setting is set to false:
hide-displayname-in-vanish
you can view its description in the config.yml file.
