### ISSUE TITLE
Hook ProtocolLib for 1.20.6

### ISSUE THREAD

**Issue by Yastrals** [EssentialsX/Essentials#5892]
### Type of bug

Compatibility issue, Error in console

### `/ess dump all` output

/ess dump all

### Error log (if applicable)

https://paste.gg/p/anonymous/f5443e4c44444d9cb5f53c5698a11a74

### Bug description

I have paper 1.20.6 and i downloaded the latest version of protocollib(build #726). I put in pom.xml all dependences with version 5.1.0(it doesn't work if i put 5.2.0 for some strange reason) and when i execute my plugin with protocollibhook, it doesn't work(the console give me that the "ProtocolManager" is null). i tried to get other builds from protocollib, but none of them work.

### Steps to reproduce

When i execute my plugin 1.20.6 with protocollib.

### Expected behaviour

protocollib hook should work for 1.20.6

### Actual behaviour

Console error.

**Comment by Chew** [comment]
1. I'm not sure how this relates to Essentials, did you mean to post here? https://github.com/dmulloy2/ProtocolLib
2. The version for that build is `5.3.0`, not `5.2.0` or `5.1.0`. Regardless, we can't help here.
