### ISSUE TITLE
Negative balance enhancement

### ISSUE THREAD

**Issue by JHarris12345** [EssentialsX/Essentials#5897]
### Feature description

We can enable negative balances for players, but is it possible to have a further option like "CommandNegativeOnly" which can be true or false. And essentially, if it's true, the only way players can get a negative balance is by a staff member /eco set or /eco taking it. So players cant still start /paying people into the negative

### How the feature is useful

It allows staff to set people to a negative balance without allowing everyone to have an "overdraft" that they can freely enter themselves

**Comment by Evidentsinger14** [comment]
Followed up on discord a while back, negative balances worked as the issue suggests it should. `/eco` bypassed loan restrictions, vault transactions, and /pay did not.
