### ISSUE TITLE
Cant Uninstall!

### ISSUE THREAD

**Issue by 1BenPro** [EssentialsX/Essentials#5898]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=eadb5408b58f4344a4ff9b7a475e3e4f

### Bug description

When I delete the plugin and restart the server, it just regenerates the files and runs as normally (with the plugins features).

### Steps to reproduce

Idk how trigger it.

### Expected behaviour

The plugin gets deleted and stays like that until I add it back

### Actual behaviour

It doesn`t stay deleted :(

### Additional Information

I am using Minehut to do this

**Comment by Evidentsinger14** [comment]
If you installed using their plugin installer, you need to uninstall it with that same installer. Essx doesn’t replace its own jar after being deleted.

**Comment by 1BenPro** [comment]
> If you installed using their plugin installer, you need to uninstall it with that same installer. Essx doesn’t replace its own jar after being deleted.

where can i find said installer?

**Comment by Evidentsinger14** [comment]
ask them. It’s their panel

**Comment by 1BenPro** [comment]
it came with the server tho

**Comment by mbax** [comment]
Plugins do not possess the ability to reinstall themselves. Talk to your host.
