### ISSUE TITLE
Repo down?

### ISSUE THREAD

**Issue by Sataniel98** [EssentialsX/Essentials#591]
Hi,
first of all, thank you very much for your great work :)

I have one issue, though: I need EssentialsX in a plugin as a dependency. I did the project setup just like you did in FactionsUUID, but it doesn't compile and NetBeans can't find it, neither ;_; Is it my fault or is it possible that the repo is down?

```
        <dependency>
            <groupId>net.ess3</groupId>
            <artifactId>EssentialsX</artifactId>
            <version>2.0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.ess3</groupId>
            <artifactId>EssentialsXChat</artifactId>
            <version>2.0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
```

```
        <repository>
            <id>ess-repo</id>
            <url>https://ci.drtshock.net/plugin/repository/everything/</url>
        </repository>
```

**Comment by vemacs** [comment]
Compile EssX locally (read instructions in readme), it'll be in your local maven repo. We're probably bringing ours back eventually.

**Comment by drtshock** [comment]
https://ci.drtshock.net/plugin/repository/everything/net/ess3/EssentialsX/
