### ISSUE TITLE
/vanish particles 

### ISSUE THREAD

**Issue by MrFadeFancy** [EssentialsX/Essentials#5914]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=e32546d4f25c445b959b2890c3485de4

### Bug description

Hi players can see your particles if you are vanished 

### Steps to reproduce

just do /v and if you are near a player they can see your particles 

### Expected behaviour

no particles 

### Actual behaviour

showing particles

**Comment by Evidentsinger14** [comment]
Unable to reproduce this behavior. make sure your players don't have essentials.vanish.effect granted to them.
