### ISSUE TITLE
1.20 and 1.21 items not recognized by essentialsx commands like /give

### ISSUE THREAD

**Issue by samkee00** [EssentialsX/Essentials#5917]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=9516ff0d5c7b46b384c7020cf9d94aab

### Bug description

Items added in 1.20 and 1.21, such as cherry_wood or vault respectively, aren't in items.json or recognized by essentials commands like /give. This can be bypassed by using /minecraft:give instead, but is inconvenient and could presumably be fixed by updating essentials' list of recognized items.

### Steps to reproduce

1. Try to run the /give command with an item added in 1.20 or 1.21 (ie /give samkee00 cherry_wood)

### Expected behaviour

The player should receive the specified item (in this case, cherry_wood)

### Actual behaviour

The text "Error: Unknown item name: cherry_wood." appears in chat

**Comment by Evidentsinger14** [comment]
Stop your server, delete `/plugins/Essentials/items.json` and then start the server. Try it again.

**Comment by samkee00** [comment]
> Stop your server, delete `/plugins/Essentials/items.json` and then start the server. Try it again.

I realized this almost immediately after posting this issue. So sorry
