### ISSUE TITLE
Add /take command

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#592]
Contrary to /give command function
/take <player> <item|numeric> [amount [itemmeta...]]
/take XYBlue 1 64 name:Diamond lore:A diamond
Can you add this new feature?
Thank you!

**Comment by techied** [comment]
You can use /invsee and pull the item[s] out of their inventory
or if you do not need the item, use /clear (playerName) [item:data] [amount]

**Comment by ghost** [comment]
@techied Thank you very much, but I can not use the /clear XYBlue 164 name:Diamond lore:A diamond.Name and lore are not working.It will tell me that I don't have this item

**Comment by techied** [comment]
Try /clear XYBlue 164 {name:Diamond,lore:"A diamond"}

or (1.7 and above) /clear XYBlue Diamond {name:Diamond,lore:"A diamond"}

**Comment by ghost** [comment]
It will still clean up items that do not have lore and name.And also can not clean up the lore and name items

**Comment by pop4959** [comment]
Invsee is perfectly fine for this purpose. Don't see the point in adding an extremely specific and complicated command to handle removing items from someone's inventory.

Also there is already another issue open for the /clear command supporting filtering by item type. This might be effectively what you're asking for here.

**Comment by x3mp** [comment]
Reopening.
Invsee does not do the job for command execution. I want to be able to clear a specific item with a specific item meta from a player their inventory.
This can not be done with any /take or /clear command
I have a renamed rotten_flesh that I want to be cleared but when I do /eclean or any clean/clear command it says 0 rotten_flesh removed from their inventory even though they have it in there.

I use color codes and lore with multiple lines for this item
