### ISSUE TITLE
EssentialsX Bug When player dies items are lost!

### ISSUE THREAD

**Issue by Xiantrius** [EssentialsX/Essentials#5920]
### Type of bug

Compatibility issue

### `/ess dump all` output

https://essentialsx.net/dump.html?id=d42044eb71284901a19ac4954f86b166

### Error log (if applicable)

Not Found for this problem

### Bug description

If the player dies there is still a chance that /gamerule keepinventory is false, the player:
1. The items do not drop.
2. Some of the items are lost.
3. No error message is displayed after the bug occurs.

### Steps to reproduce

not all players can reproduce. Special problem on other servers!

### Expected behaviour

EssentailsX bug Report:
When I die, it happens that I can't get the items despite gamerule keepinventory false and in luckperm EssentailsX.keepinv < which doesn't work, even without it the problem remains that the items stay in my inventory and the items that you last collected are also partially lost, as described above, as if they weren't recorded.

### Actual behaviour

more u can read here:
[Show Report](https://github.com/kettingpowered/Ketting-1-20-x/issues/336)

### Additional Information

This happens on the Hybrid Ketting Server v0.3.22 with mods.
One note: I can play the mods on a normal Forge server without any problems. It's not the mods' fault.

I hope that we can work together a bit here. Thank you for your understanding.

**Comment by LaxWasHere** [comment]
EssentialsX does not support modded servers.
