### ISSUE TITLE
Discord Channel Recognition Failure on Server Startup

### ISSUE THREAD

**Issue by D4vide106** [EssentialsX/Essentials#5923]
### Type of bug

Compatibility issue, Error in console, Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=97779e13056046658d5f4dda387a523c

### Error log (if applicable)

https://paste.gg/p/anonymous/c5962cb29a004cb79fb685e0d8209459

### Bug description

The server fails to recognize the specified Discord text channel (Thread) during startup, resulting in an error. The /link command also fails, despite the plugins and bot appearing active.

### Steps to reproduce

1. **Configure the Plugin**:  
   Set up the EssentialsX Discord Link and EssentialsX Discord plugins by entering the required data. In the configuration, specify a Discord text channel of type Thread where messages should be sent, and ensure all necessary permissions are correctly set.
2. **Start the Server**:  
   Start the Minecraft server. Observe that an error occurs, indicating that the text channel cannot be found. Enter the game and run the `/link` command, which will also produce an error. Despite this, check the plugin status with `/pl` and see that the plugins appear active, and the bot is online in the Discord server.

### Expected behaviour

The server should correctly recognize the specified Discord text channel, allow the /link command to function properly, and seamlessly connect the Minecraft server with the Discord channel without errors.

### Actual behaviour

In the configuration of the plugins EssentialsX Discord Link and EssentialsX Discord, I entered the required data. In the section where the messages should be sent, I specified a text channel of type Thread and set all the necessary permissions. However, when the server starts, it gives an error indicating that the text channel cannot be found. I added the pastebin, and when I enter the world, the /link command gives an error. However, when I run /pl, the plugins seem to be active, and the bot is also active in the Discord server.

### Additional Information

/Link:
![image](https://github.com/user-attachments/assets/1e3a86a2-2f50-4a45-8d4e-76ab68386f30)

Console:
![image](https://github.com/user-attachments/assets/c2e42ca5-ebc8-4eec-9e74-ef3d857cf071)

Plugin and Bot Active
![image](https://github.com/user-attachments/assets/3891fedd-1cea-4e92-a940-8ec8d027a097)
![image](https://github.com/user-attachments/assets/aa66b72a-0ec0-4608-8ab9-95eef48b7e0b)

**Comment by JRoy** [comment]
> Your bot cannot see or talk in any channel! Please make sure your bot has read and write permissions in all channels you wish to use.
