### ISSUE TITLE
Players unable to teleport

### ISSUE THREAD

**Issue by Koora7334** [EssentialsX/Essentials#5928]
### Type of bug

Error in console, Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=ac8d332de74047a5a8f1e44123ae625a

### Error log (if applicable)

https://paste.gg/p/anonymous/b243635c0b064406b1eec7a53c54f73e

### Bug description

When a player logs in, or under certain unknown circumstances, the player is unable to teleport. At those times, my console is flooded with this message: Essentials updated the underlying Player object for b97d86b4-8462-4f8e-a67c-39ae8b730fbb.

### Steps to reproduce

Appear sometimes when doing baltop, or just leaving then joining

### Expected behaviour

Player can teleport

### Actual behaviour

Player can't teleport

### Additional Information

The cache is updated every seconds/500ms, that makes the player unable to teleport.
Coming from loadUncachedUser -> "else if (!player.equals(user.getBase())" in ModernUserMap.java
The player seems to be updated in a loop, but the loop seems broken?

_No response_

**Comment by JRoy** [comment]
Likely your other plugins causing a conflict.

**Comment by Koora7334** [comment]
No, I have this issue since 2015, and still appears times to times. Even with minimal plugins this shit still appears.

**Comment by JRoy** [comment]
The code you're referencing in the ticket didn't exist in 2015, your plugins related to sharing playerdata between servers is likely what is causing issues.

**Comment by Koora7334** [comment]
> The code you're referencing in the ticket didn't exist in 2015, your plugins related to sharing playerdata between servers is likely what is causing issues.

PlayerSQL only sync users inventories, nothing more
And this bug is present since 2015, if this code was not here since, it's coming from an other part of EssX

**Comment by dayofpay** [comment]
i have the same issue

**Comment by Koora7334** [comment]
@JRoy I'm not the only one having this issue.
