### ISSUE TITLE
Fly is activated when logging in 

### ISSUE THREAD

**Issue by EtienneBinginot** [EssentialsX/Essentials#5931]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=b33652cc6d384f44a636b900bb1cd288

### Bug description

When disconnecting while sneaking on a stair with a block above us, at the reconnection the fly will be activated by default if the player has the right to fly

### Steps to reproduce

1. Place a stair on the ground
2. Leave a block of air above the stair and place a block above the air
3. Sneak and go between the stair and the block
4. Disconnect
5. Reconnect

### Expected behaviour

The fly should not be activated if the fly was not activated before disconnecting

### Actual behaviour

The fly is activated event if the fly was not activated before disconnecting

### Additional Information

Example of setup to activate the bug :  ![2024-09-08_12 06 33](https://github.com/user-attachments/assets/4cc14bd3-be63-4b97-9a7b-c77b2605c31f)

**Comment by chance-06** [comment]
I was having issues where I was seemingly lagging out when cutting down trees (an entity would drop - like sticks, but I wouldn't be able to pick it up and it would just continually fly back up and then drop again. I found out it gets fixed if I log out and log back in) and every time I logged back in I also was set to fly. I was on grass, though, not stairs, and there was nothing above me.

**Comment by Evidentsinger14** [comment]
Unable to reproduce this behavior. 
typically your flight is only enabled on login when you have `essentials.fly.safelogin` - which will enable your flight if you're not standing on a solid block just to prevent you from falling and dying.
