### ISSUE TITLE
EssentialsXMPP spelled wrong

### ISSUE THREAD

**Issue by coderlaari** [EssentialsX/Essentials#5947]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

Nothing here :)

### Bug description

EssentialsXMPP plugin is spelled wrong in Essentials messages_fi.properties. Path: Essentials (folder) / src / main / resources / messages_fi.properties, line 998, character 79 to 94

### Steps to reproduce

Go to Essentials (folder) / src / main / resources / messages_fi.properties, line 998, character 79 to 94

### Expected behaviour

EssentialsXMPP

### Actual behaviour

EssentialsXXMPP 

### Additional Information

Nothing here again :)

**Comment by JRoy** [comment]
For any other translations please use the Essentials [Crowdin](https://crowdin.com/project/essentialsx-official) as changes made through Github will be overwritten by copy there.

Thank you for pointing it out though.
