### ISSUE TITLE
/give sand command fails

### ISSUE THREAD

**Issue by GitNuck** [EssentialsX/Essentials#5948]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=628f437c36364eb5a2250c2d58ec2b6b

### Error log (if applicable)

https://paste.gg/p/anonymous/5a5b60270284421d9fd4d109c3f17b96

### Bug description

Use the command to give sand and it fails, throwing errors.

### Steps to reproduce

/give <playername> sand

### Expected behaviour

Should get some sand :)

### Actual behaviour

You don't get sand, you get errors in the console.

**Comment by JRoy** [comment]
This could be a number of things:
* Try turning off your server and renaming `custom_items.yml` to `custom_items.yml.d` in the `plugins/Essentials` directory. 
  * If the command works after this you have an alias for sand in there causing a problem. Seek help on discord or just delete the file if you don't use the custom items feature.
* Try turning off your server and deleting the `items.json` file in the `plugins/Essentials` directory.

**Comment by GitNuck** [comment]
Thank-you for the help, I had zero custom items added but renamed the file anyway.  Also deleted the items.json file as well.  Works great now!  Thanks again :)
