### ISSUE TITLE
Request: essentials.balancetop.exclude

### ISSUE THREAD

**Issue by Volander** [EssentialsX/Essentials#595]
essentials.balancetop.exclude

People with this permission node would not show up in the /baltop list
- Volander

**Comment by Brend-Smits** [comment]
I would like this as well! Would finally clean up my /baltop list!

**Comment by khobbits** [comment]
Just an FYI: Checking the permissions for offline users isn't well supported across permissions systems.
This is why it wasn't done in the past.

**Comment by mdcfe** [comment]
This can likely be done now, as LuckPerms is now our main supported permissions system and as far as I know, it supports offline permissions checks.

**Comment by khobbits** [comment]
@md678685 Be aware that that method runs asynchronously, and could potentially do a lot of permissions lookups.  I moved it to a different thread to prevent server lockups, but not all permissions managers are threadsafe.  At the time, the built in bukkit one, wasn't.
