### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by Flecksing** [EssentialsX/Essentials#5953]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

essentialsx.net/dump.html?id=b32d12464dd24d538a246cdbfa5ecde4

### Error log (if applicable)

n/a

### Bug description

![image](https://github.com/user-attachments/assets/a5a7ddcb-ec12-40b4-a548-05c103d99bd9)

### Steps to reproduce

Shown above

### Expected behaviour

Shown above

### Actual behaviour

Shown above

**Comment by AfkF24** [comment]
Same as #5940
