### ISSUE TITLE
ChatEvent doesn't have a getHandlerList

### ISSUE THREAD

**Issue by Lory9098** [EssentialsX/Essentials#5955]
### Type of bug

Error in console, Other unexpected behaviour

### `/ess dump all` output

[16:18:23] [Server thread/INFO]: Creazione di un backup server...

### Bug description

    @EventHandler(ignoreCancelled = true, priority = EventPriority.LOWEST)
    public void onChat(ChatEvent e) {

 org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event net.essentialsx.api.v2.events.chat.ChatEvent. Static getHandlerList method required!

### Steps to reproduce

just create a plugin that listen to ChatEvent

### Expected behaviour

.

### Actual behaviour

throws error

**Comment by JRoy** [comment]
ChatEvent is an abstract event, you should be listening to LocalChatSpyEvent, GlobalChatEvent, or LocalChatEvent.
