### ISSUE TITLE
Weird error message

### ISSUE THREAD

**Issue by TrixterPro** [EssentialsX/Essentials#5964]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=8945ee4a12c34eaa832938298f8db857

### Bug description

When i click on the repair sign with bare hands, it shows this type of error, I wasn't expecting the \<dark_red> text
![image_2024-11-10_173645768](https://github.com/user-attachments/assets/9a82836e-abc3-461a-8588-6cd6b4c381be)

### Steps to reproduce

Right click on the repair sign without anything in main hand.

Sign:

[Repair]
hand
500

### Expected behaviour

`#FC5454`Error: `#A80000`This item cannot be repaired.

### Actual behaviour

`#FC5454`Error: `#A80000`\<dark_red>This item cannot be repaired.

### Additional Information

I tried changing the language file but still couldn't fix it, I managed to remove the Error: Error but not the \

@Evidentsinger14

**Comment by Evidentsinger14** [comment]
Confirmed issue
