### ISSUE TITLE
-/tprandom is not working on latest dev version: 2.21.0-dev+128-0b49421

### ISSUE THREAD

**Issue by ILikeOrangeJuice** [EssentialsX/Essentials#5966]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=faaa197fdcab4a2d8a33ea7c7c9e0a36

### Error log (if applicable)

No errors appear to happen

### Bug description

Using the /tprandom command nothing does happen anymore. I tried it on multiple servers on our network with the latest dev version 2.21.0-dev+128-0b49421. No error, no outputs, just literally nothing is happening when using the command.

### Steps to reproduce

Update to  2.21.0-dev+128-0b49421
Setup /tprandom in config/own file
Use it

### Expected behaviour

To teleport me randomly in a specific setup defined in the files.

### Actual behaviour

Nothing, literally nothing happens at all.

### Additional Information

-

**Comment by Evidentsinger14** [comment]
make sure you're setting a maxrange, minrange, and center. i did experience similar behavior before setting those. no message, and no teleport. not a "bug" with it being broken, but definitely a problem as it lacks feedback for whatever reason.

**Comment by ILikeOrangeJuice** [comment]
Hey Charles,

it worked fine with the same settings for years, if I put in the backup I had taken, which is this version: 
it does work without issues, so no idea, I also see nothing related to tpr/tprandom being changed in the jenkins logs of said versions between unfortunately.

I even regenerated the tpr.yml and reset my desired values, such as the correct world name, but sadly the same thing happens.

**Comment by chance-06** [comment]
I'm having the same issue. Worked previously, after I updated no longer works. Lags the server out as though it is, but it doesn't teleport me. Same with other players. I set a center because I saw that suggested elsewhere a while ago and it still didn't work.

**Comment by danieliustt** [comment]
Same, please fix.

**Comment by Hurming** [comment]
same, please fix. :)

**Comment by Evidentsinger14** [comment]
if anybody can actually provide reliable reproduction steps, it would help narrow down any issue. As I stated, I was unable to experience the issue. Just saying “please fix” is not very helpful.

**Comment by chance-06** [comment]
The reproduction steps for me are literally just - try to use /tpr or /tprandom and then it happens. It doesn't matter where I am or anything so I'm not sure exactly how to help there. The same thing happens if others try as well.
However, you can find a video of me trying to do it attached and hopefully that helps. You can see the server lag as though it has teleported me, but you can see that I did not move. 

https://github.com/user-attachments/assets/5e10405a-8b1a-4410-9356-1437a45c51ba
You can also see that I have the center set for the random teleport in the attached screenshot of my tpr.yml file:
![image](https://github.com/user-attachments/assets/e40828e3-2004-4e2a-943b-329c537e7c31)

**Comment by 00BBL** [comment]
same, please fix. :) - i actually just thought it was me, but now that I realize I did infact go to the latest dev release then it stopped working , it makes sense now

**Comment by AAlchemy** [comment]
Running Paper 1.21.1-131.
I am also experiencing this. no other changes other than updating from dev+121 to dev+129.
I'm not sure why this isn't reproducible for the dev. maybe it's a combination of other plugins. 
I can't post my plugin list here. might risk the server.

**Comment by Evidentsinger14** [comment]
Anyone having the issue, please join the EssentialsX support guild, and ping me `evident._.`. I want to get dumps containing plugins lists and configs to review.

**Comment by chance-06** [comment]
> EssentialsX support guild

Sorry I'm not sure what an EssentialsX support guild is. Are you referencing the MOSS Discord?

**Comment by mbax** [comment]
Yes.

**Comment by pop4959** [comment]
The team is currently unable to reproduce this issue on a clean server with just Essentials installed. So far the information provided here is too circumstantial for anything to be done about this. Can someone confirm that this still occurs for them on the latest dev build of Essentials with no other plugins installed? If so, please follow-up with Evident promptly with more details so that we can confirm whether this issue is valid.

**Comment by Hurming** [comment]
this is a debug
![image](https://github.com/user-attachments/assets/d8140a1d-0bb4-4385-979a-ab662e32e036)

**Comment by Hurming** [comment]
No plugins nothing else and this is the debug

![image](https://github.com/user-attachments/assets/f0928744-026b-485d-8961-a206aa5d923a)
![image](https://github.com/user-attachments/assets/ce99e740-7163-4f1b-a452-26d9608dac6c)

**Comment by chance-06** [comment]
> The team is currently unable to reproduce this issue on a clean server with just Essentials installed. So far the information provided here is too circumstantial for anything to be done about this. Can someone confirm that this still occurs for them on the latest dev build of Essentials with no other plugins installed? If so, please follow-up with Evident promptly with more details so that we can confirm whether this issue is valid.

I just deleted all of my plugins and tried again and it's producing the same thing that it previously did - the console clocks that the server is lagging due to the TPR command, but it still does not teleport me anywhere.

**Comment by JasonHorkles** [comment]
It could be helpful if someone wants to send a zipped version of their entire server so we can test different things on our end

**Comment by chance-06** [comment]
Can I send it on Discord so that it's not a file that's able to be publicly viewed?

**Comment by JasonHorkles** [comment]
Sure, DM it to Chester#0634 (modmail bot)

**Comment by Evidentsinger14** [comment]
This appears to be related to 1.21.1 specifically, on builds targeting newer versions. was able to reproduce, but updating to the latest supported minecraft version (1.21.3/4) fixed this.
