### ISSUE TITLE
add /itemown

### ISSUE THREAD

**Issue by perlsol** [EssentialsX/Essentials#5968]
### Feature description

to add the command /itemown which will add [username] to the bottom of the item

### How the feature is useful

Marking an item as [username] at the bottom, so once set its cannot be removed or overwritten will allow people to mark ownership and will also allow the use of restone shops that use a ticket system to purchase, users would not be able to make fake tickets by just adding lore to paper

**Comment by pop4959** [comment]
This can already be done with the /itemlore command and adding a more specific command than this is out of scope for Essentials.
