### ISSUE TITLE
Cannot use /plugins command from within game

### ISSUE THREAD

**Issue by FabTheZen** [EssentialsX/Essentials#597]
Nobody can use the "/plugins" command, even with the "bukkit.command.plugins" explicitly assigned (not even with " \* " or opped by "/op <nick>"). From console, it can be used with no problems though.
Using spigot-essentials, as expected, everyone can use it by default.

**Comment by ClankyPoo** [comment]
What permission plugin are you using?

**Comment by FabTheZen** [comment]
Oh sorry, my bad, i forgot to check back. It was a conflict between GroupManager and PermissionsEx. I'll close it since I was using GroupManager on top of PEX which is not something anyone should do.
