### ISSUE TITLE
Issue with certain 1.21.3 ess commands in essentials

### ISSUE THREAD

**Issue by PenguinTC** [EssentialsX/Essentials#5970]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=356bf1bc17f54aafb96fe89449f6c4c4

### Error log (if applicable)

https://mcpaste.io/b7be96d40d29c9f8

### Bug description

#5965 same issue as this but i have isolated it to Protocollib possibly
i just thought i'd make you guys aware

### Steps to reproduce

[1] Run the server
[2] Use /warp [nameofwarp]
[3] fall through the world in my case ( but not die )

### Expected behaviour

Just teleport and use commands like normal

### Actual behaviour

Glitchy non-functional behaviour

**Comment by Evidentsinger14** [comment]
closing due to a non-essx issue
