### ISSUE TITLE
[BUG] Clear Inventory command has added space

### ISSUE THREAD

**Issue by burnplayz** [EssentialsX/Essentials#5973]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=39161c699e244dd4b43b66598b47cf8f

### Bug description

When I click on run_command using the clear inventory command, it adds spaces.
![image](https://github.com/user-attachments/assets/02e9818f-ceae-452f-99d7-9d4998779b11)
![image](https://github.com/user-attachments/assets/0720e0dd-8a6b-424c-8837-91a568a1811c)

Raw Paste:

[01:27:20 INFO]: BurnPlayz issued server command: /clear
[01:27:21 INFO]: BurnPlayz issued server command: /clear 
[01:27:22 INFO]: BurnPlayz issued server command: /ci
[01:27:24 INFO]: BurnPlayz issued server command: /ci 
[01:27:25 INFO]: BurnPlayz issued server command: /clearinvent
[01:27:26 INFO]: BurnPlayz issued server command: /clearinvent 
[01:27:27 INFO]: BurnPlayz issued server command: /clearinventory
[01:27:29 INFO]: BurnPlayz issued server command: /clearinventory 

### Steps to reproduce

1. Toggle clear inventory toggle on
2. Create a message that has a click message to confirm
3. Click it.

### Expected behaviour

When I click, it should run /ci

### Actual behaviour

When I click, it runs the command with extra spaces. I checked with the person who made the config, and they confirmed there's added spaces from ESSENTIALS.

**Comment by pop4959** [comment]
What are you using to perform this "run command" click action? Can you provide additional information such as the configuration you are using for this message and reproduction steps?

**Comment by burnplayz** [comment]
confirmClear=$<p:prefix>To <bold><p:primary-color>CONFIRM</p></bold> inventory clear <p:primary-color><click:run_command:"{0}">[➥✔ Confirm]</click></p>

Here it is, in Essentials messages (sorry for the long wait!).

**Comment by Evidentsinger14** [comment]
I've got no clue what you're doing with these messages, but that is not official MiniMessage format. 
This does not happen using the proper [click components from MiniMessage](https://docs.advntr.dev/minimessage/format.html#click), as intended by us.
