### ISSUE TITLE
Clickable commands

### ISSUE THREAD

**Issue by LappenXD2** [EssentialsX/Essentials#5977]
### Feature description

I want to click for example the TPA Command. No and yes should be clickable. 

### How the feature is useful

It is usefully to players because they can simple click in the chat to accept a teleport request instead of writing /tpaccept. The same for /tpdeny or other commands that are similar

**Comment by Evidentsinger14** [comment]
This is already possible with minimessage / adventure [click components](https://docs.advntr.dev/minimessage/format.html#click). modify your language file to add this behavior to your setup.
