### ISSUE TITLE
Minimessages format broken

### ISSUE THREAD

**Issue by pjindras** [EssentialsX/Essentials#5979]
### Type of bug

Compatibility issue

### `/ess dump all` output

cannot do plugin is disabled

### Error log (if applicable)

https://mclo.gs/8jGl3Ut

### Bug description

I used minimessages messages and it doesnt work properly.

[messages.txt](https://github.com/user-attachments/files/17961334/messages.txt)

see startup log: https://mclo.gs/8jGl3Ut

### Steps to reproduce

Try my messages, they are in correct minimessages format.

### Expected behaviour

IT should work.

### Actual behaviour

pluin cannot start.

**Comment by JRoy** [comment]
You either have modified the jar to edit the default `messages.properties` file or you have added a file called `messages.properties` to the `plugins/Essentials` folder which does not contain the message shown in the error. It is not recommended to edit the default bundle for this reason, try redownloading the jar or removing any file called just `messages.properties` from your server.
