### ISSUE TITLE
bed respawn not working and overide custom flags of worldguard

### ISSUE THREAD

**Issue by Khran** [EssentialsX/Essentials#598]
Hi,

The bed respawn don't work when player die after check this bed.

And essentials overide the flag respawn-location of worldguard custom flag.

No error in the console.

Can you help me ?

my config.yml of essentials here : http://pastebin.com/3gtvEMKL

Thx a lot.

**Comment by ClankyPoo** [comment]
install EssentialsSpawn and change
respawn-listener-priority: lowest to
respawn-listener-priority: high

**Comment by Khran** [comment]
hi!

EssentialsSpawn is already installed and the priority of "respawn-listener-priority:" not change anything.

Thx for your help.

**Comment by ClankyPoo** [comment]
strange

**Comment by Khran** [comment]
any idéas ?

**Comment by ClankyPoo** [comment]
What plugins are installed?

**Comment by Khran** [comment]
i try essentials alone on a local server, bed respawn not work to. The bug was appear when i switch to spigot 1.9
For you all work fine ?

**Comment by ClankyPoo** [comment]
change 
respawn-at-home: false
to true

**Comment by Khran** [comment]
ha yes that work on 1.10, in 1.9.4 he didn't work for me lol. Problem solved Thanks
