### ISSUE TITLE
Skull Meta is not applied for /give Command if the Skull-Owner is offline

### ISSUE THREAD

**Issue by 0x484** [EssentialsX/Essentials#5980]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=c66d6d2b35c94d65a4b9f625582c1cd4

### Bug description

I think the Bug only happens on 1.21 but I haven't tested the other versions, I just know that it worked before updating to 1.21
Skull Meta is not applied for the give Command if the Player is offline/was not on the server.
/essentials:give PLAYER player_head 1 owner:OFFLINE-PLAYER

### Steps to reproduce

1. /essentials:give PLAYER player_head 1 owner:OFFLINE-PLAYER

### Expected behaviour

It should always apply the correct Skull Skin

### Actual behaviour

It does not apply the Skull Skin and instead gives a default Head.

**Comment by JRoy** [comment]
Bukkit issue, not much we can do.

**Comment by 0x484** [comment]
But it works when I use /skull while Holding a head.
it only doesn't work with the give command
