### ISSUE TITLE
/baltop problem latest dev build

### ISSUE THREAD

**Issue by danieliustt** [EssentialsX/Essentials#5983]
### Type of bug

Compatibility issue

### `/ess dump all` output

Latest EssentialsX dev build

### Error log (if applicable)

No errors

### Bug description

On a 1.20.4 server, the /baltop command doesn't show any player top balances; it only displays the total sum of all players' balances.

### Steps to reproduce

Just write command/baltop, /balancetop

### Expected behaviour

.

### Actual behaviour

Do not see all players balance top

**Comment by JRoy** [comment]
Cannot reproduce, please share an /ess dump.
