### ISSUE TITLE
Add "/fly off" command instead of/in addition to toggling with just "/fly"

### ISSUE THREAD

**Issue by stapleshotz** [EssentialsX/Essentials#599]
I have a few other plugins that I'm trying to use in conjunction with essentialsx /fly command to make a sort of fast swimming ability by enabling /fly for a player when they enter the water, but I need a way to disable it when they leave. I can't do /fly again because it would toggle it on for them any time they log in while not in water too, which I don't want. 
Therefore, I need a command that only turns flying off. 
I've only offered my example of how this would be useful, but I think that adding this would help to make essentialsx more versitile in a very simple way. 
Thanks for considering it!

**Comment by ljacqu** [comment]
Looking at the [code](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/commands/EssentialsToggleCommand.java) it seems like you can do `fly %p off` and `fly %p on`, no?

**Comment by stapleshotz** [comment]
Oh! Oh my god I feel dumb. Thank you! My friend and I were working on this problem and he said he had tried that. APPARENTLY NOT.

**Comment by stapleshotz** [comment]
Damn, how do I close this ticket? It's embarrassing.

**Comment by ljacqu** [comment]
:smile: There should be a "Close" button at the bottom of the page, next to the "Comment" one if I'm not mistaken. I'm sure someone else will take care of it otherwise :)
