### ISSUE TITLE
Creating a kit with custom item from another plugin breaks the kit

### ISSUE THREAD

**Issue by TerdyTheTerd** [EssentialsX/Essentials#5997]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=82662e58055442e698a83c013a38bef6

### Bug description

One of our plugins adds in a custom item, which uses suspicious stew at the base item and also applies mending to the item. Essentials allows me to create a kit with this item, but when I try to give the kit to a player it gives me an error that the itemstack does not support the mending enchantment:
![image](https://github.com/user-attachments/assets/57b2f708-02da-41b7-8807-2fc59c24802f)

If Essentials allows me to create the kit in the first place, then it should also support giving the kit, otherwise it should give an error when trying to create the kit.

### Steps to reproduce

Give yourself an item with an illegal enchantment.
Create a kit with the item
Try to give the kit to a player

### Expected behaviour

Expected behavior is either:
 - The kit works, ignoring the "illegal" enchantment. If an admin creates a kit with an item with an illegal enchantment, its for a good reason
 - The kit creation fails, letting the player know that an item in their inventory is not supported

### Actual behaviour

The kit is created but then cannot be given out.

**Comment by LaxWasHere** [comment]
Enable unsafe-enchants in the config.
