### ISSUE TITLE
[11:05:12 ERROR]: [Essentials] You are running an unsupported server version! 

### ISSUE THREAD

**Issue by juanmolidsadsadsadadadsad** [EssentialsX/Essentials#5999]
### Type of bug

Error in console

### `/ess dump all` output

n

### Error log (if applicable)

d

### Bug description

en github dice que essentials es compatible con hasta la 1.21.4 y mi servidor es 1.21.0

### Steps to reproduce

d

### Expected behaviour

d

### Actual behaviour

si marca que esta en verde en /plugins pero nose si traiga probelmas por ese aviso

### Additional Information

cual seria la solucion

**Comment by Evidentsinger14** [comment]
base 1.21 is not supported anymore, you should always be running the latest patch versions when there is a stable build for your server software. 
update your server to paper 1.21.3 and ignore the message, or run the experimental version of 1.21.4. 

for the future, putting "n" or "d" to just bypass the required steps will lead to a closed issue without triage.
