### ISSUE TITLE
[Request] Ban items

### ISSUE THREAD

**Issue by techied** [EssentialsX/Essentials#600]
Hey, just an idea, but could you add in an item banner?
I really love this plugin!

**Comment by TheExceed** [comment]
@techied Is this not already available through essentials protect?

**Comment by mdcfe** [comment]
If there's still any interest in this, is there anything you'd want that `item-spawn-blacklist` and EssentialsX Protect can't do?

**Comment by pop4959** [comment]
Closing due to not enough info. Feel free to create another issue if you want something that Essentials doesn't currently already do. But I feel like this is something that EssentialsXProtect already does.
