### ISSUE TITLE
Invisibility II Affect

### ISSUE THREAD

**Issue by MeAngel** [EssentialsX/Essentials#601]
When players enter our Survival server via BungeePortal or by the command " /server Survival"  the Invisibility II effect is applied to them. In console they show as [Hidden].
The only way to remove it is to drink milk.
It doesn't happen to all players either. I haven't determined what pattern there is, what activated this for one player while another is not affected, etc.

We use SuperVanish, but I disabled that plugin and nothing changed.

I disabled Essentials, teleported back to the server and the effect was gone. Enabled it again and the effect was back.

Is there any specific information you need from me?

**Comment by SupaHam** [comment]
Hey,

This simply means they're being vanished when they join the game. However, this would only happen unnoticed if you made these players op or gave them all permissions.

If this is happening to those players, this means they are able to vanish when they join. if this is not what you want to happen you need to set your permissions accordingly.

You can find a list of permissions for the /vanish command [here](http://wiki.mc-ess.net/wiki/Command_Reference) (Make sure to select `Dev 2.14.x` release).

However, if these players are given permission to vanish intentionally, then you need to negate the `essentials.silentjoin.vanish` permission from them.
