### ISSUE TITLE
[Server] INFO CONSOLE issued server command: /list 

### ISSUE THREAD

**Issue by Ar1sC** [EssentialsX/Essentials#602]
Hello, i am getting this "INFO" in console every 35 seconds.
I'm using Spigot 1.9.2 and the latest version of essentials.

05.05 00:45:15 [Server] INFO CONSOLE issued server command: /list 
05.05 00:44:40 [Server] INFO CONSOLE issued server command: /list 
05.05 00:44:05 [Server] INFO CONSOLE issued server command: /list 
05.05 00:43:30 [Server] INFO CONSOLE issued server command: /list 
05.05 00:42:55 [Server] INFO CONSOLE issued server command: /list 
05.05 00:42:20 [Server] INFO CONSOLE issued server command: /list 
05.05 00:41:45 [Server] INFO CONSOLE issued server command: /list 
05.05 00:41:10 [Server] INFO CONSOLE issued server command: /list 
05.05 00:40:35 [Server] INFO CONSOLE issued server command: /list 
05.05 00:40:00 [Server] INFO CONSOLE issued server command: /list 
05.05 00:39:25 [Server] INFO CONSOLE issued server command: /list 
05.05 00:38:50 [Server] INFO CONSOLE issued server command: /list 
05.05 00:38:26 [Server] INFO World saved.
05.05 00:38:25 [Server] INFO Saving...
05.05 00:38:25 [Server] INFO Saving is already turned on.
05.05 00:38:25 [Multicraft] Auto-saving world...
05.05 00:38:15 [Server] INFO CONSOLE issued server command: /list 
05.05 00:37:40 [Server] INFO CONSOLE issued server command: /list 
05.05 00:37:05 [Server] INFO CONSOLE issued server command: /list 
05.05 00:36:30 [Server] INFO CONSOLE issued server command: /list 
05.05 00:35:55 [Server] INFO CONSOLE issued server command: /list 
05.05 00:35:20 [Server] INFO CONSOLE issued server command: /list 
05.05 00:34:45 [Server] INFO CONSOLE issued server command: /list 
05.05 00:34:10 [Server] INFO CONSOLE issued server command: /list 
05.05 00:33:35 [Server] INFO CONSOLE issued server command: /list 
05.05 00:33:00 [Server] INFO CONSOLE issued server command: /list 
05.05 00:32:25 [Server] INFO CONSOLE issued server command: /list 
05.05 00:31:50 [Server] INFO CONSOLE issued server command: /list 
05.05 00:31:15 [Server] INFO CONSOLE issued server command: /list 
05.05 00:30:40 [Server] INFO CONSOLE issued server command: /list 
05.05 00:30:05 [Server] INFO CONSOLE issued server command: /list 
05.05 00:29:30 [Server] INFO CONSOLE issued server command: /list 
05.05 00:28:55 [Server] INFO CONSOLE issued server command: /list 
05.05 00:28:20 [Server] INFO World saved.
05.05 00:28:20 [Server] INFO Saving...
05.05 00:28:20 [Server] INFO Saving is already turned on.
05.05 00:28:20 [Multicraft] Auto-saving world...
05.05 00:28:20 [Server] INFO CONSOLE issued server command: /list 
05.05 00:27:45 [Server] INFO CONSOLE issued server command: /list 
05.05 00:27:10 [Server] INFO CONSOLE issued server command: /list 
05.05 00:26:35 [Server] INFO CONSOLE issued server command: /list 
05.05 00:26:00 [Server] INFO CONSOLE issued server command: /list 
05.05 00:25:25 [Server] INFO CONSOLE issued server command: /list 
05.05 00:24:50 [Server] INFO CONSOLE issued server command: /list 
05.05 00:24:15 [Server] INFO CONSOLE issued server command: /list 
05.05 00:23:40 [Server] INFO CONSOLE issued server command: /list 
05.05 00:23:05 [Server] INFO CONSOLE issued server command: /list 
05.05 00:22:30 [Server] INFO CONSOLE issued server command: /list 
05.05 00:21:55 [Server] INFO CONSOLE issued server command: /list 
05.05 00:21:20 [Server] INFO CONSOLE issued server command: /list 
05.05 00:20:45 [Server] INFO CONSOLE issued server command: /list 
05.05 00:20:10 [Server] INFO CONSOLE issued server command: /list 
05.05 00:19:35 [Server] INFO CONSOLE issued server command: /list 
05.05 00:19:00 [Server] INFO CONSOLE issued server command: /list 
05.05 00:18:25 [Server] INFO CONSOLE issued server command: /list 
05.05 00:18:15 [Server] INFO World saved.
05.05 00:18:15 [Server] INFO Saving...
05.05 00:18:15 [Server] INFO Saving is already turned on.
05.05 00:18:15 [Multicraft] Auto-saving world...
05.05 00:17:50 [Server] INFO CONSOLE issued server command: /list 
05.05 00:17:15 [Server] INFO CONSOLE issued server command: /list 
05.05 00:16:40 [Server] INFO CONSOLE issued server command: /list 
05.05 00:16:05 [Server] INFO CONSOLE issued server command: /list 
05.05 00:15:30 [Server] INFO CONSOLE issued server command: /list 
05.05 00:14:55 [Server] INFO CONSOLE issued server command: /list 
05.05 00:14:20 [Server] INFO CONSOLE issued server command: /list 
05.05 00:13:45 [Server] INFO CONSOLE issued server command: /list 
05.05 00:13:10 [Server] INFO CONSOLE issued server command: /list 
05.05 00:12:35 [Server] INFO CONSOLE issued server command: /list 
05.05 00:12:00 [Server] INFO CONSOLE issued server command: /list 
05.05 00:11:25 [Server] INFO CONSOLE issued server command: /list 
05.05 00:10:50 [Server] INFO CONSOLE issued server command: /list 
05.05 00:10:15 [Server] INFO CONSOLE issued server command: /list 
05.05 00:09:40 [Server] INFO CONSOLE issued server command: /list 
05.05 00:09:05 [Server] INFO CONSOLE issued server command: /list 
05.05 00:08:30 [Server] INFO CONSOLE issued server command: /list 
05.05 00:08:10 [Server] INFO World saved.
05.05 00:08:10 [Server] INFO Saving...
05.05 00:08:10 [Server] INFO Saving is already turned on.
05.05 00:08:10 [Multicraft] Auto-saving world...
05.05 00:07:55 [Server] INFO CONSOLE issued server command: /list 
05.05 00:07:20 [Server] INFO CONSOLE issued server command: /list 
05.05 00:06:45 [Server] INFO CONSOLE issued server command: /list 
05.05 00:06:10 [Server] INFO CONSOLE issued server command: /list 
05.05 00:05:35 [Server] INFO CONSOLE issued server command: /list 
05.05 00:05:00 [Server] INFO CONSOLE issued server command: /list 
05.05 00:04:25 [Server] INFO CONSOLE issued server command: /list 
05.05 00:03:50 [Server] INFO CONSOLE issued server command: /list 
05.05 00:03:15 [Server] INFO CONSOLE issued server command: /list 
05.05 00:02:40 [Server] INFO CONSOLE issued server command: /list 
05.05 00:02:05 [Server] INFO CONSOLE issued server command: /list 
05.05 00:01:30 [Server] INFO CONSOLE issued server command: /list 
05.05 00:00:55 [Server] INFO CONSOLE issued server command: /list 
05.05 00:00:20 [Server] INFO CONSOLE issued server command: /list 
04.05 23:59:45 [Server] INFO CONSOLE issued server command: /list 
04.05 23:59:10 [Server] INFO CONSOLE issued server command: /list 
04.05 23:58:35 [Server] INFO CONSOLE issued server command: /list 
04.05 23:58:05 [Server] INFO World saved.
04.05 23:58:05 [Server] INFO Saving...
04.05 23:58:05 [Server] INFO Saving is already turned on.
04.05 23:58:05 [Multicraft] Auto-saving world...
04.05 23:58:00 [Server] INFO CONSOLE issued server command: /list 
04.05 23:57:25 [Server] INFO CONSOLE issued server command: /list 
04.05 23:56:50 [Server] INFO CONSOLE issued server command: /list 
04.05 23:56:15 [Server] INFO CONSOLE issued server command: /list 
04.05 23:55:40 [Server] INFO CONSOLE issued server command: /list 
04.05 23:55:05 [Server] INFO CONSOLE issued server command: /list 
04.05 23:54:30 [Server] INFO CONSOLE issued server command: /list 
04.05 23:53:55 [Server] INFO CONSOLE issued server command: /list 
04.05 23:53:20 [Server] INFO CONSOLE issued server command: /list 
04.05 23:52:45 [Server] INFO CONSOLE issued server command: /list 
04.05 23:52:10 [Server] INFO CONSOLE issued server command: /list 
04.05 23:51:35 [Server] INFO CONSOLE issued server command: /list 
04.05 23:51:01 [Server] INFO CONSOLE issued server command: /list 
04.05 23:50:26 [Server] INFO CONSOLE issued server command: /list 
04.05 23:49:51 [Server] INFO CONSOLE issued server command: /list 
04.05 23:49:16 [Server] INFO CONSOLE issued server command: /list 
04.05 23:48:41 [Server] INFO CONSOLE issued server command: /list 
04.05 23:48:06 [Server] INFO CONSOLE issued server command: /list 
04.05 23:48:00 [Server] INFO World saved.
04.05 23:48:00 [Server] INFO Saving...
04.05 23:48:00 [Server] INFO Saving is already turned on.
04.05 23:48:00 [Multicraft] Auto-saving world...
04.05 23:47:31 [Server] INFO CONSOLE issued server command: /list 
04.05 23:46:56 [Server] INFO CONSOLE issued server command: /list

**Comment by ClankyPoo** [comment]
This is probably caused by Multicraft

**Comment by Ar1sC** [comment]
Can I do anything about that ?

**Comment by ClankyPoo** [comment]
contact Multicraft about it

**Comment by TheExceed** [comment]
@Ar1sC You cannot do anything about that. Multicraft using this to determine whether your server is "responding" or not lagging. It runs a command if it does not receive a response is x seconds it restarts the server. The command can be changed however. Depending on how you are hosting it, via host or you installed multicraft, it can be changed in the config, depending on how you use it, you will either be able to do it yourself of via contacting your host support.

**Comment by JupiterSnarl** [comment]
This is NOT Multicraft. We've been running Multcraft for months and now the second I installed EssentialsX tonight this started happening. It's definitely EssentialsX, or something related.

**Comment by mdcfe** [comment]
@Kingdingbat The message appears when `/list` is run from the console. If you're 100% certain that EssentialsX has become sentient and is running commands at will, feel free to open a new issue. Otherwise, Multicraft is running the command.

**Comment by mishyy** [comment]
More likely than not, as @TheExceed mentioned it is Multicraft, the only reason it has started now is probably due to the command not existing on the server prior to installing Essentials, thus the issue is not seen.

**Comment by JupiterSnarl** [comment]
Let me clarify... after thinking about it for a while - Perhaps it was always running, but it was not appearing in the console until EssentialsX was installed.

**Comment by LaxWasHere** [comment]
yes, multicrap has been known to do that for years.

**Comment by kodalee** [comment]
You have to go into your settings on multicraft and set your Crash Check Interval to 0, as it uses /list to make sure the server is responding.

**Comment by kodalee** [comment]
I am late but I wanted to write this.

**Comment by MrThiemann** [comment]
alternatively you can also edit the "commands.yaml".
Underneath the "icanhasbukkit" value, insert the following:
```
list:
- []
```

<img width="547" alt="Bildschirmfoto 2022-08-28 um 06 09 06" src="https://user-images.githubusercontent.com/54147030/187056985-d9f2e4be-0206-40a3-9b63-22992555829c.png">

**Comment by osfanbuff63** [comment]
> alternatively you can also edit the "commands.yaml".
> Underneath the "icanhasbukkit" value, insert the following:
> ```
> list:
> - []
> ```
> 
> <img width="547" alt="Bildschirmfoto 2022-08-28 um 06 09 06" src="https://user-images.githubusercontent.com/54147030/187056985-d9f2e4be-0206-40a3-9b63-22992555829c.png">
> 
> 

However, you can't use /list manually from the server with that workaround. Although, /list isn't too useful of a command xD (when you have the tab list)

**Comment by kodalee** [comment]
> > alternatively you can also edit the "commands.yaml".
> > Underneath the "icanhasbukkit" value, insert the following:
> > ```
> > list:
> > - []
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="Bildschirmfoto 2022-08-28 um 06 09 06" width="547" src="https://user-images.githubusercontent.com/54147030/187056985-d9f2e4be-0206-40a3-9b63-22992555829c.png">
> 
> However, you can't use /list manually from the server with that workaround. Although, /list isn't too useful of a command xD (when you have the tab list)

Like @osfanbuff63 said, this disables the usage of the /list command. This isn't the best thing to do to prevent the spam in the console. Also I'm pretty sure the console will still spam the "CONSOLE issued server command: /list". I'm confused on why Essentials logs the server's console executing a command like /list

This is bad design from EssentialsX and Multicraft.

**Changing your Crash Check interval to 0 effectively stops Multicraft from executing this command a ton like this.**

Multicraft could just make some sort of heartbeat plugin that gets installed when the server is created. In this way, when the server is running, it can relay 5 bytes of heartbeat data like HBEAT to the Multicraft daemon to indicate its presence and if there is some sort of skipped beat, there can be an alert like "Server had a late heartbeat by #ms". Spamming /list is kinda stupid IMO

Essentials could just allow you to turn off that notification for certain commands. 🤷
