### ISSUE TITLE
Enhance /give

### ISSUE THREAD

**Issue by EvilOlaf** [EssentialsX/Essentials#603]
At the moment when a player should receive an item using the `give` command and there is no room in the inventory left, the item is lost.
Therefor I suggest to add an option to drop the item/s on the ground instead of dismissing  them.

Thanks for reading.

**Comment by TheExceed** [comment]
I agree, and on top of this, a give all command that gives items to all online players. I don't recall reading anything about it.

**Comment by npateras** [comment]
Yep this is needed, it must be added as soon as possible, also the option to change the item names when the msg that you receive an item appears.

**Comment by SupaHam** [comment]
There's a config option for this called [`drop-items-if-full`](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/config.yml#L103).
