### ISSUE TITLE
/me

### ISSUE THREAD

**Issue by TheExceed** [EssentialsX/Essentials#604]
For some reason /me does not work?
Not too sure why. I did not read anything about it being removed.
Using version b342

**Comment by techied** [comment]
/me is built into the vanilla minecraft server jar, not essentials.
if you use pex, that might be interfering with your ability to run the command.

**Comment by TheExceed** [comment]
@techied 
me  essentials.me   Allow access to the /me command.

**Comment by TheExceed** [comment]
Any help?
