### ISSUE TITLE
Signs not woking

### ISSUE THREAD

**Issue by Qballl** [EssentialsX/Essentials#606]
Hello I switched to this from essentials mainly because the createkit command makes my like so much easier as a manager of a minecraft server. But recently the only informed me that the old essentials buy/sell signs werent working. Can you tell me what could be the problem
There is no error log the signs just dont work.

**Comment by Cldfire** [comment]
Do you have them enabled in your config?

**Comment by Qballl** [comment]
There appears to be nothing about signs in the config

**Comment by Qballl** [comment]
I guess Ill copy the kits and regen the config
