### ISSUE TITLE
enhancement: Support JSON in all areas of Essentials

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#607]
Its a little surprising all configs still do not support JSON formatting for text, It's been around a very long time now, I think its about time Essentials caught up and allow JSON formatting in the array of in-game chat that is available. This includes click able words, hover over tooltips etc in all these files:
motd.txt
rules.txt
info.txt
info_rankname.txt
book.txt
custom.txt

as well as the Essentials Chat formatting, to allow for clickable usernames in chat, and hover over tooltips for them aswell.

**Comment by NoHoPeLess** [comment]
This is an very awesome idea :D

**Comment by TomLewis** [comment]
Bump; Just found another simple reason to implement it, When multiple people /msg you in game, it would make life 10x easier to be able to click on their username/message to auto fill /msg <username> into chat.

**Comment by NoHoPeLess** [comment]
yeahh hope this will be implementet! AWESOME

**Comment by pop4959** [comment]
Easier said than done. Spigot has pretty limited support for this, and EssentialsX targets CraftBukkit. Probably would need to be done via NMS, and that requires even more maintenance. Not to mention the complexity this can introduce.

Closing and leaving this as open to PR. This will be added when it becomes a viable option, and/or when someone feels like investing a huge amount of hours to do this.

**Comment by pop4959** [comment]
Oh, also, future discussion relating to JSON support and other message related overhaul features should be directed to #2391.
