### ISSUE TITLE
EssentialsChat and Chat Formats doesnt work.

### ISSUE THREAD

**Issue by Senchurius** [EssentialsX/Essentials#609]
So.. Today i worked on my server, everything was fine. After a bit of time, i came back to the server, and the chat formats didnt work anymore.. I've reinstalled both plugins and even my spigot.jar too. Still doesn't seem to work. Here's a screenshot of my config. https://gyazo.com/a5e431bb7a2abda0106e19a36b502e87

-Senchurius

**Comment by SupaHam** [comment]
Turns out this user was using another plugin which was overriding essentials' features. Please check all your plugins in the future. :smiley:
