### ISSUE TITLE
Multiple homes not working

### ISSUE THREAD

**Issue by melinstagibson** [EssentialsX/Essentials#611]
the multiple homes thing is broken, it wonly works if i give essentials.sethome.multiple.*

if i enter a number tho i can have a max of 3 sethomes, no matter what i do

i.e.:
the permission essentials.sethome.multiple.five wont work
in the config its set to 5

but it would only let me have 3 homes

its not a permission error since i tested that out with \* and all kinds of essentials.? permissions

**Comment by TheExceed** [comment]
@melinstagibson So your config looks like this:
`five: 5`

**Comment by melinstagibson** [comment]
yep, this is the whole section:

`sethome-multiple:`
`default: 1`
`earl: 2`
`count: 3`
 `duke: 4`
`lord: 5`
`king: 6`
`saint: 10`
`five: 5`
`six: 6`
`seven: 7`
`nine: 9`
`thirteen: 13`

is there some global limit option somewhere hidden?
because i moved back to the "old" essentials and it works with pretty much the same config (except the additional settings yours offers ofc)

i can set unlimited homes with `essentials.sethome.multiple.*`
but whenever i define it like `essentials.sethome.multiple.five` it tells me "you can only set 3 homes blah"

**Comment by TheExceed** [comment]
`essentials.sethome.multiple`
`essentials.sethome.multiple.[set name]`
Are my perms and they work fine.
Maybe inheritance is messing about. Not sure.

**Comment by vemacs** [comment]
What permissions plugin?

**Comment by melinstagibson** [comment]
pex and im not using inheritance on this server

**Comment by khobbits** [comment]
I'd recommend checking your indenting, if it's defaulting to '3', that means it didn't find 'five' in the list.  There should be two spaces before the 'five'.
