### ISSUE TITLE
hi, question about essentialsx-eco

### ISSUE THREAD

**Issue by larrycatania** [EssentialsX/Essentials#613]
i have 1 server using iconomy for towny,

I just moved to bungeeproxy on 1 computer, lobby on a 2nd computer and my old towny on a 3rd server, everything seems ok accept for the ess saying slow economy response...do i need to stop using iconomy?

if i stop using iconomy then all the peoples towns money and accounts disappear of course..Can you please recommend some other economy to use? Or do I just use Essentials Economy?

Thank you,

Larry

**Comment by vemacs** [comment]
Essentials Eco doesn't support multi-server. I would continue using iConomy and see if there's an option to decrease the refresh interval.
