### ISSUE TITLE
Monster Spawners turn to pig when /rl is done!

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#614]
When i got EssentialsX i thought it would solve the problem to the other essentials plugin I had (spawners wouldnt work!) But when i do /rl now it makes some spawners a pig spawner! Only the villager spawner has not turned to pig yet. But when I break a cow spawner that looks like a pig spawner it it tells me "Cow spawner broken" and when I place it again it changes back to cow! Please help SOMEONE! 
BTW I have Silk Spawners v3.7.2 thats why it said "Cow spawner broken"

**Comment by vemacs** [comment]
Don't use reload. It's not supported by any plugin or server implementation.
