### ISSUE TITLE
Buy and Sell Signs Not Working?

### ISSUE THREAD

**Issue by Gbtank** [EssentialsX/Essentials#616]
Only Operators can use the sell and buy signs but obviously, that is problematic. I get no errors and I am certain my permissions are correct.

Perms: http://hastebin.com/vadisifila.avrasm

My spawn protection is 0, btw.

**Comment by Kakifrucht** [comment]
Please read the correct documentation: http://ess.khhq.net/wiki/Command_Reference/Perm
Why would you think that your permissions are certainly right, when they are clearly not?

**Comment by Gbtank** [comment]
I just realised that while I was testing now. I found online that those were the "correct" permissions. Apparently not. Thanks for your help tho.
