### ISSUE TITLE
Duplication

### ISSUE THREAD

**Issue by BlueDemonic** [EssentialsX/Essentials#617]
Hey, there is a dupe with this plugin.

If you set a home on a lillypad then move away then put something in your pv then go back to your home and run /pv 1 and then take the item out and close the pv it will be in your inv and still in the pv = you can duplicate the items. please fix this asap

maybe you can make it so you cant set homes on lillypads or something like this please do something to fix it

1.8.8 PaperSpigot
http://prntscr.com/b6241v

**Comment by drtshock** [comment]
update playervaults
