### ISSUE TITLE
Teleport delay only if there is a player X blocks away

### ISSUE THREAD

**Issue by Agazed** [EssentialsX/Essentials#62]
An option in the config to make it so there is a teleport delay only if there is a player X blocks away.

This will be really cool so players dont have to wait for the annoying amount of time to teleport when there is no body around to kill them.

**Comment by Kakifrucht** [comment]
This could be used to check if you have enemies around you though.

**Comment by Agazed** [comment]
Yeah. Would sound like a lot of work if you could integrate support with FactionsUUID so that way faction members/allies would be checked for.

**Comment by Agazed** [comment]
Wouldnt be a big deal with enemies if you set the radius low. Wouldnt the player already see a nametag?

**Comment by pop4959** [comment]
This sounds like a pretty niche feature to me, and something that would probably be better in its own plugin. Essentials has teleport API which you can use (if you haven't already abandoned this idea, since it's been 5 years)!
