### ISSUE TITLE
Only player who mutes can see the mute time.

### ISSUE THREAD

**Issue by Done84** [EssentialsX/Essentials#625]
http://i.imgur.com/wZQ7Sv4.png
Only the player that mutes someone sees the time of the  mute, everyone else just see "Xplayer muted YPlayer"

It would be nice for everyone to see the mute time.

**Comment by JustBru00** [comment]
I agree this is a feature that would be very helpful.

**Comment by SupaHam** [comment]
This feature has been added in 203e8b0. You can grab [build 356](https://ci.drtshock.net/job/EssentialsX/356/) from the CI server.
