### ISSUE TITLE
buy / sell signs invalid charge problem with money over 1000

### ISSUE THREAD

**Issue by Twi5TeD** [EssentialsX/Essentials#626]
not sure if this is a bug or not but when i have a buy shop with a price of 1000 + i get the error invalid  charge if i do below 1000 it works fine version 2.0.1 - b82

**Comment by drtshock** [comment]
Which economy plugin are you using and which version of vault?

**Comment by Twi5TeD** [comment]
using essentials and vault version 1.5.6-b49

**Comment by drtshock** [comment]
Are you sure you have more than $1k when you're trying to make that picture?

And can you reproduce this with ess debug mode enabled please.

**Comment by Twi5TeD** [comment]
this happens when i do this on a sign

[buy]
1
1
$3000

http://pastebin.com/nx0cLtSA

**Comment by Twi5TeD** [comment]
and this is when i charge only 1$ to test 
[buy]
1
1
$1
http://pastebin.com/mvqwLwb1

**Comment by Twi5TeD** [comment]
https://gyazo.com/590faa96b6b9290831fc1ddc966f9e35 as you can see from the top sign it automaticly addes a comma and my balance was 60k

**Comment by drtshock** [comment]
Can you use a paste service so the logs are legible please

**Comment by Twi5TeD** [comment]
updated :)

**Comment by SupaHam** [comment]
Hey, I just tested this on build 355. I am unable to reproduce this issue:
![it works!](http://supa.me/2Hgr0N.png)

**Comment by SupaHam** [comment]
@Twi5TeD Could you try using that version of essentials by itself without any other plugin on the server and see if the issue still occurs?

**Comment by Twi5TeD** [comment]
comma-separated-money: true add this to your config and try create the sign
ive tried with just that plugin and vault still the same

**Comment by Twi5TeD** [comment]
it works fine when comma-separated-money: true is set to false
but then the money doesnt have comma

**Comment by SupaHam** [comment]
That is correct. I'll dig deeper and see if I can fix this. Thanks for the help. We'd appreciate it if you could share your findings as soon as possible in order to squash the bugs and make other people have a better experience. :)

**Comment by SupaHam** [comment]
Upon further review. This was actually caused by something else entirely. The only case where you get the error message "Invalid Charge" is when you don't insert a currency symbol before the sign (e.g $, £, €, etc.) before the price.

So this works:

```
[Buy]
1
1
$1000
```

However, this doesn't work because it lacks the money symbol:

```
[Buy]
1
1
$3000
```

**Comment by Twi5TeD** [comment]
ill make a video and show if you want?

**Comment by SupaHam** [comment]
Yes please.

**Comment by Twi5TeD** [comment]
just rendering the video

**Comment by Twi5TeD** [comment]
https://youtu.be/OiaNgGFfMJw there you go

**Comment by SupaHam** [comment]
This is weird. I can't recall exactly where I saw `comma-separated-money` but the project has never had that property in the configuration based on my search queries... Are you using our EssentialsX or a fork?

**Comment by Twi5TeD** [comment]
its a fork from someone ill ask them thanks

**Comment by SupaHam** [comment]
Ahh I remember. I believe this is it https://github.com/HunterGPlays/Essentials/commit/daec100725c79888e6524bbe990123a7ce371cca

I'll go add some configuration towards my pretty currency commit as I assume that is the reason you're using that fork.

**Comment by SupaHam** [comment]
I've created a PR #665 which should get accepted sometime soon.
