### ISSUE TITLE
Balance of offline players showing as 500

### ISSUE THREAD

**Issue by tehrenderr** [EssentialsX/Essentials#628]
When players do /bal (name) of an offline player it shows up as the default 500 even though they may have more.

**Comment by Platinteufel** [comment]
Not for me .. EssX and Spigot version?

**Comment by tehrenderr** [comment]
Latest paperspigot 1.8.8, using essentials X 2.0.1-b342

**Comment by drtshock** [comment]
Can you show the logs of this in debug mode please

**Comment by tehrenderr** [comment]
http://pastebin.com/R9CSKWHM
https://gyazo.com/6b567166abb4ef6b47374de866b98852
https://gyazo.com/f34f86a4e30d3fc5784dc5cae6108386

This shows 2 issues, one with the balance of random players showing as 500 and another showing that some players can't be /seen for some reason even though they've been on the server.

**Comment by khobbits** [comment]
The online mode uuid for 'retraced' is: 2ec7346d-277c-4f8b-93ee-2f0c82f6ff5f
The offline mode uuid for 'retraced' is: e13ce71e-326e-311a-a7d0-0a1483bdc4d9
The previous owner of 'retraced' has uuid: 9923e28d-e391-4613-a0ee-1f548a0f5abd
None of those match the UUID in the log: fdbd7b1a-33af-3531-8150-e5e446b82a06

The next thing I would do is run the console command "ess uuidtest retraced" and paste the result here.

**Comment by SupaHam** [comment]
@tehrenderr are you able to do what Khobbits has advised?

**Comment by tehrenderr** [comment]
https://gyazo.com/55b09b0a37154ddd7fa4219a7b7508f1

Sorry for the late response, I was on vacation. I took a screenshot of what it showed when I did that command. 

Now when I /seen retraced it shows his data just fine and it shows his /bal.

**Comment by SupaHam** [comment]
Alright. I guess that's issue resolved until the next time.
