### ISSUE TITLE
essentialsX chat format shows default

### ISSUE THREAD

**Issue by audenga** [EssentialsX/Essentials#630]
when i have this enabled the chatformat is always

[default] {name} {chat}

doesnt matter what i do, once i disable it the defualt goes away
using build #345
http://pastebin.com/B1jxDDq2
copy of config

**Comment by drtshock** [comment]
Do you have essentialsxchat as well?

**Comment by audenga** [comment]
yea

**Comment by audenga** [comment]
otherwise no formatting would work at all

**Comment by drtshock** [comment]
Groups are case sensitive.. And you only have one defined. So the only permissions group that would have custom chat with that config is `Admin`

**Comment by audenga** [comment]
i know that, what i find funny is that it still hows default even when no formatting has been applied, or set in any way what so ever, so even with all the formatting/settings/lines commented out or removed so there should be abosutly no sort of formatting it still shows up

**Comment by audenga** [comment]
i even got a couple other people to take a look at it and it still did the same thing not even permissionsEX or group manager formatting worked

**Comment by SupaHam** [comment]
Hey,

A requirement of chat formatting is [Vault](http://dev.bukkit.org/bukkit-plugins/vault/). This plugin allows EssentialsX to connect with other plugins like PermissionsEx and do formatting as you wish.

![Formatting works!](http://supa.me/EpdAm4.png)
