### ISSUE TITLE
Piston bug

### ISSUE THREAD

**Issue by NewBestX** [EssentialsX/Essentials#631]
There is a bug with piston push blacklist.

Let's say you add unber antibuild balcklist: piston: 1 .
Now, in game build the following structure:

S A P B

S - stone
A - air
P - sticky piston facing right (towards B)
B - any block that a piston can push

Now, if you power up the piston, it will push the block away, but it won't retract it. Looks like the plugin isn't looking for the direction of the piston, it just prevents pistons around stone from retracting the block (don't forget about that 1 air gap).

**Comment by SupaHam** [comment]
Mmm, I'm unable to reproduce this issue. I've tried with one air block and one without. They both retract the dirt block just fine.
![Pistons](http://supa.me/JAHrnv.png)

Are you absolutely certain you are using a sticky piston?

**Comment by SupaHam** [comment]
Please ignore my last reply. I am able to reproduce this issue exactly how you described it. I'll see what I can do about it.

**Comment by SupaHam** [comment]
Hey, I decided to take a stab at it, the fix was much easier than I had thought. c75594f fixes this issue and you can grab the fix from [here; build 355](https://ci.drtshock.net/job/EssentialsX/355/).
