### ISSUE TITLE
What's the permissions of Essentialsx

### ISSUE THREAD

**Issue by mibibini77** [EssentialsX/Essentials#632]
i dont know the permissions
essentials.\* or essentialsx.\* dont work i dont know which permissions help me

**Comment by FlippantCactus** [comment]
It's essentials.\* although you should be using nodes, or at least grouping them in bukkit's permissions.yml

**Comment by vemacs** [comment]
Same as essentials http://wiki.ess3.net/wiki/Command_Reference/Perm
