### ISSUE TITLE
Vanished even while not being in vanish

### ISSUE THREAD

**Issue by PetKCH** [EssentialsX/Essentials#635]
This is a problem I got reported numerous times by players, my staff, which are not in vanish, sometimes appear to be vanished even if they are not using it. Then they have to /v and re /v to appear back. Same happens for me. I was thinking so far this is only problem I have, but my friend who owns his server said he has very same problem too. I am still on 1.8.8, he is on 1.9.2.

I am using one of the dev builds 2.0.1.-b342

**Comment by drtshock** [comment]
Can you give me exact steps to reproduce this? As well as a list of other plugins you're using, and then the server log in debug mode with this happening please.

**Comment by ridalarry** [comment]
This issue also happens to me but its rare I dont know the steps though

**Comment by vemacs** [comment]
Spigot bug: https://hub.spigotmc.org/jira/si/jira.issueviews:issue-html/SPIGOT-890/SPIGOT-890.html
