### ISSUE TITLE
bug with /recipe map

### ISSUE THREAD

**Issue by ridalarry** [EssentialsX/Essentials#636]
if you do /recipe map the crafted map wont appear until you click on the map in the middle of the crafting table and then if you clicked the crafted map it will crash you.

**Comment by Kakifrucht** [comment]
Nice catch, can confirm.

**Comment by drtshock** [comment]
Which version of essentialsx, spigot, and which version is the client? Like does it happen with a 1.9.2 client on 1.9.4 server but not 1.9.4 on both?

**Comment by Kakifrucht** [comment]
I can speak for 1.9.4 client/server.

**Comment by drtshock** [comment]
and which version of essentialx?

**Comment by Kakifrucht** [comment]
b330

**Comment by ridalarry** [comment]
latest spigot 1.9.4 and the latest essentialsx from the dev builds

**Comment by khobbits** [comment]
I think this was a client side bug, when I looked into it.

**Comment by SupaHam** [comment]
Is there anything we should do about it? If we disable `/recipe map` then they can't see the recipe, which then sort of becomes a broken feature :P Otherwise I can picture people using this to cause grief to others, so maybe have a yet another configurable feature?

**Comment by pop4959** [comment]
Recipe is currently disabled within Essentials, and also this sounds like a client-side crash (which Essentials would at best be able to mitigate, however players can avoid the issue by simply not intentionally clicking the map).
