### ISSUE TITLE
Flight enabled for random people upon joining

### ISSUE THREAD

**Issue by Germanode** [EssentialsX/Essentials#638]
People without essentials.fly permission sometimes are able to fly upon joining the server. I think it has to be something with the fly-upon-join-if-location-unsafe thingy. Please check on that.

**Comment by drtshock** [comment]
Can you give us some more info? Like put essx in debug mode and show us the server log of them logging in when this happens. And exactly how to reproduce that.

**Comment by Germanode** [comment]
I will do that asap. :)

**Comment by Germanode** [comment]
Players loses connection because ping lag kicked him out for "Flying is not enabled on this server". NoCheat+ does not detect any suspicious activity. The players logs in again. Then he has fly. 
Console: (note: I am candr, player who got fly mode enabled is obaid - I checked with /whois obaid and fly was green - before the kick, fly was not enabled for anyone)

> [13:50:20] [Server thread/INFO]: obaid[/x.x.x.x:censored] logged in with entity id 12409 at ([Plains]-11844.955850948178, 64.25220334025373, -431.08080541154874)
> [13:50:20] [Craft Scheduler Thread - 51/INFO]: [GAListener] Player: obaid has 32 votes
> [13:50:20] [Craft Scheduler Thread - 49/INFO]: [Essentials] looking up groupname of obaid - Member
> [13:50:20] [Craft Scheduler Thread - 41/INFO]: [Essentials] checking if obaid has essentials.geoip.hide - false
> [13:50:20] [Craft Scheduler Thread - 41/INFO]: [Essentials] checking if candr has essentials.geoip.show - true
> [13:50:20] [Craft Scheduler Thread - 41/INFO]: [Essentials] checking if Debichi01 has essentials.geoip.show - false
> [13:50:20] [Craft Scheduler Thread - 41/INFO]: [Essentials] checking if obaid has essentials.geoip.show - false
> [13:50:20] [Server thread/INFO]: [Essentials] checking if obaid has essentials.sleepingignored - false
> [13:50:20] [Server thread/INFO]: [Essentials] checking if obaid has essentials.motd - false
> [13:50:20] [Server thread/INFO]: [Essentials] checking if obaid has essentials.mail - true
> [13:50:20] [Server thread/INFO]: [Essentials] checking if obaid has essentials.fly.safelogin - false
> [13:50:20] [Server thread/INFO]: [Essentials] checking if obaid has essentials.speed - false
> [13:50:20] [Thread-13/INFO]: [CommandSync] [x.x.x.x:censored] Sent output - console@#@bungee@#@setprefix+obaid+&8[&eMember&8]&7
> [13:50:21] [Craft Scheduler Thread - 41/INFO]: [AuthMe] obaid logged in!
> [13:50:21] [Craft Scheduler Thread - 49/WARN]: [AuthMe] ERROR: Some error on creating file cache...
> [13:50:21] [Craft Scheduler Thread - 49/INFO]: [AuthMe] obaid logged in!
> [13:50:32] [Server thread/INFO]: candr issued server command: /whois obaid
> [13:50:32] [Server thread/INFO]: [Essentials] checking if candr has essentials.mail - true
> [13:50:32] [Server thread/INFO]: [Essentials] checking if candr has essentials.whois - true
> [13:50:32] [Server thread/INFO]: [Essentials] checking if candr can afford charge.
> [13:50:32] [Server thread/INFO]: [Essentials] calculated command (whois) cost for candr as 0
> [13:50:32] [Server thread/INFO]: [Essentials] charge user candr completed
> [13:50:39] [Server thread/INFO]: [0;30;1m[[0;31;22mWarning[0;30;1m][0;31;1m Ground items will be removed in [0;37;22m30 [0;31;1mseconds![m
> [13:50:49] [Server thread/FATAL]: Error executing task
> java.util.concurrent.ExecutionException: java.lang.NullPointerException
> at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_77]
> at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_77]
> at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:46) [craftbukkit.jar:git-Spigot-8a048fe-71e5248]
> at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [craftbukkit.jar:git-Spigot-8a048fe-71e5248]
> at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [craftbukkit.jar:git-Spigot-8a048fe-71e5248]
> at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [craftbukkit.jar:git-Spigot-8a048fe-71e5248]
> at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [craftbukkit.jar:git-Spigot-8a048fe-71e5248]
> at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
> Caused by: java.lang.NullPointerException
> at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:436) ~[craftbukkit.jar:git-Spigot-8a048fe-71e5248]
> at net.minecraft.server.v1_9_R2.PacketPlayInTeleportAccept.a(SourceFile:31) ~[craftbukkit.jar:git-Spigot-8a048fe-71e5248]
> at net.minecraft.server.v1_9_R2.PacketPlayInTeleportAccept.a(SourceFile:8) ~[craftbukkit.jar:git-Spigot-8a048fe-71e5248]
> at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) ~[craftbukkit.jar:git-Spigot-8a048fe-71e5248]
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_77]
> at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_77]
> at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) ~[craftbukkit.jar:git-Spigot-8a048fe-71e5248]
> ... 5 more
> [13:51:06] [Server thread/INFO]: [0;30;1m[[0;31;22mWarning[0;30;1m][0;31;1m Ground items will be removed in [0;37;22m3 [0;31;1mseconds![m
> [13:51:07] [Server thread/INFO]: [0;30;1m[[0;31;22mWarning[0;30;1m][0;31;1m Ground items will be removed in [0;37;22m2 [0;31;1mseconds![m
> [13:51:08] [Server thread/INFO]: [0;30;1m[[0;31;22mWarning[0;30;1m][0;31;1m Ground items will be removed in [0;37;22m1 [0;31;1mseconds![m
> [13:51:09] [Server thread/INFO]: [0;30;1m[[0;31;22mWarning[0;30;1m] [0;32;1mRemoved 3 Entities![m
> [13:51:09] [Craft Scheduler Thread - 63/WARN]: Exception in thread "Craft Scheduler Thread - 63" 
> [13:51:09] [Craft Scheduler Thread - 63/WARN]: org.apache.commons.lang.UnhandledException: Plugin RemoteToolkitPlugin vR10_A15.3 generated an exception while executing task 30
> at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
> at com.drdanick.McRKit.plugin.MetricsLite.postPlugin(MetricsLite.java:287)
> at com.drdanick.McRKit.plugin.MetricsLite.access$200(MetricsLite.java:53)
> at com.drdanick.McRKit.plugin.MetricsLite$1.run(MetricsLite.java:175)
> at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
> at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
> ... 3 more

[13:51:09] [Craft Scheduler Thread - 57/WARN]: Exception in thread "Craft Scheduler Thread - 57" 
[13:51:09] [Craft Scheduler Thread - 57/WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.0-SNAPSHOT generated an exception while executing task 303
at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
at fr.xephi.authme.Metrics.postPlugin(Metrics.java:335)
at fr.xephi.authme.Metrics.access$400(Metrics.java:57)
at fr.xephi.authme.Metrics$1.run(Metrics.java:223)
at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 3 more

This is it. Some errors are caused by half-compatible plugins :(

**Comment by vemacs** [comment]
Don't run a cracked server.

**Comment by Germanode** [comment]
How the bloody fuck does a cracked server affect the fly bug?

**Comment by vemacs** [comment]
Auth plugins have been known to interfere with stuff like this.
