### ISSUE TITLE
UTF8 cyrillic bug in messages file...

### ISSUE THREAD

**Issue by dyanakiev** [EssentialsX/Essentials#639]
Hey, i tried many encodings but my messages file not working property..
I dont have this problem with my other plugins!
When i type ъ in messages file, ingame is displaying some strange characters like ᶇ.... :)

**Comment by vemacs** [comment]
Escape your unicode. http://itpro.cz/juniconv/

**Comment by dyanakiev** [comment]
hallelujah This probably will work....
