### ISSUE TITLE
Prevent spawner changing with spawn eggs

### ISSUE THREAD

**Issue by Sikatsu** [EssentialsX/Essentials#641]
Can you make an config option to disable the feature to change a spawner with spawn eggs?

I sell some spawn eggs in my shop but they can change all spawners due to that.. (Villager spawners and such)

**Comment by vemacs** [comment]
Deny essentials.spawnerconvert.mobname or essentials.spawnerconvert.*.

**Comment by Kakifrucht** [comment]
They do not prevent spawnegg mobspawner changing, as that is vanilla behaviour.

**Comment by Sikatsu** [comment]
@vemacs Sir, I tried to deny that permission but they can still convert their spawners to villager spawners.

@Kakifrucht That's why I want an option in essentials. Guess it suits the best for Essentials plugin.

**Comment by Sikatsu** [comment]
I rather not use an extra plugin to disable it.. hope I can just disable that with Essentials. It would fit perfectly for essentials so.. I hate it that they can so easily buy just one spawn egg and convert their spawners to get a lot of villagers and such. Easy mending villager grinders. Breaks the economy too.

Hope you can help and re-open this issue @vemacs @drtshock

**Comment by Kakifrucht** [comment]
How about denying interact via WorldGuard blacklist?

**Comment by Sikatsu** [comment]
@Kakifrucht Do you know how that works? Would that fix the entire problem on the server so no one is able to convert the spawners anymore? If they find a spawner it should just stay the same type spawner as how they found it.

**Comment by Sikatsu** [comment]
Great, found it!

[spawner,mob_spawner,52]
ignore-groups=admin,moderator,owner,co-owner
on-interact=deny,tell

**Comment by victorlindox** [comment]
@Sikatsu Dude, thank you so much for, you saved my life and my server

**Comment by PirataGu** [comment]
Having a problem with it... interact is the same thing as break on world guard LOOOL

**Comment by mo7jas** [comment]
> Great, found it!
> 
> [spawner,mob_spawner,52] ignore-groups=admin,moderator,owner,co-owner on-interact=deny,tell

Sir, I do not understand how this command works. Please rewrite it so that I can understand how it works
