### ISSUE TITLE
Echo admin commands to admins in chat

### ISSUE THREAD

**Issue by addlepated** [EssentialsX/Essentials#643]
Prior to installing EssentialsX, if an admin did something like /tp, /time set, etc. it would pop up on the chat to other admins.  Now it's not there and I'm not sure if there is a setting I'm overlooking to make it come back.

**Comment by drtshock** [comment]
Are you sure this is from essentials and not something else? I believe that minecraft itself shows op commands to other ops.

**Comment by addlepated** [comment]
It's weird - it was echoing the op commands in the chat window to the admins prior to installing Essentials, but not afterwards.  That hard drive actually crashed last night (rip) so I just tried it out on a fresh install.  I see the op commands in the console window, but not in chat.

I don't want every single little command to show up, just the op-only ones.  There's probably a quick and easy way to get that done but I'm just a mom trying to run a server for her kids, so I'm not exactly up on scripting.

**Comment by drtshock** [comment]
Minecraft commands will broadcast to other ops. When you install essentials, it will override Minecraft's handling of the commands to handle them itself. When doing so, it won't broadcast the execution to other ops on the server.

My suggestion would be to enable social spy and then add those commands to the social spy filter. That would allow you to see when people execute them. You can do that here https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/config.yml#L134
