### ISSUE TITLE
Unsafe Enchants break in 1.9

### ISSUE THREAD

**Issue by DeadIntermediate** [EssentialsX/Essentials#644]
I noticed that in 1.9.4. The Unsafe-Enchants become broken. They will work for a while and then stop working. Although the enchants are still on it.

**Comment by drtshock** [comment]
can you elaborate?

**Comment by DeadIntermediate** [comment]
Example: I have pickaxe, with Fortune:15, Unbreaking:20 and Efficiency 15. The unbreaking will work, but the fortune and efficiency will stop working.

One way that causes those enchants to not anymore is I heard, with the pickaxe in your inventory, break a few blocks, and go back into survival and those enchants will not work anymore. But now, it happens very intermittent.

**Comment by Kakifrucht** [comment]
Why would that be an Essentials issue? Seems like a Minecraft/Spigot bug to me.

**Comment by drtshock** [comment]
Like you get the enchantments but they stop working? That's a minecraft issue.
