### ISSUE TITLE
Can't wear Elytra as a hat.

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#645]
Use to be able to when 1.9 was first released. Made for good bunny ears. Now when trying to wear an elytra on your head via /hat, it states 'You cannot use this item as a hat!'.

**Comment by SupaHam** [comment]
The code in charge of causing that code has not been modified in years. From the looks of it, this was a bug in spigot regarding max-durability of elytra being 0 whereas it's actually greater than that. 

I don't feel it is a great idea to mess around with this just for elytra. Maybe if this feature attracts more attention it might be reconsidered. :)

**Comment by mibby** [comment]
That's unfortunate. Elytra was one of the few items that actually looked great as a hat. :( Oh well, thanks for considering.
