### ISSUE TITLE
Bug? Not confirmed.

### ISSUE THREAD

**Issue by FabioZumbi12** [EssentialsX/Essentials#646]
My server is experiencing a bug where on sometime when a new player join the server stops and kick all players. This is the print of error: http://prntscr.com/bd733y

Can this is because EssentialsX?

Thanks.

**Comment by drtshock** [comment]
Can you reproduce this in debug mode enabled in essentialsx? Also, are you running the logs through something like multicraft that would truncate them?

**Comment by FabioZumbi12** [comment]
I running directly from SSH. I will turn on the debug and leave running to se we get the error. Is not always...sometimes only.

**Comment by drtshock** [comment]
thanks

**Comment by vemacs** [comment]
Can you pastebin logs/latest.log

**Comment by FabioZumbi12** [comment]
Here, my server stoped with debug on: http://pastebin.com/VNZPQSkH

I think the problen is when where a player login for the first time with other UUID (Online mode to OfflineMode).

I hope you find wheres the problem.

**Comment by drtshock** [comment]
Can you reproduce this without essentials on?

**Comment by FabioZumbi12** [comment]
I cant, or i can try with the old essentials.

**Comment by drtshock** [comment]
then it looks like it's not an ess issue.

**Comment by FabioZumbi12** [comment]
I will test with old essentials!

**Comment by drtshock** [comment]
test without essentials

**Comment by FabioZumbi12** [comment]
I cant, my server cant run without essentials because all basic commands, and this happens only if a player join with new UUID, then the server need to be running as public.

This started to happens after some days that i have update to EssentialsX

**Comment by Kakifrucht** [comment]
How about setting up a testing environment with your whole setup, just delete some player files of your own account(s) and try it out? Offline, you shouldn't test stuff like this in a production environment either way.
