### ISSUE TITLE
BUG WARPS

### ISSUE THREAD

**Issue by xSlamw** [EssentialsX/Essentials#648]
i try to use /warps , and /warp namewarp and i can't , i'm using the nodes but i can't, but with op i can use that, [Sorry for my bad english]

**Comment by drtshock** [comment]
can you paste the server log while this happens

**Comment by xSlamw** [comment]
The server do not have on log when that happening

**Comment by xSlamw** [comment]
do not make any message on log

**Comment by drtshock** [comment]
yes it does
