### ISSUE TITLE
BUG Entites

### ISSUE THREAD

**Issue by yzandre** [EssentialsX/Essentials#650]
hi, 
command with entites don't work with last release

example :                   /tp @e[type=Pig,r=3] Player
another example :     /kill @e[type=ArmorStand]

error return :     the player is not found

Thanks fix it for 1.9.4 plz.

**Comment by JustBru00** [comment]
@yzandre Essentials doesn't have support for non player teleport. (At least I don't believe so.) You can use `/minecraft:tp @e[type=Pig,r=3]`

**Comment by drtshock** [comment]
^
