### ISSUE TITLE
Not an issue just a request of a feature

### ISSUE THREAD

**Issue by MADS0LADEN** [EssentialsX/Essentials#651]
Please make an event that listens for vanish toggle. :)

**Comment by drtshock** [comment]
what do you mean

**Comment by MADS0LADEN** [comment]
Make a custom event that triggers when a player goes vanish

**Comment by SupaHam** [comment]
This has been introduced in 19f65108. You can grab the feature from [build 384](https://ci.drtshock.net/job/EssentialsX/) on the CI server.
