### ISSUE TITLE
The suffix does not change message color 

### ISSUE THREAD

**Issue by chief-j** [EssentialsX/Essentials#654]
Usually, the color suffix should change the color of the message, but it does not happen, even if you remove all spaces

**Comment by drtshock** [comment]
Can you show me your chat format?

**Comment by chief-j** [comment]
![screenshot_26](https://cloud.githubusercontent.com/assets/6630061/15973470/4341fd7e-2f4c-11e6-8c53-fff1b525bf58.png)
![screenshot_27](https://cloud.githubusercontent.com/assets/6630061/15973469/42a75a30-2f4c-11e6-9624-78a6279de063.png)
![screenshot_29](https://cloud.githubusercontent.com/assets/6630061/15973888/58ac1986-2f4e-11e6-90b8-f4049327bfe4.png)
message: `[Admin]chief: This message should be painted in Aqua color`
`suffix: §f: §b`
And please, divide displayname for prefix, suffix and username

**Comment by drtshock** [comment]
You have &r ...

**Comment by chief-j** [comment]
There is no such...

**Comment by chief-j** [comment]
`format: '{DISPLAYNAME}{MESSAGE}'`

**Comment by chief-j** [comment]
format: '{DISPLAYNAME}{MESSAGE}'
