### ISSUE TITLE
over player's head nickname.

### ISSUE THREAD

**Issue by netherarts** [EssentialsX/Essentials#656]
i want to change the nickname which displays over player's head. there's was plugin called tagapi but it doesn't works with 1.9 anymore.

i keep trying to find some plugin like TagAPI but not yet to find and also i should find the plugin that can connect or convert with essential's data.

can you make for it?

**Comment by FlippantCactus** [comment]
NameTagEdit does this. It's not an essential feature...

**Comment by vemacs** [comment]
Not within the scope of the project.
