### ISSUE TITLE
Home teleporting doesn't work even with checks disabled

### ISSUE THREAD

**Issue by ampavre** [EssentialsX/Essentials#657]
After listening to drtshock in a previous issue, with values:

config.yml
teleport-safety: false
force-disable-teleport-safety: true

paper.yml
disable-teleportation-suffocation-check: true 

but when doing /home it says Teleporting... then never teleports the player? But all checks for safe TP'ing is disabled so it should allow the player to be TP'd? Which I assume this is a bug?

Using latest EssentialsX and paperspigot 1.9.4

**Comment by vemacs** [comment]
Read the wiki more closely. teleport-safety needs to be set to true. It's counterintuitive, but how it works.
