### ISSUE TITLE
/r going to 2nd last person messaged

### ISSUE THREAD

**Issue by jake430** [EssentialsX/Essentials#658]
Good morning,
On spigot 1.9.4 using the latest EssentialsX (also tried with last 1.9.4 version of EssentialsX), /r doesn't go to the last person that messaged you.  Instead, it goes to the 2nd to last person.

Demonstration: http://prntscr.com/bftx4z
As you can see, the message went to Pam, which was the first person that messaged me instead of the last, which was who it was supposed to go to.

Spigot version: http://prntscr.com/bftwlu (last 1.9.4 release available before 1.10 builds began to be released)

Thank you for your dedication and work on EssentialsX!

**Comment by Kakifrucht** [comment]
Check your config for last-message-reply-recipient and last-message-reply-recipient-timeout.
If reply-repicient is set to true, it will always go to the last person you messaged.

**Comment by SupaHam** [comment]
It should be noted that if you used the original Essentials or an old version of EssentialsX that your config.yml will **not** be populated with `last-message-reply-recipient` or other related features. Please refer to the config.yml [here](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/config.yml) for the latest configurable features.

**Comment by jake430** [comment]
Thank you!
