### ISSUE TITLE
A way to scale price via EssEco signs.

### ISSUE THREAD

**Issue by cooperisdunn** [EssentialsX/Essentials#66]
Player A has been mining for a long time, and has a tonne of cobble. He goes to the shop, and starts selling his cobble to the EssEco sign that will take his cobble and give him money. This sign is setup to take 64 cobble blocks at a time. When he is finished selling his cobble, Player A realizes he had an uneven amount of cobble and is stuck with a measly 46 cobble he cannot sell. Player A cries himself to sleep that night thinking about the money he missed because he couldn't sell his leftover 46 cobble. My request is to add a scaling feature that would allow 46 cobble to be sold to an EssEco sign that (as of right now) only takes 64 at a time and give the correct amount of money.

Please label this as an Enhancement.

**Comment by pop4959** [comment]
Creating a sign that says it takes 64 items but allows less would be confusing. In your scenario it makes more sense to create a buy sign that takes less items, or the player should just make sure to sell when he has enough items.
