### ISSUE TITLE
Essentialsx and Hyperconomy

### ISSUE THREAD

**Issue by merlinshaw** [EssentialsX/Essentials#660]
I have sent this error to developer of Hyperconomy as well but I'm unsure who i need to send it to so here it is.

http://paste.md-5.net/wuwoyaxoca.avrasm

I am setting up a server market and the market plugin wants to create a user in the essentials userdata " I think" the user it is trying to create is "SinisterMarket"  It makes this user seance it uses a dynamic economy for item pricing and the market needs money to buy from players and gains money from selling to players.

**Comment by drtshock** [comment]
Can you link me to the ticket you made with them?

**Comment by merlinshaw** [comment]
I had sent him the Error using the Bukkit PM system.
