### ISSUE TITLE
Issue with dimensional travel while in spectator mode

### ISSUE THREAD

**Issue by Bob1nz** [EssentialsX/Essentials#662]
Hello there seems to be a problem where players who are not OP will fall into the void when teleporting to a player in another dimension while in spectator mode.
This issues is not present when the player is OP or when Essentials is not loaded and the player teleports correctly and does not fall.

Essentials is the only plugin loaded  using 2.0.1-b354 for 1.10
Using CraftBukkit version git-Bukkit-9856d8a (MC: 1.10) (Implementing API version 1.10-R0.1-SNAPSHOT)

**Comment by SupaHam** [comment]
Hey. You should note that Multiverse has world-specific gamemodes. This means that when a normal (not op) player leaves world A and goes to world B their gamemode will be set to whatever it is set to in Multiverse, by default this is Survival gamemode.

If a player is op and teleports from world A to world B, their gamemode is retained as opposed to being set to the world default gamemode as can be configured in Multiverse.

**Comment by Bob1nz** [comment]
There is no multiverse installed.

**Comment by kz5ee** [comment]
I'm having the same issue.  When running only Craftbukkit/Spigot, spectator teleportation works as expected.  When Essentials is installed is when this issue occurs.

Current status of server.  Fresh build of CraftBukkit and Build #359 of EssentialsX:
![bukkitversionplugins](https://cloud.githubusercontent.com/assets/5105197/16174583/3c5ffd02-358d-11e6-8001-c95a6cd38749.png)

Update 0:59 UTC:  Using /tpa <user> from command line from spectator account produces same result.

Update 1:16 UTC:  Assigning the permissions fly && fly.safelogin permissions seems to fix the issue.

Update 1:25 UTC:  It seems that the spectator account is checked for flight permissions and if it doesn't have the permission, flight is removed and the spectator falls through the world.

**Comment by kz5ee** [comment]
I think that `if ( Player.getGameMode != SPECTATOR )` before the check for fly permission will fix the issue.

**Comment by SupaHam** [comment]
Based on what I am reading, you shouldn't need `essentials.fly.safelogin`. However, you seem to have provided the fix, I'll test and get back to you.

**Comment by kz5ee** [comment]
Yes, I've tested without `essentials.fly.safelogin` and it works as expected with only `essentials.fly`.

**Comment by SupaHam** [comment]
This has been fixed in a267fb1. You can grab the fix from [build 360](https://ci.drtshock.net/job/EssentialsX/360/) on the CI server.

Thanks for your help @kz5ee.

**Comment by kz5ee** [comment]
No problem!  Thanks for the super quick fix!
