### ISSUE TITLE
EssentialsX First Join Command

### ISSUE THREAD

**Issue by Nitacraft** [EssentialsX/Essentials#667]
Please give us the power to run console commands on the first join of player.

**Comment by drtshock** [comment]
Use commands in kits that you give players on first join

**Comment by Nitacraft** [comment]
No no no, I want to run another command. /profile setup
https://www.spigotmc.org/resources/myprofile-mysql.18606/

**Comment by drtshock** [comment]
When players join? Yes just put that command in a kit when players join.
