### ISSUE TITLE
Bug with selling potions

### ISSUE THREAD

**Issue by johnb165** [EssentialsX/Essentials#671]
Cannot sell potions example, Speed two as it always gives me this:
http://prntscr.com/bjbohd

**Comment by SupaHam** [comment]
The message is clear. You cannot sell a potion that is both extended in time and amplified. This is due to Minecraft limitations of potion values.

**Comment by johnb165** [comment]
But its just a regular speed two potion, unless that was removed from 1.10?

**Comment by SupaHam** [comment]
Can you post the exact contents of your sign? I will try to get back to you as soon as I can.

**Comment by johnb165** [comment]
http://prntscr.com/bjch1g

**Comment by SupaHam** [comment]
The id you're looking for is `373:8226` not `373:8290`.

Potion data values can be found [here](http://minecraft.gamepedia.com/Potion).
