### ISSUE TITLE
My server won't recognise that I have Essentials...

### ISSUE THREAD

**Issue by RenCayce** [EssentialsX/Essentials#673]
Sorry if there's a solution for this somewhere but I've been looking forever...  If I do /plugins, Essentials isn't there. There's no indication I even downloaded it except that it's in the plugins folder if I look...

I've tried moving the files around and unpacking stuff and... basically I've given up. Please help me.

**Comment by drtshock** [comment]
Paste your startup log in pastebin please

**Comment by RenCayce** [comment]
http://pastebin.com/USAu2HtL

?? Sorry this is a mess; I don't know what exactly you're looking for. As far as I can see only the beginning of it looks... useful.

**Comment by drtshock** [comment]
You don't have essentials installed.

**Comment by RenCayce** [comment]
How exactly do I "install" it though...

**Comment by SupaHam** [comment]
1. Make sure your server is not running.
2. If you haven't done so already, move the downloaded jar files to your plugins directory.
3. Start the server.
4. If you made a backup of your config.yml file, stop the server and edit the newly generated config.yml file with only what you need, from the backup.
5. Start the server.
6. Enjoy!

**Comment by RenCayce** [comment]
Thank you! Turns up I wasn't moving the .jar files...
