### ISSUE TITLE
Color codes in group formats not working

### ISSUE THREAD

**Issue by hjklr54679** [EssentialsX/Essentials#674]
After switching from spigot-essentials to EssentialsX for a number of reasons, the colors in group formats stopped working. I can display other things using group formats, ex. faction tags or custom display names, however I cannot use colors for the chat of a PermissionsEX group. I have tried using & and § for colors but it makes no difference. I have created a new config file and copied over the group formats rather than keeping the old file, if that helps. Here is an example of the group formats: http://pastebin.com/hYV981pi. Yes, I have the chat module on the server.

**Comment by drtshock** [comment]
Can you paste your server startup log in pastebin please

And is it the factions relation color not working or is it the color codes themselves. They should be working with &

**Comment by hjklr54679** [comment]
Not at the moment, as the server is on my friend's computer (still working on it). I will get to it as soon as possible. Also, it is the color codes themselves. Factions recolor works fine.

**Comment by NicoNekoDev** [comment]
group-formats:
    Admin: '&a&l[&6PikaCraft&a&l] &8[&cAdmin&8] {DISPLAYNAME} &e➽ &b{MESSAGE}'
    Owner: '&a&l[&6PikaCraft&a&l] &6[&4Owner&6] {DISPLAYNAME} &e➽ &a{MESSAGE}'
not working... please fix vault group dependency

**Comment by SupaHam** [comment]
![group formatting works](http://supa.me/a9qVUj.png)

Hi I just tested this on build 361 and it works just fine.

Please make sure you have the following plugins installed:
- Vault
- EssentialsX
- EssentialsXChat
- _Permissions plugin_

**Comment by NicoNekoDev** [comment]
I solved for myself anyway, i used my custom plugin for formating, but whatever, this is a bug and need solved.
