### ISSUE TITLE
PermissionsEX and Sign Shops

### ISSUE THREAD

**Issue by teamaonn** [EssentialsX/Essentials#677]
Okay, So I couldn't get this to work right in Essentials the first time i tried over a year ago... gave up and used a suppliment. 

Now I wanna try again, Using EssentialsX this time, I put in the permissions to PEX manually, erased it from the Config even to see if it was just pex that was unsupported, and non-oped players cannot still buy or sell to signs. No sign permissions seem to work. Just have it entered as - essentials.(perm name) tried to enter it with :true at the end too, but that didn't work either. What am I missing?

**Comment by vemacs** [comment]
Read the wiki:

> Since Essentials 2.8, all signs are now disabled by default. You can enable each sign individually in the Essentials config.yml.

http://ess.khhq.net/wiki/Sign_Tutorial

**Comment by teamaonn** [comment]
but no one can use them. except for ops.

**Comment by vemacs** [comment]
Don't edit the config file. Use in-game commands to add essentials.signs.use.\* to your main group.

**Comment by teamaonn** [comment]
Did that. Still nothing. Using 1.9.4, spigot with PEX.  it's right at the top.

**Comment by vemacs** [comment]
Can't help then. This is not an issue with EssentialsX, but rather your permissions setup. Maybe somebody else can step in.

You should check if the user does indeed have the permission with `pex user <user> check <permission>`, and if Essentials is running in non-config-based-permissions mode (it's in the startup log).

**Comment by teamaonn** [comment]
Wow you're good. Set my pex to debug mode in the config and tried using the signs again while Deoped and it told me what perm to add. Added it and instantly usable. THANKS SO MUCH!
