### ISSUE TITLE
Migration from Essentials on EssentialsX

### ISSUE THREAD

**Issue by StalKlim** [EssentialsX/Essentials#679]
Hello, I would like to know what I need to do and change configurations if I want to go to your plug-in? The fact that at the moment the server is running an older version of Essentials and I would like to go on EssentialsX without problems. What should I do for this? And whether it is possible to save userdata folder intact?

**Comment by FlippantCactus** [comment]
Backup all your userdata. Replace the old essentials jar with the essentials x jar. If you want to benefit from the new features, delete your config and add what you had back in.

**Comment by vemacs** [comment]
The plugin documentation says that it's drop-in. Read the readme.
