### ISSUE TITLE
Support for /spectate

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#68]
Hey man.
First of all, thank you for keeping this project alive, this is such an essential plugin collection for any server of any size.
In your wiki https://github.com/drtshock/Essentials/wiki you document saying you have specific permissions for each gamemode, does this include /spectate at current I have a custom script I made to allow staff to toggle /spectate to spy on suspect players.
I haven't yet upgraded to your version of essetnails and wish to clear a few things up before I do :)

**Comment by vemacs** [comment]
Use /gmsp, /egmsp, /gm spec, /gm 3, or /gm sp. Permission is essentials.gamemode.spectator.

**Comment by TomLewis** [comment]
essentials.gamemode.spectator is what I was looking for, thank you.
