### ISSUE TITLE
Error on PlayerJoin

### ISSUE THREAD

**Issue by 10becja** [EssentialsX/Essentials#680]
When a player joins the server, there is an exception that occurs (build 363)

http://pastebin.com/J3jsneL0

I'm using Spigot 1.10.2

Plugins: Essentials, EssentialsSpawn

**Comment by Vestle** [comment]
It says you are running build 354 in the error. Try a reboot.

**Comment by 10becja** [comment]
Well I feel silly now. Figured out what I did: Used the main plugin from the spigot page and essentials spawn from jenkins. Thanks.
