### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by StalKlim** [EssentialsX/Essentials#682]
Hello guys! Support of my hosting answered my question about an error, I was informed that this is most likely caused by a plugin that is responsible for the chat on my server. That plugin is Essentialschat. Can you fix this? Or am I mistaken? http://pastebin.com/jFnNV6Tk Can you help to solve this? And to explain because of what is happening, if not to blame EssentialsChat. Aaand Can you help to solve this? And to explain of what is happening, if plugin EssentialsChat is not cause. Thanks.

**Comment by Kakifrucht** [comment]
Essentials doesn't seem to have anything to do with this.

**Comment by SupaHam** [comment]
Hey @StalKlim Not sure how you came to this area but the errors are being caused by two other plugins:
- CoreProtect
- ServerSigns

Please open tickets in their respective forums and hopefully they can help you from there. This is out of our hands. Sorry.
