### ISSUE TITLE
Essentials X Permissions

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#683]
Hey i was wondering are all the original essentials permissions the same on Essentials X or not? also whats the permission to give access to all essentials commands in Essentials X?

**Comment by lapry34** [comment]
http://wiki.mc-ess.net/wiki/Command_Reference/Perm

**Comment by ghost** [comment]
are those working?

**Comment by JonathanBrouwer** [comment]
They should work

**Comment by ghost** [comment]
Okay ill try them out
and whats the permission to give access to all commands?

**Comment by SupaHam** [comment]
`essentials.*` gives permission to all of EssentialsX functionality. **Use it with caution**.

Also check our wiki for more information about EssentialsX's features. There's a button at the top that says wiki or you can just click [here](https://github.com/drtshock/Essentials/wiki).
