### ISSUE TITLE
essentials:tp does not support decimal numbers

### ISSUE THREAD

**Issue by Cat7373** [EssentialsX/Essentials#685]
see: [SpigotPlugins/PLUG-158](https://hub.spigotmc.org/jira/browse/PLUG-158)

**Comment by SupaHam** [comment]
This has been fixed in ebe6abd. You can grab the fix from [build 365](https://ci.drtshock.net/job/EssentialsX/365/) on the CI server.

P.S. you must have `teleport-to-center` set to `false` in your config.yml. If it is not present you can simply add it to your config.yml on a new line like so:

``` yaml
teleport-to-center: false
```
