### ISSUE TITLE
/baltop cluttered when using factions

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#686]
On two servers where I am staff we are using the factions plugin, and in both cases (1.9.4 and 1.8.7) if you type /baltop there are players as well as factions in it. I reported this issue to the factions plugin maker, and they said that they use UUID's to recognise the factions bank accounts, and that they can't controll how the /baltop command handles those UUIDs. They advised me to report it to you! Here is the link to that [issue](https://github.com/MassiveCraft/Factions/issues/1094) for more information!

**Comment by SupaHam** [comment]
Hi. Thank you for the report can you provide me with some more information:
- Spigot version
- EssentialsX version
- One or more files of a faction found under `plugins/Essentials/userdata/`.

**Comment by Kakifrucht** [comment]
#191 ?

**Comment by SupaHam** [comment]
Yes thank you but I will resume investigations here as that is a much older issue.

**Comment by ghost** [comment]
The server that is on 1.8.7 that I own is running on:
- CraftBukkit version git-Spigot-6d16e64-09ddd9b (MC: 1.8.7) (Implementing API version 1.8.7-R0.1-SNAPSHOT)
- EssentialsX v2.0.1 b342 (but this is no issue specific to this version, older and newer ones have it too)

I also included on of the faction userdata files, they are all similar to this except for the name, so I think that this one will be a clear example:

[faction_userdata_example.zip](https://github.com/drtshock/Essentials/files/333823/faction_userdata_example.zip)

**Comment by SupaHam** [comment]
For reference I am putting the content of the zip file in here:

``` yaml
npc: true
lastAccountName: faction_e1dbccec_7860_40e3_aa72_2c12f722eda1
money: '0.0'
```

**Comment by SupaHam** [comment]
@AlHollandiyah Are you able to download [build 366](https://ci.drtshock.net/job/EssentialsX/366/) and tell me if this issue still occurs?

**Comment by ghost** [comment]
Going to test it right away!

**Comment by ghost** [comment]
It seems to have fixed it properly! Thank you very much, that is awesome!!

**Comment by SupaHam** [comment]
Thank you for your assistance. :)
