### ISSUE TITLE
Fly

### ISSUE THREAD

**Issue by renzotom** [EssentialsX/Essentials#691]
Hello, when I use /fly PLAYER, it write him enabled, when I try it again, also enabled, but he can´t fly. I can spam /fly player and him it write enabled, enabled, enabled, but he can´t fly. Maybe sometimes, there is disabled and he can´t fly before I disabled it, but I must spam to do it. Fix it please. I use same version of essentialsX and spigot how in my issue about Gamemode 3.

**Comment by SupaHam** [comment]
Thanks for your report. Are you able to provide the server startup log when this happened? I have a feeling something - or someone - else is toggling that player's flight mode.

P.S. you can find the server startup log in your server's `logs` folder.

**Comment by renzotom** [comment]
Here http://pastebin.com/59EHF6uX

**Comment by SupaHam** [comment]
Wow. You really need sort out your server. I've no idea why you have a plugin called RuntimeCompiler but that sounds absolutely stupid.

Anyways, nothing indicates Essentials being at fault here. I must ask that you fix all of your issues and then come back to us for help. There is a huge mess and anyone of those errors can be interfering with EssentialsX and other functionality.

Please make another issue once you have resolved all of these issues.

**Comment by renzotom** [comment]
I don´t know, what is runtimecompiler plugin, I don´t have it in folder, it probably make another plugin. And what are there for problems? I know problem with RandomTeleport and Kingdoms, Sorter (I report all) but another?

**Comment by SupaHam** [comment]
Honestly your log file scares me. 
1. Line 12: Incorrect CraftBook jar file.
2. Line 146: LogBlock cannot connect to MySQL server. Contact your server host to obtain your MySQL details and insert them into the LogBlock config appropriately.
3. Line 989: AdvancedKitsReloaded plugin config incorrect. You'll have to ask them for information on how to fix.
4. Line 1879: SpecializedCrates BasicCrate can't load properly. Contact them for help.
5. Line 2146: FurnitureMaker has a NullPointerException. Contact them for help.
6. Line 2237: CubeRunner cannot connect to MySQL server, repeat step 2 for CubeRunner's config.
7. Line 2403: Error in FurnitureLib all the way to the bottom.

If you wish to resolve this issue quicker I would ask that you disable all the plugins but EssentialsX and see if the issue still happens.

If it does type `/ess debug`. Then, type `/fly` twice. Then, open the log file and put it in http//pastebin.com like you did.

**Comment by renzotom** [comment]
Here is log, and it work :/ http://pastebin.com/BQE4kYGi. You don´t know, what plugin can block it? Maybe Pfly ? It is buggy for this version

**Comment by SupaHam** [comment]
I'm not entirely sure. You'll have to disable one plugin at a time until it works.

**Comment by renzotom** [comment]
Ok, gamemode also work with essentials only.  I try it.

**Comment by renzotom** [comment]
And sorry, I thought, this bug was from EssentialsX. You can close that.
