### ISSUE TITLE
Permission for bypass teleport unsafe ?

### ISSUE THREAD

**Issue by renzotom** [EssentialsX/Essentials#693]
Hello, when is destination unsafety, players can´t teleport there. But, when you add permissions, ex. Owner or admin can teleport there (no all OP, only bypass permission).

**Comment by drtshock** [comment]
what

**Comment by SupaHam** [comment]
Hey. EssentialsX does not have any permissions regarding bypassing teleport safety. Teleport safety is managed via the config.yml and applies to all players on the server.

You can turn off teleport safety by setting `teleport-safety: false` in the config.yml. However, players might suffocate if the teleportation coordinates are within a fully solid enclosed area.

**Comment by renzotom** [comment]
I know, but you can add bypass permission or for Op players?

**Comment by vemacs** [comment]
Not intended
