### ISSUE TITLE
Essentials Prefixes

### ISSUE THREAD

**Issue by Drumples** [EssentialsX/Essentials#694]
Hello, I am having problems with Prefixes using essentials, vault, and permissions ex. My server is running 1.10 craftbukkit. I have set the prefix for the owner group using permissions ex and nothing more. I checked the permissions ex config file, and the prefix was set. However, the prefixes are not showing up in the chat. Can anybody help?

**Comment by drtshock** [comment]
Can you paste your server startup log in pastebin please

**Comment by Drumples** [comment]
30.06 14:55:47 [Multicraft] Loading server properties
30.06 14:55:47 [Multicraft] Starting server!
30.06 14:55:47 [Multicraft] Loaded config for "Spigot 1.10.2 (Auto Update)"
30.06 14:55:47 [Multicraft] JAR file not found, copying from global JAR directory
30.06 14:55:47 [Multicraft] Updating eula.txt file
30.06 14:55:47 [Multicraft] Failed to obtain process information: NoSuchProcess no process found with pid 6087
30.06 14:55:47 [Server] INFO Loading libraries, please wait...
30.06 14:55:52 [Server] INFO Starting minecraft server version 1.10.2
30.06 14:55:52 [Server] INFO Loading properties
30.06 14:55:52 [Server] INFO Default game type: SURVIVAL
30.06 14:55:53 [Server] INFO This server is running CraftBukkit version git-Spigot-5391d73-287ef78 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
30.06 14:55:53 [Server] INFO Debug logging is disabled
30.06 14:55:53 [Server] INFO Server Ping Player Sample Count: 12
30.06 14:55:53 [Server] INFO Using 4 threads for Netty based IO
30.06 14:55:53 [Server] INFO Generating keypair
30.06 14:55:53 [Server] INFO Starting Minecraft server on 167.114.118.194:26048
30.06 14:55:54 [Server] INFO Using epoll channel type
30.06 14:55:54 [Server] INFO Set PluginClassLoader as parallel capable
30.06 14:55:54 [Server] INFO [PermissionsEx] Loading PermissionsEx v1.23.4
30.06 14:55:54 [Server] INFO [Vault] Loading Vault v1.5.6-b49
30.06 14:55:54 [Server] INFO [Essentials] Loading Essentials v2.0.1-b354
30.06 14:55:54 [Server] INFO [Vault] Enabling Vault v1.5.6-b49
30.06 14:55:54 [Server] INFO [Vault] [Economy] Essentials Economy found: Waiting
30.06 14:55:54 [Server] INFO [Vault] [Permission] PermissionsEx found: Waiting
30.06 14:55:54 [Server] INFO [Vault] [Permission] SuperPermissions loaded as backup permission system.
30.06 14:55:54 [Server] INFO [Vault] [Chat] PermissionsEx found: Waiting
30.06 14:55:54 [Server] INFO [Vault] Enabled Version 1.5.6-b49
30.06 14:55:54 [Server] INFO **** Beginning UUID conversion, this may take A LONG time ****
30.06 14:55:54 [Server] INFO Preparing level "world"
30.06 14:55:54 [Server] INFO -------- World Settings For [world] --------
30.06 14:55:54 [Server] INFO Cactus Growth Modifier: 100%
30.06 14:55:54 [Server] INFO Cane Growth Modifier: 100%
30.06 14:55:54 [Server] INFO Melon Growth Modifier: 100%
30.06 14:55:54 [Server] INFO Mushroom Growth Modifier: 100%
30.06 14:55:54 [Server] INFO Pumpkin Growth Modifier: 100%
30.06 14:55:54 [Server] INFO Sapling Growth Modifier: 100%
30.06 14:55:54 [Server] INFO Wheat Growth Modifier: 100%
30.06 14:55:54 [Server] INFO NetherWart Growth Modifier: 100%
30.06 14:55:54 [Server] INFO Mob Spawn Range: 4
30.06 14:55:54 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Mi 16
30.06 14:55:54 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
30.06 14:55:54 [Server] INFO Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
30.06 14:55:54 [Server] INFO Random Lighting Updates: false
30.06 14:55:54 [Server] INFO Structure Info Saving: true
30.06 14:55:54 [Server] INFO Max Entity Collisions: 8
30.06 14:55:54 [Server] INFO Custom Map Seeds:  Village: 10387312 Feature: 14357617
30.06 14:55:54 [Server] INFO Max TNT Explosions: 100
30.06 14:55:54 [Server] INFO Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
30.06 14:55:54 [Server] INFO Item Despawn Rate: 6000
30.06 14:55:54 [Server] INFO Item Merge Radius: 2.5
30.06 14:55:55 [Server] INFO Arrow Despawn Rate: 1200
30.06 14:55:55 [Server] INFO Allow Zombie Pigmen to spawn from portal blocks: true
30.06 14:55:55 [Server] INFO Experience Merge Radius: 3.0
30.06 14:55:55 [Server] INFO Nerfing mobs spawned from spawners: false
30.06 14:55:55 [Server] INFO View Distance: 10
30.06 14:55:55 [Server] INFO Zombie Aggressive Towards Villager: true
30.06 14:55:55 [Server] INFO -------- World Settings For [world_nether] --------
30.06 14:55:55 [Server] INFO Cactus Growth Modifier: 100%
30.06 14:55:55 [Server] INFO Cane Growth Modifier: 100%
30.06 14:55:55 [Server] INFO Melon Growth Modifier: 100%
30.06 14:55:55 [Server] INFO Mushroom Growth Modifier: 100%
30.06 14:55:55 [Server] INFO Pumpkin Growth Modifier: 100%
30.06 14:55:55 [Server] INFO Sapling Growth Modifier: 100%
30.06 14:55:55 [Server] INFO Wheat Growth Modifier: 100%
30.06 14:55:55 [Server] INFO NetherWart Growth Modifier: 100%
30.06 14:55:55 [Server] INFO Mob Spawn Range: 4
30.06 14:55:55 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Mi 16
30.06 14:55:55 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
30.06 14:55:55 [Server] INFO Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
30.06 14:55:55 [Server] INFO Random Lighting Updates: false
30.06 14:55:55 [Server] INFO Structure Info Saving: true
30.06 14:55:55 [Server] INFO Max Entity Collisions: 8
30.06 14:55:55 [Server] INFO Custom Map Seeds:  Village: 10387312 Feature: 14357617
30.06 14:55:55 [Server] INFO Max TNT Explosions: 100
30.06 14:55:55 [Server] INFO Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
30.06 14:55:55 [Server] INFO Item Despawn Rate: 6000
30.06 14:55:55 [Server] INFO Item Merge Radius: 2.5
30.06 14:55:55 [Server] INFO Arrow Despawn Rate: 1200
30.06 14:55:55 [Server] INFO Allow Zombie Pigmen to spawn from portal blocks: true
30.06 14:55:55 [Server] INFO Experience Merge Radius: 3.0
30.06 14:55:55 [Server] INFO Nerfing mobs spawned from spawners: false
30.06 14:55:55 [Server] INFO View Distance: 10
30.06 14:55:55 [Server] INFO Zombie Aggressive Towards Villager: true
30.06 14:55:55 [Server] INFO -------- World Settings For [world_the_end] --------
30.06 14:55:55 [Server] INFO Cactus Growth Modifier: 100%
30.06 14:55:55 [Server] INFO Cane Growth Modifier: 100%
30.06 14:55:55 [Server] INFO Melon Growth Modifier: 100%
30.06 14:55:55 [Server] INFO Mushroom Growth Modifier: 100%
30.06 14:55:55 [Server] INFO Pumpkin Growth Modifier: 100%
30.06 14:55:55 [Server] INFO Sapling Growth Modifier: 100%
30.06 14:55:55 [Server] INFO Wheat Growth Modifier: 100%
30.06 14:55:55 [Server] INFO NetherWart Growth Modifier: 100%
30.06 14:55:55 [Server] INFO Mob Spawn Range: 4
30.06 14:55:55 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Mi 16
30.06 14:55:55 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
30.06 14:55:55 [Server] INFO Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
30.06 14:55:55 [Server] INFO Random Lighting Updates: false
30.06 14:55:55 [Server] INFO Structure Info Saving: true
30.06 14:55:55 [Server] INFO Max Entity Collisions: 8
30.06 14:55:55 [Server] INFO Custom Map Seeds:  Village: 10387312 Feature: 14357617
30.06 14:55:55 [Server] INFO Max TNT Explosions: 100
30.06 14:55:55 [Server] INFO Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
30.06 14:55:55 [Server] INFO Item Despawn Rate: 6000
30.06 14:55:55 [Server] INFO Item Merge Radius: 2.5
30.06 14:55:55 [Server] INFO Arrow Despawn Rate: 1200
30.06 14:55:55 [Server] INFO Allow Zombie Pigmen to spawn from portal blocks: true
30.06 14:55:55 [Server] INFO Experience Merge Radius: 3.0
30.06 14:55:55 [Server] INFO Nerfing mobs spawned from spawners: false
30.06 14:55:55 [Server] INFO View Distance: 10
30.06 14:55:55 [Server] INFO Zombie Aggressive Towards Villager: true
30.06 14:55:56 [Server] INFO Preparing start region for level 0 (Seed: 8829917126768265191)
30.06 14:55:57 [Server] INFO Preparing spawn area: 0%
30.06 14:55:58 [Server] INFO Preparing spawn area: 62%
30.06 14:55:58 [Server] INFO Preparing start region for level 1 (Seed: 8829917126768265191)
30.06 14:55:59 [Server] INFO Preparing spawn area: 81%
30.06 14:55:59 [Server] INFO Preparing start region for level 2 (Seed: 8829917126768265191)
30.06 14:55:59 [Server] INFO [PermissionsEx] Enabling PermissionsEx v1.23.4
30.06 14:55:59 [Server] INFO [PermissionsEx] Initializing file backend
30.06 14:55:59 [Server] INFO [PermissionsEx] Permissions file successfully reloaded
30.06 14:55:59 [Server] INFO [Vault][Permission] PermissionsEx hooked.
30.06 14:55:59 [Server] INFO [Vault][Chat] PermissionsEx_Chat hooked.
30.06 14:55:59 [Server] INFO [Essentials] Enabling Essentials v2.0.1-b354
30.06 14:56:00 [Server] INFO Using locale en_GB
30.06 14:56:00 [Server] INFO [Essentials] Using 1.8.3+ BlockStateMeta provider as mob spawner provider.
30.06 14:56:00 [Server] INFO [Essentials] Using Reflection based provider as spawn egg provider.
30.06 14:56:00 [Server] INFO [Essentials] Using 1.9+ BasePotionData provider as potion meta provider.
30.06 14:56:00 [Server] INFO Using locale en_GB
30.06 14:56:00 [Server] INFO [Essentials] Starting Metrics. Opt-out using the global PluginMetrics config.
30.06 14:56:00 [Server] INFO [Vault][Economy] Essentials Economy hooked.
30.06 14:56:00 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
30.06 14:56:00 [Server] Startup Done (5.878s)! For help, type "help" or "?"
30.06 14:56:00 [Server] INFO [Vault] Checking for Updates ... 
30.06 14:56:01 [Server] INFO [Vault] No new version available

**Comment by Drumples** [comment]
Thankyou for responding btw! I really appreciate the help :D

**Comment by drtshock** [comment]
> pastebin

**Comment by Drumples** [comment]
<script src="//pastebin.com/embed_js/4mSzABzw"></script>

**Comment by Drumples** [comment]
http://pastebin.com/4mSzABzw

**Comment by SupaHam** [comment]
You need to use [EssentialsXChat](https://ci.drtshock.net/job/EssentialsX/) as well.
