### ISSUE TITLE
Possible to enforce default and maximum time for mute, jail, and temp-ban time?

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#697]
Is it possible to enforce a default and maximum allowed time for mutes, jails, and temp-bans on lesser staff positions so players jailed always have a minimum time they are in there for (so they aren't stuck until someone unjails them) and so the lesser staff position can't set a time longer than wanted allowed? I.e. maximum mute time of 30 minutes

As well as have a bypass permission so higher staff ranks can permanently mute/jail or define any  duration they'd like?

**Comment by drtshock** [comment]
Currently no

**Comment by mibby** [comment]
Perhaps in the future then. Thanks for considering.

**Comment by SupaHam** [comment]
Is there a specific reason you want this feature? I'm thinking, if you cant
trust their judgement, should they really have the power in the first place?

**Comment by mibby** [comment]
@SupaHam Well, it would mainly be for two reasons that I can foresee.

1) To allow enforcing a minimum time so players aren't permanently jailed / muted if forgotten about or if the staff personnel didn't set a time by default.

and 

2) To enforce a maximum time so it can't be abused in the event a typo is made on the duration when entering the command or in the rare event someone abuses their power.
