### ISSUE TITLE
Need to add 'career' type to villagers.

### ISSUE THREAD

**Issue by drtshock** [EssentialsX/Essentials#7]

**Comment by vemacs** [comment]
See https://hub.spigotmc.org/jira/browse/SPIGOT-355

**Comment by SupaHam** [comment]
Can you elaborate?

**Comment by drtshock** [comment]
When spawning them

**Comment by vemacs** [comment]
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Villager.Profession.html

Probably not available in 1.8, might be possible to backport

**Comment by vemacs** [comment]
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/fbdb54a166f6064ea28e5f17d8c774999bc6ee67

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/46327ceda77c04d99fec14dec7a2489aa1c81f13

Never merged.

**Comment by SupaHam** [comment]
We can add support for >1.8 when this was implemented.

**Comment by vemacs** [comment]
There is no current API, we'll need to provide field mappings for all versions.

**Comment by jvdoorn** [comment]
Is this still something that needs to be implemented? Because it looks to me as if it has been implemented:
https://github.com/EssentialsX/Essentials/blob/b555ea6350edfa76e2ce76974f5797cad7ca60fd/Essentials/src/com/earth2me/essentials/MobData.java#L86-L91

**Comment by mdcfe** [comment]
@Argetan EssentialsX doesn't include `Villager.Career` types yet. However, the 1.14 branch now supports these.

**Comment by jvdoorn** [comment]
So that means this issue can be closed right? Since it has been implemented in the `1.14` branch which, I assume, will be merged into `2.x` soon.

**Comment by mdcfe** [comment]
I'll close this when 1.14 support is merged.
