### ISSUE TITLE
Request: Allow specific teleport cooldown bypasses

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#70]
At present the cooldown and timer bypasses are universal, can I please request that these permissions be set via what is needed for the server, So in my case I want to have cooldowns for all teleporting apart from /back I want that to keep the default cooldown and timer to use to stop PVP abuse, but keep it allowed to certain ranks as a perk.
These are the current permissions:

```
    - essentials.teleport.cooldown.bypass
    - essentials.teleport.timer.bypass
```

What I suggest the permissions should allow:

```
    - essentials.teleport.cooldown.bypass.back
    - essentials.teleport.timer.bypass.back
    - essentials.teleport.cooldown.bypass.tpa
    - essentials.teleport.timer.bypass.tpahere
```

There is also a - essentials.back.ondeath Can I make another request for a:

```
    - essentials.back.onplayerdeath
```

The onplayerdeath would be a permission to or not to teleport back to your death location if the death was caused by another player instead of PvE.

**Comment by drtshock** [comment]
Good suggestions. We'll see about getting these implemented in one way or another.

**Comment by vemacs** [comment]
I've partially implemented this with cooldowns. It's default-allow to avoid breaking existing behavior, but you can deny `essentials.teleport.cooldown.bypass.tpa` and `essentials.teleport.cooldown.bypass.back` to force players to go through that cooldown.

**Comment by TomLewis** [comment]
That's awesome @vemacs im exited to put this into use soon!

**Comment by TomLewis** [comment]
Hey @vemacs I tested this out on my server last night, denoting 
-essentials.teleport.cooldown.bypass.back from groups that have essentials.teleport.cooldown.bypass, but it just added a cooldown to all teleporting, its as if the .back was ignored, i presume because this hasn't been built into the builds yet?

**Comment by TomLewis** [comment]
Any Luck on getting this implemented?

**Comment by TomLewis** [comment]
_Bump_

**Comment by pop4959** [comment]
Cool down bypass permissions appear to exist in the latest version, and there is a `command-cooldowns` section in the config. If this is still **not** working on the latest version, please create a new issue as a bug report.
