### ISSUE TITLE
Clear Inventory clearing all items (Armor you're wearing too)

### ISSUE THREAD

**Issue by SlayerMarth** [EssentialsX/Essentials#701]
Like the title says. /ci clears everything. All the items in the inventory, along with the armor and such that you're wearing. I only typed /ci, nothing more.

https://gyazo.com/204d6c2cbdcfbc506d89b62fbbe90e1f

**Comment by SupaHam** [comment]
What does `/ess reload` output? I just need the EssentialsX version you're using.

**Comment by SlayerMarth** [comment]
2.0.1-b354
I downgraded to an older version and /ci worked, then re-upgraded and now it's working oddly.

**Comment by SupaHam** [comment]
Well 354 is designed to work with 1.10. Since the addition of the extra hand slot, the inventory code changed a bit, as such the 1.9+ versions of EssentialsX depend on the hand being present, i.e. Minecraft 1.9+.
