### ISSUE TITLE
God Mode has no effect

### ISSUE THREAD

**Issue by DerSeegler** [EssentialsX/Essentials#704]
Got mode has simply no effect. Typing the command "/god" it says "Invincibility activated" but monsters still do damage to myself. Typing "/god" again supposedly deactivates it again but again with no visible effect.

Running Spigot 1.10.2 (exact version: git-Spigot-a9631d2-67b2424 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT))
and EssentialsX 2.0.1-b368

Startup Log: http://pastebin.com/9xCvj680

**Comment by DerSeegler** [comment]
Also noticed that /afk will not make the player invincible either, even though I set it in the config that they should be.

**Comment by drtshock** [comment]
Uh are you sure you don't have any plugins interfering? Try reproducing this with just essentialsx installed.

**Comment by DerSeegler** [comment]
Problem was caused my another plugin named RandomTP. Without it everything works just fine.
