### ISSUE TITLE
[Feature] /nick command cooldown

### ISSUE THREAD

**Issue by Brend-Smits** [EssentialsX/Essentials#705]
Hello,
Someone on my server suggested to added a cooldown to /nick to prevent abuse. I kinda like his suggestion, this would allow more flexibility for servers that provide the /nick feature for a donation option. It will prevent people abusing the /nick .
The cooldown will prevent players with the /nick permission to perform the command again for the configured amount of time.
To allow even more flexibility a permission node could be added that will add a bypass, this will allow certain ranks/groups to be able to bypass the cooldown feature. 

Config option would look like this

```
----
# This option will add a cooldown to the /nick command
# Default: 15 seconds, 0 seconds will disable the cooldown feature
# To bypass this cooldown you can add the permissions essentials.nick.cooldown.bypass
nick-cooldown: 15 
------
```

**Comment by JonathanBrouwer** [comment]
In this command, an option for command cooldowns in general was added.
You can use this.
https://github.com/drtshock/Essentials/commit/09acbcdb05f34e0043116f1866904b0ff0f03ddd

**Comment by SupaHam** [comment]
https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/config.yml#L487 You can use `command-cooldowns`.

**Comment by Brend-Smits** [comment]
Thanks for the information. My bad.
