### ISSUE TITLE
EssentialsXChat and PermissionsEX Colored Chat

### ISSUE THREAD

**Issue by IcyPhoenix15** [EssentialsX/Essentials#706]
In the area where you do group formats and stuff like that, you can set per group colored chat. I always did it with essentials but that same feature doesn't work with essentialsX. This is driving me insane. I am using Permissionsex and EssentialsX (For spigot 1.8.8). This is bugging me really badly.

**Comment by Koncealed** [comment]
Download Vault

**Comment by SupaHam** [comment]
Please make sure you have both Vault and EssentialsXChat installed, the main EssentialsX plugin does not provide this functionality by itself.

**Comment by IcyPhoenix15** [comment]
I have them already. Here is a link to the picture of all my plugins. (To prove they are installed)
https://gyazo.com/76b462605c5253c7d813b03303bd797d

**Comment by SupaHam** [comment]
Can you pastebin your startup log and config file please?

**Comment by IcyPhoenix15** [comment]
Console: http://pastebin.com/kZQW0d7N
EssentialsX Config: http://pastebin.com/ugDQMtWY
Need Anything Else?

**Comment by IcyPhoenix15** [comment]
I switched to GroupManager and its still broken. This is really pissing me off. Why add a feature to a plugin then abandon half of it or even keep the chat format if its broken. The people that make this plugin need to get their crap together and read these issues.

**Comment by drtshock** [comment]
Don't use groupmanager. It's abandoned. You also don't have any group formatting setup in your essentialschat configuration on line 674 of your config you pasted so I'm not sure how you expect it to work.
