### ISSUE TITLE
permissions list

### ISSUE THREAD

**Issue by reventcake295** [EssentialsX/Essentials#707]
I have been searching for days on the ethernet for a permissions list of this plugin but i can't find it do you now a place where i can find a complete list of it?

**Comment by SupaHam** [comment]
First of all, there's a wiki button at the top. Usually that's a sign of help universally. That's for EssentialsX.

For the original Essentials (which we don't document), check out [mc-ess.net](http://wiki.mc-ess.net/wiki/Command_Reference/Perm)

**Comment by drtshock** [comment]
ethernet
