### ISSUE TITLE
EssentialsXSpawn-2.0.1 - 'Craft Scheduler Thread' Warning

### ISSUE THREAD

**Issue by SamuelMoller** [EssentialsX/Essentials#709]
Craft Scheduler throws out a warning as players join the server.

> [21:29:33] [Server thread/INFO]: DeepDisc0[/83.253.9.106:61161] logged in with entity id 227373 at ([arctus]516.057064603963, 72.37307505008019, 182.35134151179196)
> [21:29:33] [Craft Scheduler Thread - 3590/WARN]: Exception in thread "Craft Scheduler Thread - 3590" 
> [21:29:33] [Craft Scheduler Thread - 3590/WARN]: org.apache.commons.lang.UnhandledException: Plugin Essentials v2.0.1-b348 generated an exception while executing task 598224
>   at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
>   at java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.NoSuchMethodError: com.earth2me.essentials.ISettings.isSpawnOnJoin()Z
>   at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener.delayedJoin(EssentialsSpawnPlayerListener.java:75)
>   at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener$1.run(EssentialsSpawnPlayerListener.java:66)
>   at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
>   at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
>   ... 3 more

**Comment by vemacs** [comment]
Update your EssentialsSpawn to the latest CI build.
