### ISSUE TITLE
BUG Spawner Problem

### ISSUE THREAD

**Issue by justin2001** [EssentialsX/Essentials#71]
After I buy a spawner with essentials signs, and I put the spawner to another hotbar, and place the spawner, the spawner is gone! If I didn't change the spawner to another hotbar, it won't have this problem. Please fix this as soon a possible. It's so important.

**Comment by vemacs** [comment]
I'm not sure what you mean, I have no issues with dragging spawners between inventories. The spawners we deliver are technically equivalent to the vanilla ones.

**Comment by Kakifrucht** [comment]
Me neither.

**Comment by vemacs** [comment]
Can't repro at all, plus this shouldn't happen since our spawners are identical. Check your other plugins.

**Comment by justin2001** [comment]
Here is the proof:
https://www.youtube.com/watch?v=OL6FndS9yaw

**Comment by Terrobility** [comment]
By any chance, do you have SilkSpawners? I used to have the same problem but it stopped after updating it.

**Comment by vemacs** [comment]
I can't reproduce without SilkSpawners, and can't reproduce with latest SilkSpawners. This is not our problem.

**Comment by justin2001** [comment]
Means I have to update my silk spawners to the latest version?

**Comment by vemacs** [comment]
Yeah, or remove it altogether...?

You should also update Spigot as well...?

**Comment by justin2001** [comment]
Means I have to upgrade silk spawners to the latest version and spigot to the latest version of 1.8.7 to make the spawners work?

**Comment by drtshock** [comment]
omg you have to update something to work with newer builds? omgwow
