### ISSUE TITLE
Essentials economy bug.

### ISSUE THREAD

**Issue by AkarCraft** [EssentialsX/Essentials#710]
Hi, I have a non premium server.

I will give an example of my problem.

If I join a one server with the nick: MiguelFierro but more later I join with the nick: MiguelFierrO my economy will be bug and I'll have infinite money.

I hope that you can solve this.

Thanks!

**Comment by vemacs** [comment]
Don't run a cracked server. It's not supported and never will be.

**Comment by AkarCraft** [comment]
...

**Comment by drtshock** [comment]
seriously
