### ISSUE TITLE
Signs aren't working

### ISSUE THREAD

**Issue by Aslaak** [EssentialsX/Essentials#711]
Hello,

I have a problem with all signs, when I place them they are reset and don't show anything, so I can't do signs like [Buy], [Sell], etc...

I'm using the last version ( 2.0.1 - b354 ) and my server is running spigot 1.10.2 - R0.1

An idea for solve this problem ? :(
Thank !
ps: sorry for my english

**Comment by drtshock** [comment]
Did you enable them in the config...?

**Comment by SupaHam** [comment]
This is most likely a duplicate of #687. Please update spigot.
