### ISSUE TITLE
[Request] /showkit to be a GUI

### ISSUE THREAD

**Issue by GiansCode** [EssentialsX/Essentials#712]
Hi there,

I have request for something I'd like to see added to EssX. The command /showkit currently brings up the kit contents in a message and is a bit iffy. It'd be nice if it became a GUI showing the item exactly how it's made in the config (name, enchants, etc),

Thanks

**Comment by GiansCode** [comment]
Sorry for the bump. Any updates?

**Comment by wardpieters** [comment]
I think it is a really Nice idea that you then see the kit inside a chest. Same as /enderchest but now with kit tools for example

**Comment by arklanq** [comment]
Will be this feature added?
I am also interested in using this.

**Comment by triagonal** [comment]
Closing for reasons discussed in #292.
