### ISSUE TITLE
AutoUpdate config option

### ISSUE THREAD

**Issue by RikoDEV** [EssentialsX/Essentials#713]
I would ask to add automatic update feature config.yml, because after adding a new feature you have to fumble in the config, and append or delete ruler. Thanks.

**Comment by SupaHam** [comment]
I don't think you should expect this any time soon as there's nothing planned and as far as I can see, it would require a good amount of effort.

**Comment by RikoDEV** [comment]
Yes, but this option will certainly come in handy

**Comment by SupaHam** [comment]
I can see why you would think that, but in reality if someone is updating, they should be aware of the updates (reading changelogs).

**Comment by drtshock** [comment]
That + it'd delete comments in the config.yml without some super duper magic.
