### ISSUE TITLE
SOME BUGS

### ISSUE THREAD

**Issue by RAZERMC** [EssentialsX/Essentials#714]
Using spigot 1.10 latest build tools on java 8
using latest essentials for 1.9
Players can use repair signs ignoring the players balance. 
Player with essentials.silentleave still informs the server when leaving 
even with enable in config

**Comment by SupaHam** [comment]
Please never say latest version, that's almost never useful. Please provide the whole startup log and Essentials config.

**Comment by RAZERMC** [comment]
Essentials v2.0.1-b370
git-Spigot-c3e4052-1953f52 (MC: 1.10) (Implementing API version 1.10-R0.1-SNAPSHOT)
http://pastebin.com/63gv6GA9

**Comment by RAZERMC** [comment]
# 
# +------------------------------------------------------+ #
# |                       Notes                          | #
# +------------------------------------------------------+ #
ops-name-color: none
nickname-prefix: '~'
max-nick-length: 15
change-displayname: true
teleport-safety: true
teleport-cooldown: 5
teleport-delay: 5
teleport-invulnerability: 4
heal-cooldown: 60
permission-based-item-spawn: false
spawnmob-limit: 10
warn-on-smite: true
socialspy-commands:
- msg
- w
- r
- mail
- m
- t
- whisper
- emsg
- tell
- er
- reply
- ereply
- email
- action
- describe
- eme
- eaction
- edescribe
- etell
- ewhisper
- pm
player-commands:
- afk
- afk.auto
- back
- back.ondeath
- balance
- balance.others
- balancetop
- build
- chat.color
- chat.format
- chat.shout
- chat.question
- clearinventory
- compass
- depth
- delhome
- getpos
- geoip.show
- home
- home.others
- ignore
- info
- itemdb
- kit
- kits.tools
- list
- mail
- mail.send
- me
- motd
- msg
- msg.color
- nick
- near
- pay
- ping
- protect
- r
- rules
- realname
- seen
- sell
- sethome
- setxmpp
- signs.create.protection
- signs.create.trade
- signs.break.protection
- signs.break.trade
- signs.use.balance
- signs.use.buy
- signs.use.disposal
- signs.use.enchant
- signs.use.free
- signs.use.gamemode
- signs.use.heal
- signs.use.info
- signs.use.kit
- signs.use.mail
- signs.use.protection
- signs.use.repair
- signs.use.sell
- signs.use.time
- signs.use.trade
- signs.use.warp
- signs.use.weather
- spawn
- suicide
- time
- tpa
- tpaccept
- tpahere
- tpdeny
- warp
- warp.list
- world
- worth
- xmpp
kits:
  STARTER:
    delay: 600
    items:
    - 268 1 durability:10
    - 298 1 durability:10
    - 299 1 durability:10
    - 300 1 durability:10
    - 301 1 durability:10
  leatherset:
    delay: 2700
    items:
    - 268 1 sharpness:3 name:&4TYPE_A_&6SWORD
    - 298 1 color:0,0,255 durability:5 protect:2 name:&bBATTLEKIT_&4TYPE_A
    - 299 1 color:0,0,255 durability:5 protect:2 name:&bBATTLEKIT_&4TYPE_A
    - 300 1 color:0,0,255 durability:5 protect:2 name:&bBATTLEKIT_&4TYPE_A
    - 301 1 color:0,0,255 durability:5 protect:2 name:&bBATTLEKIT_&4TYPE_A
    - 261 1 name:&4TYPE_A_&bBOW
    - 262 10
  ironset:
    delay: 5400
    items:
    - 267 1 sharpness:4 name:&1TYPE_B_SWORD
    - 306 1 durability:1 protect:3 blastprot:1 name:&bBATTLEKIT_&4TYPE_B
    - 307 1 durability:1 protect:3 blastprot:1 name:&bBATTLEKIT_&4TYPE_B
    - 308 1 durability:1 protect:3 blastprot:1 name:&bBATTLEKIT_&4TYPE_B
    - 309 1 durability:1 protect:3 blastprot:1 name:&bBATTLEKIT_&4TYPE_B
    - 261 1 punch:1 name:&4TYPE_B_&bBOW
    - 262 10
  goldset:
    delay: 10800
    items:
    - 283 1 sharpness:5 name:&6TYPE_C_SWORD
    - 314 1 durability:1 protect:4 blastprot:2 projprot:1 name:&6BATTLEKIT_&4TYPE_C
    - 315 1 durability:1 protect:4 blastprot:2 projprot:1 name:&6BATTLEKIT_&4TYPE_C
    - 316 1 durability:1 protect:4 blastprot:2 projprot:1 name:&6BATTLEKIT_&4TYPE_C
    - 317 1 durability:1 protect:4 blastprot:2 projprot:1 name:&6BATTLEKIT_&4TYPE_C
    - 261 1 flame:1 name:&4TYPE_C_&bBOW
    - 262 20
  diamondset:
    delay: 21600
    items:
    - 276 1 sharpness:5 knockback:1 name:&5TYPE_D_SWORD
    - 310 1 durability:1 protect:5 blastprot:2 projprot:1 name:BATTLEKIT_&4TYPE_D
    - 311 1 durability:1 protect:5 blastprot:2 projprot:1 name:BATTLEKIT_&4TYPE_D
    - 312 1 durability:1 protect:5 blastprot:2 projprot:1 name:BATTLEKIT_&4TYPE_D
    - 313 1 durability:1 protect:5 blastprot:2 projprot:1 name:BATTLEKIT_&4TYPE_D
    - 261 1 flame:2 power:2 name:&4TYPE_D_&bBOW
  chainset:
    delay: 21600
    items:
    - 276 1 sharpness:5 knockback:1 name:&5TYPE_D_SWORD
    - 302 1 durability:1 protect:5 blastprot:2 projprot:1 name:BATTLEKIT_&4TYPE_D
    - 303 1 durability:1 protect:5 blastprot:2 projprot:1 name:BATTLEKIT_&4TYPE_D
    - 304 1 durability:1 protect:5 blastprot:2 projprot:1 name:BATTLEKIT_&4TYPE_D
    - 305 1 durability:1 protect:5 blastprot:2 projprot:1 name:BATTLEKIT_&4TYPE_D
    - 261 1 flame:2 power:2 name:&4TYPE_D_&bBOW
  TOOLS:
    delay: 600
    items:
    - 291 1
    - 273 1
    - 274 1
    - 275 1
  FOOD:
    delay: 600
    items:
    - steak 10
enabledSigns:
- color
- balance
- buy
- sell
- trade
- free
- disposal
- warp
- kit
- mail
- enchant
- gamemode
- heal
- info
- spawnmob
- repair
- time
- weather
sign-use-per-second: 2
backup:
  interval: 30
per-warp-permission: true
list:
  Admins: owner admin
debug: false
locale: custom
remove-god-on-disconnect: true
auto-afk: 300
auto-afk-kick: -1
freeze-afk-players: false
disable-item-pickup-while-afk: false
cancel-afk-on-interact: true
cancel-afk-on-move: true
death-messages: true
allow-silent-join-quit: true
custom-join-message: none
custom-quit-message: none
world-teleport-permissions: false
default-stack-size: -1
oversized-stacksize: 64
repair-enchanted: false
unsafe-enchantments: true
register-back-in-listener: false
login-attack-delay: 5
max-fly-speed: 0.8
max-walk-speed: 0.8
mails-per-minute: 1000
max-tempban-time: -1
update-bed-at-daytime: true
world-home-permissions: false
sethome-multiple:
  default: 1
  vip: 5
  staff: 10
tpa-accept-cancellation: 120
starting-balance: 1000
currency-symbol: $
max-money: 10000000
min-money: 0
economy-log-enabled: true
non-ess-in-help: true
hide-permissionless-help: true
chat:
  radius: -1
  group-formats:
    PRIVATE: '&2[&6{factions_name|rp}&2]&r{DISPLAYNAME}&7:&r {MESSAGE}'
    LEIUTENANT: '&2[&6{factions_name|rp}&2]&r{DISPLAYNAME}&7:&r {MESSAGE}'
    CAPTAIN: '&2[&6{factions_name|rp}&2]&r{DISPLAYNAME}&7:&r {MESSAGE}'
    DONATOR: '&2[&6{factions_name|rp}&2]&r{DISPLAYNAME}&7:&r {MESSAGE}'
    OWNER: '&r{DISPLAYNAME}&7: &d{MESSAGE}'
protect:
  prevent:
    lava-flow: false
    water-flow: false
    water-bucket-flow: false
    fire-spread: true
    lava-fire-spread: true
    flint-fire: false
    lightning-fire-spread: true
    portal-creation: false
    tnt-explosion: false
    tnt-playerdamage: false
    tnt-minecart-explosion: false
    tnt-minecart-playerdamage: false
    fireball-explosion: false
    fireball-fire: false
    fireball-playerdamage: false
    witherskull-explosion: false
    witherskull-playerdamage: false
    wither-spawnexplosion: false
    wither-blockreplace: false
    creeper-explosion: false
    creeper-playerdamage: false
    creeper-blockdamage: false
    enderdragon-blockdamage: true
    enderman-pickup: false
    villager-death: false
    entitytarget: false
    spawn:
      creeper: false
      skeleton: false
      spider: false
      giant: false
      zombie: false
      slime: false
      ghast: false
      pig_zombie: false
      enderman: false
      cave_spider: false
      silverfish: false
      blaze: false
      magma_cube: false
      ender_dragon: false
      pig: false
      sheep: false
      cow: false
      chicken: false
      squid: false
      wolf: false
      mushroom_cow: false
      snowman: false
      ocelot: false
      iron_golem: false
      villager: false
      wither: false
      bat: false
      witch: false
      horse: false
  creeper:
    max-height: -1
  disable:
    fall: false
    pvp: false
    drown: false
    suffocate: false
    lavadmg: false
    projectiles: false
    contactdmg: false
    firedmg: false
    lightning: false
    wither: false
    weather:
      storm: false
      thunder: false
      lightning: false
    build: true
    use: true
    warn-on-build-disallow: true
  alert:
    on-placement: 10,11,46,327
    on-use: 327
  blacklist:
    placement: 10,11,46,327
    usage: 327
newbies:
  announce-format: ''
  spawnpoint: none
  kit: STARTER
respawn-listener-priority: lowest
respawn-at-home: false

**Comment by SupaHam** [comment]
Whenever someone asks you to provide information that spans over a dozen lines, you should use a pastebin such as http://pastebin.com. I've done that for you and edited your comment.

I asked for your startup log as well.

**Comment by SupaHam** [comment]
I just realised you said `essentials.silentleave`. The permission you want is actually `essentials.silentquit`.

**Comment by RAZERMC** [comment]
yep same result with essentials.silentquit.

**Comment by SupaHam** [comment]
I just tested it. If I have `essentials.silentquit` and the config specifies `allow-silent-join-quit: true` it works.

**Comment by RAZERMC** [comment]
what spigot version do you use?

**Comment by SupaHam** [comment]
`git-Spigot-5391d73-00359a1` (1.10.2)

**Comment by RAZERMC** [comment]
i use spigot for 1.10 on java 8 well if it does not work for me then its ok i just disable the features that dont work thanks again
