### ISSUE TITLE
Spamming bug

### ISSUE THREAD

**Issue by airoons** [EssentialsX/Essentials#715]
Hello!

It seems like, that this bug (idk if it is) has happened before to other users. Basically, I have command block in one world. It just clears every player inventory in certain raduis. But the problem is - it spams console with messages similar to this:

06.07 07:46:24 [Server] INFO CommandBlock at 79,128,235 issued server command: /clear vugu3100

I have already disabled logAdminCommands and CommandBlockOutput in all worlds, even typed that in console. In spigot.yml I disabled commandblock output to console, basically, I did everything, but this still happens.

I think, that essentials might be the "problem", but I'm not shure... Please help!

I'm using spigot 1.8.8 (Spigot-e4d4710-e1ebe52)
Essentials version: 2.0.1-b361

**Comment by SupaHam** [comment]
It's not a bug. It is just informing the console that a command block is executing an essentials command.

@drtshock @vemacs thoughts on making this a configurable feature, where output is on by default?

**Comment by drtshock** [comment]
Sounds more like something he could filter out with his log4j configuration.

**Comment by TheIronMinerLv** [comment]
How could I do that?

**Comment by airoons** [comment]
Fixed this, I disabled /clear command in essentials config, but it seems like, that that wasn't enough - now I deleted /clear even from plugin.yml in essentialsx.jar, then that message dissapeared.

**Comment by SupaHam** [comment]
No... that is not a fix. That is a terrible hack. If you want to use minecraft's clear you can use `/minecraft:clear`, if it's from another plugin you can use `/pluginname:clear`.

![](https://media.giphy.com/media/SEp6Zq6ZkzUNW/giphy.gif)

**Comment by airoons** [comment]
That would work too, I guess
