### ISSUE TITLE
[Request] Add config option for NPCs in /baltop

### ISSUE THREAD

**Issue by Yamakaja** [EssentialsX/Essentials#716]
The title sais it all ...

**Comment by drtshock** [comment]
Thanks for making this :)

@SupaHam thoughts?

**Comment by SupaHam** [comment]
This has been fixed in 992ef5d. You can grab the fix from [build 371](https://ci.drtshock.net/job/EssentialsX/) on the CI server.

**Comment by drtshock** [comment]
That was fast ;)

**Comment by SupaHam** [comment]
@drtshock pls review https://github.com/drtshock/Essentials/pull/665 :)

**Comment by Yamakaja** [comment]
Whoa, awesome
