### ISSUE TITLE
Home others command not working

### ISSUE THREAD

**Issue by DynamiteDez** [EssentialsX/Essentials#718]
Running the latest Spigot and Essentials X, however the command for listing other players homes does nothing and the same for teleporting.

No errors or in-game information are displayed unfortunately.

**Comment by vemacs** [comment]
Pastebin your startup log (including what happens when you run that command) and permissions plugin config, please

**Comment by DynamiteDez** [comment]
Turns out re-adding the permissions fixed this, even though both the group and user had access originally. Thanks for sending me in the right direction!
