### ISSUE TITLE
Problems in Chat Formattings

### ISSUE THREAD

**Issue by nichslos** [EssentialsX/Essentials#720]
Running latest Spigot, but i have latest plugin PermissionEx, Vault, EssentialsX, EssentialsXChat.
I'ved try this formatting codes but not working.

List of working:
- &1 to &9
- &e
- &a
- &b
- &f

Not working:
- &l
- &n
- &o
- &k but turns to Bold
- &m
- &r

This is would be nice if you fixed this

**Comment by SupaHam** [comment]
Please paste your entire config.yml.

**Comment by nichslos** [comment]
http://pastebin.com/Edmn35zN

**Comment by nichslos** [comment]
I have the Donators ranks and i'ved setup to pex then, the prefix is &f[&a&k::&4&lDonator&a&k::&f]
The &k format turns to bold and it won't magic

**Comment by pop4959** [comment]
This is an extremely late answer, so I don't know if this is useful to you anymore, but there is a chat format permission which you must set for those to work properly. Config does not affect it.
