### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#725]
Hi ive had essentials X for about a month now and kept getting these errors i ouldnt find help on any forums and have now proceeded to here here are the 2/3 errors 

1: This error pops up when I'm joining the server

10.07 01:22:33 [Server] WARN Exception in thread "Craft Scheduler Thread - 694" 
10.07 01:22:33 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Essentials v2.0.1-b354 generated an exception while executing task 13741
10.07 01:22:33 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
10.07 01:22:33 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
10.07 01:22:33 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
10.07 01:22:33 [Server] INFO at java.lang.Thread.run(Unknown Source)
10.07 01:22:33 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.earth2me.essentials.ISettings.isSpawnOnJoin()Z
10.07 01:22:33 [Server] INFO at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener.delayedJoin(EssentialsSpawnPlayerListener.java:75)
10.07 01:22:33 [Server] INFO at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener$1.run(EssentialsSpawnPlayerListener.java:66)
10.07 01:22:33 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
10.07 01:22:33 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
10.07 01:22:33 [Server] INFO ... 3 more

2: This error pops up when I'm starting the server
10.07 02:27:53 [Server] WARN Version mismatch! Please update all Essentials jars to the same version.

3: This error pops up when I'm starting the server
10.07 02:28:21 [Server] WARN Version mismatch! Please update EssentialsChat to the same version.
10.07 02:28:21 [Server] WARN Version mismatch! Please update EssentialsSpawn to the same version.

**Comment by FlippantCactus** [comment]
10.07 02:27:53 [Server] WARN Version mismatch! Please update all Essentials jars to the same version.
This means update them all rather than just the main jar
You're also very out of date with versions so I'd consider updating the main jar too.

**Comment by ghost** [comment]
> 10.07 02:27:53 [Server] WARN Version mismatch! Please update all Essentials jars to the same version.
> This means update them all rather than just the main jar
> You're also very out of date with versions so I'd consider updating the main jar too.

 Now what about the top error? and how could i solve it?

**Comment by vemacs** [comment]
All of them are related to outdated JARs.
