### ISSUE TITLE
Different Versions of essentials

### ISSUE THREAD

**Issue by mcredragon** [EssentialsX/Essentials#727]
I am running a minecraft bukkit 1.10 server, and scrolling along, i found this error in my cmd prompt: [(http://pastebin.com/vDCcuSJA)] Can you update essentials x to 392

**Comment by SupaHam** [comment]
Whenever there's a version for another EssentialsX plugin, there's always one for the main EssentialsX  plugin itself. You can find the latest EssentialsX builds including 392 on the [CI server](https://ci.drtshock.net/job/EssentialsX/).
