### ISSUE TITLE
EssentialsX 1.7/1.8

### ISSUE THREAD

**Issue by dannylif** [EssentialsX/Essentials#73]

**Comment by vemacs** [comment]
Due to the guava version bump in Spigot 1.8, plus the fact that our fixes are mostly irrelevant for 1.7, plus the fact that 1.7 is not a supported server platform, we don't plan to support 1.7.

**Comment by dannylif** [comment]
Is there anything similair to this for that works for 1,7/1.8

**Comment by PsychoNavigator** [comment]
For 1.7?

Essentials. http://wiki.ess3.net/wiki/Main_Page
