### ISSUE TITLE
[Feature] {UNIQUE} placeholder with commas.

### ISSUE THREAD

**Issue by voodootje0** [EssentialsX/Essentials#730]
Could you add commas to {UNIQUE}.
https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java#L256

Now it returns 2355149, it will be nice if it returns 2,355,149

**Comment by SupaHam** [comment]
This has been fixed in 535fb43. You can grab the fix from [build 397](https://ci.drtshock.net/job/EssentialsX/) on the CI server.

**Comment by voodootje0** [comment]
Woops, I've told you the wrong replace location.
https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/textreader/KeywordReplacer.java#L146

That must be the good one,

**Comment by voodootje0** [comment]
@SupaHam ^^

**Comment by SupaHam** [comment]
This has been fixed in e0d69d05. You can grab the fix from [build 402](https://ci.drtshock.net/job/EssentialsX/) on the CI server.
