### ISSUE TITLE
[Request] Ability to delete kits in-game

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#731]
Hey.

I'm staff on a server that gives players the ability to create their own "player server," and they don't have access to the console/config files. I was wondering if it would be possible to create a function to delete kits in-game. 

For example:
- **/delkit kitName**

This feature would be a great help  so we don't have people complaining about deleting their "test kits." 
_(If it is already a feature please ignore this as I can't find a way to remove kits.)_

**Comment by drtshock** [comment]
no because then we'll get complains about people using it and having it delete all the comments in their config. I know it wouldn't matter in your case, but that's what would happen if added. It wouldn't be difficult for you to add this yourself in your own fork :)

**Comment by drtshock** [comment]
Also, I'm curious which server this is? I'm only aware of https://minehut.com/ that allows something like this :)

**Comment by fieu** [comment]
@drtshock If I may ask, why does it delete all the comments in your config when you run `/createkit` ?

**Comment by ghost** [comment]
@drtshock, that's the one. :+1: I saw you tweet @ us on twitter :)

**Comment by Kakifrucht** [comment]
@NurdTurd because that's what the YAML API does when adding new keys/values programmatically.
This can be fixed but not easily and is not worth the hassle.

**Comment by SupaHam** [comment]
@NurdTurd We're currently working on a fix for this problem as we speak.

**Comment by drtshock** [comment]
@SupaHam the new way will actually break their current setup. RIP

**Comment by lukechatton** [comment]
RIP. Time to fork it up I guess. Unbelievable that we aren't prioritized over the other 15k servers that use Essentials /s

**Comment by drtshock** [comment]
ikr rip

But there's a new config option for you guys <3

**Comment by triagonal** [comment]
This was implemented in b97eb12, and then improved on in #2908. The `/delkit` command and improvements are present in EssentialsX versions `2.17.1.47` and above.
