### ISSUE TITLE
[Request] Permission node for ignore-colors-in-max-nick-length

### ISSUE THREAD

**Issue by MinecraftAdmin** [EssentialsX/Essentials#733]
Hello. Please consider adding a permission node that allows anyone with the node to be able to set their nickname to the length ignoring formatting tags.

**Comment by MinecraftAdmin** [comment]
Also I apologize for not knowing this but how does one set the "enhancement" flag?

**Comment by SupaHam** [comment]
Are you aware of the `ignore-colors-in-max-nick-length` option in config.yml?

**Comment by MinecraftAdmin** [comment]
Yes, is there a permission node for it though? My guess is that the option **ignore-colors-in-max-nick-length** enables it for everyone who has the _essentials.nick_ and _essentials.nick.color_ permissions.

A permission node will allow people with the node to have more colors in their nicknames, for example staff members and donators.

**Comment by SupaHam** [comment]
I'll look into it.

**Comment by pop4959** [comment]
Too specific / niche. There's really no reason why you can't just turn the setting on/off for all players. You're likely overthinking it. Not a necessary addition for Essentials.
