### ISSUE TITLE
Weird Symbol

### ISSUE THREAD

**Issue by SlenderBird** [EssentialsX/Essentials#734]
This weird symbol appears when the balance of anyone is 1000 or above.
![5dde2e2f4087490b8ed17497b7d19d42](https://cloud.githubusercontent.com/assets/20443119/16810817/33a0b210-492e-11e6-9cd0-e72a361c78e3.png)

**Comment by vemacs** [comment]
That doesn't seem like the stock color scheme. It's an issue with your particular locale file.
