### ISSUE TITLE
Small Fix

### ISSUE THREAD

**Issue by justin2001** [EssentialsX/Essentials#74]
When i buy a pig spawner, and i place it, it says placing default spawner and say that something is broken. @drtshock Can you fix that because i dont want my players to see that. You can change to pig spawner placed and pig spawner broken.

**Comment by vemacs** [comment]
**Update SilkSpawners. Update Spigot. Update EssentialsX. Nobody else can reproduce this with the latest versions of all software.**

**Comment by justin2001** [comment]
No this is different problem. Only small fixes on pig spawner. When you buy it, it will say placing default spawner and something is broken. I dont want players to see that. Just fix that. Thanks.

**Comment by justin2001** [comment]
@vemacs Please fix this, only pig spawner have the problem I stated above.

**Comment by vemacs** [comment]
That isn't our message, that message is on SilkSpawners' side.

**Comment by justin2001** [comment]
No, @drtshock already fix that problem on all the spawners except for the pig one. If you buy and place a zombie spawner, it will say zombie spawner placed. Other spawner also gives this message but if you buy and place a pig spawner, it will say placinv default spawner and something is broken. I dont want my players to see this. Please fix it.

**Comment by vemacs** [comment]
How are you spawning the pig spawner? What SilkSpawners version? What Spigot version? Please screenshot the sign.

**Comment by justin2001** [comment]
The version does not matter. @drtshock only didn't fix the pig spawner. Try buying a pig spawner with essentials sign and place it, it will say placing default spawner...... something like that. Even though the spawner don't have problem, I don't want player to see that message. Just that small problem. Thanks you!

**Comment by vemacs** [comment]
WE NEED TO SEE THE SIGN. WE NEED TO SEE THE SIGN. WE NEED TO SEE THE SIGN. WE NEED TO SEE THE SIGN. WE NEED TO SEE THE SIGN. WE NEED TO SEE THE SIGN. WE NEED TO SEE THE SIGN.

**Comment by Agazed** [comment]
This is the EssentialsX bug page. Not SilkSpawners.

**Comment by justin2001** [comment]
[Buy]
1
52:90
$250000

**Comment by Kakifrucht** [comment]
I saw the sign! And it opened up my hear... wait..

**Comment by Agazed** [comment]
@drtshock please close and limit this -_-

**Comment by justin2001** [comment]
I will make a video and show you guys this Saturday.

**Comment by justin2001** [comment]
Sorry so much. The latest essentialsX fixed this.
