### ISSUE TITLE
Colored Item Titles not working

### ISSUE THREAD

**Issue by malonnnn** [EssentialsX/Essentials#742]
So I was using commands like the following in commandblocks on my server:

> /give @p "minecraft:iron_sword 1 0 {ench:[{id:16,lvl:10}],display:{Name:§4D§0ea§4dP§0oo§4l's Katana}}"

And the name used to be colored using § characters as you can see above.

But as of recent, the item names once in your hand look like:

http://i.imgur.com/jeSJdFC.png

using latest EssentialsX (build 403) and spigot

> ver
> [04:35:57 INFO]: This server is running CraftBukkit version git-Spigot-078e2f8-7f9fbe5 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
> [04:35:57 INFO]: Checking version, please wait...
> [04:35:58 INFO]: You are running the latest version

I think this is an essentialsX error, because default spigot is unable to produce custom color names by itself, and it used to work for me.

Thank you!

**Comment by drtshock** [comment]
Use /minecraft:give

**Comment by malonnnn** [comment]
Even with minecraft:give the item name still isnt' colored.

I don't believe spigot by itself can create colored item names.

But a week ago I was using colored item names with just the /give command in commandblocks.

It stopped working this past week, so my deduction seemed to point to essentialsx. If I'm wrong, I apologize.

**Comment by malonnnn** [comment]
Why was this closed?

**Comment by fieu** [comment]
@malonnnn As far as I'm concerned, it was an error on your part.

**Comment by malonnnn** [comment]
I'm getting conflicting messages, I went to  the spigot forums and asked the best way to make colored items and I was recommended to get Essentials and EssentialsChat.

So are they wrong? Does Essentials not support colored items names?

**Comment by Kakifrucht** [comment]
See [the Wiki](http://ess.khhq.net/wiki/Item_Meta) to learn how to spawn colored items.

Example: `/give player dirt 1 name:&6Hi_&2this_&3is_&1multicolored`

**Comment by malonnnn** [comment]
@Kakifrucht 

Thank you, I'm attempting this method now, but I'm running into some issues

> /give @p "minecraft:fishing_rod 1 0 {ench:[{id:61,lvl:32767},{id:62,lvl:8}],display:{Name:§eA§6qua§2man's Perfect Fishing Rod}}"
> /give @p "minecraft:leather_helmet 1 0 {ench:[{id:5,lvl:50},{id:6,lvl:1},{id:8,lvl:3}],display:{color:13291780},display:{Name:§eA§6qua§2man's Public §9Water Helmet}}"
> 
> /give @p "minecraft:fishing_rod 1 luckofthesea:32767 lure:8 name:&eA&6qua&2man's_Perfect_Fishing_Rod"
> /give @p "minecraft:leather_helmet 1 respiration:50 aquaaffinity:1 depthstrider:3 name:&eA&6qua&2man's_Public_&9Water_Helmet"

I'm trying to convert the top one to the bottom one, do you see anything wrong? The issue I am getting is that the converted water helmet is not spawning at all and the fishing rod has lure 3 for some reason, and is lacking the other two enchantments.

**Comment by Kakifrucht** [comment]
You would need to set `unsafe-enchantments` to true in your config.yml.
Also:
- Remove the `"` from the command
- No need to prefix item names with `minecraft:`.
- You can keep the enchantment id's if you wish (`61:32767`)

Poor Github user @p getting spammed with your tags :cry:

**Comment by malonnnn** [comment]
@Kakifrucht 

Sorry, @p! I won;t use your name anymore!

I'm still having trouble;

> /give player 346 1 61:32767 62:8 name:&eA&6qua&2mans_Perfect_Fishing_Rod
> /give player() 298 1 5:50 6:1 8:3 name:&eA&6qua&2mans_Public_&9Water_Helmet

The helmet still doesn't spawn.
The error:

> [17:55:40] There is no such item with name minecraft:298

Also, I can't allow unsafe enchantments in the config because a certain group is allowed the /enchant command. I only want to be able to spawn OP weapons with a commandblock. How can I do that?

**Comment by Kakifrucht** [comment]
You can allow it, just don't hand out the permission `essentials.enchantments.allowunsafe`.
The command you provided is fine, are you sure that you removed the `minecraft:` prefix? Otherwise the error message doesn't make any sense.

**Comment by malonnnn** [comment]
@Kakifrucht 

I copied and pasted directly from the commandblock right to here. I can make a twitch video proving it. I promise you that's the error.

EDIT:

Here's another direct copy/paste from the commandblock (i changed @ p to player)

/give player 298 1 5:50 6:1 8:3 name:&eA&6qua&2mans_Public_&9Water_Helmet

**Comment by Kakifrucht** [comment]
Works perfectly fine on my end, I copied your command into a commandblock.

![helmet](https://i.imgur.com/GuF2BDB.jpg)

**Comment by malonnnn** [comment]
@Kakifrucht 

Thank you, I've got it sorted out now. Your help is very appreciated.

**Comment by malonnnn** [comment]
@Kakifrucht 

Sorry but another one, I can't find documentation on how to spawn the following item, how can I spawn a specific shield pattern with a custom name?

> /give player minecraft:shield 1 0 {BlockEntityTag:{Base:14,Patterns:[{Pattern:gra,Color:11},{Pattern:gru,Color:1},{Pattern:tt,Color:11},{Pattern:cbo,Color:0},{Pattern:tt,Color:0},{Pattern:moj,Color:0},{Pattern:mc,Color:0},{Pattern:bo,Color:0}]},display:{Name:§4§lAr§0§le§4§ls's §4Shield}}

**Comment by Kakifrucht** [comment]
I don't think that is possible. You can [spawn preset banners](https://github.com/drtshock/Essentials/wiki/BannerMeta) though.

**Comment by malonnnn** [comment]
@Kakifrucht 

Shit. Can I add this as a feature request?

**Comment by malonnnn** [comment]
@Kakifrucht 

I don't understand how to convert the colors of the banners. For example:

Base:14
{Pattern:tt,Color:11}

Means Top Triangle, but what color is "11"? If I were to convert it to essentials syntax, it would look like

BANNER:13 1 basecolor:??? TOP_TRIANGLE:???

I don't know what to use in place of "11", since I don't know what RGB color "11" is
