### ISSUE TITLE
[Fix] [High Prioity] Teleport glitch

### ISSUE THREAD

**Issue by voodootje0** [EssentialsX/Essentials#743]
There is a new teleport glitch, youtube video: 
https://www.youtube.com/watch?v=vwv41lCnZsQ

Text explain:
"I mined under a faction claimed base, while flying upwards, after repeating it for some times 3-5 minutes, my head gets stuck in the block and i start suffocating, then I can tpa a player to me, or warp to somewhere and do /back, and it'll tpa me to nearest safe location, instead of the block I was stuck in."

**Comment by Kakifrucht** [comment]
That video doesn't explain much.
Please write a proper ticket.

**Comment by voodootje0** [comment]
@Kakifrucht added text explain

**Comment by Kakifrucht** [comment]
So this is with `force-disable-teleport-safety: true`?

**Comment by voodootje0** [comment]
teleport-safety and force-disable-teleport-safety are on true since the start of the server.

**Comment by voodootje0** [comment]
@SupaHam @drtshock High Priority =)

**Comment by SupaHam** [comment]
I'm busy atm, i'll have to take a look later.

**Comment by voodootje0** [comment]
@SupaHam bump

**Comment by SupaHam** [comment]
@voodootje0 Since `teleport-safety` and `force-disable-teleport-safety` are ON, this means Essentials will not provide safe teleports.

If you do not want these reports to be produced by your players, you **MUST** advise your players to create safer spawn points. It's as simple as that.

**Comment by voodootje0** [comment]
@SupaHam Why I could ask me players to create safer points if they are trying to glitch into bases of other players. This is really important. Just watch the video and read the explaining again.

**Comment by SupaHam** [comment]
Then they tell the other players to fix their spawn points? Otherwise, enable teleportation safety in your config.
