### ISSUE TITLE
[Feature Request] Allow spawning of custom shields with colored names

### ISSUE THREAD

**Issue by malonnnn** [EssentialsX/Essentials#744]
> give player minecraft:banner 1 basecolor:14188339 GRADIENT:15066419 GRADIENT_UP:10040115 TRIANGLE_TOP:15066419 CURLY_BORDER:1644825 TRIANGLE_TOP:1644825 MOJANG:1644825 CIRCLE_MIDDLE:1644825 BORDER:1644825 name:&4&lAr&0&le&4&ls's_&4Shield

The above command woks fine until you switch minecraft:banner with minecraft:shield, then it just gives you a blank shield.

Can this be added for shields?

**Comment by malonnnn** [comment]
Shit, close this request.

I figured out how to use banner meta on shields, it's just not very intuitive at all.

Thanks!

**Comment by fieu** [comment]
👍

**Comment by mdcfe** [comment]
Does this work now? I wasn't aware that this was fixed.

**Comment by malonnnn** [comment]
idk, I figured out how to spawn them in vanilla instead, so i closed all my open issues that weren't being addressed
