### ISSUE TITLE
[Request] Y-Offset on teleport to fix teleport lag.

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#747]
When you teleport around, due to teleportation lag you teleport half a block in the ground until it forces you back up a second later. For example, create a warp somewhere far off in the world, then teleport between that warp and spawn. You'll be half a block in the ground for a second when teleporting, every time. Even local host testing.

I'm requesting a setting to adjust Y-Offset for all teleports handled by Essentials to fix the teleportation lag. :) An arena plugin I use recently fixed this problem with a 0.5 block Y-offset with teleports it handles.

**Comment by SupaHam** [comment]
I'm not entirely comfortable with this solution. A solution to this issue is loading chunks before teleportation. Since EssentialsX's teleports are general teleports (not focused like an Arena plugin) this might cause unexpected results in different cases.

**Comment by pop4959** [comment]
Yeah this is not really something that Essentials can completely fix IIRC, as it's an issue with teleportation in general. Y-offset would be more of a hack rather than offering a real solution.
