### ISSUE TITLE
Essentials/Groupmanager no permission bug

### ISSUE THREAD

**Issue by mehboss09** [EssentialsX/Essentials#748]
So I recently upgraded to this build of essentials and I had an older one, I upgraded because I was looking for a fix to the lower case and upper case /baltop names bug, which this had a fix for.. Well I swap out the old and put in the new and I restart my server, I then try and to essentials commands like /essentials reload and it say no permission.. I am opped and have '*' permission node set for my owner group, which I am assigned to.

Spigot version 1.8.8
   Old Essentials:
      Essentials-2.x-SNAPSHOT.jar
      EssentialsChat-2.x-SNAPSHOT.jar
      EssentialsGroupManager.jar
      EssentialsSpawn-2.x-SNAPSHOT.jar

  New Essentials:
      EssentialsX-2.0.1.jar
      EssentialsXChat-2.0.1.jar
      EssentialsXGroupManager-2.0.1.jar
      EssentialsXSpawn-2.0.1.jar

**Comment by Kakifrucht** [comment]
GroupManager is not supported. Switch to a still maintained permissions plugin please.

**Comment by mehboss09** [comment]
If I switched to permissionsex would it work?

**Comment by mehboss09** [comment]
bump

**Comment by Kakifrucht** [comment]
please don't "bump", especially not after 8 minutes.
I can't tell you if it would fix your problem, I can only tell you that as long as you use an outdated plugin trying to pin point the exact issue is not worth it for anyone.

**Comment by mehboss09** [comment]
:) Thank you so much, I have done exactly what you said and now it works. <3

**Comment by mehboss09** [comment]
Don't mean to waste time but how often can I bump?

**Comment by mehboss09** [comment]
bump

**Comment by Kakifrucht** [comment]
I don't think that you will get any help with that attitude. I tried to help, your sarcasm is not appreciated here.

Seriously, I like helping people, but it's people like you who come here and disincentivize people like me from helping other randoms. I would kindly ask you to fuck off, but maybe somebody else is willing to sacrifice his time for ungrateful people like you (which I hope not).

**Comment by mehboss09** [comment]
Bro, this isn't sarcasm. I understand why you thought it was and I apologize. I thank you for taking your time to help me, your solution actually did work..

19.07 20:10:17 [Server] INFO [EssentialsSpawn] Loading EssentialsSpawn v2.0.1-b403
19.07 20:10:17 [Server] INFO [Essentials] Loading Essentials v2.0.1-b403
19.07 20:10:17 [Server] INFO [EssentialsChat] Loading EssentialsChat v2.0.1-b403
19.07 20:10:17 [Server] INFO [PermissionsEx] Loading PermissionsEx v1.23.4

^ There's proof if you don't believe me. ^-^

**Comment by mehboss09** [comment]
bump

**Comment by mehboss09** [comment]
19.07 20:10:17 [Server] INFO [EssentialsSpawn] Loading EssentialsSpawn v2.0.1-b403
19.07 20:10:17 [Server] INFO [Essentials] Loading Essentials v2.0.1-b403
19.07 20:10:17 [Server] INFO [EssentialsChat] Loading EssentialsChat v2.0.1-b403
19.07 20:10:17 [Server] INFO [PermissionsEx] Loading PermissionsEx v1.23.4

**Comment by drtshock** [comment]
Use online mode
