### ISSUE TITLE
Players display leave messages even with proper settings

### ISSUE THREAD

**Issue by Elgorond** [EssentialsX/Essentials#75]
I have given players the permission "essentials.silentjoin" and "essentials.silentquit", but it does not give them a silent quit. It does give them a silent join however.

I have also made sure to enable allow-silent-join-quit in the config. Note that I haven't had this issue before switching from Spigot-Essentials to this.

Spigot version: git-Spigot-f928e7a-e91aed8 (MC: 1.8.7)
EssentialsX: 2.0.1-b171

**Comment by ghost** [comment]
Essentials 2.0.1-b206
Spigot 1.8.8-R0.1-SNAPSHOT

**EssentialsX debug:**
checking if xxxxx has essentials.silentquit - false

**GroupManager Permission Check:**
The user inherits the permission from group: xxxx
Permission Node: essentials.silentquit
SuperPerms reports Node: true

The player does have the permission but Essentials does not detect it. It does detect essentials.silentjoin however.

**Comment by SupaHam** [comment]
@wazoomie Were there any errors since startup?

**Comment by ghost** [comment]
[Essentials] Loading Essentials v2.0.1-b206
[Vault] [Economy] Essentials Economy found: Waiting
[Multiverse-Core] [AllPay] - Version 13.0 - hooked into Essentials Economy for Multiverse-Core v2.5-b691
[Lottery] Payment method found (Essentials version: 2.2)
[boosCooldowns] found [Essentials Economy] plugin, enabling prices support.
[Essentials] Enabling Essentials v2.0.1-b206
Using locale en_GB
[Essentials] Using 1.8.3+ BlockStateMeta provider as spawner provider.
Using locale en_GB
[Essentials] Starting Metrics. Opt-out using the global PluginMetrics config.
[Vault][Economy] Essentials Economy hooked.
[Essentials] Using Vault based permissions (GroupManager)
[Essentials] Using Vault based permissions (GroupManager)
[Essentials] Using Vault based permissions (GroupManager)
[Essentials] Using Vault based permissions (GroupManager)
[Essentials] Using Vault based permissions (GroupManager)
[Essentials] Using Vault based permissions (GroupManager)
[Essentials] Using Vault based permissions (GroupManager)
[Essentials] Using Vault based permissions (GroupManager)
[Essentials] Using Vault based permissions (GroupManager)
GriefPrevention: Hooked into economy: Essentials Economy.
[Essentials] Using Vault based permissions (GroupManager)
[Essentials] Using Vault based permissions (GroupManager)
[Essentials] Using Vault based permissions (GroupManager)
[Essentials] Using Vault based permissions (GroupManager)
[EssentialsSpawn] Enabling EssentialsSpawn v2.0.1-b206
[Essentials] Using Vault based permissions (GroupManager)
[MoreSounds] Essentials hooked!
[Essentials] Using Vault based permissions (GroupManager)
[Essentials] Using Vault based permissions (GroupManager)

This is the startup log filtered on Essentials.

**Comment by SupaHam** [comment]
Hey, could you please update EssentialsX and let me know if this issue still occurs?
