### ISSUE TITLE
feature request > attributes in kits

### ISSUE THREAD

**Issue by random1167** [EssentialsX/Essentials#750]
Hello , I am using a plugin called itemizer to edit some items i want to package together into a kit,
now i dont know if this is a itemizer issue or a EssentialsX issue but when i create the kit 
this
![q748i9e7](https://cloud.githubusercontent.com/assets/13611085/17009659/52cb5c2c-4f40-11e6-98cb-3b15276bd755.jpg)
reverts back to default with only the lore,enchantments and name edits been save.
![a6y8k704](https://cloud.githubusercontent.com/assets/13611085/17009696/b46bbd0a-4f40-11e6-9206-4ab868e20ccd.jpg)
is there anything i could try to help fix this ?

**Comment by fieu** [comment]
AFAIK EssentialsX unfortunately doesn't support attributes. 😞

**Comment by random1167** [comment]
O..well lemmie update this to a request

**Comment by MithrandirCraft** [comment]
+1

**Comment by MadWookie** [comment]
+1

**Comment by mdcfe** [comment]
Closing in favour of #1105.
