### ISSUE TITLE
Bypass unsafe enchant

### ISSUE THREAD

**Issue by Pijanista** [EssentialsX/Essentials#752]
There is bypass for unsafe enchant with commandblock, is there possibilty to fix that?

/give p minecraft:diamond_sword 1 0 {ench:[{id:19,lvl:1000},{id:20,lvl:1000},{id:21,lvl:1000}]}

**Comment by SupaHam** [comment]
So you don't want command blocks to bypass the unsafe enchantments?

Just as a heads up, if you're using command blocks you need to make sure only trusted people have access to them, otherwise you are vulnerable to attacks on your server.
