### ISSUE TITLE
Essentials X Signs not working?!

### ISSUE THREAD

**Issue by MinatoGitHub** [EssentialsX/Essentials#753]
Hello my essentials signs isnt working,
yes i enabled it in the config.... anyone know why?

**Comment by SupaHam** [comment]
Define "isnt working"

**Comment by AckPyro** [comment]
Yeah I have same problem. I enable it in the config but isnt working :/ It says unknown item name but item name is right. Balance is with blue but its not working i enable all signs but no 1 is working pls help!!!
![2016-08-12_17 47 15](https://cloud.githubusercontent.com/assets/20993925/17628259/e5d2ee4c-60b4-11e6-8a13-a93ad4d3ee11.png)

**Comment by mdcfe** [comment]
Closing due to lack of response from OP; if this is still a problem, please open a new issue.
