### ISSUE TITLE
Cant use certain commands

### ISSUE THREAD

**Issue by ZachLSX** [EssentialsX/Essentials#757]
Hi.
I have GroupManagerX along with EssentialsX. They are both up to date, but something seems to not work.
I op myself in game and tried doing /ess rl and it doesn't work. I have '_' in my group, and individually on me and I still can't do it. I can do other commands such as createkit. Earlier I couldn't do /setspawn so I added the perm individually and it worked. I also added essentials._ and it still didn't work. Any help?!

**Comment by SupaHam** [comment]
There's no such plugin as GroupManagerX. We ship the original GroupManager plugin, but sadly we do not support it.

![](http://supa.me/kJyqd3.png)

**Comment by ZachLSX** [comment]
What? On the download page there is this:
http://i.imgur.com/6bZ6tbf.png

My friend uses group manager, it works? I dont' understand

**Comment by SupaHam** [comment]
On that same download page there is the image I linked above. Also in my previous post I said we **ship it**, meaning we do supply it with our downloads, but we do not **support it**. This means you can use GroupManager at your own risk, if you are having issues with it, you cannot come here asking for help and expecting results.

**Comment by ZachLSX** [comment]
Oh, sorry. I am fairly new to this. Thanks for the help though.
