### ISSUE TITLE
Essentialsx Signs Do Not Function

### ISSUE THREAD

**Issue by Buzzyboyty** [EssentialsX/Essentials#758]
Hello,

After installing EssentialsX on my server, including the latest version, Essentials sign's do not work. I have activated them by removing the hashtag in the essentials config.

For example:

When I try to place a [Heal] sign, it doesn't say anything when its created, and the sign stays blank, and does not work. 

If you could please get this fixed soon, it would be great!!

**Comment by SupaHam** [comment]
Update your Spigot version and get back to us.
