### ISSUE TITLE
"left the game" issue + /god problem?

### ISSUE THREAD

**Issue by TNTUP** [EssentialsX/Essentials#759]
See here: http://i.qcfb.ca/20160725065409.png

When the server started up, I've noticed a 5 sec delay when the player disconnects, I tried the /ess reload, the delay is gone, but the "left the game" appears (5 sec delay). I don't know if it will fix if I restart the server, using this build (https://ci.drtshock.net/job/EssentialsX/411/) 

I'm on Paper 1.10.2 #820. I'll take a look what it causes this.

EDIT: Server restarted, same as I've explained. I've repeated what I did and it happens again :S

**Comment by SupaHam** [comment]
I suspect this has something to do with the server lagging. Next time this happens I need you to not do anything and wait until his custom quit message displays. It would be great if you could provide timings during this event as well.

Steps:
1. Start and join server
2. Type `/timings on`
3. Quit server
4. Wait until the custom message is displayed
5. Type `/timings paste`
6. Share link here.

**Comment by TNTUP** [comment]
I tried on a test server and it seem not to happen, so I suspect thats another plugin doing this, I'll have a look

Here's the timings requested https://timings.aikar.co/v2/?id=0eecf4b0abee44909d09dbfb45c30252 (still happens on my live server) I'll check plugin-by-plugin

Here's another (it just did happen on my test server) https://timings.aikar.co/v2/?id=9c934f9eab3a434a937df1a6f6f3dd6e&raw=1

EDIT: It is caused by GriefPrevention (the Quit delay)
EDIT2: RandomTP caused /god to be broken. Removed the plugin.

**Comment by TNTUP** [comment]
Closing issue, at first I thought it was Essentials, but it was in GriefPrenvention antispam thing which affected my issue(s)
