### ISSUE TITLE
Playername/UUID issue

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#76]
There is one but with essentials on the cracked servers and i think you can fix it
So, the issue is...
When i join with nickname Th3Tr0LLeR and get /kit tools i can't get it again but when i join with Th3Tr0LLer i can get the kit again with no problems. so, the player Player gets the kit and then joins with PLAYER and gets the kit again.

This is because the user files are saved as UUIDs and when you change the case of your nickname you have a new uuid.
Can you make it to check the nickname before join so if the nickname is with another case = kick ?
Thank you :)

**Comment by drtshock** [comment]
"Can you make it to check the nickname before join so if the nickname is with another case = kick ?"
make another plugin that does that.

**Comment by ghost** [comment]
Is that because you cant fix it ?

**Comment by vemacs** [comment]
We don't support cracked servers.

**Comment by ghost** [comment]
So, its it...
