### ISSUE TITLE
essentials.fly.safelogin not working

### ISSUE THREAD

**Issue by Sckaletz** [EssentialsX/Essentials#760]
The permission essentials.fly.safelogin is not working. When entering a server where you were using fly the last time you were there, you still fall to your death.

**Comment by SupaHam** [comment]
Please do the following:
1. Type `/ess debug`
2. Log in whilst in the air
3. http://pastebin.com your server log.

**Comment by Sckaletz** [comment]
http://pastebin.com/ZxTJ27bz

The playername to look for is my own - Sckaletz.

Essentials version: Essentials v2.0.1-b267
Spigot version: git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by SupaHam** [comment]
@Sckaletz Based on what the log says, EssentialsX checked if you were meant to fly or not and it decided not successfully.

Can you describe the column of blocks under you when you spawn in? If they are possibly damaging or air blocks, EssentialsX will try to make you fly.

**Comment by Sckaletz** [comment]
That's strange. The blocks beneath me in this case are dark oak logs.

**Comment by SupaHam** [comment]
So you're standing on dark oak logs? If so then EssentialsX doesn't make you fly when you log in.

**Comment by Sckaletz** [comment]
No no I'm flying about 10 blocks above them

**Comment by SupaHam** [comment]
Plugins can override EssentialsX behaviour. Are you using Multiverse? Multiverse forces the world's gamemode by default when players enter that world.

**Comment by Sckaletz** [comment]
Ok thank you. I'll try and figure it out then :D
