### ISSUE TITLE
Please make option to disable " bulk buy/sell when sneaking"

### ISSUE THREAD

**Issue by netherstar** [EssentialsX/Essentials#765]
Please make option to disable " bulk buy/sell when sneaking", i think many Owner don't want this feature,.

**Comment by SupaHam** [comment]
This has been introduced in f1d9cda. You can grab the feature from [build 415](https://ci.drtshock.net/job/EssentialsX/) on the CI server.

If you do not have the allow-bulk-buy-sell property in your config (which was just added to the default config), you do not need to do anything. The previous functionality will remain for old EssentialsX users.

**Comment by netherstar** [comment]
Thank you very much!
