### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#766]
*snip*

**Comment by SupaHam** [comment]
Make sure you have Vault and EssentialsXChat installed.

**Comment by ImPat** [comment]
Vault is not updated to 1.10 jet. If you have a link for a download please tell me here.

**Comment by SupaHam** [comment]
Plugins don't need to be updated to 1.10 to work on 1.10. That's one of the greater things about Bukkit. Use whatever the latest version is.
