### ISSUE TITLE
Error when applying enchantments to shields

### ISSUE THREAD

**Issue by malonnnn** [EssentialsX/Essentials#767]
> /give player minecraft:shield 1 durability:3 mending:1 basecolor:14188339 HALF_HORIZONTAL:10040115 HALF_HORIZONTAL_MIRROR:10040115 CROSS:3361970 STRIPE_CENTER:3361970 STRIPE_MIDDLE:3361970 FLOWER:16777215 name:&4C&9apt&fain_&4A&9mer&4ica's_&9Shield

 .

> Error: No enum constant org.bukkit.block.banner.PatternType.durability

**Comment by SupaHam** [comment]
Durability is not a value, you'll want to use `minecraft:shield:3` instead

This has been fixed in 5960f55. You can grab the fix from [build 417](https://ci.drtshock.net/job/EssentialsX/) on the CI server.
