### ISSUE TITLE
Muted people can use /afk message 

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#768]
Muted people can bypass the mute by using /afk message when the message is displayed in global chat via userIsAwayWithMessage=\u00a77\* {0} \u00a77is now AFK: {1}
I added {1} to trial to see if the afk message would be abused being shown in global chat, temp muted people have figured out this!

**Comment by SupaHam** [comment]
That makes no sense. Based on [this code](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/commands/Commandafk.java#L50) when muted players type /afk with a message they are denied.

Edit: Are you sure they're muted on Essentials? If not, I don't think there's anything we will do about it. You can always add /afk to the muted commands in the config.

**Comment by TomLewis** [comment]
I forgot to mention I use BanManager... That would be why..
