### ISSUE TITLE
Request: /nicklist and timed nicks

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#769]
Simple request to list all players with nicknames, if I have 70,000 players and a bunch have nicknames, I have forgotten who has nicks and who hasn't, I cant /realname everyone.
So could we please have a /nicklist to list the players name and what they are nicknamed something like
FrozenBeard > Frozen
To display their username and what they are nicked to.
This way nick can actually be used on a medium server.

Request 2: Temporary nicks, nicks that have a timer. So they can be set via another plugin or game to change the players username temporarily for a certain period of time.
For example. /nick FrozenBeard Frozen 10m

**Comment by ghost** [comment]
NCP has a feature to delay commands. In this case you could execute the command "nick FrozenBeard Frozen"
and then execute "ncp delay 12000(delay in ticks in this case 10 minutes) nick FrozenBeard"
This can be simplified using aliases.

**Comment by TomLewis** [comment]
That's a ductape fix for sure, This is more of a package of small features to make /nick ever so slightly better, as at present its bare bones.

**Comment by SupaHam** [comment]
Can you please elaborate on the use case for the first request? Why would you need to see every nick on the server? Does `/nicklist` list every player's nickname including offline players? What is the benefit? Generally if you're checking someone's nickname out, you're checking them out specifically. 

I don't like the second request very much, but if you want it, I'd recommend you make another issue about it.

**Comment by TomLewis** [comment]
To see who is nicknamed... so it can be kept track of, so if you nickname someone and then forget about it which is what happens, then you can go back and see who is actually nicknamed, if I wanted to find out who is nicknamed on my server of 70k players, its impossible how do I do it? i cant? Yes offline players.

**Comment by mdcfe** [comment]
Closing in favour of #2188.
