### ISSUE TITLE
Question: Stable/dev releases or rolling release?

### ISSUE THREAD

**Issue by EvilOlaf** [EssentialsX/Essentials#77]
Just a small question about the versioning: Do you plan to release stable snapshots from EssentialsX or will the dev builds be declared as stable and some kind a rolling release?

**Comment by drtshock** [comment]
We'll have snapshots built every commit that will be auto built and up for download on my CI. We will also (most likely) be posting periodic updates / minor version bumps to Spigot and Bukkitdev. Can expect those updates to be on a period similar to FactionsUUID https://www.spigotmc.org/resources/factionsuuid.1035/history
