### ISSUE TITLE
messages_en variable for "has messages disabled" does not exist.

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#770]
Hello, I have asked this before, the error message players receive when a player has /msgtoggle disabling people to msg them cannot be customized. 
I have searched everything in messages_en.properties, and I have tried all the 
msgDisabled, msgDisabledFor, msgEnabled, msgEnabledFor
What has been missed is the msgError, its nowhere to be found, the exact error message players receive is:
`has messages disabled`
in dark red.
I wish to amend this to tell players if they need help to create a support ticket.

**Comment by ghost** [comment]
Bump

**Comment by SupaHam** [comment]
@ImPat Don't bump again.

**Comment by SupaHam** [comment]
~~@FrozenBeard Just by locating the command class (called Commandmsgtoggle) I can see the message nodes:
-msgEnabled
-msgDisabled
-msgEnabledFor
-msgDisabledFor~~

Check the latest jar's message.properties, or browse the code, hit t on your keyboard and type message.properties, and click the first thing.

Edit: [Here's the actual message node which is called `msgIgnore`](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/messages.properties#L582).

**Comment by TomLewis** [comment]
What? im sure you havne't read the issue properly, this is the second time I have reported this and both times it has been misunderstood.
I don't know how to explain this without repeating myself.

I am not talking about those parameters at all, you are **missing a parameter** for the exact phrase 
`has messages disabled`
Again, this is NOT the messages for when you toggle it, this is the ERROR message that OTHER PEOPLE get when they attempt to send a message to the person that has it disabled.

**Comment by SupaHam** [comment]
Refresh ;)

Whoever added this didn't add the message to all files. To be safe, always check messages.properties.

**Comment by TomLewis** [comment]
Can I just add this parameter or will I need to push a new jar?
Edit: Ah! I was checking messages_en.properties, I will check the messages.properties in the future! 
Thank you.

**Comment by SupaHam** [comment]
You can just add it to your current language file and it will pick up on it just fine. :)

**Comment by TomLewis** [comment]
Thank you @SupaHam one last really quick question, can I add new lines to this messages_en.properties? Looking for a way to space out the error message.

**Comment by SupaHam** [comment]
Yeah, any blank lines are ignored. You can also leave commands using `#`

```
####################
## ERROR MESSAGES ##
####################
...
```

**Comment by TomLewis** [comment]
As in, new lines in-game, I cant just use a \n can I in messages?

**Comment by SupaHam** [comment]
Oh right, yeah you can use `\n`
