### ISSUE TITLE
Items.csv update to 1.10

### ISSUE THREAD

**Issue by dscalzi** [EssentialsX/Essentials#772]
The items.csv file needs to be updated to include aliases for the 1.10 blocks. The [current version](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/items.csv) is only updated up to 1.9.

**Comment by dscalzi** [comment]
For ease, I'll list the 5 new blocks below:
STRUCTURE_BLOCK - id 255
MAGMA - id 213
NETHER_WART_BLOCK - id 214
RED_NETHER_BRICK - id 215
BONE_BLOCK - id 216

There are also several new spawn eggs but they don't have data values.

**Comment by SupaHam** [comment]
This has been introduced in 3a6da5c. You can grab the feature from [build 423](https://ci.drtshock.net/job/EssentialsX/) on the CI server.
