### ISSUE TITLE
Vanished players go afk

### ISSUE THREAD

**Issue by BiGUNMAN** [EssentialsX/Essentials#773]
Hi, I have an afk timer, but players with access to vanish can easily bypass it. I was hoping you guys could add a permission activates this functionality, so that standard players in vanish without this permission still get kicked.

**Comment by drtshock** [comment]
Isn't vanish meant to be given to staff = people that you don't want kicked?

**Comment by BiGUNMAN** [comment]
Quite a few servers (I think atleast), sell vanish to players. And there is an exempt afk kick permission to not kick staff.

**Comment by drtshock** [comment]
https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/User.java#L531

Looks like we just have a check to see if the player is vanished when looking at activity. Should just be able to remove the `!isHidden` from that line unless I'm missing something.

**Comment by SupaHam** [comment]
Yeah I don't see a reason to rely on that `isHidden` check for exemption.

**Comment by SupaHam** [comment]
This has been fixed in  8927fe9. You can grab the fix from [build 420](https://ci.drtshock.net/job/EssentialsX/) on the CI server.

_blaze it_
