### ISSUE TITLE
java.lang.NoSuchFieldError: MENDING (Essentials v2.0.1-b417) (PaperSpigot-1.7.10)

### ISSUE THREAD

**Issue by md79** [EssentialsX/Essentials#774]
http://hastebin.com/nolimopage.avrasm

**Comment by SupaHam** [comment]
Sorry, I accidently broke backwards compatibility.

This has been fixed in 30d5fbd. You can grab the fix from [build 418](https://ci.drtshock.net/job/EssentialsX/) on the CI server.
