### ISSUE TITLE
Eco command not functional.

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#78]
Typing `/eco give <player> <amount>` in console does not credit the user with money. This function use to work before updating.

EssentialsX dev 173

[Edit] It seems all `/eco` commands do not work. In-game or from console. Nothing is outputted.

**Comment by mibby** [comment]
@drtshock This commit is the cause. https://github.com/drtshock/Essentials/commit/dd65a1e76c6cc07aead41ebefe90b156e7163234

Downgrading to dev 172 and removing 

```
# Setting to true will completely disable eco operations for Essentials.
# This might have weird effects and we recommend leaving this to false.
disable-eco: false
```

from the config fixes the issue.

**Comment by Kakifrucht** [comment]
Quite annoying, since /essentials reload doesn't fix the issue :(

**Comment by vemacs** [comment]
Please delete that line from the config after upgrade.
