### ISSUE TITLE
Add 1.10 Mobs

### ISSUE THREAD

**Issue by dscalzi** [EssentialsX/Essentials#781]
Three new mobs have been added in version 1.10. These mobs are currently unrecognizable by essentials commands such as /spawnmob.

Polar Bear
Stray (Ice Skeleton)
Husk (Desert Zombie)

The latter two are not spawnable by adding data tags to zombie or skeleton. The skeleton data tag is 2, the zombie data tag is 6.

**Comment by SupaHam** [comment]
Husk and Stray are zombies and skeletons respectively. We cannot properly add support for these extra mob data until Spigot adds API support for them. This can be continued in #793.
