### ISSUE TITLE
Delay on on custom quit messages.

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#784]
Hello.

Since I updated my server there's a 10 second  delay on my custom logout message.
I did not find anything in the config file to fix it.
I am using the latest version from Jenkins
![console](https://cloud.githubusercontent.com/assets/20758389/17296608/6de68eda-5802-11e6-967c-6b1cb7c56562.PNG)

**Comment by ghost** [comment]
FIXED! Figured out that it was GriefPreventions fault!

**Comment by TomLewis** [comment]
How did you fix it? I am having the same issue and also use GriefPrevetion.

**Comment by Turbotailz** [comment]
@FrozenBeard you may have figured it out already but I'll put this here in case anyone else is looking (this was the top hit on Google).

In GriefPrevention config.yml you'll want to find this setting:

`Logout Message Delay In Seconds: 10`

and change it to 0 if you don't want a delay for the logout message.

**Comment by TomLewis** [comment]
@Turbotailz thanks man.
