### ISSUE TITLE
[Request] /ignore list

### ISSUE THREAD

**Issue by voodootje0** [EssentialsX/Essentials#785]
Could you please add /ignore list so that you can see who you have ignored?
Thanks!
- voodootje0

**Comment by Kakifrucht** [comment]
Ignores are not properly stored yet, they are not saved as UUID's. That would have to be fixed first.

#239

**Comment by ghost** [comment]
News?

**Comment by mdcfe** [comment]
This can be achieved by just running `/ignore` to see every user that has been ignored.
