### ISSUE TITLE
Signs become Blank

### ISSUE THREAD

**Issue by Bergyrr** [EssentialsX/Essentials#786]
I'm running Bukkit 1.10.2
Signs don't work, when I enable them and try the sign becomes blank. I tried have essentials as the only plugin and it still didn't work. 
Current plugins: creative gates, dynmap, factions, hub that, massive core, multiverse core, per world plugin, per world inventory, sky wars, vampires, world edit, world guard.
Start up log: http://pastebin.com/ZhbJBsEr

**Comment by SupaHam** [comment]
Duplicate of #687. Spigot bug, update spigot.

**Comment by Bergyrr** [comment]
not running spigot and bukkit is current

**Comment by SupaHam** [comment]
Update craftbukkit then.

**Comment by Bergyrr** [comment]
it is 1.10.2

**Comment by SupaHam** [comment]
Yes but there are individual builds for each Minecraft version. Just rerun buildtools and use that jar.

**Comment by Bergyrr** [comment]
get back to you after i do that

**Comment by Bergyrr** [comment]
it's working thx for the help
