### ISSUE TITLE
[Request] Tpa Cooldown

### ISSUE THREAD

**Issue by AntZaro** [EssentialsX/Essentials#787]
This is going off of command cool downs. People sometimes spam a player with /tpa. Could there be a cool down for /tpa but _only_ if it goes to the same person? So if I run /tpa notch and then /tpa notch again right after, it might say something like "You already sent Notch a request recently" and it wouldn't let you send another until the previous one times out, as configured in the config file. 

Unrelated: I noticed some updates regarding the format of social spy in chat. Will we ever be allowed to completely configure the look of social spy ourselves? Like change the color of it or something?

**Comment by justcool393** [comment]
> Unrelated: I noticed some updates regarding the format of social spy in chat. Will we ever be allowed to completely configure the look of social spy ourselves? Like change the color of it or something? 

You can change the socialspy formatting by changing [the locale settings](http://wiki.ess3.net/wiki/Locale#Custom_Messages). The SocialSpy format is under the key ~~`socialSpy`~~ `socialSpyPrefix`.

**Comment by AntZaro** [comment]
The "socialSpy" key in the locale only configures the message for when you enable/disable social spy. For instance, "SocialSpy for [Admin]~Notch: enabled" that is the message you can configure in the locale. You cannot change social spy formatting of the actual message (like using username instead of display name, changing the text color, etc.) Those are the features I was hoping to have.

**Comment by justcool393** [comment]
Sorry, meant `socialSpyPrefix`. You can change the color of it by changing \u00a7f to \u00a7[colorcode]. You are right about it using the display name, but I'm pretty sure that's used almost everywhere else is Essentials. You could try using /realname afterward although I admit it is a little longer.

**Comment by AntZaro** [comment]
Yeah. It's just a major complaint from all our staff members. Everyone thinks the social spy is too much spam and confuses it with their own messages. I just wish I could make it all gray using usernames or something like that. Just to make it a bit easier on the eyes. Thanks anyway though; hopefully they will add more customization soon.

**Comment by pop4959** [comment]
A player can turn off their teleportation requests with `/tptoggle`. This forces the player who wants to teleport to actually ask if they may teleport (then they can be send a request with `/tpahere`) and thus takes care of any spam concerns. For this reason, I don't think this is really a necessary addition. although if someone wanted to PR it they could.
