### ISSUE TITLE
[Suggestion] More than one symbol in "currency-symbol"

### ISSUE THREAD

**Issue by PsychoLynx** [EssentialsX/Essentials#790]
Hey there! I am creating an RP server where the currency is gold marks, for which the short form would be mk. However, it seems that EssentialsX seems to only print out "m" out of the "mk" defined in the currency-symbol. 

If this could be fixed, I would be very grateful. Thank you!

**Comment by fieu** [comment]
👍 **+1**

**Comment by dscalzi** [comment]
I can confirm this issue.

**Comment by SupaHam** [comment]
A solution to this is to use a messages file from the jar and modify the currency message to replace `{0}` with whatever you want. `{1}` is the money.

P.S. make sure the messages file is the same as the one in the config, which by default is `messages_en.properties`.
