### ISSUE TITLE
[Request] Support UUID in commands for player names.

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#791]
For example;
`/nick <uuid> off` - does not work.

**Comment by fieu** [comment]
+1

**Comment by deleted-user53829** [comment]
+1

**Comment by triagonal** [comment]
Loop commands can now target UUIDs as of #2606, so most commands that warrant this feature should work with UUIDs. 

If any other commands which might benefit from this are missing, feel free to open another issue.
