### ISSUE TITLE
Weird crash

### ISSUE THREAD

**Issue by TheExceed** [EssentialsX/Essentials#792]
http://hastebin.com/bepuzibebi.avrasm
Happened upon me joining.

**Comment by TheExceed** [comment]
Any help?

**Comment by Kakifrucht** [comment]
Which Spigot version are you on? Try to update and use that build. I checked my spigot.jar and it surely included the class `CrashReport$1`, which seems to be missing somehow in your case.

**Comment by SupaHam** [comment]
They're on git-Spigot-90f61bc-83a9dbd. I'm willing to bet they didn't copy the jar properly or did something very wrong when launching the server. Not our problem though, sorry.

**Comment by Kakifrucht** [comment]
Haha completely missed that the version is included in the stacktrace :baby:
