### ISSUE TITLE
Polarbears, Sign shops, and Spawnmobs

### ISSUE THREAD

**Issue by MoonlessMidnight** [EssentialsX/Essentials#793]
Hi Trent,
Is there a way to get polar bears added?  We'd like to add them to the sign shop as a spawn egg and be able to spawn them with /spawnmobs.  Thanks!

**Comment by fieu** [comment]
+1

**Comment by drtshock** [comment]
Yeah we still don't have all the 1.10 features. Need to get those added.

**Comment by SupaHam** [comment]
3a6da5c introduces some 1.10 entries in items.csv, meaning you can use new items in signs. However, `/spawnmob` requires that we have API access to the new entity data, which we don't. So we have to wait for Spigot to support that.
