### ISSUE TITLE
[Fix] [High Prioity] Boat glitch

### ISSUE THREAD

**Issue by voodootje0** [EssentialsX/Essentials#794]
Players can glitch through blocks and into bases using boats. We have tried disabling boats in faction claims but players can still glitch, just place boat at end of the faction claim.

When you're in the boat:
![](http://i.imgur.com/fg57YwW.png)

When you exit the boat.
![](http://i.imgur.com/FlTcavK.png)

**Comment by drtshock** [comment]
How is this an essentialsx issue?

**Comment by Kakifrucht** [comment]
There are (probably) millions of boat glitches in MC right now, this is most likely neither a Factions nor a EssentialsX issue. I don't think that it's within the scope of EssentialsX/Factions to take care of such glitches.

**Comment by TheExceed** [comment]
@voodootje0 Look for the plugin fbasics.
