### ISSUE TITLE
ItemFlags in kits

### ISSUE THREAD

**Issue by 7rory768** [EssentialsX/Essentials#795]
I used /createkit to create a kit but it doesnt registered the item flags that are on the items in my inventory. For example I have a renameItem given by a plugin where if you right click a renameItem it'll do something but since the item when given using /kit doesnt have the ItemFlag the rename plugin doesn't recognize the item as a renameItem when right clicked. Is there a way to manually add ItemFlags to an item in the config where its defined?

Here is the kit I made:

>   Member:
>     delay: -1
>     items:
>     - DIAMOND_PICKAXE 1 name:&a&lStarter_Pickaxe dig_speed:25 durability:25 loot_bonus_blocks:25
>     - MAGMA_CREAM 50 name:&b&lToken_&7(Right-Click) lore:&7This_item_is_worth_&b1_&7enchant_token
>     - NAME_TAG 1 name:&5&lRename_Item lore:&7Right_click_this_item_to_choose_an|&7item_out_of_your_inventory_to_rename durability:10

**Comment by TomLewis** [comment]
What is an itemflag? and how can I use it?
