### ISSUE TITLE
[Add] Vote for time/weather & /nickrequest

### ISSUE THREAD

**Issue by TheExceed** [EssentialsX/Essentials#797]
I wanted to see if it was possible to add commands for like:
/timevote - starts a poll to change the time to the reverse of what it is
/weathervote - starts a poll to change the weather to the reverse
/nickrequest or /requestnick <nick> - a request nick command so players with perms can request their nicks.

I think all would be quite useful and easier on server staff :D

**Comment by SupaHam** [comment]
Sadly I do not see this happening. Essentials is meant to provide essential features for players. These features you're requesting seem like they belong in a more specialised plugin.
