### ISSUE TITLE
Add /createkit and /showkit entry to default messages.properties

### ISSUE THREAD

**Issue by Log1x** [EssentialsX/Essentials#80]
Hi.

I'm one of those insane people who edit every single line in messages.properties to fit my color scheme.

Upon looking in the default messages_en.properties within' the source/jar, I don't seem to see a line to customize those 2 new commands.

Unfortunately I can't search the repo because it's a fork so I'm unsure if it's actually implemented (looked around a bit, can't find it), just not shown in messages.properties by default.

Thanks!

**Comment by bendem** [comment]
Are you looking for `createdKit`, `kitContains` and `kitItem`?

**Comment by drtshock** [comment]
`createKit=\u00a74/createkit <kitname> <delay>`
`kitContains=\u00a76Kit \u00a7c{0} \u00a76contains:`
`kitItem=\u00a76- \u00a7f{0}`
have been there since I added the commands :)
