### ISSUE TITLE
Question: EssentialsXGroupManager what differences does it have?

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#802]
Hello! I just noticed EssentialsXGroupManager, I do see the giant red writing that says its not supported, thats fine, I just wondered what differences this has to the original jar? 
If its got a few fixes that were showing up in the update to 1.9 that would be amazing!

**Comment by SupaHam** [comment]
Nope, hence us not supporting it.

**Comment by TomLewis** [comment]
That's fine, So there are absolutely no differences? 
I had to run my groupmanger through specialsource to get it to work, I just want to make sure to see if I should switch from the specialsource version I have, if this one is any different at all.
I understand its for legacy purposes.

**Comment by drtshock** [comment]
Yeah it just compiled on 1.9 or something or w/e version it was.

**Comment by TomLewis** [comment]
@drtshock That might actually be better than the specialsource version I have then, I might give it a whirl and see if it fixes this one issue I have :+1:
