### ISSUE TITLE
Not all cooldowns work

### ISSUE THREAD

**Issue by CycloneNW** [EssentialsX/Essentials#803]
Hey, 

command-cooldowns:
  feed: 10
  heal: 300
  fix: 3600

The "Fix" command does not have a cooldown, I have also tried wildcards and it doesn't work. All the others do work.

**Comment by SupaHam** [comment]
can you http://pastebin.com your whole config.yml and your whole server log.

**Comment by CycloneNW** [comment]
Hey, http://pastebin.com/ZCSZBjxw. Thanks.

**Comment by SupaHam** [comment]
What about the server log? Also turn on `/ess debug` before you type `/fix` please.

**Comment by CycloneNW** [comment]
http://hastebin.com/ahunogebod.cs

**Comment by SupaHam** [comment]
Can you [update to latest](https://ci.drtshock.net/job/EssentialsX/) and try again.

**Comment by CycloneNW** [comment]
Thanks, I'll check in the morning sorry, thank you!

**Comment by CycloneNW** [comment]
Hey, yeah, it doesn't work.
http://pastebin.com/KgXcFue4

The fix doesn't work but the heal does.

**Comment by SupaHam** [comment]
That wasn't actually a fix, it was just to add more information to `/ess debug`.

The issue right now is that you're specifying a command called `fix` when that's actually an alias to a command called `repair`. I'm debating whether this is something which should be fixed on our end or not, it might introduce other issues with interfering commands.

Simply replace `fix` with `repair` and any other command aliases.
