### ISSUE TITLE
Shop signs not working | Version: 2.0.1-b424

### ISSUE THREAD

**Issue by Suleman28** [EssentialsX/Essentials#804]
Hi,
I am trying to make Shop signs but everytime i make the signs and click done there is nothing there on the signs they are blank, i have also enabled all the signs in the config. the signs were working fine until i updated the server to 1.10.2
here is a little video clip of what happens.
https://www.youtube.com/watch?v=-HhGYRxP_lU

Please help me out

**Comment by CycloneNW** [comment]
Hey, the video is private.

**Comment by PixelPlayzzz** [comment]
Sorry 1 second

**Comment by Suleman28** [comment]
Sorry watch it now :)

**Comment by SupaHam** [comment]
Duplicate of #687. Update server software.
