### ISSUE TITLE
afk-list-name not working?

### ISSUE THREAD

**Issue by molor** [EssentialsX/Essentials#805]
Hello. This is my config:

```
change-playerlist: true
add-prefix-in-playerlist: true
add-suffix-in-playerlist: true
auto-afk: 180
afk-list-name: "&7{PLAYER}"
```

If player performing an /afk command, his name in player list (tab) become gray color.
But if player does nothing for 180 seconds and automatically becomes afk, his name does not become gray. This is bug?

And, can you help me, how to remove [NB SP] (2**[NB SP]**731 MB) in the /gc command?
![66](https://cloud.githubusercontent.com/assets/19989717/17457728/d5c437a0-5c08-11e6-9df8-50b28b91b948.PNG)

**Comment by SupaHam** [comment]
This has been fixed in 611429b. You can grab the fix from [build 425](https://ci.drtshock.net/job/EssentialsX/) on the CI server.
