### ISSUE TITLE
1.10.2 Logging out message disapayed wrong

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#806]
The timing of the Exit message is all screwed up, players leaving in chat and not actually leaving, or being delayed when they do.

**Comment by SupaHam** [comment]
Do you have GriefPrevention installed?

**Comment by TomLewis** [comment]
@SupaHam Yes I do

**Comment by SupaHam** [comment]
That's your problem. I'm not sure what the fix is but I heard one person saying something about Anti Spam. If you can't figure it, you should contact them about this issue.

**Comment by TomLewis** [comment]
Its an Essentails message, 100% as I customized my messaged, I will message the dev to see if it can be fixed his end. Be aware there are a lot of servers that use GriefPrevetion so don't assume its their fault without investigating.

**Comment by SupaHam** [comment]
I'm not assuming anything.....

Duplicate of #784 and others
