### ISSUE TITLE
/seen command compatibility with "PremiumVanish"

### ISSUE THREAD

**Issue by MithrandirCraft** [EssentialsX/Essentials#807]
Please add compatibility with PremiumVanish plugin. Specifically in commands such as /seen, which show for how long a vanished with PremiumVanish player has been online.

I think there's also a command for viewing online players right? Maybe that function should also consider not showing vanished players.

Please consider. Thanks! :)

**Comment by drtshock** [comment]
Could you link the plugin? And I doubt we'll hook it because that sounds like something outside of the scope of this project.

**Comment by MithrandirCraft** [comment]
If you can't do it no one will, because Premium Vanish's author thinks it thould be done on your side for some reason.

https://www.spigotmc.org/resources/premiumvanish-stay-hidden-bungee-support.14404/

I've been told that this was already being managed by Essentials. There actually was an attempt at vanish compatibility by the original essentials plugin, which was later maintained by Spigot. However, it wasn't enough, as you could still notice if a vanished player was online because the seen command would only show the player had been logged out for 0 seconds.

**Comment by LeonMangler** [comment]
For your information, I'm using essentialsUser#setHidden(..) for Essentials compatiblity in PremiumVanish and SuperVanish.

**Comment by drtshock** [comment]
There is an issue with the players showing as online even if they are vanished, which they shouldn't. We will fix that.

We will not be hooking into another third party (and premium) plugin for adding the vanished time though.

**Comment by MithrandirCraft** [comment]
What would you suggest me to do? Can I disable "/seen **Mithrandir**" with essentials somehow? Or should I deny the command usage?

PremiumVanish is the only vanish plugin alive meeting VanishNoPacket standards.
The VNP dev team fully expressed their dissinterest in maintaining their plugin.
PremiumVanish as all premium Spigot resources is only paid for once. I consider it the most decent Vanish plugin currently. It shouldn't hurt to pay for the best available.
Creating a hook for vanish plugins doesn't seem so far fetched. Specially considering the fact that Essentials has already done it in the past.

**Comment by drtshock** [comment]
Yes you can disable /seen with essentials.

**Comment by MithrandirCraft** [comment]
I wouldn't like to disable the whole command, just usage with specific name.
Essentials used to have a command whitelist, is this still present?

**Comment by LeonMangler** [comment]
I don't see how you have to hook into PremiumVanish to add support for /seen offline time. user#setHidden(..) is part of Essentials's /vanish so adding support wouldn't only benefit PremiumVanish but also every other vanish plugin which hooks into Essentials using user#setHidden(..) including Essentials itself because of Essentials's /vanish command. It's expanding Essentials's functionality, not hooking into another plugin.

**Comment by pop4959** [comment]
I agree with drtshock that this is entirely upon the author of PremiumVanish. The author of that plugin can send us a PR if they want some interoperability, but it really isn't our problem to deal with this.
