### ISSUE TITLE
UserMap and memory issues?

### ISSUE THREAD

**Issue by L4BORG** [EssentialsX/Essentials#814]
This is one of our servers (less than 12h since last restart):

![Screen](http://i.imgur.com/dsJZ0TQ.png)

Any idea what is causing this? I guess trying to remove .csv files would be good start but I don't think this is a long term solution.

**Comment by L4BORG** [comment]
```
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

```
>ver
[20:04:38 INFO]: This server is running CraftBukkit version git-TacoSpigot-"758e09a" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
```

```
>ess version
[20:05:35 INFO]: CONSOLE issued server command: /ess version
[20:05:35 INFO]: Using locale en_US
[20:05:35 INFO]: Essentials reloaded 2.0.1-b370.
```

**Comment by L4BORG** [comment]
usermap.csv was only like 25kb and usermap1044003661783068220.tmp.csv was 7,7Mb with 167k usernames/uuids... updated to latest Ess and removed all usermap files, can't wait to see what happens now... :0

**Comment by L4BORG** [comment]
Same old same old...

![](http://i.imgur.com/hrh6aXz.png)
![](http://i.imgur.com/3WlJkUm.png)

**Comment by L4BORG** [comment]
Also this was not the issue with "old" essentials, the one used before 1.9 came, https://www.spigotmc.org/resources/essentialsx.9089/update?update=67412 still worked fine iirc...

**Comment by vemacs** [comment]
Cache max is controlled by this value: 

https://github.com/drtshock/Essentials/blob/a9e41841e9370fd07c77c73646ede29c497c4247/Essentials/src/com/earth2me/essentials/UserMap.java#L40

Default is based off of allocated heap: https://github.com/drtshock/Essentials/blob/5187be5d0264622b7fec36d77b2dd1c309be6e16/Essentials/src/com/earth2me/essentials/Settings.java#L1153

Manually set the value or allocate less heap.

**Comment by L4BORG** [comment]
And if value is not set by config...

```
        long count = Runtime.getRuntime().maxMemory() / 1024 / 96;
        return config.getInt("max-user-cache-count", (int) count); 
```

right?    

We're running this on server with 6G of mem and between 100 and 250 (peaks only) players. 

max-user-cache-count: 10000 would be a good start I assume?

Everyone else is using default? Because I've only found... https://www.reddit.com/r/admincraft/comments/2gspb7/does_anyone_elses_server_that_uses_essentials/ (1yr ago lol)

Edit: oh ok.

**Comment by L4BORG** [comment]
With..

```
max-user-cache-count: 20000
```

the issue is still there.

**Comment by L4BORG** [comment]
Also...

https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/register/payment/methods/VaultEco.java#L79

is wrong according to...

http://milkbowl.github.io/VaultAPI/net/milkbowl/vault/economy/Economy.html#createBank(java.lang.String,%20java.lang.String)

?

But this shouldn't be the reason for memory leak?
