### ISSUE TITLE
trade sign error

### ISSUE THREAD

**Issue by pookshuman** [EssentialsX/Essentials#816]
Hello :)

I spoke with SupaHam in the support chat and he suggested I make an issue for this.

My server uses a lot of barter trade signs ... meaning we don't use a currency. Trade signs are items for other items. I noticed the sales line (line 3) has possible glitch.  

On line 3 you enter 2 numbers: the first is the number of items you are selling per click and the second number is the total number of sales you want to make.  So if you wanted to sell 1 piece of wool for 1 dirt and allow up to 50 sales, the sign would look like:

[trade]
1 dirt
1 wool:50
name here

This works fine as long as the items per sale (1) does not exceed the total number of sales (50)
If you reverse the numbers and try to do a sale of 50 wool in 1 sale the sign will fail and give "ERROR: Quantities must be greater than 0"

I hope this screenshot clarifies things a bit.
![tradesign-fail-examples](https://cloud.githubusercontent.com/assets/2133413/17611201/2d039250-6013-11e6-9db6-9b4a29686346.png)
http://digstraightdown.com/files/tradesign-fail-examples.png

I should note that this is not specific to essX and occurs in the original essentials. Also, I have not tested what happens with a currency economy, only trades.

Thank you for your time :)

EDIT: OK, I realized I misunderstood how this functions and so it appears to be working fine. Please remove this report or ignore it.

**Comment by NoxiousPluK** [comment]
@pookshuman What is the solution to this?

I'm trying to buy 2 books for $50 each, so I enter this:
![image](https://user-images.githubusercontent.com/4255780/153697087-86815f2b-3ba2-4ecd-a88d-751d74f035d7.png)

This should be correct according to https://wiki.mc-ess.net/wiki/Sign_Tutorial#Trade_Sign

However, I get the same error and Google returns almost nothing except this.

**Comment by Chew** [comment]
Please don't bump exceptionally old posts. Use the discussions tab or Discord if you need assistance.
