### ISSUE TITLE
EssentialsX 2.0.1 Signs 1.8 not working ! :/ 

### ISSUE THREAD

**Issue by AckPyro** [EssentialsX/Essentials#817]
I enable it in the config but isnt working :/ It says unknown item name but item name is right. Balance is with blue but its not working, Heal is not working it say that total amount must be greather than 0... I enable all signs but no 1 is working pls help!!! 
![2016-08-12_17 47 15](https://cloud.githubusercontent.com/assets/20993925/17628687/e5faf73c-60b6-11e6-84cd-58a562df84de.png)

**Comment by wardpieters** [comment]
Please do the following:
1. type /ess debug
2. create [buy] sign
3. pastebin console log.

**Comment by AckPyro** [comment]
Now its ok. I changed server version to the 1.8.8 and it is good,
everything is now working perfectly. :)

2016-08-19 0:53 GMT+02:00 wardpieters notifications@github.com:
