### ISSUE TITLE
MuteStatusChangeEvent is not fired...

### ISSUE THREAD

**Issue by L4BORG** [EssentialsX/Essentials#819]
... ever.

Tested on latest 1.8.8 TacoSpigot and latest Essentials.

**Comment by drtshock** [comment]
We're trying to be healthy.

**Comment by L4BORG** [comment]
Meaning? It's strange because JailStatusChangeEvent on the other hand, works just fine.

**Comment by drtshock** [comment]
you said it's not fried

**Comment by rye761** [comment]
Yes, it seems that this event wasn't properly implemented.
