### ISSUE TITLE
Remove stripping excess colorcodes in MOTD

### ISSUE THREAD

**Issue by Log1x** [EssentialsX/Essentials#82]
I was curious if we could remove the code that makes Essentials strip every color code but the last in a MOTD that way we can seamlessly implement SImple Block Codes.

You can see this issue here: https://github.com/Lunatrius/Schematica/issues/75#issuecomment-75020561

This would be purely enhancement, but only proceed with this if you feel it won't affect users negatively. Assuming their color coding within' their MOTD isn't a disaster, it should be just fine I'd think.

**Comment by lol768** [comment]
@Log1x I'm curious as to why you use chat messages rather than the [plugin channels](http://wiki.vg/Plugin_channel) system for this.

**Comment by Log1x** [comment]
I have no personal experience with the plugin channels system, but saw that issue with Essentials in the Schematica issue section when I tried to add the Block Codes to my MOTD at one point to block players from using it.

The whole concept of Simple Block Codes is not only hacky and unconventional, but easily bypassable with a custom compile. But to stop noobs, if it wasn't too big of a deal to stop Essentials from stripping sequenced color codes like that, It'd be nice to shove them in a MOTD instead of having an empty line with a plugin such as http://dev.bukkit.org/bukkit-plugins/sbc/

You can see another explanation here https://github.com/Lunatrius/Schematica/wiki/Simple-Block-Codes

Schematica is one of about 10-15 known used mods that support block codes in multiplayer.

**Comment by lol768** [comment]
It's not at all up to me, was simply curious about the concept. Thanks for the explanation/background info.

**Comment by pop4959** [comment]
As mentioned in the linked post, it's probably better to get a plugin that is intended for sending block codes. It looks like such a plugin was created a few months after this issue was created, so there's no necessity for this to be supported in Essentials.
