### ISSUE TITLE
Add PlaceholderAPI Support

### ISSUE THREAD

**Issue by fieu** [EssentialsX/Essentials#820]
I understand that it has been requested before. I just don't see why you can't add it as a soft dependency. Everybody wants it.

Link to plugin: https://www.spigotmc.org/resources/placeholderapi.6245/

**Comment by Tosser42069** [comment]
Bump^ This would be greatly appreciated.

**Comment by Portanna** [comment]
Agree

**Comment by mdcfe** [comment]
Closing in favour of #1945.
