### ISSUE TITLE
Player loses /back after being jailed

### ISSUE THREAD

**Issue by EvModder** [EssentialsX/Essentials#821]
If a player is unjailed, they are teleported back to where they were prior to being jailed.  However, if they type /back, they are sent to the jail (and not what their /back was before being jailed)

**Comment by mdcfe** [comment]
I'm fairly certain this is intentional - Essentials teleported them when they were jailed, which overwrote their /back location.

**Comment by mdcfe** [comment]
Closing as this is intended behaviour.
