### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by eamonniknafs** [EssentialsX/Essentials#822]
Just a heads up.

**Comment by SupaHam** [comment]
If you're talking about http://wiki.mc-ess.net/wiki/Main_Page, it's up. Plus we don't manage that website.

Edit: Nevermind, I think you mean [https;//ci.drtshock.net](https;//ci.drtshock.net) which is indeed down, I've notified drtshock.

**Comment by drtshock** [comment]
see twitter
