### ISSUE TITLE
Add socialspy.exempt permission

### ISSUE THREAD

**Issue by Log1x** [EssentialsX/Essentials#83]
Referencing this from https://essentials3.atlassian.net/browse/ESS-3346

A comment says that they object this morally.

On my server, my concern isn't my /msg being spied on. I have a vast amount of commands in my Social Spy list so I can make sure staff/administrators and even users (we all have the random user who joins and starts railing /pex, /say, /minecraft:say, whatever-- I like to know these things to get a better idea of who I'm dealing with.) are acting appropriately.

As far as justifying Exempt it's self, sometimes, I like to perform administrative actions and certain things that are on my social spy list privately allowing me to concentrate on executing the changes and working on the actual server without getting railed about builds and player problems. I can't say it much simpler than that. Maybe it's just the introvert in me..

Sure, I could just perform my commands as needed in Console; but does the convenience really make it that crazy? 

If Wild Card permissions are a concern, you could add a config option like silentjoin/silentquit but I personally just use negative permissions.

If this still seems inhumane and evil-- then leave it at that and delete/close. But, I'd like it and It shouldn't be a hard implementation. <3

I know other owners/admins would like it too.

**Comment by TheJadyha** [comment]
Agreed!!

**Comment by TomLewis** [comment]
Agreed.

**Comment by drtshock** [comment]
There ya go :)
