### ISSUE TITLE
Ability to remove "Creating empty config: ..."

### ISSUE THREAD

**Issue by molor** [EssentialsX/Essentials#831]
Can add the ability to remove this info from console?
For me, this information is useless and just takes up space..

Setting "creatingEmptyConfig" in messages.properties file to the value "" gives a empty line in the console..

**Comment by FlippantCactus** [comment]
So you want to conserve your log file space...?

**Comment by fieu** [comment]
Just run a program like `ack` to strip the data. Easy.

**Comment by molor** [comment]
@TWSSYesterday, yes..

**Comment by mdcfe** [comment]
I don't see the use case of this - if you want to minimise the size of your logs, you can manually remove these lines using a script, but they are invaluable in resolving issues (eg. determining when a user's EssentialsX data was reset).
