### ISSUE TITLE
ERROR: Could not load 'plugins/EssentialsX-2.0.1.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by retriple333** [EssentialsX/Essentials#834]
Title says it all!

I am On Java 8.

Bukkit works fine,

Essentials isn't.

Help D:

**Comment by SupaHam** [comment]
Title doesn't say it all.
Please Pastebin your server log.

Steps:
1. Open `logs` directory in server directory.
2. Find and open a file called `latest.log`.
3. Go to [www.pastebin.com](http://pastebin.com).
4. Copy all `latest.log` contents and paste into the big text area.
5. Copy & paste the URL in your browser into a reply here.

**Comment by retriple333** [comment]
Lol..

I was on Java 8, and I went back to java 7. Then it worked. Do you not support Java 8 Yet?

**Comment by SupaHam** [comment]
I just told you what to do...

Yes we support java 8, and anything higher probably...

**Comment by retriple333** [comment]
http://pastebin.com/tDPr0MSW

If you need it :D

When I was on Java 8, Btw,

**Comment by SupaHam** [comment]
That's not java 8. That's java 6.
