### ISSUE TITLE
Hide vanished players from server list.

### ISSUE THREAD

**Issue by molor** [EssentialsX/Essentials#837]
Vanished players are visible in the servers list on client.

I mean this:
![2](https://cloud.githubusercontent.com/assets/19989717/17867320/b7485f3e-68b2-11e6-8b1f-33514c1f214f.png)

**Comment by ghost** [comment]
Solution is awaiting merge @ https://github.com/drtshock/Essentials/pull/841

**Comment by ScuroK** [comment]
This problem still exists!
