### ISSUE TITLE
我是中国用户，我想问一下为什么无交互权限（I am a Chinese user, I would like to ask why no interaction permission）

### ISSUE THREAD

**Issue by 417584801** [EssentialsX/Essentials#839]
就是在world世界不用op打建筑会提示这个，想问一下essX的交互权限（破坏权限）是什么（What in the world is a world without op play this building will be prompted to ask ourselves essX interactive privileges (permissions destruction) is）

**Comment by SupaHam** [comment]
This is probably Essentials AntiBuild. You can remove it or properly configure it by following the wiki.

**Comment by 417584801** [comment]
能详细说明一下具体怎么配置吗？（Elaborate on how the specific configuration?）

**Comment by SupaHam** [comment]
http://wiki.mc-ess.net/wiki/AntiBuild
