### ISSUE TITLE
Auto AFK does not respect VanishNoPacket

### ISSUE THREAD

**Issue by Puremin0rez** [EssentialsX/Essentials#84]
In chat, when auto afk does "X is now afk" - even if your vanished, it'll still display the message.

**Comment by Kakifrucht** [comment]
Are you sure that you properly hooked vanish into Essentials?

**Comment by Puremin0rez** [comment]
I assume so, since /near and /list and other things are hiding my status properly in essentials.

**Comment by Kakifrucht** [comment]
I just tried it on my server and cannot reproduce it.

**Comment by Puremin0rez** [comment]
Hm, I have no idea then. Anyone vanished with VanishNoPacket still gets auto broadcasted as "x is now afk". I'll just disable that message for now :)
