### ISSUE TITLE
Request: EssentialsXGeoIP add permission for log in location

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#840]
There is currently one permission to show a players location when they log in and in whois and seen:
essentials.geoip.show
Can we get a separate permission for showing/not-showing Location when they enter the server, its annoying, and then it can only be used in whois and seen.
Another option would be to create a toggle
Another option would be to create a config option in config.yml

**Comment by rye761** [comment]
There is a `show-on-login` config option.

**Comment by pop4959** [comment]
Closing since as rye mentioned, this is already a feature in Essentials.

**Comment by TomLewis** [comment]
Someone is going over old tickets haha, this was from 4 years ago!

**Comment by pop4959** [comment]
You mean me? Yeah, I've been sifting through the old issues to try to filter out ones that should be closed, and make way to give focus towards those that still need attention or are, in general, higher quality issues.

It's actually insane how many of these are already solved, fixed, or are not even valid issues, etc. Cleaning them up should really help a lot.

Also, thanks for putting up with my email spam, as I'm aware you had quite a few open.
