### ISSUE TITLE
Request: Add permission to bypass god in specific worlds.

### ISSUE THREAD

**Issue by TheExceed** [EssentialsX/Essentials#842]
You have the ability to disable god in the config but I cannot find a permission to bypass it

**Comment by drtshock** [comment]
bypass god what

**Comment by TheExceed** [comment]
```
no-god-in-worlds:
  - Resource
  - Vip
```

This, can a permission be added to bypass this setting. @drtshock I use, example, resource as a hardcore world where stuff like /god is not enabled but would like staff to still have it there. Instead of cluttering per world permissions with it, it would be easier to do it with a perm from ESSX

Also, can you have it put a message like saying its not allowed? It still gives the god enabling message, you just take dmg.
EDIT: A message is sent but not sent on command use

**Comment by h4x0r4h1r3** [comment]
> bypass god what
pretty sure he means disabling god in certain worlds

**Comment by pop4959** [comment]
This enhancement is no longer necessary. Modern permission plugins such as LuckPerms allow the world context to be passed in, which effectively renders the `no-gods-in-worlds` feature useless.

For example: if you want a certain player or rank to be able to use god in a world, but not in another, set the permission true with the one world context, and false in the other world context.
