### ISSUE TITLE
Changed nicknames not visible in server list!

### ISSUE THREAD

**Issue by molor** [EssentialsX/Essentials#844]
If a player changed his name with the /nick command, in the server list is still displayed his real name.

![image](https://cloud.githubusercontent.com/assets/19989717/17926926/15216c14-69fc-11e6-8497-aec287bff6c0.png)

**Comment by SupaHam** [comment]
Yes. That's the minecraft server list I assume, the real player name will never change. Their display name in the game however, is what changes.
