### ISSUE TITLE
Bizarre issue with Beacons | Night Vision plugin

### ISSUE THREAD

**Issue by Chalwk** [EssentialsX/Essentials#847]
Hello.

I have a rather bizarre problem involving Essentials. 

Wondering if you could shed some light on the situation?
https://www.spigotmc.org/threads/bizarre-issue-with-beacons-and-night-vision.175504/

Any help with this would be highly appreciated!

Kind Regards,
Chalwk

**Comment by RoboMWM** [comment]
You may want to close this, as you removed the spigot thread - or add the details here.

**Comment by mdcfe** [comment]
Closing as this has been inactive for over a year and details on the issue are no longer available.
