### ISSUE TITLE
Disable collisions when player AFK

### ISSUE THREAD

**Issue by Kixot14** [EssentialsX/Essentials#849]
Disable collisions when player AFK. Can we do it ?

And another suggestion: How can we fix this bug with elytra launcher ?? https://www.youtube.com/watch?v=o56VCNISYI8
It is very annoying! Provoke players to create many boats and then use bug for flying with huge speed and load world!
Maybe add feature to disable collisions with boat entity or something like...

**Comment by RoboMWM** [comment]
> Disable collisions when player AFK.

Player collisions are client-side. The only way to do this is adding a player to a team with all other players, which _could_ cause issues with other plugins that deal with the scoreboard. If you're interested, Paper has an option to disable player collisions.

**Comment by pop4959** [comment]
I believe `freeze-afk-players` should do this, if not it probably isn't supported anymore, as RoboMWM mentioned it works differently in newer versions of MineCraft. His other solution for disabling collisions on the server should work though. Paper has a lot of options when it comes to tweaking gameplay mechanics.
