### ISSUE TITLE
Essentials version bug

### ISSUE THREAD

**Issue by FarisR99** [EssentialsX/Essentials#851]
Hey, I'm not sure if this is intentional, but when using the latest dev release and I type /ess reload, it says '${BUILD_NUMBER}'
![9d90ac008540b0a5071924f4d7650243](https://cloud.githubusercontent.com/assets/3731915/18030433/d56e140a-6cad-11e6-8be3-802af6d40bb7.png)

**Comment by SupaHam** [comment]
@vemacs pls.

**Comment by vemacs** [comment]
O

**Comment by rye761** [comment]
Duplicate of #829.

**Comment by FarisR99** [comment]
Fixed.
