### ISSUE TITLE
Only some custom spawners can be placed by players in survival gamemode

### ISSUE THREAD

**Issue by RoboMWM** [EssentialsX/Essentials#853]
For whatever reason, some spawned-in mobspawners, like mobspawners containing shulker bullets (ID 25) or fireworks (ID 22), while others like armor stand spawners (ID 30) do work when placed in survival. Is this intended/a limitation?

This was tested with gamemode creative vs. survival, was op in both cases.
### Testing procedure
1. Install latest build of EssentialsX.
2. Start server, join as op'd player, in survival gamemode
3. Spawn in mob spawners via `/i spawner:30` and  `/i spawner:22`
4. Place down the spawners. Observe that only some of the spawners (e.g. id 30, the armor stand spawner) will actually be placed, while the rest will remain as pig spawners.
5. Change to creative gamemode.
6. Place spawners. Observe that all spawners will be "converted" respectively.

**Comment by pop4959** [comment]
Closing since this shouldn't be valid anymore with IDs having been removed.

In the current version of Essentials, you can create an armor stand spawner like so:
- /i spawner 1
- place spawner
- /spawner armorstand
