### ISSUE TITLE
Add-ons need version number update

### ISSUE THREAD

**Issue by DelboyDylan** [EssentialsX/Essentials#856]
Since build 428 (to fix internal version number as per #829 ) the internal version of the add-ons do not match the main jar.

![essxaddonversions](https://cloud.githubusercontent.com/assets/20739704/18080014/7abd89f2-6e8b-11e6-91d8-824bc21cee57.jpg)

**Comment by frizzbee30** [comment]
yep, we are getting a version mismatch with the latest build too

**Comment by drtshock** [comment]
ah, you have a point. i only updated the main jar. keep in mind that those warnings don't actually affect anything so nothing is broken while you wait for me to fix it.

**Comment by mdcfe** [comment]
I believe #861 fixes this.
