### ISSUE TITLE
Players can change teleport location after request is sent

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#858]
1. Player 2 sends a TP request to player 1.
2. Player 1 warps to mine, in the 5 seconds (warmup) he has to wait he can do /tpaccept. which takes another 5 seconds (warmup).
3. When player 1 is in the mine, player 2 gets teleported to him despite attempting to teleport to player 1's location before he is teleported.

I understand that may be confusing, quite hard to explain.

**Comment by drtshock** [comment]
So you're saying that the player is teleported to where the other player is at time of teleport instead of where they were when they accepted the request?

**Comment by ghost** [comment]
Yes. This bypasses blocked-cmds in certain areas that are restricted (/tpaccept).

**Comment by pop4959** [comment]
This is intentional. Teleportation will happen once the cooldown is satisfied. If you don't want that to happen, I'd advise removing the cooldown so that the effect of the accepted tp is immediate.

**Comment by TauCu** [comment]
It would be really nice to have a fix for this.

Perhaps just check if the teleporter and teleportee has permission to accept/make such a request in the context both players are in after the warmup elapses.

Removing the cooldown isn't a good solution as that allows players to cheese the system.
