### ISSUE TITLE
Chat message notification of new mails has grammar errors (extra "s")

### ISSUE THREAD

**Issue by VashaTS** [EssentialsX/Essentials#859]
**For example:**
http://i.imgur.com/JKS7SmN.png

**Possible solution:**
Check if number of unread mails == 1, if so display "message";
else display "messages";

**Comment by Kakifrucht** [comment]
I think it's fine as it is.

**Comment by VashaTS** [comment]
Still a bug, even if low priority one

**Comment by Kakifrucht** [comment]
I wouldn't even interpret it as a bug. Doing this is very common. It says "1", and not "one", or "a". In that context, number + pluralized form is completely fine from my understanding, even if it's just one message.

**Comment by drtshock** [comment]
I mean.. If this is the kind of thing people say is wrong with the project, I think we did a decent job.

**Comment by FarisR99** [comment]
It's not that easy to fix (as suggested) because the messages are configurable. In my own private plugins, I add a configurable placeholder '%plural%' after 'message', i.e. 'message%plural%' and if messages != 1, %plural% is replaced with 's' otherwise it's replaced by an empty String.

I do agree that it would be nice if this was 'fixed'.

**Comment by Kakifrucht** [comment]
Such a %plural% placeholder is not compatible with every language.

**Comment by FarisR99** [comment]
Then only make %plural% in the languages that have the rule '1 is singular'?

**Comment by drtshock** [comment]
Sounds pretty ethnocentric ;)

**Comment by FarisR99** [comment]
Uhm sure but Essentials was created by English developers... The fact it has support for multiple languages itself is good enough. Whatever, if you don't want to do this then just say lol.

**Comment by vemacs** [comment]
Plurals are hard
