### ISSUE TITLE
Kit drop

### ISSUE THREAD

**Issue by Johandrex** [EssentialsX/Essentials#86]
Could you fix so if you have a full inventory the rest of the kit doesn't gets dropped on the ground? That'd be awesome

**Comment by TheJadyha** [comment]
Agreed, Instead, An error message should be displayed telling the player that he needs more room in his inventory.

**Comment by FlippantCactus** [comment]
Does this no longer happen? Used to work on original Essentials branch

**Comment by Johandrex** [comment]
Bump

**Comment by Cldfire** [comment]
This was already implemented on the original Essentials branch...

**Comment by Johandrex** [comment]
Doesn't work with kits. I don't want the items to be dropped.

**Comment by Johandrex** [comment]
Guess it's not being fixed..

**Comment by Cldfire** [comment]
Patience.
