### ISSUE TITLE
/clear doesn't clear armor or off-hand slots

### ISSUE THREAD

**Issue by mawkews** [EssentialsX/Essentials#860]
Spigot 1.10.2
Essentials 2.1.0-b428
same for
/clearinventory
/clearinvent
/ci
In regular 1.10.2 minecraft the /clear command does clear everything

**Comment by Kakifrucht** [comment]
Github issues has a search function.

#653

**Comment by mawkews** [comment]
@Kakifrucht "/clear all" says player not found

**Comment by mdcfe** [comment]
`/clear <player> *`

**Comment by YonatanAhituv** [comment]
Still doesn't work, reopen the issue

**Comment by jahlib** [comment]
try 
/clear nickname **
it works for me
