### ISSUE TITLE
Can't create [Buy](etc.) sign

### ISSUE THREAD

**Issue by imDaniX** [EssentialsX/Essentials#863]
Spigot 1.10.2
Plugins: EssentialsX 2.0.1 (+ XAntiBuild,XChat,XProtect,XSpawn,XGeoIP)
When trying to create [Buy]-sign it leaves blank sign. 
Also, when trying to create [Trade]-sign it leaves blank sign and takes specified item(s).
These signs are enabled in config.

**Comment by SupaHam** [comment]
Duplicate of #687. Update spigot.
