### ISSUE TITLE
Flame arrows in god

### ISSUE THREAD

**Issue by NewBestX** [EssentialsX/Essentials#871]
If a player in god mode shoots a bow with flame, the arrow itself won't damage the player, but the fire effect will still apply, so the player will take damage from the fire.
^Good to mention that the player does not have the permission essentials.god.pvp

**Comment by Kakifrucht** [comment]
Commit that caused it: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/71e5248c8b97a6345a367543bdb8a85477baf81b

**Comment by fieu** [comment]
@Kakifrucht :+1:

**Comment by drtshock** [comment]
:(

**Comment by vemacs** [comment]
Could be worth introducing compatibility if people care enough

**Comment by NewBestX** [comment]
It looks like this issue hasn't been fixed to this day. Sorry if I'm wrong.

**Comment by NewBestX** [comment]
@md678685 @SupaHam This hasn't been fixed to this day.

**Comment by SupaHam** [comment]
This has been fixed in 13fbd311. You can grab the fix from [build 519](https://ci.drtshock.net/job/EssentialsX/) on the CI server.
