### ISSUE TITLE
[request]player owned warps just like with homes

### ISSUE THREAD

**Issue by mawkews** [EssentialsX/Essentials#873]
players can create and delete their own warps

**Comment by rye761** [comment]
I don't quite understand. What do you need that homes or warps doesn't do?

**Comment by drtshock** [comment]
^

**Comment by mawkews** [comment]
I want to put a limit on the amount of warps players can set
and not be able to delete each others warps

**Comment by RoboMWM** [comment]
> I want to put a limit on the amount of warps players can set
>  and not be able to delete each others warps

Isn't this describing the /home feature?

**Comment by rye761** [comment]
This is basically the `/home` feature. I'm not sure if you are aware, but players can access other players homes if they have the `essentials.home.others` permission.

**Comment by mawkews** [comment]
is it possible to do the same thing except with warps?

**Comment by RoboMWM** [comment]
@Markersx, he just explained how this is possible with the /home feature.

That being said, you can give permission to set warps, but not delete warps, if you _so_ desire to do that. However, they won't be able to delete warps they make. I strongly suggest you just use the /home feature as rye761 stated above.

**Comment by mdcfe** [comment]
Closing as this just appears to be asking for `/warp` to duplicate home functionality.
