### ISSUE TITLE
Original essentials maven repo is down [BREAKS BUILDING]

### ISSUE THREAD

**Issue by sgdc3** [EssentialsX/Essentials#877]
The repo.ess3.net maven repo is offline, thsi means that EssentialsX willfail building due to missing dependencies. @drtshock Could you move the deps to your repo?

**Comment by drtshock** [comment]
aww :( @khobbits any input on this?

**Comment by khobbits** [comment]
I can't remember who hosted that.  Think it was either Chrisward or ementalo.  If you rehost I can point the domain to the new one.

**Comment by fieu** [comment]
Doesn't LGTM. 😕 

![Turtle Fail](https://m.popkey.co/61dfd9/mzAR7.gif)

**Comment by drtshock** [comment]
Yeah we have someone that sponsors an OVH vps for us for the CI. Can just put it on there.

**Comment by sgdc3** [comment]
@drtshock why don't you just use the jenkins repository plugin?

**Comment by drtshock** [comment]
https://ci.drtshock.net/plugin/repository/

**Comment by drtshock** [comment]
But it doesn't seem to publish. Working on that..

**Comment by sgdc3** [comment]
It works only if you use the "install" task i think @drtshock

**Comment by drtshock** [comment]
I'm running clean install as the maven goal. I have it setup to archive build artifacts to the maven repo as a post build action. Not sure what else to do.

**Comment by sgdc3** [comment]
repo.ess3.net seems to be online again ;) @drtshock

**Comment by sgdc3** [comment]
Should we thank someone for that? :D
