### ISSUE TITLE
Tablist order

### ISSUE THREAD

**Issue by Platinteufel** [EssentialsX/Essentials#879]
Since I've updated to the latest dev build from an earlier release my tablist order messed up.
In the past it was in alphabetical order, but now I don't get it at all ..

![tablist order](https://cloud.githubusercontent.com/assets/13700636/18356482/131be7b2-75ed-11e6-9e94-4c78b11f1e5c.png)

**Comment by vemacs** [comment]
What server version are you running? Are you behind a proxy?

**Comment by Platinteufel** [comment]
latest PaperSpigot, 1.10
Nope, I don't use a proxy. 

It happens since the "addPlayerPrefixToTablist" update, even I'm not using it

**Comment by Platinteufel** [comment]
Okay, seems like it has to do something with different /scoreboard players values on my server. I think you don't touch this, right?
