### ISSUE TITLE
Blacklisted Nicknames

### ISSUE THREAD

**Issue by Log1x** [EssentialsX/Essentials#88]
Possible Enhancement Suggestion here.

Add a list of nicknames that users aren't allowed to switch too, and a permission to override that list.
Obviously strip color codes when comparing to the blacklisted nickname.

A lot of servers don't really mind that Users change their nicknames freely, but them changing it to a Staff's name or notch/jeb_ can be a little annoying.

Just a thought. Delete if not interested. :)

**Comment by denizaygundev** [comment]
Great suggestion, would love for this to be implemented with!

**Comment by TheJadyha** [comment]
Agreed

**Comment by denizaygundev** [comment]
Realistically there's no need for this, just thought about it, there's plenty of plugins out their that can block things from being said in commands/chat, check out PwnFilter or Chatcontrol.

**Comment by mdcfe** [comment]
This has now been implemented - you can download the latest version from [here](https://essentialsx.netlify.com/downloads.html).
