### ISSUE TITLE
Thermos serverlist ping issue

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#880]
Hi, so I'm using essentialsx on my thermos (pixelmon) server and I'm getting this issue: http://pastebin.com/1zKk4fRK it spams this each time a player pings the server on the server list. Is there a chance this can be fixed or would I have to try reverting to an older version? I used the latest as spigot stated it should work with 1.7

More information:
- Server version : https://gyazo.com/d46f288f014bc6f99e46665d395bac84
- EssentialsX version : v2.0.1-b429

**Comment by Kakifrucht** [comment]
That's a Thermos issue, the dev didn't implement the iterator() method of ServerListPingEvent.

**Comment by SupaHam** [comment]
https://github.com/drtshock/Essentials/pull/868#issuecomment-244369011
