### ISSUE TITLE
cant seem to get kits to work

### ISSUE THREAD

**Issue by seeker17** [EssentialsX/Essentials#882]
First let me start baby saying that I am new to this whole running a server thing, so i'm sorry if this is a stupid question,

I am trying to set up specific kits for specific ranks, but when I try to give a group access to for example kit "starter" I give the group the perm for essentials.kit.starter but it does not give them access to the kit, and if I do /kits it says "there are no kits available yet." Any help would be greatly appreciated!

**Comment by SupaHam** [comment]
http://www.pastebin.com your `config.yml` file found inside `plugins/Essentials`.

**Comment by seeker17** [comment]
Here you go.
http://pastebin.com/tJF9sfC1
Also thanks for the super fast reply.
I also have tried a kit "1" to see if it was a case sensitive issue, that did not work either.

**Comment by SupaHam** [comment]
Try `essentials.kits.starter`, note the s in kits.

**Comment by seeker17** [comment]
I have been trying for over 4 hours trying to figure out what I was doing wrong.....one simple s. _grabs diamond shovel_ "well i'm off to bash my skull in!"

but seriously thank you for your help.

Also I do have one more question, do you see anything in my config that would stop colored chat from working? It was working at the start, then my friend removed nifty chat (which wasn't working correctly to begin with) and it stopped working. It does not even work when i am op'ed.

**Comment by SupaHam** [comment]
In order for Essentials to color chat messages EssentialsXChat needs to be
installed. You can grab that from the CI server https://ci.drtshock.net.

**Comment by seeker17** [comment]
Thank you,

but now I have another issue, my prefix shows up twice. https://gyazo.com/81b2bde4987562bf2c00f2e3e885a4b5

**Comment by SupaHam** [comment]
Do you have that prefix in your nickname (`/nick`)? If not, you probably have it inside either your prefix or the group prefix and your permissions plugin adds both of them or something.

**Comment by seeker17** [comment]
There is no prefix in my nick, I also got rid of my custom prefix that I gave myself with pex, now I have a normal groups prefix but I am still having this issue. I did some looking around and I am not the only one to have this issue, it seems to be both pex and essentials chat are giving prefixes. But every solution that I find tells me to go into essentials config and find and set "add-prefix-suffix:to false." but I cant seem to find it in my config. Here are paste bins to all of the configs for both pex and essentials, maybe you will see something that I don't.

Essentials:
http://pastebin.com/W27E0WKz

PermissionsEX:
config: http://pastebin.com/quPaQTir
permissions: http://pastebin.com/aBDCTi0u

I am sorry for asking you to look at stuff for another plugin, but im and the end of my rope.

**Comment by seeker17** [comment]
Okay, i have an update. My friend and I managed to narrow down the issue to towny chat. We have since fixed the double prefix issue, but now we have a ~ in front of nicknames. Any idea how we fix this?

**Comment by SupaHam** [comment]
Check Essentials' config. it should be at the top :)

**Comment by seeker17** [comment]
Thank you so much for all of your help, I really do appreciate it. You have helped me a ton!

**Comment by seeker17** [comment]
I'm sorry, I really am. I cant seem to get signs to work, i.e. balance, i put in the first row [Balance] but it still does not work :/.....sorry for being a noob lol

**Comment by SupaHam** [comment]
You should create an issue for each issue you're having. In the case that "does not work" means the signs go blank, it's not your fault, it's spigot's fault, see #687. Updating spigot should do the trick.
