### ISSUE TITLE
1.8-1.10 potions???

### ISSUE THREAD

**Issue by Elgorond** [EssentialsX/Essentials#883]
http://prnt.sc/cgarbb

the kit with the pot: http://hastebin.com/isoneruliv.sm

Is this something I just have to deal with because I'm allowing 1.8-1.10 users?

**Comment by Elgorond** [comment]
The pots are supposed to be healing I. In 1.8 it shows it as that, but in 1.10 it's all weird.

**Comment by mdcfe** [comment]
We can't help with issues caused by multi-version protocol hacks. If you can replicate the issue without the protocol hacks installed, feel free to reopen the issue.
