### ISSUE TITLE
Hide join message for joined player.

### ISSUE THREAD

**Issue by molor** [EssentialsX/Essentials#885]
Can you add this option to config file, please?
I wish this message had only seen the other players on the server.

**Comment by mdcfe** [comment]
Why wouldn't you want the player to see their own join message?

**Comment by molor** [comment]
@md678685, I think that the message that tells the joined player that he joined the server, is obvious and meaningless.

**Comment by mdcfe** [comment]
It appears once, when the player logs in, and is at most one or two lines long. I fail to see the point of hiding it from them, it's not like it takes up excessive amounts of space in chat.

**Comment by Elgorond** [comment]
It does take up excessive amounts of space in chat if you have a busy server.

Edit: Read the OP wrong... yeah this shouldn't have to be a feature.

**Comment by drtshock** [comment]
It's part of Minecraft though.
