### ISSUE TITLE
/recipe showing missing/corrupt textures

### ISSUE THREAD

**Issue by exoticmanta** [EssentialsX/Essentials#889]
the /recipe command seems to be showing missing or corrupt textures for some outcomes. (ex https://www.dropbox.com/s/66mfuxcvivndk58/2016-09-14_11.37.33.png?dl=0) while others seem to display with no problems (ex:https://www.dropbox.com/s/x2o0yhpyqy4vtsk/2016-09-14_11.37.53.png?dl=0)

server is running spitog 1.10. im not 100% with snapshot im running of essentials, but its a few months old

**Comment by mdcfe** [comment]
Check your client mods are up-to-date? This doesn't look like an Essentials issue to me.

**Comment by rye761** [comment]
I agree this looks like a client issue. Could you try to reproduce the bug with a vanilla minecraft client and the latest build of essentials? Doing `/recipe beacon` shows the recipe fine for me.

**Comment by exoticmanta** [comment]
I don't think its client side as all my players report the same issue

**Comment by rye761** [comment]
While that does make a better case for this being a server side bug, it doesn't confirm it. If it is a problematic client mod, your players may just be running the same mod as you and thus have the same problem. You mentioned your version of EssentialsX was a few months old. Please try it again with the latest version and a totally vanilla minecraft client. If the problem persists, it could be an issue with another plugin. Try starting the server with only Essentials enabled and then see if the problem remains. If it does, then this is a real bug. As it stands, I'm unable to reproduce with with a vanilla minecraft client, the latest version of EssentialsX and Minecraft 1.10.

**Comment by exoticmanta** [comment]
has been fixed. thankyou
