### ISSUE TITLE
Add /msgtoggle

### ISSUE THREAD

**Issue by FlippantCactus** [EssentialsX/Essentials#89]
Add /msgtoggle which mirrors /tptoggle but for /msg 
![2015-07-12_23-08-31](https://cloud.githubusercontent.com/assets/3855601/8640304/402ec8d2-28eb-11e5-8e6e-c9fc4488ce9d.png)
Was requested and I'd like to see it too :)

**Comment by baticag** [comment]
I would like this one too! Great command for big servers!

**Comment by EvilOlaf** [comment]
Might be a stupid question but what is this supposed to do?

**Comment by Kakifrucht** [comment]
Disable the possibility to /msg you I guess, just like /tptoggle disables /tp and /tpa's.

**Comment by TomLewis** [comment]
Jesus we need this, any member of staff will know the feeling of people /msg adminusername useless-time-wasting-message

We need this.

**Comment by EvilOlaf** [comment]
Hm yes, sounds like a pretty nice feature :P

**Comment by drtshock** [comment]
Will definitely get added.

**Comment by FlippantCactus** [comment]
Yay :)

**Comment by vemacs** [comment]
Let me know if this works.

**Comment by baticag** [comment]
It gives me Unknown command...

**Comment by vemacs** [comment]
Try the next build

**Comment by baticag** [comment]
You missed the message sent to player when doing command: when it's enabled you cannot send messages to player, and when it's disabled you can. Also when it should be disabled I can send messages and it's shown to me that I send them, but user doesn't receive them. Can you add that it sends message to user that they cannot send messages to that player?

**Comment by vemacs** [comment]
The command is sent to the player when running the command. I'm copying msg /ignore behavior for the player sending the message to the user that's ignoring. Generally people ignoring messages don't want people to know that they're ignoring messages.

**Comment by baticag** [comment]
Ok, but fixed the first bug please.
First message sent to me when entering command for first time is: Receving messages enabled. (but they are disabled)
And when I type it again it shows me: Receving messages disabled. (but they are enabled).

**Comment by vemacs** [comment]
First bug fixed, was due to bad naming on my part.

**Comment by Mikgreg** [comment]
Essentials forgets you have messages toggled off when you log off, can it remain disabled permanently like /tptoggle does?

**Comment by justwheel** [comment]
@Mikgreg: Might want to just make a new issue in the tracker for that.
