### ISSUE TITLE
Default /home.

### ISSUE THREAD

**Issue by molor** [EssentialsX/Essentials#893]
Hello,

Can you make home "home" default if player typed /home without any arguments and have homes "home" and "home2" (for example)?

I noticed that most of my players having a few houses, it is necessary first to write to /home, then /home home to get into the first house. And I think it would be nice if the default player moved into the home "home". A list of all homes can see with the command /homes.

**Comment by drtshock** [comment]
I'm not sure what you're even asking for here. Can you try to reword it?

**Comment by molor** [comment]
Oh.. Sorry for my bad English.

Player joined the server for first time.
Player performed "/sethome" command.
Now, if player performs "/home" command, it will be teleported to home "home".
Player performed "/sethome h2" command.
Now, if player performs "/home" command, it will receive the following message: "Homes: home, h2, bed".
To teleport to the "home", you need to write "/home home" instead of "/home".

I would like to see if "/home" command is performed without arguments, then it would be identical to "/home home". "/homes" command is used to show a list of all player homes.

**Comment by Kakifrucht** [comment]
I think this was requested already. I rather have a list with /home.

**Comment by molor** [comment]
It would be possible to add setting to config file that switch between the old mode and the proposed mode..

**Comment by rye761** [comment]
#881 was opened with the intention to fix this. Seems to be pretty much dead though.

**Comment by mdcfe** [comment]
Closing in favour of PR #881 which implements this (and has further discussion of the idea).
