### ISSUE TITLE
Teleportation delay API

### ISSUE THREAD

**Issue by RoboMWM** [EssentialsX/Essentials#895]
Unless I'm blind, is there a way to determine when a player is waiting to be teleported in EssentialsX? Basically I'd like to play a particle effect while the player is warming up to teleport. This is currently how I'm (dumbly) doing it: https://github.com/MLG-Fortress/MountainDewritoes/blob/master/src/main/java/me/robomwm/MountainDewritoes/TeleportingEffects.java

Short of re-implementing teleportation commands, I'm not aware of any other way to do this while using EssentialsX' teleportation. Is it possible an API/event can be added for this?

**Comment by drtshock** [comment]
Nothing currently but PRs are always nice <3

**Comment by Kakifrucht** [comment]
There is Essentials.getUser().getTeleport(), maybe you could use that to check if the teleport is still active at least? Unsure if it works as expected.

**Comment by pop4959** [comment]
Not sure if you still need this, but as drtshock mentioned, PR's are always welcome.
