### ISSUE TITLE
what happened to groupmanagerX?  alternative suggestions?

### ISSUE THREAD

**Issue by Sidious82** [EssentialsX/Essentials#898]
i noticed upon trying to update recently that groupmanagerX is no longer part of the essentialsX package.  maybe im blind but this came out of nowhere to me and I am hoping somebody can help with a link to active development and/or alternative compatible group manager suggestions.
thank you for your time and consideration

**Comment by Elgorond** [comment]
I would consider trying out LuckPerms on spigot. They also support migrating from GM to LuckPerms.
https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-system.28140/

**Comment by SupaHam** [comment]
There never was a GroupManagerX
