### ISSUE TITLE
Empty newbies 'announce-format' gives blank line

### ISSUE THREAD

**Issue by Log1x** [EssentialsX/Essentials#90]
When you have an empty 'announce-format' under newbies in the config (for example, when using DeluxeJoin), it will send a blank line to all users when someone connects (whether they are a newbie or not).

This should be an easy fix and would be greatly appreciated as it's quite bothersome. For now I just use '§' so at least it doesn't effect all players who join.

**Comment by Agazed** [comment]
Post your config please.

**Comment by drtshock** [comment]
Put 'none' as the join message and it won't broadcast anything.
