### ISSUE TITLE
config comments deleted

### ISSUE THREAD

**Issue by SlimeDog** [EssentialsX/Essentials#901]
As of relatively recently, comments in config.yml are deleted on server reboot or user connection. This is most unfortunate. Can that change be backed out?

**Comment by drtshock** [comment]
If you edit it with createkit they will be deleted.

**Comment by SlimeDog** [comment]
I did not edit in any manner, of which I am aware. I do not use Essentials kits. I will try to create a reproducible case.

**Comment by SlimeDog** [comment]
Tried for an hour, could not reproduce the issue. I will open a new ticket if I am able to stumble upon a scenario. Thanks.
