### ISSUE TITLE
essentials.keepxp not working

### ISSUE THREAD

**Issue by PhanaticD** [EssentialsX/Essentials#904]
with the permission node essentials.keepxp XP is not kept on death, tested with permission node and as OP

**Comment by Elgorond** [comment]
It works for me...?

**Comment by PhanaticD** [comment]
not for me :O

**Comment by mdcfe** [comment]
If this is still an issue, could you reopen this and paste the output in console when a player dies and respawns with `/ess debug` enabled?

**Comment by PhanaticD** [comment]
sorry found out a while ago it was another plugin, MassiveCombat/MassiveCore causing this
