### ISSUE TITLE
AFK suggestion

### ISSUE THREAD

**Issue by Borc55** [EssentialsX/Essentials#905]
,,Greetings, you probably got this idea multiple times, but is it possible to add /afk (reason). In case you don't want to remove the (player) thing, you can maybe add another command like /afkr (reason). In my opinion, /afk (player) is pretty useless since you can do /sudo (player) afk. But that's just my point of view. Thanks for reading."

**Comment by Kakifrucht** [comment]
This makes no sense at all.

**Comment by Borc55** [comment]
How so?

**Comment by Borc55** [comment]
Oh I see, it got corrupted. I just copy pasted it from different log. Fixed it.

**Comment by Kakifrucht** [comment]
You could take away the permission to set other players afk status. This way /afk reason will be the default.

**Comment by Borc55** [comment]
Wait, afk reason is already implemented? I never saw it anywhere in config/commands of EssentialsX. I'm sorry in that case.

**Comment by Kakifrucht** [comment]
Yes here https://github.com/drtshock/Essentials/commit/5842b5f51d3b14be82a93a1142d8780a9aff2911

**Comment by Borc55** [comment]
Thanks for being kind. Tho when I type /afk (message), it doesn't show it, I checked en_messages and there's not even a tag for reason, it's written the same way as normal AFK.

userIsAway=\u00a77* {0} \u00a77is now AFK.
userIsAwayWithMessage=\u00a77* {0} \u00a77is now AFK.

I tried adding {1} to the userIsAwayWithMessage, it didn't work tho. Is that an error or my mistake?

**Comment by Borc55** [comment]
Thanks for being kind. Tho when I type /afk (message), it doesn't show it, I checked en_messages and there's not even a tag for reason, it's written the same way as normal AFK.

userIsAway=\u00a77\* {0} \u00a77is now AFK.
userIsAwayWithMessage=\u00a77\* {0} \u00a77is now AFK.

I tried adding {1} to the userIsAwayWithMessage, it didn't work tho. Is that an error or my mistake?
Reason only shows when typing a /msg to afk player.

//EDIT
They can't even be translated/changed, maybe that's why.

**Comment by Kakifrucht** [comment]
Adding {1} should work though. The default language file is not messages_en.properties, but just messages.properties.

**Comment by Borc55** [comment]
I have messages_en set in the config, every other change I did in the messages has updated, only those two didn't.
(userAFKWithReason and userIsAwayWithReason)
Tried it on localhost with fresh config, same result, every message can be changed, only those two are kept the same.

**Comment by Kakifrucht** [comment]
He actually renamed the message keys [here](https://github.com/drtshock/Essentials/commit/4951c4822eabf55f2d06b936a8e8ce8f071fed1d), use userAFKWithMessage anduserIsAwayWithMessage instead.

**Comment by Borc55** [comment]
I see, thanks a million, pretty sure that's gonna work.

**Comment by mdcfe** [comment]
Should this be closed now?
