### ISSUE TITLE
"/sell" sells named items but using signs doesn't

### ISSUE THREAD

**Issue by mawkews** [EssentialsX/Essentials#908]
When you use a sell sign to try to sell a named item it won't work but if you use /sell hand or /sell all it will sell the named items. They both should work the same way or be configurable. I would like to disable named item selling when using /sell because players are abusing this to sell cosmetic gadgets.

**Comment by LaughNgamez** [comment]
If anyone is interested in privately making this change I'll happily make a commission for it :)

**Comment by LaughNgamez** [comment]
In addition to adding this /removename would be a cool command.
