### ISSUE TITLE
[Request] Configurable Spawner Name Format

### ISSUE THREAD

**Issue by PetKCH** [EssentialsX/Essentials#909]
As the title say, could you please add in config variable with which I could configure names format of the spawners bought over EssX signs? As of now, not a single silk spawners plugin I am using has same format for spawners once they are mined causing diffrent names with incompatible stacking with ones purchased from EssX signs.

As I see, for example SilkSpawners dev make SilkSpawnersShopAddon plugin which is basically a sign shop for spawners, which "fixes this", however its premium and I sadly wasted cash even tho its poorly optimized and has often boot issues.

I think giving a option to format ourselves spawners name could solve this and save some people cash :)

**Comment by pop4959** [comment]
This should probably be fixed on SilkSpawner's side. If the player acquires spawners, that plugin should be renaming them. There's no point in adding this to Essentials.
