### ISSUE TITLE
Command Suggestions

### ISSUE THREAD

**Issue by CoolV1994** [EssentialsX/Essentials#91]
I have a few suggestions for commands that Essentials always needed but never had.

/tpposw - Teleport to a specific position in a specific world.
/tprandom - Randomly teleport to a location.
/namecolor - Colorize your username.

And a bug fix:
With Mojang /tp, you can `/tp ~ ~10 ~` to go up 10 blocks.
With Essentials, you get an error. You have to use as `/tp ~0 ~10 ~0`

I can submit the code in a pull request, I already have it written.

**Comment by EvilOlaf** [comment]
I think there is no need to add an additional command. Just add a 4th argument to `/tppos` which contains the world, like
`/<command> <x> <y> <z> [yaw] [pitch] [world]`
If there are no valid numbers for `yaw` and `pitch` provided check for a valid `world` name and use it instead. So the last three arguments are still optional and would not break any existing commands like in command blocks.

2nd: http://dev.bukkit.org/bukkit-plugins/randomlocation/ ^^
3d: https://www.spigotmc.org/resources/namemanager.5147/ ^^

**Comment by drtshock** [comment]
I can agree with @EvilOlaf on all of that. No new command, just add an arg.
