### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by Forestage** [EssentialsX/Essentials#915]
03.10 19:34:05 [Server] WARN Task #6401 for Essentials v2.0.1-b434 generated an exception 03.10 19:34:05 [Server] INFO java.lang.NullPointerException 03.10 19:34:05 [Server] INFO at com.earth2me.essentials.xmpp.XMPPManager.updatePresence(XMPPManager.java:148) ~[?:?] 03.10 19:34:05 [Server] INFO at com.earth2me.essentials.xmpp.EssentialsXMPP.updatePresence(EssentialsXMPP.java:109) ~[?:?] 03.10 19:34:05 [Server] INFO at com.earth2me.essentials.xmpp.EssentialsXMPPPlayerListener$1.run(EssentialsXMPPPlayerListener.java:31) ~[?:?] 03.10 19:34:05 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 03.10 19:34:05 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 03.10 19:34:05 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 03.10 19:34:05 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 03.10 19:34:05 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24] 03.10 19:34:05 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]

**Comment by SupaHam** [comment]
Please pastebin your whole server log for more help.

Steps:
1. Open `logs` directory in server directory.
2. Find and open a file called `latest.log`.
3. Go to [www.pastebin.com](http://pastebin.com).
4. Copy all `latest.log` contents and paste into the big text area.
5. Copy & paste the URL in your browser into a reply here.

**Comment by mdcfe** [comment]
Closing due to a lack of response.
