### ISSUE TITLE
Kits cannot save item attributes

### ISSUE THREAD

**Issue by MithrandirCraft** [EssentialsX/Essentials#916]
Just as the title says. Essentials kit saving cannot manage item attributes. Please add support for the new 1.10.2 attributes.

I think specifying a version here is unnecesary. EssentialsX simply doesn't manage this, therefore saving items directly from inventory is innefective if these items have attributes.

**Comment by MithrandirCraft** [comment]
plox.

**Comment by Kakifrucht** [comment]
There are already 2 other tickets about the same thing, how about closing this one instead of bumping every single thread?

**Comment by MithrandirCraft** [comment]
Yeah, I'm just trying to point out this issue. But that's obvious. Do as you wish.

**Comment by mdcfe** [comment]
I'm fairly certain there's a lot of work to do before it's even worth adding support for attributes - including reworking the config system, which has been suggested numerous times.

**Comment by MithrandirCraft** [comment]
A lot of work before it's even worth... It's 1.10.2, and attributes have been around since 1.6, but still no support for them allthough they are now a basic item component.

I don't know what Essentials's priorities are, so I won't judge. I'll just say I personally feel absolutely confortable with the current config format. So if remaking the config is prioritary, maybe Attributes could be added along the way.

**Comment by mdcfe** [comment]
Closing as this is a duplicate of #838.
