### ISSUE TITLE
command /setworth improvement

### ISSUE THREAD

**Issue by Brend-Smits** [EssentialsX/Essentials#917]
Hello,

I have a small suggestion which will spare a lot of people a great bunch of time. 
Would it be possible to add a function when you do /setworth it will take the material name+Metadata (example: ProjectE_Nova_cataclysm:3) from the item that you are currently holding? 

Or maybe add a function where you type /setworth hand price it will take the item in your hand? 
This will save people from adding 1000's of items by themselves.

Thank you in advance.

**Comment by WesJD** [comment]
You can currently do `/setworth <price>` with the item you want in your hand to set the price. Is this not what you want?
