### ISSUE TITLE
Version Mismatch Error In Console

### ISSUE THREAD

**Issue by jpalip** [EssentialsX/Essentials#92]
Hi,

So upon startup on my server, I get this error message that says:
11.07 12:28:39 [Server] WARN §4Version mismatch! Please update EssentialsSpawn to the same version.
11.07 12:28:39 [Server] WARN §4Version mismatch! Please update EssentialsChat to the same version.
11.07 12:28:39 [Server] WARN §4Version mismatch! Please update EssentialsProtect to the same version.
EssentialsX Version: 2.0.1
Spigot Version: CraftBukkit version git-Spigot-ec3f46e-2359f6f (MC: 1.8.7) (Implementing API version 1.8.7-R0.1-SNAPSHOT)

Thanks,
Flub (JP A.)

**Comment by vemacs** [comment]
Harmless message, please ignore. You can download EssentialsSpawn/Chat/Protect from the CI if you really care.
