### ISSUE TITLE
Essentials Go Crazy !

### ISSUE THREAD

**Issue by MatinHQ** [EssentialsX/Essentials#920]
Essentials Plugin Spam This Error On My Server Error :
[18:41:43 WARN]: [Essentials] Task #28 for Essentials vTeamCity generated an exception
java.lang.NullPointerException
And Sometimes Give Randomly Players Fly !
I Use Essentials For My All Server Skyblock Lobby and ..... and work fine but on survival spam this error

**Comment by Kakifrucht** [comment]
That is neither enough information, nor the correct place to report issues with TeamCity/Spigot Essentials. You are not using EssentialsX.
