### ISSUE TITLE
Killall Monsters - not working

### ISSUE THREAD

**Issue by EverNife** [EssentialsX/Essentials#922]
#### Current behavior

`/killall monsters` is not working
#### Steps to reproduce (for bugs)

1. Use `/killall monsters` or, by console `/killall monsters DIM-name`
#### Console output

1.
![image](https://cloud.githubusercontent.com/assets/11357801/19210492/428f79f8-8cfb-11e6-9555-936be18042ab.png)

2.
![image](https://cloud.githubusercontent.com/assets/11357801/19210510/b4d2fa76-8cfb-11e6-9a47-84ecf3037910.png)

Same thing for every world, it just... dont kill the monsters..
#### My environment

- Server platform:  _Thermos 57_
- Server version: _1.7.10_
- EssentialX version: **_2.0.1-b434**_

**Comment by EverNife** [comment]
https://github.com/drtshock/Essentials/issues/931 is related to this :D

**Comment by mdcfe** [comment]
Looks like a 1.7.10 bug - I haven't yet reproduced this on 1.10.2, but I'll see if I can.

**Comment by mdcfe** [comment]
1.7.10 is no longer supported.
