### ISSUE TITLE
Sign direction (North/South) change the colours

### ISSUE THREAD

**Issue by Twonox** [EssentialsX/Essentials#923]
http://image.noelshack.com/fichiers/2016/40/1475926001-2016-10-08-13-19-46.png
http://image.noelshack.com/fichiers/2016/40/1475926003-2016-10-08-13-19-54.png

**Comment by mdcfe** [comment]
The colours are identical; they look different due to lighting.

**Comment by Twonox** [comment]
No, at night there is same problem.

**Comment by mdcfe** [comment]
@Twonox: my point remains;

> The colours are identical; they look different due to lighting.

The client shades some faces automatically IIRC - this is not an Essentials bug.

**Comment by Kakifrucht** [comment]
@md678685 is right, this is, if even, a Minecraft rendering bug. Look at the signs background, you can see that they are differently lit.

**Comment by Twonox** [comment]
The colors are managed by Essentials, it's not possible to fix that ?

**Comment by Kakifrucht** [comment]
..
I don't really know what to tell you to make it clear to you. What did you not understand? This issue has nothing to do with Essentials.

**Comment by Twonox** [comment]
I understand but it's only the colors who have lighting problem and they are managed by essentials... I just ask if it's possible to fix it even if it's a Minecraft issue.

**Comment by Kakifrucht** [comment]
No

**Comment by mdcfe** [comment]
No, the colours are managed by your client. All Essentials does is turn &0 into "Minecraft please make this black" and &6 into "Minecraft please make this gold" - it's up to the client to render this, and vanilla doesn't fully support coloured signs anyway. Report it as a Minecraft bug if it is such a big issue.

**Comment by Twonox** [comment]
Okay I see, thanks.
