### ISSUE TITLE
per-world-spawnpoint

### ISSUE THREAD

**Issue by Platinteufel** [EssentialsX/Essentials#925]
Hello,

is it possible to implement serveral spawnpoint for different worlds? It would be very helpful for me if I could type `/spawnpoint mainWorld` and only respawn at this spawnpoint if I die in mainWorld.
Thanks!

**Comment by Platinteufel** [comment]
Just a little explanation: I'm running a survival server with an adventure world with some cool minigames. Every minigame has it's own lobby where you can wait for other players and after start you'll get teleported to the map. Additionally I set the lobby as respawnpoint for the players, so that they spawn in lobby if they die (= loose the minigame) and can play it again. But if they go back into the survival world and die there, they won't respawn next to their bed, but in the minigame lobby where their spawnpoint is set. That's confusing and annoying for the most of my players. 
An easy solution would be if I could set `/spawnpoint adventure` instead of `/spawnpoint`, so that they would only respawn in the minigame lobby if they die in my adventure world and otherwise next to their bed in survival.
I don't now if it's (technically) possible to implement this into EssX, but it would be awesome if an experienced developer could take a short look into it and implement/PR this feature. 
A thousand thanks for your help!

**Comment by vemacs** [comment]
Multiverse-core has this functionality

**Comment by Platinteufel** [comment]
Hm? It is able to respawn players at the worlds spawn (mv spawn), but not at a specific point in world. Please correct me if I'm wrong @vemacs.

**Comment by Platinteufel** [comment]
Thanks anyway.

**Comment by Platinteufel** [comment]
I've tried it with MV-Core, but it doesn't respawn players at a specific point in world. It isn't possible to implement this into EssX?

**Comment by mdcfe** [comment]
Can't you set the minigame world spawn point to the minigame lobby?

**Comment by Platinteufel** [comment]
Every minigame has it's own lobby. But that's not the problem. If you die in survival after playing minigames, you will respawn at your spawnpoint in adventure, and that's really annoying and confusing.
