### ISSUE TITLE
url filter

### ISSUE THREAD

**Issue by Ironic8b498** [EssentialsX/Essentials#927]
I can't figure out how to stopped Essentials from removing the periods in a URL, I need to let my chat filter do that?

**Comment by Kakifrucht** [comment]
Hand out the appropriate permission, `essentials.chat.url`.

**Comment by Ironic8b498** [comment]
Thanks, I had fixed it on my servers once when I was running pwnfilter, now that I have gone back to using pwnfilter with 2 new servers added on the network since I fixed it last time
