### ISSUE TITLE
Build fingerprinting not visible on Jenkins

### ISSUE THREAD

**Issue by mdcfe** [EssentialsX/Essentials#928]
Jenkins isn't showing the build fingerprint; this would be useful to confirm that downloaded jars match the jars on Jenkins - for example, in #924.

**Comment by drtshock** [comment]
Good point. Just added it in https://ci.drtshock.net/job/EssentialsX/lastSuccessfulBuild/artifact/Essentials/target/EssentialsX-2.0.1.jar/*fingerprint*/
