### ISSUE TITLE
/back freaks out on grass path tiles

### ISSUE THREAD

**Issue by itsthejoker** [EssentialsX/Essentials#929]
When standing on a grass path (standard grass block, right click with shovel), /warp somewhere and then use /back. You will be stuck on that block and unable to move while the screen jitters up and down; the only way you can escape it is if you have fly enabled.

**Comment by itsthejoker** [comment]
Using the most recent release of Spigot and EssentialsX at the time of this writing.

**Comment by mdcfe** [comment]
Can confirm that this has occurred when warping onto grass paths, although we use Paper as opposed to regular Spigot.

**Comment by vemacs** [comment]
Does this only happen for grass? Does it happen on Spigot 1.10 builds from a few months back?

**Comment by mdcfe** [comment]
In theory this should be possible to replicate with soul sand too, but I've only personally experienced this with grass paths (which are 15/16 of a block tall).

**Comment by itsthejoker** [comment]
@md678685 I actually don't experience this with soul sand. Interestingly enough, I was able to confirm that the grass path needs to be in a chunk that is not currently loaded. If the path that you're warping to _is_ currently loaded, then it works as expected.

@vemacs I don't have any earlier builds to test with at the moment, but I'll look into it this evening.

**Comment by stevmei** [comment]
Still a problem.

**Comment by stevmei** [comment]
I guess this will never be fixed...

**Comment by mdcfe** [comment]
I don't think this can be fixed within EssentialsX, though if someone can point out where the flaw is then I'll take another look at this.

**Comment by pop4959** [comment]
Yeah afaik this is a problem with teleportation in general, and not specific to Essentials. Happens in other plugins commonly. Will probably need to be fixed in Bukkit some day, if ever.
