### ISSUE TITLE
Recipe bug

### ISSUE THREAD

**Issue by dannypha09** [EssentialsX/Essentials#932]
When i do a /recipe
I can get the object out of the crafting table.
Bug or intended..i dont know

**Comment by mdcfe** [comment]
What server software and version of EssentialsX are you using?

**Comment by dannypha09** [comment]
SERVER:
This server is running CraftBukkit version git-Spigot-f9671b8-48b88ed (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

BUNGEE:
This server is running BungeeCord version git:BungeeCord-Bootstrap:1.10-SNAPSHOT:0581e49:1190 by md_5

ESSENTIALS:
Essentials reloaded 2.0.1-b370.

**Comment by dannypha09** [comment]
It says i'm 16 versions behind, will updating my spigot fix it?

**Comment by mdcfe** [comment]
Try updating EssentialsX to a more recent version.

**Comment by dannypha09** [comment]
Essentials x is latest version

**Comment by dannypha09** [comment]
spigot was 16 behind

**Comment by dannypha09** [comment]
Oh, i'm going to try the lastest jenkins build

**Comment by dannypha09** [comment]
Ye, still happens on latest essentialsx

**Comment by Kakifrucht** [comment]
Most likely another plugin uncancelling the event/overwriting. It works fine on my end. You should try and fix your setup.

**Comment by mdcfe** [comment]
I agree with @Kakifrucht; what plugins do you have?

**Comment by dannypha09** [comment]
http://pastebin.com/VhRJT1bt
my plugins

**Comment by Kakifrucht** [comment]
Think about which plugins work with inventories and then try removing them one by one until the issue no longer persists. Once you know which plugin it is go ahead and report the bug to that author.

**Comment by dannypha09** [comment]
OK, i loaded every plugin with essentials individually
and it concludes to GUISHOP. I wont be using guishop in the future anyway, so ye

**Comment by dscalzi** [comment]
I can confirm this bug on 1.11

**Comment by mdcfe** [comment]
@dscalzi This issue is for a bug with GuiShop. Please open another issue if you are not using the plugin.
