### ISSUE TITLE
Impersonation possible with nicknames

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#936]
Hello, I have a problem with EssentialsX build 370 (And 354) in which two users can have the exact same nickname, which is a huge problem. Is this a bug? I don't believe this used to be possible. Thank you.

**Comment by SupaHam** [comment]
Nicknames have never been unique. There's the option of adding a prefix to nicknames (by default tilde `~`), to identify whether it is a nickname or real name.
