### ISSUE TITLE
Userdata purge, or cleanup

### ISSUE THREAD

**Issue by DeusNinja** [EssentialsX/Essentials#938]
Currently can't find any way other than brute force and manually going through the files to remove old and unused player data. I've got 38 thousand user data .yml files and would like to clean them up somehow..

**Comment by Kakifrucht** [comment]
It's a bit hidden. Use `/essentials cleanup <days> [money] [homes]`, where days is the time that has to have passed for purge since last login, and you can define exemptions for players who have more than x money/homes.

**Comment by DeusNinja** [comment]
Does it work for mail? or to even purge the entire userdata file if the player hasn't been on for more than 100 days?

**Comment by Kakifrucht** [comment]
This will clear the whole userdata file of affected players. That includes mails.

**Comment by DeusNinja** [comment]
Thank you for your help, one last question, where could I request a feature?

**Comment by Kakifrucht** [comment]
On this issue tracker aswell, don't expect it to be implemented though. There are tons of feature requests already.

**Comment by DeusNinja** [comment]
Thank you :)
