### ISSUE TITLE
EssentialsSpawn for newbies & starting-balance problem when using PerWorldInventory

### ISSUE THREAD

**Issue by Rocologo** [EssentialsX/Essentials#939]
I have this problem. My first world (named world) is a creative world and the I have a survival world called asgaard. 

I have set starting balance to 3000 and the newbies spawn point i the second world (asgaard). I use Multiverse Core and I use Per World Inventory to seperate inventory and balance. 

When a new player joins he get 3000 i world, but he joins in asgaard, and PWI change the balance in asgaard to 0 as it should. Newbies kit has the same problem. New players get the items in world and not in the world where they actually spawn first time.

I thing starting-balance and newbies kit should use the worldname for group newbies (if exist)in spawn.yml

**Comment by Rocologo** [comment]
I just realized that you dont use the world name, when you resetBalance to starting-balance. The solution to this must the be to call resetBalance after the has been moved to newbies spawn.

**Comment by Rocologo** [comment]
Maybe in EssentialsSpawnPlayerListener.java after line 151 ?

**Comment by mdcfe** [comment]
I'm not exactly sure what the issue is here - could you elaborate if it's still a problem?

**Comment by Rocologo** [comment]
I will try :-)

The problem is:
1) new players dont get 3000 $ when they join the server. (as intended)

Here is my setup
2) I have two worlds: “world” and “asgaard”
3) I use EssentialsX, multiverse and PerWorldInventory
4) I use Essentials Spawn to set new players to spawn in “asgaard”
5) When a player joins, he gets 3000 in world from EssentialsX
6) The player is then teleported to the newbee spawn in asgaard.
7) Because of changing worlds PerWorldInventory, set balance to 0 in asgaard (and 3000 in world)
8) So the player feels like he dont get any money. As he never saw “world” 

The problem would be solved if the new player was teleported to the newbee spawn and then got the starting balance after the teleport.

**Comment by mdcfe** [comment]
Is there any reason not the put `world` and `asgaard` in the same PWI "group", so that inventories and balance are shared across the two worlds?

Edit: thanks for replying on such an old issue :p

**Comment by Rocologo** [comment]
I cant do that. World is a creative world, asgaard is survival.

**Comment by Rocologo** [comment]
I could say the same to you ;-)

**Comment by pop4959** [comment]
Sounds like something that should be handled specially in PWI; seems like Essentials is doing its part correctly here. If you're still here after this second necro, I recommend seeing if PWI can do anything about this situation, as this probably happens with any economy plugin. Maybe PWI can implement its own way of doing per-world starting balance.
