### ISSUE TITLE
Restrict fly speed

### ISSUE THREAD

**Issue by Kixot14** [EssentialsX/Essentials#942]
EssentialsX have 'max-fly-speed' feature (range from 0.1 to 1.0 (default flySpeed is 1.0 ??))
But looks like this work only when use fly by command, and don't work, if player fly by WGFlyFlag, for example.
Can you make this restrict global? And can you deny fly exeleration for players, which don't have special permission, when this restriction active ??

**Comment by mdcfe** [comment]
I believe this option only applies to `/speed` rather than `/fly`, and so it won't apply to other plugins. I don't think that's something we're intending to add, because we'd need to somehow support individual plugins for this to work.
