### ISSUE TITLE
Players can't see vanished staff

### ISSUE THREAD

**Issue by tehrenderr** [EssentialsX/Essentials#943]
Whenever a staff goes into vanish and then goes back out of it, sometimes players are unable to see them. I am using Essentials X 2.0.1 on a 1.8.8 paperspigot server. I understand that this is a problem for regular essentials but I was wondering if it could be fixed on here.

**Comment by mdcfe** [comment]
I have an alias set up which toggles /v twice as an attempt to fix this; it seems to work well enough.

**Comment by mdcfe** [comment]
Also, related: #145

**Comment by Trickster489** [comment]
@md678685 https://github.com/drtshock/Essentials/issues/145 is hardly related, they're different bugs in the same feature.

**Comment by mdcfe** [comment]
@foxehc They're both inconsistencies in vanish functionality and they're both issues I have to deal with on my server. Many people were confused in #145 because somebody thought an actually useful feature was the bug being experienced.

**Comment by mdcfe** [comment]
This appears to be caused by the bug in #1764.
