### ISSUE TITLE
a perm for view spectator

### ISSUE THREAD

**Issue by saturnux** [EssentialsX/Essentials#944]
Can you create a permission so that we can see a player spetateur, such as those in Vanish ?

thanks.

**Comment by Trickster489** [comment]
I'll look into submitting a pull request for this feature near the weekend.

**Comment by mdcfe** [comment]
@saturnux There's already a permission to see vanished players. 
@foxehc If you want to be able to see spectated players, you may need to use CB/NMS code; I'm not sure how Spigot implemented spectator mode.

**Comment by saturnux** [comment]
@md678685 
yes, a perm for vanished player exist, and i use that.
a mod exist for view a player that use an invisibilty potion.

fot the staff, or use after game, i dont think if it's possible, a perm for view all player on gamemode spectator do not exist :(

**Comment by mdcfe** [comment]
@saturnux That clears it up, I thought you were referring to vanished players, not spectators.

**Comment by mdcfe** [comment]
I'm not sure whether this is actually possible, as I don't think we can control whether non-spectators can see spectators through Spigot.

**Comment by pop4959** [comment]
I don't think it's possible either, unfortunately. If anyone does find a way to do this and wants to add it in as a feature to vanish, feel free to suggest a PR though.
