### ISSUE TITLE
essentials.silentjoin.vanish

### ISSUE THREAD

**Issue by Twonox** [EssentialsX/Essentials#945]
If `allow-silent-join-quit: true` & if I'm OP, I'm always vanished on join but I wouldn't that.
Could you add option to disable `essentials.silentjoin.vanish` for OP please ?

**Comment by mdcfe** [comment]
Negate the permission (use permissions.yml if you don't have a permissions plugin).

**Comment by Twonox** [comment]
I will test with this permission but with an other permission the negative permission doesn't work (-essentials.afk.auto

**Comment by Twonox** [comment]
I have tested, it doesn't work :/

**Comment by Kakifrucht** [comment]
Using Essentials vanish functionality is not really recommended, as the information as to where you are, even if vanished, is still being sent to clients. Modified clients or "hacks" could most likely still see you. Look into VanishNoPacket for proper vanishing functionality.
Why did you negate essentials.afk.auto? What does that have to do with anything?

**Comment by Twonox** [comment]
Just! I doesn't use essentials vanish, I use SuperVanish, but when I use `allow-silent-join-quit`, I'm automatically vanished... because I'm OP.
When I'm vanished (with supervanish) I'm spotted because of auto afk. It's enabled for players, but I'm OP and I have this permission automatically like silentjoin.vanish

**Comment by SupaHam** [comment]
Firstly, please type `/ess debug` then try log in with the player who is automatically vanished. Then, please Pastebin your server log.

Steps:
1. Open `logs` directory in server directory.
2. Find and open a file called `latest.log`.
3. Go to [www.pastebin.com](http://pastebin.com).
4. Copy all `latest.log` contents and paste into the big text area.
5. Copy & paste the URL in your browser into a reply here.

**Comment by Twonox** [comment]
I founded the cause of this problem after some test.
If I have the permission '*' (in user, not in group), the negative permissions in my Group are not included. So, I must use negative permissions in User to it works.
