### ISSUE TITLE
Money glitch

### ISSUE THREAD

**Issue by AmazedMender16** [EssentialsX/Essentials#947]
hello there is a money glitch if you use lower letter and bigger letter

like

Glenn
glenn

has the same ball can you fix this?

**Comment by mdcfe** [comment]
If the server is an online mode server, this appears to be intentional.

**Comment by AmazedMender16** [comment]
the server is for cracked players also.. but this should be able to get fixed i havent had this for long

**Comment by AmazedMender16** [comment]
https://www.spigotmc.org/threads/essentials-1-8-baltop-players-duplicating-with-0.40920/

here is a fix can the dev of essentialsx add this to hes own plugin? if possible ;(

**Comment by drtshock** [comment]
Use online mode
