### ISSUE TITLE
Essentials glitch

### ISSUE THREAD

**Issue by AmazedMender16** [EssentialsX/Essentials#948]
There is  a bug with money/accounts where people make random accounts which have different amount of bals when register, for example: if I was to do amazedmener16 instead of AmazedMender16 it would give me majority of the money on that account.

**Comment by mdcfe** [comment]
Use online mode and this won't be an issue.

**Comment by Kakifrucht** [comment]
Why do you create another ticket? What do you expect as a response? Don't use offline mode and you won't have issues. The big warning you see in the console when starting a offline mode server has a reason.

**Comment by Twonox** [comment]
You can use Authme's NickCase protection

**Comment by AmazedMender16** [comment]
what you mean Authme NickCase?

**Comment by Twonox** [comment]
Line ~291 `preventOtherCase: true`
If it's true, you can't join the serveur with amazedmener16 instead of AmazedMender16
