### ISSUE TITLE
Weird looking /list and people dissappearing

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#949]
Hi,

Recently my server started making the /list look quite weird (http://prntscr.com/d0i57u) when counting up total players online. If you multiply the 22 +3, you get the total amount online. What does the /3 behind 22 mean?

Also, people are dissapearing randomly in tab and in-game, so they become invisible and untrackable. Anyone have a clue why this is happening? 

Best wishes

**Comment by SupaHam** [comment]
This is not an issue in Essentials. This must be due to a custom messages file in your local setup. Please check if you have a file called `messages_de.properties` inside your Essentials folder. If there is, you need to find that line and change it to something else or use the latest found [here](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/messages_de.properties).

**Comment by ghost** [comment]
Hi mate, 

I just removed all language files from Essentials except the english one.
http://prntscr.com/d0lq2d
Problem is still there and I believe the issue is not in Essentials as well. But, I would like to ask you why the /list command is writing 17/3 instead of 20?

**Comment by SupaHam** [comment]
[This is a feature](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/PlayerList.java#L50). This type of message is only shown to players who can see other vanished players.

So when it says 17/3 it means there are 17 players online, 3 of which are vanished. I'm not entirely sure why it was done this way, but that is what the numbers represent.

Keep in mind this only happens with players, usually admins, that can see the other vanished players.

**Comment by ghost** [comment]
Okay, thank you! I figured out that a feature named "PlayerRadar" in the plugin AAC casued the players to vanish when reaching a certain distance. It is fixed now. :)
