### ISSUE TITLE
Cant sell mined spawners

### ISSUE THREAD

**Issue by VoidShift** [EssentialsX/Essentials#95]
Spawners that have been mined with a silktouch pickaxe from the plugin SilkSpawners can't sell them using essentials signs.

**Comment by zRiaz** [comment]
Would suggest talking to the dev of SilkSpawners about this issue as I think thats on his part.

**Comment by VoidShift** [comment]
I posted a ticket to the dev of silkspawners

**Comment by timbru31** [comment]
I've described the issue here ;)
https://github.com/drtshock/Essentials/issues/103

Nasty Spigot/CraftBukkit implementation IMHO...
