### ISSUE TITLE
[Question] How do you remove tamed wolves with /killall?  Can you?

### ISSUE THREAD

**Issue by c0wg0d** [EssentialsX/Essentials#952]
If I wanted to remove only tamed dogs, how would I do it with EssentialsX?  I've tried all the following and none of them work:

/killall dog
/killall wolf
/killall wolf:tamed

**Comment by mdcfe** [comment]
I think this is deliberately disabled by EssentialsX, because in most use cases this is not wanted.

**Comment by c0wg0d** [comment]
In most cases, I would agree, but there should still be an option added for this if it's not possible.  Using vanilla Minecraft commands for this purpose is very tedious.

**Comment by Aurgelmir** [comment]
I don't know if the command is still available, but I personally user the `/killall tamed`
Just notice that it will also kill tames horses and other tamed animals, not only wolves.
