### ISSUE TITLE
Request: essentials.seen.exempt

### ISSUE THREAD

**Issue by Twonox** [EssentialsX/Essentials#953]
Could you add the permission `essentials.seen.exempt` ?
I think you understand its utility

But, if it's possible, add possibility to /seen someone who have this permission if we are OP.

**Comment by Trickster489** [comment]
I don't understand what you want. Do you want a permission implemented in case you don't want an user being /seen?

**Comment by Twonox** [comment]
If a player have the permission `essentials.seen.exempt`, an other player with permission `essentials.seen` can't /seen a player with permission `essentials.seen.exempt`.

**Comment by mdcfe** [comment]
This may not work consistently with some permissions plugins as the player will be offline, but it's a valid feature request.

**Comment by pop4959** [comment]
If someone comes across it and still feels like making a PR it's on the table. It just seems there is not much interest in this issue, so I will be closing it.

Edit: And also as md mentioned above it might not be a very stable addition to the plugin. Be warned.
