### ISSUE TITLE
Allow for players with an essentials.hat permission to put on anything as a hat without having to type the command /hat.

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#956]
Would it be possible to implement a new permission for the Essentials ```/hat``` feature to allow for players to be able to drag anything in the hat slot and put it on instead of having to type /hat every time?

**Comment by mdcfe** [comment]
Not sure how easy that is - you'd have to listen to cancelled inventory events for the helmet slot and uncancel them hoping another plugin doesn't break it.

**Comment by mibby** [comment]
MassiveHat (https://github.com/MassiveCraft/MassiveHat) and some other Hat plugins I've come across have this behavior. So it was mainly just something I was wondering could be done in Essentials to simplify or expand upon the hat functionality.

**Comment by Trickster489** [comment]
Devs would have to cancel any interfering ICEs trying to cancel the event in which a Player clicks their armor inventory slot, but eitherway it's very possible.

I might PR your feature this weekend depending on how much time I can spare.

**Comment by mdcfe** [comment]
@Trickster489 Was going to look at it some point as well; the reason I held back was because the last time I recall an event listener being added in a PR it caused issues with poor implementations of Bukkit.

**Comment by Trickster489** [comment]
@md678685 Blame whoever submitted the pull request, not the entire project.

**Comment by mdcfe** [comment]
@foxehc I submitted the pull request and had it merged, and encouraged the last maintained 1.7.10 implementation to actually fix their implementation so people would stop reporting EssentialsX bugs which weren't EssentialsX's fault.

**Comment by mibby** [comment]
@SupaHam Any update to this issue? I also noticed you can't wear tools on your head as it says you cannot use that item as a hat. I have a custom resource pack that changes some tools to equippable hat items..

**Comment by mdcfe** [comment]
This has been added by #960 - grab the latest build from the [build server](https://ci.drtshock.net/job/EssentialsX).

**Comment by mibby** [comment]
Still can't wear tools on your head with /hat or clicking (tools used for resource pack that sets custom textures for damage values), but you can now just drag most items in the head slot as long as you have permission. :)
