### ISSUE TITLE
Essentials X Signs Not Working on 1.10 Spigot server

### ISSUE THREAD

**Issue by KJ03** [EssentialsX/Essentials#957]
I was setting up factions on my server and I did Config and enable the Signs For More information, look at the spigot forum I posted https://www.spigotmc.org/threads/essentials-signs-still-not-working.188400/

**Comment by Trickster489** [comment]
Paste your configuration, "certain" users are banned from Spigot for staff harassment.

**Comment by KJ03** [comment]
there you go !!

[config.zip](https://github.com/drtshock/Essentials/files/573101/config.zip)

**Comment by 777Ricky** [comment]
I'm also having this issue

**Comment by SupaHam** [comment]
Make sure you update spigot if you're seeing blank signs. Otherwise please specify more specific information than "not working". What isn't working exactly? What messages do you get? Does the server crash? What is not working?
