### ISSUE TITLE
Trade sign doesn't recognizes potions and eggs meta

### ISSUE THREAD

**Issue by matcracker** [EssentialsX/Essentials#958]
For reproduce this issue follow these steps:
- Create a sign trade that sell a potion (for example speed) or an egg.
- Now add to sign more potion or egg of another type (for example jump, or a normal potion with ID 373)
- You see that you can add different type of potion or egg in a sign that sell another type of potion, but if someone buy the potion it returns the potion type written in the sign.

**Comment by mdcfe** [comment]
So the more sign is broken or the buy sign is?

**Comment by matcracker** [comment]
I don't try on other sign, I've tried only on Trade sign

**Comment by saturnux** [comment]
sell and buy not work too

**Comment by matcracker** [comment]
Yes, I can confirm too

**Comment by SupaHam** [comment]
Have you tried on the latest build on our [CI server](https://ci.drtshock.net)?

**Comment by saturnux** [comment]
yes, i use a last. #453

**Comment by Rakdos8** [comment]
Issue still up to date with build #532
__Server version:__ CraftBukkit version git-Spigot-da42974-8f47214 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**Comment by Rakdos8** [comment]
The Trade sign with potion are still broken: [screenshot](https://redmine.modulmonde.com/attachments/download/63/2017-09-16_22.03.17.png)
Latest version used (546) and latest 1.12.1 version of spigot.
(The date of the screen is old, yeah, but the problem is strictly the same)

**Comment by Rakdos8** [comment]
The latest build now allow to trade back potions.
Thank you !

**Comment by pop4959** [comment]
Closing since according to Rakdos8 this is fixed. Feel free to make a new issue if there is still another issue with trade signs.
