### ISSUE TITLE
Option to send "player is afk" only to the /afk player

### ISSUE THREAD

**Issue by RoboMWM** [EssentialsX/Essentials#959]
Helps prevent spamming chat, but gives feedback to the player doing /afk

**Comment by Vanturian** [comment]
I'll do it now

**Comment by Aurgelmir** [comment]
Hi,
I guess you can't, or maybe the trick would be to add a function or class for this. The only option is to open the EssentialsX jar file, to edit messages_[your local].properties, and remove the line for the message. The issue will be that nobody will get the information, not even the players who's AFK-ing

Regards

**Comment by RoboMWM** [comment]
@Aurgelmir yes I'm aware, and that's what I do currently. I used to actually have it also run a command that tells the player to check their afk status with `/seen` but it seems a "recent" update has made it so that running /seen (or probably any other command at this point) removes you from being afk. I probably will be doing something in my plugin to tell the player of their afk status or make a PR - but will only do the latter if the team would accept such(?)

**Comment by mdcfe** [comment]
I think adding an AFK message which is only sent to the AFK player could be a good way to solve this - if you didn't want anyone else to know, you could leave this message enabled and disable the public message.

**Comment by Aurgelmir** [comment]
@RoboMWM for the `/afk` command, I guess that an external plugin can do it.
For instance the plugin could act like: if /afk is input by a player, then `/tell {player} You went AFK` or something like that. I can't remember what is the plugin's name, but there is one that listens to command inputs and can do different actions when triggered by a specific command.
As far as I know that's the only way to do this without modifying Essentials files by yourself

**Comment by Aurgelmir** [comment]
@RoboMWM I found how to fix this!
In case you didn't know, there's a `/sudo` command, that you can run when the player types `/afk` that will not make him un-AFK.
To do so, the command has to be: `/sudo {PLAYER} seen {PLAYER}`
I just tried, and it works.

The sudo command's description is the following: `/sudo: Make another user perform a command.`

**Comment by RoboMWM** [comment]
@md678685 would you recommend adding a config option or just a new messages key, which is default empty/null? Sounds like the latter would make sense.

**Comment by mdcfe** [comment]
@RoboMWM The latter; I'd suggest that it either defaults to matching the existing one or saying something along the lines of "You are now AFK."

**Comment by RoboMWM** [comment]
Well by default I'd have it set to none since the public one broadcasts to everyone

**Comment by mdcfe** [comment]
If the additional message was added to be sent only to the AFK player, wouldn't it make sense not to send the public one to the player who was marked AFK (unless, of course, no message was set for the new message key)?

**Comment by RoboMWM** [comment]
This would break original behavior though - think of those filing an issue report stating that the afk message isn't changing.

**Comment by mdcfe** [comment]
Inform them that there has been a change? The messages should ideally be adjacent in the localisation file.

**Comment by triagonal** [comment]
This has been implemented in #2780 and is present in EssentialsX versions 2.17.2.56 and above.
