### ISSUE TITLE
Jailing and mailing players who have never connected to the server before creates a new userdata yml file.

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#962]
Had someone discover a minor bug. If you jail someone who has never joined the server before, it creates a new userdata yml file for that player based on the UUID of that name (if it exists for an account). This made it so someone was unable to use their usual ```/nick``` because that name was taken up due to an incorrect jail command usage.

Looking through my userdata folder, I have quite a few player ymls generated that are <200 bytes in size. Created from misused jail commands, mail sends to names typed incorrectly, and presumably also from offline bans from players who have never joined before. 

Shouldn't .yml files only be created if the player has actually joined the server?

**Comment by JRoy** [comment]
@pop4959 this can be closed. Looks like these commands have proper checks in place now!
