### ISSUE TITLE
Request: YAW and PITCH in /tp <username> x y z

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#964]
Hello
Can we please get yaw and pitch added to /tp <username> x y z
they would be extra parameters on the end for example:
/tp <username> x y z 3.2 1.2

**Comment by Hunkboy** [comment]
You can use `/tppos`

**Comment by TomLewis** [comment]
nah I cant use /tppos as this cannot be run with a <username> to send a username via a command.

**Comment by mdcfe** [comment]
Try `/execute <name> ~ ~ ~ tppos ...` or `/sudo tppos ...` if they have permission for tppos.

**Comment by TomLewis** [comment]
@md678685 They dont have perms to tppos, hence why I want to do it via the terminal, I tried that /execute which is bound to something else so I tried /eexecute for essentials, it seemed to run but didn't TP the user.
Example use:
`eexecute playername tppos -7130 70 -1001 -178 4.8`
ALSO
`eexecute playername ~ ~ ~ tppos -7130 70 -1001 -178 4.8`

**Comment by mdcfe** [comment]
@FrozenBeard I was referring to `/minecraft:execute` - your server software may allow you to use vanilla's execute command. Alternatively, use `/minecraft:tp`.

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to reopen the issue.
