### ISSUE TITLE
Money Duplications

### ISSUE THREAD

**Issue by DisTrugator** [EssentialsX/Essentials#966]
Hello
Today i see someting weird
I use EssentialsX and PerWorldInventory with Multiverse Core because i have multiple worlds but i see that the players balance duplicating and duplicating when they go on another world .
I Ask for suport at PerWorldInventory (Have Multiple worlds money addons) but authot say that is no problem with his plugin and ask for support at essentials .
Yes , I using Vault and my server is running on offline Mode ! 
I'm waiting for a fast reponse !

**Comment by mdcfe** [comment]
Use online mode.
