### ISSUE TITLE
1.11 Blocks on items.csv

### ISSUE THREAD

**Issue by dscalzi** [EssentialsX/Essentials#968]
As with 1.10, not many new blocks have been added in 1.11. The list can be found here:

http://minecraft.gamepedia.com/1.11#Blocks

These blocks and items need to be eventually added to the items.csv file.

**Comment by SupaHam** [comment]
This has been fixed in 8b0659a. You can grab the fix from [build 440](https://ci.drtshock.net/job/EssentialsX/) on the CI server.
