### ISSUE TITLE
Invsee inventory top and bottom inconsistency.

### ISSUE THREAD

**Issue by KevinNovak** [EssentialsX/Essentials#969]
When [testing which inventory is clicked](http://pastebin.com/DJBDmGf9) (top or bottom), there is [weird behavior](https://proxy.spigotmc.org/d6e04cdca263df0c7429c012de165a14c4a803e3?url=http%3A%2F%2Fi.imgur.com%2FFKUZtIb.png) when each slot is clicked. This only seems to happen with Essentials /invsee inventory, and not other inventorys (such as chests, OpenInv's inventory, etc). See [this Spigot forum post](https://www.spigotmc.org/threads/recreating-spigots-getclickedinventory-for-craftbukkit.194442/#post-2029608) for more info.

**Comment by mdcfe** [comment]
I feel like this is an unintended side effect of the Combat Update, as slots 36-40 have been occupied by armour and the offhand item since around that time. Does putting an item in the "top" slots at the bottom affect the other player's armour or offhand items?

**Comment by KevinNovak** [comment]
>  Does putting an item in the "top" slots at the bottom affect the other player's armour or offhand items?

It does not, invsee works as is should as far as I can tell. I am trying to make a plugin that relies on knowing whether an inventory is top or bottom, and for some reason Essentials /invsee is throwing me off.

**Comment by Jikoo** [comment]
Essentials is opening a 41-slot inventory, not 36, and the client doesn't know how to handle it properly. This is due to the fact that PlayerInventory#getContents contains the armor and offhand slots as well as of midway through 1.9.

**Comment by KevinNovak** [comment]
> PlayerInventory#getContents contains the armor and offhand slots as well

Why does Essentials use this if it is not displaying them to the /invsee viewer?

EDIT: Why not use [Inventory#getStorageContents](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/Inventory.html#getStorageContents%28%29)?

**Comment by Jikoo** [comment]
> Why does Essentials use this if it is not displaying them to the /invsee viewer?

Old code that doesn't appear broken to the casual observer. Pre-1.9, it was fine. Pretty sure this is actually more of a CB issue - there's [no special handling for opening player inventories](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/entity/CraftHumanEntity.java#189) even though it's no longer standard sized.

**Comment by KevinNovak** [comment]
> there's no special handling for opening player inventories even though it's no longer standard sized.

I see what you mean. That's sort of unfortunate. Maybe I'll submit an issue on the CraftBukkit site, although I guess for the majority of cases it's not a problem. Will Essentials be making any changes? It'd be great if /invsee could open a 36-slot inventory, since that is what is being shown... but it almost doesn't even seem worth it to make the change.

**Comment by Jikoo** [comment]
You could submit a PR. I can't really speak for the EssentialsX team, but based on the fact that #472 has been sitting for several months I doubt they're likely to make changes. The reason it's done the way it is is that modifying the opened inventory directly modifies the actual underlying inventory of the target player. Creating a 36-slot inventory would require either a decent lot more work in terms of event handling or some fiddly NMS to keep both inventories in sync.

For your reading pleasure: [inventory click handling](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java#L616) and [inventory opening](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/commands/Commandinvsee.java#L27)

**Comment by mdcfe** [comment]
I think the `/invsee` command could be modified to deal with this by extending Inventory to create a 48 slot mirror of the given inventory. I may have a look into this at some point if I find time.

**Comment by khobbits** [comment]
Little bit late to the party here, but do keep in mind that modded versions of Minecraft can use some really odd inventories, so when I was originally writing this I was trying to avoid using any hard coded numbers.

**Comment by pop4959** [comment]
Not sure if this is still an issue, but seems to be a Bukkit related problem. Closing for now since this doesn't seem to have any meaningful impact on functionality to Essentials.
