### ISSUE TITLE
Afk on join?

### ISSUE THREAD

**Issue by FlippantCactus** [EssentialsX/Essentials#97]
http://i.imgur.com/3MBNEVH.png
AFK on join apparently, bug?

**Comment by vemacs** [comment]
Can't reproduce. Need way more information. What's timeout in config? 0?

**Comment by FlippantCactus** [comment]
https://paste.sway.pw/ajaxumafah.vala - AFK part of config.
2.0.1 Beta 174
Spigot
Sorry for lack of information.

**Comment by vemacs** [comment]
Still can't repro at all. Closing.

**Comment by Kakifrucht** [comment]
Me neither.

**Comment by SupaHam** [comment]
Fixed in 0641791.
