### ISSUE TITLE
Maven Compiling Issue

### ISSUE THREAD

**Issue by stuntguy3000** [EssentialsX/Essentials#970]
Hi there,

I am unable to compile due to a maven repo host error.

[ERROR] Failed to execute goal on project EssentialsX: Could not resolve dependencies for project net.ess3:EssentialsX:jar:2.0.1: Failed to collect dependencies for [BOSEconomy:BOSEconomy:jar:v0.7.8.1 (system), iConomy:iConomy5:jar:5 (system), iConomy:iConomy6:jar:6 (system), MultiCurrency:MultiCurrency:jar:2.2 (system), net.milkbowl.vault:Vault:jar:1.5.6 (provided), net.ess3:NMSProvider:jar:2.0.1 (compile), net.ess3:UpdatedMetaProvider:jar:2.0.1 (compile), net.ess3:1_8_R1Provider:jar:2.0.1 (compile), net.ess3:1_8_R2Provider:jar:2.0.1 (compile), net.ess3:LegacyProvider:jar:2.0.1 (compile), net.ess3:ReflectionProvider:jar:2.0.1 (compile), org.bukkit:bukkit:jar:1.10-R0.1-SNAPSHOT (provided), junit:junit:jar:4.11 (test), org.projectlombok:lombok:jar:1.12.2 (provided)]: Failed to read artifact descriptor for net.milkbowl.vault:Vault:jar:1.5.6: Could not transfer artifact net.milkbowl.vault:Vault:pom:1.5.6 from/to vault-repo (http://nexus.theyeticave.net/content/repositories/pub_releases): nexus.theyeticave.net: **Unknown host nexus.theyeticave.net** -> [Help 1]

Is this happening to anyone else or is the domain fully offline?

**Comment by mdcfe** [comment]
This occurs normally; I have a hosts entry which redirects nexus.theyeticave.net to the new Vault repo.

**Comment by stuntguy3000** [comment]
What a crappy solution

**Comment by vemacs** [comment]
I'm fixing it, should've just PMed me on telegram lol

Edit: shit, we don't actually reference theyeticave anywhere: https://github.com/drtshock/Essentials/blob/db47460a7949c5686222b16feb3c5f4be2a8376f/Essentials/pom.xml#L138
