### ISSUE TITLE
EssentialsX - Can't type on or right-click signs

### ISSUE THREAD

**Issue by ICauseDarkDays** [EssentialsX/Essentials#971]
**It's as the title says. No typing and no right-clicking. Whenever I try to doeither, it says "you do not have permission".**

**Comment by mdcfe** [comment]
"No typing"... as in, you can't set the sign's text once you've placed it? What other plugins do you have installed?

**Comment by SupaHam** [comment]
Make sure you have worldguard permission in the area.

**Comment by ICauseDarkDays** [comment]
I don't have worldguard in the region and I'll post plugins later

**Comment by ICauseDarkDays** [comment]
I mean unless you're op, you cannot place signs anywhere and it's pretty essential to my server. I summed it up to the problem being EssentialsX

**Comment by vemacs** [comment]
Unless you remove all other plugins and can still repro the problem, you can't conclude the problem to be EssX

**Comment by ICauseDarkDays** [comment]
**My plugin list:**
![aaaaaaaplugs](https://cloud.githubusercontent.com/assets/11409098/20458875/cd14da92-ae65-11e6-910f-1617fde61234.png)

**Comment by vemacs** [comment]
Remove all your plugins other than EssX and add them back one by one...

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to reopen the issue with the results of having followed the given instructions.
