### ISSUE TITLE
essentials.kill.exempt

### ISSUE THREAD

**Issue by cicatrice74** [EssentialsX/Essentials#972]
the essentials kill exempt doesn't function , can u fix this, i'm on latest 1.10.2 spigot

**Comment by mdcfe** [comment]
Make sure you don't have the `essentials.kill.force` permission.

**Comment by cicatrice74** [comment]
Probably that's the problem... but i think it's better to remove the kill force from the '*' permission like kick force and ban force and sudo.. that's my real issue

**Comment by mdcfe** [comment]
As far as I can tell, this is intended; just negate the permission from the users as needed. If this changes, more people will complain about essentials.kill.force not working.

**Comment by cicatrice74** [comment]
i told this 'cause with kick, ban, jail the error does not occur, i have the ' * ' permission, obviously these are not included in the '*' permission so i think the kill.force would be also not included in the ' * ' permission. that's all folks...lol
