### ISSUE TITLE
/kill and /suicide not working. Spigot 1.11

### ISSUE THREAD

**Issue by KiaraPaw** [EssentialsX/Essentials#974]
Nothing happens when these two command are executed.

**Comment by mdcfe** [comment]
Could you paste the console output when these commands are run, as well as your list of plugins?

**Comment by SupaHam** [comment]
Working on it.

**Comment by SupaHam** [comment]
This has been fixed in 8b0659a. You can grab the fix from [build 440](https://ci.drtshock.net/job/EssentialsX/) on the CI server.
