### ISSUE TITLE
Question about compatible versions

### ISSUE THREAD

**Issue by Kixot14** [EssentialsX/Essentials#975]
Did the EssX 1.11 full compatible with Spigot 1.10 ??

**Comment by mdcfe** [comment]
~~It should be fully backwards-compatible with 1.8-1.10 and mostly backwards-compatible with 1.7.10 (issues #922 and #931 come to mind).~~

Correction: certain inventory- and mob-related commands may currently be broken on Minecraft 1.10 and below. Use build 439 for full support on 1.10.

**Comment by Kixot14** [comment]
Good.

**Comment by Kixot14** [comment]
backwards-compatible is a very good thing!

**Comment by md678685** [comment]
Correction: certain inventory- and mob-related commands may currently be broken on Minecraft 1.10 and below.
