### ISSUE TITLE
Spawn eggs not working with /give on 1.11

### ISSUE THREAD

**Issue by Sikatsu** [EssentialsX/Essentials#976]
The old /give Sikatsu spawn_egg:50 1 or /give Sikatsu 383:50 1 is not working anymore.
The output is a default spawn_egg that doesn't do anything.

Minecraft wiki says:

`From 1.11, the command should be /give <playername> spawn_egg 1 0 {EntityTag:{id:minecraft:wither_skeleton}}. The minecraft: should be added properly.`

This command seems to work for now, but gives staff a notification everytime the command runs:

`/minecraft:give Sikatsu spawn_egg 1 0 {EntityTag:{id:minecraft:wither_skeleton}}`

I use the command so players can buy spawn eggs, or win them from vote crates.

**Comment by Sikatsu** [comment]
`From 1.11, the command should be /give <playername> spawn_egg 1 0 {EntityTag:{id:minecraft:wither_skeleton}}. The minecraft: should be added properly.`

**Comment by Sikatsu** [comment]
@SupaHam 

/minecraft:give Sikatsu spawn_egg 1 0 {EntityTag:{id:minecraft:wither_skeleton}}

Seems to work, but spams OP's when someone buys an egg.

**Comment by mdcfe** [comment]
I think this has been an issue for a long time for certain items, and I believe fixing this would require a lot of changes to how items are handled.

**Comment by Sikatsu** [comment]
Really? I never had issues with it on any of the previous minecraft versions..

**Comment by SonyUSA** [comment]
I'm also having this issue, there is currently no way to sell eggs from sign shops. You just get a white spawn egg that does nothing :( I tried 383:x and spawn_egg:x where x = mob ID. Nothing else will fit on the sign, therefore we need the y:x method to work again! This would apply to spawners, too, I'm sure. 

I'm trying to sell LLama eggs, btw: 103

**Comment by mdcfe** [comment]
Not this specific issue, but 1.10 attributes have never been supported by EssentialsX and I believe there are other similar issues elsewhere.

**Comment by Sikatsu** [comment]
While attributes didn't, /give Sikatsu spawn_egg:50 1 always worked

**Comment by SupaHam** [comment]
This has been fixed in 5fda1d0. You can grab the fix from [build 451](https://ci.drtshock.net/job/EssentialsX/) on the CI server.

Sorry for any inconvenience this may have caused.

**Comment by Sikatsu** [comment]
Thanks! I seem to be able to spawn llama eggs, but skeleton horses and zombie horses are missing?
