### ISSUE TITLE
Error message when a player joins the server. Happens on all my servers

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#978]
Hi so when a player joins the server I get this error in console.

http://pastebin.com/kFWrmzZN

**Comment by mdcfe** [comment]
Update EssentialsX and EssentialsXChat to the [latest version](https://ci.drtshock.net/job/EssentialsX/lastSuccessfulBuild/).

**Comment by ghost** [comment]
@md678685 Perfect thanks dude!
