### ISSUE TITLE
Allow ability to open inventories of offline players

### ISSUE THREAD

**Issue by Agazed** [EssentialsX/Essentials#98]
Currently opening inventories and enderchests of offline players is not supported and it is extremely useful to be able to see and modify items in those places.

Also you should add the ability to see the equipped armor with invsee.

**Comment by EvilOlaf** [comment]
Agree.

**Comment by zRiaz** [comment]
Agree

**Comment by Kakifrucht** [comment]
I'm pretty sure that the this would require the use of NMS, so it won't be added.

**Comment by zRiaz** [comment]
;(

**Comment by drtshock** [comment]
Would require nms though :(

**Comment by EvilOlaf** [comment]
But that would be a great feature :P

**Comment by Kakifrucht** [comment]
I'd rather not have Essentials break on every Minecraft version update, though.

**Comment by zRiaz** [comment]
But but I cri

**Comment by zRiaz** [comment]
No clue what nms is but ya sure there is no way around that? :(

**Comment by Kakifrucht** [comment]
NMS is accessing the minecraft servers objects/functions directly, instead through the BukkitAPI. This allows to do alot more with the server, however this means that it needs to be updated with every (bigger) change in the Minecraft source code. Also, it is not fun to work with for developers and the code usually looks ugly due to the obfuscation.

**Comment by vemacs** [comment]
The only reason we do have NMS implementations for spawners is because Spigot does offer a Bukkit-only solution for 1.8.3+, so we don't need to update for newer versions. Unfortunately, this isn't a thing for offline inventory manipulation, and this doesn't seem reliable with reflection.

**Comment by drtshock** [comment]
Why not use the plugin open inventory?

**Comment by Terrobility** [comment]
I +1 this feature. What about some sort of way that's similar to how the other open inventory plugins do it? Perhaps then it may not require much work related to NMS.

**Comment by drtshock** [comment]
We already do it without nms. Adding it for offline players would require nms.

**Comment by EvilOlaf** [comment]
@drtshock will give OpenInv a try. Thanks.
Sounds like a good compromise using a 3rd party plugin for this feature and not adding NMS to ESS.

**Comment by Elgorond** [comment]
@Agazed for your 2nd issue, /invsee (player) armor? That's how it works for normal Essentials, doubt it's different here.

**Comment by Agazed** [comment]
@Theepwner Haha! Never even knew that. Thanks for that! :P

**Comment by Kakifrucht** [comment]
@Theepwner i don't see armor with /invsee

**Comment by zRiaz** [comment]
I do with "/invsee (player) armor"
Never knew about this until now either.

**Comment by Kakifrucht** [comment]
Haha that's funny, new to me too.
