### ISSUE TITLE
1,11 Fly permissions enabled, not available until using /fly twice

### ISSUE THREAD

**Issue by smmmadden** [EssentialsX/Essentials#981]
In line with testing for Issue #980 , my user is an admin, oped level 4 and has all essentials permissions enabled including flight. When using Essentials-2x, I would have flight automatically enabled and can just fly on join.  Now, using EssentialsX with 1.11 (could be either change), I have to issue /fly two times.  The first turns it off "You can no longer fly!" and the second enables it "You can now fly!".  If it was already enabled, I should be able to fly right?

Environment: Spigot 1.11 on Windows 10 Pro x64
server.properties - allow-flight=true
Global Permissions (GroupManager): essentials.* for world
Normal users have negated essentials specific permissions.  Basically enabled for all, then disabled by group/user.

**Comment by mdcfe** [comment]
Don't use GroupManager. There is no support from Essentials nor EssentialsX for it. 
Look through the EssentialsX config; I believe there is a fly-on-join option somewhere.

Correction: I don't know of such an option exists. There's an option to send a "fly mode enabled" message on join though which might help.

**Comment by smmmadden** [comment]
there is a send-fly-enable-on-join in config.yml but that says "Toggles whether or not the fly status message should be sent to players on join".  I don't want all players to know fly is available when it is not.  Is this the same?

If GroupManager isn't supported, which permissions system do I have to switch to?  PermissionsEx?

**Comment by mdcfe** [comment]
That is correct. Could you enable the option and report back whether the message is sent on join?

I personally use PermissionsEx, but other plugins are available. Just make sure that the plugin you switch to is supported by Vault.

**Comment by smmmadden** [comment]
Thank you, that did it.  Guess the verbiage had me confused thinking a "broadcast" message would be sent to all users that fly is enabled when they join because of the comment above it talking about the "fly status message" and not saying enabling "flight" for users who have been granted the essentials.fly permission.

**Comment by mdcfe** [comment]
The option should do exactly what the comment says; I asked about changing that option to try and debug the flight issue. If the double `/fly` issue is resolved however, feel free to close the issue.

**Comment by smmmadden** [comment]
primary issue is resolved by enabling the send-fly-enable-on-join in config.yml.  The comment above the option in config.yml is deceiving as written.  This is enabling the ability to take flight and not sending any broadcast message to anyone joining.  Possibly better to change parameter to enable-fly-on-join which will work if the user has permissions to do so. :-)
