### ISSUE TITLE
cannot use my transated messages

### ISSUE THREAD

**Issue by cicatrice74** [EssentialsX/Essentials#983]
I updated to latest dev and now essentialsx doesn't use my translated messages... is there a new option to do that or is this a bug?

**Comment by mdcfe** [comment]
Have you checked that the `locale` option in `config.yml` is set correctly?

**Comment by SupaHam** [comment]
I believe I helped this person figure out the issue last night. Their `config.yml` was wiped of comments, and so locale was not present in the file.

Simply setting `locale: it` fixed the problem for them.
