### ISSUE TITLE
Able to find last 1.8 Core version but other modules are gone.

### ISSUE THREAD

**Issue by JK82NL** [EssentialsX/Essentials#984]
I can find EssentialsX b276 for 1.8 everywhere, but no trace of Build 276 for Chat, Antibuild, Spawn or Protect. The Jenkins page is even 150 releases ahead of that.
Maybe it would be beter to put them together in a zip like it used to be with the original essentials?
So anyway, where can I get my hands on those.

**Comment by mdcfe** [comment]
@JK82NL Every current dev build supports 1.7.10 to 1.11.

Correction: builds 439 and below support 1.7.10 to 1.10.2. As of build 440, EssentialsX only works on 1.11.

**Comment by JK82NL** [comment]
Thank you for the quick reply MD.

That is great to hear.
It can be a hassle sometimes with plugins and finding the right versions or dev builds.

**Comment by vemacs** [comment]
Builds 450+ have restored most pre-1.11 functionality.
