### ISSUE TITLE
Essentials join full server permission

### ISSUE THREAD

**Issue by bertek41** [EssentialsX/Essentials#985]
Hey i download plugin here: https://www.spigotmc.org/resources/essentialsx.9089/
And i have a problem "essentials.joinfullserver" permission is not work please fix this.

**Comment by mdcfe** [comment]
Could you try the [latest version](https://ci.drtshock.net/job/EssentialsX/lastSuccessfulBuild)?

**Comment by SupaHam** [comment]
Please type `/ess debug` in game then join the server then finally Pastebin your server log.

Steps:

1. Type `/ess debug` in game or `ess debug` in console.
1. Join the game.
1. Open `logs` directory in server directory.
1. Find and open a file called `latest.log`.
1. Go to [www.pastebin.com](http://pastebin.com).
1. Copy all `latest.log` contents and paste into the big text area.
1. Copy & paste the URL in your browser into a reply here.

**Comment by Liphius** [comment]
Thing is, it does not show any errors in the server logs while in debug mode. It's like the permission is non-existent. 

http://pastebin.com/HtZPTveJ

I am using 1.11.2 and tried the latest dev version, build 461.

**Comment by XxCoolGamesxX** [comment]
Some for us...
