### ISSUE TITLE
Enchant command error

### ISSUE THREAD

**Issue by Elijeh** [EssentialsX/Essentials#986]
With the latest build on Jenkins I get this error when trying to enchant an item on a 1.8 server:
http://pastebin.com/s2wxpiz8

**Comment by mdcfe** [comment]
It might have been better to paste your log somewhere like Gist or Hastebin.

**Comment by Elijeh** [comment]
Updated

**Comment by mdcfe** [comment]
This is due to a change in EssentialsX for 1.11 which replaces deprecated methods which were only replaced in 1.9.

**Comment by SupaHam** [comment]
Simply downgrading to build 439 should work. You will no longer be able to receive EssentialsX updates though.
