### ISSUE TITLE
Retain backwards-compatibility for 1.7.10/1.8, or clearly mark the end of support in the README

### ISSUE THREAD

**Issue by mdcfe** [EssentialsX/Essentials#988]
Changes introduced in 944ddf8d to replace deprecated methods have broken a number of commands, most notably (according to number of issues reported) `/enchant` - see #986 and #987. While the reason given is that the plugin is at the mercy of Spigot and their API changes, there are still people on 1.7.10 and 1.8 who rely on this plugin.
EssentialsX could, in theory, continue to support these versions, but even if it is better to drop support for the older versions, it should be clear that there is no longer support for older versions in newer builds.

**Comment by SupaHam** [comment]
I've added a comment to our CI server that states builds 440 and above are for Minecraft 1.11 only.

**Comment by vemacs** [comment]
https://github.com/drtshock/Essentials/commit/96164f5851143e49412426a8912b8ed3b875a71f

According to MCStats, at least 45% of users are running 1.7.10-1.8.8, and 1.11 only has 9.5% market share. That drops to ~30% for us, but I can assure you that number is underreported on plenty of large deployments. It's still worth it to maintain a reasonable degree of legacy compatibility, especially if the amount of wrapper code is under control (which I believe it is).

**Comment by vemacs** [comment]
If supporting the more obscure spawnmob features on older server implementations is absolutely necessary, it would be relatively straightforward to refactor the MobData enum into an interface and two derivative enum classes.

**Comment by SupaHam** [comment]
Can this be closed now?

**Comment by vemacs** [comment]
Leave it open until MobData is resolved

**Comment by mdcfe** [comment]
By this point I think we've agreed to drop support for versions below 1.11, so I'm closing this issue.
