### ISSUE TITLE
Player Join Messages not being broadcast

### ISSUE THREAD

**Issue by smmmadden** [EssentialsX/Essentials#989]
When a player joins, typically other players want to know who joined so they can welcome them.  But for some reason, we only see when players quit the game, not when they join.
My config.yml has the messages set, but no one sees the joins.
custom-join-message: "Welcome {USERNAME} to the game!"
custom-quit-message: "{USERNAME} has left the game!"
Is there a special permission just for joins?  Also, if there is, where is the "full permissions" listing?  I can't find it in the wiki or elsewhere for this release of EssentialsX.

Server: Windows 10 Pro x64
Minecraft Server: Spigot 1.11 
Permissions System Enabled: PermissionsEx

**Comment by SupaHam** [comment]
What does it say when players join the server?

A full permissions list can be found [here](http://wiki.mc-ess.net/wiki/Command_Reference/Perm) and on our [wiki](https://github.com/drtshock/Essentials/wiki)

**Comment by smmmadden** [comment]
Hi SupaHam,

Users in-game do not see anything at all.  So no one knows who is joining.  The server console however, does show users coming in and going, but obviously they don't have that level of access.

Thanks for the two pages of permissions.  I did see those, but the first link shows permissions for Essentials-2x and the second a small list for EssentialsX.  If EssentialsX is replacing the former, I was expecting a separate page on the Wiki to show all the New/combined permissions.  From a documentation perspective, that's where they should be especially if there are changes between them.  I'm trying to determine if the former Essentials-2X permissions I have in PermissionsEx are causing problems since I didn't have a full list to use when switching to PermissionsEx and EssentialsX.

**Comment by mdcfe** [comment]
EssentialsX uses all of the permissions from [the Essentials wiki page](http://wiki.mc-ess.net/wiki/Command_Reference/Perm) **and** [its own wiki](https://github.com/drtshock/Essentials/wiki).

Side note: I'm assuming by "Essentials-2X" you're referring to the upstream essentials/Essentials plugin; I don't know of any other fork called "Essentials-2X".

**Comment by SupaHam** [comment]
@smmmadden I feel like this is another plugin's fault. Unless you specifically set the quit message to be `""` (empty) then EssentialsX will broadcast a message. However, if no message is being broadcasted that means another plugin is interfering with the join event and handling the join message.

Edit: Could you please list all plugins on your server?
If it wouldn't be too much to ask, could you also try using just EssentialsX with your current configuration and see if the issue still occurs.

Edit 2: We don't have our own wiki. And we cannot update the `ess3.net` wiki as it doesn't belong to us, nor is it the same project. With that said, we do use a lot of their permissions of course as this project is a fork of the original Essentials.

**Comment by smmmadden** [comment]
Thanks for the quick reply.  Seems it was TitleMotd 2.1 and it was not working correctly or at least 100% the way it was supposed to do (player join message and all player broadcast message).  Only the first part was working.  The developer created a fix for 1.11 (today) and now it displays both correctly.

There is a wiki page on this project which contains some of the permissions.  That's where it could be expanded to include all the content for EssentialsX.  I've done this for another project plugin (Residence) so everything is all in one place.  I understand it is time-consuming to document a plugin of this size and all the testing associated with it. I'm happy to help contribute to this any way I can.  I've written literally hundreds of technical documents, user manuals and guides over the last 30+ years. :-)

**Comment by mdcfe** [comment]
@SupaHam @smmmadden I was referring to the wiki on GitHub regarding differences between Essentials and EssentialsX, but I appreciate that it's not a comprehensive documentation of the plugin. If it did cover all of the content, it would be heavily duplicating Essentials' (perfectly acceptable) wiki.

**Comment by smmmadden** [comment]
The Essentials-2X project is located here: https://hub.spigotmc.org/jenkins/job/spigot-essentials/

One thing I'm seeing is cross-over of plugins to respect the previous owners naming convention and then leading to confusion over which one is the valid one to use.  Being open source projects and no real oversight of naming conventions/conflicts, there could be many plugins with the same name doing similar functions which is fine, but leads to confusion and false-positive bug reports.  Case in point is this plugin appears to have several similar names as does TitleMotd on Spigot.  I was using v2.01 and today version 1.5.0 was released which lead to me questioning the downgrading of the version.  Turned out they were both written similarly (probably one copied the other) but only version 1.5.0 works. :-)

**Comment by smmmadden** [comment]
Thanks @md678685 for the reply.  Yes, I agree it would duplicate it which makes it easier to port the previous forward.  If everyone knows the original Essentials project (or any other) will not be revived and this release of EssentialsX is the replacement, the old could be removed at any time and then all that documentation would be lost.  As developers, we often don't think about something being removed and expect it to live perpetually.  However, reality is a different story and why I made the suggestion based on my 25 years in this industry seeing it happen many times and then all hell breaks loose.  :-)
