### ISSUE TITLE
worth.yml allows selling of damaged/enchanted items

### ISSUE THREAD

**Issue by denizaygundev** [EssentialsX/Essentials#99]
I was hoping that the items in worth.yml would be required to be fully repaired and non-enchanted, is their a way to achieve this? Not too sure if this is an issue or if there's a way, I tried looking on google and couldn't find anything.

Thanks.

**Comment by Terrobility** [comment]
I'm not sure if there already is, but there should be the ability to add metadata to the worth.yml. Then you would be able to use something like diamondsword:0 in the worth.yml to prevent this issue.

**Comment by denizaygundev** [comment]
The default metadata is "0"

I'm not using the defualt worth file either, this is still a bug

**Comment by pop4959** [comment]
I don't think this is supported still, but there doesn't seem to be much interest. If you still want this, please open a new issue as a feature request.
