### ISSUE TITLE
Impossible to disable join/quit messages

### ISSUE THREAD

**Issue by leonardo-dgs** [EssentialsX/Essentials#991]
If you set custom-join-message or custom-quit-message to "none" it doesn't disable join/quit messages, but simply send the default messages.

**Comment by mdcfe** [comment]
Have you tried setting the message to ""? "none" is supposed to show the default messages.

**Comment by leonardo-dgs** [comment]
Setting the message to "" give an empty line

**Comment by mdcfe** [comment]
Is this a major problem? There's no actual indication of what happened unless players check the tab list.

**Comment by leonardo-dgs** [comment]
In some old essentials' version this bug wasn't present. But i believe that is easy to fix

**Comment by SupaHam** [comment]
If you give players `essentials.silentjoin` permission, and have `allow-silent-join-quit` set to true in config, those players won't have a message when they join.

**Comment by mdcfe** [comment]
Depending on your permissions plugin, you may also have to negate essentials.silentjoin.vanish.
