### ISSUE TITLE
/reply works but /r don't

### ISSUE THREAD

**Issue by Ironic8b498** [EssentialsX/Essentials#994]
Last tested om build version #450 also I rebuilt Spigot on 11/30 7pm est. I use pex 1.23.4, it worked fine till I updated, my guess it's something with the coding.

**Comment by mdcfe** [comment]
Could you elaborate on what you mean by "not working"? Does anything happen in the console or in chat?

**Comment by Ironic8b498** [comment]
if they use /r non op players gets a reply of, <Unknown command. Type '/help" for help.> And when you type help /r is not is list of commands they can use

**Comment by mdcfe** [comment]
> non op players

Does the command work for opped players?

**Comment by Ironic8b498** [comment]
yes opped players can use /r

**Comment by SupaHam** [comment]
If I had to guess, another plugin is interfering. Try getting the same player to type `/essentials:r` and see if that works.

**Comment by mdcfe** [comment]
I agree with @SupaHam. Could you paste a plugin list?

**Comment by Ironic8b498** [comment]
well I run 8 different spigot servers on my bungee network 2 are 1.10.2 and 6 are 1.11 this issue is on all servers.  I can't think of any commands either of these plugins would use. The message does look like it could be coming from a bungeecord plugin now that I think of it:

the common plugins for all servers are:

worldguard-legacy-6.2.1-SNAPSHOT-dist-#1694
worldedit-bukkit-6.1.6-SNAPSHOT-dist-#3649
Vault-1.5.6
PwnFilter-#125
ProtocolLib-4.2.0-20161117.025901-4-#330
PermissionsEx-1.23.4
NoPlugins-4.3
EssentialsXSpawn-2.0.1-#450
EssentialsXChat-2.0.1-#450
EssentialsX-2.0.1-#450
BungeeTabListPlus_BukkitBridge-2.5.4

On my bungee server I run

BungeeAdminTools-1.4.3-basics
BungeeEssentials-2.6.3
BungeeTabListPlus-2.5.4
BungeeVote-1.0
ServerListPlus-3.4.7-Universal
SlashServer-3.0
UltimateVotesBunge-1.5.0e
Yamler-Bungee-2.4.0-SNAPSHOT-#16

**Comment by mdcfe** [comment]
What happens if you connect directly to the Spigot servers? Does /r work?

**Comment by Ironic8b498** [comment]
I can't connect directly, it's not setup so I can connect directly, but I forgot tp tell you the /essentials:r does work. I removed all plugins from my lobby server and /r works. I will returned the plugins one at a time to find out the culprit was pwnfilter  Well deeper investigation it was a typo in the regex . Thanks for the help

**Comment by SupaHam** [comment]
If `/essentials:r` does work, that does confirm the issue is coming from somewhere else. Possibly Bungee plugins. If I had to guess I'd say BungeeEssentials.
