### ISSUE TITLE
Version Mismatch

### ISSUE THREAD

**Issue by Aurgelmir** [EssentialsX/Essentials#996]
Hi, I just installed EssentialsX on my 1.11 spigot server, and noticed that AntiBuild isn't working.

I worked around my logs, and there's a version mismatch between all EssentialsX files, but they're all at version 2.0.1 when I download them. Forgot to update some xml?

**Comment by SupaHam** [comment]
It just means you need to make sure you use the same version across all EssentialsX plugins. You can get all the same versions from our [CI server](https://ci.drtshock.net/job/EssentialsX/).

**Comment by Aurgelmir** [comment]
That's what I did, and I got this error, even after retrying many time, even with a clean install.

**Comment by Aurgelmir** [comment]
Do I need all the EssentialsX components in order to get Antibuild, Spawn and Protect to work?
If not, black magic happened, because I downloaded all #450 build files I needed at the same time so they should be up to date regarding to each others.

**Comment by SupaHam** [comment]
You don't need all components, only what you need.

Nothing has changed regarding this warning message. EssentialsX will simply inform you if you have mismatching versions. Try deleting all the EssentialsX plugin files then download them all again from our [CI server](https://ci.drtshock.net/job/EssentialsX/).

**Comment by Aurgelmir** [comment]
I've done that a few hours ago but it appears to be totally messed up, I'll try on a clean server to see what's wrong. Is there any incompatibility with WorldGuard for Minecraft 1.11?

**Comment by SupaHam** [comment]
With regards to EssentialsX? Not that I know of. It would probably be reported a lot more if there was any issues with WorldGuard.

**Comment by Aurgelmir** [comment]
Thank you for your help though, I will try to download EssentialsX with Antibuild, Protect and Spawn from build 450, and I will run them on a clean server to see if I still have this issue.
I think I'll head back to you with some logs and my plug-in list, just in case, if I still have the error.

Best regards

**Comment by Aurgelmir** [comment]
Okay I just tried on a clean server, and got no warning or error, but even when disabling building for non-op players, they can build/break things. I ran the `/ess debug` command, and when trying to break a block, pick an item, and place the block back, here's what the console tells me:
`[17:20:19] [Server thread/INFO]: [Essentials] looking up groupname of Piercing_Light - default
 [17:20:20] [Server thread/INFO]: [Essentials] looking up groupname of Piercing_Light - default
 [17:20:23] [Server thread/INFO]: [Essentials] looking up groupname of Piercing_Light - default
 [17:20:27] [Server thread/INFO]: [Essentials] looking up groupname of Piercing_Light - default
 [17:20:27] [Server thread/INFO]: [Essentials] looking up groupname of Piercing_Light - default`

It seems to look for groups, but the only files I've got in my plugins folder are EssentialsX-2.0.1.jar, EssentialsXAntiBuild-2.0.1.jar, EssentialsXProtect-2.0.1.jar and EssentialsXSpawn-2.0.1.jar.
I've been told that we only need to put the files corresponding to the Essentials functions we need, so I guess I don't have to put the other Jars in my plugin folder.

I looked all my debugged logs, and nothing looks broken here, I don't know how to get rid of this.

**Comment by Aurgelmir** [comment]
Any idea?

**Comment by mdcfe** [comment]
Make sure you've set the permissions in the Essentials config.yml, if you aren't using a plugin. Alternatively use a permissions plugin and install Vault.

**Comment by Aurgelmir** [comment]
I already have Vault, and I guess there's no need for any perms plugin as I've set `build` to `true` in the AntiBuild section of the config.yml file. There might be an incompatibility between 1.11 servers and AntiBuild. I tried on both Spigot 1.11 server and CraftBukkit 1.11 server and I can't get it to work, so... wtf am I doing wrong?

**Comment by SupaHam** [comment]
I'll ask that you ignore this error for now and I will investigate it at a later date. This can easily be an issue with the CI server.

**Comment by Aurgelmir** [comment]
Thanks, I'll do so, and use PEX to avoid building until it's fixed, I hope you'll find a way to fix this
Regards

**Comment by mdcfe** [comment]
Closing as this doesn't appear to be an issue any more.
