### ISSUE TITLE
./repair isn't costing any money

### ISSUE THREAD

**Issue by TheLoyalOne** [EssentialsX/Essentials#998]
I have an issue where /repair is not costing donators any money, while /fix is.

My config consisted of this previously.
command-costs:
  repair: 750
  repair-all: 5000

I've changed it to this for testing:
command-costs:
  repair: 750
  fix: 750
  fix-all: 5000
  repair-all: 5000

However, /repair and /repair all doesn't have a command cost at all, while /fix and /fix all does have a proper command cost.

Is this a bug, and if so, can you please fix?

- Loyal

**Comment by bagelcoder** [comment]
Is "/repair" costing regular members money?

**Comment by TheLoyalOne** [comment]
It's only accessible to donators on my server

**Comment by TheLoyalOne** [comment]
I've updated my main post so it makes a bit more sense.

**Comment by TheLoyalOne** [comment]
I figured out the issue, unrelated to essentials. Closed.
